command/job_status_test.go

Fixes https://github.com/hashicorp/nomad/issues/6799
The `command/TestJobStatusCommand_Run` test assumes that it gets back running
allocations and will panic the test runner rather than failing.

testing: prevent panic when `job status` output changes

---

.changelog/10868.txt
nomad/structs/structs.go

Fixes https://github.com/hashicorp/nomad/issues/6637 (finally!)
When a task group with `service` block(s) is validated, we validate that there
are no duplicates, but this validation doesn't have access to the task environment
because it hasn't been created yet. Services and checks with interpolation can
be flagged incorrectly as conflicting. Name conflicts in services are not
actually an error in Consul and users have reported wanting to use the same
service name for task groups differentiated by tags.

service: remove duplicate name check during validation

---

.changelog/10870.txt
command/agent/config.go

Fixes https://github.com/hashicorp/nomad/issues/9028
The default agent configuration values were not set, which meant they were not
being set in the client configuration and this results in fingerprints failing
unless the values were set explicitly.

cni: respect default `cni_config_dir` and `cni_path`

---

.changelog/10872.txt
command/agent/consul/group_test.go
command/agent/consul/service_client.go
command/agent/consul/service_client_test.go

This PR uses regex-based matching for sidecar proxy services and checks when syncing
with Consul. Previously we would check if the parent of the sidecar was still being
tracked in Nomad. This is a false invariant - one which we must not depend when we
make #10845 work.
Fixes #10843

consul/connect: Avoid assumption of parent service when filtering connect proxies

---

.changelog/10873.txt
command/agent/consul/service_client.go

This PR will have Nomad de-register a sidecar proxy service before
attempting to de-register the parent service. Otherwise, Consul will
emit a warning and an error.
Fixes #10845

consul/connect: remove sidecar proxy before removing parent service

---

.changelog/10876.txt
client/taskenv/env.go
client/taskenv/env_test.go

Fixes https://github.com/hashicorp/nomad/issues/6506 so our [`meta`](https://www.nomadproject.io/docs/job-specification/meta#interpolation) docs are correct.
Adds missing interpolation step to the `meta` blocks when building the task
environment. Also fixes incorrect parameter order in the test assertion and
adds diagnostics to the test.

client: interpolate meta blocks with task environment

---

website/content/docs/drivers/external/containerd.mdx

- Auth support via driver config
- pid_mode
- shm_size

Containerd task driver options.

---

e2e/e2eutil/job.go

Pick up 15d39f0dee but for RegisterFromJobspec:
>  This PR changes the e2e helper thingy to set -detach option
>  when registering a job with the CLI instead of the API. This is
>  necessary for jobs which never become healthy, as the deployment
>  never finishes for failing jobs and the command never returns,
>  causing the test to timeout after 10 minutes.
This case occurs in TestVaultSecrets

e2e: more -detach mode when registering jobs

---

website/redirects.js

This PR removes a seemingly unnecessary redirect that causes odd reload behaviour when on the [`/docs/internals/scheduling`](https://www.nomadproject.io/docs/internals/scheduling) page.
This page can be accessed via client-side navigation, but on reload, the viewer is redirected to [`/docs/internals/scheduling/scheduling`](https://www.nomadproject.io/docs/internals/scheduling/scheduling), which doesn't seem intentional.

website: remove redirect away from existing page

---

ui/app/services/system.js
ui/app/templates/components/gutter-menu.hbs
ui/mirage/config.js
ui/mirage/factories/agent.js
ui/mirage/serializers/agent.js
ui/tests/acceptance/server-detail-test.js
ui/tests/acceptance/server-monitor-test.js
ui/tests/acceptance/servers-list-test.js

This PR closes [10672](https://github.com/hashicorp/nomad/issues/10672).
The the Nomad UI previously made a request to the `agent/self` endpoint and returned information about the Nomad Agent Version via the Nomad Agent Version.
This PR edits that to retrieve the Nomad Agent Version from the Nomad Agent Config which is created at build time.
The rationale behind this change was that, we have a guaranteed result for Nomad Agent Config Version. Whereas, we didn't have a guarantee that we'd always have a Nomad Agent Member because Clients are not included in the Serf Gossip Protocol.
We know the bug always occurs when we have clients, but no servers.
This PR does not resolve the issue pointed out by @DingoEatingFuzz regarding [cached requests](https://github.com/hashicorp/nomad/issues/6458). …

Closes Nomad UI showing 'vUnknown' #10672

---

.changelog/10883.txt
client/allocrunner/taskrunner/envoy_bootstrap_hook.go
client/allocrunner/taskrunner/envoy_bootstrap_hook_test.go
website/content/partials/envvars.mdx

This PR fixes a bug where the underlying Envoy process of a Connect gateway
would consume a full core of CPU if there is more than one sidecar or gateway
in a group. The utilization was being caused by Consul injecting an `envoy_ready_listener`
on `127.0.0.1:8443`, of which only one of the Envoys would be able to bind to.
The others would spin in a hot loop trying to bind the listener.
As a workaround, we now specify `-address` during the Envoy bootstrap config
step, which is how Consul maps this ready listener. Because there is already
the `envoy_admin_listener`, and we need to continue supporting running gateways
in host networking mode, and in those case we want to use the same port
value coming from the `service.port` field, we now bind the admin listener to
the `127.0.0.2` loop-back …

consul/connect: fix bug causing high cpu with multiple connect sidecars in group

---

ui/app/services/token.js
ui/tests/acceptance/proxy-test.js

Proposed fix for issue #10561.
I looked into the source code and right now, the only places where a token secret is set are:
- https://github.com/hashicorp/nomad/blob/276644470e15f8e4b4dad967192d0ccf1e606417/ui/app/services/token.js#L49
- https://github.com/hashicorp/nomad/blob/276644470e15f8e4b4dad967192d0ccf1e606417/ui/app/controllers/settings/tokens.js#L43
We simply need to capture and store the secret in `TokenService` when call is made to the Token `self` API.
Here is a tentative implementation that I've tested here. I'm open for recommendations.

Capture ACL Token from self API call for Reverse Proxy use-case

---

.circleci/config.yml

Job `test-e2e` uses an unprivileged user to compile and run tests.
Ensure that the user has ssh and git properly configured to checkout
dependencies.

ci: prepare unprivileged user for checkout

---

.changelog/10864.txt
scheduler/generic_sched_test.go
scheduler/util.go

Fixes https://github.com/hashicorp/nomad/issues/10746
Updates to the datacenter field should be destructive for any allocation that
is on a node no longer in the list of datacenters, but inplace for any
allocation on a node that is still in the list. Add a check for this change to
the system and generic schedulers after we've checked the task definition for
updates and obtained the node for each current allocation.

scheduler: datacenter updates should be destructive

---

.changelog/10875.txt
command/agent/job_endpoint.go
command/agent/job_endpoint_test.go

Fixes https://github.com/hashicorp/nomad/issues/9893
When a jobspec doesn't include a namespace, we provide it with the default
namespace, but this ends up overriding the explicit `-namespace` flag. This
changeset uses the same logic as region parsing to create an order of
precedence: the query string parameter (the `-namespace` flag) overrides the
API request body which overrides the jobspec.

cli: `-namespace` should override job namespace

---

command/deployment_status.go
website/content/docs/commands/deployment/status.mdx
website/content/docs/commands/job/run.mdx

This PR introduces a slightly different CLI output to handle successful/canceled/blocked deployments. Otherwise the spinner would just end, which felt a bit awkward.
```console
$ nomad job run example.nomad
...
⠙ Deployment "62eb607c" successful
...
```
```console
$ nomad job run example.nomad
...
✓ Deployment "62eb607c" successful
...
```

Handle successful/canceled/blocked deployments in CLI output

---

.changelog/10849.txt
client/allocrunner/taskrunner/task_runner.go

This code just seems incorrect. As it stands today it reports a
successful restore if RecoverTask fails and then DestroyTask succeeds.
This can result in a really annoying bug where it then calls RecoverTask
again, whereby it will probably get ErrTaskNotFound and call DestroyTask
once more.
I think the only reason this has not been noticed so far is because most
drivers like Docker will return Success, then nomad will call
RecoverTask, get an error (not found) and call DestroyTask again, and
get a ErrTasksNotFound err.

Don't treat a failed recover + successful destroy as a successful recover

---

.changelog/10907.txt
client/client.go

When the client launches, use a consistent read to fetch its own allocs,
but allow stale read afterwards as long as reads don't revert into older
state.
This change addresses an edge case affecting restarting clients. When a
client restarts, it may fetch a stale data concerning its allocs: allocs
that have completed prior to the client shutdown may still have "run/running"
desired/client status, and have the client attempt to re-run again.
An alternative approach is to track the indices such that the client
set MinQueryIndex on the maximum index the client ever saw, or compare
received allocs against locally restored client state. Garbage
collection complicates this approach (local knowledge is not complete),
and the approach still risks starting "dead" allocations (e.g. the
allocation …

client: avoid acting on stale data after launch

---

.changelog/10917.txt
command/alloc_signal.go

The `nomad alloc signal` CLI command takes the signal input as a flag.

fix `nomad alloc signal` help message

---

go.mod
go.sum

This was pinned to a pseudo version to jump ahead for some Consul tests; we can now just use a published version.

deps: upgrade consul api to 1.9.1

---

.changelog/10926.txt
command/deployment_status.go
go.mod
go.sum

Use glint to determine if os.Stdout is a terminal.
glint Terminal renderer expects os.Stdout [not only to be a terminal, but also to have non-zero size](https://github.com/mitchellh/go-glint/blob/b492b545f6208fc979e7ee498d55599b8107e770/renderer_term.go#L39-L46). It's unclear how this condition arises, but this additional check causes Nomad to render deployments progress through glint when glint cannot support it.
By using golint to perform the check, we eliminate the risk of mis-judgement.
I opened https://github.com/mitchellh/go-glint/pull/4 to fix the panic upstream: https://github.com/mitchellh/go-glint/pull/4 . The upstream fix isn't sufficient for us, as it would just skip rendering deployments in this condition, instead of going the non-terminal rendering path in Nomad.
Fixes …

cli: Use glint to determine if os.Stdout is tty

---

.changelog/10952.txt
nomad/acl_endpoint.go
nomad/leader.go

Fix a panic in handling one-time auth tokens, used to support `nomad ui
--authenticate`.
If the nomad leader is a 1.1.x with some servers running as 1.0.x, the
pre-1.1.0 servers risk crashing and the cluster may lose quorum. That
can happen when `nomad authenticate -ui` command is issued, or when the
leader scans for expired tokens every 10 minutes.
Fixed #10943 .

nomad: only activate one-time auth tokens with 1.1.0

---

.changelog/10958.txt
api/api.go

PR #10778 incidentally changed the api http client to connect with
HTTP/2 first. However, the websocket libraries used in `alloc exec`
features don't handle http/2 well, and don't downgrade to http/1
gracefully.
Given that the switch is incidental, and not requested by users.
Furthermore, api consumers can opt-in to forcing http/2 by setting
custom http clients.
Fixes #10922

api: revert to defaulting to http/1

---

e2e/nodedrain/nodedrain.go
e2e/rescheduling/rescheduling.go

As we moved to using `-detach` for registering jobs, we should wait
until allocs and deployments are created before asserting their
properties.
Fixing `TestNodeDrainIgnoreSystem` and `TestRescheduleProgressDeadlineFail` tests as they seem particularly flaky, failing 9 and 7 times (respectively) in the last two weeks.

e2e: wait for allocs and deployments

---

website/content/api-docs/allocations.mdx

The published docs state that the json parameter to restart a specific task is `Task` when it's `TaskName`. If we follow the docs we get a 500 response.
Example with `Task`:
```
$ curl -v -X PUT -d '{"Task": "php"}' -s "localhost:4646/v1/client/allocation/$php_dev_alloc_id/restart"
*   Trying 127.0.0.1:4646...                         
* TCP_NODELAY set                                    
* Connected to localhost (127.0.0.1) port 4646 (#0)                                                                                                                                                                                    
> PUT /v1/client/allocation/86da5b90-16b4-47b4-2174-b9ff6806d030/restart HTTP/1.1
> Host: localhost:4646
> User-Agent: curl/7.68.0                          
> Accept: */* …
```

API docs: Fix allocation restart example

---

.changelog/10990.txt
command/agent/job_endpoint.go
command/agent/job_endpoint_test.go

1.1.3 had a bug where task.VolumeMounts will be an empty slice instead of nil. Eventually, it gets canonicalized and is set to `nil`, but it seems to confuse dry-run planning.
The regression was introduced in https://github.com/hashicorp/nomad/pull/10855/files#diff-56b3c82fcbc857f8fb93a903f1610f6e6859b3610a4eddf92bad9ea27fdc85ecL1028-R1037 . Curiously, it's the only place where `len(apiTask.VolumeMounts)` check was dropped. I assume it was dropped accidentally.
Fixes #10981

Only initialize task.VolumeMounts when not-nil

---

ui/app/components/job-dispatch.js
ui/tests/acceptance/job-dispatch-test.js
ui/tests/pages/jobs/dispatch.js

When a job doesn't have any meta field declared, the API returns `null`. The previous logic would not cover this case.

ui: fix job dispatch page when job doesn't have any meta fields

---

drivers/docker/utils.go

Hi!
When evaluating Nomad on Azure I came across an authentication issue with our Azure Container Registry.
I looked at https://github.com/hashicorp/nomad/issues/10722  but I was not able to find a sustainable solution (other Azure authentication means could have worked, but I had not the opportunity to test)
After digging into the code, I found out that the IdentityToken from the docker.json auth config is simply not used and therefore not passed to docker, resulting in the authentication issue; I also added the RegistryToken, since it is missing as well.
I'm not sure AWS auth works the same, but it *may* explain why some solutions work but other not.
This is my first golang PR so please let me know if there is anything I'm not handling or could improve.
Thanks for your amazing work!

fix: load token in docker auth config

---

CHANGELOG.md
website/content/docs/upgrade/upgrade-specific.mdx

Fixes #11002
Is this the best way to update the changelog for old releases? It's certainly easy enough and doesn't seem to conflict with the new `go-changelog` driven generation. Since we always link to tags for the changelog it seems moot to update it anyway, but maybe it will help someone.
Wording advice always eagerly accepted. I'll update https://github.com/hashicorp/nomad/releases/tag/v1.1.3 once this is merged.
Screenshot of the upgrade guide:

docs: add backward incompat note about #10875

---

.changelog/10951.txt
client/allocrunner/consul_grpc_sock_hook.go

When creating a TCP proxy bridge for Connect tasks, we are at the
mercy of either end for managing the connection state. For long
lived gRPC connections the proxy could reasonably expect to stay
open until the context was cancelled. For the HTTP connections used
by connect native tasks, we experience connection disconnects.
The proxy gets recreated as needed on follow up requests, however
we also emit a WARN log when the connection is broken. This PR
lowers the WARN to a TRACE, because these disconnects are to be
expected.
Ideally we would be able to proxy at the HTTP layer, however Consul
or the connect native task could be configured to expect mTLS, preventing
Nomad from MiTM the requests.
We also can't mange the proxy lifecycle more intelligently, because
we have no control over the …

consul/connect: avoid warn messages on connect proxy errors

---

GNUmakefile

The Nomad UI is [compiled to binary data](https://raw.githubusercontent.com/hashicorp/nomad/main/command/agent/bindata_assetfs.go) that is conditionally loaded based on the `ui` Go build tag. Historically, the `make dev` command didn't include this tag, resulting in a `nomad` executable without the Nomad UI.
`make dev-ui` does include the Nomad UI, but it re-compiles the UI code and requires the entire UI dev stack to be installed, which is an additional burden when you are not actually changing UI code.
This PR changes the default behaviour of the makefile to always include the UI by default. The original behaviour can be achieved by setting the `NOMAD_NO_UI` environment variable before building.

make: embed the Nomad UI data by default

---

.changelog/11019.txt
ui/app/templates/components/job-page/parts/children.hbs

The `Dispatch Job` button is only supported on parameterized jobs. Currently it is also being displayed in periodic jobs as well. Clicking the button in a non-parameterized job can cause the UI to crash.

ui: only dipslay "Dispatch Job" button on parameterized jobs

---

website/content/docs/configuration/acl.mdx

replication_token always works together with authoritative_region, add a link for a better doc.

docs: Add replication_token link with authoritative_region

---

.changelog/11020.txt
ui/app/templates/components/job-page/parameterized-child.hbs
ui/app/templates/components/job-page/periodic-child.hbs

The detail page for a child job include a header section pointing back to its parent. This header has a missing `|` separator between the job priority and the parent link.

ui: add missing pipe separator in parameterized and periodic jobs

---

.changelog/11005.txt
client/client.go

Speed up client startup, by retrying more until the servers are known.
Currently, if client fingerprinting is fast and finishes before the
client connect to a server, node registration may be delayed by 15
seconds or so!
Ideally, we'd wait until the client discovers the servers and then retry
immediately, but that requires significant code changes.
Here, we simply retry the node registration request every second. That's
basically the equivalent of check if the client discovered servers every
second. Should be a cheap operation.
When testing this change on my local computer and where both servers and
clients are co-located, the time from startup till node registration
dropped from 34 seconds to 8 seconds!

Speed up client startup and registration

---

.changelog/11013.txt
nomad/structs/structs.go
nomad/structs/structs_test.go

In a multi-task-group job, treat 0 canary groups as auto-promote.
This change fixes an edge case where Nomad requires a manual promotion,
if the job had any group with canary=0 and rest of groups having
auto_promote set.
Fixes #8139

deployments: canary=0 is implicitly autopromote

---

.changelog/11007.txt
nomad/node_endpoint.go
nomad/node_endpoint_test.go

Fix a bug where system jobs may fail to be placed on a node that
initially was not eligible for system job placement.
This changes causes the reschedule to re-evaluate the node if any
attribute used in feasability checks changes.
Fixes https://github.com/hashicorp/nomad/issues/8448

system: re-evaluate node on feasability changes

---

.changelog/10848.txt
api/csi.go
client/csi_endpoint_test.go
client/structs/csi.go
command/agent/csi_endpoint.go
command/volume_snapshot_list.go
nomad/csi_endpoint.go
nomad/csi_endpoint_test.go
nomad/structs/csi.go
plugins/csi/plugin.go
website/content/api-docs/volumes.mdx
website/content/docs/commands/volume/snapshot-list.mdx

CSI Listsnapshot secrets support

---

website/content/docs/integrations/consul-connect.mdx

Tweaks to the commands in Consul Connect page.
For multi-command scripts, having the leading `$` is a bit annoying, as it makes copying the text harder. Also, the `copy` button would only copy the first command and ignore the rest.
Also, the `echo 1 > ...` commands are required to run as root, unlike the rest! I made them use `| sudo tee` pattern to ease copy & paste as well.
Lastly, update the CNI plugin links to 1.0.0. It's fresh off the oven - just got released less than an hour ago: https://github.com/containernetworking/plugins/releases/tag/v1.0.0 .
You can compare the Copy behavior between: [Original Page](https://www.nomadproject.io/docs/integrations/consul-connect#cni-plugins) with [Proposed](https://nomad-lfnqviaj6-hashicorp.vercel.app/docs/integrations/consul-connect#cni-plugins) …

docs: Consul Connect tweaks

---

.changelog/11054.txt
nomad/node_endpoint.go
nomad/node_endpoint_test.go
nomad/structs/structs.go
scheduler/rank.go

When a node becomes ready, create an eval for all system jobs across
namespaces.
The previous code uses `job.ID` to deduplicate evals, but that ignores
the job namespace. Thus if there are multiple jobs in different
namespaces sharing the same ID/Name, only one will be considered for
running in the new node. Thus, Nomad may skip running some system jobs
in that node.
I've added a failing test in the first comment to highlight the issue: https://app.circleci.com/pipelines/github/hashicorp/nomad/17325/workflows/0a3cbdb9-8433-403d-b226-97eb0f9218c5/jobs/170084 that passes with the fix.

Consider all system jobs for a new node

---

nomad/autopilot_test.go
nomad/leader_test.go

Best reviewed commit-by-commit.
Attempt to deflake TestLeader_LeftLeader and TestAutopilot_CleanupDeadServer , mostly by validating leadership transition, and waiting if necessary.  Look at individual commit messages for info.
Also, update the assertion failures so we can get more meaningful errors and the like.

Deflake tests attempts

---

.changelog/11070.txt
command/agent/log_file.go
command/agent/log_file_test.go
website/content/docs/configuration/index.mdx
website/content/docs/upgrade/upgrade-specific.mdx

The `log_file` configuration option allows setting the log file name to use. In practice, however, this value was being used as a filename prefix with a timestamp appended.
This PR changes the log file creation logic to always use the value set in `log_file` as the active log file name.
Closes #11061 #9582

Don't timestamp active log file

---

website/content/docs/job-specification/gateway.mdx

Update the ingress gateway documentation to remove the note stating that a port must be specified for values in the `hosts` field when the ingress gateway is listening on a non-standard HTTP port.
Specifying a port was required in Consul 1.8.0, but that requirement was removed in 1.8.1 with hashicorp/consul#8190 which made Consul include the port number when constructing the Envoy configuration.
Related Consul docs PR: hashicorp/consul#10827

docs: Remove note on ingress gateway hosts field needing a port number

---

website/content/docs/autoscaling/policy.mdx
website/content/docs/job-specification/scaling.mdx

The documentation for the `scaling` and `policy` blocks were not clear on how they are used for Dynamic Application Sizing.

Update `scaling` and `policy` blocks documentation

---

.changelog/11065.txt
go.mod
go.sum

Updates x/sys to support go 1.17 which is blocking brew go 1.17
more context here: https://github.com/Homebrew/homebrew-core/pull/83413
please cut a release after merging this.

Update x/sys to support go 1.17

---

demo/csi/digitalocean/.terraform.lock.hcl
demo/csi/digitalocean/main.tf
demo/csi/digitalocean/volume-job.nomad

This PR updates the `demo/csi/digitalocean` terraform files in the following ways
- Updates `main.tf` to use the new `capability` stanza
- Updates `volume-job.nomad` to include required `access_mode` and `attachment_mode` properties in the `volume` stanza
- Adds the recently introduced `terraform.lock.hcl` file

Update terraform configuration for demo/csi/digitalocean

---

e2e/terraform/.terraform.lock.hcl
e2e/terraform/config/dev-cluster/consul/base.json
e2e/terraform/config/shared/consul-tls.json
e2e/terraform/config/shared/nomad-tls.hcl
e2e/terraform/config/shared/vault-tls.hcl
e2e/terraform/network.tf
e2e/terraform/nomad.tf
e2e/terraform/outputs.tf
e2e/terraform/packer/ubuntu-bionic-amd64/provision.sh
e2e/terraform/provision-nomad/main.tf
e2e/terraform/provision-nomad/variables.tf
e2e/terraform/terraform.tfvars
e2e/terraform/tls_ca.tf
e2e/terraform/variables.tf
e2e/terraform/vault.tf

This allows us to spin up e2e clusters with mTLS configured for all HashiCorp services, i.e. Nomad, Consul, and Vault. Used it for testing https://github.com/hashicorp/nomad/pull/11089 .
mTLS is disabled by default.  I have not updated Windows provisioning scripts yet - Windows also lacks ACL support from before. I intend to follow up for them in another round.

Support mTLS clusters for e2e testing

---

nomad/server.go

updated with Nomad ports and web link (learn guide: https://learn.hashicorp.com/tutorials/nomad/outage-recovery)

corrected peersInfoContent - was copied from Consul and not updated for Nomad

---

website/content/docs/drivers/docker.mdx
website/content/docs/upgrade/upgrade-specific.mdx

#11056 highlighted an issue with using `extra_hosts` with Consul Connect in Nomad v1.1.3 that was introduced by #10823.
This PR documents this new behaviour and provides a workaround for using `sidecar_task.config` instead to set the desired `extra_hosts`.
Preview:
Docker driver docs
Nomad 1.0.9 and 1.1.3 upgrade docs:

Document Docker `extra_hosts` behaviour post v1.1.3

---

.changelog/11110.txt
ui/app/components/job-page/parts/children.js
ui/app/routes/jobs/job/index.js
ui/app/templates/components/job-page/parts/children.hbs
ui/tests/acceptance/job-detail-test.js
ui/tests/helpers/module-for-job.js
ui/tests/pages/jobs/detail.js

When setting the watcher for child jobs, the watcher was not setting the namespace value. This would cause periodic or parameterized jobs in a non-default namespace to query for the wrong child jobs.
Additionally, the `Job Launches` table was missing the possibility that the job namespace would be displayed in the table row, causing a mismatch between the number of `th` and `td` tags in the table.
Closes #10906

ui: set namespace when looking for and displaying children jobs

---

.changelog/10935.txt
nomad/fsm_test.go
nomad/state/deployment_events_test.go
nomad/stream/event_broker_test.go
nomad/stream/subscription.go
nomad/stream/subscription_test.go
website/content/api-docs/events.mdx

@notnoop I know we talked about doing a check for a management token with all namespaces, but then I realized that wouldn't work with ACL policies with `namespace *` so I kept it the way it is. Totally happy to rethink that though
This fixes a bug in the event stream API where it currently interprets
namespace=* as an actual namespace, not a wildcard. When Nomad parses
incoming requests, it sets namespace to default if not specified, which
means the request namespace will never be an empty string, which is what
the event subscription was checking for. This changes the conditional
logic to check for a wildcard namespace instead of an empty one.
It also updates some event tests to include the default namespace in the
subscription to match current behavior.
Fixes #10903

events: fix wildcard namespace handling

---

e2e/terraform/outputs.tf

Use absolute paths when setting the environment variables for mTLS keys and certificates so you are able to run `nomad` commands from any directory.

e2e: use absolute path for mTLS env vars

---

website/content/api-docs/operator/autopilot.mdx

i found this confusing since 8300 is associated with consul. suggest using more nomad ports

suggest changing port number to nomad default

---

website/content/docs/integrations/consul-connect.mdx

[This documentation](https://www.nomadproject.io/docs/integrations/consul-connect#run-the-connect-enabled-services) describes a `port` stanza in the group `dashboard`:
```
group "dashboard" {
network {
mode = "bridge"
port "http" {
static = 9002
to     = 9002
}
}
```
But then doesn't use this defined port in the `service` stanza:
```
service {
name = "count-dashboard"
port = "9002"
connect {
sidecar_service {
proxy {
upstreams {
destination_name = "count-api"
local_bind_port  = 8080
}
}
}
}
}
```
And instead just uses `port = "9002"`. I suppose you define the port inside of network to establish a static port on the host, but then it seems odd to redefine the port manually. I found this confusing, and it might contribute to people thinking this is the way it needs to be. It's bad because …

Change dashboard port to http

---

.changelog/11141.txt
ui/app/components/job-dispatch.js
ui/app/templates/components/job-page/parts/title.hbs
ui/tests/acceptance/job-dispatch-test.js
ui/tests/integration/components/job-page/periodic-test.js
ui/tests/pages/jobs/detail.js

After a job is dispatched via the UI, the user is redirected to the newly created job. But we were not setting the namespace so the redirect would result in a `Not Found` error message.
Closes #11121

ui: set the job namespace when redirecting after the job is dispatched

---

.changelog/11128.txt
command/monitor.go
command/monitor_test.go

The previous logic would only look at the first metric metadata to build the table header row. 
This PR changes this logic to look at all metadata values first, collecting the different metrics available in each of them.
Closes #11117

cli: include all possible scores in alloc status metric table

---

.changelog/11143.txt
go.mod
go.sum

deps: update go-plugin to v1.4.3 to fix Windows handle leak.

---

website/content/docs/devices/nvidia.mdx

The instructions we linked to previously were to an outdated document that contains instructions that no longer work (the `nvidia-docker` package is no longer available in their repository – only the `nvidia-docker2` package is which is not compatible). Instead, you need to follow the instructions for installing the `nvidia-container-runtime`.

docs: Update Nvidia GPU installation instructions

---

.github/dependabot.yml

By default, dependabot sets a `dependency` label to all of its PRs.
The Nomad team actually uses the `theme/dependency` label plus some `theme/*` specific labels for different parts of the codebase.
Docs: https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#labels

dependabot: set proper theme/* labels

---

.changelog/11111.txt
scheduler/scheduler_sysbatch_test.go
scheduler/scheduler_system.go
scheduler/scheduler_system_test.go

When a system or sysbatch job specify constraints that none of the current nodes meet, report a warning to the user.
Also, for sysbatch job, mark the job as dead if no allocation is placed at all. System jobs behavior isn't affected by this.
A sample run would look like:
```
$ nomad job run ./example.nomad
==> 2021-08-31T16:57:35-04:00: Monitoring evaluation "b48e8882"
2021-08-31T16:57:35-04:00: Evaluation triggered by job "example"
==> 2021-08-31T16:57:36-04:00: Monitoring evaluation "b48e8882"
2021-08-31T16:57:36-04:00: Evaluation status changed: "pending" -> "complete"
==> 2021-08-31T16:57:36-04:00: Evaluation "b48e8882" finished with status "complete" but failed to place all allocations:
2021-08-31T16:57:36-04:00: Task Group "cache" (failed to place 1 allocation):
* Constraint …
```

scheduler: warn when system jobs cannot place an alloc

---

.changelog/11185.txt
go.mod
go.sum

Update `go-memdb` to pick-up https://github.com/hashicorp/go-memdb/pull/87 in an attempt to fix #11174

deps: update go-memdb to 1.3.2

---

ui/app/components/allocation-row.js
ui/app/components/client-row.hbs
ui/app/components/client-row.js
ui/app/components/client-status-bar.js
ui/app/components/job-page/parts/summary.js
ui/app/components/task-row.js
ui/app/controllers/jobs/job/clients.js
ui/app/routes/jobs/job/clients.js
ui/app/styles/components.scss
ui/app/styles/components/job-client-status-row.scss
ui/app/templates/jobs/job/clients.hbs
ui/mirage/scenarios/sysbatch.js
ui/tests/unit/utils/job-client-status-test.js

- Fix create, edit and status sorting
- Fix initial client list filtering to only include clients targeted by the job
- Make table row clickable
- Some code refactoring

System and sysbtach clients tab

---

.changelog/11173.txt
website/content/docs/job-specification/network.mdx

docs: add changelog and website entry for #11173

---

.changelog/11184.txt
client/fingerprint/network.go
client/fingerprint/network_linux.go
client/fingerprint/network_windows.go

While debugging an issue with network fingerprinting, I found it useful to have the network device name in the log output.

Log network device name during fingerprinting

---

.changelog/11168.txt
command/meta.go
command/meta_test.go

Fixed usage of NOMAD_CLI_NO_COLOR env variable.

---

.changelog/11206.txt
client/taskenv/env.go
client/taskenv/env_test.go

client: task env vars should take precedence over host env vars.

---

website/content/docs/job-specification/meta.mdx
website/content/docs/runtime/environment.mdx

Nomad passes some of the client host environment variables to tasks, as well as `meta` values defined in the jobspec, but this behaviour is not documented very clearly. 
This PR adds some content to https://www.nomadproject.io/docs/runtime/environment and https://www.nomadproject.io/docs/job-specification/meta to explain this behaviour in more visible places.
Preview:
-----------

docs: add some extra documentation around client host environment variables

---

website/content/docs/configuration/client.mdx

The current wording can lead someone to believe that you can use percentage values.

DOCS: Clarify the reservation example

---

website/content/docs/job-specification/network.mdx

Network modes and isolation are currently only supported on Linux. The PR makes the documentation explicit about it.
Preview:

docs: document that network mode is only supported on Linux

---

nomad/eval_broker.go
nomad/eval_broker_test.go

Test originally only had a 10ms time window tolerance. Increased to
100ms and also improved assertions and docstrings.

test: fix fake by increasing time window

---

.changelog/11257.txt
command/agent/consul/service_client.go
nomad/job_endpoint_hook_connect.go
nomad/job_endpoint_hook_connect_test.go

When a `gateway -> mesh` block is set in a service without a `proxy` block, Nomad is expected to generate a default proxy configuration. This was being done when the group network mode was `bridge`, but not when it was `host`, even though that is a [supported option](https://www.nomadproject.io/docs/job-specification/gateway#gateway-with-host-networking). 
Without the proxy configuration, Nomad would panic when trying to generate the Consul API request to register the service.
This PR generates the proxy configuration regardless of the network mode. When in `bridge`, the previous behaviour is preserved. In `host`, no special configuration is done, so the default Consul behaviour is used.
Closes #11243

fix panic when Connect mesh gateway doesn't have a proxy block

---

.changelog/11084.txt
helper/tlsutil/generate.go
helper/tlsutil/generate_test.go
nomad/rpc.go
nomad/rpc_test.go

When mTLS is enabled, only nomad servers of the region should access the Raft RPC layer. Clients and servers in other regions should only use the Nomad RPC endpoints.
Co-authored-by: Michael Schurter <mschurter@hashicorp.com>
Co-authored-by: Seth Hoenig <shoenig@hashicorp.com>
Fixes https://github.com/hashicorp/nomad/issues/11084

Apply authZ for nomad Raft RPC layer

---

.changelog/11213.txt
command/ui.go
website/content/docs/commands/ui.mdx

add `-show-url` option for `ui` command

---

ui/app/utils/properties/job-client-status.js
ui/tests/integration/components/job-client-status-bar-test.js

The job client status helper relies on updating whenever an allocation
client status updates. Or if a new allocation is added to the client
node. We were previously observing the allocations array as a whole,
but we're depending on a specific property in that list to update in
order to make sure we're getting notifications to update at the right
time.

edit dependent keys on `computed job-client-status` helper

---

.changelog/11273.txt
drivers/shared/executor/client.go

Suppress stats streaming error log messages when task finishes.
Streaming errors are expected when a task finishes and they aren't
actionable to users.
Also, note that the task runner Stats hook retries collecting stats
after a delay. If the connection terminates prematurely, it will be
retried, and closing the stats stream is not very disruptive.
Ideally, executor terminates cleanly when task exits, but that's a more
substantial change that may require changing the executor/drivers interface.
Fixes https://github.com/hashicorp/nomad/issues/10814

executor: suppress spurious log messages

---

demo/csi/kadalu-csi/README.md
demo/csi/kadalu-csi/app.nomad
demo/csi/kadalu-csi/cluster.vars
demo/csi/kadalu-csi/controller.nomad
demo/csi/kadalu-csi/nodeplugin.nomad

- Access external gluster cluster from Nomad via Kadalu CSI
Signed-off-by: Leela Venkaiah G <leelavg@thoughtexpo.com>

[demo] Kadalu CSI support for Nomad

---

.changelog/11242.txt
command/commands.go
command/job_allocs.go
command/job_allocs_test.go
website/content/docs/commands/job/allocs.mdx
website/data/docs-nav-data.json

This PR provides a CLI interface to display allocations for a particular job.  
`nomad job allocs [options] <job>`
- `-json` : Output the allocations in JSON format.
- `-t` : Format and display the allocations using a Go template.
- `-verbose`: Show full information.
- `-all`: Display all allocations matching the job ID, even those from an
older instance of the job.

cli: Add nomad job allocs command

---

.changelog/11269.txt
command/operator_debug.go
command/operator_debug_test.go
command/util_test.go
helper/funcs.go
helper/funcs_test.go
nomad/client_agent_endpoint_test.go
testutil/wait.go

This PR provides additional insight into namespaces and regions known to the cluster.
* Add namespace/region filter to CLI output
* Add region filtering for servers
* Add namespaces.json and regions.json to cluster meta
* Add helper function to test for presence of string prefix in slice of strings
* Refactor tests to validate correct behavior

debug: Improve namespace and region support

---

.changelog/11270.txt
command/job_dispatch.go
command/job_dispatch_test.go
command/operator_debug.go

This PR provides additional autocomplete support for the following commands:
`nomad operator debug`
* -log-level
* -node-class
* -node-id
* -server-id
* -output
`nomad job dispatch`
* only autocomplete parameterized jobs

cli: Improved autocomplete support for job dispatch and operator debug

---

.changelog/10799.txt
api/operator.go
command/agent/operator_endpoint.go
command/agent/operator_endpoint_test.go
e2e/oversubscription/oversubscription.go
internal/testing/apitests/operator_test.go
website/content/api-docs/operator/scheduler.mdx

Currently, `GET /v1/operator/scheduler/configuration` returns a SchedulerConfigResponse object. The APIs usually use the QueryMeta from the Response objects to populate the HTTP headers for their response to the HTTP API client, but then return the object next to them as the HTTP body.
This is a breaking change to the API; however, this endpoint should be an extremely low use endpoint so it might be acceptable to make it consistent at this point?
Reference code:
https://github.com/hashicorp/nomad/blob/b430bafe9031f871e21403fde008bd8494350091/command/agent/node_endpoint.go#L184-L193

Return SchedulerConfig instead of SchedulerConfigResponse struct

---

nomad/structs/funcs.go
scheduler/preemption_test.go

Fix a bug where the scheduler may panic when preemption is enabled. The conditions are a bit complicated:
A job with higher priority that schedule multiple allocations that preempt other multiple allocations on the same node, due to port/network/device assignments.
The cause of the bug is incidental mutation of internal cached data. `RankedNode` computes and cache proposed allocations  in https://github.com/hashicorp/nomad/blob/v1.1.6/scheduler/rank.go#L42-L53 . But scheduler then mutates the list to remove pre-emptable allocs in https://github.com/hashicorp/nomad/blob/v1.1.6/scheduler/rank.go#L293-L294, and  `RemoveAllocs` mutates and sets the tail of cached slice with `nil`s triggering a nil-pointer derefencing case.
I fixed the issue by avoiding the mutation in `RemoveAllocs` - the …

Fix preemption panic

---

.changelog/11331.txt
drivers/docker/config.go
drivers/docker/driver.go
drivers/docker/driver_test.go
website/content/docs/drivers/docker.mdx

Add support for --init to docker driver.

---

ui/app/components/tooltip.js
ui/app/templates/components/allocation-row.hbs
ui/app/templates/components/plugin-allocation-row.hbs
ui/app/templates/components/tooltip.hbs
ui/tests/acceptance/plugin-detail-test.js
ui/tests/acceptance/volume-detail-test.js
ui/tests/pages/components/allocations.js
ui/tests/unit/components/tooltip-test.js

After using #11358 for a bit, I was quickly annoyed with the unnecessarily wide tooltip when client names are relatively short. This PR creates a `Tooltip` component that ellipsizes the tooltip text content in the middle, keeping it short enough to fit into a single-line tooltip.
Before:
After:
Ellipsizing in the middle allow users to glance at the beginning and end of text. This is important for client names since they are often prefixed and indexed in a standard format. Cutting off the end of the string would make impossible to distinguish between `nomad-client-with-long-name-1` and `nomad-client-with-long-name-2`.
Using `multiline` was also not helpful in the case where client names had no spaces.
The value used as a threshold to decide if the text must be ellipsized is fairly …

ui: create tooltip component

---

.changelog/11400.txt
nomad/structs/diff.go
nomad/structs/diff_test.go
nomad/structs/structs.go

Currently Nomad will use a generic diff method when computing changes in a jobspec. This method uses a hash of the block content as a way to match values from the old jobspec to the new one. This approach generates less than ideal diffs since any change to block will result in a add/delete pair instead of a more precise edit output.
This PR introduces a new interface that can be implemented by structs that have some kind of stable and uniquely identifiable field that can be used to match blocks from the old jobspec to the new one.
Implementing this interface for the `Template` struct, for example, allows using the destination path as the ID. Nomad guarantees its uniqueness in a task and If the user modifies it it's fair to assume this is a new block.
Big thanks to @apollo13  for flagging …

Allow using specific object ID on diff

---

.changelog/11144.txt
command/agent/agent.go
command/agent/agent_test.go

Almost all of the TLS settings are reloadable, but changes to RPC upgrade mode don't trigger TLS configuration reloads. This PR adds the value to the ShouldReload function.

Making RPC Upgrade mode reloadable.

---

.changelog/10799.txt
api/operator.go
command/agent/operator_endpoint.go
command/agent/operator_endpoint_test.go
e2e/oversubscription/oversubscription.go
internal/testing/apitests/operator_test.go
website/content/api-docs/operator/scheduler.mdx

Reverts hashicorp/nomad#10799 since it was discovered during the 1.2.0 beta period that the impact of this change is wider than expected.
Existing clients that use the `github.com/hashicorp/nomad/api` package will panic if they communicate with a Nomad `1.2.0-beta1` agent.

Revert "Return SchedulerConfig instead of SchedulerConfigResponse struct"

---

website/content/docs/drivers/podman.mdx

Update Podman task driver documentation based on latest [repo's README](https://github.com/hashicorp/nomad-driver-podman/blob/main/README.md).

docs: update podman driver documentation

---

.changelog/11334.txt
client/allocdir/alloc_dir.go
client/allocdir/alloc_dir_test.go
client/allocdir/task_dir.go
client/allocdir/task_dir_test.go
client/allocdir/testing.go
client/allocrunner/alloc_runner.go
client/allocrunner/consul_grpc_sock_hook_test.go
client/allocrunner/consul_http_sock_hook_test.go
client/allocrunner/taskrunner/connect_native_hook_test.go
client/allocrunner/taskrunner/dispatch_hook_test.go
client/allocrunner/taskrunner/envoy_bootstrap_hook_test.go
client/allocrunner/taskrunner/envoy_version_hook_test.go
client/allocrunner/taskrunner/task_runner_test.go
client/allocrunner/taskrunner/template/template_test.go
client/allocwatcher/alloc_watcher.go
client/allocwatcher/alloc_watcher_test.go
client/fs_endpoint_test.go
command/agent/consul/int_test.go
drivers/docker/driver_unix_test.go
drivers/shared/executor/executor_linux_test.go
drivers/shared/executor/executor_test.go
plugins/drivers/testutils/testing.go
testutil/wait.go
website/content/docs/configuration/client.mdx
website/content/docs/configuration/index.mdx

Fixes #2522
Skip embedding client.alloc_dir when building chroot. If a user
configures a Nomad client agent so that the chroot_env will embed the
client.alloc_dir, Nomad will happily infinitely recurse while building
the chroot until something horrible happens. The best case scenario is
the filesystem's path length limit is hit. The worst case scenario is
disk space is exhausted.
A bad agent configuration will look something like this:
```hcl
data_dir = "/tmp/nomad-badagent"
client {
enabled = true
chroot_env {
"/tmp/nomad-badagent" = "/ohno"
}
}
```
Note that `/ohno/client` (the state_dir) will still be created but not
`/ohno/alloc` (the alloc_dir).
While I cannot think of a good reason why someone would want to embed
Nomad's client (and possibly server) directories in chroots, there …

client: never embed alloc_dir in chroot

---

.changelog/11416.txt
nomad/plan_apply.go
website/redirects.js

As we have continued to see reports of #9506 we need to elevate this log
line as it is the only way to detect when plans are being *erroneously*
rejected.
Users who see this log line repeatedly should drain and restart the node
in the log line. This seems to workaorund the issue.
Please post any details on #9506!

core: bump rejected plans from debug -> info

---

command/commands.go
command/operator_raft_state.go
command/operator_snapshot_state.go
helper/raftutil/fsm.go
helper/raftutil/sample_test.go
helper/raftutil/snapshot.go
helper/snapshot/snapshot.go
main.go

This PR refactors `helper/raftutil` package to ease testing and debugging a cluster dump programatically. When debugging a customer cluster, one can write a test case to find the offending raft entry that voilates an invariant, or simulate a scheduling decision based on a state index. Illustrative tests are in [`helper/raftutil/sample_test.go`](https://github.com/hashicorp/nomad/blob/c-raftutil-debug-3/helper/raftutil/sample_test.go).
Also, adding `nomad operator snapshot _state` command that emits the state in json from a snapshot generated by `operator snapshot save`. This basically the equivalent of `nomad operator raft _state` but for snapshots.

Raft Debugging Improvements

---

.changelog/11165.txt
command/helpers.go
jobspec2/types.variables.go

As per Nomad documentation, all variables used within a job specification must be defined via a variable block within the job specification file. Attempting to perform an override on a variable that doesn't exist will result in a parse error. This change fixes the behaviour, so there is consistency no matter where the override came.
closes #11149

jobspec2: ensure consistent error handling between var-file & var.

---

.changelog/11284.txt
command/helpers.go
command/helpers_test.go
command/job_plan.go
command/job_run.go
command/job_validate.go
jobspec2/types.variables.go
website/content/docs/commands/job/plan.mdx
website/content/docs/commands/job/run.mdx
website/content/docs/commands/job/validate.mdx

@jrasell Hi I have added a `-lenient` flag to allow users to enable non-strict parsing of the job variables. What do you think?
closes #11164

Added a `-hcl2-strict` flag to allow for lenient hcl variable parsing.

---

.changelog/11432.txt
api/nodes.go
client/client.go
command/node_status.go
command/status_test.go
nomad/structs/network.go
nomad/structs/structs.go
website/content/api-docs/nodes.mdx

This commit should address #11223.
Specifically it enhances the CLI in order to return two flavours
(default,verbose) of the `node status` command that include `host_network` information
as defined in the `client` stanza of a node.
Signed-off-by: Alessandro De Blasis <alex@deblasis.net>

cli: nomad agent does not show configured `host_network`

---

.changelog/11429.txt
nomad/job_endpoint.go
nomad/job_endpoint_test.go

Previously the eval priority was set to the default priority
rather than the priority configured within the target job. This
change fixes this bug, ensuring any eval created as a result of
scaling uses the job priority.

rpc: set the job scale eval priority to the job priority.

---

.changelog/11426.txt
nomad/job_endpoint.go
nomad/job_endpoint_test.go

Previously when creating an eval for job deregistration, the eval
priority was set to the default value irregardless of the job
priority. In situations where an operator would want to deregister
a high priority job so they could re-register; the evaluation may
get blocked for some time on a busy cluster because of the
deregsiter priority.
If a job had a lower than default priority and was deregistered,
the deregister eval would get a priority higher than that of the
job. If we attempted to register another job with a higher
priority than this, but still below the default, the deregister
would be actioned before the register.
Both situations described above seem incorrect and unexpected from
a user perspective.
This fix modifies to behaviour to set the deregister eval priority
to that of …

rpc: set the deregistration eval priority to the job priority.

---

.changelog/11461.txt
.circleci/config.yml
contributing/README.md
go.mod
scripts/release/mac-remote-build
scripts/vagrant-linux-priv-go.sh
tools/go.mod

* Go 1.17 release notes: https://golang.org/doc/devel/release#go1.17
* Go 1.17.2 milestone: https://github.com/golang/go/issues?q=milestone%3AGo1.17.2+label%3ACherryPickApproved
* Go 1.17.3 milestone: https://github.com/golang/go/issues?q=milestone%3AGo1.17.3+label%3ACherryPickApproved

build: bump go version to 1.17.3

---

.changelog/11466.txt
client/testutil/driver_compatible.go
command/operator_debug.go
command/operator_debug_test.go
testutil/vault.go

This PR refactors the collection routines for Consul and Vault, captures a bit more useful information for troubleshooting, and expands the unit test coverage.
* Fix Consul/Vault TLS address mismatch issues
* Fix Vault sys health URL
* Add capture of Consul agent host and agent metrics
* Add CLI version to output
* Update unit test to validate multiregion cluster

cli: refactor operator debug capture

---

website/content/docs/autoscaling/plugins/target/aws-asg.mdx
website/content/docs/autoscaling/plugins/target/azure-vmss.mdx
website/content/docs/autoscaling/plugins/target/gce-mig.mdx

With https://github.com/hashicorp/nomad-autoscaler/pull/535, `node_class` and `datacenter` can be defined at the same time in a scaling policy.

docs: remove mutual-exclusion between node class and datacenter in scaling policies

---

website/content/docs/autoscaling/plugins/apm/nomad.mdx

Scaling a cluster to zero clients while using the Nomad APM is [not possible](https://github.com/hashicorp/nomad-autoscaler/pull/534), so we should document this more explicitly.

docs: add note about the Nomad APM autoscaling plugin and scaling cluster to zero

---

.changelog/11504.txt
go.mod
go.sum

The update includes a number of useful enhancements and bug fixes including streaming metrics and a deadlock fix within the in-memory sink.

deps: update armon/go-metrics to v0.3.10.

---

.changelog/11482.txt
command/agent/fs_endpoint.go
nomad/structs/errors.go
ui/app/adapters/allocation.js
ui/tests/acceptance/behaviors/fs.js

Fixes https://github.com/hashicorp/nomad/issues/11480
If the alloc filesystem doesn't have a file requested by the List Files (`/v1/client/fs/ls`) or Stat File API (`/v1/client/fs/stat`), we currently return a HTTP 500 error with the expected "file not found" error message. Return a HTTP 404 error instead.
This change doesn't help the streaming endpoints, but all our callers currently call the `/v1/client/fs/stat` endpoint first.

api: return 404 for alloc FS list/stat endpoints

---

.gitignore
terraform/Vagrantfile

The file syntax had been updated to post-0.12 syntax, whereas the Vagrant machine still installed a 0.11 version causing a failure to run `terraform init`. The update also includes a gitignore entry, ignoring the Terraform lock file present in newer versions.
closes #11536

terraform: update installed version used to 1.0.11.

---

website/content/docs/configuration/vault.mdx

While it *is* clarified toward the bottom of this page, I've seen people
go to great lengths to configure tokens for clients anyway, so I think
it's worth noting on the parameter's docs as well.

docs: clarify vault.token only required on servers

---

.changelog/11556.txt
nomad/job_endpoint.go
nomad/job_endpoint_test.go

Following-up on https://github.com/hashicorp/nomad-autoscaler/pull/542, scaling actions not being performed due to active deployments is actually not uncommon. 
This PR removes the scaling event error that used to emitted in these situations to reduce noise and avoid confusing operators and make them look into possible errors that are not really a problem.

Don't emit scaling event error when a deployment is underway

---

Vagrantfile

As of VirtualBox 6.1.28, host-only networks [are restricted to `192.168.56.0/21` by default](https://www.virtualbox.org/manual/ch06.html#network_hostonly),  so spinning up the Vagrant boxes with secondary networks fail with an error `E_ACCESSDENIED`.
Update the IP configuration of the Vagrant boxes to fall within the allowed range so that we don't need to ask developers from the community to make VirtualBox configuration updates outside of their normal Vagrant use.
(I ran into this myself but see also https://github.com/hashicorp/vagrant/issues/12553)

tools: update virtualbox networking configuration

---

command/agent/config.go
command/agent/http.go
nomad/structs/config/ui.go
nomad/structs/config/ui_test.go
website/content/docs/configuration/ui.mdx
website/data/docs-nav-data.json

For https://github.com/hashicorp/nomad/issues/5860
Add `ui` block to agent configuration to enable/disable the web UI and
provide the web UI with links to Vault/Consul.
---
This PR should probably wait pending on the RFC I've circulated earlier today. But this is what it looks like with this configuration block:
```hcl
ui {
enabled = true
consul {
base_url = "https://consul.example.com:8500/ui"
}
vault {
base_url = "https://vault.example.com:8200/ui"
}
}
```
It shows up like the following in the API:
```
$ curl -s localhost:4646/v1/agent/self | jq '.config.UI'
{
"Consul": {
"BaseURL": "https://consul.example.com:8500/ui"
},
"Enabled": true,
"Vault": {
"BaseURL": "https://vault.example.com:8200/ui"
}
}
```

config: UI configuration block with Vault/Consul links

---

.changelog/11565.txt
scheduler/scheduler_system.go

Fixes https://github.com/hashicorp/nomad/issues/11563
In the system scheduler, if a subset of clients are filtered by class,
we hit a code path where the `AllocMetric` has been copied, but the
`Copy` method does not instantiate the various maps. This leads to an
assignment to a nil map. This changeset ensures that the maps are
non-nil before continuing.
The `Copy` method relies on functions in the `helper` package that all
return nil slices or maps when passed zero-length inputs. This
changeset to fix the panic bug intentionally defers updating those
functions because it'll have potential impact on memory usage. See
https://github.com/hashicorp/nomad/issues/11564 for more details.
This impacts 1.2.0 and above, so there's no backport required.

scheduler: fix panic in system jobs when nodes filtered by class

---

website/content/docs/autoscaling/agent/source.mdx
website/content/docs/autoscaling/cli.mdx
website/data/docs-nav-data.json

Add support documentation for the new feature implemented in https://github.com/hashicorp/nomad-autoscaler/pull/544.

docs: add CLI and config docs for the Autoscaler policy source config

---

command/agent/http_test.go

The `TestHTTPServer_Limits_Error` test never starts the agent so it
had an incomplete configuration, which caused panics in the test. Fix
the configuration.
The PR #11555 had a branch name like `f-ui-*` which caused CI to skip
the unit tests over the HTTP handler setup, so this wasn't caught in
PR review.

config: fix test-only failures in UI handler setup

---

client/config/config.go

This PR fixes a typo in the source code for `Config.Logger` field: `thhe -> the`.

docs: fix typo in the comment

---

website/content/docs/job-specification/volume.mdx

Fixes https://github.com/hashicorp/nomad/issues/11581
The `mount_flags` option takes a slice of strings, not a comma-separated string like the flags passed to `mount(8)`.
Examples in use in [ceph](https://github.com/hashicorp/nomad/blob/main/demo/csi/ceph-csi-plugin/volume.hcl#L21) and [hostpath](https://github.com/hashicorp/nomad/blob/main/demo/csi/hostpath/hostpath.hcl#L24) demos

docs: `mount_flags` takes a slice of strings

---

website/content/partials/envvars.mdx

docs: add deprecation note to old style network task env vars.

---

nomad/structs/config/ui.go
nomad/structs/config/ui_test.go
ui/app/templates/components/global-header.hbs
website/content/docs/configuration/ui.mdx

Give ourselves some room for extension in the UI configuration block
by naming the field `ui_url`, which will let us have an `api_url`.

ui: change Consul/Vault base URL field name

---

.changelog/11585.txt
client/client.go

Fixes https://github.com/hashicorp/nomad/issues/11404
The `consul.client_auto_join` configuration block tells the Nomad
client whether to use Consul service discovery to find Nomad
servers. By default it is set to `true`, but contrary to the
documentation it was only respected during the initial client
registration. If a client missed a heartbeat, failed a
`Node.UpdateStatus` RPC, or if there was no Nomad leader, the client
would fallback to Consul even if `client_auto_join` was set to
`false`. This changeset returns early from the client's trigger for
Consul discovery if the `client_auto_join` field is set to `false`.
---
To test this I ran a client node and a server node with Consul under Vagrant. Then I blocked access to the server's ports and Consul:
```
$ sudo iptables -A INPUT -p …
```

client: respect `client_auto_join` after connection loss

---

.changelog/_664.txt

This changelog is for a PR that landed in Nomad Enterprise only ([ref](https://github.com/hashicorp/nomad-enterprise/pull/664))
(I checked with the Consul folks and `_<id of ENT PR>.txt` is how they do the changelog entries for ENT-only items with go-changelog.)

changelog: new metrics in Nomad Enterprise

---

command/meta.go

This block used to set the entire config.TLSConfig with the
values passed by the user. This worked fine if the user set all the options,
or at least enough, but had the unintended side effect of overwriting values
that had been configured in environment variables. If the user passed only
one setting, say `tls-skip-verify`, all the other settings, like CACert would
get overwritten with blank strings.

Override TLS flags individually for meta commands

---

e2e/terraform/config/dev-cluster/nomad/client-linux/client.hcl
e2e/terraform/config/shared/nomad-tls.hcl

This slipped through to main and is breaking `lint-go` on some open PRs

hclfmt on some config files

---

.changelog/11610.txt
api/operator.go
command/agent/http.go
command/agent/operator_endpoint.go
nomad/job_endpoint.go
nomad/job_endpoint_test.go
nomad/structs/errors.go
nomad/structs/operator.go
website/content/api-docs/operator/scheduler.mdx
website/content/docs/configuration/server.mdx

Fixes https://github.com/hashicorp/nomad/issues/11450
During incident response, operators may find that automated processes
elsewhere in the organization can be generating new workloads on Nomad
clusters that are unable to handle the workload. This changeset adds a
field to the `SchedulerConfiguration` API that causes all job
registration calls to be rejected unless the request has a management
ACL token.
---
Note this doesn't include any new CLI commands (see https://github.com/hashicorp/nomad/issues/11450#issuecomment-984944578 for why)

scheduler: config option to reject job registration

---

.github/workflows/backport.yml

This introduces backport assistant to backport changes to target branches.
The main purpose that this serves is to preserve docs changes to `stable-website` on _some_ target release-branch, since `stable-website` is considered to be ephemeral and force-pushing over it may occur at any time.
- `stable-website`
- latest `release-#.#.#` branch, determined by the greatest semver out of labels that match `backport/*`
- `release-a.b.c`
A `ELEVATED_GITHUB_TOKEN` repository secret to be present

feat: `backport.yml`

---

README.md
website/README.md

Use a trivial change to verify `backport-assistant` functionality 
Label `backport/1.2.2` should backport to `release-1.2.2`
The target of this PR is `stable-website`

chore: verify backport-assistant

---

website/content/docs/operations/metrics.mdx

I didn't add additional detail as I noticed https://github.com/hashicorp/nomad/pull/11623 was in-progress.

docs: add license expiry metric to metrics website doc.

---

.changelog/11631.txt
command/job_plan.go

cli: Add var args to plan output.

---

website/content/docs/operations/metrics-reference.mdx
website/content/docs/operations/monitoring-nomad.mdx
website/data/docs-nav-data.json
website/redirects.js

Fixes https://github.com/hashicorp/nomad/issues/11597
This changeset adds more specific recommendations as to what metrics
to monitor, and what resources should be examined during incident
response.
It also renames the "Telemetry" section to "Monitoring Nomad" to
surface the material better and distinguish it from the "Metric
Reference".
---
Preview link: https://nomad-i7hsaw7pp-hashicorp.vercel.app/docs/operations/monitoring-nomad
Note to reviewers: I don't think this is intended to be an all-comprehensive
troubleshooting guide for all things Nomad, so much as significantly improving 
the detail in the documentation we have. Keep that scope in mind. 😀

docs: improve docs for troubleshooting and monitoring scheduler

---

.circleci/config.yml

We don't run tests over documentation PRs marked by the branch prefix
`docs-*`. With the new backport assistant, that should also include
branches with the prefix `backports/docs-*`

CI: don't run unit tests over docs backports

---

.changelog/11550.txt
command/deployment_status.go
command/monitor.go
website/content/docs/commands/job/run.mdx

This PR changes the `nomad run` command (and other commands using the `monitor.monitor` function) to return a non-zero exit code when monitoring is enabled and deployment fails just like `levant deploy` does. This enables CI scripts to easily detect deployment failures. I chose return code `1` to match the existing documentation stating `0` on success, `2` on scheduling problems, and `1` for any other failures. A dedicated return code for deployment failures may makes sense though.
I also noticed and fixed a supposed typo from #10661 via 24fbb5eeb9ad0ae5eeb7ed88afe6ab0928efc1eb: The monitoring code was using `DeploymentStatusDescriptionBlocked` instead of `DeploymentStatusBlocked`.
Fixes #11082, fixes #10994.

CLI: Return non-zero exit code when deployment fails in `nomad run`

---

contributing/checklist-rpc-endpoint.md

This PR adds instructions for making sure that RPC/HTTP API changes get appropriately reflected in the Nomad OpenAPI project.

Add OpenAPI instructions to RPC Endpoint Checklist

---

.changelog/11662.txt
.circleci/config.yml
CHANGELOG.md
GNUmakefile
contributing/README.md
scripts/release/mac-remote-build
scripts/vagrant-linux-priv-go.sh

For https://github.com/hashicorp/nomad/issues/11662

Merge release 1.2.3 branch

---

website/data/version.js

The 1.2.3 release pushed documentation that was supposed to be only in `main` (i.e. for unreleased features). We'll need to update the release checklist but in the meantime this branch was forked from `v1.2.2` and cherry-picks over only the appropriate commits from https://github.com/hashicorp/nomad/compare/v1.2.2..stable-website

Fix for stable website

---

website/Dockerfile

This PR updates the website's Dockerfile to use a `node:14.17.0-alpine` image, bringing it in line with other product site Dockerfiles.

website: Update website Docker image

---

.changelog/11644.txt
api/operator.go
api/operator_ent_test.go

Without this check, the `api` package tries to parse the response as JSON regardless of status code. But in some situations, like with invalid ACL tokens, the response body is a plain text message, resulting in weird errors like this being sent to clients that make use of the Nomad `api` package:
```
invalid character 'P' looking for beginning of value
```

api: return error when `LicenseGet` status is not `200`

---

.changelog/11678.txt
api/agent.go
api/nodes.go
api/regions.go
command/agent/agent_endpoint.go
command/operator_debug.go
command/operator_debug_test.go

Fixes https://github.com/hashicorp/nomad/issues/10767
When a cluster doesn't have a leader, the `nomad operator debug`
command can safely use stale queries to gracefully degrade the
consistency of almost all its queries. The query parameter for these
API calls was not being set by the command.
Some `api` package queries do not include `QueryOptions` because
they target a specific agent, but they can potentially be forwarded to
other agents. If there is no leader, these forwarded queries will
fail. Provide methods to call these APIs with `QueryOptions`.

cli: ensure `-stale` flag is respected by `nomad operator debug`

---

.changelog/11675.txt
command/commands.go
command/eval_list.go
command/eval_list_test.go
website/content/docs/commands/eval/index.mdx
website/content/docs/commands/eval/list.mdx
website/content/docs/commands/eval/status.mdx
website/content/docs/upgrade/upgrade-specific.mdx
website/data/docs-nav-data.json
website/redirects.js

Use the new filtering and pagination capabilities of the `Eval.List` RPC (ref https://github.com/hashicorp/nomad/pull/11648) to provide filtering and pagination at the command line.

`nomad eval list` command

---

.changelog/11682.txt
command/commands.go
command/operator_raft.go
command/operator_raft_info.go
command/operator_raft_logs.go
command/operator_raft_state.go
command/operator_snapshot_state.go
website/content/docs/commands/operator/raft-info.mdx
website/content/docs/commands/operator/raft-list-peers.mdx
website/content/docs/commands/operator/raft-logs.mdx
website/content/docs/commands/operator/raft-state.mdx
website/content/docs/commands/operator/snapshot-state.mdx
website/data/docs-nav-data.json

Fixes https://github.com/hashicorp/nomad/issues/11474, should merge before https://github.com/hashicorp/nomad/issues/11451
The `nomad operator raft` and `nomad operator snapshot state`
subcommands for inspecting on-disk raft state were hidden and
undocumented. Expose and document these so that advanced operators
have support for these tools.
----
Preview links for docs:
* https://nomad-ozcyz2xf2-hashicorp.vercel.app/docs/commands/operator/raft-info
* https://nomad-ozcyz2xf2-hashicorp.vercel.app/docs/commands/operator/raft-logs
* https://nomad-ozcyz2xf2-hashicorp.vercel.app/docs/commands/operator/raft-state
* https://nomad-ozcyz2xf2-hashicorp.vercel.app/docs/commands/operator/snapshot-state

cli: unhide advanced operator raft debugging commands

---

command/operator_raft_logs.go
helper/raftutil/state.go

Fixes https://github.com/hashicorp/nomad/issues/11451
The `nomad operator raft logs` command uses a raft helper that reads
in the logs from raft and serializes them to JSON. The previous
implementation returned the slice of all logs and then serializes the
entire object. Update the helper to stream the log entries and then
serialize them as newline-delimited JSON.

cli: stream raft data to `operator raft logs` subcommand

---

website/content/docs/job-specification/template.mdx

`template` blocks are a powerful tool for task configuration and service discovery, but they can be hard to get started and our documentation is rather light in references and examples.
This PR adds more Consul related examples and links to resources where users can learn more about Consul Template functions and Go template syntax in general.

docs: add more references and examples to the `template` block

---

helper/raftutil/state.go
helper/raftutil/state_test.go

Before this change trying to run `nomad operator raft {info,logs}` on an
inuse raft.db would cause the command to block until the agent using
raft.db is closed.
After this change the command will block for 1s before returning a
(hopefully) helpful error message.
This change also sets the ReadOnly mode on the underlying BoltDb to
ensure diagnostics make no changes to the underlying store. We have no
evidence this has ever occurred, but it seems like a useful safety
measure.
No changelog added since this is a minor tweak in a "new" feature (it
was hidden in previous relases).

cli: return error from raft commands if db is open

---

ui/app/components/breadcrumbs/default.hbs
ui/app/components/breadcrumbs/job.hbs
ui/app/controllers/allocations/allocation.js
ui/app/controllers/allocations/allocation/task.js
ui/app/controllers/clients/client.js
ui/app/controllers/jobs/job/task-group.js
ui/app/controllers/servers/server.js
ui/app/styles/core/breadcrumb.scss
ui/app/styles/core/navbar.scss
ui/tests/acceptance/client-detail-test.js
ui/tests/acceptance/client-monitor-test.js
ui/tests/acceptance/server-monitor-test.js
ui/tests/acceptance/task-detail-test.js
ui/tests/acceptance/task-group-detail-test.js

This PR handles creating titles to breadcrumbs.
Actual
Mock
Special Case for Parent Jobs per the RFC

add titles to breadcrumbs

---

.changelog/11544.txt
ui/app/controllers/jobs/job/allocations.js
ui/app/templates/jobs/job/allocations.hbs
ui/tests/acceptance/job-allocations-test.js
ui/tests/pages/jobs/job/allocations.js

Add filters to Allocations

---

.changelog/11545.txt
ui/app/controllers/clients/client/index.js
ui/app/controllers/jobs/job/task-group.js
ui/app/models/allocation.js
ui/app/styles/components/boxed-section.scss
ui/app/templates/clients/client/index.hbs
ui/app/templates/jobs/job/task-group.hbs
ui/tests/acceptance/client-detail-test.js
ui/tests/acceptance/task-group-detail-test.js
ui/tests/pages/clients/detail.js
ui/tests/pages/jobs/job/task-group.js
ui/tests/unit/serializers/allocation-test.js
ui/tests/unit/serializers/volume-test.js

@mikenomitch @juliezzhou adding the `client` filter doesn't make sense here, because all allocations in this view belong to the same client since its the `clients/client` route its already filtered to show 1 client.

Add Allocation Filters in Client View

---

ui/app/components/job-page/parts/summary.js
ui/app/templates/components/job-page/parts/summary.hbs

The spec calls for editing the Allocation Status Chart to look more like the Job Client Status Chart. However, the surface area of the Allocation Status Chart spans much further than the Job Client Status Chart as it appears in severals rows throughout the application, as well as, in the Task Group page.
Additionally, the linking capability requested by this feature requires getting the context of a job (and its associated namespace).
Until, we have clarity regarding the surface area of the requested changes:  is this change scoped only to the Job Detail Overview page or everywhere that we are rendering an Allocation Status Summary chart, we can't complete the work for adding links to the legend chart (and reformatting the legend).
Spec:

clickable links in allocations chart

---

.changelog/11710.txt
nomad/eval_endpoint.go
nomad/eval_endpoint_test.go
website/content/api-docs/evaluations.mdx

Fixes https://github.com/hashicorp/nomad/issues/11599

api: respect wildcard in evaluations list API

---

website/content/docs/job-specification/gateway.mdx

1. I believe this line should be corrected to add mesh as one of the choices
2. I found that we are not setting this meta, and it is a required element for wan federation. I believe it would be helpful and potentially time saving to note that right here.

Mesh Gateway doc enhancements

---

.changelog/11712.txt
scheduler/spread_test.go
scheduler/stack.go
website/content/docs/job-specification/spread.mdx

When the scheduler picks a node for each evaluation, the
`LimitIterator` provides at most 2 eligible nodes for the
`MaxScoreIterator` to choose from. This keeps scheduling fast while
producing acceptable results because the results are binpacked.
Jobs with a `spread` block (or node affinity) remove this limit in
order to produce correct spread scoring. This means that every
allocation within a job with a `spread` block is evaluated against
_all_ eligible nodes. Operators of large clusters have reported that
jobs with `spread` blocks that are eligible on a large number of nodes
can take longer than the nack timeout to evaluate (60s). Typical
evaluations are processed in milliseconds.
In practice, it's not necessary to evaluate every eligible node for
every allocation on large clusters, …

scheduler: fix quadratic performance with spread blocks

---

.changelog/11526.txt
drivers/docker/config.go
drivers/docker/driver.go
drivers/docker/driver_linux_test.go
drivers/docker/fingerprint.go
website/content/docs/drivers/docker.mdx

Currently, Nomad doesn't have a way to enforce `pids_limit` in containers, unless set by user in their job spec.
If a malicious user launches a container with a fork-bomb, that could exhaust entire nomad client host pids.
This PR will allow the operator to enforce `pids_limit` at Nomad client plugin config. User can still override that `pids_limit` in their job spec by setting [`pids_limit`](https://www.nomadproject.io/docs/drivers/docker#pids_limit)  however it must be less than the limit defined on nomad client plugin config.

Add support for setting pids_limit in docker plugin config.

---

.changelog/11724.txt
nomad/csi_endpoint.go
nomad/csi_endpoint_test.go

The lack of wildcard listing impacted the UI due to #11357, where users would first see an empty list when the page loads since the CSI volume list didn't have support for wildcard querying.
Closes #11574

api: support namespace wildcard in CSI volume list

---

website/redirects.js

[https://nomad-9a6467pz5-hashicorp.vercel.app/home](https://nomad-9a6467pz5-hashicorp.vercel.app/home)

fix: redirects website `/home` to `/`

---

scheduler/benchmarks/benchmarks_test.go
scheduler/benchmarks/helpers_test.go

Adds a package `scheduler/benchmarks` with some examples of profile
and benchmarking the scheduler, along with helpers for loading
real-world data for profiling.
This tooling comes out of work done for #11712. These profiles and
test benchmarks have not been added to CI because these particular
profiles are mostly examples and the runs will add an excessive amount
of time to CI runs for code that rarely changes in a way that has any
chance of impacting performance.

scheduler: tooling for scheduler benchmarking

---

.changelog/11728.txt
client/fingerprint/network.go
client/fingerprint/network_test.go

During the network fingerprint, client configuration values are mapped to actual network addresses and interfaces. During this process a `ClientHostNetworkConfig` is translated into `NodeNetworkResource`, but reserved ports were not being set.
Closes #9492

fix host network reserved port fingerprint

---

go.mod
go.sum

The `go-getter` library was updated to 1.5.9 in #11481 to pick up a
bug fix for automatically unpacking uncompressed tar archives. But
this version had a regression in git `ref` param behavior and was
patched in 1.5.10.
Nomad was never release with the bugged version, so no changelog
or backport required. (h/t @apparentlymart for the heads up on this!)

deps: upgrade go-getter to 1.5.10

---

.changelog/11741.txt
client/allocrunner/interfaces/task_lifecycle.go
client/allocrunner/taskrunner/task_runner_hooks.go

Fixes https://github.com/hashicorp/nomad/issues/11547
The task runner prestart hooks take a `joincontext` so they have the
option to exit early if either of two contexts are canceled: from
killing the task or client shutdown. Some tasks exit without being
shutdown from the server, so neither of the joined contexts ever gets
canceled and we leak the `joincontext` (48 bytes) and its internal
goroutine. This primarily impacts batch jobs and any task that fails
or completes early such as non-sidecar prestart lifecycle tasks.
Cancel the `joincontext` after the prestart call exits to fix the
leak.

task runner: fix goroutine leak in prestart hook

---

website/components/downloads-props/index.jsx
website/pages/downloads/enterprise.jsx
website/pages/downloads/index.jsx

A nicer interface to see enterprise binaries, approved by release engineering and legal. A license key is required to actually run any given enterprise binary.
[🔎 Preview](https://nomad-27azxzas8-hashicorp.vercel.app/downloads/enterprise)

add enterprise downloads page

---

.changelog/11743.txt
nomad/deployment_endpoint.go
nomad/deployment_endpoint_test.go
website/content/api-docs/deployments.mdx

Add `per_page` and `next_token` handling to `Deployment.List` RPC, and
allow the use of a wildcard namespace for namespace filtering.
Note for reviewers: this brings the API up to parity with `Eval.List` but doesn't
include the CLI updates we'd need to use it. I want to hold off on that until we 
have #11742 figured out, because that'll impact the design.

api: paginate deployment list and accept wildcard namespace

---

command/agent/agent.go
command/agent/agent_test.go
command/agent/command.go
command/agent/config.go
command/agent/config_test.go
command/agent/http.go
command/agent/http_test.go
command/agent/testagent.go
website/content/docs/configuration/consul.mdx

naive partial support for #9257 (HTTP addresses only) by creating a `http.Server` for every space-seperated address defined in `addresses.http`. Example:
```hcl
addresses {
http="127.0.0.1 {{ GetPrivateIP }} ..."
}
```
Hoping to get some feedback if this is the approach that should be take or something like consul is doing by abstracting the servers into [apiserver.go](https://github.com/hashicorp/consul/blob/main/agent/apiserver.go). There are also one or two TODOs I am not sure the best approach to take.

agent: support multiple http address in addresses.http

---

.changelog/11582.txt
command/agent/config_test.go
command/agent/testagent.go
website/content/docs/configuration/index.mdx

Some minor follow-ups to https://github.com/hashicorp/nomad/pull/11582:
* changelog entry
* expanded the tests a bit
* added the docs for the config value

docs/tests for multiple HTTP address config

---

.changelog/11721.txt
client/fs_endpoint.go
client/fs_endpoint_test.go

Hi,
this MR aims to address the issue reported here https://github.com/hashicorp/nomad/issues/11653 .  I described the problem in [this comment](https://github.com/hashicorp/nomad/issues/11653#issuecomment-996874918). 
This solution adds one more channel to the `streamFile` function that instead of cancelling on the event from channel when eof is reached, it performs one more read until eof which I think should be an expected behavior while streaming logs.
It is a draft for now opened for discussion. I confirmed that it works for the example posted in the issue. It should work since while newFileEvent is generated, the previous file is already full.
I haven't checked tests yet.

Fix log streaming missing frames

---

.changelog/11776.txt
nomad/volumewatcher/volume_watcher.go
nomad/volumewatcher/volumes_watcher_test.go

When `volumewatcher.Watcher` starts on the leader, it starts a watch
on every volume and triggers a reap of unused claims on any change to
that volume. But if a reaping is in-flight during leadership
transitions, it will fail and the event that triggered the reap will
be dropped. Perform one reap of unused claims at the start of the
watcher so that leadership transitions don't drop this event.
This bug contributes to https://github.com/hashicorp/nomad/issues/10927 but is not the full cause of all cases.

csi: reap unused volume claims at leadership transitions

---

.changelog/11744.txt
nomad/node_endpoint_test.go
nomad/structs/structs.go
nomad/structs/structs_test.go

Node.Copy() had a couple minor bugs. I believe both fields incorrectly copied (DNS and CPU) are only ever overwritten, so I don't think this fixes any existing buggy behavior.
fd1c71dc8d40dfa2b974f3d83f79fad9069efda5 also reorders fields in Node.Copy to match their order on the struct. Makes checking easier.

Fix Node.Copy()

---

nomad/eval_broker.go

We wanted metric visibility into when waiting evaluations would be evaluated to reschedule a failed/lost allocation.  This is the change we made for ourselves and figured it might have value upstream.
If any small changes are desired to upstream this, please let me know.

Emit metrics for eval waitUntil as nomad.nomad.broker.eval_waiting

---

ui/app/controllers/jobs/job/task-group.js
ui/app/templates/csi/volumes/volume.hbs
ui/app/templates/jobs/job/task-group.hbs
ui/app/templates/optimize.hbs
ui/tests/integration/components/trigger-test.js

#11590 introduced a few changes due to auto-formatting that caused CI to break. #11754 will address these issues, but until it's merged, this PR aims to revert those changes to make sure `main` is properly tested in CI. Reverting these changes also help us validate that #11754 will format templates properly.

ui: fix CI

---

client/allocrunner/alloc_runner_hooks.go
client/allocrunner/csi_hook.go
client/allocrunner/csi_hook_test.go

Small refactoring of the allocrunner hook for CSI to make it more testable, and a unit test that covers most of its logic. These tests have uncovered a bug https://github.com/hashicorp/nomad/issues/11786 which I'm going to tackle as part of the work I'm doing on https://github.com/hashicorp/nomad/issues/10833 and https://github.com/hashicorp/nomad/issues/10927

CSI: tests to exercise csi_hook

---

website/content/docs/configuration/acl.mdx

Fixes https://github.com/hashicorp/nomad/issues/11676
Client endpoints such as `alloc exec` are enforced on the client if
the API client or CLI has "line of sight" to the client. This is
already in the Learn guide but having it in the ACL configuration docs
would be helpful.

docs: note that clients need to have ACLs enabled

---

CHANGELOG.md
client/allocdir/input/test.go
client/client.go
client/interfaces/client.go
nomad/job_endpoint_test.go
nomad/structs/structs.go

Signed-off-by: Conor Evans <coevans@tcd.ie>
If this is deemed inappropriate, feel free to close it. I spotted one of these when making a different contribution and figured I'd fix it, then figured it might be spread throughout the comments etc.

Replace 'a alloc' with 'an alloc' where appropriate

---

client/allocrunner/taskrunner/vault_hook.go

Templates in nomad jobs make use of the vault token defined in
the vault stanza when issuing credentials like client certificates.
When using change_mode "noop" in the vault stanza, consul-template
is not informed in case a vault token is re-issued (which can
happen from time to time for various reasons, as described
in https://www.nomadproject.io/docs/job-specification/vault).
As a result, consul-template will keep using the old vault token
to renew credentials and - once the token expired - stop renewing
credentials. The symptom of this problem is a vault_token
file that is newer than the issued credential (e.g., TLS certificate)
in a job's /secrets directory.
This change corrects this, so that h.updater.updatedVaultToken(token)
is called, which will inform stakeholders about the new …

Un-break templates when using vault stanza change_mode noop

---

.changelog/11500.txt
client/allocrunner/taskrunner/task_runner.go
client/structs/structs.go
drivers/docker/stats_test.go
drivers/docker/util/stats_posix.go
drivers/shared/executor/executor_linux.go

This PR should address #10067 and trivially adds  `mapped_file` in DockerStatsToTaskResourceUsage.
It sounds like that the `mapped_file` metric is needed in here as well:
https://github.com/deblasis/nomad/blob/b4a230d2cf57ff7a18c1e3bca006a9a7c4b284ca/drivers/shared/executor/executor_linux.go#L386
I had a look at [runc](https://github.com/opencontainers/runc) code and it seems that the metric is pulled from the `memory.stat` file, in compliance with https://www.kernel.org/doc/Documentation/cgroup-v1/memory.txt
so I thought it was a good thing to add it in `LibcontainerExecutor` as well.
If you think it's a welcome addition and tests are needed, I would like a pointer on how to test that as well. 
Cheers

metrics: added `mapped_file` metric

---

.changelog/11783.txt

As pointed out in https://github.com/hashicorp/nomad/commit/ef93ab2d560179ccd401d8e26b3033ae1879a76e#r63487464, the changelog I wrote for #11783 was ambiguous between the `vault` and `template` `change_mode` field. Correct that for clarity.

docs: improve changelog for PR #11783

---

api/internal/testutil/responsewriter.go
command/agent/acl_endpoint_test.go
command/agent/alloc_endpoint_test.go
command/agent/deployment_endpoint_test.go
command/agent/eval_endpoint_test.go
command/agent/job_endpoint_test.go

Remove reference to the deprecated `ResponseRecorder.HeaderMap` field,
instead calling `.Response.Header()` to get the same data.
closes #10520

cleanup: stop referencing depreceted HeaderMap field

---

.changelog/11830.txt
command/agent/command.go
command/agent/command_test.go
nomad/structs/funcs.go
nomad/structs/funcs_test.go

Minimal alternative to #11819. I think the more drastic changes in the other PR should wait until 1.3.
Goal is to fix at least one of the causes that can cause a node to be
ineligible to receive work:
https://github.com/hashicorp/nomad/issues/9506#issuecomment-1002880600

agent: validate reserved_ports are valid

---

website/content/tools/autoscaling/plugins/apm/datadog.mdx

As pointed out in https://github.com/hashicorp/nomad-autoscaler/issues/558, the `site` configuration for the Datadog Autoscaler plugin should not include a subdomain (and even if it did, it was the example had the wrong one).
The site linked for the list of possible values is also misleading and I couldn't find anything better, so I removed it for now.

docs: fix autoscaling Datadog site configuration

---

go.mod

Adds comment pointing to #11826 where individual packages are noted. And segregates `/api` because it's a special case.

mods: explain replace statements

---

.changelog/11838.txt
command/agent/command.go
go.mod
go.sum

Update `go-hclog` to pull https://github.com/hashicorp/go-hclog/pull/101 and fix log level inference from dependencies that don't use `go-hclog`.
Closes #11594

Fix log level parsing from lines that include a timestamp

---

command/agent/command.go
command/agent/command_test.go
website/content/docs/configuration/server.mdx

agent/docs: add better clarification when top-level data dir needs setting

---

nomad/fsm_oss.go
nomad/plan_apply_oss.go
scheduler/stack_not_ent.go
scheduler/stack_oss.go

Files mostly use the `_oss.go` pattern apart from these ones, which
confused me for a moment when I first came across one. I also fixed-up
the unused function param style where needed.

chore: ensure consistent file naming for non-enterprise files.

---

.changelog/11856.txt
drivers/shared/resolvconf/mount.go

Fixes https://github.com/hashicorp/nomad/issues/11845
When we copy the system DNS to a task's `resolv.conf`, we should set
the permissions as world-readable so that unprivileged users within
the task can read it.

drivers: set world-readable permissions on copied resolv.conf

---

.changelog/11854.txt
command/agent/log_file_bsd.go

Fixes https://github.com/hashicorp/nomad/issues/11850 (pending feedback by @clausecker)
The size of `stat_t` fields is architecture dependent, which was
reportedly causing a build failure on FreeBSD ARM7 32-bit
systems. This changeset matches the behavior we have on Linux.

freebsd: build fix for ARM7 32-bit

---

.changelog/11853.txt
command/volume_deregister.go
command/volume_detach.go

Fixes https://github.com/hashicorp/nomad/issues/11847
When the `volume deregister` or `volume detach` commands get an ID
prefix that matches multiple volumes, show the full length of the
volume IDs in the list of volumes shown so so that the user can select
the correct one.
---
Before:
```
$ nomad volume deregister test-
Prefix matched multiple volumes
ID        Name            Plugin ID         Schedulable  Access Mode
test-vol  test-volume[0]  hostpath-plugin0  true         single-node-reader-only
test-vol  test-volume[1]  hostpath-plugin0  true         single-node-reader-only
```
After
```
$ nomad volume deregister test-
Prefix matched multiple volumes
ID              Name            Plugin ID         Schedulable  Access Mode
test-volume[0]  test-volume[0]  hostpath-plugin0  true …
```

csi: when warning for multiple prefix matches, use full ID

---

.changelog/11852.txt
nomad/state/state_store.go
nomad/state/state_store_test.go

Fixes https://github.com/hashicorp/nomad/issues/11846
The command line client sends a specific volume ID, but this isn't
enforced at the API level and we were incorrectly using a prefix match
for volume deregistration, resulting in cases where a volume with a
shorter ID that's a prefix of another volume would be deregistered
instead of the intended volume.

csi: volume deregistration should require exact ID

---

.changelog/11820.txt
ui/app/components/allocation-status-bar.js
ui/app/styles/charts/distribution-bar.scss
ui/app/templates/components/job-page/parts/job-client-status-summary.hbs
ui/app/templates/components/job-page/parts/summary-legend-item.hbs
ui/app/templates/components/job-page/parts/summary.hbs
ui/tests/helpers/module-for-job.js
ui/tests/pages/components/job-client-status-bar.js
ui/tests/pages/jobs/detail.js

feat:  add links to legend items in `allocation-summary`

---

website/content/tools/index.mdx

HashiBox
https://github.com/nunchistudio/hashibox 
Vagrant environment to simulate a highly-available cloud with Consul, Vault, and Nomad.

docs: add HashiBox to the list of community tools

---

.changelog/11507.txt
command/operator_debug.go
command/operator_debug_test.go

Improves `nomad debug` error messages when contacting agents that do not
have /v1/agent/host endpoints (the endpoint was added in v0.12.0)
Part of #9568 and manually tested against Nomad v0.8.7.
Hopefully isRedirectError can be reused for more cases listed in #9568

cli: improve debug error messages

---

.changelog/11865.txt
command/operator_debug.go
command/operator_debug_test.go
website/content/docs/commands/operator/debug.mdx

Adds Event Stream capture to `nomad operator debug`.  Enable `-verbose` output for realtime feedback on events as they are captured.
New CLI flags:
* `-event-filter`
* `-verbose`
Example usage:
`nomad operator debug -event-filter="Evaluation:*" -verbose`
See [Events API](https://www.nomadproject.io/api-docs/events) documentation for more details on topic filtering.
Closes #11493

cli: Add event stream capture to nomad operator debug

---

ui/tests/helpers/module-for-job.js

`main` is currently [failing](https://app.circleci.com/pipelines/github/hashicorp/nomad/19270/workflows/752f955b-2e30-40f3-9a04-eabc9cbe4c37/jobs/195119/tests#failed-test-0) due to a missing URI encoding to the job name.
closes https://github.com/hashicorp/nomad/issues/11866

ui: fix test

---

.changelog/11843.txt
api/api.go
api/api_test.go
command/agent/http.go
go.mod
go.sum

(going in 1.3.0)
After swapping gzip handler to use the gorilla library, we
must account for a quirk in how zero/minimal length response
bodies are delivered.
The previous gzip handler was configured to compress all responses
regardless of size - even if the data was zero length or below the
network MTU. This behavior changed in [v1.1.0](https://github.com/nytimes/gziphandler/commit/c551b6c3b4b976eafa1a18220b5e21692784d8e2#diff-de723e6602cc2f16f7a9d85fd89d69954edc12a49134dab8901b10ee06d1879d)
which is why we could not upgrade.
The Nomad HTTP Client mutates the http.Response.Body object, making
a strong assumption that if the Content-Encoding header is set to "gzip",
the response will be readable via gzip decoder. This is no longer true
for the nytimes gzip handler, and is also not true …

deps: replace gzip handler

---

.changelog/11855.txt
command/meta_test.go
drivers/shared/executor/executor.go
drivers/shared/executor/pty_unix.go
go.mod
go.sum

(going in 1.3.0)
github.com/kr/pty was moved to github.com/creack/pty
https://github.com/kr/pty#pty
Swap this dependency so we can upgrade to the latest version
and no longer need a replace directive.

deps: pty has new home

---

e2e/terraform/config/shared/consul-tls.json
e2e/terraform/packer/ubuntu-bionic-amd64/nomad.service

Consul's HTTPS port is not enabled by default and setting a non-zero value for `StartLimitIntervalSec` will result in [systemd not attempting to restart Nomad anymore](https://www.freedesktop.org/software/systemd/man/systemd.unit.html#StartLimitIntervalSec=interval).
Note: we have noticed the Windows client SSH connection timeout sometimes, but it seems like a separate issue.

e2e: enable Consul HTTPS port and always restart Nomad systemd unit

---

website/content/docs/commands/volume/create.mdx
website/content/docs/commands/volume/register.mdx

The examples for `nomad volume create` and `nomad volume register` are
not setting `mount_flags` using an array of strings.
This fixes the issue by changing the example to be `mount_flags =
["noatime"]`.

docs: Update volume create/register mount options to use []string example

---

.changelog/11891.txt
nomad/leader.go
nomad/volumewatcher/volumes_watcher.go
nomad/volumewatcher/volumes_watcher_test.go

Partial fix for https://github.com/hashicorp/nomad/issues/10927 https://github.com/hashicorp/nomad/issues/10052 
The volumewatcher that runs on the leader needs to make RPC calls
rather than writing to raft (as we do in the deploymentwatcher)
because the unpublish workflow needs to make RPC calls to the
clients. This requires that the volumewatcher has access to the
leader's ACL token.
But when leadership transitions, the new leader creates a new leader
ACL token. This ACL token needs to be passed into the volumewatcher
when we enable it, otherwise the volumewatcher can find itself with a
stale token.

CSI: update leader's ACL in volumewatcher

---

command/agent/http.go
drivers/shared/executor/executor_universal_linux.go
helper/flags/autopilot_flags.go
lib/cpuset/cpuset.go
plugins/drivers/server.go

This series of commits fixes some integer bounds checking bugs that in practice don't result in user-visible issues but were triggering security and code quality scanners. Fixing these reduces automated scanner noise.
(Partially covers https://github.com/hashicorp/nomad/issues/11777)

fix integer bounds checks

---

.changelog/11902.txt
client/config/config.go
command/agent/config_test.go
command/agent/test-resources/client_with_basic_template.hcl
command/agent/test-resources/client_with_basic_template.json

When parsing the new `consul-template` configuration parameters introduced in 1.2.4 , the `finalizeClientTemplateConfig` function failed to account for the pre-1.2.4 fields in its logic and set the `ClientTemplateConfig` to `nil` only if none of the new configuration options were set. 
This PR:
- Updates that logic to check the pre-1.2.4 fields
- Adds negative tests to ensure configs without the new `consul-template` settings introduced in 1.2.4 can still parse.
Closes #11902

Update IsEmpty logic in finalizeClientTemplateConfig

---

.changelog/11896.txt
ui/app/templates/allocations/allocation/task/index.hbs

This fixes the wrong link target in the volumes list of tasks. I moved the link to the source column which is the actual link target.

Fix for #11884: Move volume link to the source column and fix the link target

---

.github/workflows/semgrep.yml
.semgrep/changelog.yml
.semgrep/go_tests.yml

Add some initial set of `semgrep` rules. Currently they only run against files modified in PRs because the `go_tests.yml` rules are not followed in `main`, but they will at least nudge us towards following the new style.

ci: add semgrep

---

website/content/docs/configuration/client.mdx

note: need to figure out the right labels to get this onto the correct versioned websites (back to 1.1.0)

docs: add `cores` to client reserved config block.

---

.changelog/11890.txt
nomad/core_sched.go
nomad/core_sched_test.go
nomad/state/state_store.go
nomad/state/testing.go
nomad/volumewatcher/volume_watcher_test.go
nomad/volumewatcher/volumes_watcher_test.go
scheduler/feasible.go

Partial fix for https://github.com/hashicorp/nomad/issues/10927 https://github.com/hashicorp/nomad/issues/10052 https://github.com/hashicorp/nomad/issues/8734
It's currently possible (because of either bugs which we still need to resolve, or simply from node failures) for CSI volumes to be claimed by allocations that don't exist. This changeset is intended to assert a reasonable state at the state store level by registering these nil allocations as "past claims" on any read. This will cause any pass through the periodic GC or volume watcher to trigger the unpublishing workflow for those claims.
---
Note this won't entirely fix the issue:
* PR https://github.com/hashicorp/nomad/pull/11892 will address ensuring that the unpublish workflow will handle a wider range of weird conditions we've …

CSI: resolve invalid claim states

---

nomad/state/state_store.go
nomad/state/testing.go

Fixes https://github.com/hashicorp/nomad/issues/10927#issuecomment-1020600171. 
In the client's `(*csiHook) Postrun()` method, we make an unpublish RPC that includes a claim in the `CSIVolumeClaimStateUnpublishing` state and using the mode from the client. But then in the `(*CSIVolume) Unpublish` RPC handler, we query the volume from the state store (because we only get an ID from the client). And when we make the client RPC for the node unpublish step, we use the _current volume's_ view of the mode. If the volume's mode has been changed before the old allocations can have their claims released, then we end up making a CSI RPC that will never succeed.
Why does this code path get the mode from the volume and not the claim? Because the claim written by the GC job in `(*CoreScheduler) …

CSI: ensure that PastClaims are populated with correct mode

---

ui/package.json
ui/testem.js
ui/tests/test-helper.js
ui/yarn.lock

Our test suite currently takes 15+ minutes to run. We're adding new tooling to allow local testing to be done in < 2 minutes.
New CLI commands:
`yarn test:ember` this will run the test suite in server mode. To add filters:
`yarn test:ember filter="your filter here"`
`yarn test:local` runs the full test suite against all cores of your laptop. If you don't have regular MacBook pro with 8 cores see directions below.
Note:  Apple M1 laptops can't load balance their tests against all 8 cores. It's capped at 4.
Run `ember exam --server --load-balance --parallel=4`.

ui:  test tooling

---

client/allocrunner/csi_hook.go
client/allocrunner/csi_hook_test.go
client/pluginmanager/csimanager/volume.go

Partial fix for https://github.com/hashicorp/nomad/issues/10927 https://github.com/hashicorp/nomad/issues/10052 https://github.com/hashicorp/nomad/issues/10833
Requires https://github.com/hashicorp/nomad/pull/11890 https://github.com/hashicorp/nomad/pull/11932 
When an allocation stops, the `csi_hook` makes an unpublish RPC to the
servers to unpublish via the CSI RPCs: first to the node plugins and
then the controller plugins. The controller RPCs must happen after the
node RPCs so that the node has had a chance to unmount the volume
before the controller tries to detach the associated device.
But the client has local access to the node plugins and can
independently determine if it's safe to send unpublish RPC to those
plugins. This will allow the server to treat the node plugin as …

CSI: node unmount from the client before unpublish RPC

---

nomad/plan_endpoint.go
nomad/plan_endpoint_test.go
nomad/structs/structs.go

The Plan.Submit endpoint assumed PlanRequest.Plan was never nil. While
there is no evidence it ever has been nil, we should not panic if a nil
plan is ever submitted because that would crash the leader.

core: prevent malformed plans from crashing leader

---

.changelog/11878.txt
nomad/deploymentwatcher/deployment_watcher.go
nomad/deploymentwatcher/deployments_watcher_test.go
nomad/mock/mock.go

When using the auto promote feature with canary deployments that have task groups without canaries, the deployment will never auto promote and hang even when the canaries are all healthy for the task groups that it has been enabled for.
This PR fixes this bug by skipping task groups that have no canaries set during the auto promote validation and adds a test to catch this case specifically. To see what occurs when this fix is not implemented (as has been observed in mainstream Nomad):
- comment out/delete `L292-L294 of nomad/deploymentwatcher/deployment_watcher.go`
- run tests for this package
Let me know if there's anything I can do to help shepard this through into a release, currently there's manual intervention in some of our deployments that this occurs in and it would be great to …

Bugfix: auto-promote canary taskgroups when mixed with non-canary taskgroups

---

e2e/consul/check_restart.go
e2e/consultemplate/consultemplate.go
e2e/csi/ebs.go
e2e/csi/efs.go
e2e/e2eutil/job.go
e2e/namespaces/namespaces.go
e2e/networking/networking.go
e2e/rescheduling/rescheduling.go
e2e/scaling/scaling.go
e2e/scalingpolicies/scalingpolicies.go
e2e/volumes/volumes.go

PR #11550 changed the job stop exit behaviour when monitoring the
deployment. When stopping a job, the deployment becomes cancelled
and therefore the CLI now exits with status code 1 as it see this
as an error.
This change adds a new utility e2e function that accounts for this
behaviour.
Closes #11950

e2e: account for new job stop CLI exit behaviour.

---

.semgrepignore

Semgrep seems to consistently break with the error below anytime `structs.go` is modified. There isn't much we can do besides disable the semgrep rules entirely or disable semgrep from running on this file, while we wait for an upstream fix.
```
=== setting up agent configuration
| using semgrep rules from the committed .semgrep/ directory
| not on head ref 990a6dfb5fd900388869c33c8ffa8c8cf0928eb3; checking that out now...
| reporting findings introduced by these commits:
|   * 990a6df client: follow up on CR comments
|   * 713de8b client: fix a bug
| looking at 5 changed paths
=== looking for current issues in 5 files
| returning to original head revision 024137f92d771c1b38071fa2f210dbd83e17d3f1
=== failed command's STDOUT:
=== failed command's STDERR:
Error: ROR] …
```

build: disable semgrep on structs.go for now

---

.changelog/11956.txt
.semgrep/rpc_endpoint.yml
nomad/alloc_endpoint.go
nomad/deployment_endpoint.go
nomad/eval_endpoint.go
nomad/job_endpoint.go
nomad/node_endpoint.go
nomad/plan_endpoint.go
nomad/rpc.go
nomad/rpc_test.go
nomad/server.go
nomad/util.go

There are different types of endpoints in Nomad, and different types use different mechanism to validate and authenticate requests.
The most common endpoints are called by end-users via the HTTP API and get translated to an RPC request. They are authenticated using ACL tokens.
Another type of endpoint is used by Raft and are called between servers. This process doesn't have ACL tokens involved, so requests are validated by checking the mTLS certificates, when available.
Finally, there are endpoints that are called by agents directly via RPC, either `client -> server` or `server -> server`. These also don't use ACL tokens, so there was no explicit validation.
This PRs adds a check to these agent to agent endpoints similar to Raft's, using the mTLS certificate, if available.

Verify TLS certificate on endpoints that are used between agents only

---

helper/funcs.go

I've been working on [hashicorp/nomad-openapi](https://github.com/hashicorp/nomad-openapi) and some of the parameters (i.e. `MaxTrailingLogs` in [Autopilot Configuration](https://www.nomadproject.io/api-docs/operator/autopilot#parameters) is of type `*int32` and I had to write a local `Int32ToPtr` function as one didn't exist in nomad/helper, which doesn't look as clean, so would like to add one in to referenced in the future.

added Int32ToPtr helper function

---

.changelog/11983.txt
api/allocations_exec.go
client/allocrunner/taskrunner/task_runner.go
command/agent/consul/version_checker.go
command/agent/monitor/monitor.go
drivers/docker/stats.go
drivers/shared/eventer/eventer.go
helper/funcs.go
helper/funcs_test.go
nomad/blocked_evals.go
nomad/drainer/watch_jobs.go
nomad/drainer/watch_nodes.go
nomad/eval_broker.go
nomad/plan_queue.go
nomad/server.go
nomad/vault.go

This PR replaces use of time.After with a safe helper function
that creates a time.Timer to use instead. The new function returns
both a time.Timer and a Stop function that the caller must handle.
Unlike time.NewTimer, the helper function does not panic if the duration
set is <= 0.
Fixes #11982

cleanup: prevent leaks from time.After

---

.changelog/11572.txt
command/agent/config.go
website/content/docs/configuration/server.mdx
website/content/docs/upgrade/index.mdx
website/content/docs/upgrade/upgrade-specific.mdx

**DO NOT MERGE TILL 1.3.0**
Many of Nomad's Autopilot features require raft protocol version 3. Set the default raft protocol to 3, and improve the upgrade documentation.
Fixes https://github.com/hashicorp/nomad/issues/7208. Our concerns about the corner case of a server which is shut down during the upgrade can be alleviated by operators upgrading one server at a time, as we generally recommend for updates. I've tentatively marked this issue for 1.3.0 because it seems like it's got enough risk associated with it that it should be in a major update.
---
I've tested out the docs by using the 3-server cluster described in our Vagrant file, with the following configuration file (replace the IPs for server02 and server03 as usual):
<details><summary>server config</summary>
```hcl
log_level  = …
```

raft: default to protocol v3

---

nomad/core_sched.go

Non-CSI garbage collection tasks on the server only log the cutoff
index in the case where it's not a forced GC from `nomad system gc`.
Do the same for CSI for consistency.
Compare to https://github.com/hashicorp/nomad/blob/v1.2.4/nomad/core_sched.go#L102-L115
Pulled this out of plugin count work to keep review sizes reasonable.

core: log CSI GC cutoff index only on non-forced GC

---

.semgrep/time_after.yml

As described in #11983, the use of `<- time.After` may lead to memory leaks. This rule check for potential leaks and suggests  using the new `NewSafeTimer` instead.

add semgrep rule to check for potential time.After leaks

---

.changelog/12012.txt
client/allocrunner/taskrunner/validate_hook.go
nomad/structs/services.go

Currently if len(service name) > 63, the API incorrectly reports the issue to be "not a valid RFC 1123" misleading the developer. Changed the wording to ensure it reflects the correct logic

improve error message on service length

---

.changelog/11995.txt
ui/app/styles/core/table.scss
ui/app/templates/allocations/allocation/index.hbs

for service like [traefik](https://github.com/traefik/traefik), it is easy to break the table ui when specific a middleware config like basic auth.
ref https://doc.traefik.io/traefik/middlewares/http/basicauth/  an example consul catalog tags look like this:
```
traefik.http.middlewares.test-auth.basicauth.users=test:$apr1$H6uskkkW$IgXLP6ewTrSuBkTrqE8wj/,test2:$apr1$d9hr9HBB$4HxwgUir3HP4EsggP/QNo0
```
with word break css enbled:

style: fix up very long tag word breaking the allocation service table width

---

.semgrep/rpc_endpoint.yml
nomad/alloc_endpoint.go
nomad/deployment_endpoint.go
nomad/eval_endpoint.go
nomad/node_endpoint.go
nomad/plan_endpoint.go
nomad/rpc.go
nomad/rpc_test.go
nomad/util.go

PR #11956 implemented a new mTLS RPC check to validate the role of the
certificate used in the request, but further testing revealed two flaws:
1. client-only endpoints did not accept server certificates so the
request would fail when forwarded from one server to another.
2. the certificate was being checked after the request was forwarded,
so the check would happen over the server certificate, not the
actual source.
This PR checks for the desired mTLS level, where the client level
accepts both, a server or a client certificate. It also validates the
cercertificate before the request is forwarded.
#11956 was never released, so no CHANGELOG needed.

fix mTLS certificate check on agent to agent RPCs

---

scheduler/reconcile.go
scheduler/reconcile_util.go

This PR includes readability improvements to `scheduler.allocReconciler` and `scheduler.allocSet`. It does not change behavior.

reconciler: improve variable names and extract methods from inline logic

---

client/fingerprint/env_digitalocean.go
client/fingerprint/env_digitalocean_test.go
client/fingerprint/fingerprint.go

adds fingerprinter for [DigitalOcean droplets](https://www.digitalocean.com/) using the [DigitalOcean Metadata api](https://docs.digitalocean.com/reference/api/metadata-api/).
screenshot of it working on a droplet:

client/fingerprint: add digitalocean fingerprinter

---

.changelog/12008.txt
scheduler/context_test.go
scheduler/feasible.go
scheduler/scheduler.go
scheduler/stack.go
scheduler/util.go
scheduler/util_test.go

Processing an evaluation is nearly a pure function over the state
snapshot, but we randomly shuffle the nodes. This means that
developers can't take a given state snapshot and pass an evaluation
through it and be guaranteed the same plan results.
But the evaluation ID is already random, so if we use this as the seed
for shuffling the nodes we can greatly reduce the sources of
non-determinism. Unfortunately golang map iteration uses a global
source of randomness and not a goroutine-local one, but arguably
if the scheduler behavior is impacted by this, that's a bug in the
iteration.
---
Reviewers: I've grabbed a random set of folks to look at this but maybe consider this mostly a "working proposal". I'm not certain there aren't side-effects I haven't considered here. But this could have …

scheduler: seed random shuffle of nodes with eval ID

---

client/fingerprint/env_digitalocean.go

Fixes the unit tests on `main`, which for some reason didn't run for https://github.com/hashicorp/nomad/pull/12015
This PR should fix the broken test, but that being said @kevinschoonover I'm not sure I understand where the test requirement for that header is coming from. I don't see anything about that in the DO docs: https://docs.digitalocean.com/reference/api/metadata-api/

fingerprint: digitalocean fingerprint test requires metadata header

---

client/fingerprint/env_digitalocean.go
client/fingerprint/env_digitalocean_test.go

follow up to #12028.
Feel free to close this as noise as I'm not sure if this PR is necessary, but wanted to try to address the comments on #12028 since metadata was a remanent of me copying the GCE fingerprinter and is not necessary / used.
ran the tests locally:
```console
> pwd
./nomad/client/fingerprint
> go test
PASS
ok  	github.com/hashicorp/nomad/client/fingerprint	0.875s
```

fingerprint: remove metadata from digitalocean

---

.changelog/9198.txt
website/content/docs/commands/config/index.mdx
website/content/docs/commands/config/validate.mdx
website/data/docs-nav-data.json

For https://github.com/hashicorp/nomad/pull/9198

docs and changelog for `nomad config validate`

---

scheduler/generic_sched.go
scheduler/reconcile.go
scheduler/reconcile_util.go

**This PR contains the following:**
- Refactored `allocReconciler.computeGroup` - extracted inline logic to a series of intention-revealing functions.
- Combined iteration logic in `GenericScheduler`.
- Added or improved comments throughout.

reconciler: refactor `computeGroup`

---

website/content/docs/job-specification/hcl2/index.mdx

I came upon this error in one of your example of code in the docs.

doc(typo): technical typo in advertised example

---

.changelog/12050.txt
client/allocrunner/taskrunner/plugin_supervisor_hook.go
client/allocrunner/taskrunner/task_runner_hooks.go

Fixes https://github.com/hashicorp/nomad/issues/11874 The CSI specification says:
> The CO SHALL provide the listen-address for the Plugin by way of the `CSI_ENDPOINT` environment variable.
Note that plugins without filesystem isolation won't have the plugin dir bind-mounted to their alloc dir, but we can provide a path to the socket anyways. These still won't quite work until https://github.com/hashicorp/nomad/issues/11885 is complete.
I've also refactored to use an options struct for the plugin supervisor hook config. The parameter list was getting out of control and we use this pattern for similar task runner hooks (ex. template). That's in a second commit.

csi: provide `CSI_ENDPOINT` env var to plugins

---

.changelog/12051.txt
command/volume_deregister.go
command/volume_detach.go
command/volume_status_csi.go

Fixes https://github.com/hashicorp/nomad/issues/12005
The `volume detach`, `volume deregister`, and `volume status` commands
accept a prefix argument for the volume ID. Update the behavior on
exact matches so that if there is more than one volume that matches
the prefix, we should only return an error if one of the volume IDs is
not an exact match. Otherwise we won't be able to use these commands
at all on those volumes. This also makes the behavior of these commands
consistent with `job stop`.

CSI: volume cli prefix matching should accept exact match

---

client/allocrunner/alloc_runner_unix_test.go
client/allocrunner/taskrunner/service_hook.go
client/allocrunner/taskrunner/service_hook_test.go
client/allocrunner/taskrunner/task_runner_test.go

In certain task lifecycles the taskrunner service deregister call
could be called three times for a task that is exiting. Whilst
each hook caller of deregister has its own purpose, we should try
and ensure it is only called once during the shutdown lifecycle of
a task.
This change therefore tracks when deregister has been called, so
that subsequent calls are noop. In the event the task is
restarting, the deregister value is reset to ensure proper
operation.

client: track service deregister call so it's only called once.

---

scheduler/spread_test.go

This fixes a dropped `err` variable in the `scheduler` package.

scheduler: fix dropped test error

---

command/agent/config.go

Fixes: https://github.com/hashicorp/nomad/issues/12043
Note: There is an inconsistency throughout the codebase regarding `Reserveable` and `Reservable`

bug: merge ReservableCores in clientConfig

---

GNUmakefile

Since switching to `golangci-lint` we have set the `-j 1` flag, which
restricts the tool to using 1 CPU thread.
This PR removes the flag so `make check` takes less time on good
computers.
```
➜ golangci-lint | grep '\-j'
-j, --concurrency int           Concurrency (default NumCPU) (default 16)
```

build: allow golangci-lint to use more than 1 core

---

.changelog/12057.txt
client/allocrunner/taskrunner/plugin_supervisor_hook.go
client/allocrunner/taskrunner/task_runner_hooks.go
client/client.go
client/pluginmanager/csimanager/instance.go
plugins/csi/client.go
plugins/csi/client_test.go

Related to https://github.com/hashicorp/nomad/issues/11784. It doesn't fix it but makes debugging it more legible.
I've broken this up into mostly bite-sized commits for review.
---
Nomad communicates with CSI plugin tasks via gRPC. The plugin
supervisor hook uses this to ping the plugin for health checks which
it emits as task events. After the first successful health check the
plugin supervisor registers the plugin in the client's dynamic plugin
registry, which in turn creates a CSI plugin manager instance that has
its own gRPC client for fingerprinting the plugin and sending mount
requests.
If the plugin manager instance fails to connect to the plugin on its
first attempt, it exits. The plugin supervisor hook is unaware that
connection failed so long as its own pings continue to work. …

CSI: make gRPC client creation more robust

---

.changelog/12021.txt
client/taskenv/network.go
client/taskenv/network_test.go
website/content/docs/job-specification/network.mdx

This implements client side interpolation of the network.dns block to fix #11851.
Unit tests, changelog entry, and website docs have been added/updated.

interpolate network.dns block on client (fixes #11851)

---

.changelog/12034.txt
api/api.go
api/evaluations_test.go
command/agent/http.go
command/deployment_list.go
command/eval_list.go
go.mod
go.sum
nomad/deployment_endpoint.go
nomad/deployment_endpoint_test.go
nomad/eval_endpoint.go
nomad/eval_endpoint_test.go
nomad/state/filter_test.go
nomad/state/paginator.go
nomad/state/paginator_test.go
nomad/structs/errors.go
nomad/structs/structs.go
website/content/api-docs/deployments.mdx
website/content/api-docs/evaluations.mdx
website/content/docs/commands/deployment/list.mdx
website/content/docs/commands/eval/list.mdx

Add support for [`go-bexpr`](https://github.com/hashicorp/go-bexpr) filters to `/v1/evaluations` and `/v1/deployments`.
Detailed documentation and changelog entry will come in follow-up PRs where this pattern will be applied to other endpoints.
----------
Note to reviewers:
A [previous version](https://github.com/hashicorp/nomad/commit/e1c5dbd4ad686aab500ab3d1e003686e4dd9ee90) of this work had an attempt to use `go-memdb` indexes if possible when the filter expression was a simple equality check over [`namespace`](https://www.nomadproject.io/api-docs/evaluations#namespace) or [`prefix`](https://www.nomadproject.io/api-docs/evaluations#prefix), but I found some problems with that implementation.
For `prefix`, there are multiple ways to express that with `go-bexpr`. The most strict way is …

Add `go-bexpr` filters to evals and deployment list endpoints

---

helper/funcs.go
helper/funcs_test.go
nomad/state/state_store.go
nomad/structs/structs.go
scheduler/generic_sched.go
scheduler/generic_sched_test.go
scheduler/reconcile.go
scheduler/reconcile_test.go
scheduler/reconcile_util.go
scheduler/reconcile_util_test.go
scheduler/util.go

**Description**
This PR is a work in progress tracking against the long-running feature branch `f-disconnected-client-handling`.
It includes:
- New node status (`NodeStatusDisconnected`), new client status (`AllocClientStatusUnknown`), and a new eval trigger (`EvalTriggerMaxDisconnectTimeout`)
- Updates to the `taintedNodes` function to include disconnected nodes as part of the tainted set
- A new `MaxClientDisconnect` field on the `Allocation` struct for tracking how long an alloc is allowed to be disconnected
- `allocReconciler` changes to support allocs that can disconnect and reconnect without restarting
- `GenericScheduler` changes to add disconnects to the `NodeAllocation` set for upsert with new status `AllocClientStatusUnknown`
- `GenericScheduler` changes to add reconnects to …

reconciler: support disconnected clients

---

command/agent/deployment_endpoint.go
command/agent/eval_endpoint.go
command/agent/http.go
nomad/deployment_endpoint.go
nomad/deployment_endpoint_test.go
nomad/eval_endpoint.go
nomad/eval_endpoint_test.go
nomad/state/filter_test.go
nomad/state/paginator.go
nomad/state/paginator_test.go
nomad/structs/structs.go

This PR adds two main changes that are require to add filter, pagination, and sort to API list endpoints:
- move `OrderAscending` into `QueryOptions` so it's available to all endpoints. It also renames it just `Ascending` to match the name in `api`.
- allow the paginator `appendFunc` to return an error, which will halt pagination. [Some endpoints](https://github.com/hashicorp/nomad/blob/v1.2.6/nomad/job_endpoint.go#L1377-L1379) require additional data to construct the result, so they may return an error when fetching it.
This is an internal change, so no CHANGELOG required.

initial base work for implementing sorting and filter across API endpoints

---

GNUmakefile

I broke the build due to https://github.com/hashicorp/nomad/pull/12077 not using our workaround for GOPATH
2nd time I've been burned by https://discuss.circleci.com/t/gopath-is-set-to-multiple-directories/7174
Circle: 2 Seth: 0
```
BIN is /home/circleci/.go_workspace:/usr/local/go_workspace/bin
```
```
=== Failed
=== FAIL: command TestIntegration_Command_RoundTripJob (0.13s)
...
integration_test.go:57: 
Error Trace:	integration_test.go:57
Error:      	Expected nil, but got: &exec.Error{Name:"nomad", Err:(*errors.errorString)(0xc000129190)}
Test:       	TestIntegration_Command_RoundTripJob
integration_test.go:66: error running example.nomad: exec: "nomad": executable file not found in $PATH
```

build: BIN value must use single-path GOPATH value

---

.changelog/12011.txt
client/allocrunner/taskrunner/envoy_bootstrap_hook.go
client/allocrunner/taskrunner/envoy_bootstrap_hook_test.go

This PR modifies the Consul CLI arguments used to bootstrap envoy for
Connect sidecars to make use of '-proxy-id' instead of '-sidecar-for'.
Nomad registers the sidecar service, so we know what ID it has. The
'-sidecar-for' was intended for use when you only know the name of the
service for which the sidecar is being created.
The improvement here is that using '-proxy-id' does not require an underlying
request for listing Consul services. This will make make the interaction
between Nomad and Consul more efficient.
Closes #10452

connect: bootstrap envoy using -proxy-id

---

.changelog/11975.txt
client/allocrunner/taskrunner/envoy_bootstrap_hook.go

When Consul Connect just works, it's wonderful. When it doesn't work it
can be exceeding difficult to debug: operators have to check task
events, Nomad logs, Consul logs, Consul APIs, and even then critical
information is missing.
Using Consul to generate a bootstrap config for Envoy is notoriously
difficult. Nomad doesn't even log stderr, so operators are left trying
to piece together what went wrong.
This patch attempts to provide *maximal* context which unfortunately
includes secrets. **Secrets are always restricted to the secrets/
directory.** This makes debugging a little harder, but allows operators
to know exactly what operation Nomad was trying to perform.
What's added:
- stderr is sent to alloc/logs/envoy_bootstrap.stderr.0
- the CLI is written to secrets/.envoy_bootstrap.cmd
- …

connect: write envoy bootstrap debugging info

---

website/content/tools/autoscaling/plugins/target/aws-asg.mdx

docs update for PR https://github.com/hashicorp/nomad-autoscaler/pull/564 - the autoscaler agent no longer needs an AWS keypair if it's running on an EC2 instance with the appropriate IAM role attached to it.

Update autoscaler AWS ASG target docs: AWS keypair can be empty

---

client/client.go
client/client_test.go
nomad/heartbeat.go
nomad/node_endpoint.go
nomad/plan_apply.go
scheduler/reconcile.go

This PR includes several changes related to the newly added `NodeStatusDisconnected` and `AllocClientStatusUnknown` statuses. This PR targets multiple components, but none of the changes work safely without the rest. The purpose of each of the 4 commits is detailed below.
- If the `client` receives an allocation in the unknown state, it updates the server with the state from the `AllocRunner`. Changes are included in [`37d02d6`](https://github.com/hashicorp/nomad/pull/12086/commits/37d02d6242979396895ba36f8653f270a6d8b1a4) .
- If the `nodeHearbeater` detects that a `client` should transition to `NodeStatusDisconnected` rather than`NodeStatusDown`, it sends that status to the node endpoint's `UpdateStatus` function. `UpdateStatus` incorporates the new status when determining whether to …

disconnected clients: manage and integrate new node and allocations statuses

---

website/content/docs/drivers/docker.mdx

Update `mount` link to point to non-deprecated option.
Closes #12074

docs: update link to `mount` in Docker task driver

---

nomad/state/state_store_test.go

https://github.com/hashicorp/nomad/pull/12105 had a broken test hidden by a test flake. 😊

CSI: fix broken test

---

api/nodes.go

Detection of the full set of plugin capabilities was added in Nomad
1.1 for the volume creation workflow, but these were not added to the
API response for plugins.
Blocks showing caps in `plugin status -verbose` https://github.com/hashicorp/nomad/issues/10221
Nice-to-have for implementing topology in https://github.com/hashicorp/nomad/issues/7669

CSI: add missing plugin capabilities to api response

---

.changelog/12114.txt
nomad/state/state_store.go

Fixes https://github.com/hashicorp/nomad/issues/11758
If a plugin job fails before successfully fingerprinting the plugins,
the plugin will not exist when we try to delete the job. Tolerate
missing plugins.
---
```
$ nomad job stop -purge badplugin
==> 2022-02-23T16:02:06-05:00: Monitoring evaluation "c3b163b5"
2022-02-23T16:02:06-05:00: Evaluation triggered by job "badplugin"
==> 2022-02-23T16:02:07-05:00: Monitoring evaluation "c3b163b5"
2022-02-23T16:02:07-05:00: Evaluation status changed: "pending" -> "complete"
==> 2022-02-23T16:02:07-05:00: Evaluation "c3b163b5" finished with status "complete"
$ nomad job status badplugin
No job(s) with prefix or id "badplugin" found
```

CSI: tolerate missing plugins on job delete

---

.changelog/12107.txt
.golangci.yml
client/state/state_database.go
client/state/upgrade.go
client/state/upgrade_int_test.go
client/state/upgrade_test.go
command/agent/agent.go
command/agent/config.go
command/raft_tools/state.go
go.mod
go.sum
helper/boltdd/boltdd.go
helper/boltdd/boltdd_test.go
helper/raftutil/fsm.go
helper/raftutil/state.go
helper/raftutil/state_test.go
nomad/config.go
nomad/server.go
website/content/docs/configuration/server.mdx
website/content/docs/operations/metrics-reference.mdx
website/content/docs/upgrade/upgrade-specific.mdx

This PR swaps the underlying BoltDB implementation from boltdb/bolt
to go.etc.io/bbolt. Applies to both server raft store and client data store.
In addition, the Server has a new configuration option for disabling
NoFreelistSync on the underlying database.
Freelist option: https://github.com/etcd-io/bbolt/blob/master/db.go#L81
Consul equivelent PR: https://github.com/hashicorp/consul/pull/11720
Closes https://github.com/hashicorp/nomad/issues/11775

core: swap bolt impl and enable configuring raft freelist sync behavior

---

.changelog/11807.txt
api/namespace.go
command/namespace_apply.go
command/namespace_list.go
command/namespace_status.go
nomad/job_endpoint.go
nomad/job_endpoint_validators.go
nomad/job_endpoint_validators_test.go
nomad/structs/structs.go
website/content/docs/commands/namespace/apply.mdx
website/content/docs/commands/namespace/status.mdx

Looks good so far:
```
➜  nomad git:(main) ✗ ./bin/nomad namespace list                                         
Name     Description               Drivers
default  Default shared namespace  *
test     <none>                    docker,test
➜  nomad git:(main) ✗ ./bin/nomad job plan test.nomad                                    
Error during plan: Unexpected response code: 500 (1 error occurred:
* used task driver 'lala' in cache[redis] is not allowed in namespace test
```
@tgross Do you mind giving it an initial quick review -- if I am on the right track I will continue with it.
Refs #11807

Intial implementation for #11807

---

.changelog/12084.txt
command/agent/config.go
go.mod
go.sum
nomad/structs/config/consul.go
nomad/structs/config/consul_test.go
website/content/docs/configuration/consul.mdx

This PR adds support for go-sockaddr/template in the [consul address Stanza](https://www.nomadproject.io/docs/configuration/consul#address).
As noted in the issue, this becomes especially useful when you want to pair your nomad agent to the consul private network agent in a dynamic fashion.
Fixes: #11062
A check has been added to only support one single IP in the Stanza, as was done in other places using `ParseSingleIPTemplate`. However, I think in the years Hashicorp defines this in their shared package: https://github.com/hashicorp/go-secure-stdlib/blob/7166b1cdf6a6eb1311247e34feae17eaf7b657bf/listenerutil/parse.go#L374
Adding an extra dependency to the repo of [go-secure-stdlib](https://github.com/hashicorp/go-secure-stdlib) might not be something preferable. If this is still …

feature(config): Add go-sockaddr templating support to nomad consul address

---

.changelog/12112.txt
nomad/csi_endpoint_test.go
nomad/structs/csi.go

When the scheduler checks feasibility for CSI volumes, the check is
fairly loose: earlier versions of the same job are not counted as
active claims. This allows the scheduler to place new allocations
for the new version of a job, under the assumption that we'll replace
the existing allocations and their volume claims.
But when the alloc runner claims the volume, we need to enforce the
active claims even if they're for allocations of an earlier version of
the job. Otherwise we'll try to mount a volume that's currently being
unmounted, and this will cause replacement allocations to frequently
fail.
This changeset corrects this behavior for both write claims and read 
claims. I've broken it across a small set of commits for clarity.
---
Partial fix for …

CSI: enforce usage at claim time

---

.changelog/12113.txt
client/allocrunner/csi_hook.go
client/allocrunner/csi_hook_test.go

Fixes https://github.com/hashicorp/nomad/issues/8609 when combined with https://github.com/hashicorp/nomad/pull/12112
Fixes https://github.com/hashicorp/nomad/issues/11477
When the alloc runner claims a volume, an allocation for a previous
version of the job may still have the volume claimed because it's
still shutting down. In this case we'll receive an error from the
server. Retry this error until we succeed or until a very long timeout
expires, to give operators a chance to recover broken plugins.
Make the claim hook tolerate temporary RPC failures in general to
prevent errors during client restart or during leadership elections.
---
(Tests don't pass until #12112 is merged; I'll rebase this on that PR)

CSI: retry claims from client

---

website/content/tools/autoscaling/policy.mdx

Document the new configuration added in https://github.com/hashicorp/nomad-autoscaler/pull/566

docs: add docs for the autoscaler `on_error` and `on_check_error` configuration

---

.changelog/12116.txt
command/plugin_status_csi.go

Fixes https://github.com/hashicorp/nomad/issues/10221
The behaviors of CSI plugins are governed by their capabilities as
defined by the CSI specification. When debugging plugin issues, it's
useful to know which behaviors are expected so they can be matched
against RPC calls made to the plugin allocations.
Expose the plugin capabilities as named in the CSI spec in the 
`nomad plugin status -verbose` output.

CSI: display plugin capabilities in verbose status

---

command/agent/csi_endpoint.go

In PR #12108 we added missing fields to the plugin response, but we
didn't include the manual serialization steps that we need until
issue #10470 is resolved.
(We should almost certainly have a bunch of testing to ensure that we're mapping structs->api structs correctly, but I'd rather fix this particular case with #10470 but that's not in the scope for blocking 1.3.0)

CSI: ensure all fields are mapped from structs to api response

---

website/package-lock.json
website/package.json

👀 [Preview][preview]
This PR bumps to the latest `@hashicorp/react-docs-page` release, in order to fix an underlying issue in `@hashicorp/react-code-block` (via `@hashicorp/platform-docs-mdx`).
This fix is specific to Firefox browsers, and with this fix, newlines are now included when manually selecting and copying `code-block` contents.
See https://github.com/hashicorp/react-components/pull/503 for further details.
When using [Firefox](https://www.mozilla.org/en-US/firefox/new/):
- On [the live site][live], manually selecting code block contents, copying, and pasting into a plain text editor should result in missing newlines.
- On [the preview][preview], manually selecting code block contents, copying, and pasting into a plain text editor should result in the expected content, with …

chore: bump docs-page for code-block fix

---

.changelog/12130.txt
go.mod
go.sum
nomad/rpc.go
nomad/serf_test.go

This PR
- upgrades the serf library
- has the test start the join process using the un-joined server first
- disables schedulers on the servers
- uses the WaitForLeader and wantPeers helpers
Not sure which, if any of these actually improves the flakiness of this test.
Closes https://github.com/hashicorp/nomad/issues/12115 ... hopefully :cat2:

tests: deflake test that joins a server with non-voting servers to form quorum

---

website/content/docs/configuration/index.mdx

The `advertise.rpc` config option is not intuitive. At first glance you'd
assume it works like `advertise.http` or `advertise.serf`, but it does not.
The current behavior is working as intended, but the documentation is
very hard to parse and doesn't draw a clear picture of what the setting
actually does.
Closes https://github.com/hashicorp/nomad/issues/11075

docs: clairfy advertise.rpc effect

---

website/pages/api-docs/[[...page]].jsx
website/pages/docs/[[...page]].jsx
website/pages/intro/[[...page]].jsx
website/pages/plugins/[[...page]].tsx
website/pages/tools/[[...page]].tsx

This fixes a bug on the UI where the version select is being incorrectly displayed for `/plugins` and `/tools`

fix(website): hide version select on `/plugins` & `/tools`

---

.changelog/12153.txt
command/volume_deregister.go
command/volume_detach.go
command/volume_status.go
command/volume_status_csi.go

Fixes https://github.com/hashicorp/nomad/issues/11964

CSI: respect -verbose flag for allocs in volume status

---

.changelog/12150.txt
command/agent/csi_endpoint.go

Fixes https://github.com/hashicorp/nomad/issues/9825
The `volume status` command and associated API redacts the entire
mount options instead of just the `MountFlags` field that can contain
sensitive data. Return a redacted value so that the return value makes
sense to operators who have set this field.

CSI: fix redaction of `volume status` mount flags

---

.changelog/12144.txt
api/api.go
api/csi.go
command/agent/csi_endpoint.go
command/agent/csi_endpoint_test.go
command/volume_snapshot_delete.go
command/volume_snapshot_list.go
website/content/docs/commands/volume/snapshot-delete.mdx
website/content/docs/commands/volume/snapshot-list.mdx

Fixes https://github.com/hashicorp/nomad/issues/11308
Unblocks https://github.com/hashicorp/nomad/issues/10997 https://github.com/hashicorp/nomad/pull/11245
* Use a header for passing the CSI secrets rather than querystring params. 
* Deprecate the existing (*CSIVolumes) ListSnapshots()` HTTP API method.
* Updates the CLI for consistency across uses of the `-secret` flag.

CSI: use HTTP headers for passing CSI secrets

---

client/allocrunner/taskrunner/plugin_supervisor_hook.go

The Prestart hook for task runner hooks doesn't get called when we
restore a task, because the task is already running. The Postrun hook
for CSI plugin supervisors needs the socket path to have been
populated so that the client has a valid path.
---
This got missed in testing https://github.com/hashicorp/nomad/pull/12078, I suspect because I was testing a lot with node plugins running as system jobs which quickly get replaced if you're not paying close attention. In any case, that PR hasn't shipped in a release yet, so there's no changelog. It'll need to be backported with that changeset.

CSI: set plugin socket path on restore

---

command/commands.go
command/volume_snapshot.go

The `nomad volume snapshot` subcommand wasn't defined, which left an unpolished blank spot in the help text if you ran `nomad volume`

CSI: subcommand for volume snapshot

---

api/evaluations_test.go
nomad/deployment_endpoint.go
nomad/deployment_endpoint_test.go
nomad/eval_endpoint.go
nomad/eval_endpoint_test.go
nomad/state/filter_test.go
nomad/state/paginator.go
nomad/state/paginator_test.go
nomad/state/schema.go
nomad/structs/structs.go

The paginator logic was built when go-memdb iterators would return items
ordered lexicographically by their ID prefixes, but #12054 added the
option for some tables to return results ordered by their `CreateIndex`
instead, which invalidated the previous paginator assumption.
The iterator used for pagination must still return results in some order
so that the paginator can properly handle requests where the next_token
value is not present in the results anymore (e.g., the eval was GC'ed).
In these situations, the paginator will start the returned page in the
first element right after where the requested token should've been.
This commit moves the logic to generate pagination tokens from the
elements being paginated to the iterator itself so that callers can have
more control over the token …

api: paginated results with different ordering

---

api/tasks.go
client/allocrunner/alloc_runner.go
client/allocrunner/alloc_runner_test.go
client/allocrunner/testing.go
client/client.go
client/interfaces/client.go
command/alloc_status.go
nomad/structs/structs.go
nomad/structs/structs_test.go
scheduler/generic_sched.go

This PR introduces a new `TaskClientReconnected` task event. This task event will be appended by the `allocRunner` each time an unknown alloc is reconnected after the `client` comes back online.
This PR includes:
- The changes related to defining the `TaskEvent` and translating it to meaningful human text for display.
- Refactors the reconnect logic out of the `client` and into the `allocRunner` as it has grown in scope. Specifically, the logic workflow is now:
- Appends a task event entry for allocs still running on the `client`.
-  Updates the existing alloc instance with the indexes from the incoming update.
- Recomputes task states with new events.
- Calls `clientAlloc` to compute the current alloc state including the appended events.
- Updates the `client` state store with the …

disconnected clients: Add reconnect task event

---

client/allocrunner/alloc_runner_test.go

I looked at the wrong CircleCI notification and missed that these tests were failing before merging.
- Refactor failing test
- Remove no longer necessary guard test

Fix client test reconnect test; Remove guard test

---

.semgrep/go_tests.yml

These rules have resulted in too many false positives that are confusing and interfere with development flow. I didn't find a way to disable specific rules with the semgrep GitHub Action, so I'm just excluding all paths instead.

ci: disable Go test semgrep rules

---

.changelog/12178.txt
command/agent/csi_endpoint.go

The HTTP endpoint for CSI manually serializes the internal struct to
the API struct for purposes of redaction (see also #10470). Add fields
that were missing from this serialization so they don't show up as
always empty in the API response.
Found these while testing https://github.com/hashicorp/nomad/pull/12167
That PR won't get backported but we'll want this one to be.

CSI: add missing fields to HTTP API response

---

e2e/networking/inputs/validate.sh

With mTLS enabled in nightly E2E as of bfac8d8, using `curl` in a bash 
script for validation involves having to configure arguments to `curl` 
based  on whether or not the test infrastructure is using mTLS, whether 
ACLs are enabled, etc. Use the new `operator api` command instead to
pick up the client configuration from the test environment automatically.

e2e: use `operator api` for Networking suite validation

---

.changelog/12184.txt
nomad/csi_endpoint.go
nomad/csi_endpoint_test.go
nomad/state/state_store.go

When using a prefix value and the * wildcard for namespace, the endpoint
would not take the prefix value into consideration due to the order in
which the checks were executed but also the logic for retrieving volumes
from the state store.
This commit changes the order to check for a prefix first and wraps the
result iterator of the state store query in a filter to apply the
prefix.

Fix CSI volume list with prefix and `*` namespace

---

helper/ipaddr/ipaddr.go
helper/ipaddr/ipaddr_test.go
nomad/alloc_endpoint.go
nomad/alloc_endpoint_test.go
nomad/fsm.go
nomad/fsm_test.go
nomad/job_endpoint.go
nomad/job_endpoint_test.go
nomad/rpc_test.go
nomad/server.go
nomad/service_registration_endpoint.go
nomad/service_registration_endpoint_test.go
nomad/structs/alloc.go
nomad/structs/alloc_test.go
nomad/structs/job.go
nomad/structs/job_test.go
nomad/structs/service_registration.go
nomad/structs/service_registration_test.go

This PR adds the RPC logic for service discovery. This includes a new endpoint as well as updates to the alloc and job endpoints to provide easy lookup of registrations associated to these objects.
The new `ServiceRegistration` endpoint is static/dynamic to ensure the `Upsert` RPC, which is only callable via client agent, includes TLS verification. It also includes functionality for wildcard listing as is common across all list endpoint within Nomad.
The `ipaddr` package mirrors Consul and ensure no service is registered which has an any IP address and therefore is not logically routable outside its local instance.
Apologies for the size, although I believe at least 60% of the additions are tests. The PR is split into commits which group the additions into logical chunks and hope to make …

service discovery: add RPC endpoints and FSM logic

---

api/allocations.go
api/allocations_test.go
api/jobs.go
api/jobs_test.go
api/service_registrations.go
api/service_registrations_test.go
command/agent/alloc_endpoint.go
command/agent/alloc_endpoint_test.go
command/agent/http.go
command/agent/job_endpoint.go
command/agent/job_endpoint_test.go
command/agent/service_registration_endpoint.go
command/agent/service_registration_endpoint_test.go

This work continues to build out the service discovery feature by adding the HTTP and Go SDK covering all the publicly available RPC endpoints. This includes a new endpoint as well as updates to the alloc and job endpoints to provide easy lookup of registrations associated to these objects.
The PR is split into commits which group the additions into logical chunks and hope to make it easier to review.
closes https://github.com/hashicorp/team-nomad/issues/262

service discovery: add HTTP endpoints and sdk wrapper

---

api/csi.go

When we set the headers for CSI secrets in the `WriteOptions`, it
turns out that we're not always passing a non-nil object. In that
case, instantiate it on demand in the API.
This slipped in with https://github.com/hashicorp/nomad/pull/12178 but got caught by E2E.

csi: ensure `WriteOptions` aren't nil when handling secrets

---

e2e/metrics/input/prometheus.nomad
e2e/terraform/config/dev-cluster/nomad/client-linux/client.hcl
e2e/terraform/config/full-cluster/nomad/client-linux/indexed/client-0.hcl
e2e/terraform/config/full-cluster/nomad/client-linux/indexed/client-1.hcl
e2e/terraform/config/full-cluster/nomad/client-linux/indexed/client-2.hcl
e2e/terraform/config/full-cluster/nomad/client-linux/indexed/client-3.hcl

The `Metrics` suite uses prometheus to scrape Nomad metrics so that
we're testing the full user experience of extracting metrics from
Nomad. With the addition of mTLS, we need to make sure prometheus also
has mTLS configuration because the metrics endpoint is protected.
Update the Nomad client configuration and prometheus job to bind-mount
the client's certs into the task so that the job can use these certs
to scrape the server. This is a temporary solution that gets the job
passing; we should give the job its own certificates (issued by
Vault?) when we've done some of the infrastructure rework we'd like.
---
Temporary hack for https://github.com/hashicorp/nomad/issues/11484 but I'm going to leave that open with a note to complete the infra work required here.

e2e: configure prometheus for mTLS for `Metrics` suite

---

e2e/e2eutil/job.go

The `TestRescheduleProgressDeadlineFail` E2E test failed during test
cleanup because the error message "progress deadline expired" that it
emits when we stop the job does not match the one expected from
monitoring the `job stop` command. Update the `StopJob` helper 
introduced in c2b5a5e to tolerate this use case as well.

e2e: `StopJob` should tolerate progress deadline expired

---

e2e/csi/csi.go
e2e/e2eutil/cli.go
e2e/e2eutil/job.go
e2e/vaultsecrets/vaultsecrets.go

If any E2E test hangs, it'll eventually timeout and panic, causing the
all the remaining tests to fail. External commands should use a short
context whenever possible so we can fail the test quickly and move on
to the next test.
(Example recent workflow where this happened: [ref](https://app.circleci.com/pipelines/github/hashicorp/nomad-e2e/419/workflows/1f7bd133-519e-4d13-a696-d6ef975a1cf3/jobs/2398))

e2e: use context for executing external commands

---

nomad/leader.go
nomad/state/state_store.go
nomad/state/state_store_test.go
nomad/structs/structs.go
scheduler/reconcile.go
website/content/docs/operations/metrics-reference.mdx

**NOTE TO REVIEWER**: Converting this back to draft, as it makes sense to include the `TaskGroupSummary` changes in this batch of commits.
This PR contains three changes. 
- It adds `disconnect` & `reconnect` to the `GoString` implementation for `reconcileResults` so that the count of these 
maps will be included in log output.
- It adds a call to `emitRescheduleInfo` in `createTimeoutLaterEvals` so that metrics will now include reschedule metrics for disconnects.
- Adds an `Unknown` field to the `TaskGroupSummary` struct and includes that value in all related processing and metrics.

disconnected clients: Observability plumbing

---

api/tasks.go
command/agent/job_endpoint.go
command/agent/job_endpoint_test.go
nomad/structs/diff.go
nomad/structs/diff_test.go
nomad/structs/structs.go
nomad/structs/structs_test.go
website/content/api-docs/jobs.mdx

* New fields should be added to existing Canonicalize, Copy methods
* Test the structs/fields via methods mentioned above

`MaxClientDisconnect` Jobspec checklist

---

.changelog/12194.txt
command/plugin_status_csi.go
nomad/csi_endpoint.go
nomad/csi_endpoint_test.go
nomad/state/state_store.go

The `CSIPlugin.List` RPC was intended to accept a prefix to filter the
list of plugins being listed. This was being accidentally being done
in the state store instead, which contributed to incorrect filtering
behavior for plugins in the `volume plugin status` command.
Move the prefix matching into the RPC so that it calls the
prefix-matching method in the state store if we're looking for a
prefix.
Update the `plugin status command` to accept a prefix for the plugin
ID argument so that it matches the expected behavior of other commands.
---
I pulled this out of https://github.com/hashicorp/nomad/pull/12193 because this will need to be backported, whereas not everything in that PR should be.

CSI: fix prefix queries for `plugin status`

---

.changelog/12195.txt
nomad/csi_endpoint.go
nomad/csi_endpoint_test.go

The `CreateSnapshot` RPC expects a plugin ID to be set by the API, but
in the common case of the `nomad volume snapshot create` command, we
don't ask the user for the plugin ID because it's available from the
volume we're snapshotting.
Change the order of the RPC so that we get the volume first and then
use the volume's plugin ID for the plugin if the API didn't set the
value.
---
Pulled out of https://github.com/hashicorp/nomad/pull/12193 because this will need backporting.

CSI: get plugin ID for creating snapshot from volume, not args

---

nomad/plan_apply.go

The changes from [8f2fa49](https://github.com/hashicorp/nomad/commit/8f2fa49ae0788c2e58c6b5d3a29be252a43371cd) weren't actually required as the client will request its allocations when it reconnects.

Remove changes to `evaluateNodePlan`

---

.changelog/12197.txt
command/volume_snapshot_list.go
e2e/csi/ebs.go
website/content/docs/commands/volume/snapshot-list.mdx

The RPC for listing volume snapshots requires a plugin ID. Update the
`volume snapshot list` command to find the specific plugin from the
provided prefix.
---
Pulled out of https://github.com/hashicorp/nomad/pull/12193

CSI: volume snapshot list plugin option is required

---

.changelog/12193.txt
command/volume_snapshot_list.go
e2e/csi/ebs.go
website/content/docs/commands/volume/snapshot-list.mdx

The snapshot list API supports pagination as part of the CSI
specification, but we didn't have it plumbed through to the command
line.
This also breaks E2E testing because the output from the AWS EBS plugin
can be extremely long without pagination, bringing the time it takes to
complete the command above the test timeout.
---
This PR requires bugfixes in https://github.com/hashicorp/nomad/pull/12194 https://github.com/hashicorp/nomad/pull/12195 and https://github.com/hashicorp/nomad/pull/12197, and currently includes those commits. It'll be rebased once those get merged.

CSI: snapshot list pagination parameters

---

.changelog/12138.txt
api/namespace.go
command/agent/namespace_endpoint_test.go
command/namespace_apply.go
command/namespace_apply_test.go
command/namespace_delete_test.go
command/namespace_inspect_test.go
command/namespace_list_test.go
command/namespace_status.go
command/namespace_status_oss_test.go
command/namespace_status_test.go
nomad/mock/mock.go
nomad/structs/structs.go
website/content/api-docs/namespaces.mdx
website/content/docs/commands/namespace/apply.mdx
website/content/docs/commands/namespace/status.mdx

This PR adds a metadata field to the namespace objects allowing users to attach custom data to namespaces.
Fixes #9631

Add metadata to namespaces

---

nomad/util_test.go
nomad/worker.go
scheduler/generic_sched.go
scheduler/reconcile.go
scheduler/reconcile_test.go
scheduler/reconcile_util.go
scheduler/reconcile_util_test.go
scheduler/scheduler.go
scheduler/testing.go

**Note for Reviewer**: This is a pragmatic compromise that might need discussion. 
- The `CoreScheduler` has a direct reference to the `nomad.Server` and thus its members and is responsible for 
performing server version checks for core jobs.
- Initially, I tried exposing this functionality via the `Scheduler` interface, however, the `GenericScheduler` cannot have a 
direct reference to the `nomad.Server` because it is in the `scheduler` package and that creates an import cycle.
- The `Worker` fulfills the `Planner` interface, is made available to the `GenericScheduler` by that interface, and also 
has a reference to the `nomad.Server`. So the `Planner` interface was extended instead.
This PR contains the logic necessary to ensure clusters running mixed version servers do not enable the …

disconnected clients: ensure servers meet minimum required version

---

website/content/docs/job-specification/affinity.mdx

Make the examples match the affinity operator being documented.

docs: fix examples for set_contains_all and set_contains_any

---

website/content/docs/drivers/docker.mdx

Fixes https://github.com/hashicorp/nomad/issues/11857 https://github.com/hashicorp/nomad/issues/11239
The Docker DNS configuration options are not compatible with a
group-level network in `bridge` mode. Warn users about this in the
Docker task configuration docs.

docs: add note about docker DNS config when using bridge mode

---

nomad/csi_endpoint_test.go

#12167 renamed `CSIVolumeRegister` but I forgot to pull that change before merging #12186

fix CSI volume list test

---

nomad/job_endpoint.go

The `Job.List` RPC attaches a `JobSummary` to each job stub. We're
using the request namespace and not the job namespace for that query,
which results in a nil `JobSummary` whenever we pass the wildcard
namespace. This is incorrect and causes panics in downstream consumers
like the CLI, which assume the `JobSummary` is non-nil as an unstated
invariant.

job summary query in `Job.List` RPC should use job's namespace

---

plugins/drivers/testutils/testing.go

The default chroot copies all of /bin, /usr, etc. which can ammount
to gigabytes of stuff not actually needed for running our tests.
Use a smaller chroot in test cases so that CI infra with poor disk
IO has a chance.

testing: use a smaller chroot when running exec driver tests

---

website/content/api-docs/jobs.mdx

https://github.com/hashicorp/nomad/issues/12038 added ACL requirements to the job parse endpoint to prevent potential abuse via malformed jobs.
Since job ACLs are attached to namespaces, and the token is checked before the job data is parsed to avoid abuse, the request must contain a `namespace` query param that the token is allowed to access.

docs: add namespace param to job parse API

---

nomad/acl_endpoint.go
nomad/alloc_endpoint.go
nomad/deployment_endpoint.go
nomad/eval_endpoint.go
nomad/leader.go
nomad/node_endpoint_test.go
nomad/search_endpoint.go
nomad/state/state_store.go
nomad/state/state_store_test.go
website/content/api-docs/acl-tokens.mdx
website/content/api-docs/allocations.mdx
website/content/api-docs/deployments.mdx
website/content/api-docs/evaluations.mdx

The `reverse` query parameter uses `GetReverse` to traverse the go-memdb table in the opposite order. Initially (https://github.com/hashicorp/nomad/pull/12186) this was used to return results in ascending or descending chronological order, but since this was only possible in some situations where the table schema allowed the `reverse` query parameter would only work in some specific combination of query parameters.
Given that there is no inherit meaning in using `Get` or `GetReverse` (they are just opposite orders to traverse results) the `reverse` query parameter can actually be used in most situations.
This PR adds the `sort` argument to state store functions used by the list endpoints that have been updated so far. If `sort` is `SortReverse`, the `GetReverse` method is used and results …

api: apply consistent behaviour of the reverse query parameter

---

api/jobs_test.go
api/services.go
api/services_test.go
command/agent/job_endpoint.go
command/agent/job_endpoint_test.go
jobspec/parse_service.go
jobspec/parse_test.go
jobspec/test-fixtures/service-provider.hcl
nomad/structs/consul.go
nomad/structs/diff_test.go
nomad/structs/services.go
nomad/structs/services_test.go
nomad/structs/structs.go
nomad/structs/structs_test.go

This PR adds a new parameter to the service block named `provider`. This dictates which service registration provider to use and defaults to `consul` maintaining the current implementation default. The parameter can also be `nomad`; any other value will result in an error being returned to the user upon job registration or similar.
The validation of services now includes specific validations depending on the provider configuration parameter. The MVP also only allows a single provider to be used per task group.
closes https://github.com/hashicorp/team-nomad/issues/264

jobspec: add service block provider parameter

---

client/config/config.go
command/agent/agent.go
command/agent/agent_test.go
command/agent/config.go
command/agent/config_test.go

This adds a boolean configuration parameter giving operators the ability to enable/disable clients from utilising the Nomad native service discovery feature.
closes https://github.com/hashicorp/team-nomad/issues/261

config: add native service discovery admin boolean parameter.

---

client/fingerprint/nomad.go
client/fingerprint/nomad_test.go
nomad/job_endpoint_hooks.go
nomad/job_endpoint_hooks_test.go
nomad/structs/job.go
nomad/structs/job_test.go

This change adds a new client parameter which allows operators to control whether the client can utilise the native service discovery feature. This will default to true, meaning the feature is enabled. This configuration value is exported as a fingerprinted attribute under the meta partition.
In order to ensure allocations are only placed on clients which have the feature enabled, when using `provider = nomad` the job group is mutated to contain a constraint. This mutator mimics the current Vault mutator.
closes https://github.com/hashicorp/team-nomad/issues/265

service discovery: add config boolean parameter and fingerprinting

---

scheduler/generic_sched.go
scheduler/reconcile.go

When assessing the event stream for disconnected client events, I found that allocations that are stopped due to a reconnect had a description indicating the alloc was stopped because the jobspec had changed, which is inaccurate.  This PR adds a description so that the stop reason is accurate when an allocation is stopped due to a reconnect event.

Add description for allocs stopped due to reconnect

---

website/content/docs/job-specification/restart.mdx

Fixes https://github.com/hashicorp/nomad/issues/12250 https://github.com/hashicorp/nomad/issues/12017
Clarify the behavior of `restart` inheritance with respect to Connect
sidecar tasks. Remove incorrect language about the scheduler being
involved in restart decisions. Try to make the `delay` mode
documentation more clear, and provide examples of delay vs fail.
Preview: https://nomad-a7l4md20c-hashicorp.vercel.app/docs/job-specification/restart

docs: clarify `restart` inheritance and add examples

---

nomad/alloc_endpoint_test.go

The alloc list test with pagination was creating allocs before the
target namespace existed. This works in OSS but fails in ENT because
quotas are checked before the alloc can be created, so the namespace
must exist beforehand.
Test before and after the fix:
```console
$ go test -tags ent,consulent -run TestAllocEndpoint_List_PaginationFiltering ./nomad
[INFO] freeport: detected ephemeral port range of [49152, 65535]
--- FAIL: TestAllocEndpoint_List_PaginationFiltering (0.35s)
alloc_endpoint_test.go:146:
Error Trace:    alloc_endpoint_test.go:146
Error:          Received unexpected error:
updating quota usage failed: allocation "aaaaaa33-3350-4b4b-d185-0e1992ed43e9" is in non-existent namespace "non-default"
Test:           TestAllocEndpoint_List_PaginationFiltering
FAIL
FAIL …
```

fix alloc list test

---

client/serviceregistration/wrapper/wrapper.go
client/serviceregistration/wrapper/wrapper_test.go

The service registration wrapper handles sending requests to
backend providers without the caller needing to know this
information. This will be used within the task and alloc runner
service hooks when performing service registration activities.
related https://github.com/hashicorp/team-nomad/issues/266

client: add service registration wrapper to handle providers.

---

.changelog/12305.txt
api/evaluations.go
api/evaluations_test.go
command/agent/eval_endpoint.go
command/agent/eval_endpoint_test.go
nomad/eval_endpoint.go
nomad/eval_endpoint_test.go
nomad/state/state_store.go
nomad/state/state_store_test.go
nomad/structs/structs.go
website/content/api-docs/evaluations.mdx

The `related` query param is used to indicate that the request should
return a list of related (next, previous, and blocked) evaluations.
Closes #11858

api: add related evals to eval details 

---

.changelog/12317.txt
command/server_members.go
command/server_members_test.go
website/content/docs/commands/server/members.mdx
website/content/docs/upgrade/upgrade-specific.mdx

The previous output of the `nomad server members` command would output a
column named `Protocol` that displayed the Serf protocol being currently
used by servers.
This is not a configurable option, so it holds very little value to
operators. It is also easy to confuse it with the Raft Protocol version,
which is configurable and highly relevant to operators.
This commit replaces the previous `Protocol` column with the new `Raft
Version`. It also updates the `-detailed` flag to be called `-verbose`
so it matches other commands. The detailed output now also outputs the
same information as the standard output with the addition of the
previous `Protocol` column and `Tags`.

cli: display Raft version in `server members`

---

api/operator_ent_test.go

The `api/testutil` package was moved to `api/internal/testutil` but
this wasn't caught in the ENT tests because they're not run here in
the OSS repo.

api: fix ENT-only test imports for moved testutil package

---

.circleci/config.yml
GNUmakefile
command/agent/testagent.go
helper/testlog/testlog.go
nomad/testing.go

Part 2 of breaking up https://github.com/hashicorp/nomad/pull/12255
This PR makes it so `gotestsum` is invoked only in CircleCI. Also the
`HCLogger(t)` is plumbed more correctly in `TestServer` and `TestAgent` so
that they respect `NOMAD_TEST_LOG_LEVEL`.
The reason for these is we'll want to disable logging in GHA,
where spamming the disk with logs drags performance.
Also upgrade `gotestsum` while we're here.

ci: limit gotestsum to circle ci

---

.github/workflows/test-core.yaml
GNUmakefile
scripts/update_golang_version.sh

This is part 3 of breaking up https://github.com/hashicorp/nomad/pull/12255
Start running CI on GHA! But not the packages that currently assume cgroups v1. These will be turned back on in the cgroups v2 PR.

ci: turn on testing in github actions

---

e2e/connect/acls.go

The `ConnectACLsE2ETest` checks that the SI tokens have been properly
cleaned up between tests, but following the change to use HCP the
previous `Connect` test suite will often have SI tokens that haven't
been cleaned up by the time this test suite runs. Wait for the SI
tokens to be cleaned up at the start of the test to ensure we have a
clean state.
----
The longer-term fix for this might be something like https://github.com/hashicorp/nomad/issues/12316 but for now this will get nightly green again. Test run with Nomad ENT binaries, showing that we're now waiting for the SI tokens to be cleaned up before proceeding:
```
$ go test -v .
=== RUN   TestE2E/Affinity
=== RUN   TestE2E/Affinity/*affinities.BasicAffinityTest
=== RUN …
```

E2E: ensure `ConnectACLsE2ETest` has clean state before starting

---

client/allocrunner/taskrunner/plugin_supervisor_hook.go
demo/csi/ceph-csi-plugin/README.md
demo/csi/cinder-csi-plugin/README.md
demo/csi/cinder-csi-plugin/cinder-csi-plugin.hcl
demo/csi/digitalocean/plugin.nomad
demo/csi/hostpath/plugin.nomad
e2e/csi/input/plugin-aws-ebs-controller.nomad
e2e/csi/input/plugin-aws-ebs-nodes.nomad
e2e/csi/input/plugin-aws-efs-nodes.nomad

From https://github.com/hashicorp/nomad/issues/12118#issuecomment-1064501769
* Some plugins have strict validation over the format of the `CSI_ENDPOINT` variable, and unfortunately not all plugins agree. Allow the user to override the `CSI_ENDPOINT` to workaround those cases.
* Use `unix://` prefix for the `CSI_ENDPOINT` variable, which is typically what plugins are looking for.
* Update examples and tests to use `CSI_ENDPOINT` env var interpolation
* Upgrade EFS test plugin image

CSI: set plugin `CSI_ENDPOINT` env var only if unset by user

---

client/allocrunner/alloc_runner.go
client/allocrunner/alloc_runner_hooks.go
client/allocrunner/alloc_runner_test.go
client/allocrunner/alloc_runner_unix_test.go
client/allocrunner/config.go
client/allocrunner/groupservice_hook.go
client/allocrunner/groupservice_hook_test.go
client/allocrunner/taskrunner/script_check_hook_test.go
client/allocrunner/taskrunner/service_hook.go
client/allocrunner/taskrunner/service_hook_test.go
client/allocrunner/taskrunner/task_runner.go
client/allocrunner/taskrunner/task_runner_hooks.go
client/allocrunner/taskrunner/task_runner_test.go
client/allocrunner/testing.go
client/client.go
client/serviceregistration/wrapper/wrapper.go
client/serviceregistration/wrapper/wrapper_test.go
command/agent/agent.go
command/agent/consul/int_test.go
nomad/structs/alloc.go
nomad/structs/alloc_test.go

This PR modifies the client task and alloc runners to utilise the new service registration wrapper. The service hooks have also been updated to use the wrapper along with some naming improvements which were previously Consul specific.
In order to handle a test case, the wrapper has been slightly modified. The function has a comment which details this change. Additional testing via table driven test should be added in the future.
closes https://github.com/hashicorp/team-nomad/issues/266

client: hookup service wrapper for use in clients

---

command/agent/csi_endpoint.go
command/plugin_status_csi.go
command/volume_status.go
nomad/state/state_store.go

Fixes https://github.com/hashicorp/nomad/issues/12073 and other fit-and-finish wobbles.
* Sort allocations for CSI plugins in the state store so they show up nice in `nomad plugin status :id`
* Sort allocations for CSI volumes in the HTTP server so they show up nice in `nomad volume status :id` (this has to be done here because the allocations list in the API response is a merge of 2 lists from the state store)
* Fix sorting of CSI plugins capabilities introduced in https://github.com/hashicorp/nomad/pull/12154. The `sort.StringSlice` method in the stdlib doesn't actually sort, but instead constructs a sorting type which you call `Sort()` on.
* Fix extra long alloc IDs in `nomad volume status` because of a line that got missed in https://github.com/hashicorp/nomad/pull/12153

CSI: presentation improvements

---

.changelog/12324.txt
nomad/drainer/draining_node.go
nomad/structs/structs.go
website/content/docs/commands/node/drain.mdx

Fixes https://github.com/hashicorp/nomad/issues/11614 (when combined with #11892)
When a node is drained, system jobs are left until last so that
operators can rely on things like log shippers running even as their
applications are getting drained off. Include CSI plugins in this set
so that Controller plugins deployed as services can be handled as
gracefully as Node plugins that are running as system jobs.
---
The changeset here is fairly trivial and I've tested it by hand; I don't know that a unit test is going to tell us anything interesting here. But I'm going to follow up this PR next week with an E2E test for CSI node drain behavior more generally.

drainer: defer CSI plugins until last

---

nomad/config.go

The Raft version is being properly set in [`command/agent/config.go`](https://github.com/hashicorp/nomad/blob/main/command/agent/config.go#L974) so I don't think this was impacting anything, so the change is mostly for consistency.

set Raft v3 as the default config

---

.changelog/12350.txt
nomad/csi_endpoint.go

Fixes #12346 (ref https://github.com/hashicorp/nomad/issues/12346#issuecomment-1075343830)
When a node is garbage collected, we assume that the volume is no
longer attached to it and ignore the `ErrUnknownNode` error. But we
used `errors.Is` to check for a wrapped error, and RPC flattens the
errors during serialization. This results in an error check that works
in automated testing but not in real clusters. Use a string contains
check instead.

CSI: fix handling of garbage collected node in node unpublish

---

.changelog/12337.txt
nomad/job_endpoint_test.go
nomad/structs/csi_test.go
nomad/structs/structs.go
nomad/structs/volume_test.go
nomad/structs/volumes.go

Fixes https://github.com/hashicorp/nomad/issues/10157 
A volume that has single-use access mode is feasibility checked during
scheduling to ensure that only a single reader or writer claim
exists. However, because feasibility checking is done one alloc at a
time before the plan is written, a job that's misconfigured to have
count > 1 that mounts one of these volumes will pass feasibility
checking.
Enforce the check at validation time instead to prevent us from even
trying to evaluation a job that's misconfigured this way.
Rework the validation code for legibility and add missing unit test.

CSI: enforce single access mode at validation time

---

.changelog/12352.txt
command/volume_snapshot_list.go
go.mod
nomad/csi_endpoint_test.go
plugins/csi/client_test.go
plugins/csi/plugin.go

Fixes https://github.com/hashicorp/nomad/issues/10670
Listing snapshots was incorrectly returning nanoseconds instead of
seconds, and formatting of timestamps both list and create snapshot
was treating the timestamp as though it were nanoseconds instead of
seconds. This resulted in create timestamps always being displayed as
zero values.
Fix the unit conversion error in the command line and the incorrect
extraction in the CSI plugin client code. Beef up the unit tests to
make sure this code is actually exercised.
---
After this patch, the CLI outputs look like the following.
Listing snapshots. Note these sort the reverse way I'd expect and want, but we'll come back to that in a separate patch.
```
$ nomad volume snapshot list -plugin aws-ebs0 -per-page 5
Snapshot ID             Volume ID …
```

CSI: fix timestamp from volume snapshot responses

---

command/commands.go
command/service.go
command/service_delete.go
command/service_delete_test.go
command/service_info.go
command/service_info_test.go
command/service_list.go
command/service_list_test.go

closes https://github.com/hashicorp/team-nomad/issues/263

cli: add service commands for list, info, and delete.

---

.changelog/12369.txt
nomad/server.go

`0755` is common for directories, but `peers.json` is a file where we want `0644`.

core: write peers.json file with correct permissions

---

.changelog/12360.txt
api/csi.go
command/volume_snapshot_create.go
command/volume_snapshot_delete.go
command/volume_snapshot_list.go
nomad/csi_endpoint.go
website/content/docs/commands/volume/snapshot-create.mdx
website/content/docs/commands/volume/snapshot-list.mdx

Fixes https://github.com/hashicorp/nomad/issues/12318
Pass-through the `-secret` and `-parameter` flags to allow setting
parameters for the snapshot and overriding the secrets we've stored on
the CSI volume in the state store.

CSI: add `-secret` and `-parameter` flags to `volume snapshot create`

---

.changelog/12362.txt
nomad/server.go
nomad/server_test.go
nomad/testing.go

Downgrading the Raft version protocol is not a supported operation.
Checking for a downgrade is hard since this information is not stored in
any persistent place. When a server re-joins a cluster with a prior Raft
version, the Serf tag is updated so Nomad can't tell that the version
changed.
Mixed version clusters must be supported to allow for zero-downtime
rolling upgrades. During this it's expected that the cluster will have
mixed Raft versions. Enforcing consistency strong version consistency
would disrupt this flow.
The approach taken here is to store the Raft version on disk. When the
server starts the `raft_protocol` value is written to the file
`data_dir/raft/version`. If that file already exists, its content is
checked against the current `raft_protocol` value to detect …

core: store and check for Raft version changes

---

nomad/server.go
nomad/util.go
nomad/util_test.go

Revert a small part of #11600 after @lgfa29 discovered it would break
compatibility with Nomad <= v1.2!
Nomad <= v1.2 expects the `vsn` tag to exist in Serf. It has always been
`1`. It has no functional purpose. However it causes a parsing error if
it is not set:
https://github.com/hashicorp/nomad/blob/v1.2.6/nomad/util.go#L103-L108
This means Nomad servers at version v1.2 or older will not allow servers
without this tag to join.
The `mvn` minor version tag is also checked, but soft fails. I'm not
setting that because I want as much of this cruft gone as possible.

core: add deprecated mvn tag to serf

---

nomad/rpc_test.go

Autopilot [makes a lot of requests to `Status.RaftStats`](https://github.com/hashicorp/nomad/blob/v1.2.6/nomad/stats_fetcher.go#L46) which end up affecting the connection limit enforcer. 
I couldn't find a way to stop it, or ignore these requests in the counter (the connection limiter [rejects the request](https://github.com/hashicorp/nomad/blob/v1.2.6/nomad/rpc.go#L135-L144) before we can read and figure out what method is being called), so I'm downgrading the Raft version for this test.
It may be worth investigating the impact of this in real clusters as the configured request limit may be off. I tried setting `c.RPCMaxConnsPerClient = tc.limit + 1` to account for the potential concurrent `Status.RaftStats` but that wasn't enough.

tests: fix rpc limit tests

---

.changelog/12252.txt
ui/app/templates/allocations/allocation/index.hbs
ui/app/templates/allocations/allocation/task/index.hbs
ui/app/templates/clients/client/index.hbs
ui/app/templates/components/job-page/parts/latest-deployment.hbs
ui/app/templates/components/job-page/parts/title.hbs
ui/app/templates/components/job-version.hbs

Make stop job message clearer to ensure job is not stopped by mistake instead of allocation
Decided to create a PR instead of requesting for change. Open to suggestions :)

make stop job message clearer

---

website/content/docs/job-specification/gateway.mdx

Stating at Nomad version 1.2.0 `grpc` and `http2` protocols [are supported](https://github.com/hashicorp/nomad/pull/11187)
The change affects [gateway protocol docs](https://www.nomadproject.io/docs/job-specification/gateway#protocol)

Add grpc and http2 listeners to gateway docs

---

command/meta.go

A number of commands support namespace wildcard querying, so it
should be up to the sub-command to detail support, rather than
keeping this list up to date.

cli: update namespace wildcard help to be non-specific.

---

.github/workflows/test-core.yaml
GNUmakefile

test_checks.sh was removed in 2019 and now just breaks if VERBOSE is
set when running tests via make targets
in GHA, use verbose mode to display what tests are running

ci: cleanup verbose mode and enable for gha

---

.changelog/12371.txt
client/fingerprint/env_aws.go
client/fingerprint/env_aws_test.go
website/content/docs/runtime/interpolation.mdx

The EC2 instance life cycle metadata allows jobs to add constraints or affinity stanzas with a preference for on-demand or spot requests. On AWS, this can be particularly useful for segmenting workloads based on risk tolerance of preemption.

client: Add AWS EC2 instance-life-cycle from metadata to client fingerprint

---

e2e/disconnectedclients/disconnectedclients.go
e2e/disconnectedclients/input/lost_simple.nomad
e2e/e2e_test.go
e2e/e2eutil/input/restart-node.nomad
e2e/e2eutil/node.go

This test exercises the behavior of clients that become disconnected
and have their allocations replaced. Future test cases will exercise
the `max_client_disconnect` field on the job spec.
---
Example test run. I think we'll end up having to tune the timeouts on this a bit as we add more test cases; this is a naturally slow test because it takes a while for a node to get marked lost.
```
$ go test -v . -suite DisconnectedClients
...
=== RUN   TestE2E/DisconnectedClients
=== RUN   TestE2E/DisconnectedClients/*disconnectedclients.DisconnectedClientsE2ETest
=== RUN   TestE2E/DisconnectedClients/*disconnectedclients.DisconnectedClientsE2ETest/TestDisconnectedClients_AllocReplacment
...
--- PASS: TestE2E (42.85s)
...
--- PASS: TestE2E/DisconnectedClients (42.85s)
--- PASS: …
```

E2E: test for allocations replacement on disconnected clients

---

e2e/terraform/hcp_consul.tf
e2e/terraform/hcp_vault.tf

Concurrent E2E runs can collide when provisioning policies on HCP
Consul and HCP Vault. Namespace these by the test run name, as we do
for most everything else.
Errors on the runner look like so:
```
Error: error creating ACL policy: Unexpected response code: 500 (Invalid Policy: A Policy with Name "consul_agent_policy" already exists)
on hcp_consul.tf line 13, in resource "consul_acl_policy" "consul_agent":
13: resource "consul_acl_policy" "consul_agent" {
```

E2E: namespace HCP vault and consul policies to avoid collisions

---

.github/workflows/test-core.yaml
GNUmakefile
command/agent/keyring_test.go
command/agent/log_levels.go
command/agent/testagent.go

Many of our tests do terrible things, causing many log lines even at ERROR level. From CI all we really want is the normal `go test` output with the line number of the failure. `TestAgent` still needed some plumbing for `NOMAD_TEST_LOG_LEVEL` to take affect. 
includes https://github.com/hashicorp/nomad/pull/12379

ci: set test log level off in gha

---

.changelog/12248.txt
api/fs.go

A tiny fix to close the StreamFream channel before finishing the streaming by the `<-cancel` channel.
Let's say you use [FrameReader.Read()](https://pkg.go.dev/github.com/hashicorp/nomad/api#FrameReader.Read), now we have no way to quit the select block even when the streaming finished. (Actually we can pass `cancelCh chan struct{}` to [NewFrameReader](https://github.com/hashicorp/nomad/blob/154264fcd927/api/fs.go#L306) but I'd like to stop reading when `<-ctx.Done()`)
Therefore, I would say it should close immediately as soon as the streaming finished.

Ensure to close StreamFrame channel

---

client/allocrunner/csi_hook.go
nomad/core_sched_test.go
nomad/csi_endpoint.go
nomad/csi_endpoint_test.go

Ran into this while working on #12384
In #12112 and #12113 we solved for the problem of races in releasing
volume claims, but there was a case that we missed. During a node
drain with a controller attach/detach, we can hit a race where we call
controller publish before the unpublish has completed. This is
discouraged in the spec but plugins are supposed to handle it
safely. But if the storage provider's API is slow enough and the
plugin doesn't handle the case safely, the volume can get "locked"
into a state where the provider's API won't detach it cleanly.
Check the claim before making any external controller publish RPC
calls so that Nomad is responsible for the canonical information about
whether a volume is currently claimed.
This has a couple side-effects that also had to get fixed …

CSI: reorder controller volume detachment

---

e2e/csi/ebs.go
e2e/terraform/Makefile

Run a test on nightly that drains a node and ensures that the CSI volume is moved as expected. (This is still using the "framework-style" testing because I didn't want to rewrite the entire `e2e/csi` package just to land this. Will do that in a follow-up PR.)

E2E: test exercising node drain behavior for CSI volumes

---

.changelog/12400.txt
command/volume_init.go
command/volume_register_test.go
nomad/csi_endpoint.go
nomad/csi_endpoint_test.go
website/content/docs/commands/volume/create.mdx
website/content/docs/commands/volume/register.mdx

Fixes https://github.com/hashicorp/nomad/issues/11196.
Use the volume spec's `namespace` field to override the value of the
`-namespace` and `NOMAD_NAMESPACE` field, just as we do with job spec.

CSI: allow `namespace` field to be passed in volume spec

---

e2e/disconnectedclients/disconnectedclients.go
e2e/disconnectedclients/disconnectedclients_test.go
e2e/disconnectedclients/doc.go
e2e/e2eutil/node.go

* Wait longer for the node to go down. The existing helper only waits 10s, 
but there's a jitter on heartbeats that we need to account for. Wait for 30s 
for node to go down to give us plenty of room
* Port the test to the stdlib style test as we did in https://github.com/hashicorp/nomad/pull/12383

E2E disconnected clients test refactor

---

command/operator_debug_test.go
command/recommendation_list_test.go
command/service_delete_test.go

These tend to fail on GHA, where I believe the client is not
starting up fast enough before making requests. So wait on
the client agent first.
e.g.
```
=== RUN   TestDebug_CapturedFiles
operator_debug_test.go:422: serverName: TestDebug_CapturedFiles.global, clientID, 1afb00e6-13f2-d8d6-d0f9-745a3fd6e8e4
operator_debug_test.go:492:
Error Trace:	operator_debug_test.go:492
Error:      	Should be empty, but was No node(s) with prefix "1afb00e6-13f2-d8d6-d0f9-745a3fd6e8e4" found
Failed to retrieve clients, 0 nodes found in list: 1afb00e6-13f2-d8d6-d0f9-745a3fd6e8e4
Test:       	TestDebug_CapturedFiles
--- FAIL: TestDebug_CapturedFiles (0.08s)
```

tests: wait on client in a couple of tests

---

ui/app/templates/evaluations/index.hbs

This change establishes an `active` style to evaluations table rows when they're the subject of the current sidebar.
https://user-images.githubusercontent.com/713991/160969243-3c514d12-f2d0-400f-a197-f343c8c27fd1.mov

conditional class looking for currentEval equality

---

client/allocrunner/alloc_runner.go
client/allocwatcher/alloc_watcher.go
client/client_test.go
nomad/node_endpoint.go
nomad/structs/structs.go
nomad/structs/structs_test.go
scheduler/generic_sched.go
scheduler/reconcile.go
scheduler/reconcile_test.go
scheduler/reconcile_util.go
scheduler/reconcile_util_test.go

Not ready for review
This PR changes the generic scheduler reconcile logic to support zero-downtime reconnects.
The initial implementation for disconnected clients stopped replacement allocations before the reconnecting node synced its alloc state with the server. If the alloc failed while the node was disconnected, this could lead to a scenario where the replacement was stopped, but the reconnecting alloc was not healthy, and the cluster ends up underprovisioned.
This PR changes the logic so that allocs are identified as reconnecting after the reconnecting client sends its alloc updates to the server.  To make this work, I made the following changes.
- `Node.UpdateAlloc`
- Looks up the server-side alloc state immediately instead of after checking if the incoming client alloc is terminal. …

reconciler: 2 phase reconnects and tests

---

client/allocrunner/groupservice_hook_test.go

This is a test around upgrading from Nomad 0.8, which is long since
no longer supported. The test is slow, flaky, and imports consul/sdk.
Remove this test as it is no longer relevant.

tests: remove update 08 groups services test

---

website/content/docs/schedulers.mdx

`exit` here is more correct, and consistent with the description of a `batch` job
> Batch jobs are intended to run until they exit successfully.

docs: fix typo in system batch description

---

nomad/core_sched_test.go
nomad/volumewatcher/volumes_watcher_test.go

I have a gnarly PR coming up that's touching both these files, so I want to split out the `require` fixes and removing the `state` aliasing into their own PR so as not to scare-off reviewers with a large changeset.

Test lint touchup

---

nomad/core_sched_test.go
nomad/csi_endpoint.go
nomad/volumewatcher/volume_watcher.go
nomad/volumewatcher/volumes_watcher.go
nomad/volumewatcher/volumes_watcher_test.go

The volume watcher design was based on deploymentwatcher and drainer,
but has an important difference: we don't want to maintain a goroutine
for the lifetime of the volume. So we stop the volumewatcher goroutine
for a volume when that volume has no more claims to free. But the
shutdown races with updates on the parent goroutine, and it's possible
to drop updates. Fortunately these updates are picked up on the next
core GC job, but we're most likely to hit this race when we're
replacing an allocation and that's the time we least want to wait.
Wait until the volume has "settled" before stopping this goroutine so
that the race between shutdown and the parent goroutine sending on
`<-updateCh` is pushed to after the window we most care about quick
freeing of claims.
* Fixes a resource leak …

CSI: volume watcher shutdown fixes

---

.changelog/11938.txt
command/operator_debug.go
command/operator_debug_test.go
website/content/docs/commands/operator/debug.mdx

command/operator_debug: add pprof interval

---

.changelog/11245.txt
api/csi.go
command/agent/csi_endpoint.go
command/volume_delete.go
nomad/csi_endpoint.go
nomad/csi_endpoint_test.go
nomad/structs/csi.go
website/content/api-docs/volumes.mdx
website/content/docs/commands/volume/delete.mdx

CSI: Add secrets flag support for delete volume

---

client/allocrunner/csi_hook.go
client/allocrunner/csi_hook_test.go

When we unmount a volume we need to be able to recover from cases
where the plugin has been shutdown before the allocation that needs
it, so in #11892 we blocked shutting down the alloc runner hook. But
this blocks client shutdown if we're in the middle of unmounting. The
client won't be able to communicate with the plugin or send the
unpublish RPC anyways, so we should cancel the context and assume that
we'll resume the unmounting process when the client restarts.
For `-dev` mode we don't send the graceful `Shutdown()` method and
instead destroy all the allocations. In this case, we'll never be able
to communicate with the plugin but also never close the context we
need to prevent the hook from blocking. To fix this, move the retries
into their own goroutine that doesn't block the main …

CSI: don't block client shutdown for node unmount

---

command/node_status.go
command/node_status_test.go
website/content/docs/commands/node/status.mdx

More details [`here`](https://github.com/hashicorp/nomad/pull/12388#issuecomment-1083404072)
/cc @tgross @DerekStrickland 

Add -quiet to nomad node status command.

---

website/content/docs/internals/plugins/csi.mdx
website/content/docs/job-specification/csi_plugin.mdx

Preview links:
* https://nomad-ik2g3r0e0-hashicorp.vercel.app/docs/internals/plugins/csi
* https://nomad-ik2g3r0e0-hashicorp.vercel.app/docs/job-specification/csi_plugin

docs: updates for CSI plugin improvements for 1.3.0

---

ui/app/routes/evaluations/index.js
ui/app/templates/evaluations/index.hbs
ui/tests/acceptance/evaluations-test.js

Using query param filters with the new `filter` param will return an error, so hiding these for now.

ui: hide triggered by and status filters for now

---

.changelog/12264.txt
nomad/plan_apply.go
nomad/plan_apply_test.go
nomad/structs/funcs.go

Fix in-place updates over ineligible nodes

---

.changelog/12409.txt
api/api.go

The only difference is DefaultTransport sets DisableKeepAlives
This doesn't make much sense to me - every http connection from the
nomad client goes to the same NOMAD_ADDR so it's a great case for keep
alive. Except round robin DNS and anycast perhaps.
Consul does this already
https://github.com/hashicorp/consul/blob/1e47e3c82b6eb937baab0688a67cf7ef334ce42c/api/api.go#L397

Use cleanhttp.DefaultPooledTransport for the default API client

---

GNUmakefile
scripts/version.sh

The ENT version of this script works fine for OSS and having the same in both places reduces the chance of a merge conflict.

ci: make version script match ENT to avoid unnecessary merge conflicts

---

.changelog/12409.txt
api/api.go

I merged https://github.com/hashicorp/nomad/pull/12409 earlier today but missed that it was failing one of our tests. I've had a look at the test and it _looks_ to me like the test is this is an artifact of the test rig and not a real bug, plus the author of the PR is using the patch in production at large scale already. But rather than have our tests failing and/or holding up the upcoming Nomad 1.3.0 beta, let's revert and then I'll track down the issue with the test under a bit less time pressure.

revert `cleanhttp.DefaultPooledTransport`

---

nomad/vault.go

metrics: emit stats for vault token next_renewal & last_renewal #5222

---

client/allocrunner/taskrunner/task_runner_hooks.go
client/allocrunner/taskrunner/template/template.go
client/allocrunner/taskrunner/template/template_test.go
client/allocrunner/taskrunner/template_hook.go
client/config/config.go
command/agent/agent.go
command/agent/command.go
command/agent/http.go
e2e/consultemplate/consultemplate.go
e2e/consultemplate/input/nomad_provider_service.nomad
e2e/consultemplate/input/nomad_provider_service_lookup.nomad
e2e/consultemplate/input/nomad_provider_service_ns.nomad
go.mod
go.sum
helper/bufconndialer/bufconndialer.go

This change modifies the template task runner to utilise the
new consul-template which includes Nomad service lookup template
funcs.
In order to provide security and auth to consul-template, we use
a custom HTTP dialer which is passed to consul-template when
setting up the runner. This method follows Vault implementation.
This PR also includes an E2E test in lieu of integration tests. This
is due to the taskrunner/template pkg being in a long import chain
making utilising current test agents/clients impossible without a
large refactor. We will therefore step back and address this
properly in the future.

client: add Nomad template service functionality to runner. 

---

client/allocrunner/groupservice_hook.go
client/allocrunner/taskrunner/service_hook.go

When a service is updated, the service hooks update a number of
internal fields which helps generate the new workload. This also
needs to update the namespace for the service provider. It is
possible for these to be different, and in the case of Nomad and
Consul running OSS, this is to be expected.
I'll add a backlog item to come up with integration tests which cover
this alongside the E2E tests I can currently writing which found this.

client: account for service provider namespace updates in hooks.

---

.changelog/11945.txt
.changelog/12274.txt
.changelog/12369.txt
.changelog/12419.txt
.changelog/changelog.tmpl

Add missing component prefix in some entries and preserve the line break after the `BREAKING CHANGES` section title

changelog: minor fixes

---

.changelog/12492.txt
api/api.go
command/agent/http_test.go

We expect every Nomad API client to use a single connection to any
given agent, so take advantage of keep-alive by switching the default
transport to `DefaultPooledClient`. Provide a facility to close idle
connections for testing purposes.
Restores the previously reverted #12409 (cc @benbuzbee)

api: use `cleanhttp.DefaultPooledTransport` for default API client

---

nomad/state/state_store_service_regisration_test.go

This fixes two dropped `err` variables in `nomad/state`.

nomad/state: fix dropped test errors

---

.changelog/12496.txt
client/taskenv/env.go
client/taskenv/env_test.go
website/content/partials/envvars.mdx

This PR injects the `NOMAD_CPU_CORES` environment variable into
tasks that have been allocated reserved cpu cores. The value uses
normal cpuset notation, as found in cpuset.cpu cgroup interface files.
Note this value is not necessiarly the same as the content of the actual
cpuset.cpus interface file for the task, which will also include shared cpu 
cores when using cgroups v2. This variable is a workaround for users who 
used to be able to read the reserved cgroup cpuset file, but lose the information
about distinct reserved cores when using cgroups v2.
Side discussion in: https://github.com/hashicorp/nomad/issues/12374

client: set environment variable indicating set of reserved cpu cores

---

ui/app/adapters/application.js
ui/app/components/job-page/parts/job-client-status-summary.js
ui/app/components/job-page/parts/summary.js
ui/app/helpers/css-class.js
ui/app/serializers/application.js
ui/app/serializers/volume.js
ui/mirage/factories/alloc-file.js
ui/mirage/factories/csi-volume.js
ui/mirage/factories/job.js
ui/mirage/factories/service.js
ui/mirage/factories/task-group.js
ui/mirage/factories/task.js
ui/mirage/serializers/application.js
ui/tests/integration/components/agent-monitor-test.js

1.3 prod build unblocker
Handles the [deprecation of string prototype extensions](https://deprecations.emberjs.com/ember/v3.x/#toc_ember-string-prototype_extensions) in Ember by importing them explicitly

Importing string methods directly from @ember/string

---

.github/workflows/build.yml

The `make prerelease` target is not idempotent, which causes the binary version to show with `+CHANGES`

ci: skip `prerelease` if triggered by the generate assets workflow

---

website/content/docs/job-specification/hcl2/variables.mdx

This adds a custom variable validation section to the input variable docs since it wasn't apparent that this was supported in Nomad. Personally I was surprised that this worked in Nomad I couldn't find any mention in the official docs.
I've cribbed the content from the terraform docs, specifically from https://www.terraform.io/language/values/variables#custom-validation-rules with some light changes. Feel free to make any wording, grammar changes etc.
This addresses issue https://github.com/hashicorp/nomad/issues/12507

Add custom variable validation to docs

---

.semgrep/ui.yml

Detect invalid calls to string extensions that were deprecated. List of functions taken from https://github.com/hashicorp/nomad/pull/12502
Playground link: https://semgrep.dev/s/vpvl

ci: add semgrep rule to catch usage of invalid string extensions

---

website/content/docs/job-specification/template.mdx

Alongside adding a Nomad example, the change tightens up the Consul service example and fixes an issue where the Consul service name detailed isn't a valid service name.

docs: add nomad services template jobspec example.

---

website/content/docs/upgrade/upgrade-specific.mdx

Having a title start with `code block` looks off. Also move the deny list changes above the cgroups wall of text, so it doesn't get lost.

docs: fixup title formatting in upgrade guide

---

e2e/e2eutil/job.go
e2e/servicediscovery/doc.go
e2e/servicediscovery/input/consul_provider.nomad
e2e/servicediscovery/input/multi_provider.nomad
e2e/servicediscovery/input/nomad_provider.nomad
e2e/servicediscovery/service_discovery_test.go

The PR also includes a new cancellable cleanup util.

e2e: add initial service discovery tests.

---

scheduler/reconcile_util.go
scheduler/reconcile_util_test.go

In the reconciler's filtering for tainted nodes, we use whether the
server supports disconnected clients as a gate to a bunch of our
logic, but this doesn't account for cases where the job doesn't have
`max_client_disconnect`. The only real consequence of this appears to
be that allocs on disconnected nodes are marked "complete" instead of
"lost".

allocs without max_client_disconnect should be lost on disconnect

---

e2e/disconnectedclients/disconnectedclients_test.go
e2e/disconnectedclients/input/lost_max_disconnect.nomad
e2e/e2eutil/input/disconnect-node.nomad
e2e/e2eutil/input/restart-node.nomad
e2e/e2eutil/node.go

Adds a matrix of 4 test scenarios: shutdown vs netsplit, and with `max_client_disconnect` vs not.
Blocked on https://github.com/hashicorp/nomad/pull/12529
---
```
$ go test -v ./disconnectedclients -count=1
=== RUN   TestDisconnectedClients
=== RUN   TestDisconnectedClients/netsplit_client_no_max_disconnect
disconnectedclients_test.go:179: waiting for 4 nodes to become ready again
=== RUN   TestDisconnectedClients/netsplit_client_with_max_disconnect
disconnectedclients_test.go:179: waiting for 4 nodes to become ready again
=== RUN   TestDisconnectedClients/shutdown_client_no_max_disconnect
disconnectedclients_test.go:179: waiting for 4 nodes to become ready again
=== RUN   TestDisconnectedClients/shutdown_client_with_max_disconnect
disconnectedclients_test.go:179: waiting for 4 nodes to …
```

E2E: test for nodes disconnected by netsplit

---

.release/ci.hcl

`#proj-nomad-releases` is starting to get a bit nosy. Another option would be change the `verify` event notification to `on = "error"`, but this would have to be change during releases and it's a bit too far down to find it.
Switching channels is easier since it's defined at the top of the file. Keeping both channel IDs also means we can comment/uncomment them when needed.

ci: change notification channel to feed-nomad-releases

---

e2e/events/events.go
e2e/events/input/initial.nomad

Fixes https://github.com/hashicorp/nomad/issues/12538
This changeset fixes two sources of flakiness in the event stream test.
First, the stream request gets the event *closest* to the index, not
the exact match. Although events are written before raft entries
they're written asynchronously, so it's possible to race and get a
raft index from this query higher than the current head of the event
buffer. Ensure the job is running before we try to get the index, so
that we've given the event enough time to land in the buffer.
Second, the assertion that the found index is greater than the start
index is only true if the `PlanResult` event manages to land before we
do the second registration. Although it should now with the first fix
above, it's not a correct assertion for what we're testing.

E2E: fix flaky event stream test

---

demo/csi/hostpath/run.sh
e2e/bin/run
e2e/bin/update
e2e/networking/inputs/validate.sh
e2e/terraform/packer/ubuntu-bionic-amd64/dnsconfig.sh
e2e/terraform/packer/ubuntu-bionic-amd64/setup.sh
e2e/terraform/scripts/bootstrap-nomad.sh
nomad/structs/generate.sh
scripts/example_weave.bash
terraform/aws/env/us-east/user-data-client.sh
terraform/aws/env/us-east/user-data-server.sh
terraform/azure/env/EastUS/user-data-client.sh
terraform/azure/env/EastUS/user-data-server.sh
terraform/shared/scripts/client.sh
terraform/shared/scripts/server.sh
terraform/shared/scripts/setup.sh
website/scripts/should-build.sh

Many of our scripts have a non-portable interpreter line for bash and
use bash-specific variables like `BASH_SOURCE`. Update the interpreter
line to be portable between various Linuxes and macOS without
complaint from posix shell users.
(This was originally encountered by @philrenaud in the CSI demo directory but it applies across a number of our scripts, so I've gone thru and fixed it everywhere.)

scripts: fix interpreter for bash

---

nomad/state/paginator/tokenizer.go

It wasn't clear how these options were supposed to be set since any combination is technically valid, but in practice may result in unexpected pagination results.
In the future, we should probably have specialized tokenizers for each of the use cases.

add some godocs for the API pagination tokenizer options

---

e2e/terraform/README.md

Arguments/flags were out of order in E2E readme.

Update E2E terraform output command

---

.changelog/12543.txt
command/agent/consul/connect.go
command/agent/consul/connect_test.go
command/agent/consul/group_test.go
command/agent/consul/service_client.go
command/agent/consul/unit_test.go
website/content/docs/upgrade/upgrade-specific.mdx

Adds alloc_id to envoy tags during the sidecar bootstrapping process.  Addresses issue #12326
This does not change gateway bootstrapping, only sidecar bootstrapping.
Thanks to @fredwangwang  and @gulavanir for the collaboration on this.

Add alloc_id to sidecar bootstrap

---

client/dynamicplugins/registry_test.go

These tests have a data race where the test assertion is reading a
value that's being set in the `listenFunc` goroutines that are
subscribing to registry update events. Move the assertion into the
subscribing goroutine to remove the race. This bug was discovered
in #12098 but does not impact production Nomad code.

fix data race in dynamic plugin registry tests

---

ui/app/templates/components/gutter-menu.hbs

In Nomad 1.3.0, the storage integration (CSI) is finally out of beta.

ui: remove beta tag from gutter menu for CSI

---

e2e/disconnectedclients/disconnectedclients_test.go

This test has a failure that's happening only occassionally and not
very reproducibly. Print out the allocation status on test failure so
that we can do some post-mortum debugging of the test on nightly.

E2E: add debugging outputs for disconnected clients test

---

website/content/docs/operations/monitoring-nomad.mdx

- Moved federation docs to the bottom since *everyone* is potentially
affected by the other sections on the page, but only users of
federation are affected by it.
- Added section on the plan for node rejected bug since it is fairly
easy to diagnose and removing affected nodes is a fairly reliable
workaround.
- Mention 5s cliff for wait_for_index.
- Remove the lie that we do not have job status metrics! How old was
that?!
- Reinforce the importance of monitoring basic system resources

docs: add plan for node rejected details and more

---

command/agent/http_test.go

This fixes a test where `defer client.Close()` was happening before an `err` check.

command/agent: check err before close

---

.changelog/12573.txt
command/alloc_status.go

While walking @philrenaud thru https://github.com/hashicorp/nomad/issues/11965 I realized that we have the exact same problem in the CLI. 🤦 
The Nomad client's `csi_hook` interpolates the alloc suffix with the
volume request's name for CSI volumes with `per_alloc = true`, turning
`example` into `example[1]`. We need to do this same behavior in the
`alloc status` output so that we show the correct volume.

CSI: handle per-alloc volumes in `alloc status -verbose` CLI

---

nomad/structs/structs.go
scheduler/generic_sched.go
scheduler/reconcile_util.go
scheduler/scheduler_system.go
scheduler/scheduler_system_test.go
scheduler/util.go
scheduler/util_test.go

This PR modifies the system scheduler so that `system` and `sysbatch` jobs can take advantage of the disconnected client feature.
- `e2090b1`: Adds a shared logic function to `Allocation` for determining if an allocation is configured with `max_client_disconnect`
- `4dbb5f6`: Modifies the system scheduler to 
- Guard against minimum server version
- Track and report disconnecting/reconnecting allocs
- Mark an allocation as `unknown` when its node transitions to disconnected
- Mark an allocation as `lost` when its disconnect duration expires
- Ignore `unknown` allocations that have not yet expired
- Log reconnecting allocations when the node transitions back to `ready`

system_scheduler: support disconnected clients

---

nomad/heartbeat.go
nomad/heartbeat_test.go
nomad/node_endpoint.go

Closes #12470
This PR updates the `nodeHeartbeater` to handle transitioning a client from `disconnected` to `down`
It does this by:
- Updating `node_endpoint` to allow `disconnect` updates to participate in the heartbeat timer process
- Checking to see if the node has any pending reconnectable allocations on each heartbeat
- Setting the node status to `down` when there are no more pending reconnectable allocations

heartbeat: Handle transitioning from disconnected to down

---

website/redirects.js

This redirects all `v1.2._`, `v1.1._` and `v1.0._` docs to respective generic release versions: `v1.2.x`, `v1.1.x`, and `v1.0.x`
**Dont merge until the targets are live and ready**
```console
λ  curl -I -X GET nomad-p2ipxjp94-hashicorp.vercel.app/docs/1.0.9000
HTTP/1.1 308 Permanent Redirect
Location: https://nomad-p2ipxjp94-hashicorp.vercel.app/docs/1.0.9000
λ  curl -I -X GET nomad-p2ipxjp94-hashicorp.vercel.app/docs/1.0.9000/foobar
HTTP/1.1 308 Permanent Redirect
Location: https://nomad-p2ipxjp94-hashicorp.vercel.app/docs/1.0.9000/foobar
λ  curl -I -X GET nomad-p2ipxjp94-hashicorp.vercel.app/docs/1.1.9000
HTTP/1.1 308 Permanent Redirect
Location: https://nomad-p2ipxjp94-hashicorp.vercel.app/docs/1.1.9000
λ  curl -I -X GET nomad-p2ipxjp94-hashicorp.vercel.app/docs/1.1.9000/foobar …
```

chore: redirects

---

command/volume_status_csi.go

The API for `CSIVolume.List` sorts by created index and not by ID,
which breaks the logic for prefix matching in the `volume status`
output when the prefix is also an exact match. Ensure that we're
handling this case correctly.
---
No changelog because this hasn't shipped in a GA version.
```
$ nomad volume status -namespace '*'
Container Storage Interface
ID                 Name               Plugin ID               Schedulable  Access Mode
csi-volume-nfs     csi-volume-nfs     org.democratic-csi.nfs  true         multi-node-multi-writer
csi-volume-nfs[0]  csi-volume-nfs[0]  org.democratic-csi.nfs  true         multi-node-multi-writer
csi-volume-nfs[1]  csi-volume-nfs[1]  org.democratic-csi.nfs  true         multi-node-multi-writer
$ nomad volume status -namespace '*' csi-volume-nfs | …
```

CSI: fix volume status prefix matching in CLI

---

api/nodes.go
command/agent/node_endpoint.go
command/agent/node_endpoint_test.go
command/node_status.go
nomad/structs/structs.go
website/content/api-docs/nodes.mdx

ping @tgross @DerekStrickland 

Add os to NodeListStub struct.

---

.circleci/config.yml

Build binaries for every code change, not just backend code
changes. This means that we'll have up-to-date compiled assets for
every commit available in CircleCI artifacts.
(As far as I can tell, our GHA builds already include this step.)

CI: build binaries for UI branches

---

.changelog/12593.txt
nomad/structs/structs.go

fix #12592 by changing a by-value method receiver into a pointer receiver

fix #12592

---

ci/slow.go
client/allocrunner/taskrunner/task_runner_test.go
client/config/testing.go
plugins/drivers/testutils/testing.go

This PR is 2 fixes for the flaky `TestTaskRunner_TaskEnv_Chroot` test, which hadn't been running in GHA until the recent [coverage fix](https://github.com/hashicorp/nomad/pull/12579/files#diff-999a0a7a9c02c83b86cfcdab3f79fa1a5f7eae38f6714e723beef804f1ba7aeaR95). 
- Use TinyChroot to stop copying gigabytes of data, which causes GHA
to fail to create the environment in time.
- Pre-create cgroups on V2 systems. Normally the cgroup directory is
managed by the cpuset manager, but that is not active in taskrunner tests,
so create it by hand in the test framework.

ci: fixup task runner chroot test

---

e2e/terraform/README.md
e2e/terraform/network.tf
e2e/terraform/provision-nomad/install-linux.tf
e2e/terraform/provision-nomad/main.tf
e2e/terraform/tls_client.tf
e2e/ui/input/proxy.nomad

Our E2E test environment is deployed with mTLS, but it's impractical
for us to use mTLS in headless browsers for automated testing (or even
in manual testing). Provide certificates for proxying the web UI via
Nginx. This proxy uses client certs for proxying to the HTTP endpoint
and a self-signed cert for the browser-facing endpoint. We can accept
certificate errors in the automated tests we'll be adding in the next
step of this work.
Example results (this cluster has already been torn down):

E2E: provide options for reverse proxy for web UI

---

.changelog/12602.txt
client/alloc_watcher_e2e_test.go
client/client_test.go
command/integration_test.go
nomad/job_endpoint_hooks.go
nomad/job_endpoint_hooks_test.go
nomad/job_endpoint_test.go
nomad/mock/mock.go
nomad/structs/job.go
nomad/structs/job_test.go

This change adds an implicit constraint to task groups which utilise Consul for service registration. This matches the behaviour when using the Nomad provider. The change also refactors the mutator function so we only loop through the task groups once, no matter how many constraint mutators we have.
The first commit adds tests to cover the mutator functionality; this can be used to ensure the functionality of the refactor has not regressed.
Other tests needed slight changes, to accommodate this new feature.
closes #11471

job_hooks: add implicit constraint when using Consul for services.

---

client/allocrunner/taskrunner/plugin_supervisor_hook.go

Apply the same changes as in https://github.com/hashicorp/nomad/pull/12682 to the 1.2.x release line.

Backport #12149 to 1.2.x release

---

client/allocrunner/taskrunner/plugin_supervisor_hook.go

Manual backport of https://github.com/hashicorp/nomad/pull/12149 to include some required parts of https://github.com/hashicorp/nomad/pull/12078.
The main difference is the removal of [this block](https://github.com/hashicorp/nomad/blob/v1.3.0-beta.1/client/allocrunner/taskrunner/plugin_supervisor_hook.go#L206-L213) that calls `PluginForAlloc`. This function was added in #12078 by backporting that PR didn't seem like a good choice since it represents a major change in the underlying volume mount point structure.
So I only pulled the changes related to the new struct field `socketPath` and used the existing `mountPoint` value instead of the new `socketMountPoint` to avoid pulling too much.

Backport #12149 to 1.1.x release

---

.changelog/11531.txt
client/allocrunner/taskrunner/artifact_hook.go
client/allocrunner/taskrunner/artifact_hook_test.go

This PR adds support for concurrent downloads as requested on #11244. Currently 3 is set as the max number of downloads that can be active at a time, but I'm happy to add that to client or task configuration.
resolves #11244

Add Concurrent Download Support for artifacts

---

ui/app/utils/classes/stream-logger.js
ui/tests/unit/utils/stream-logger-test.js

During the Ember dependecy upgrade work,
https://github.com/hashicorp/nomad/commit/ce8c039f4ce7359d60ede5dee36b9cef82
moved the `isSupported` method from using Ember's `reopenClass` to a
getter, but `reopenClass` creates a static method, so the getter must be
static as well.
~I couldn't find a way to test this since the test suite uses a mock object.~
Not true, the mocks are for something else.
Closes #12647

ui: fix bug that prevented files streaming

---

nomad/state/autopilot.go

The original code was copied from Consul; upon spotting these I also checked Consul which has this updated error handling also.

autopilot: correctly return errors within state functions.

---

website/content/docs/job-specification/hcl2/expressions.mdx

Updates the doc to use a more "complete" example which both uses a complex local as well as labels and loops.
closes https://github.com/hashicorp/nomad/issues/12681

docs: update HCL2 dynamic example to use block with label.

---

e2e/csi/csi.go
e2e/csi/ebs.go
e2e/csi/efs.go

The CSI plugin allocations take a while to be marked healthy,
sometimes causing E2E test flakes during the setup phase of the
tests. There's nothing CSI specific about marking plugin allocs
healthy, as the plugin supervisor hook does all the fingerprinting in
the postrun hook (the prestart hook just makes a couple of empty
directories). The timeouts we're seeing may be because of where we're
pulling the images from; most our jobs pull from a CDN-backed public
registry whereas these are pulling from ECR. Set a 1min timeout for
these to make sure we have enough time to pull the image and start the
task.

E2E: set longer timeout for CSI plugin alloc start

---

drivers/docker/handle.go

When shutting down an allocation that ends up needing to be
force-killed, we're getting a spurious "OOM Killed (137)" message on
the task termination event. We introduced this as part of cgroups v2
support because the Docker daemon isn't detecting the container status
correctly. Although exit code 137 is the exit code we get for
OOM-killed processes, that's because OOM kill is a `SIGKILL`. So any
sigkilled process will get that exit code.
(I'm totally open to trying another approach here @shoenig, just couldn't come up with one.)
---
Example of spurious error:
```
Recent Events:
Time                  Type        Description
2022-04-21T15:32:50Z  Killed      Task successfully killed
2022-04-21T15:32:50Z  Terminated  Exit Code: 137, Exit Message: "OOM Killed (137)"
2022-04-21T15:32:44Z …
```

docker: back out cgroup v2 OOM detection

---

.changelog/12713.txt
jsconfig.json
ui/.ember-cli
ui/.template-lintrc.js
ui/app/components/task-row.js
ui/app/helpers/format-volume-name.js
ui/app/models/allocation.js
ui/app/models/volume-definition.js
ui/app/templates/allocations/allocation/task/index.hbs
ui/app/templates/components/task-row.hbs
ui/app/templates/jobs/job/task-group.hbs
ui/tests/unit/helpers/format-volume-name-test.js

In situations where `per_alloc` of a volume stanza is set to `true`, we currently throw a broken link: we try to find a base volume in a situation where it is split into multiples.
With this change, we disambiguate the per_alloc'd volume where possible.
This happens in 3 places:
- on the allocation route, in the Tasks table
- on the task route, in the Volumes table
- on the task group route, in the Volume Requirements table.
Importantly, this third situation does not have the ability to disambiguate: because a task group does not know which allocation it refers to, I've opted to provide the user with a link to queried volumes route instead.
- Allocations spread across multiple clients always receive a `[#]` suffix in their `name` property, and this is always the last bracketed text.
- The …

[ui, bugfix] Link fix for volumes where per_alloc=true

---

command/namespace_apply.go
website/content/docs/commands/namespace/apply.mdx

The new `namespace apply` feature that allows for passing a namespace
specification file detects the difference between an empty namespace
and a namespace specification by checking if the file exists. For most
cases, the file will have an extension like `.hcl` and so there's
little danger that a user will apply a file spec when they intended to
apply a file name.
But because directory names typically don't include an extension,
you're much more likely to collide when trying to `namespace apply` by
name only, and then you get a confusing error message of the form:
> Failed to read file: read $namespace: is a directory
Detect the case where the namespace name collides with a directory in
the current working directory, and skip trying to load the directory.
---
No changelog entry, as this …

cli: detect directory when applying namespace spec file

---

.changelog/12591.txt
command/helpers.go
command/helpers_test.go
command/job_plan.go
command/job_plan_test.go
command/job_run.go
command/job_run_test.go
command/job_validate.go
command/job_validate_test.go
command/testdata/example-short-bad.json
command/testdata/example-short.json
website/content/docs/commands/job/plan.mdx
website/content/docs/commands/job/run.mdx
website/content/docs/commands/job/validate.mdx

Fixes #6758
Fixes #1749
While the CLI has always supported running JSON jobs, its support has
been via HCLv2's JSON parsing. I have no idea what format it expects the
job to be in, but it's absolutely not in the same format as the API
expects.
So I ignored that and added a new -json flag to explicitly support *API*
style JSON jobspecs.

cli: add -json flag to support job commands

---

e2e/ui/run.sh

The E2E test runner is running from the root of the Nomad
repository. Make this run independent of the working directory for
convenience of developers and the test runner.
Unblocks https://github.com/hashicorp/nomad-e2e/pull/98

E2E: make UIs runnable from any working directory

---

e2e/disconnectedclients/disconnectedclients_test.go

We're logging inside the "eventually" loop, which means we're dumping way too much into the test logs. Move the dump so that it happens only when the "eventually" loop fails.

E2E: fix debug logging on disconnected clients test

---

command/volume_status_csi.go

Fixes panic demonstrated in [CircleCI workflow 32eb0f1f](https://app.circleci.com/pipelines/github/hashicorp/nomad-e2e/489/workflows/32eb0f1f-bd01-4e19-ade9-60d2fc03be29/jobs/2818). I'm not sure why this hadn't shown up previously and it's at least possible something is wrong in the volume API output, but regardless of what comes back from the API the CLI shouldn't panic.

CSI: handle nil topologies safely in command line

---

.changelog/12752.txt
client/allocrunner/taskrunner/plugin_supervisor_hook.go

Fixes https://github.com/hashicorp/nomad/issues/12744
The task runner hook `Prestart` response object includes a `Done`
field that's intended to tell the client not to run the hook
again. The plugin supervisor creates mount points for the task during
prestart and saves these mounts in the hook resources. But if a client
restarts the hook resources will not be populated. If the plugin task
restarts at any time after the client restarts, it will fail to have
the correct mounts and crash loop until restart attempts run out.
Fix this by not returning `Done` in the response, just as we do for
the `volume_mount_hook`.

CSI: plugin supervisor prestart should not mark itself done

---

jsconfig.json

Accidentally added while setting lint rules elsewhere. It already exists at /ui/jsconfig.json , so removing this one.

Removing the project root jsconfig.json

---

ui/app/controllers/evaluations/index.js
ui/app/routes/evaluations/index.js
ui/app/templates/evaluations/index.hbs
ui/tests/acceptance/evaluations-test.js

Resolves #12741
Resolves #12742
Fixes the 400 error that was being returned by the API and uses the new filter expression DSL.
Side Effect:
Conditional logic to generate error and no match copy.

bug:  fix filter and search

---

website/content/api-docs/json-jobs.mdx
website/content/docs/commands/job/run.mdx
website/content/docs/job-specification/hcl2/index.mdx

Did you know that Nomad has not 1 but 2 JSON formats for jobs? 2½ if you
want to acknowledge that sometimes our JSON job representations have a
Job top-level wrapper and sometimes do not.
The 2½ formats are:
```
1.   HCL JSON
2.   Input API JSON (top-level Job field)
2.5. Output API JSON (lacks top-level Job field)
```
`#2` is what our docs consider our API JSON. `#2.5` seems to be an
accident of history we can't fix with breaking API compatibility.
`#1` is an even more interesting accident of history: the `jobspec2`
package automatically detects if the input to Parse is JSON and switches
to a JSON parser. This behavior is undocumented, the format is
unspecified, and there is no official HashiCorp tooling to produce this
JSON from HCL. The plot thickens when you discover popular third …

docs: update json jobs docs

---

.changelog/12777.txt
api/jobs.go
api/jobs_test.go

The existing ParseHCL func didn't allow setting HCLv1=true.
ParseHCLOpts name matches other "with options" helper funcs like https://pkg.go.dev/github.com/hashicorp/nomad/api#CSIVolumes.ListSnapshotsOpts

api: add ParseHCLOpts helper method

---

e2e/disconnectedclients/disconnectedclients_test.go
e2e/e2eutil/input/disconnect-node.nomad
e2e/e2eutil/input/restart-node.nomad

The E2E tests for disconnected clients were disconnecting one of the clients before the initial deployment was complete. This triggered a replacement alloc on an unanticipated node. This PR adds a call to `e2eutil.WaitForLastDeploymentStatus` to ensure the deployment is complete before disconnecting the client.

e2e: Wait for deployment to finish before disconnect

---

.github/workflows/build-trigger.yml
.github/workflows/build.yml
.github/workflows/release.yml
.release/ci.hcl

The Nomad release process requires several files to be modified and committed back to the repo. Some of those changes are currently done manually (update `version.go`, add new entries to `CHANGELOG.md` etc.) and others are automated (call `make prerelease` to build the UI and other auto-generated code).
These changes are committed to the repo to provide users with a deterministic build from the release SHA, meaning that anyone building from that commit will always get the same binary regardless of external dependencies.
But these files are fairly large so we only commit them on release and never to the `main` branch.
For Nomad 1.3.0-beta.1, the release was created from a short-lived release branch specific to that version, but this is not the recommended pattern for CRT. The reason for …

ci: setup release process with CRT

---

.changelog/12807.txt
command/operator_debug.go
command/operator_debug_test.go

This PR introduces `go-version` constraint checks to avoid capturing the threadcreate pprof profile on Nomad versions 0.11.0 to 0.11.2.  The code to obtain the version number for a given server or node ID isn't pretty, but in lieu of a better method it should suffice for now.
Fixes #12804.

debug: add version constraint to avoid pprof panic

---

ui/app/templates/evaluations/index.hbs

Resolves #12763 
Horizontal scrollbar was happening by combination of .toolbar's negative margins, while being inside the .table-container for evaluations.
Elsewhere, this toolbar is outside the table container, causing no such break.

Moves the evaluations table toolbar outside of the table-container

---

website/content/docs/commands/volume/create.mdx

Fixes https://github.com/hashicorp/nomad/issues/12821
The capacity fields for `create volume` set bounds on the resulting
size of the volume, but the ultimate size of the volume will be
determined by the storage provider (between the min and max). Clarify
this in the documentation and provide a suggestion for how to set a
exact size.

docs: clarify `capacity_min/max` for volumes

---

website/content/docs/commands/index.mdx

The [posener/complete](https://github.com/posener/complete) package seems to automatically also support fish shell.  We should mention it in the docs.  I was about to go and roll my own autocomplete for fish but luckily it is already supported :)

docs: nomad can also install autocomplete for fish shell

---

ui/app/components/job-page/parts/task-groups.js
ui/app/components/task-group-row.js
ui/app/templates/components/job-page/parts/task-groups.hbs
ui/tests/helpers/module-for-job.js
ui/tests/pages/components/task-groups.js
ui/tests/pages/jobs/detail.js

Clicking in a task group row in the job details page would throw the
error:
```
Uncaught Error: You didn't provide enough string/numeric parameters to satisfy all of the dynamic segments for route jobs.job.task-group. Missing params: name
createParamHandlerInfo http://localhost:4646/ui/assets/vendor-194b1e0d68d11ef7a4bf334eb30ba74d.js:4814
applyToHandlers http://localhost:4646/ui/assets/vendor-194b1e0d68d11ef7a4bf334eb30ba74d.js:4804
applyToState http://localhost:4646/ui/assets/vendor-194b1e0d68d11ef7a4bf334eb30ba74d.js:4801
getTransitionByIntent http://localhost:4646/ui/assets/vendor-194b1e0d68d11ef7a4bf334eb30ba74d.js:4843
transitionByIntent http://localhost:4646/ui/assets/vendor-194b1e0d68d11ef7a4bf334eb30ba74d.js:4836
refresh …
```

ui: fix an error when navigating to a task group

---

nomad/drainer/draining_node.go
website/content/docs/commands/node/drain.mdx

Fixes https://github.com/hashicorp/nomad/issues/12835
In #12324 we made it so that plugins wait until the node drain is
complete, as we do for system jobs. But we neglected to mark the node
drain as complete once only plugins (or system jobs) remaining, which
means that the node drain is left in a draining state until the
`deadline` time expires. This was incorrectly documented as expected
behavior in #12324.
---
The new behavior shipped in 1.3.0-beta.1 but not yet in GA, so depending on when this can get merged we might not need a changelog entry for this one.

CSI: node drain should end once only plugins remain

---

website/content/docs/job-specification/constraint.mdx

This constraint and affinity was added in 0.9.x but was only
documented for affinities. Close that documentation gap.
(ref https://github.com/hashicorp/nomad/issues/5691#issuecomment-491894600)
Preview link: https://nomad-8dgktugzl-hashicorp.vercel.app/docs/job-specification/constraint#set_contains_any

docs: add missing `set_contains_any` constraint docs

---

client/allocrunner/taskrunner/task_runner.go
client/allocrunner/taskrunner/task_runner_test.go
client/lib/cgutil/group_killer.go
drivers/exec/driver.go

This PR modifies raw_exec and exec to ensure the cgroup for a task
they are driving still exists during a task restart. These drivers
have the same bug but with different root cause.
For raw_exec, we were removing the cgroup in 2 places - the cpuset
manager, and in the unix containment implementation (the thing that
uses freezer cgroup to clean house). During a task restart, the
containment would remove the cgroup, and when the task runner hooks
went to start again would block on waiting for the cgroup to exist,
which will never happen, because it gets created by the cpuset manager
which only runs as an alloc pre-start hook. The fix here is to simply
not delete the cgroup in the containment implementation; killing the
PIDs is enough. The removal happens in the cpuset manager later anyway. …

cgroups: make sure cgroup still exists after task restart

---

.changelog/12847.txt
ui/app/routes/evaluations/index.js
ui/tests/acceptance/evaluations-test.js

Chronological most-recent evals by default

---

.github/workflows/release.yml
.release/ci.hcl

During the release there are several files that need to be modified:
- .release/ci.hcl: the notification channel needs to be updated to a
channel with greater team visibility during the release.
- version/version.go: the Version and VersionPrerelease variables
need to be set so they match the release version.
After the release these files need to be reverted.
For GA releases the following additional changes also need to happen:
- version/version.go: the Version variable needs to be bumped to the
next version number.
- GNUMakefile: the LAST_RELEASE variable needs to be set to the
version that was just released.
Since the release process will commit file changes to the branch being
used for the release, it should _never_ run on main, so the first step
is now to protect against that.
It also …

ci: revert file changes and add some checks

---

.github/workflows/backport.yml

Remove the step to automatically backport `backport/website` PRs to the
latest release. This will be done manually by adding the proper tags.
Also use squash backports to match the pattern we use for `main`.

ci: update backport assitant workflow

---

website/content/docs/job-specification/template.mdx

The current public docs site is showing features for 1.3.x (from main branch) despite viewing the 1.2.x. I think the doc sites also needs to be adjusted to show a tag for 1.2, but until then, a version note should help out. A similar note is found in the documentation for the CLI service command which is also visible on the public site.

docs: add version note to nomad services template

---

CODEOWNERS

Backports are failing with an error about a lack of admin access - we suspect that this can be patched by adding the nomad service acct as a codeowner.

add service acct to codeowners for backport merging

---

ui/app/services/token.js
ui/tests/acceptance/proxy-test.js

This fixes an issue with Exec feature not working when a reverse proxy is used to automatically inject X-Nomad-Token.

Fix Exec not working with reverse proxy X-Nomad-Token

---

GNUmakefile

https://github.com/shoenig/hc-install/pull/2
Uses new version of hc-install which supports the new
json content type reported by api.releases.hashicorp.com

build: use new version of hc-install

---

website/content/docs/internals/scheduling/scheduling.mdx

We could definitely write more about it here, but I just wanted to get the smallest possible correction out first.

docs: add `sysbatch` to scheduling internals

---

website/data/docs-nav-data.json

I managed to remove this from the UI but missed it on the docs sidebar!

docs: remove beta tag for CSI from sidebar

---

ui/.percy.yml
ui/config/environment.js
ui/mirage/faker.js
ui/package.json

Resolves #12964
- Sets a seed on test fixtures to get visual diff tests running with the same dataset
- Removes percy-css (previous attempt at stabilization)
- Introduces a `USE_PERCY` environment variable that can be set for local runs, and `test:ember-seedless` to ~still run our test suite~ be run locally as needed with random data (but without Percy snapshots)
Our UI tests straddle a line between "Be reliable and idempotent" and "Catch bugs with randomization". Last week, when we pushed our Percy visual diff tests up, we opted to maintain randomized test data in order to allow for more potential style bugs to be found.
We overcame the random differences in tests by applying `percy-css` to our test config, that would grey-out all tables (the main sources of conflicting visuals). Not …

Visual diff tests seed-stabilized by default

---

go.mod
go.sum
helper/raftutil/msgtypes.go
nomad/encrypter.go
nomad/fsm.go
nomad/keyring_endpoint.go
nomad/secure_variables_endpoint.go
nomad/state/schema.go
nomad/state/state_store.go
nomad/state/state_store_restore.go
nomad/structs/secure_variables.go
nomad/structs/structs.go

This changeset is a mostly-empty implementation of the memdb schema and state store operations we'll need for https://github.com/hashicorp/nomad/issues/12802. 
Nothing here has gone through RFC review yet, so it'll likely need to be revised, but this can serve as a skeleton for us to do little spikes as part of the design process. Implementations are largely incomplete.

secure variables: initial state store

---

website/redirects.js

The shortlink /s/port-plan-failure is logged when a plan for a node is
rejected to help users debug and mitigate repeated `plan for node
rejected` failures.
The current link to #9506 is... less than useful. It is not clear to
users what steps they should take to either fix their cluster or
contribute to the issue.
While .[../monitoring-nomad#progess](https://www.nomadproject.io/docs/operations/monitoring-nomad#progress) isn't as comprehensive as it could
be, it's a much more gentle introduction to the class of bug than the
original issue.
(Thanks to @mmcquillan for pointing this out!)

docs: link s/port-plan-failure to more helpful doc

---

.changelog/12962.txt
command/agent/command.go

The log line comes before the agent logger has been setup,
therefore we need to use the UI logging to avoid panic.

agent: fix panic when logging about protocol version config use.

---

.changelog/13008.txt
scheduler/util.go
scheduler/util_test.go

Fixes https://github.com/hashicorp/nomad/issues/12963
No task driver with file system isolation can support updating mounts in-place. Host volume and CSI volume or volume mount additions or updates should therefore always be destructive.
---
This changeset includes some unit testing but I've manually tested it on real CSI volumes as well. Adding a new volume:
```
$ nomad job plan ./demo/csi/hostpath/redis.nomad
+/- Job: "example"
+/- Task Group: "cache" (1 create/destroy update)
+   Volume {
+ AccessMode:     "single-node-reader-only"
+ AttachmentMode: "file-system"
+ Name:           "volume0"
+ PerAlloc:       "true"
+ ReadOnly:       "true"
+ Source:         "test-volume"
+ Type:           "csi"
}
+/- Task: "redis" (forces in-place update)
```
Altering an existing volume:
```
$ nomad …
```

scheduler: volume updates should always be destructive

---

command/agent/http.go
command/agent/secure_variable_endpoint.go
command/agent/secure_variable_endpoint_test.go
go.mod
go.sum
helper/codec/inmem.go
nomad/mock/mock.go
nomad/secure_variable_mock.go
nomad/secure_variable_mock_test.go
nomad/secure_variables_endpoint.go
nomad/server.go
nomad/structs/secure_variables.go

This PR provides a minimal backend to test the secure variable API. 
⚠️ **Warning** ⚠️ 
Data in this mock backend will become irrational with leadership transitions, so it can not be used in any way other than to perform early work on the UI in a single node case.
- secure variables: initial state store (#12932)
- Add SecureVariable mock
- Add SecureVariableStub
- Add SecureVariable Copy and AsStub funcs
- Wire up secure variable mock interface
- Fix panic when not RPC endpoint not found

Provide mock secure variables implementation

---

.changelog/13012.txt
ui/app/models/job.js
ui/app/models/volume.js
ui/app/routes/jobs/job.js
ui/tests/acceptance/allocation-detail-test.js
ui/tests/acceptance/jobs-list-test.js
ui/tests/acceptance/regions-test.js
ui/tests/acceptance/task-detail-test.js
ui/tests/acceptance/topology-test.js

Resolves a bug where we were mis-identifying the namespace of jobs with the "@" character in their names.
Now, we explicitly link to @default for any namespace-less links to jobs, and specifically look for the last "@" in a job name to determine namespace.
Resolves #12986

12986 UI fails to load job when there is an "@" in job name in nomad 130

---

terraform/shared/scripts/setup.sh

"W: GPG error: http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A4B469963BF863CC"
NVidia rotated their repo keys, see https://forums.developer.nvidia.com/t/notice-cuda-linux-repository-key-rotation/212771

[terraform/aws] Fix NVidia GPG key error

---

contributing/testing.md

Add a note to the contributing guide pointing out that if you're
writing `api` package tests, you need to build a binary with any of
your changes.

docs: API package tests need a binary with your changes

---

ui/.percy.yml

Caused flakiness in our snapshot tests w/ Percy

Add a forgotten comma to snapshot-specific CSS

---

.changelog/12817.txt
client/allocrunner/taskrunner/task_runner.go

This fixes https://github.com/hashicorp/nomad/issues/12780
When https://github.com/hashicorp/nomad/pull/12021 was introduced, it doesn't actually work for the group -> network -> dns stanza. This PR finishes the work to get network.dns interpolation working, by actually using the interpolated DNS values.

Fix network.dns interpolation

---

ui/app/components/keyboard-shortcuts-modal.hbs
ui/app/services/keyboard.js
ui/app/styles/components/keyboard-shortcuts-modal.scss

- Changes to the modal style
- Ability to disable/enable keyboard nav. Only thing it won't disable is `?` and `ESC` to open/close the nav itself.
- TODO: save to localstorage for persistence

Make keyboard nav disableable

---

nomad/state/state_store.go
nomad/state/state_store_test.go
nomad/structs/secure_variables.go

Implement the basic upsert, list, and delete operations for `RootKeyMeta` needed by the Keyring RPCs.
This changeset also implements two convenience methods `RootKeyMetaByID` and `GetActiveRootKeyMeta` which are useful for testing but also will be needed to implement the rest of the RPCs.

keyring state store operations

---

.changelog/13070.txt
command/job_validate.go
command/job_validate_test.go
command/testdata/example-basic.nomad
command/testdata/example-vault.nomad
nomad/job_endpoint_hook_vault.go
testutil/server.go
website/content/docs/commands/job/validate.mdx

This PR fixes `job validate` to respect `-vault-token` and `$VAULT_TOKEN`
and `-vault-namespace` if set.
Fixes #13062
Only needs to backport to 1.3.x, when the refactoring happened.

cli: correctly validate job with vault token set

---

.changelog/13076.txt
command/agent/command.go

Fixes #13015.
There's no reason to buffer json logs on agent startup, since logs in this format already aren't reordered (see https://github.com/hashicorp/nomad/issues/13015#issuecomment-1129157784).
This PR adds an early `logGate.Flush()` where the UI implementation is swapped out for JSON logs, so they are no longer buffered.

Don't buffer json logs on agent startup

---

nomad/encrypter.go
nomad/keyring_endpoint.go
nomad/keyring_endpoint_test.go
nomad/server.go
nomad/structs/secure_variables.go

Implement the upsert, list, delete, and rotate RPC handlers for the
secure variables keyring. Operations on the keyring itself are still
stubbed out.
See draft PR https://github.com/hashicorp/nomad/pull/13077 for reference on the callers.

keyring RPC handlers

---

.changelog/13058.txt
drivers/docker/driver.go
drivers/docker/driver_test.go

This PR fixes a bug where the `CgroupParent` on the docker
`HostConfig` struct was accidentally being set when running in
cgroups v1 mode.
Fixes https://github.com/hashicorp/nomad/issues/13031

drivers/docker: do not set cgroup parent in v1 mode

---

.changelog/13104.txt
nomad/blocked_evals.go
nomad/blocked_evals_stats.go
nomad/blocked_evals_stats_test.go
nomad/structs/structs.go

This PR fixes blocked eval resource math. 
8506bd6b1 - the 1 line bug fix, where we now subtract off the correct eval
c3c739cab - added tests around eval math 
Fixes https://github.com/hashicorp/nomad/issues/12848
Backport to 1.3.x, 1.2.x

core: fix blocked eval math

---

api/keyring_test.go
command/agent/keyring_endpoint.go
command/agent/keyring_endpoint_test.go
nomad/encrypter.go
nomad/encrypter_test.go
nomad/keyring_endpoint.go
nomad/keyring_endpoint_test.go
nomad/server.go
nomad/state/state_store.go
nomad/structs/extensions.go
nomad/structs/secure_variables.go
nomad/testing.go

This changeset implements the keystore serialization/deserialization:
* Adds a JSON serialization extension for the `RootKey` struct, along with a metadata stub. When we serialize RootKey to the on-disk keystore, we want to base64 encode the key material but also exclude any frequently-changing fields which are stored in raft.
* Implements methods for loading/saving keys to the keystore.
* Implements methods for restoring the whole keystore from disk.
* Wires it all up with the `Keyring` RPC handlers and fixes up any fallout on tests.
Best reviewed commit-by-commit.

keystore serialization

---

website/content/docs/job-specification/service.mdx

Nomad errors out when attempting to specify a task for a service that uses consul connect but does not have script or gRPC checks. See https://github.com/hashicorp/nomad/blob/304d0cf5958065d14ab8b704055b1bb11d915876/nomad/structs/structs.go#L6643 for details.

Update service.check.task definition to match code

---

ui/app/components/secure-variable-form.hbs
ui/app/modifiers/autofocus.js
ui/app/styles/components/secure-variables.scss
ui/tests/integration/modifiers/autofocus-test.js

(Twig branch of #13069; resolves [13141](https://github.com/hashicorp/nomad/issues/13141))
- Introduces a new `autofocus` modifier for input elements
- Makes it so, when you add a new element to the variables/new form, its key is auto-focused for faster typing
- Slightly darken the focus state of the "Add more" button, as it was inaccessibly low-vis before

Autofocus modifier and better Add More button UX

---

ui/app/components/secure-variable-form.hbs
ui/app/components/secure-variable-form.js
ui/app/controllers/variables/new.js
ui/app/styles/components/secure-variables.scss
ui/jsconfig.json
ui/package.json
ui/tests/integration/components/secure-variable-form-test.js
ui/yarn.lock

(Twig branch of #13069; resolves #13128)
- Hides values in the values field by default (shows them as stars, default password field behaviour)
- Allows the ability to toggle show/hide of those fields
- Introduces HashiCorp's [Flight Icons](https://flight-hashicorp.vercel.app/) library. We'll probably move to this over x-icon across the app with time.
- Adds a target to our jsconfig to allow Glimmer type-checking to work. Otherwise, `//@ts-check` on ember files with `@action` or `get()` will throw type errors.
Default
Toggled

Secure Variables: show/hide functionality when adding new values

---

website/content/docs/drivers/docker.mdx

Something I ran into when trying this.

docs: make the example for 'load' work

---

website/content/tools/index.mdx

Nomad Pipeline is a tool I have been working on and using at work. It is a bit hacky but I thought it would be cool to have it in this list for others that might be looking for "pipelines on Nomad".

docs: add nomad-pipeline to community tools page

---

website/content/docs/integrations/vault-integration.mdx

The example `vault token create` command sets the `-period` flag but doesn't mention anything about the flag in the explanation afterwards.

Added note about -period flag for context

---

GNUmakefile
nomad/server.go
nomad/structs/network.go
nomad/structs/services.go
nomad/structs/structs.go

This version of golangci-lint improves support for generics, but also
is more strict in copy vs. loop for slice copying.

build: update golangci-lint to v1.46.2

---

nomad/core_sched.go

Almost all GC jobs check the index of the objects being GC'd to see if
they're older than a configured threshold. This code was repeated six
times in `CoreScheduler` with only logging changes, so it seems safe
to extract it as its own method.
Ran into this while working on 2 new core jobs for Secure Variables, so
this changeset will eliminate the need for 2 more repetitions of this function.

refactor index threshold calculation for core GC jobs

---

nomad/state/schema.go
nomad/state/state_store_secure_variables.go
nomad/state/state_store_secure_variables_test.go

The core jobs to garbage collect unused keys and perform full key
rotations will need to be able to query secure variables by key ID for
efficiency. Add an index to the state store and associated query
function and test.

provide state store query for variables by key ID

---

.changelog/13188.txt
ui/app/templates/components/job-page/parts/stats-box.hbs

This PR adds the total count of services from the `job` model to the `StatBox` in the Job Detail Overview page.

ui:  add service count to `StatBox`

---

api/keyring.go
api/keyring_test.go
command/agent/keyring_endpoint.go
command/agent/keyring_endpoint_test.go
nomad/encrypter.go
nomad/encrypter_test.go
nomad/keyring_endpoint.go
nomad/keyring_endpoint_test.go
nomad/leader.go
nomad/state/state_store.go
nomad/structs/extensions.go
nomad/structs/secure_variables.go

After internal design review, we decided to remove exposing algorithm
choice to the end-user for the initial release. We'll solve nonce
rotation by forcing rotations automatically on key GC (in a core job,
not included in this changeset). Default to AES-256 GCM for the
following criteria:
* faster implementation when hardware acceleration is available
* FIPS compliant
* implementation in pure go
* post-quantum resistance

remove end-user algorithm selection

---

nomad/config.go
nomad/core_sched.go
nomad/core_sched_test.go
nomad/leader.go
nomad/structs/structs.go

Inactive and unused keys older than a threshold will be periodically
garbage collected.
This changeset only implements the GC job and not the full key rotation
job in order to keep the PR size reasonable. The configuration values are
not exposed in this PR either, as I'd like to do the whole configuration
as a single PR once we've got some of the remaining keyring items finished.

core job for root key GC

---

.changelog/13182.txt
client/fingerprint/arch.go
client/fingerprint/host.go
website/content/docs/runtime/interpolation.mdx

first attempt at classic cpu architecture names while fingerprinting the cpu.
ref: #13181 
Note as mentioned in the issue, I am fine if folks can come up with a name different that "classic" :)

fingerprint kernel architecture name

---

.changelog/13205.txt
scheduler/reconcile_util.go
scheduler/reconcile_util_test.go

This PR fixes a bug where an evicted batch job would not be rescheduled
once resources become available.
Intuition: previously the scheduler would filter an alloc that was evicted but its tasked completed successfully. The problem is that that tasks were stopped _because_ of the eviction stop signal, not because they had run to completion. Such an alloc needs to be queued to run again.
Closes #9890

core: reschedule evicted batch job when resources become available

---

ui/app/router.js
ui/app/templates/components/job-page/parts/stats-box.hbs
ui/app/templates/components/job-subnav.hbs

This PR adds `/services` as a nested route within the `/jobs/:jobId` hierarchy.
Side Effect:  Update `StatsBox` to link to `/jobs/:jobId/services` and add Services link to `JobSubnav`.
This PR intentionally does not add:  Route, Controller or Template for `/services`. That will be handled in the following in #13200.
Expectation:
Actual:
Note:  there's a discrepancy between `Services` value. Currently, we list a `Services ${servicesLength}` instead of `Services ${servicesLength} services`. Will iron this out with Design later on.

ui:  create `/services` nested route within `/jobs/:jobId` hierarchy

---

website/content/docs/drivers/docker.mdx

When I first read the docs, it wasn't clear to me what `docker.volumes.enabled` refers to. I'm proposing this minor addition of a link to (hopefully) make it more obvious.
I know that the name probably refers more to the way it's represented in the dot-separated hierarchy of the client attributes (along with other fingerprinted data), but the relationship between those and the agent HCL configuration wasn't clear to me at first.

docs: link to client reqs section for added clarity

---

client/allochealth/tracker.go
client/allocrunner/alloc_runner_test.go

This is a minor change in the error message to aid with debugging.
When I first looked at the message it wasn't entirely clear to me what it means and how I could address it. I knew that the task was healthy for far longer than 10s but wasn't aware of `healthy_deadline` stanza until I have read the docs.

client/allochealth: add healthy_deadline as context to error messages

---

command/agent/http.go
command/agent/http_test.go
website/content/api-docs/index.mdx

Adds support for reading ACL token from the [RFC6750](https://tools.ietf.org/html/rfc6750) Bearer token (`Authorization: Bearer <token>`).
The code samples / documentation were taken from Consul:
https://github.com/hashicorp/consul/blob/973d2d0f9a2d32f6f3eae506c2b5b89f98007b58/agent/http.go#L1021-L1041
https://github.com/hashicorp/consul/blob/1d817f683a4922756db44b991428cd5f582ea6ae/website/content/api-docs/index.mdx
Background behind this is I'm using prometheus static_config to scrape metrics from nomad and the [static_config configuration doesn't support custom headers, only authorization tokens](https://github.com/prometheus/prometheus/issues/1724). This would allow me to properly embed and use the token.
I have yet to test the locally, but will update here when I have a chance to do. …

parse ACL token from authorization header

---

nomad/state/state_store.go
nomad/state/state_store_test.go

When deleting evaluations and allocations during a reap event, the
index table entries for evals and allocs was updated irregardless
of whether changes were made.
This change modifies the state logic so that the index table is
only modified when the corresponding table has actually been
modified. Along with matching expected behaviour, this change has
the potential to reduce the number of times blocking queries will
return without any real state change.

state: only update index on change when deleting evals.

---

nomad/encrypter.go
nomad/encrypter_test.go
nomad/leader.go
nomad/server.go

Replication for the secure variables keyring. Because only key
metadata is stored in raft, we need to distribute key material
out-of-band from raft replication. A goroutine runs on each server and
watches for changes to the `RootKeyMeta`. When a new key is received,
attempt to fetch the key from the leader. If the leader doesn't have
the key (which may happen if a key is rotated right before a leader
transition), try to get the key from any peer.

keyring replication

---

e2e/consultemplate/consultemplate.go

The test has failed on/off recently and therefore this extends to wait period in hopes to fix this.

e2e: use longer wait in template update triggers to avoid flake.

---

.changelog/13055.txt
client/allocrunner/alloc_runner.go
client/allocrunner/alloc_runner_test.go
client/allocrunner/task_hook_coordinator.go
client/allocrunner/taskrunner/task_runner_getters.go

Closes #10340
This PR addresses a defect where sidecar tasks are stopped prior to their associated main task being successfully stopped. This can create problems in scenarios where the main task can take a long time to shut down, but still need their sidecars to be operational while they finish their shutdown task (e.g. Consul Connect proxy). 
This fix includes the following changes:
- Adds the `IsSidecarTask` helper method.
- Refactors other helpers to use `IsSidecarTask`.
- Updates the doc string on the `hasSidecarTasks` method to correctly describe the behavior of the function.
- Modifies the second kill loop in `allocRunner.killTasks` to skip shutting down sidecar tasks. This allows the existing logic in `allocHandler.handleTaskStateUpdates` to shutdown sidecars after the main task …

alloc_runner: stop sidecar tasks last

---

command/agent/secure_variable_endpoint.go

If an inbound payload doesn't contain `Items` collection, we should skip writing it and return an error.

SV HTTP API: skip empty variables

---

api/keyring.go
command/commands.go
command/operator_secure_variables_keyring.go

Command line for secure variables keyring commands. 
Most of these don't really work until https://github.com/hashicorp/nomad/pull/13124 and https://github.com/hashicorp/nomad/pull/13167 are merged, but here's the results of use with a server that's running a build with those PRs.
---
Example operations:
```
$ nomad operator secure-variables keyring -list
Key       Active  Algorithm  Create Time
46c35471  true    xchacha20  2022-05-27T20:23:27Z
$ nomad operator secure-variables keyring -rotate
Key       Active  Algorithm  Create Time
d8b6351c  true    xchacha20  2022-05-27T20:23:56Z
$ nomad operator secure-variables keyring -list -verbose
Key                                   Active  Algorithm  Create Time
46c35471-141b-4e18-0e7e-bfb7b304d47f  false   xchacha20  2022-05-27T20:23:27Z …
```

keyring command line

---

ui/app/components/secure-variable-form.hbs
ui/app/styles/components/secure-variables.scss
ui/tests/integration/components/secure-variable-form-test.js

Resolves #13178 
- Still allows you to edit the path when editing at /new
- Disallows path editing on existing variables

Disable path input when model is not new

---

website/content/docs/job-specification/group.mdx

`heartbeat_grace` is a `server` parameter, not a `client` parameter.

docfix: `heartbeat_grace` is a `server` parameter

---

.changelog/12800.txt
drivers/qemu/driver.go
website/content/docs/drivers/qemu.mdx

When enabled, this will add the necessary virtual hardware and create a `qemu-guest-agent.sock` file in the task's working directory for interacting with the agent, which must be running in the VM to work. 
https://wiki.qemu.org/Features/GuestAgent

Add `guest_agent` config option for QEMU driver

---

.changelog/13301.txt
nomad/csi_endpoint.go
nomad/csi_endpoint_test.go

Fixes https://github.com/hashicorp/nomad/issues/13264
If the node has been GC'd or is down, we can't send it a node
unpublish. The CSI spec requires that we don't send the controller
unpublish before the node unpublish, but in the case where a node is
gone we can't know the final fate of the node unpublish step.
The `csi_hook` on the client will unpublish if the allocation has
stopped and if the host is terminated there's no mount for the volume
anyways. So we'll now assume that the node has unpublished at its
end. If it hasn't, any controller unpublish will potentially hang or
error and need to be retried.
(Note that while this behavior isn't ideal, it appears to match user
expectations and the behavior reported by k8s users.)

CSI: skip node unpublish on GC'd or down nodes

---

go.mod
go.sum
helper/funcs.go
helper/funcs_test.go
helper/pointer/pointer.go
helper/pointer/pointer_test.go

This PR deprecates some functions in favor of generic alternatives.
The new functions are compatible only with Nomad v1.4+.
The old functions (and their use) should not be removed until Nomad v1.6+.
emphasis on DO NOT BACKPORT

helpers: provide a few generic helper functions

---

.circleci/config.yml

If PATH comes first, an older version of Go is used that cannot install
dependencies that use features of newer versions of Go, which we just
installed.

build: rearrange go path order on windows

---

.semgrep/rpc_endpoint.yml
client/allocrunner/interfaces/task_lifecycle.go
client/allocrunner/taskrunner/identity_hook.go
client/allocrunner/taskrunner/task_runner.go
client/allocrunner/taskrunner/task_runner_getters.go
client/allocrunner/taskrunner/task_runner_hooks.go
client/allocrunner/taskrunner/template/template.go
client/allocrunner/taskrunner/template_hook.go
go.mod
go.sum
nomad/acl.go
nomad/encrypter.go
nomad/encrypter_test.go
nomad/plan_apply.go
nomad/secure_variables_endpoint.go
nomad/secure_variables_endpoint_test.go
nomad/server.go
nomad/service_registration_endpoint.go
nomad/service_registration_endpoint_test.go
nomad/structs/generate.sh
nomad/structs/structs.go

In order to support implicit ACL policies for tasks to get their own
secrets, each task would need to have its own ACL token. This would
add extra raft overhead as well as new garbage collection jobs for
cleaning up task-specific ACL tokens. Instead, Nomad will create a
workload Identity Claim for each task.
An Identity Claim is a JSON Web Token (JWT) signed by the server’s
private key and attached to an Allocation at the time a plan is
applied. The encoded JWT can be submitted as the X-Nomad-Token header
to replace ACL token secret IDs for the RPCs that support identity
claims.
Whenever a key is is added to a server’s keyring, it will use the key
as the seed for a Ed25519 public-private private keypair. That keypair
will be used for signing the JWT and for verifying the JWT.
This …

workload identity

---

website/content/docs/configuration/client.mdx

This PR addresses two issues:
- The language for the `max_stale` setting contained out of date "by default" language relative to the new default behavior.
- The `wait` language was clarified to remove a confusing "by default" statement when explaining how Consul Template works.

template: improve default language for max_stale and wait

---

ui/app/components/secure-variable-form.hbs
ui/app/components/secure-variable-form.js
ui/app/controllers/variables/variable/edit.js
ui/app/styles/components/secure-variables.scss
ui/app/templates/variables/new.hbs
ui/app/templates/variables/variable/edit.hbs
ui/tests/integration/components/secure-variable-form-test.js

Secure Variables form validation improvements

---

website/content/docs/commands/system/gc.mdx

Thanks to @tbehling for pointing out how incomplete these docs were. I had forgotten `system gc` ignores the server's `threshold` configuration!
Rendered:

docs: explain behavior of system gc command

---

.changelog/13340.txt
api/tasks.go
client/allocrunner/taskrunner/plugin_supervisor_hook.go
command/agent/job_endpoint.go
jobspec/parse_task.go
jobspec/parse_test.go
jobspec/test-fixtures/csi-plugin.hcl
nomad/structs/csi.go
nomad/structs/structs.go
website/content/docs/job-specification/csi_plugin.mdx

Fixes #13179 
Test results: Configured health_timeout as `5m` and introduced an artificial error to make sure Portworx was killed after 5m:
```
Recent Events:
Time                  Type                     Description
2022-06-10T20:05:40Z  Killed                   Task successfully killed
2022-06-10T20:05:40Z  Terminated               Exit Code: 2, Exit Message: "Docker container exited with non-zero exit code: 2"
2022-06-10T20:05:40Z  Killing                  CSI plugin did not become healthy before configured 5m0s health timeout
2022-06-10T20:05:40Z  Plugin became unhealthy  Error: CSI plugin failed probe: timeout while connecting to gRPC socket: failed to stat socket: stat /etc/nomad.d/client/csi/plugins/62bdddd8-3955-92d2-cc23-02b6f6204e62/csi.sock: no such file or directory …
```

CSI: make plugin health_timeout configurable in csi_plugin stanza

---

client/client.go

Implemented originally for https://github.com/hashicorp/nomad/issues/12261 but this was reported not to fix their problem. However, it does appear to be a legitimate race that's possible to hit.

client: wait for create index when deriving vault token

---

command/commands.go
command/operator_secure_variables_keyring.go
command/operator_secure_variables_keyring_install.go
command/operator_secure_variables_keyring_list.go
command/operator_secure_variables_keyring_remove.go
command/operator_secure_variables_keyring_rotate.go

Split the flag options for the `secure-variables keyring` into their
own subcommands. The gossip keyring CLI will be similarly refactored
and the old version will be deprecated.
I've also fixed the totally inconsistent `-help` text output, which I was doing like
a bash script instead of like the rest of Nomad for some reason 😊 
```
$ nomad operator secure-variables keyring list
Key       Active  Create Time
448b6b7a  true    2022-06-13T19:23:24Z
$ nomad operator secure-variables keyring list -verbose
Key                                   Active  Create Time
448b6b7a-764e-dcf3-8a8f-d4f8dcd66f26  true    2022-06-13T19:23:24Z
$ nomad operator secure-variables keyring rotate
Key       Active  Create Time
b690c5f8  true    2022-06-13T19:23:36Z
$ nomad operator secure-variables keyring remove …
```

keyring CLI: refactor to use subcommands

---

.github/workflows/build.yml

These flags were not being used because GNUmakefile overwrites them with
another value. We also don't want to set `-s -w` since they remove
information that is important for production debug.
In other projects this variable is used to override the default `-dev`
prerelease that is set even if `VersionPrerelease` is empty, but in
Nomad this check is never actually done because this conditional in
`version/version.go` is always false:
```go
func GetVersion() *VersionInfo {
// ...
rel := VersionPrerelease
// ...
if GitDescribe == "" && rel == "" && VersionPrerelease != "" {
rel = "dev"
}
// ...
}
```
This seems like some leftover from a previous release process, but I
decided the leave the code as is.

ci: remove step that generates GO_LDFLAGS

---

.changelog/13340.txt

The changelog entry for #13340 indicated it was an improvement. But on
discussion, it was determined that this was a workaround for a
regression. Update the changelog to make this clear.

fixup changelog entry for backported regression fix

---

website/content/tools/autoscaling/index.mdx

Improve Autoscaler overview

---

ui/app/components/variable-paths.js
ui/app/controllers/variables/variable/index.js
ui/app/models/variable.js
ui/app/routes/variables/path.js
ui/app/utils/compact-path.js
ui/app/utils/path-tree.js
ui/tests/unit/utils/compact-path-test.js
ui/tests/unit/utils/path-tree-test.js

- Moves folder compaction (listing folder "foo" in a directory as "foo/bar" when it only has one child descendent named "bar") to render time instead of compute time
- Removes secondary functions from the Path Tree util (compact paths, pathToObject) and standardizes its types
In practice, this lets you traverse the directory tree structure for variables at a compacted path without issue.
So if you have a single variable at `a/b/c/d/e/myVar`, you previously would only be able to see anything at `a/b/c/d/e`; now you could traverse to `a/b/c` if you so chose, and `d/e/` would be listed therein.

Path Tree compaction refactor

---

ui/app/components/secure-variable-form.js
ui/app/controllers/application.js
ui/app/router.js
ui/app/routes/variables.js
ui/app/styles/core.scss
ui/app/styles/core/notifications.scss
ui/app/templates/application.hbs
ui/package.json
ui/tests/helpers/flash-message.js
ui/yarn.lock

Global notification state that persists across routing change (you can fire a notification and redirect the user and the notification will stay)
- Progress bar toggleable on/off
- can either have a duration or be "sticky"
- Currently allow for only error and success states but extensible

Toast-style global notification state

---

ui/app/components/two-step-button.js
ui/app/controllers/variables/variable/index.js
ui/app/templates/variables/variable/index.hbs

This PR removes the `Edit` `LinkTo` component from the template when the `Delete` button is clicked.
Side Effect:  This PR updates the `TwoStepButton` component API to accept an `onPrompt` callback function to be fired with the `promptForConfirmation` action and adds logic for the `onCancel` callback function to be fired when the `TwoStepButton` registers on outside click event.

ui:  update  component api to accept callback fns to be fired on cancel/prompt

---

ui/app/components/secure-variable-form.hbs
ui/app/components/secure-variable-form.js
ui/app/components/secure-variable-form/input-group.hbs
ui/app/components/secure-variable-form/input-group.js
ui/tests/integration/components/secure-variable-form-test.js

Enable `SecureVariableForm` to allow users to specify if the `value` in a key-value pair input group is obscured instead of obscuring all key-value pairs in the form.

ui:  make eye toggles only toggle on/off for their respective row

---

nomad/encrypter.go
nomad/encrypter_test.go
nomad/secure_variables_endpoint.go
nomad/structs/secure_variables.go

The `Encrypt` method generates an appropriately-sized nonce and uses
that buffer as the prefix for the ciphertext. This keeps the
ciphertext and nonce together for decryption, and reuses the buffer as
much as possible without presenting the temptation to reuse the
cleartext buffer owned by the caller.
We include the key ID as the "additional data" field that's used as an
extra input to the authentication signature, to provide additional
protection that a ciphertext originated with that key.
Refactors the locking for the keyring so that the public methods are
generally (with one commented exception) responsible for taking the
lock and then inner methods are assumed locked.
Also fixes a bug where we forgot to check the bytes read from cryptorand
when generating our encryption key.

implement Encrypt/Decrypt methods of encrypter

---

acl/acl.go
acl/acl_test.go
acl/policy.go
acl/policy_test.go
nomad/acl.go
nomad/secure_variables_endpoint.go
nomad/secure_variables_endpoint_test.go
nomad/service_registration_endpoint.go

Adds a new policy block inside namespaces to control access to secure
variables on the basis of path, with support for globbing.
Adds a notion of implied policies for workload identities, where we'll
check for policies that might exist with particular well-known names,
and apply those policies to storage RPCs if they exist.
Refactors how we verify the token for the service registration RPCs so
that we can reuse the verification method. Best reviewed
commit-by-commit.

secure variables ACL policies

---

.changelog/13428.txt
client/allocrunner/networking_bridge_linux.go

CNI changed how to bring up the interface in v0.2.0.
Support was moved to a new loopback plugin.
https://github.com/containernetworking/cni/pull/121
Fixes  #10014

cni: add loopback to linux bridge

---

command/commands.go
command/operator_gossip_keyring.go
command/operator_gossip_keyring_generate.go
command/operator_gossip_keyring_install.go
command/operator_gossip_keyring_list.go
command/operator_gossip_keyring_remove.go
command/operator_gossip_keyring_test.go
command/operator_gossip_keyring_use.go
command/operator_keyring.go

Move all the gossip keyring and key generation commands under
`operator gossip keyring` subcommands to align with the new `operator
secure-variables keyring` subcommands. Deprecate the `operator keyring`
and `operator keygen` commands.
---
Examples in use:
```
$ nomad operator gossip keyring list
Gathering installed encryption keys...
Key
oN9/woSOTb5adzIEnudgNRpsKu02EZaaIsb2MvR4ifw=
$ nomad operator keyring -list
nomad operator keyring is deprecated and will be removed in Nomad 1.5.0.
Use nomad operator gossip keyring
Gathering installed encryption keys...
Key
oN9/woSOTb5adzIEnudgNRpsKu02EZaaIsb2MvR4ifw=
$ nomad operator gossip keyring install $(nomad operator gossip keyring generate)
Installing new gossip encryption key...
$ nomad operator gossip keyring install $(nomad operator keygen) …
```

move gossip keyring command to their own subcommands

---

nomad/config.go
nomad/core_sched.go
nomad/core_sched_test.go
nomad/leader.go
nomad/structs/structs.go

Extend the GC job to support periodic key rotation.
Update the GC process to safely support signed workload identity. We
can't GC any key used to sign a workload identity. Finding which key
was used to sign every allocation will be expensive, but there are not
that many keys. This lets us take a conservative approach: find the
oldest live allocation and ensure that we don't GC any key older than
that key.

core job for periodic key rotation

---

ui/app/components/secure-variable-form.js
ui/app/models/variable.js
ui/mirage/config.js
ui/tests/acceptance/secure-variables-test.js
ui/tests/integration/components/variable-paths-test.js
ui/tests/pages/variables.js
ui/tests/test-helper.js

Resolves #13393
1. Compacts items (key/values) by filtering out those with no key/value
2. Throws an error message to the user if they attempt to save a Secure Variable with no items

Throw an error if you try to save a Secure Variable with no items

---

ui/app/components/secure-variable-form.hbs
ui/app/components/secure-variable-form.js

Resolves #13394
Appends an empty row to the end of your Items array when you modify an existing Secure Variable.
This ensures that all previous rows are deletable, and with https://github.com/hashicorp/nomad/pull/13424, will compact/remove empty items on save.

Append an empty item when editing an existing Secure Variable

---

ui/app/abilities/variable.js
ui/mirage/factories/token.js

This PR updates the logic in `policiesSupportVariableCreation` to read the capabilities of the Secure Variables wildcard and updates the ACL Token to add `create` permissions.
This is a developer environment improvement PR.

dx:  update `canCreate` logic and token generation for secure var dev environment

---

.changelog/13405.txt
command/deployment_fail.go
command/deployment_promote.go
command/deployment_resume.go
command/deployment_unblock.go
command/job_promote.go

Closes: #13382
This PR includes fixes to several CLI commands that are not handling the detach flag correctly. In each case, the command should be printing an Eval ID before exiting. The affected commands are:
- `deployment fail`
- `deployment promote`
- `deployment resume`
- `deployment unblock`
- `job promote`

cli: fix detach handling

---

command/agent/config.go
nomad/encrypter.go
nomad/server.go

Add fields for configuring root key garbage collection. Fix the
keystore path so that we write to a tempdir when in dev mode.

secure variable server configuration

---

.changelog/13446.txt
client/allocrunner/csi_hook.go
client/allocrunner/csi_hook_test.go

Closes #13038
This PR fixes a bug in the CSI hook's validation logic. Previously, the `claimVolumesFromAlloc` function would iterate over each volume request, and then within that loop iterate over each task in the task group. If any of the tasks in the group did not support volumes the entire validation would fail. 
This PR fixes that by:
- Moving the inspection of tasks in the group out side of the volume request loop (optimization).
- Changing the validation logic to ensure that at least one task supports volumes rather than requiring that all support volumes.

csi_hook: valid if any driver supports csi

---

website/content/docs/operations/metrics-reference.mdx

I'm not attached to this PR, so we can throw it out if you think trying to cram in more details about a subtle metrics only confuses things further.
Also I didn't see how best to format long content in mdx tables, so we can throw it out based purely on ugliness of source. :sweat_smile: A `Metrics Codex` where we could actually write more than one sentence for a metric would be nice as I feel we end up relying on engineer's memory and code spelunking to get any nuanced meaning for metrics.

docs: clarify total_escaped is just an optimization

---

acl/acl_test.go

This changeset includes some additional unit tests for secure
variables ACL policies, so that we have explicit coverage of edge
cases we're discussing with the UI folks.

additional ACL Policy tests

---

.changelog/13407.txt
nomad/plan_apply.go
nomad/plan_endpoint_test.go
nomad/state/state_store.go

The plan applier has to get a snapshot with a minimum index for the
plan it's working on in order to ensure consistency. Under heavy raft
loads, we can exceed the timeout. When this happens, we hit a bug
where the plan applier blocks waiting on the `indexCh` forever, and
all schedulers will block in `Plan.Submit`.
Closing the `indexCh` when the `asyncPlanWait` is done with it will
prevent the deadlock without impacting correctness of the previous
snapshot index.
---
Note for reviewers: the test code here can't actually exercise this bug,
because there's no interface for us to introduce this timeout. But this
code path was not covered by unit testing, so with these tests we at least
exercise the normal state.
6fab937 is how we verified the behavior and that the fix works, but we'll
want to …

fix deadlock in plan_apply

---

ui/app/abilities/variable.js
ui/tests/unit/abilities/variable-test.js

This PR is one of two PRs that will unblock [13447](https://github.com/hashicorp/nomad/pull/13447).
This PR specifically handles namespace filtering when handling path matching.

ui:  handle namespace filtering for capabilities check

---

api/api.go
api/api_test.go

Just minor cleanup to use `T.Setenv` instead of `os.Setenv` + `defer`.

api: use testing.T.Setenv to set env vars in tests

---

.changelog/13493.txt
nomad/structs/alloc.go
nomad/structs/alloc_test.go

When calculating a services namespace for registration, the code
assumed the first task within the task array would include a
service block. This is incorrect as it is possible only a latter
task within the array contains a service definition.
This change fixes the logic, so we correctly search for a service
definition before identifying the namespace.
closes https://github.com/hashicorp/nomad/issues/13483

client: fixed a problem calculating a service namespace.

---

website/content/docs/job-specification/task.mdx

Closes #9986
This PR expands the documentation for the `task.leader` field to explain the impact on shutdown processing. The issue suggests providing an explanation of `lifecycle`, but I've opted to link out to existing documentation rather than duplicating the text in multiple places.

docs: update task leader to explain shutdown sequence.

---

ui/app/abilities/variable.js
ui/tests/unit/abilities/variable-test.js

This PR creates a private method on the Variable Ability class to mirror the special glob matching algorithm used by the Nomad API (a standalone [Go module](https://github.com/ryanuber/go-glob)).
This PR is the second to last step in the UI being able to match the way the Nomad API computes a path's capabilities.

ui:  glob matching algorithm

---

nomad/structs/structs.go

It appears way back when this was first implemented in
9a917281af9c0a97a6c59575eaa52c5c86ffc60d, it was renamed from
NodeEvict (with a correct comment) to NodeUpdate. The comment was
changed from referring to only evictions to referring to "all allocs" in
the first sentence and "stop or evict" in the second.
This confuses every time I see it because I read the name (NodeUpdate)
and first sentence ("all the allocs") and assume this represents *all*
allocations... which isn't true.
I'm going to assume I'm the only one who doesn't read the 2nd sentence
and that's why this suboptimal wording has lasted 7 years, but can we
change it for my sake?

docs: fix Plan{,Result}.NodeUpdate comment

---

.changelog/12862.txt
command/agent/service_registration_endpoint.go
command/agent/service_registration_endpoint_test.go
go.mod
go.sum
nomad/service_registration_endpoint.go
nomad/service_registration_endpoint_test.go
nomad/structs/errors.go
nomad/structs/service_registration.go
nomad/structs/service_registration_test.go
website/content/api-docs/services.mdx

This PR adds the `?choose` query parameter to the `/v1/service/<service>` endpoint.
The value of `choose` is in the form `<number>|<key>`, number is the number
of desired services and key is a value unique but consistent to the requester
(e.g. `allocID`).
Folks aren't really expected to use this API directly, but rather through `consul-template` / `template` block
which will soon be getting a new helper function making use of this query parameter.
Example,
```shell
curl 'localhost:4646/v1/service/redis?choose=2|abc123'
```
Part of https://github.com/hashicorp/nomad/issues/12575
Because this also includes updating CT, the `template` part works now as well.

api: enable selecting subset of services using rendezvous hashing

---

ui/app/routes/jobs/job/services.js
ui/app/styles/core/tag.scss
ui/app/templates/jobs/job/services.hbs

This PR creates a dummy template. Notably, missing from the table is the `Number of Allocations` column. We're currently unsure if this column is tenable given the API schema for services lists `AllocID:  string` instead of `Allocations: string[]`. The API schema per NMD-130 suggests there's a one-to-one relationship which will require some clarity.
Expected:
Actual:

ui:  create dummy template for `jobs/:jobId/services` route

---

helper/boltdd/boltdd.go
helper/boltdd/boltdd_test.go

This PR adds 2 helper functions to the `helpers/bbolt` package
- `Iterate`: iterate every key in a bucket starting with prefix. Automatically decodes the
msg pack value into the provided value argument.
- `DeletePrefix`: deletes every key in a bucket starting with a
given prefix. Manages the wrapper's hash values accordingly. Uses
a cursor & sync to operate efficiently.
Need these changes for nomad service check persistence stuff, but pulled into a separate PR because I got carried away cleaning up these tests.

boltdd: add iterate and prefix deletion helpers

---

ui/app/abilities/variable.js
ui/app/templates/variables/index.hbs
ui/app/templates/variables/path.hbs
ui/app/templates/variables/variable/index.hbs
ui/mirage/factories/token.js
ui/tests/unit/abilities/variable-test.js

This PR reflects that capabilities have the following names:  `["write", "read", "destroy", "list"]`.
Originally, we designed around capabilities having the names:  `["create", "read", "edit", "delete", "list"]` per the original RFC.
Side Effect:  minor update to `rules` in `Token` factory to match `rulesJSON`.

refact:  update capability names

---

nomad/alloc_endpoint.go
nomad/alloc_endpoint_test.go
nomad/job_endpoint.go

In #13606 the ACL check was refactored to better support the all
namespaces wildcard (`*`). This commit applies the changes to the jobs
and alloc list endpoints.

api: apply new ACL check for wildcard namespace

---

website/content/docs/integrations/vault-integration.mdx

Should the capability for "sys/capabilities-self" be read? From the comment above, it seems like we shouldn't need "update" as a capability if only checking is required.

Update sys/capabilties-self to read only

---

ui/app/abilities/variable.js
ui/app/components/secure-variable-form.hbs
ui/app/components/secure-variable-form/input-group.hbs
ui/app/templates/variables/index.hbs
ui/app/templates/variables/path.hbs
ui/app/templates/variables/variable/index.hbs
ui/mirage/factories/token.js
ui/tests/acceptance/secure-variables-test.js
ui/tests/unit/abilities/variable-test.js

This PR is one of two PRs that will unblock  [#13447](https://github.com/hashicorp/nomad/pull/13447).
This PR specifically handle path matching when there is no exact match. However, this PR is not in use because there will be a follow-up PR for integrating namespaces as part of the path matching process.

ui:  handle path matching

---

api/internal/testutil/discover/discover.go
api/internal/testutil/server.go

When running an API test in a debugger, the tests immediately "PASS" rather than run. This is because the discover code attempts to run the debug test executable _**as**_ the Nomad binary, which errors and then ends in the Skip pathway.

Fix Testutil for delve debugging API tests

---

ui/app/abilities/variable.js
ui/app/components/secure-variable-form.hbs
ui/app/components/secure-variable-form/input-group.hbs
ui/app/templates/variables/index.hbs
ui/app/templates/variables/path.hbs
ui/app/templates/variables/variable/index.hbs
ui/mirage/factories/token.js
ui/tests/acceptance/secure-variables-test.js
ui/tests/unit/abilities/variable-test.js

This PR creates logic for the `canCreate` permission, updates templates to properly check for this ability.
Closes [#13435](https://github.com/hashicorp/nomad/issues/13435).
Side Effect:  Update `Token` factory to enable `blue/berkshire` path to have `create` ability by default.
Enabled:
Disabled:

ui:  create variable permission logic

---

.changelog/13472.txt
command/operator_debug.go

The `operator debug` command doesn't output the leader anywhere in the
output, which adds extra burden to offline debugging (away from an
ongoing incident where you can simply check manually). Query the
`/v1/status/leader` API but degrade gracefully.

query for leader in `operator debug` command

---

.circleci/config.yml

Got an email from Circle about removing the version we are currently
using; bump to the latest stable version
https://circleci.com/docs/2.0/testing-ios
```
We’re reaching out to you to let you know that we have deprecated the following macOS images on CircleCI and will be removing them from our platform on Tuesday, August 2, 2022:
Xcode 10.3.0
Xcode 11.4.1
Xcode 11.5.0
Xcode 11.6.0
Xcode 12.0.1
Xcode 12.1.1
Xcode 12.2.0
Xcode 12.3.0
Xcode 12.4.0
In the last four weeks, you have used the above images on the following project(s):
nomad
```

build: bump circleci macos version

---

ui/app/models/variable.js
ui/app/serializers/variable.js

Otherwise, we'd get an unmarshall error on save, and/or an invalid date on tables in the UI.

Handling createTime and modifyTime through serialization now that they contain nanoseconds

---

api/secure_variables.go
api/secure_variables_test.go

- SV API: Go API
- Fix Testutil for delve debugging API tests
- Updates to API
- SV: Go API: Working state

WIP: Secure Variables: Go API

---

.changelog/12955.txt
nomad/node_endpoint.go
nomad/node_endpoint_test.go

Whenever a node joins the cluster, either for the first time or after
being `down`, we emit a evaluation for every system job to ensure all
applicable system jobs are running on the node.
This patch adds an optimization to skip creating evaluations for system
jobs not in the current node's DC. While the scheduler performs the same
feasability check, skipping the creation of the evaluation altogether
saves disk, network, and memory.

core: emit node evals only for sys jobs in dc

---

.changelog/13265.txt
drivers/docker/network.go
website/content/docs/drivers/docker.mdx

This PR tweaks the behavior of Nomad's Docker driver during network setup.
When Nomad sets up a new Docker network, it establishes the network namespace by running a "no-op" container, internally called `InfraImage`.  By default the container's image is `gcr.io/google_containers/pause-amd64:3.1` (where `amd64` is the GOARCH).
Every time a network is set up, that container image is pulled from the Google Container Registry (or alternate image, if configured).  In a cluster with a high rate of Nomad job creation, the Docker pull is seen to intermittently fail (about 0.4%), perhaps due to rate limiting or normal transient network problems.
Because this image is versioned (tagged `3.1`, currently), it is not necessary to run a Docker pull on every use.  This PR proposes a refinement to the …

driver/docker: Don't pull InfraImage if it exists

---

.changelog/13581.txt
command/eval.go
command/eval_delete.go
command/eval_list.go
command/eval_status.go
website/content/docs/commands/eval/delete.mdx
website/content/docs/commands/eval/list.mdx
website/content/docs/commands/eval/status.mdx

Use the same output format when listing multiple evals in the `eval
list` command and when `eval status <prefix>` matches more than one
eval.
Include the eval namespace in all output formats and always include the
job ID in `eval status` since, even `node-update` evals are related to a
job.
Add Node ID to the evals table output to help differentiate
`node-update` evals.

cli: improve output of eval commands

---

api/keyring.go
api/keyring_test.go
command/agent/keyring_endpoint.go
command/agent/keyring_endpoint_test.go
command/operator_secure_variables_keyring.go
nomad/config.go
nomad/core_sched.go
nomad/core_sched_test.go
nomad/encrypter.go
nomad/fsm.go
nomad/keyring_endpoint.go
nomad/keyring_endpoint_test.go
nomad/leader.go
nomad/state/state_store.go
nomad/state/state_store_test.go
nomad/structs/secure_variables.go
nomad/structs/structs.go

When the `Full` flag is passed for key rotation, we kick off a core
job to decrypt and re-encrypt all the secure variables so that they
use the new key.

core job for secure variables re-key

---

.git-blame-ignore-revs

Mainly an excuse to experiment with .git-blame-ignore-revs

ignore b0a20b4dc965a38b0c843f47c16685ccad7439da

---

.changelog/13658.txt
command/operator_snapshot_state.go
helper/raftutil/fsm.go
helper/raftutil/snapshot.go
helper/snapshot/snapshot.go
nomad/fsm.go
scheduler/benchmarks/helpers_test.go

This changeset implements two improvements to restoring FSM snapshots from archives:
* The existing implementation decompresses the archive to a temporary file before reading it in to the FSM. For large snapshots this performs a lot of disk IO. Stream decompress the snapshot as we read it, without first writing to a temporary file. This also moves some of the work to a second core.
* Add bexpr filters to the `RestoreFromArchive` helper. The operator can pass these as `-filter` arguments to `nomad operator snapshot state` (and other commands in the future) to include only desired data when reading the snapshot.
Deferred for this PR: the `nomad operator snapshot state` command still has to load everything that's been filtered into the FSM before writing it out to a large JSON blob. We …

snapshot restore-from-archive streaming and filtering

---

.github/workflows/build.yml
.release/ci.hcl

This is a CI-only change that opts nomad into a new workflow in the CRT pipeline called fossa-scan. The fossa-scan workflow will pass regardless of any dependency licensing issues raised by fossa, but failures will be raised in #proj-oss-compliance-scanning. This will allow us to triage issues to share with the legal team, who will reach out to nomad directly if there are questions about any dependencies. 
The fossa-scan workflow ran on the first commit here https://github.com/hashicorp/nomad/runs/7240033075 and this produced the fossa report available here https://app.fossa.com/projects/custom+23027%2fgithub.com%2fhashicorp%2fnomad/refs/branch/master/58c8bccf87515d09e56d78dce91389f25f38e659. The scan raised a few new issues that the legal team will look into here: …

[CI-only] Support fossa scanning

---

.changelog/10808.txt
.changelog/13679.txt
ui/app/controllers/csi/volumes/index.js
ui/app/controllers/jobs/index.js
ui/app/controllers/optimize.js
ui/app/services/system.js
ui/app/templates/csi/volumes/index.hbs
ui/app/templates/jobs/index.hbs
ui/app/templates/optimize.hbs
ui/tests/acceptance/jobs-list-test.js
ui/tests/acceptance/optimize-test.js
ui/tests/acceptance/volumes-list-test.js

Removes the "namespace" query parameter between routes (jobs, optimize, volumes) to keep that filter isolated (you may not want to filter across all entity types).
This more closely aligns to the behaviour of our current Evaluations page

Remove namespace cache

---

api/api_test.go
api/evaluations_test.go

When running the `api` tests in parallel the following panics could
happen:
```
--- FAIL: TestEvaluations_List (1.62s)
panic: runtime error: index out of range [0] with length 0 [recovered]
panic: runtime error: index out of range [0] with length 0
goroutine 114 [running]:
testing.tRunner.func1.2({0x7e6a80, 0xc00001c1c8})
/usr/local/go/src/testing/testing.go:1389 +0x24e
testing.tRunner.func1()
/usr/local/go/src/testing/testing.go:1392 +0x39f
panic({0x7e6a80, 0xc00001c1c8})
/usr/local/go/src/runtime/panic.go:838 +0x207
github.com/hashicorp/nomad/api.TestEvaluations_List(0xc0001ac680)
/home/vagrant/src/hashicorp/nomad-oss/api/evaluations_test.go:78 +0x765
testing.tRunner(0xc0001ac680, 0x843220)
/usr/local/go/src/testing/testing.go:1439 +0x102
created by testing.(*T).Run …
```

test: fix panics in api package

---

scripts/vagrant-linux-unpriv-ui.sh

Remove other versions of Node installed in nvm to avoid issues where the
CI runner uses the wrong one.

ci: remove any other versions of Node installed

---

nomad/secure_variables_endpoint.go
nomad/structs/secure_variables.go

**ACL check namespace value in SecureVariable**
Since the RPC endpoint can handle multiple variables in a single Upsert and they could target different namespaces, we need to check the ACL permissions per update.
**Error on wildcard namespace**
Guards against someone having NOMAD_NAMESPACE or the namespace flag set to `*` on a write.

SV: fixes for namespace handling

---

nomad/secure_variables_endpoint_test.go

In OSS we can upsert an allocation without worrying about whether that
alloc is in a namespace that actually exists, but in ENT that upsert
will add to the namespace's quotas. Ensure we're doing so in this
secure variables RPC test to fix the test breaking in the ENT repo.

secure vars: fix enterprise test by upserting the namespace

---

.changelog/13651.txt
command/agent/agent.go
command/agent/command.go
nomad/structs/funcs.go
nomad/structs/network.go
nomad/structs/network_test.go
nomad/structs/structs.go
scheduler/context_test.go
scheduler/feasible.go
scheduler/propertyset.go
scheduler/rank.go
scheduler/rank_test.go
website/content/docs/configuration/client.mdx

Fixes #13505
This fixes #13505 by treating reserved_ports like we treat a lot of jobspec settings: merging settings from more global stanzas (`client.reserved.reserved_ports`) "down" into more specific stanzas (`client.host_networks[].reserved_ports`).
As discussed in #13505 there are other options, and since it's totally broken right now we have some flexibility:
1. Treat overlapping `reserved_ports` on addresses as invalid and refuse to start agents. However, I'm not sure there's a cohesive model we want to publish right now since so much 0.9-0.12 compat code still exists! We would have to explain to folks that if their `-network-interface` and `host_network` addresses overlapped, they could only specify reserved_ports in one place or the other?! It gets ugly.
2. Use the global …

core: merge reserved_ports into host_networks

---

.changelog/13421.txt
command/agent/agent.go
command/agent/agent_test.go
command/agent/config.go
command/agent/config_parse.go
command/agent/config_parse_test.go
command/agent/config_test.go
command/agent/testdata/basic.hcl
command/agent/testdata/basic.json
command/agent/testdata/sample0.json
command/agent/testdata/sample1/sample0.json
nomad/config.go
nomad/plan_apply.go
nomad/plan_apply_node_tracker.go
nomad/plan_apply_node_tracker_test.go
nomad/server.go
nomad/state/state_store.go
nomad/structs/structs.go
website/content/docs/configuration/server.mdx
website/content/docs/operations/metrics-reference.mdx
website/content/docs/operations/monitoring-nomad.mdx

Plan rejections occur when the scheduler work and the leader plan
applier disagree on the feasibility of a plan. This may happen for valid
reasons: since Nomad does parallel scheduling, it is expected that
different workers will have a different state when computing placements.
As the final plan reaches the leader plan applier, it may no longer be
valid due to a concurrent scheduling taking up intended resources. In
these situations the plan applier will notify the worker that the plan
was rejected and that they should refresh their state before trying
again.
In some rare and unexpected circumstances it has been observed that
workers will repeatedly submit the same plan, even if they are always
rejected.
While the root cause is still unknown this mitigation has been put in
place. The plan …

Track plan rejection history and automatically mark clients as ineligible

---

.semgrep/fsm_time.yml

See `message:` in rule for details.
This catches a few uses that should be cleaned up:
```
$ semgrep scan -c .semgrep/fsm_time.yml nomad
... 
nomad/fsm.go
semgrep.no-time-in-fsm
time.Now() should not be called from within the Server's FSM. Apply Raft log messages to the
State Store must be deterministic so that each server contains exactly the same state. Since
time drifts between nodes, it must be set before the Raft log message is applied so that all
Raft members see the same timestamp.
568┆ Launch:    time.Now(),
nomad/state/state_store.go
semgrep.no-time-in-fsm
time.Now() should not be called from within the Server's FSM. Apply Raft log messages to the
State Store must be deterministic so that each server contains exactly the same state. Since
time drifts between nodes, it must be set …
```

Add semgrep rule to catch non-determinism in FSM

---

helper/funcs.go
nomad/acl_endpoint.go
nomad/acl_endpoint_test.go
nomad/state/indexer/indexer.go
nomad/state/indexer/indexer_test.go
nomad/state/indexer/time.go
nomad/state/indexer/time_test.go
nomad/state/schema.go
nomad/state/state_store_acl.go
nomad/state/state_store_acl_test.go
nomad/structs/acl.go
nomad/structs/acl_test.go
nomad/structs/structs.go
nomad/structs/structs_test.go

The ACL token state schema has been updated to utilise two new
indexes which track expiration of tokens that are configured with
an expiration TTL or time. A new state function allows listing
ACL expired tokens which will be used by internal garbage
collection.
The ACL endpoint has been modified so that all validation happens
within a single function call. This is easier to understand and
see at a glance. The ACL token validation now also includes logic
for expiry TTL and times. The ACL endpoint upsert tests have been
condensed into a single, table driven test.
There is a new token canonicalize which provides a single place
for token canonicalization, rather than logic spread in the RPC
handler.

core: add ACL token expiry state, struct, and RPC handling.

---

ui/app/models/job.js
ui/app/models/task-group.js
ui/app/models/task.js
ui/app/models/variable.js
ui/app/routes/variables.js
ui/app/serializers/job.js
ui/app/templates/allocations/allocation/task/index.hbs
ui/app/templates/components/job-page/parts/stats-box.hbs
ui/app/templates/jobs/job/task-group.hbs
ui/tests/acceptance/secure-variables-test.js

Adds a relationship between a job and variables, defined by any variables that are prefixed with that job's name.
Further adds a model property of `pathLinkedVariable` for all jobs, task groups, and tasks, that look for an exact match against their (or their parent job's) variables. Displays this in the details bar:

13553 secure vars linked from jobs

---

ui/app/components/secure-variable-form.hbs
ui/app/components/secure-variable-form.js
ui/app/components/secure-variable-form/namespace-filter.hbs
ui/app/components/secure-variable-form/namespace-filter.js
ui/app/components/single-select-dropdown/index.hbs
ui/app/styles/components/secure-variables.scss
ui/mirage/factories/variable.js
ui/tests/acceptance/secure-variables-test.js

This PR handles setting a namespace in the create secure variables form.
Actual:
Figma:

ui:  allow namespaces to be set in forms

---

helper/testlog/testlog.go

A minor improvement to make server logs in testing outputs more readable, which I ran into while debugging https://github.com/hashicorp/nomad/pull/13749
Before:
> node-2832022-07-13T12:57:04.242Z [INFO]  raft@v1.3.5/raft.go:369: nomad.raft: entering leader state: leader="Node at 127.0.0.1:9268 [Leader]"
After:
> node-283 2022-07-13T12:57:04.242Z [INFO]  raft@v1.3.5/raft.go:369: nomad.raft: entering leader state: leader="Node at 127.0.0.1:9268 [Leader]"

tests: add a space between node name and timestamp

---

nomad/state/state_store.go

Fixes https://github.com/hashicorp/nomad/pull/13725 for the secure variables keyring. This hasn't shipped in a release of Nomad, so that's why it's in its own PR with no changelog.

keyring: upserting key metadata in FSM must be deterministic

---

nomad/acl.go
nomad/acl_test.go
nomad/structs/errors.go

This commit adds basic expiry checking when performing ACL token
resolution. This expiry checking is local to each server and does
not at this time take into account potential time skew on server
hosts.
A new error message has been created so clients whose token has
expired get a clear message, rather than a generic token not
found.
The ACL resolution tests have been refactored into table driven
tests, so additions are easier in the future.
This is the simpler of two potential approaches, the second of
which I will raise an issue to track as a potential future
enhancement. This followup includes a new leader loop that watches
for ACL token table changes and maintains a heap of expiring tokens
so that the leader can set expiry authoritatively. There is significant
overhead in this approach …

acl: add token expiry checking to ACL token resolution.

---

.release/linux/postrm

Fixes #13739
This restarts the nomad systemd unit after the nomad package is updated
Documentation on how the postrm/upgrade event is handled can be found [here](https://www.debian.org/doc/debian-policy/ch-maintainerscripts.html#details-of-unpack-phase-of-installation-or-upgrade)

packaging: restart nomad service after package update

---

website/content/docs/operations/metrics-reference.mdx

- Remove mention of 0.9 from 1.1.x and newer docs
- Improve client allocation status metrics
Inspired by #13759

Improve metrics reference documentation

---

nomad/core_sched.go
nomad/core_sched_test.go
nomad/leader.go
nomad/leader_test.go
nomad/state/state_store_acl.go
nomad/state/state_store_acl_test.go
nomad/structs/acl.go
nomad/structs/structs.go

Two new periodic core jobs have been added which handle removing
expired local and global tokens from state. The local core job is
run on every leader; the global core job is only run on the leader
within the authoritative region.

core: add expired token garbage collection periodic jobs.

---

nomad/secure_variables_endpoint.go
nomad/secure_variables_endpoint_test.go
nomad/structs/secure_variables.go
nomad/structs/secure_variables_test.go

Tasks are automatically granted access to variables on a path that matches their
workload identity, with a well-known prefix. Change the prefix to `nomad/jobs`
to allow for future prefixes like `nomad/volumes` or `nomad/plugins`. Reserve
the prefix by emitting errors during validation.

secure vars: rename automatically accessible vars path for jobs

---

go.mod
go.sum
nomad/service_registration_endpoint.go

This PR is a little experiment / demo of using [go-set](https://github.com/hashicorp/go-set) to replace the use of `map[T]struct{}` as a make-shift set.

cleanup: example refactoring out map[string]struct{} using set.Set

---

ui/app/components/secure-variable-form.hbs
ui/app/components/secure-variable-form.js
ui/app/models/job.js
ui/app/models/task-group.js
ui/app/models/task.js
ui/app/models/variable.js
ui/mirage/scenarios/default.js
ui/tests/acceptance/secure-variables-test.js
ui/tests/unit/models/variable-test.js

Updates references to `/jobs` for path-linked-entities to `nomad/jobs/`, and disallows anything like `nomad/foo/` from letting you submit your job.
---
---

Change path-linked-variables to start with nomad/jobs/, instead of jobs/

---

.changelog/13621.txt
command/agent/http.go
command/agent/http_test.go
website/content/docs/operations/metrics-reference.mdx

The `limits.http_max_conns_per_client` configuration option sets a limit on the max number of concurrent TCP connections per client IP address:
https://github.com/hashicorp/nomad/blob/0b3ba5c77cc3ecc62bd380bcd2d52d272cf49c8c/website/content/docs/configuration/index.mdx#L197-L200
The current implementation behavior silently closes the TCP connection, resulting in opaque 'unexpected EOF' or 'connection reset' errors which many users fail to correctly diagnose, and is likely the root cause of various reported Nomad issues.
Instead of silently closing the connection, this PR returns a `429 Too Many Requests` HTTP response with a helpful error message to aid debugging when the connection limit is unintentionally reached. This should help diagnose/fix some instances of #12273 and #8718, where …

Return 429 response on HTTP max connection limit

---

website/content/docs/configuration/server.mdx

Document the server config options that control core jobs for encryption key rotation.

docs: document secure variables server config options

---

command/operator_secure_variables_keyring_install.go
website/content/docs/commands/operator/gossip/keyring-generate.mdx
website/content/docs/commands/operator/gossip/keyring-install.mdx
website/content/docs/commands/operator/gossip/keyring-list.mdx
website/content/docs/commands/operator/gossip/keyring-remove.mdx
website/content/docs/commands/operator/gossip/keyring-use.mdx
website/content/docs/commands/operator/keygen.mdx
website/content/docs/commands/operator/keyring.mdx
website/content/docs/commands/operator/secure-variables/keyring-install.mdx
website/content/docs/commands/operator/secure-variables/keyring-list.mdx
website/content/docs/commands/operator/secure-variables/keyring-remove.mdx
website/content/docs/commands/operator/secure-variables/keyring-rotate.mdx
website/data/docs-nav-data.json

Document the secure variables keyring commands, document the aliased
gossip keyring commands, and note that the old gossip keyring commands
are deprecated.

docs: keyring commands

---

api/keyring.go
command/operator_secure_variables_keyring.go
nomad/keyring_endpoint_test.go
nomad/structs/secure_variables.go

Most of our objects use int64 timestamps derived from `UnixNano()` instead of
`time.Time` objects. Switch the keyring metadata to use `UnixNano()` for
consistency across the API.

keyring: use nanos for `CreateTime` in key metadata

---

acl/acl.go
acl/acl_test.go
command/agent/search_endpoint_test.go
nomad/search_endpoint.go

The search RPC used a placeholder policy for searching within the secure
variables context. Now that we have ACL policies built for secure variables, we
can use them for search. Requires a new loose policy for checking if a token has
any secure variables access within a namespace, so that we can filter on
specific paths in the iterator.

search: use secure vars ACL policy for secure vars context

---

nomad/encrypter_test.go
nomad/plan_apply.go
nomad/secure_variables_endpoint.go
nomad/secure_variables_endpoint_test.go
nomad/structs/structs.go

Workload identities grant implicit access to policies, and operators
will not want to craft separate policies for each invocation of a
periodic or dispatch job. Use the parent job's ID as the JobID claim.
Tagging @philrenaud just as an FYI, as he noticed this problem.

workload identity: use parent ID for dispatch/periodic jobs

---

command/agent/config.go

` nomad agent -dev` should be super fast now

client: use test timeouts for network fingerprinters in dev mode

---

.changelog/13869.txt
nomad/structs/structs.go

87ef5178d1111b092ffa86be46b0caaff8638027: some cleanup to use `set` in the `validateServices` function 
0cc18331058f7ff8d14907f2f71d0870d4515e87: track uniqueness of services in `validateServices` function 
Fixes #13814
Closes #13836 - This PR went in the other direction - to _support_ groups with services that had the same <name, task|group, port_label>. The change is gnarly - basically we would need to add something like a hash of the tags of a service to the unique ID generated by `MakeAllocationServiceID` - which is then used as an index in the state store. All services with tags would be given new IDs, causing unwanted churn in large clusters. The benefit doesn't come close to justifying the means, so I'm going to abandon the feature and just validate the intrinsic invariant we …

servicedisco: ensure service uniqueness in job validation 

---

.changelog/13880.txt
nomad/state/state_store.go
nomad/state/state_store_test.go

When we delete a namespace, we check to ensure that there are no non-terminal
jobs, which effectively covers evals, allocs, etc. CSI volumes are also
namespaced, so extend this check to cover CSI volumes.
We'll also need to add this check for Secure Variables, but this is in a separate
PR because it'll need to be backported.

block deleting namespaces if the namespace contains a volume

---

nomad/state/state_store.go
nomad/state/state_store_secure_variables.go
nomad/state/state_store_test.go

When we delete a namespace, we check to ensure that there are no non-terminal
jobs or CSI volume, which also covers evals, allocs, etc. Secure variables are
also namespaces, so extend this check to them as well.

block deleting namespace if it contains a secure variable

---

ui/tests/acceptance/secure-variables-test.js
ui/tests/integration/components/secure-variable-form-test.js

We made a change to our markup in this commit [84401fe](https://github.com/hashicorp/nomad/pull/13618/commits/84401fe72f43869f31964569dc354e79ed2a6e12). Some of our tests are brittle and aren't taking advantage of `data-test-attributes` and relied on CSS selector that are dependent on the order of our markup causing the tests to fail.

chore:  update tests

---

ui/app/components/keyboard-shortcuts-modal.hbs
ui/app/components/keyboard-shortcuts-modal.js
ui/tests/acceptance/keyboard-test.js
ui/tests/pages/layout.js

Adds tests for general Keyboard nav usage:
- Dynamic tables
- Dynamic keynav (arrow keys)
- Shortcuts modal
- Hints
- Shortcuts enable/disable
- Shortcuts re-binding
- Shortcuts from localStorage

Keyboard Navigation acceptance tests

---

website/Makefile

When working in a podman environment, it's convenient to run the website development container using podman.

website: enable setting custom tool for launching website dev container

---

client/logmon/server.go
drivers/docker/docklog/docker_logger.go
drivers/docker/docklog/docker_logger_test.go
drivers/docker/docklog/server.go
drivers/docker/handle.go
drivers/shared/executor/grpc_server.go
go.mod
plugins/base/server.go
plugins/device/server.go
plugins/drivers/server.go

The `golang.org/x/net/context` package was merged into the stdlib as of go
1.7. Update the imports to use the identical stdlib version. Clean up import
blocks for the impacted files to remove unnecessary package aliasing.
(Note we still have a transitive dependency, but removing our copy will help.)

deps: remove deprecated net/context

---

drivers/docker/driver_test.go

OOM detection under cgroups v2 is flaky under versions of `containerd` before
v1.6.3, but our `containerd` dependency is transitive on `moby/moby`, who have
not yet updated. Disable this test for cgroups v2 environments until we can
update the dependency chain.
---
This removes the test flake from https://github.com/hashicorp/nomad/issues/13119, but we should leave that issue open even after this merges. The underlying problem is in the OOM detection and not in the test code.
On cgroups v2:
```
root@jammy# NOMAD_TEST_LOG_LEVEL=warn go test -v -count=1 ./drivers/docker -run TestDockerDriver_OOMKilled
=== RUN   TestDockerDriver_OOMKilled
=== PAUSE TestDockerDriver_OOMKilled
=== CONT  TestDockerDriver_OOMKilled
docker.go:36: Successfully connected to docker daemon running version 20.10.17 …
```

test: disable docker OOM detection test on cgroups v2

---

command/agent/agent_test.go

Fixes https://github.com/hashicorp/nomad/issues/13720
This test is a fairly trivial test of the agent RPC, but the test setup waits
for a short fixed window after the node starts to send the RPC. After looking at
detailed logs for recent test failures, it looks like the node registration for
the first node doesn't get a chance to happen before we make the RPC call. Use
`WaitForResultUntil` to give the test more time to run in slower test
environments, while allowing it to finish quickly if possible.

fix flaky `TestAgent_ProxyRPC_Dev` test

---

go.mod
go.sum

Upgrading to v0.3.0 gives us the ability to add more context to test case failures.
examples in 
https://github.com/shoenig/test/pull/23

deps: update test package

---

ui/app/abilities/variable.js
ui/app/templates/variables/path.hbs
ui/app/templates/variables/variable/index.hbs
ui/tests/acceptance/secure-variables-test.js
ui/tests/unit/abilities/variable-test.js

This PR adds namespaces to the path matching algorithm. Previously, we were expecting a set namespace to look up paths based upon like we do for jobs. However, that same logic does not apply for secure variables and because we're not setting a namespace like we do with jobs. Instead, we're doing a dictionary lookup based upon each individual namespace on a secure variable and secure variables can belong to the same hierarchy but have different namespaces.

add namespace to path matching algorithm

---

website/content/api-docs/quotas.mdx

The example path in the quota API docs doesn't match the path in the actual API (or the table above it).

docs: fix path for quota/usage API

---

ui/app/components/secure-variable-form.js

Closes [#13855](https://github.com/hashicorp/nomad/issues/13855).
Sets the default dropdown option when the component is invoked to be based on the `Variable` model.

refact: default dropdown option based on model

---

client/serviceregistration/checks/client_test.go
helper/funcs.go
helper/funcs_test.go
nomad/structs/services.go
nomad/structs/services_test.go

Unblock `check.method` in service validation. Add tests around making sure this value gets plumbed through.
Part of https://github.com/hashicorp/nomad/issues/13945

nsd: add support for specifying check.method in nomad service checks

---

ui/mirage/factories/variable.js

[ui] Variables: time formats in mirage mocks should match server-returned microsecond time

---

drivers/docker/driver_test.go

Revert "Backport of test: disable docker OOM detection test on cgroups v2 into release/1.1.x"

---

drivers/docker/driver_test.go

Revert "Backport of test: disable docker OOM detection test on cgroups v2 into release/1.2.x"

---

.changelog/13991.txt
ui/app/routes/variables/new.js

Resolves an issue where you don't have access to the `default` namespace but do have the ability to create variables on one of your other namespaces.
This is a very basic fix that prevents most cases from erroring on save, or showing a problem form state (see below image). A more robust fix would be to parse through your policy to see which namespaces have `write` access for Secure Variables.

New variable creation adds the first namespace in your available list at variable creation time

---

client/serviceregistration/checks/client.go
client/serviceregistration/checks/client_test.go
client/serviceregistration/checks/result.go
nomad/structs/services.go
nomad/structs/services_test.go

This PR enables setting of the headers block on services registered
into Nomad's service provider. Works just like the existing support
in Consul checks.
Part 2 of #13945

nsd: add support for setting headers on nomad service http checks

---

website/content/docs/job-specification/hcl2/functions/datetime/formatdate.mdx

The `timestamp` HCL2 function was never part of the set of supported
functions.

docs: remove link to HCL2 `timestamp` function

---

.changelog/14000.txt
drivers/qemu/driver.go

When a QEMU task is recovered the monitor socket path was not being
restored into the task handler, so the `graceful_shutdown` configuration
was effectively ignored if the client restarted.

qemu: restore monitor socket path

---

.changelog/14001.txt
nomad/deploymentwatcher/deployment_watcher.go
nomad/deploymentwatcher/deployments_watcher_test.go

fixes #8150 
One thing I'm not 100% about this is if the test is correct.  If I'm reading everything from copy/pasting the other one and understanding the data model this _should_ "just work," because we're never setting `c3` to healthy, so that should test this exact bit of logic (where we want 2 healthy canaries, have 3 placed, and only 2 are ever promoted to healthy).

allow unhealthy canaries without blocking autopromote

---

.changelog/13971.txt
drivers/qemu/driver.go
drivers/qemu/driver_bsd.go
drivers/qemu/driver_fallback.go
drivers/qemu/driver_linux.go
drivers/qemu/driver_test.go
go.mod
go.sum
website/content/docs/drivers/qemu.mdx

The QEMU driver can take an optional `graceful_shutdown` configuration
which will create a Unix socket to send ACPI shutdown signal to the VM.
Unix sockets have a hard length limit and the driver implementation
assumed that QEMU versions 2.10.1 were able to handle longer paths. This
is not correct, the linked QEMU fix only changed the behaviour from
silently truncating longer socket paths to throwing an error.
By validating the socket path before starting the QEMU machine we can
provide users a more actionable and meaningful error message, and by
using a shorter socket file name we leave a bit more room for
user-defined values in the path, such as the task name.
The maximum length allowed is also platform-dependant, so validation
needs to be different for each OS.

qemu: reduce monitor socket path

---

.changelog/13996.txt
ui/app/abilities/variable.js
ui/tests/unit/abilities/variable-test.js

In order to determine if you should list variables / be able to access the variables route at all, check against all your policies' namespaces' secvars' paths' capabilties to see if any of them contain `write`, `read`, `list`, or `destroy` capabilities (in other words, any of the possible capabilities).
If any of your paths, from within any of your namespaces' SecureVariables blocks, contains any of those abilities, you get a link to the route in your nav.
Created a generic lookup function to pave the way for future lookups along the lines of `can view variable` etc.

[ui] "can list variables" capability refactor

---

website/data/docs-nav-data.json
website/data/plugins-nav-data.json

Replaces the `<sup>` tags in nav data JSON files with a `badge` property. This is a new feature in DevDot, introduced in https://github.com/hashicorp/dev-portal/pull/562. Each badge has `type="outlined"` and `color="neutral"`.
Asana task: [[Nomad] Remove `<sup>` tags from nav data](https://app.asana.com/0/1202097197789424/1202707964020090/f)

Use badge for <sup> tags in nav data JSON files

---

ui/app/abilities/variable.js
ui/tests/unit/abilities/variable-test.js

This PR addresses matching namespaces when a namespace glob is used.
Closes [14034](https://github.com/hashicorp/nomad/issues/14034).
Reference:  https://learn.hashicorp.com/tutorials/nomad/access-control-policies

refact:  namespace glob matching

---

README.md

The CI badge is always red but not actually indicative of anything (well, other than we have a flaky test problem). The MPL badge helps emphasize Nomad is open source.
- Remove Circle CI badge
- Add MPL license badge 
- Remove link to deprecated google groups

docs: minor readme tweaks

---

ui/app/templates/variables/index.hbs
ui/app/templates/variables/path.hbs
ui/tests/acceptance/secure-variables-test.js

Currently we show the wrong error message to users when they are filtering variables by namespace making them falsely believe that there are no variables or paths. We need a better error message that is consistent with how this behavior is handled in the rest of the Nomad UI.
Closes [13974](https://github.com/hashicorp/nomad/issues/13974)

ui:  handle error messages for when filtering doesn't return matches

---

nomad/structs/structs_test.go
scheduler/feasible_test.go
scheduler/generic_sched_test.go

https://pkg.go.dev/testing#T.Fatalf
> Fatalf is equivalent to Logf followed by FailNow.
see https://go.dev/play/p/I6MX-QOTC9n for example:
```go
package main
import (
"testing"
)
func TestLastIndex(t *testing.T) {
t.Errorf("first line")
t.Errorf("second line")
t.Fatalf("t.Fatalf will cause exit")
t.Fatalf("so this line cant reach")
}
/* output:
=== RUN   TestLastIndex
prog.go:8: first line
prog.go:9: second line
prog.go:10: t.Fatalf will cause exit
--- FAIL: TestLastIndex (0.00s)
FAIL
Program exited.
*/
```

fix minor unreachable code caused by t.Fatal

---

.release/ci.hcl

Manual backport of https://github.com/hashicorp/nomad/pull/13815.

[manual backport] introduces the post publish website event

---

helper/raftutil/msgtypes.go
nomad/fsm.go
nomad/fsm_test.go
nomad/mock/mock.go
nomad/state/schema.go
nomad/state/state_store_acl.go
nomad/state/state_store_acl_test.go
nomad/state/state_store_restore.go
nomad/state/state_store_restore_test.go
nomad/structs/acl.go
nomad/structs/acl_test.go
nomad/structs/structs.go

This commit includes the new state schema for ACL roles along with
state interaction functions for CRUD actions.
The change also includes snapshot persist and restore
functionality and the addition of FSM messages for Raft updates
which will come via RPC endpoints.

core: add ACL role state schema and functionality.

---

.changelog/13996.txt
ui/app/abilities/variable.js
ui/app/components/variable-paths.hbs
ui/app/components/variable-paths.js
ui/app/controllers/variables/variable.js
ui/app/routes/variables/variable.js
ui/app/styles/components/secure-variables.scss
ui/app/templates/variables/variable.hbs
ui/mirage/config.js
ui/mirage/factories/token.js
ui/mirage/factories/variable.js
ui/mirage/scenarios/default.js
ui/tests/acceptance/secure-variables-test.js
ui/tests/integration/components/variable-paths-test.js
ui/tests/unit/abilities/variable-test.js

Resolves #13744 
---
- Adds a path/namespace-aware check for whether individual variables can be accessed via the ui: links become unclickable and not-link-coloured.
- Adds an Unauthorized banner if you do end up on a variable page for which you do not have access (403). Say, you copied it from your machine where you have management access, and you sent it to your network-connected, touchscreen-enabled fridge and clicked it via the tiny touchpad. In this scenario you now have the ability to scowl at your kitchen appliance and read instructions for contacting your administrator.
- Made clickable links, both folders and files, blue and underlined to emphasize the difference. (cc @juliezzhou who suggested it)
- Breadcrumb creation in the variables/variable controller now depends on `params` …

[ui] "Can Read" checks on individual Secure Variables

---

ui/app/abilities/variable.js
ui/app/templates/variables/index.hbs
ui/app/templates/variables/path.hbs

Resolves #13949 and #14061
Makes the empty-variables-list link adhere to the same rules as the create button
Adds a more permissive check when you're on * namespace and * path
Added a TODO for handling * namespace on a specific path. We're being too restricted about that currently and should consider modifying allPaths to account for checking against multiple namespaces at once.

[ui] Fixes a bug for first-time SecVars users on namespaces

---

ui/tests/unit/abilities/abstract-test.js

Closes [14059](https://github.com/hashicorp/nomad/issues/14059) and follows up on [14034](https://github.com/hashicorp/nomad/issues/14034).
A set of unit tests to ensure that we encapsulated the correct behavior for namespace matching in the UI.

test: add unit tests for namespace matching util

---

.changelog/14065.txt
nomad/job_endpoint.go
website/content/api-docs/validate.mdx

This PR changes the behavior of 'nomad job validate' to forward the
request to the nomad leader, rather than responding from any server.
This is because we need the leader when validating Vault tokens, since
the leader is the only server with an active vault client.
Closes https://github.com/hashicorp/nomad/issues/13940

cli: forward request for job validation to nomad leader

---

.github/workflows/release.yml

The generated files are created as part of the final build process but
should not present in the repository afterwards.

ci: delete generated files after build

---

api/acl.go
api/acl_test.go
command/agent/acl_endpoint.go
command/agent/acl_endpoint_test.go
command/agent/http.go
nomad/acl_endpoint.go
nomad/acl_endpoint_test.go
nomad/state/state_store_acl.go
nomad/state/state_store_acl_test.go
nomad/structs/acl.go
nomad/structs/acl_test.go

New ACL Role RPC endpoints have been created to allow the creation,
update, read, and deletion of ACL roles. All endpoints require a
management token; in the future readers will also be allowed to
view roles associated to their ACL token.
The create endpoint in particular is responsible for deduplicating
ACL policy links and ensuring named policies are found within
state. This is done within the RPC handler so we perform a single
loop through the links for slight efficiency.
These new HTTP endpoints are exposed under the /v1/acl/roles
and /v1/acl/role endpoints.
notes: best viewed by commit which each represents a different
Nomad system.

ACL Role: add RPC, HTTP API, and API SDK functionality.

---

.changelog/14069.txt
command/node_status.go

Follow up to https://github.com/hashicorp/nomad/pull/13670 which fixes the bug for the UI, but not using the CLI (`nomad node status`).

cli: for systems with cgroups v2, fix alloation resource utilization showing 0 memory used

---

command/acl_role.go
command/acl_role_create.go
command/acl_role_create_test.go
command/acl_role_delete.go
command/acl_role_delete_test.go
command/acl_role_info.go
command/acl_role_info_test.go
command/acl_role_list.go
command/acl_role_list_test.go
command/acl_role_test.go
command/acl_role_update.go
command/acl_role_update_test.go
command/commands.go

cli: add new acl role subcommands for CRUD role actions.

---

.changelog/14088.txt
command/job_plan.go
command/job_plan_test.go
website/content/docs/commands/job/plan.mdx

This PR fixes a regression where the 'job plan' command would not respect
a Vault token if set via --vault-token or $VAULT_TOKEN.
Basically the same bug/fix as for the validate command in https://github.com/hashicorp/nomad/issues/13062
Fixes https://github.com/hashicorp/nomad/issues/13939

cli: support vault token in plan command

---

ui/app/controllers/variables/path.js
ui/app/helpers/trim-path.js
ui/app/routes/variables.js
ui/app/routes/variables/index.js
ui/app/routes/variables/path.js
ui/app/templates/variables/index.hbs
ui/app/templates/variables/path.hbs

Twig branch: Solves an issue where you have a policy like this:
```
namespace "*" {
policy = "read"
secure_variables {
path "*" {
capabilities = ["list"]
}
}
}
namespace "mad*" {
policy = "read"
secure_variables {
path "*" {
capabilities = []
}
}
}
namespace "nonsense" {
policy = "write"
secure_variables {
path "*" {
capabilities = ["write", "read", "destroy", "list"]
}
}
}
```
This makes it so we correctly return the forbidden state error to the user, rather than throw a fatal exception like we were doing before, when they switch to the `madness` namespace. Applies at both index and path levels.

Solves a harsh bug where you have namespace access but no secvars access

---

ui/app/adapters/variable.js
ui/app/components/secure-variable-form.hbs
ui/app/components/secure-variable-form.js
ui/app/components/variable-paths.hbs
ui/app/components/variable-paths.js
ui/app/controllers/variables/path.js
ui/app/controllers/variables/variable.js
ui/app/helpers/trim-path.js
ui/app/models/variable.js
ui/app/router.js
ui/app/routes/variables.js
ui/app/routes/variables/index.js
ui/app/routes/variables/path.js
ui/app/routes/variables/variable.js
ui/app/serializers/variable.js
ui/app/templates/variables/index.hbs
ui/app/templates/variables/path.hbs
ui/mirage/config.js
ui/mirage/factories/variable.js
ui/mirage/scenarios/default.js
ui/tests/acceptance/secure-variables-test.js
ui/tests/integration/components/secure-variable-form-test.js
ui/tests/integration/components/variable-paths-test.js
ui/tests/unit/adapters/variable-test.js

resolves #14066, #13950 and #14066
Adds namespaces to the stored identity of variables.
This means you can have multiple variables at `a/b/c/foo0` if their namespaces are different.
IDs are now stored in the browser as `<pathname>@<namespace>`, or `a/b/c/foo0@default` in the above case, and URLs reflect this:
Note that we now display same-pathed, different-namespaced variables alongside one another:

UI variables made to be unique by namespace and path

---

api/allocations.go
api/api.go
api/fs.go

HTTP API consumers that have network line-of-sight to client nodes can connect
directly for a small number of APIs. But in environments where the consumer
doesn't have line-of-sight, there's a long pause waiting for the
`api.ClientConnTimeout` to expire. Warn about this in the API docs so that
authors can avoid the extra timeout.
Closes https://github.com/hashicorp/nomad/issues/13800
No changelog for this, because it's entirely golang API docs.

api: document warnings for setting `api.ClientConnTimeout`

---

acl/policy.go
acl/policy_test.go

Fixes https://github.com/hashicorp/nomad/issues/14038
The HCL parser allows for labels that aren't needed, which makes it easy to
accidentally write a `secure_variable` block that has the intended path as the
label for that block instead of the innner `path` block. This can result in
silent failure to lock down variables if an incorrectly specified block was used
to reduce the scope of capabilities (for example, if another correctly-written
rule allows access to `*`).
We can't detect the extraneous label in the HCL API, but we can detect if we're
missing `path` blocks entirely. Use this to block obvious user errors.

ACL: disallow missing `path` in secure variable policy

---

ui/app/adapters/variable.js
ui/app/components/secure-variable-form.hbs
ui/app/components/secure-variable-form.js
ui/app/styles/components/secure-variables.scss
ui/app/utils/notify-conflict.js
ui/mirage/config.js
ui/mirage/scenarios/default.js
ui/tests/acceptance/secure-variables-test.js
ui/tests/pages/variables.js

Resolves #13420
Handles situations in which you try to save a variable, but somebody elsewhere has saved a variable underneath you while you had your page open.

Handle conflict swith a cas qp on save and create

---

command/agent/consul/connect.go
command/agent/consul/connect_test.go
command/agent/job_endpoint.go
command/agent/job_endpoint_test.go
nomad/structs/diff_test.go
nomad/structs/services.go
nomad/structs/services_test.go

This PR changes the use of `structs.ConsulMeshGateway` to value types instead of via pointers. This makes it more consistent and will help in a follow up PR where we cleanup a lot of custom comparison code with helper functions instead.

cleanup: consul mesh gateway type need not be pointer

---

nomad/deploymentwatcher/deployment_watcher.go
nomad/deploymentwatcher/deployments_watcher.go

Part 3/n of my effort to make agent tests race free. (Prev: #14120)
Both priority and state related fields may be mutated concurrently and need to be accessed with the lock acquired.
Our whole approach to flush()/setenabled in these daemon goroutines could be refactored to avoid these locking concerns (eg creating whole new structs instead of re-initializing all fields on "live" structs), but it was out of scope for my refactoring effort.

deployments: fix data races

---

go.mod
nomad/config.go
nomad/serf.go
nomad/serf_test.go
nomad/server.go

Part 2/n of my effort to make agent tests race free. (Prev: #14119)
I gave up on an initial effort of refactoring serf interactions out of Server because it was just going to be too big of a distraction at the moment. I think that's the eventual direction we should head (if we don't just remove serf entirely).

nomad: fix race in Bootstrapped access

---

nomad/blocked_evals.go

Part 4/n of my effort to make agent tests race free. (Prev: #14139)
Similar to the deployment watcher fix in #14121 - the server code loves these mutable structs so we need to guard access to the struct fields with locks.
Capturing `ch := b.capacityChangeCh` is sufficient to satisfy the data race detector, but I noticed it was also possible to leak goroutines:
Since the watchCapacity loop is in charge of receiving from capacityChangeCh and exits when stopCh is closed, senders to capacityChangeCh also must exit when stopCh is closed. Otherwise they may block forever if capacityChangeCh is full because it will never be received on again. I did *not* find evidence of this occurring in my meager smattering of prod goroutine dumps I have laying around, but this isn't surprising as the chan has …

core: fix data races in blocked eval chan handling

---

helper/funcs.go
helper/funcs_test.go
nomad/structs/services.go

This PR adds a `helper.EqualsFunc` interface (types that implement `.Equals`) and a `ElementsEquals` helper function which returns true if two slices contain the same elements (any order) - as determined by the type's `.Equals` function.

cleanup: helper func for comparing slices of .Equals types

---

ui/app/abilities/job.js
ui/app/abilities/variable.js

ACL Policies aren't required to have any `namespace` blocks, and this is
particularly common with the anonymous policy. If a user visits the web UI
without a token already in their local storage and the anonymous policy has no
`namespace` blocks, the UI will hit unhandled exceptions when rendering the
sidebar or jobs page.
Filter for the case where there's no `namespace` block.

ui: fix ability checking when anon policy is missing namespace

---

.changelog/14145.txt
GNUmakefile
api/api.go

This PR does a `strings.TrimSpace` on the response body of a failed API request, so that an error response is not extended with unwanted whitespace. 
before:
```
➜ nomad job run bad.nomad
Error submitting job: Unexpected response code: 500 (1 error occurred:
* Task group cache validation failed: 1 error occurred:
* Task group service validation failed: 1 error occurred:
* Services are not unique: [group->foo]
)
```
after:
```
➜ nomad job run bad.nomad
Error submitting job: Unexpected response code: 500 (1 error occurred:
* Task group cache validation failed: 1 error occurred:
* Task group service validation failed: 1 error occurred:
* Services are not unique: [group->foo])
```

api: trim space of error response output

---

website/content/api-docs/ui.mdx

Keynav docs

---

ui/app/services/system.js
ui/app/services/token.js

Closes [13847](https://github.com/hashicorp/nomad/issues/13847)

refact: conditional checks for token secret before fetch

---

api/acl.go
api/acl_test.go
command/acl_bootstrap.go
command/acl_token_create.go
command/acl_token_create_test.go
command/acl_token_info.go
command/acl_token_self.go
command/acl_token_update.go
helper/funcs.go
helper/funcs_test.go
nomad/acl.go
nomad/acl_endpoint.go
nomad/acl_endpoint_test.go
nomad/acl_test.go
nomad/state/state_store.go
nomad/state/state_store_acl.go
nomad/state/state_store_acl_test.go
nomad/structs/acl.go
nomad/structs/acl_test.go
nomad/structs/structs.go

ACL tokens can now utilize ACL roles in order to provide API
authorization. Each ACL token can be created and linked to an
array of policies as well as an array of ACL role links. The link
can be provided via the role name or ID, but internally, is always
resolved to the ID as this is immutable whereas the name can be
changed by operators.
When resolving an ACL token, the policies linked from an ACL role
are unpacked and combined with the policy array to form the
complete auth set for the token.
The ACL token creation endpoint handles deduplicating ACL role
links as well as ensuring they exist within state.
When reading a token, Nomad will also ensure the ACL role link is
current. This handles ACL roles being deleted from under a token
from a UX standpoint.
The PR also includes adding the …

ACL: add ACL role functionality to ACL tokens
