hashicorp/nomad

- ui/app/components/variable-paths.hbs
- ui/app/services/keyboard.js
- ui/app/templates/components/gutter-menu.hbs
- ui/app/templates/variables/variable/index.hbs
Adds variables-specific keyboard nav:
- `g v` to go to variables, globally
- `v` to show/hide values on a variable page
- `j` to switch to/from JSON mode when viewing or editing a variable
- `Shift + NUM` to enter a folder/file
( Port of https://github.com/hashicorp/nomad/pull/12831/commits/68e5999665041e267c5440ac5c1af81847eb098d and https://github.com/hashicorp/nomad/pull/12831/commits/357b3d73417497beabb76a921a704f56b0c3177f )
> Variables-specific keyboard commands

- command/acl_bootstrap_test.go
- command/acl_policy_apply_test.go
- command/acl_policy_delete_test.go
- command/acl_policy_info_test.go
- command/acl_policy_list_test.go
- command/acl_token_create_test.go
- command/acl_token_delete_test.go
- command/acl_token_info_test.go
- command/acl_token_list_test.go
- command/acl_token_self_test.go
- command/acl_token_update_test.go
- command/alloc_status.go
- command/alloc_status_test.go
- command/helpers_test.go
- command/meta_test.go
- command/testing_test.go
- command/ui_test.go
- go.mod
- go.sum
This PR is the first of several for cleaning up warnings, and refactoring
bits of code in the command package. First pass is over acl_ files and
gets some helpers in place.
> cleanup: first pass at fixing command package warnings

- command/agent_info_test.go
- command/agent_monitor_test.go
- command/alloc_exec_test.go
- command/alloc_fs_test.go
- command/alloc_logs_test.go
- command/alloc_restart_test.go
- command/alloc_signal_test.go
- command/alloc_status_test.go
- command/alloc_stop_test.go
- command/check_test.go
- command/config_validate_test.go
- command/testing_test.go
This PR continues the cleanup of the command package, removing linter
warnings, refactoring to use helpers, making tests easier to read, etc.
> cleanup: fixing warnings and refactoring of command package, part 2

- .circleci/config.yml
This PR fixes the circle workflow step on windows where we print
the go version. Like the other commands that use Go, we must
inject the install path into PATH first.
> build: print installed go version in cricle on windows

- nomad/stream/event_broker.go
Part 6/n of my effort to make agent tests race free. (Prev: #14173)
Doing a shallow copy seems sufficient here. Note that this is on the Event (singular) object and that sharing the envelope Events (plural) object in the publishCh appears fine. If it's not fine future `go test -race` runs will find it at least. :sweat_smile:
> events: fix race in acl event handling

- .changelog/14171.txt
- nomad/job_endpoint.go
- nomad/job_endpoint_oss.go
This PR synchronizes the Sentinel related changes required to support Nomad ACL Tokens and Namespaces when writing policies.
> sentinel: add support for Nomad ACL Token and Namespace

- client/acl.go
- client/agent_endpoint.go
- client/client.go
- client/client_test.go
- client/config/config.go
- client/driver_manager_test.go
- client/node_updater.go
- client/rpc.go
- client/testing.go
- command/agent/agent.go
- command/agent/agent_endpoint.go
- command/agent/agent_test.go
- command/agent/command.go
- command/agent/config.go
- command/agent/http_test.go
- command/agent/job_endpoint_test.go
- helper/funcs.go
- helper/funcs_test.go
- helper/pointer/pointer.go
- nomad/client_csi_endpoint_test.go
- nomad/config.go
- nomad/csi_endpoint_test.go
- nomad/server_setup_oss.go
- nomad/structs/config/sentinel.go
- nomad/structs/config/tls.go
- nomad/structs/operator.go
- nomad/structs/search.go
- nomad/structs/structs.go
- version/version.go
Part 4/n of my effort to make agent tests race free. (Prev: #14121)
This is the big ugly one as it tackles one of the oldest sources of data races in Nomad: client config handling.
Before this change, Client had 2 copies of the config object: config and configCopy. There was no guidance around which to use where (other than configCopy's comment to pass it to alloc runners), both are shared among goroutines and mutated in data racy ways. At least at one point I think the idea was to have `config` be mutable and then grab a lock to overwrite `configCopy`'s pointer atomically. This would have allowed alloc runners to read their config copies in data race safe ways, but this isn't how the current implementation worked.
This change takes the following approach to safely handling configs in the …
> client: fix data races in config handling

- nomad/job_endpoint.go
Part 8/n of my effort to make agent tests race free. (Prev: #14188)
Since the state store returns a pointer to the shared job structs in
memdb we must always copy it before mutating it and applying the new
version via raft. Otherwise if the rpc fails before the mutated job is
committed to raft (either due to validation, bug, crash, or other exit
condition), the leader server will have an updated copy of the job that
other servers will not have.
> core: fix race mutating jobs in scaling api

- command/acl_role_delete_test.go
- command/acl_role_info_test.go
- command/acl_role_list_test.go
- command/acl_role_update_test.go
- command/agent/acl_endpoint_test.go
- nomad/acl_endpoint.go
- nomad/acl_endpoint_test.go
- nomad/acl_test.go
- nomad/fsm.go
- nomad/fsm_test.go
- nomad/leader.go
- nomad/leader_test.go
- nomad/state/state_store_acl.go
- nomad/state/state_store_acl_test.go
- nomad/structs/acl.go
- nomad/structs/acl_test.go
ACL Roles along with policies and global token will be replicated
from the authoritative region to all federated regions. This
involves a new replication loop running on the federated leader.
Policies and roles may be replicated at different times, meaning
the policies and role references may not be present within the
local state upon replication upsert. In order to bypass the RPC
and state check, a new RPC request parameter has been added. This
is used by the replication process; all other callers will trigger
the ACL role policy validation check.
There is a new ACL RPC endpoint to allow the reading of a set of
ACL Roles which is required by the replication process and matches
ACL Policies and Tokens. A bug within the ACL Role listing RPC has
also been fixed which returned incorrect data …
> acl: add replication to ACL Roles from authoritative region.

- README.md
gitter is not an officially supported forum, so we should not link
to it from the readme.
> readme: remove Gitter lobby link.

- api/allocations.go
- api/tasks.go
- command/alloc_checks.go
- command/alloc_checks_test.go
- command/alloc_status.go
- command/alloc_status_test.go
- command/commands.go
- command/testing_test.go
This PR adds some NSD check status output to the CLI.
1. The `nomad alloc status` command produces nsd check summary output (if present)
2. The `nomad alloc checks` sub-command is added to produce complete nsd check output 
no CL, this is part of the checks feature as a whole
Closes #14054
> cli: display nomad service check status output in CLI commands

- api/acl.go
- command/acl_role_list.go
- command/agent/acl_endpoint.go
- command/agent/acl_endpoint_test.go
- nomad/acl_endpoint.go
- nomad/leader.go
- nomad/leader_test.go
- nomad/structs/acl.go
- nomad/structs/acl_test.go
Making the ACL Role listing return object a stub future-proofs the
endpoint. In the event the role object grows, we are not bound by
having to return all fields within the list endpoint or change the
signature of the endpoint to reduce the list return size.
> acl: make listing RPC and HTTP API a stub return object.

- .changelog/14199.txt
- ui/app/controllers/allocations/allocation/index.js
- ui/app/models/task.js
- ui/tests/acceptance/regions-test.js
(resolves #14198)
Adds service fragments to allocations and union taskGroup and task services. Works with both Consul and Nomad service providers.
> [ui] Allocation route services table: show task-level services

- client/client.go
In #14139 this code was changed to use the original copy of the config,
but Config.AllocDir is updated in the `Client.init()` method for dev
agents.
This uses the latest version of the alloc dir (which cannot change
further at runtime without a client restart which would reinitialize
the stats collector as well).
> client: stats need latest allocdir

- nomad/secure_variables_endpoint_test.go
- nomad/state/state_store_secure_variables.go
Looks like I missed the Watch on the GetSecureVariable function in the state store causing blocking queries against variables to block until the timeout.  Added a test to validate that `GetSecureVariable` blocks as expected based on the test for `Node`
> SV: Make GetSecureVariable a blocking query

- .changelog/14140.txt
- api/acl.go
- command/acl_bootstrap.go
- command/acl_policy_apply.go
- command/acl_policy_info.go
- nomad/acl.go
- nomad/acl_test.go
- nomad/secure_variables_endpoint_test.go
- nomad/state/schema.go
- nomad/state/state_store.go
- nomad/structs/structs.go
- website/content/docs/commands/acl/policy-apply.mdx
- website/content/docs/commands/acl/policy-info.mdx
- website/content/docs/concepts/secure-variables.mdx
- website/content/docs/concepts/workload-identity.mdx
The original design for workload identities and ACLs allows for operators to
extend the automatic capabilities of a workload by using a specially-named
policy. This has shown to be potentially unsafe because of naming collisions, so
instead we'll allow operators to explicitly attach a policy to a workload
identity.
This changeset adds workload identity fields to ACL policy objects and threads
that all the way down to the command line. It also a new secondary index to the
ACL policy table on namespace and job so that claim resolution can efficiently
query for related policies.
---
Fixes https://github.com/hashicorp/nomad/issues/13995
cc @schmichael @apollo13 @angrycub ~~I've got this in draft while I do some end-to-end verification~~ but the overall design seems sound enough for a first …
> allow ACL policies to be associated with workload identity

- api/go.mod
- go.mod
Since we started using `atomic.Pointer`, we should specify the `go1.19`
requirement in our `go.mod` files.
> build: go.mod should require go1.19

- website/content/docs/job-specification/check.mdx
This PR updates the checks documentation to mention support for checks
when using the Nomad service provider. There are limitations of NSD
compared to Consul, and those configuration options are now noted as
being Consul-only.
> docs: update check documentation with NSD specifics

- website/content/docs/concepts/secure-variables.mdx
This link was missed in https://github.com/hashicorp/nomad/pull/14140
> docs: fix an anchor link in secure vars docs

- .changelog/14171.txt
- nomad/job_endpoint.go
- nomad/job_endpoint_oss.go
> Revert "Backport of sentinel: add support for Nomad ACL Token and Namespace into release/1.1.x"

- .changelog/14171.txt
- nomad/job_endpoint.go
- nomad/job_endpoint_oss.go
> Revert "Backport of sentinel: add support for Nomad ACL Token and Namespace into release/1.2.x"

- .changelog/14224.txt
- ui/app/models/task-state.js
- ui/tests/acceptance/allocation-detail-test.js
- ui/tests/acceptance/exec-test.js
- ui/tests/acceptance/task-detail-test.js
- ui/tests/pages/allocations/detail.js
The current implementation uses the task's finishedAt field to determine
if a task is active of not, but this check is not accurate. A task in
the "pending" state will not have finishedAt value but it's also not
active.
This discrepancy results in some components, like the inline stats chart
of the task row component, to be displayed even whey they shouldn't.
> ui: use task state to determine if task is active

- nomad/server_setup.go
- nomad/server_setup_oss.go
This moves LicenseConfig.Copy to a shared file so that enterprise can
use it as well.
> core: move LicenseConfig.Copy to shared file

- command/agent/acl_endpoint_test.go
- go.mod
- go.sum
- nomad/acl_endpoint.go
- nomad/acl_endpoint_test.go
- nomad/state/state_store.go
When listing or reading an ACL role, roles linked to the ACL token
used for authentication can be returned to the caller.
I looked into using go-set for the allowed logic within the handler,
the requirement for creating the set, then transforming it meant it
was not suitable.
> acl: allow tokens to lookup linked roles.

- .changelog/14248.txt
- GNUmakefile
This PR activates the osuergo build tag in GNUMakefile. This forces the os/user
package to be compiled without CGO. Doing so seems to resolve a race condition
in `getpwnam_r` that causes alloc creation to hang or panic on `user.Lookup("nobody")`.
Fixes: https://github.com/hashicorp/nomad/issues/14235
Fixes: https://github.com/hashicorp/nomad/issues/14217
> build: set osusergo build tag by default

- .changelog/14212.txt
- website/content/docs/upgrade/upgrade-specific.mdx
This PR documents a change made in the enterprise version of nomad that addresses the following issue:
When a user tries to filter audit logs, they do so with a stanza that looks like the following:
```
audit {
enabled = true
filter "remove deletes" {
type = "HTTPEvent"
endpoints  = ["*"]
stages = ["OperationComplete"]
operations = ["DELETE"]
}
}
```
When specifying both an "endpoint" and a "stage", the events with both matching a "endpoint" AND a matching "stage" will be filtered.
When specifying both an "endpoint" and an "operation" the events with both matching a "endpoint" AND a matching "operation" will be filtered.
When specifying both a "stage" and an "operation" the events with a matching a "stage" OR a matching "operation" will be filtered.
The "OR" logic with stages and …
> docs: Update upgrade guide to reflect enterprise changes introduced in nomad-enterprise

- go.mod
- go.sum
In #13491 the version of `go-discover` was updated in `go.mod` but the
comment above it mentions that it also needs to be updated in the
`replace` directive.
> deps: sync versions of go-discover in go.mod

- .changelog/14212.txt
This change will cause event filters to behave differently from how they currently work, so marking it as breaking change to raise awareness when 1.4.0 comes out.
> changelog: update #14212 to breaking-change

- .changelog/14297.txt
- client/logmon/plugin.go
This PR causes the logmon task runner to acquire the path of binary of the
Nomad executable file in an `init` block, so as to almost certainly acquire
the name while the nomad file still exists.
This is an attempt at fixing the case where a deleted Nomad file
(e.g. during upgrade) may be getting renamed with a suffix before the deletion
(maybe SELinux specific?).
If this doesn't work, as a last resort we can literally just trim the mystery string.
Fixes: #14079
> client/logmon: acquire executable in init block

- .changelog/14298.txt
- command/agent/agent_test.go
- nomad/server_test.go
- nomad/structs/config/vault.go
- nomad/structs/config/vault_test.go
- nomad/vault.go
- nomad/vault_testing.go
The `namespace` field was not included in the equality check between old and new
Vault configurations, which meant that a Vault config change that only changed
the namespace would not be detected as a change and the clients would not be
reloaded.
Also, the comparison for boolean fields such as `enabled` and
`allow_unauthenticated` was on the pointer and not the value of that pointer,
which results in spurious reloads in real config reload that is easily missed in
typical test scenarios.
Includes a minor refactor of the order of fields for `Copy` and `Merge` to match
the struct fields in hopes it makes it harder to make this mistake in the
future, as well as additional test coverage.
---
This comes out of https://github.com/hashicorp/nomad/issues/14233 but doesn't fix it as far as I can …
> vault: detect namespace change in config reload

- .changelog/14127.txt
- api/allocations.go
- client/alloc_endpoint.go
- client/alloc_endpoint_test.go
- client/allocrunner/alloc_runner.go
- client/allocrunner/alloc_runner_test.go
- client/allocrunner/alloc_runner_unix_test.go
- client/allocrunner/tasklifecycle/coordinator.go
- client/allocrunner/tasklifecycle/coordinator_test.go
- client/allocrunner/taskrunner/lifecycle.go
- client/allocrunner/taskrunner/sids_hook_test.go
- client/allocrunner/taskrunner/state/state.go
- client/allocrunner/taskrunner/task_runner.go
- client/allocrunner/taskrunner/task_runner_test.go
- client/allocrunner/testing.go
- client/client.go
- command/agent/alloc_endpoint.go
- command/agent/consul/check_watcher.go
- command/alloc_restart.go
- nomad/mock/mock.go
- nomad/structs/structs.go
- website/content/api-docs/allocations.mdx
- website/content/docs/commands/alloc/restart.mdx
Following-up on the work done in #14009, this PR implements a new restart mode that allows for all tasks of an allocation to be restarted, even those that have already run, such as non-sidecar prestart or poststop tasks.
It also solves some related issues, such as the restart command failing with `Task not running` due to dead tasks in the allocation. These errors are now ignore when restarting the allocation (restarting a dead task with `-task` will still result in this error).
Closes #9464
Closes #9688
Closes #9841
-----------
_Note to reviewers_: The internal RFC proposed a new task state (`complete`) to differentiate between a task that is really `dead` (and would never run again) from that a task that finished running, but is waiting for a restart. 
But during implementation I …
> Task lifecycle restart

- .changelog/14223.txt
- ui/app/adapters/allocation.js
- ui/app/components/lifecycle-chart-row.js
- ui/app/controllers/allocations/allocation/index.js
- ui/app/models/allocation.js
- ui/app/templates/allocations/allocation/index.hbs
- ui/tests/acceptance/allocation-detail-test.js
- ui/tests/integration/components/lifecycle-chart-test.js
- ui/tests/pages/allocations/detail.js
This PR adds the option to restart all tasks in an allocation and fixes a CSS rule that was defined by a task `finishedAt` value. Since tasks that finished running can now be restarted, this check caused the lifecycle element to be rendered with the wrong class.
After/Before:
> ui: task lifecycle restart all tasks

- command/alloc_status_test.go
- command/testing_test.go
This PR fixes a flakey test where we did not wait on the check
status to actually become failing (go too fast and you just get
a pending check).
Instead add a helper for waiting on any check in the alloc to become
the state we are looking for.
> testing: fix flakey check status test

- command/agent/agent_test.go
`must` was not imported in the file yet in `release/1.3.x` and `Config.Copy()` was added in https://github.com/hashicorp/nomad/pull/14139, which was not backported.
I wasn't sure how to deal with `Copy()`, I thought of just copying the function over to `release/1.3.x` but it seemed unnecessary for the test.
[CI errors](https://app.circleci.com/pipelines/github/hashicorp/nomad/30498/workflows/e84f203f-c4b2-41ab-a64a-bc8b54ae441a/jobs/340995).
> fix backport of #14310

- .changelog/14248.txt
- GNUmakefile
Reverts hashicorp/nomad#14276
This tag is not supported in the Go version used in `release/1.1.x`.
> Revert "Backport of build: set osusergo build tag by default into release/1.1.x"

- .changelog/14230.txt
- client/client.go
- client/client_test.go
- client/lib/cgutil/cgutil_linux.go
- client/lib/cgutil/cgutil_linux_test.go
- client/lib/cgutil/cgutil_noop.go
- client/lib/cgutil/cpuset_manager.go
- client/lib/cgutil/cpuset_manager_v1.go
- client/lib/cgutil/cpuset_manager_v1_test.go
- client/lib/cgutil/cpuset_manager_v2.go
- client/lib/cgutil/cpuset_manager_v2_test.go
This PR refactors the code path in Client startup for setting up the cpuset
cgroup manager (non-linux systems not affected).
Before, there was a logic bug where we would try to read the `cpuset.cpus.effective`
cgroup interface file before ensuring nomad's parent cgroup existed. Therefore on first run that
file would not exist, and the list of usable cpus would be empty. Tasks started
thereafter would not have a value set for their `cpuset.cpus` file.
The refactoring fixes some hard to parse init code. Instead we now bootstrap
each cpuset manager type (v1/v2) within its own constructor. If something goes
awry during bootstrap (e.g. cgroups not enabled), the constructor returns the
noop implementation and logs a warning.
Fixes #14229
Only 1.3.x and higher, when cgroup v2 support was added
> client: refactor cpuset manager initialization

- api/secure_variables.go
- api/secure_variables_test.go
- command/agent/secure_variable_endpoint.go
- command/agent/secure_variable_endpoint_test.go
Now that the CAS is all the way to the write transaction and we plumbed the responses back out the RPC, provide them to the HTTP API and the Go API implementation.
> SV API: return upserted variable to caller

- helper/funcs.go
- helper/funcs_test.go
- helper/pointer/pointer.go
- helper/pointer/pointer_test.go
- nomad/structs/services.go
This PR creates a pointer.Compare helper for comparing equality of
two pointers. Strictly only works with primitive types we know are
safe to derefence and compare using `==`.
> cleanup: create pointer.Compare helper function

- .changelog/14333.txt
- command/job_periodic_force.go
- command/job_periodic_force_test.go
Closes #14116 
If jobs PrefixList found more than one job, we need first check whether one of their IDs equals search prefix. If it is so, we should force this job.
> cli: force periodic job if its id equals search prefix (#14116)

- ui/app/components/service-status-bar.js
- ui/tests/integration/components/service-status-bar-test.js
This PR creates a component to use when its time to visualize Service Health on the Allocation Detail Page. The component handles accepting a `RecordArray` and performs a `filterBy` method and return the `length` property of:  failing, success and pending services.
> service-health-bar

- e2e/ui/api-client.js
- e2e/ui/global-setup.js
- e2e/ui/global-teardown.js
- e2e/ui/playwright.config.js
Adding a `globalTeardown` script to call `DELETE` on all `namespaces`, `policies` and `tokens` created by the E2E test suite.
Note: We may need to add an extra step in case one of these REST API calls fails to ensure that we bubble this back up to the test runner for the E2E suite. But that should be its own PR.
> e2e: add `globalTeardown` script to not leak into other tests

- ui/app/adapters/allocation.js
- ui/app/models/allocation.js
- ui/app/routes/allocations/allocation.js
- ui/app/utils/properties/watch.js
- ui/package.json
- ui/yarn.lock
This PR handles long polling the `client/allocations/:allocId/checks` endpoint which is not stored in Ember Data. Instead we add the property directly onto the `Allocation` to visualize the Service Health information in real-time.
When doing real-time visualizations, we follow a pattern of skipping the Ember Data store because we expect a clean slate on every fetch.
> ui: long poll `/checks` endpoint

- .changelog/12953.txt
- command/agent/consul/namespaces_client.go
Nomad reconciles services it expects to be registered in Consul with
what is actually registered in the local Consul agent. This is necessary
to prevent leaking service registrations if Nomad crashes at certain
points (or if there are bugs).
When Consul has namespaces enabled, we must iterate over each available
namespace to be sure no services were leaked into non-default
namespaces.
Since this reconciliation happens often, there's no need to require
results from the Consul leader server. In large clusters this creates
far more load than the "freshness" of the response is worth.
Therefore this patch switches the request to AllowStale=true
> consul: allow stale namespace results

- nomad/structs/structs.go
- nomad/structs/structs_test.go
> bugfix: fixed template validation panic in case of incorrect ChangeScript configuration

- go.mod
- go.sum
- helper/funcs.go
- helper/funcs_test.go
- nomad/structs/services.go
This PR makes use of `go-set` and `ElementsEquals` helpers to cleanup more of these set-like equality checks on slices. 
The wrapper functions are left as-is - there are tests on them that prove the changes here are safe.
> cleanup: more cleanup of slices that are really sets

- ui/app/services/system.js
- ui/app/services/token.js
Reverts hashicorp/nomad#14134
In a cluster where ACLs are not enabled, this change results in several errors in the UI.
> Revert "refact: conditional checks for token secret before fetch"

- .changelog/14371.txt
- client/lib/cgutil/editor.go
- client/lib/cgutil/editor_test.go
- client/lib/cgutil/group_killer.go
This PR refactors the cgroups v2 group kill code path to use the
`cgroups.kill` interface file for destroying the cgroup. Previously
we copied the freeze + sigkill + unfreeze pattern from the v1 code,
but v2 provides a more efficient and more race-free way to handle
this.
Closes #14371
Backport only to 1.3.x (when v2 support was added)
> cgroups: refactor v2 kill path to use cgroups.kill interface file

- go.mod
- go.sum
- helper/crypto.go
- helper/crypto/crypto.go
- helper/uuid/uuid.go
- nomad/encrypter.go
- nomad/encrypter_test.go
- nomad/structs/extensions.go
- nomad/structs/keyring.go
- website/content/docs/operations/key-management.mdx
Update the on-disk format for the root key so that it's wrapped with a unique
per-key/per-server key encryption key. This is a bit of security theatre for the
current implementation, but it uses `go-kms-wrapping` as the interface for
wrapping the key. This provides a shim for future support of external KMS such
as cloud provider APIs or Vault transit encryption.
* Removes the JSON serialization extension we had on the `RootKey` struct; this
struct is now only used for key replication and not for disk serialization, so
we don't need this helper.
* Creates a helper for generating cryptographically random slices of bytes that
properly accounts for short reads from the source.
* No observable functional changes outside of the on-disk format, so there are
no test updates.
> keyring: wrap root key in key encryption key

- command/agent/search_endpoint_test.go
- nomad/search_endpoint.go
When the Search API was updated for variables, we didn't have the ACLs finished yet. We missed a spot when updating this endpoint for the updated ACLs.
> search: enforce correct ACL for search over variables

- api/api_test.go
- client/allocrunner/taskrunner/template/template_test.go
- client/fingerprint/env_azure_test.go
- client/fingerprint/env_digitalocean_test.go
- client/fingerprint/env_gce_test.go
- command/agent/host/host_test.go
- command/helpers_test.go
- command/job_plan_test.go
- command/job_validate_test.go
- command/meta_test.go
- command/ui_test.go
- drivers/docker/driver_darwin_test.go
- drivers/docker/driver_linux_test.go
Neither the `os.Setenv` nor `t.Setenv` helper are safe to use in parallel tests
because environment variables are process-global. The stdlib panics if you try
to do this. Remove the `ci.Parallel()` call from all tests where we're setting
environment variables.
Switched to `t.Setenv` where possible to take advantage of automatic cleanup.
Fixes panics trying to run these tests locally with `go test ./$packagename`
> testing: setting env var incompatible with parallel tests

- nomad/serf_test.go
PR #12130 refactored the test to use the `wantPeers` helper, but this
function only returns the number of voting peers, which in this test
should be equal to 2.
I think the tests were passing back them because of a bug in Raft
(https://github.com/hashicorp/raft/pull/483) where a non-voting server
was able to transition to candidate state.
One possible evidence of this is that a successful test run would have
the following log line:
```
raft@v1.3.5/raft.go:1058: nomad.raft: updating configuration: command=AddVoter server-id=127.0.0.1:9101 server-addr=127.0.0.1:9101 servers="[{Suffrage:Voter ID:127.0.0.1:9107 Address:127.0.0.1:9107} {Suffrage:Voter ID:127.0.0.1:9105 Address:127.0.0.1:9105} {Suffrage:Voter ID:127.0.0.1:9103 Address:127.0.0.1:9103} {Suffrage:Voter ID:127.0.0.1:9101 …
```
> ci: fix TestNomad_BootstrapExpect_NonVoter test

- e2e/acl/acl_role_test.go
- e2e/acl/acl_test.go
- e2e/acl/doc.go
This adds a new ACL test suite to the e2e framework which includes
an initial test for ACL roles. The ACL test includes a helper to
track and clean created Nomad resources which keeps the test
cluster clean no matter if the test fails early or not.
Related #13120
> e2e: add ACL test suite with ACL Role test.

- ui/app/controllers/jobs/job/services/index.js
- ui/app/styles/components/services.scss
- ui/app/templates/components/job-service-row.hbs
- ui/app/templates/jobs/job/services/index.hbs
- ui/app/templates/jobs/job/services/service.hbs
Resolves #14387
Implements sorting on the Services table, and makes a style adjustment to move provider icon inline next to service name
> [ui] Jobs/jobid/services table sorting

- e2e/acl/acl_test.go
- e2e/acl/acl_token_test.go
- e2e/terraform/etc/nomad.d/server-linux.hcl
In order to add an E2E test to cover token expiration, the server
config has been updated to include a low minimum allowed TTL
value. For ease of reading, the max value is also set.
> e2e: add acl test for token expiration.

- client/allocrunner/networking_cni.go
- client/client.go
- client/fingerprint/env_digitalocean.go
- client/lib/cgutil/cpuset_manager_v2.go
- client/logmon/logging/rotator.go
- client/logmon/logmon.go
- client/pluginmanager/drivermanager/instance.go
- drivers/docker/reconcile_cpuset.go
- drivers/exec/driver.go
- drivers/java/driver.go
- drivers/qemu/driver.go
- drivers/rawexec/driver.go
- nomad/client_csi_endpoint.go
- scheduler/reconcile.go
Log lines which include an error should use the full term "error"
as the context key. This provides consistency across the codebase
and avoids a Go style which operators might not be aware of.
> chore: remove use of "err" a log line context key for errors.

- website/content/docs/concepts/plugins/csi.mdx
Nomad is generally compliant with the CSI specification for Container
Orchestrators (CO), except for unimplemented features. However, some storage
vendors have built CSI plugins that are not compliant with the specification or
which expect that they're only deployed on Kubernetes. Nomad cannot vouch for
the compatibility of any particular plugin, so clarify this in the docs.
> docs: clarify CSI plugin compatibility

- .changelog/14426.txt
- command/job_plan.go
- command/job_plan_test.go
- command/job_run.go
- command/job_run_test.go
- command/job_validate.go
- command/job_validate_test.go
- website/content/docs/commands/job/plan.mdx
- website/content/docs/commands/job/run.mdx
- website/content/docs/commands/job/validate.mdx
These options are mutually exclusive but, since `-hcl2-strict` defaults
to `true` users had to explicitily set it to `false` when using `-hcl1`.
Closes #14384
> cli: set -hcl2-strict to false if -hcl1 is defined

- website/content/docs/configuration/index.mdx
As pointed out in #14429, changing an agent's `region` while it still has local state can result in data loss, so we should warn about this in our documentation.
Preview:
> docs: add warning about changing region config

- e2e/acl/acl_test.go
- e2e/acl/acl_token_test.go
> e2e: add test to exercise ACL tokens with role and policy links.

- .changelog/14445.txt
- client/taskenv/services.go
- client/taskenv/services_test.go
- website/content/docs/job-specification/gateway.mdx
- website/content/docs/job-specification/proxy.mdx
- website/content/docs/job-specification/sidecar_task.mdx
When configuring Consul Service Mesh, it's sometimes necessary to
provide dynamic value that are only known to Nomad at runtime. By
interpolating configuration values (in addition to configuration keys),
user are able to pass these dynamic values to Consul from their Nomad
jobs.
Closes #14403
> connect: interpolate task env in config values

- .changelog/14071.txt
- ui/app/controllers/exec.js
Show a different message in the terminal when there are no tasks in the job.
Closes #10545
> [ui] Show a different message when there are no tasks in a job

- .changelog/13103.txt
- nomad/structs/structs.go
- nomad/structs/structs_test.go
The warning doesn't make sense when count is 0 or 1 (destructive anyway). It's distractive and may cause users to ignore useful warnings.
> warn destructive update only when count > 1

- .changelog/14468.txt
- command/quota_status.go
As reported in https://github.com/hashicorp/nomad/issues/9920#issuecomment-1236376964
Network quotas were removed in Nomad 1.0.4. Remove the fields no longer in use
from the `quota status` output.
---
This PR won't run the test here because it's in the OSS repo, but I've verified the test passes locally in the ENT repo. Adding a `fmt.Println` to the test in the appropriate spot shows the following new output:
```
Name        = test
Description = <none>
Limits      = 1
Quota Limits
Region  CPU Usage  Memory Usage  Memory Max Usage  Variables Usage
global  0 / 100    0 / inf       0 / inf           0 / inf
```
> cli: remove network from `quota status` output

- website/content/docs/index.mdx
- website/content/docs/install/quickstart.mdx
- website/content/docs/job-specification/lifecycle.mdx
- website/content/docs/job-specification/template.mdx
- website/content/intro/index.mdx
- References to HashiCorp Learn removed
- References to `nomadproject.io` checked (none found in text, just links)
> devdot updates

- ui/app/routes/allocations/allocation.js
Closes [14471](https://github.com/hashicorp/nomad/issues/14471).
> ui:  only long poll `/checks` endpoint when route is active

- .changelog/14463.txt
- jobspec2/functions.go
- website/content/docs/job-specification/hcl2/functions/collection/length.mdx
- website/content/docs/job-specification/hcl2/functions/string/strlen.mdx
- website/data/docs-nav-data.json
> hcl2: add strlen function and update docs.

- .changelog/14457.txt
- ui/app/templates/components/gutter-menu.hbs
> ui: remove extra space in menu footer

- nomad/stats_fetcher_test.go
The map of in-flight RPCs gets cleared by a goroutine in the test without first locking it to make sure that it's not being accessed concurrently by the stats fetcher itself. This can cause a panic in tests.
I hit this panic while testing https://github.com/hashicorp/nomad/pull/14484. The line of code was last touched in https://github.com/hashicorp/nomad/pull/14441 (the autopilot migration) but that just changed the inputs, not the access pattern. We should probably fix this in backports too but I don't think I've ever seen the failure there so it may not be possible to hit without the new autopilot library.
> test: fix concurrent map access in `TestStatsFetcher`

- .changelog/14497.txt
- helper/cluster.go
- helper/cluster_test.go
This PR modifies `RandomStagger` to protect against negative input
values. If the given interval is negative, the value returned will
be somewhere in the stratosphere. Instead, treat negative inputs
like zero, returning zero.
Before:
```
=== RUN   TestCluster_RandomStagger
interface.go:24: 
cluster_test.go:27: expected 2409629h13m43.082153551s <= 1s
--- FAIL: TestCluster_RandomStagger (0.00s)
```
> helper: guard against negative inputs into random stagger

- command/agent/alloc_endpoint.go
- nomad/client_alloc_endpoint.go
When querying the checks for an allocation, the request must be forwarded to the agent that is running the allocation. If the initial request is made to a server agent, the request can be made directly to the client agent running the allocation. If the request is made to a client agent not running the alloc, the request needs to be forwarded to a server and then the correct client.
I'll look into adding additional tests as a follow up PR so this can unblock E2E testing.
> client: fix RPC forwarding when querying checks for alloc.

- .changelog/14484.txt
- api/csi.go
- nomad/csi_endpoint.go
- nomad/csi_endpoint_test.go
- nomad/structs/csi.go
- website/content/api-docs/volumes.mdx
A Nomad user reported problems with CSI volumes associated with failed allocations, where the Nomad server did not send a controller unpublish RPC.
The controller unpublish is skipped if other non-terminal allocations on the same node claim the volume. The check has a bug where the allocation belonging to the claim being freed was included in the check incorrectly. During a normal allocation stop for `job stop` or a new version of the job, the allocation is terminal so that's ok. But allocations that fail are not yet marked terminal at the point in time when the client sends the unpublish RPC to the server.
For CSI plugins that support controller attach/detach, this means that the controller will not be able to detach the volume from the allocation's host and the replacement claim will …
> CSI: failed allocation should not block its own controller unpublish

- .changelog/14483.txt
- client/client.go
- nomad/node_endpoint.go
- nomad/structs/structs.go
Adds the client's scheduling eligibility to the NodeUpdateResponse so that the client is made aware of the server-side value. Takes a heartbeat to get the data to the client and one metrics window to shed the value with the former label, but it appears to be a net improvement over the current behavior.
Fixes #8965
> Add client scheduling eligibility to heartbeat

- ui/app/adapters/allocation.js
- ui/app/components/allocation-service-sidebar.hbs
- ui/app/components/allocation-service-sidebar.js
- ui/app/controllers/allocations/allocation/index.js
- ui/app/serializers/service-fragment.js
- ui/app/serializers/task-group.js
- ui/tests/acceptance/allocation-detail-test.js
- ui/tests/unit/controllers/allocations/allocation/index-test.js
- Services/Service Fragments exist independent from a given allocation
- but service health checks exist within the context of an allocation
- and we still want some way to show all health checks for a given service
So, we bundle all health checks across all allocs into service.healthChecks, add an `Alloc` ID, and filter where we want to show that.
This gives us flexibility to show general service health in the future, plus a historical record of health within the confines of a given alloc.
> [ui] Service health checks unique by allocation

- GNUmakefile
It seems the test-website task is outdated, this pull request removes the reference in the makefile.
> Removing reference to non existant test-website task in makefile

- client/fingerprint/cgroup.go
- client/fingerprint/cgroup_linux.go
- client/lib/cgutil/cpuset_manager.go
- client/lib/cgutil/cpuset_manager_v2.go
Running `make check` on macOS identifies some dead code because the code is used only with the Linux build tag. Move this code into appropriately-tagged code files.
> CI: make `make check` clean on macOS

- .changelog/14519.txt
- nomad/job_endpoint.go
- nomad/job_endpoint_oss.go
This PR introduces a helper method to the Job RPC endpoint called specChanged. This method checks whether an incoming jobspec has changed relative to the currently deployed jobspec in all regions. This handles the case where a job has been stopped in one or more regions, and the operator now wants to restart it. By checking all regions, the spec change is detected, and a new job version can be computed and deployed to all multiregion targets.
> job_endpoint: check spec for all regions

- ui/app/components/allocation-service-sidebar.hbs
- ui/app/components/allocation-service-sidebar.js
- ui/app/components/job-service-row.js
- ui/app/templates/components/job-service-row.hbs
- ui/tests/integration/components/allocation-service-sidebar-test.js
If you pop open a Consul service, and you've configured your [UI stanza to have a consul link](https://www.nomadproject.io/docs/configuration/ui), use that link to redirect a user for better pathfinding.
Just a nice little quality of life thing. Resolves #14530
> [ui] Service Discovery: provide a quick link to the Consul UI if available

- client/acl.go
- client/agent_endpoint.go
- client/client.go
- client/client_test.go
- client/config/config.go
- client/driver_manager_test.go
- client/node_updater.go
- client/rpc.go
- client/testing.go
- command/agent/agent.go
- command/agent/agent_endpoint.go
- command/agent/agent_test.go
- command/agent/command.go
- command/agent/config.go
- command/agent/http_test.go
- command/agent/job_endpoint_test.go
- helper/funcs.go
- helper/funcs_test.go
- nomad/client_csi_endpoint_test.go
- nomad/config.go
- nomad/csi_endpoint_test.go
- nomad/server_setup_oss.go
- nomad/structs/config/sentinel.go
- nomad/structs/config/tls.go
- nomad/structs/operator.go
- nomad/structs/search.go
- nomad/structs/structs.go
- version/version.go
Before this change, Client had 2 copies of the config object: config and configCopy. There was no guidance around which to use where (other than configCopy's comment to pass it to alloc runners), both are shared among goroutines and mutated in data racy ways. At least at one point I think the idea was to have `config` be mutable and then grab a lock to overwrite `configCopy`'s pointer atomically. This would have allowed alloc runners to read their config copies in data race safe ways, but this isn't how the current implementation worked.
This change takes the following approach to safely handling configs in the client:
1. `Client.config` is the only copy of the config and all access must go through the `Client.configLock` mutex
2. Since the mutex *only protects the config pointer itself …
> Backport client: fix data races in config handling (#14139) to 1.3.x

- client/acl.go
- client/agent_endpoint.go
- client/client.go
- client/client_test.go
- client/config/config.go
- client/driver_manager_test.go
- client/node_updater.go
- client/rpc.go
- client/testing.go
- command/agent/agent.go
- command/agent/agent_endpoint.go
- command/agent/agent_test.go
- command/agent/command.go
- command/agent/config.go
- command/agent/http_test.go
- command/agent/job_endpoint_test.go
- helper/funcs.go
- helper/funcs_test.go
- nomad/client_csi_endpoint_test.go
- nomad/config.go
- nomad/csi_endpoint_test.go
- nomad/node_endpoint.go
- nomad/server_setup_oss.go
- nomad/structs/config/sentinel.go
- nomad/structs/config/tls.go
- nomad/structs/operator.go
- nomad/structs/search.go
- nomad/structs/structs.go
- version/version.go
Before this change, Client had 2 copies of the config object: config and configCopy. There was no guidance around which to use where (other than configCopy's comment to pass it to alloc runners), both are shared among goroutines and mutated in data racy ways. At least at one point I think the idea was to have `config` be mutable and then grab a lock to overwrite `configCopy`'s pointer atomically. This would have allowed alloc runners to read their config copies in data race safe ways, but this isn't how the current implementation worked.
This change takes the following approach to safely handling configs in the client:
1. `Client.config` is the only copy of the config and all access must go through the `Client.configLock` mutex
2. Since the mutex *only protects the config pointer itself …
> Backport client: fix data races in config handling (#14139) to 1.2.x

- ui/app/components/keyboard-shortcuts-modal.js
- ui/app/styles/components/keyboard-shortcuts-modal.scss
- ui/app/templates/csi/volumes/index.hbs
Resolves #14526
Solves an issue where you can have shift held and click away and hints are still shown.
This will **not** fix this for when you're taking screenshots, as cmd+shift+5 (and etc.) doesn't fire any window-or-document-detectable events, but it's still an improvement.
> On window blur, immediately hide keyboard hints

- command/var.go
- command/var_list.go
- command/var_list_test.go
Renames `-q` to `-out=terse`. Removed the combination of `-json` and `-q` since it was of uncertain value because the expectation is that json output would be post-processed anyway
> [vars] Make `var list` flags match other var commands

- command/var_init.go
- command/var_init_test.go
- command/var_put.go
Also fixes a typo in the `var put` help text.
> variables: change spec file extension to match rename

- website/content/docs/job-specification/template.mdx
Preview: https://nomad-gsgqqf402-hashicorp.vercel.app/docs/job-specification/template#nomad-variables
Once https://github.com/hashicorp/consul-template/pull/1632 is merged (after Nomad 1.4.0 beta goes out), we'll probably want to include a link to the docs over there as well.
> docs: update `template` for Nomad Variables

- nomad/structs/variables.go
- nomad/structs/variables_test.go
Fixes https://github.com/hashicorp/nomad/issues/14244
Restrict variable paths to RFC3986 URL-safe characters that don't conflict with the use of characters "@" and "." in `template` blocks. This prevents users from writing variables that will require tricky templating syntax or that they simply won't be able to use.
Also restrict the length so that a user can't make queries in the state store unusually expensive (as they are O(k) on the key length).
> variables: restrict allowed paths for variables

- website/content/docs/commands/var/get.mdx
- website/content/docs/commands/var/index.mdx
- website/content/docs/commands/var/init.mdx
- website/content/docs/commands/var/list.mdx
- website/content/docs/commands/var/purge.mdx
- website/content/docs/commands/var/put.mdx
- website/data/docs-nav-data.json
In the Nomad Secure Variables CLI, there are some new flags that I am proposing we adopt for managing input and output formatting. This PR presents these flags as they would appear in the documentation so that we can discuss these as potential updates.
Of specific note, are the `-if` and `-of` flags which are meant to manage the input and output format respectively. Invocations of the `nomad var put` command, might need to set both of these values since secure variable data can come from stdin and put has the option of returning the value once set.
Another option that seemed to have value as I was writing up the commands was `-exit-code-not-found`, which would allow users to override the default exit code of 1 in cases where the variable was not found.
[Preview Website …
> Variables CLI documentation

- nomad/state/state_store_variables.go
- nomad/state/state_store_variables_test.go
When check-index = 0, a CAS delete should succeed on a nonexistent path and fail if the path is found.
> var: Correct 0-index CAS Deletes

- command/var_get.go
- command/var_list.go
- command/var_purge.go
- command/var_put.go
- website/content/docs/commands/var/get.mdx
- website/content/docs/commands/var/list.mdx
- website/content/docs/commands/var/purge.mdx
- website/content/docs/commands/var/put.mdx
Also add links to the ACL policy reference and variables concepts docs near the top of the page.
> docs: include path in ACL requirements for variables

- website/data/docs-nav-data.json
- website/data/intro-nav-data.json
Replaces `learn.hashicorp.com` links in nav-data JSON files with paths internal to DevDot
DevDot needs these links to point to internal collection/tutorial pages rather than external ones.
> Replacing nav-data Learn links with DevDot ones

- client/allocrunner/taskrunner/service_hook.go
- client/client.go
- client/serviceregistration/checks/checkstore/shim.go
- client/serviceregistration/checks/checkstore/shim_test.go
- client/serviceregistration/nsd/nsd.go
- client/serviceregistration/nsd/nsd_test.go
- client/serviceregistration/nsd/statuses.go
- client/serviceregistration/nsd/statuses_test.go
- client/serviceregistration/watcher.go
- client/serviceregistration/watcher_test.go
- command/agent/consul/service_client.go
- nomad/mock/checks.go
- nomad/structs/services.go
- nomad/structs/services_test.go
~Merge the check watcher refactor first: https://github.com/hashicorp/nomad/pull/14546~
This PR implements support for `check_restart` for checks registered in the Nomad service provider. The actual
monitoring/restarting logic is shared with the Consul provider, via the PR above. Here we just fill in the blank
for the `CheckStatusGetter` interface for the Nomad provider and plug it in.
Unlike Consul, Nomad service checks never report a `"warning"` status, and so the `check_restart.ignore_warnings` configuration is not valid for Nomad service checks.
Closes #14370
Note: the interface + mock refactoring I'll also take care of as part of the cleanup in https://github.com/hashicorp/nomad/issues/14548
Will also follow up with docs + e2e testing.
> servicedisco: implement check_restart support for nomad service checks

- website/content/docs/job-specification/check.mdx
- website/content/docs/job-specification/check_restart.mdx
~Merge https://github.com/hashicorp/nomad/pull/14553 first~
This PR adds docs for `check_restart` support for checks registered in Nomad service provider.
> docs: add documentation for nomad service check restarts

- .changelog/10446.txt
- nomad/job_endpoint_test.go
- nomad/structs/devices.go
- nomad/structs/devices_test.go
- nomad/structs/funcs.go
- nomad/structs/funcs_test.go
- nomad/structs/network.go
- nomad/structs/network_test.go
- scheduler/context.go
- scheduler/generic_sched_test.go
- testutil/wait.go
- website/content/docs/upgrade/upgrade-specific.mdx
_This is a straw-man PR to kick the discussion going. Needs more testing; before merging._
Updates the scheduler so that it treats the alloc as running and using its resources until it truly completes as reported by the client. Typically, an alloc is terminates quickly upon being stopped, but an alloc may take a "long" time to properly shutdown and free up exclusive resources: e.g. ports, CSI/host volumes.
Previously, the scheduler optimistically treats stopped-yet-running allocs as terminated and may schedule an alloc in their place. This introduces a widow where both stopped-yet-running and new allocs are running on the client. During the window, the client resources can be oversubscribed unexpectedly (with OOM trigger) or lead to port/volume collision. Avoiding such window seems like …
> scheduler: stopped-yet-running allocs are still running

- client/allochealth/tracker_test.go
- client/logmon/logging/rotator.go
- helper/funcs.go
Trying to make some progress on #14236
While the logmon race is in runtime code, I don't think it could account for any logging related issues I see. I think the worst it could do is cause purging to happen too often or not often enough, but unless the *other* logic is wrong in purgeOldFiles that shouldn't cause logging to fail. Just use too much disk space or not as much as it could.
The WithLock helper really shouldn't be used outside of tests where we often "peek into" the state of structs that require locking semantics. I could move it into `testutil` if you think that's a better idea.
> 2 small data race fixes in logmon and check tests

- ui/app/components/allocation-service-sidebar.hbs
- ui/app/templates/allocations/allocation/index.hbs
- ui/app/templates/components/job-service-row.hbs
Resolves #14421 
Adds tooltips to a few places we only show node shortIDs
> Tooltips for client (node) names

- .changelog/14483.txt
- client/client.go
- nomad/node_endpoint.go
- nomad/structs/structs.go
> Revert "Backport of core: Add client scheduling eligibility to heartbeat into release/1.1.x"

- .release/security-scan.hcl
Temporarily turn off binary secret scanning until false negatives are resolved
> [release/1.4.0-beta.1] Temporarily turn off binary secret scanning

- version/version.go
Artifacts will be named `1.4.0-beta.1` rather than `1.4.0-dev`
> Update version string for 1.4.0 beta.1 release

- GNUmakefile
The way this tag was previous declared would cause it to be overwritten when the GO_TAGS env var was set.
> build: always set osusergo

- website/content/tools/autoscaling/plugins/target/nomad.mdx
This PR updates the Nomad Autoscaler documentation to correctly reference the Nomad Task Group target plugin as `nomad-target`. The current example references the plugin as `nomad`, which causes the Autoscaler agent to fail to start:
```
2022-09-13T19:24:07.280Z [ERROR] agent: failed to start agent:
error=
| failed to setup plugins: 1 error occurred:
| 	* failed to dispense plugin nomad: failed to instantiate plugin nomad client: fork/exec /plugins/nomad: no such file or directory
| 
```
> docs: Correct driver name for 'Nomad Task Group' autoscaler target

- client/serviceregistration/nsd/nsd.go
- client/serviceregistration/nsd/nsd_test.go
- client/serviceregistration/watcher.go
- client/serviceregistration/watcher_test.go
- command/agent/consul/service_client.go
This PR refactors `serviceregistration.CheckWatcher` to be an interface, that we then mock in some service registration tests where we can keep a tally of `Watch` and `Unwatch` calls, making sure they meet expectations.
> cleanup: create interface for check watcher and mock it in nsd tests

- .changelog/14551.txt
- ui/mirage/scenarios/default.js
- ui/tests/acceptance/clients-list-test.js
- ui/tests/acceptance/evaluations-test.js
- ui/tests/acceptance/jobs-list-test.js
- ui/tests/acceptance/keyboard-test.js
- ui/tests/acceptance/servers-list-test.js
- ui/tests/acceptance/token-test.js
- ui/tests/acceptance/topology-test.js
- ui/tests/acceptance/variables-test.js
- ui/tests/acceptance/volumes-list-test.js
- ui/tests/integration/components/variable-form-test.js
Adding faker.seed() in relevant tests, just before a snapshot takes place. Looks like it will prevent instability, for example, in our management token name (which has been changing on every percy run, but seems stable (and named Manager Daphnee Altenwerth forevermore)
> Stabilizing percy snapshots with faker

- e2e/ui/README.md
- e2e/ui/api-client.js
- e2e/ui/global-setup.js
- e2e/ui/input/tokens/operator.js
- e2e/ui/run.sh
- e2e/ui/tests/download-logs.spec.js
- e2e/ui/tests/example.spec.js
The Nomad UI will be proxied by the proxy job, but the test setup also requires making direct HTTP API requests that bypass the UI. For clusters with mTLS configured (ex. nightly), we need to bind-mount the user's mTLS certs picked up by the API client into the test runner.
Includes a new README that explains the topology of the test environments in detail and provides some advice for running locally.
---
Tested against both an E2E test cluster and local development environment. Once we've merged it I'll need to make a PR over in the [private test infra repo](https://github.com/hashicorp/nomad-e2e) to set the `NOMAD_PROXY_ADDR` value.
README preview link: https://github.com/hashicorp/nomad/blob/d24570eb342884e79535a64c8fb06055139859f1/e2e/ui/README.md
> E2E/UI: set `NOMAD_PROXY_ADDR` separately from `NOMAD_ADDR`

- command/var_get_test.go
The `TestVarGetCommand` test uses the wrong namespace in the autocomplete test. The namespace only gets validated against if we have quota enforcement (or more typically by ACL checks), so the test only fails in the ENT repo test runs.
(Arguably we should always be belt-and-suspenders enforcing a namespace exists but none of our other endpoints do, and it turns out this gets indirectly handled by ACLs anyways, but we can revisit that discussion in follow-up PRs once we get the beta out.)
> variables: fix ENT-only test failure in command tests

- plugins/drivers/testutils/exec_testing.go
This test is broken in CircleCI only. It works on GHA in both 20.04 and 22.04 and has been verified to work on real Nomad; temporarily commenting-out so that we don't block unrelated CI runs.
WIP to fix in https://github.com/hashicorp/nomad/pull/14600
> testing: skip exec stream child process test

- .semgrep/loopclosure.yml
- drivers/docker/driver_test.go
- nomad/client_agent_endpoint_test.go
- nomad/client_alloc_endpoint_test.go
Thanks to @lgfa29 for the semgrep rule to find a common source of data races in tests!
This contains 0 runtime fixes so no changelog, but it makes a little more progress on #14236
> Data race fixes in tests and a new semgrep rule

- e2e/connect/acls.go
In the event a single test fails to clear up properly after itself, all other tests will fail as they attempt to create ACL policies with the same names. This change ensures they use unique ACL names, so when a single test fails, it is easy to identify it is a problem with the test rather than the suite.
> e2e: use unique names for Connect ACL Consul policy names.

- .changelog/14592.txt
- ui/app/components/job-page/parts/recent-allocations.js
- ui/app/components/task-sub-row.hbs
- ui/app/components/task-sub-row.js
- ui/app/controllers/clients/client/index.js
- ui/app/controllers/jobs/job/task-group.js
- ui/app/styles/components.scss
- ui/app/styles/components/task-sub-row.scss
- ui/app/styles/core/table.scss
- ui/app/templates/clients/client/index.hbs
- ui/app/templates/components/job-page/parts/recent-allocations.hbs
- ui/app/templates/jobs/job/allocations.hbs
- ui/app/templates/jobs/job/task-group.hbs
- ui/package.json
- ui/tests/integration/components/task-sub-row-test.js
- ui/yarn.lock
Resolves #14578 
Adds a quicker way to dive a level or two deeper into Nomad via the UI, by optionally listing tasks beneath their parent allocations in four places:
- Job page (shown by default, togglable)
- Task Group page (shown by default, togglable)
- Client page (hidden by default, togglable)
- job/allocations sub-page (always shown)
In all cases, toggling sets a localStorage property for future usage.
> Added task links to various alloc tables

- .changelog/13991.txt
- CHANGELOG.md
Bug fixes on new features in Nomad 1.4.0 don't need or want changelog entries in the same changelog the feature appeared, so remove this one.
> remove 1.4.0 changelog entry that refers to bugfix on new code

- client/allocrunner/tasklifecycle/gate_test.go
The concurrent gate access test is flaky since it depends on the order of operations of two concurrent goroutines. Despite the heavy bias towards one of the results, it's still possible to end the execution with a closed gate.
I believe this case was created to test an earlier implementation where the gate state was stored and mutated internally, so the access had to be protected by a lock. However, the final implementation changed this approach to be only channel-based, so there is no need for this flaky test anymore.
> test: remove flaky Gate test

- ui/app/components/allocation-service-sidebar.hbs
- ui/app/styles/utils/z-indices.scss
- ui/app/templates/allocations/allocation/index.hbs
- ui/app/templates/components/job-service-row.hbs
- ui/app/templates/jobs/job/services/index.hbs
- ui/app/templates/jobs/job/services/service.hbs
Minor tweaks in the job service page and the service sidebar. I'm not sure if all the changes make sense so I tried to isolate them per commit.
7a4fa3da72463be3204f76709706637cbd48e041 adjust the z-index of elements so the sidebar renders above them.
**Before**
**After**
https://github.com/hashicorp/nomad/commit/b17611ee1244d8c018e4dfe78ed1a09f36494baa updates the column name in the service details sidebar so it's more clear that the table is about health checks (visible in the previous image as well).
https://github.com/hashicorp/nomad/commit/26b5bc8bd3ba4727d0d8ed46d8e979946b4689ee updates the service table so it uses the same pattern as other tables when displaying icons.
https://github.com/hashicorp/nomad/commit/e4749643bcbb02881d5f55f1f972adb9d5a30e88 restricts the length of the …
> Minor tweaks to the service views

- .github/14629.txt
- command/agent/acl_endpoint.go
JSON decode error messages can be quite cryptic and hard to pinpoint, so this provides more context that the error happen while trying to decode the request body.
> api: provide more detail on ACL bootstrap request error

- .gitignore
Backport the `.gitignore` changes to make `go.work` not get managed by git (target: release/1.3.x)
> chore: backport go.work gitignore changes

- .changelog/14610.txt
- command/operator_debug.go
The `operator debug` command writes JSON files from API responses as a single line containing an array of JSON objects. But some of these files can be extremely large (GB's) for large production clusters, which makes it difficult to parse them using typical line-oriented Unix command line tools that can stream their inputs without consuming a lot of memory.
For collections that are typically large, instead emit newline-delimited JSON.
This changeset includes some first-pass refactoring of this command. It breaks up monolithic methods that validate a path, create a file, serialize objects, and write them to disk into smaller functions, some of which can now be standalone to take advantage of generics.
---
There are mostly likely a bunch more improvements we can make here to memory usage, …
> operator debug: write NDJSON for large collections

- .changelog/14311.txt
- client/allocrunner/alloc_runner_hooks.go
- client/allocrunner/group_service_hook.go
- client/allocrunner/taskrunner/service_hook.go
- client/allocrunner/taskrunner/service_hook_test.go
- client/allocrunner/taskrunner/task_runner_hooks.go
- client/serviceregistration/mock/mock.go
- client/serviceregistration/nsd/nsd.go
- client/serviceregistration/nsd/nsd_test.go
- client/serviceregistration/workload.go
- command/agent/consul/connect.go
- command/agent/consul/connect_test.go
- command/agent/consul/group_test.go
- command/agent/consul/service_client.go
- command/agent/consul/service_client_test.go
- command/agent/consul/structs.go
- command/agent/consul/unit_test.go
- nomad/structs/alloc.go
This PR adds more tags (nomad namespace, job and group) to the envoy stats tags. 
It's useful when performing scaling based on envoy request being able to filter the service by nomad job/group.
Follows the work done in #12543
> Add Namespace, Job and Group to envoy stats

- .changelog/14651.txt
- command/eval_status.go
- command/eval_status_test.go
- website/content/docs/upgrade/upgrade-specific.mdx
Fixes https://github.com/hashicorp/nomad/issues/13101
In Nomad 1.2.6 we shipped `eval list`, which accepts a `-json` flag, and deprecated the usage of `eval status` without an evaluation ID with an upgrade note that it would be removed in Nomad 1.4.0. This changeset completes that work.
> cli: remove deprecated `eval status -json` list behavior

- nomad/consul.go
- nomad/consul_oss_test.go
- nomad/structs/consul.go
@picatz As promised, could you verify with the nomad team that this is indeed not needed?
EDIT:// Not exactly sure how to fix the tests properly. Just deleting them seems wrong
> Removed unused ConsulUsage.Kinds.

- .changelog/12959.txt
- client/allocrunner/taskrunner/envoy_bootstrap_hook.go
Just saw #12543 .We are doing things a bit different in a fork we have. This PR takes a different aproach and adds enviroment variables to the envoy boostrap hook. This along with https://github.com/hashicorp/consul/pull/13049 allow us to configure things like the following in the consul configuration:
```
kind = "proxy-defaults"
name = "global"
Config {
envoy_dogstatsd_url = "udp://172.26.64.1:9125"
envoy_stats_tags = [
"alloc_id=${NOMAD_ALLOC_ID}",
"nomad_group=${NOMAD_GROUP_NAME}",
"nomad_job=${NOMAD_JOB_NAME}",
"nomad_namespace=${NOMAD_NAMESPACE}",
]
}
```
This can also be set on the nomad sidecar configuration.
> Add nomad env to envoy bootstrap

- .changelog/14659.txt
- nomad/structs/structs.go
- scheduler/reconcile.go
- scheduler/reconcile_test.go
This PR fixes a bug in the `allocReconciler` where multiregion job types that don't support deployments would be flagged as paused. 
- `structs.Job` - Added a `UsesDeployments` function that can be expanded as more job types support deployments
- `scheduler.allocReconciler` - Added check to `computeDeploymentPaused` to guard against setting `deploymentPaused = true` if the job type doesn't use deployments.
-
> scheduler: Fix bug where the would treat multiregion jobs as paused for job types that don't use deployments

- e2e/overlap/overlap_test.go
- e2e/overlap/testdata/overlap.nomad
Followup to #10446
Fails (as expected) against 1.3.x at the wait for blocked eval (because the allocs are allowed to overlap).
Passes against 1.4.0-beta.1 (as expected).
> test: add e2e for non-overlapping placements

- .changelog/14673.txt
- client/fingerprint/consul.go
- client/fingerprint/consul_test.go
- client/fingerprint/vault.go
- client/fingerprint/vault_test.go
- testutil/vault.go
- website/content/docs/upgrade/upgrade-specific.mdx
Clients periodically fingerprint Vault and Consul to ensure the server has updated attributes in the client's fingerprint. If the client can't reach Vault/Consul, the fingerprinter clears the attributes and requires a node update. Although this seems like correct behavior so that we can detect intentional removal of Vault/Consul access, it has two serious failure modes:
(1) If a local Consul agent is restarted to pick up configuration changes and the client happens to fingerprint at that moment, the client will update its fingerprint and result in evaluations for all its jobs and all the system jobs in the cluster.
(2) If a client loses Vault connectivity, the same thing happens. But the consequences are much worse in the Vault case because Vault is not run as a local agent, so Vault …
> fingerprint: don't clear Consul/Vault attributes on failure

- .changelog/14665.txt
- ui/app/components/variable-form.js
- ui/app/templates/variables/variable/edit.hbs
- ui/tests/acceptance/variables-test.js
Performs an equality lookup for key values and path when attempting to leave the variables/new or variables/edit routes.
Note: early attempts at using `model.hasDirtyAttributes()` in parent routes proved to be really cumbersome — would have had to do it in a few places. @ChaiWithJai made a good suggestion to try it in the component and so here we are.
This will not notify a user when they have changes in JSON mode, as we don't observe (nor want to observe) keystroke changes to that textarea. This could be done but the perf tradeoff would be non-trivial.
Resolves #14658
> [ui] Warn users when they leave an edited but unsaved variable page

- .changelog/14634.txt
- command/operator_api.go
- command/operator_api_test.go
http.NewRequestWithContext will only set the right value for Content-Length if the input is *bytes.Buffer, *bytes.Reader, or *strings.Reader [0].
Since os.Stdin is an os.File, POST requests made with the `nomad operator api` command would always have Content-Length set to -1, which is interpreted as an unknown length by web servers.
[0]: https://pkg.go.dev/net/http#NewRequestWithContext
> cli: set content length on `operator api` requests

- client/fingerprint/vault.go
- client/fingerprint/vault_test.go
- client/fingerprint_manager.go
- website/content/docs/upgrade/upgrade-specific.mdx
@tgross Yikes! #14673 made me realize how pathological the Vault fingerprinting was. What do you think about going a step further and backing off fingerprints as long as Vault is available?
-- Original commit message --
Extension of #14673
Once Vault is initially fingerprinted, extend the period since changes should be infrequent and the fingerprint is relatively expensive since it is contacting a central Vault server.
Also move the period timer reset *after* the fingerprint. This is similar to #9435 where the idea is to ensure the retry period starts *after* the operation is attempted. 15s will be the *minimum* time between fingerprints now instead of the *maximum* time between fingerprints.
In the case of Vault fingerprinting, the original behavior might cause the following:
1. Timer is …
> fingerprint: lengthen Vault check after seen

- .changelog/14694.txt
- client/fingerprint/cpu.go
- client/fingerprint/cpu_test.go
- website/content/docs/runtime/interpolation.mdx
Add an attribute for the number of reservable CPU cores as they may differ from the existing `cpu.numcores` due to client configuration or OS support.
Hopefully clarifies some confusion in #14676
> fingerprint: add node attr for reserverable cores

- website/content/docs/configuration/server.mdx
Alternative to #14670
Well if wordcount is what matters I sure win, but I'm pretty sure wordcount is uncorrelated or perhaps even slightly inversely proportional to utility when it comes to docs.
Let me know what you think. If this approach seems good I might do something similar for the `gc` parameters.
Preview: https://nomad-f8oqghj31-hashicorp.vercel.app/docs/configuration/server#client-heartbeats
> docs: write a lot of words about heartbeats

- .changelog/14675.txt
- nomad/core_sched_test.go
- nomad/csi_endpoint.go
- nomad/csi_endpoint_test.go
A test flake revealed a bug in the CSI unpublish workflow, where an unpublish
that comes from a client that's successfully done the node-unpublish step will
not have the claim checkpointed if the controller-unpublish step fails. This
will result in a delay in releasing the volume claim until the next GC.
This changeset also ensures we're using a new snapshot after each write to raft,
and fixes two timing issues in test where either the volume watcher can
unpublish before the unpublish RPC is sent or we don't wait long enough in
resource-restricted environments like GHA.
---
Two notes for reviewers:
* This is somewhat related to https://github.com/hashicorp/nomad/pull/14484 but is really a distinct bug, so I've given it its own changelog and it'll need backports.
* This doesn't fix the …
> CSI: ensure initial unpublish state is checkpointed

- .changelog/14720.txt
- nomad/csi_endpoint.go
https://github.com/hashicorp/nomad/pull/13301 was supposed to have been backported to 1.2.x but there's no backport tag. Weirdly, https://github.com/hashicorp/nomad/pull/13311 refers to the code having been backported, and the test changes from #13301 are already here, just not the code changes. Not sure how that happened but #13301 was one of the PRs impacted by the weirdness around the 1.3.2 vs 1.3.5 release. In any case, this bug should get released in the next 1.2.x.
(1/2 PRs, the other will be for 1.1.x)
> backport to 1.2.x: CSI: skip node unpublish on GC'd or down nodes

- .changelog/14720.txt
- nomad/csi_endpoint.go
https://github.com/hashicorp/nomad/pull/13301 was supposed to have been backported to 1.1.x but there's no backport tag. Weirdly, https://github.com/hashicorp/nomad/pull/13311 refers to the code having been backported, and the test changes from #13301 are already here, just not the code changes. Not sure how that happened but #13301 was one of the PRs impacted by the weirdness around the 1.3.2 vs 1.3.5 release. In any case, this bug should get released in the next 1.1.x.
(2/2 PRs, the other was for 1.2.x)
> backport to 1.1.x: CSI: skip node unpublish on GC'd or down nodes

- .changelog/14722.txt
- scheduler/feasible.go
- scheduler/feasible_test.go
- website/content/docs/job-specification/constraint.mdx
- website/content/docs/upgrade/upgrade-specific.mdx
This PR changes constraint comparisons to be numeric rather than
lexical if both operands are integers or floats.
Inspiration #4856
Closes #4729
Closes #14719
> core: numeric operands comparisons in constraints

- .changelog/14637.txt
- jobspec/parse_task.go
- jobspec/parse_test.go
- jobspec/test-fixtures/artifacts.hcl
This test fixture comes straight from the documentation and uncovers a failure in parsing the 'headers' key.
Closes #14657
> jobspec: allow artifact headers in HCLv1 

- client/allocrunner/taskrunner/template/template_test.go
CI always runs this as root, so it worked there and always scared me when I ran it locally.
> test: skip chown test if nonroot

- .changelog/14742.txt
- GNUmakefile
- client/allocdir/fs_unix.go
- client/allocrunner/taskrunner/template/template_test.go
- command/agent/config.go
- drivers/shared/executor/executor_universal_linux.go
- helper/users/lookup.go
- helper/users/lookup_test.go
This PR updates Nomad client to always do user lookups while holding
a global process lock. This is to prevent concurrency unsafe implementations
of NSS, but still enabling NSS lookups of users (i.e. cannot not use osusergo).
> client: protect user lookups with global lock

- ui/app/components/variable-form.hbs
- ui/app/components/variable-form.js
- ui/tests/acceptance/variables-test.js
When we isolated the variable form path to within its component for isolation reasons, we lost the model-level checks for related entities at type-time.
This reinstates the notification for variable-creating users that what they're about to create will be accessible by specific jobs/groups/paths as they type.
> [ui] Bugfix: reinstate the "this variable will be accessible by $job/$group/$task" notification

- .changelog/14749.txt
- client/allocrunner/taskrunner/template/template.go
- client/allocrunner/taskrunner/template/template_test.go
Previously, the splay timeout was only applied if a template re-render caused a restart or a signal action. The `change_mode = "script"` was running after the `if restart || len(signals) != 0` check, so it was invoked at all times.
This change refactors the logic so it's easier to notice that new `change_mode` options should start only after `splay` is applied.
Closes #14734
> template: apply splay value on change_mode script

- ui/app/components/allocation-row.js
Resolves #14644
This PR guards calling `job.reload` in the `AllocationRow` component by checking if the `job` on the `allocation` argument on the `AllocationRow` component is a `partial job` (a job without task groups).
The challenge we're trying to solve is an infinite loop of dispatching asynchronous requests reported in #14644.
> refact: only reload job if job has no taskGroups

- contributing/architecture-eval-lifecycle.md
- contributing/architecture-eval-states.md
- contributing/architecture-eval-triggers.md
- contributing/architecture-state-store.md
- website/content/docs/concepts/architecture.mdx
Fixes https://github.com/hashicorp/nomad/issues/13731 
Fixes https://github.com/hashicorp/nomad/issues/13468
Fixes https://github.com/hashicorp/nomad/issues/8588
This changeset adds new architecture internals documents to the contributing guide. These are intentionally here and not on the public-facing website because the material is not required for operators and includes a lot of diagrams that we can cheaply maintain with mermaid syntax but would involve art assets to have up on the main site that would become quickly out of date as code changes happen and be extremely expensive to maintain. However, these should be suitable to use as points of conversation with expert end users.
Included:
* A description of Evaluation triggers and expected counts, with examples. …
> internals documentation with diagrams

- website/content/docs/job-specification/periodic.mdx
This is probably undocumented for a reason, but the `enabled` toggle in the `periodic` stanza is very useful so I figured I try adding it to the docs.
The feature has been secretly avaliable since #9142 and was [called out in that PR as being a dubious addition](https://github.com/hashicorp/nomad/pull/9142/files#r510132150), only added to avoid regressions in the update to hcl2.
The use case for disabling a periodic job in this way is to prevent it from running without modifying the schedule. Ideally Nomad would make it more clear that this was the case, and allow you to force a run of the job, but even with those rough edges I think users would benefit from knowing about this toggle.
> Docs(job-specification/periodic): Add enabled toggle

- .github/workflows/test-core.yaml
- GNUmakefile
Fixes https://github.com/hashicorp/nomad/issues/14785
The `hc-install` tool we're using needed a patch for a specific bug, but that's since been merged. We definitely want to switch to using a standard release from that project once one is shipped with the CLI, but pinning to HEAD should keep us for now.
> deps: use install from current HEAD for `hc-install`

- tools/go.mod
- tools/go.sum
- tools/missing/main.go
Fixes https://github.com/hashicorp/nomad/issues/14785 by removing the dependency on `gophers.dev/pkg/ignore`. This package registry has a broken cert. The package is really our own @shoenig's https://github.com/shoenig/ignore, but the package is declared with the gophers.dev domain so we can't fix it directly (and he's on vacation :grin:). We're using a one-liner function from it, so to get all the tools build working again, just remove it and we can have a discussion about that when @shoenig gets back.
> deps: remove gophers.dev dependency

- client/allocdir/fs_unix.go
- helper/users/lookup.go
In #14742 we introduced a cached lookup of the `nobody` user, which is only ever called on Unixish machines. But the initial caching was being done in an `init` block, which meant it was being run on Windows as well. This prevents the Nomad agent from starting on Windows.
An alternative fix here would be to have a separate `init` block for Windows and Unix, but this potentially masks incorrect behavior if we accidentally added a call to the `Nobody()` method on Windows later. This way we're forced to handle the error in the caller.
---
Before:
```
C:\opt> C:\opt\nomad.exe agent -config C:\etc\nomad.d"
panic: unable to lookup the nobody user: No mapping between account names and security IDs was done.
goroutine 1 [running]:
github.com/hashicorp/nomad/helper/users.init.0() …
```
> client: defer `nobody` user lookup so Windows doesn't panic

- ui/app/components/service-status-bar.js
Before:
After: 
Compare to the Running vs Complete greens we use elsewhere:
> Switch to the 'running' green for health checks

- .semgrep/fsm_time.yml
Fixes https://github.com/hashicorp/nomad/issues/14028
Metrics state is local to the server and needs to use time, which is normally forbidden in the FSM code. We have a bypass for this rule for `metrics.MeasureSince` but needed one for `metrics.MeasureSinceWithLabels` as well.
> semgrep: add MeasureSinceWithLabels to FSM time rule

- .changelog/14821.txt
- nomad/encrypter.go
- nomad/encrypter_test.go
- nomad/leader.go
- nomad/plan_apply_test.go
- nomad/worker_test.go
Fixes https://github.com/hashicorp/nomad/issues/14819
During an upgrade to Nomad 1.4.0, if a server running 1.4.0 becomes the leader before one of the 1.3.x servers, the old server will crash because the keyring is initialized and writes a raft entry.
Wait until all members are on a version that supports the keyring before initializing it.
> fix panic from keyring raft entries being written during upgrade

- website/content/docs/concepts/variables.mdx
I think we should make the difference in root key management between Nomad and Vault clear in the concept docs. I didn't see anywhere else in the docs we compared it.
I also s/secrets/variables everywhere except the first sentence since the feature is intended to be more generic than secrets. Right now it's more of a compliment to Consul's kv than Vault due to root key handling and featureset.
> docs: clarify nomad vars vs vault

- .github/workflows/lock.yml
When community members comment on long-closed issues, there's a number of failure modes that make for a bad experience for them:
* Their comments are often missed entirely because notification settings make it impractical for most developers to read comments on inactive issues.
* In our experience, the problem is only rarely a regression; because failures are complex, totally different code paths can result in symptoms that initially appear to be the same but turn out to be completely different under close examination. This is particularly the case for issues fixed in very old versions (sometimes 2 or more years old).
The Terraform core team uses a bot that locks issues after only 30 days. But because we typically close issues automatically on PR merge but don't have rolling releases, …
> lock closed issues and PRs after 120 days

- .changelog/14631.txt
- api/jobs.go
- command/job_dispatch.go
- e2e/scheduler_sysbatch/sysbatch.go
- nomad/job_endpoint.go
- nomad/structs/structs.go
- website/content/docs/commands/job/dispatch.mdx
Now it's possible to use a custom prefix in the job ID of the parameterized jobs. It's just necessary to use a new flag called `id-prefix-template` on `nomad job dispatch` command.
This PR fixes #13594.
> Allow specification of a custom job name/prefix for parameterized jobs

- .changelog/14615.txt
- client/client.go
This PR addresses https://github.com/hashicorp/nomad/issues/14614, by adding the missing call to Fingerprint's Reload() method from within SIGHUP handling on agent's code.
> Invoke FingerprintManager's Reload() func during agent's SIGHUP (Fixes #14614)

- .changelog/14492.txt
- command/job_plan.go
Hi everyone! 
* This PR is strongly related to https://github.com/hashicorp/nomad/issues/2012, where if you:
`nomad plan ...`
and there are new allocations it should give an exit status code of 1.
* However if you do:
`nomad run ...`
and then:
`nomad plan ...`
It still returns an exit status code of 1.
These changes prevent that from happening, as if there wasn't any edits to the deployment file `resp.Diff.Type` is 'None', and it gives an exit status code of 0.
I'm wondering if this is the right solution for this problem or we are searching for a better one.
> Check that JobPlanResponse Diff Type is None before checking for changes on getExitCode

- .changelog/14300.txt
- scheduler/feasible.go
Jobs not requiring any network resources should be allowed even when the network fingerprinter is disabled.
My use-case: Nomad Client running on a host with thousands of virtual network interfaces where the `network` fingerprinter takes a long time (several minutes), and the job definitions aren't allocating any network resources. I would like to add `network` to the `fingerprint.denylist` option, but this makes the scheduler fail to place any job because the current `NetworkChecker` fails if the node doesn't have any network. Allowing jobs not requiring any network resources would let me disable the `network` fingerprinter while still placing jobs properly.
> Allow jobs not requiring network resources with network fingerprinter disabled

- .changelog/14775.txt
- client/allocrunner/taskrunner/task_runner.go
- nomad/structs/structs.go
Signed-off-by: Hemanth Krishna <hkpdev008@gmail.com>
- Fixes #14170 
- Adds a new Task Event named `TaskWaitingShuttingDownDelay ` (Open to suggestions)
> enhancement: UpdateTask when Task is waiting for ShutdownDelay

- .changelog/14814.txt
- ui/app/components/line-chart.js
- ui/app/templates/components/line-chart.hbs
Resolves #14808 
Previously (for quite awhile perhaps?) the chart line would move above the time x-axis, but the axis itself would never update.  While it is cool to rip a hole in space-time via client-side javascript, it's probably better that we scroll the ticks as new x-scale extents update.
Side-note: I am skeptical if the `{{did-update this.renderChart}}` does anything at all. `renderChart()` is also called, once removed, from the `onInsert` modifier-fired action. But I don't think the template modifier triggers at all.
> [ui] Line charts: explicitly update X-axis whenever xScale changes

- .changelog/14832.txt
- ui/app/components/allocation-service-sidebar.hbs
- ui/app/styles/components/inline-definitions.scss
Resolves #14832 
Fixes an issue where, if there were many tags on a service, they would bleed off-page.
Now, we show them as ui-conventional tags and wrap them.
Gratuitous example:
> [ui] Makes service tags wrap and look like tag items

- .changelog/14864.txt
- nomad/structs/structs.go
- nomad/structs/structs_test.go
- website/content/docs/job-specification/check.mdx
This PR removes the assertion around when the 'task' field of
a check may be set. Starting in Nomad 1.4 we automatically set
the task field on all checks in support of the NSD checks feature.
This is causing validation problems elsewhere, e.g. when a group
service using the Consul provider sets 'task' it will fail
validation that worked previously.
The assertion of leaving 'task' unset was only about making sure
job submitters weren't expecting some behavior, but in practice
is causing bugs now that we need the task field for more than it
was originally added for.
We can simply update the docs, noting when the task field set by
job submitters actually has value.
Closes #14822
Closes #14849
> services: remove assertion on 'task' field being set

- .changelog/14875.txt
- main.go
Nomad runs one logmon process and also one docker_logger process for each running allocation. A naive look at memory usage shows 10-30 MB of RSS, but a closer look shows that most of this memory (ex. all but ~2MB for logmon) is shared (`Shared_Clean` in Linux pmap).
But a heap dump of docker_logger shows that it currently has an extra ~2500 KiB of heap (anonymously-mapped unshared memory) used for init blocks coming from the agent code (ex. mostly regexes from go-version, structs, and the Consul SDK). The packages for running logmon, docker_logger, and executor have an init block that parses `os.Args` to drop into their own logic, which prevents them from loading all the rest of the agent code and saves on memory, so this was unexpected.
It looks like we accidentally reordered the imports …
> docker_logger: reorder imports to save memory

- e2e/overlap/overlap_test.go
- e2e/overlap/testdata/overlap.nomad
Trying to fix #14806
Both the previous approach as well as this one worked on e2e clusters I spun up.
The old approach added a constraint to both the initial job and the followup job on a specific node. This would fail when a Windows node was selected and fixed in #14780. I have no idea why #14780 didn't fit it entirely though. It worked in my own e2e cluster.
But I realized I could simplify the test and make it more robust at the same time! Instead of picking a node before registering the job: let the initial job get placed, and then ensure the subsequent job has a constraint on that placement's node!
> test: simplify overlap job placement logic

- ui/app/adapters/job.js
- ui/app/components/job-page/parts/title.js
- ui/app/models/job.js
- ui/app/templates/components/job-page/parts/title.hbs
- ui/tests/helpers/module-for-job.js
- ui/tests/integration/components/job-page/helpers.js
- ui/tests/integration/components/job-page/periodic-test.js
- ui/tests/integration/components/job-page/service-test.js
- ui/tests/pages/jobs/detail.js
- ui/tests/unit/adapters/job-test.js
This adds a "Purge Job" button + confirmation button to the Job show page.
The Purge Job button will only show up if the job is currently dead. This conditional was added because I did not want somebody to accidentally purge a running job and then have no way to restart it. The button is already a TwoStep button with confirmation, but this felt like it added additional friction to the purge in a good way.
Closes https://github.com/hashicorp/nomad/issues/14411
> Adds purge job button to UI

- e2e/e2eutil/utils.go
- e2e/overlap/overlap_test.go
Keeps failing in the nightly e2e test with unhelpful output like:
```
Failed
=== RUN   TestOverlap
overlap_test.go:92: Followup job overlap93ee1d2b blocked. Sleeping for the rest of overlap48c26c39's shutdown_delay (9.2/10s)
overlap_test.go:105: 1500/2000 retries reached for github.com/hashicorp/nomad/e2e/overlap.TestOverlap (err=timed out before an allocation was found for overlap93ee1d2b)
overlap_test.go:105: timeout: timed out before an allocation was found for overlap93ee1d2b
--- FAIL: TestOverlap (38.96s)
```
I have not been able to replicate it in my own e2e cluster, so I added the EvalDump helper to add detailed eval information like:
```
=== RUN   TestOverlap
1/1 Job overlap7b0e90ec Eval c38c9919-a4f0-5baf-45f7-0702383c682a
Type:         service
TriggeredBy:  job-register …
```
> test: extend timing and output of overlap e2e test

- .changelog/14901.txt
- nomad/encrypter.go
- nomad/leader.go
In #14821 we fixed a panic that can happen if a leadership election happens in the middle of an upgrade. That fix checks that all servers are at the minimum version before initializing the keyring (which blocks evaluation processing during trhe upgrade). But the check we implemented is over the serf membership, which includes servers in any federated regions, which don't necessarily have the same upgrade cycle.
Filter the version check by the leader's region.
Fixes https://github.com/hashicorp/nomad/issues/14896 but this fix makes me wonder if we have other lurking bugs in this version check.
> keyring: filter by region before checking version

- command/agent/consul/service_client.go
- command/agent/consul/service_client_test.go
This fix for https://github.com/hashicorp/nomad/issues/14914 should make use of the changes here.
> cleanup: remove another string-set helper function

- .changelog/14911.txt
- nomad/acl_endpoint.go
- nomad/core_sched.go
- nomad/job_endpoint.go
- nomad/leader.go
- nomad/operator_endpoint.go
- nomad/periodic.go
- nomad/plan_apply.go
- nomad/util.go
- nomad/util_test.go
- nomad/worker.go
- scheduler/scheduler.go
* One-time tokens are not replicated between regions, so we don't want to enforce
that the version check across all of serf, just members in the same region.
* Scheduler: Disconnected clients handling is specific to a single region, so we
don't want to enforce that the version check across all of serf, just members in
the same region.
* Cleans up a bunch of legacy checks.
This changeset is specific to 1.3.x and the changes for other versions of
Nomad will be manually backported in separate PRs
> make version checks specific to region (1.3.x)

- .changelog/14912.txt
- nomad/acl_endpoint.go
- nomad/core_sched.go
- nomad/job_endpoint.go
- nomad/leader.go
- nomad/operator_endpoint.go
- nomad/periodic.go
- nomad/plan_apply.go
- nomad/util.go
- nomad/util_test.go
- nomad/variables_endpoint.go
- nomad/worker.go
- scheduler/scheduler.go
* One-time tokens are not replicated between regions, so we don't want to enforce
that the version check across all of serf, just members in the same region.
* Scheduler: Disconnected clients handling is specific to a single region, so we
don't want to enforce that the version check across all of serf, just members in
the same region.
* Variables: enforce version check in Apply RPC
* Cleans up a bunch of legacy checks.
This changeset is specific to 1.4.x and the changes for previous versions of
Nomad will be manually backported in separate PRs.
> make version checks specific to region (1.4.x)

- .changelog/14910.txt
- nomad/acl_endpoint.go
- nomad/core_sched.go
- nomad/job_endpoint.go
- nomad/leader.go
- nomad/operator_endpoint.go
- nomad/periodic.go
- nomad/plan_apply.go
- nomad/util.go
- nomad/util_test.go
- nomad/worker.go
* One-time tokens are not replicated between regions, so we don't want to enforce
that the version check across all of serf, just members in the same region.
* Cleans up a bunch of legacy checks.
This changeset is specific to 1.2.x and the changes for other versions of
Nomad will be manually backported in separate PRs.
(And yes the 1.1 in the branch name is wrong 😁 )
> make version checks specific to region (1.2.x) 

- .changelog/14917.txt
- command/agent/consul/service_client.go
This PR updates Nomad's Consul service client to do map comparisons
using `maps.Equal` instead of `reflect.DeepEqual`. The bug fix is in how
`DeepEqual` treats nil slices different from empty slices, when actually
they should be treated the same.
Also, we need to avoid comparing `TaggedAddress` on agent registrations if
none are set on the Nomad side - because Consul will helpfully set that field
for us on its side.
And some drive-by cleanup `map[string]struct{}` for `set.Set`
Fixes #14914
> consul: do not re-register already registered services

- .changelog/14908.txt
- nomad/acl_endpoint.go
- nomad/leader.go
This ensures all federated servers are running v1.4.0 or greater before the use of ACL roles is allowed.
> acl: gate ACL role write and delete RPC usage on v1.4.0 or greater.

- e2e/overlap/overlap_test.go
> test: expand timing and debugging for overlap test

- client/allocrunner/taskrunner/task_runner_test.go
- e2e/isolation/chroot_test.go
- e2e/isolation/input/chroot_dl_exec.nomad
Similar to https://github.com/hashicorp/nomad/pull/14710, convert flaky `TestTaskRunner_Download_ChrootExec` into e2e test.
This job
1. Creates an executable script and creates a tar (prestart task)
2. Starts an http server to serve the tar (prestart sidecar task)
3. Runs the script as the command of an exec task 
The e2e test then checks the output from the script is present in the task logs.
> e2e: convert flaky exec download in chroot unit test into e2e test

- .changelog/14944.txt
- client/serviceregistration/service_registration.go
- command/agent/consul/catalog_testing.go
- command/agent/consul/service_client.go
- command/agent/consul/unit_test.go
This PR updates Nomad's Consul service client to include checks in
an initial service registration, so that the checks associated with
the service are registered "atomically" with the service. Before, we
would only register the checks after the service registration, which
causes problems where the service is deemed healthy, even if one or
more checks are unhealthy - especially problematic in the case where
SuccessBeforePassing is configured.
Fixes #3935
Note this doesn't address service _de_-registrations; which we'll get to in https://github.com/hashicorp/nomad/issues/10482
> consul: register checks along with service on initial registration

- website/content/tools/autoscaling/agent.mdx
- website/content/tools/autoscaling/api.mdx
- website/content/tools/autoscaling/cli.mdx
Document the debug endpoints which is similar to https://www.nomadproject.io/api-docs/agent#agent-runtime-profiles.
(Note: the second commit is temporary change to make preview links work with the new devDot website)
Preview links:
- API docs: https://nomad-fu98cud5d-hashicorp.vercel.app//nomad/tools/autoscaling/api#agent-runtime-profiles
- Config value: https://nomad-fu98cud5d-hashicorp.vercel.app//nomad/tools/autoscaling/agent#general-parameters
- CLI flag: https://nomad-fu98cud5d-hashicorp.vercel.app//nomad/tools/autoscaling/cli#enable-debug
> docs: add autoscaling debug

- .changelog/14913.txt
- ui/app/controllers/topology.js
- ui/app/templates/components/topo-viz.hbs
- ui/app/templates/components/topo-viz/node.hbs
- ui/app/templates/topology.hbs
- ui/tests/acceptance/topology-test.js
- ui/tests/pages/topology.js
Adds a toolbar for searching and filtering clients within the Topology view, and really ties the room together.
Resolves #10002
> Adds searching and filtering for nodes on topology view

- .changelog/14923.txt
- nomad/acl_endpoint.go
- nomad/acl_endpoint_test.go
- nomad/state/events.go
- nomad/state/events_test.go
- nomad/state/state_store_acl.go
- nomad/stream/event_broker.go
- nomad/stream/event_broker_test.go
- nomad/structs/acl.go
- nomad/structs/acl_test.go
- nomad/structs/event.go
- website/content/api-docs/events.mdx
This changes adds ACL role creation and deletion to the event stream. It is exposed as a single topic with two types; the filter is primarily the role ID but also includes the role name.
While conducting this work it was also discovered that the events stream has its own ACL resolution logic. This did not account for ACL tokens which included role links, or tokens with expiry times. ACL role links are now resolved to their policies and tokens are checked for expiry correctly.
Related to #14922 and includes a modification in the RPC handler to accommodate the linked PR.
Closes #14777
> acl: add ACL roles to event stream topic and resolve policies.

- .changelog/14992.txt
- command/operator_debug.go
If the API returns an error during debug bundle collection the CLI was expanding the wrong error object, resulting in a panic since `err` is `nil`.
First spotted in https://app.circleci.com/pipelines/github/hashicorp/nomad/33328/workflows/763506a7-c0cc-4e23-b8c1-151d09b3af93/jobs/376622/steps?invite=true#step-108-860. Steps to reproduce:
1. start a 3 server Nomad cluster and wait for leadership
2. run `nomad operator debug`
3. stop 2 servers and wait for leadership to be lost
> cli: prevent panic on `operator debug`

- GNUmakefile
This PR changes `make test-nomad` and `make test-nomad-module` to use `gotestsum` in GHA,
and combine the new behavior with Circle. Also bumps `gotestsum` to `v1.8.2`. Removes some
unused bits of GNUMakefile.
`gotestsum` is configured to retry failed individual test cases up to 3 times, and with a total of up to 10 retries across all tests (per runner) per run (which is the default).
The run below was set with a deliberately broken test to confirm real test failures still fail the build
https://github.com/hashicorp/nomad/actions/runs/3294509753
> ci: try gotestsum in gha

- website/content/tools/autoscaling/plugins/apm/nomad.mdx
Document how the value of `node_class` is used during cluster scaling.
https://github.com/hashicorp/nomad-autoscaler/issues/255
Preview link: https://nomad-ce5se8qxd-hashicorp.vercel.app/nomad/tools/autoscaling/plugins/apm/nomad#policy-configuration-options-client-nodes
> docs: use of `node_class` when autoscaling

- e2e/e2eutil/utils.go
- e2e/overlap/overlap_test.go
- e2e/overlap/testdata/overlap.nomad
Originally this test relied on Job 1 blocking Job 2 until Job 1 had a terminal *ClientStatus.* Job 2 ensured it would get blocked using 2 mechanisms:
1. A constraint requiring it is placed on the same node as Job 1.
2. Job 2 would require all unreserved CPU on the node to ensure it would be blocked until Job 1's resources were free.
That 2nd assertion breaks if *any previous job is still running on the target node!* That seems very likely to happen in the flaky world of our e2e tests. In fact there may be some jobs we intentionally want running throughout; in hindsight it was never safe to assume my test would be the only thing scheduled when it ran.
*Ports to the rescue!* Reserving a static port means that both Job 2 will now block on Job 1 being terminal. It will only conflict with …
> test: use port collision instead of cpu exhaustion

- nomad/encrypter.go
- nomad/encrypter_test.go
- nomad/keyring_endpoint.go
- nomad/leader.go
Fixes https://github.com/hashicorp/nomad/issues/14981. Note to reviewers: these are definitely bugs but I don't have 100% confidence we've solved the problem because there's a log line missing in the reports from both the issue author and our internal user that I would expect to see. So I'm still trying to repro exactly, but it's worth getting some early eyes on this PR anyways.
* Don't unblock early if rate limit burst exceeded. The rate limiter returns an error and unblocks early if its burst limit is exceeded (unless the burst limit is Inf). Ensure we're not unblocking early, otherwise we'll only slow down the cases where we're already pausing to make external RPC requests.
* Set `MinQueryIndex` on stale queries. When keyring replication makes a stale query to non-leader peers to find …
> keyring: fixes for keyring replication on cluster join

- .github/workflows/test-core.yaml
This PR configures the `test-core` Action(?) with a new `mods` job on which the
other jobs depend on. The mods job just runs `mod tidy` and `bootstrap` to download
all the Go modules that will be needed and caches them. The dependent jobs then make
use of the same cache so they do not need to download / cache the near 1GB of modules
themselves.
Closes https://github.com/hashicorp/nomad/issues/15000
> ci: use the same go mod cache across test-core jobs

- .changelog/14987.txt
- .changelog/15009.txt
- command/agent/agent.go
- nomad/core_sched.go
For https://github.com/hashicorp/nomad/issues/14981
The configuration knobs for root keyring garbage collection are present in the consumer and present in the user-facing config, but we missed the spot where we copy from one to the other. Fix this so that users can set their own thresholds.
The root key is automatically rotated every ~30d, but the function that does both rotation and key GC was wired up such that `nomad system gc` caused an unexpected key rotation. Split this into two functions so that `nomad system gc` cleans up old keys without forcing a rotation, which will be done periodically or by the `nomad operator root keyring rotate` command.
> keyring: fix missing GC config, don't rotate on manual GC

- .github/workflows/test-core.yaml
Forgot to add this line to the new mods job; without it, it
creates a cache different from the one used by the other jobs. :facepalm:
> ci: add -core suffix to mods action

- .changelog/15021.txt
- go.mod
- go.sum
Includes part of the fix for https://github.com/hashicorp/raft/issues/524
> deps: update hashicorp/raft to v1.3.11

- website/redirects.js
This PR adds some notes to the `website/redirects.js` file. Intent here is to add some clarity, as part of the recent Nomad-in-Dev-Dot transition I accidentally removed the helpful comments that used to be in this file 😅
> docs: add details to redirects file

- nomad/encrypter.go
Follow-up from https://github.com/hashicorp/nomad/pull/14987/files#r1003611644
We don't need to hold the lock when querying the state store, so move the read-lock to the interior of the `activeKeySet` function.
> keyring: refactor to hold locks for less time

- .changelog/15027.txt
- client/lib/cgutil/cpuset_manager_v2.go
This PR fixes a bug where Nomad could not operate properly on operating
systems that set the root `cgroup.subtree_control` to a set of controllers that
do not include the minimal set of controllers needed by Nomad.
Nomad needs these controllers enabled to operate:
- cpuset
- cpu
- io
- memory
- pids
Now, Nomad will ensure these controllers are enabled during Client initialization,
adding them to `cgroup.subtree_control` as necessary. This should be particularly
helpful on the RHEL/CentOS/Fedora family of system. Ubuntu systems should be
unaffected as they enable all controllers by default.
Fixes: https://github.com/hashicorp/nomad/issues/14494
Backports to 1.4.x and 1.3.x (1.2.x predates cgroups v2 support)
> client: ensure minimal cgroup controllers enabled

- .changelog/15034.txt
- nomad/core_sched.go
- nomad/core_sched_test.go
- website/content/docs/configuration/server.mdx
While trying to repro https://github.com/hashicorp/nomad/issues/14981 I discovered that the approach we're using to GC keys by timeboxing them based on allocation `CreateIndex` simply won't work. Allocations would need to have a reference to the key ID that signed their WI. The current check we have is based on allocation index but it's bugged: we can only GC inactive keys newer than the newest allocation, which is useless.
We only rotate keys every 30d by default, so remove the key GC for now until we can come up with a better long-term fix for this problem.
> keyring: remove root key GC

- .changelog/15102.txt
- nomad/core_sched.go
In order to limit how much the rekey job can monopolize a scheduler worker, we limit how long it can run to 1min before stopping work and emitting a new eval. But this exactly matches the default nack timeout, so it'll fail the eval rather than getting a chance to emit a new one.
Set the timeout for the rekey eval to half the configured nack timeout.
> variables: limit rekey eval to half the nack timeout

- .changelog/15101.txt
- nomad/volumewatcher/volume_watcher.go
- nomad/volumewatcher/volumes_watcher.go
- nomad/volumewatcher/volumes_watcher_test.go
Fixes https://github.com/hashicorp/nomad/issues/15095
If a GC claim is written and then volume is deleted before the `volumewatcher` enters its run loop, we panic on the nil-pointer access. Simply doing a nil-check at the top of the loop reveals a race condition around shutting down the loop just as a new update is coming in.
Have the parent `volumeswatcher` send an initial update on the channel before returning, so that we're still holding the lock. Update the watcher's `Stop` method to set the running state, which lets us avoid having a second context and makes stopping synchronous. This reduces the cases we have to handle in the run loop.
Updated the tests now that we'll safely return from the goroutine and stop the runner in a larger set of cases. Ran the tests with the `-race` …
> volumewatcher: prevent panic on nil volume

- .changelog/15091.txt
- ui/app/controllers/application.js
- ui/app/services/token.js
- ui/app/styles/core/notifications.scss
- ui/app/templates/application.hbs
- ui/app/templates/settings/tokens.hbs
- ui/mirage/factories/token.js
- ui/mirage/scenarios/default.js
- ui/tests/acceptance/token-test.js
Throw a global notification when an active token is within 10 minutes of expiring, and prompt the user to re-authenticate.
These notifications pair with the tokens page changes from #15073 to resolve #15061; these notifications will be seen anyplace in the UI.
> [ui, sso] warn user about pending token expiry

- .changelog/14833.txt
- api/jobs.go
- command/agent/job_endpoint.go
- command/job_status.go
- nomad/job_endpoint.go
- nomad/job_endpoint_test.go
- nomad/structs/structs.go
- ui/app/routes/jobs/index.js
- ui/app/routes/jobs/job.js
- ui/app/routes/jobs/job/index.js
- ui/app/styles/core/tag.scss
- ui/app/templates/components/job-row.hbs
- ui/app/templates/components/topo-viz/datacenter.hbs
- website/content/api-docs/jobs.mdx
Resolves #11886 
Adds a Pack logo to the jobs list index's job row:
> [ui] Adds meta to job list stub and displays a pack logo on the jobs index

- .changelog/15121.txt
- client/allocrunner/taskrunner/identity_hook.go
- client/allocrunner/taskrunner/task_runner.go
For #15115
Allocations created before 1.4.0 will not have a workload identity token. When the client running these allocs is upgraded to 1.4.x, the identity hook will run and replace the node secret ID token used previously with an empty string. This causes service discovery queries to fail.
Fallback to the node's secret ID when the allocation doesn't have a signed identity. Note that pre-1.4.0 allocations won't have templates that read Variables, so there's no threat that this new node ID secret will be able to read data that the allocation shouldn't have access to.
I've smoke-tested this by creating a build of Nomad that doesn't sign identities in the plan applier, and verified that we can query service registrations as expected now.
> WI: set identity to client secret if missing

- ui/package.json
- ui/yarn.lock
Updated to upgrade per https://blog.emberjs.com/ember-4-8-1-released/
Note: Although Nomad is not susceptible to prototype pollution as the Ember upgrade seeks to fix, we're including this upgrade now to keep up with Ember security updates.
> Ember patched for security release

- .changelog/15125.txt
- client/node_updater.go
Fixes #14888
Hi, thanks for this awesome project. Recently when I use nomad with the plugin `nomad-device-nvidia`, I found that the plugin did not work well, then I found [this issue](https://github.com/hashicorp/nomad/issues/14888) reporting the same problem. By researching the code, I found that the Devices was not successfully updated in batchFirstFingerprints, maybe I try help fix it by this PR.
> fix: batchFirstFingerprints does not update device on node after v1.3.5

- .changelog/15134.txt
- nomad/plan_queue.go
In applying the fixes in #11983, a timer.Reset was missed for the Plan Queue's EmitStats function.
Fixes #15128
> Add missing timer reset

- .changelog/15140.txt
- client/rpc.go
When a Nomad service starts it tries to establish a connection with servers, but it also runs alloc runners to manage whatever allocations it needs to run.
The alloc runner will invoke several hooks to perform actions, with some of them requiring access to the Nomad servers, such as Native Service Discovery Registration.
If the alloc runner starts before a connection is established the alloc runner will fail, causing the allocation to be shutdown. This is particularly problematic for disconnected allocations that are reconnecting, as they may fail as soon as the client reconnects.
This commit changes the RPC request logic to retry it, using the existing retry mechanism, if there are no servers available.
Closes #15139
> client: retry RPC call when no server is available

- .changelog/15147.txt
- api/evaluations.go
- command/agent/eval_endpoint.go
- command/agent/eval_endpoint_test.go
- command/agent/http.go
- nomad/eval_endpoint.go
- nomad/eval_endpoint_test.go
- nomad/structs/structs.go
- website/content/api-docs/evaluations.mdx
Add a new `Eval.Count` RPC and associated HTTP API endpoints. This API is designed to support interactive use in the `nomad eval delete` command to get a count of evals expected to be deleted before doing so. (ref https://github.com/hashicorp/nomad/pull/15117)
The state store operations to do this sort of thing are somewhat expensive, but it's cheaper than serializing a big list of evals to JSON. Note that although it seems like this could be done as an extra parameter and response field on `Eval.List`, having it as its own endpoint avoids having to change the response body shape and lets us avoid handling the legacy filter params supported by `Eval.List`.
> API for `Eval.Count`

- .changelog/15146.txt
- ui/app/styles/components/sidebar.scss
Resolves #15113 
Context: While our other sidebar portals (Evaluations, Services) are parent-contextual ("expand info on this already-existing child of my route"), Task logs are different: they fetch out-of-context information (logs for a task) from several different places (including a client index, or a job index).
Because of this:
- We opted to make the sidebars conditional elements within each of the `<TaskSubRow>` components, conditional upon that row being selected (having "View Logs" clicked)
- This means that the animation treatment was different for each; instead of depending on an "open" status, we always animated it in/out when it showed up in the DOM
This presents a problem: because the context can change (ie: job stops, client stops), the task log context also changes and …
> [ui] Remove animation from task logs sidebar

- website/content/docs/job-specification/artifact.mdx
Unfortunately, s3 urls prefixed with https:// do _NOT_ work with the underlying go-getter library. As such, this fixes the examples so that they are working examples that won't cause problems for people reading the docs. 
This is a known limitation of the go-getter lib since at least 2016 per https://github.com/hashicorp/nomad/issues/1113
I've also put up a PR with the underlying go-getter lib to fix their docs as well: https://github.com/hashicorp/go-getter/pull/394
> Fix s3 example URLs in the artifacts docs

- GNUmakefile
- contributing/CHANGELOG.md
- tools/cl-entry/main.go
- tools/go.mod
- tools/go.sum
This PR adds `tools/cl-entry` and the `make cl` Makefile target for
conveniently creating correctly formatted Changelog entries.
FWIW I'm trying very hard not to name this `clippy` :paperclip:
> make: add target cl for create changelog entry

- .changelog/15192.txt
- client/allocrunner/taskrunner/template_hook.go
This PR protects access to `templateHook.templateManager` with its lock. So
far we have not been able to reproduce the panic - but it seems either Poststart
is running without a Prestart being run first (should be impossible), or the
Update hook is running concurrently with Poststart, nil-ing out the templateManager
in a race with Poststart.
Fixes #15189
Backport only to 1.4.x and 1.3.x
> template: protect use of template manager with a lock

- .changelog/15191.txt
- helper/raftutil/msgtypes.go
- nomad/fsm.go
- nomad/mock/acl.go
- nomad/state/schema.go
- nomad/state/state_store_acl_sso.go
- nomad/state/state_store_acl_sso_test.go
- nomad/state/state_store_restore.go
- nomad/state/state_store_restore_test.go
- nomad/structs/structs.go
- nomad/structs/structs_test.go
This PR implements `ACLAuthMethod` type, `acl_auth_methods` table schema and crud state store methods. It also updates `nomadSnapshot.Persist` and `nomadSnapshot.Restore` methods in order for them to work with the new table, and adds two new Raft messages: `ACLAuthMethodsUpsertRequestType` and `ACLAuthMethodsDeleteRequestType`
This PR is part of the SSO work captured under ☂️ ticket #13120. 
Consult NMD-155 RFC for documentation details.
> acl: sso auth method schema and store functions

- .github/workflows/test-core.yaml
Now that the tests are grouped more tightly we don't use as many runners as before, so we can re-enable these without clogging the queue.
> ci: re-enable tests on main

- .github/workflows/backport.yml
I'm not sure how to test this properly, so we may need to iterate a bit. I manually tested as much as I could and you can see some samples in my test channel `#feed-nomad-alerts`
> ci: notify on backport-assistant errors

- website/content/docs/job-specification/meta.mdx
- website/content/docs/job-specification/template.mdx
This PR updates template and meta docs pages to give examples of accessing
meta values in templates. To do so one must use the environment variable form
of the meta key name, which isn't obvious and wasn't yet documented.
> docs: clarify how to access task meta values in templates

- .changelog/14851.txt
- drivers/shared/executor/executor_linux.go
- drivers/shared/executor/executor_linux_test.go
- website/content/docs/drivers/exec.mdx
Fixes https://github.com/hashicorp/nomad/issues/11781
The exec driver and other drivers derived from the shared executor check the path of the command before handing off to libcontainer to ensure that the command doesn't escape the sandbox. But we don't check any host volume mounts, which should be safe to use as a source for executables if we're letting the user mount them to the container in the first place.
Check the mount config to verify the executable lives in the mount's host path, but then return an absolute path within the mount's task path so that we can hand that off to libcontainer to run.
Includes a good bit of refactoring here because the anchoring of the final task path has different code paths for inside the task dir vs inside a mount. But I've fleshed out the test …
> exec: allow running commands from host volume

- .changelog/15215.txt
- client/allocrunner/taskrunner/task_runner.go
- helper/funcs.go
- helper/funcs_test.go
This PR fixes a bug introduced in #11983 where a Timer initialized with 0
duration causes an immediate tick, even if Reset is called before reading the
channel. The fix is to avoid doing that, instead creating a Timer with a non-zero
initial wait time, and then immediately calling Stop.
Fixes #15198
> client: avoid unconsumed channel in timer construction

- .changelog/15214.txt
- client/allocrunner/network_manager_linux.go
This PR changes the behavior on reconnect from the behavior introduced in #9757. 
https://github.com/hashicorp/nomad/blob/83b31ea44f7153a482de85992dcf77b52057047d/client/allocrunner/network_manager_linux.go#L100-L104
If the client enters this case and is returned a nil spec. When the network_hook's Postrun func is called to clean things up, the nil spec causes a fast exit.
https://github.com/hashicorp/nomad/blob/83b31ea44f7153a482de85992dcf77b52057047d/client/allocrunner/network_hook.go#L115-L118
This PR changes the behavior when we encounter the existing network namespace to return the spec so that the Postrun behavior will run properly to reap the namespace. 
Fixes #11096
> [bug] Return a spec on reconnect

- .changelog/15117.txt
- api/evaluations.go
- command/agent/eval_endpoint.go
- command/agent/eval_endpoint_test.go
- command/eval_delete.go
- nomad/eval_endpoint.go
- nomad/eval_endpoint_test.go
- nomad/fsm.go
- nomad/state/state_store.go
- nomad/state/state_store_test.go
- nomad/structs/eval.go
- nomad/structs/structs.go
- website/content/docs/commands/eval/delete.mdx
During unusual outage recovery scenarios on large clusters, a backlog of millions of evaluatons can appear. In these cases, the `eval delete` command can put excessive load on the cluster by listing large sets of evals to extract the IDs and then sending larges batches of IDs. Although the command's batch size was carefully tuned, we still need to be JSON deserialize, reserialize to messagepack, send the log entries through raft, and get the FSM applied.
To improve performance of this recovery case, move the batching process into the RPC handler and the state store. The design here is a little weird, so let's look at the failed options first:
* A naive solution here would be to just send the filter as the raft request and let the FSM apply delete the whole set in a single operation. …
> eval delete: move batching of deletes into RPC handler and state

- ui/app/routes/topology.js
Related to [10830](https://github.com/hashicorp/nomad/issues/10830).
The Topology Visualization makes a request to the `/jobs` endpoint and by default, requests all jobs in the `default` namespace. Upon investigating the issue, there is no usage of `model.jobs` in the controller, nor the template. It appears that we may not need this API call.
> refact: remove unused API

- ui/app/styles/core/section.scss
- ui/app/styles/core/table.scss
- ui/app/styles/core/variables.scss
Closes [15207](https://github.com/hashicorp/nomad/issues/15207).
When using the Nomad UI, once your screen width goes under 1100px (most screens are about 1400px width, so anytime a user wants to use two windows e.g. having a terminal and browser on the same screen -- common use case even for me), information on tables becomes inaccessible. This happens everywhere that we use a table.
The simplest solution would be to enable horizontal scrolling when information is too wide for our screen.
**Problem**
**Solution**
> styling: add overflow-x to section

- ui/app/styles/core/table.scss
- ui/app/styles/core/variables.scss
- ui/app/templates/csi/volumes/index.hbs
Closes [13535](https://github.com/hashicorp/nomad/issues/13535).
Volume Names are not unique. Users may want to ensure that they're selecting the correct volume. A simple patch for us can be to provide a tooltip that shows the unique volume id.
> feat: add tooltip to storage volumes

- nomad/leader_test.go
The `TestLeader_Reelection` test waits for a leader to be elected and then makes some other assertions. But it implcitly assumes that there's no failure of leadership before shutting down the leader, which can lead to a panic in the tests. Assert there's still a leader before the shutdown.
> test: ensure leader is still valid in reelection test

- .changelog/14621.txt
- nomad/config.go
- nomad/eval_broker.go
- nomad/eval_broker_test.go
- nomad/eval_endpoint.go
- nomad/leader.go
- nomad/server.go
- nomad/worker_test.go
When an evaluation is acknowledged by a scheduler, the resulting plan is guaranteed to cover up to the `ModifyIndex` ("wait index") set by the worker based on the most recent evaluation for that job in the state store. At that point, we no longer need to retain blocked evaluations in the broker that are older than that index.
Move these stale evals into a canceled set. When the `Eval.Ack` RPC returns from the eval broker it will retrieve a batch of canceable evals to write to raft. This paces the cancelations limited by how frequently the schedulers are acknowledging evals; this should reduce the risk of cancelations from overwhelming raft relative to scheduler progress. 
Note that the evals will still need to be deleted during garbage collection, but there's not much we can do about that …
> eval broker: shed all but one blocked eval per job after ack

- .changelog/15227.txt
- nomad/encrypter.go
- nomad/encrypter_test.go
Fixes https://github.com/hashicorp/nomad/issues/14981
When keyring replication starts, we take a handle to the state store. But whenever a snapshot is restored, this handle is invalidated and no longer points to a state store that is receiving new keys. This leaks a bunch of memory too!
In addition to operator-initiated restores, when fresh servers are added to existing clusters with large-enough state, the keyring replication can get started quickly enough that it's running before the snapshot from the existing clusters have been restored.
Fix this by updating the handle to the state store when we query.
> keyring: update handle to state inside replication loop

- .github/workflows/test-core.yaml
This PR changes test-core to make use of
https://github.com/hashicorp/setup-golang
to consolidate the setting up of the Go compiler and the Go modules cache
used for the CI job. The version of Go is automatically detected from the `.go-version` file. The `PATH` is automatically configured to include `GOBIN`.
Fixes: https://github.com/hashicorp/nomad/issues/14905
> ci: use hashicorp/setup-golang for setting up go compiler, cache

- .changelog/15180.txt
- plugins/drivers/client.go
Please see https://github.com/hashicorp/nomad/issues/15179 for a more detailed explanation. The call to `joincontext.Join` generates a `goroutine` which must be garbage collected (which means the context cleanup).
> Fix goroutine leakage

- e2e/terraform/packer/ubuntu-jammy-amd64/setup.sh
make sure systemd stub resolver does not try to start and steal port 53
> e2e: disable systemd stub dns in jammy image

- .changelog/15290.txt
- nomad/autopilot.go
- nomad/autopilot_test.go
Fixes https://github.com/hashicorp/nomad/issues/15085
When we migrated to the updated autopilot library in Nomad 1.4.0, the interface for finding servers changed. Previously autopilot would get the serf members and call `IsServer` on each of them, leaving it up to the implementor to filter out clients (and in Nomad's case, other regions). But in the "new" autopilot library, the equivalent interface is `KnownServers` for which we did not filter by region. This causes spurious attempts for the cross-region stats fetching, which results in TLS errors and a lot of log noise.
Filter the member set by region to fix the regression.
---
Compare old caller (in Consul, which we imported directly): [autopilot.go#L215](https://github.com/hashicorp/consul/blob/v1.7.0/agent/consul/autopilot/autopilot.go …
> autopilot: include only servers from the same region

- nomad/eval_endpoint.go
In #14621 we added an eval canelation reaper goroutine with a channel that allowed us to wake it up. But we forgot to actually send on this channel from `Eval.Ack` and are still committing the cancelations synchronously. Fix this by sending on the buffered channel to wake up the reaper instead.
(ref https://github.com/hashicorp/nomad/pull/14621/files#r1025630828)
> make eval cancelation async with `Eval.Ack`

- scheduler/generic_sched.go
- scheduler/scheduler_system.go
The original message did not have enough information that would allow us to debug the problem. Printing the stack trace will help us understand where the error happened.
> scheduler: log stack in case of panic

- website/content/tools/autoscaling/plugins/apm/nomad.mdx
Document the Autoscaler Nomad APM paramemeters `cpu-allocated` and `memory-allocated` that were implemented in
https://github.com/hashicorp/nomad-autoscaler/pull/324 and https://github.com/hashicorp/nomad-autoscaler/pull/334
> docs: add cpu-allocated and memory-allocated

- .changelog/15252.txt
- command/agent/acl_endpoint.go
- command/agent/agent_endpoint.go
- command/agent/namespace_endpoint.go
Related to #15253 but split, so this PR can be back-ported further.
> api: ensure all request body decode error return a 400 status code.

- .changelog/15309.txt
- client/allocrunner/alloc_runner_hooks.go
- client/allocrunner/consul_grpc_sock_hook.go
- client/allocrunner/consul_grpc_sock_hook_test.go
- client/fingerprint/consul.go
- client/fingerprint/consul_test.go
- website/content/docs/configuration/consul.mdx
- website/content/docs/integrations/consul-connect.mdx
Consul 1.14.0 changed the way in which gRPC listeners are configured, particularly when using TLS. Prior to the change, a single listener was responsible for handling plain-text and encrypted gRPC requests. In 1.14.0 and beyond, separate listeners will be used for each, defaulting to 8502 and 8503 for plain-text and TLS respectively.
The change means that Nomad’s Consul Connect integration would not work when integrated with Consul clusters using TLS and running 1.14.0 or greater.
The Nomad Consul fingerprinter identifies the gRPC port Consul has exposed using the "DebugConfig.GRPCPort" value from Consul’s “/v1/agent/self” endpoint. In Consul 1.14.0 and greater, this only represents the plain-text gRPC port which is likely to be disbaled in clusters running TLS. In order to fix this …
> client: accommodate Consul 1.14.0 gRPC and agent self changes.

- ui/app/controllers/settings/tokens.js
- ui/app/styles/components.scss
- ui/app/styles/components/authorization.scss
- ui/app/templates/settings/tokens.hbs
- ui/tests/acceptance/token-test.js
Resolves #15269 
- Renames a few computed properties to be more clear: `tokenIsValid` to `successfulSignIn` (because it only fires immediately upon auth request), `this.tokenRecord` to `this.shouldShowPolicies`, etc.
- Modify styles to match intended designs: stacked notifications -> tokens -> sso
> Tokens page styles

- e2e/oversubscription/testdata/docker.nomad
jammy uses cgroups v2, need to lookup the max memory limit from the
unified heirarchy format
> e2e: fixup oversubscription test case for jammy

- .github/workflows/build.yml
- .github/workflows/release.yml
The `ubuntu-latest` runner has been migrated to Ubuntu 22.04, which doesn't have all the same multilib packages as 20.04. Although we'll probably want to migrate eventually, we should ship Nomad 1.4.3 with the same toolchain as we did previously so that we're not introducing new issues. This is currently blocking the 1.4.3 release (and backports).
> pin build/release pipeline to ubuntu 20.04

- CODEOWNERS
Adds @hashicorp/nomad-eng to the codeowners list for the build and release workflow files, so that we can fix problems that arise without being bottlenecked on another team.
> ensure engineering has merge authority on build pipeline

- ui/tests/acceptance/exec-test.js
- ui/tests/acceptance/task-logs-test.js
Resolves #15349 
- Adds a 1-second timer to allow [xterm](https://xtermjs.org/) to finish writing our example lines for the Exec view
- Adds conditional CSS to hide the (highly variable) allocation created-at fields that were showing up in the background of our sidebar snapshot
The result should be no more default red Xs for percy tests on Nomad. At least until I accidentally add more volatile screenshots again in the future :)
> [ui] Stabilize Percy tests for Exec and Logs Sidebar views

- e2e/disconnectedclients/disconnectedclients_test.go
- e2e/e2eutil/input/disconnect-node.nomad
- e2e/terraform/etc/nomad.d/client-linux.hcl
This PR modifies the disconnect helper job to run as root, which is necesary
for manipulating iptables as it does. Also re-organizes the final test logic
to wait for client re-connect before looking for the replacement (3rd) allocation
in case that client was needed to run the alloc (also giving the sheduler more
time to do its thing).
Skips the other 3 tests, which fail and I cannot yet figure out what is going on.
> e2e: fix 1 of 4 client disconnect tests

- api/acl.go
- api/acl_test.go
- command/agent/acl_endpoint.go
- command/agent/acl_endpoint_test.go
- command/agent/http.go
- nomad/acl_endpoint.go
- nomad/acl_endpoint_test.go
- nomad/config.go
This adds the ACL auth-method HTTP API for CRUD actions on ACL auth-methods. The change also includes a modification to the ACL RPC endpoint, so that we utilise the existing TTLs rather than add new ones.
Related #13120
> sso: add ACL auth-method HTTP API CRUD endpoints

- go.sum
This passed lint in #15335 but that PR was not rebased on incoming changes before merging, so this was missed and has shown up on `main`
> fix linter for go.mod tidy

- .changelog/15262.txt
- command/deployment_status.go
- command/monitor.go
- website/content/docs/commands/deployment/status.mdx
Addresses comments laid out in https://github.com/hashicorp/nomad/issues/11068
> cli: `wait` flag for use with `deployment status -monitor`

- command/deployment_status.go
This was part of the work done in #15325, but I extracted it into a separate PR to help scope code review.
> cli: improve errors for multiregion deployments

- .changelog/15372.txt
- scheduler/scheduler_system_test.go
- scheduler/stack.go
Fixes https://github.com/hashicorp/nomad/issues/15094
When the scheduler checks feasibility of each node, it creates a "stack" which carries attributes of the job and task group it needs to check feasibility for. The `system` and `sysbatch` scheduler use a different stack than `service` and `batch` jobs. This stack was missing the call to set the job ID and namespace for the CSI check. This prevents CSI volumes from being scheduled for system jobs whenever the volume is in a non-default namespace.
Set the job ID and namespace to match the generic scheduler.
> scheduler: set job on system stack for CSI feasibility check

- .changelog/15325.txt
- nomad/fsm.go
- nomad/job_endpoint.go
- nomad/job_endpoint_oss.go
- nomad/state/state_store.go
- nomad/structs/structs.go
- scheduler/reconcile.go
- scheduler/reconcile_test.go
For multiregion jobs, the scheduler does not create placements on registration because the deployment must wait for the other regions. Once of these regions will then trigger the deployment to run.
Currently, this is done in the scheduler by considering any eval for a multiregion job as "paused" since it's expected that another region will eventually unpause it.
This becomes a problem where evals not triggered by a job registration happen, such as on a node update. These types of regional changes do not have other regions waiting to progress the deployment, and so they were never resulting in placements.
The fix is to create a deployment at job registration time. This additional piece of state allows the scheduler to differentiate between a multiregion change, where there are other …
> scheduler: create placements for non-register MRD

- api/acl.go
- api/acl_test.go
- nomad/leader.go
- nomad/leader_test.go
- nomad/structs/acl.go
- nomad/structs/acl_test.go
I rejigged some on the leader code so it was easier and made more sense when scrolling.
The hash has been added to the stub object so this can be used when performing replication diffs as is done with other ACL objects. It also now includes the create and modify indexes.
The auth method struct object has JSON marhsal/unmarshal implementations to allow for the time.Duration parameter.
Related https://github.com/hashicorp/nomad/issues/13120
> acl: replicate auth-methods from federated cluster leaders.

- ui/app/components/line-chart.js
- ui/app/templates/components/line-chart.hbs
Resolves #15098 
---
Uses a `did-update` triggered on `yScale()` to manually re-call the yAxis scale formatter. Similar change to what we did in https://github.com/hashicorp/nomad/pull/14814.
> [ui] Recompute Y Axis on data change

- client/pluginmanager/csimanager/volume.go
- go.mod
- helper/mount/mount_linux.go
https://github.com/hashicorp/nomad/pull/15229 updated Docker in `release/1.2.x`, but it had some breaking changes that [caused CI to fail](https://app.circleci.com/pipelines/github/hashicorp/nomad/35387/workflows/04f7a731-7f34-44dc-8d97-45173a34d6b2/jobs/391854). The fixes had already been done in https://github.com/hashicorp/nomad/pull/11872 for 1.3.0+, that's why only `release/1.2.x` fails. 
I applied the Docker-related changes here, I believe the other changes are related the `runc` update.
> deps: apply fixes after Docker update

- api/acl.go
- api/acl_test.go
- command/acl_auth_method_create.go
- command/acl_auth_method_update.go
- command/agent/acl_endpoint.go
- command/agent/acl_endpoint_test.go
- nomad/acl_endpoint.go
- nomad/acl_endpoint_test.go
- nomad/structs/acl.go
Currently CRUD code that operates on SSO auth methods does not return created or updated object upon creation/update. This is bad UX and inconsistent behavior compared to other ACL objects like roles, policies or tokens. 
This PR fixes it. 
Relates to #13120
> acl: sso auth methods RPC/API/CLI should return created or updated objects

- website/content/tools/autoscaling/plugins/strategy/target-value.mdx
How `threshold` is used: https://github.com/hashicorp/nomad-autoscaler/blob/v0.3.7/plugins/builtin/strategy/target-value/plugin/plugin.go#L161-L162
How `factor` and `new_count` are calculated: https://github.com/hashicorp/nomad-autoscaler/blob/v0.3.7/plugins/builtin/strategy/target-value/plugin/plugin.go#L108-L134
> docs: clarify autoscaling factor and threshold for target-value plugin

- ui/app/templates/settings/tokens.hbs
- ui/tests/acceptance/token-test.js
Otherwise, all visual diff tests will fail, since the token expiry time is always 11 minutes after the test runs.
> Percy-specific CSS to block out the exact token expiry time

- nomad/acl_endpoint.go
- nomad/alloc_endpoint.go
- nomad/client_agent_endpoint.go
- nomad/client_alloc_endpoint.go
- nomad/client_csi_endpoint.go
- nomad/client_fs_endpoint.go
- nomad/client_stats_endpoint.go
- nomad/csi_endpoint.go
- nomad/deployment_endpoint.go
- nomad/endpoints_oss.go
- nomad/eval_endpoint.go
- nomad/event_endpoint.go
- nomad/job_endpoint.go
- nomad/job_endpoint_hook_connect_test.go
- nomad/keyring_endpoint.go
- nomad/namespace_endpoint.go
- nomad/node_endpoint.go
- nomad/operator_endpoint.go
- nomad/periodic_endpoint.go
- nomad/plan_endpoint.go
- nomad/regions_endpoint.go
- nomad/scaling_endpoint.go
- nomad/search_endpoint.go
- nomad/server.go
- nomad/service_registration_endpoint.go
- nomad/status_endpoint.go
- nomad/system_endpoint.go
- nomad/variables_endpoint.go
Upcoming work to instrument the rate of RPC requests by consumer (and eventually rate limit) requires that we thread the `RPCContext` through all RPC handlers so that we can access the underlying connection. This changeset adds the context to everywhere we intend to initially support it and therefore intentionally excludes streaming RPCs and client RPCs.
To improve the ergonomics of adding the context everywhere its needed and to clarify the requirements of dynamic vs static handlers, I've also done a good bit of refactoring here:
* canonicalized the RPC handler fields so they're as close to identical as possible without introducing unused fields (i.e. I didn't add loggers if the handler doesn't use them already).
* canonicalized the imports in the handler files.
* added a …
> provide `RPCContext` to all RPC handlers

- nomad/server.go
In #15430 we refactored the RPC endpoint configuration to make adding the RPC context easier. But when implementing the change on the Enterprise side, I discovered that the registration of enterprise endpoints was being done incorrectly -- this doesn't show up on OSS because the registration is always a no-op here.
> fix enterprise endpoint registration

- website/content/docs/commands/plugin/status.mdx
The `plugin status` command supports displaying CSI capabilities and topology accessibility, but this was missing from the documentation. Extend the `-verbose` example to show that info.
Noticed this was missing while discussing https://github.com/hashicorp/nomad/issues/15420
Preview link: https://nomad-2gj2qug2a-hashicorp.vercel.app/nomad/docs/commands/plugin/status#examples
> docs: update `plugin status` docs with capabilities and topology

- nomad/client_csi_endpoint_test.go
- nomad/csi_endpoint_test.go
- nomad/heartbeat.go
- nomad/node_endpoint_test.go
- nomad/server.go
- nomad/variables_endpoint_test.go
Nomad server components that aren't in the `nomad` package like the deployment watcher and volume watcher need to make RPC calls but can't import the Server struct to do so because it creates a circular reference. These components have a "shim" object that gets populated to pass a "static" handler that has no RPC context.
Most RPC handlers are never used in this way, but during server setup we were constructing a set of static handlers for most RPC endpoints anyways. This is slightly wasteful but also confusing to developers who end up being encouraged to just copy what was being done for previous RPCs.
This changeset includes the following refactorings:
* Remove the static handlers field on the server
* Instead construct just the specific static handlers we need to pass into the …
> remove most static RPC handlers

- ui/app/templates/components/task-row.hbs
Resolves #12881 
The task row is clickable however since it was not formatted like a hyperlink users report that its not obvious that its clickable.
This PR removes the "is-primary" class on the task id which is overriding the default a tag styling. This PR follows the linking pattern in the HashiCorp Design System.
Here's the current appearance:
Here's how linking is in the HashiCorp Design System:
PS: I'd love an internship with the HashiCorp Design System team!
> style: Remove "is-primary" class from TaskRow

- .changelog/15454.txt
- ui/app/controllers/exec.js
Fixes an issue where namespaces weren't being respected in Exec window URLs upon refresh (they were on initial load, by virtue of having the full job object passed in via openExecUrl). 
Resolves #13921
> [ui] Add namespaces to exec window

- .changelog/15458.txt
- ui/app/components/allocation-service-sidebar.hbs
- ui/app/models/service-fragment.js
- ui/app/models/service.js
- ui/app/styles/components/services.scss
- ui/app/styles/core/tag.scss
- ui/app/templates/allocations/allocation/index.hbs
- ui/app/templates/components/job-service-row.hbs
Appending, with a custom style, to anyplace we show service tags:
Resolves #13018
> [ui] Adding canary_tags the web UI

- command/acl_auth_method_create.go
Corrected indentation for `-config` option:
```
ACL Auth Method Create Options:
-name
Sets the human readable name for the ACL auth method. The name must be
between 1-128 characters and is a required parameter.
-type
Sets the type of the auth method. Currently the only supported type is
'OIDC'.
-max-token-ttl
Sets the duration of time all tokens created by this auth method should be
valid for.
-token-locality
Defines the kind of token that this auth method should produce. This can be
either 'local' or 'global'.
-default
Specifies whether this auth method should be treated as a default one in
case no auth method is explicitly specified for a login command.
-config
Auth method configuration in JSON format. May be prefixed with '@' to
indicate that the value is a file path to load the config …
```
> bugfix: corrected indentation for ACL auth method create CLI command

- nomad/server.go
Streaming RPCs should only be registered once, not on every RPC call, because they set keys in [`StreamingRpcRegistry.registry` map](https://github.com/hashicorp/nomad/blob/main/nomad/structs/streaming_rpc.go#L42). This PR fixes it by checking whether endpoints are already registered before calling `.register()` method. Fixes #15474
> bugfix: make sure streaming endpoints are only registered once

- nomad/acl_endpoint.go
- nomad/mock/acl.go
- nomad/state/state_store_acl_sso.go
- nomad/structs/acl.go
- nomad/structs/acl_test.go
> acl: canonicalize ACL Auth Method object

- helper/pointer/pointer.go
- helper/pointer/pointer_test.go
This PR adds `Merge(previous, next)` helper function for choosing which value of two pointers
to use during a larger merge operation.
If `next` is not nil, use that value, otherwise use the `previous` value.
This will help cleanup some other code which does a lot of manual if-statements when merging a struct full of pointer fields. E.g.
```go
// ... merge ...
return &ArtifactConfig{
HTTPReadTimeout: pointer.Merge(a.HTTPReadTimeout, o.HTTPReadTimeout),
HTTPMaxSize:     pointer.Merge(a.HTTPMaxSize, o.HTTPMaxSize),
GCSTimeout:      pointer.Merge(a.GCSTimeout, o.GCSTimeout),
GitTimeout:      pointer.Merge(a.GitTimeout, o.GitTimeout),
HgTimeout:       pointer.Merge(a.HgTimeout, o.HgTimeout),
S3Timeout:       pointer.Merge(a.S3Timeout, o.S3Timeout),
}
```
> pointer: add Merge helper function for merging pointers

- client/allocrunner/taskrunner/getter/params.go
- client/allocrunner/taskrunner/getter/params_test.go
- client/allocrunner/taskrunner/getter/sandbox.go
- client/allocrunner/taskrunner/getter/util.go
- client/allocrunner/taskrunner/getter/z_getter_cmd.go
- client/config/artifact.go
- nomad/structs/config/artifact.go
- nomad/structs/config/artifact_test.go
- website/content/docs/configuration/client.mdx
- website/content/docs/upgrade/upgrade-specific.mdx
This PR adds the client config option for turning off filesystem isolation,
applicable on Linux systems where filesystem isolation is possible and
enabled by default.
```hcl
client{
artifact {
disable_filesystem_isolation = <bool:false>
}
}
```
Closes #15496
> artifact: add client toggle to disable filesystem isolation

- website/content/api-docs/acl/auth-methods.mdx
- website/content/api-docs/acl/index.mdx
- website/data/api-docs-nav-data.json
This PR provides documentation for the ACL Auth Methods API endpoints. 
Relates to #13120
> acl: SSO auth methods API documentation

- nomad/acl_endpoint.go
- nomad/acl_endpoint_test.go
- nomad/mock/acl.go
- nomad/state/state_store_acl_sso.go
- nomad/state/state_store_acl_sso_test.go
This PR adds a check that makes sure we don't insert a duplicate `default` ACL auth method for a given type. 
Relates to #13120
> acl: make sure there is only one default Auth Method per type

- .github/workflows/build.yml
- Use custom github hosted runners for building nomad on linux. These are version pinned to ubuntu 20.04, and only available to the repos `nomad` and `nomad-enterprise`. More context is available in https://github.com/hashicorp/nomad-enterprise/pull/969#issuecomment-1341641159
- Remove set-output deprecation warnings in each github actions run by following https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> Use custom runners for building nomad

- client/allocrunner/taskrunner/getter/params.go
- client/allocrunner/taskrunner/getter/params_test.go
- client/allocrunner/taskrunner/getter/sandbox.go
- client/allocrunner/taskrunner/getter/util.go
- client/allocrunner/taskrunner/getter/util_default.go
- client/allocrunner/taskrunner/getter/util_linux.go
- client/allocrunner/taskrunner/getter/util_test.go
- client/allocrunner/taskrunner/getter/util_windows.go
- client/config/artifact.go
- client/config/artifact_test.go
- nomad/structs/config/artifact.go
- nomad/structs/config/artifact_test.go
- website/content/docs/configuration/client.mdx
- website/content/docs/upgrade/upgrade-specific.mdx
This PR adds client configuration for specifying environment variables that
should be inherited by the artifact sandbox process from the Nomad Client agent.
Most users should not need to set these values but the configuration is provided
to ensure backwards compatability. Configuration of go-getter should ideally be
done through the artifact block in a jobspec task.
e.g.
```hcl
client {
artifact {
set_environment_variables = "TMPDIR,GIT_SSH_OPTS"
}
}
```
Closes #15497
> artifact: enable inheriting environment variables from client

- ui/app/components/variable-form.hbs
- ui/app/components/variable-form.js
- ui/app/styles/components/variables.scss
- ui/tests/integration/components/variable-form-test.js
Resolves [#15345](https://github.com/hashicorp/nomad/issues/15345) and [#15346](https://github.com/hashicorp/nomad/issues/15346).
Users are accidentally adding more variables when the mean to save the variable because of the placement of "add more" button.
> ui:  move "add more" button in variable create and edit forms

- .github/workflows/build.yml
Backport of https://github.com/hashicorp/nomad/pull/15490
Note: The build workflow wasn't being kicked off on the `release/1.3.x branch`, so I updated that 🙏
> Backport of Use custom runners for building nomad into release/1.3.x

- .github/workflows/build.yml
Backport of https://github.com/hashicorp/nomad/pull/15490
Note: The build workflow wasn't being kicked off on the `release/1.4.x branch`, so I updated that 🙏
> Backport of Use custom runners for building nomad into release/1.4.x

- helper/raftutil/msgtypes.go
- nomad/fsm.go
- nomad/fsm_test.go
- nomad/mock/acl.go
- nomad/state/schema.go
- nomad/state/state_store_acl_binding_rule.go
- nomad/state/state_store_acl_binding_rule_test.go
- nomad/state/state_store_restore.go
- nomad/state/state_store_restore_test.go
- nomad/structs/acl.go
- nomad/structs/acl_test.go
- nomad/structs/structs.go
This change adds a new table that will store ACL binding rule objects. The two indexes allow fast lookups by their ID, or by which auth method they are linked to. Snapshot persist and restore functionality ensures this table can be saved and restored from snapshots.
In order to write and delete the object to state, new Raft messages have been added.
All RPC request and response structs, along with object functions such as diff and canonicalize have been included within this work as it is nicely separated from the other areas of work.
Related #13120
> acl: add binding rule object state schema and functionality.

- website/content/docs/commands/acl/auth-method/create.mdx
- website/content/docs/commands/acl/auth-method/delete.mdx
- website/content/docs/commands/acl/auth-method/info.mdx
- website/content/docs/commands/acl/auth-method/list.mdx
- website/content/docs/commands/acl/auth-method/update.mdx
- website/content/docs/commands/acl/index.mdx
- website/data/docs-nav-data.json
This PR provides documentation for the ACL Auth Methods CLI commands.
Relates to https://github.com/hashicorp/nomad/issues/13120
> acl: SSO auth methods CLI documentation

- .changelog/15435.txt
- ui/app/abilities/token.js
- ui/app/adapters/token.js
- ui/app/components/policy-editor.js
- ui/app/components/tooltip.js
- ui/app/controllers/policies/index.js
- ui/app/controllers/policies/policy.js
- ui/app/routes/policies.js
- ui/app/routes/policies/policy.js
- ui/app/styles/components/policies.scss
- ui/app/templates/policies/index.hbs
- ui/app/templates/policies/policy.hbs
- ui/mirage/config.js
- ui/mirage/factories/token.js
- ui/tests/acceptance/policies-test.js
- ui/tests/acceptance/token-test.js
- ui/tests/unit/abilities/token-test.js
Adds the ability to view, delete, and create tokens associated with a given policy in the new [Policies UI](https://github.com/hashicorp/nomad/pull/13976).
Ability to do any of this is available only to `manager` tokens only.
> [ui] Token management interface on policy pages

- nomad/leader.go
- nomad/leader_test.go
- nomad/structs/acl.go
ACL binding rule create and deletes are always forwarded to the authoritative region. In order to make these available in federated regions, the leaders in these regions need to replicate from the authoritative.
Related #13120
> core: add ACL binding rule to replication system.

- .changelog/12582.txt
- command/job_stop.go
- command/job_stop_test.go
- website/content/docs/commands/job/stop.mdx
Closes #2390
Signed-off-by: danishprakash <grafitykoncept@gmail.com>
> command/job_stop: accept multiple jobs, stop concurrently

- helper/funcs.go
- nomad/acl_endpoint.go
- nomad/acl_endpoint_test.go
- nomad/structs/acl.go
- nomad/structs/acl_test.go
API and RPC endpoints for `ACLAuthMethod`s and `ACLBindingRule`s should allow users to send incomplete objects in order to, e.g., update single fields. This PR provides "merging" functionality for these endpoints. 
Relates to #13120
> acl: modify update endpoints behavior

- nomad/state/state_store_acl_binding_rule_test.go
Unit test for GetACLBindingRules state store method would fail because we'd expect order of returned items.
vide discussion under #15580
> bugfix: unit test for GetACLBindingRules

- ui/app/components/forbidden-message.js
- ui/app/helpers/conditionally-capitalize.js
- ui/app/templates/components/forbidden-message.hbs
- ui/tests/integration/helpers/conditionally-capitalize-test.js
Resolves https://github.com/hashicorp/nomad/issues/15556
Signed out, have auth-methods configured:
Signed out, no auth-methods:
Signed in, but lacking permissions:
> [ui] Make the not-auth'd messages in the app less token-centric

- .circleci/config.yml
This PR remove the lint-go workflow from circle; we already have the linting
covered in GHA and the circle stuff is just outdated anyway.
> ci: remove lint workflow from circle

- nomad/structs/variables.go
- nomad/structs/variables_test.go
- ui/app/components/variable-form.js
- ui/tests/acceptance/variables-test.js
Sets the ability for Nomad Variables with paths that start with `nomad/` to include `job-templates`. Previously only variables at `nomad/jobs/____` were permitted.
---
Resolves #15569
> Extend variables under the nomad path prefix to allow for job-templates

- command/agent/testagent.go
- command/helpers.go
- command/helpers_test.go
- command/job_stop_test.go
This PR refactors / fixes the StopCommand test that runs 10 jobs and then
passes them all to one invokation of 'job stop'. Never actually dug into why
the previous test implementation was failing, but I didn't like the async setup
hoop jumping anyway.
Also fixes `TestStopCommand_Fails` failures, where the error messages from `job stop` 
are different now (also due to https://github.com/hashicorp/nomad/pull/12582)
Closes https://github.com/hashicorp/nomad/issues/15575
> command: fixup tests concerning multi job stop

- ui/app/serializers/variable.js
The `VariableSerializer` currently does not save key/value pairs when querying multiple `Variable` records. This PR updates the `normalize` method to use the same logic in the `serialize` method to extract the `key/value` attributes form the `Items` property on `Variable` so that we can use that logic in the `jobs.run.templates.index` view where we need to visualize this data.
> ui:  update `VariableSerializer` normalize method

- api/acl_test.go
- api/agent_test.go
- api/allocations_test.go
- api/api_test.go
- api/compose_test.go
- api/constraint_test.go
- api/consul_test.go
- api/csi_test.go
- api/evaluations_test.go
- api/event_stream_test.go
- api/fs_test.go
- api/go.mod
- api/go.sum
- api/ioutil_test.go
- api/jobs_test.go
- api/keyring_test.go
- api/operator_ent_test.go
- api/operator_metrics_test.go
- api/operator_test.go
- api/quota_test.go
- api/resources_test.go
- api/scaling_test.go
- api/search_test.go
- api/sentinel_test.go
- api/services_test.go
- api/status_test.go
- api/system_test.go
- api/tasks_test.go
- api/utils_test.go
- api/variables_test.go
This PR refactors API tests to no longer depend on testify or pretty.
> api: purge testify and pretty dependencies 

- .changelog/15605.txt
- command/agent/http.go
- command/agent/http_test.go
Hi Nomad core dev team,
Please let me know if there are other places I need to make changes too. Thank you !
Resolve: #15562
> fix: `stale` querystring parameter value as boolean

- command/agent/operator_endpoint_test.go
- internal/testing/apitests/operator_autopilot_test.go
- internal/testing/apitests/operator_test.go
- nomad/leader_test.go
This PR removes usages of `consul/sdk/testutil/retry`, as part of the
ongoing effort to remove use of any non-API module from Consul.
There is one remanining usage in the helper/freeport package, but that
will get removed as part of #15589
> cleanup: remove usage of consul/sdk/testutil/retry

- website/content/api-docs/system.mdx
added the missing PUT http method for /v1/system/reconcile/summaries
> docs: fix system sample request

- nomad/structs/variables.go
- nomad/structs/variables_test.go
- ui/app/components/variable-form.js
Realized the existing code would let you write to `nomad/job-templates` with no suffix. This disallows writing there but allows you to write to `nomad/job-templates/foo`.
In so doing, refactored the switch statement for path name error handling.
> Disallows variables at exactly nomad/job-templates

- .changelog/15670.txt
- command/agent/csi_endpoint.go
- command/agent/csi_endpoint_test.go
- command/volume_delete.go
- command/volume_snapshot_create.go
- command/volume_snapshot_delete.go
- command/volume_snapshot_list.go
Fixes https://github.com/hashicorp/nomad/issues/15663
The command line flag parsing and the HTTP header parsing for CSI secrets incorrectly split at more than one '=' rune, making it impossible to use secrets that included that rune.
> csi: Fix parsing of '=' in secrets at command line and HTTP

- api/jobs_test.go
This assertions got borked during the refactoring; should be at least one element, not exactly one element.
Closes https://github.com/hashicorp/nomad/issues/15671
> tests: fix assertion for slice length

- .changelog/15625.txt
- command/agent/command.go
- website/content/docs/configuration/index.mdx
Fix issue : #15087
Hi Nomad Core Dev team,
Below is my attempt to fix the issue mentioned above. Imo, we can either make an extra argument for syslog log level or make it inherit from Nomad Agent existing one. This PR is using the latter approach because there is not need to use the former for a rarely used feature.
Would appreciate getting your feedback on this PR, especially on a few issues:
- On the mapping between gsyslog and Nomad Agent log, I'm not entirely sure about how `OFF` and `TRACE` in Nomad log_level maps to [gsyslog](https://pkg.go.dev/log/syslog) log level
- I attempted to write one similar to [TestCommand_Args()](https://github.com/hashicorp/nomad/blob/v1.4.3/command/agent/command_test.go#L26-L98) but the log is not captured by either `ui.ErrorWriter` or …
> fix: Make agent syslog log level inherit from Nomad agent log

- .github/workflows/test-core.yaml
Running tests `on: push` prevents GitHub from showing the workflow approval button, which prevents tests from being run on community-contributed (or even just non-Nomad HashiCorp folks) PRs. Running `on: pull_request` automatically picks up opened, reopened, and synchronize hooks (where "synchronize" means a push to HEAD on the PR's branch, so that'll pick up rebases and updates).
But we also want to run tests on `main` and the various `release` backport
branches, so retain a `on: push` for those.
Closes https://github.com/hashicorp/nomad/issues/15632
> CI: run tests on pull_request and push to main/release

- website/content/docs/job-specification/group.mdx
- website/content/docs/job-specification/task.mdx
Clarifies that the task and group level `shutdown_delay` parameters do not influence each other and that they apply to both Nomad and Consul service registrations.
The change also clarifies that service blocks apply to both Nomad and Consul service registrations.
Closes #15602
> docs: clarify shutdown_delay jobspec param and service behaviour.

- e2e/disconnectedclients/disconnectedclients_test.go
The e2e suite is not in good shape right now; let's disable the tests that modify
agent / node state until we can get things working again. Also the one DC test
that was enabled still doesn't work anyway.
> e2e: disable disconnected clients test(s)

- e2e/artifact/artifact_test.go
- e2e/artifact/input/artifact_windows.nomad
- fix wrong task name for one case
- comment out git windows test (still need to setup git on e2e windows client)
> e2e: fixup windows artifact download test cases

- command/job_init.go
- command/job_init_test.go
- ui/app/components/variable-form.hbs
- ui/app/components/variable-form.js
- ui/app/components/variable-form/job-template-editor.hbs
- ui/app/components/variable-form/job-template-editor.js
- ui/app/styles/components/variables.scss
- ui/tests/acceptance/variables-test.js
---
reads from all variables at `nomad/job-templates/...` and lists them out. 
---
- changes the interface when editing a variable at `nomad/job-templates/...` to have an interface that's less free-form, and specifically supports only editing description and template.
Resolves #15563
> Expanding nomad job init to accept a template flag

- client/allocrunner/taskrunner/getter/params.go
- client/allocrunner/taskrunner/getter/params_test.go
- client/allocrunner/taskrunner/getter/sandbox.go
- client/allocrunner/taskrunner/getter/util.go
- client/allocrunner/taskrunner/getter/util_default.go
- client/allocrunner/taskrunner/getter/util_linux.go
- client/allocrunner/taskrunner/getter/util_test.go
- client/allocrunner/taskrunner/getter/util_windows.go
- client/allocrunner/taskrunner/getter/z_getter_cmd.go
- e2e/artifact/artifact_test.go
- e2e/artifact/input/artifact_linux.nomad
This PR fixes the artifact sandbox (new in Nomad 1.5) to allow downloading
artifacts into the shared 'alloc' directory made available to each task in
a common allocation. Previously we assumed the 'alloc' dir would be mounted
under the 'task' dir, but this is only the case in fs isolation: chroot; in
other modes the alloc dir is elsewhere.
Closes https://github.com/hashicorp/nomad/issues/15711
> artifact: fix sandbox behavior when destination is shared alloc directory

- .changelog/15732.txt
- drivers/docker/network.go
- drivers/docker/network_test.go
This PR modifies the configuration of the networking pause contaier to include the "unless-stopped" restart policy. The pause container should always be restored into a running state until Nomad itself issues a stop command for the container.
This is not a _perfect_ fix for #12216 but it should cover the 99% use case - where a pause container gets accidentally killed / exits for some reason. There is still a possibility where the pause container and main task container are stopped and started in the order where the bad behavior persists, but this is fundamentally unavoidable due to how docker itself abstracts and manages the underlying network namespace referenced by the containers.
Closes #12216
> docker: configure restart policy for networking pause container

- .semgrep/rpc_endpoint.yml
- nomad/acl.go
- nomad/acl_endpoint.go
- nomad/acl_test.go
- nomad/namespace_endpoint.go
- nomad/structs/structs.go
This changeset covers a sidebar discussion that @schmichael and I had around the
design for pre-forwarding auth. This includes some changes extracted out of
#15513 to make it easier to review both and leave a clean history. 
* Remove fast path for NodeID: Previously-connected clients will have a NodeID
set on the context, and because this is a large portion of the RPCs sent we
fast-pathed it at the top of the `Authenticate` method. But the context is
shared for all yamux streams over the same yamux session (and TCP
connection). This lets an authenticated HTTP request to a client use the NodeID
for authentication, which is a privilege escalation. Remove the fast path and
annotate it so that we don't break it again.
* Add context to decisions. The `Authenticate` method taken on its own …
> Authenticate method improvements

- go.mod
- go.sum
- lib/auth/binder.go
- lib/auth/oidc/binder.go
- lib/auth/oidc/binder_test.go
- lib/auth/oidc/claims.go
- lib/auth/oidc/claims_test.go
- nomad/structs/acl.go
- nomad/structs/structs.go
`Binder` provides an interface for binding claims and ACL roles/policies of Nomad.
> acl: binding rules evaluation

- .changelog/15745.txt
- client/fingerprint/vault.go
- client/vaultclient/vaultclient.go
- client/vaultclient/vaultclient_test.go
- e2e/e2eutil/client.go
- e2e/framework/provisioner.go
- helper/useragent/useragent.go
- nomad/vault.go
- testutil/vault.go
This PR attempts to set the User-Agent header on each Vault API client
created by Nomad. Still need to figure a way to set User-Agent on the
Vault client created internally by consul-template.
Partial of https://github.com/hashicorp/nomad/issues/15629
> vault: configure user agent on Nomad vault clients

- .changelog/15455.txt
- scheduler/feasible.go
- scheduler/feasible_test.go
- website/content/docs/job-specification/device.mdx
Devices are fingerprinted as groups of similar devices. This prevented specifying specific device by their ID in constraint and affinity rules.
This commit introduces the `${device.ids}` attribute that returns a comma separated list of IDs that are part of the device group. Users can then use the set operators to write rules.
Closes https://github.com/hashicorp/nomad-device-nvidia/issues/11
> scheduler: allow using device ID as attribute

- .changelog/15733.txt
- ui/app/components/task-context-sidebar.hbs
- ui/app/styles/components/sidebar.scss
Shows Task Events in the Nomad UI sidebar. Accessible via Job or Task Group pages.
Resolves #15730
> [ui] Show task events in the sidebar

- .changelog/15552.txt
- command/agent/agent.go
- command/agent/config.go
- nomad/server.go
- website/content/docs/upgrade/upgrade-specific.mdx
This will effectively change the default behavior of Serf to _not_ rejoin after leave, which (I believe...) is actually the documented behavior. But this could be perceived as a breaking change by some cluster operators who may be accustomed to server nodes ignoring leave events.
Alternative approaches which would not change the default behavior would be
* use a bool pointer in this config field in order to be able to discern `nil` (not configured) from intentionally `false`, and default to `true` as exists today
* introduce a new config field `disable_rejoin_after_leave` which would default to `false` and therefore continue to produce the current behavior
In any case, docs probably need to be updated here and if necessary, a behavior change be communicated out.
> Fix rejoin_after_leave behavior

- .changelog/15761.txt
- api/consul.go
- api/consul_test.go
- api/go.mod
- api/go.sum
- client/taskenv/services.go
- client/taskenv/services_test.go
- command/agent/consul/connect.go
- command/agent/consul/connect_test.go
- command/agent/job_endpoint.go
- go.mod
- go.sum
- nomad/structs/services.go
- nomad/structs/services_test.go
- website/content/docs/job-specification/proxy.mdx
- website/content/docs/job-specification/upstreams.mdx
This PR adds support for configuring `proxy.upstreams[].config` for
Consul Connect upstreams. This is an opaque config value to Nomad -
the data is passed directly to Consul and is unknown to Nomad.
Closes #11392
> consul/connect: support for proxy upstreams opaque config

- api/consul.go
- jobspec2/parse_test.go
- jobspec2/test-fixtures/connect-example.hcl
I forgot that I created an uncommitted change while testing https://github.com/hashicorp/nomad/pull/15761. Adds the fix and adds a relevant parsing test too.
> consul/connect: use block not optional for opaque map

- website/content/docs/commands/operator/client-state.mdx
Adds missing indentation from a frontmatter's `description`.
> [docs] Fixing yaml syntax in frontmatter

- .changelog/15558.txt
- api/fs.go
- api/go.mod
- api/go.sum
To see why I think this is a good change lets look at why I am making it
My disk was full, which means GC was happening agressively. So by the time I called the logging endpoint from the SDK, the logs were GC'd
The error I was getting before was:
```
invalid character 'i' in literal false (expecting 'l')
```
Now the error I get is:
```
failed to decode log endpoint response as JSON: "failed to list entries: open /tmp/nomad.data.4219353875/alloc/f11fee50-2b66-a7a2-d3ec-8442cb3d557a/alloc/logs: no such file or directory"
```
Still not super descriptive but much more debugable
> Return buffered text from log endpoint if decoding fails

- .changelog/15797.txt
- command/fmt.go
- command/fmt_test.go
Hi team,
This PR is to resolve issue #15740. Could you help to review when you have time ?
> fix bug in nomad fmt -check does not return error code

- website/content/docs/faq.mdx
- website/content/docs/install/index.mdx
- website/content/docs/job-specification/upstreams.mdx
- website/content/docs/partnerships.mdx
- website/content/plugins/drivers/remote/index.mdx
- Fixes a typo in a tutorial link in `website/content/docs/faq.mdx`
- Updates two old `learn.hashicorp.com` links that redirect to their devdot paths
- Updates a link in `website/content/docs/partnerships.mdx` to go to `/nomad/intro` instead of `/` (which was previously the nomadproject.io hompage)
- Removes an extra space from a definition in `website/content/plugins/drivers/remote/index.mdx`
> [docs] Adjusting links for rewrite project

- command/acl_auth_method_list_test.go
- nomad/acl_endpoint.go
- ui/app/adapters/auth-method.js
- ui/app/controllers/settings/tokens.js
- ui/app/templates/settings/tokens.hbs
- ui/mirage/config.js
This changes some properties to match expected endpoint props (AuthMethod -> AuthMethodName), and adds redirect URIs to requests.
Additionally, makes a change to the `list auth methods` API endpoint to not check for authentication (as we want to provide auth methods for users who are signed out, have invalid or expired tokens, etc.)
> [sso] OIDC Updates for the UI

- command/login.go
- lib/auth/oidc/server.go
- lib/auth/oidc/server_test.go
The change also impacts the callback server and ensures that the URL it returns is true to what was passed. Without this change, passing `localhost` would always mean the callback would return the IP translated address from the `RedirectURI` func.
> cli: use localhost for default login callback address.

- .changelog/15191.txt
- .changelog/15816.txt
Removed the entry regarding auth method schema and state.
Adds feature entry for SSO via OIDC. I used the login PR as we need to link to a single entry; although this feature was the result of a large number of PRs.
> changelog: add feature entry for SSO OIDC

- .changelog/15822.txt
- client/allochealth/tracker.go
- client/allochealth/tracker_test.go
- client/serviceregistration/service_registration.go
- nomad/structs/structs.go
This PR fixes a bug where Nomad assumed any registered Checks would exist
in the service registration coming back from Consul. In some cases, the
Consul may be slow in processing the check registration, and the response
object would not contain checks. Nomad would then scan the empty response
looking for Checks with failing health status, finding none, and then
marking a task/alloc as healthy.
In reality, we must always use Nomad's view of what checks should exist as
the source of truth, and compare that with the response Consul gives us,
making sure they match, before scanning the Consul response for failing
check statuses.
Fixes #15536
> consul: correctly interpret missing consul checks as unhealthy

- ui/app/controllers/jobs/run/templates/manage.js
- ui/app/helpers/create-columns.js
- ui/app/helpers/invoke-fn.js
- ui/app/routes/jobs/run/templates/manage.js
- ui/app/templates/jobs/run/templates/index.hbs
- ui/app/templates/jobs/run/templates/manage.hbs
- ui/tests/acceptance/job-run-test.js
> ui: job templates manager view

- .changelog/15835.txt
- nomad/eval_broker.go
- nomad/eval_broker_test.go
- website/content/docs/operations/metrics-reference.mdx
- website/content/docs/operations/monitoring-nomad.mdx
- website/content/docs/upgrade/upgrade-specific.mdx
Fixes https://github.com/hashicorp/nomad/issues/6480 and addresses comments from https://github.com/hashicorp/nomad/pull/14621#discussion_r1023293596
This changeset fixes a long-standing point of confusion in metrics emitted by the eval broker. The eval broker has a queue of "blocked" evals that are waiting for an in-flight ("unacked") eval of the same job to be completed. But this "blocked" state is not the same as the `blocked` status that we write to raft and expose in the Nomad API to end users. There's a second metric `nomad.blocked_eval.total_blocked` that refers to evaluations in that state. This has caused ongoing confusion in major customer incidents and even in our own documentation! (Fixed in this PR.)
There's little functional change in this PR aside from the name of the …
> Rename `nomad.broker.total_blocked` metric

- website/content/docs/operations/monitoring-nomad.mdx
In #15835 we renamed the `nomad.broker.total_blocked` metric to `nomad.broker.total_pending`, but in the process identified that the existing scheduling performance monitoring guide mixed up the `broker.total_blocked` metric with the `blocked_evals.total_blocked` metric. This changeset backports the fix to the docs without renaming the metric (for backwards compatibility).
> docs: backport fix for metrics on blocked_evals vs broker

- .changelog/15842.txt
- client/allocrunner/taskrunner/task_runner.go
- client/logmon/logmon.go
Fixes #15840
While this makes Nomad client agent logging noisier, I think it adds a lot of value. See #15840 for details.
Starting and stopping a task before this change (5 lines, 1011 bytes w/timestamps):
```
[INFO]  client: node registration complete
[INFO]  client.alloc_runner.task_runner.task_hook.logmon.nomad-1.4.3: opening fifo: alloc_id=701624a4-d78d-c5e7-bd17-47ce170d65ce task=sleepy @module=logmon path=/tmp/NomadClient582607065/701624a4-d78d-c5e7-bd17-47ce170d65ce/alloc/logs/.sleepy.stdout.fifo timestamp=2023-01-20T11:35:20.575-0800
[INFO]  client.alloc_runner.task_runner.task_hook.logmon.nomad-1.4.3: opening fifo: alloc_id=701624a4-d78d-c5e7-bd17-47ce170d65ce task=sleepy @module=logmon path=/tmp/NomadClient582607065/701624a4-d78d-c5e7-bd17-47ce170d65ce/alloc/logs/.sleepy.stderr.f …
```
> Add INFO task even log line and make logmon less noisy

- .changelog/15852.txt
- client/config/config.go
- client/fingerprint/storage.go
- command/agent/agent.go
- command/agent/config.go
- website/content/docs/configuration/client.mdx
@tgross as suggested in https://github.com/hashicorp/nomad/issues/6172#issuecomment-1377479562 and in regard to your positive reply I implemented the config options `disk_total_mb` and `disk_free_mb`. This is my first PR to nomad and none of the checklists in the contributing folder seems to fit those changes. Therefore I'm not sure if something is missing or how to proceed. I'm looking forward to your feedback.
> Add disk_total_mb and disk_free_mb client config options

- client/client_test.go
- client/rpc.go
- command/agent/agent_test.go
- nomad/deployment_endpoint.go
- nomad/eval_endpoint.go
- nomad/namespace_endpoint.go
- nomad/node_endpoint.go
- nomad/rpc_test.go
- nomad/server_test.go
- nomad/status_endpoint.go
- nomad/status_endpoint_test.go
- nomad/variables_endpoint.go
- nomad/variables_endpoint_test.go
In #15417 we added a new `Authenticate` method to the server that returns an `AuthenticatedIdentity` struct. This changeset implements this method for a small number of RPC endpoints that together represent all the various ways in which RPCs are sent, so that we can validate that we're happy with this approach.
A follow-up PR will do all the dirty work of adding this everywhere else.
> implement pre-forwarding auth on select RPCs

- .changelog/15819.txt
- drivers/docker/config.go
- drivers/docker/driver.go
- website/content/docs/drivers/docker.mdx
This change enables the --isolation=hyper-v flag in the docker driver for Windows users. 
Prior to this change attempts to use the flag would cause an error in Nomad.
> Adds docker isolation option

- nomad/acl.go
- nomad/acl_test.go
- nomad/namespace_endpoint_test.go
If a consumer of the new `Authenticate` method gets passed a bogus token that's a correctly-shaped UUID, it will correctly get an identity without a ACL token. But most consumers will then panic when they consume this nil `ACLToken` for authorization.
Because no API client should ever send a bogus auth token, update the `Authenticate` method to create the identity with remote IP (for metrics tracking) but also return an `ErrPermissionDenied`.
---
I hit this while adding the `Authenticate` to a broader set of APIs, in particular the CSI endpoint that has special authorization handling b/c it takes both nodes and tokens.
> acl: Fix panic when bogus token is passed

- .changelog/15870.txt
- .semgrep/rpc_endpoint.yml
- nomad/acl.go
- nomad/acl_endpoint.go
- nomad/acl_endpoint_test.go
- nomad/alloc_endpoint.go
- nomad/alloc_endpoint_test.go
- nomad/client_agent_endpoint.go
- nomad/client_alloc_endpoint.go
- nomad/client_fs_endpoint.go
- nomad/client_stats_endpoint.go
- nomad/csi_endpoint.go
- nomad/deployment_endpoint.go
- nomad/eval_endpoint.go
- nomad/event_endpoint.go
- nomad/job_endpoint.go
- nomad/keyring_endpoint.go
- nomad/namespace_endpoint.go
- nomad/node_endpoint.go
- nomad/operator_endpoint.go
- nomad/operator_endpoint_test.go
- nomad/periodic_endpoint.go
- nomad/scaling_endpoint.go
- nomad/search_endpoint.go
- nomad/service_registration_endpoint.go
- nomad/status_endpoint.go
- nomad/system_endpoint.go
- nomad/variables_endpoint.go
This changeset allows Workload Identities to authenticate to all the RPCs that
support HTTP API endpoints, for use with PR #15864.
* Extends the work done for pre-forwarding authentication to all RPCs that
support a HTTP API endpoint.
* Consolidates the auth helpers used by the CSI, Service Registration, and Node
endpoints that are currently used to support both tokens and client secrets.
Intentionally excluded from this changeset:
* The Variables endpoint still has custom handling because of the implicit
policies. Ideally we'll figure out an efficient way to resolve those into real
policies and then we can get rid of that custom handling.
* The RPCs that don't currently support auth tokens (i.e. those that don't
support HTTP endpoints) have not been updated with the new pre-forwarding …
> WI: allow workloads to use RPCs associated with HTTP API

- .changelog/15808.txt
- nomad/fsm_test.go
- nomad/node_endpoint.go
- nomad/node_endpoint_test.go
- nomad/state/state_store.go
- nomad/state/state_store_test.go
- nomad/structs/structs.go
- testutil/wait.go
When a Nomad client that is running an allocation with `max_client_disconnect` set misses a heartbeat the Nomad server will update its status to `disconnected`.
Upon reconnecting, the client will make three main RPC calls:
- `Node.UpdateStatus` is used to set the client status to `ready`.
- `Node.UpdateAlloc` is used to update the client-side information about
allocations, such as their `ClientStatus`, task states etc.
- `Node.Register` is used to upsert the entire node information,
including its status.
These calls are made concurrently and are also running in parallel with the scheduler. Depending on the order they run the scheduler may end up with incomplete data when reconciling allocations. 
#15068 already enforced clients to heartbeat before updating their allocation data, but there …
> core: enforce strict steps for clients reconnect

- website/content/docs/job-specification/hcl2/expressions.mdx
Some values in the jobspec are opaque to Nomad, such as a task `config` or a scaling policy `policy` block. Since Nomad does not attempt to parse these fields it's not possible to use `dynamic` blocks inside them.
Closes #15850
> docs: add caveat on dynamic blocks

- .changelog/15876.txt
- nomad/acl_endpoint.go
- nomad/alloc_endpoint.go
- nomad/client_agent_endpoint.go
- nomad/client_alloc_endpoint.go
- nomad/client_fs_endpoint.go
- nomad/client_stats_endpoint.go
- nomad/csi_endpoint.go
- nomad/deployment_endpoint.go
- nomad/eval_endpoint.go
- nomad/event_endpoint.go
- nomad/job_endpoint.go
- nomad/keyring_endpoint.go
- nomad/namespace_endpoint.go
- nomad/node_endpoint.go
- nomad/operator_endpoint.go
- nomad/periodic_endpoint.go
- nomad/scaling_endpoint.go
- nomad/search_endpoint.go
- nomad/service_registration_endpoint.go
- nomad/status_endpoint.go
- nomad/system_endpoint.go
- nomad/variables_endpoint.go
This changeset configures the RPC rate metrics that were added in #15515 to all the RPCs that support authenticated HTTP API requests. These endpoints already configured with pre-forwarding authentication in #15870, and a handful of others were done already as part of the proof-of-concept work. So this changeset is entirely copy-and-pasting one method call into a whole mess of handlers.
Upcoming PRs will wire up pre-forwarding auth and rate metrics for the remaining set of RPCs that have no API consumers or aren't authenticated, in smaller chunks that can be more thoughtfully reviewed. (And add the metrics reference docs update.)
> metrics: measure rate of RPC requests that serve API

- website/content/plugins/drivers/podman.mdx
The Podman task driver implements the `user` attribute outside of the task config stanza, however the current Nomad docs have the task within the task config stanza.  This PR corrects this error.
https://github.com/hashicorp/nomad-driver-podman
> docs: correct "User" attribute in Podman Task Driver Docs

- api/acl.go
- command/acl_binding_rule_create.go
- command/acl_binding_rule_create_test.go
- command/acl_binding_rule_update.go
- command/acl_binding_rule_update_test.go
- lib/auth/oidc/binder.go
- lib/auth/oidc/binder_test.go
- nomad/acl_endpoint.go
- nomad/acl_endpoint_test.go
- nomad/structs/acl.go
- nomad/structs/acl_test.go
- website/content/api-docs/acl/binding-rules.mdx
- website/content/docs/commands/acl/binding-rule/create.mdx
- website/content/docs/commands/acl/binding-rule/update.mdx
This change allows binding rules to be created with a new type
named management. When this binding rule matches against a users
SSO claims, the resulting token will be of type management and not
client.
A match will supercede previous role or policy matches. This is
required as all binding rules are evaluated on login via
an auth method. It would be highly complex for users to ensure
those with rights to management tokens, do not match any other
binding rules.
When creating a binding rule of management type, the bind name
must be empty. This is account for within the validation logic, so
errors are clear for operators.
> sso: allow binding rules to create management ACL tokens.

- .changelog/15869.txt
- command/login.go
- command/login_test.go
- nomad/acl_endpoint.go
- nomad/state/state_store_acl_sso.go
- nomad/state/state_store_acl_sso_test.go
- website/content/docs/commands/login.mdx
As discussed with the team, we want to have `default` auth method across all types, for better UX. 
Relates to https://github.com/hashicorp/nomad/issues/13120
> acl: make auth method default across all types

- .changelog/15780.txt
- client/allocrunner/interfaces/task_lifecycle.go
- client/allocrunner/taskrunner/task_runner_hooks.go
- client/allocrunner/taskrunner/volume_hook.go
- nomad/structs/volume_test.go
- nomad/structs/volumes.go
- scheduler/feasible.go
- scheduler/feasible_test.go
- scheduler/stack.go
- website/content/docs/job-specification/update.mdx
- website/content/docs/job-specification/volume.mdx
Disallowing per_alloc for host volumes in some cases makes life of a nomad user much harder. When we rely on the NOMAD_ALLOC_INDEX for any configuration that needs to be re-used across restarts we need to make sure allocation placement is consistent. With CSI volumes we can use the `per_alloc` feature but for some reason this is explicitly disabled for host volumes.
I couldn't find a reason why this done, since as far as I could see the per_alloc is only used for the scheduler to determine placement.
> Allow per_alloc to be used with host volumes

- .changelog/15862.txt
- client/allocrunner/group_service_hook.go
- client/serviceregistration/nsd/nsd.go
- e2e/servicediscovery/input/checks_task_restart_helper.nomad
- e2e/servicediscovery/input/checks_task_restart_main.nomad
- e2e/servicediscovery/nomad_checks_test.go
- e2e/servicediscovery/service_discovery_test.go
This PR uses a WaitGroup to ensure workload removals are complete
before returning from ServiceRegistrationHandler.RemoveWorkload of
the nomad service provider. The de-registration of individual services
still occurs asynchrously, but we must block on the parent removal
call so that we do not race with further operations on the same set
of services - e.g. in the case of a task restart where we de-register
and then re-register the services in quick succession.
Fixes #15032
> nsd: block on removal of services

- nomad/structs/services_test.go
https://github.com/hashicorp/nomad/pull/15749 used `must` but this package was not imported in the `release/1.3.x` branch.
> test: add missing import to release/1.3.x

- nomad/structs/services_test.go
https://github.com/hashicorp/nomad/pull/15749 used `must` but this package was not imported in the `release/1.2.x` branch.
> test: add missing import to release/1.2.x

- client/allocrunner/taskrunner/getter/util_linux.go
- client/allocrunner/taskrunner/getter/util_test.go
This PR adjusts the artifact sandbox on Linux to enable reading from known
system-wide git or mercurial configuration, if they exist.
Folks doing something odd like specifying custom paths for global config will
need to use the standard locations, or disable artifact filesystem isolation.
Closes #15498
> artifact: enable reading system git/mercurial configuration

- .semgrep/rpc_metrics.yml
- nomad/alloc_endpoint.go
- nomad/deployment_endpoint.go
- nomad/eval_endpoint.go
- nomad/keyring_endpoint.go
- nomad/node_endpoint.go
- nomad/plan_endpoint.go
- nomad/service_registration_endpoint.go
Continues the work done in #15876 by extending rate metrics measurement over the various RPCs that are authenticated via TLS name validation. This changeset also canonicalizes the order-of-operations between `Authenticate` and that validation. We call `Authenticate` first so that we get identity info like the remote IP address. This changeset doesn't change the existing behavior that drops the RPC before forwarding; I think that's worth having a discussion about but I didn't want to bloat this PR with behavior changes.
> metrics: Add RPC rate metrics to endpoints that validate TLS names

- nomad/regions_endpoint.go
- nomad/stats_fetcher.go
- nomad/status_endpoint.go
Continues the work done in #15876 by extending rate metrics measurement over the various unauthenticated RPCs.
> metrics: Add metrics to unauthenticated endpoints

- .changelog/15906.txt
- ui/app/components/global-search/control.js
- ui/app/components/gutter-menu.js
- ui/app/components/job-version.js
- ui/tests/acceptance/job-versions-test.js
- ui/tests/acceptance/search-test.js
Use the new URL structure for navigating to a job page.
I started in the global search, but did a quick search to find other places with the same problem. I found this [`gotoJobsForNamespace` function](https://github.com/hashicorp/nomad/blob/v1.4.3/ui/app/components/gutter-menu.js#L46-L60) that I think it's also wrong, but it doesn't seem to be called from anywhere so maybe we can delete it?
Closes #15893
> ui: fix navigation for namespaced jobs in search and job version

- nomad/client_csi_endpoint.go
- nomad/client_csi_endpoint_test.go
- nomad/server.go
Continues the work done in https://github.com/hashicorp/nomad/pull/15876 by extending rate metrics measurement over client CSI endpoints (the last batch of stuff!)
Also tightens up authentication for these endpoints by enforcing the server certificate name is valid. We protect these endpoints currently by mTLS and can't use an auth token because these endpoints are (uniquely) called by the leader and followers for a given node won't have the leader's ephemeral ACL token. Add a certificate name check that requests come from a server and not a client, because no client should ever send these RPCs directly.
> metrics: Add rate metrics to Client CSI endpoints

- .changelog/15909.txt
- ui/app/utils/classes/allocation-stats-tracker.js
- ui/tests/unit/utils/allocation-stats-tracker-test.js
Match memory usage logic with the [CLI](https://github.com/hashicorp/nomad/blob/v1.4.3/command/alloc_status.go#L623-L628).
Closes #15830
> ui: fix alloc memory stats to match CLI output

- .semgrep/rpc_endpoint.yml
- client/alloc_endpoint_test.go
- command/agent/agent_endpoint_test.go
- command/agent/alloc_endpoint_test.go
- command/agent/stats_endpoint_test.go
- nomad/acl_endpoint.go
Continues the work done in #15876 by extending rate metrics measurement over a few stragglers that got missed in the original PR (probably because of concurrent PRs landing).
This changeset includes an update to the semgrep rule to add a rule for rate metrics, and another so that we're matching on only the currently used patterns. I've also left a some TODOs in the auth rule pointing to https://github.com/hashicorp/nomad/issues/15875, which isn't likely to ship in 1.5.0
> metrics: Add remaining server RPC rate metrics

- .changelog/15915.txt
- client/allocrunner/taskrunner/template_hook.go
When the template hook Update() method is called it may recreate the template manager if the Nomad or Vault token has been updated.
This caused the new template manager did not have a driver handler because this was only being set on the Poststart hook, which is not called for inplace updates.
Closes #15851
> template: restore driver handle on update

- .changelog/15477.txt
- client/allocrunner/alloc_runner.go
- client/allocrunner/alloc_runner_hooks.go
- client/allocrunner/alloc_runner_test.go
- client/allocrunner/alloc_runner_unix_test.go
This PR fixes a bug where alloc pre-kill hooks were not run in the
edge case where there are no live tasks remaining, but it is also
the final update to process for the (terminal) allocation. We need
to run cleanup hooks here, otherwise they will not run until the
allocation gets garbage collected (i.e. via Destroy()), possibly
at a distant time in the future.
Fixes #15477
> client: always run alloc cleanup hooks on final update

- website/content/docs/install/index.mdx
The getting started Tutorial has a post-installation steps section that includes installing CNI plugins. Many users will want to use `bridge` networking right out of the gate, so adding these same post-install instructions to the main docs will be a better Day 0 experience for them.
> docs: add post-install steps for CNI to main install docs page

- .changelog/15928.txt
- command/agent/consul/acl_testing.go
- nomad/consul_policy.go
- nomad/consul_policy_oss_test.go
When registering a job with a service and 'consul.allow_unauthenticated=false',
we scan the given Consul token for an acceptable policy or role with an
acceptable policy, but did not scan for an acceptable service identity (which
is backed by an acceptable virtual policy). This PR updates our consul token
validation to also accept a matching service identity when registering a service
into Consul.
Fixes #15902
> consul: check for acceptable service identity on consul tokens

- website/content/docs/concepts/acl.mdx
- website/data/docs-nav-data.json
An attempt at having some concept documentation on the main website that introduces that main areas of the ACL subsystem. While this information is also available within the tutorials, I feel having this available as a website page is useful as a reference, or for people who land and navigate the website as their learning process.
> docs: add ACL concepts page to introduce objects.

- command/acl_auth_method.go
- command/acl_auth_method_create.go
- command/acl_auth_method_info.go
- command/acl_auth_method_update.go
- website/content/docs/commands/acl/auth-method/create.mdx
- website/content/docs/commands/acl/auth-method/info.mdx
- website/content/docs/commands/acl/auth-method/update.mdx
"easier reading" is subjective, so interested in overall feedback on how this looks and what could be improved.
> cli: separate auth method config output for easier reading.

- .changelog/15940.txt
- website/content/docs/job-specification/meta.mdx
Hi team,
This PR will solve the issue #15359
> Fix documentation for `meta` block: string replacement in key from `-` to `_`

- .changelog/15541.txt
- api/consul.go
- api/consul_test.go
- command/agent/job_endpoint.go
- command/agent/job_endpoint_test.go
- jobspec/parse_service.go
- jobspec/parse_test.go
- nomad/structs/services.go
This renames two fields in the api for proxyConfig.
- ExposeConfig to Expose
- Path to Paths
The old fields are mantained for backwards compatibility
Fixes https://github.com/hashicorp/nomad/issues/11304
Fixes https://github.com/hashicorp/nomad/issues/12174
Fixes https://github.com/hashicorp/nomad/issues/9379
> Rename fields on proxyConfig

- .changelog/15898.txt
- drivers/docker/network.go
- drivers/docker/network_test.go
Currently infra containers are not cleaned up as part of the dangling container cleanup routine. The reason is that Nomad checks if a container is a Nomad owned container by verifying the existence of the: `com.hashicorp.nomad.alloc_id` label.
Ensure we set this label on the infra container as well.
> Ensure infra_image gets proper label used for reconciliation

- website/content/docs/commands/var/put.mdx
While you can use any string value for a variable Item's key name using characters that are outside of the set [unicode.Letter, unicode.Number, `_`] will require the `index` function for direct access.
[[Preview 🔎]](https://nomad-9zsrqb18n-hashicorp.vercel.app/nomad/docs/commands/var/put#restrictions)
> docs: Add info about variable item key name restrictions

- website/content/docs/job-specification/check.mdx
Fixed a broken markdown link. While looking, spotted a typo and an opportunity to tidy up some of the codeblocks
> docs: Fix broken link on job-specification/checks page

- .changelog/15962.txt
- drivers/docker/coordinator.go
- drivers/docker/coordinator_test.go
- website/content/docs/drivers/docker.mdx
This PR changes our call of docker client `RemoveImage()` to `RemoveImageExtended` with
the `Force=true` option set. This fixes a bug where an image referenced by more than
one tag could never be garbage collected by Nomad. The Force option only applies to
[stopped containers](https://docs.docker.com/engine/api/v1.41/#tag/Image/operation/ImageDelete); it does not affect running workloads.
Fixes https://github.com/hashicorp/nomad/issues/15760
> docker: set force=true on remove image to handle images referenced by multiple tags

- .changelog/15983.txt
- nomad/structs/variables.go
- website/content/api-docs/jobs.mdx
- website/content/api-docs/variables.mdx
- website/content/docs/commands/var/put.mdx
16 was a little bit too little overhead for common tasks
> Bumps max variable size to 64 KiB

- website/content/docs/job-specification/template.mdx
In the example code block in [Simple Load Balancing with Nomad Services](https://developer.hashicorp.com/nomad/docs/job-specification/template#simple-load-balancing-with-nomad-services), there is an extra `{{- end }}` which will cause that snippet of code to produce an error
> docs (typo fix): removed extra 'end' in one of the code blocks in template stanza documentation

- website/content/docs/upgrade/upgrade-specific.mdx
Upgrade notes for #15097.
I wasn't sure how to document this change since it applies to multiple versions and the `Nomad 1.5.0` already exists. I thinking duplication here is fine since we're not likely to change this and having all the major release upgrade notes under the same section makes it easier for people upgrading to 1.5.0.
> docs: add upgrade notice for batch GC changes

- .changelog/16000.txt
- command/agent/acl_endpoint_test.go
- nomad/acl_endpoint.go
- nomad/acl_endpoint_test.go
> acl: return 400 not 404 code when creating an invalid policy.

- .changelog/15999.txt
- api/acl.go
- command/agent/acl_endpoint_test.go
- nomad/structs/acl.go
- website/content/api-docs/acl/tokens.mdx
The ACL token decoding was not correctly handling time duration
syntax such as "1h" which forced people to use the nanosecond
representation via the HTTP API.
The change adds an unmarshal function which allows this syntax to
be used, along with other styles correctly.
It also includes a docs clarification on the validation params used for
TTL values.
closes #15960
> acl: fix a bug in token creation when parsing expiration TTLs. 

- .changelog/15996.txt
- e2e/consul/input/service_reversion.nomad
- e2e/consul/service_revert_test.go
- e2e/e2eutil/job.go
- nomad/job_endpoint.go
- consul: restore consul token on job during registration of a reversion
- e2e: add test for reverting a job with a consul service
Fixes https://github.com/hashicorp/nomad/issues/15964
> consul: restore consul token when reverting a job

- .changelog/13845.txt
- api/jobs.go
- command/job_run.go
I am new to this codebase, so unsure I have the best approach, but this fixes my issue in #13844. I traced the issue down to the nil pointer [here](https://github.com/hashicorp/nomad/blob/208b68221184fe5712272c13f4f307373fb9117e/api/jobs.go#L792), which is called [from this path](https://github.com/hashicorp/nomad/blob/208b68221184fe5712272c13f4f307373fb9117e/command/job_run.go#L349-L355).
This code is called after the job registration succeeds on the server. I believe the root of the issue is that when submitting an API job via the CLI, it is canonicalized server-side, but not client-side. Registration succeeds on the server, and then this code path is called. It references paths that have not been canonicalized with their default values, and fails.
Another option would be to …
> fix(#13844): canonicalize job to avoid nil pointer deference

- .changelog/16018.txt
- jobspec2/types.variables.go
Fixes https://github.com/hashicorp/nomad/issues/12513
---
Test using the example jobspec from #12513:
```
$ nomad job run -var 'image_id=foo-' example.nomad
Error getting job struct: Error parsing job file from example.nomad:
example.nomad:5,14-14: Missing required argument; The argument "condition" is required, but no definition was found.
example.nomad:5,3-13: Invalid variable validation specification; validation requires a condition.
```
> job parsing: fix panic when variable validation is missing condition

- .changelog/15522.txt
- .changelog/15819.txt
- tools/cl-entry/main.go
I noticed these while previewing the changelog from `main`.
> changelog: fix entries for #15522 and #15819

- api/acl.go
- nomad/structs/acl.go
targets `release/1.4.x`
caused by #16005 
reason: imports present on main due to auth-method feature, not present in 1.4.x release branch
> acl: fix imports required due to backport of change #16005

- command/agent/acl_endpoint_test.go
- nomad/acl_endpoint.go
- nomad/acl_endpoint_test.go
targets release/1.2.x
caused by https://github.com/hashicorp/nomad/pull/16002
reason: imports present on main, not present in 1.2.x release branch
> acl: fix imports required due to backport of change #16002

- .changelog/11170.txt
- command/agent/command.go
- command/agent/command_test.go
- command/assets/connect-short.nomad
- command/assets/connect.nomad
- command/assets/example-short.nomad
- command/assets/example.nomad
- command/testdata/example-short-bad.json
- nomad/node_endpoint.go
- nomad/structs/structs.go
- nomad/structs/structs_test.go
- scheduler/datacenters.go
- scheduler/generic_sched_test.go
- scheduler/util.go
- scheduler/util_test.go
- website/content/docs/job-specification/job.mdx
- website/content/docs/upgrade/upgrade-specific.mdx
This PR addresses the issue https://github.com/hashicorp/nomad/issues/9024
It uses the `filepath.Match` golang std lib to accomplish the matching, which is somewhat simpler and more intuitive than using a regex. Because of that simplicity, it should be minimally impactful.
It is not completely backwards compatible, as datacenters with "*", "]", "?" in their name may be impacted. I do not believe the requested feature could be implemented without a theoretical compatibility break, or an entirely new property (which feels worse).
The docs do not appear to be part of the project, at least not that I could see, so they would need to be updated as well.
The returned list of datacenters will no longer have keys with a node count of 0. This is because we cannot a priori determine the number of …
> Allow wildcard datacenters to be specified in job file

- .changelog/15961.txt
- client/allocrunner/alloc_runner_test.go
- client/allocrunner/network_manager_linux.go
- client/allocrunner/networking_bridge_linux.go
- client/allocrunner/networking_bridge_linux_test.go
- client/config/config.go
- client/fingerprint/bridge_default.go
- client/fingerprint/bridge_linux.go
- command/agent/agent.go
- command/agent/config.go
- website/content/docs/configuration/client.mdx
- Add `bridge_network_hairpin_mode` client config setting
- Add hairpin mode to bridge template; convert to go template
- add node attribute: nomad.bridge.hairpin_mode
- Add documentation
> client: Add option to enable hairpinMode on Nomad bridge

- GNUmakefile
- e2e/e2eutil/job.go
This PR updates golangci-lint to work better with go1.20 - the previous
version would cause in oom on 'make check'.
The baseArgs tweak fixes something the linter now finds (useless for-loop vs. append)
Part of https://github.com/hashicorp/nomad/issues/16022
> bootstrap: upgrade golangci-lint in prep for go1.20

- .changelog/16011.txt
- command/deployment_status.go
Fixes https://github.com/hashicorp/nomad/issues/15235
If a deployment fails, the `deployment status` command can get a nil deployment when it checks for a rollback deployment if there isn't one (or at least not one at the time of the query). Fix the panic.
Note that I'm intentionally punting on solving the old TODO here, as it'd just take too long for me to page all this code in. Dropping a quick panic fix was a small win between other tasks :grin:
> cli: Fix a panic in `deployment status` when scheduling is slow

- .changelog/15908.txt
- client/allocrunner/taskrunner/envoy_bootstrap_hook.go
- client/allocrunner/taskrunner/envoy_bootstrap_hook_test.go
- nomad/structs/structs.go
- website/content/docs/integrations/consul-connect.mdx
Largely a doc-ification of this commit message: d47678074bf8ae9ff2da3c91d0729bf03aee8446
This doesn't spell out all (or any of) the possible failure modes, but should be a good starting point for folks.
Relates to issue #12389 which doesn't have a straightforward solution, but this documentation at least puts some steps out on our website for people to try out.
Closes #12389
> docs: how to troubleshoot consul connect envoy

- .changelog/16006.txt
- nomad/structs/config/ui.go
- nomad/structs/config/ui_test.go
- ui/app/components/global-header.js
- ui/app/styles/core/navbar.scss
- ui/app/templates/application.hbs
- ui/app/templates/components/global-header.hbs
- ui/mirage/factories/agent.js
- ui/tests/acceptance/allocation-detail-test.js
- ui/tests/acceptance/behaviors/fs.js
- ui/tests/acceptance/client-detail-test.js
- ui/tests/acceptance/clients-list-test.js
- ui/tests/acceptance/exec-test.js
- ui/tests/acceptance/regions-test.js
- ui/tests/acceptance/server-detail-test.js
- ui/tests/acceptance/servers-list-test.js
- ui/tests/acceptance/task-detail-test.js
- ui/tests/acceptance/task-group-detail-test.js
- ui/tests/acceptance/task-logs-test.js
- ui/tests/acceptance/token-test.js
- website/content/docs/configuration/ui.mdx
Resolves #10813
Adds a label block to the Nomad agent config:
```
ui {
label {
text             = "Miami Datacenter"
background_color = "palegreen"
text_color       = "hotpink"
}
}
```
Also shows up in the `<title>` attribute for browser tabs etc.
> Label for the Web UI

- ui/app/styles/core/forms.scss
Fixes a misalignment on job template form footer button group:
> Footer styles re-applied to job template footer

- website/content/docs/commands/operator/keyring.mdx
- website/content/docs/commands/operator/metrics.mdx
- website/content/docs/job-specification/hcl2/expressions.mdx
Addresses some outstanding content errors detected with our content checks.
```
content/docs/commands/operator/keyring.mdx
1:1 error Document does not have a description key in its frontmatter. Add a description key at the top of the document. ensure-valid-frontmatter
content/docs/commands/operator/metrics.mdx
1:1 error Document does not have a description key in its frontmatter. Add a description key at the top of the document. ensure-valid-frontmatter
content/docs/job-specification/hcl2/expressions.mdx
339:1-339:71 error Unexpected product-relative link: /docs/job-specification/hcl2/functions/collection/flatten. Ensure that relative links are fully-qualified Developer paths: /{productSlug}/docs/job-specification/hcl2/functions/collection/flatten ensure-valid-link-format
340:1-340:77 …
```
> docs: fix outstanding content conformance errors

- .changelog/16030.txt
- nomad/structs/structs.go
- nomad/structs/volume_test.go
- nomad/structs/volumes.go
- scheduler/generic_sched_test.go
- scheduler/scheduler_sysbatch_test.go
- scheduler/scheduler_system_test.go
- website/content/docs/job-specification/volume.mdx
- website/content/partials/envvars.mdx
This hand-backports https://github.com/hashicorp/nomad/pull/16030 to 1.3.x, because the original PR touched some code that has a minor new feature for 1.5.0 (per_alloc host volumes) and because there are some significant conflicts over the env vars page, for which the new table syntax was never backported.
---
Service jobs should have unique allocation Names, derived from the Job.ID. System jobs do not have unique allocation Names because the index is intended to indicated the instance out of a desired count size. Because system jobs do not have an explicit count but the results are based on the targeted nodes, the index is less informative and this was intentionally omitted from the original design.
Update docs to make it clear that NOMAD_ALLOC_INDEX is always zero for system/sysbatch …
> Backport #16030 System and sysbatch jobs always have zero index to 1.3.x

- .changelog/16030.txt
- nomad/structs/structs.go
- nomad/structs/volume_test.go
- nomad/structs/volumes.go
- scheduler/generic_sched_test.go
- scheduler/scheduler_sysbatch_test.go
- scheduler/scheduler_system_test.go
- website/content/docs/job-specification/volume.mdx
- website/content/partials/envvars.mdx
This hand-backports https://github.com/hashicorp/nomad/pull/16030 to 1.2.x, because the original PR touched some code that has a minor new feature for 1.5.0 (per_alloc host volumes) and because there are some significant conflicts over the env vars page, for which the new table syntax was never backported.
---
Service jobs should have unique allocation Names, derived from the Job.ID. System jobs do not have unique allocation Names because the index is intended to indicated the instance out of a desired count size. Because system jobs do not have an explicit count but the results are based on the targeted nodes, the index is less informative and this was intentionally omitted from the original design.
Update docs to make it clear that NOMAD_ALLOC_INDEX is always zero for system/sysbatch …
> Backport #16030 System and sysbatch jobs always have zero index to 1.2.x

- GNUmakefile
fixes a build failure 
```
==> Linting hclog statements...
Error: /home/runner/work/nomad/nomad/main.go:180:43: cmd.Synopsis undefined (type cli.Command has no field or method Synopsis)
hclogvet: analysis skipped due to errors in package
make: *** [GNUmakefile:155: check] Error 1
```
> build: update hclogvet

- .changelog/15864.txt
- client/allocrunner/interfaces/task_lifecycle.go
- client/allocrunner/taskrunner/api_hook.go
- client/allocrunner/taskrunner/api_hook_test.go
- client/allocrunner/taskrunner/task_runner.go
- client/allocrunner/taskrunner/task_runner_hooks.go
- client/config/config.go
- client/config/testing.go
- command/agent/agent.go
- command/agent/agent_endpoint.go
- command/agent/alloc_endpoint.go
- command/agent/consul/int_test.go
- command/agent/http.go
- command/agent/job_endpoint.go
- command/agent/metrics_endpoint.go
- command/agent/variable_endpoint.go
- e2e/workload_id/input/api-auth.nomad.hcl
- e2e/workload_id/input/api-win.nomad.hcl
- e2e/workload_id/taskapi_test.go
- helper/users/lookup.go
- helper/users/lookup_linux_test.go
- helper/users/lookup_windows_test.go
- nomad/acl_endpoint.go
- nomad/structs/structs.go
The goal of this PR is to provide universal workload access to Nomad's HTTP API via Unix Domain Sockets (UDS).
Dynamic Node Metadata #15844 is one potential use case.
Inspired by https://github.com/hashicorp/nomad/commit/e90807ec080c72025c434eb7ba7247e6adb84304
TODO
> Task API via Unix Domain Socket

- .changelog/7794.txt
- client/testutil/driver_compatible.go
- drivers/docker/fingerprint.go
- drivers/docker/fingerprint_test.go
This PR modifies the docker driver to behave like exec when being run
as a non-root user on a host machine with cgroups v2 enabled. Because
of how cpu resources are managed by the Nomad client, the nomad agent
must be run as root to manage docker-created cgroups.
Fixes #15927
> docker: disable driver when running as non-root on cgroups v2 hosts

- .changelog/16055.txt
- command/acl_token_create.go
- command/acl_token_create_test.go
- website/content/docs/commands/acl/token/create.mdx
Hi team,
This PR aims to add `-json` and `-t` flag for `nomad acl token create` command. This is related to issue #15894 
Example output:
- With `-json` flag
```
❯ nomad acl token create -type="management" -global=true \
-name="Cluster A Replication Token" \
-token="abcxyz" -ttl=10m -json
{
"AccessorID": "83a61305-15c2-c78a-1c59-75c44afa7a13",
"CreateIndex": 927,
"CreateTime": "2023-02-04T09:39:33.710007669Z",
"ExpirationTTL": 600000000000,
"ExpirationTime": "2023-02-04T09:49:33.710007669Z",
"Global": true,
"ModifyIndex": 927,
"Name": "Cluster A Replication Token",
"Policies": null,
"Roles": null,
"SecretID": "6d23da6a-677d-c7b9-02ac-f1c41ad5f5d0",
"Type": "management"
}
```
- With `-t` flag
```
❯ nomad acl token create -type="management" -global=true \
-name="Cluster A Replication Token" …
```
> Add `-json` and `-t` flag for  `nomad acl token create` command

- e2e/framework/case.go
- e2e/framework/context.go
- e2e/framework/doc.go
- e2e/framework/framework.go
- e2e/framework/interfaces.go
- e2e/framework/provisioner.go
Nothing more motivating than lots of deprecation warnings to get some code refactored.
> e2e: mark framework package as deprecated

- .changelog/16074.txt
- client/servers/manager_internal_test.go
- command/agent/testagent.go
- go.mod
- main.go
- nomad/periodic_test.go
- scheduler/spread_test.go
go1.20 deprecates rand.Seed, and seeds the rand package automatically. Remove cases where we seed the random package, and cleanup the one test case where we intentionally create a known random source.
https://pkg.go.dev/math/rand#Seed
https://go.dev/doc/go1.20
> main: remove deprecated uses of rand.Seed

- command/agent/event/event.go
- command/agent/http.go
https://github.com/hashicorp/nomad/pull/15864 changed the way in which the agent is passed to the HTTP servers by wrapping it in an interface. This removed access to the audit eventer, which is used by the HTTP server to log events for the enterprise codebase.
This change therefore explicitly passes the `event.Auditor` interface to the agent HTTP servers for use. This change will be needed along with an enterprise specific one, to slightly alter the audit calls to use the new field.
Please see the internal nightly runs to see the original error.
> agent: fix agent HTTP server audit event implementation access.

- .changelog/9053.txt
- command/data_format.go
- command/data_format_test.go
- go.mod
This PR adds the https://github.com/Masterminds/sprig function library to be available when using the -t flag to format output with a go template.
> Add sprig for command templates

- ui/app/adapters/node.js
- ui/app/components/metadata-editor.hbs
- ui/app/components/metadata-editor.js
- ui/app/components/metadata-kv.hbs
- ui/app/components/metadata-kv.js
- ui/app/controllers/clients/client/index.js
- ui/app/models/node.js
- ui/app/models/structured-attributes.js
- ui/app/styles/components.scss
- ui/app/styles/components/metadata-editor.scss
- ui/app/templates/clients/client/index.hbs
- ui/app/templates/components/attributes-section.hbs
- ui/app/templates/components/attributes-table.hbs
- ui/mirage/config.js
- ui/mirage/scenarios/default.js
- ui/tests/acceptance/client-detail-test.js
Allows for editing node metadata via the Web UI. New metadata can be added and existing metadata can be edited or removed.
Some nice things like escape press within an input are handled as you'd expect.
Requires `can write node` access levels so, if testing against vercel/mirage, please "sign in" as a manager
> [ui] Dynamic Node Metadata editing

- .release/linux/package/etc/nomad.d/nomad.hcl
- website/content/docs/commands/index.mdx
- website/content/docs/configuration/server.mdx
In #13374 we updated the commented-out `license_path` in the packaged example configuration file to match the existing documentation. Although this config value was commented-out, it was reported that changing the value was confusing. Update the commented-out line to the previous value and update the documented examples to match that. This matches most of the examples for Consul/Vault licensing as well. I've double-checked the tutorials and it looks like it'd been left on the previous value there, so no additional work to be done.
> docs: update example `license_path`

- nomad/leader.go
I didn't change the logic check on this change to just look for the main version chunk, as I didn't want to make that change so late in the day.
Requires merge just before we decide to go ahead with beta release.
The interesting thing with this PR, is that a bunch of tests will break (auth method/ bindings rules) because the current Nomad version is not high enough. I am therefore not sure if we want to do this after the release, or before.
> RPC: bump SSO feature gate version.

- client/allocrunner/taskrunner/template/template_test.go
- helper/users/lookup.go
This PR deletes the `user.LookupGroupId` function as it was only being used
in a single test case, and its value was not important to the test.
Prep for https://github.com/hashicorp/nomad/issues/16010
No CL - only affects test case
> users: eliminate LookupGroupId and its one use case

- .changelog/16085.txt
- client/acl.go
- client/acl_test.go
- client/client.go
- go.mod
- go.sum
- lib/lang/doc.go
- lib/lang/pair.go
- nomad/acl.go
- nomad/plan_apply_node_tracker.go
- nomad/plan_apply_node_tracker_test.go
- nomad/server.go
- nomad/stream/event_broker.go
- nomad/structs/acl.go
- nomad/structs/funcs.go
- nomad/structs/funcs_test.go
- nomad/structs/generate.sh
Upgrade to hashicorp/golang-lru/v2, and refactor the ACL cache to leverage all the generics. Previously each cache entry contained 3 pointers, only one of which would be in use - so we should get some space savings out of that (not that the cache sizes are large).
> deps: upgrade to hashicorp/golang-lru/v2

- command/login.go
When an auth method was not supplied and the OIDC type was given in lower case, the CLI was not matching the default method due to casing and responded with a confusing user message.
This change fixes the above problem, along with making use of the santized type easier.
> cli: fix use of the sanitized method type for the login command.

- .changelog/16100.txt
- helper/users/cache.go
- helper/users/cache_test.go
- helper/users/lookup.go
- helper/users/lookup_unix.go
This PR introduces a global cache for OS user lookups. This should
relieve pressure on the OS domain/directory lookups, which would be
queried more now that Task API exists.
Hits are cached for 1 hour, and misses are cached for 1 minute. These
values are fairly arbitrary - we can tweak them if there is any reason to.
Closes #16010
> users: create cache for user lookups

- nomad/acl_endpoint.go
Fixes https://github.com/hashicorp/nomad/issues/16098 introduced in 1.5.0-beta.1
In #15901 we introduced pre-forwarding authentication for RPCs so that we can grab the identity for rate metrics. The `ACL.Bootstrap` RPC is an unauthenticated endpoint, so any error message from authentication is not particularly useful. This would be harmless, but if you try to bootstrap with your `NOMAD_TOKEN` already set (perhaps because you were talking to another cluster previously from the same shell session), you'll get an authentication error instead of just having the token be ignored. This is a regression from the existing behavior, so have this endpoint ignore auth errors the same way we do for every other unauthenticated endpoint (ex `Status.Peers`)
> acl: never return auth errors for `ACL.Bootstrap` RPC

- .github/workflows/test-core.yaml
Sometimes GHA gets wedged, and there is no need to waste 30 minutes
on a job that usually takes < 3.
e.g. stuck loading module cache, which is out of our control
https://github.com/hashicorp/nomad/actions/runs/4135098558/jobs/7147128419
> tests: reduce timeout on test-api

- ui/app/templates/components/global-header.hbs
Running a simple `nomad agent -dev` results in an empty label because `this.system.agent.config.UI.Label` is an object shaped like this:
```
{
"BackgroundColor": "",
"Text": "",
"TextColor": ""
}
```
After the change the label is not displayed unless a text is provided:
I wasn't able to figure out how to modify the label config to write a proper test 😅
> ui: hide custom label if not text is provided

- client/allocrunner/taskrunner/getter/util_linux_test.go
- client/allocrunner/taskrunner/getter/util_test.go
Since this test tests a function that in a file controlled by a build flag, when not on Linux, the implementation is not found by the Go language server and makes IDEs sad.
> [chore] Move TestUtil_loadVersionControlGlobalConfigs into build flagged file

- .github/workflows/ember-test-audit.yml
Reduce the number of `ember-test-audit` iterations to speed up CI. With 3 iterations each run was about 40min long and we are not experiencing flaky tests so often.
> ci: reduce number of ember-test-audit iterations

- website/content/api-docs/client.mdx
- website/content/api-docs/task-api.mdx
- website/content/docs/concepts/workload-identity.mdx
- website/content/docs/job-specification/identity.mdx
- website/content/docs/job-specification/task.mdx
- website/data/api-docs-nav-data.json
Better late than never! Here is some much needed documentation for new features in the freshly released 1.5.0-beta.1 release.
A new tutorial demonstrating how to use the Task API to serve the Nomad UI would be neat, but that's a job for another PR.
I added Task API to the little section above the list of endpoints:
> Workload Identity, Task API, and Dynamic Node Metadata Docs

- .semgrep/protect_globals.yml
- nomad/core_sched.go
- nomad/core_sched_test.go
- nomad/structs/uuid.go
Some of the core scheduler tests need the maximum batch size for writes to be smaller than the usual `structs.MaxUUIDsPerWriteRequest`. But they do so by unsafely modifying the global struct, which creates test flakes in other tests.
Modify the functions under test to take a batch size parameter. Production code will pass the global while the tests can inject smaller values. Turn the `structs.MaxUUIDsPerWriteRequest` into a constant, and add a semgrep rule for avoiding this kind of thing in the future.
Discovered while trying to debug https://github.com/hashicorp/nomad/pull/16112, but this should get backported to all supported versions whereas that will be only to 1.4.x
> tests: don't mutate global structs in core scheduler tests

- .changelog/16112.txt
- nomad/eval_broker.go
- nomad/eval_broker_test.go
- nomad/leader.go
The eval broker's `Cancelable` method used by the cancelable eval reaper mutates
the slice of cancelable evals by removing a batch at a time from the slice. But
this method unsafely uses a read lock despite this mutation. Under normal
workloads this is likely to be safe but when the eval broker is under the heavy
load this feature is intended to fix, we're likely to have a race
condition. Switch this to a write lock, like the other locks that mutate the
eval broker state.
This changeset also adjusts the timeout to allow poorly-sized Actions runners
more time to schedule the appropriate goroutines. The test has also been updated
to use `shoenig/test/wait` so we can have sensible reporting of the results
rather than just a timeout error when things go wrong.
> eval broker: use write lock when reaping cancelable evals

- .changelog/16111.txt
- command/agent/agent.go
- command/agent/plugins.go
- command/agent/plugins_test.go
- nomad/config.go
- nomad/testing.go
The plugin loader loads task and device driver plugins which are not
used on server nodes.
> [core] Do not start the plugin loader on non-clients

- .changelog/16138.txt
- command/node_status.go
Hi team,
This PR aims to fix #12816. I find unused variable in func `nodeCSIVolumeNames` so I removed it as well
> Fix unbold header `Device Group Attributes` and remove unused var in  func `nodeCSIVolumeNames`

- client/fingerprint/plugins_cni.go
- client/fingerprint/plugins_cni_test.go
- client/fingerprint/test_fixtures/cni2/custom2
This PR fixes the CNI plugin fingerprinter to take into account the fact
that the `cni_path` config can be a multi-path (e.g. `/foo:/bar:/baz`).
Accumulate plugins from each of the possible path elements. If scanning
any of the named directory fails, the fingerprinter fails.
Fixes #16083
No CL/BP - has not shipped yet.
> cni: handle multi-path cni_path when fingerprinting plugins

- .changelog/15933.txt
- command/job_validate.go
- command/meta.go
- command/var_put.go
- command/var_put_test.go
- helper/warning.go
- helper/warning_test.go
- nomad/job_endpoint.go
- nomad/structs/funcs.go
- nomad/structs/funcs_test.go
- ui/app/components/variable-form.js
- ui/tests/integration/components/variable-form-test.js
- Adding warnings to put output for iffy keys
- Share warning formatting logic between API and CLI
- Fix warning header to adjust for singular and plural headers
- Remove unnecessary extra space at the end of warnings
- Apply same logic and error message to the UI
Closes https://github.com/hashicorp/nomad/issues/15853
> Add warnings to `var put` for non-alphanumeric keys. 

- .changelog/16166.txt
- api/nodes.go
Looks like a new node status was introduced with nomad 1.3.x but this isn't reflected in the API
> Fix: missing Node Status "disconnected" in API

- website/content/docs/upgrade/upgrade-specific.mdx
The panic bug for upgrades with older servers that shipped in 1.4.0 was fixed in 1.4.1, which makes the versions described in the warning in the upgrade guide misleading. Clarify the upgrade guide.
> docs: clarify upgrade note on 1.4.0 panics

- website/content/docs/drivers/docker.mdx
- website/content/docs/drivers/exec.mdx
- website/content/docs/job-specification/resources.mdx
Closes https://github.com/hashicorp/nomad/issues/13775
> docs: remove cores/memory beta label, update driver cpu docs

- .changelog/16180.txt
- client/lib/cgutil/cgutil_linux.go
This PR wraps the `cgroups.IsCgroup2UnifiedMode()` helper method from
runc in a `defer/recover` block because it might panic in some cases.
Upstream fix in: https://github.com/opencontainers/runc/pull/3745
Closes #16179
Backports as far back as 1.3.x, when support for cgv2 was added.
> cgutil: handle panic from runc helper method

- CHANGELOG.md
The actual code changes for these releases already exist in `main` and the backport branches.
> Merge release 1.4.4 changelog entries

- .changelog/16174.txt
- command/fmt.go
- command/fmt_test.go
- website/content/docs/commands/fmt.mdx
Fixes https://github.com/hashicorp/nomad/issues/16170
The `nomad fmt -check` command incorrectly writes to file because we didn't
return before writing the file on a diff. Fix this bug and update the command
internals to differentiate between the write-to-file and write-to-stdout code
paths, which are activated by different combinations of options and flags.
The docstring for the `-list` and `-write` flags is also unclear and can be
easily misread to be the opposite of the actual behavior. Clarify this and fix
up the docs to match.
This changeset also refactors the tests quite a bit so as to make the test
outputs clear when something is incorrect and avoid reusing the UI state.
> cli: `fmt -check` should return early on diff

- .changelog/16195.txt
- command/agent/agent.go
- command/agent/config.go
- command/agent/config_parse_test.go
- command/agent/testdata/basic.hcl
- command/agent/testdata/basic.json
- website/content/docs/configuration/server.mdx
The default setting is 5 minutes. If we lose an instance using an EBS volume with the CSI EBS volume plugin, it takes up to 5 minutes before the claims are GC'ed and we can get the job rescheduled. We would like to be able to configure this to be lower.
> client: add option to configure CSIVolumeClaimGCInterval

- GNUmakefile
- contributing/README.md
I wanted to run tests locally to start contributing to Nomad; So as [current documentation mentions](https://github.com/hashicorp/nomad/blob/main/contributing/README.md?plain=1#L49), I had to run `make test` to run the tests.
But after checking the [GNUMakefile](https://github.com/hashicorp/nomad/blob/main/GNUmakefile), found that it doesn't exist any more and documentation should be updated.
Also after trying to run the unit tests with `make test-nomad`, I found that it doesn't work properly as `GOTEST_GROUP` is not set in local run and it gets set in CI like [this](https://github.com/hashicorp/nomad/blob/main/.github/workflows/test-core.yaml#L110).
So this PR:
1. Fix the documentation regarding how to run the unit tests
2. Fix the Makefile so anyone can run the unit tests localy
I'm not …
> fix: correct Makefile to run unit tests locally

- nomad/rpc_test.go
The RPC TLS enforcement test was frequently failing with broken connections. The
most likely cause was that the tests started to run before the server had
started its RPC server. Wait until it self-elects to ensure that the RPC server
is up. This seems to have corrected the error; I ran this 3 times without a
failure (even accounting for `gotestsum` retries).
Also, fix a minor test bug that didn't impact the test but showed an incorrect
usage for `Status.Ping.`
> fix test flake for RPC TLS enforcement test

- command/agent/variable_endpoint.go
- nomad/variables_endpoint.go
- website/content/api-docs/task-api.mdx
- website/content/docs/concepts/workload-identity.mdx
1. Remove `TODO` that isn't going to get addressed
2. Return an error when `parse` fails
3. Rename `cap -> policy` because `cap` is a builtin, and the variables we pass in are called `SomethingPolicy`
4. Fix a misspelling
5. Mention anonymous policy doesn't work for task api
6. Remove old `Using WI` section
> Minor post-1.5-beta1 API, code, and docs cleanups

- .changelog/16181.txt
- command/var_put.go
This fixes an issue when providing a variable path to the command, but using an HCL variable specification for its items data.
```plaintext
$ nomad var put test @spec.nv.hcl
Failed to parse variable data: error unmarshaling json: invalid character '#' looking for beginning of value
```
```plaintext
$ bin/nomad var put test @spec.nv.hcl
Created variable "test" with modify index 44954
```
> [cli] var put - Add extension parsing to second argument when file

- ui/app/utils/default_jobs/hello-world.js
Adding because count is a pretty core concept for our job specs. Hoping I got the definition accurate enough.
> [ui] "count" added to hello world job template

- api/acl_test.go
- command/acl_binding_rule_create_test.go
- nomad/structs/acl.go
- nomad/structs/acl_test.go
- website/content/api-docs/acl/binding-rules.mdx
- website/content/docs/commands/acl/binding-rule/create.mdx
The selector should be validated on upsert, otherwise an expression that is invalid will cause mapping failures at login which can be confusing to the user and operator. The docs have also been updated to include a little information about this and an example of dealing with claim names that include dashes.
This update targets an unreleased feature, so doesn't require a changelong entry.
Closes #16206
> acl: add validation to binding rule selector on upsert.

- website/content/docs/schedulers.mdx
Also remove old version indicators.
Inspired by discussion arising from #16097 -- specifically that I forgot sysbatch supported `count > 1`!
Not sure we have a best practice on when to remove version spam from our docs. Removing "Since Nomad 0.9" seems safe, but is it too soon to remove the `Nomad 1.2` note?
> docs: clarify sysbatch supports count

- e2e/terraform/.gitignore
- e2e/terraform/.terraform.lock.hcl
- e2e/terraform/compute.tf
- e2e/terraform/ecs.tf
- e2e/terraform/network.tf
Add an Elastic Network Interface (ENI) to each Linux host, on a secondary subnet we have provisioned in each AZ. Revise security groups as follows:
* Split out client security groups from servers so that we can't have clients accidentally accessing serf addresses or other unexpected cross-talk.
* Add new security groups for the secondary subnet that only allows communication within the security group so we can exercise behaviors with multiple IPs.
* Drop inbound Consul/Vault access, as we're running those on HCP these days
This changeset doesn't include any Nomad configuration changes needed to take advantage of the extra network interface. I'll include those with testing for PR #16217. (And I've verified the cluster comes up normally with this change.)
> E2E: add multi-home networking to test infrastructure

- command/agent/http.go
- e2e/workload_id/input/api-auth.nomad.hcl
- e2e/workload_id/input/api-win.nomad.hcl
- e2e/workload_id/input/node-meta.nomad.hcl
- e2e/workload_id/nodemeta_test.go
Fixes based on #16218 
Peeking at the commits is best, but there they're grouped by file neatly as well:
- TaskAPI middlewhere needs to turn RPC Permission Denied errors into Forbidden status codes to ensure acl.enabled=true behavior matches acl.enabled=false behavior. The e2e test covers this (and was failing as it should in our e2e environment!)
- Removed datacenters from all of my recent e2e jobspecs because I love the new default.
- I forgot to skip the Windows node in the Dynamic Node Metadata test. Fixed that.
> Task API / Dynamic Node Metadata E2E test fixes

- .changelog/16237.txt
- api/variables.go
- api/variables_test.go
This PR
- fixes a panic in `GetItems` when looking up a variable that does not exist
- deprecates `GetItems` in favor of `GetVariableItems` which avoids returning a pointer to a `map`
- deprecates `ErrVariableNotFound` in favor of `ErrVariablePathNotFound` which is an actual `error` type
- eliminates unused constant `ErrVariableMissingItems`
- does some minor code cleanup to make linters happier
Fixes #16236
Fixes #16235
Fixes #16234
No backport - we don't tag the api module anyway
> api: fix a panic and tweak some exported types

- .changelog/16240.txt
- client/allocrunner/taskrunner/script_check_hook_test.go
- client/allocrunner/taskrunner/service_hook.go
This PR fixes a bug where the task group information was not being set
on the `serviceHook.AllocInfo` struct, which is needed later on for calculating
the `CheckID` of a nomad service check. The `CheckID` is calculated independently
from multiple callsites, and the information being passed in must be consistent,
including the group name.
The `workload.AllocInfo.Group` was not set at this callsite, due to the bug fixed in this PR.
https://github.com/hashicorp/nomad/blob/main/client/serviceregistration/nsd/nsd.go#L114
Fixes #16238
I suspect the bug was introduced as part of https://github.com/hashicorp/nomad/pull/14311
Backport only to 1.4.x (when NSD checks were introduced).
> services: ensure task group is set on service hook

- website/content/api-docs/jobs.mdx
Hi team,
This MR will fix the missing `namespace` query parameter in job doc
Closes #14197
> docs: Fix missing `namespace`  query parameter in job doc

- .changelog/16248.txt
- client/serviceregistration/checks/client.go
- client/serviceregistration/checks/client_test.go
- helper/useragent/useragent.go
This PR sets the default `User-Agent` on checks of nomad services to the common UA for Nomad stuff (e.g. `"Nomad/1.5.0-dev (+https://www.nomadproject.io/; go1.20)"`). If the user supplies a UA that one takes precedence.
> services: Set Nomad's User-Agent by default on HTTP checks for nomad services

- command/agent/agent.go
- command/agent/http.go
Fixes #16239
In my original Task API code I expected `agent.NewHTTPServers` to only be called once, but it's called on SIGHUP when TLS certificates change.
There's no reason to touch non-TLS-enabled HTTP servers in this case, so I fixed the panic by not reloading those. I hate special casing things in already messy code like Agent/NewHTTPServers, but I think this is the best option without signfiicantly refactoring HTTP server setup.
Testing is awkward, but here's what I used locally to reproduce the panic and test the fix:
> tls.hcl
```hcl
tls {
http      = true
rpc       = true
ca_file   = ".../tls/nomad-agent-ca.pem"
cert_file = ".../tls/global-server-nomad.pem"
key_file  = ".../tls/global-server-nomad-key.pem"
}
```
> generated certs with
```
$ cd .../tls
$ nomad tls cert create …
```
> agent: only reload HTTP servers that use TLS

- .changelog/16256.txt
- nomad/core_sched.go
- nomad/core_sched_test.go
- nomad/state/state_store.go
- nomad/state/state_store_test.go
The `CSIVolume` struct has references to allocations that are "denormalized"; we don't store them on the `CSIVolume` struct but hydrate them on read. Tests detecting potential state store corruptions (ref https://github.com/hashicorp/nomad/pull/16257) found two locations where we're not copying the volume before denormalizing:
* When garbage collecting CSI volume claims.
* When checking if it's safe to force-deregister the volume.
There are no known user-visible problems associated with these bugs but both have the potential of mutating volume claims outside of a FSM transaction. This changeset also cleans up state mutations in some CSI tests so as to avoid having working tests cover up potential future bugs.
> CSI: fix potential state store corruptions

- .changelog/16266.txt
- client/allocrunner/taskrunner/task_runner_hooks.go
Fixes https://github.com/hashicorp/nomad/issues/16259
The `TaskUpdateRequest` struct we send to task runner update hooks was not populating the Nomad token that we get from the task runner (which we do for the Vault token). This results in task runner hooks like the template hook overwriting the Nomad token with the zero value for the token. This causes in-place updates of a task to break templates (but not other uses that rely on identity but don't currently bother to update it, like the identity hook).
> populate Nomad token for task runner update hooks

- .changelog/16216.txt
- GNUmakefile
- command/agent/agent.go
- nomad/config.go
- nomad/server_setup.go
- version/version.go
- website/content/docs/commands/version.mdx
Populate a new `BuildDate` value based on the latest commit at build time.
Using commit time instead of a simple `$(date)` to be consistent across multiple builds, as done in Consul and Vault.
`BuildDate` will be used in Enterprise to compare to license expiration time, but here in OSS it only changes the output of `nomad version`. I could be convinced to revert that if we don't want to futz with it here, but I can imagine cases where it would be nice for folks to have available.
Relates to: hashicorp/nomad-enterprise#855
> build/cli: Add BuildDate

- .changelog/16217.txt
- client/client.go
Fixes https://github.com/hashicorp/nomad/issues/16211
Nomad servers can advertise independent IP addresses for `serf` and `rpc`. Somewhat unexpectedly, the `serf` address is also used for both Serf and server-to-server RPC communication (including Raft RPC). The address advertised for `rpc` is only used for client-to-server RPC. This split was introduced intentionally in Nomad 0.8.
When clients are using Consul discovery for connecting to servers, they get an initial discovery set from Consul and use the correct `rpc` tag in Consul to get a list of adddresses for servers. The client then makes a `Status.Peers` RPC to get the list of those servers that are raft peers. But this endpoint is shared between servers and clients, and provides the address used for Raft.
Most of the time this is …
> client: use RPC address and not serf after initial Consul discovery

- ci/skip_non_root.go
- client/allocrunner/taskrunner/artifact_hook_test.go
- client/allocrunner/taskrunner/task_runner_test.go
- drivers/exec/driver_unix_test.go
[After a short discussion](https://github.com/hashicorp/nomad/pull/16137#pullrequestreview-1301517321) with @tgross, I learned that some of the tests will fail if we run them locally and without root access.
This PR will add a functionality to skip tests if the tests:
- Are **not** running in CI environment (they are running locally)
- and if they are **not** running with Root access
Also it will log that the test is skipped, so if user wants to run them, she/he has to run it with root access.
In the current behavior, They are failing by saying something like: `operation not permitted`. 
**Note:** I used `make test | grep -C 5 "operation not permitted"` to find which tests require Root access, But it may not contain all of the tests which require root access.
Please let me know if …
> Skip tests running locally without root access  

- go.mod
- go.sum
Fixes #16288. An earlier version of `go-plugin` introduced a warning log if `SecureConfig` is unset. For Nomad and other applications that have "internal" `go-plugin` consumers where the application runs itself as a plugin, this causes spurious warn-level logs. For Nomad in particular this means every task driver and logmon invocation emits the log, which is our primary operation.
The change was reverted upstream, so this changeset picks up the reverted version.
> deps: update go-plugin to 1.4.9

- .changelog/16287.txt
- api/jobs_test.go
- api/nodes_test.go
- nomad/acl_endpoint.go
- nomad/csi_endpoint.go
- nomad/drainer_shims.go
- nomad/job_endpoint.go
- nomad/job_endpoint_test.go
- nomad/keyring_endpoint.go
- nomad/namespace_endpoint.go
- nomad/operator_endpoint.go
- nomad/periodic.go
- nomad/rpc.go
- nomad/service_registration_endpoint.go
The signature of the `raftApply` function requires that the caller unwrap the first returned value (the response from `FSM.Apply`) to see if it's an error. This puts the burden on the caller to remember to check two different places for errors, and we've done so inconsistently.
Update `raftApply` to do the unwrapping for us and return any `FSM.Apply` error as the error value. Similar work was done in Consul in https://github.com/hashicorp/consul/pull/9991. This eliminates some boilerplate and surfaces a few minor bugs in the process:
* job deregistrations of already-GC'd jobs were still emitting evals
* reconcile job summaries does not return scheduler errors
* node updates did not report errors associated with inconsistent service discovery or CSI plugin states
Note that although _most_ …
> handle `FSM.Apply` errors in `raftApply`

- .changelog/16099.txt
- ui/app/components/job-page/parts/title.js
- ui/app/components/policy-editor.js
- ui/app/components/variable-form.js
- ui/app/controllers/application.js
- ui/app/controllers/clients/client/index.js
- ui/app/controllers/jobs/run/templates/manage.js
- ui/app/controllers/jobs/run/templates/new.js
- ui/app/controllers/jobs/run/templates/template.js
- ui/app/controllers/policies/policy.js
- ui/app/controllers/variables/variable/index.js
- ui/app/routes/allocations/allocation.js
- ui/app/routes/jobs/run/index.js
- ui/app/services/notifications.js
- ui/app/services/token.js
- ui/app/styles/core/notifications.scss
- ui/app/templates/application.hbs
- ui/tests/acceptance/allocation-detail-test.js
- ui/tests/acceptance/job-run-test.js
- ui/tests/acceptance/policies-test.js
- ui/tests/acceptance/token-test.js
- ui/tests/acceptance/variables-test.js
Adds toast component styles from Helios to the Nomad Web UI
Resolves #16095
> [ui, helios] Toast Component

- .changelog/16221.txt
- command/operator_raft_list.go
Hi team,
This PR presents a small fix to sort the Node value in `nomad operator raft list-peers` command.
It will resolve #13711
> Fix unsorted Node value in `nomad operator raft list-peers` command

- website/content/api-docs/task-api.mdx
- website/content/docs/concepts/workload-identity.mdx
According to [envvars.mdx](https://github.com/hashicorp/nomad/blob/f89910d4650c47006838a7b6de17cbacdc62fe1c/website/content/partials/envvars.mdx), I don't think there is a `SECRETS_DIR` environment variable here, it should be `NOMAD_SECRETS_DIR`.
> docs: fix typos in task-api.mdx and workload-identity.mdx

- api/agent.go
- api/agent_test.go
- api/nodes.go
Hi team,
This MR aims to add the test case for force-leave on exsisting node
It will solve issue #15559
> Add new test case for force-leave

- .changelog/16316.txt
- nomad/service_registration_endpoint.go
- nomad/service_registration_endpoint_test.go
Fixes https://github.com/hashicorp/nomad/issues/16276
When native service discovery was added, we used the node secret as the auth token. Once Workload Identity was added in Nomad 1.4.x we needed to use the claim token for `template` blocks, and so we allowed valid claims to bypass the ACL policy check to preserve the existing behavior. (Invalid claims are still rejected, so this didn't widen any security boundary.)
In reworking authentication for 1.5.0, we unintentionally removed this bypass. For WIs without a policy attached to their job, everything works as expected because the resulting `acl.ACL` is nil. But once a policy is attached to the job the `acl.ACL` is no longer nil and this causes permissions errors.
Fix the regression by adding back the bypass for valid claims. In future …
> service: fix regression in task access to list/read endpoint

- .changelog/16306.txt
- command/job_allocs.go
- command/job_allocs_test.go
- command/job_deployments.go
- command/job_deployments_test.go
- command/job_dispatch.go
- command/job_dispatch_test.go
- command/job_eval.go
- command/job_history.go
- command/job_history_test.go
- command/job_inspect.go
- command/job_inspect_test.go
- command/job_periodic_force.go
- command/job_periodic_force_test.go
- command/job_promote.go
- command/job_promote_test.go
- command/job_revert.go
- command/job_revert_test.go
- command/job_scale.go
- command/job_scaling_events.go
- command/job_status.go
- command/job_stop.go
- command/job_stop_test.go
- command/meta.go
- command/meta_test.go
Several `nomad job` subcommands had duplicate or slightly similar logic for resolving a job ID from a CLI argument prefix, while others did not have this functionality at all.
This commit pulls the shared logic to the command Meta and updates all `nomad job` subcommands to use it.
> cli: use shared logic for resolving job prefix

- command/alloc_stop.go
- website/content/api-docs/allocations.mdx
Document and remove the tab from CLI help output.
> docs: fix alloc stop `no_shutdown_delay`

- .changelog/16305.txt
- nomad/job_endpoint.go
- nomad/job_endpoint_test.go
- nomad/leader.go
- nomad/periodic.go
In Nomad 0.12.1 we introduced atomic job registration/deregistration, where the new eval was written in the same raft entry. Backwards-compatibility checks were supposed to have been removed in Nomad 1.1.0, but we missed that. This is long safe to remove.
> remove backcompat support for non-atomic job registration

- .changelog/16319.txt
- api/allocations.go
- api/allocations_test.go
Some of the methods in `Allocations()` incorrectly use the `putQuery` in API calls where `put` is more appropriate since they are not reading information back. These methods are also not returning request metadata such as `LastIndex` back to callers, which can be useful to have in some scenarios.
They also provide poor developer experience as they take an `*api.Allocation` struct when only the allocation ID is necessary. This can lead consumers to make unnecessary API calls to fetch the full allocation.
Fixing these problems require updating the methods' signatures so they take `*WriteOptions` instead of `*QueryOptions` and return `*WriteMeta`, but this is a breaking change that requires advanced notice to consumers.
This commit adds a future breaking change notice and also fixes the …
> api: set last index and request time on alloc stop

- .changelog/16281.txt
- client/allocrunner/taskrunner/task_runner.go
- client/allocrunner/taskrunner/task_runner_test.go
- nomad/structs/structs.go
https://github.com/hashicorp/nomad/pull/14775 introduced a new task event when the task runner is waiting for the `shutdown_delay`, but some requests can be configured to [ignore the `shutdown_delay`](https://developer.hashicorp.com/nomad/docs/commands/alloc/stop#no-shutdown-delay), in which case it can confusing to have this event, so emit one that notes the delay is being skipped instead.
~No changelog or backports necessary since #14775 has not being released yet.~
I just realized that I should've merged this for 1.5.0 🤦 
Not big deal, but I added a changelog entry now.
> client: don't emit task shutdown delay event if not waiting

- api/go.mod
- api/go.sum
- go.mod
- go.sum
https://github.com/shoenig/test/releases/tag/v0.6.2
> deps: update test to 0.6.2 for new functions

- .changelog/16362.txt
- nomad/node_endpoint.go
- nomad/structs/structs.go
- scheduler/util.go
- scheduler/util_test.go
Wildcard datacenters introduced a bug where a system job with any wildcard datacenters will always be treated as a destructive update when we check whether a datacenter has been removed from the jobspec.
Includes updating the helper so that callers don't have to loop over the job's datacenters.
> scheduler: correctly detect inplace update with wildcard datacenters

- website/content/docs/concepts/filesystem.mdx
- website/content/docs/job-specification/template.mdx
- website/content/docs/runtime/environment.mdx
Fixes https://github.com/hashicorp/nomad/issues/16308
> docs: note that secrets dir is usually mounted `noexec`

- .changelog/16357.txt
- command/acl_binding_rule_info.go
- command/acl_binding_rule_info_test.go
> cli: support `json` and `t` on `acl binding-rule info` command.

- website/content/docs/upgrade/upgrade-specific.mdx
> docs: add 1.5.0, 1.4.5, and 1.3.10 pause regression upgrade note.

- .changelog/16352.txt
- drivers/docker/driver.go
- drivers/docker/network.go
- drivers/docker/reconcile_dangling.go
- drivers/docker/reconcile_dangling_test.go
- drivers/docker/state.go
This PR adds tracking of pause containers to the docker driver, fixing a bug introduced by https://github.com/hashicorp/nomad/pull/15898 where the containers are now subject to dangling container reconciliation. The pause container created for allocs with docker tasks making use of bridge networking is not created in the same flow as a normal Task - which have a `TaskHandle` state. The set of tasks _not_ to reconcile was identified by scanning the set of these states, which does not include pause containers. 
To remedy this, this PR now tracks pause containers in their own little store. Since the Nomad Client may be restarted, we scan existing running containers on startup to reload the store from existing running containers. 
Fixes: https://github.com/hashicorp/nomad/issues/16338
> docker: fix bug where network pause containers would be erroneously reconciled 

- e2e/terraform/provision-nomad/install-linux.tf
This PR updates the provisioning step where we create /opt/nomad/data,
such that it is with 0700 permissions in line with our security guidance.
Should be followed up shortly by https://github.com/hashicorp/nomad/pull/16375 which fixes Nomad Client to work with this directory structure.
> e2e: fix permissions on nomad data directory

- e2e/terraform/etc/nomad.d/nomad-client.service
- e2e/terraform/etc/nomad.d/nomad-server.service
- e2e/terraform/provision-nomad/install-linux.tf
This PR configures
- server nodes with a systemd unit running the agent as the nomad service user
- client nodes with a root owned nomad data directory
> e2e: setup nomad permissions correctly (client vs. server)

- .changelog/16401.txt
- nomad/structs/bitmap.go
- nomad/structs/network.go
- nomad/structs/network_test.go
- scheduler/generic_sched_test.go
- scheduler/rank.go
Fixes #9506 #14850 (and several internally-tracked issues)
When the scheduler tries to find a placement for a new allocation, it iterates over a subset of nodes. For each node, we populate a `NetworkIndex` bitmap with the ports of all existing allocations and any other allocations already proposed as part of this same evaluation via its `SetAllocs` method. Then we make an "ask" of the `NetworkIndex` in `AssignPorts` for any ports we need and receive an "offer" in return. The offer will include both static ports and any dynamic port assignments.
The `AssignPorts` method was written to support group networks, and it shares code that selects dynamic ports with the original `AssignTaskNetwork` code. `AssignTaskNetwork` can request multiple ports from the bitmap at a time. But `AssignPorts` …
> scheduling: prevent self-collision in dynamic port network offerings

- .changelog/16402.txt
- client/allochealth/tracker.go
- client/allochealth/tracker_test.go
- client/allocrunner/alloc_runner_hooks.go
- client/allocrunner/health_hook.go
- client/allocrunner/health_hook_test.go
- client/taskenv/services.go
- nomad/mock/alloc.go
Services must be canonicalized and have its values interpolated before comparing with the values returned by Consul.
Close #16382
Close #16307
> allocrunner: fix health check monitoring for Consul services

- e2e/isolation/chroot_test.go
- e2e/isolation/input/chroot_dl_exec.nomad
- e2e/isolation/input/chroot_docker.nomad
- e2e/isolation/input/chroot_exec.nomad
- e2e/namespaces/namespaces_test.go
- e2e/operator_scheduler/input/basic.nomad
See individual commits for details but basically:
Failed last night, but I couldn't find a cause. Its allocs were stuck in pending along with a lot of other unexpected failures, so I suspect something went wrong with the client setup last night? Unsure.
Gave its jobs more resources and datacenters, but I doubt that will fix whatever happened last night.
Expected output changed in #16306. I fixed the test to match the new CLI output.
Test expects to find it running, but the job only sleeps for 1s. Lengthened the time to be safe (does *not* lengthen the overall test time). However I suspect this hit the "bad client" issue like chroot and all the others last night.
> e2e fixes: cli output, timing issue, and some cleanups

- go.mod
Which we no longer need since we no longer have consul as a dependency (the thing that also imported go-discover with it's own desired version). 
backport only to 1.5.x and 1.4.x (first without Consul dependency)
> deps: remove replace statement for go-discover

- nomad/mock/job.go
- scheduler/util_test.go
In preperation for some refactoring to `tasksUpdated`, add a benchmark to the
old code so it's easy to compare with the changes, making sure nothing goes
off the rails for performance.
inaugural run:
```
➜ go test -count=3 -bench=BenchmarkTasksUpdated -run BenchmarkTasksUpdated
BenchmarkTasksUpdated-24           91621             15052 ns/op
BenchmarkTasksUpdated-24           80002             15023 ns/op
BenchmarkTasksUpdated-24           78248             15514 ns/op
```
> scheduler: add simple benchmark for tasksUpdated

- nomad/structs/structs.go
- scheduler/system_util.go
- scheduler/system_util_test.go
The tests for the system allocs reconciling code path (`diffSystemAllocs`) include many impossible test environments, such as passing allocs for the wrong node into the function. This makes the test assertions nonsensible for use in walking yourself through the correct behavior.
I've pulled this changeset out of PR #16097 so that we can merge these improvements and revisit the right approach to fix the problem in #16097 with less urgency now that the PFNR bug fix has been merged. This changeset breaks up a couple of tests, expands test coverage, and makes test assertions more clear. It also corrects one bit of production code that behaves fine in production because of canonicalization, but forces us to remember to set values in tests to compensate.
> scheduler: refactor system util tests

- website/content/docs/commands/fmt.mdx
Hi team,
This PR updates the `nomad fmt` doc for further clarification on non-deprecated HCL2 syntax
Will close #16312 and #15072
> doc: Update `nomad fmt` doc to run against non-deprecated HCL2 jobspec only

- .changelog/16463.txt
- command/job_eval.go
- command/job_eval_test.go
- nomad/job_endpoint.go
- nomad/job_endpoint_test.go
- website/content/api-docs/jobs.mdx
- website/content/docs/commands/job/eval.mdx
- website/content/docs/upgrade/upgrade-specific.mdx
The job evaluate endpoint creates a new evaluation for the job which is a write operation. This change modifies the necessary capability from `read-job` to `submit-job` to better reflect this.
No backport since this is targeted for Nomad 1.6.0
> acl: update job eval requirement to `submit-job`

- .changelog/16467.txt
- client/lib/cgutil/cpuset_manager_v1.go
This PR fixes a bug where restarting a Nomad Client on a machine using cgroups
v1 (e.g. Ubuntu 20.04 or earlier) would cause the cpuset cgroups manager to disable itself.
This is being caused by incorrectly interpreting a "file exists" error as
problematic when ensuring the reserved cpuset exists. If we get a "file exists"
error, that just means there is nothing to do, and the cpuset manager should continue
initializing normally.
Note that a machine reboot would fix the issue - the interfaces are ephemeral.
Fixes https://github.com/hashicorp/nomad/issues/16291
> cgv1: do not disable cpuset manager if reserved interface already exists

- .changelog/16469.txt
- command/agent/http.go
- command/agent/http_test.go
Fixes https://github.com/hashicorp/nomad/issues/11898 and will replace https://github.com/hashicorp/nomad/pull/11897
Our auth token parsing code trims space around the `Authorization` header but not around `X-Nomad-Token`. When using the UI, it's easy to accidentally introduce a leading or trailing space, which results in spurious authentication errors. Some browsers fix this automatically, but apparently not all do. Trim the space at the HTTP server.
> agent: trim space when parsing X-Nomad-Token header

- ui/app/components/job-editor.js
- ui/app/routes/jobs/job/definition.js
- ui/app/templates/components/job-editor/read.hbs
Older jobs do not have a `Specification` field. Therefore, we'll need to conditionally render the toggle button.
> ui:  conditionally render toggle in `jobs.job.definition`

- ui/app/components/job-editor.js
- ui/app/routes/jobs/job/definition.js
- ui/app/templates/components/job-editor/read.hbs
- ui/mirage/scenarios/default.js
This PR updates the `default` Mirage scenario to include a `Job` that has the new `Specification` field required to display HCL in the UI. Note:  Older jobs will not have this field.
> update `default` Mirage scenario

- ui/app/components/job-status/panel.hbs
- ui/app/components/job-status/panel.js
- ui/app/controllers/jobs/job/index.js
- ui/app/templates/components/job-page/service.hbs
- ui/app/templates/jobs/job/index.hbs
- ui/tests/acceptance/job-status-panel-test.js
- ui/tests/helpers/module-for-job.js
- ui/tests/integration/components/job-page/service-test.js
Resolves #16340 
Passes `statusMode` down to the job status panel; changes behaviour to be at job index level.
> [ui, job status] Make panel status mode a queryParam

- GNUmakefile
Previous to this change, Juanita and I were getting the following error when trying to run `make test-nomad`:
```
FAIL: usage: [filename] <group>
exit status 1
FAIL: usage: [filename] <group>
exit status 1
FAIL: usage: [filename] <group>
exit status 1
==> Running Nomad unit tests nomad client command drivers quick
==> with packages
gotestsum --format=testname --rerun-fails=3 --packages="" -- \
-cover \
-timeout=20m \
-count=1 \
-tags "ui " \
ERROR when go test args are used with --rerun-fails-max-attempts the list of packages to test must be specified by the --packages flag
make: *** [test-nomad] Error 3
```
Related: https://github.com/hashicorp/nomad/pull/16137
> build: fix `test-nomad` make target when running locally.

- website/content/api-docs/jobs.mdx
- website/content/docs/job-specification/dispatch_payload.mdx
* dispatch_payload - Docs said "Examples" when there was only 1 example. Not sure what the floating "to" in the description was for.
* jobs api docs just had an extra `#` for one heading
> docs: dispatch_payload and jobs api docs had some weirdness

- .changelog/16495.txt
- client/allocrunner/taskrunner/getter/util_linux.go
- client/allocrunner/taskrunner/getter/util_linux_test.go
- client/allocrunner/taskrunner/getter/util_test.go
- go.mod
This PR fixes artifact downloading so that git may work when cloning from
private repositories. It needs
- file read on `/etc/passwd`
- dir read on `/root/.ssh`
- file write on `/root/.ssh/known_hosts`
Add these rules to the landlock rules for the artifact sandbox.
Fixes https://github.com/hashicorp/nomad/issues/16477
> artifact: git needs more files for private repositories

- e2e/terraform/etc/nomad.d/base.hcl
- e2e/terraform/etc/nomad.d/server-linux.hcl
- website/content/docs/configuration/acl.mdx
I also updated the docs to hopefully make it more clear that ACLs should be uniformly enabled or disabled on all nodes. I wouldn't mind making it bold or a note or something because I really don't want to give the impression we support a mixed-auth world. Hopefully in the near future it will be an auth-only world and this easy-get-wrong config will go away!
> Enable ACLs on E2E test clients

- .changelog/16289.txt
- client/allocrunner/group_service_hook.go
- client/allocrunner/group_service_hook_test.go
- client/serviceregistration/nsd/nsd.go
This PR fixes a bug where the group service hook's deregister flag was not set in `Postrun()`, causing the hook to attempt deregistrations twice during job updates (alloc replacement), where `PreKill()` would also do a deregistration. With the Nomad service provider, this shows up as Error logs on every job update.
First commit is the bug fix, second is drive by test cleanup.
> nsd: always set deregister flag after deregistration of group

- .changelog/16504.txt
- command/login.go
- command/login_test.go
- website/content/docs/commands/login.mdx
`nomad login` command does not need to know ACL Auth Method's type, since all method names are unique. I discovered this while fixing a bug in which `login` ignored the existence of default auth method and errored when users didn't provide a method name or type. I believe this bug comes from the fact that originally we intended to have default-per-type design, and later we decided it's better UX to have global-default auth methods. 
Closes #16501.
> cli: nomad login command should not require a -type flag and should respect default auth method

- nomad/rpc_test.go
- nomad/testing.go
- testutil/wait.go
- tests: add WaitForLeaders helpers using must/wait timings
- tests: start servers for mtls tests together
Fixes: #16253 ... :crossed_fingers:
> tls enforcement flaky tests

- .changelog/16378.txt
- ui/app/components/job-page/parts/title.js
- ui/app/controllers/jobs/index.js
- ui/app/services/keyboard.js
- ui/app/templates/clients/client/index.hbs
- ui/app/templates/components/exec/open-button.hbs
- ui/app/templates/components/job-page/parts/title.hbs
- ui/app/templates/jobs/index.hbs
Traversal has been a strong-suit of keyboard navigation for long enough that I feel confident in its behaviour in the Nomad UI.
Now, this PR adds some basic action-running for jobs.
From the jobs index:
- run a new job with `r u n`
From a job page:
- exec with `e x e c`
- stop with `s t o p`
- purge with `p u r g e`
- start with `s t a r t`
> [ui] Perform common job tasks with keyboard shortcuts

- ui/app/components/job-editor.js
- ui/app/controllers/jobs/job/definition.js
- ui/app/routes/jobs/job/definition.js
- ui/app/styles/components/codemirror.scss
- ui/app/templates/components/job-editor.hbs
- ui/app/templates/components/job-editor/edit.hbs
- ui/app/templates/components/job-editor/read.hbs
- ui/app/templates/components/job-editor/review.hbs
- ui/app/templates/jobs/job/definition.hbs
- ui/mirage/scenarios/default.js
- ui/tests/acceptance/job-definition-test.js
- ui/tests/integration/components/job-editor-test.js
Closes #16269 for creating a Toggle Button to display both the Job Specification and Full Definition.
**Functional Changes**
This PR adds a toggle button when the `JobEditor` component is in a read-only state. 
**Refactoring**
This PR refactors the JobEditor component to improve its flexibility and maintainability. The original code tightly coupled the component's state with its rendering logic, which made it difficult to modify and extend. This PR introduces several improvements to make the code more modular and easier to understand.
**Changes**
- Uses Ember's `component helper` to dynamically render the appropriate child component based on the value of the stage property.
- Reorganizes the code to separate the component state from the rendering logic, which makes the component more …
> ui:  Toggle for `read-only` view

- ui/mirage/scenarios/default.js
This PR adds a variable table so the Vercel deployment displays a variables table.
> chore: add mirage fixture

- contributing/mock-driver.md
We don't have any handy documentation for the `mock_driver` that we use for internal testing. This isn't exposed to end users so it doesn't belong in the real documentation, but it can live in the contributing guide.
> contrib: developer docs for `mock_driver`

- .changelog/16549.txt
- api/allocations.go
- api/api.go
- api/node_meta.go
- command/agent/meta_endpoint.go
- contributing/checklist-rpc-endpoint.md
- go.mod
- go.sum
- nomad/client_meta_endpoint.go
- nomad/client_meta_endpoint_test.go
- nomad/structs/node.go
- nomad/testing.go
- testutil/wait.go
Fixes #16517
Given a 3 Server cluster with at least 1 Client connected to Follower 1:
If a NodeMeta.{Apply,Read} for the Client request is received by Follower 1 with `AllowStale = false` the Follower will forward the request to the Leader.
The Leader, not being connected to the target Client, will forward the RPC to Follower 1.
Follower 1, seeing AllowStale=false, will forward the request to the Leader.
The Leader, not being connected to... well hoppefully you get the picture: an infinite loop occurs.
Manually testing looks good, but ~~automated testing is still WIP.~~
_Update:_ I'm pretty pleased with how the manual test turned out! It's pretty big but *reliably* exercises the bug without the patch. With the fix the test runs in <400ms locally which isn't bad for running *7 agents* and …
> client/metadata: fix crasher caused by AllowStale = false

- .changelog/16427.txt
The security fix in Go 1.20.2 does not apply to Nomad.
> changelog: update #16427 to improvement

- contributing/architecture-drainer.md
The drainer component is fairly complex. As part of upcoming work to fix some of the drainer's rough edges, document the drainer's architecture from a Nomad developer perspective.
[Preview link for the diagrams](https://github.com/hashicorp/nomad/blob/drain-legibility-arch-docs/contributing/architecture-drainer.md)
> contrib: architecture guide to the drainer

- e2e/ui/input/proxy.nomad
- e2e/workload_id/taskapi_test.go
2 commits:
1. Skip Task API test if no new Windows boxes are available (awkward check, see #16591 for how to improve)
2. Don't try to run the proxy on Windows (it nicely reschedules and works, but takes a while)
> Windows fixes for e2e tests

- e2e/events/events.go
- e2e/events/input/deploy.nomad
- e2e/events/input/initial.nomad
In #12916 we updated the events test as part of a larger set of changes around mapstructure serialization fixes. But the changes to the jobs we're deploying in the tests had invalid task configs so they never result in good deployments and the test will always fail. Make the before/after jobs identical (except for the version bump) and make them valid. Also wait for allocations for the 2nd job run to appear before checking the deployment list, so that we don't race with the scheduler.
> E2E: fix events tests

- command/agent/http.go
Matches the "normal" HTTP error detection logic in the same file.
Tested by `TestTaskAPI/testTaskAPI_Auth` (which is currently failing in the nightly run, but passes against this patch).
> taskapi: use HasSuffix to detect errors from rpcs

- .changelog/16548.txt
- ui/app/components/copy-button.js
- ui/app/components/metadata-kv.hbs
- ui/app/styles/components/copy-button.scss
- ui/app/styles/core/buttons.scss
- ui/app/templates/clients/client/index.hbs
- ui/app/templates/components/attributes-section.hbs
- ui/app/templates/components/attributes-table.hbs
- ui/app/templates/components/copy-button.hbs
- ui/app/templates/servers/server/index.hbs
Resolves #16539 
Adds Copy buttons to server and client attribute values:
In order to get this working within the confines of a (potentially overflow:hidden) table row, added the `@inset` argument, which will modify the background to be transparent, the dom placement to be inline, and to not show a "Copied!" message and defer instead to just the checkmark icon.
> [ui] Copyable server and client attribute values

- .release/ci.hcl
We used to get a notification whenever artifacts were ready for promotion, but after https://github.com/hashicorp/nomad/pull/15600 the message was not sent anymore because the previous [`verify` step that sent the notification](https://github.com/hashicorp/nomad/blob/949a6f60c729f4a9942cfca9598bea0257331ab6/.release/ci.hcl#L148-L160) is now part of `prepare`.
> ci: send notification when prepare is complete

- ui/app/components/job-status/deployment-history.hbs
- ui/app/components/job-status/deployment-history.js
- ui/app/styles/components/job-status-panel.scss
- ui/mirage/factories/allocation.js
- ui/mirage/factories/task-event.js
- ui/tests/acceptance/allocation-detail-test.js
- ui/tests/acceptance/job-status-panel-test.js
- ui/tests/acceptance/task-detail-test.js
- ui/tests/integration/components/job-page/service-test.js
- ui/tests/integration/components/job-status-panel-test.js
- Adds a "loading shimmer" and rolling slide-in for events:
- Adds a searchbox:
Search term persists as a deployment rolls forward; which is to say, if you search a term when there are no events that match it, but a placed allocation matches it later, it will show up with no further user action needed.
> [ui] Deployment History search

- .changelog/16609.txt
- scheduler/reconcile.go
- scheduler/reconcile_test.go
- scheduler/reconcile_util.go
When a disconnect client reconnects the `allocReconciler` must find the
allocations that were created to replace the original disconnected
allocations.
This process was being done in only a subset of non-terminal untainted
allocations, meaning that, if the replacement allocations were not in
this state the reconciler didn't stop them, leaving the job in an
inconsistent state.
This inconsistency is only solved in a future job evaluation, but at
that point the allocation is considered reconnected and so the specific
reconnection logic was not applied, leading to unexpected outcomes.
This commit fixes the problem by running reconnecting allocation
reconciliation logic earlier into the process, leaving the rest of the
reconciler oblivious of reconnecting allocations.
It also uses the full set …
> scheduler: fix reconciliation of reconnecting allocs

- .changelog/16583.txt
- nomad/leader.go
- nomad/leader_test.go
- nomad/periodic.go
This PR addresses the bug reported on [#11052](https://github.com/hashicorp/nomad/issues/11052) 
When a leader change happens, the periodic dispatcher on the new leader starts by re running all periodic jobs by force, without checking if there is an instance of the said job already. 
A new check is introduced that skips the job if prohibit_overlap is set and there is already a instance running.
> Multiple instances of a periodic job are run simultaneously, when prohibit_overlap is true

- ui/app/adapters/job.js
- ui/app/models/job.js
- ui/tests/unit/models/job-test.js
Resolves #16589. This PR updates the `parse` adapter and model methods to enable passing `HCL Variables` to the `/parse` endpoint and also creates a new private property on the `Job` model to store `HCL Variables`.
Note:  We do not know the request schema for the `/parse` endpoint. We have not addressed how we'll handle complex data types like tuples, maps and etcetera when sending this request. That will be resolved in a later PR when its time to integrate the API.
> ui:  update `parse` method on `Job` model to accept variables

- ui/app/utils/has-variable-declarations.js
- ui/tests/unit/utils/has-variable-declarations-test.js
This PR kicks off the refactoring work required for #16666.
This PR specifically creates a utility function that will parse a string representation of a  job specification file that has a `variable` declaration or reference.
> ui:  validate job specification file for variables

- ui/app/templates/components/job-editor/read.hbs
- ui/tests/acceptance/job-definition-test.js
This PR is part of #16666 and is specifically responsible for removing the Variables table.
The following PR will include the information label based on the regular expression to detect variables.
> ui:  remove `variables` table from `read-only` view

- ui/app/adapters/job.js
- ui/app/models/job.js
- ui/tests/unit/models/job-test.js
This PR is part of a larger block of work for #16589 to refactor the `Job` model to enable parsing HCL specifications that include variables.
> test: update test coverage for `parse` model method

- website/content/docs/configuration/client.mdx
Fixes https://github.com/hashicorp/nomad/issues/16656
The configuration docs for `client.template.vault_retry`, `consul_retry`, and `nomad_retry` incorrectly document the default number of attempts to be unlimited (0). When we added these config blocks, we defaulted the fields to `nil` for backwards compatibility, which causes them to fall back to the default consul-template configuration values.
> docs: fix template retry attempts default documentation

- .changelog/16583.txt
- nomad/leader.go
- nomad/leader_test.go
* Multiple instances of a periodic job are run simultaneously, when prohibit_overlap is true
Fixes #11052
When restoring periodic dispatcher, all periodic jobs are forced without checking for previous childre.
* Multiple instances of a periodic job are run simultaneously, when prohibit_overlap is true
Fixes #11052
When restoring periodic dispatcher, all periodic jobs are forced without checking for previous children.
* style: refactor force run function
* fix: remove defer and inline unlock for speed optimization
* Update nomad/leader.go
Co-authored-by: James Rasell <jrasell@users.noreply.github.com>
* Update nomad/leader_test.go
Co-authored-by: James Rasell <jrasell@users.noreply.github.com>
* Update nomad/leader_test.go
Co-authored-by: James Rasell <jrasell@users.noreply.github.com>
* …
> Backport of Multiple instances of a periodic job are run simultaneously, when prohibit_overlap is true into release/1.5.x 

- .changelog/16672.txt
- api/go.mod
- api/go.sum
- client/fingerprint/cpu.go
- client/fingerprint/cpu_darwin_test.go
- client/fingerprint/cpu_default.go
- client/fingerprint/cpu_default_test.go
- client/fingerprint/cpu_linux.go
- client/stats/cpu.go
- drivers/docker/util/stats_posix.go
- drivers/docker/util/stats_windows.go
- go.mod
- go.sum
- helper/stats/cpu.go
- helper/stats/cpu_darwin_test.go
This PR adds detection of asymetric core types (Power (P) & Efficiency (E))
when running on M1/M2 Apple Silicon CPUs. This functionality is provided
by [`shoenig/go-m1cpu`](https://github.com/shoenig/go-m1cpu) which makes use of the Apple IOKit framework to read
undocumented registers containing CPU performance data. Currently working
on getting that functionality [merged upstream](https://github.com/shirou/gopsutil/pull/1436) into `gopsutil`, but `gopsutil`
would still not support detecting P vs E cores like this PR does.
Also refactors the `CPUFingerprinter` code to handle the mixed core
types, now setting power vs efficiency cpu attributes.
For now the scheduler is still unaware of mixed core types - on Apple
platforms tasks cannot reserve cores anyway so it doesn't matter, but
at …
> client/fingerprint: correctly fingerprint E/P cores of Apple Silicon chips

- website/content/docs/drivers/docker.mdx
Closes https://github.com/hashicorp/nomad/issues/16692
The `docker` driver cannot expand capabilities beyond the default set when the task is a non-root user. Clarify this in the documentation of `allow_caps` and update the `cap_add` and `cap_drop` to match the `exec` driver, which has more clear language overall.
> docs: clarify capabilities options for `docker` driver

- ui/app/controllers/settings/tokens.js
- ui/app/models/auth-method.js
- ui/app/styles/components/authorization.scss
- ui/app/templates/settings/tokens.hbs
- ui/jsconfig.json
- ui/tests/acceptance/token-test.js
In #16625 , we allow a user to sign in using a JWT. However, this only looks for the first `authMethod` of type JWT and assumes that's good enough.
This PR allows the user to have multiple JWTs and select from among them upon token input.
The select dropdown does not appear until the secret provided is "JWT-shaped", at which point it will give options if more than one JWT auth method exists.
- updated our jsconfig to let us do more type-safety and module interpretative type work. Your editor should give you good type hinting for any authMethods, etc. in this file and others, using in-comment type imports.
3 JWT auth methods, but the token provided is not JWT: 
3 JWT auth methods, token provided is JWT-shaped:
User can modify the method upon form submission:
> [ui] Allow for multiple JWT auth methods in the UI

- ui/app/components/job-editor.js
- ui/app/routes/jobs/job/definition.js
- ui/app/templates/components/job-editor.hbs
- ui/app/templates/components/job-editor/alert.hbs
- ui/app/templates/components/job-editor/edit.hbs
- ui/app/templates/components/job-editor/read.hbs
Display code properly in the edit state.
Loom Walk Through: https://www.loom.com/share/9aa4e60cc20546749a4bc5c2803910cd
> refact: handle edit state

- ui/app/components/job-editor.js
- ui/app/controllers/jobs/job/definition.js
- ui/app/routes/jobs/job/definition.js
- ui/app/templates/components/job-editor.hbs
- ui/app/templates/components/job-editor/alert.hbs
- ui/app/templates/components/job-editor/edit.hbs
- ui/app/templates/components/job-editor/read.hbs
- ui/app/templates/jobs/job/definition.hbs
- ui/tests/integration/components/job-editor-test.js
This PR is also pre-work for #16714. This PR moves the editing state of the `JobEditor` into the controller for the `Definition` view.
Loom Walk Through:  https://www.loom.com/share/c9290a770a1b4164a19d16a39e82d577
> refact:  move `edit` state to controller

- ui/app/components/job-editor.js
- ui/app/components/job-editor/alert.js
- ui/app/controllers/jobs/job/definition.js
- ui/app/helpers/merge.js
- ui/app/routes/jobs/job/definition.js
- ui/app/styles/components/codemirror.scss
- ui/app/templates/components/job-editor.hbs
- ui/app/templates/components/job-editor/alert.hbs
- ui/app/templates/components/job-editor/edit.hbs
- ui/app/templates/components/job-editor/read.hbs
- ui/app/templates/components/job-editor/review.hbs
- ui/app/templates/jobs/job/definition.hbs
- ui/tests/acceptance/keyboard-test.js
- ui/tests/helpers/module-for-job.js
- ui/tests/integration/components/job-editor-test.js
The PR is pre-work for #16714 to create some uniformity in alerts on the `JobEditor` component before adding a brand new alert.
Loom Walkthrough:  https://www.loom.com/share/ac82a522ba40423ab5c625799153a077
> refact:  uniform alerts

- ui/app/components/job-editor.js
- ui/app/components/job-editor/alert.js
- ui/app/controllers/jobs/job/definition.js
- ui/app/helpers/merge.js
- ui/app/routes/jobs/job/definition.js
- ui/app/styles/components/codemirror.scss
- ui/app/templates/components/job-editor.hbs
- ui/app/templates/components/job-editor/alert.hbs
- ui/app/templates/components/job-editor/edit.hbs
- ui/app/templates/components/job-editor/read.hbs
- ui/app/templates/components/job-editor/review.hbs
- ui/app/templates/jobs/job/definition.hbs
- ui/tests/acceptance/job-definition-test.js
- ui/tests/acceptance/keyboard-test.js
- ui/tests/helpers/module-for-job.js
- ui/tests/integration/components/job-editor-test.js
This PR resolves #16509.
This PR adds a query parameter to track the state of the view of the `JobEditor`.
> refact: `JobEditor` reactive query parameters

- command/agent/agent.go
- nomad/config.go
- nomad/license_config.go
- nomad/license_config_oss.go
- nomad/server.go
- nomad/server_setup_oss.go
- nomad/testing.go
and add new `TestConfigForServer()` to get a valid `nomad.Config` to use in tests.
Should be noop here in OSS.
Relates to hashicorp/nomad-enterprise#855
These OSS files originated in ent PR hashicorp/nomad-enterprise#1060
> ent: move all license info into LicenseConfig{}

- .changelog/16615.txt
- website/content/docs/commands/license/index.mdx
- website/content/docs/commands/license/inspect.mdx
- website/content/docs/enterprise/index.mdx
- website/content/docs/enterprise/license/faq.mdx
- website/content/docs/enterprise/license/index.mdx
- website/content/docs/upgrade/index.mdx
- website/content/docs/upgrade/upgrade-specific.mdx
- website/data/docs-nav-data.json
Update various docs including new expiration behavior in v1.6 and the `nomad license inspect` command to validate pre-upgrade.
Nearly done with: hashicorp/nomad-enterprise#855
> Update enterprise licensing documentation

- nomad/structs/services.go
This PR addresses the bug reported on https://github.com/hashicorp/nomad/issues/11097
After some consideration, it was decided that it was better to keep the validation in place:
- If in the future external DNS is used, putting the restriction back wont be backwards compatible.
- consul templates also has a similar validation.
> [Docs] Update comments on service name validation

- .changelog/16740.txt
- helper/stats/cpu.go
Currently we take just first processor Mhz, and exit, assuming they are all the same.
We depend on 	"github.com/shoenig/go-m1cpu" to get the cpu data 
On linux platform this either uses maximum frequency https://github.com/shoenig/gopsutil/blob/master/cpu/cpu_linux.go#L88 from `cpuinfo_max_freq` (that would be correct)
However some machines lack this file, and then we fallback to real frequency https://github.com/shoenig/gopsutil/blob/master/cpu/cpu_linux.go#L175-L179
Real frequency can be much lower than maximal, and taking just first processor value can give incorrect data.
For example on my machine
```
[georgy@kf06 ~]$ cat /proc/cpuinfo  | grep "cpu MHz"
cpu MHz		: 2200.000
cpu MHz		: 2685.956
cpu MHz		: 2200.000
cpu MHz		: 2252.721
cpu MHz		: 2200.000
cpu MHz		: 2200.000
cpu MHz		: …
```
> take maximum processor Mhz

- website/content/docs/install/index.mdx
The workflow described in the docs for apt installation is deprecated. Update to match the workflow described in the Tutorials and official packaging guide.
> docs: fix install instructions for apt

- client/allocrunner/alloc_runner.go
- client/allocrunner/alloc_runner_hooks.go
- client/allocrunner/csi_hook.go
- client/allocrunner/csi_hook_test.go
- client/allocrunner/interfaces/runner.go
- client/allocrunner/taskrunner/task_runner.go
- client/allocrunner/taskrunner/volume_hook_test.go
- client/pluginmanager/csimanager/interface.go
- client/structs/allochook.go
Fixes https://github.com/hashicorp/nomad/issues/16623
The allocrunner has a facility for passing data written by allocrunner hooks to taskrunner hooks. Currently the only consumers of this facility are the allocrunner CSI hook (which writes data) and the taskrunner volume hook (which reads that same data).
The allocrunner hook for CSI volumes doesn't set the alloc hook resources atomically. Instead, it gets the current resources and then writes a new version back. Because the CSI hook is currently the only writer and all readers happen long afterwards, this should be safe but #16623 shows there's some sequence of events during restore where this breaks down.
Refactor hook resources so that hook data is accessed via setters and getters that hold the mutex, and ensure the object is …
> CSI: set mounts in alloc hook resources atomically

- command/agent/job_endpoint.go
These endpoints all refer to `JobID` by the time you get to the RPC request layer, but the HTTP handler functions call the corresponding parameter `JobName`, which is a totally different thing (... though often with the same value).
> cleanup: use jobID name rather than jobName in job endpoints

- go.mod
- go.sum
https://github.com/shoenig/go-m1cpu/releases/tag/v0.1.5
which may also help with the Nix package for Nomad, which makes use of
the older IOKit framework version
https://github.com/shoenig/go-m1cpu/issues/5
> deps: update go-m1cpu with fix for BigSur users

- .changelog/16791.txt
- client/allocrunner/taskrunner/getter/testing.go
- client/allocrunner/taskrunner/getter/util.go
- client/allocrunner/taskrunner/getter/util_default.go
- client/allocrunner/taskrunner/getter/util_linux.go
- client/allocrunner/taskrunner/getter/util_windows.go
https://github.com/hashicorp/nomad/commit/95359b8c4cc9afbfe4db9b612d07f5116bad1066 disabled running the artifact downloader on Linux as the user `nobody` but left behind the code to set UID / GID, which are currently set as the same ones the user Nomad runs under. The current implementation however doesn't work, as described in https://github.com/hashicorp/nomad/issues/16789.
This PR removes setting attributes altogether as they are technically non required and they'll be inherited from the parent.
Fixes https://github.com/hashicorp/nomad/issues/16789
> Do not set attributes when spawning the getter child

- command/agent/command.go
Nomad's security model requires mTLS in order to secure client-to-server and server-to-server communications. Configuring ACLs alone is not enough. Loudly warn the user if mTLS is not configured in non-dev modes.
---
Note to reviewers: I'm totally happy to bikeshed the language used here  :grin: But it matches the other top-level pre-logging warnings like the bootstrap warning. 
Example output (first line of banner):
```
==> WARNING: mTLS is not configured - Nomad is not secure without mTLS!
==> WARNING: Bootstrap mode enabled! Potentially unsafe operation.
==> Loaded configuration from /home/tim/ws/nomad/etc/local/standalone.hcl
==> Starting Nomad agent...
==> Nomad agent configuration:
Advertise Addrs: HTTP: 192.168.1.162:4646; RPC: 192.168.1.162:4647; Serf: 192.168.1.162:4648
Bind …
```
> agent: add top-level warning if mTLS is not configured

- website/content/docs/concepts/plugins/csi.mdx
The vSphere plugin is exclusive to k8s because it relies on k8s-APIs (and crashes without them being present). Upstream unfortunately will not support Nomad, so we shouldn't refer to it in our concept docs here.
> docs: remove reference to vSphere from CSI concepts docs

- e2e/auth/auth_test.go
- e2e/auth/doc.go
- e2e/terraform/scripts/anonymous.nomad_policy.hcl
Follow-up to https://github.com/hashicorp/nomad/issues/16775
Closes https://github.com/hashicorp/nomad/issues/16483
This changeset provides a matrix test of ACL enforcement across several dimensions:
* anonymous vs bogus vs valid tokens
* permitted vs not permitted by policy
* request sent to server vs sent to client (and forwarded)
In order for this test to be meaningful for anonymous requests, I also had to reduce the permissions of the anonymous policy on the E2E cluster. The test runner uses a management token unless there's a test that overrides it that I've missed. I've spot-checked this didn't cause any new breakage on E2E tests but we have a few things like https://github.com/hashicorp/nomad/issues/16803 floating around that make it hard to be sure without digging into all the …
> E2E: test enforcement of ACL system

- api/internal/testutil/slow.go
Noticed that it was logging RequireRoot's line number and not the test.
> [testing] Set RequireRoot to be a test helper

- e2e/acl/acl_role_test.go
- e2e/acl/acl_test.go
- e2e/acl/acl_token_test.go
- e2e/acl/helpers.go
The `e2e/acl` package has some nice helpers for tracking and cleaning up ACL objects, but they are currently private. Export them so I can use them in other e2e packages.
> e2e: export ACL resource Cleanup helpers

- ui/app/components/job-status/allocation-status-block.hbs
- ui/app/components/job-status/panel/deploying.hbs
- ui/app/styles/components/job-status-panel.scss
- Animates the border on "unplaced" with a shimmer
- Animates the background on "pending" with a shimmer
> Shimmer effect on pending and unplaced allocs

- .changelog/16811.txt
- drivers/docker/config.go
- drivers/docker/config_test.go
- drivers/docker/driver.go
- drivers/docker/driver_test.go
Matches docker cli behavior.
Fixes #16754
> docker: default device.container_path to host_path

- e2e/nodedrain/doc.go
- e2e/nodedrain/input/drain_ignore_system.nomad
- e2e/nodedrain/input/drain_simple.nomad
- e2e/nodedrain/node_drain_test.go
- e2e/nodedrain/nodedrain.go
While working on several open drain issues, I'm fixing up the E2E tests. This subset of tests being refactored are existing ones that already work. I'm shipping these as their own PR to keep review sizes manageable when I push up PRs in the next few days for #9902, #12314, and #12915.
> E2E: update subset of node drain tests off the old framework

- .changelog/16826.txt
- client/allocwatcher/alloc_watcher.go
- e2e/nodedrain/input/drain_migrate.nomad
- e2e/nodedrain/node_drain_test.go
- e2e/nodedrain/nodedrain.go
- nomad/structs/structs.go
- nomad/structs/structs_test.go
- scheduler/generic_sched.go
- website/content/docs/job-specification/ephemeral_disk.mdx
The `ephemeral_disk` block's `migrate` field allows for best-effort migration of the ephemeral disk data to new nodes. The documentation says the `migrate` field is only respected if `sticky=true`, but in fact if client ACLs are not set the data is migrated even if `sticky=false`.
The existing behavior when client ACLs are disabled has existed since the early implementation, so "fixing" that case now would silently break backwards compatibility. Additionally, having `migrate` not imply `sticky` seems nonsensical: it suggests that if we place on a new node we migrate the data but if we place on the same node, we throw the data away!
Update so that `migrate=true` implies `sticky=true` as follows:
* The failure mode when client ACLs are enabled comes from the server not passing along a …
> ephemeral disk: `migrate` should imply `sticky`

- .changelog/16809.txt
- client/allocrunner/csi_hook.go
- client/allocrunner/csi_hook_test.go
- client/dynamicplugins/registry.go
- client/pluginmanager/csimanager/interface.go
- client/pluginmanager/csimanager/manager.go
- client/pluginmanager/csimanager/manager_test.go
With happy running tasks that use a CSI volume, on client restart they may fail to be recovered and instead be killed and rescheduled, even though there is a healthy happy CSI plugin running right next to them.
The simplest version of the error condition I could replicate was using this repo's `demo/csi/hostpath` example.  With the tasks all set up, I stop the client and start it again:
```
2023-04-05T22:10:33.940Z [INFO]  client.alloc_runner.task_runner: Task event: alloc_id=0480ac51-dd38-49ec-8831-48fd3c674279 task=redis type=Received msg="Task received by client" failed=false
2023-04-05T22:10:33.948Z [INFO]  client.alloc_runner.task_runner: Task event: alloc_id=d013ee08-10fc-ff0e-ef5e-cc444048fbfd task=plugin type=Received msg="Task received by client" failed=false …
```
> gracefully recover tasks that use csi node plugins

- .changelog/16815.txt
- client/allocrunner/taskrunner/envoy_version_hook.go
- client/allocrunner/taskrunner/envoy_version_hook_test.go
The first start of a Consul Connect proxy sidecar triggers a run of the envoy_version hook which modifies the task config image entry. The modification takes into account a number of factors to correctly populate this. Importantly, once the hook has run, it marks itself as done so the taskrunner will not execute it again.
When the client receives a non-destructive update for the allocation which the proxy sidecar is a member of, it will update and overwrite the task definition within the taskerunner. In doing so it overwrite the modification performed by the hook. If the allocation is restarted, the envoy_version hook will be skipped as it previously marked itself as done, and therefore the sidecar config image is incorrect and causes a driver error.
The fix removes the hook in marking …
> consul/connect: fixed a bug where restarting proxy tasks failed.

- ui/app/components/conditional-link-to.hbs
- ui/app/components/conditional-link-to.js
- ui/app/components/job-status/allocation-status-block.hbs
- ui/app/components/job-status/allocation-status-row.hbs
- ui/app/components/job-status/allocation-status-row.js
- ui/app/components/job-status/panel/deploying.hbs
- ui/app/components/job-status/panel/deploying.js
- ui/app/components/job-status/panel/steady.hbs
- ui/app/components/job-status/panel/steady.js
- ui/app/controllers/jobs/job/allocations.js
- ui/app/models/allocation.js
- ui/app/styles/components/job-status-panel.scss
- ui/app/templates/jobs/job/allocations.hbs
- ui/tests/acceptance/job-status-panel-test.js
Instead of just splitting by `alloc.clientStatus`, we now split by multiple factors and give indicators/icons as such.
This splits `allocBlocks` objects in both the "steady" and "deploying" panels into an object format like this:
```
allocBlocks = {
running: {
healthy: {
nonCanary: [Allocation, Allocation, Allocation],
canary: [Allocation],
},
unhealthy: {
nonCanary: [],
canary: [],
},
},
pending: {
healthy: {
nonCanary: [Allocation, Allocation, Allocation],
canary: [],
},
unhealthy: {
nonCanary: [],
canary: [],
},
},
failed: {
healthy: {
nonCanary: [],
canary: [],
},
unhealthy: {
nonCanary: [],
canary: [],
},
},
unplaced: {
healthy: {
nonCanary: [Allocation, Allocation, Allocation],
canary: [],
},
unhealthy: {
nonCanary: [],
canary: [],
},
},
complete: {
healthy: {
nonCanary: [],
canary: …
```
> [ui] Splitting deployment allocs by status, health, and canary status

- website/content/docs/operations/nomad-agent.mdx
Expand documentation about Nomad's signal handling behaviors, including removing incorrect information about graceful client shutdowns.
---
* preview link: https://nomad-9cb2o1urm-hashicorp.vercel.app/nomad/docs/operations/nomad-agent#stopping-an-agent
* note: I'm having this PR up separately from https://github.com/hashicorp/nomad/pull/16827 which changes the behavior because I want these docs backported whereas #16827 will only land in 1.5.x
> docs: document signal handling

- .changelog/16792.txt
- nomad/deployment_endpoint.go
- nomad/deployment_endpoint_test.go
- nomad/state/state_store.go
- nomad/structs/structs.go
This PR addresses the bug reported [here](https://github.com/hashicorp/nomad/issues/13660)
The deployments Namespace filter did not take into account the namespace wildcard, resulting on an empty response every time it was used in conjunction with a prefix.  This PR adds the missing wildcard check as well as filtering by the allowed namespaces according to the ACL token.
> Deployment Status Command Does Not Respect -namespace Wildcard

- .changelog/16792.txt
- nomad/deployment_endpoint.go
- nomad/deployment_endpoint_test.go
- nomad/state/state_store.go
- nomad/structs/structs.go
* func: add namespace support for list deployment
* func: add wildcard to namespace filter for deployments
* Update deployment_endpoint.go
* style: use must instead of require or asseert
* style: rename paginator to avoid clash with import
* style: add changelog entry
* fix: add missing parameter for upsert jobs
> Backport to 1.5.x: Deployment Status Command Does Not Respect -namespace Wildcard

- .changelog/16792.txt
- nomad/deployment_endpoint.go
- nomad/deployment_endpoint_test.go
- nomad/state/state_store.go
- nomad/structs/structs.go
* func: add namespace support for list deployment
* func: add wildcard to namespace filter for deployments
* Update deployment_endpoint.go
* style: use must instead of require or asseert
* style: rename paginator to avoid clash with import
* style: add changelog entry
* fix: add missing parameter for upsert jobs
> Backport to 1.3.x: Deployment Status Command Does Not Respect -namespace Wildcard

- .changelog/16827.txt
- client/client.go
- client/config/config.go
- client/config/drain.go
- client/drain.go
- client/drain_test.go
- command/agent/agent.go
- command/agent/config.go
- nomad/fsm.go
- nomad/structs/config/drain.go
- website/content/docs/configuration/client.mdx
- website/content/docs/configuration/index.mdx
- website/content/docs/operations/nomad-agent.mdx
- website/content/docs/upgrade/index.mdx
Fixes https://github.com/hashicorp/nomad/issues/2052
Adds a new configuration to clients to optionally allow them to drain their workloads on shutdown. The client sends the `Node.UpdateDrain` RPC targeting itself and then monitors the drain state as seen by the server until the drain is complete or the deadline expires.
---
In addition to the unit tests here, I've run a bench test. Clients have the following config:
```hcl
leave_on_interrupt = true
client {
drain_on_shutdown {
deadline = "20s"
ignore_system_jobs = true
}
```
Then I run a service job and a system job.
In the first test the `service_job` has a 5s `kill_timeout`. Then I stopped the node where the service job is running. The alloc takes a little over 5s to be stopped, and then the client immediately exits because the drain …
> client: allow `drain_on_shutdown` configuration

- website/content/docs/enterprise/license/faq.mdx
- website/content/docs/enterprise/license/index.mdx
Although we are changing licensing behavior in 1.6.0, the documentation for 1.5.x and previous is only mostly correct. It doesn't include the separate notion of license termination, which is well-described in Vault and Consul docs. The FAQ's section on expiring licenses was also never updated when we updated the behavior around expiration back in 1.1.0.
Make all the pre-1.6.0 licensing documentation accurately describe Nomad's actual behavior.
Note this PR is directly to the `release/1.5.x` branch.
> docs: update licensing FAQ to match current documentation

- .github/secret-scanning.yml
Examples in the documentation frequently include tokens, including Vault tokens which end up triggering GitHub's secret scanner. Remove these from consideration so that we don't get false positive reports.
> docs: disable secret scanning for documentation content

- .changelog/16907.txt
- jobspec2/hcl_conversions.go
- scheduler/feasible.go
- scheduler/feasible_test.go
Currently, when checking a nodes feasibility against the `distinct_hosts` constraint, the mere presence of the constraint is sufficient to activate it; however, the documentation indicates that setting the value to false is a legitimate answer.
The `jobspec` HCL1 parser would look for cases where the value was set to false and strip it from the generated job specification before submission. The `jobspec2` HCL2 parser writes it into the specification with the provided value whether true or false.
This has the consequence of causing jobs or tasks with a distinct_hosts constraint to always act as though the value is set to true.
Fixes #13861 
- Honor value for distinct_hosts constraint
- Add test for feasibility checking for `false`
> [scheduler] Honor `false` for distinct hosts constraint

- ui/app/controllers/settings/tokens.js
Remove unneeded service injection. This service is not being used in this controller and currently only exists in `main`, causing `release/1.5.x` to [break](https://app.circleci.com/pipelines/github/hashicorp/nomad-enterprise/4640/workflows/c21e8058-80dd-4f5b-8fb6-1217ced4241d/jobs/50445?invite=true#step-107-2759).
> ui: fix notification service in token controller

- nomad/structs/structs.go
- nomad/structs/structs_test.go
Using the "+" operator is faster than the `fmt` package functions which I think makes sense to use here as they are simple concatenations and in a hot-path. I added some simple tests to ensure the change doesn't alter the behaviour.
> rpc: use "+" concatenations in hot path RPC rate limit metrics.

- scheduler/feasible_test.go
Add missing import to fix https://github.com/hashicorp/nomad/actions/runs/4726130915/jobs/8385391229#step:4:3833
Targets `release/1.3.x` only.
> ci: fix missing import

- .changelog/16921.txt
- client/allocrunner/network_manager_linux.go
- client/allocrunner/network_manager_linux_test.go
Check the task group network length before trying to access the first element.
I haven't been able to reproduce the problem but the fix seems clear enough.
Closes #16863
> allocrunner: prevent panic on network manager

- website/content/docs/configuration/ui.mdx
1. On the Consul address, following the recommendation for the HTTPS API on port `8501`.
2. Add the hint to use HEX values for the colors.
> docs: Updates to the UI block

- website/content/api-docs/acl/policies.mdx
- website/content/docs/concepts/workload-identity.mdx
For some reason the headers are not displayed if they're a level 1 header:
https://developer.hashicorp.com/nomad/docs/concepts/workload-identity
> docs: add missing API field JobACL and fix workload identity headers

- .changelog/16071.txt
- .changelog/_14.txt
This PR is just an update to the changelog to reflect a bug that was fixed in our [actions-packaging-linux](https://github.com/hashicorp/actions-packaging-linux) action. We received a report from a user stating that vendor labels were missing when downloading linux packages (for products that were released via CRT) We fixed this in [this PR](https://github.com/hashicorp/actions-packaging-linux/pull/14) and we added a vendor label and set the default to `HashiCorp` This will only affect future releases that go through our linux promotion pipeline -- historical releases will not have this vendor label.
> changelog: add changelog update for vendor label for linux packaging

- website/content/docs/install/index.mdx
As noted in https://github.com/hashicorp/nomad/pull/16767#discussion_r1172756817, our fix for adding the keyring had a typo on the path. I checked the equivalent tutorials repo PR and it was correct there.
> docs: fix keyring path in install docs

- .changelog/16944.txt
- command/job_plan.go
PR #14492 introduced a new check to return 0 when the `nomad job plan` command returns a diff of type `None`.
But the `-diff` CLI flag was also being used to control whether the plan request should return the diff of not instead of just controlling if the diff was printed.
This means that when `-diff=false` is set the response does not include any diff information, and so the new check panics.
This commit fixes the problem by always requesting a diff and using the `-diff` only for controlling output, as it's currently documented.
Closes https://github.com/hashicorp/nomad/issues/16939
> cli: fix panic on job plan when -diff=false

- .changelog/16776.txt
- client/fingerprint/plugins_cni.go
- client/fingerprint/plugins_cni_test.go
- client/fingerprint/test_fixtures/cni/bridge
- client/fingerprint/test_fixtures/cni/vlan
CNI plugins v1.2.0 and above output a second line, containing supported protocol versions. Nomad tests should support this.
> cni: fix plugin fingerprinting versions

- .changelog/16723.txt
- client/taskenv/env.go
- client/taskenv/env_test.go
- command/agent/agent_endpoint_test.go
- nomad/job_endpoint_hook_connect.go
- nomad/structs/diff.go
> fix host port handling for ipv6, fixes #16550

- .changelog/16905.txt
- client/allocrunner/group_service_hook.go
- e2e/consul/alloc_restart_test.go
- e2e/consul/consul_test.go
- e2e/consul/input/alloc_restart.hcl
- e2e/consul/service_revert_test.go
This PR may fix a bug where group services will never be deregistered if the group undergoes an alloc restart.
Fixes #16616
Adds an e2e test case covering the repro in ^
> services: un-mark group services as deregistered if restart hook runs

- .changelog/16969.txt
- nomad/job_endpoint.go
- nomad/job_endpoint_test.go
> scale: do not allow scaling of jobs with type system.

- ui/app/adapters/job.js
- ui/app/models/job.js
- ui/app/routes/jobs/job/definition.js
- ui/app/utils/add-to-path.js
- ui/tests/unit/adapters/job-test.js
This PR creates a new adapter and model method for fetching a specification for a job and refactors the `jobs.job.definition` route's model to use the specification returned from this API response instead of trying to pull this off of the `GET /job/:jobId` endpoint.
This PR is part of a larger block of work that will update the UI in accordance with late API changes.
Loom Walk Through:  https://www.loom.com/share/6291a654c01f473a98edcae0b5fff0cd
> refact:  update for `GET job/:jobId/submission` endpoint

- .changelog/16960.txt
- ui/app/components/evaluation-sidebar/detail.hbs
- ui/app/styles/components/sidebar.scss
This PR establishes CSS flexbox regions in the Evaluations sidebar so both it, and the evaluation response, can be scrolled.
> [ui] Fixed: Evaluations sidebar/response not scrollable

- drivers/docker/driver_test.go
- nomad/job_endpoint_test.go
causing CI failures with the following error:
```
=== Errors
drivers\docker\driver_test.go:849:20: undefined: os
drivers\docker\driver_test.go:850:20: undefined: os
```
```
nomad/job_endpoint_test.go:7648:69: too many arguments in call to state.UpsertJob
have ("github.com/hashicorp/nomad/nomad/structs".MessageType, number, nil, *"github.com/hashicorp/nomad/nomad/structs".Job)
want ("github.com/hashicorp/nomad/nomad/structs".MessageType, uint64, *"github.com/hashicorp/nomad/nomad/structs".Job)
```
> ci: fix test failures due to backport issues

- drivers/mock/driver.go
- drivers/mock/driver_test.go
While working on client status update improvements, I encountered problems getting tests with the mock driver to correctly restore.
Unlike typical drivers the mock driver doesn't have an external source of truth for whether the task is running (ex. making API calls to `dockerd` or looking for a running PID), and so in order to make up that information, it re-parses the original task config. But the taskrunner doesn't call the encoding step for `RecoverTask`, only `StartTask`, so the task config the mock driver gets is missing data.
Update the mock driver to stash the "external" state in the task state that we'll get from the task runner, so that we don't have to try to recover from the original `TaskConfig` anymore. This should bring the mock driver closer to the behavior of the other …
> testing: improve fidelity of mock driver task restore

- .changelog/15514.txt
- CHANGELOG.md
- website/content/docs/job-specification/artifact.mdx
- changelog: note artifact breaking changes for 1.5.0
- docs: add note about environment variables to artifact job spec docs
Closes #17000
I didn't add a .changelog file for the compression limits entry because there already is one (originally got sorted under improvements, now calling it out as a breaking change)
> docs: add more notes about artifact breaking changes in 1.5.0

- ui/app/adapters/job.js
- ui/app/components/job-editor.js
- ui/app/controllers/jobs/job/definition.js
- ui/app/models/job.js
- ui/app/routes/jobs/job/definition.js
- ui/app/styles/components/json-viewer.scss
- ui/app/templates/components/job-editor.hbs
- ui/app/templates/components/job-editor/alert.hbs
- ui/app/templates/components/job-editor/edit.hbs
- ui/app/templates/components/job-editor/read.hbs
- ui/app/templates/jobs/job/definition.hbs
- ui/app/utils/add-to-path.js
- ui/mirage/config.js
- ui/tests/acceptance/job-definition-test.js
- ui/tests/unit/adapters/job-test.js
In this PR, we introduce a feature to display specification literals via variable flags from the API response in the read-only and edit views. The PR also adds styling and spacing adjustments to ensure that the displayed literals look visually appealing and that code mirror doesn't take up too much space. Additionally, the PR includes logic to manually convert JSON objects to HCL format using loose logic, focusing on variable flags. 
Side Effect: Note that the text displayed in the Job Editor header is now only conditionally rendered to show on the job run page, which utilizes the same editor component.
Loom Walk Through:  https://www.loom.com/share/07a0d2cde466416890d3aaa3988e5559
> ui: visualize variables

- ui/tests/acceptance/job-status-panel-test.js
Our acceptance tests generate some relative-time-from-now text that varies on each test run. This hides those values.
> [ui] Stabilize Percy visual diff tests for new Job Status feature

- ui/app/components/job-status/panel/deploying.js
- ui/mirage/scenarios/default.js
- ui/tests/integration/components/job-status-panel-test.js
An allocation might get deploymentStatus.Healthy set on it while it's running, and THEN fail, but its deployment status is never revoked.
This makes it so it's not observed with respect to how we group our allocs.
> [ui, deployments] Don't separate allocation groups based on their deployment health unless they're "running"

- .git-blame-ignore-revs
Update the configuration file that's handy for those of us with `blame.ignoreRevsFile` set
> add copywrite headers commit to ignore-revs config file

- ui/app/components/job-status/failed-or-lost.hbs
- ui/app/components/job-status/failed-or-lost.js
- ui/app/components/job-status/panel/deploying.hbs
- ui/app/components/job-status/panel/deploying.js
- ui/app/components/job-status/panel/steady.hbs
- ui/app/components/job-status/panel/steady.js
- ui/app/models/allocation.js
- ui/app/styles/components/job-status-panel.scss
- ui/tests/acceptance/job-status-panel-test.js
- ui/tests/integration/components/job-status/failed-or-lost-test.js
Adds indicators and links for those allocations that have been restarted and rescheduled, either during a deployment or due to failures in an otherwise steady state.
Additionally, adds the concept of "permanent failure" to allocations we show in the main chart. For example, an allocation that has failed past its restart attempts will go into a "failed" clientStatus, but we don't want to show it in the main chart if there's a rescheduled allocation to take it over. The new `allocation.hasBeenRescheduled` computed property handles this.
> [ui, deployments] Restarted and Rescheduled panel cells

- .changelog/17045.txt
- client/allocrunner/taskrunner/envoy_version_hook.go
- client/allocrunner/taskrunner/envoy_version_hook_test.go
- helper/envoy/envoy.go
- website/content/api-docs/client.mdx
- website/content/docs/commands/node/meta/read.mdx
- website/content/docs/job-specification/gateway.mdx
- website/content/docs/job-specification/sidecar_task.mdx
This PR modifies references to the `envoyproxy/envoy` docker image to
explicitly include the `docker.io` prefix. This does not affect existing
[docker] users, but makes things easier for Podman users, who otherwise need to
specify the full name because Podman does not default to `docker.io`
> connect: set default envoy version domain

- .changelog/17044.txt
- client/allocrunner/taskrunner/envoy_version_hook.go
- client/allocrunner/taskrunner/envoy_version_hook_test.go
- helper/envoy/envoy.go
This PR does some cleanup of an old code path for versions of Consul that
did not support reporting the supported versions of Envoy in its API. Those
versions are no longer supported for years at this point, and the fallback
version of envoy hasn't been supported by any version of Consul for almost
as long. Remove this code path that is no longer useful.
> connect: envoy remove fallback

- ui/app/adapters/job.js
- ui/app/components/job-page/parts/title.js
- ui/app/models/job.js
This PR updates the adapter method's (`run` and `update`) on the `Job` class to reflect the new request schema to include a `Submission` object to maintain a job version history.
> bug:  update `job.run` and `job.update` adapter methods

- command/agent/acl_endpoint_test.go
- go.mod
- go.sum
- lib/auth/jwt/validator_test.go
- nomad/acl_endpoint_test.go
- nomad/encrypter.go
- nomad/encrypter_test.go
- nomad/mock/acl.go
- nomad/structs/structs.go
Their release notes are here: https://github.com/golang-jwt/jwt/releases
Seemed wise to upgrade before we do even more with JWTs. For example this upgrade *would* have mattered if we already implemented common JWT claims such as expiration. Since we didn't rely on any claim verification this upgrade is a noop...
...except for 1 test that called `Claims.Valid()`! Removing that assertion *seems* scary, but it didn't actually do anything because we didn't implement any of the standard claims it validated:
https://github.com/golang-jwt/jwt/blob/v4.5.0/map_claims.go#L120-L151
So functionally this major upgrade is a noop.
> dep: update from jwt/v4 to jwt/v5

- ui/app/adapters/job.js
- ui/app/components/job-editor.js
- ui/app/components/job-page/parts/title.js
- ui/app/components/tooltip.js
- ui/app/models/job.js
- ui/app/styles/components/codemirror.scss
- ui/app/templates/components/job-editor.hbs
- ui/app/templates/components/job-editor/alert.hbs
- ui/app/templates/components/job-editor/edit.hbs
- ui/app/templates/components/job-editor/read.hbs
- ui/app/templates/components/tooltip.hbs
This PR tackles several styling requests:
- Disabling the toggle with tooltip messaging
- Spacing out alerts
- Dismissing the plan message
- Sticky job plan button
- Autofocusing the code mirror editor to prevent automatic scrolling when there's too much code in the editor or a second editor is present
Video Walk Through:  https://www.loom.com/share/74a9dc40dc2d4d5586b4e4f98f0538b6
> styling:  UX requests

- website/content/docs/integrations/consul-connect.mdx
- website/content/docs/networking/cni.mdx
- website/content/docs/networking/index.mdx
This PR moves the instruction steps for install the CNI reference plugins
from the Consul Mesh integration page to the general Networking CNI page.
These plugins are required for bridge networking, not just Consul Mesh,
so it makes sense to have them on the general CNI page.
Closes #17038
> docs: move CNI reference plugins installation to CNI overview page

- ui/app/components/job-status/panel/steady.hbs
- ui/app/components/job-status/panel/steady.js
- ui/app/models/allocation.js
We depend on iterating over `nodes` to determine how many allocations should be running in a system job. So what happens when the user's ACL doesn't allow for `node-read` permissions?
An easy solution would be to just drop a "You require node-read" block over top of the panel, like we do for the `JobStatusInClient` panel.
But we _can_ know a bit about the nodes — their IDs, anyway — and we can know that for system jobs at most one alloc is supposed to run per node.
So in this way, we can do something, which is better than nothing: show them the actual state, if not the desired state, of their job allocations.
This drops the "/Y" part of "X/Y allocations running" for the steady state panel when you lack node-read permissions and are viewing a system job. It also can never show "Unplaced" …
> [ui, deployments] handle node read permissions for system job panel

- ui/app/components/job-status/panel/deploying.js
- ui/app/components/job-status/panel/steady.hbs
- ui/app/components/job-status/panel/steady.js
- ui/app/utils/properties/job-client-status.js
- ui/tests/acceptance/job-detail-test.js
- ui/tests/acceptance/job-status-panel-test.js
- ui/tests/helpers/module-for-job.js
The order in which we want to show allocations (that may have previously been relevant but perhaps no longer are?) in our new visualization has gone through a few changes.
First, we figured "Let's just show them in order of what the user cares about! Running first, then pending, then failed, then lost...." and so on.
Then, we realized that this would clump all the failed allocations from older versions together before we got to the lost allocations of the newest version.
Because the user would expect the "latest" allocs to exist there instead, we can walk backwards by job version instead.
Ah! But that's not *quite right*. Running/Pending still matter above all else. So the new, nuanced solution looks like this:
- Look at all job allocations and grab the running/pending ones first
- Then, …
> [ui, deployments] Fix order in which allocations are ascribed to the status chart

- command/agent/config.go
Intended to be `job_max_source_size`, rather than `max_job_source_size`.
This way it fits better with existing client config options related
to jobs.
No backport as this is a 1.6 thing
> client: fix job_max_source_size client config name

- .changelog/17092.txt
- nomad/job_endpoint.go
- nomad/job_endpoint_test.go
The job scale RPC endpoint hard-coded the eval creation to use the type of service. This meant scaling events triggered on jobs of type batch would create evaluations with the wrong type, which does not seem to cause any problems, just confusion when correlating the two.
closes #17091
> scale: fixed a bug where evals could be created with wrong type.

- .changelog/17065.txt
- nomad/job_endpoint_hook_connect.go
- nomad/job_endpoint_hook_connect_test.go
This PR adds a heuristic to detect whether to use the podman task driver
for the connect sidecar proxy. The podman driver will be selected if there
is at least one task in the task group configured to use podman, and there
are zero tasks in the group configured to use docker. In all other cases
the task driver defaults to docker.
After this change, we should be able to run typical Connect jobspecs
(e.g. nomad job init [-short] -connect) on Clusters configured with the
podman task driver, without modification to the job files.
Closes #17042
> connect: use heuristic to detect sidecar task driver

- CHANGELOG.md
minor typo; 1.3.x not 1.13.x
tagging @tgross
> minor typo; 1.3.x not 1.13.x

- ui/app/components/job-status/panel.hbs
- ui/app/components/job-status/panel.js
- ui/app/components/job-status/panel/deploying.js
- ui/app/components/job-status/panel/steady.hbs
- ui/app/components/job-status/panel/steady.js
- ui/app/models/allocation.js
- ui/app/styles/components/job-status-panel.scss
- ui/app/templates/components/job-page/system.hbs
- ui/tests/acceptance/job-detail-test.js
- ui/tests/acceptance/job-status-panel-test.js
- ui/tests/helpers/module-for-job.js
Extends the new Job Status panel to System type jobs.
System jobs have a few nuances compared to Service jobs worth mentioning, and that generally drove this PR:
- They do not have the concept of allocation "Rescheduling", so the rescheduling cell has been omitted 
- They have no concept of deployments, so the panel only has a "steady" mode
- The desired allocation count **cannot be known**. This is currently the subject of [some discussion elsewhere](https://github.com/hashicorp/nomad/issues/17099) but for purposes of this PR has amounted to showing "3 allocations running" instead of "3/5 allocations running"
This PR deprecates the JobClientStatusSummary and Summary items for system jobs.
> [ui, deployments] Job status for System Jobs

- .changelog/17071.txt
- nomad/state/state_store.go
- nomad/state/state_store_test.go
Fix for https://github.com/hashicorp/nomad/issues/17070. Corrected the status description and modify time of evals which are canceled due to another eval having completed in the meantime. 
Tests added. It seems that the testing has originally been written a rather long time before the new-style of testing started within the Nomad codebase. Please let me know if you'd rather I moved the entire test to the new style, or if added if clauses seem like a reasonable tradeoff given the size of the change.
> [17070] Correct the status description and modify time of canceled evals.

- website/content/docs/upgrade/upgrade-specific.mdx
Nomad 1.5.4 shipped with a logmon bug that we rolled out a fix for in Nomad 1.5.5. Unfortunately we can't yank the release but we should leave a note in the upgrade guide telling users to avoid it.
I'll backport this to `release/1.5.x` and the `stable-website` branch once merged.
> docs: add note to upgrade guide about yanked version

- .github/workflows/backport.yml
This reverts commit 1721e687c0832bea3d9b7eec5dcd3c4e7a924d71.
The change was expected to solve the sporadic problems we were having with Backport Assistant, but it end up creating even more failures.
> Revert "ci: use `BACKPORT_MERGE_COMMIT` option (#16730)"

- .changelog/17104.txt
- client/allocrunner/alloc_runner.go
- client/allocrunner/alloc_runner_hooks.go
- client/allocrunner/fail_hook.go
- client/allocrunner/taskrunner/task_runner.go
- client/allocrunner/taskrunner/task_runner_test.go
- client/client_test.go
- client/config/config.go
- nomad/mock/alloc.go
- testutil/wait.go
Fixes #17102 -- I describe the issue more fully there.
My approach here is to stop skipping over `allocRunner.runTasks()` on prerun error.  That way, instead of duplicating more cleanup code, which may change in the future, the same `TaskRunner.Run()` code that usually handles task cleanup can do what it needs to as appropriate with tasks that fail prerun during the alloc restore process.
In pursuit of that, I made an error-inducing `FailHook` and added the ability to include it as part of client Config for the client integration test.  I could remove the non-Prerun interface implementations, but I figured while I'm at it, may as well make a thing that can be induced to fail at any stage in case it's useful?
> Fix task leak during client restore when allocrunner prerun hook fails

- e2e/jobsubmissions/jobsubapi_test.go
- nomad/state/state_store.go
This PR fixes a bug where the job submission would always be nil when
a job goes through a reversion to a previous version. Basically we need
to detect when this happens, lookup the submission of the job version
being reverted to, and set that as the submission of the new job being
created.
No CL/BP; this is for a 1.6 feature
> api: set the job submission during job reversion

- client/allocrunner/taskrunner/getter/util_linux.go
- client/allocrunner/taskrunner/getter/util_linux_test.go
This PR fixes a bug where nodes configured with populated
`/etc/ssh/ssh_known_hosts` files would be unable to read them during
artifact downloading.
Fixes #17086
> client: unveil /etc/ssh/ssh_known_hosts for artifact downloads

- ui/app/components/job-status/panel/steady.hbs
- ui/app/components/job-status/panel/steady.js
Resolves #17149
- Sorts versions ascending
- changes "pending" to "unknown" and removes the "v" before it
> [ui, deployments] Version sorting in the job status panel

- go.mod
- go.sum
#15861 describes intermittent panics caused by go-metrics Prometheus client. We have not been able to further debug this problem due to the lack of information when the panic happens.
https://github.com/hashicorp/go-metrics/pull/146 prevents the panic from happening and also logs additional information that can help us understand the root cause of the problem.
This commits pins the go-metric dependency to this branch until we can better debug the issue.
> deps: update go-metrics to prevent panic

- ui/app/templates/application.hbs
- ui/tests/acceptance/application-errors-test.js
- ui/tests/pages/jobs/list.js
This PR adds a link to the Sign In page to the Nomad UI error page.
> ui:  add sign-in link on err page

- ui/app/components/job-status/panel/steady.hbs
- ui/app/components/job-status/panel/steady.js
- ui/tests/acceptance/job-status-panel-test.js
We shouldn't count "complete" allocations against the denominator in the "7/10 Allocations Running" heading, when the 3 non-running are of "complete" status. Instead, in this case, we would say "7/7 Remaining Allocations Running".
Resolves #17139
> [ui, deployments] Denominator based on completed allocations for batch jobs

- nomad/state/schema.go
- nomad/state/state_store.go
- nomad/structs/structs.go
This PR refactors the `job_submissions` state store code to eliminate the
use of a second index formerly used for purging all versions of a given
job. In practice we ended up with duplicate entries on the table. Instead,
use index prefix scanning on the primary index and also tidy up any potential
for creating (or removing) duplicates.
Currently on main attempting to GC a job results in, 
```
2023-05-10T20:15:42.657Z [ERROR] nomad.fsm: deregistering job failed: job=http error="DeleteJob failed: deleting job submission failed: not found"
2023-05-10T20:15:42.657Z [ERROR] nomad.job: batch deregister failed: error="DeleteJob failed: deleting job submission failed: not found"
2023-05-10T20:15:42.657Z [ERROR] core.sched: batch job reap failed: error="DeleteJob failed: deleting job submission …
```
> core: eliminate second index on job_submissions table

- ui/app/components/job-editor.js
- ui/app/controllers/jobs/job/definition.js
- ui/app/routes/jobs/job/definition.js
> chore:  write js doc

- ui/tests/acceptance/job-definition-test.js
> chore: add percy tests

- .changelog/17169.txt
- ui/app/components/region-switcher.js
- ui/app/templates/components/region-switcher.hbs
- ui/tests/acceptance/keyboard-test.js
Adds `r #` keyboard bindings to regions.
**Note**: I'm making an assumption here that users have few regions in general to save on keystrokes. If, however, we expect that users commonly have 10+ regions, then I should switch this to `r 0 1` instead of just `r 1`, lest you end up on the wrong region when you meant to go to region 10 or 11 etc. (we evaluate the buffer on keypress eagerly)
> [ui] Keyboard shortcuts to switch regions

- ui/app/components/job-status/deployment-history.hbs
- ui/app/components/job-status/deployment-history.js
- ui/app/components/job-status/panel/steady.hbs
- ui/app/components/job-status/panel/steady.js
- ui/app/styles/components/job-status-panel.scss
Adds a toggle to show/hide deployment history, and adds task event history to steady-state job status panels
Resolves #17159
> [ui, deployments] Deployment history on steady state

- helper/raftutil/msgtypes.go
- nomad/fsm.go
- nomad/fsm_test.go
- nomad/mock/mock.go
- nomad/state/schema.go
- nomad/state/state_store.go
- nomad/state/state_store_node_pools.go
- nomad/state/state_store_node_pools_test.go
- nomad/state/state_store_restore.go
- nomad/structs/node_pool.go
- nomad/structs/node_pool_test.go
- nomad/structs/structs.go
This PR adds the base work for the new node pools feature. It includes a new `NodePool` struct and its corresponding state store table. 
Upon start the state store is populated with two reserved node pools that cannot be modified nor deleted:
* `all` is a node pool that always includes all nodes in the cluster.
* `default`  is the node pool where nodes that don't specify a node pool in their configuration are placed.
> node pool: initial base work

- nomad/acl_endpoint.go
New RPC endpoints introduced during OIDC and JWT auth perform unnecessary many RPC calls when they upsert generated ACL tokens, as [pointed out](https://github.com/hashicorp/nomad/pull/15918/files/223c764e82408f02c306d9ebf98477167a4c6a05#r1138684122) by @tgross. 
This PR moves the common logic from `acl.UpsertTokens` method into a helper method that contains common logic, and sidesteps authentication, metrics, etc.
> acl: refactor acl.UpsertTokens to avoid unnecessary RPC calls

- .changelog/16071.txt
The backport bot missed https://github.com/hashicorp/nomad/pull/16071 so this changelog-only PR is not present in the release/1.5.x branch as we'd expect.
> backport changelog update for vendor label for linux packaging (#16071)

- .changelog/17175.txt
- client/allocrunner/alloc_runner.go
- e2e/clientstate/allocs_test.go
- e2e/clientstate/input/alloc_zombie.nomad
This PR fixes a bug where issuing a restart to a terminal allocation
would cause the allocation to run its hooks anyway. This was particularly
apparent with group_service_hook who would then register services but
then never deregister them - as the allocation would be effectively in
a "zombie" state where it is prepped to run tasks but never will.
Part of #17079
Part of #16238
Part of #14618
Part of #17182 
Part of #16762 
Note this doesn't appear to be the only source of leaked registrations - see https://github.com/hashicorp/nomad/issues/17079 for more.
> client: ignore restart issued to terminal allocations

- .changelog/17198.txt
- scheduler/spread.go
- scheduler/spread_test.go
When spread targets have a percent value of zero it's possible for them to return -Inf scoring because of a float divide by zero. This is very hard for operators to debug because the string "-Inf" is returned in the API and that breaks the presentation of debugging data.
Most scoring iterators are bracketed to -1/+1, but spread iterators do not so that they can handle greatly unbalanced scoring so we can't simply return a -1 score without generating a score that might be greater than the negative scores set by other spread targets. Instead, track the lowest-seen spread boost and use that as the spread boost for any cases where we'd divide by zero.
Fixes: #8863
> scheduler: prevent -Inf in spread scoring 

- ui/app/components/job-subnav.js
- ui/app/templates/components/job-subnav.hbs
- ui/tests/helpers/module-for-job.js
Allocations, Evaluations, and Services don't exist for parents of child jobs, but we show their menu items anyway. This adds a check to see if the job has children, and if so, hides the relevant nav. "Clients" is also swept up on this, and is a redundant check, but that's fine.
Resolves #17189
> [ui] Remove unnecessary subnav for parent jobs

- .github/workflows/build.yml
- .github/workflows/ember-assets.yml
- .github/workflows/ember-test-audit.yml
- .github/workflows/release.yml
- .github/workflows/semgrep.yml
- CODEOWNERS
Many of the GitHub Actions from the build pipeline are written in a truly ancient version of NodeJS. Upgrade to more recent versions.
Fixes: #17215
> build: update deprecated GitHub Actions

- .changelog/17195.txt
- scheduler/propertyset.go
- scheduler/spread.go
- scheduler/spread_test.go
When calculating the score in the `SpreadIterator`, the score boost is proportional to the difference between the current and desired count. But when there are implicit spread targets, the current count is the sum of the possible implicit targets, which results in incorrect scoring unless there's only one implicit target.
This changeset updates the `propertySet` struct to accept a set of explicit target values so it can detect when a property value falls into the implicit set and should be combined with other implicit values.
Fixes: #11823
> scheduler: count implicit spread targets as a single target

- .changelog/17214.txt
- ui/app/mixins/with-watchers.js
On a parent/child Nomad job (periodic, parameterized), the Nomad UI shows a page at `jobs/:job` that aggregates information about its child jobs. For example, a periodic job that runs hourly, etc. would have all its hourly runs included in a "Child Jobs" table.
That parent job, though, does not have any allocations (or evaluations, or services) of its own. Despite this, we do consider it a job, if only of a different type (we might otherwise have considered it a "folder" or some other similar concept)
Because we consider it a job, we give it all the bells and whistles that nomad jobs have at the top level (we're pulling some of these back, though; see the removal of unnecessary subnav in https://github.com/hashicorp/nomad/pull/17190 for example).
While this is pretty innocuous most of the …
> [ui, deployments] Fix a bug where watchers on a parent (periodic) job would continue on a child route

- website/content/docs/job-specification/template.mdx
Removes unnecessary curly brackets from the job specification template docs in the ["Nomad variables"](https://developer.hashicorp.com/nomad/docs/job-specification/template#nomad-variables) section.
```diff
template {
data        = <<EOH
{{ range nomadVarList }}
{{ . }}
{{ end }}
- }
EOH
}
```
> docs: remove unneeded brackets from job specification template docs

- website/content/docs/job-specification/ephemeral_disk.mdx
- website/content/docs/job-specification/logs.mdx
Adds docs explaining the logs/ephemeral disk connection
I'm pretty sure this is accurate content, but a sanity-check from Nomad eng would be good
> Adds documentation on ephemeral disk and logs

- .changelog/17199.txt
- drivers/shared/executor/executor.go
On Windows the executor returns an error when trying to open the `NUL` device when we pass it `os.DevNull` for the stdout/stderr paths. Instead of opening the device, use the discard pipe so that we have platform-specific behavior from the executor itself.
Fixes: #17148
---
Because our E2E tests are a much more realistic exercise of the behavior, I ran the following Windows batch job on our E2E cluster with Windows 2016. The job has log collection enabled:
<details><summary>jobspec</summary>
```hcl
type = "batch"
constraint {
attribute = "${attr.kernel.name}"
value     = "windows"
}
group "group" {
task "task" {
driver = "raw_exec"
template {
data = <<EOH
$Number = 1..30
$Number | ForEach-Object {
if ($_ % 5 -eq 0 -and $_ % 3 -eq 0)
{
Write-Host "FizzBuzz"
}
elseif ($_ % 3 …
```
> logs: fix `logs.disabled` on Windows

- ui/app/controllers/jobs/index.js
- ui/app/controllers/optimize.js
- ui/app/models/job.js
- ui/app/templates/components/job-row.hbs
- ui/tests/acceptance/jobs-list-test.js
Resolves #15736 
This PR adds a UI filter to the `jobs.index` view to enable filtering for jobs that are packs.
> ui:  add option to filter for jobs that are packs

- api/allocations.go
- nomad/structs/structs.go
- ui/app/components/job-status/failed-or-lost.hbs
- ui/app/components/job-status/failed-or-lost.js
- ui/app/components/job-status/panel/steady.hbs
- ui/app/components/job-status/panel/steady.js
- ui/app/controllers/jobs/job/allocations.js
- ui/app/templates/components/multi-select-dropdown.hbs
- ui/app/templates/jobs/job/allocations.hbs
Adds a new filter, "Scheduling", to the job allocations page. This helps facilitate Rescheduled/Restarted links from the upcoming [Job Status Panel](https://github.com/hashicorp/nomad/issues/16128) and gives us future options for letting users drill down on this list page.
Because of some seen inconsistencies in testing, this adds `NextAllocation` to Allocations in their list/stub form from our API, where before they only existed when an allocation was being fetched individually. This, combined with a check for FollowUpEvalID, gives us a better picture of "Is a terminal allocation never going to be rescheduled?", which the UI is seeking to show to users here.
Resolves #17221
> [ui] Adds a "Scheduling" filter to the job.allocations page

- .changelog/17138.txt
- command/server_members.go
Leader status is shown in regular table output but not in json output.
> cli: Show leader status in json output of server members

- .github/workflows/ember-assets.yml
- .github/workflows/ember-test-audit.yml
- .github/workflows/semgrep.yml
The `backspace/ember-asset-size` action we're using is unmaintained and has a bunch of vulns in it, so it won't pass security screening (this is a NodeJS action so it has piles of dependencies, 99% of which won't be in use but fails automated screening anyways). Move this to the upstream version.
The `machine-learning-apps/pr-comment` action also presents a problem for the ProdSec security screening because it's archived and also runs an external Docker image. Move this to a likely-ok maintained action for now, until we can spare some time to remove this in lieu of something more reasonable that isn't a GitHub action.
Once this is tested, I'll then have to follow up in https://github.com/hashicorp/security-tsccr/pull/428 to pin the SHA, and then I'll have to follow-up once that other PR …
> build: move GitHub actions to versions allowed by prodsec

- .github/workflows/semgrep.yml
The ref, sha, and URL in the TSCCR repo for the `returntocorp/semgrep-action` action was incorrect, so the pinning tool was not able to find the correct entry and it was not pinned in #17238.
The repository is fixed in https://github.com/hashicorp/security-tsccr/pull/431
> build: pin semgrep action

- website/content/docs/concepts/workload-identity.mdx
Workload Identities have an implicit default policy. This policy can't currently be described via HCL because it includes task interpolation for Variables and access to the Services API (which doesn't exist as its own ACL capbility). Describe this in our WI documentation.
Fixes: #16277
> docs: describe the default Workload Identity ACL policy

- .changelog/17018.txt
- nomad/acl.go
- nomad/variables_endpoint_test.go
prevent all calls to the [Task API](https://developer.hashicorp.com/nomad/api-docs/task-api) from a periodically-dispatched job failing with `403`.
This happens because no policy for the job id (one with a `periodic-\d+` suffix) matches the generated token claims (that specifically use the [parent job id](https://github.com/hashicorp/nomad/blob/891999789689240006b2a6076b73ddc67249d48d/nomad/structs/structs.go#L10912C19-L10914)).
Create a policy with
```sh
nomad acl policy apply -namespace default -job example example-job <(cat <<EOF
namespace "default" {
policy = "write"
}
EOF
)
```
Create a job
```hcl
datacenters = ["casa"]
type = "batch"
priority = 10
periodic {
cron             = "*/15 * * * * *"
prohibit_overlap = true
}
group "example" {
task "example" {
driver = …
```
> allow periodic jobs to use workload identity ACL policies

- .changelog/16743.txt
- api/api.go
- api/error_unexpected_response.go
- api/error_unexpected_response_test.go
- api/go.mod
- api/go.sum
- api/internal/testutil/ports.go
- api/internal/testutil/server.go
- api/namespace_test.go
- api/operator.go
- api/variables.go
- go.mod
- go.sum
**Motivation**
Currently the majority of the Nomad Go API methods use the `api.Client`'s generic methods like query, putQuery, etc. which wrap the response with a `requireOK` to report unexpected status errors. However, this results in 404's also appearing as unexpected responses. Additionally, each function that handled unexpected response errors implemented their own error string creation (even though it was identical behavior) risking drift between implementations.
This PR seeks to do the following:
- **Create a structured error type** - In considering feedback to #16437, I wanted to be able to group the warnings by unexpected response error type, which would have depended on brittle string matches to implement. Providing an error that can be cast to a structured error would reduce the …
> [api] Return a shapely error for unexpected response

- .github/workflows/build.yml
- website/content/docs/upgrade/upgrade-specific.mdx
The 32-bit Intel builds (aka "386") are not tested and likely have bugs involving platform-sized integers when operated at any non-trivial scale. Remove these builds from the upcoming Nomad 1.6.0 and provide recommendations in the upgrade notes for those users who might have hobbyist boards running 32-bit ARM (this will primarily be the RaspberryPi Zero or older spins of the RaspPi).
Ref https://github.com/hashicorp/nomad-enterprise/issues/1053
cc @davemay99 as a heads up and @mikenomitch and @mmcquillan for approvals
**DO NOT BACKPORT!** :grinning:
> build: remove 386 builds for Nomad 1.6.0

- .changelog/17281.txt
The Vault SDK was updated by dependabot but I forgot to add a changelog entry for it. I'll cherry-pick this commit onto a backport PR as well.
> changelog entry for Vault SDK update

- website/content/docs/job-specification/check.mdx
A "readiness" check implies a failing healthcheck will not cause the
deployment of a service to stop - i.e. it is only used as a liveness
probe in the context of service discoverability.
Fix our docs example to reflect that a readiness check is created by
setting on_update to "ignore" (as opposed to "ignore_warnings").
> docs: fixup example of readiness check

- ui/app/components/job-status/failed-or-lost.hbs
- ui/app/components/job-status/failed-or-lost.js
- ui/app/components/job-status/latest-deployment.hbs
- ui/app/components/job-status/latest-deployment.js
- ui/app/components/job-status/panel/deploying.hbs
- ui/app/components/job-status/panel/steady.hbs
- ui/app/styles/components/job-status-panel.scss
- ui/tests/acceptance/job-status-panel-test.js
- ui/tests/integration/components/job-status/failed-or-lost-test.js
Adds a "Latest Deployment" cell to the steady-state job deployment panel when relevant. This will only ever occur for Service job types.
As a side-effect, and to make room, this condenses the "Restarted" and "Rescheduled" blocks into a single cell.
Resolves #17240
> [ui, deployments] Show a "Latest Deployment Status" cell within the Job Status panel on steady service jobs

- .changelog/17316.txt
- client/client.go
- nomad/node_endpoint.go
- nomad/node_endpoint_test.go
Add a nil check to `constructNodeServerInfoResponse` to manage an apparent race between deregister and client heartbeats.
Should fix #17310
> [core] nil check and error handling for client status in heartbeat responses

- nomad/node_endpoint_test.go
PR 17322 introduced a test that depends on a constructor missing in 1.4.x. This converts the test to instantiate the struct directly.
> Replace missing constructor in backported test

- .changelog/17319.txt
- ui/app/components/variable-form.hbs
- ui/app/components/variable-form.js
- ui/app/components/variable-form/related-entities.hbs
- ui/app/controllers/variables/variable/index.js
- Adds a "this variable will be accessible by all jobs" notification if saving to exactly `nomad/jobs`
- moves said notification, on new variables, to the top of the form because otherwise it separated the "Add More" button and made it non-obviously connected
- fixed a bug where a no-namespaces cluster would result in no duplicate path warnings firing
- delete button is disabled for the only remaining KV in a variable when editing
- fixed a bug where you would add an illegal character, delete the KV row, add a new blank one, and the illegal character warning was still present.
> [ui] A few variables-ui-related bugfixes

- .changelog/17349.txt
- client/fingerprint/consul.go
- client/fingerprint/consul_test.go
- command/agent/consul/self.go
Consul v1.13.8 was released with a [breaking change](https://github.com/hashicorp/consul/issues/17503) in the /v1/agent/self endpoint version where a line break was being returned.
This caused the Nomad finterprint to fail because `NewVersion` errors on parse.
This commit removes any extra space from the Consul version returned by the API.
Closes https://github.com/hashicorp/nomad/issues/17302
> client: fix Consul version finterprint

- .changelog/17346.txt
- command/job_restart.go
When monitoring the replacement allocation, if the `Allocations().Info()` request fails, the `alloc` variable is `nil`, so it should not be read.
Only backport to 1.5.x because that's when the `nomad job restart` was added.
Fixes #17329
> cli: fix panic on job restart

- .changelog/17348.txt
- command/deployment_status.go
A few errors during deployment monitoring were being ignored, preventing further investigation and understanding or problems such as #12062
> cli: output errors when monitoring deployment

- .changelog/17343.txt
- ui/app/styles/components/variables.scss
Resolves #17183 
pre-wrap-formatting will honour newline characters and still attempt to wrap at the appropriate point (in case of a particularly long variable with spaces, etc.)
> Observe newlines when displaying variables

- .changelog/17345.txt
- ui/app/templates/settings/tokens.hbs
Resolves #16901
Changes ACL Token/JWT input field to be of type "password", enabling password managers and triggering browsers to store it sensitively.
I considered adding a "show token" button but opted against it for keeping overhead low.
> [ui] Text type to password type input on profile sign-in page

- ui/mirage/factories/job.js
- ui/mirage/factories/node-pool.js
- ui/mirage/factories/node.js
- ui/mirage/models/node-pool.js
- ui/mirage/models/node.js
- ui/tests/acceptance/job-detail-test.js
- ui/tests/acceptance/job-status-panel-test.js
- ui/tests/acceptance/token-test.js
Resolves #17294 
This PR adds a new `node-pool` Mirage model and updates the `node` Mirage model that has a `node-pool` relationship. It also updates the factories for `node` to create an associated `node-pool` and the `job` factory to associate itself to a `node-pool`.
**Impact**
This PR impacts our Mirage server and the fake calls we make.
**Side Effect**
This PR runs prettier on `mirage/factories/node` so just pay attention to the `afterCreate` hook changes.
**Next Steps**
This is the final prerequisite we need to start developing against the real API. We'll start PRs that impact the view layer next.
> chore: setup mirage models + factory hooks

- ui/app/models/job.js
- ui/app/models/node-pool.js
- ui/app/models/node.js
- ui/mirage/factories/job.js
- ui/mirage/factories/node-pool.js
- ui/mirage/factories/node.js
- ui/mirage/models/node-pool.js
- ui/mirage/models/node.js
- ui/tests/acceptance/job-detail-test.js
- ui/tests/acceptance/job-status-panel-test.js
- ui/tests/acceptance/token-test.js
- ui/tests/unit/models/node-test.js
Resolves #17293 
This PR adds a relationship between the Node and NodePool models. In addition, The Job model now has an @attr('string') property called nodePool.
The nodePool property on the Node model is used to store the name of the NodePool that the job is associated with. The nodes property on the NodePool model is used to store a list of the Job models that are associated with the NodePool.
This change was made to allow users to easily associate jobs with node pools. For example, a user could create a job and specify the name of the node pool that the job should be run on.
**Testing**
The changes in this PR have been tested using the following tests:
`ui/tests/unit/models/node-pool-test.js`
The tests have been written to ensure that the Node and NodePool models can be associated …
> refact:  update models for relationship

- .changelog/17354.txt
- client/allocrunner/alloc_runner.go
- client/allocrunner/alloc_runner_test.go
- client/allocrunner/interfaces/runner.go
- client/client.go
- client/client_interface_test.go
- client/client_test.go
- client/structs/enum.go
The allocrunner sends several updates to the server during the early lifecycle of an allocation and its tasks. Clients batch-up allocation updates every 200ms, but experiments like the [C2M challenge](https://www.hashicorp.com/blog/hashicorp-nomad-meets-the-2-million-container-challenge) have shown that even with this batching, servers can be overwhelmed with client updates during high volume deployments. Benchmarking done in #9451 has shown that client updates can easily represent ~70% of all Nomad Raft traffic.
Each allocation sends many updates during its lifetime, but only those that change the `ClientStatus` field are critical for progressing a deployment or kicking off a reschedule to recover from failures.
Add a priority to the client allocation sync and update the `syncTicker` …
> prioritized client updates

- ui/app/templates/clients/client/index.hbs
- ui/app/templates/components/job-page/parts/stats-box.hbs
Resolves #17289 and #17291 
This PR adds the associated Node Pool name to the Job and Client Detail Overview pages.
> ui:  node pools - add node pool to overview pages

- acl/acl.go
- nomad/search_endpoint.go
- nomad/search_endpoint_test.go
- nomad/structs/search.go
- website/content/api-docs/search.mdx
Add node pools support to the fuzzy and prefix search endpoints. 
These endpoints are used by the CLI for prefix match and shell tab-completion.
Doc preview:
https://nomad-git-f-node-pools-search-hashicorp.vercel.app/nomad/api-docs/search
> node pool: add search support

- .changelog/17342.txt
- nomad/structs/structs.go
- nomad/structs/structs_test.go
Fixes the validation for `kill_timeout` when `progress_deadline` is set to 0, which is a special case that should not be validated.
Closes #17335
> core: fix kill_timeout validation when progress_deadline is 0

- nomad/structs/structs.go
- nomad/structs/structs_test.go
Move all validations related to task fields to `Task.Validate()`. Prior to this, some task validations were being done inside `TaskGroup.Validate()` because they required access to some group values.
But similarly to how `TaskGroup.Validate()` takes the job as parameter, it's fair to expect the task to receive its group.
Note: this could be considered an alternative implementation for #17342, but we could also just merge https://github.com/hashicorp/nomad/commit/a5f3e0d34a4765d3c095f9b3108f6d80ca7f0287, or nothing at all if we don't think this is worth it 😄
> Refactor task validation

- .changelog/17334.txt
- api/services.go
- command/agent/consul/service_client.go
- command/agent/consul/unit_test.go
- command/agent/job_endpoint.go
- nomad/structs/diff_test.go
- nomad/structs/services.go
- nomad/structs/services_test.go
- ui/stories/components/diff-viewer.stories.js
- website/content/docs/job-specification/check.mdx
The `tls_server_name` field was added to Consul in hashicorp/consul#9475. This PR adds support for the same field in Nomad `service -> check` stanzas.
There are two common situations where specifying this field can be beneficial:
1. When the check address is an IP, `tls_server_name` can be specified for SNI. Note: setting `tls_server_name` will also override the hostname used to verify the certificate presented by the server being checked.
2. When the hostname in the check address won't be present in the SAN (Subject Alternative Name) field of the certificate presented by the server being checked. Note: setting `tls_server_name` will also override the hostname used for SNI.
The latter of these is especially important given that today you would have to specify `tls_skip_verify` which omits …
> check: Add support for Consul field tls_server_name

- ui/mirage/factories/job.js
- ui/tests/acceptance/job-detail-test.js
- ui/tests/helpers/module-for-job.js
UI-specific tests that were pulled from https://github.com/hashicorp/nomad/pull/17103 — they were necessitated because GHA appears to run our acceptance tests under a different order / set of circumstances than Circle.
This hardens the tests a bit and gives them some sensible defaults (like "Batch jobs do not have deployments", etc.)
> UI-specific GHA test changes re-implemented
