hashicorp/nomad

command/alloc_status.go

Found typo and quickly changed it

Changed typo in documentation

---

scripts/build.sh

Not that is critical, but see: [google's Shell Style Guide](https://google-styleguide.googlecode.com/svn/trunk/shell.xml?showone=Test,_%5B_and_%5B%5B#Test,_%5B_and_%5B%5B)

use 'idiomatic' bash

---

website/source/intro/getting-started/install.html.md

Save 10 seconds for the next person who copies this link and sends it straight to curl.

Link to raw Vagrantfile instead

---

command/meta.go
website/source/docs/drivers/docker.html.md

`when` just did not seem to fit here

fixes some typos

---

website/Vagrantfile
website/source/docs/agent/config.html.md

Update the docs with new agent commands, alphabetize them and fix the anchor links.

Fix anchor links and add new agent cli commands

---

website/source/docs/drivers/docker.html.md

net is not a valid network mode

Fix network mode

---

website/source/docs/http/job.html.md

Fix website typo in jobs.html.md

---

api/compose_test.go
api/tasks_test.go
client/executor/exec_linux.go
website/source/docs/jobspec/index.html.md

Fixes https://github.com/hashicorp/nomad/issues/220

Switch from using cgroups BlkioThrottleReadIOpsDevice to BlkioWeight

---

client/fingerprint/memory.go
command/agent_info_test.go
helper/discover/discover.go
nomad/plan_apply.go
scheduler/generic_sched.go

Mostly just simple string formatting issues.

Fix vet warnings

---

website/source/intro/getting-started/jobs.html.md

overtime -> over time
add comma
change -> to change

minor grammar fixes

---

website/source/intro/getting-started/cluster.html.md

have it elect as a leader -> have it elected as a leader
Not completely sure if this is correct (maybe “have it elect itself as a leader” is better?)

rewording suggestion

---

client/driver/rkt.go
client/driver/rkt_test.go
website/source/docs/drivers/rkt.html.md

* Logs stderr and stdout
* Decoupled exec command from arguments
* Pass environment variables to container
* Evaluate nomad variables in user arguments.

Rkt Driver Enhancements

---

client/driver/docker.go

Makes the driver error out when a wrong or un-supported
network_mode is used

Do not default to a network mode

---

website/source/docs/drivers/docker.html.md
website/source/docs/drivers/qemu.html.md

- Clarify container network mode
- Format qemu driver version

Some docs update

---

demo/vagrant/Vagrantfile

I'm probably not the only one that reached for `vim` during the getting started guide. Super minor but might save some apt-get'ing.

Install vim in demos

---

client/driver/docker.go

I missed that in the last commit

Run gofmt on the docker driver

---

client/driver/java.go
website/source/docs/drivers/java.html.md

Support passing options to the JVM in java driver

---

client/driver/java.go
client/driver/java_test.go

Actually append jvm opts to the CLI

---

client/driver/environment/vars.go
client/driver/environment/vars_test.go
client/driver/rkt.go
website/source/docs/drivers/rkt.html.md
website/source/docs/jobspec/environment.html.md

Document that Rkt doesn't support task directory mounting and track the issue.

Document that Rkt doesn't support task directory mounting

---

website/source/docs/internals/scheduling.html.md
website/source/docs/jobspec/index.html.md

https://github.com/hashicorp/nomad/pull/287

Update doc with System Scheduler from PR #287

---

api/jobs.go

Added the UpdataStrategy struct to the api/jobs struct

---

scheduler/util_test.go

Make go vet happy

---

command/node_status.go

Adds node attributes to the node-status command when a single
node ID is passed
Closes #303

Show node attribute in node-status

---

website/source/docs/internals/architecture.html.md

To make the text be in the same order of the menu:

list Getting in depth in same order as menu

---

website/source/docs/agent/config.html.md

Provide a pointer to #183 regarding Nomad/Atlas integration.

Update agent config docs on Atlas integration

---

client/fingerprint/network_test.go
client/fingerprint/network_unix.go

* Using Go's stdlib APIs to fingerprint network devices and find IPv4 addresses

Network fingerprint refactor

---

client/alloc_runner.go
client/restarts.go
client/restarts_test.go
client/task_runner.go
client/task_runner_test.go

This PR implements the logic of Client Side restarts in the Task Runner

Part 2 - Client side restarts

---

client/driver/args/args.go
client/driver/executor/exec_basic.go
client/driver/executor/exec_linux.go
client/driver/qemu.go
client/driver/qemu_test.go

Qemu Driver uses Executor

---

client/driver/executor/exec_basic.go
client/driver/raw_exec.go
client/driver/raw_exec_test.go

RawExec driver uses exec_basic

RawExec driver uses exec_basic

---

client/driver/executor/exec_basic.go
client/driver/executor/exec_linux.go
client/driver/executor/test_harness.go
client/driver/spawn/spawn.go
client/driver/spawn/spawn_posix.go
client/driver/spawn/spawn_test.go

Add Valid command to spawner and make executors check when opening

Add Valid command to spawner and make executors check when opening

---

client/driver/docker.go
client/driver/driver_test.go

- Ports allocated to a container are exposed
Fixes #212

Expose provisioned ports for docker containers

---

client/driver/docker.go
client/driver/docker_test.go
website/source/docs/drivers/docker.html.md

Fixes merge conflicts in #414. Thanks @fernandezvara!

Support labels for docker containers

---

client/config/config.go
client/driver/docker.go

- Improved a lot of logging statements to have more information and better phrasing
- DRY up some code in network configuration
- Add config.ReadBool and config.ReadBoolDefault

Cleanup docker driver

---

client/driver/qemu.go
client/driver/qemu_test.go

Qemu driver takes a port_map to configure host to guest port forwarding

Qemu driver takes a port_map to configure host to guest port forwarding

---

client/driver/docker.go
client/driver/docker_test.go
website/source/docs/drivers/docker.html.md

Was a comma-separated string before

Change docker DNS configuration to lists

---

client/alloc_runner_test.go
client/client_test.go
client/driver/args/args.go
client/driver/args/args_test.go
client/driver/docker.go
client/driver/docker_test.go
client/driver/exec.go
client/driver/exec_test.go
client/driver/executor/exec_basic.go
client/driver/executor/exec_linux.go
client/driver/executor/test_harness_test.go
client/driver/java.go
client/driver/java_test.go
client/driver/raw_exec.go
client/driver/raw_exec_test.go
client/driver/rkt.go
client/driver/rkt_test.go
client/task_runner_test.go
command/run.go
nomad/fsm.go
nomad/mock/mock.go
nomad/rpc.go
nomad/structs/structs.go
nomad/timetable_test.go
website/source/docs/drivers/docker.html.md
website/source/docs/drivers/exec.html.md
website/source/docs/drivers/java.html.md
website/source/docs/drivers/qemu.html.md
website/source/docs/drivers/raw_exec.html.md
website/source/docs/drivers/rkt.html.md

Make drivers take args as a list rather than as a string

---

client/driver/environment/vars.go
client/driver/environment/vars_test.go

Handle additional edge cases when parsing environment variables.

---

client/driver/docker.go
client/driver/docker_test.go

Add ContainerID() method to get the containerID from a handle

---

nomad/eval_broker.go
nomad/eval_broker_test.go

Make a zero timeout for eval_broker.Dequeue() block

Make a zero timeout for eval_broker.Dequeue() block

---

client/consul.go
client/consul_test.go
jobspec/parse.go
jobspec/parse_test.go
nomad/structs/structs.go
nomad/structs/structs_test.go

And also adds the service ID to check hash.

This simplifies the logic of tracking services and checks

---

client/client.go
website/source/docs/agent/config.html.md
website/source/docs/jobspec/servicediscovery.html.md

- Matches documentation default value and clarifies config

Verify Consul SSL by default

---

nomad/plan_queue_test.go

On platforms where `time.Now` has low granularity (such as Windows), this test could easily add many plans to the queue with the same time stamp. This PR changes the test to only require each dequeued plan to have a time stamp >= to the previous one. It also adds occasional calls to `time.Sleep` when building the queue to make sure there is always at least one time step somewhere in the queue.

Fix test to tolerate multiple pending plans with the same time stamp.

---

api/nodes.go

Adds the `Meta` map for Node responses.

Add Meta field for Node struct

---

command/agent/config.go

As advertised by documentation.

Sets default syslog facility

---

client/consul.go

s/registerting/registering/g :dancers:

Fix minor spelling error

---

command/agent/config.go

Sort config files as documented.

---

scripts/deps.sh

Removed a broken dependency

---

client/restarts_test.go

Allow for low precision time.Now on Windows.

---

client/fingerprint/env_aws.go
client/fingerprint/env_gce.go

Not 100% sure what the behavior should be here. Please comment.
cc @c4milo

Handle non 200 codes while getting env metadata

---

client/driver/executor/exec_linux.go

Hi @diptanu,
Per #636, here is the PR.

linux/exec: add /usr/share to ChrootEnv

---

client/driver/rkt.go

rkt docs herer https://coreos.com/rkt/docs/latest/subcommands/run.html#mounting-volumes

Mount task and alloc dirs in the rkt driver

---

client/driver/qemu.go

Adding a , between args to netdav

---

website/source/docs/jobspec/index.html.md

Improved update docs

---

api/jobs.go
command/eval_monitor.go
command/monitor.go
command/monitor_test.go
command/run.go
command/status.go
command/stop.go
nomad/periodic.go
nomad/periodic_test.go
nomad/structs/structs.go

This PR improves the output of `nomad status` when given a periodic job.
Fixes #644

Improve nomad status on periodic jobs

---

website/source/docs/commands/index.html.md.erb

changed agent-status to agent-info as agent-status does not exist

changed agent-status to agent-info as agent-status does not exist

---

.travis.yml
client/alloc_runner_test.go
client/allocdir/alloc_dir.go
client/allocdir/alloc_dir_test.go
client/client_test.go
client/driver/docker.go
client/driver/docker_test.go
client/driver/env/env.go
client/driver/exec_test.go
client/driver/executor/exec_basic.go
client/driver/executor/exec_linux.go
client/driver/executor/test_harness_test.go
client/driver/java_test.go
client/driver/raw_exec_test.go
client/driver/rkt_test.go
client/restarts.go
client/task_runner_test.go
helper/testtask/testtask.go
scripts/test.sh
testutil/wait.go

There are a variety of tests that were failing. This PR aims to fix them all and then enable root under Travis
Fixes #666

Fix failing tests running under root

---

website/source/intro/vs/kubernetes.html.md

This is an update from the Twitter conversation here: https://twitter.com/asynchio/status/690357014925549568
The changes made should both be based on fact from everyone involved.

Update K8S vs from Twitter

---

client/fingerprint/consul.go
client/fingerprint/consul_test.go
client/fingerprint/env_aws.go
client/fingerprint/env_aws_test.go
client/fingerprint/env_gce.go
client/fingerprint/env_gce_test.go
client/fingerprint/network.go
client/fingerprint/network_test.go
client/fingerprint/storage.go
client/fingerprint/storage_test.go
nomad/node_endpoint.go
nomad/node_endpoint_test.go
nomad/structs/node_class.go
nomad/structs/node_class_test.go
nomad/structs/structs.go

This PR adds computed node classes.
@mitchellh @armon

Computed node class

---

client/driver/rkt.go

Update Rkt regex to determine version

---

scheduler/generic_sched.go
scheduler/generic_sched_test.go

This PR makes it so that batch allocations that are dead don't get replaced unless they have failed when run through the scheduler.

Only replace batch allocations that have failed

---

.travis.yml
Makefile

Travis runs docker 1.7 which is pretty old. We should test with more recent docker.
Lifted from https://github.com/fsouza/go-dockerclient

Update docker before testing

---

client/driver/exec.go
client/driver/exec_test.go
client/driver/java.go
client/driver/qemu.go
client/driver/raw_exec.go
client/driver/raw_exec_test.go
website/source/docs/drivers/exec.html.md
website/source/docs/drivers/raw_exec.html.md

Extract artifacts to the root of the task, not in the local directory

Extract artifacts to the root of the task, not in the local directory

---

website/source/intro/getting-started/cluster.html.md
website/source/intro/getting-started/install.html.md
website/source/intro/getting-started/jobs.html.md
website/source/intro/getting-started/running.html.md

Update getting started with short ids

---

client/driver/env/env.go
website/source/docs/drivers/docker.html.md
website/source/docs/drivers/exec.html.md
website/source/docs/drivers/java.html.md
website/source/docs/drivers/raw_exec.html.md
website/source/docs/drivers/rkt.html.md
website/source/docs/jobspec/index.html.md
website/source/docs/jobspec/interpreted.html.md
website/source/docs/jobspec/networking.html.md
website/source/intro/getting-started/jobs.html.md
website/source/layouts/docs.erb

Documentation for interpreted variables

---

website/source/docs/http/job.html.md

WIP - https://github.com/zanella/nomad-api

Trailing comma typos

---

README.md

* Make sure to clone first and bootstrap second

Update Readme for local dev.

---

command/agent/agent.go
command/agent/agent_test.go

Construct http addr for clients properly

---

nomad/leader.go

This frees up more CPU for the evaluation broker and plan queue

Disable half the workers, freeing half the CPUs, on the leader

---

nomad/fsm.go
nomad/fsm_test.go
nomad/rpc.go
nomad/structs/structs.go
nomad/structs/structs_test.go

This PR LZW compresses raft entries in an effort to reduce Raft latency.

LZW compress raft entries

---

nomad/plan_apply.go
nomad/plan_apply_test.go

nomad: cleanup handling of refresh index

---

client/consul_test.go
client/util_test.go

The util tests can definitely be run in parallel

Run a bunch of tests in parallel

---

client/driver/driver.go
client/driver/driver_test.go
client/driver/env/env.go
client/task_runner.go
website/source/docs/jobspec/environment.html.md
website/source/docs/jobspec/interpreted.html.md

Add Alloc ID/Name and Task Name to environment variables

---

client/driver/rkt_test.go
nomad/eval_broker.go
nomad/plan_apply.go

Fix bug introduced with paused nack timers

---

command/agent/agent.go
command/agent/agent_test.go
command/agent/config.go
command/agent/config_test.go

This PR allows the operator to configure the grace period for client heartbeats.

agent: Configurable heartbeat grace

---

command/agent/fs_endpoint.go
command/agent/http.go

Guard client/ api to ensure the client is running

---

client/driver/driver.go
client/driver/env/env.go
nomad/structs/structs.go
nomad/structs/structs_test.go
website/source/docs/jobspec/environment.html.md
website/source/docs/jobspec/interpreted.html.md

client: Add allocation index environment variable
Fixes #895

Add allocation index environment variable

---

client/driver/executor/executor_linux.go

executor: add /run/resolvconf to chroot

executor: add /run/resolvconf to chroot

---

website/source/docs/drivers/docker.html.md

Typo in docker.html.md

---

website/Gemfile.lock
website/source/assets/stylesheets/_announcement-bnr.scss
website/source/assets/stylesheets/application.scss
website/source/layouts/_announcement-bnr.erb
website/source/layouts/_header.erb
website/source/layouts/_meta.erb

@pearkes added annoucement banner

announcement bnr

---

api/status.go
command/server_members.go
nomad/server.go

cli: server-members displays leader per region

cli: server-members displays leader per region

---

client/driver/docker.go
client/driver/docker_test.go
client/driver/exec.go
client/driver/executor/executor.go
client/driver/executor/executor_linux.go
client/driver/executor/executor_posix.go
client/driver/executor/executor_test.go
client/driver/executor/executor_windows.go
client/driver/executor_plugin.go
client/driver/java.go
client/driver/logging/syslog_server_windows.go
client/driver/qemu.go
client/driver/raw_exec.go
client/driver/rkt.go
client/driver/structs/structs.go

Unified executor

---

website/source/docs/jobspec/interpreted.html.md

Adds a couple examples and aligns variable formatting to others in the table.

Minor updates to Interpreted Variables docs

---

Vagrantfile

Setup rkt in vagrant

---

command/node_status.go
command/node_status_test.go

cli: Less verbose output and show node's total resources

cli: Less verbose output and show node's total resources

---

website/source/docs/jobspec/index.html.md

Document operator equality

---

website/source/docs/drivers/docker.html.md
website/source/docs/drivers/raw_exec.html.md

Clarify client options in drivers
Fixes https://github.com/hashicorp/nomad/issues/733

Clarify client options in drivers

---

website/source/docs/jobspec/index.html.md

Pulled this info from https://github.com/hashicorp/nomad/blob/master/nomad/structs/structs.go#L623-L630 and https://github.com/hashicorp/nomad/blob/master/nomad/structs/structs.go#L769.

wbsite: document default resources

---

api/tasks.go
client/config/config.go
client/task_runner.go
client/task_runner_test.go
command/alloc_status.go
nomad/structs/structs.go
website/source/docs/agent/config.html.md

This PR allows an operator to specify users that a task can not use. We provide sane defaults. 
Small extension to #950

Operator specifiable blacklist for task's using certain users

---

command/node_drain.go
command/stop.go

Fixes the logic for drain and stop command's confirmation prompt

---

api/fs.go
command/agent/fs_endpoint.go
command/fs_cat.go

Added the /fs/cat/ api

---

client/driver/executor/executor.go
client/driver/executor/executor_test.go
helper/args/args.go
nomad/mock/mock.go
website/source/docs/jobspec/servicediscovery.html.md

cc/ @dadgar @mitchellh 
Only interpolating service tags currently.

Interpolating service and checks

---

client/driver/executor/executor_linux.go
client/driver/java.go

This PR chroots the full /usr/ dir

Chroot all of /usr/

---

command/status.go

Showing the status of the first job when it's prefixed matched

---

client/client.go
client/driver/docker.go
client/driver/exec.go
client/driver/java.go
client/driver/qemu.go
client/driver/raw_exec.go
client/driver/rkt.go
nomad/fsm.go
nomad/fsm_test.go
nomad/structs/node_class_test.go

Enabling Periodic fingerprinters for drivers

---

client/allocdir/alloc_dir.go

Seeking to offset while doing readAt with non-zero offset

---

client/driver/docker.go

Added the tty flag to the driverconfig

---

command/agent/agent.go
command/agent/config.go
command/agent/config_parse.go
website/source/docs/agent/config.html.md

cc/ @dadgar 
removing the interfaces block.

removing interfaces from config

---

nomad/core_sched.go
nomad/core_sched_test.go
nomad/structs/funcs_test.go
nomad/structs/structs.go
scheduler/generic_sched.go

This rolls back a previous change to remove this.

add client status to allocation terminal status

---

website/packer.json
website/scripts/deploy.sh

Update website push script to fix metadata

---

website/Gemfile.lock
website/source/docs/jobspec/index.html.md
website/source/docs/jobspec/json.html.md

@diptanu still need services (w/ scripts) in the JSON.  I think we shouldn't have the object definition in a separate page.

Improved JSON docs

---

client/fingerprint/env_gce.go

Just removes inconsistent log formatting

Make logging more consistent

---

client/driver/executor/executor_linux.go

Potentially addresses https://github.com/hashicorp/nomad/issues/1018

Remove systemd cgroup manager

---

website/source/docs/agent/config.html.md

Fixes https://github.com/hashicorp/nomad/issues/953

Added docs for http advertise addr

---

nomad/node_endpoint.go

Always trigger evals on drain update

---

website/source/docs/faq.html.md

Added a missing "is" to complete the last sentence.

Minor grammar fix.

---

client/driver/env/env.go

Fix splitting on equals to return maximum of two strings

---

nomad/mock/mock.go
scheduler/util.go
scheduler/util_test.go

Task is not eligible for update if User, Meta, or Resources change

---

nomad/structs/structs.go
nomad/structs/structs_test.go

Ensuring service names are unique

---

nomad/structs/structs.go
nomad/structs/structs_test.go

Ensuring check names are unique

---

nomad/structs/network.go
scheduler/util.go
scheduler/util_test.go

Check if network asks have changed when checking task updates

---

helper/flatmap/flatmap.go
helper/flatmap/flatmap_test.go
nomad/structs/diff.go
nomad/structs/diff_test.go

Job diff with simple diff objects

Job Diff structure

---

website/source/docs/internals/scheduling.html.md

Typo in docs: beings -> begins

---

dist/systemd/nomad.service

Hi,
I added ```systemctl reload nomad``` to the systemd unit file.

Add reload command to systemd unit file

---

client/driver/executor/executor.go
client/task_runner.go
command/alloc_status.go
nomad/eval_endpoint_test.go

fix wait result being nil and some panics in the cli

---

client/driver/docker.go

Using a different client for collecting stats and waiting on containers

---

command/meta.go
command/node_status.go
demo/vagrant/client1.hcl
website/helpers/command_helpers.rb

This PR improves the node-status commands output and also displays allocation usage separately from host usage.
Requires a rebase off of  #1260

Improve node-status command

---

scheduler/system_sched.go

This got lost in a refactor that occurred on the generic scheduler but not the system one.
Fixes https://github.com/hashicorp/nomad/issues/1281

Track failed allocations properly in System scheduler

---

api/jobs.go
command/helpers.go
command/plan.go
command/run.go
command/status.go
nomad/job_endpoint.go
nomad/structs/structs.go

Plan displays launch time of periodic jobs

---

website/source/docs/drivers/docker.html.md

Fixes https://github.com/hashicorp/nomad/issues/1292

Correct the dynamic port specification in Docker docs

---

client/client_test.go

Pointy-hat: sean-
I'm positive I've done this before.

Fix tests for NewServer() in client mode.

---

command/plan.go
website/source/docs/commands/plan.html.md.erb
website/source/docs/commands/run.html.md.erb
website/source/layouts/docs.erb

Adds documentation for `nomad plan`

plan cli docs

---

command/agent/consul/syncer.go
nomad/structs/config/consul.go

Said differently, centralize the creation of consul's client config
in one place and use it everywhere.

Teach config.ConsulConfig how to construct a consulapi TLS client.

---

client/driver/logging/syslog_parser_unix.go

Great catch by @a86c6f7964
Fixes #1198

Make line copy to avoid being overriden by subsequent scans

---

client/client.go
nomad/server.go

Fix the shuffling of remote datacenters

---

client/fingerprint/cpu.go
client/fingerprint/host.go
helper/stats/cpu.go

Fixes an issue where most nodes get their own computed node class.

Floor CPU MHz and total compute and mark hostname as unique

---

command/agent/command.go

Fixed parsing of consul agent service names

---

client/task_runner.go

Set running when restoring

---

command/validate.go
website/source/docs/commands/validate.html.md.erb

Document validate works on HCL only

---

website/source/docs/upgrade/upgrade-specific.html.md

Added an upgrade guide for the 0.4.0 release

---

api/tasks.go
command/agent/consul/syncer.go
command/agent/consul/syncer_test.go
jobspec/parse.go
jobspec/parse_test.go
jobspec/test-fixtures/basic.hcl
nomad/structs/diff_test.go
nomad/structs/structs.go

Allowing ports to be overriden in check definitions

---

nomad/structs/structs.go
nomad/structs/structs_test.go

Fixed the validation logic for check timeout and interval

---

client/client.go
client/driver/exec.go
client/driver/executor/executor.go
client/driver/executor/executor_basic.go
client/driver/executor/executor_linux.go
client/driver/executor/executor_linux_test.go
client/driver/executor/executor_test.go
client/driver/executor/resource_container_default.go
client/driver/executor/resource_container_linux.go
client/driver/java.go
client/driver/structs/structs.go
client/driver/structs/structs_default.go
client/driver/structs/structs_linux.go
client/fingerprint/fingerprint.go
client/fingerprint/fingerprint_default.go
client/fingerprint/fingerprint_linux.go

Pushdown Cgroup-specific items into a platform specific `resourceContainer` type.

Resource isolation cleanup

---

client/driver/logging/syslog_parser_unix.go
client/driver/logging/syslog_parser_unix_test.go

Support docker syslog unixformat and defaultformat

---

GNUmakefile
client/driver/rkt_test.go

Skipping travis tests and not installing rkt on travis

---

client/restarts.go
client/restarts_test.go

do not fail for multiple startup failures, delay instead

---

api/fs.go
api/fs_test.go
command/agent/fs_endpoint.go
command/fs.go
command/helpers.go
command/helpers_test.go

This PR implements `tail -n <lines>` behavior.

Implement tail -n

---

command/agent/agent.go
command/agent/util.go

Fixes #1318 by making sure it uses the correct syntax for IPv6 addresses. 
Adds 2 helper functions

Fix IPv6 advertise addresses

---

api/nodes.go

Added the status updated at timestamp

---

nomad/state/state_store.go
nomad/structs/structs.go
scheduler/generic_sched_test.go

Mark desired state of allocations as stop when nodes goes down

---

scheduler/generic_sched.go
scheduler/generic_sched_test.go

filterCompleteAllocs filters replaced batch allocs

---

.gitignore

not sure how y'all feel about adding an ignore for the intellij iml file, but it would be nice to have as part of the ignore

add intellij iml as an ignored file

---

website/source/docs/jobspec/index.html.md
website/source/docs/jobspec/json.html.md

Job Spec: Link restart policy reference

---

jobspec/parse.go
jobspec/parse_test.go
jobspec/test-fixtures/basic.hcl
jobspec/test-fixtures/multi-vault.hcl
nomad/structs/structs.go

This PR introduces `vault` to the job spec and adds the appropriate structs

Vault job block

---

command/node_status.go

nomad node-status outputs `Disk 0 B/0 B`.
~~~
$ nomad node-status 11f9838e
...
Host Resource Utilization
CPU        Memory          Disk
1122/7396  4.1 GiB/15 GiB  0 B/0 B
~~~
This is one of the issues reported in https://github.com/hashicorp/nomad/issues/1374.
nomad client collects disk data from physical partitions only. So, `tmpfs` is not collected. Ref - 
[disk.Partitions(false)](https://github.com/hashicorp/nomad/blob/f847db6d5d704a3fa8b509fa62de2c0385082aa7/client/stats/host.go#L108) and [shirou/gopsutil's code](https://github.com/shirou/gopsutil/blob/4d0c402af66c78735c5ccf820dc2ca7de5e4ff08/disk/disk_linux.go#L214-L219)
This PR changes nomad to output only volume name instead of `0 B` when non-physical volume is used.
(e.g)
~~~
$ nomad node-status 11f9838e
...
Host Resource …

node-status outputs volumename instead of 0B utilization when non-physical volume is used

---

client/alloc_runner.go
client/client.go
client/task_runner.go

Fixed some error messages

---

website/source/layouts/docs.erb

Add link to fs

---

command/agent/consul/syncer.go
command/agent/consul/syncer_test.go

support query strings in checks

---

api/evaluations_test.go

fixing eval test in same way as #1541

allow multiple evals check last one in test

---

client/client.go

If the client detects that a heartbeat has failed because it is not registered, reregister the client
Fixes #1590

Reregister Client on failed heartbeat

---

demo/vagrant/server.hcl
nomad/server.go
nomad/server_test.go
nomad/structs/config/vault.go
nomad/vault.go
nomad/vault_test.go
testutil/vault.go
vendor/github.com/hashicorp/vault/api/client.go
vendor/github.com/hashicorp/vault/api/sys_audit.go
vendor/github.com/hashicorp/vault/api/sys_auth.go
vendor/github.com/hashicorp/vault/api/sys_capabilities.go
vendor/github.com/hashicorp/vault/api/sys_lease.go
vendor/github.com/hashicorp/vault/api/sys_mounts.go
vendor/github.com/hashicorp/vault/api/sys_policy.go
vendor/github.com/hashicorp/vault/api/sys_rotate.go
vendor/vendor.json

This PR introduces:
* a test vault server
* A VaultClient interface
* An implementation of that interface that currently just contacts Vault, retrieves information about its token and then renews it
For review: @vishalnayak @diptanu

Server Vault Client that Renews Token

---

README.md

golang 1.7+ is required now

---

website/source/docs/cluster/bootstrapping.html.md

This just cost me about 30 minutes of my life...
/cc @dadgar

Fix bootstrapping docs error

---

GNUmakefile

Instlling the vault binary

---

website/source/docs/agent/config.html.md
website/source/docs/agent/telemetry.html.md

added docs for configuration of telemetry publishing nobs

---

api/tasks.go

initial status is missing from the the api

api/tasks.go: add check initial_status

---

website/source/docs/drivers/exec.html.md

Just a tiny spelling correction; slowly ramping up on Nomad.

small spelling correction

---

website/source/docs/drivers/exec.html.md
website/source/docs/drivers/java.html.md
website/source/docs/drivers/qemu.html.md
website/source/docs/drivers/raw_exec.html.md
website/source/docs/drivers/rkt.html.md

I'm not really this pedantic, I'm just working my way through the docs and wanted to contribute :-).

Web copy fixes

---

vendor/github.com/shirou/gopsutil/Makefile
vendor/github.com/shirou/gopsutil/README.rst
vendor/github.com/shirou/gopsutil/cpu/cpu_darwin.go
vendor/github.com/shirou/gopsutil/cpu/cpu_darwin_cgo.go
vendor/github.com/shirou/gopsutil/cpu/cpu_fallback.go
vendor/github.com/shirou/gopsutil/cpu/cpu_linux.go
vendor/github.com/shirou/gopsutil/disk/disk.go
vendor/github.com/shirou/gopsutil/disk/disk_fallback.go
vendor/github.com/shirou/gopsutil/disk/disk_freebsd.go
vendor/github.com/shirou/gopsutil/disk/disk_linux.go
vendor/github.com/shirou/gopsutil/disk/disk_unix.go
vendor/github.com/shirou/gopsutil/host/host.go
vendor/github.com/shirou/gopsutil/host/host_darwin.go
vendor/github.com/shirou/gopsutil/host/host_fallback.go
vendor/github.com/shirou/gopsutil/host/host_freebsd.go
vendor/github.com/shirou/gopsutil/host/host_linux.go
vendor/github.com/shirou/gopsutil/host/host_windows.go
vendor/github.com/shirou/gopsutil/internal/common/common.go
vendor/github.com/shirou/gopsutil/internal/common/common_linux.go
vendor/github.com/shirou/gopsutil/mem/mem.go
vendor/github.com/shirou/gopsutil/mem/mem_fallback.go
vendor/github.com/shirou/gopsutil/mem/mem_linux.go
vendor/github.com/shirou/gopsutil/net/net_fallback.go
vendor/github.com/shirou/gopsutil/process/process_darwin.go
vendor/github.com/shirou/gopsutil/process/process_fallback.go
vendor/github.com/shirou/gopsutil/process/process_linux.go
vendor/vendor.json

* resolve #1392
* pull in the fix for shirou/gopsutil/#249 which updates
the Linux driver for `cpu` to set `cpu.Mhz` to the maximum
clock-speed of the CPU, if that's available

Update vendor package shirou/gopsutil

---

website/source/intro/getting-started/jobs.html.md

Changed "your" to "you" to become "...what would happen if you ran the updated job:"

Fixed grammar

---

nomad/fsm.go
nomad/fsm_test.go
nomad/leader.go
nomad/leader_test.go
nomad/node_endpoint.go
nomad/node_endpoint_test.go
nomad/server.go
nomad/state/state_store.go
nomad/state/state_store_test.go
nomad/structs/structs.go
nomad/vault.go
nomad/vault_test.go
nomad/vault_testing.go
testutil/vault.go
vendor/gopkg.in/tomb.v2/LICENSE
vendor/gopkg.in/tomb.v2/README.md
vendor/gopkg.in/tomb.v2/tomb.go
vendor/vendor.json

@diptanu @vishalnayak for review

Token revocation and keeping only a single Vault client active among servers

---

client/alloc_runner.go
client/alloc_runner_test.go
client/allocdir/alloc_dir.go
client/allocdir/alloc_dir_darwin.go
client/allocdir/alloc_dir_freebsd.go
client/allocdir/alloc_dir_linux.go
client/allocdir/alloc_dir_test.go
client/allocdir/alloc_dir_testing.go
client/allocdir/alloc_dir_unix.go
client/allocdir/alloc_dir_windows.go
client/client.go
client/client_test.go
client/driver/docker.go
client/driver/driver.go
client/driver/driver_test.go
client/driver/env/env.go
client/driver/executor/executor_linux.go
client/driver/executor/executor_linux_test.go
client/driver/executor/executor_test.go
client/driver/rkt_test.go
client/secretdir/secret_dir.go
client/secretdir/secret_dir_test.go
client/secretdir/secret_dir_testing.go
client/secretdir/secret_dir_universal.go
client/secretdir/secret_dir_unix.go
client/secretdir/secret_dir_unix_test.go
client/task_runner_test.go

This PR introduces a `secrets/` directory and a `NOMAD_SECRET_DIR` environment variable

Introduce a Secret/ directory

---

website/source/docs/jobspec/index.html.md
website/source/docs/jobspec/json.html.md

Kill timeout default documentation

---

client/client.go

I'm definitely not getting the whole picture here, but for me it would certainly help just to see this in the logs.

Log adding of servers at INFO level

---

nomad/structs/structs.go

Change error message

---

nomad/structs/structs.go
scheduler/generic_sched.go
scheduler/generic_sched_test.go

cc/ @dadgar 
Modified the test, but the logic in the scheduler is same as previous PR.

Not setting a drained node as preferred node

---

client/allocdir/alloc_dir.go

Attempting to fix #1697 
cc/ @dadgar @schmichael

Closing files when files are removed

---

client/allocdir/alloc_dir_unix.go

Avoiding copying files if they are already present in chrootw

---

website/source/assets/stylesheets/_docs.scss
website/source/docs/drivers/docker.html.md
website/source/docs/drivers/exec.html.md
website/source/docs/drivers/java.html.md
website/source/docs/drivers/qemu.html.md
website/source/docs/drivers/raw_exec.html.md
website/source/docs/drivers/rkt.html.md
website/source/docs/jobspec/interpreted.html.md

Add more examples and clarify interpreted variables docs

---

website/source/docs/drivers/docker.html.md
website/source/docs/drivers/exec.html.md
website/source/docs/drivers/java.html.md
website/source/docs/drivers/qemu.html.md
website/source/docs/drivers/raw_exec.html.md
website/source/docs/drivers/rkt.html.md

There are a bunch of alignment issues this fixes.

Fix formatting and add more examples to driver docs

---

website/source/community.html.erb

I tried to copy-paste for how consul have done this :)

add nomad-ui to community page

---

command/agent/command.go

Skip SIGPIPE

---

client/driver/docker.go
client/driver/exec.go
client/driver/executor/checks_test.go
client/driver/executor/executor.go
client/driver/executor/executor_linux_test.go
client/driver/executor/executor_test.go
client/driver/executor/executor_unix.go
client/driver/executor_plugin.go
client/driver/java.go
client/driver/qemu.go
client/driver/raw_exec.go
client/driver/rkt.go

@evanphx Should fix the panic on your branch

Send Executor Ctx separately from Launch commands

---

client/task_runner.go
nomad/vault.go
nomad/vault_test.go

Validates that we have a proper Vault role.
@vishalnayak for extra 👀

Validate the Vault role being used

---

client/driver/rkt.go
client/driver/rkt_test.go
website/source/docs/drivers/rkt.html.md

Thanks to @nak3 for the original PR! #1616 
I rebased on master, fixed the test, and changed the docs to include an example that should Just Work for anyone with rkt installed.
@nak3 I'd love if you could verify my changes. I'm new to rkt networking and having to specify port names that are defined either in the image or on the system was a little confusing to me.

driver.rkt: support network configuration [waiting]

---

client/driver/docker.go
client/driver/docker_test.go

Expand env vars in docker volume paths

---

api/allocations.go
client/consul_template.go
client/consul_template_test.go
client/task_runner.go
nomad/node_endpoint.go
nomad/vault.go
vendor/github.com/hashicorp/consul-template/manager/runner.go
vendor/vendor.json

Small Stuff:
* Add logging when there is an error on the DeriveVaultToken endpoint
* Add Previous Allocation to api package
* Fix set active on vault client

Fixes to Consul-Template when file exists + other small stuff

---

command/init.go
website/source/docs/job-specification/artifact.html.md
website/source/docs/job-specification/constraint.html.md
website/source/docs/job-specification/env.html.md
website/source/docs/job-specification/group.html.md
website/source/docs/job-specification/job.html.md
website/source/docs/job-specification/logs.html.md
website/source/docs/job-specification/meta.html.md
website/source/docs/job-specification/network.html.md
website/source/docs/job-specification/periodic.html.md
website/source/docs/job-specification/resources.html.md
website/source/docs/job-specification/service.html.md
website/source/docs/job-specification/task.html.md
website/source/docs/job-specification/template.html.md
website/source/docs/job-specification/update.html.md
website/source/docs/job-specification/vault.html.md
website/source/docs/service-discovery/index.html.md
website/source/layouts/docs.erb

This fixes up a few small issues and adds new docs for `service`, `template`, and `vault`. Some of these docs are incomplete, but I would prefer to get these into master just so we can work in smaller chunks and get better feedback loops.

Add more documentation

---

command/init.go
website/source/docs/job-specification/ephemeral_disk.html.md
website/source/layouts/docs.erb

Update init command and add ephemeral_disk docs

---

website/source/docs/job-specification/restart.html.md

Clarify restart mode "fail"

---

nomad/structs/structs.go
nomad/structs/structs_test.go

Change the 0 timeout, interval validation to be more user friendly

---

vendor/github.com/hashicorp/hcl/Makefile
vendor/github.com/hashicorp/hcl/README.md
vendor/github.com/hashicorp/hcl/decoder.go
vendor/github.com/hashicorp/hcl/hcl/ast/ast.go
vendor/github.com/hashicorp/hcl/hcl/parser/parser.go
vendor/github.com/hashicorp/hcl/hcl/scanner/scanner.go
vendor/github.com/hashicorp/hcl/hcl/strconv/quote.go
vendor/github.com/hashicorp/hcl/hcl/token/token.go
vendor/github.com/hashicorp/hcl/json/parser/flatten.go
vendor/github.com/hashicorp/hcl/json/parser/parser.go
vendor/github.com/hashicorp/hcl/json/scanner/scanner.go
vendor/vendor.json

Update hcl to fix json parsing panic

---

website/source/docs/job-specification/ephemeral_disk.html.md
website/source/docs/job-specification/group.html.md

Document ephemeral_disk under group

---

website/source/docs/commands/stop.html.md.erb

Fixes to stop command

---

command/agent/agent.go

Disable http checks if TLS is enabled

---

client/driver/docker.go
client/driver/exec.go
client/driver/java.go
client/driver/qemu.go
client/driver/raw_exec.go
client/driver/rkt.go
client/task_runner.go
client/task_runner_test.go

Fix Docker container creation and task runner updating

---

client/consul_template.go
client/consul_template_test.go
website/source/docs/job-specification/template.html.md

Allow absolute paths for template sources

---

CHANGELOG.md
api/agent.go
command/agent/agent_endpoint.go
command/server_members.go
nomad/status_endpoint.go
nomad/structs/structs.go

For Nomad `v0.5.1`
Fixes #1382 #1761

Add an RPC endpoint for server members

---

client/driver/executor/executor.go

Interpolate all service/check fields

---

vendor/github.com/circonus-labs/circonusllhist/circonusllhist.go
vendor/vendor.json

revert to previous circonusllhist, a bug is causing an index out of range panic.

vendor circonus

---

website/source/docs/cluster/bootstrapping.html.md

For what I understand, regions are not meant to be nested (?)

Possible errata

---

client/client.go

Check for Ephemeral Disk being nil

---

website/source/docs/job-specification/service.html.md

Fix example for service using HTTPS check

---

website/source/docs/agent/encryption.html.md

Update encryption docs

---

website/source/docs/agent/configuration/telemetry.html.md

Fix typo in telemetry documentation.

---

client/driver/docker.go

Fixes https://github.com/hashicorp/nomad/issues/1662

Log when lookup in docker.auth.config fails

---

jobspec/parse.go

Fixes https://github.com/hashicorp/nomad/issues/1880

Improve parsing of job struct

---

CHANGELOG.md
client/driver/rkt.go

rkt: Support host and none dns options

---

client/driver/docker.go

This PR makes errors starting a container recoverable and tries to
optimistically handle 500 errors.

Make errors starting a container recoverable

---

website/source/docs/agent/configuration/client.html.md
website/source/docs/job-specification/constraint.html.md
website/source/docs/job-specification/job.html.md
website/source/docs/runtime/interpolation.html.md

Hey @dadgar 
I think this fixes the broken link. I'm still a bit uncertain about how to fix up the runtime/interpolation section.

Fix broken meta links

---

website/source/docs/runtime/interpolation.html.md

Linked to https://github.com/hashicorp/nomad/issues/2068

doc(interpolation): More explicit

---

website/source/docs/http/node.html.md

https://github.com/zanella/nomad-api/pull/4

Added example for the Reserved field

---

command/alloc_status.go

- Grammar change in usage info text
- Capitalization in stats retrieval error text
- Typo in outputTaskResources stats comment

Help text grammar updates in alloc_status

---

demo/vagrant/Vagrantfile
demo/vagrant/server.hcl
website/source/intro/getting-started/cluster.html.md

Fix demo vagrant server by making hostname resolve

---

website/source/docs/drivers/docker.html.md

Found, presumably, some guys name that had no reason for being in the documentation.

Updated docker doc to remove useless word

---

website/source/downloads.html.erb

Takes care of request #2 on Nomad [GH-2129](https://github.com/hashicorp/nomad/issues/2129)
This was largely just copy/pasted from the Terraform page.

Add link to CHANGELOG on the Nomad downloads.html page

---

client/client.go

Fixed how alloc lock is held

---

client/fingerprint/arch.go
client/fingerprint/arch_test.go

Fixed namespacing for the cpu arch

---

website/source/docs/vault-integration/index.html.md

Fix typo in docs

---

CHANGELOG.md
api/jobs.go
client/task_runner_test.go
command/agent/job_endpoint_test.go
command/job_dispatch.go
command/run.go
command/status.go
jobspec/parse.go
jobspec/parse_test.go
jobspec/test-fixtures/constructor.hcl
jobspec/test-fixtures/parameterized_job.hcl
nomad/job_endpoint.go
nomad/job_endpoint_test.go
nomad/state/state_store.go
nomad/structs/diff.go
nomad/structs/diff_test.go
nomad/structs/structs.go
nomad/structs/structs_test.go

```
ConstructorConfig -> ParameterizedJobConfig
Job.Constructor   -> Job.ParameterizedJob
```
And in the config:
```
constructor -> parameterized_job
```

Rename Constructor -> Parameterized Job

---

client/driver/env/env.go
client/driver/env/env_test.go
nomad/mock/mock.go
website/source/docs/runtime/environment.html.md

Setting the Addrs of sibling tasks in the env

---

website/source/docs/drivers/rkt.html.md

Expand rkt port_map docs since it confused me

---

client/client.go
helper/funcs.go
vendor/github.com/shirou/gopsutil/host/host_windows.go

https://github.com/shirou/gopsutil/pull/312

Add durable HostID generation support to Windows.

---

command/agent/config.go
command/agent/config_test.go

avoid a nil pointer dereference

---

Vagrantfile
build_linux_arm.go
scripts/build.sh

Had to use the hack from https://github.com/golang/go/issues/12443

Fix 32bit arm build

---

client/task_runner.go
client/task_runner_test.go

Fix upgrade path for created resources

---

command/agent/job_endpoint.go
nomad/job_endpoint.go

Fixes https://github.com/hashicorp/nomad/issues/2326

Deregistering non-existant job returns 404

---

command/job_dispatch.go

Tiny grammar fix

---

command/agent/job_endpoint.go
nomad/job_endpoint.go

Revert "Deregistering non-existant job returns 404"

---

website/source/assets/stylesheets/hashicorp-shared/_hashicorp-sidebar.scss
website/source/layouts/_sidebar.erb

Fix missing asset

---

command/alloc_status.go

Fixes https://github.com/hashicorp/nomad/issues/2401

Display Disk resources on CLI

---

nomad/structs/structs.go

The error message had an off-by-one error :)

Correct error message re length of service name

---

client/driver/env/env.go
helper/funcs.go
helper/funcs_test.go
website/source/docs/runtime/environment.html.md

Should bring us into conformance with IEEE Std 1003.1, 2004 Edition:
http://pubs.opengroup.org/onlinepubs/009695399/basedefs/xbd_chap08.html
1 alloc/op and ~80ns/op on my machine.

Round two of env var cleaning

---

website/source/docs/agent/configuration/telemetry.html.md

Added docs for the collection_interval option in the telemetry block

---

vendor/github.com/docker/docker/pkg/system/meminfo_solaris.go
vendor/vendor.json

This commit updates the `system` package of `docker/docker` - this is the last update required to build unmodified on Illumos.

deps: Update github.com/docker/docker/pkg/system

---

scheduler/generic_sched_test.go
scheduler/util.go

This PR skips adding an inplace update to a successfully terminal batch
job to the plan. This avoids extra data in the plan and avoids
triggering updates on all clients that have the terminal allocation.
This is matching behavior of the service scheduler.
/cc @armon for review

Skip inplace update on terminal batch allocation

---

client/driver/rkt.go
client/driver/rkt_test.go

Replace `_` with `-` in task names for rkt volumes

---

website/source/docs/job-specification/artifact.html.md

The correct list is like 5 lines up

Remove incorrect list of supported protocols

---

vendor/github.com/hashicorp/go-getter/decompress_tar.go
vendor/github.com/hashicorp/go-getter/decompress_tbz2.go
vendor/github.com/hashicorp/go-getter/decompress_testing.go
vendor/github.com/hashicorp/go-getter/decompress_tgz.go
vendor/github.com/hashicorp/go-getter/get_http.go
vendor/vendor.json

Fixes two issues:
* netrc not being honored
* tar files with files listed before their parent directories not being
properly untarred.

Vendor go-getter

---

website/source/docs/agent/encryption.html.md

Mention required cli config when using tls

---

website/source/intro/vs/kubernetes.html.md

According to http://blog.kubernetes.io/2017/03/scalability-updates-in-kubernetes-1.6.html

Update K8S max nodes

---

website/source/docs/commands/node-status.html.md.erb

- Add details about Desired Status and Client Status for #264

Docs: Update node-status page

---

website/source/docs/runtime/schedulers.html.md

- Update grammar
- Add link to Large-scale cluster management at Google with Borg

DOCS: Update Scheduler Types page

---

website/source/intro/getting-started/cluster.html.md

Sorry to bombard you with two PRs, I just saw that [the website](https://www.nomadproject.io/intro/getting-started/cluster.html) inlines that sample file and so people are most likely still gonna be confused.
Would be nice if it didn't just duplicate those, but a bigger problem than I'll solve today 😛 .

Update cluster tutorial to generate random client UUIDs

---

client/client.go

Fix perms to just set exec bit

---

client/driver/docker.go

This PR fixes an issue in which the value of the portmap could not be
interpolated.
Fixes https://github.com/hashicorp/nomad/issues/2680

Fix port map interpolation for docker

---

website/Gemfile
website/Gemfile.lock
website/Makefile
website/packer.json

update middleman version 25 to 26

---

website/source/docs/operating-a-job/update-strategies/handling-signals.html.md

This took me like two hours to find out why my clean up code wasn’t run. 🙈

Explain term signal behavior for Docker tasks

---

command/agent/agent.go
command/agent/config.go
command/agent/config_parse_test.go

Need to pointerify it to default to true since we can't tell false from
unset if it's not a pointer.

Fix no_host_uuid parsing

---

demo/vagrant/Vagrantfile
demo/vagrant/consul.service
scripts/install_consul.sh

Fixes #2206
Sneak a version bump to consul in as well

Start consul in getting started vagrant

---

vendor/github.com/Microsoft/go-winio/file.go
vendor/github.com/Microsoft/go-winio/pipe.go
vendor/github.com/Microsoft/go-winio/zsyscall_windows.go
vendor/vendor.json

* Microsoft/go-winio#53
* Microsoft/go-winio#54

Update go-winio to get some fixes

---

nomad/structs/structs.go
nomad/structs/structs_test.go

Validate job type

---

client/driver/docker_test.go
website/source/docs/drivers/docker.html.md

Also cleanup docker config opts docs

Test #2652 - Docker MAC Address option

---

website/source/docs/job-specification/update.html.md

This PR adds documentation and examples for the new update stanza.

Document new upgrade stanza

---

nomad/plan_apply.go
nomad/plan_apply_pool.go
nomad/plan_apply_test.go
nomad/server_test.go

This PR adds a log explaining why a plan gets rejected. Should help
debugging.

Log reason a plan gets rejected per node.

---

nomad/structs/structs.go
nomad/structs/structs_test.go

Fixes https://github.com/hashicorp/nomad/issues/2819

Warn instead of error when max_parallel is greater than count.

---

main.go
vendor/github.com/mitchellh/cli/autocomplete.go
vendor/github.com/mitchellh/cli/cli.go
vendor/github.com/mitchellh/cli/command.go
vendor/github.com/mitchellh/cli/command_mock.go
vendor/github.com/posener/complete/LICENSE.txt
vendor/github.com/posener/complete/args.go
vendor/github.com/posener/complete/cmd/cmd.go
vendor/github.com/posener/complete/cmd/install/bash.go
vendor/github.com/posener/complete/cmd/install/install.go
vendor/github.com/posener/complete/cmd/install/utils.go
vendor/github.com/posener/complete/cmd/install/zsh.go
vendor/github.com/posener/complete/command.go
vendor/github.com/posener/complete/complete.go
vendor/github.com/posener/complete/log.go
vendor/github.com/posener/complete/match/file.go
vendor/github.com/posener/complete/match/match.go
vendor/github.com/posener/complete/match/prefix.go
vendor/github.com/posener/complete/metalinter.json
vendor/github.com/posener/complete/predict.go
vendor/github.com/posener/complete/predict_files.go
vendor/github.com/posener/complete/predict_set.go
vendor/github.com/posener/complete/readme.md
vendor/github.com/posener/complete/test.sh
vendor/github.com/posener/complete/utils.go
vendor/vendor.json
website/source/docs/commands/index.html.md.erb

This PR adds command autocompletion to the CLI.

Add command autocompletion.

---

command/plan.go
command/run.go
command/validate.go

This PR makes run, validate and plan autocomplete their arg to
appropriate files.

Autocomplete files

---

command/agent/consul/unit_test.go
command/job_deployments.go

Implement -json for job deployments

---

nomad/deploymentwatcher/deployment_watcher.go
nomad/deploymentwatcher/deployments_watcher.go

This PR fixes the detection of a shutdown scenario and squelches the
error log.

Skip error log on shutdown

---

CHANGELOG.md
command/deployment_fail.go
command/deployment_pause.go
command/deployment_promote.go
command/deployment_resume.go
command/deployment_status.go
command/eval_status.go
command/fs.go
command/inspect.go
command/job_deployments.go
command/job_history.go
command/job_promote.go
command/job_promote_test.go
command/job_revert.go
command/logs.go
command/node_drain.go
command/node_status.go
command/status.go
command/status_test.go
command/stop.go
commands.go
main.go
nomad/deployment_endpoint.go
website/source/docs/job-specification/update.html.md

This PR:
* Fixes a variety of incorrect errors
* Adds a job promote command
* Cleans the UX of the `nomad deployment promote` command
* Adds documentation around blue/green and the canary parameter.

Variety of UX fixes

---

website/source/api/allocations.html.md
website/source/api/jobs.html.md
website/source/api/json-jobs.html.md
website/source/api/validate.html.md
website/source/docs/commands/alloc-status.html.md.erb

This PR updates the api documentation to reflect 0.6 HTTP API and the
JSON job specification as well.

Update API and JSON Job Documentation

---

main.go

This PR displays a custom help function that displays the flags to install and
uninstall bash autocompletions.
```
Usage: nomad [-version] [-help] [-autocomplete-(un)install] <command> [<args>]
Available commands are:
agent                 Runs a Nomad agent
agent-info            Display status information about the local agent
alloc-status          Display allocation status information and metadata
client-config         View or modify client configuration details
deployment            Interact with deployments
eval-status           Display evaluation status and placement failure reasons
fs                    Inspect the contents of an allocation directory
init                  Create an example job file
inspect               Inspect a submitted job
job                   Interact with …
```

Use a custom help output function

---

command/init.go
nomad/structs/structs.go
nomad/structs/structs_test.go

I kept it simple because the sample is getting so big. Let me know if I should expand it.

Mention env templates in nomad init

---

client/driver/logging/syslog_server.go

This PR fixes a leaking of the unix socket used when launching a syslog
server for the Docker driver.
Fixes https://github.com/hashicorp/nomad/issues/2844

Fix leaked plugin files for syslog server

---

website/source/api/json-jobs.html.md

This PR makes the example JSON job submitable via the HTTP API.

Example JSON is submitable

---

website/source/docs/job-specification/env.html.md
website/source/docs/operating-a-job/update-strategies/blue-green-and-canary-deployments.html.md

This PR fixes an incorrect placement of the update stanza in the task
and also links from the env stanza into an example of using the template
block to generate dynamic environment variables.

Small improvements to docs

---

vendor/github.com/hashicorp/raft/file_snapshot.go
vendor/github.com/hashicorp/raft/observer.go
vendor/github.com/hashicorp/raft/state.go
vendor/vendor.json

Related to #2963
Also pulls in some state file syncing improvements

Update raft to fix atomics alingment on 32bit

---

terraform/README.md

Easier copy-paste with filename highlighting.

Code highlighting

---

client/fingerprint/env_aws.go

Changed the keys map to reflect that.

AMI ID is potentially non-unique

---

website/source/api/index.html.md

Counting didn't keep up with new features. :)

Fix number of primary nouns in Nomad

---

website/source/docs/job-specification/index.html.md

"two-at-a-time" == `max_parallel = 2`

Match example update configuration to comment

---

command/alloc_status_test.go
command/eval_status.go
command/eval_status_test.go
command/job_status.go
command/job_status_test.go
command/node_status.go
command/node_status_test.go

Completes autocomplete functionality for status commands.

Add autocomplete for nodes, evals, and jobs

---

dev/README.md
dev/hooks/pre-push

This PR adds a place to share git hooks.

Add a shared git hooks directory

---

CHANGELOG.md
vendor/github.com/shirou/gopsutil/Makefile
vendor/github.com/shirou/gopsutil/disk/disk_fallback.go
vendor/github.com/shirou/gopsutil/host/host_darwin.go
vendor/github.com/shirou/gopsutil/host/host_fallback.go
vendor/github.com/shirou/gopsutil/host/host_freebsd.go
vendor/github.com/shirou/gopsutil/host/host_openbsd.go
vendor/github.com/shirou/gopsutil/host/host_solaris.go
vendor/github.com/shirou/gopsutil/host/host_windows.go
vendor/github.com/shirou/gopsutil/internal/common/common.go
vendor/github.com/shirou/gopsutil/internal/common/common_darwin.go
vendor/github.com/shirou/gopsutil/internal/common/common_freebsd.go
vendor/github.com/shirou/gopsutil/internal/common/common_linux.go
vendor/github.com/shirou/gopsutil/internal/common/common_openbsd.go
vendor/github.com/shirou/gopsutil/process/process_linux.go
vendor/vendor.json

Pulls in shirou/gopsutil#417
Fixes #3036

Update gopsutil to stop calling SetEnv

---

website/source/docs/drivers/docker.html.md

add docs for mount

---

website/source/api/deployments.html.md

Fixes https://github.com/hashicorp/nomad/issues/3079

Clarify deployment api docs

---

api/system.go

References https://www.nomadproject.io/api/system.html#reconcile-summaries

Add missing ReconcileSummaries API method

---

api/acl.go
api/acl_test.go
api/api.go
api/api_test.go
testutil/server.go

This PR adds the SDK methods for ACL Policies and ACL Tokens.

Adding SDK for ACL policies and tokens

---

website/source/api/jobs.html.md

Fixes https://github.com/hashicorp/nomad/issues/3092

Describe the all parameter when listing job allocs

---

client/stats/host.go

To reproduce logspam:
```
$ docker plugin install --grant-all-permissions vieux/sshfs
$ nomad agent -dev
...
2017/08/25 17:09:03.282868 [WARN] client: error fetching host disk usage stats for /var/lib/docker/plugins/a8b4a69b07e5180f828d19e1e9e102ccc0e26f9c9939eaef85357260c30b20a7/rootfs/mnt/volumes: permission denied
... repeats every collection period ...
```

Squelch logspam when unable to get disk usage stats

---

command/job_status.go
website/source/docs/commands/job.html.md.erb
website/source/docs/commands/job/status.html.md.erb
website/source/docs/commands/status.html.md.erb
website/source/layouts/docs.erb

This PR documents the new status and job status command.

Document new status command

---

CHANGELOG.md
api/fs.go

This PR fixes an assignment to a nil map in the api pkg related to
accessing logs and the filesystem of allocations.
Fixes https://github.com/hashicorp/nomad/issues/3115

Fix logs/fs commands

---

website/source/api/json-jobs.html.md
website/source/docs/job-specification/job.html.md

Fixes https://github.com/hashicorp/nomad/issues/3125

Clarify all_at_once parameter

---

CHANGELOG.md
vendor/github.com/posener/complete/cmd/install/zsh.go
vendor/vendor.json

This PR fixes autocompletion of paths that include folders on zsh.

Fix path completions on zsh

---

CHANGELOG.md
command/deployment_status.go

Fixes https://github.com/hashicorp/nomad/issues/3131

Sort task groups when displaying a deployment

---

nomad/server.go

Just a simple PR to help clarify the intent of peers.info. If my understanding is correct.

Update peers.info message for operators

---

CHANGELOG.md
vendor/github.com/hashicorp/consul-template/dependency/vault_read.go
vendor/github.com/hashicorp/consul-template/dependency/vault_token.go
vendor/github.com/hashicorp/consul-template/dependency/vault_write.go
vendor/vendor.json

Fixes https://github.com/hashicorp/nomad/issues/3133

Vendor consul-template

---

client/driver/docker.go

Fixes https://github.com/hashicorp/nomad/issues/3182

Fix docker user specified syslogging

---

client/driver/docker.go

Fixes https://github.com/hashicorp/nomad/issues/3181

Fix MemorySwappiness on Windows Docker

---

website/source/guides/acl.html.markdown

Now it's about ACLs instead of outage recovery.

Update the ACL guide description

---

website/source/docs/agent/telemetry.html.md

Adding missing <

---

client/driver/docker.go

Fixes #3228. More details in issue.

Fix incorrect docker stats

---

website/source/guides/nomad-metrics.html.md

Metrics guide fix

---

website/source/api/ui.html.md
website/source/layouts/api.erb

Rather dry, but maybe it will help someone?

Document each route in the UI for the API docs

---

api/fs.go
api/fs_test.go
command/agent/http.go
command/fs.go
command/logs.go
vendor/github.com/NYTimes/gziphandler/gzip.go
vendor/vendor.json

Fixes https://github.com/hashicorp/nomad/issues/3246

Fix gzip encoding

---

website/source/docs/agent/configuration/consul.html.md

Minor typo on consul.html.md

---

GNUmakefile
website/source/api/jobs.html.md
website/source/api/json-jobs.html.md
website/source/api/ui.html.md
website/source/docs/commands/job/dispatch.html.md.erb
website/source/docs/commands/job/history.html.md.erb
website/source/docs/commands/logs.html.md.erb
website/source/docs/job-specification/index.html.md
website/source/docs/operating-a-job/update-strategies/blue-green-and-canary-deployments.html.md
website/source/docs/operating-a-job/update-strategies/rolling-upgrades.html.md
website/source/guides/acl.html.markdown
website/source/guides/namespaces.html.markdown
website/source/guides/nomad-metrics.html.md
website/source/guides/securing-nomad.html.md
website/source/guides/sentinel-policy.html.markdown
website/source/guides/sentinel/job.html.md
website/source/index.html.erb

Fixes misspelled words and adds a step to `make check` to ensure no regressions.

Spell check website

---

ui/app/components/distribution-bar.js
ui/app/mixins/window-resizable.js
ui/app/styles/charts/distribution-bar.scss
ui/app/styles/core/nav.scss

- Spacer in the top-right menu are now aligned with text
- Allocation charts are vertically centered
- Allocation charts use the full width available

Fix style discrepancies in Firefox

---

nomad/job_endpoint.go
nomad/job_endpoint_test.go
website/source/api/jobs.html.md

This endpoint is not documented so this PR does not include ACL documentation.

Add ACL endpoint for Job Stable

---

ui/app/components/search-box.js
ui/app/initializers/app-token.js
ui/app/styles/components.scss
ui/app/styles/components/empty-message.scss
ui/app/templates/jobs/index.hbs
ui/app/templates/jobs/job/task-group.hbs
ui/app/templates/nodes/index.hbs
ui/app/templates/servers.hbs
ui/tests/acceptance/jobs-list-test.js
ui/tests/acceptance/nodes-list-test.js
ui/tests/acceptance/task-group-detail-test.js

Helpful messages for all the things.

UI empty states

---

command/agent/fs_endpoint.go
command/agent/fs_endpoint_test.go
website/source/api/client.html.md

ACL enforcement for the filesystem HTTP APIs on clients.

FS HTTP API ACL enforcement

---

nomad/system_endpoint.go
nomad/system_endpoint_test.go
website/source/api/system.html.md

Enforce ACL for System.GarbageCollect and System.ReconcileJobSummaries
RPC endpoints.

System ACL enforcement

---

CHANGELOG.md
api/jobs_test.go
api/tasks.go
vendor/github.com/hashicorp/consul-template/config/vault.go
vendor/github.com/hashicorp/consul-template/manager/runner.go
vendor/vendor.json
website/source/docs/job-specification/template.html.md

This PR:
* Changes the default vault_grace to match Vaults
* Vendors consul-template
Fixes https://github.com/hashicorp/nomad/issues/3197

Use Vault default grace

---

ui/app/routes/application.js
ui/app/templates/application.hbs
ui/tests/acceptance/application-errors-test.js

The joys of a single page application.

Allow users to escape error pages with the back button

---

client/client_test.go
command/agent/alloc_endpoint_test.go

Test fixes from #3383

---

api/acl.go
api/acl_test.go
command/agent/acl_endpoint.go
command/agent/acl_endpoint_test.go
dev/acls/default-ns.hcl
dev/acls/node-read.hcl
nomad/acl_endpoint.go
nomad/acl_endpoint_test.go
website/source/api/acl-policies.html.md
website/source/api/acl-tokens.html.md

Ability to lookup self token, list policies and get policies attached to own token

Ability to introspect self token

---

nomad/acl_endpoint.go
nomad/acl_endpoint_test.go

Return error if tokens cannot be deleted because they do not exist

---

ui/app/helpers/format-bytes.js
ui/app/models/allocation.js
ui/app/serializers/node.js
ui/app/templates/components/allocation-row.hbs
ui/tests/acceptance/client-detail-test.js
ui/tests/acceptance/task-group-detail-test.js
ui/tests/unit/helpers/format-bytes-test.js

This was just plain wrong 😳 
It's right now, plus there are tooltips for exact numbers:

Use the right math and metrics to measure used Memory 

---

ui/app/controllers/settings/tokens.js
ui/app/mixins/sortable.js
ui/app/routes/jobs/job.js
ui/tests/acceptance/token-test.js

This guarantees no privileged data is shown to unprivileged credentials.

Unload all records when a token is set or cleared

---

command/agent/http.go
vendor/github.com/rs/cors/LICENSE
vendor/github.com/rs/cors/README.md
vendor/github.com/rs/cors/cors.go
vendor/github.com/rs/cors/utils.go
vendor/vendor.json

Added to /v1/client/stats and /v1/client/allocation/

Support CORS for client endpoints

---

ui/app/models/allocation.js
ui/tests/acceptance/client-detail-test.js
ui/tests/acceptance/task-group-detail-test.js

Just do the math client-side with TotalTicks and Reserved

Don't rely on CpuStats.Percent

---

ui/app/adapters/application.js
ui/app/controllers/settings/tokens.js

Ember Data checks strictly against undefined:
https://github.com/emberjs/data/blob/master/addon/adapters/rest.js#L1128

Never return null for adapter headers

---

website/source/docs/runtime/_envvars.html.md.erb

Prevent _ from causing italics

---

ui/app/helpers/format-bytes.js
ui/app/models/allocation.js
ui/app/templates/components/job-deployment/deployment-allocations.hbs
ui/tests/unit/helpers/format-bytes-test.js

Add modified and version headers to deployment allocation table

---

vendor/github.com/davecgh/go-spew/LICENSE
vendor/github.com/davecgh/go-spew/spew/bypass.go
vendor/github.com/davecgh/go-spew/spew/bypasssafe.go
vendor/github.com/davecgh/go-spew/spew/common.go
vendor/github.com/davecgh/go-spew/spew/dump.go
vendor/github.com/davecgh/go-spew/spew/format.go
vendor/github.com/ugorji/go/codec/binc.go
vendor/github.com/ugorji/go/codec/cbor.go
vendor/github.com/ugorji/go/codec/decode.go
vendor/github.com/ugorji/go/codec/helper_not_unsafe.go
vendor/github.com/ugorji/go/codec/helper_unsafe.go
vendor/github.com/ugorji/go/codec/msgpack.go
vendor/github.com/ugorji/go/codec/prebuild.sh
vendor/github.com/ugorji/go/codec/simple.go
vendor/vendor.json

This updates the go-spew and ugorji/go/codec packages to allow make generate to work correctly.

Updates vendor directory to get code generation working correctly

---

website/source/guides/ui.html.md
website/source/layouts/guides.erb

Also linked to the ACL guide and the online demo.

Replace 'Nomad UI' with 'Web UI' in UI guide

---

.travis.yml
GNUmakefile
scripts/travis.sh

Looks to save 3-5 minutes looking at historical runs.

seperate linting from testing

---

website/source/api/allocations.html.md
website/source/api/deployments.html.md
website/source/api/jobs.html.md
website/source/api/nodes.html.md
website/source/docs/commands/alloc-status.html.md.erb
website/source/docs/commands/job/status.html.md.erb
website/source/intro/getting-started/jobs.html.md

I may be missing more places in the documentation beyond these, so pls take a look

Added documentation for modify time in a bunch of places

---

client/alloc_runner.go

@preetapan Fixes the test you were hitting

Alloc Runner doesn't panic on restoration.

---

website/source/docs/agent/configuration/index.html.md

Fixes https://github.com/hashicorp/nomad/issues/3517

Clarify Name config

---

website/source/docs/drivers/docker.html.md

Fixes https://github.com/hashicorp/nomad/issues/3533

Better docs for docker.endpoint option

---

website/source/api/agent.html.md

Hello,
I was playing around with the API today and noticed that this call is a GET request, not POST

update API docs for /agent/self from POST to GET

---

website/source/docs/enterprise/index.html.md
website/source/docs/enterprise/namespaces/index.html.md
website/source/docs/enterprise/quotas/index.html.md
website/source/docs/enterprise/sentinel/index.html.md
website/source/guides/namespaces.html.markdown
website/source/guides/quotas.html.md
website/source/guides/sentinel-policy.html.markdown
website/source/layouts/docs.erb

-Rewords introductory paragraph
-Slight wording changes elsewhere
-Adds additional links to the Enterprise product page

Minor tweaks to Enterprise docs

---

client/client.go

Fixes https://github.com/hashicorp/nomad/issues/3518

Handle race between fingerprinters and registration

---

command/helpers.go
command/helpers_test.go
command/job_status.go

Relies on https://github.com/hashicorp/nomad/pull/3647

Node Status output includes new modify time

---

command/agent/consul/client.go
command/agent/consul/int_test.go
command/agent/consul/unit_test.go
nomad/fsm_test.go
nomad/mock/mock.go
nomad/structs/structs.go
nomad/structs/structs_test.go
website/source/api/json-jobs.html.md
website/source/docs/job-specification/service.html.md
website/source/docs/job-specification/task.html.md

Services should not require a port

---

website/source/docs/commands/job/promote.html.md.erb

Add missing -group=cache to docs

---

website/redirects.txt
website/source/layouts/layout.erb
website/source/resources.html.erb

This consolidates everything under Resources and adds a redirect.

Merge Community and Resources pages

---

scripts/vagrant-linux-priv-consul.sh
scripts/vagrant-linux-priv-rkt.sh
scripts/vagrant-linux-priv-vault.sh

Needed to update Vault for #3334

Update Consul/rkt/Vault in Vagrant

---

CHANGELOG.md
client/driver/java.go

Found more priviledge.

---

website/source/docs/agent/configuration/consul.html.md

Fixes https://github.com/hashicorp/nomad/issues/3758

Actually show Consul config defaults

---

website/source/docs/drivers/docker.html.md

Fixes https://github.com/hashicorp/nomad/issues/3750

Docs:  update volume-driver, reflecting a supported driver

---

api/allocations.go
api/jobs.go
api/jobs_test.go
api/tasks.go
api/tasks_test.go
command/agent/job_endpoint.go
command/agent/job_endpoint_test.go
jobspec/parse.go
jobspec/parse_test.go
jobspec/test-fixtures/basic.hcl
jobspec/test-fixtures/reschedule-job.hcl
nomad/alloc_endpoint_test.go

Adds parsing support for reschedule policy and adds reschedule events to alloc API structs

Reschedule policy parsing

---

api/allocations.go
nomad/state/state_store.go
nomad/state/state_store_test.go
nomad/structs/structs.go
scheduler/generic_sched_test.go

Ported from #3794 for master branch

Track next allocation

---

website/source/api/acl-policies.html.md
website/source/api/acl-tokens.html.md
website/source/api/agent.html.md
website/source/api/allocations.html.md
website/source/api/client.html.md
website/source/api/deployments.html.md
website/source/api/evaluations.html.md
website/source/api/index.html.md
website/source/api/jobs.html.md
website/source/api/metrics.html.md
website/source/api/namespaces.html.md
website/source/api/nodes.html.md
website/source/api/operator.html.md
website/source/api/quotas.html.md
website/source/api/regions.html.md
website/source/api/search.html.md
website/source/api/sentinel-policies.html.md
website/source/api/status.html.md
website/source/api/system.html.md
website/source/api/validate.html.md
website/source/guides/acl.html.markdown

Should provide cut and paste example for most users. Advanced users should be able to correct URLs to something appropriate.
This PR is just a possible solution to #3808.  Creating it for comment

Changed `nomad.rocks` to `localhost:4646` to align with defaults

---

website/source/docs/job-specification/service.html.md

Clarify that check names are auto generated.

---

client/rpc.go
client/rpc_test.go
nomad/client_rpc.go
nomad/client_rpc_test.go
nomad/rpc.go
nomad/rpc_test.go
nomad/structs/streaming_rpc.go

Add Streaming RPC ack

---

client/alloc_endpoint.go
client/alloc_endpoint_test.go
client/client_stats_endpoint.go
client/client_stats_endpoint_test.go
client/rpc.go
client/structs/structs.go
command/agent/alloc_endpoint.go
command/agent/alloc_endpoint_test.go
command/agent/fs_endpoint.go
command/agent/fs_endpoint_test.go
command/agent/helpers.go
command/agent/helpers_test.go
command/agent/stats_endpoint.go
nomad/client_alloc_endpoint.go
nomad/client_alloc_endpoint_test.go
nomad/client_fs_endpoint.go
nomad/client_rpc.go
nomad/client_stats_endpoint.go
nomad/client_stats_endpoint_test.go
nomad/server.go

Builds on https://github.com/hashicorp/nomad/pull/3835

Client RPCs for garbage collection and alloc stats

---

scheduler/reconcile_test.go
scheduler/reconcile_util.go

are rescheduled again. Simplified logic and added test case to catch this.

Fixes bug in reconciler where previously rescheduled allocs 

---

api/nodes.go
api/nodes_test.go
command/agent/node_endpoint.go
command/agent/node_endpoint_test.go
command/node.go
command/node_drain.go
command/node_drain_test.go
command/node_status.go
commands.go
main.go
nomad/drain_test.go
nomad/fsm.go
nomad/fsm_test.go
nomad/mock/mock.go
nomad/node_endpoint.go
nomad/node_endpoint_test.go
nomad/state/state_store.go
nomad/state/state_store_test.go
nomad/structs/structs.go

This PR introduces the new node drain API and exposes it via the CLI command.

Node Drain API and CLI

---

client/fingerprint_manager.go

Fixes a race condition due to multiple fingerprinters accessing node attributes via the `cgroupsMounted` function: https://github.com/hashicorp/nomad/blob/34d3bba8ebc6e385ed54a5692fc6c8f786b8090f/client/driver/utils.go#L28
See output here: https://gist.github.com/preetapan/93ef7c2bf2953182cada3ee7b6855f0f

Fingerprinters accessing node information should be thread safe

---

website/Gemfile
website/Gemfile.lock
website/source/index.html.erb

As requested by Armon & Mitchell ✨ 
Also, wow sorry about the accidental push to master and revert 😧

A couple small website fixes

---

website/source/docs/job-specification/template.html.md

Update the template documentation, and add a vault PKI integration example.

Template docs, add vault PKI integration example.

---

CHANGELOG.md
api/agent_test.go
api/evaluations_test.go
api/jobs_test.go
api/nodes_test.go
client/allocdir/fs_linux_test.go
client/allocdir/task_dir_linux_test.go
client/allocdir/task_dir_test.go
client/driver/docker.go
client/driver/rkt_test.go
client/vaultclient/vaultclient_test.go
command/inspect_test.go
command/node_drain_test.go
command/node_status_test.go
command/stop_test.go
nomad/acl_endpoint.go
nomad/acl_endpoint_test.go
nomad/alloc_endpoint_test.go
nomad/eval_endpoint_test.go
nomad/fsm_test.go
nomad/job_endpoint_test.go
nomad/state/state_store.go
nomad/state/state_store_test.go
nomad/structs/structs.go
nomad/vault_test.go
ui/tests/acceptance/allocation-detail-test.js
ui/tests/acceptance/client-detail-test.js
ui/tests/acceptance/job-detail-test.js
ui/tests/acceptance/task-detail-test.js

Cleaning up from #3963
https://www.merriam-webster.com/dictionary/existent

non-Existent -> nonexistent

---

ui/app/components/job-page/abstract.js
ui/app/controllers/allocations/allocation.js
ui/app/controllers/allocations/allocation/index.js
ui/app/controllers/allocations/allocation/task.js
ui/app/controllers/allocations/allocation/task/index.js
ui/app/controllers/allocations/allocation/task/logs.js
ui/app/controllers/jobs/job.js
ui/app/controllers/jobs/job/task-group.js
ui/app/routes/allocations/allocation.js
ui/app/templates/allocations/allocation/index.hbs
ui/app/templates/allocations/allocation/task/index.hbs
ui/app/templates/allocations/allocation/task/logs.hbs
ui/app/templates/jobs/job/task-group.hbs
ui/app/utils/classes/query-params.js
ui/mirage/factories/evaluation.js
ui/mirage/factories/job.js
ui/mirage/serializers/application.js
ui/tests/acceptance/task-detail-test.js

This is a more natural structure of information than having allocations be their own thing.

UI: Allocation and task breadcrumbs extend job breadcrumbs

---

ui/app/components/allocation-row.js
ui/app/models/allocation.js
ui/app/templates/components/allocation-row.hbs
ui/app/utils/classes/allocation-stats.js

I missed this when making all the views live update since this data doesn't go through the blocking queries path.

UI: Poll for allocation stats

---

client/driver/executor/executor.go

Should help with debugging issues like #3971

executor: increase level for helpful log lines

---

main.go

This helps fix a `make check` warning for dead code.

Remove unused function

---

client/driver/rkt.go

Added extra debug logging; extended timeout; added jitter.

rkt: logging enhancements

---

e2e/rescheduling/input/norescheduling.hcl
e2e/rescheduling/input/reschedule_success.hcl
e2e/rescheduling/input/rescheduling_canary_autorevert.hcl
e2e/rescheduling/input/rescheduling_default.hcl
e2e/rescheduling/input/rescheduling_maxp.hcl
e2e/rescheduling/input/rescheduling_maxp_autorevert.hcl
e2e/rescheduling/input/rescheduling_system.hcl
e2e/rescheduling/input/rescheduling_update.hcl
e2e/rescheduling/server_side_restarts_test.go
nomad/structs/structs.go
scheduler/reconcile_test.go
scheduler/reconcile_util.go

This PR also refactors the filterByReschedulable method and makes the logic much easier to follow.

Filter desired status stop allocs correctly 

---

nomad/fsm.go
nomad/fsm_test.go
nomad/structs/structs.go
nomad/structs/structs_test.go

This PR handles upgrading a node that has no scheduling eligiblity set.

Handle upgrade where Node doesn't have eligiblity

---

nomad/drainer/drain_heap.go
nomad/drainer/drain_heap_test.go
nomad/drainer_int_test.go

The deadline heap was not properly firing for force deadlines. Added unit and integration test.

Fix issue where force deadlines weren't respected

---

client/alloc_runner_test.go

~**WIP** I want to see what Travis thinks of this fix.~
**Updtate:** Only test failure appears to be an unrelated flaky test, so I think this is good to merge.
Not sure why we required at least 6 alloc updates in this test as the
number of updates is non-deterministic. What we care about is the
TaskEvents.

test: don't rely on alloc runner update count

---

api/nodes.go
api/nodes_test.go
command/agent/command.go
command/commands.go
command/node_drain.go
command/node_drain_test.go
command/node_eligibility.go
command/operator_keyring.go
main.go

Also toggle eligibility output based on value
Output:

drain: add timestamps to cli output

---

CHANGELOG.md
command/job_init.go
website/source/docs/commands/job/deployments.html.md.erb
website/source/docs/commands/node.html.md.erb
website/source/docs/commands/node/drain.html.md.erb
website/source/docs/commands/node/eligibility.html.md.erb
website/source/docs/job-specification/migrate.html.md
website/source/layouts/docs.erb

Initial Node drain docs

---

api/jobs_test.go

Fix a bad assumption where the query meta index wouldn't be zero on the first
list of jobs before any jobs have been registered.

Fix flaky api/jobs tests based on index != 0

---

command/node_status.go

See original comment here: https://github.com/hashicorp/nomad/pull/4098#discussion-diff-179622946R396

Correctly initialize array length

---

dev/vault/README.md
website/source/docs/vault-integration/index.html.md
website/source/guides/acl.html.markdown

Fixes https://github.com/hashicorp/nomad/issues/3816

Use new Vault CLI commands in guides

---

website/source/resources.html.erb

-Datadog integration
-Heron integration
-Blog: Cluster scheduling systems for large scale Security Operations
-Trusted By: Pandora

Add items to Resources page

---

website/source/api/json-jobs.html.md
website/source/api/nodes.html.md

Made sample URLs use `http` instead of `https` so they should Just Work with a dev agent.
Will add a followup PR to fix other API pages.

Add drain API and JSON jobspec docs

---

website/source/docs/operating-a-job/failure-handling-strategies/check-restart.html.md
website/source/docs/operating-a-job/failure-handling-strategies/index.html.md
website/source/docs/operating-a-job/failure-handling-strategies/reschedule.html.md
website/source/docs/operating-a-job/failure-handling-strategies/restart.html.md
website/source/layouts/docs.erb

Rather than just mentioning rescheduling, this new section talks about all three restart related stanzas and when to use them.

Added section on failure recovery under operating a job 

---

website/source/docs/upgrade/index.html.md
website/source/docs/upgrade/upgrade-specific.html.md

Add drain upgrade guide docs

---

website/source/docs/commands/node/status.html.md.erb
website/source/guides/securing-nomad.html.md
website/source/intro/getting-started/cluster.html.md
website/source/intro/getting-started/running.html.md

Update dated example outputs ;)

[Docs] Update output message of `nomad node status`

---

website/source/guides/nomad-metrics.html.md

I noticed this while reading the docs. Quick fix.

Typo fix on a link

---

website/source/docs/agent/telemetry.html.md

See: https://github.com/hashicorp/nomad/pull/3467#issuecomment-381467572

Document job telemetry from #3467

---

client/alloc_runner_test.go

I could not reproduce the failure locally even with `stress -cpu ...`
eating all the cpu it could on my machine.
But I think the race was in one of two places:
* The task could restart which could create new events
* I think there could be a race between the updater's version of events
and alloc runners as updates are async
I fixed both. Here's hoping that fixes this flaky test.

tests: fix race in alloc_runner_test.go

---

nomad/deploymentwatcher/deployment_watcher.go
nomad/deploymentwatcher/deployments_watcher_test.go
nomad/deploymentwatcher/testutil_test.go

…ocations and eventually has failed allocations

Fix deadlock when deployment is initially created without allocations

---

demo/vagrant/Vagrantfile

Use CONSUL_VERSION variable in demo Vagrantfile

---

CHANGELOG.md
vendor/github.com/hashicorp/go-getter/decompress_tar.go
vendor/github.com/hashicorp/go-getter/decompress_testing.go
vendor/vendor.json

Fixes https://github.com/hashicorp/nomad/issues/4194

Update go-getter to pick up file access time fix

---

website/source/docs/commands/node/drain.html.md.erb
website/source/guides/node-draining.html.md

Update docs CLI output for node drain

---

website/source/assets/javascripts/analytics.js
website/source/assets/stylesheets/_global.scss

So sorry about this missing line, this was really a huge mistake 😢

Fix js syntax error, resolve fout issues

---

website/source/docs/commands/alloc/status.html.md.erb

Missed change to `alloc status` from `alloc-status`

---

website/source/resources.html.erb

Add link to Portworx blog, please.

Add Portworx Blog link

---

client/client.go
client/config/config.go
command/agent/http.go
helper/tlsutil/config.go
helper/tlsutil/config_test.go
nomad/config.go
nomad/server.go
nomad/structs/config/tls.go
nomad/structs/config/tls_test.go

Add missing fields to TLS merge method

Refactor to prefer using NewTLSConfiguration constructor

---

api/nodes.go
command/agent/node_endpoint.go
command/agent/node_endpoint_test.go

Set node eligibility to true when old client calls disable

---

ui/app/templates/allocations/allocation/index.hbs
ui/app/templates/allocations/allocation/task/index.hbs
ui/tests/acceptance/allocation-detail-test.js
ui/tests/acceptance/task-detail-test.js

UI: Use the network ip for the task address instead of the node ip

---

ui/app/templates/allocations/allocation/index.hbs

UI: Style tasks on the alloc index page like other tables of resources

---

GNUmakefile
scripts/vagrant-linux-priv-ui.sh

Update all the UI dependencies in for vagrant.

UI: update vagrant

---

ui/app/components/allocation-row.js
ui/app/models/allocation.js
ui/app/models/evaluation.js
ui/app/serializers/allocation.js
ui/app/serializers/evaluation.js
ui/mirage/factories/task.js

Original bug report: https://github.com/emberjs/data/issues/5209
It's fixed in 2.18, I'm just now getting around to undoing the workaround.

UI: Clean up some ember data code

---

ui/tests/acceptance/allocation-detail-test.js

This has been a flaky test since it was written. It's honestly surprising how often if passed given there was no guarantee.

UI: Actually ensure that the allocation relies on an unhealthy driver

---

website/source/docs/job-specification/constraint.html.md

To resolve https://github.com/hashicorp/nomad/issues/4424 and prevent this pitfall for others.

Added warning about impossible constraints

---

helper/stats/cpu.go

Closes https://github.com/hashicorp/nomad/issues/4439.

Extend timeout based on user feedback

---

CHANGELOG.md

Creates changelog line for https://github.com/hashicorp/nomad/pull/4441

Added info about #4441 to Changelog

---

ui/config/environment.js
ui/mirage/scenarios/default.js

Different work requires different mock data setups. I had been manually tweaking the setup I wanted, but some common patterns have emerged that make sense to persist for future use and to help other contributors.

UI: Codify common mirage scenarios and make it easy to switch between

---

scheduler/generic_sched.go

scheduler: fixed nil panic and clearer error handling

---

client/allocrunnerv2/alloc_runner.go
client/allocrunnerv2/alloc_runner_test.go
client/allocrunnerv2/config.go
client/allocrunnerv2/interfaces/task_lifecycle.go
client/allocrunnerv2/taskrunner/lifecycle.go
client/allocrunnerv2/taskrunner/state/state.go
client/allocrunnerv2/taskrunner/task_runner.go
client/allocrunnerv2/taskrunner/task_runner_getters.go
client/allocrunnerv2/taskrunner/task_runner_hooks.go
client/allocrunnerv2/taskrunner/vault_hook.go
client/client.go

This Vault hook can derive a token but currently can't restart, signal or kill a task.

Basic Vault hook 

---

website/source/docs/job-specification/constraint.html.md

Signed-off-by: M S Vishwanath Bhat <msvbhat@gmail.com>

Fix client metadata link in Nomad constraints docs

---

website/source/docs/faq.html.md

typo - duplication of the word can

---

website/source/api/index.html.md

Document HTTP response codes

---

terraform/azure/README.md

for non linux users, variable part is not clear that need to be set manually

Update Azure notes for variables

---

website/source/docs/job-specification/periodic.html.md

Added note about resubmitting the non-periodic job as a periodic one. #4526 
This is how it'll look like:

Updated periodic stanza documentation

---

client/allocrunner/taskrunner/task_runner.go
client/allocrunnerv2/alloc_runner.go
client/allocrunnerv2/config.go
client/allocrunnerv2/interfaces/task_lifecycle.go
client/allocrunnerv2/taskrunner/lifecycle.go
client/allocrunnerv2/taskrunner/service_hook.go
client/allocrunnerv2/taskrunner/task_runner.go
client/allocrunnerv2/taskrunner/task_runner_getters.go
client/allocrunnerv2/taskrunner/task_runner_hooks.go
client/client.go
client/driver/docker.go
client/driver/driver.go
client/driver/exec.go
client/driver/java.go
client/driver/mock_driver.go
client/driver/qemu.go
client/driver/raw_exec.go
client/driver/rkt.go
command/agent/consul/check_watcher.go
nomad/structs/structs.go

Stopping tasks not fully implemented but Consul Service Hook still works.

Consul Service Hook

---

client/allocrunnerv2/alloc_runner.go
client/allocrunnerv2/taskrunner/task_runner.go
client/allocrunnerv2/taskrunner/task_runner_getters.go
client/allocrunnerv2/taskrunner/task_runner_hooks.go
client/allocrunnerv2/taskrunner/vault_hook.go
client/client.go

Updates are applied asynchronously but sequentially

Implement alloc updates in arv2

---

e2e/cli/command/environment.go
e2e/cli/command/meta.go
e2e/cli/command/provision.go
e2e/cli/command/run.go
e2e/cli/command/scanner.go
e2e/cli/command/test_decoder.go
e2e/cli/command/util.go
e2e/cli/environments/mock/mock/main.tf
e2e/cli/environments/mock/mock/terraform.tfvars
e2e/cli/main.go
e2e/example/example.go
vendor/github.com/hashicorp/go-hclog/README.md
vendor/github.com/hashicorp/go-hclog/int.go
vendor/github.com/hashicorp/go-hclog/log.go
vendor/github.com/hashicorp/go-hclog/nulllogger.go
vendor/vendor.json

This PR is dependent on #4461.
Run output example:

E2E: CLI Implementation

---

dist/systemd/nomad.service

Signed-off-by: M S Vishwanath Bhat <msvbhat@gmail.com>

Nomad systemd unit - Add restarting on failure

---

nomad/structs/funcs.go
nomad/structs/structs.go
nomad/structs/structs_test.go
scheduler/generic_sched_test.go
scheduler/propertyset.go
scheduler/spread.go
scheduler/spread_test.go
scheduler/stack.go

Reconstructing this PR https://github.com/hashicorp/nomad/pull/4527/files that got lost during a force push

backend for spread

---

website/source/docs/job-specification/meta.html.md

I was checking up on how to set some metadata and stumbled upon this.

possible typo about node.class

---

api/allocations.go
api/jobs.go
nomad/structs/structs.go
nomad/structs/structs_test.go

This is a pretty small PR into the feature branch for internal struct and API level changes needed for preemption.

Changes to plan and allocation structs for preemption

---

client/allocrunnerv2/health_hook.go
client/allocrunnerv2/health_hook_test.go

Still more testing to do, but I want to get this panic fixed ASAP.
All new tests pass with -race

health_hook: fix panic and add tests

---

plugins/shared/loader/instance.go
plugins/shared/loader/loader.go
plugins/shared/loader/loader_test.go
plugins/shared/loader/testing.go
plugins/shared/singleton/future.go
plugins/shared/singleton/singleton.go
plugins/shared/singleton/singleton_test.go

This PR creates a singleton factory that wraps a PluginCatalog and caches the
plugins to provide singleton behavior.

Singleton plugin loader

---

client/allocrunnerv2/alloc_runner.go
client/allocrunnerv2/interfaces/task_lifecycle.go
client/allocrunnerv2/taskrunner/service_hook.go
client/allocrunnerv2/taskrunner/stats_hook.go
client/allocrunnerv2/taskrunner/stats_hook_test.go
client/allocrunnerv2/taskrunner/task_runner.go
client/allocrunnerv2/taskrunner/task_runner_hooks.go
client/client.go

Tested except for the net/rpc specific error case which may need
changing in the gRPC world.

Implement stats collection hook

---

website/source/guides/operations/requirements.html.md

References discussion at : 
https://groups.google.com/forum/#!topic/nomad-tool/PGziYvb22-g

docs: make explicit the communication pattern on RPC port (4647)

---

api/resources.go
command/agent/job_endpoint.go
command/agent/job_endpoint_test.go
jobspec/parse.go
jobspec/parse_test.go
jobspec/test-fixtures/basic.hcl
nomad/structs/diff.go
nomad/structs/diff_test.go
nomad/structs/structs.go

This PR adds the following:
* Api and struct definitions of a device request
* Jobspec parsing of a device request
* API->Struct conversion
* Struct diffing logic

Parse devices in job spec

---

.travis.yml
GNUmakefile
website/Makefile
website/scripts/test.sh
website/source/docs/runtime/index.html.md
website/source/guides/load-balancing/fabio.html.md
website/source/intro/getting-started/ui.html.md

there were a few bad links that are fixed now
also, note that I modified some `localhost` URLs in https://www.nomadproject.io/intro/getting-started/ui.html to no longer be hyperlinks, because they are not valid and because I couldn't find a way to get `wget` to ignore them.
also, I rolled this into the travis stage with the UI testing, let me know if you would like this broken out into its own stage.

docs: check website for broken links

---

client/allocrunner/taskrunner/interfaces/handle.go
client/allocrunner/taskrunner/task_runner.go
client/allocrunner/taskrunner/task_runner_getters.go
drivers/mock/driver.go
plugins/base/plugin.go
plugins/drivers/driver.go

Each commit is its own important fix.

Fix driver config encoding, config tag parsing, mock plugin name, and nil interface

---

drivers/rkt/driver.go
drivers/rkt/driver_test.go
drivers/rkt/handle.go
drivers/rkt/state.go
plugins/drivers/driver.go
plugins/drivers/utils.go

Implements Rkt driver plugin, and ported over unit tests from client/driver/rkt_test.go

rkt driver plugin

---

ui/app/styles/core/navbar.scss
ui/app/templates/components/global-header.hbs

UI: Make the global logo link to the jobs page (home page)

---

client/allocrunner/taskrunner/task_runner_hooks.go

Pulled out of #4775 to try to make merging that PR easier.

tr: cleanup hook logs

---

drivers/qemu/driver.go
drivers/qemu/driver_test.go
drivers/qemu/handle.go
drivers/qemu/state.go

Redo on #4787 rebased against master. Finished all tests except for one that uses the monitor socket

QEMU driver plugin

---

drivers/qemu/driver.go
plugins/shared/catalog/register.go

API changes had broken the build.

qemu: fix build and register by default

---

ui/config/environment.js
ui/ember-cli-build.js
ui/package.json
ui/yarn.lock

Pretty basic heuristics to improve build times based on different config and env conditions.
Further reading: https://discuss.emberjs.com/t/tips-for-improving-build-time-of-large-apps/15008

UI: build time performance improvements

---

drivers/rawexec/driver.go

If Nomad is not running as root, we should not try to use cgroups for pid
freezing.
This originally was implemented pre-driver-support in
https://github.com/hashicorp/nomad/blob/v0.8.6/client/driver/raw_exec.go#L120-L130

rawexec: Only use cgroups when running as root.

---

GNUmakefile
client/allocrunner/alloc_runner_test.go
client/allocrunner/taskrunner/task_runner_test.go
client/allocrunnerdeprecated/alloc_runner_test.go
client/allocrunnerdeprecated/taskrunner/task_runner_test.go
client/allocrunnerdeprecated/testing.go
client/allocwatcher/alloc_watcher_test.go
client/client_test.go
client/driver/docker.go
client/driver/docker_linux_test.go
client/driver/rkt.go
client/fs_endpoint_test.go
client/gc_test.go
command/agent/alloc_endpoint_test.go
command/agent/consul/script_test.go
command/agent/consul/unit_test.go
drivers/docker/docklog/docker_logger_test.go
drivers/java/driver.go
drivers/java/driver_test.go
drivers/mock/driver.go
drivers/mock/handle.go
drivers/mock/utils.go
drivers/mock/utils_test.go
drivers/shared/eventer/eventer.go
nomad/client_alloc_endpoint_test.go
nomad/client_fs_endpoint_test.go
nomad/mock/mock.go
plugins/device/plugin_test.go
scripts/travis-linux.sh

This is better viewed by evaluating them commit by commit.

Fix some tests in master

---

website/source/api/allocations.html.md
website/source/api/index.html.md
website/source/api/jobs.html.md
website/source/api/json-jobs.html.md
website/source/docs/job-specification/affinity.html.md
website/source/layouts/docs.erb

PR for documentation for affinity. Still need to figure out various API end points that need to be updated.

docs for affinity

---

drivers/docker/driver_test.go
drivers/docker/handle.go
plugins/drivers/proto/driver.pb.go
plugins/drivers/proto/driver.proto

CI Linter job identified the issues fixed here.

Fix linter job

---

CHANGELOG.md

Batch update for the PRs I recently merged.

Some changelog items

---

nomad/structs/devices.go
scheduler/preemption.go
scheduler/preemption_test.go
scheduler/rank.go

This PR implements preemption support for device resources

Device preemption

---

website/source/guides/ui.html.md
website/source/layouts/layout.erb

Commenting out references along with header + footer to demo.nomadproject.io

Comment out demo stable

---

client/client_test.go

Re-enabling and updating an old test. Able to cut out a ton of extra
work by using WaitForRunning which does almost everything this test
needs.
Sadly the test still takes >4s due to a delay in logmon shutdown. Going to tackle that separately.

client: assert alloc status updates work

---

README.md
client/allocrunner/testing.go

client: add proper build flag to allocrunner testing.go

---

client/allocrunner/alloc_runner.go

Follow up from https://github.com/hashicorp/nomad/pull/5007#pullrequestreview-186739124

allocrunner: Standardised discard logs

---

client/taskenv/util.go
client/taskenv/util_test.go

**The Bug:**
You may have seen log lines like this when running 0.9.0-dev:
```
... client.alloc_runner.task_runner: some environment variables not available for rendering: ... keys="attr.driver.docker.volumes.enabled, attr.driver.docker.version, attr.driver.docker.bridge_ip, attr.driver.qemu.version"
```
Not only should we not be erroring on builtin driver attributes, but the
results were nondeterministic due to map iteration order!
The root cause is that we have an old root attribute for all drivers
like:
```
attr.driver.docker = "1"
```
When attributes were opaque variable names it was fine to also have
"nested" attributes like:
```
attr.driver.docker.version = "1.2.3"
```
However in the HCLv2 world the variable names are no longer opaque: they
form an object tree. The `docker` object …

taskenv: have maps take precedence over primitives

---

client/rpc.go
command/node_status.go
drivers/rkt/driver.go
nomad/core_sched.go
nomad/periodic.go
plugins/drivers/plugin.go
plugins/drivers/server.go

Fix a panic on node.Deregister fail

---

website/source/docs/runtime/interpolation.html.md.erb

General readability improvement of this paragraph.

Oxford comma in variable interpolation summary

---

website/source/api/allocations.html.md
website/source/api/jobs.html.md
website/source/api/json-jobs.html.md
website/source/docs/job-specification/spread.html.md
website/source/layouts/docs.erb

This PR adds documentation for the spread stanza

Docs for spread stanza

---

client/client.go

This adds a helper for accessing an allocrunner, to avoid accidentally
hanging on to the allocLock for longer than is necessary.

client: Cleanup allocrunner access

---

client/allochealth/tracker.go
client/allocrunner/alloc_runner_test.go
client/allocrunner/taskrunner/service_hook_test.go
client/allocrunner/taskrunner/task_runner_test.go
client/consul/consul_testing.go
command/agent/consul/int_test.go

_Test and test helper changes only. No functional runtime changes._
Skipping 1 test because it's failing, but I want to get this work merged as I need to move to another work item and don't want to leave this orphaned on my machine.

Port a bunch of pre-0.9 Consul tests to 0.9

---

CHANGELOG.md

updating 0.8.7 release date on GH

make change to the 0.8.7 release date

---

client/allocrunner/taskrunner/task_runner_test.go

test: porting TestTaskRunner_SimpleRun_Dispatch

---

client/allocrunner/taskrunner/task_runner.go

v0.9.0-dev started emitting a Terminated event every time a task process
exited. While this wasn't true in previous versions, it's a useful task
event because it's the only place for job operators to view the task's
exit code.
This behavior is asserted in the e2e/taskevents tests.

client: restore Terminated event on every exit

---

website/source/docs/job-specification/affinity.html.md
website/source/docs/job-specification/group.html.md
website/source/docs/job-specification/job.html.md
website/source/docs/job-specification/spread.html.md
website/source/docs/job-specification/task.html.md

Some small fixes and adding links in a few pages that were missing

Documentation fixes for affinity and spread

---

website/source/guides/advanced-scheduling/advanced-scheduling.html.md
website/source/guides/advanced-scheduling/affinity.html.md
website/source/guides/advanced-scheduling/spread.html.md
website/source/layouts/guides.erb

This PR adds the **Advanced Scheduling Features** section in the guides page and starts off by placing the affinity and spread guides in there.

Advanced scheduling guides (affinity + spread)

---

drivers/docker/handle.go

https://gist.github.com/dadgar/c1030dfeac45b5823940396153d49306

Fix killing non-existant container with a kill timeout

---

CHANGELOG.md

Add major features and fix some missing changes

Nomad 0.9.0 changelog

---

scripts/vagrant-linux-priv-go.sh

Use latest Golang point release at this time for development.

dev: use golang 1.11.5

---

website/source/docs/devices/nvidia.html.md

fixes https://github.com/hashicorp/nomad/issues/5271
Updates the affinity stanza in the devices example to include a valid
weight.

docs: Update affinity stanza in device

---

command/job_status.go

Fixes #5291 
Manually verified bug and fix with attached job file.
[sleeper.nomad.gz](https://github.com/hashicorp/nomad/files/2822632/sleeper.nomad.gz)

cli: do not duplicate reschedule headers per group

---

drivers/docker/config.go

docker: Fix volume driver_config options spec

---

website/source/docs/job-specification/device.html.md

Fix https://github.com/hashicorp/nomad/issues/5315

Fix device.attr typo

---

client/allocrunner/alloc_runner_test.go

Also add destroy(ar) helper to fix a bunch of shutdown races in AR tests.

tests: port TestAllocRunner_Destroy from 0.8

---

website/source/docs/job-specification/template.html.md

Fixes #5347
The fact that you *must* use `toJSON` in env templates when passing a password from Vault to your task is incredibly non-obvious. I confused myself in the linked ticket and discussion thread!
Not trying to support newlines in env vars (the PEM certificate example) would have been a better idea and let out parser be *much* simpler. I don't think there's any going back though.
In the future we may want to add a `literal` function as an alias for `toJSON` just to make this feature a little more obvious. The fact that we use JSON to encode/parse the values is an internal implementation detail that should not be exposed to users.

docs: clarify use of toJSON for passwords

---

website/source/guides/external/lxc.html.md

reformat lxc guide

---

command/agent/agent.go
command/agent/command.go
command/agent/testagent.go
helper/logging/logging.go

Refactored some initialization around agent startup so that the CLI output also uses json with json logging is enabled

Support json logging for CLI output for agent 

---

client/allocrunner/alloc_runner_test.go

Ported TestAllocRunner_TaskFailed_KillTG and TestAllocRunner_TerminalUpdate_Destroy from 0.8.7

More alloc runner tests ported from 0.8.7

---

website/source/guides/external/lxc.html.md
website/source/layouts/docs.erb

Cherry-picking the following commits (approved and merged into master):
https://github.com/hashicorp/nomad/pull/5338
https://github.com/hashicorp/nomad/pull/5339

Lxc content update stable

---

website/source/guides/operations/vault-integration/index.html.md

* update formatting and add toJSON function with explanation
* edit typo
* Update website/source/guides/operations/vault-integration/index.html.md
Co-Authored-By: Omar-Khawaja <Omar-Khawaja@users.noreply.github.com>
* fixing clarification bullet explaining the use of toJSON

update formatting and add toJSON function with explanation (#5366)

---

ui/app/styles/core/section.scss
ui/app/templates/allocations/allocation/task/logs.hbs

Fixes #5303 
Added simple class that allows `section` to take whole available space

Logs view - support widescreen format

---

terraform/aws/README.md
terraform/aws/env/us-east/terraform.tfvars
terraform/shared/config/consul-template.hcl
terraform/shared/config/consul-template.service
terraform/shared/scripts/client.sh
terraform/shared/scripts/server.sh
terraform/shared/scripts/setup.sh

Updating configurations and AWS image
Consul:   1.3.1   ---> 1.4.3
Vault:      0.11.4 ---> 1.0.3
Nomad:  0.8.6  ---> 0.8.7
Installed + configured Consul Template on nodes (0.20.0) as well.

AWS env update

---

scripts/vagrant-linux-priv-go.sh

https://golang.org/doc/devel/release.html#go1.11.minor

vagrant: upgrade to Go 1.11.6

---

client/allocrunner/taskrunner/task_runner_test.go

I chose to make them more of integration tests since there's a lot more
plumbing involved. The internal implementation details of how we craft
task envs can now change and these tests will still properly assert the
task runtime environment is setup properly.

tests: port pre-0.9 task env tests

---

.github/ISSUE_TEMPLATE.md

Also reordered the sections to put the logs at the end.

Mention nomad-oss-debug in issue template

---

e2e/upgrades/README.md
e2e/upgrades/client1.hcl
e2e/upgrades/client2.hcl
e2e/upgrades/client3.hcl
e2e/upgrades/kill_node.sh
e2e/upgrades/run_cluster.sh
e2e/upgrades/run_node.sh
e2e/upgrades/server1.hcl
e2e/upgrades/server2.hcl
e2e/upgrades/server3.hcl

Some helper scripts for testing upgrades, ive been using them to manually test upgrades. They could turn into automated tests in the future.

scripts for upgrade testing

---

terraform/aws/env/us-east/terraform.tfvars
terraform/aws/packer.json

More terraform updates

---

command/commands.go
command/job_periodic.go
command/job_periodic_force.go
command/job_periodic_force_test.go
website/source/docs/commands/job/periodic-force.html.md.erb
website/source/layouts/docs.erb

cli: add support for periodic force evaluation

---

website/source/guides/operations/deployment-guide.html.md
website/source/guides/operations/reference-architecture.html.md

Confirmed RA and DG work for Nomad 0.9

Docs ea update 0.9

---

website/source/docs/drivers/external/singularity.html.md

Signed-off-by: Eduardo Arango <eduardo@sylabs.io>

singularity_path -> singularity_cache

---

website/source/docs/commands/node.html.md.erb

Fixed typo: scheduilng/scheduling.

Fixed Typo

---

GNUmakefile
dev/hooks/pre-push

this adds a master branch guard to dev/hooks/pre-push and a dependency in the makefile to install that hook on make bootstrap

Dev make boostrap git hooks

---

README.md

Added a link to the Gitter/IRC chat room into our Resources page + revised the opening line in Overview for consistency with other copy.

Added Gitter to Resources + revised Overview in for ReadME.

---

website/source/index.html.erb
website/source/resources.html.erb

Cherry-picked #5636 merge to stable-website branch to push changes into production.

cherry-pick to stable-website from PR #5636

---

e2e/metrics/input/helloworld.nomad
e2e/terraform/shared/scripts/setup.sh
terraform/examples/spark/README.md
terraform/shared/scripts/setup.sh
website/source/api/json-jobs.html.md
website/source/docs/commands/job/dispatch.html.md.erb
website/source/docs/job-specification/artifact.html.md
website/source/guides/spark/monitoring.html.md
website/source/guides/spark/pre.html.md
website/source/guides/spark/submit.html.md

In response to https://forums.aws.amazon.com/ann.jspa?annID=6776

docs: update s3 urls to use virtual bucket style

---

website/source/docs/job-specification/restart.html.md

Compare against the code here: https://github.com/hashicorp/nomad/blob/master/nomad/structs/structs.go#L4156-L4172

docs: fix default restart values

---

website/source/guides/operating-a-job/advanced-scheduling/affinity.html.md

Fixed wording: "as show below" -> "as shown below".

doc: wording

---

website/source/docs/schedulers.html.md

per @endocrimes comments on #5675, adding here.

Added Sparrow link

---

website/source/guides/operating-a-job/accessing-logs.html.md

Fixed typo: programatic/programmatic

docs: fixed typo

---

website/source/guides/analytical-workloads/spark/pre.html.md

Taking out remnants from what looks like a merge conflict that is throwing off formatting of page.

fixing formatting

---

website/source/guides/upgrade/upgrade-specific.html.md

docs: mention regression in task config validation

---

website/source/docs/devices/community.html.md
website/source/docs/devices/index.html.md
website/source/docs/drivers/external/index.html.md
website/source/docs/drivers/index.html.md
website/source/guides/upgrade/upgrade-specific.html.md

Merges #5693 and #5697 into stable-website

Stable website 5693 5697

---

website/source/docs/job-specification/update.html.md

docs: fix description of update.stagger

---

client/servers/manager.go

Stop logging in the happy path when nothing has changed.

client: log when server list changes

---

website/redirects.txt

Fixed bug reported with updated redirects for Google results + new website restructure.

Correct Spark links in redirects.txt

---

website/source/guides/integrations/vault-integration/index.html.md

Resolving merge conflict message and restoring proper formatting.

resolve merge conflict message in vault guide

---

website/source/guides/operating-a-job/external/lxc.html.md

Fixed wording: "as show below"/shown.

docs: fixed wording

---

website/source/guides/install/quickstart/index.html.md
website/source/intro/getting-started/install.html.md
website/source/intro/getting-started/running.html.md

* specify Vagrant as optional in getting started and installation
* edit next steps

Vagrant optional (#5724)

---

client/alloc_endpoint.go

Without this change, alloc_endpoint cancel the context passed to handler
when we detect EOF.  This races driver in setting exit code; and we run
into a case where the exec process terminates cleanly yet we attempt to
mark it as failed with context error.
Here, we rely on the driver to handle errors returned from Stream and
without racing to set an error.

exec: allow drivers to handle stream termination

---

client/driver_manager_test.go
client/fs_endpoint_test.go
client/lib/fifo/fifo_test.go
helper/escapingio/reader_test.go

Fixes to various tests, mainly data race related - better to be reviewed commit-by-commit.
These reveal no actual data race in code so grouping them here independently from others.

Grab bag of (primarily race) test fixes

---

ui/app/controllers/jobs/index.js
ui/tests/acceptance/jobs-list-test.js

And include all prefix types in the test data.
Fixes #5745

Include the _ prefix separator in both regexes

---

CHANGELOG.md

In each section, entries should be sorted by component name (except for core that appears in top), and then by line length.

sort and changelog entries

---

client/client.go
client/servers/manager.go

See #5730 for details.
This PR does not change any functionality. It is only removing unused code to prevent future confusion.

client: drop unused DC field from servers list

---

website/config.rb
website/source/api/allocations.html.md
website/source/api/jobs.html.md
website/source/api/json-jobs.html.md
website/source/api/operator.html.md
website/source/docs/commands/acl/token-list.html.md.erb
website/source/docs/commands/agent.html.md.erb
website/source/docs/commands/alloc.html.md.erb
website/source/docs/commands/alloc/exec.html.md.erb
website/source/docs/commands/alloc/restart.html.md.erb
website/source/docs/commands/alloc/signal.html.md.erb
website/source/docs/commands/alloc/stop.html.md.erb
website/source/docs/commands/job/deployments.html.md.erb
website/source/docs/commands/job/periodic-force.html.md.erb
website/source/docs/configuration/vault.html.md
website/source/docs/job-specification/update.html.md
website/source/downloads.html.erb
website/source/layouts/docs.erb

Revert 0.9.2 release super script tags

---

client/allocrunner/taskrunner/template/template_test.go
nomad/deploymentwatcher/deployments_watcher_test.go
nomad/drainer/drain_testing.go
nomad/drainer/watch_nodes_test.go

More Grab back of race detector test fixes.

More test fixes

---

terraform/aws/env/us-east/terraform.tfvars

I realize that this is a bit redundant given that terraform can answer these questions interactively, but folks walking up to this repo might not have a bunch of terraform experience.  This is mainly for discussion and to see if this has value for the end users.

Proposing new tfvars with additional inline docs

---

e2e/README.md
e2e/bin/run
e2e/bin/update
e2e/deployment/deployment.go
e2e/e2eutil/utils.go
website/source/docs/commands/deployment/promote.html.md.erb
website/source/docs/commands/deployment/status.html.md.erb
website/source/docs/commands/job/deployments.html.md.erb
website/source/docs/commands/job/promote.html.md.erb
website/source/guides/operating-a-job/update-strategies/blue-green-and-canary-deployments.html.md

fix flaky e2e test for deployment auto promotion

flaky e2e test

---

.netlify/state.json
netlify.toml

I doubt this will work on the first try. I also hope to refine it so they’re only produced when there are changes in `ui/`.

Add PR previews with Netlify

---

command/agent/config_parse_test.go
nomad/state/state_store.go

Noticed few things while reviewing code - each commit is independent.

Assorted minor changes

---

website/source/guides/upgrade/index.html.md
website/source/guides/upgrade/upgrade-specific.html.md

Added some text in the upgrade page explaining that downgrades are not supported

Add warning docs around downgrades

---

website/source/guides/operations/monitoring/nomad-metrics.html.md

Fix incorrect link to the sample Grafana dashboard

---

README.md
scripts/release/mac-remote-build
scripts/vagrant-linux-priv-go.sh

It's the latest 1.11 point release as of now

Update golang to 1.11.11

---

terraform/aws/README.md
terraform/aws/env/us-east/terraform.tfvars

roll back to previous ami

---

website/source/docs/configuration/index.html.md

Update the example agent configuration to `0.9+` plugin syntax to align with syntax defined specifically for the `raw_exec` plugin: https://www.nomadproject.io/docs/drivers/raw_exec.html#client-requirements
Validated that website reflected changes via:
```
cd website && make website
```

Update website example config

---

api/resources.go
api/tasks.go
client/allochealth/tracker.go
command/agent/job_endpoint.go
helper/funcs.go
helper/funcs_test.go
jobspec/parse.go
nomad/structs/consul.go
nomad/structs/structs.go
vendor/github.com/hashicorp/consul/api/README.md
vendor/github.com/hashicorp/consul/api/acl.go
vendor/github.com/hashicorp/consul/api/agent.go
vendor/github.com/hashicorp/consul/api/api.go
vendor/github.com/hashicorp/consul/api/catalog.go
vendor/github.com/hashicorp/consul/api/config_entry.go
vendor/github.com/hashicorp/consul/api/connect_ca.go
vendor/github.com/hashicorp/consul/api/debug.go
vendor/github.com/hashicorp/consul/api/health.go
vendor/github.com/hashicorp/consul/api/kv.go
vendor/github.com/hashicorp/consul/api/operator_area.go
vendor/github.com/hashicorp/consul/api/operator_keyring.go
vendor/github.com/hashicorp/consul/api/prepared_query.go
vendor/github.com/hashicorp/consul/api/txn.go
vendor/vendor.json

Refactored out of my `f-connect` branch because I did a sloppy job of committing over there. Also snuck in a Consul vendoring update as its another Connect dependency.

Add support for Service Stanzas in Task Groups

---

api/allocations.go
nomad/structs/structs.go

Fixed AllocatedResources.Copy as well (wasn't deepcopying Networks before)

 api: add missing Networks field to alloc resources

---

CHANGELOG.md
website/source/docs/drivers/external/index.html.md
website/source/docs/drivers/external/jail-task-driver.html.md
website/source/layouts/docs.erb

Added documentation for a FreeBSD task driver that leverages jails for container creation.

Added Community task driver for FreeBSD jails

---

e2e/terraform/configs/indexed/client-0.hcl
e2e/terraform/configs/indexed/client-1.hcl
e2e/terraform/configs/indexed/client-2.hcl
e2e/terraform/configs/indexed/client-3.hcl
e2e/terraform/configs/indexed/server-0.hcl
e2e/terraform/configs/indexed/server-1.hcl
e2e/terraform/configs/indexed/server-2.hcl
e2e/terraform/configs/server.hcl

Enables the pprof http endpoint for debugging.

e2e: enable_debug=true for all agents

---

api/jobs.go
api/jobs_test.go
api/tasks_test.go

Add a test that demonstrates that update stanza merging, and make AutoPromote match AutoRevert

jobs update stanza merging cleanup

---

website/source/docs/job-specification/service.html.md

Closes https://github.com/hashicorp/nomad/issues/5981

Clarify script checks requiring shell

---

ui/app/router.js

This looks to me to be a route-not-taken in #4612.

UI: Remove unused route

---

website/source/guides/operating-a-job/advanced-scheduling/preemption-service-batch.html.md
website/source/guides/operating-a-job/advanced-scheduling/spread.html.md
website/source/layouts/guides.erb

* fix navigation issue for spread guide
* skeleton for preemption guide
* background info, challenge, and pre-reqs
* steps
* rewording of intro
* re-wording
* adding more detail to intro
* clarify use of preemption in intro

Service and Batch Job Preemption Guide (#5853)

---

drivers/docker/win32_volume_parse.go

Reverts hashicorp/nomad#6001
Needs to wait until after 0.9.4 is released.

Revert "driver/docker: support unix destination mount path in windows"

---

website/source/api/namespaces.html.md

Fix namespace parameter name

---

drivers/docker/win32_volume_parse.go

This reverts commit a6c96eade56f0b8880edbec3c4392934492f09bf.

driver/docker: support unix destination mount path in windows

---

website/source/docs/drivers/rkt.html.md

Added newline to fix list rendering on https://www.nomadproject.io/docs/drivers/rkt.html#client-requirements

Fix list rendering

---

api/tasks.go
command/agent/job_endpoint.go
jobspec/parse.go
jobspec/parse_test.go
jobspec/test-fixtures/basic.hcl
nomad/structs/structs.go

Add field "kind" to task for use in connect tasks

---

.circleci/config.yml

fix test result reporting summary in all jobs, e.g. https://circleci.com/gh/hashicorp/nomad/822, https://circleci.com/gh/hashicorp/nomad/819, and https://circleci.com/gh/hashicorp/nomad/818 .
also some incidental changes:
* introduce a reference for common variables and install-golang step
* upload test results artifacts so we can check raw results if we need to

circleci: fix test reports and some refactoring

---

command/agent/job_endpoint.go
nomad/structs/structs.go
nomad/structs/structs_test.go

Added validation for the "Kind" field
Fixes #6038

Add validation for kind field if it is a consul connect proxy

---

client/client.go
nomad/job_endpoint.go
nomad/job_endpoint_hook_connect.go
nomad/job_endpoint_hook_connect_test.go
nomad/job_endpoint_hook_test.go
nomad/job_endpoint_hooks.go
nomad/job_endpoint_test.go
nomad/server.go
nomad/structs/services.go
nomad/structs/structs.go
nomad/structs/structs_test.go

This PR implements an admission controller framework to more easily compose validation and mutation operations done to jobs during registration and planning.
fixes #6039

Builtin Admission Controller Framework

---

website/source/api/jobs.html.md

--payload -> --data for curl; consistent @payload

---

website/source/resources.html.erb

Link to [the discussion forum](https://discuss.hashicorp.com/c/nomad).

Add a link to the discussion forum on the resources page

---

vendor/github.com/hashicorp/go-syslog/builtin.go
vendor/github.com/hashicorp/go-syslog/go.mod
vendor/github.com/hashicorp/go-syslog/unix.go
vendor/github.com/hashicorp/go-syslog/unsupported.go
vendor/vendor.json

Bump up github.com/hashicorp/go-syslog for better BSD support

Bump up github.com/hashicorp/go-syslog for better BSD support

---

website/source/docs/runtime/interpolation.html.md.erb

add node.region to interpolation documentation

---

scheduler/feasible.go
scheduler/feasible_test.go

Currently, if a nomad host exposes a read only hostvolume, requests for a writeable volume can be scheduled on those hosts, and we'll silently mount it as read only. 
Here we switch to only scheduling requests for writeable volumes on hosts with a writeable volume. ReadOnly volume requests may be scheduled on both ReadOnly volumes and writeable volumes.

scheduler: Implicit constraint on readonly hostvol

---

terraform/shared/scripts/client.sh
terraform/shared/scripts/server.sh
terraform/shared/scripts/setup.sh

Bumped hadoop version from 2.7.6 to 2.7.7

bumped hadoop version

---

website/source/docs/drivers/index.html.md

Extend task driver documentation to better address resource isolation & security considerations.

docs: task driver resource isolation & security

---

nomad/structs/structs.go

structs: canonicalize tg Services and Networks

---

command/agent/command.go
nomad/autopilot_test.go
nomad/client_rpc_test.go
nomad/config.go
nomad/heartbeat_test.go
nomad/leader_test.go
nomad/operator_endpoint_test.go
nomad/plan_apply_test.go
nomad/testing.go
testutil/wait.go
website/source/guides/operations/autopilot.html.md

Update default raft protocol to version 3

---

website/source/guides/stateful-workloads/host-volumes.md
website/source/guides/stateful-workloads/portworx.html.md
website/source/guides/stateful-workloads/stateful-workloads.html.md
website/source/layouts/guides.erb

Based on the existing portworx guide
depends on #6211

docs: Add Persistent Workload using Host Volumes guide 

---

CHANGELOG.md

update changelog for 0.10

---

Vagrantfile
scripts/vagrant-linux-priv-cni.sh

Needed this for testing of https://github.com/hashicorp/nomad/pull/6252

add CNI plugins to Vagrant install

---

website/source/docs/job-specification/connect.html.md
website/source/docs/job-specification/index.html.md
website/source/docs/job-specification/proxy.html.md
website/source/docs/job-specification/sidecar_service.html.md
website/source/docs/job-specification/sidecar_task.html.md
website/source/docs/job-specification/task.html.md
website/source/docs/job-specification/upstreams.html.md
website/source/layouts/docs.erb

Initial placeholder connect docs

---

website/source/guides/upgrade/upgrade-specific.html.md

upgrade guide for 0.10.0

---

website/source/guides/security/acl.html.markdown

These were added in #5632, so we needed to add them to the guide.  Reflowed whitespace.

Docs: Added alloc_exec and alloc_node_exec capabilities

---

CHANGELOG.md
website/source/docs/job-specification/service.html.md
website/source/guides/integrations/consul-connect/index.html.md

Tweak wording in changelog to match other entries.

docs: mention task field for checks

---

website/source/docs/job-specification/network.html.md
website/source/docs/job-specification/service.html.md

Start of docs for group level service and network stanza.

---

client/logmon/logging/rotator.go

this PR fix https://github.com/hashicorp/nomad/issues/6309

close file handle when FileRotator object will closed.

---

website/source/docs/job-specification/template.html.md

Added an example of using multiple template stanzas to render individual template files for a PKI cert, key, and CA cert.  Added a note about how these value from the underlying query is shared among the templates.
One additional unrelated link change, just because having it span a line break made me sad.

Added vault PKI example with separate cert files

---

website/source/docs/job-specification/volume.html.md
website/source/docs/job-specification/volume_mount.html.md
website/source/layouts/docs.erb

Fixes `volume` stanza and broken link

Website doc fixes

---

ui/tests/acceptance/allocation-detail-test.js
ui/tests/acceptance/task-detail-test.js

These are still flapping despite #6343 😢

UI: Remove proxy tag tests again

---

website/source/docs/drivers/external/index.html.md
website/source/docs/drivers/external/pot.html.md
website/source/layouts/docs.erb

rename file and index.html changes
Update docs.erb
Update pot-task-driver.html.md
Added new external driver for Pot to nomad documentation

Added documentation for nomad pot driver.

---

.circleci/config.yml
README.md
appveyor.yml
scripts/release/mac-remote-build
scripts/vagrant-linux-priv-go.sh

To get fix for https://github.com/golang/go/issues/34540 .

Use golang 1.12.10

---

website/source/downloads.html.erb

Specify RHEL7, RHEL8, CentOS7, CentOS8
Specify beta1 for 0.10 (beta2 coming soon? :wink: )

clarify rhel/centos and beta1

---

terraform/aws/env/us-east/main.tf
terraform/aws/env/us-east/versions.tf
terraform/aws/modules/hashistack/hashistack.tf
terraform/aws/modules/hashistack/versions.tf

Upgrading Terraform code to be compatible with TF 0.12+

Upgrade Nomad terraform directory for TF 0.12+

---

website/source/guides/stateful-workloads/host-volumes.md

* Added read_only to each volume-related stanza to highlight them (re: #6411. Thanks to @spuder for the suggestions).
* Style updates

Docs: Updated Host Volumes guide

---

command/agent/agent_endpoint.go
command/agent/agent_endpoint_test.go

Fixes https://github.com/hashicorp/nomad/issues/6430

Redact replication tokens in /agent/self

---

client/allocrunner/interfaces/task_lifecycle.go
client/allocrunner/taskrunner/task_runner_hooks.go
client/allocrunner/taskrunner/task_runner_test.go

Reverts hashicorp/nomad#6445
Restores #6395

Revert "Revert "Use joint context to cancel prestart hooks""

---

website/source/docs/configuration/server.html.md

clarify version for new gc config in server stanza

---

website/source/docs/configuration/consul.html.md

"you may have have" to "you may have".

Update consul.html.md (#6456)

---

.github/ISSUE_TEMPLATE.md
.github/SECURITY.md

Add link to https://www.nomadproject.io/security.html

docs: link to security page on website

---

CHANGELOG.md
website/source/docs/job-specification/sidecar_service.html.md

docs: document service tags for connect sidecar

---

README.md

My website recently moved to a new domain. I've updated the link accordingly.

Update link to new blog

---

website/source/guides/integrations/consul-connect/index.html.md
website/source/guides/stateful-workloads/host-volumes.md

Removed beta download link in connect guide as well.

Added version requirement to new feature guides

---

website/source/guides/load-balancing/fabio.html.md
website/source/guides/load-balancing/load-balancing.html.md
website/source/guides/load-balancing/nginx.html.md
website/source/layouts/guides.erb

* add nginx to load balancing nav menu and fix bullets
* fill out nginx lb guide
* formatting
* change Nginx to NGINX
* add step to verify load balancer config
* update docker image and web app output
* change Nginx to NGINX in main load balancing page
* modify change signal to SIGHUP and add else condition in template stanza to prevent nginx from crashing when no services are available to load balance
* add note about external load balancer
* clarifications and link to reference architecture

Nomad NGINX Load Balancing Guide (#6529)

---

drivers/docker/driver_test.go
website/source/docs/drivers/docker.html.md

Also, add a test case.
Closes #6519

docs: Docker driver supports task user option

---

nomad/plan_queue_test.go

`testing.T.Fatal()` is a convenience function that calls `T.Log()` before `T.FailNow()`. From the godoc:
> FailNow must be called from the goroutine running the test or benchmark function, not from other goroutines created during the test. Calling FailNow does not stop those other goroutines.
This PR changes `TestPlanQueue_Enqueue_Dequeue()` to use an error channel instead of relying on `testing.T.Fatal()` inside a goroutine. It also closes `resCh` and `errCh` from inside the goroutine once they are done.

nomad: fix test goroutine

---

CHANGELOG.md
website/source/api/agent.html.md
website/source/docs/commands/monitor.html.md.erb
website/source/layouts/docs.erb

docs for monitor command and api, add monitor to changelog

Monitor docs

---

nomad/eval_broker_test.go

This removes a `T.Fatal()` from the goroutine in `TestEvalBroker_PauseResumeNackTimeout()`, and also has some logging tweaks to improve readability.

TestEvalBroker_PauseResumeNackTimeout Goroutine

---

CHANGELOG.md
nomad/job_endpoint_hook_connect.go
nomad/job_endpoint_hook_connect_test.go
nomad/structs/structs.go

nomad: fix bug that didn't allow for multiple connect services in same tg

---

nomad/eval_broker_test.go

This is a copypasta application of the goroutine error handling scheme I've used in a couple of recent pull requests, https://github.com/hashicorp/nomad/pull/6593 https://github.com/hashicorp/nomad/pull/6649/

TestEvalBroker_Dequeue_Blocked() Goroutine

---

nomad/client_agent_endpoint.go

return after forwarding request to specific node

return after request has been forwarded

---

nomad/eval_broker_test.go

This PR is the last in a series that remove `T.Fatal()` from test goroutines in `eval_broker_test.go`.

nomad: TestEvalBroker_Dequeue_Empty_Timeout() Goroutine

---

website/source/docs/drivers/external/firecracker-task-driver.html.md

Small fixes from legacy markup; some trailing whitespace.  Pulled defaults into prose.

linter fixes

---

website/source/docs/drivers/external/firecracker-task-driver.html.md
website/source/docs/drivers/external/index.html.md
website/source/docs/drivers/external/lxc.html.md
website/source/layouts/docs.erb

Publish documentation updates for task drivers from #6654 and #6640

Publish task driver doc updates

---

api/nodes.go

Update MonitorDrain comment to indicate channel is closed on errors

---

dist/systemd/nomad.service

Set OOMScoreAdjust within systemd dist example

---

command/agent/http_test.go

test rootfallthrough handler

---

website/source/docs/commands/alloc.html.md

Not sure who is best to review sorry 🤔

Docs: fix broken alloc signal link

---

.circleci/config.yml
.circleci/config/commands/run-tests.yml
client/client_test.go

Improvements to client tests.
Best reviewed commit by commit.

CI and Test tweaks

---

CHANGELOG.md
website/source/downloads.html.erb

I'll add a link to the Docker Container Cleanup line item when they're posted.

Changelog updates and download link for 0.10.2-rc1

---

website/source/docs/internals/plugins/devices.html.md
website/source/docs/internals/plugins/task-drivers.html.md

added the device plugin authoring guide, made minor formatting changes to task driver plugin authoring guide.

device plugin authoring guide

---

website/source/docs/internals/plugins/devices.html.md
website/source/docs/internals/plugins/task-drivers.html.md

added the device plugin authoring guide, made minor formatting changes to task driver plugin authoring guide.
cherry-pick of #6751

cherry-pick: device plugin authoring guide

---

website/source/docs/drivers/docker.html.md
website/source/guides/upgrade/upgrade-specific.html.md

Incorporate suggestions in https://github.com/hashicorp/nomad/pull/6762#pullrequestreview-321716747
Thanks @angrycub

docs: address more GH-6762 review comments

---

.circleci/.gitattributes
.circleci/config.yml
.circleci/config/commands/install-circleci-local-cli.yml
.circleci/config/config.yml
.circleci/config/jobs/lint-go.yml
.circleci/config/workflows/build-test.yml

Best reviewed commit by commit.

Further tweaks to CircleCI build scripts

---

plugins/shared/cmd/launcher/command/device.go

Remove trace level logs that contain configuration contents, to avoid potentially leaking secrets into the logs.

Plugins device: remove trace level containing config contents

---

README.md

Following the Consul pattern of using shields.io with brand colors

Added Discuss badge to README

---

client/logmon/client.go

Add an RPC timeout for logmon.  In
https://github.com/hashicorp/nomad/issues/6461#issuecomment-559747758 ,
`logmonClient.Stop` locked up and indefinitely blocked the task runner
destroy operation.
This is an incremental improvement.  We still need to follow up to
understand how we got to that state, and the full impact of locked-up
Stop and its link to pending allocations on restart.

logmon: add timeout to RPC operations

---

website/source/guides/web-ui/index.html.md

Corrected link to Nomad UI track from comments in #6876

docs: Fix bad link to UI Guide track

---

command/node_drain.go
command/node_eligibility.go

@nickethier is to be forgiven for making these typos. :P
I came across this in nomad v0.10.2.

Fix typo, Ethier -> Either

---

website/source/docs/configuration/consul.html.md

Because this is an easy misconfig, it is probably worth highlighting

[docs] Change consul agent note to callout

---

api/csi.go
api/csi_test.go
command/agent/csi_endpoint.go
command/agent/http.go
contributing/checklist-command.md
nomad/csi_volume_endpoint_test.go
nomad/rpc.go

API client support for new CSI Volume server side endpoints. Closes #6910

CSI Volumes API Client

---

plugins/csi/client.go
plugins/csi/client_test.go
plugins/csi/fake/client.go
plugins/csi/plugin.go
plugins/csi/testing/client.go

All of these RPCs are similar enough that resolving local merge conflics
is uhhh fun :sob:

csi: Add NodePublishVolume RPCs

---

plugins/csi/client.go
plugins/csi/client_test.go
plugins/csi/fake/client.go
plugins/csi/plugin.go
plugins/csi/testing/client.go

Finally, the last one of these for a while! - This adds support for the
NodeUnpublishVolume RPC!

csi: Support for NodeUnpublishVolume RPCs

---

client/pluginmanager/csimanager/volume.go
client/pluginmanager/csimanager/volume_test.go
plugins/csi/client.go
plugins/csi/fake/client.go
plugins/csi/plugin.go

This is the minimum viable work for unstaging volumes, with #7029 filled
as a follow up ticket for implementing tracking of volumes on
mount/unmount when staging is required.

csi: Initial support for unstaging volumes

---

nomad/node_endpoint.go
nomad/node_endpoint_test.go

For #7036 
When an alloc is marked terminal, and after node unstage/unpublish have been called, the client will sync the terminal alloc state with the server via `Node.UpdateAlloc` RPC.
This changeset implements releasing the volume claim for each volume associated with the terminal alloc. It doesn't yet implement the RPC call we need to make to the `ControllerUnpublishVolume` CSI RPC. (That is blocked by #6903 )

csi: implement releasing volume claims for terminal allocs

---

client/pluginmanager/csimanager/instance.go

Sorry I missed this :see_no_evil:

csimanager: Instantiate fingerprint manager's client

---

client/pluginmanager/csimanager/fingerprint.go
client/pluginmanager/csimanager/instance.go

This PR removes the fairly complicated locking that was involved during
the setup of a volume manager by replacing them with two
block-until-close channels.
I'm not too happy with storing state on the fingerprinter, but we could
potentially replace the single bool with `lastSuccessfulFingerprint` or
similar if we want to expand this rather than replacing it.

csimanager: Cleanup volumemanager setup

---

nomad/csi_endpoint.go
nomad/csi_endpoint_test.go

This commit refactors the ACL code for the CSI endpoint to support
environments that run without acls enabled (e.g developer environments)
and also provides an easy way to restrict which endpoints may be
accessed with a client's SecretID to limit the blast radius of a
malicious client on the state of the environment.

csi_endpoint: Support No ACLs and restrict Nodes

---

command/agent/job_endpoint.go
nomad/structs/csi.go
scheduler/feasible.go
scheduler/feasible_test.go

This PR does a few small changes to ensure that CSI Volumes may be
scheduled within a cluster. It's taken primarily from #7095 with cleaned
up commit messages.

csi: Scheduling fixes rollup

---

nomad/endpoints_oss.go
nomad/fsm_registry_oss.go
nomad/leader_oss.go
nomad/search_endpoint_oss.go
nomad/state/state_store_oss.go
scheduler/generic_sched_oss.go
scheduler/scheduler_oss.go
scheduler/stack_oss.go

include pro in a few oss.go files to align with https://www.hashicorp.com/products/nomad/pricing/

include pro tag in serveral oss.go files

---

contributing/checklist-command.md
contributing/checklist-jobspec.md

docs: explicitly callout checking for prior art

---

client/client.go
command/agent/agent.go
command/agent/agent_endpoint_test.go
command/agent/fs_endpoint_test.go
command/agent/helpers_test.go
command/agent/http_test.go
command/agent/metrics_endpoint_test.go
command/agent/testagent.go
e2e/vault/vault_test.go
nomad/config.go
nomad/rpc_test.go

Smattering of test and data race (mostly test only) fixes. Comments and commit messages should explain the individual bits.

Fix some race conditions and flaky tests

---

CHANGELOG.md
website/pages/docs/job-specification/service.mdx

Documents https://github.com/hashicorp/nomad/issues/2057

docs: document enable_tag_override field for service stanzas

---

README.md

rawgit image is not longer available, point to github blob for now

rawgit has reached EOL, point to github blob

---

command/agent/http_oss.go

pro endpoints now align with oss

inlude pro in http_oss.go

---

website/pages/home/index.jsx

Homepage typo fix

---

website/pages/intro/index.mdx

moves up youtube intro video on the /intro page - per suggestion from dev-rel

website: move up nomad intro yt video

---

client/pluginmanager/csimanager/volume.go

Sorry - Forgot to cleanup this TODO earlier

csimanager/volume: Update MountVolume docstring

---

website/lib/consent-manager-config.js

Accidentally had the wrong analytics tracker in here before 😭

[website] analytics correction

---

website/package-lock.json
website/package.json

This makes an update to the downloads page to more flexibly accommodate prereleases

[website] upgrade deps, product-downloader

---

client/allocrunner/csi_hook.go
nomad/client_csi_endpoint.go
nomad/client_rpc.go
nomad/csi_endpoint.go
nomad/csi_endpoint_test.go
nomad/state/state_store.go
nomad/structs/csi.go

Determine plugin `ControllerRequired` from both the presence of a controller and it supporting the publish/unpublish workflow.

csi: csi-hostpath plugin unimplemented error on controller publish

---

acl/acl.go
acl/policy.go
acl/policy_test.go
nomad/core_sched_test.go
nomad/csi_endpoint.go
nomad/csi_endpoint_test.go
nomad/job_endpoint.go
nomad/job_endpoint_test.go
nomad/mock/acl.go
nomad/search_endpoint_oss.go

fixes https://github.com/hashicorp/nomad/issues/7305

csi: implement volume ACLs

---

command/monitor.go

#4471 update log output to clarify that nodes were filtered out rather than down

clarify log output

---

acl/acl.go
acl/policy.go
acl/policy_test.go
nomad/csi_endpoint.go
nomad/csi_endpoint_test.go
nomad/job_endpoint.go
nomad/job_endpoint_test.go
nomad/testing.go

csi: ACLs for plugin endpoints

---

website/package-lock.json
website/package.json
website/pages/_app.js
website/pages/style.css

Add Share Your Story Alert

---

nomad/rpc_test.go

The test starts enough connections to hit the limit, then closes the
connection and immediately starts one expecting the new one to succeed.
We must wait until the server side recognizes the connection
closing and free up a limits slot.  The current test attempts to achieve
that by waiting to get an error on conn.Read, however, this error is
returned from local client without waiting for server update.
As such, I change the logic so it retries on connection rejection but
force the first non-EOF failure to be a deadline error.

Deflake TestRPC_Limits_Streaming test

---

e2e/csi/csi.go

This fixes a sloppy error on my part.

csi: fix setup error in e2e test

---

scheduler/feasible.go

The `FilterConstraintCSIVolumeExhaustedTemplate` error message was not in use, and the error messages coming from the scheduler were too broad to be useful in debugging issues. This adds specific error messages for failing claims.
Results:
```
▶ nomad job run csi/input/use-ebs-volume.nomad
==> Monitoring evaluation "4d6d0167"
Evaluation triggered by job "use-ebs-volume"
Evaluation within deployment: "927be2a6"
Evaluation status changed: "pending" -> "complete"
==> Evaluation "4d6d0167" finished with status "complete" but failed to place all allocations:
Task Group "group" (failed to place 1 allocation):
* Constraint "CSI volume ebs-vol0 has exhausted its available writer claims or is read-only" filtered 2 nodes
```

csi: improve error messages from scheduler

---

client/acl.go
client/acl_test.go
command/agent/agent.go
command/agent/agent_oss.go
command/agent/command.go
command/agent/config.go
command/agent/config_parse.go
command/agent/config_parse_test.go
command/agent/config_test.go
command/agent/event/event.go
command/agent/http.go
command/agent/http_oss.go
command/agent/testdata/basic.hcl
command/agent/testdata/basic.json
command/agent/testdata/sample0.json
command/agent/testdata/sample1/sample2.hcl
jobspec/test-fixtures/basic.hcl
nomad/acl.go
nomad/acl_test.go
nomad/structs/config/audit.go
nomad/structs/config/audit_test.go

Agent config and HCL for events/auditing

Audit config, seams for enterprise audit features

---

.circleci/config.yml
.circleci/config/commands/install-consul.yml
.circleci/config/commands/install-golang.yml
.circleci/config/commands/install-vault.yml
.circleci/config/config.yml
.circleci/config/jobs/build-darwin-binaries.yml
.circleci/config/workflows/build-test.yml
scripts/travis-consul.sh
scripts/travis-vault.sh
scripts/vagrant-linux-priv-cni.sh
scripts/vagrant-linux-priv-consul.sh
scripts/vagrant-linux-priv-dev.sh
scripts/vagrant-linux-priv-go.sh
scripts/vagrant-linux-priv-protoc.sh
scripts/vagrant-linux-priv-vault.sh
scripts/vagrant-linux-unpriv-ui.sh

This is meant to be a basic check to ensure that the project at least compiles in darwin.  Would have helped protect against issues like https://github.com/hashicorp/nomad/pull/7355
As part of that, switch to using `curl` instead `wget` in our scripts, mostly because CircleCI has curl but not wget.

build darwin binaries in CI

---

command/alloc_status.go
command/alloc_status_test.go

Display task lifecycle info in `nomad alloc status <alloc_id>` output.
I chose to embed it in the Task header and only add it for tasks with
lifecycle info.
Also, I chose to order the tasks in the following order:
1. prestart non-sidecar tasks
2. prestart sidecar tasks
3. main tasks
The tasks are sorted lexicographically within each tier.
Sample output:
```
$ nomad alloc status 6ec0eb52
ID                  = 6ec0eb52-e6c8-665c-169c-113d6081309b
Eval ID             = fb0caa98
Name                = lifecycle.cache[0]
[...]
Task "init" (prestart) is "dead"
Task Resources
CPU        Memory       Disk     Addresses
0/500 MHz  0 B/256 MiB  300 MiB
[...]
Task "some-sidecar" (prestart sidecar) is "running"
Task Resources
CPU        Memory          Disk     Addresses
0/500 MHz  68 KiB/256 MiB  300 …
```

cli: show lifecycle info in alloc status

---

command/agent/agent.go
command/agent/agent_oss.go
command/agent/event/event.go

renaming Eventer to Auditor to make more explicit

make auditor interface more explicit

---

nomad/csi_endpoint_test.go
nomad/state/state_store.go
nomad/state/state_store_test.go
nomad/structs/csi.go
nomad/structs/csi_test.go
scheduler/feasible.go
scheduler/scheduler.go
scheduler/stack.go

csi: the scheduler allows a job with a volume write claim to be updated

---

nomad/state/state_store.go
nomad/state/state_store_test.go
nomad/structs/csi.go

csi: volume deregister fails for volumes actively in use

---

website/data/api-navigation.js
website/pages/api-docs/plugins.mdx
website/pages/api-docs/volumes.mdx

Completes https://github.com/hashicorp/nomad/issues/7091
HTTP API documentation for the `/plugin` and `/volume` endpoints, to
support CSI.

CSI: HTTP API docs

---

website/data/docs-navigation.js
website/pages/docs/configuration/audit.mdx
website/pages/docs/configuration/index.mdx
website/pages/docs/enterprise/index.mdx

Docs for enterprise audit logging

docs: audit logging

---

acl/policy.go
acl/policy_test.go
api/jobs_test.go
api/scaling.go
api/tasks.go
api/tasks_test.go
api/utils.go
jobspec/parse_test.go
jobspec/test-fixtures/tg-scaling-policy.hcl
nomad/job_endpoint.go
nomad/job_endpoint_test.go
nomad/mock/mock.go
nomad/scaling_endpoint_test.go

addressing some of the review comments from https://github.com/hashicorp/nomad/pull/7409

more testing for scaling API

---

CHANGELOG.md

Doing this in a PR and not directly to master just to avoid conflicts with a bunch of other folks who will be trying to get this in today.

add changelog entries for 0.11.0

---

CHANGELOG.md

tweaks 0.11.0 changelog

---

website/data/version.js
website/pages/downloads/index.jsx

Also, update latest release to 0.10.5

Prepare website for 0.11.0-beta1 release

---

ui/app/components/exec/task-group-parent.js

This closes #7476. The decomposition of computed properties
is necessary to avoid nested aggregate dependent keys; the
previous dependent key of `taskGroup` will be inadequate
when the sidebar becomes live-updating.

UI: Change determination of exec sidebar active tasks

---

website/pages/docs/schedulers.mdx

Per our conversation, removing deployments.

[docs] System scheduler doesn't do deployments.

---

website/package-lock.json
website/package.json
website/pages/style.css

Fixes for a couple trailing issues post anchor link fixes:
- Permalinks are no longer swallowed by the floating header
- A bug causing jump to links to not work has been resolved

Anchor Links Cleanup

---

command/agent/config_parse_test.go
command/agent/testdata/basic.hcl
command/agent/testdata/basic.json
command/agent/testdata/sample0.json
command/agent/testdata/sample1/sample2.hcl
nomad/structs/config/audit_test.go
website/pages/docs/configuration/audit.mdx

/ui/ and /v1/agent/health are not audited endpoints, update docs and examples to a more realistic example

update audit examples to an endpoint that is audited

---

client/allocrunner/csi_hook.go
client/pluginmanager/csimanager/fingerprint_test.go

Fixes https://github.com/hashicorp/nomad/issues/7278 (once https://github.com/hashicorp/nomad/pull/7549 is done too).

csi: annotate remaining missing cancellation contexts

---

api/services.go
command/agent/job_endpoint.go
jobspec/parse_service.go
jobspec/parse_test.go
jobspec/test-fixtures/tg-service-check-expose.hcl
nomad/job_endpoint.go
nomad/job_endpoint_hook_expose_check.go
nomad/job_endpoint_hook_expose_check_test.go
nomad/job_endpoint_test.go
nomad/structs/diff_test.go
nomad/structs/services.go
nomad/structs/structs_test.go

approved in https://github.com/hashicorp/nomad/pull/7515
(but that was merged into another dev branch)
this one targets master

merge changes for expose checks percheck

---

ui/app/controllers/exec.js
ui/tests/acceptance/exec-test.js

This closes #7469. Trivial thanks to localStorageProperty! 🥳

UI: Add localStorage persistence of exec command

---

website/pages/docs/job-specification/lifecycle.mdx

Added a link to the learn guides; re-wrapped text

[docs] Adding link to learn track

---

nomad/csi_endpoint_test.go
nomad/node_endpoint_test.go
nomad/state/state_store.go
nomad/state/state_store_test.go

Validate namespaces on volume registration

csi: volume validate namespace

---

website/data/docs-navigation.js
website/pages/docs/internals/plugins/csi.mdx

For https://github.com/hashicorp/nomad/issues/7467
Summarizes the internal RFCs for plugins and volume lifecycles.

csi: internals docs

---

website/pages/docs/configuration/audit.mdx

make placement of filter and sink stanzas clearer

make placement of filter and sinks stanzas clearer

---

e2e/e2eutil/utils.go

gometa isn't the Hashi standard package for testing, and it dumps big gnarly stack traces in the case of failures, rather than reasonable error messages. This removes it from the e2eutils package.
We still have a few other places with `gometa` in the e2e suite, but they'll take a bit more work to finish.

e2e: remove gometa from e2eutils

---

scheduler/feasible.go

Fixes a null pointer exception reported by @chenjpu: https://github.com/hashicorp/nomad/issues/7625#issuecomment-609552824

scheduler: prevent a reported NPE for CSI

---

website/pages/_app.js
website/pages/downloads/index.jsx

update banner from "Beta" to "Release Candidate"

docs: add 0.11.0-rc1 to download page

---

dist/README.md
dist/upstart/nomad.conf

Fixes https://github.com/hashicorp/nomad/issues/7598

dist: make README consistent with service unit

---

website/pages/_app.js

The Webinar has just completed today, adjusting the alert to point the blog post.

website: Adjust the website alert to point to the blog post

---

demo/vagrant/Vagrantfile

as per subject. Thought I'd update it.

demo/vagrant/Vagrantfile: Update Nomad version (0.10.4 -> latest, 0.10.5)

---

website/pages/docs/integrations/consul-connect.mdx

fixup references in connect docs

---

CHANGELOG.md

Changelog entries for previously-merged PRs

changelog entries for 0.11.1 bugfixes

---

api/jobs.go

api: fix some documentation typos

---

website/data/api-navigation.js
website/pages/api-docs/index.mdx

Added a link to the API Overview page to the sidebar.

[docs] Adding API homepage to sidebar.

---

ui/app/styles/components.scss
ui/app/styles/components/exec-button.scss
ui/app/styles/components/exec-window.scss
ui/app/templates/exec-loading.hbs
ui/app/templates/exec.hbs

UI: update exec styles to match conventions

---

nomad/structs/generate.sh

a little simplification now that there is a release of github.com/hashicorp/go-msgpack

structs: give codecgen import

---

scheduler/rank_test.go

Somehow I missed this one - potentially post a rebase :(.

Follow up fix for spread

---

client/allocdir/fs_windows.go
drivers/docker/driver.go
drivers/docker/fingerprint.go
drivers/docker/win32_volume_parse.go

This PR fixes issue [#2633](https://github.com/hashicorp/nomad/issues/2633) for Windows Server 2019.

Run Linux Images (LCOW) and Windows Containers side by side

---

api/operator.go
command/license.go
command/license_get.go
command/license_get_test.go
command/license_put.go

removes unused struct fields and validity checks that will be handled by returning errors instead

update license command output to reflect api changes

---

command/license.go

updates structure of license command output

update license output

---

website/pages/docs/job-specification/volume_mount.mdx

Fixes https://github.com/hashicorp/nomad/issues/7899

volume_mount doc tweak

---

ui/app/templates/components/client-node-row.hbs
ui/tests/acceptance/clients-list-test.js

Follow up to https://github.com/hashicorp/nomad/pull/7874 .

Add tests for running allocation client count

---

CHANGELOG.md

Changelog additions for bugs and improvements to the UI

---

ui/app/adapters/plugin.js
ui/app/utils/properties/watch.js

UI: Make the Plugin adapter extend Watchable

---

api/operator.go
command/commands.go

Reverts hashicorp/nomad#7922
Adding license cli commands back in

Revert "disable license cli commands"

---

website/pages/home/index.jsx

This PR adds another item to `<CaseStudyCarousel />` to highlight the [new community story](https://www.hashicorp.com/blog/nomad-community-story-navi-capital)

Add Case Study Carousel Item

---

ui/app/components/distribution-bar.js
ui/app/components/gauge-chart.js
ui/app/components/line-chart.js
ui/app/helpers/lazy-click.js
ui/app/initializers/app-env.js
ui/app/mixins/window-resizable.js

We've actually done a pretty good job at not using jQuery extensively so this is a small changeset.

UI: Remove jQuery from the rest of application code

---

ui/config/optional-features.json
ui/package.json
ui/yarn.lock

UI: Remove jQuery

---

client/client.go
client/enterprise_client_oss.go

give enterpriseclient a logger

---

api/internal/testutil/server.go
client/alloc_endpoint_test.go
drivers/shared/executor/executor_test.go

Few more test deflate attempts.  Best reviewed commit-by-commit.

More Test deflaking - 2020-05-31 edition

---

website/data/docs-navigation.js
website/pages/docs/drivers/external/iis.mdx
website/pages/docs/drivers/external/index.mdx

Cherry-picking #8079 onto the stable-website branch.

Deploy Windows IIS docs

---

vendor/github.com/docker/docker/pkg/archive/archive.go
vendor/github.com/docker/docker/pkg/archive/archive_linux.go
vendor/github.com/docker/docker/pkg/archive/archive_windows.go
vendor/github.com/docker/docker/pkg/idtools/utils_unix.go
vendor/github.com/docker/docker/pkg/system/chtimes_unix.go
vendor/github.com/docker/docker/pkg/system/chtimes_windows.go
vendor/github.com/docker/docker/pkg/system/filesys_windows.go
vendor/github.com/docker/docker/pkg/system/path_windows.go
vendor/github.com/docker/docker/pkg/system/process_windows.go
vendor/github.com/docker/docker/pkg/system/rm.go
vendor/github.com/docker/docker/pkg/system/syscall_unix.go
vendor/github.com/docker/docker/pkg/system/syscall_windows.go
vendor/github.com/docker/docker/pkg/system/xattrs_linux.go

Noticed some local vendored files get modified with `go mod vendor`.

run go mod vendor

---

website/pages/home/index.jsx

🔍 [Preview](https://deploy-preview-8152--nomad-website.netlify.app/)
Adds a testimonial card from Cloudflare.

website: add cloudflare testimonial

---

website/pages/docs/job-specification/periodic.mdx

Point to HashiCorp fork of library

docs: update cronexpr github link

---

CHANGELOG.md

bugfix belongs in 0.12.0 not 0.11.3

move bugfix to correct version

---

api/operator.go
vendor/github.com/hashicorp/nomad/api/jobs.go
vendor/github.com/hashicorp/nomad/api/operator.go

OSS component to allowing a raw request body instead of json encoded string for license put endpoint

allow raw body instead of JSON encoded string

---

CHANGELOG.md
command/commands.go
command/commands_oss.go
nomad/alloc_endpoint_test.go
scheduler/generic_sched.go

Few tiny OSS followups from recent work.  I consolidated them as each is very small on its own.  Best reviewed by examining each commit individually.

Assorted follow ups 

---

website/data/alert-banner.js

Update banner contents

---

website/data/version.js
website/pages/docs/upgrade/upgrade-specific.mdx
website/pages/downloads/index.jsx

Also, pick stable-website changes to be merged in master.

Docs: note agent unresponsive

---

ui/app/components/global-search/control.js

This will fix a linting error introduced in 068ad06.

UI: Remove non-classic use of this.set

---

website/pages/resources/index.jsx

Per Slack conversation on April 30 with Schmichael and Gale. Aligning navigation verbiage with other .io sites (Community instead of Resources). Page updates remove Gitter and Mailing List links to direct users to the Forum. Also changed some header content and positioning. If this all doesn't work based on full content of page, happy to brainstorm a better approach. Thank you for reviewing!

Update resources index.jsx

---

nomad/structs/structs.go

docs: add comments to structs.Port struct

---

CHANGELOG.md

docs: tweak changelog wording for multiregion deployments

---

website/pages/docs/job-specification/multiregion.mdx

Found while working on the learn guide.

docs: spellcheck fix for multiregion

---

website/pages/home/index.jsx

[Preview Link](https://deploy-preview-8254--nomad-website.netlify.app/)
---
This PR adds a quote from BetterHelp to the `<CaseStudyCarousel />` component on the landing page.

[Website] Add quote for CaseStudy carousel from BetterHelp

---

website/pages/docs/devices/nvidia.mdx

This PR updates the docs for the Nvidia plugin configuration so it aligns (and works) with the docs for general plugin configuration.

Fixes Nvidia plugin configuration docs (#7711)

---

website/pages/docs/install/production/deployment-guide.mdx

"Nomad" is already included in all page titles, this change makes things more consistent!

Update deployment guide docs title

---

website/_redirects

cherry-picked from `stable-website`: 666b5ac35bbeeccee4fdc2d1713a0eda13b4b1ec

added redirect for /docs/index.html

---

website/_redirects

cherry-pick from https://github.com/hashicorp/nomad/pull/8308

[docs] cherry-pick website redirect

---

GNUmakefile
tools/go.mod
tools/go.sum
tools/tools.go

run hclogvet to ensure that key/value log statement pairs are balanced

add hclog vet to check step
