hashicorp/nomad

- nomad/search_endpoint.go
- nomad/search_endpoint_test.go
When checking if a token is allowed to query the search endpoints we need to return an error if the search context includes `node_pool` and the token doesn't have access to _any_ pool. This prevents returning an empty list instead of a permission denied error.
> np: fix node pool search permission check

- drivers/docker/docklog/docker_logger_test.go
- drivers/docker/driver_test.go
- drivers/docker/driver_windows_test.go
- drivers/docker/reconcile_dangling_test.go
- testutil/container_images.go
In pursuit of moving Windows tests to GitHub Actions (#17103),
* "allow" (don't try to drop) linux capabilities in the docker test driver harness (near-term workaround for #15181)
* refactor to allow different busybox images since windows containers need to be the same version as the underlying OS, and we're moving from 2016 to 2019 (images published via: [hashicorp/busybox-windows](https://github.com/hashicorp/busybox-windows))
* one docker test was flakey from apparently being a bit slower on windows, so add Wait()
> Update tests to work with newer Windows

- .circleci/config.yml
- .github/actionlint.yml
- .github/actions/install-vault/action.yml
- .github/workflows/actionlint.yml
- .github/workflows/backport.yml
- .github/workflows/build.yml
- .github/workflows/ember-assets.yml
- .github/workflows/ember-test-audit.yml
- .github/workflows/lock.yml
- .github/workflows/release.yml
- .github/workflows/semgrep.yml
- .github/workflows/test-core.yaml
- .github/workflows/test-e2e.yml
- .github/workflows/test-ui.yml
- .github/workflows/test-windows.yml
The primary goal here is to migrate our remaining CI workflows from Circle CI to GitHub Actions, namely: test-e2e, test-ui, and test-windows.
Related test changes to enable that were split out to separate PRs: #17401 and #17399
Extra-curricularly, as part of the overall migration effort company-wide, this also includes some standardization such as:
* explicit permissions:read on various workflows
* pinned action version shas (per [hashicorp/security-public-tsccr](https://github.com/hashicorp/security-public-tsccr))
* actionlint, which among other things runs shellcheck on GHA run steps
> Standardize on GitHub Actions for CI

- api/nodes.go
- api/nodes_test.go
- client/client_test.go
- command/agent/agent.go
- command/agent/command.go
- command/agent/command_test.go
- command/agent/config.go
- command/agent/config_test.go
- command/node_status.go
- nomad/fsm_test.go
- nomad/mock/node.go
- nomad/node_endpoint.go
- nomad/node_endpoint_test.go
- nomad/state/state_store.go
- nomad/state/state_store_node_pools.go
- nomad/state/state_store_test.go
- nomad/structs/node_class.go
- nomad/structs/node_class_test.go
- nomad/structs/node_pool.go
- nomad/structs/structs.go
- website/content/api-docs/nodes.mdx
- website/content/docs/commands/agent.mdx
- website/content/docs/commands/node/status.mdx
- website/content/docs/configuration/client.mdx
Add new client configuration `node_pool` to allow assigning a node to a pool. If the node pool does not exist yet, it will be created automatically when the node registers. The built-in `all` node pool is not allowed to be used.
Doc preview:
https://nomad-git-f-node-pools-register-node-hashicorp.vercel.app/nomad/docs/configuration/client#node_pool
> node pools: register a node in a node pool

- nomad/fsm_test.go
- nomad/node_pool_endpoint_test.go
- nomad/state/state_store_test.go
Move tests that assumed canonicalization was been done in the state store to the FSM, where it actually happens, and fix some state store pointer mutation.
> node pools: fix node upsert and state mutation tests

- client/fingerprint/cpu_default_test.go
This PR fixes a racey test where we need to ensure the cpuset cgroup
is setup before trying to fingerprint it.
> test: ensure cpuset cgroup is setup before fingerprinting

- .changelog/17393.txt
- command/agent/command.go
- command/agent/command_test.go
Hi team,
This PR aims to add additional check for missing `path` value in client `host_volume` config. I have added 2 more test cases to validate this change. Please let me know if I need to make any additional changes for this :pray: 
Fixes : https://github.com/hashicorp/nomad/issues/16968
> Add check for missing `path` in client `host_volume` config

- api/event_stream.go
- api/event_stream_test.go
- nomad/state/events.go
- nomad/state/events_test.go
- nomad/state/state_store_node_pools.go
- nomad/stream/event_broker.go
- nomad/stream/event_broker_test.go
- nomad/structs/event.go
- nomad/structs/structs.go
- website/content/api-docs/events.mdx
Add event stream support for node pools. Upsert and delete actions are 
Doc preview:
https://nomad-git-f-node-pools-event-stream-hashicorp.vercel.app/nomad/api-docs/events
> node pools: add event stream support

- api/node_pools.go
- command/agent/node_pool_endpoint.go
- command/agent/node_pool_endpoint_test.go
- nomad/node_pool_endpoint.go
- nomad/node_pool_endpoint_test.go
- website/content/api-docs/node-pools.mdx
Implements the HTTP API associated with the `NodePool.ListJobs` RPC, including the `api` package for the public API. Also fixes a bug in the RPC handler where we were missing handling of the special `all` node pool.
> node pools: implement HTTP API to list jobs in pool

- command/commands.go
- command/node_pool.go
- command/node_pool_info.go
- command/node_pool_jobs.go
- command/node_pool_jobs_test.go
- website/content/docs/commands/node-pool/index.mdx
- website/content/docs/commands/node-pool/jobs.mdx
- website/content/partials/general_options.mdx
- website/data/docs-nav-data.json
_WIP_ this PR current includes everything in https://github.com/hashicorp/nomad/pull/17431. I'll rebase once that's been merged.
> node pools: implement CLI for `node pool jobs` command

- api/node_pools.go
- command/commands.go
- command/node_pool_nodes.go
- command/node_pool_nodes_test.go
- website/content/api-docs/node-pools.mdx
- website/content/docs/commands/node-pool/index.mdx
- website/content/docs/commands/node-pool/list.mdx
- website/content/docs/commands/node-pool/nodes.mdx
- website/data/docs-nav-data.json
Implements the `nomad node pool nodes` command to return the list of nodes in a given node pool.
https://github.com/hashicorp/nomad/pull/17444/commits/5718808c3683147cd0dbdeb00ea29db51accbf7d also has some small drive-by fixes I noticed while ~copying code from~ learning how it was implemented in other places.
Doc preview:
https://nomad-git-f-node-pools-nodes-cli-hashicorp.vercel.app/nomad/docs/commands/node-pool/nodes
> node pool: implement `nomad node pool nodes` CLI

- .changelog/17450.txt
- client/lib/cgutil/cpuset_manager_v2.go
During shutdown of a client with drain_on_shutdown there is a race between
the Client ending the cgroup and the task's cpuset manager cleaning up
the cgroup. During the path traversal, skip anything we cannot read, which
avoids the nil DirEntry we try to dereference now.
Fixes #17439
> client: avoid trying to remove unreadable cgroup

- .github/workflows/test-ui.yml
- ui/mirage/factories/service.js
- ui/package.json
- ui/tests/acceptance/allocation-detail-test.js
- ui/tests/acceptance/job-services-test.js
- ui/tests/acceptance/task-logs-test.js
Uses Ember Exam to parallelize tests; includes a few fixes for tests that are affected by leaks more than others. Surely more'll pop up eventually and we'll patch them when they do.
> [ui] Parallelize ember tests

- .changelog/17455.txt
- client/allocrunner/network_hook.go
- client/allocrunner/network_hook_test.go
- client/allocrunner/network_manager_linux.go
- drivers/docker/driver.go
- drivers/docker/network.go
- plugins/drivers/client.go
This PR fixes a bug where the docker network pause container would not be
stopped and removed in the case where a node is restarted, the alloc is
moved to another node, the node comes back up. See the issue below for
full repro conditions.
Basically in the DestroyNetwork PostRun hook we would depend on the
NetworkIsolationResource field not being nil - which is only the case
if the Client stays alive all the way from network creation to network
teardown. If the node is rebooted we lose that state and previously
would not be able to find the pause container to remove. Now, we manually
find the pause container by scanning them and looking for the associated
allocID.
Fixes #17299
> docker: stop network pause container of lost alloc after node restart

- .changelog/17465.txt
- ui/app/components/allocation-service-sidebar.hbs
- ui/app/components/allocation-service-sidebar.js
- ui/tests/integration/components/allocation-service-sidebar-test.js
Adds a "Health Unknown" indicator and tooltip when the allocation a service is running on is not in a running state.
Previously, any /checks would return `null` and it would optimistically show Healthy for its aggregate status.
> [ui] Don't show a service as healthy when its parent alloc is not running

- command/agent/node_pool_endpoint_test.go
- nomad/leader.go
- nomad/leader_test.go
- nomad/mock/mock.go
- nomad/node_pool_endpoint.go
- nomad/node_pool_endpoint_test.go
- nomad/structs/node_pool.go
Upserts and deletes of node pools are forwarded to the authoritative region, just like we do for namespaces, quotas, ACL policies, etc. Replicate node pools from the authoritative region.
> node pools: replicate from authoritative region

- command/agent/config_parse.go
Add `preemption_config` to the set of keys which should be pruned from the server config as described in https://github.com/hashicorp/nomad/issues/17480. Please note that I do not know of any existing unit tests for this behavior, but I have tested this manually:
```
make bootstrap
make dev
$ cat ../nomad_sandbox/server.config 
{                                                                                                                                                                                                                                                                                      
"data_dir": "/tmp/nomad/server",
"log_level": "TRACE",
"advertise": { …
```
> Add preemption_config to the server extra HCL keys to remove from config

- command/asset/asset.go
- command/asset/pool.nomad.hcl
- command/asset/pool.nomad.json
- command/commands.go
- command/node_pool_init.go
- command/node_pool_init_test.go
- website/content/docs/commands/node-pool/init.mdx
- website/data/docs-nav-data.json
Implement a `nomad node pool init` command that generates an example spec file in either HCL or JSON format.
> node pools: implement `node pool init` command

- .changelog/17526.txt
- command/var_init.go
- website/content/docs/commands/var/init.mdx
The `var init` command was intended to have support for a `-quiet` flag but it was not documented and never parsed.
> cli: fix missing `-quiet` flag for `var init`

- nomad/node_endpoint.go
Fix log messages that currently look like this:
```
[DEBUG] nomad.client: marking node as %s due to missing node pool: EXTRA_VALUE_AT_END=initializing
```
> rpc: fix log message in Node.UpdateStatus

- website/content/docs/operations/metrics-reference.mdx
The docs were missing counter metrics emitted by the task runner around task state changes (ref [`task_runner.go#L797`](https://github.com/hashicorp/nomad/blob/main/client/allocrunner/taskrunner/task_runner.go#L797), [`task_runner.go#L1286-L1314`](https://github.com/hashicorp/nomad/blob/main/client/allocrunner/taskrunner/task_runner.go#L1286-L1314), and [`task_runner.go#L1372`](https://github.com/hashicorp/nomad/blob/main/client/allocrunner/taskrunner/task_runner.go#L1372))
Preview link: https://nomad-nmjpxm52z-hashicorp.vercel.app/nomad/docs/operations/metrics-reference#allocation-metrics
> docs: add missing `client.allocs` metrics

- .changelog/17535.txt
- client/lib/cgutil/cpuset_manager_v2.go
- e2e/isolation/devices_test.go
- e2e/isolation/input/cgroup_devices.hcl
This meant that if any allocation was created or removed, all active DevicesSets were removed from all cgroups of all tasks.
This was most noticeable with "exec" and "raw_exec", as it meant they no longer had access to `/dev` files.
Fixes #12877, and possibly a bunch of other related but different reports in the issue tracker. See https://github.com/hashicorp/nomad/issues/12877#issuecomment-1591666774 for steps how to reproduce this problem, and validate it is actually fixed with this change. Most important piece of context: https://github.com/opencontainers/runc/blob/5cf9bb229feed19a767cbfdf9702f6487341e29e/libcontainer/cgroups/devices/v2.go#L55-L57
Few warnings:
- 4 hours ago I had no idea how cgroups worked, nor how BPF and DevicesSets interacted with cgroups
- 1 hour ago I never …
> Fix DevicesSets being removed when cpusets are reloaded with cgroup v2

- scheduler/feasible.go
- scheduler/feasible_test.go
- website/content/docs/runtime/interpolation.mdx
Although most of the time jobs will be assigned to a single node pool, users may want to set the node pool to "all" and then constraint to a subset of node pools. Add support for setting a contraint like `${node.pool}`.
> node pools: support `node.pool` constraint in scheduler

- command/job_status.go
If the `nomad` CLI is used to access a cluster running a version that does not include node pools the command will `nil` panic when trying to resolve the job's node pool.
Thanks @gulducat for the report!
> cli: prevent panic if job node pool is nil

- terraform/azure/modules/hashistack/hashistack.tf
Hi team,
This PR is my attempt to fix the syntax error highlighted in issue https://github.com/hashicorp/nomad/issues/17464
- `address_prefixes` is the latest arg for `azurerm_subnet` resource ([link](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/subnet#address_prefixes)) . The last supported version for `address_prefix` was in [3.2.0](https://registry.terraform.io/providers/hashicorp/azurerm/3.2.0/docs/resources/subnet)
- `allocation_method` replaces `public_ip_address_allocation`. Sorry the version was too old I could not find any doc earlier than 2.0 that uses `public_ip_address_allocation`. The intial code commit was 6 years ago so I guess it goes further than that :smile: 
- A few smaller changes from HCL ( current format ) to HCL2.
There was no …
> Fix terraform syntax in Azure example due to deprecated tf resource arguments

- api/node_pools.go
- command/agent/node_pool_endpoint_test.go
- command/asset/pool.nomad.hcl
- command/asset/pool.nomad.json
- command/node_pool_info.go
- command/node_pool_info_test.go
- nomad/mock/mock.go
- nomad/structs/node_pool.go
- nomad/structs/node_pool_oss.go
- nomad/structs/node_pool_oss_test.go
- nomad/structs/node_pool_test.go
- website/content/docs/commands/node-pool/apply.mdx
- website/content/docs/other-specifications/node-pool.mdx
This PR makes a few general changes to node pool scheduler configuration:
* Rename the HCL spec to `scheduler_config` to match other configuration blocks.
* Add the `memory_oversubscription_enabled` config.
* Make `scheduler_config` an Enterprise feature.
> np: scheduler configuration updates

- .github/workflows/checks.yaml
- .github/workflows/test-core.yaml
- terraform/azure/modules/hashistack/hashistack.tf
Apply `hclfmt` on files in the `terraform` directory and also add a new workflow to run `make check` on paths that are ignored by [`test-core.yaml`](https://github.com/hashicorp/nomad/blob/main/.github/workflows/test-core.yaml) but have content verified by `make check`.
https://github.com/hashicorp/nomad/pull/17601 shows an example where code is changed. Only one instance of `checks.yaml` runs.
https://github.com/hashicorp/nomad/pull/17604 shows an example where only HCL files are changed. Again, only one isntance of `checks.yaml` runs.
I think we may ended up with duplicate runs if a PR changes files in and out of the ignore list, but I think that's relative rare? Except maybe for `website/**` so we could remove it from `checks.yaml`.
> ci: hclfmt files

- nomad/state/schema.go
It's a vague, 3 year old todo. If we want more indexes, we can identify which when coming to design it.
> state: remove vague scaling event schema todo item.

- nomad/state/state_store_variables_test.go
Small piece of admin while starting locking work.
> state: move variables tests to use must library.

- nomad/mock/job.go
Add `MultiregionMinJob()` mock to be used in Enterprise tests. Backporting in case it becomes useful to test bug fixes.
> test: add MultiregionMinJob mock

- .changelog/17619.txt
- nomad/structs/network.go
- nomad/structs/network_test.go
If the dynamic port range for a node is set so that the min is equal to the max, there's only one port available and this passes config validation. But the scheduler panics when it tries to pick a random port. Only add the randomness when there's more than one to pick from.
Adds a test for the behavior but also adjusts the commentary on a couple of the existing tests that made it seem like this case was already covered if you didn't look too closely.
Fixes: https://github.com/hashicorp/nomad/issues/17585
> scheduler: tolerate having only one dynamic port available

- ui/app/components/job-status/panel/deploying.js
"Health Unknown" no longer counts unplaced, failed, etc. allocations.
> [ui] Job status panel legend should only show "health unknown" for running allocs

- ui/app/components/job-status/panel/deploying.hbs
Type "promote" or "fail" to promote/fail your actively-running deployment.
> [ui] Keyboard shortcuts for Promote Canary and Fail Deployment

- ui/app/controllers/clients/index.js
- ui/app/templates/components/client-node-row.hbs
- ui/tests/acceptance/clients-list-test.js
- ui/tests/pages/clients/list.js
The built-in node pool `all` should not be a client filter because nodes are not allowed to register there.
> ui: remove node pool `all` from client list filter

- ui/app/controllers/topology.js
- ui/app/routes/topology.js
- ui/app/styles/components/dashboard-metric.scss
- ui/app/templates/components/topo-viz/datacenter.hbs
- ui/app/templates/components/topo-viz/node.hbs
- ui/app/templates/topology.hbs
- ui/tests/acceptance/topology-test.js
- ui/tests/pages/topology.js
This PR adds some node pool information and interactions to the Topology page.
* Allow filtering nodes by node pool.
* Don't count the `all` node pool in the aggregate metric box.
* Add tooltips to the node and datacenter labels to clarify what they represent.
I know that there's a new tooltip component, but it's currently not available in this branch. I can updated it once everything is merged to `main`.
https://github.com/hashicorp/nomad/assets/775380/ee1b2fb5-4c71-4c3e-b203-1d12f980e53e
> F UI node pool topoviz

- .changelog/17576.txt
- client/fingerprint/host.go
- client/fingerprint/host_test.go
- website/content/docs/runtime/interpolation.mdx
> Feat: add windows `os.build` attribute to host fingerprint

- ui/app/components/job-status/panel/deploying.hbs
- ui/app/components/job-status/panel/steady.hbs
- ui/app/components/job-status/panel/steady.js
- ui/app/styles/components/job-status-panel.scss
- ui/app/templates/components/job-page/parts/title.hbs
- ui/tests/integration/components/job-page/service-test.js
- ui/tests/integration/components/job-status-panel-test.js
An abstracted status to indicate how a job is doing, based on its allocations' clientStatus, compared to what is expected/desired.
Possible states:
Batch/Sysbatch jobs:
- Complete if all are complete
- Running if any are running
- Degraded if any are failed/lost
- Failed if all are failed/lost
Service and System jobs:
- Healthy if all are running
- Recovering if any are "pending" (Note: pending in a non-deploying state means a reschedule has taken place, etc.)
- Degraded if some are failed/lost/unplaced
- Failed if all are failed/lost/unplaced
> [ui] General status for steady-state jobs

- ui/app/models/node-pool.js
- ui/tests/unit/serializers/node-pool-test.js
Add new node pool scheduler configuration to `NodePool` model that was created in https://github.com/hashicorp/nomad/pull/17575 and update serializer test to cover more scenarios. Since `SchedulerConfiguration` is an Enterprise feature, it will be returned as `null` in OSS. It's also comprised of all optional fields, meaning that a node pool like this is valid:
```hcl
node_pool "test" {
scheduler_configuration {}
}
```
> ui: add node pool memory oversubscription config

- .github/workflows/build.yml
- .github/workflows/release.yml
- scripts/vagrant-linux-unpriv-ui.sh
- ui/README.md
Much like the ember-test-audit node version bumps from https://github.com/hashicorp/nomad/pull/17624, this upgrades Node to the current LTS version for our build workflows.
Without this, an older version of node would fail upon storybook installation, and possibly elsewhere.
> Moves to the current LTS release of Node for our build and release workflows

- ui/app/templates/components/job-page/parts/children.hbs
- ui/app/templates/components/job-page/parts/stats-box.hbs
- ui/app/templates/components/job-row.hbs
- ui/tests/acceptance/job-detail-test.js
- ui/tests/acceptance/jobs-list-test.js
- ui/tests/helpers/module-for-job.js
- ui/tests/pages/jobs/detail.js
- ui/tests/pages/jobs/list.js
The namespace, node pool, type, and priority values were already displayed at the page header, so they made the children job table quite crowded.
> ui: remove redundant children jobs table columns

- helper/iterator/iterator.go
- nomad/job_endpoint_hooks.go
- nomad/job_endpoint_test.go
- nomad/structs/node_pool.go
- nomad/structs/node_pool_test.go
- nomad/structs/operator.go
- nomad/structs/operator_test.go
- scheduler/generic_sched.go
- scheduler/generic_sched_test.go
- scheduler/preemption_test.go
- scheduler/rank.go
- scheduler/rank_test.go
- scheduler/scheduler.go
- scheduler/scheduler_system.go
- scheduler/scheduler_test.go
- scheduler/stack.go
- website/content/api-docs/operator/scheduler.mdx
- website/content/docs/job-specification/resources.mdx
Merge global scheduler configuration with the job's node pool scheduler configuration when processing nodes.
> node pools: apply node pool scheduler configuration

- nomad/structs/funcs.go
I was poking around in this code, so thought I would experiment quickly with an improvement to the name generation. I'm not strongly in favour of this, as it makes reading slightly more difficult, but thought I'd raise it to be opinions anyway.
benchmark:
```
goos: darwin
goarch: arm64
pkg: jrasell-experiments/benchmarks
BenchmarkAllocNameOriginal-12    	 9239590	       111.2 ns/op	      80 B/op	       3 allocs/op
BenchmarkAllocNameNew-12         	34172659	        35.10 ns/op	      48 B/op	       1 allocs/op
```
> core: use faster concatenation for alloc name generation.

- .changelog/17645.txt
- ui/app/templates/components/job-page/parts/children.hbs
- ui/app/templates/components/job-row.hbs
- ui/tests/acceptance/job-detail-test.js
- ui/tests/pages/jobs/detail.js
Namespace, job type, and priority are already available from the parent job header, so displaying them in the table caused it to be too crowded.
(Extracted from https://github.com/hashicorp/nomad/pull/17301 as a user-facing change)
> ui: remove redundant columns from child job table

- .changelog/17647.txt
- ui/app/templates/components/topo-viz/datacenter.hbs
- ui/app/templates/components/topo-viz/node.hbs
- ui/tests/integration/components/topo-viz/datacenter-test.js
Add tooltips to labels in nodes and datacenters for the Topology view page to clarify what each value represents.
(Extracted from https://github.com/hashicorp/nomad/pull/17301 as user-facing change)
> ui: add tooltips to the Topology labels

- .changelog/17625.txt
- client/lib/cgutil/cgutil_linux.go
- client/lib/cgutil/cgutil_linux_test.go
- drivers/shared/executor/executor_linux.go
This PR adds a workaround for very old Linux kernels which do not support
the memory swappiness interface file. Normally we write a "0" to the file
to explicitly disable swap. In the case the kernel does not support it,
give libcontainer a nil value so it does not write anything.
Fixes #17448
> client: do not disable memory swappiness if kernel does not support it

- client/client.go
- client/client_test.go
- client/rpc.go
- client/state/db_bolt.go
- client/state/db_error.go
- client/state/db_mem.go
- client/state/db_noop.go
- client/state/interface.go
- client/structs/structs.go
- nomad/acl.go
In Nomad 1.5.3 we fixed a security bug that allowed bypass of ACL checks if the request came thru a client node first. But this fix broke (knowingly) the identification of many client-to-server RPCs. These will be now measured as if they were anonymous. The reason for this is that many client-to-server RPCs do not send the node secret and instead rely on the protection of mTLS.
This changeset ensures that the node secret is being sent with every client-to-server RPC request. In a future version of Nomad we can add enforcement on the server side, but this was left out of this changeset to reduce risks to the safe upgrade path.
Sending the node secret as an auth token introduces a new problem during initial introduction of a client. Clients send many RPCs concurrently with `Node.Register`, …
> client: send node secret with every client-to-server RPC

- .github/workflows/test-ui.yml
Since the matrix exercises different test cases, it's better to allow all partitions to completely run, even if one of them fails, so it's easier to catch multiple test failures.
> ci: set `continue-on-error: true` on `test-ui`

- .changelog/17654.txt
- scheduler/generic_sched.go
- scheduler/generic_sched_test.go
When a non-canary allocation fails during a canary deployment it must be replaced according to the original job specification, which includes resources, constraints, datacenters etc.
Prior to this change, only the job was being reset in the stack, which could lead to the replacement being placed in nodes in the wrong datacenter.
Manual backport to `release/1.3.x` from the solution discussed in https://github.com/hashicorp/nomad/pull/17598#discussion_r1235295426 which will go to `main`.
FIxes https://github.com/hashicorp/nomad/issues/17651
> core: set proper nodes on downgrade

- ui/app/components/job-status/panel/deploying.hbs
- ui/app/components/job-status/panel/steady.hbs
Previously, the "0 pending", "0 failed" here would have been links to otherwise empty list pages. Now we check for the existence of allocations in that class before making it a link, otherwise it's just a span.
> [ui] Job Status/Deployment Panel: legend items with a count of 0 no longer links

- .github/workflows/release.yml
Although #17669 fixed the permissions of the release pipeline to push new commits, there was still an error when invoking the `build` workflow.
The format of the reference was changed in #17103 such that we're sending the git ref (a SHA) and not the "--ref" argument required by the GH actions workflow API, which in this case is apparently specially defined as "The branch or tag name which contains the version of the workflow file you'd like to run" and not what git calls a "ref".
This changeset:
* Removes the third-party action entirely so that we're using GitHub's own tooling. This removes one more thing from the supply chain to pin and ensures a 1:1 mapping of args to what's documented by GitHub.
* Removes the `--ref` argument entirely, which causes it to default to the current branch …
> release pipeline: fix ref arguments in invoking workflow

- ui/app/components/job-status/panel/deploying.hbs
- ui/app/components/job-status/panel/deploying.js
- ui/app/components/job-status/panel/steady.hbs
- ui/app/styles/components/job-status-panel.scss
- ui/tests/integration/components/job-status-panel-test.js
In two places:
- next to the "New allocations: x/y running and healthy" shows the latest version number
- in a "Versions" cell that matches the steady state format, which'll show counts for all allocations running between prev and new allocs of non-terminal status
> [ui] Versions added to deploying status panel

- ui/tests/acceptance/allocation-detail-test.js
While backporting https://github.com/hashicorp/nomad/pull/17648 I noticed that this test can still be flaky because the service can be assigned to a non-running allocation.
I fixed this during the backports, so pulling it to `main` as here.
> ci: fix flaky UI test

- e2e/example/doc.go
- e2e/example/example_test.go
- e2e/example/input/env.hcl
- e2e/example/input/sleep.hcl
- e2e/v3/README.md
- e2e/v3/cluster3/cluster3.go
- e2e/v3/jobs3/jobs3.go
- e2e/v3/namespaces3/namespaces3.go
- e2e/v3/util3/util3.go
This PR creates an experimental set of packages under `e2e/v3/` for crafting
Nomad e2e tests. This is an attempt at providing a way to create tests in a
declarative (ish) pattern, with a focus on being easy to use, easy to cleanup,
and easy to debug.
There's enough in place for the `examples` package, and for running a docker registry
and running tests against that (in another PR).
Lots of features need to be implemented.
Many more docs need to be written.
Breaking changes are to be expected.
There are known and unknown bugs.
No warranty.
A revised `example` suite
```go
package example
import (
"fmt"
"testing"
"time"
"github.com/hashicorp/nomad/e2e/v3/cluster3"
"github.com/hashicorp/nomad/e2e/v3/jobs3"
"github.com/hashicorp/nomad/e2e/v3/namespaces3" …
```
> e2e: create a v3/ set of packages for creating Nomad e2e tests

- ui/stories/charts/recommendation-chart.stories.js
- ui/stories/charts/topo-viz.stories.js
This completes the collection of stories for charts in our li'l Storybook.
1. recommendation-chart, which is used in the Dynamic Application Sizing UI
2. topo-viz (and topo-viz/node and topo-viz/datacenter)
All should be previewable in the PR storybook build 🚀
> [UI] Missing chart stories

- nomad/node_pool_endpoint.go
- nomad/node_pool_endpoint_test.go
Unlike nodes, jobs are allowed to be registered in the node pool `all`, in which case all nodes are used for evaluating placements. When listing jobs for the `all` node pool only those that are explicitly in this node pool should be returned.
> np: fix list of jobs for node pool `all`

- .changelog/17017.txt
- .github/workflows/build.yml
- .release/ci.hcl
- Dockerfile
- scripts/docker-entrypoint.sh
- website/content/docs/install/production/requirements.mdx
Update release process to produce a [Docker image](https://hub.docker.com/r/hashicorp/nomad). 
This image is intended for CI usage and running clients as Docker containers is not supported for the reasons described in https://github.com/hashicorp/nomad/issues/6487#issuecomment-542484234 and https://github.com/hashicorp/nomad/issues/6487#issuecomment-1473795286.
Closes https://github.com/hashicorp/nomad/issues/6487
> build: add Docker image

- .changelog/17689.txt
- api/jobs.go
- api/jobs_test.go
Check for a nil job ID to prevent a panic when calling Jobs().Plan().
Closes https://github.com/hashicorp/nomad/issues/17418
> api: prevent panic on job plan

- website/content/docs/commands/node/drain.mdx
If you use `nomad node drain -force`, the drain deadline is set to -1ns. If you have not prevented system and CSI node plugin allocations from being drained with `-ignore-system`, they will be immediately drained as well. This is typically not safe for CSI node plugins.
Also fix some broken links.
Preview link: https://nomad-4twwjcfw3-hashicorp.vercel.app/nomad/docs/commands/node/drain
Fixes: #17696
> docs: clarify drain's `-force` flag behavior with system/CSI jobs

- command/agent/node_pool_endpoint_test.go
- command/node_pool_jobs_test.go
In #17705 we fixed a bug in the treatment of the "all" node pool for the `node pool jobs` command but missed a test in the CLI and HTTP endpoint.
> cli: fix broken `node pool jobs` test

- .changelog/16134.txt
- ui/app/components/job-status/panel/deploying.hbs
- ui/app/components/job-status/panel/steady.hbs
- ui/app/components/job-status/update-params.hbs
- ui/app/styles/components/job-status-panel.scss
- ui/tests/acceptance/allocation-detail-test.js
Cleans up and standardizes spacing across a handful of elements in the job status panel;
makes the version tabs stand out more;
fades only the text part of faded legend items
> [ui] alignment and spacing for job status panel

- .changelog/17341.txt
- nomad/deploymentwatcher/deployment_watcher.go
- nomad/deploymentwatcher/deployments_watcher_test.go
- nomad/structs/structs.go
Given a deployment that has a progress_deadline, if a task group runs out of reschedule attempts, allow it to fail at this time instead of waiting until the progress_deadline is reached.
See #17260
> deploymentwatcher: fail early whenever possible

- .changelog/17731.txt
- drivers/docker/config.go
- drivers/docker/driver.go
- drivers/docker/driver_unix_test.go
- drivers/docker/fingerprint.go
- drivers/docker/handle.go
- drivers/docker/network.go
- drivers/docker/reconcile_dangling.go
- drivers/docker/stats.go
This PR refactors how we manage the two underlying clients used by the
docker driver for communicating with the docker daemon. We keep two clients
One with a hard-coded timeout that applies to all operations no matter
what, intended for use with short lived / async calls to docker.
The other has no timeout and is the responsibility of the caller to set a
context that will ensure the call eventually terminates (except in the `.Wait` case).
The use of these two clients has been confusing and mistakes were made
in a number of places where calls were making use of the wrong client.
This PR makes it so that a user must explicitly call a function to get
the client that makes sense for that use case.
Fixes #17023
> drivers/docker: refactor use of clients in docker driver

- ui/app/templates/clients/index.hbs
- ui/app/templates/components/job-row.hbs
- ui/app/templates/jobs/index.hbs
- moves the "state" filter box on the clients index page to be first
- moves the "Node Pool" column header to after Type on the jobs index page
> [ui] Node Pools moved to after Type in jobs index columns

- ui/app/controllers/clients/client/index.js
- ui/app/controllers/csi/plugins/plugin/allocations.js
- ui/app/controllers/csi/plugins/plugin/index.js
- ui/app/controllers/csi/volumes/volume.js
- ui/app/controllers/jobs/job/allocations.js
- ui/app/controllers/jobs/job/task-group.js
- ui/app/routes/allocations/allocation.js
- ui/tests/acceptance/job-allocations-test.js
Resolves #17521 
When loading an allocation from a parent page, like the allocations list of a job, there were circumstances where that allocation would load as `isPartial`, and be missing critical data, notably `taskGroup`. We have components like our `LifecycleChart` that make use of that data and throw a fatal exception if not found.
This ensures that the model, if partial, is fully loaded when /allocations/allocation/$id is hit. This further changes our links to allocation pages to pass in the ID of the allocation rather than a (potentially partial) model itself, in order to cause it to rerun the route model hook.
> [ui] links to allocations explicitly go through their route model hook

- ui/app/templates/components/job-page/batch.hbs
- ui/app/templates/components/job-page/parameterized-child.hbs
- ui/app/templates/components/job-page/parts/placement-failures.hbs
- ui/app/templates/components/job-page/service.hbs
- ui/app/templates/components/job-page/sysbatch.hbs
- ui/app/templates/components/job-page/system.hbs
- ui/app/templates/components/placement-failure.hbs
When present, a placement failure is the most succinct and actionable notification that a user is likely to see during a deployment. As such, this bumps it up to the top of the page.
Additionally, styles the notification with updated HDS/Helios styles.
> [ui] Move Placement Failures notification above job status panel

- e2e/terraform/network.tf
`ipify.org` is frequently flakey, causing Terraform apply/destroy to errors in E2E tests, e.g.
```
│ Error: HTTP request error. Response code: 502
│ 
Terraform planned the following actions, but then encountered a problem:
│   with data.http.my_public_ipv4,
│   on network.tf line 23, in data "http" "my_public_ipv4":
│   23: data "http" "my_public_ipv4" {
```
This replaces the HTTP lookup with DNS, which is faster (not that speed matters a whole lot here), but more importantly, OpenDNS should (hopefully) be more reliable.
> e2e: use DNS instead of HTTP to get my_public_ipv4

- .changelog/17752.txt
- ui/app/components/job-editor.js
- ui/app/styles/components/codemirror.scss
- ui/app/templates/components/job-editor.hbs
- ui/app/templates/components/job-editor/edit.hbs
- ui/tests/integration/components/job-editor-test.js
- Rearranges buttons when adding a jobspec, or editing an existing jobspec, to be more intuitive
- Adds a "Download as .nomad.hcl" button when editing, to let users practice good infra-as-code
Resolves #17327
> [ui] HCL-in-UI: Re-arrange buttons, add save-as-file

- .github/workflows/build.yml
- .github/workflows/release.yml
This should always reflect the commit that's being built, as this may differ from the default `github.sha `that the workflow was invoked at.
Goes with https://github.com/hashicorp/actions-docker-build/pull/59 - and should not be merged until the PR is merged and a new version of the action is cut.
> Update the revision used by the docker build action.

- website/content/docs/install/production/requirements.mdx
The requirements for client-to-server and client-to-client topologies are not well-documented in the production install requirements docs. Document that clients make connections to servers (and not the other way around), and that clients don't need to communicate with each other (with some exceptions).
Fixes: #17631
Preview link: https://nomad-1lii3ldjy-hashicorp.vercel.app/nomad/docs/install/production/requirements#network-topology
> docs: clarify network topology requirements for clients

- .release/ci.hcl
- Dockerfile
- scripts/docker-entrypoint.sh
- website/content/docs/install/production/requirements.mdx
In https://github.com/hashicorp/nomad/pull/17769 we backported the build pipeline to be current with `main` but missed the Dockerfile, related scripts, and docs.
Test run in progress: https://github.com/hashicorp/nomad/actions/runs/5423915270
> backport docker build to 1.5.x

- .changelog/17754.txt
- ui/app/components/job-editor.js
- ui/app/components/task-log.js
- ui/app/modifiers/code-mirror.js
- ui/app/styles/components/boxed-section.scss
- ui/app/styles/components/cli-window.scss
- ui/app/templates/components/job-editor/edit.hbs
- ui/app/templates/components/job-editor/read.hbs
- ui/app/templates/components/streaming-file.hbs
- ui/app/templates/components/task-log.hbs
- ui/tests/acceptance/task-logs-test.js
Lets a user wrap text in their logs and job definitions.
- Adds a "Wrap" button to job definitions and logs in the UI
- Preference saved to localStorage, so persists across refresh
- Adds a keyboard shortcut (`ww`) to toggle
TODO: tests
Resolves #17749
> [ui] Text wrap long lines of code and logs

- .changelog/17783.txt
- ui/app/styles/components/page-layout.scss
A report shows a 3rd party browser extension puts a banner at the top of page and awkwardly shifts nav; this fixes that
> [ui] Affix the page header to the top of the page

- nomad/leader.go
- nomad/leader_test.go
- nomad/lock/delay.go
- nomad/lock/delay_test.go
- nomad/lock/ttl.go
- nomad/server.go
- nomad/structs/variables.go
- nomad/structs/variables_test.go
Lock timers are tracked within memory, the TTLs are monitored from the leader only. This means leadership transition must start/stop certain background processes to track TTL timers, and emit metrics about the background processes.
Related: #17449 
Targets: feature branch
> leadership: add lock timer leadership transition functionality.

- .changelog/17280.txt
- api/allocations.go
- api/allocations_test.go
Service discovery or mesh network systems consuming the Nomad event stream or API need to know the CNI assigned IP for the allocation. This data is returned by the underlying Nomad API but isn't mapped in the response struct in the Go client.
> [api] Add NetworkStatus to allocation response

- .github/actions/setup-js/action.yml
- .github/workflows/backport.yml
- .github/workflows/build.yml
- .github/workflows/checks.yaml
- .github/workflows/release.yml
- .github/workflows/test-core.yaml
- .github/workflows/test-e2e.yml
- .github/workflows/test-ui.yml
- .github/workflows/test-windows.yml
In order to fetch secrets from Vault in our Enterprise repo, we need to use self-hosted runners, but here in this public repo, we may only use public runners.
To reduce merge conflicts between OSS and ENT (and backports..), this PR adds conditions that will result in public runners here in OSS, but self-hosted runners in ENT.  I have done a lot of trial-and-error to end up with what I hope is a nice middle-ground between complexity, explicitness, and non-mergeflictery.
A subsequent PR will add the steps to (again, conditionally) fetch secrets from Vault.
> CI: Dynamic runs-on values for oss/ent

- .github/workflows/build.yml
This is basically to avoid Fear/Uncertainty/Doubt.
The github action [actions/setup-go](https://github.com/actions/setup-go) (and, with a different chache key, [hashicorp/setup-golang](https://github.com/hashicorp/setup-golang)) caches both GOMODCACHE (go source files), which is good, and GOCACHE (build outputs), which *might* be bad, if the cache was built on an OS with an older glibc than we want to support. from `go help cache`:
> [...] the build cache does not detect changes to C libraries imported with cgo.
I think we've been okay so far, because the cache has always(~?) been built on 20.04 machines, but to be safe, this wipes the build cache (leaving the mod cache alone) before building.
related PR that checks the build after the fact: #17706
> ci: clean GOCACHE before build

- .changelog/17766.txt
- client/allocrunner/networking_cni.go
- client/allocrunner/networking_cni_test.go
Currently as commented in the code the go-cni library returns an unordered map
of interfaces. In cases where there are multiple CNI interfaces being created this
creates a problem with service registration and healthchecking because the first
address in the map is being used.
The use case we have where this is an issue is that we run CNI with the macvlan
plugin to isolate workloads, but they still need to be able to access the host on
a static address to be able to perform local resolving and hit host services like
the Consul agent API. To make this work there are 2 options, you either add a
macvlan interface on the host with an assigned address for each VLAN you have or
you create an additional veth bridged interface in the container namespace.
We chose the latter option through a custom …
> cni: ensure to setup CNI addresses in deterministic order

- .github/workflows/test-windows.yml
After merging #17775 I discovered that our self-hosted windows runners lack `docker` currently, so for now just revert to public runners.
Will revisit later.
> ci: keep windows tests on public runners

- .github/actions/vault-secrets/action.yml
- .github/workflows/backport.yml
- .github/workflows/build.yml
- .github/workflows/checks.yaml
- .github/workflows/release.yml
- .github/workflows/test-core.yaml
- .github/workflows/test-e2e.yml
- .github/workflows/test-ui.yml
Now that (most) secrets-requiring workflows run on self-hosted runners in nomad-enterprise (#17775), we're able to (conditionally) pull secrets from our internal CI Vault cluster.
The approach here uses a [composite action](https://docs.github.com/en/actions/creating-actions/about-custom-actions#composite-actions) to avoid repetitive boilerplate, which also means it needs* to set secrets as env vars (also the default behavior of hashicorp/vault-action, and common practice in other projects, sans the composite action).  Otherwise, it would require an odd maneuver, for GHA reasons, to have the composite output a dynamic map instead (*but it is possible, if we really want to. ask me how if you'd like).
As with the aforementioned PR, this is here in OSS Nomad repo to avoid merge conflicts …
> ci: pull secrets from Vault in nomad-enterprise

- .changelog/17847.txt
- nomad/consul.go
In Consul 1.15.0, the Delete Token API was changed so as to return an error when deleting a non-existent ACL token. This means that if Nomad successfully deletes the token but fails to persist that fact, it will get stuck trying to delete a non-existent token forever.
Update the token deletion function to ignore "not found" errors and treat them as successful deletions.
Fixes: #17833
Source for text of error (there's no const in the `api` package for it): https://github.com/hashicorp/consul/blob/api/v1.22.0/agent/acl_endpoint.go#L470
> consul: handle "not found" errors from Consul when deleting tokens

- .changelog/17766.txt
- client/allocrunner/networking_cni.go
- client/allocrunner/networking_cni_test.go
Replaces failed automatic backport #17825
---
* cni: ensure to setup CNI addresses in deterministic order
Currently as commented in the code the go-cni library returns an unordered map
of interfaces. In cases where there are multiple CNI interfaces being created this
creates a problem with service registration and healthchecking because the first
address in the map is being used.
The use case we have where this is an issue is that we run CNI with the macvlan
plugin to isolate workloads, but they still need to be able to access the host on
a static address to be able to perform local resolving and hit host services like
the Consul agent API. To make this work there are 2 options, you either add a
macvlan interface on the host with an assigned address for each VLAN you have or
you create an …
> Backport of cni: ensure to setup CNI addresses in deterministic order (#17766)

- .github/workflows/checks.yaml
Avoid hitting the timeout on nomad-enterprise.
These values have worked consistently in my tests over yonder.
> ci: more self-hosted iops for checks workflow

- .changelog/17840.txt
- client/allocrunner/alloc_runner.go
- client/allocrunner/csi_hook.go
- client/allocrunner/csi_hook_test.go
- client/allocrunner/state/state.go
- client/pluginmanager/csimanager/instance.go
- client/pluginmanager/csimanager/interface.go
- client/pluginmanager/csimanager/volume.go
- client/pluginmanager/csimanager/volume_test.go
- client/state/db_bolt.go
- client/state/db_error.go
- client/state/db_mem.go
- client/state/db_noop.go
- client/state/interface.go
- helper/funcs.go
- nomad/csi_endpoint.go
- nomad/structs/volumes.go
When claiming a CSI volume, we need to ensure the CSI node plugin is running before we send any CSI RPCs. This extends even to the controller publish RPC because it requires the storage provider's "external node ID" for the client. This primarily impacts client restarts because the client's initial fingerprint won't include restored plugins.
Unfortunately there's no mapping of volume to plugin ID available in the jobspec, so we don't have enough information to wait on plugins until we either get the volume from the server or retrieve the plugin ID from data we've persisted on the client.
If we always require getting the volume from the server before making the claim, a client restart for disconnected clients will cause all the allocations that need CSI volumes to fail. Even while …
> CSI: persist previous mounts on client to restore during restart

- website/content/docs/upgrade/upgrade-specific.mdx
> docs: v1.6.0 requires ipc_lock cap for mlock

- .changelog/17309.txt
- command/tls_ca_create.go
- command/tls_ca_create_test.go
- helper/tlsutil/generate.go
- helper/tlsutil/generate_test.go
- nomad/rpc_test.go
- website/content/docs/commands/tls/ca-create.mdx
Allow operators to customise the CA created using `nomad tls ca create`
> Add the ability to customise the details of the CA

- website/content/docs/job-specification/update.mdx
As discussed, the update stanza's stagger docs don't mention the alternative for service jobs (min_healthy_time).
> Clarify update stagger description and alternatives

- website/content/plugins/drivers/community/index.mdx
- website/content/plugins/drivers/community/pledge.mdx
- website/data/docs-nav-data.json
- website/data/plugins-nav-data.json
Adds documentation for the [pledge](https://github.com/shoenig/nomad-pledge-driver) task driver to the set of Nomad community plugins.
> docs: add plugin docs for pledge task driver

- .github/workflows/build.yml
This adds a quick smoke test of our binaries to verify we haven't exceeded the maximum glibc (2.17) version supported on older OSes (EL7). Which would break our ability to execute on older OSes.
This is related to our recent efforts to upgrade our GH build environment. When CGO enabled builds are built on Ubuntu-22 they include symbols to glibc versions (2.32+) that exceed our desired minimum OS version (EL7). To mitigate we are instead building on Ubuntu-20. However, Ubuntu-20 itself also includes a newer glibc version. So we need to make sure we check the binaries to prevent us from unintentionally dropping support by adding explicit smoke testing of the binary.
For clarity, here's a breakdown of distribution and glibc versions to provide a bit more context to why we should test on EL7: …
> Smoke test binaries for EL7/glibc-2.17 compatiblity

- .github/workflows/copywrite.yml
This PR's copywrite CI run: https://github.com/hashicorp/nomad/actions/runs/5521733801/jobs/10070278831?pr=17889
closes #17887
> ci: add copywrite action to check file headers.

- e2e/pledge/doc.go
- e2e/pledge/input/bridge.hcl
- e2e/pledge/input/curl.hcl
- e2e/pledge/input/sleep.hcl
- e2e/pledge/input/unveil.hcl
- e2e/pledge/pledge_test.go
- e2e/terraform/etc/nomad.d/client-linux.hcl
- e2e/terraform/packer/build
- e2e/terraform/packer/ubuntu-jammy-amd64/setup.sh
- e2e: setup nomad for pledge driver
- e2e: add some e2e tests for pledge task driver
> e2e: add some e2e tests for pledge task driver

- ui/tests/acceptance/token-test.js
We've got this acceptance test in the UI that checks to make sure that, when the "10 minutes until your ACL token expires" point hits, you get a notification.
We would create a token with an expiry 10m5s out, wait 0.5s for initialization, and then wait 5s to make sure the notification is there.
With recent test runner changes (Circle -> GHA), we're noticing this fail more often. This may be because the JS runtime is different or slightly slower.
Because the user-facing notification is persistent (doesn't go away on its own), we're safe to wait a little longer before checking if the notification is present. And in order not to take any longer on our already-kind-of-long test runs, I've opted to shorten the token TTL rather than extending the setTimeout() length.
> [ui] Flaky test fix: expiring token notification

- website/content/tools/autoscaling/plugins/apm/nomad.mdx
Based on the [nomad-autoscaler](https://github.com/hashicorp/nomad-autoscaler) codebase and on the [validateMetricTaskGroupQuery](https://github.com/hashicorp/nomad-autoscaler/blob/954f26e8c56526d62f78d6991f5ff2a29dc6fa9f/plugins/builtin/apm/nomad/plugin/job.go#L273) vs [validateMetricNodeQuery](https://github.com/hashicorp/nomad-autoscaler/blob/954f26e8c56526d62f78d6991f5ff2a29dc6fa9f/plugins/builtin/apm/nomad/plugin/node.go#L197), this is how the documentation should look like.
> fix: allowed metric values documentation for the Nomad APM plugin

- website/content/api-docs/task-api.mdx
- website/content/docs/concepts/workload-identity.mdx
- website/content/docs/job-specification/identity.mdx
Support for UDS sockets was added to Windows 10 (build 17063), make a note in the Task API docs. Also reference Task API from WI  pages since it's a common use case to combine the two features.
https://devblogs.microsoft.com/commandline/af_unix-comes-to-windows/
> docs: note windows requirement for workload identity

- .changelog/17940.txt
- ui/app/controllers/topology.js
- ui/tests/acceptance/topology-test.js
"Ineligible" and "Draining" are not determined by the node status, but are rather inferred from other fields.
Closes https://github.com/hashicorp/nomad/issues/17772
> ui: fix Topology node state filter

- .changelog/17936.txt
- client/serviceregistration/checks/client.go
- client/serviceregistration/checks/client_test.go
Apply the [same logic as Consul service health checks](https://github.com/hashicorp/nomad/blob/437941816c6b84f4b756f694fe42cb028ff50e65/command/agent/consul/service_client.go#L1658-L1667) when building the HTTP URL so that query params in `path` are preserved.
Closes https://github.com/hashicorp/nomad/issues/17790
> nsd: retain query params in HTTP health checks

- .changelog/17938.txt
- client/allocrunner/taskrunner/task_runner.go
- website/content/docs/operations/metrics-reference.mdx
Add new `nomad.client.allocs.memory.max_allocated` metric to report the value of the task `memory_max` resource value.
Closes https://github.com/hashicorp/nomad/issues/17716
> metrics: report task memory_max value

- e2e/podman/input/auth_basic.hcl
- e2e/podman/input/auth_helper.hcl
- e2e/podman/input/auth_static.hcl
- e2e/podman/input/redis.hcl
- e2e/podman/input/registry-auths.hcl
- e2e/podman/input/registry.hcl
- e2e/podman/podman_test.go
- e2e/terraform/etc/nomad.d/client-linux.hcl
- e2e/terraform/packer/ubuntu-jammy-amd64/setup.sh
**note**: I had to add `-k` to a few curl commands - I'm fairly sure the base Ubuntu image did a [Bad Thing](https://bugs.launchpad.net/ubuntu/+source/curl/+bug/2028170) to its own trust store / curl package and we'll need to ignore certificate errors until that is fixed. Also replaced the use of the deprecated `apt-key` command with the gpg/tee dance recommended by Docker and Hashicorp packaging.
---
e2e: add a test for using private registry with podman driver
This PR adds e2e tests that stands up a private docker registry
and has a podman tasks run a container from an image in that private
registry.
Tests
- user:password set in task config
- auth_soft_fail works for public images when auth is set in driver
- credentials helper is set in driver auth config
- config auth.json file is set …
> e2e podman private registry

- ui/app/controllers/jobs/job.js
- ui/app/routes/jobs/job.js
- ui/app/routes/jobs/job/index.js
- ui/app/templates/jobs/job.hbs
- ui/app/utils/properties/watch.js
- ui/tests/acceptance/job-detail-test.js
- In the event that a job is removed/purged/GC'd from elsewhere while the user is actively on a job page, this PR causes an event to fire that 1. boots the user back to the jobs index page, and 2. gives them a sticky notification about what happened.
- Moves the "job watcher" from jobs.job.index level to jobs.job level, so a "yoinked" job can be observed from anyplace within the job's subnav, not just the index page
- extends the `watchRecord` watcher util to accept a `shouldSurfaceErrors` param. This is experimental, but makes it so that elsewhere we can check `this.model.watchers.{}.isError`, where before it was being yielded but not set on the watcher itself.
Resolves #17757
> [ui] When a purged/404-ing job is detected, boot the user out of that job and back to the index

- .changelog/17996.txt
- nomad/client_csi_endpoint.go
- nomad/csi_endpoint.go
- nomad/csi_endpoint_test.go
- nomad/server.go
The CSI specification says that we "SHOULD" send no more than one in-flight request per *volume* at a time, with an allowance for losing state (ex. leadership transitions) which the plugins "SHOULD" handle gracefully. We mostly successfully serialize node and controller RPCs for the same volume, except when Nomad clients are lost. (See also https://github.com/container-storage-interface/spec/issues/512)
These concurrency requirements in the spec fall short because Storage Provider APIs aren't necessarily safe to call concurrently on the same host even for _different_ volumes. For example, concurrently attaching AWS EBS volumes to an EC2 instance results in a race for device names, which results in failure to attach (because the device name is taken already and the API call fails) and …
> CSI: improve controller RPC reliability

- .changelog/18017.txt
- nomad/state/state_store_restore.go
The upgrade path to Nomad 1.6.0 requires canonicalizing the namespace in order to set the default scheduler configuration values.
Previous implementation only canonicalized on namespace upsert operations, which works for recent namespaces as those Raft transactions are reapplied on upgrade.
But for older namespaces restore from a snapshot the code path did not canonicalize them, leaving the scheduler configuration set as `nil`.
Fixes #18007
_Note to reviewers: I was writing tests for this, but then I remembered that `Namespace.Canonicalize()` on OSS is no-op so I will add them to the Enterprise repo._
https://github.com/hashicorp/nomad/blob/f52912454dec9bc552b7e2b6f0e3160bd31c625e/nomad/structs/structs_oss.go#L16
> state: canonicalize namespace on restore

- nomad/client_csi_endpoint.go
- nomad/csi_endpoint_test.go
The backport for #17996 was automatically merged by BPA but the build did not work due to missing imports and changes to the signatures of some our RPC structs. Fix the backport.
> backport fix for PR #17996 to 1.4.x

- .changelog/18020.txt
- ui/app/adapters/application.js
When a request is made to an RPC service that doesn't exist (for example, a cross-region request from a newer version of Nomad to an older version that doesn't implement the endpoint) the application should return an empty list as well.
> ui: handle errors from unimplemented services

- .changelog/18021.txt
- ui/app/adapters/node-pool.js
- ui/app/templates/clients/client/index.hbs
- ui/app/templates/components/client-node-row.hbs
- ui/app/templates/components/job-page/parts/stats-box.hbs
- ui/app/templates/components/job-row.hbs
When accessing a region running a version of Nomad without node pools an error was thrown because the request is handled by the nodes endpoint which fails because it assumes `pools` is the node ID.
Fixes #18007
> ui: handle node pool requests to older regions

- .changelog/17971.txt
- client/allocrunner/alloc_runner.go
Persist the task states for post stop tasks at the time of killing to resolve https://github.com/hashicorp/nomad/issues/17971.
Please note that this is the safer of the two options discussed within the original issue description.
> Retain task states for post stop tasks at the time of node GC

- nomad/fsm.go
- nomad/state/state_store_variables.go
- nomad/state/state_store_variables_test.go
- nomad/variables_endpoint.go
This PR adds the implementation of the acquire and release calls on the state store. If an acquire call is made on a variable that doesn't exist, it will be created. For the release, the lock ID is verified before proceeding with the release.
Related: https://github.com/hashicorp/nomad/issues/17449
Targets: feature branch
> Add acquire and release lock functions on the state store

- .changelog/17815.txt
- command/alloc_logs.go
Prevent panic if stderrFrame is nil
```
debug logging:
logUI: &{reader:0xc000014010 writer:0xc000014018 errorWriter:0xc000014020 underlyingUI:0xc000a26750 isColor:true outputColor:{Code:0 Bold:false} infoColor:{Code:92 Bold:false} errorColor:{Code:91 Bold:false} warnColor:{Code:93 Bold:false}} 
stderrFrame: <nil> 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1fbf565]
goroutine 1 [running]:
github.com/hashicorp/nomad/command.(*AllocLogsCommand).tailMultipleFiles(0xc00040d7a0, 0xc000a2ae70, 0x24?)
/home/kmulvey/src/go/src/github.com/hashicorp/nomad/command/alloc_logs.go:403 +0x645
github.com/hashicorp/nomad/command.(*AllocLogsCommand).Run(0xc00040d7a0, {0xc0000520c0, 0x3, 0x3}) …
```
> check in stderrFrame is nil before logging stderrFrame.Data

- terraform/shared/config/consul.json
- terraform/shared/config/consul_client.json
This Terraform folder is for quickly building an integrated Nomad/Consul cluster on the cloud. To avoid Job submission failures with Consul as the provider, it requires to include grpc port `8502` and enable the `connect` option in the configuration.
> Add missing consul grpc config

- website/content/tools/index.mdx
Add https://github.com/nomad-ops/nomad-ops to our Tools page.
> website: add Nomad Ops to Tools

- .changelog/18051.txt
- ui/app/serializers/variable.js
Doesn't impact the variable view page, as it's already using a table that sorts ascending on key by default, but on the edit page, which iterates over and creates a form label for each, they'll now appear ascending on key alpha.
> [ui] Sort variables ascending by key at serialization time

- command/agent/node_pool_endpoint.go
- command/agent/node_pool_endpoint_test.go
Split node pool related changes from #17968 to a separate PR. Makes backporting these changes easier.
- Modify `net/http` related calls to consistently use HTTP methods and response codes from variables/constants provided by the pkg.
Some parts of the codebase already use these. With this PR, better code consistency and reliability.
> chore(nodepool): Go stdlib vars for HTTP methods and status codes

- command/agent/variable_endpoint.go
- command/agent/variable_endpoint_test.go
Split variable endpoint related changes from #17968 to a separate PR. Makes backporting these changes easier.
- Modify `net/http` related calls to consistently use HTTP methods and response codes from variables/constants provided by the pkg.
Some parts of the codebase already use these. With this PR, better code consistency and reliability.
> chore(variable): Go stdlib vars for HTTP methods and status codes

- .changelog/18069.txt
- GNUmakefile
Makefile changes required for supporting s390x builds and a corresponding changelog entry. 
Enterprise PR: https://github.com/hashicorp/nomad-enterprise/pull/1202
Resolves #18068
> build: support s390x architecture for linux (ent)

- .semgrep/rpc_endpoint.yml
- command/agent/http.go
- command/agent/keyring_endpoint.go
- go.mod
- go.sum
- helper/retry.go
- helper/retry_test.go
- nomad/encrypter.go
- nomad/keyring_endpoint.go
- nomad/keyring_endpoint_test.go
- nomad/structs/keyring.go
Yanked out of #17434 
JWKS endpoint to expose the public keys used to sign workload identity JWTs. The ultimate purpose of this endpoint is to enable integrations with 3rd party JWT auth methods such as [Consul's](https://developer.hashicorp.com/consul/docs/security/acl/auth-methods/jwt) and [Vault's](https://developer.hashicorp.com/vault/docs/auth/jwt).
Not documenting this yet, but have a note on the project board. It's not really possible to use _safely_ to use until we add audiences, expiration, and rotation to workload identities, so I'd like to leave it "hidden" or at least "unsupported" until we can offer a secure experience.
> core: add jwks rpc and http api

- .changelog/18081.txt
- command/job_run.go
- website/content/docs/commands/job/run.mdx
Add missing help entry for the `-consul-namespace` flag in `nomad job run`.
> cli: add help message for `-consul-namespace`

- .github/actions/setup-js/action.yml
- .github/workflows/actionlint.yml
- .github/workflows/backport.yml
- .github/workflows/build.yml
- .github/workflows/checks.yaml
- .github/workflows/copywrite.yml
- .github/workflows/ember-test-audit.yml
- .github/workflows/lock.yml
- .github/workflows/release.yml
- .github/workflows/semgrep.yml
- .github/workflows/test-core.yaml
- .github/workflows/test-e2e.yml
- .github/workflows/test-ui.yml
- .github/workflows/test-windows.yml
Trusted Supply Chain Component Registry (TSCCR) enforcement starts Monday and an internal report shows our semgrep action is pinned to a version that's not currently permitted. Update all the action versions to whatever's the new hotness to maximum the time-to-live on these until we have automated pinning setup.
No backport labels because there's no possible way BPA is going to work with these changes so I'll just make the 6 PRs by hand.
> GHA pinning updates

- scheduler/util.go
In #18054 we introduced a new field `render_templates` in the `restart` block. Previously changes to the `restart` block were always non-destructive in the scheduler but we now need to check the new field so that we can update the template runner. The check assumed that the block was always non-nil, which causes panics in our scheduler tests.
No changelog entry as this was never shipped.
Will be backported to 1.6.x
> scheduler: fix panic in `render_templates` destructive update check

- .changelog/18053.txt
- ui/app/controllers/jobs/index.js
- ui/tests/acceptance/jobs-list-test.js
Bit of context here:
- Our Searchable mixin uses fuzzy-finding, so both my jobs "fakepy" and "fails_after_10" will show up when I type "fai" or "fak" into my search bar
- Last year, we addressed a [bug where sorting wouldn't apply at all if a search term was present](https://github.com/hashicorp/nomad/issues/14872) in PR #15432 
- More recently, we'd heard concerns that our search results appeared degraded from previous versions, see these screenshots showing 1.5.6 and 1.4.10 respectively: 
This PR attempts to both preserve the ability to sort after searching, and not overload results with searched-but-not-ordered filter results by creating a new getter() that checks to see if any sorting has been applied.
> [ui] Search results are overloading filter with sorted results

- .changelog/18095.txt
- command/alloc_exec.go
- command/alloc_exec_test.go
- command/alloc_fs.go
- command/alloc_logs.go
- website/content/docs/commands/alloc/exec.mdx
- website/content/docs/commands/alloc/fs.mdx
- website/content/docs/commands/alloc/logs.mdx
The alloc exec and filesystem/logs commands allow passing the `-job` flag to select a random allocation. If the namespace for the command is set to `*`, the RPC handler doesn't handle this correctly as it's expecting to query for a specific job. Most commands handle this ambiguity by first verifying that only a single object of the type in question exists (ex. a single node or job).
Update these commands so that when the `-job` flag is set we first verify there's a single job that matches. This also allows us to extend the functionality to allow for the `-job` flag to support prefix matching.
Fixes: #12097
---
What this looks like if there are multiple matching jobs:
```
$ nomad alloc exec -namespace '*' -job httpd /bin/sh
Prefix "httpd" matched multiple jobs
ID     Namespace  Type …
```
> cli: support wildcard namespace in alloc subcommands

- command/agent/variable_endpoint_test.go
Update the tests for the variables HTTP endpoint to use [must](https://pkg.go.dev/github.com/shoenig/test@v0.6.6) instead of [require](https://pkg.go.dev/github.com/stretchr/testify@v1.8.4/require)
> Update the test library

- .changelog/18096.txt
- client/fingerprint/network.go
- client/fingerprint/network_test.go
closes https://github.com/hashicorp/nomad/issues/18097
consider the following config.hcl
```hcl
client {
network_interface = "tailscale0"
host_network "tailscale" {
interface = "tailscale0"
}
host_network "public" {
interface = "wlan0"
}
}
```
whenever you would schedule the following job 
```hcl
job "docs" {
datacenters = ["dc1"]
group "example" {
network {
port "http" {}
}
task "server" {
config {
image = "hashicorp/http-echo"
ports = ["http"]
args = [
"-listen",
":5678",
"-text",
"hello world",
]
}
}
}
}
```
you would see `* Constraint "missing host network \"default\" for port \"http\"": 1 nodes excluded by filter` because the 'default' host_network alias is being replaces with 'tailscale'. The follow PR appends the 'default' alias regardless to the addresses …
> fix 'default' alias not added to interface specified by `network_interface` 

- .changelog/17925.txt
- command/node_status.go
- command/volume_status_csi.go
When looking for CSI volumes to display in the `node status` command the CLI needs to search all namespaces. ~It's also helpful to display the volume namespace in the command output.~ This has been handled by #17911.
Closes https://github.com/hashicorp/nomad/issues/17923
> cli: search all namespaces for node volumes

- .changelog/18141.txt
- scheduler/device.go
- scheduler/device_test.go
When the scheduler assigns a device instance, it iterates over the feasible devices and then picks the first instance with availability. If the jobspec uses a constraint on device ID, this can lead to buggy/surprising behavior where the node's device matches the constraint but then the individual device instance does not.
Add a second filter based on the `${device.ids}` constraint after selecting a node's device to ensure the device instance ID falls within the constraint as well.
Fixes: #18112
See https://github.com/hashicorp/nomad/issues/18112#issuecomment-1664162029 for reproduction steps.
Will get backported to 1.6.x, 1.5.x, and 1.4.x
> scheduler: filter device instance IDs by constraints

- website/content/api-docs/agent.mdx
From: https://github.com/hashicorp/nomad/issues/18113#issuecomment-1664520478
> docs: fix URL in agent pprof examples

- .changelog/17958.txt
- command/volume_snapshot_create.go
- Make snapshot name argument requiered
- Update documentation and helps
> CLI: make snapshot name requiered in creating volume snapshots

- nomad/rpc_test.go
The RPC TLS enforcment test creates network connections to a server and these are occassionally failing in testing with `write: broken pipe` errors. This has been an ongoing issue where it'll appear to get fixed, then reoccur, and no one seems to be able to reproduce outside of CI. The test assertion itself is reliable and correct, which is why it's been hard to spend effort to hunt this down.
We've eliminated RPC connection limits as a possibility, because we'd be getting a different error. But I've been able to trigger the error locally by setting a low `RPCHandshakeTimeout`, which suggests it might be the cause of the flaky tests.
This changeset sets the `RPCHandshakeTimeout` to 10s, twice its default. It also cleans up the test code to use current idioms around using `shoenig/test` …
> test: fix flaky RPC TLS enforcement test

- website/content/api-docs/agent.mdx
Preview link: https://nomad-f86stwn7l-hashicorp.vercel.app/nomad/api-docs/agent#debug
> docs: expand pprof documentation on goroutine profiles

- dev/hooks/pre-push
In #17560 I broke the pre-push hook. This PR should fix it and adds some more possibilities to the mix.
Since we use the presence of the sentinel file to determine if we're pushing the enterprise version, rather than checking the remote every time the hook runs, I moved all of the enterprise checking into a conditional based on that test.
The regex is nasty, because there are a lot of optional components to legit remote URLs 😢
> [hooks] Fix pre-push hook

- .copywrite.hcl
- .github/workflows/build.yml
This updates the linux package license to BUSL-1.1.
This PR should be merged to main so that the change is included in the next minor release that is cut from main.
License changes are not required on release branches (ongoing patch releases of current minor releases).
Also update copywrite.hcl to exclude MPL licensed subdirs.
> Update linux package license to BUSL-1.1

- website/content/api-docs/agent.mdx
the `&` symbol messes up the command when copying and pasting into a shell
> docs: ampersand and bash backgrounding problem

- nomad/job_endpoint_test.go
We've seen test flakiness in the `TestJobEndpoint_Register_NonOverlapping` test, which asserts that we don't try to placed allocations for blocked evals until resources have been actually freed by setting the client status of the previous alloc to complete.
The flaky assertion includes sorting the two allocations by CreateIndex and this appears to be a non-stable sort in the context of the test run, which results in failures that shouldn't exist. There's no reason to sort the allocations instead of just examining them by ID. This changeset does so (and after a few dozen runs locally seems to have worked? He said, hopefully.)
> test: deflake job endpoint registration test

- nomad/drainer_int_test.go
The `TestDrainer_AllTypes_NoDeadline` test has been flaky. It looks like this might be because the final update of batch allocations to complete is improperly updating the state store directly rather than by RPC. If the service jobs have restarted in the meantime, the `allocClientStateSimulator` will have updated the index on the allocations table and that will prevent the drainer from unblocking (and being marked complete) when the batch jobs are written with an earlier index.
This changeset attempts to fix that by making the update via RPC (as it normally would be in real code).
Fixes: https://github.com/hashicorp/nomad/issues/18147
> test: deflake node drain intergration test

- .github/workflows/test-core.yaml
- GNUmakefile
- go.mod
This is the first of two uses of [go-modtool](https://github.com/shoenig/go-modtool) - here we use the `fmt` subcommand to consistently format the `go.mod` file of the Nomad project (and will do the same in the ent repo). Once the formatting is in place in both repos, we can use the `merge` subcommand during `oss-merge.sh` fallback merge resolution to (hopefully) avoid dealing with trivial `go.mod` merge conflicts. I suspect the same pattern could be used for backports, but I hadn't thought that far ahead.
> build: use go-modtool to format go.mod file

- nomad/variables_endpoint.go
- nomad/variables_endpoint_test.go
On top of fixing the lock owner check, this PR also introduces a change that allows for the ACL object that is created when the call is made using a workload identity token to be used outside of the `authorize` function.
This code will need to be revisited after the nil ACLs is removed
> Fix the logic for the display of a newly created lock

- .changelog/18200.txt
- client/allocrunner/taskrunner/stats_hook.go
- client/allocrunner/taskrunner/vault_hook.go
- client/devicemanager/instance.go
- client/pluginmanager/drivermanager/instance.go
- command/agent/consul/version_checker.go
- drivers/docker/driver.go
- drivers/docker/stats.go
- helper/backoff.go
- helper/backoff_test.go
- nomad/state/state_store.go
- nomad/worker.go
We use capped exponential backoff in several places in the code when handling failures. The code we've copy-and-pasted all over has a check to see if the backoff is greater than the limit, but this check happens after the bitshift and we always increment the number of attempts. This causes an overflow with a fairly small number of failures (ex. at one place I tested it occurs after only 24 iterations), resulting in a negative backoff which then never recovers. The backoff becomes a tight loop consuming resources and/or DoS'ing a Nomad RPC handler or an external API such as Vault. Note this doesn't occur in places where we cap the number of iterations so the loop breaks (usually to return an error), so long as the number of iterations is reasonable.
Introduce a check on the cap before the …
> fix multiple overflow errors in exponential backoff

- client/allocrunner/taskrunner/wrangler_hook.go
- client/lib/numalib/topology.go
- lib/lang/stack.go
- lang: note that Stack is not concurrency-safe
- client: use more descriptive name for wrangler hook in logs
- numalib: use correct name for receiver parameter
> followup to numa/cgroups refactor 

- .github/workflows/test-e2e.yml
- e2e/vaultcompat/vaultcompat_test.go
- testutil/server.go
6747ef8803 fixes the Nomad client to support using the raw_exec
driver while running as a non-root user. Remove the use of sudo
in the test-e2e workflow for running integration (vaultcompat)
tests.
Needed to plumb `cpu_total_compute` client config for the agent
runner, since Nomad cannot detect the cpu specs on the github public
runner without root.
> test-e2e: no need to run vaultcomat tests as root

- website/content/api-docs/jobs.mdx
- website/content/docs/concepts/architecture.mdx
- website/content/docs/concepts/node-pools.mdx
- website/content/docs/concepts/scheduling/index.mdx
- website/content/docs/concepts/scheduling/placement.mdx
- website/content/docs/concepts/scheduling/scheduling.mdx
- website/content/docs/job-specification/multiregion.mdx
- website/content/docs/other-specifications/node-pool.mdx
- website/content/docs/schedulers.mdx
- website/data/docs-nav-data.json
Add new Concepts page about node pools and expand the Architecture page to note planning client configuration. Also include some smaller changes where node pools may affect the scheduling outcome.
Preview links for the biggest changes:
https://nomad-git-docs-node-pools-hashicorp.vercel.app/nomad/docs/concepts/architecture#client-organization
https://nomad-git-docs-node-pools-hashicorp.vercel.app/nomad/docs/concepts/node-pools
> docs: expand documentation on node pools

- website/content/docs/concepts/architecture.mdx
- website/content/docs/glossary.mdx
- website/data/docs-nav-data.json
Preview link:
https://nomad-git-docs-move-glossary-hashicorp.vercel.app/nomad/docs/glossary
> docs: move glossary to a top-level menu item

- website/content/api-docs/jobs.mdx
- website/content/docs/commands/job/dispatch.mdx
- Add missing `IdPrefixTemplate` to the API docs.
- Fix casing of `IdempotencyToken` in the API docs.
- Remove `template` from the `-id-prefix-template` flag description. I found it to be confusing as, as far as I can tell, the value isn't actually templated.
Closes #18173
> docs: fix job dispatch documentation

- api/api.go
- api/retry.go
- api/retry_test.go
The SDK for the locking could benefit from a retry mechanism for calls made to the nomad server, this PR introduces this mechanism on top of the put call already present on the api.
> Add retry mechanism for put call

- client/lib/cgroupslib/default.go
- drivers/docker/driver.go
`cgroupslib.MaybeDisableMemorySwappiness` returned an incorrect type, and was
incorrectly typecast to `int64` causing a panic on non-linux and non-windows hosts.
> drivers/docker: fix a hostConfigMemorySwappiness panic

- .changelog/18120.txt
- ui/app/components/job-page/parts/title.js
- ui/mirage/config.js
- ui/tests/integration/components/job-page/helpers.js
- ui/tests/integration/components/job-page/periodic-test.js
- ui/tests/integration/components/job-page/service-test.js
Previously, the start button shown here wouldn't be aware of the HCL2 job specification of a job, unless the user had previously navigated to the /definition page.
This PR makes it so that the specification is fetched immediately before attempting a `start`.
Resolves #17806
> [ui] Preserve HCL2 on stop/start via the web UI

- .changelog/18234.txt
- nomad/csi_endpoint.go
- nomad/csi_endpoint_test.go
When a CSI volume is deleted when its plugin is not running, the function `volAndPluginLookup` returns a `nil` plugin value resulting a panic in the request handler.
Note to reviewers: the other place where `volAndPluginLookup` is used already checks for a `nil` plugin.
https://github.com/hashicorp/nomad/blob/e21ab7d948b96ad7c4a944abde8e703040e6eae7/nomad/csi_endpoint.go#L513-L518
> csi: prevent panic on volume delete

- .github/workflows/backport.yml
Backport assistant has been failing and generating wrong PRs and merges sometimes. Removing the `-automerge` flag allows us to review and fix backports before they are silently merged.
Examples of incorrect backporting:
https://github.com/hashicorp/nomad/pull/17925/files 
https://github.com/hashicorp/nomad/commit/950235df48869e0f3f1dc8950dc430394ababa85
https://github.com/hashicorp/nomad/pull/18234/files 
https://github.com/hashicorp/nomad/commit/52e2ad7807884aa385183c68d7bf653c49e4881d
> ci: remove backport automerge

- client/config/config.go
- client/config/testing.go
- command/agent/agent.go
- command/agent/agent_endpoint.go
- command/agent/command.go
- command/agent/config.go
- command/agent/config_parse.go
- command/agent/config_parse_test.go
- command/agent/config_test.go
- command/agent/testdata/extra-vault.hcl
- command/agent/testdata/sample0.json
- nomad/config.go
- nomad/structs/config/vault.go
Add the plumbing we need to accept multiple Vault clusters in Nomad agent configuration, to support upcoming Nomad Enterprise features. The `vault` blocks are differentiated by a new `name` field, and if the `name` is omitted it becomes the "default" Vault configuration. All blocks with the same name are merged together, as with the existing behavior.
Unfortunately we're still using HCL1 for parsing configuration and the `Decode` method doesn't parse multiple blocks differentiated only by a field name without a label. So we've had to add an extra parsing pass, similar to what we've done for HCL1 jobspecs.
For now, all existing consumers will use the "default" Vault configuration, so there's no user-facing behavior change in this changeset other than the contents of the agent self API. …
> config: parsing support for multiple Vault clusters in agent config

- .changelog/18210.txt
- ui/.template-lintrc.js
- ui/app/components/list-pagination/list-pager.js
- ui/app/templates/components/list-pagination/list-pager.hbs
- ui/config/environment.js
Adds a `[[` and `]]` key command to the `list-pager` prev/next page elements. These are included on, for example, the Jobs index page, clients index page, jobs.job.allocatinos page, etc.
> [ui] Use ]] and [[ to paginate index pages

- api/tasks.go
- command/agent/job_endpoint.go
- command/agent/job_endpoint_test.go
- nomad/structs/diff_test.go
- nomad/structs/structs.go
- nomad/structs/structs_test.go
- website/content/docs/job-specification/vault.mdx
Add new `role` field to the `vault` block in jobspecs that will be used to derive Vault ACL tokens from JWTs.
> jobspec: add `role` to `vault`

- client/fingerprint/vault.go
- client/fingerprint/vault_ce.go
- client/fingerprint/vault_test.go
- testutil/vault.go
Add fingerprinting we'll need to accept multiple Vault clusters in upcoming Nomad Enterprise features. The fingerprinter will create a map of Vault clients by cluster name. In Nomad CE, all but the default cluster will be ignored and there will be no visible behavior change.
_Don't merge until we've got a ENT repo PR ready for the `vault_ent.go` file._
> fingerprint: add support for fingerprinting multiple Vault clusters

- website/content/tools/autoscaling/plugins/apm/nomad.mdx
- website/content/tools/autoscaling/policy.mdx
Based on the [nomad-autoscaler source code](https://github.com/hashicorp/nomad-autoscaler/blob/954f26e8c56526d62f78d6991f5ff2a29dc6fa9f/plugins/builtin/apm/nomad/plugin/metrics.go#L37), the `query_window` property is ignored, if the Nomad APM plugin is in use, because that doesn't have memory.
> feat: improve policy documentation for "query_window" property

- .changelog/18232.txt
- client/fs_endpoint.go
- client/fs_endpoint_test.go
When an allocation is garbage collected from the client, but not from the servers, the API request is routed to the client and the client does attempt to read the file, but the alloc files have already been deleted, resulting in a 500 error.
This happens because the client GC only destroys the alloc runner (deleting the alloc dir), but it keeps a reference to the alloc runner until the alloc is garbage collected from the servers as well.
This commit adjusts this logic by checking if the alloc runner (and the alloc files) has been destroyed, returning a 404 if so.
Closes #18216
> client: 404 when accessing files for GC'ed alloc

- nomad/job_endpoint.go
- nomad/job_endpoint_hooks.go
- nomad/job_endpoint_hooks_test.go
This PR introduces a job-mutating hook that inserts an `Identity` block for services that use the `consul` provider. 
Relates to https://github.com/hashicorp/team-nomad/issues/404
> job_endpoint: jobIdentityCreator hook

- nomad/structs/diff.go
- nomad/structs/diff_test.go
Without this diff `nomad job plan` returns an empty destructive update:
Before:
```
$ nomad job plan redis.nomad.hcl
+/- Job: "example"
+/- Task Group: "cache" (1 create/destroy update)
+/- Task: "redis" (forces in-place update)
Scheduler dry-run:
- All tasks successfully allocated.
```
After:
```
$ nomad job plan redis.nomad.hcl
+/- Job: "example"
+/- Task Group: "cache" (1 create/destroy update)
+/- Task: "redis" (forces create/destroy update)
+/- Identity {
+/- Env:         "true" => "false"
+/- File:        "false" => "true"
Name:        "test"
ServiceName: ""
+/- Audience {
+ Audience: "test-2"
- Audience: "test"
}
}
+   Identity {
+ Env:         "false"
+ File:        "true"
+ Name:        "test-2"
ServiceName: ""
+ Audience {
+ Audience: "test-2"
}
}
```
No changelog since …
> jobspec: add diff for alternate workload identities

- nomad/job_endpoint_hooks.go
- nomad/job_endpoint_hooks_test.go
If there's an `identity` block present in the config, do not overwrite it
completely. Only set the `Name` and `ServiceName` fields, and keep the rest.
> job_endpoint hooks: fix identity block mutator behavior

- .github/workflows/semgrep.yml
closes #18312 
related https://github.com/hashicorp/nomad/issues/18325
> ci: migrate semgrep action from deprecated wrapper

- .changelog/18333.txt
- nomad/structs/services.go
- nomad/structs/services_test.go
`TLSSkipVerify` is ignored for Nomad service checks.
> nds: add validation for `tls_skip_verify`

- .changelog/18269.txt
- client/client.go
- client/client_test.go
A fix for https://github.com/hashicorp/nomad/issues/18267, ensuring that "time travel" of the client state is not possible.
I could not find tests which may exercise this logic meaningfully. Please point me the right direction and I'm happy to add them
Please note that this isn't an actual good fix to the underlying issue, but rather a stop-gap measure.
> Ensure that the index processed by the client is at least as new as the last one processed.

- .changelog/18332.txt
- nomad/structs/diff.go
- nomad/structs/diff_test.go
Without this diff `nomad job plan` won't report changes in `scaling` block.
Before:
```
$ nomad job plan job.hcl
+/- Job: "foo"
+/- Task Group: "foo" (1 create, 1 in-place update)
+/- Count: "1" => "2" (forces create)
Task: "foo"
```
After:
```
nomad job plan job.hcl
+/- Job: "foo"
+/- Task Group: "foo" (1 create, 1 in-place update)
+/- Count: "1" => "2" (forces create)
+   Scaling {
+ Enabled: "true"
+ Max:     "10"
+ Min:     "2"
+ Policy {
+ check[0][active_connections][0][query]:                                "scalar(open_connections_example_cache)"
+ check[0][active_connections][0][source]:                               "prometheus"
+ check[0][active_connections][0][strategy][0][target-value][0][target]: "20"
+ cooldown: …
```
> jobspec: add diff for Task Group Scaling block

- .changelog/18345.txt
- client/serviceregistration/checks/client.go
- client/serviceregistration/checks/client_test.go
This brings Nomad's service checks closer in line with those of Consul. Specifically, Consul provides the HTTP response body in the "Output" field of health checks, even those that are passing. 
This is needed for services that query the Nomad alloc checks API for more detailed service health info (for example, we return player count for game servers in our health check and use this to stop jobs that have no players for extended periods of time.)
On a side note, I'd like to think through (and would contribute to) a solid way to query for all health checks for a given service ala Consul's "/health/checks/:service" endpoint. 
I'm learning this is may be a limitation because health checks are only stored on the Nomad client and not replicated. Even an endpoint to get all health checks for a …
> client: include response body in output for successful HTTP checks

- .changelog/18345.txt
- client/serviceregistration/checks/client.go
- client/serviceregistration/checks/client_test.go
This reverts commit d0a93f12d1ec1e2b276f9958898c9a6fe4f6b077.
> Revert "client: include response body in output for successful HTTP checks (#18345)"

- website/content/docs/drivers/docker.mdx
Hi team,
This PR fixes the order of docker auth method.
Fixes: https://github.com/hashicorp/nomad/issues/17760
> docs: Update the order of docker auth method

- nomad/fsm.go
- nomad/state/state_store.go
- nomad/state/state_store_test.go
- nomad/state/testing.go
that occurred during server fsm restore, which later produced a negative slice index when trying to upsertJobVersion.
The bug appears to have been introduced in #17939 where [the risk was identified](https://github.com/hashicorp/nomad/pull/17939#discussion_r1268092633) but not quite covered all the way.
Stack trace of the panic:
```
==> Starting Nomad agent...
panic: runtime error: index out of range [-1]
goroutine 115 [running]:
github.com/hashicorp/nomad/nomad/state.(*StateStore).upsertJobVersion(0xc000ecedb0, 0x21da, 0xc000c50b40, 0xc000d70100)
github.com/hashicorp/nomad/nomad/state/state_store.go:2068 +0x370
github.com/hashicorp/nomad/nomad/state.(*StateStore).upsertJobImpl(0xc00146cd80?, 0x21da, 0x0, 0xc000c50b40, 0x0, 0xc000d70100) …
```
> fix panic from zero JobTrackedVersions config

- website/content/docs/networking/index.mdx
- website/content/docs/networking/service-discovery.mdx
> docs: fix broken link to Consul DNS overview page

- api/consul.go
- api/jobs_test.go
- api/services.go
- command/agent/job_endpoint.go
- command/agent/job_endpoint_test.go
- nomad/structs/consul.go
- nomad/structs/diff_test.go
- nomad/structs/services.go
- scheduler/util.go
This field supports the upcoming ENT-only multiple Consul clusters feature. The job validation and mutation hooks will come in a separate PR.
> jobspec: support `cluster` field for Consul and Service blocks

- client/fingerprint/vault_ce.go
Nomad CE only supports a single (default) Vault cluster, so log a warning if the user has configured multiple Vaults. Matches the logging done in https://github.com/hashicorp/nomad/pull/18392
> fingerprint: add warning in CE when there are multiple vaults

- api/api.go
- api/locks.go
- api/locks_test.go
- api/retry.go
- api/variables.go
- nomad/locks.go
- nomad/variables_endpoint.go
Add mechanism to run on high availability by using a lock to maintain the synchrony among instances, to ensure only one is running at all times, keeping others on stand by in case of failure.
For more information, refer to the RFC: [[NMD-179] Leader election using locking mechanism for the Autoscaler](https://go.hashi.co/rfc/nmd-179)
> [f-gh-17449-lease] Add lease mechanism to SDK

- client/fingerprint/consul.go
- client/fingerprint/consul_ce.go
- client/fingerprint/consul_test.go
- client/fingerprint/vault.go
Add fingerprinting we'll need to accept multiple Consul clusters in upcoming Nomad Enterprise features. The fingerprinter will create a map of Consul clients by cluster name. In Nomad CE, all but the default cluster will be ignored and there will be no visible behavior change.
_Note: similar to https://github.com/hashicorp/nomad/pull/18253, I'll need to prep an ENT PR to go with this one_
> fingerprint: add support for fingerprinting multiple Consul clusters

- .changelog/18426.txt
- client/fingerprint/consul.go
- client/fingerprint/consul_test.go
In the original design of Consul fingerprinting, we would poll every period so that we could change the client's fingerprint if Consul became unavailable. As of 1.4.0 (ref #14673) we no longer update the fingerprint in order to avoid excessive `Node.Register` RPCs when someone's Consul cluster is flapping.
This allows us to safely backoff Consul fingerprinting on success, just as we have with Vault.
Ref: https://github.com/hashicorp/nomad/pull/18392#discussion_r1318549264
> fingerprint: backoff on Consul fingerprint after initial success

- api/namespace.go
- command/agent/command.go
- command/namespace_apply.go
- command/namespace_apply_test.go
- command/namespace_status.go
- nomad/structs/consul.go
- nomad/structs/namespace.go
- nomad/structs/structs.go
- nomad/structs/structs_ce.go
- nomad/structs/structs_ce_test.go
- nomad/structs/structs_test.go
- nomad/structs/vault.go
In Nomad Enterprise when multiple Vault/Consul clusters are configured, cluster admins can control access to clusters for jobs via namespace ACLs, similar to how we've done so for node pools. This changeset updates the ACL configuration structs, but doesn't wire them up. I'll follow up with additional PRs for the job admission hooks and documentation. I'll also need a matching PR in the ENT repo for the validation/canonicalization methods.
> ACLs: allow/deny/default config for Consul/Vault clusters by namespace

- client/allocrunner/csi_hook.go
- client/allocrunner/csi_hook_test.go
- client/csi_endpoint.go
- client/pluginmanager/csimanager/instance.go
- client/pluginmanager/csimanager/interface.go
- client/pluginmanager/csimanager/manager.go
- client/pluginmanager/csimanager/volume.go
to align with its broader purpose, and the existing `volumeManager` implementation.
Arguably if this were being designed from scratch, maybe a tight little Mounter interface could be valuable, but this just brings the word usage into alignment, and I won't feel bad about taking advantage of all this nice plumbing to add `ExpandVolume` to this "Manager" soon.
I figure backporting this isolated change might be good for other future bugfixes or similar in this territory, but let me know if I shouldn't backport it for some reason.
> CSI: Rename volume Mounter to Manager

- .changelog/18419.txt
- client/acl.go
- client/acl_test.go
This change deduplicates the ACL policy list generated from ACL roles referenced within an ACL token on the client.
Previously the list could contain duplicates, which would cause erronous permission denied errors when calling client related RPC/ HTTP API endpoints. This is because the client calls the ACL get policies endpoint which subsequently ensures the caller has permission to view the ACL policies. This check is performed by comparing the requested list args with the policies referenced by the caller ACL token. When a duplicate is present, this check fails, as the check must ensure the slices match exactly.
The linked issue has details on how to reproduce the problem, if readers want to test this before and after the code changes.
Closes #17201
> client: fix role permission issue with duplicate policies.

- api/locks.go
Following the Consul example, where the user can configure the number of retries on the calls to the locks endpoint, this PR introduces the same functionality for the locks handler in nomad.
> Add functional option to configure max retries

- e2e/terraform/packer/windows-2016-amd64.pkr.hcl
E2E tests have not been running due to Windows packer build failing with "No AMI was found matching filters"
Specifically the filter that this PR alters, because "Containers" AMIs evaporated at some point...
https://aws.amazon.com/marketplace/pp/prodview-yfve3zjgfjtug
> This version has been removed and is no longer available to new customers.
Related PR from not that long ago, which switched to "Containers" -- #17572 
I confirmed that "[ECS_Optimized](https://aws.amazon.com/marketplace/pp/prodview-i7fubrhchpwdi)" can run docker commands, and build scripts run clean, but I have not verified an actual E2E run against it manually.
I tried updating to 2019, but at least one build script failed (install-consul.ps1), and I don't want to hunt it down right now.  For posterity, the error was: …
> e2e: packer windows from "ECS_Optimized" image

- api/api.go
- api/locks.go
- api/retry.go
- api/retry_test.go
- command/var_lock.go
Following the Consul lead, this PR introduces a flag to use on the CLI when using the var lock command that allows the user to modify the number of times the client retries a call in case of an unexpected response.
> [f-gh-17449] Add flag to modify the number of time the client attempts to call the locks endpoints

- website/content/docs/configuration/consul.mdx
- website/content/docs/configuration/vault.mdx
- website/content/docs/job-specification/group.mdx
- website/content/docs/job-specification/service.mdx
- website/content/docs/job-specification/vault.mdx
- website/content/docs/other-specifications/namespace.mdx
This changeset is the documentation for supporting multiple Vault and Consul clusters in Nomad Enterprise. It includes documentation changes for the agent configuration (#18255), the namespace specification (#18425), and the vault, consul, and service blocks of the jobspec (#18409).
Preview links:
* https://nomad-asjneuto4-hashicorp.vercel.app/nomad/docs/configuration/consul
* https://nomad-asjneuto4-hashicorp.vercel.app/nomad/docs/configuration/vault
* https://nomad-asjneuto4-hashicorp.vercel.app/nomad/docs/other-specifications/namespace
* https://nomad-asjneuto4-hashicorp.vercel.app/nomad/docs/job-specification/group#cluster
* https://nomad-asjneuto4-hashicorp.vercel.app/nomad/docs/job-specification/service#cluster
* https://nomad-asjneuto4-hashicorp.vercel.app/nomad/docs/job-specificati …
> docs: support multiple Vault and Consul clusters (ENT-only)

- command/agent/config_parse.go
- command/agent/config_parse_test.go
- command/agent/testdata/basic.hcl
- command/agent/testdata/basic.json
- nomad/config.go
- nomad/job_endpoint_hook_implicit_identities.go
- nomad/job_endpoint_hook_implicit_identities_test.go
- nomad/job_endpoint_hooks.go
- nomad/job_endpoint_hooks_test.go
- nomad/structs/config/vault.go
- nomad/structs/config/vault_test.go
- nomad/structs/structs.go
- nomad/structs/structs_test.go
Add new agent configuration `use_identity` and `default_identity` to the `vault` block.
`use_identity` is a boolean value that determines if Vault tokens should be derived from workload identity JWTs instead of the traditional flow of relying on Nomad servers for token derivation. If `use_identity` is `true` jobs with a `vault` block receive an implicit `identity` called `vault` if one is not already present.
`default_identity` is the `identity` block injected to tasks that don't define an `identity` block named `vault`.
Job validation on register becomes a little more complicated because we now need to check three places:
1. `vault` block in job
2. `vault` block in server config
3. `identity` in task
```mermaid
flowchart TD
Start[Job Registered] --> HasVault{Job has vault block?} …
```
> vault: add `use_identity` and `default_identity` agent configuration and implicit workload identity

- nomad/locks.go
- nomad/locks_test.go
- nomad/variables_endpoint.go
The [PR](https://github.com/hashicorp/nomad/pull/17660) removed the function VarGet that was used for the lock renewal. This PR updates the code to use a different function that was not removed.
> [f-gh-17449] Remove usage of deleted function 

- .changelog/18444.txt
- client/allocrunner/taskrunner/getter/util.go
- helper/subproc/subproc.go
possible fix for https://github.com/hashicorp/nomad/issues/18442
EDIT:
Tested the locally built Nomad agent binary using `nomad agent -dev` with:
```bash
mkdir large_tar
cd large_tar/
mkdir data
for i in {1..5000} ; do echo "" > data/$i.txt; done
tar czvf data.tar.gz data/
python3 -m http.server 9000
```
```hcl
job "tar_fail" {
group "cache" {
network {
port "db" {
to = 6379
}
}
task "redis" {
artifact {
source      = "http://127.0.0.1:9000/data.tar.gz"
destination = "local/some-directory"
}
config {
image          = "redis:7"
ports          = ["db"]
auth_soft_fail = true
}
identity {
env  = true
file = true
}
resources {
cpu    = 500
memory = 256
}
}
}
}
```
> bubble up the error message from go-getter

- website/content/docs/concepts/variables.mdx
It was not obvious to me that Nomad Variables could themselves be used in templates. I read this page and wasn't exactly sure what they're used for w/o an example.
The timeline was:
1. day 0: read this page
2. day 1-2: monkey with HCL2 variables in job specs
3. day 3: come across this page on [Nomad Variables in templates](https://developer.hashicorp.com/nomad/docs/job-specification/template#nomad-variables) when it dawned on me that... that's how they can be used and it's sick
This PR adds two links and one sentence to try to get that across to Nomad novices like myself so they can go straight from Nomad Variables > "oh this is cool" faster.
I think ideally this doc also has an example like from the Nomad Variables section of the `template` page:
```md
template {
data        = <<EOH
{{ …
```
> Add more links from Variables doc to Nomad Variable template examples

- helper/subproc/subproc.go
I somehow missed this was failing in https://github.com/hashicorp/nomad/pull/18444
> lint: fix a missing gofmt -s

- nomad/job_endpoint_hooks_test.go
- nomad/structs/services.go
- nomad/structs/structs.go
Apply workload identity warnings to group and task level Consul services that have an identity assigned.
> consul: check for warnings on service identity

- website/content/docs/configuration/vault.mdx
Update documentation for the agent configuration `vault` block for workload identity support.
Preview link: https://nomad-git-docs-vault-wid-hashicorp.vercel.app/nomad/docs/configuration/vault
> docs: update Vault config for workload identity

- .changelog/18463.txt
- api/agent.go
- api/agent_test.go
- command/agent/agent_endpoint.go
- command/server_force_leave.go
- nomad/server.go
- website/content/api-docs/agent.mdx
- website/content/docs/commands/server/force-leave.mdx
This feature will help operator to remove a failed/left node from Serf layer immediately without waiting for 24 hours for the node to be reaped
* Update CLI with prune flag
* Update API /v1/agent/force-leave with prune query string parameter
* Update CLI and API doc
* Add unit test
> feature: Add prune flag for nomad server force-leave command

- website/content/api-docs/variables/index.mdx
- website/content/api-docs/variables/locks.mdx
- website/content/api-docs/variables/variables.mdx
- website/content/docs/commands/var/lock.mdx
- website/data/api-docs-nav-data.json
- website/data/docs-nav-data.json
Related: https://github.com/hashicorp/nomad/issues/17449
> [f-gh-17449] Docs: Add website documentation for the var lock command and HTTP lock operations

- api/locks.go
- api/retry.go
- api/variables_test.go
- command/agent/variable_endpoint_test.go
- nomad/state/state_store_variables.go
- nomad/state/state_store_variables_test.go
- nomad/structs/variables.go
- nomad/variables_endpoint.go
- nomad/variables_endpoint_test.go
This PR addresses a 3 of small issues:
-  The logic to not show the lock ID unless a management token was used for the Read and List endpoints only worked if ACL was enabled, by changing `if aclObj != nil && !aclObj.IsManagement() ` to `!(aclObj != nil && aclObj.IsManagement())` the problem is fixed. 
- When a new variable is created and it includes lock parameters, the endpoint returns an error, to avoid creating locks without TTL
- When releasing a lock, the items provided in the variable are ignored because the lock release operation doesn't update the items, in this PR a new type of error is introduces to reject this requests.
> [f-gh-17449] Locks: Fixes for lock visibility

- nomad/job_endpoint.go
- nomad/job_endpoint_test.go
When job registrations are disabled, there's no reason to do the potentially expensive job mutation and admission hooks. Move the ACL resolution and this check before those hooks.
> job endpoint: reorder check for disabled job registrations

- client/allocrunner/csi_hook_test.go
- client/csi_endpoint.go
- client/csi_endpoint_test.go
- client/pluginmanager/csimanager/interface.go
- client/pluginmanager/csimanager/testing.go
- client/pluginmanager/csimanager/volume.go
- client/structs/csi.go
- client/structs/csi_test.go
- nomad/client_csi_endpoint.go
- nomad/client_csi_endpoint_test.go
- nomad/csi_endpoint.go
- nomad/csi_endpoint_test.go
- plugins/csi/client.go
- plugins/csi/client_test.go
- plugins/csi/plugin.go
- plugins/csi/testing/client.go
Follow-up to #18359, wrapping up the full feature requested in #10324 (sans docs)
After the controller plugin has expanded the disk at e.g. a cloud vendor, it may say that we also need to issue [NodeExpandVolume](https://github.com/container-storage-interface/spec/blob/c918b7f/spec.md#nodeexpandvolume) for the node plugin to make the new disk space available to task(s) that have claims on the volume by e.g. expanding the filesystem on the node.
The main gap in test coverage is `sendCSINodeRPC` which I split out from `ClientCSI.NodeDetachVolume`, which was not actually tested before.  I know that it works, but I'm open to (figuring out how to) add proper coverage there, amongst all the other layers with greater coverage, if it's a considerable concern.
> CSI: Expand Volume (Node edition)

- nomad/job_endpoint.go
- nomad/job_endpoint_hook_consul_ce.go
- nomad/job_endpoint_hooks.go
- nomad/job_endpoint_hooks_test.go
- nomad/structs/consul.go
- nomad/structs/job.go
- nomad/structs/services.go
Update the implicit constraint mutating hook to support multiple Vault and Consul clusters in Nomad Enterprise. This requires moving the Vault/Consul mutating hooks earlier in the list as well, because that'll ensure we've canonicalized properly for multiple clusters.
> job endpoint: implicit constraints for multi-Vault/Consul

- api/locks.go
- api/locks_test.go
- api/variables.go
- command/var_lock.go
This PR introduces 2 new options to the API and var lock command to allow users to return early if the lock is not acquired and to modify the sleep period between calls to lock acquire.
> [f-gh-17449] Add early return and configurable backoff to the leaser

- command/agent/config_parse.go
- command/agent/config_parse_test.go
- command/agent/testdata/basic.hcl
- command/agent/testdata/basic.json
- nomad/config.go
- nomad/job_endpoint_hook_implicit_identities.go
- nomad/job_endpoint_hook_implicit_identities_test.go
- nomad/structs/config/consul.go
The original thinking for Workload Identity integration with Consul and Vault was that we'd allow `template` blocks to specify their own identity. But because the login to Consul/Vault to get tokens happens at the task level, this would involve making the `template` block a new WID watcher on its own rather than using the Consul and Vault hooks we're building at the group/task level.
So it doesn't make sense to have separate identities for individual `template` blocks rather than at the level of tasks. Update the agent configuration to rename the `template_identity` to the more accurate `task_identity`, which will be used for any non-service hooks (just `template` today).
Update the implicit identities job mutation hook to create the identity we'll need as well.
> config: remove `consul.template_identity` in lieu of `task_identity`

- .changelog/18318.txt
- .github/workflows/ember-test-audit.yml
- ui/app/components/client-node-row.js
- ui/app/components/server-agent-row.js
- ui/app/templates/components/client-node-row.hbs
- ui/app/templates/components/server-agent-row.hbs
- ui/tests/acceptance/clients-list-test.js
- ui/tests/acceptance/servers-list-test.js
- ui/tests/pages/clients/list.js
Plus a nice little icon for when a server is leader
> [ui] Color indicators for server/client status

- client/allocrunner/csi_hook_test.go
- client/csi_endpoint_test.go
- client/pluginmanager/csimanager/testing.go
- testutil/mock_calls.go
Right up front: I have mixed feelings about this.  Let me know if I should just throw it out :yum: 
Instead of separately implementing csimanager
interfaces in two separate places:
* client/allocrunner/csi_hook_test
* client/csi_endpoint_test
they can both use the same mocks defined in
client/pluginmanager/csimanager/
alongside the actual implementations of them.
---
My misgivings: my desire to leave the csi_hook tests mostly unchanged has resulted in a sorta franken-mock where ExpandVolume sticks out as different, since it tracks LastExpandVolumeCall, which I wanted in client/csi_endpoint, whereas allocrunner/csi_hook does call counting.
I'm not thrilled with the result... I might prefer proper call recording across the board, which could also cover call counts, but I should probably …
> test: Refactor mock CSI manager

- client/allocrunner/csi_hook_test.go
- client/csi_endpoint_test.go
- client/pluginmanager/csimanager/testing.go
- testutil/mock_calls.go
manual backport of #18554 - 7bd5c6e84e to 1.5.x
auto backport should work for 1.4.x from here.
> backport test: Refactor mock CSI manager into release/1.5.x

- client/allocrunner/csi_hook_test.go
- client/csi_endpoint_test.go
- client/pluginmanager/csimanager/testing.go
- testutil/mock_calls.go
last (:crossed_fingers:) rendition of #18554
> backport test: Refactor mock CSI manager (#18554) into release/1.4.x

- nomad/state/state_store.go
- nomad/structs/csi.go
- nomad/structs/csi_test.go
fix for part of: c6dbba7cde911bb08f1f8da445a44a0125cd2047 (specifically around [here](https://github.com/hashicorp/nomad/commit/c6dbba7cde911bb08f1f8da445a44a0125cd2047#diff-53c7d524897a192ece819816a9dcf006dee46747fbb853e7f638601ea556a72cL2433-L2435))
which allowed updating volumes while in use,
because CSI expand may occur while in use.
but it mistakenly stopped copying other
important values that may be updated
whether in use or not.
this moves some of the in-use validation to
happen during Merge(), before writing to state,
leaving UpsertCSIVolume with only minimal final
sanity-checking.
> csi: fix volume updating behavior

- client/client.go
- command/agent/config_parse.go
- command/agent/config_parse_test.go
- command/agent/testdata/extra-consul.hcl
- command/agent/testdata/extra-vault.hcl
- nomad/structs/config/workload_id.go
- nomad/structs/config/workload_id_test.go
Breaking up #18534 into more manageable pieces, this PR fixes some small bugs in configuration parsing and handling of workload identity and multi Consul and Vault. 
Each commit contains a specific bug fix.
> config: fix some issues with workload identity and multi Consul and Vault

- client/allocrunner/taskrunner/task_runner_linux_test.go
- client/allocrunner/taskrunner/task_runner_test.go
- client/config/config.go
- client/config/config_ce.go
- client/config/testing.go
- client/fingerprint/vault.go
- client/fingerprint/vault_test.go
- command/agent/command.go
- command/agent/config.go
- command/agent/config_parse.go
- command/agent/config_parse_test.go
- command/agent/config_test.go
- command/agent/job_endpoint_test.go
- nomad/config.go
- nomad/job_endpoint_hook_implicit_identities.go
- nomad/job_endpoint_hook_implicit_identities_test.go
- nomad/job_endpoint_hook_vault_ce_test.go
- nomad/job_endpoint_hooks.go
- nomad/job_endpoint_hooks_test.go
- nomad/structs/config/vault.go
- nomad/structs/diff_test.go
- nomad/structs/structs.go
- nomad/structs/vault.go
- nomad/structs/workload_id.go
- testutil/vault.go
- website/content/docs/configuration/vault.mdx
Another workstream split from #18534.
In the original proposal, workload identities used to derive Vault tokens were expected to be called just `vault`. But in order to support multiple Vault clusters it is necessary to associate identities with specific Vault cluster configuration.
This PR implements a new proposal to have Vault identities named as `vault_<cluster>`.
To avoid the use of the hard coded string `"default"`, a new constant named `VaultDefaultCluster` was created. https://github.com/hashicorp/nomad/commit/4be533d69223c239e5e9ec5650855902c35358eb updates previous uses of `"default"` in the context of a Vault cluster to use this new constant and may ignored or reviewed separately to reduce noise. 
I wasn't sure if this is something we would want to have so we can also easily …
> vault: update identity name to start with `vault_`

- command/agent/config_parse_test.go
- command/agent/testdata/basic.hcl
- command/agent/testdata/basic.json
- nomad/config.go
- nomad/job_endpoint_hook_implicit_identities.go
- nomad/job_endpoint_hook_implicit_identities_test.go
- nomad/job_endpoint_hooks.go
- nomad/job_endpoint_hooks_test.go
- nomad/structs/config/vault.go
- nomad/structs/config/vault_test.go
- website/content/docs/configuration/vault.mdx
The initial intention behind the `vault.use_identity` configuration was to indicate to Nomad servers that they would need to sign a workload identities for allocs with a `vault` block.
But in order to support identity renewal, #18262 and #18431 moved the token signing logic to the alloc runner since a new token needs to be signed prior to the TTL expiring.
So #18343 implemented `use_identity` as a flag to indicate that the workload identity JWT flow should be used when deriving Vault tokens for tasks.
But this configuration value is set on servers so it is not available to clients at the time of token derivation, making its meaning not clear: a job may end up using the identity-based flow even when `use_identity` is `false`.
The only reliable signal available to clients at token …
> vault: remove `use_identity` agent config

- .changelog/18595.txt
- ui/app/models/task-event.js
- ui/mirage/factories/task-event.js
- ui/tests/acceptance/allocation-detail-test.js
- ui/tests/acceptance/job-status-panel-test.js
- ui/tests/acceptance/task-detail-test.js
- ui/tests/unit/models/task-test.js
Resolves https://github.com/hashicorp/nomad/issues/18507
Task restarts (and possibly other events) use more time specificity than is needed (for example, "task restarting in 10.01934802s").
This simplifies and rounds times to simple second, minute, or hour strings where relevant.
> [ui] Simplify times in task events

- client/client.go
- nomad/alloc_endpoint.go
Similar to #18269, it is possible that even if Node.GetClientAllocs retrieves fresh allocs that the subsequent Alloc.GetAllocs call retrieves stale allocs. While [`diffAlloc(existing, updated)`](https://github.com/hashicorp/nomad/blob/v1.6.2/client/util.go#L27-L46) properly ignores stale alloc *updates*, alloc deletions have no such check.
So if a client retrieves an alloc created at index 123, and then a subsequent Alloc.GetAllocs call hits a new server which returns results at index 100, the client will stop the alloc created at 123 because it will be missing from the stale response.
This change applies the same logic as #18269 and ensures only fresh responses are used.
Glossary:
* fresh - modified at an index > the query index
* stale - modified at an index <= the query index
> client: prevent using stale allocs

- ci/test-core.json
- command/agent/agent.go
- nomad/config.go
- nomad/reporting/reporting_ce.go
- nomad/server.go
To continue with the licensing reporting, the configuration needs to be passed down to the server who will in turn be responsable for the metrics. This PR adds the a reporting manager that will only be populated and used on the enterprise version.
Related: [#1106](https://github.com/hashicorp/nomad-enterprise/issues/1106)
> server: Add reporting configuration to  nomad server

- client/config/config.go
- client/config/config_ce.go
- client/fingerprint/consul.go
- client/fingerprint/consul_test.go
- command/agent/command.go
- command/agent/config.go
- command/agent/config_parse.go
- command/agent/config_parse_test.go
- command/agent/config_test.go
- command/agent/job_endpoint_test.go
- nomad/config.go
- nomad/job_endpoint_hook_consul_ce_test.go
- nomad/job_endpoint_hooks.go
- nomad/structs/consul.go
Use the constant `structs.ConsulDefaultCluster` instead of the string literal "default", as we've done for Vault.
> consul: use constant instead of "default" literal

- client/widmgr/widmgr.go
Since the `identity_hook` is meant to be the central place that makes signed identities available to other hooks, it should also expose the `default` identity that is signed by the plan applier. 
> WI: WIDMgr should expose default identity signatures

- .changelog/18621.txt
- ui/app/components/job-page/parts/title.js
In Nomad 1.6, we introduced HCL-in-the-UI using a new /submissions endpoint among other things.
Shortly after the release, we realized we missed a spot: stop/starting via the UI would not maintain the submission data. My initial fix for this solved the issue of maintaining HCL, but caused a new bug: jobs that lacked submission data (perhaps they were submitted via curl with just the json spec, and without HCL) would 404 on /submission and fail to progress through to /parse and submit.
This PR provides a fallback to the initial method in cases where the /submission request fails.
Resolves #18547 
Resolves #18536
> [ui] bugfix: when hitting the "start" button on a job page, if it has no submission data, fallback to raw json definition

- api/tasks.go
- client/allocrunner/taskrunner/task_runner_hooks.go
- command/agent/job_endpoint.go
- nomad/structs/diff.go
- nomad/structs/structs.go
- scheduler/util.go
To support Workload Identity with Consul for templates, we want templates to be able to use the WI created at the task scope (either implicitly or set by the user). But to allow different tasks within a group to be assigned to different clusters as we're doing for Vault, we need to be able to set the `consul` block with its `cluster` field at the task level to override the group.
> consul: allow `consul` block in task scope

- client/allocwatcher/alloc_watcher.go
- client/client.go
When waiting on a previous alloc we must query against the leader before switching to a stale query with index set.
Also check to ensure the response is fresh before using it like #18269
> client: prevent watching stale alloc state

- command/agent/config.go
- command/agent/config_parse_test.go
- command/agent/config_test.go
- command/agent/testagent.go
Apply the expected default values when loading additional Consul and Vault cluster configuration. Without these defaults some fields would be left empty.
> config: apply defaults to extra Consul and Vault

- nomad/job_endpoint_hook_implicit_identities.go
- nomad/job_endpoint_hook_implicit_identities_test.go
- nomad/structs/services.go
- nomad/structs/structs.go
`consul_hook` depends on Consul service and task identity names being unique. 
> consul: make service and task identity names unique

- .changelog/18604.txt
- command/alloc_logs.go
> cli: use same offset when following single or multiple alloc logs.

- client/allocrunner/taskrunner/sids_hook.go
- client/allocrunner/taskrunner/task_runner_hooks.go
- client/allocrunner/taskrunner/task_runner_test.go
The `sids_hook` runs for Connect sidecar/gateway tasks and gets Consul Service Identity (SI) tokens for use by the Envoy bootstrap hook. When Workload Identity is being used with Consul, the `consul_hook` will have already added these tokens to the alloc hook resources. Update the `sids_hook` to use those tokens instead and write them to the expected area of the taskdir.
> sids_hook: read tokens from consul_hook when available

- .changelog/18637.txt
- nomad/job_endpoint.go
I noticed this while working on hashicorp/nomad-autoscaler#604 -- When a job went away, the blocking query on `/v1/job/{job-id}/scale` kept blocking for the full 5 minute timeout, instead of returning "not found" as soon as the job was purged/gc'd.
returning a nil error in a `blockingOptions.run()`
without increasing the reply `Index` can cause the
query to block indefinitely (until timeout).
this fixes that happening in `Job.ScaleStatus`
when the job is deleted -- the job going away
should now return as not-found and provide a new
index for the caller to try if they so please.
> scaling: set Index on nil-job scale status reply

- client/allocrunner/alloc_runner_hooks.go
- client/allocrunner/group_service_hook.go
- client/allocrunner/group_service_hook_test.go
- client/allocrunner/taskrunner/script_check_hook_test.go
- client/allocrunner/taskrunner/service_hook.go
- client/allocrunner/taskrunner/service_hook_test.go
- client/allocrunner/taskrunner/task_runner_hooks.go
- client/allocrunner/taskrunner/task_runner_test.go
- command/agent/consul/int_test.go
When Workload Identity is being used with Consul, the `consul_hook` will add Consul tokens to the alloc hook resources. Update the `group_service_hook` and `service_hook` to use those tokens when available for registering and deregistering Consul workloads.
> services: get Consul token from hook resources

- .changelog/18584.txt
- client/allocrunner/alloc_runner_hooks.go
- client/allocrunner/checks_hook.go
- client/allocrunner/checks_hook_test.go
> fix: use interpolated address when performing health checks

- .changelog/17383.txt
- api/operator.go
- command/agent/operator_endpoint.go
- command/agent/operator_endpoint_test.go
- command/commands.go
- command/operator_raft_leadership_transfer.go
- nomad/leader.go
- nomad/operator_endpoint.go
- nomad/operator_endpoint_test.go
- nomad/structs/operator.go
- website/content/api-docs/operator/raft.mdx
- website/content/docs/commands/operator/raft/transfer-leadership.mdx
- website/data/docs-nav-data.json
This PR adds an API endpoint and a CLI command to allow cluster operators to move leadership from the current leader to a specified server node. This can reduce leadership churn during rolling updates by allowing the operator to migrate leadership to the first upgraded node.
**Commits**
- Add directed leadership transfer func
- Add leadership transfer RPC endpoint
- Add ACL tests for leadership-transfer endpoint
- Add HTTP API route and implementation
- Add to Go API client
- Implement CLI command
- Add documentation
- [🔍 cli docs](https://nomad-qglbkcast-hashicorp.vercel.app/nomad/docs/commands/operator/raft/transfer-leadership)
- [🔍 api docs](https://nomad-qglbkcast-hashicorp.vercel.app/nomad/api-docs/operator/raft#transfer-leadership-to-another-raft-peer)
Fixes: …
> [server] Directed leadership transfer CLI and API

- client/vaultclient/vaultclient.go
- client/vaultclient/vaultclient_test.go
- client/vaultclient_test.go
This PR eliminates the vaultclient test import cycle by putting the test file into a separate package and making vaultclient objects public. 
Ref https://github.com/hashicorp/team-nomad/issues/404
> vault: eliminate vaultclient test import cycle

- nomad/leader.go
- nomad/leader_ce.go
- nomad/leader_test.go
- nomad/node_endpoint.go
- nomad/operator_endpoint_test.go
- nomad/server.go
- nomad/testing.go
This PR changes the usage of Cluster ID to Cluster metadata and uses it to start the reporting agent.
Refer to [1257](https://github.com/hashicorp/nomad-enterprise/pull/1257)
> [f-gh-1106-reporting] Use full cluster metadata for reporting 

- .changelog/18662.txt
- client/allocrunner/taskrunner/task_runner.go
Since the allocation in the task runner is updated in a separate goroutine, a race condition may happen where the task is started but the prestart hooks are skipped because the allocation became terminal.
Checking for a terminal allocation before proceeding with the task start ensures the task only runs if the prestart hooks are also executed.
Since `shouldShutdown()` only uses terminal allocation status, it remains `true` after the first transition, so it's safe to check it again after the prestart hooks as it will never revert to `false`.
Some other implementations ideas I considered:
1. Move the check for `shouldShutdown()` from within `prestart()` to before it is called. I think this would be more or less equivalent to this approach.
2. Create a read lock on the task runner alloc so …
> client: ensure task only runs with prestart hooks

- .changelog/18664.txt
- client/meta_endpoint.go
- client/meta_endpoint_test.go
Setting a null value to a node metadata is expected to remove it from subsequent reads. This is true both for static node metadata (defined in the agent configuration file) as well as for dynamic node metadata (defined via the Nomad API).
Null values for static metadata must be persisted to indicate that the value has been removed, but strictly dynamic metadata null values can be removed from state and client memory.
Closes #18603
> client: remove null dynamic metadata keys

- .changelog/18598.txt
- ui/app/components/editable-variable-link.hbs
On the new /job/:jobid/variables page, we list variables that can be automatically read by the job in question.
In the event that the user does not have `write variable` access, we want to provide the name of the path, not as a link, so it can at least be known to them.
Without the wrapping `{{}}` brackets, this would always output the string "@path", instead of the desired passed path string.
> [ui] Bugfix: Wrap the passed path prop as a handlebars tag

- scheduler/feasible.go
- scheduler/stack.go
- scheduler/stack_test.go
Host volumes were considered regular feasibility checks. This had two unintended consequences.
The first happened when scheduling an allocation with a host volume on a set of nodes with the same computed class but where only some of them had the desired host volume.
If the first node evaluated did not have the host volume, the entire node class was considered ineligible for the task group.
```go
// Run the job feasibility checks.
for _, check := range w.jobCheckers {
feasible := check.Feasible(option)
if !feasible {
// If the job hasn't escaped, set it to be ineligible since it
// failed a job check.
if !jobEscaped {
evalElig.SetJobEligibility(false, option.ComputedClass)
}
continue OUTER
}
}
```
This results in all nodes with the same computed class to be skipped, even if they do have …
> scheduler: fix host volume feasibility check

- client/allocrunner/consul_hook.go
- client/allocrunner/identity_hook_test.go
- client/allocrunner/taskrunner/identity_hook.go
- client/allocrunner/taskrunner/identity_hook_test.go
- client/widmgr/mock.go
- client/widmgr/widmgr.go
- client/widmgr/widmgr_test.go
- nomad/alloc_endpoint.go
- nomad/alloc_endpoint_test.go
- nomad/plan_apply.go
- nomad/structs/services.go
- nomad/structs/structs.go
- nomad/structs/workload_id.go
Any code that tracks workloads and their identities should not rely on string comparisons, especially since we support 2 types of workload identities: those that identify tasks and those that identify services. This means we cannot rely on `task.Name` for workload-identity pairs. 
The new type `structs.WIHandle` solves this problem by providing a uniform way of identifying workloads and their identities. 
(https://github.com/hashicorp/nomad/pull/18650 depends on this PR)
> wi: introduce workload identity handler

- .changelog/18676.txt
- GNUmakefile
Nomad uses `time.LoadLocation()` to translate a periodic job time zone string value to a `time.Location`. From godocs:
LoadLocation looks for the IANA Time Zone database in the following locations in order:
* the directory or uncompressed zip file named by the ZONEINFO environment variable
* on a Unix system, the system standard installation location
* $GOROOT/lib/time/zoneinfo.zip
* the time/tzdata package, if it was imported
So non-Unix systems require Go to be installed or `time/tzdata` to be imported, otherwise running periodic jobs with a specific `time_zone` value results in an error:
Invalid time zone "America/Toronto": unknown time zone America/Toronto
This commit adds the `timetzdata` build tag on Windows to embed the time zone data into the final binary. This results in a …
> build: load time/tzdata on Windows

- client/allocrunner/alloc_runner.go
- client/allocrunner/identity_hook_test.go
- client/allocrunner/taskrunner/identity_hook_test.go
- client/allocrunner/taskrunner/task_runner_test.go
- client/state/db_bolt.go
- client/state/db_error.go
- client/state/db_mem.go
- client/state/db_noop.go
- client/state/interface.go
- client/widmgr/mock.go
- client/widmgr/widmgr.go
- client/widmgr/widmgr_int_test.go
- client/widmgr/widmgr_test.go
When clients are restarted and the identity hook runs when we restore allocations, the running allocations are likely to have already-signed Workload Identities that are unexpired. Save these to the client's local state DB so that we can avoid a thundering herd of RPCs during client restart. When we restore, we'll check if there's at least one expired signed WI before making any initial signing request.
Included:
* Renames `getIdentities` to `getInitialIdentities` to make the workflow more clear.
* Renames the existing `widmgr_test.go` file of integration tests, which is in its own package to avoid circular imports to `widmgr_int_test.go`
Currently WIP because we'll need https://github.com/hashicorp/nomad/pull/18650 for it to make any sense for service identities, which @pkazmierczak is …
> WID manager: save and restore signed WIs from client state DB

- .changelog/18689.txt
- command/acl_token_update.go
- website/content/docs/commands/acl/token/update.mdx
With a default value set to `client`, the `nomad acl token update` command can silently downgrade a management token to client on update if the command does not specify `-type=management` on every update.
> cli: remove default for ACL token type on update

- nomad/leader.go
- nomad/leader_test.go
- nomad/node_endpoint.go
- nomad/server.go
This PR backports some changes from the ent repo for consistency.
> server: Rename functions and use iterator function for clarity

- client/vaultclient_test.go
- go.mod
- go.sum
- nomad/vault_test.go
Nomad imports the Vault SDK to get testing helpers, but it turns out the only thing actually in use was a single string constant for the Vault namespace header. Remove this dependency and hardcode the constant to reduce dependency churn.
> deps: remove Vault SDK

- .semgrep/rpc_endpoint.yml
- acl/acl.go
- acl/acl_test.go
- acl/virtual.go
- nomad/acl.go
- nomad/auth/auth.go
- nomad/auth/auth_test.go
- nomad/client_csi_endpoint.go
- nomad/deployment_endpoint.go
- nomad/encrypter_test.go
- nomad/eval_endpoint.go
- nomad/keyring_endpoint.go
- nomad/keyring_endpoint_test.go
- nomad/plan_endpoint.go
- nomad/rpc_test.go
The RPC handlers expect to see `nil` ACL objects whenever ACLs are disabled. By using `nil` as a sentinel value, we have the risk of nil pointer exceptions and improper handling of `nil` when returned from our various auth methods that can lead to privilege escalation bugs. This is the second in a series to eliminate the use of `nil` ACLs as a sentinel value for when ACLs are disabled.
This patch involves creating a new "virtual" ACL object for checking permissions on server operations and a matching `AuthenticateServerOnly` method for server-only RPCs that can produce that ACL.
Ref: https://github.com/hashicorp/nomad-enterprise/pull/1218
Ref: https://github.com/hashicorp/nomad/pull/18703
> auth: add server-only ACL

- api/retry_test.go
The retry tests in the `api` package set up a client but don't use `NewClient`, so the address never gets parsed into a `url.URL` and that's causing some test failures.
> testing: fix configuration for retry tests

- api/tasks.go
- command/agent/alloc_endpoint.go
- command/agent/job_endpoint.go
- command/agent/job_endpoint_test.go
- command/agent/testingutils_test.go
- jobspec/parse_task.go
- nomad/mock/job.go
- nomad/structs/actions.go
- nomad/structs/diff.go
- nomad/structs/diff_test.go
- nomad/structs/funcs.go
- nomad/structs/structs.go
- ui/app/services/sockets.js
- ui/config/environment.js
First steps in setting up Nomad Actions (#18627)
- Establishes the Action struct at task level and allows them to be included in a jobspec
- Returns them under tasks on the GET job endpoint
Also includes a (temporary) workaround to get exec working on our local Ember development environment: direct forwarding to :4646. This is marked with FIXMEs and will be removed prior to merge with main.
> Scaffolding actions

- client/allocrunner/consul_hook.go
- nomad/job_endpoint_hook_implicit_identities.go
- nomad/job_endpoint_hook_implicit_identities_test.go
- nomad/job_endpoint_hooks_test.go
- nomad/structs/consul.go
- nomad/structs/structs.go
Consul tasks should only have 1 identity of the form `consul/{consul_cluster_name}`.
> WI: set the right identity name for Consul tasks

- api/jobs.go
- command/agent/job_endpoint.go
- command/agent/job_endpoint_test.go
- nomad/job_endpoint.go
- nomad/mock/job.go
- nomad/structs/actions.go
Adds a new endpoint: /job/:id/actions
It parses through a job's taskgroups' tasks, and extracts their actions up to a single flat array with the name of task and taskGroup included as fields.
```
$ nomad operator api '/v1/job/actions-demo/actions' | jq
[
{
"Args": [
"parrot.live"
],
"Command": "/usr/bin/curl",
"Name": "party",
"TaskGroupName": "group",
"TaskName": "task"
},
{
"Args": [
"ipinfo.io"
],
"Command": "/usr/bin/curl",
"Name": "ipinfo",
"TaskGroupName": "group",
"TaskName": "task"
},
{
"Args": [
"parrot.live"
],
"Command": "/usr/bin/curl",
"Name": "party",
"TaskGroupName": "group",
"TaskName": "task2"
},
...
]
```
Resolves #18680
> New endpoint: job/:id/actions

- ui/app/models/action.js
- ui/app/models/job.js
- ui/app/models/task.js
- ui/tests/unit/models/job-test.js
Introduces Actions as a fragment (non-independently fetched, but still modelled) on Tasks, and provides a computed property at Job level to get them and aggregate them.
This is a behind-the-scenes step to be able to list actions in the UI at Job and Task level.
Resolves #18726
> [ui] Actions aggregated at job model level

- nomad/encrypter.go
- nomad/encrypter_test.go
- nomad/plan_apply.go
- nomad/plan_apply_test.go
- nomad/service_registration_endpoint_test.go
This theoretically has no practical effect here, since 0e22fc1a0b removed `identityHook.Update()` from `main`, but this will line up with a separate PR targeting `1.6.x` with backports back to `1.4.x` to fix #16846.
Here this just keeps the `*Allocation` on the server aligned with what's used in the actual running task.
> Only generate default workload identity once per alloc task

- client/allocrunner/alloc_runner.go
- client/allocrunner/taskrunner/envoy_version_hook.go
- client/allocrunner/taskrunner/envoy_version_hook_test.go
- client/allocrunner/taskrunner/task_runner.go
- client/allocrunner/taskrunner/task_runner_hooks.go
- client/client.go
- client/client_test.go
- client/config/arconfig.go
- client/consul/consul.go
- client/serviceregistration/service_registration.go
- client/serviceregistration/wrapper/wrapper.go
- command/agent/agent.go
- command/agent/consul/catalog_testing.go
- command/agent/consul/connect_proxies.go
- command/agent/consul/service_client.go
- command/agent/consul/service_client_test.go
- nomad/consul.go
- nomad/consul_test.go
- nomad/job_endpoint.go
- nomad/server.go
- nomad/structs/connect.go
- nomad/testing.go
When agents start, they create a shared Consul client that is then wrapped as various interfaces for testability, and used in constructing the Nomad client and server. The interfaces that support workload services (rather than the Nomad agent itself) need to support multiple Consul clusters for Nomad Enterprise. Update these interfaces to be factory functions that return the Consul client for a given cluster name. Update the `ServiceClient` to split workload updates between clusters by creating a wrapper around all the clients that delegates to the cluster-specific `ServiceClient`.
> consul: add multi-cluster support to client constructors

- client/allocrunner/taskrunner/identity_hook.go
- client/allocrunner/taskrunner/identity_hook_test.go
- nomad/encrypter.go
- nomad/encrypter_test.go
- nomad/plan_apply.go
- nomad/plan_apply_test.go
- nomad/service_registration_endpoint_test.go
Fixes #16846 -- This is the `1.6.x` edition of #18776
> Only generate default workload identity once per alloc task - 1.6.x

- client/allocrunner/taskrunner/identity_hook.go
- client/allocrunner/taskrunner/identity_hook_test.go
- nomad/encrypter.go
- nomad/encrypter_test.go
- nomad/plan_apply.go
- nomad/plan_apply_test.go
- nomad/service_registration_endpoint_test.go
Fixes #16846 -- This is the `1.5.x` edition of #18776
> Only generate default workload identity once per alloc task - 1.5.x

- client/allocrunner/taskrunner/identity_hook.go
- nomad/encrypter.go
- nomad/encrypter_test.go
- nomad/plan_apply.go
- nomad/plan_apply_test.go
- nomad/service_registration_endpoint_test.go
Fixes #16846 -- This is the `1.4.x` edition of #18776
> Only generate default workload identity once per alloc task - 1.4.x

- nomad/heartbeat.go
- nomad/plan_apply.go
- nomad/rpc.go
These structs embedding Server, then Server _also embedding them_, confused my IDE, isn't necessary, and just feels wrong!
This is all I could find with
```
$ find -name '*.go' | xargs grep -P '^\s+\*Server$' -n
./heartbeat.go:38:      *Server
./rpc.go:47:    *Server
./plan_apply.go:25:     *Server
```
Server still embeds them, which isn't my favorite, but this makes my IDE happy, and Server's `*rpcHandler` has many tendrils, so maybe that can be a side quest for another day.
> Do not embed *Server

- ui/server/proxies/api.js
`ember-cli` includes a handler for websocket upgrade requests to start proxying requests. Handling the same upgrade event by also proxying in `api.js` causes some kind of conflict where the connection is closed unexpectedly.
The only change necessary on upgrade is to overwrite the Origin header so Nomad accepts the connection.
> ui: fix websocket connections on dev proxy

- client/allocrunner/taskrunner/task_runner_test.go
- client/allocrunner/taskrunner/template/template.go
- client/allocrunner/taskrunner/template/template_test.go
- client/allocrunner/taskrunner/template_hook.go
- client/config/config_ce.go
- nomad/config.go
- nomad/job_endpoint_hook_implicit_identities.go
- nomad/job_endpoint_hook_implicit_identities_test.go
- nomad/job_endpoint_hooks.go
- nomad/job_endpoint_hooks_test.go
In Nomad Enterprise, a task may connect to a non-default Vault cluster, requiring `consul-template` to be configured with a specific client `vault` block.
Tests require an ENT feature, so they will be done in a separate PR on the ENT repo.
> vault: add multi-cluster support on templates

- .changelog/18795.txt
- client/agent_endpoint.go
- client/structs/structs.go
- command/agent/agent_endpoint.go
- command/agent/agent_endpoint_test.go
- command/agent_monitor.go
- command/agent_monitor_test.go
- command/operator_debug.go
- nomad/client_agent_endpoint.go
- website/content/api-docs/agent.mdx
- website/content/docs/commands/monitor.mdx
- website/content/docs/commands/operator/debug.mdx
This change allows the use of the `log-include-location` logger options when using the agent monitor API and CLI. This defaults to false.
The PR also makes use of this change within the `operator debug` command, enabling this by default. Debug bundles are captured when as much information as needed should be gathered from a Nomad cluster. Therefore, including this information by default makes sense for both Nomad operators and the extended Nomad engineering team.
> monitor: add log include location option on monitor CLI and API

- command/ui.go
- go.mod
- go.sum
The cap library is used by the login command and the functionality that it provides to the CLI looks the same. Therefore swapping the login command out means we can reduce our dependency imports and use a single library.
> cli: use single dep func for opening URLs.

- lib/lang/maps.go
- lib/lang/maps_test.go
In some cases it is helpful to iterate a map in the sorted order of
the map's keyset - particularly in implementations of some function for
which the tests cannot be deterministic without order.
It's a little odd that the only use for this is in `ent` at first, but eh.
> lang: add a helper for iterating a map in order

- api/allocations.go
- api/allocations_exec.go
- api/jobs.go
- command/action.go
- command/alloc_exec.go
- command/alloc_fs.go
- command/alloc_logs.go
- command/commands.go
Adds the `nomad action` CLI command. Can be used to run a task action either by passing an allocation ID + job, or job + group + task:
```
nomad action \
-group=group \
-task=task \
-job=actions-demo \
weather
```
```
nomad action \
-allocation=3a5a5361 \
-job=actions-demo \
weather
```
As a side-effect, also adds an optional `tasakGroupName` param to `getRandomJobAlloc`, in order to only select allocations that have the specified action name.
> Action CLI command

- .changelog/18794.txt
- api/allocations_exec.go
- api/jobs.go
- api/tasks.go
- client/alloc_endpoint.go
- client/structs/structs.go
- command/action.go
- command/agent/alloc_endpoint.go
- command/agent/job_endpoint.go
- command/agent/job_endpoint_test.go
- command/agent/testingutils_test.go
- command/alloc_fs.go
- command/alloc_logs.go
- command/commands.go
- jobspec/parse_task.go
- nomad/job_endpoint.go
- nomad/mock/job.go
- nomad/structs/actions.go
- nomad/structs/diff.go
- nomad/structs/diff_test.go
- nomad/structs/funcs.go
- nomad/structs/structs.go
- ui/app/models/action.js
- ui/app/models/job.js
- ui/app/models/task.js
- ui/app/services/sockets.js
- ui/config/environment.js
- ui/tests/unit/models/job-test.js
Introduces the concept of Actions to Nomad: operator-defined commands and workflows that Nomad users can run on an allocation without having to sweat the details.
These take a similar form to task config blocks and live at task level in the jobspec. To demonstrate:
```
job "actions-demo" {
type = "system"
group "group" {
task "task" {
driver = "raw_exec"
config {
command = "node"
args    = ["-e",
<<EOT
console.log('Howdy!');
// sleep every 3 seconds
setInterval((a) => {
console.log('Howdy after 3 seconds');
}, 3000);
EOT
]
}
action "weather" {
command = "/usr/bin/curl"
args = ["-s", "wttr.in/Toronto?format=3"]
}
action "hello" {
command = "say"
args = ["howdy"]
}
action "get job info" {
command = "/bin/sh"
args    = ["-c",
<<EOT
nomad job status ${NOMAD_JOB_NAME}
EOT
]
}
action "get alloc …
```
> Nomad Actions

- client/lib/numalib/topology.go
- nomad/job_endpoint_hooks.go
- nomad/job_endpoint_hooks_test.go
- nomad/structs/job.go
- nomad/structs/job_test.go
- nomad/structs/testing.go
- scheduler/numa_ce.go
- scheduler/rank.go
- scheduler/rank_test.go
Some additional changes were made in the [ENT PR](https://github.com/hashicorp/nomad-enterprise/pull/1292) to the common code in
support of numa scheduling; this PR copies those changes back to CE.
> core: port common code changes from ENT for numa scheduling

- .semgrep/rpc_endpoint.yml
- command/agent/agent.go
- command/agent/command.go
- command/agent/command_test.go
- command/agent/config.go
- command/agent/config_test.go
- command/agent/http.go
- command/agent/keyring_endpoint.go
- command/agent/keyring_endpoint_test.go
- nomad/config.go
- nomad/encrypter.go
- nomad/encrypter_test.go
- nomad/keyring_endpoint.go
- nomad/keyring_endpoint_test.go
- nomad/server.go
- nomad/structs/keyring.go
- nomad/structs/keyring_test.go
- website/content/docs/configuration/server.mdx
Added the [OIDC Discovery](https://openid.net/specs/openid-connect-discovery-1_0.html) `/.well-known/openid-configuration` endpoint to Nomad, but it is only enabled if the `server.oidc_issuer` parameter is set. Documented the parameter, but without a tutorial trying to actually _use_ this will be very hard.
I intentionally did *not* use https://github.com/hashicorp/cap for the OIDC configuration struct because it's built to be a *compliant* OIDC provider. Nomad is *not* trying to be compliant initially because compliance to the spec does not guarantee it will actually satisfy the requirements of third parties. I want to avoid the problem where in an attempt to be standards compliant we ship configuration parameters that lock us in to a certain behavior that we end up regretting. I want to …
> OpenID Configuration Discovery Endpoint (just the endpoint)

- .changelog/18836.txt
- command/service_info.go
- command/service_list.go
The `nomad service info` command doesn't support using a wildcard namespace with a prefix match, the way that we do for many other commands. Update the command to do a prefix match list query for the services before making the get query.
Fixes: #18831
> cli: add prefix ID and wildcard namespace support for `service info`

- go.mod
- go.sum
- tools/go.mod
- tools/go.sum
fixes a rather critical bug in .Equals implementation
> deps: bump go-set/v2 to alpha.3

- .changelog/18835.txt
- client/hoststats/host.go
- client/hoststats/host_test.go
The iowait metric obtained from `/proc/stat` can under some circumstances decrease. The relevant condition is when an interrupt arrives on a different core than the one that gets woken up for the IO, and a particular counter in the kernel for that core gets decremented. This is documented in the man page for the `proc(5)` pseudo-filesystem, and considered an unfortunate behavior that can't be changed for the sake of ABI compatibility.
In Nomad, we get the current "busy" time (everything except for idle) and compare it to the previous busy time to get the counter increment. If the iowait counter decreases and the idle counter increases more than the increase in the total busy time, we can get a negative total. This previously caused a panic in our metrics collection (see #15861) but that …
> metrics: prevent negative counter from iowait decrease

- .changelog/18835.txt
- client/stats/host.go
- client/stats/host_test.go
The iowait metric obtained from `/proc/stat` can under some circumstances decrease. The relevant condition is when an interrupt arrives on a different core than the one that gets woken up for the IO, and a particular counter in the kernel for that core gets interrupted. This is documented in the man page for the `proc(5)` pseudo-filesystem, and considered an unfortunate behavior that can't be changed for the sake of ABI compatibility.
In Nomad, we get the current "busy" time (everything except for idle) and compare it to the previous busy time to get the counter incremeent. If the iowait counter decreases and the idle counter increases more than the increase in the total busy time, we can get a negative total. This previously caused a panic in our metrics collection (see #15861) but that …
> metrics: prevent negative counter from iowait decrease (backport 1.6.x)

- .changelog/18843.txt
I goofed the name the first time around, "power" should have been
"performance" which is consistent with both Apple and Intel branding.
> cl: note breaking change of numcores attribute on apple systems

- .changelog/18838.txt
- nomad/blocked_evals.go
- nomad/blocked_evals_test.go
Fixes #17278
When an eval is blocked due to e.g. cpu exhausted on nodes, but there happens to also be a quota on the job's namespace, the eval would not get auto-unblocked when the node cpu got freed up.
This change ensures, when considering quota during BlockedEvals.unblock(), that the block was due to quota in the first place, so unblocking does not get skipped due to the mere existence of a quota on the namespace.
> scheduler: appropriately unblock evals with quotas

- website/content/docs/job-specification/hcl2/functions/crypto/rsadecrypt.mdx
- website/data/docs-nav-data.json
`rsadecrypt` uses `PKCS #1 v1.5` padding which has multiple known weaknesses. While it is possible to use safely in Nomad, we should not encourage our users to use bad cryptographic primitives.
If users want to decrypt secrets in jobspecs we should choose a cryptographic primitive designed for that purpose. `rsadecrypt` was inherited from Terraform which only implemented it to support decrypting Window's passwords on AWS EC2 instances:
https://github.com/hashicorp/terraform/pull/16647
This is not something that should ever be done in a jobspec, therefore there's no reason for Nomad to support this HCL2 function.
Preview to save you a few clicks:
> docs: deprecate rsadecrypt

- command/agent/config_parse_test.go
- command/agent/testdata/basic.hcl
- command/agent/testdata/basic.json
- e2e/consulcompat/run_ce_test.go
- e2e/vaultcompat/cluster_setup_test.go
- nomad/structs/consul.go
- website/content/docs/configuration/consul.mdx
- website/content/docs/integrations/consul-integration.mdx
It should be called `nomad-services` instead of `nomad-workloads`.
> consul WI: rename default auth method for services

- .semgrep/imports.yml
- go.mod
- nomad/structs/structs.go
I think go-set/v1 got added back in the merging of a branch; add semgrep rules to keep it out.
> deps: purge and prohibit use of go-set/v1

- website/content/docs/integrations/consul-integration.mdx
- website/content/docs/integrations/vault-integration.mdx
- website/content/docs/job-specification/vault.mdx
Documentation updates to support the new Vault integration with Nomad Workload Identity. Included:
* Added a large section to the Vault integration docs to explain how to set up auth methods, roles, and policies (by hand, assuming we don't ship a `nomad setup-vault` tool for now), and how to safely migrate from the existing workflow to the new one.
* Shuffled around some of the existing text so that the legacy authentication method text is in its own section.
* Added a compatibility matrix to the Vault integration page.
* Added deprecation notice about `policies` being removed and updated the examples on the jobspec page to match.
Ref: https://github.com/hashicorp/nomad/issues/15617
Preview links:
* https://nomad-git-docs-vault-workload-identity-hashicorp.vercel.app/nomad/docs/integrations …
> docs: Vault Workload Identity integration

- command/agent/command.go
- command/job_revert.go
- command/job_run.go
Submitting a Consul or Vault token with a job is deprecated in Nomad 1.7 and intended for removal in Nomad 1.9. Add a deprecation warning to the CLI when the user passes in the appropriate flag or environment variable.
Nomad agents will no longer need a Vault token when configured with workload identity, and we'll ignore Vault tokens in the agent config after Nomad 1.9. Log a warning at agent startup.
Ref: https://github.com/hashicorp/nomad/issues/15617
Ref: https://github.com/hashicorp/nomad/issues/15618
---
Resulting log line in the agent:
> 2023-10-25T10:15:27.664-0400 [WARN]  agent: Setting a Vault token in the agent configuration is deprecated and will be removed in Nomad 1.9. Migrate your Vault configuration to use workload identity.: cluster=default
Resulting output from `nomad job …
> add deprecation warning for Vault/Consul token usage

- nomad/job_endpoint_hook_implicit_identities_test.go
- nomad/job_endpoint_hooks.go
- nomad/job_endpoint_hooks_test.go
Since Nomad servers only start a Vault client for the default cluster, tasks using non-default clusters must provide an identity to be used for token derivation, either in the task itself or in the agent configuration.
> vault: validate tasks using non-default clusters

- website/content/docs/job-specification/numa.mdx
- website/content/docs/job-specification/resources.mdx
- website/data/docs-nav-data.json
Separate from a more comprehensive "CPU Resources" concepts docs we spoke of
> docs: add job-specification docs for numa

- website/content/plugins/drivers/community/firecracker-task-driver.mdx
The location of tc-redirect-tap has been changed and the docs are now out of date.
This PR points the link in the Firecracker task driver to the correct repository.
The new location is [here](https://github.com/awslabs/tc-redirect-tap) (https://github.com/awslabs/tc-redirect-tap)
> docs: update link to tc-redirect-tap

- nomad/structs/structs.go
- nomad/worker.go
- scheduler/generic_sched_test.go
- scheduler/reconcile.go
- scheduler/reconcile_test.go
- scheduler/reconcile_util.go
- scheduler/reconcile_util_test.go
This PR fixes  [Max_client_disconnect ignores no-reschedule policy](https://github.com/hashicorp/nomad/issues/16515)
The bug had 2 root causes:
- The code was written under the assumption that disconnecting allocs should always be rescheduled:
https://github.com/hashicorp/nomad/blob/cecd9b04729e63839428cfa67fdc983ed2182481/scheduler/reconcile.go#L461
Any disconnecting allocation that should not be rescheduled now, was ignored for the rest of the reconcile process and would always end up on a new placement, because it was not taken into consideration for the deployment final count.  
- The logic to define if an allocation should be reschedule didn't take into account disconnecting allocations, they were 
never set to be explicitly replaced, because according to the …
> fix: handling non reschedule disconnecting and reconnecting allocs

- .changelog/18873.txt
- nomad/structs/structs.go
- scheduler/generic_sched.go
- scheduler/generic_sched_test.go
- scheduler/reconcile.go
- scheduler/reconcile_util.go
- scheduler/reconcile_util_test.go
This change fixes a bug within the generic scheduler which meant duplicate alloc indexes (names) could be submitted to the plan applier and written to state. The bug originates from the placements calculation notion that names of allocations being replaced are blindly copied to their replacement. This is not correct in all cases, particularly when dealing with canaries.
The fix updates the alloc name index tracker to include minor duplicate tracking. This can be used when computing placements to ensure duplicate are found, and a new name picked before the plan is submitted. The name index tracking is now passed from the reconciler to the generic scheduler via the results, so this does not have to be regenerated, or another data structure used.
closes #10727 
The new test …
> scheduler: ensure dup alloc names are fixed before plan submit.

- e2e/consulcompat/input/connect.nomad.hcl
- e2e/consulcompat/run_ce_test.go
- e2e/consulcompat/shared_run_test.go
- e2e/consulcompat/shared_setup_test.go
- testutil/server.go
The `BindName` for JWT authentication should always bind to the `nomad_service` field in the JWT and not include the namespace, as the `nomad_service` is what's actually registered in Consul. 
* Fix the binding rule for the `consulcompat` test 
* Add a reachability assertion so that we don't miss regressions.
* Ensure we have a clean shutdown so that we don't leak state (containers and iptables) between tests.
---
A note on debugging the original configuration problem. The allocations start up just fine and are healthy, so Nomad wasn't able to give much help here. To debug, I compared the results of `consul catalog services` with the results of `consul acl token list`, and looked for the tokens that resulted from the login. The `Service Identities` block in the token listing was the clue …
> e2e: fix bind name to allow Connect reachability

- website/content/docs/job-specification/template.mdx
Prior to `consul-template` v0.22.0, automatic PKI renewal wouldn't work properly based on the expiration of the cert. More recent versions of `consul-template` can use the expiry to refresh the cert, so it's no longer necessary (and in fact generates extra load on Vault) to set `generate_lease`. Remove this recommendation from the docs.
Fixes: #18893
> docs: remove stale note about `generate_lease` from template docs

- command/job_plan.go
Apply the same deprecation notice from #18863 to the `nomad job plan` command.
> cli: deprecate -vault-token flag

- client/allocrunner/taskrunner/task_runner_hooks.go
- client/allocrunner/taskrunner/task_runner_linux_test.go
- client/allocrunner/taskrunner/task_runner_test.go
- client/allocrunner/taskrunner/vault_hook.go
- client/allocrunner/taskrunner/vault_hook_test.go
- client/config/config.go
- client/vaultclient/vaultclient_testing.go
Fallback to the ACL role defined in the client's `create_from_role` configuration when using the JWT flow and the task does not specify a role to use.
> vault: derive token using `create_from_role`

- contributing/CHANGELOG.md
Adds missing code fence to the Improvements example in the CHANGELOG.md documentation.  Fixes issue where `release-note:improvement` did not appear in the rendered Markdown.
> docs: Add missing code fence to Improvements example

- client/allocrunner/identity_hook.go
- client/allocrunner/identity_hook_test.go
- client/widmgr/widmgr.go
The allocrunner's `identity_hook` implements the interface for TaskStop, but this interface is only ever called for task-level hooks. This results in a leaked goroutine that tries to periodically renew WIs until the client shuts down gracefully.
Add an implementation for the allocrunner's `PreKill` and `Destroy` hooks, so that whenever an allocation is stopped or garbage collected we stop renewing its Workload Identities. This also requires making the `Shutdown` method of `WIDMgr` safe to call multiple times.
> `identity_hook`: implement PreKill hook, not TaskStop hook

- website/content/docs/upgrade/upgrade-specific.mdx
The Consul and Vault integrations work shipping in Nomad 1.7 will deprecated the existing token-based workflows. These will be removed in Nomad 1.9, so add a note describing this to the upgrade guide.
Preview link: https://nomad-f2mh6uwj4-hashicorp.vercel.app/nomad/docs/upgrade/upgrade-specific#nomad-1-7-0
> docs: upgrade guide for integrations deprecation warnings

- nomad/job_endpoint_hook_implicit_identities.go
- nomad/job_endpoint_hooks.go
- nomad/leader.go
- version/version.go
Job submitters cannot set multiple identities prior to Nomad 1.7, and cluster administrators should not set the identity configurations for their `consul` and `vault` configuration blocks until all servers have been upgraded. Validate these cases during job submission so as to prevent state store corruption when jobs are submitting in the middle of a cluster upgrade.
> identity: version check multiple and implicit identities

- api/internal/testutil/server.go
- client/vaultclient/vaultclient_test.go
- client/widmgr/mock.go
- command/agent/http_test.go
- command/agent/testagent.go
- command/recommendation_dismiss_test.go
- command/var_list_test.go
- e2e/vaultcompat/cluster_setup_test.go
- nomad/auth/auth_test.go
- nomad/client_agent_endpoint_test.go
- nomad/core_sched_test.go
- nomad/encrypter.go
- nomad/encrypter_test.go
- nomad/keyring_endpoint_test.go
- nomad/leader.go
- nomad/locks_test.go
- nomad/node_pool_endpoint_test.go
- nomad/operator_endpoint_test.go
- nomad/service_registration_endpoint_test.go
- nomad/stats_fetcher_test.go
- nomad/structs/keyring.go
- nomad/variables_endpoint_test.go
- testutil/server.go
- testutil/wait.go
OIDC mandates the support of the RS256 signing algorithm so in order to maximize workload identity's usefulness this change switches from using the EdDSA signing algorithm to RS256.
Old keys will continue to use EdDSA but new keys will use RS256. The EdDSA generation code was left in place because it's fast and cheap and I'm not going to lie I hope we get to use it again.
**Test Updates**
Most of our Variables and Keyring tests had a subtle assumption in them that the keyring would be initialized by the time the test server had elected a leader. ed25519 key generation is so fast that the fact that it was happening asynchronously with server startup didn't seem to cause problems. Sadly rsa key generation is so slow that basically all of these tests failed.
I added a new …
> identity: default to RS256 for new workload ids

- .changelog/18035.txt
- .changelog/18123.txt
- .changelog/18262.txt
- .changelog/18691.txt
- .changelog/18882.txt
- website/content/api-docs/operator/keyring.mdx
Changelog entries and bare minimum docs for workload identity changes in 1.7.
1.7.0 Changelog would look like:
---
FEATURES:
* **Multiple Vault and Consul Clusters:** Nomad Enterprise can now use multiple Vault or Consul clusters. Each task or service can be registered with a different Consul cluster and each task can obtain secrets from a different Vault cluster. [[GH-5311](https://github.com/hashicorp/nomad/issues/5311)]
* **NUMA aware scheduling**: Nomad Enterprise now supports optimized scheduling on NUMA hardware [[GH-18681](https://github.com/hashicorp/nomad/issues/18681)]
* **Workload Identity IDP:** Nomad's workload identities may now be used with third parties that support JWT or OIDC IDPs such as the AWS IAM OIDC Provider. …
> docs: changelog & basic docs for 1.7 WI changes

- website/content/docs/integrations/vault-integration.mdx
Vault tokens requested for WI are "periodic" Vault tokens (ones that get periodically renewed). The field we should be setting for the renewal window is `token_period`.
Ref: https://developer.hashicorp.com/vault/docs/concepts/tokens#periodic-tokens
> docs: fix `token_period` in example Vault role for WI

- ui/.eslintrc.js
- ui/app/components/job-page/parts/title.js
- ui/app/styles/core/title.scss
- ui/app/templates/components/exec/open-button.hbs
- ui/app/templates/components/job-page/parts/title.hbs
- ui/app/templates/components/two-step-button.hbs
- ui/tests/acceptance/allocation-detail-test.js
- ui/tests/integration/components/two-step-button-test.js
- ui/tests/pages/components/two-step-button.js
For purposes of changing the Exec and Stop buttons shown here:
we now have all two-step buttons using Helios-style buttons instead of our previous style.
> [ui] Helios two-step button and uniform title bar for Actions

- api/allocations_exec.go
- api/jobs.go
- client/alloc_endpoint.go
- client/structs/structs.go
- command/action.go
- command/agent/job_endpoint.go
- jobspec/parse_task.go
- nomad/client_alloc_endpoint.go
- nomad/client_alloc_endpoint_test.go
- nomad/structs/actions.go
- nomad/structs/funcs.go
- nomad/structs/structs.go
Some fixes and minor changes from a late review of https://github.com/hashicorp/nomad/commit/8902afe651fbd1d9c1b740b577a30216bd7eab66.
Bugs fixed:
* Validate `action` blocks have unique names.
* Validate `action` blocks have a command.
* Validate requested job ID exists.
* Validate requested allocation belongs to the requested job.
* Percent escape job ID in request path.
* Fix block name in HCLv1 parsing.
* No-op command args autocomplete since we can't predict action name.
Known bug I found during tests:
* Command doesn't work with jobs that end or start with `/` or that have multiple `/` in a row, but this is a bug in Go that was fixed recently    
https://github.com/golang/go/issues/21955
Minor changes:
* Rename `-allocation` flag to just `-alloc` to match other commands.
* …
> actions: minor bug fixes and improvements

- client/allocrunner/taskrunner/template_hook.go
- client/allocrunner/taskrunner/vault_hook.go
Allocations that were created before Nomad 1.7 will not have the `cluster` field set for their Vault blocks. While this can be corrected server-side, that doesn't help allocations already on clients.
> vault: fix lookups of default cluster across upgrades

- client/lib/numalib/detect_darwin.go
No CL/backport; this was a bug introduced in the NUMA work for 1.7
Closes #18212
> client: fix cpu core/freq calculation on intel macs

- e2e/vaultcompat/cluster_setup_test.go
- e2e/vaultcompat/vaultcompat_test.go
- nomad/job_endpoint_hooks.go
- nomad/job_endpoint_hooks_test.go
Small fixes on Vault JWT auth:
* Remove `token_ttl` from `vaultcompat` since Nomad uses periodic tokens.
* Set minimum version required for JWT auth to 1.11.0+ because that's when `user_claim_json_pointer` was added.
> Vault small fixes

- client/allocrunner/consul_hook.go
- client/allocrunner/group_service_hook.go
- client/allocrunner/taskrunner/service_hook.go
Allocations that were created before Nomad 1.7 will not have the cluster field set for their Consul blocks. While this can be corrected server-side, that doesn't help allocations already on clients.
> consul: fix lookups of default cluster across upgrades

- .changelog/18943.txt
- api/tasks.go
- client/allocrunner/taskrunner/identity_hook.go
- client/allocrunner/taskrunner/identity_hook_test.go
- client/allocrunner/taskrunner/vault_hook.go
- command/agent/job_endpoint.go
- command/agent/job_endpoint_test.go
- contributing/checklist-jobspec.md
- nomad/structs/workload_id.go
- nomad/structs/workload_id_test.go
- website/content/docs/job-specification/identity.mdx
This implements the jobspec and client internals for `identity.change_mode`: allowing users to signal or restart tasks when their identity tokens get rotated.
As part of this I also blocked `taskrunner/identityHook.Prestart(...)` from completing until tokens are initially written (_or_ a timeout/context-cancellation is hit). I think before we technically had a race between `taskrunner/identityHook.Prestart(...)` writing initial tokens and the things that rely on those initial tokens starting up. Not sure if it would be realistically hit, but it seemed like a good idea to copy our `template` implementation of waiting for a first run.
Let me know if you think the 1 minute timeout should be changed or removed. `template` blocks indefinitely, but it has a lot more concerns than `identity`. I …
> identity: Implement `change_mode`

- client/allocrunner/consul_hook.go
- client/allocrunner/group_service_hook.go
- client/allocrunner/taskrunner/service_hook.go
- client/allocrunner/taskrunner/sids_hook.go
- client/allocrunner/taskrunner/task_runner_hooks.go
- client/allocrunner/taskrunner/template_hook.go
- client/allocrunner/taskrunner/template_hook_test.go
- client/allocrunner/taskrunner/vault_hook.go
- nomad/structs/vault.go
When looking up the Consul or Vault cluster from a client hook, we should always use an accessor function rather than trying to lookup the `Cluster` field, which may be empty for jobs registered before Nomad 1.7.
Follow-up to https://github.com/hashicorp/nomad/pull/18945 and https://github.com/hashicorp/nomad/pull/18940
> consul/vault: use accessor method to get cluster name in client

- ui/app/components/allocation-status-bar.js
Before this commit, it would bring you to the list of allocations
filtered by status=starting. This status does not exist in the Status
drop-down on the Allocations section of a job in the UI.
> Fix the "Starting" allocations link

- nomad/structs/generate.sh
Our codec code generation doesn't honor `json:"..."` tags which breaks the OIDC Discovery endpoint.
This adds the relevant struct to the code generators ignore list (just like we have done with IdentityClaims).
> identity: don't generate codec for oidc config

- .changelog/18972.txt
- nomad/acl_endpoint.go
- nomad/acl_endpoint_test.go
When a user performs a client API call, the Nomad client will perform an RPC which looks up the ACL policies which the callers ACL token is assigned. If the ACL token includes dangling (deleted) policies, the call would previously fail with a permission denied error.
This change ensures this error is not returned and that the lookup will succeed in the event of dangling policies.
closes #18619
> acl/client: fix incorrect denied error on calls with dangling policies.

- nomad/structs/generate.sh
Our codec code generation doesn't honor `json:"..."` tags which, if we were to ever implement `json.Marshaller` for the `KeyEncryptionKeyWrapper` struct, would break the on-disk format of all the existing KEKs.
As a precaution, add this struct to the code generator's ignore list (just like we have done with `IdentityClaims`).
> ignore KEK wrapper struct for codegen

- .changelog/18961.txt
- command/acl_bootstrap.go
See https://developer.hashicorp.com/nomad/docs/commands/acl/bootstrap
> cli: update acl bootstrap help to match docs

- integrations/grafana_dashboards/README.md
When starting to use Grafana for my nomad cluster, I just noted this link was broken.
Please find a suggestion to simply fix it.
> docs: fix Grafana doc breaking link

- .changelog/18996.txt
- command/operator_client_state.go
- command/operator_client_state_test.go
The `operator client-state` command is mostly used for developer debugging of the Nomad client state, but it hasn't been updated with several recent additions. Add allocation identities, network status, and dynamic volumes to the objects it outputs.
Also, fix a bug where reading the state for an allocation without task states will crash the CLI. This can happen if the Nomad client stops after an alloc is persisted to disk but before the task actually starts.
Extracted from https://github.com/hashicorp/nomad/pull/16638
> cli: extend coverage of `operator client-state` command

- command/agent/agent.go
- nomad/config.go
- nomad/job_endpoint.go
- nomad/job_endpoint_ce_test.go
- nomad/job_endpoint_hook_implicit_identities.go
- nomad/job_endpoint_hook_implicit_identities_test.go
- nomad/job_endpoint_hook_vault.go
- nomad/job_endpoint_hooks_test.go
- nomad/job_endpoint_test.go
- nomad/node_endpoint_test.go
- nomad/server.go
- nomad/server_test.go
- nomad/testing.go
Remove the now-unused original configuration blocks for Consul and Vault from the server. When the server needs to refer to a Consul or Vault block it will always be for a specific cluster for the task/service. Add a helper for accessing the default clusters (for the servers' own use).
This is one of three changesets for this work. The remainder will implement the same changes in the `client` package and on the `command/agent` package.
As part of this work I discovered two bugs:
* The job submission hook for Vault only checks the enabled flag on the default cluster, rather than the clusters that are used by the job being submitted. This will return an error on job registration saying that Vault is disabled. Fix that to check only the cluster(s) used by the job.
* The …
> config: remove old Vault/Consul config blocks from server

- website/content/docs/drivers/docker.mdx
Fixes broken `--cap_add` and `--cap_drop` links in the [Docker Driver](https://developer.hashicorp.com/nomad/docs/drivers/docker) documentation.
> docs: fix broken links in docker.mdx

- command/job_plan.go
- command/job_revert.go
- command/job_run.go
- nomad/job_endpoint_hook_consul_ce.go
- nomad/job_endpoint_hook_vault.go
Submitting a Consul or Vault token with a job is deprecated in Nomad 1.7 and
intended for removal in Nomad 1.9. We added a deprecation warning to the CLI
when the user passes in the appropriate flag or environment variable in
does not use Vault or Consul but happen to have the appropriate environment
variable in your environment. While this is generally a bad practice (because
the token is leaked to Nomad), it's also the existing practice for some users.
Move the warning to the job admission hook. This will allow us to warn only when
appropriate, and that will also help the migration process by producing warnings
only for the relevant jobs.
> Move deprecation warning to server

- e2e/artifact/artifact_test.go
- e2e/terraform/terraform.tfvars
- e2e/terraform/variables.tf
- e2e: disable windows client
- e2e: disable windows artifact test
Note: the metrics suite also has Windows tests but it's also broken for other reasons; I'll follow up with fixing up my refactoring of that suite in https://github.com/hashicorp/nomad/compare/main...e2e-refactor-metrics and disable windows in that too for now.
> e2e disable windows

- client/vaultclient/vaultclient.go
Previously, a Vault token could renewed either periodically via the renewal loop or immediately by calling `RenewToken()`.
But a race condition in the renewal loop could cause an attempt to renew an expired token. If both `updateCh` and `renewalCh` are active (such as when a task stops at the same time its token is waiting for renewal), the following `select` picks a `case` at random.
https://github.com/hashicorp/nomad/blob/78f0c6b2a910c25522ac88ff63343bb371d72bff/client/vaultclient/vaultclient.go#L557-L564
If `case <-renewalCh` is picked, the token is incorrectly re-added to the heap, causing unnecessary renewals of a token that is already expired.
https://github.com/hashicorp/nomad/blob/1604dba508b2ae8187b6b9405ce6d9b6ca8e8b4b/client/vaultclient/vaultclient.go#L505-L510
To prevent this …
> vault: always renew tokens using the renewal loop

- .changelog/18985.txt
- client/vaultclient/vaultclient.go
A series of errors may happen when a token is invalidated while the Vault client is waiting to renew it. The token may have been invalidated for several reasons, such as the alloc finished running and it's now terminal or the token may have been change directly on Vault out-of-band.
Most of the errors are caused by retries that will never succeed until Vault fully removes the token from its state.
This commit prevents the retries by making the error `invalid lease ID` a fatal error.
In earlier versions of Vault, this case was covered by the error `lease not found or lease is not renewable`, which is already considered to be a fatal error by Nomad:
https://github.com/hashicorp/vault/blob/2d0cde4ccc0323591d9414342cb15f5cb70271d7/vault/expiration.go#L636-L639
But …
> vault: avoid continual renewal of invalid token

- e2e/terraform/packer/ubuntu-jammy-amd64/setup.sh
pledge v0.3.0 has fixes for working with Nomad 1.7
https://github.com/shoenig/nomad-pledge-driver/releases/tag/v0.3.0
> e2e: update pledge driver to 0.3.0

- command/agent/agent.go
- command/agent/agent_endpoint.go
- command/agent/agent_endpoint_test.go
- command/agent/agent_test.go
- command/agent/command.go
- command/agent/config.go
- command/agent/config_parse.go
- command/agent/config_parse_test.go
- command/agent/config_test.go
- command/agent/testagent.go
- command/agent/testdata/extra-consul.json
- command/agent/testdata/extra-vault.json
- command/job_plan_test.go
- command/job_validate_test.go
- e2e/consulcompat/shared_download_test.go
- e2e/consulcompat/shared_setup_test.go
- e2e/vaultcompat/vaultcompat_test.go
- helper/funcs.go
- nomad/structs/config/consul.go
- nomad/structs/config/vault.go
- testutil/server.go
Remove the now-unused original configuration blocks for Consul and Vault from the agent configuration parsing. When the agent needs to refer to a Consul or Vault block it will always be for a specific cluster for the task/service (or the default cluster for the agent's own use).
This is third of three changesets for this work. It includes:
* A fix to the `Merge` methods where the `Name` field was not being correctly merged.
* Changing the map of Vault/Consul configs in the agent's `Config` to a slice. This doesn't change the resulting maps in the server/client `Config` because it's a lot easier to use them at the call site that way.
* Fixes to tests that were masking problems in parsing JSON format agent configuration.
Fixes: https://github.com/hashicorp/nomad/issues/18947
Ref: …
> config: remove old Vault/Consul config blocks from parser

- GNUmakefile
- ci/test-core.json
- command/agent/job_endpoint.go
- command/agent/job_endpoint_test.go
- jobspec/parse.go
- jobspec/parse_task.go
- jobspec/parse_test.go
- jobspec2/parse_test.go
- jobspec2/test-fixtures/identity-compat.nomad.hcl
- tools/missing/main.go
- tools/missing/main_test.go
Sorry for the grab bag of little fixes, fixing `WorkloadIdentity.TTL` handling just led to a few different distractions in no particular order:
* The reason this all began: Fix the bug I introduced in https://github.com/hashicorp/nomad/pull/18943/files#diff-56b3c82fcbc857f8fb93a903f1610f6e6859b3610a4eddf92bad9ea27fdc85ec by switching WorkloadIdentity handling in job registration to use a shared function that ignored the `TTL` field.
* Missing `jobspec2` testing in CI
* Incorrect `/...` handling in our `missing` tests tool that caused us to miss `jobspec2` missing from CI (thankfully it _only_ missed jobspec2)
* Couple small jobspec (hcl1) fixes hit once `jobspec2` tests were actually run
* Inconsistent ellipses use in GNUmakefile. Obviously critical to correct. :zany_face:
> Fix WorkloadIdentity.TTL handling, jobspec2 testing, and hcl1 vs 2 parsing

- command/asset/consul-wi-default-policy.hcl
- command/setup_consul.go
When creating the binding rule, `BindName` must match the pattern used for the role name, otherwise the task will not be able to login to Consul.
Also update the equality check for the binding rule to ensure this property is held even if the auth method already has existing binding rules attached.
> cli: fix `setup consul` binding rule config

- client/allocrunner/alloc_runner.go
- client/allocrunner/alloc_runner_hooks.go
- client/allocrunner/alloc_runner_test.go
- client/allocrunner/alloc_runner_unix_test.go
- client/allocrunner/taskrunner/task_runner.go
- client/allocrunner/taskrunner/task_runner_test.go
- client/allocrunner/testing.go
- client/client.go
- client/config/arconfig.go
- client/state/upgrade_int_test.go
- command/agent/consul/int_test.go
The allocrunner has a service registration handler that proxies various API calls to Consul. With multi-cluster support (for ENT), the service registration handler is what selects the correct Consul client. The name of this field in the allocrunner and taskrunner code base looks like it's referring to the actual Consul API client. This was actually the case before Nomad native service discovery was implemented, but now the name is misleading.
I ran into this while working on #19000.
> refactor: rename allocrunner's Consul service reg handler

- .github/workflows/test-ui.yml
Our percy and test-ui runs shouldn't need to be run on any non-ui-dir changes, since we fully mock our needed API endpoints etc. with mirage for our test runs.
This should save us some time and money on checks in the future.
> [ui] Only run test-ui, and percy, in the event that a push/pr touches the ui directory

- .changelog/19037.txt
- ui/app/utils/default_jobs/hello-world.js
- ui/app/utils/default_jobs/parameterized.js
- ui/app/utils/default_jobs/service-discovery.js
- ui/app/utils/default_jobs/variables.js
Swaps out the `//` for `#` comment prefixes in our job template strings (which eventually are expressed as HCL) for highlighting reasons, among others.
Old:
New:
> [ui] Nicer comment styles in example jobs

- e2e/terraform/packer/ubuntu-jammy-amd64.pkr.hcl
- e2e/terraform/packer/windows-2016-amd64.pkr.hcl
`t2` is ancient hardware; bump to the latest and greatest general compute type. builds are about twice as fast or so, though "Waiting for AMI to become ready..." unfortunately isn't any faster.
> e2e: bump packer build instances because faster

- client/allocrunner/taskrunner/task_runner_hooks.go
- client/allocrunner/taskrunner/task_runner_test.go
The task template hook uses the alloc resource to retrieve Consul tokens, so it must be passed from the allocation.
> client: pass alloc hook resources to template hook

- client/widmgr/widmgr.go
Identity change mode was implemented in #18943 and handles the update at the task level, so workload identity manager receives the update as expected.
> chore: remove comment about WI change mode

- e2e/terraform/.terraform.lock.hcl
Using the latest version of terraform, the lock file is not the same
as when it was generated. Seems like the http module is not needed?
versioned? present? anymore.
```
➜ terraform version
Terraform v1.6.3
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.10.0
+ provider registry.terraform.io/hashicorp/consul v2.15.1
+ provider registry.terraform.io/hashicorp/external v2.2.2
+ provider registry.terraform.io/hashicorp/hcp v0.26.0
+ provider registry.terraform.io/hashicorp/local v2.2.2
+ provider registry.terraform.io/hashicorp/null v3.1.1
+ provider registry.terraform.io/hashicorp/random v3.1.2
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/hashicorp/tls v3.3.0
+ provider registry.terraform.io/hashicorp/vault v3.4.1
```
> e2e: update terrform lock file for 1.6.3

- e2e/isolation/input/chroot_docker.nomad
- e2e/isolation/input/java.hcl
- e2e/isolation/input/java_host.hcl
- e2e/isolation/input/raw_exec.hcl
The memory limits on the java tasks in particular were probably too low; bump these to be more sensible.
> e2e: more cpu and memory for java tasks and some scripts

- e2e/consulcompat/input/connect.nomad.hcl
- e2e/consulcompat/input/consul-policy-for-nomad.hcl
- e2e/consulcompat/shared_run_test.go
The Consul compatibility test focuses on Connect, but it'd be a good idea to ensure we can successfully get template data out of Consul as well.
(`client` package test is failing because of https://github.com/hashicorp/nomad/pull/19056, will rebase once that's been merged)
> E2E: add template block to `consulcompat` test

- GNUmakefile
The version we have of `hc-install` doesn't allow installing Enterprise binaries. Upgrade so that this is available to the development team and to our E2E tests in the Enterprise repo.
> tools: bump version of `hc-install`

- ui/app/adapters/job.js
Small fix to let UI actions passing use job.name instead of job.id, since namespace is passed as an explicit param afterward
> [ui] Bugfix: expecting job.name and job.namespace passed as separate params, rather than job.id

- e2e/oversubscription/oversubscription_test.go
- e2e/v3/jobs3/jobs3.go
Just because an alloc is running does not mean nomad is ready to serve
task logs. In a test case where you immediatly read logs after starting
a task, it could be that nomad responds with "no logs found" when you
try to read logs, in which case you just need to wait longer. Do so in
the v3 TaskLogs helper function.
> e2ev3: wait for logs to become ready

- e2e/consulcompat/input/consul-policy-for-nomad-legacy.hcl
- e2e/consulcompat/input/consul-policy-for-nomad.hcl
- e2e/consulcompat/run_ce_test.go
- e2e/consulcompat/shared_download_test.go
- e2e/consulcompat/shared_run_test.go
- e2e/consulcompat/shared_setup_test.go
We want to run the Consul compatibility E2E test with Consul Enterprise binaries and use Consul namespaces. Refactor the `consulcompat` test so as to parameterize most of the test setup logic with the namespace, and add the appropriate build tag for the CE version of the test.
Ref: https://github.com/hashicorp/nomad-enterprise/pull/1305
> E2E: refactor `consulcompat` to allow for ENT tests

- website/content/docs/job-specification/restart.mdx
This PR introduces a new section to the restart block on the job specs that explicitly defines how to disable the restart of a task group on the job specs.
> docs: Add section for disable restart

- e2e/vaultcompat/run_ce_test.go
- e2e/vaultcompat/vaultcompat_test.go
We want to run the Vault compatibility E2E test with Vault Enterprise binaries and use Vault namespaces. Refactor the `vaultcompat` test so as to parameterize most of the test setup logic with the namespace, and add the appropriate build tag for the CE version of the test.
Ref: https://github.com/hashicorp/nomad-enterprise/pull/1311
> E2E: refactor `vaultcompat` to allow for ENT tests

- drivers/shared/executor/executor_universal_linux.go
The `qemu` driver uses our universal executor to run the QEMU command line tool. Because QEMU owns the resource isolation, we don't pass in the resource block that the universal executor uses to configure cgroups and core pinning. This resulted in a panic.
Fix the panic by returning early in the cgroup configuration in the universal executor. This fixes `qemu` but also any third-party drivers that might exist and are using our executor code without passing in the resource block.
In future work, we should ensure that the `resources` block is being translated into QEMU equivalents, so that we have support for things like NUMA-aware scheduling for that driver.
Fixes: https://github.com/hashicorp/nomad/issues/19078
Ref: https://github.com/hashicorp/nomad/issues/19090
> qemu: fix panic from missing resources block

- website/content/docs/drivers/docker.mdx
- website/content/docs/drivers/exec.mdx
- website/content/docs/drivers/java.mdx
Linux capabilities configurable by the task must be a subset of those configured in the plugin configuration. Clarify this implies that `"all"` is not permitted if the plugin is not also configured to allow all capabilities.
Fixes: https://github.com/hashicorp/nomad/issues/19059
> docs: clarify when "all" is not permitted for `cap_add`

- command/node_status.go
Display a message to indicate that there are no nodes registered when `node status` returns zero values.
> cli: add zero nodes message to `node status`

- .changelog/19051.txt
- ui/app/components/job-status/individual-allocation.hbs
- ui/app/components/job-status/individual-allocation.js
On hover, shows client info on the job status panel's allocs:
Resolves #19050
> [ui] Shows the client/node name alongside alloc short ID if the job is system/sysbatch

- .release/linux/package/usr/lib/systemd/system/nomad.service
Same issue as #10065:
```
Nov 16 06:45:52 nuc-01 systemd[1]: /lib/systemd/system/nomad.service:30: Unknown key name 'StartLimitIntervalSec' in section 'Service', ignoring.
Nov 16 09:24:11 nuc-01 systemd[1]: /lib/systemd/system/nomad.service:30: Unknown key name 'StartLimitIntervalSec' in section 'Service', ignoring.
```
which was fixed by @shoenig in #10068, but seems to have disappeared with the [reorganisation](https://github.com/hashicorp/nomad/commits/5a0a8f606ffe87fe8b8a09aa7e827498d1ed8a1a/.release/linux/package/etc/usr/lib/systemd/system/nomad.service?browsing_rename_history=true&new_path=.release/linux/package/usr/lib/systemd/system/nomad.service&original_branch=f95697abaf1a07b7445f2d2a10ff45c519c3866c) of releases.
All the params being moved belong in [Unit] instead of [Service]: …
> Move systemd unit file rate limits from [Service] to [Unit] block

- .changelog/19104.txt
- nomad/job_endpoint_hooks.go
- nomad/job_endpoint_hooks_test.go
- nomad/mock/job.go
The JWT authentication feature was added to Consul in 1.8.0. Bump the version constraint in the job endpoint hooks to match. This version is long out of support so it shouldn't have any impact on existing jobs.
> bump Consul constraint to 1.8.0

- e2e/terraform/terraform.tfvars
- e2e/terraform/variables.tf
I noticed that despite #19012, a Windows instance was still being provisioned during E2E runs.
Turns out that's because our E2E repo has its own tfvars file(s), which means that these values are set in at least 3 different places:
* `variables.tf` defaults
* `terraform.tfvars` in this repo
* `github.tfvars` in e2e repo
To reduce the likelihood of this causing more confusion in the future, this removes most variables from tfvars, leaving only those that are actually different depending on context.
> e2e: use tf variable defaults

- .changelog/19115.txt
- api/allocations.go
> Fix panic in Allocation.Stub() when Job is nil

- .changelog/19004.txt
- scheduler/feasible.go
- scheduler/feasible_test.go
- website/content/docs/job-specification/constraint.mdx
- website/content/docs/upgrade/upgrade-specific.mdx
Added test to verify original condition and that fix resolved it.
🔍 **Website Preview Links**
- [Upgrade Guide](https://nomad-2kksia0nn-hashicorp.vercel.app/nomad/docs/upgrade/upgrade-specific#nomad-1-7-0)
- [Constraint Page](https://nomad-2kksia0nn-hashicorp.vercel.app/nomad/docs/job-specification/constraint)
> [core] Honor job's namespace when checking `distinct_hosts` feasibility

- e2e/acl/acl_token_test.go
In Nomad 1.5 we started masking the specific error returned from the authentication method and returned the "permission denied" error instead. Update the E2E test that covers token expiration to ensure we're asserting the correct error here.
(Also updates all the uses of `testify` to `shoenig/test`)
Fixes: https://github.com/hashicorp/nomad/issues/16803
---
Run against a real E2E cluster:
```
$ go test -v -count=1 ./e2e/acl -run TestACL/TestACL_TokenExpiration
=== RUN   TestACL
=== RUN   TestACL/TestACL_TokenExpiration
--- PASS: TestACL (1.39s)
--- PASS: TestACL/TestACL_TokenExpiration (1.22s)
PASS
ok      github.com/hashicorp/nomad/e2e/acl      1.399s
```
> E2E: fix expected error message from token expiration test

- e2e/workload_id/nodemeta_test.go
In #18664 we change how null values worked with dynamic node metadata so that they were no longer returned if there wasn't also a static value for that key. The test assertion in E2E was not updated to match the new behavior.
Fixes: #19112
> E2E: fix assertion in dynamic node metadata test

- .changelog/19004.txt
- scheduler/feasible.go
- scheduler/feasible_test.go
- website/content/docs/job-specification/constraint.mdx
- website/content/docs/upgrade/upgrade-specific.mdx
[core] Honor job's namespace when checking `distinct_hosts` feasibility
Manual backport because of conflicts in upgrade-specific.mdx
> Backport #19004 to release/1.5.x

- .changelog/19004.txt
- scheduler/feasible.go
- scheduler/feasible_test.go
- website/content/docs/job-specification/constraint.mdx
- website/content/docs/upgrade/upgrade-specific.mdx
[core] Honor job's namespace when checking `distinct_hosts` feasibility
Manual backport because of conflicts in upgrade-specific.mdx
> Backport #19004 to release/1.6.x

- .changelog/19139.txt
- ui/app/adapters/job.js
Previously, we'd just concat `?purge=true` without checking to see if other params were present. With this PR, we use our `addToPath` helper to append either via `?` or `&`, depending whether other params like namespace are present.
Resolves #18677
> [ui] Fix: Purging jobs via the UI when namespaces are present

- client/allocrunner/consul_hook.go
- client/consul/consul.go
- client/consul/consul_testing.go
`DeriveSITokenWithJWT` is a misleading method name, because it's used to derive Consul ACL tokens for other purposes too.
> client: change Consul client interface

- command/action.go
- command/commands.go
- command/job_action.go
This establishes `nomad job action` as the primary CLI command for running actions within a job, and moves `nomad action` to a wrapping/forwarding shortcut for it (for now; when future "action" contexts come about, this will determine which one to forward to)
This mimics the behaviour of `nomad status` to route its command to either `nomad job status`, `nomad node status`, etc. depending on the context passed to it, but for actions.
```
nomad job action \
-group=group \
-task=task \
-job=actions-demo \
party
```
and
```
nomad action \
-group=group \
-task=task \
-job=actions-demo \
party
```
should now behave the same way.
> Reframe nomad action as a wrapper around nomad job action

- command/agent/job_endpoint.go
- nomad/job_endpoint.go
- nomad/structs/actions.go
- nomad/structs/actions_test.go
Custom RPC objects allows us to make future changes without impacting or bloating other RPC endpoints that use the same object. I also made some minor naming update to the response object and made use of a const for the handler name.
I noticed there were not any tests covering the RPC endpoint, so I will raise a followup PR to add some.
> actions: use specific RPC request object and tighten naming.

- .changelog/19155.txt
- command/job_restart.go
- command/job_restart_test.go
The `nomad job restart` command should skip allocations that already have replacements. Restarting an allocation with a replacement is a no-op because the allocation status is terminal and the command's replacement monitor returns immediatelly.
But by not skipping them, the effective batch size is computed incorrectly.
> cli: skip allocs with replacements on job restart

- .changelog/19154.txt
- command/job_restart.go
Fix a panic when a question receives an interrupt signal before the signal handler is initialized.
> cli: prevent panic on CTRL+C during a question

- .changelog/19172.txt
- command/agent/alloc_endpoint.go
These are "close" messages and not actual errors. 
Fixes https://github.com/hashicorp/nomad/issues/19164.
> agent: ignore websocket statuses 1000, 1001 and 1005 correctly

- e2e/ui/global-setup.js
- e2e/ui/input/proxy.nomad
- e2e/ui/playwright.config.js
- e2e/ui/run.sh
- e2e/ui/tests/example.spec.js
Fixes #19114 -- a follow-up in nomad-e2e (private) repo will make use of these changes.
Test setup:
* The Nomad service{} allows the `run.sh` script to fallback to a service IP addr, as when running against a local agent instead of AWS
* I think the `nomad exec ... curl aws metadata` here is significantly tidier that what was done over in the (failing) CI step
* it was: `IP=$(nomad node status -json -verbose "$(nomad operator api '/v1/allocations?namespace=proxy' | jq -r '.[] | select(.JobID == "nomad-proxy") | .NodeID')" | jq -r '.Attributes."unique.platform.aws.public-ipv4"')`
* Detect whether running in a TTY (docker errors if you try to run with `-it` when it can't actually do that)
* Add `ci` subcommand, which runs the whole setup, test, teardown process, instead of needing all that …
> E2E: Fix UI tests

- website/content/api-docs/client.mdx
- website/content/api-docs/nodes.mdx
@sofixa reported that was quite hard to find the API endpoints for dynamic node metadata. I think the reason is two-fold:
1. since the feature is called dynamic **node** metadata, and the command is placed under `nomad node meta`, users expect to find the endpoints under `/node`, but it's actually under `/client`.
2. search engines have a really hard time matching the `/client` page with a query such as "nomad dynamic node metadata". From my quick experiment, Google never found the page, Bing had it at the bottom of first page, and DDG had it mid-page.
This PR applies the following changes to try to fix these problems.
Clarify the difference between the `/client` and `/node` endpoints and link from one to the other to help users discover the endpoint they are looking for.
Also update the …
> docs: clarify difference between /client and /node

- command/agent/config_parse_test.go
- nomad/structs/config/vault.go
- website/content/docs/configuration/vault.mdx
Update default auth method path to be `jwt-nomad` to avoid potential conflicts when Vault's `jwt` default is already being used for something else.
> vault: update default JWT auth method path

- .changelog/19189.txt
- helper/pluginutils/loader/init.go
- website/content/docs/upgrade/upgrade-specific.mdx
Nomad load all plugins from `plugin_dir` regardless if it is listed in the agent configuration file. This can cause unexpected binaries to be executed.
This commit begins the deprecation process of this behaviour. The Nomad agent will emit a warning log for every plugin binary found without a corresponding agent configuration block.
Ref: #18529
> client: deprecate loading plugins without config

- client/allocrunner/consul_hook.go
- client/consul/consul.go
This way tokens created by Nomad workloads are easier to keep track of.
> client: add metadata to tokens requested by Consul client

- e2e/e2eutil/allocs.go
- e2e/e2eutil/cli.go
- e2e/e2eutil/job.go
- e2e/v3/jobs3/allocexec3.go
- e2e/v3/jobs3/jobs3.go
- e2e/v3/util3/util3.go
- e2e/vaultsecrets/doc.go
- e2e/vaultsecrets/vaultsecrets_test.go
Fixes #19113
Only the first commit is strictly necessary, and tiny.  I can drop as much of the other stuff as we'd like, but I went ahead and refactored to the v3 e2e structure, and took advantage of having a `testing.T` in there.
The file rename is a separate commit, so the refactor commit(s) can be reviewed by line change instead of the whole file getting recreated (as will happen when I squash all this).
Added some test helper stuff, and removed a couple of unused funcs.
> E2E: Fix vault secrets test

- command/job_stop.go
Before:
```
-no-shutdown-delay
Ignore the the group and task shutdown_delay configuration so that there is no
delay between service deregistration and task shutdown. Note that using
this flag will result in failed network connections to the allocations
being stopped.
```
After:
```
-no-shutdown-delay
Ignore the group and task shutdown_delay configuration so that there is no
delay between service deregistration and task shutdown. Note that using this
flag will result in failed network connections to the allocations being
stopped.
```
> cli: fix help formatting on job stop command.

- .changelog/19147.txt
- command/job_restart.go
- command/job_restart_test.go
- website/content/docs/commands/job/restart.mdx
The `-reschedule` flag stops allocations and assumes the Nomad scheduler will create new allocations to replace them. But this is only true for service jobs.
Restarting non-service jobs with the `-reschedule` flag causes the command to loop forever waiting for the allocations to be replaced, which never happens.
Allocations for system jobs may be replaced by triggering an evaluation after each stop to cause the reconciler to run again.
Batch and sysbatch jobs should not be allowed to be rescheduled as they are expected to run to completion unless stopped.
Closes #19043
> cli: non-service jobs on `job restart -reschedule`

- scheduler/util.go
Fix `tasksUpdated()` to compare the task level `consul` blocks instead of the group.
> scheduler: fix task-level consul diff

- GNUmakefile
- website/content/api-docs/client.mdx
- website/content/docs/commands/acl/bootstrap.mdx
- website/content/docs/commands/eval/delete.mdx
- website/content/docs/job-specification/artifact.mdx
- website/content/docs/job-specification/network.mdx
- website/content/docs/operations/nomad-agent.mdx
- website/content/plugins/drivers/community/lightrun.mdx
- website/content/plugins/drivers/remote/ecs.mdx
- website/content/tools/autoscaling/agent/dynamic_application_sizing.mdx
- website/content/tools/autoscaling/plugins/target/app-sizing-nomad.mdx
We moved the website content directory a while back and never updated the spell checking thing used by `make check`; fix the path and fixup old spelling mistakes.
> website: fix spellcheck path and cleanup some misspellings

- .changelog/19225.txt
- ui/app/components/job-editor/review.js
- ui/app/models/job-plan.js
- ui/app/templates/components/job-editor/review.hbs
- ui/mirage/config.js
- ui/tests/integration/components/job-editor-test.js
- ui/tests/pages/components/job-editor.js
Shows warnings from `job plan` (dry-run) in the Nomad web UI.
Passes along the string that we show in the CLI and otherwise:
```
$ nomad job run  -var="count=4" ../nomad-job-specs/bug-empty-variables.nomad.hcl
Job Warnings:
2 warnings:
* Group "cache" has warnings: 1 error occurred:
* Task "redis" has warnings: 1 error occurred:
* 2 errors occurred:
* Identity[vault_default] identities without an audience are insecure
* Identity[vault_default] identities without an expiration are insecure
* Task redis has an identity called vault_default but no vault block
```
Also, updated the notification/alert to [Helios](https://helios.hashicorp.design/).
Before:
After:
After, no placement errors:
Resolves #19014
> [ui] Display job plan warnings alongside dry run info when attempting to run a job through the web UI

- nomad/structs/structs.go
- nomad/structs/structs_test.go
- nomad/structs/workload_id.go
Token claims are used in several dynamic configuration in Consul and Vault, such as Consul ACL bind and namespace rules, and Vault templated policies.
Adding a claim for the Consul and Vault namespace defined for the service or task allows cluster operators to create more flexible and precise rules.
The `consul_namespace` claim is added to workload identities for Consul services and to task workload identities that have the `consul_` name prefix and are affected by a task or group `consul` block.
The `vault_namespace` claim is added to task workload identities that have the `vault_` name prefix and are affected by a `vault` block.
> identity: add Consul and Vault namespace claims

- nomad/structs/alloc.go
Ensure that the `ServiceProviderNamespace` correctly picks the task-level `consul.namespace` and falls back to the group if set.
---
I've also verified that the ENT test that covers the consumer of this are working:
```
$ go test -v -count=1 ./client/allocrunner/taskrunner -run Test_serviceHook_Namespaces
=== RUN   Test_serviceHook_Namespaces
--- PASS: Test_serviceHook_Namespaces (0.00s)
PASS
ok      github.com/hashicorp/nomad/client/allocrunner/taskrunner        0.027s
```
> service hook: get correct NS for task-level `consul`

- nomad/structs/consul.go
In the legacy Consul token workflow, we check the user's token's permissions in Consul at the time of job submit. The new task-level `consul` block was not being respected when checking the list of namespaces.
---
This can only really be test in ENT. The following test (ref https://github.com/hashicorp/nomad-enterprise/pull/1329) passes:
```go
func TestConsul_Usages(t *testing.T) {
ci.Parallel(t)
job := &Job{
ConsulNamespace: "default",
TaskGroups: []*TaskGroup{
{
Consul: &Consul{Namespace: "nondefault1"},
Services: []*Service{
{Name: "service1"},
{Name: "nomad1", Provider: "nomad"},
},
Tasks: []*Task{
{
Consul: &Consul{Namespace: "nondefault2"},
Services: []*Service{
{Name: "service2"},
{Name: "nomad2", Provider: "nomad"},
},
},
{
Services: []*Service{
{Name: "service3"},
{Name: …
```
> consul: respect task-level namespace when checking permissions

- e2e/nodedrain/node_drain_test.go
- e2e/v3/jobs3/jobs3.go
and error more verbosely if it fails
attempting to either resolve or illuminate #19111 (it's flaky, and I'm not able to reproduce)
> e2e: give node drain KillTimeout test more time

- command/asset/consul-wi-default-auth-method-config.json
- command/setup_consul.go
In order to correctly handle Consul namespaces, auth methods and binding rules must always be created in the `default` namespace only.
> cli: setup consul proper ns handling

- command/setup_consul.go
Update the `nomad setup consul` command to include a `Selector` for the `NamespaceRule` so the logic is only applied when the token has a claim for `consul_namespace`.
Jobs without an explicit `consul.namespace` value receive a JWT without the `consul_namespace` claim because Nomad is unable to determine which Consul namespace should be used.
By using `NamespaceRules`, cluster operators are able to set a default value for these jobs.
> cli: add Consul namespace selector

- website/content/docs/other-specifications/volume/index.mdx
Clarify that when updating a CSI volume's `context` via `nomad volume register`, all parameters need to be specified, not only those to be updated.
> Clarify docs around CSI volume context updates

- .changelog/19270.txt
- nomad/acl.go
In the recent auth refactor, we accidentally fixed a bug where poststop tasks would not get access to Variables. Fix this same bug for backports by ensuring that we use client-terminal status and not server-terminal status to enforce access.
Note this is a backport-only PR.
Ref: https://github.com/hashicorp/nomad/issues/16886
> variables: fix access to variables for poststop tasks

- .changelog/19268.txt
- nomad/node_endpoint.go
- nomad/node_endpoint_test.go
The new Workload Identity workflow for Vault tokens correctly handles post-stop tasks, however the legacy workflow does not. Attempts to get a Vault token are rejected if the allocation is server-terminal or client-terminal, but we should be waiting until the allocation is client-terminal (only) so that poststop tasks get a chance to get Vault tokens too.
Fixes: https://github.com/hashicorp/nomad/issues/16886
See https://github.com/hashicorp/nomad/issues/16886#issuecomment-1836456414 for testing details.
> vault: fix legacy token workflow for poststop tasks

- website/content/docs/configuration/consul.mdx
Some sections of the `consul` configuration are relevant only for clients or servers. We updated our Vault docs to split these parameters out into their own sections for clarity. Match that for the Consul docs.
Preview link: https://nomad-amgfwjney-hashicorp.vercel.app/nomad/docs/configuration/consul
> docs: split `consul` config params into client vs server sections

- nomad/job_endpoint_hook_implicit_identities.go
- nomad/job_endpoint_hook_implicit_identities_test.go
- scheduler/feasible_test.go
Clients prior to Nomad 1.7 cannot support the new workload identity-based authentication to Consul and Vault. Add an implicit Nomad version constraint on job submission for task groups that use the new workflow.
Ref: https://github.com/hashicorp/nomad/pull/18926#issuecomment-1787701350
> client version constraints for implicit identities for WI

- .changelog/18754.txt
In #18754 we accidentally fixed a bug that prevented poststop tasks from getting access to Variables. This was fixed in the 1.6.x branch in #19270, at which point we discovered the fix had been done in main already as part of the auth refactor. Add a changelog entry for it.
> docs: changelog entry for bugfix introduced in #18754

- website/content/docs/configuration/client.mdx
Fixes: https://github.com/hashicorp/nomad/issues/17362
Leaving `reservable_cores` undocumented as it's a weird feature that probably shouldn't have been added to begin with and nobody has asked for it.
> docs: fix documentation of client.reserved.cores

- e2e/isolation/pids_test.go
I think these are slower than [the current default 20s for `jobs3.Submit()`](https://github.com/hashicorp/nomad/blob/639c3f5/e2e/v3/jobs3/jobs3.go#L445) due to `exec` driver, either as a prestart task (for `java` tests) or the main task (for the alloc exec test).
Fixes #16607
> e2e: give isolation test jobs more time to start

- website/content/docs/integrations/consul-integration.mdx
Fixes some errors in the documentation for the Consul integration, based on tests locally without using the `nomad setup consul` command and updating the docs to match.
* Consul CE doesn't support the `-namespace-rule-bind-namespace` option.
* The binding rule for services should not including the Nomad namespace in the `bind-name` parameter (the service is registered in the appropriate Consul namespace).
* The role for tasks should include the suffix "-tasks" in the name to match the binding rule we create.
* Fix some quoting issues in the commands.
> docs: fix recommended binding rules for Consul integration

- e2e/metrics/metrics_test.go
- e2e/v3/cluster3/cluster3.go
This will dump much of the interesting parts of cluster state, including
available nodes and their status, existing allocations and their status,
and existing evaluations and their status.
In theory the cluster should be in a "clean" state before each e2e suite is run. By dumping this state we can see what state the cluster is actually in before running tests.
> e2e: add a ShowState() option to cluster3.Establish options

- .changelog/19153.txt
- ui/app/utils/default-job-templates.js
- ui/app/utils/default_jobs/actions.js
- ui/tests/acceptance/job-run-test.js
An example job in the UI templates to show off actions and how they work.
> [ui] example job with actions

- website/content/docs/concepts/security.mdx
- website/content/docs/configuration/tls.mdx
Some of our documentation on `tls` configuration could be more clear as to whether we're referring to mTLS or TLS. Also, when ACLs are enabled it's fine to have `verify_https_client=false` (the default). Make it clear that this is an acceptably secure configuration and that it's in fact recommended in order to avoid pain of distributing client certs to user browsers.
cc @apollo13 for your thoughts as well.
> docs: clarify behavior and recommendations for mTLS vs TLS for HTTP

- ui/app/styles/components/actions.scss
- ui/package.json
- ui/yarn.lock
Upgraded our design systems library to the latest version.
This required pinning ember-element-helper to 0.6.0 for ember-power-select and probably other reasons.
There were a few small visual artifact diffs here (highlights below), but the only "noticeably broken" change was the alignment of dropdown buttons siwtched to centred by default (only noticeable when the width is extended from elsewhere, like we do in Actions dropdowns with multiple allocs)
> [ui] Helios upgraded to 3.3.0

- e2e/v3/jobs3/jobs3.go
Still trying to figure this TestMetrics cancelled eval failure. Nothing breaks when I drive the test locally. Dumping the cluster state didn't reveal anything other than a healthy looking cluster. Now trying to dump the cancelled eval itself.
> e2e/v3: dump eval if detected as cancelled

- e2e/consul/namespaces.go
- e2e/e2eutil/consul.go
CE side of hashicorp/nomad-enterprise#1337 (look out h4x0rz, 2 1337 4 u) which fixes #19300
* We need only expect a subset of the namespaces to exist, not an exact match (our test cluster may have extra)
* Need to delete a Consul token using its accessor ID, rather than the secret value.
> e2e: fix ConsulNamespaces tests

- .changelog/19334.txt
- client/allochealth/tracker.go
- client/allochealth/tracker_test.go
- client/serviceregistration/service_registration.go
- command/agent/consul/service_client.go
When a Connect service is registered with Consul, Nomad includes the nested `Connect.SidecarService` field that includes health checks for the Envoy proxy. Because these are not part of the job spec, the alloc health tracker created by `health_hook` doesn't know to read the value of these checks.
In many circumstances this won't be noticed, but if the Envoy health check happens to take longer than the `update.min_healthy_time` (perhaps because it's been set low), it's possible for a deployment to progress too early such that there will briefly be no healthy instances of the service available in Consul.
Update the Consul service client to find the nested sidecar service in the service catalog and attach it to the results provided to the tracker. The tracker can then check the sidecar …
> connect: deployments should wait for Connect sidecar checks

- e2e/isolation/pids_test.go
I'm really hoping this is the last change for #16607.
This was the timing on the last run:
```
=== RUN   TestPIDs
=== RUN   TestPIDs/testExecNamespacePID
--- PASS: TestPIDs/testExecNamespacePID (11.42s)
=== RUN   TestPIDs/testExecHostPID
--- PASS: TestPIDs/testExecHostPID (11.44s)
=== RUN   TestPIDs/testExecNamespaceAllocExec
--- PASS: TestPIDs/testExecNamespaceAllocExec (14.96s)
=== RUN   TestPIDs/testJavaNamespacePID
assert.go:14: 
jobs3.go:409: expected not to execute this code path
↪ PostScript | annotation ↷
timeout reached waiting for alloc
--- FAIL: TestPIDs/testJavaNamespacePID (32.38s)
=== RUN   TestPIDs/testJavaHostPID
--- PASS: TestPIDs/testJavaHostPID (24.27s)
=== RUN   TestPIDs/testJavaNamespaceAllocExec
--- PASS: TestPIDs/testJavaNamespaceAllocExec (23.32s)
=== RUN …
```
> e2e: even more time for exec+java test jobs

- .changelog/19349.txt
- command/agent/command.go
- command/agent/command_test.go
The `defaultVault` variable is a pointer to the Vault configuration named `default`. Initially, this variable points to the Vault configuration that is used to load CLI flag values, but after those are merged with the default and config file values the pointer reference must be updated before mutating the config with environment variable values.
Fixes #19342
> config: fix loading Vault token from env var

- GNUmakefile
- ci/modtool.toml
added support for a config file instead of passing arguments to flags in https://github.com/shoenig/go-modtool/releases/tag/v0.2.0
this will be nice when we invoke the `merge` utility in the merge script, so that we don't have to keep the arguments to the flags in sync in two places
> ci: use go-modtool with config file

- website/content/docs/enterprise/index.mdx
- website/content/docs/enterprise/sentinel.mdx
- website/data/docs-nav-data.json
We have a tutorial already, but no reference documentation for the objects available. We can probably remove the last section of the tutorial when this gets deployed.
> docs: expand on Sentinel policy reference

- .changelog/16638.txt
- client/client.go
- client/client_test.go
If an allocrunner is persisted to the client state but the client stops before task runner can start, we end up with an allocation in the database with allocrunner state but no taskrunner state. This ends up mimicking an old pre-0.9.5 state where this state was not recorded and that hits a backwards compatibility shim. This leaves allocations in the client state that can never be restored, but won't ever be removed either.
Update the backwards compatibility shim so that we fail the restore for the allocrunner and remove the allocation from the client state. Taskrunners persist state during graceful shutdown, so it shouldn't be possible to leak tasks that have actually started. This lets us "start over" with the allocation, if the server still wants to place it on the client.
---
This work …
> client: allow incomplete allocrunners to be removed on restore

- .changelog/19377.txt
- ui/app/templates/components/job-editor/edit.hbs
- ui/app/templates/components/job-page/parts/children.hbs
- ui/app/templates/components/job-row.hbs
- ui/app/templates/jobs/index.hbs
- ui/tests/acceptance/jobs-list-test.js
- Disables the "Download as .nomad.hcl" button when running a job through the UI until the template has content (otherwise, you could download a blank file)
- Removes the # of groups column from the jobs index page table
> [ui] Two small UI quality of life changes

- website/content/docs/job-specification/template.mdx
Since `consul-template` ~0.29 (current version 0.35, 0.29 is in Nomad since 1.4.0) there's a dedicated function, `pkiCert`, for certificates. It handles them better (most notably doesn't rotate at startup if there's an already existing certificate which is still valid, which in a Nomad context could result in lots of unneeded rotations.
> update PKI example in template spec with the new pkiCert function

- website/content/docs/upgrade/upgrade-specific.mdx
Nomad 1.7.0 should be considered "yanked". Add a note about this to the upgrade guide.
> docs: add warning not to use 1.7.0

- website/content/docs/commands/operator/snapshot/agent.mdx
- website/content/docs/commands/operator/snapshot/save.mdx
The `operator snapshot` commands and agent don't back up Nomad's key material. Add some warnings about this to places where users might be looking for information on cluster recovery.
Fixes: https://github.com/hashicorp/nomad/issues/19389
cc @sofixa
> docs: add warnings about backing up keyring to snapshot commands

- website/content/docs/configuration/consul.mdx
The auth method names are used by Nomad clients, not servers.
> docs: fix placement of Consul auth method configs

- .changelog/19332.txt
- ui/app/styles/components/exec-window.scss
- ui/app/styles/core/variables.scss
Vertically stacks things so they look nicer on narrow screens
Resolves #19331
> [ui] Small-screen styles for exec window

- .changelog/18516.txt
- e2e/connect/acls.go
- nomad/consul_policy.go
Re: support case #122732
Fixes a bug where Nomad fails to fetch Consul policies whilst checking a Consul token presented when submitting a job, if the policies attached to that token exist within a namespace.
> [ERROR] agent.http: Request error: method=GET url=/v1/acl/policy/83073614-xxxx-xxxx-xxxx-xxxxxxxxxxxx from=127.0.0.1:54668 error="Requested policy does not exist: ACL not found"
- When querying policies from Consul, use the namespace of the token rather than the default namespace.
- This should be possible since [rules and policies within a specific namespace are prevented from accessing resources in another namespace](https://developer.hashicorp.com/consul/docs/security/acl/acl-rules#implicit-namespacing), therefore if the token is from a non-default namespace then all of it's …
> Fixes Consul token checking when policies exist within namespaces

- .changelog/19432.txt
- ui/app/components/token-editor.hbs
When editing or viewing a newly created token, we want the Accessor to be visible (and the secret masked).
The [Helios masked input component](https://helios.hashicorp.design/components/form/masked-input?tab=code#formmaskedinputfield-1) recently changed the property for this from `isMasked` to `isContentMasked`, so updating it here to follow up our [Helios upgrade](https://github.com/hashicorp/nomad/pull/19247):
> [ui] Fix a small regression where accessor is hidden by default when editing a token

- .changelog/19425.txt
- nomad/auth/auth.go
- nomad/auth/auth_test.go
- nomad/server.go
In Nomad 1.7.0, we refactored much of the authentication code to eliminate nil ACLs and create "virtual" ACL objects that can be used to reduce the risk of fail-open security bugs. In doing so, we accidentally dropped support for the default `tls.verify_server_hostname=false` option.
Fix the bug by including the field in the set of conditions we check for the TLS argument we pass into the constructor (this keeps "policy" separate from "mechanism" in the auth code and reduces the number of dimensions we need to test). Change the field name in the Authenticator to better match the intent.
Fixes: https://github.com/hashicorp/nomad/issues/19405
> auth: respect default `tls.verify_server_hostname=false`

- e2e/isolation/input/chroot_docker.nomad
assuming this is similar to #19381, this theoretically fixes
```
=== RUN   TestChrootFS/testTaskImageChroot
assert.go:14: 
chroot_test.go:69: expected regexp match
↪  regex: (?m:^/local\b)
↪ string: /alloc
--- FAIL: TestChrootFS/testTaskImageChroot (3.55s)
```
which is expecting stuff in alloc logs of a very-fast docker job.
> e2e: unflake testTaskImageChroot

- .changelog/19449.txt
- nomad/job_endpoint_hook_connect.go
- nomad/job_endpoint_hook_connect_test.go
The Connect-related constraints injected by the Connect job mutating hook do not account for non-default `consul` blocks (for Nomad Enterprise). This works when both the default and non-default clusters are available and are the same version, but not when they do not.
Fixes: https://github.com/hashicorp/nomad/issues/19442
> consul: fix constraints for non-default clusters (ENT)

- .changelog/19439.txt
- client/allocrunner/taskrunner/template_hook.go
- client/allocrunner/taskrunner/template_hook_test.go
It is often expected that a task that needs access to Vault defines a `vault` block to specify the Vault policy to use to derive a token.
But in some scenarios, like when the Nomad client is connected to a local Vault agent that is responsible for authn/authz, the task is not required to defined a `vault` block.
In these situations, the `default` Vault cluster should be used to render the template.
Closes https://github.com/hashicorp/nomad/issues/19380
> vault: load default config for tasks without vault

- website/content/docs/configuration/client.mdx
Circling back on the comment in [#15961](https://github.com/hashicorp/nomad/pull/15961#discussion_r1092464814). This adds a note to the `bridge_network_hairpin_mode` setting indicating that if it is changed that you need to restart the node.  
I don't thing restarting is a strict requirement but it is by far easier (and more tooling friendly) than the corresponding manual steps.
> [docs] Note reboot to update `bridge_network_hairpin_mode`

- .changelog/19383.txt
- client/lib/numalib/detect_linux.go
- client/lib/numalib/detect_linux_test.go
- client/lib/numalib/topology.go
Unsupported environments like containers or guests OSs inside LXD can incorrectly number of available cores thus leading to numalib having trouble detecting cores and panicking. This code adds tests for linux sysfs detection methods and fixes the panic from #19372.
> numa: account for incorrect core number on topology.insert

- .changelog/19452.txt
- ui/app/components/action-card.hbs
- ui/app/components/action-card.js
- ui/app/styles/components/actions.scss
Uses overflow-anchor (shoutout to https://css-tricks.com/books/greatest-css-tricks/pin-scrolling-to-bottom/) to keep long-running or tall Actions outputs in the UI scrolled to the bottom.
Importantly, if the user scrolls AWAY from the bottom, let's say to carefully read an earlier log or copy it, the anchoring behaviour ceases (until they scroll back to the bottom again)
Resolves #19437
> [ui] When Action output is long enough, keep a user scroll-anchored to the bottom

- website/content/api-docs/acl/auth-methods.mdx
Lower cased the title and headings in line with our company-wide style since this is being linked in an upcoming blog I was editing.  I also lowercased words such as "Auth Method" and other primitives/components when mentioned in prose - this is in line with our style guide as well where we don't capitalize auth method and we only capitalize components that are SKU/product-like in their separateness/importance.
https://docs.google.com/document/d/1MRvGd6tS5JkIwl_GssbyExkMJqOXKeUE00kSEtFi8m8/edit
Adam Trujilo should be in agreement with changes like this based on our past discussions, but feel free to bring in stake holders if you're not sure about accepting and we can discuss.
> Update auth-methods docs to comply with style guide

- website/content/docs/upgrade/upgrade-specific.mdx
Add a note about the 1.7.0-1.7.1 panics for CPU fingerprinting.
> docs: note that 1.7.2 yanks 1.7.0-1.7.1 due to CPU fingerprint bug

- .changelog/19485.txt
- client/fingerprint/consul.go
- client/fingerprint/consul_test.go
Consul Enterprise agents all belong to an admin partition. Fingerprint this attribute when available. When a Consul agent is not explicitly configured with "default" it is in the default partition but will not report this in its `/v1/agent/self` endpoint. Fallback to "default" when missing only for Consul Enterprise.
This feature provides users the ability to add constraints for jobs to land on Nomad nodes that have a Consul in that partition. Or it can allow cluster administrators to pair Consul partitions 1:1 with Nomad node pools. We'll also have the option to implement a future `partition` field in the jobspec's `consul` block to create an implicit constraint.
Ref: https://github.com/hashicorp/nomad/issues/13139#issuecomment-1856479581
> consul: fingerprint Consul Enterprise admin partitions

- .changelog/19490.txt
- client/allocrunner/taskrunner/consul_hook.go
- client/allocrunner/taskrunner/task_runner_hooks.go
- website/content/docs/job-specification/consul.mdx
Due to some refactoring mishap, task-level Consul hook was never triggered and thus never wrote any secrets in task secret dirs. 
Fixes #19488
> client: consul hook not called for templates

- .changelog/19176.txt
- client/lib/cgroupslib/init.go
- client/lib/cgroupslib/mount.go
On Linux systems that have been built without all necessary CGroup controllers enabled, you may get a non-descriptive error when initializing `cgroupslib`:
```
[ERROR] client.proclib.cg2: failed to create nomad cgroup: error="write /sys/fs/cgroup/cgroup.subtree_control: invalid argument"
```
A similarly-opaque error is logged on every run of `cpuparts_hook`, but I could not find a simple way of clarifying the error logs.
This PR checks whether all expected controllers are available, and will log an error if they are not.
On top of that, the controllers will be enabled one at a time, giving a more clear error when one of them is not supported.
You can validate this PR by appending `cgroup_disable=cpuset` to your kernel's command line arguments (`/etc/default/grub` or similar)
> Mark CGroups as off when missing essential controllers

- .changelog/19483.txt
- nomad/fsm.go
- nomad/fsm_test.go
Adds a "return err" that was accidentally dropped shortly after the Namespace OSS migration.
fixes https://github.com/hashicorp/nomad/issues/19414
> Surfaces errors from namespace delete properly

- .changelog/19496.txt
- ui/app/components/action-card.hbs
- ui/app/styles/components/actions.scss
A happy little button on some happy little output
Stays sticky when/if you scroll
Copies action output to clipboard
> [ui] Adds a copy button to Action output

- api/services.go
`go vet` should've caught this, but I think it may not be running in `./api` since it's a separate module. I will try to fix CI in a follow-up PR so it can be backported.
> consul: fix parsing of `service.cluster` field

- GNUmakefile
- api/agent.go
- api/allocations_exec.go
- api/api.go
- api/consul.go
- api/event_stream.go
- api/internal/testutil/responsewriter.go
- api/internal/testutil/server.go
- api/operator.go
- api/retry.go
- api/search.go
- api/tasks.go
- api/variables.go
- drivers/shared/executor/procstats/list_default.go
[Outstanding errors](https://github.com/hashicorp/nomad/actions/runs/7255037951/job/19764926088?pr=19513#step:6:31):
```
Error: agent.go:313:46: response body must be closed (bodyclose)
_, resp, err := requireOK(a.client.doRequest(r))
^
Error: allocations_exec.go:112:36: response body must be closed (bodyclose)
conn, _, _ = nodeClient.websocket(reqPath, q)
^
Error: allocations_exec.go:116:36: response body must be closed (bodyclose)
conn, _, err = s.client.websocket(reqPath, q)
^
Error: services.go:254:2: structtag: struct field tag `hcl:"cluster,optional` not compatible with reflect.StructTag.Get: bad syntax for struct tag value (govet)
Cluster string `hcl:"cluster,optional`
^
```
`services.go` is fixed in https://github.com/hashicorp/nomad/pull/19510 but I'm not sure how to fix the …
> ci: run linter in `./api` package

- .changelog/18607.txt
- ui/app/components/client-node-row.js
- ui/app/controllers/clients/index.js
- ui/app/styles/core/table.scss
- ui/app/templates/clients/index.hbs
- ui/app/templates/components/client-node-row.hbs
- ui/tests/acceptance/clients-list-test.js
- ui/tests/pages/clients/list.js
On our clients list page, we abstract node readiness, eligibility, and draining status into one `State` filter.
This leads to situations where a user selects "Ready" and expects to see eligible nodes, but a node can technically be "ready" by status and marked ineligible for new tasks.
This seems confusing with the abstraction in place. As such, selecting "Ready" will not filter out any ineligible nodes.
In resolving this, we've made some updates to the way the State filter works, relative to the others:
- It is an "inclusive" filter, with all options selected by default (others are exclusive until something is clicked)
- query parameters from it are individually appended to the URL, where in other dropdowns a stringified array of all checked options is appended
- it includes subsections …
> [ui] node eligibilty taken into consideration when clients list filtered to "ready"

- .changelog/19529.txt
- ui/app/styles/components/authorization.scss
- ui/app/templates/settings/tokens.hbs
- ui/tests/pages/settings/tokens.js
Also updates some buttons and other components on the sign-in page to the new [Helios](https://helios.hashicorp.design/) style
Resolves #19525
> [ui] Mask token secret when logged in

- .changelog/19535.txt
- nomad/structs/structs.go
- nomad/structs/structs_test.go
- website/content/docs/concepts/workload-identity.mdx
Adds vault_role as an attribute in the JWT if, and only if, the role is specified in the jobspec. This would allow Vault users to interpolate the Vault role in their templated policies. This could be generally useful, but was primarily added to unblock a specific customer. They have verified that this fix (including the constraint below) would unblock JWT-based Vault auth for their setup.
Ideally, we could add the role regardless of where it is specified, but since the server is minting the JWTs and the client has the default fallback auth_role values, it is difficult to insert the role into the JWT claims if it is using the fallback. There is also a potential syncing issue if you update config and then restart Nomad. To get around these issues, Vault Namespaces have the same constraint …
> Adds vault role to JWT claims if specified in jobspec

- .github/workflows/checks.yaml
- .github/workflows/test-core.yaml
- .github/workflows/test-e2e.yml
Bumps our `hashicorp/setup-golang` to v2, which itself bumps the official `cache` and `setup-go` actions.
Also fixes the file extension of some of our workflows/ files to use `.yaml` which is [technically correct](https://yaml.org/faq.html)
> build: bump setup-golang and fix workflow yaml extensions

- website/content/tools/autoscaling/plugins/target/aws-asg.mdx
Document the Nomad Autoscaler AWS target plugin config `retry_attempts`.
Ref.: https://github.com/hashicorp/nomad-autoscaler/pull/594
> docs: add autoscaler AWS `retry_attempts` config

- .changelog/19515.txt
- drivers/shared/executor/executor_universal_linux.go
- e2e/rawexec/doc.go
- e2e/rawexec/input/oomadj.hcl
- e2e/rawexec/rawexec_test.go
- e2e/terraform/etc/nomad.d/nomad-client.service
This might not be wholly true since I don't know all configurations of Nomad, but in our use cases, we run some of our tasks as `raw_exec` for reasons.
We observed that our tasks were running with `oom_score_adj = -1000`, which prevents them from being OOM'd. This value is being inherited from the nomad agent parent process, as configured by systemd.
Similar to #10698, we also were shocked to have this value inherited down to every child process and believe that we should also set this value to 0 explicitly.
I have no idea if there are other paths that might leverage this or other ways that `raw_exec` can manifest, but this is how I was able to observe and fix in one of our configurations.
We have been running in production our tasks wrapped in a script that does: `echo 0 > …
> drivers/executor: set oom_score_adj for raw_exec

- website/content/tools/autoscaling/agent.mdx
- website/content/tools/autoscaling/agent/nomad.mdx
Explain the behaviour when the wildcard namespace value `*` is used to configure the Nomad Autoscaler agent.
Ref.: https://github.com/hashicorp/nomad-autoscaler/issues/65#issuecomment-1620018801
> docs: add note about `*` namespace on autoscaling

- website/content/tools/autoscaling/plugins/target/aws-asg.mdx
Document new `scale_in_protection` configuration of the AWS ASG Autoscaler target plugin.
Ref: https://github.com/hashicorp/nomad-autoscaler/pull/807
> docs: add `scale_in_protection` to AWS Autoscaler

- .changelog/19585.txt
- nomad/job_endpoint_hook_vault.go
- nomad/job_endpoint_hook_vault_ce_test.go
- website/content/docs/configuration/vault.mdx
When the server's `vault` block has a default identity, we don't check the user's Vault token (and in fact, we warn them on job submit if they've provided one). But the validation hook still checks for a token if `allow_unauthenticated` is set to true. This is a misconfiguration but there's no reason for Nomad not to do the expected thing here.
Fixes: https://github.com/hashicorp/nomad/issues/19565
> vault: ignore `allow_unauthenticated` config if identity is set

- .changelog/19578.txt
- nomad/acl_endpoint.go
- nomad/acl_endpoint_test.go
In Nomad 1.7 we updated our JWT library to go-jose, but this changed the wire format of the embedded struct we have in the `IdentityClaims` struct that we return as part of the `WhoAmI` RPC response. This wasn't originally intended to be sent over the wire but other changes in Nomad 1.5+ added a caller to the client. The library change causes a deserialization error on Nomad 1.5 and 1.6 clients, which prevents access to Nomad Variables and SD via template blocks.
Removed the incompatible fields from the response, which are unused by any current caller. In a future version of Nomad, we'll likely remove the `WhoAmI` callers from the client in lieu of using the public keys the clients have to check auth.
Fixes: https://github.com/hashicorp/nomad/issues/19555
See also: …
> acl: remove timestamps from `WhoAmI` response

- e2e/consul/consul_test.go
- e2e/consul/consul_wi_test.go
Otherwise we get an error:
```
error: Nomad JWKS endpoint unreachable, verify that Nomad is running and that the JWKS URL http://localhost:4646/.well-known/jwks.json is reachable by Consul
```
> e2e: pass Nomad address to Consul WI test

- e2e/rawexec/input/oversub.hcl
- e2e/rawexec/rawexec_test.go
- website/content/docs/job-specification/resources.mdx
Nomad 1.7 started enforcing memory limits via cgroups on Linux platforms. Add an e2e test demonstrating the use of `memory_max` over subscription. And update the resources docs to mention support for the `raw_exec` driver.
> e2e: add test for raw_exec memory_max configuration

- website/content/docs/drivers/raw_exec.mdx
- website/content/docs/upgrade/upgrade-specific.mdx
Nomad 1.7 eliminated the functionality of setting `no_cgroups` in the `raw_exec` task driver config. Update docs to reflect this, including the upgrade guide.
> docs: update raw_exec driver docs and 1.7 upgrade notes

- .changelog/19601.txt
- ui/app/components/job-status/allocation-status-block.hbs
- ui/app/components/job-status/individual-allocation.hbs
- ui/app/components/job-status/individual-allocation.js
Adds tooltips to non-system/sysbatch jobs' allocation blocks when hovered:
Resolves #19314 (and supercedes #19328
> [ui] Adds group-name tooltips to deploying and steady-state job panels

- .changelog/19605.txt
- nomad/fsm.go
- nomad/fsm_test.go
- nomad/state/schema.go
- nomad/state/state_store.go
- nomad/state/state_store_restore.go
- nomad/state/state_store_restore_test.go
- nomad/state/state_store_test.go
Previously the job submission table was not persisted within state snapshots, meaning servers which received a snapshot during a restore process would seemingly lose the HCL submission data for jobs. This changes ensures this table is both persisted and restored.
closes #19561
> state: ensure the job submission table is persisted and restored.

- api/operator.go
This broke the operator snapshot command.
> Revert e4e70b086a304e4e80496d95f514a4de6e926b3b.

- .changelog/19560.txt
- client/client.go
- helper/broker/notify.go
- helper/broker/notify_test.go
- helper/group/group.go
- helper/raftutil/fsm.go
- nomad/eval_broker.go
- nomad/eval_broker_test.go
- nomad/server.go
- nomad/worker.go
- nomad/worker_test.go
Fixes https://github.com/hashicorp/nomad/issues/19556.
I'm not too sure how/where to add tests for this - please feel free to let me know and I'm happy to add the tests! For now, I've manually tested it following the repro listed in the issue and it seems to work as intended.
> Fix server shutdown not waiting for worker run completion

- website/content/docs/job-specification/group.mdx
`reschedule` is at group level, not inside task ?!
> reschedule is at group level

- website/content/docs/drivers/exec.mdx
- website/content/docs/drivers/java.mdx
- website/content/docs/install/index.mdx
- website/content/docs/install/production/requirements.mdx
Nomad can only use cgroups to control resource requirements if all the cgroups controllers are actually enabled. Add this to our requirements documentation as well as the impacted `exec` and `java` task drivers.
Ref https://github.com/hashicorp/nomad/issues/19481#issuecomment-1858011764
Preview links:
* https://nomad-64er2mu82-hashicorp.vercel.app/nomad/docs/install
* https://nomad-64er2mu82-hashicorp.vercel.app/nomad/docs/install/production/requirements#cgroup-controllers
* https://nomad-64er2mu82-hashicorp.vercel.app/nomad/docs/drivers/java#resource-isolation
* https://nomad-64er2mu82-hashicorp.vercel.app/nomad/docs/drivers/exec#resource-isolation
> docs: describe cgroup controller requirements

- .changelog/19677.txt
- nomad/structs/acl.go
- nomad/structs/acl_test.go
Adds all auth method config fields to the hash function, to ensure user initiated changes are not dropped.
closes #19668
> acl: ensure auth method configs are correctly and fully hashed.

- .changelog/19670.txt
- drivers/shared/executor/executor_universal_linux.go
- drivers/shared/executor/executor_universal_linux_test.go
- e2e/rawexec/input/oversubmax.hcl
- e2e/rawexec/rawexec_test.go
- nomad/structs/structs.go
- nomad/structs/structs_test.go
- website/content/docs/drivers/raw_exec.mdx
This PR makes it possible to configure a raw_exec task to not have an
upper memory limit, which is how the driver would behave pre-1.7.
This is done by setting memory_max = -1. The cluster (or node pool) must
have memory oversubscription enabled.
Closes #19670
Backport to 1.7 so users can re-enable behavior from before.
> drivers/raw_exec: enable configuring raw_exec task to have no memory limit

- .changelog/19665.txt
- api/consul.go
- command/agent/job_endpoint.go
- nomad/job_endpoint_hook_consul.go
- nomad/job_endpoint_hook_consul_ce.go
- nomad/job_endpoint_hook_consul_ce_test.go
- nomad/structs/consul.go
- nomad/structs/diff_test.go
- scheduler/util.go
- website/content/docs/job-specification/consul.mdx
Add support for Consul Enterprise admin partitions. We added fingerprinting in https://github.com/hashicorp/nomad/pull/19485. This PR adds a `consul.partition` field. The expectation is that most users will create a mapping of Nomad node pool to Consul admin partition. But we'll also create an implicit constraint for the fingerprinted value.
Fixes: https://github.com/hashicorp/nomad/issues/13139
> consul: support admin partitions

- .changelog/19689.txt
- nomad/leader_test.go
- nomad/node_endpoint_test.go
- nomad/server.go
- nomad/server_test.go
- nomad/structs/config/vault.go
- nomad/vault_noop.go
- website/content/docs/integrations/vault/acl.mdx
When transitioning from the legacy token-based workflow to the new JWT workflow for Vault the previous code would instantiate a no-op Vault if the server configuration had a `default_identity` block.
This no-op client returned an error for some of its operations were called, such as `LookupToken` and `RevokeTokens`. The original intention was that, in the new JWT workflow, none of these methods should be called, so returning an error could help surface potential bugs.
But the `RevokeTokens` and `MarkForRevocation` methods _are_ called even in the JWT flow. When a leadership transition happens, the new server looks for unused Vault accessors from state and tries to revoke them. Similarly, the `RevokeTokens` method is called every time the `Node.UpdataStatus` and `Node.UpdateAlloc` RPCs are …
> vault: fix token revocation during workflow migration

- nomad/job_endpoint_hook_consul.go
- nomad/job_endpoint_hook_consul_ce.go
The job mutation logic for Nomad CE and Nomad ENT are nearly identical except for a prelude that grabs the correct default cluster. Factor this out into a method that can be shared between both code bases.
Ref: discussion in https://github.com/hashicorp/nomad-enterprise/pull/1367/files#r1447861412
> consul: refactor job mutation hook

- .github/workflows/checks.yaml
- .github/workflows/test-core.yaml
- .github/workflows/test-e2e.yml
Use the latest hashicorp/setup-golang @ v3 which has been fixed to handle the fact that the actions/setup-go action automatically sets up the caching that we had to do manually before.
This should cleanup a bunch of errors showing in recent actions outputs and maybe prevent some double caching.
> build: use setup-golang@v3 to handle auto caching

- nomad/leader_test.go
- nomad/node_endpoint_test.go
- nomad/server.go
- nomad/vault_noop.go
Following up from https://github.com/hashicorp/nomad/pull/19689, when using the no-op Vault client the Nomad server still needs to delete the revoked Vault accessors from state to prevent them from lingering forever after the cluster migrates to the workload identity flow.
No changelog since https://github.com/hashicorp/nomad/pull/19689 has not been released yet.
> vault: remove revoked Vault accessors from state

- website/content/docs/integrations/consul/acl.mdx
Even with the new workload identitiy based flow the Nomad servers still need the `acl = "write"` permission in order to revoke service identity tokens.
> docs: fix Consul ACL requirements

- .changelog/19609.txt
- nomad/core_sched_test.go
- nomad/state/state_store.go
- nomad/state/state_store_test.go
When jobs are deleted with `-purge`, all their deployments and allocations should be deleted from the state store, and the evals status should be set to `complete`. Otherwise we end up in a situation where users could re-submit previously failing jobs, but these new jobs would not get deployments allocated unless `system gc` got called. 
Fixes #10502
> state store: better handling of job deletion

- client/allocdir/alloc_dir.go
- client/allocrunner/alloc_runner.go
- client/allocrunner/alloc_runner_hooks.go
- client/allocrunner/alloc_runner_test.go
- client/allocrunner/allocdir_hook.go
- client/allocrunner/consul_grpc_sock_hook.go
- client/allocrunner/consul_hook.go
- client/allocrunner/consul_http_sock_hook.go
- client/allocrunner/interfaces/runner.go
- client/allocrunner/migrate_hook.go
- client/allocwatcher/alloc_watcher.go
- client/allocwatcher/alloc_watcher_test.go
- client/client_interface_test.go
- client/config/arconfig.go
This PR replace `*allocdir.AllocDir` with `allocdir.Interface` such that we
may eventually have another implementation of alloc directories. This is
in support of the exec2 driver, which will need an implementation of the
alloc directory incompatible with the current version.
Preliminary work for https://github.com/hashicorp/team-nomad/issues/373
No backport; for 1.8
> client/allocdir: use an interface in place of AllocDir structs

- .changelog/19720.txt
- api/operator.go
- command/agent/http.go
- command/agent/operator_endpoint.go
- command/agent/operator_endpoint_test.go
- command/setup_vault.go
- command/setup_vault_test.go
- nomad/operator_endpoint.go
- nomad/operator_endpoint_test.go
- nomad/structs/operator.go
- nomad/structs/workload_id.go
- website/content/api-docs/operator/upgrade-check.mdx
- website/content/docs/commands/setup/vault.mdx
- website/content/docs/integrations/vault/acl.mdx
- website/data/api-docs-nav-data.json
- website/redirects.js
The new `nomad setup vault -check` commmand can be used to retrieve information about the changes required before a cluster is migrated from the deprecated legacy authentication flow with Vault to use only workload identities.
> vault: add new `nomad setup vault -check` commmand

- e2e/e2eutil/utils.go
There's no need to wait for allocs since https://github.com/hashicorp/nomad/pull/19609, in fact waiting for allocs to stop will always fail leading to e2e failures.
> e2e: purging jobs removes all allocs

- website/content/docs/configuration/consul.mdx
Fixes #19747.
- Updates the link from ../configuration/consul to workload identity migration docs.
> docs: updates link to Consul WLI migration docs

- website/content/tools/autoscaling/agent/high_availability.mdx
Document the `high_availability.lock_namespace` configuration of the Nomad Autoscaler.
Ref: https://github.com/hashicorp/nomad-autoscaler/pull/832
> docs: add `lock_namespace` autoscaler config

- website/content/docs/job-specification/hcl2/variables.mdx
- website/content/docs/job-specification/template.mdx
Hey everyone,
A couple of small clarifications in a couple of docs:
- add a warning to `templates` that using Nomad/Consul/Vault results in a heavy dependency
- clarify that HCL2 input variables and Nomad Variables are different
- improve the wording on the `template` source param
Adrian
> Clarify some docs pages

- e2e/e2eutil/utils.go
We're getting errors from some tests that assert service de-registration from Consul after calling `WaitForJobStopped`. Before https://github.com/hashicorp/nomad/pull/19744, `WaitForJobStopped` waited for allocs to be stopped too, but since we [changed](https://github.com/hashicorp/nomad/pull/19609) the behavior of `-purge`, there is no wait anymore and Consul-related assertions happen immediately. 
Example of a failing test:
```
=== RUN   TestE2E/ConsulNamespaces/*consul.ConsulNamespacesE2ETest/TestConsulConnectSidecarsMinimalToken
consul.go:52: 
Error Trace:	/home/runner/actions-runner/_work/nomad-e2e/nomad-e2e/nomad/e2e/e2eutil/consul.go:52
/home/runner/actions-runner/_work/nomad-e2e/nomad-e2e/nomad/testutil/wait.go:68
/home/runner/actions-runner/_work/nomad-e2e/nomad-e2e/nomad/e2e/e2eu …
```
> e2e: WaitForJobStopped correction

- e2e/e2eutil/consul.go
- e2e/e2eutil/utils.go
This fixes [failing](https://github.com/hashicorp/nomad-e2e/actions/runs/7610417480/job/20723782331) `ConsulNamespaceE2E` tests. Since we changed the behavior of `-purge` and consequently modified `WaitForJobStopped`, we need to give Consul more time to confirm de-registration of services. 
This PR also reverts https://github.com/hashicorp/nomad/pull/19749 because it was a bad approach.
> e2e: more retries for RequireConsulDeregistered

- .changelog/19787.txt
- client/allocrunner/interfaces/task_lifecycle.go
- client/allocrunner/taskrunner/connect_native_hook.go
- client/allocrunner/taskrunner/connect_native_hook_test.go
- client/allocrunner/taskrunner/envoy_bootstrap_hook.go
- client/allocrunner/taskrunner/envoy_bootstrap_hook_test.go
Fixes #19781
Do not mark the envoy bootstrap hook as done after successfully running once. Since the bootstrap file is written to /secrets, which is a tmpfs on supported platforms, it is not persisted across reboots. This causes the task and allocation to fail on reboot (see #19781).
This fixes it by *always* rewriting the envoy bootstrap file every time the Nomad agent starts. This does mean we may write a new bootstrap file to an already running Envoy task, but in my testing that doesn't have any impact.
*Alternative 1: Use a regular file*
An alternative approach would be to write the bootstrap file somewhere other than the tmpfs, but this is *unsafe* as when Consul ACLs are enabled the file will contain a secret token:
https://developer.hashicorp.com/consul/commands/connect/envoy#bootst …
> connect: rewrite envoy bootstrap on every restart

- .changelog/19818.txt
- drivers/java/driver.go
The Java driver uses the universal executor, which makes a best effort to identify when a task has been killed due to OOM. This change therefore passes that response within the driver, so that this could become visible to operators via task events and agent telemetry.
> driver/java: populate OOM killed exit result.

- .changelog/19830.txt
- drivers/qemu/driver.go
related #19829 and https://github.com/hashicorp/nomad/pull/19818
> driver/qemu: populate OOM killed exit result.

- .changelog/19829.txt
- drivers/rawexec/driver.go
related https://github.com/hashicorp/nomad/pull/19818
closes #19767
> driver/rawexec: populate OOM killed exit result.

- .semgrep/mpl_busl.yml
- demo/digitalocean/app/bench.go
- helper/crypto/.copywrite.hcl
- helper/crypto/LICENSE
- helper/crypto/crypto.go
- helper/grpc-middleware/.copywrite.hcl
- helper/grpc-middleware/LICENSE
- helper/grpc-middleware/logging/client_interceptors.go
- helper/grpc-middleware/logging/options.go
- helper/pluginutils/grpcutils/.copywrite.hcl
- helper/pluginutils/grpcutils/LICENSE
- helper/pluginutils/grpcutils/utils.go
- helper/pluginutils/hclspecutils/.copywrite.hcl
- helper/pluginutils/hclspecutils/LICENSE
- helper/pointer/.copywrite.hcl
- helper/pointer/LICENSE
- helper/pointer/pointer.go
- helper/pointer/pointer_test.go
- helper/testlog/.copywrite.hcl
- helper/testlog/LICENSE
- helper/testlog/testlog.go
- helper/uuid/.copywrite.hcl
- helper/uuid/LICENSE
- helper/uuid/uuid.go
- helper/uuid/uuid_test.go
- nomad/lock/delay.go
- nomad/lock/delay_test.go
- nomad/lock/ttl.go
- nomad/lock/ttl_test.go
Some packages licensed under MPL-2.0 were incorrectly importing code from packages licensed under BUSL-1.1.
Not all imports are fixed here as they will require additional work to untangle them. To help track progress this commit adds a Semgrep rule that detects incorrect BUSL-1.1 imports in MPL-2.0 packages.
https://github.com/hashicorp/nomad/issues/19833 tracks the remaining incorrect imports.
> license: fix some imports of BUSL-1.1 in MPL-2.0

- helper/users/lookup.go
- helper/users/lookup_linux_test.go
This PR refactors a helper function for getting the UID associated with
a given username to also return the GID and home directory. Also adds
unit tests on the known values of root and nobody user on Ubuntu Linux.
> users: refactor method for getting UID from username

- .changelog/19876.txt
- command/monitor.go
- command/monitor_test.go
When a job eval is blocked due to missing capacity, the `nomad job run` command will monitor the deployment, which may succeed once additional capacity is made available.
But the current implementation would return `2` even when the deployment succeeded because it only took the first eval status into account.
This commit updates the eval monitoring logic to reset the scheduling error state if the deployment eventually succeeds.
Closes #19780
Closes #12784
> cli: fix return code when job deployment succeeds

- .changelog/19878.txt
- ui/app/controllers/exec.js
Resolves #10962 
Previously, when selecting Exec from a group page in the UI (or selecting a task group/task from the exec window's left sidebar), we go over a given job's allocations until we find one that is active and whose name matches the selected one.
This becomes a problem in situations where a user has multiple (differently-named) groups, whose tasks share a name between them.
This PR filters down to the group name in question.
> [ui] Random exec assignment chooses from only those with a matching taskGroup, if provided

- website/content/docs/drivers/docker.mdx
Nomad 1.7 refactored how CPU cores are assigned to tasks, making the Docker-specific `cpuset_cpus` configuration no longer used.
Closes #19815
> docs: remove Docker `cpuset_cpus` config

- .changelog/19892.txt
- command/tls_ca_create.go
- command/tls_ca_create_test.go
- helper/tlsutil/generate.go
The current implementation of the `nomad tls ca create` command ovierrides the value of the `-domain` flag with `"nomad"` if no additional customization is provided.
This results in a certificate for the wrong domain or an error if the `-name-constraint` flag is also used.
The logic for `IsCustom()` also seemed reversed. If all custom fields are empty then the certificate is _not_ customized, so `IsCustom()` should return false.
Closes https://github.com/hashicorp/nomad/issues/19836
> cli: fix `tls ca create` command with `-domain`

- website/content/api-docs/index.mdx
When filtering list results, the filter expression is applied to the full object, not the stub. This is useful because it allows users to filter the list on fields not present in the object stub. But it can also be confusing because some fields have different names, or only exist in the stub, so the filter expression needs to reference fields not present in returned data.
Filtering on the stub would reduce the confusion, but it would also restrict users to only be able to filter on the fields in the stub, which, by definition, are just a subset of the original fields.
Documenting this behaviour can help users understand unexpected errors and results.
Closes #19871
> docs: add note about stub list filtering

- website/content/docs/concepts/security.mdx
When Nomad is configured with `verify_https_client=false` endpoints that do not require an ACL token can be accessed without any other type of authentication. Expand the docs to mention this effect.
Closes https://github.com/hashicorp/nomad/issues/19870
> docs: expand impact of `verify_https_client=false`

- website/content/api-docs/acl/auth-methods.mdx
- website/content/api-docs/acl/roles.mdx
- website/content/docs/commands/acl/auth-method/update.mdx
- website/content/docs/commands/acl/role/create.mdx
- website/content/docs/commands/acl/role/update.mdx
- website/content/docs/job-specification/action.mdx
Started by updating the Actions docs, and after coming across `regexp.MustCompile("^[a-zA-Z0-9-]{1,128}$")` and testing locally, realized that the docs on Roles and Auth Methods indicated underscores being allowed in names, so correcting that here too.
> [docs] Add action name restrictions and correct auth method and role name restrictions

- client/fingerprint/consul.go
- client/fingerprint/consul_test.go
Support for fingerprinting the Consul admin partition was added in #19485. But when the client fingerprints Consul CE, it gets a valid fingerprint and working Consul but with a warn-level log. Return "ok" from the partition extractor, but also ensure that we only add the Consul attribute if it actually has a value.
Fixes: https://github.com/hashicorp/nomad/issues/19756
> fingerprint: eliminate spurious warning logs with Consul CE

- .changelog/19925.txt
- command/agent/host/windows.go
- drivers/shared/executor/executor_windows.go
On Windows, Nomad uses `syscall.NewLazyDLL` and `syscall.LoadDLL` functions to load a few system DLL files, which does not prevent DLL hijacking attacks. Hypothetically a local attacker on the client host that can place an abusive library in a specific location could use this to escalate privileges to the Nomad process. Although this attack does not fall within the Nomad security model, it doesn't hurt to follow good practices here.
We can remove two of these DLL loads by using wrapper functions provided by the stdlib in `x/sys/windows`
Fixes: https://github.com/hashicorp/nomad-enterprise/issues/991
> windows: remove LazyDLL calls for system modules

- .changelog/19915.txt
- client/client.go
- client/lib/cgroupslib/init.go
- client/lib/proclib/wrangler_cg1_linux.go
- client/lib/proclib/wrangler_cg2_linux.go
- client/lib/proclib/wrangler_default.go
- client/lib/proclib/wrangler_linux.go
The Nomad client expects certain cgroups paths to exist in order to manage tasks. These paths are created when the agent first starts, but if process fails the agent would just log the error and proceed with its initialization, despite not being able to run tasks.
This commit surfaces the errors back to the client initialization so the process can stop early and make clear to operators that something went wrong.
Closes #19847
> client: prevent start on cgroups init error

- .changelog/19935.txt
- drivers/shared/executor/executor_linux.go
The value for the executor cgroup CPU weight must be within the limits imposed by the Linux kernel.
Nomad used the task `resource.cpu`, an unbounded value, directly as the cgroup CPU weight, causing it to potentially go outside the imposed values.
This commit clamps the CPU shares values to be within the limits allowed.
Closes https://github.com/hashicorp/nomad/issues/19797
> executor: limit the value of CPU shares

- .changelog/19933.txt
- nomad/job_endpoint_test.go
- scheduler/rank.go
- testutil/wait.go
When an allocation can't be placed because of a port collision the resulting blocked eval is expected to have a metric reporting the port that caused the conflict, but this metrics was not being emitted when preemption was enabled.
Closes https://github.com/hashicorp/nomad/issues/19827
> scheduler: retain eval metrics on port collision

- .changelog/19903.txt
- nomad/state/events.go
- nomad/state/events_test.go
When jobs are deregistered with the `purge` flag they are immediately deleted from the state store instead of just updated to be marked as stopped.
Without tracking job deletions the event stream would not receive a `JobDeregistered` event when `purge` was set.
Ref. #19834
> events: emit event when job is deleted

- nomad/state/state_store.go
The state store's `UpsertPlanResults` method canonicalizes allocations in order to upgrade them to a new version. But the method does not copy the allocation before doing so, which can potentially corrupt the state store. This hasn't been implicated in any known user-facing bugs, but was detected when running Nomad under a build with the Go toolchain's data race detection enabled.
Noticed while working on https://github.com/hashicorp/nomad/pull/19932, but it looks like this bug has existed since 0.10.4
> state: fix state store corruption in plan apply

- .changelog/19932.txt
- command/agent/alloc_endpoint.go
- command/agent/alloc_endpoint_test.go
- command/agent/job_endpoint.go
In #19172 we added a check on websocket errors to see if they were one of several benign "close" messages. This change inadvertently assumed that other messages used for close would not implement `HTTPCodedError`. When errors like the following are received:
> msgpack decode error [pos 0]: io: read/write on closed pipe"
they are sent from the inner loop as though they were a "real" error, but the channel is already being closed with a "close" message.
This allowed many more attempts to pass thru a previously-undiscovered race condition in the two goroutines that stream RPC responses to the websocket. When the input stream returns an error for any reason (for example, the command we're executing has exited), it will unblock the "outer" goroutine and cause a write to the websocket. If we're …
> alloc exec: fix panics after stream close

- website/content/docs/configuration/client.mdx
This PR changes the example of the client config option `fingerprint.denylist`
to include all the cloud environment fingerprinters. Each one contains a
2 second HTTP timeout to a metadata endpoint that does not exist if you are not
in that particular cloud. When run in serial on startup, this results in
an 8 second wait where nothing useful is happening.
Closes #16727
> docs: describe cloud environments in fingerprint denylist

- client/allocrunner/networking_cni.go
- client/allocrunner/networking_cni_test.go
We updated our `go-cni` dependency in #17582 but this left deprecation warnings on the `cni.CNIResult` type (now `cni.Result`).
(Nothing user-facing in here, so no changelog entry)
> CNI: fix deprecation warnings

- drivers/shared/eventer/eventer_test.go
<details>
<summary>Data race stack trace</summary>
```
Read at 0x00c0001be128 by goroutine 20:
github.com/hashicorp/nomad/drivers/shared/eventer.TestEventer_iterateConsumers()
/Users/jrasell/Projects/Go/nomad/drivers/shared/eventer/eventer_test.go:122 +0x600
testing.tRunner()
/Users/jrasell/.asdf/installs/golang/1.21.6/go/src/testing/testing.go:1595 +0x1b0
testing.(*T).Run.func1()
/Users/jrasell/.asdf/installs/golang/1.21.6/go/src/testing/testing.go:1648 +0x40
Previous write at 0x00c0001be128 by goroutine 25:
github.com/hashicorp/nomad/drivers/shared/eventer.(*Eventer).iterateConsumers()
/Users/jrasell/Projects/Go/nomad/drivers/shared/eventer/eventer.go:113 +0x514
github.com/hashicorp/nomad/drivers/shared/eventer.TestEventer_iterateConsumers.func2() …
```
> test: fix test datarace within driver shared eventer.

- helper/broker/notify_test.go
<details>
<summary>Data race stack trace</summary>
```
==================
Write at 0x00c0000a9698 by goroutine 7:
runtime.racewrite()
<autogenerated>:1 +0x10
github.com/hashicorp/nomad/helper/broker.TestGenericNotifier()
/Users/jrasell/Projects/Go/nomad/helper/broker/notify_test.go:62 +0x6b8
testing.tRunner()
/Users/jrasell/.asdf/installs/golang/1.21.6/go/src/testing/testing.go:1595 +0x1b0
testing.(*T).Run.func1()
/Users/jrasell/.asdf/installs/golang/1.21.6/go/src/testing/testing.go:1648 +0x40
Previous read at 0x00c0000a9698 by goroutine 19:
runtime.raceread()
<autogenerated>:1 +0x10
github.com/hashicorp/nomad/helper/broker.TestGenericNotifier.func2()
/Users/jrasell/Projects/Go/nomad/helper/broker/notify_test.go:50 +0x3c …
```
> test: fix test datarace within helper broker.

- .changelog/19990.txt
- nomad/structs/diff.go
- nomad/structs/diff_test.go
- nomad/structs/services.go
While working on https://github.com/hashicorp/nomad/issues/10628 I discovered that the `expose` block was missing an implementation of Diff, which means it doesn't show up correctly in `job plan` output.
I've also fixed a field comparison bug in `ServiceCheck.Equal` that doesn't appear to impact any production code.
> connect: fix missing diff of expose block

- .changelog/19985.txt
- ui/app/components/exec-terminal.js
- ui/app/templates/exec.hbs
- ui/package.json
- ui/yarn.lock
Resolves #19849 
In an exec window context, navigating away from the page is not possible by in-page links, as there are none (besides Documentation, which opens in a new tab). Otherwise, closing the window by clicking exit, or using a keyboard shortcut like ctrl+w, ctrl+q, etc. is the most common method.
Unfortunately, some of those keyboard shortcuts are also used for in-terminal activity (like `ctrl+w` to delete a word in bash, or split a terminal in vim), and users' muscle memory may cause them to close a window, losing time and context along the way.
This PR adds a beforeunload handler to the exec terminal component, triggered whenever a socket is open and the user does an action that would close the parent tab/window. It will add a prompt asking the user if they meant to close it, …
> ui: Confirmation on exit from exec as long as socket has been opened

- .changelog/19989.txt
- ui/app/adapters/variable.js
- ui/app/components/variable-form.hbs
- ui/app/components/variable-form.js
- ui/app/controllers/jobs/run/templates/new.js
- ui/app/templates/jobs/run/templates/new.hbs
- ui/tests/integration/components/variable-form-test.js
(Note: custom job templates are backed by Nomad Variables and so the variable adapter handleResponse method tackles them both)
When providing an invalid name for a variable or job template in the UI, give the user a message in realtime as they type to proactively warn of an invalid name, and if they continue to try to save regardless, transform the otherwise opaque error message (mentions an RPC error) into something more tangible.
> ui: Warning and better error handling for invalid-named variables and job templates

- .changelog/20007.txt
- client/allocrunner/alloc_runner.go
- client/allocrunner/taskrunner/task_runner.go
- client/allocrunner/taskrunner/task_runner_test.go
- client/structs/allochook.go
- website/content/docs/job-specification/network.mdx
CNI plugins may set DNS configuration, but this isn't threaded through to the task configuration so that we can write it to the `/etc/resolv.conf` file as needed. Add the `AllocNetworkStatus` to the alloc hook resources so they're accessible from the taskrunner, which will prepend the DNS entries to any entries provided by the user.
Fixes: https://github.com/hashicorp/nomad/issues/11102, which I bumped up against while working on https://github.com/hashicorp/nomad/issues/10628
> cni: add DNS set by CNI plugins to task configuration

- website/redirects.js
And cleanup whitespace
We use this s link in a log message: https://github.com/hashicorp/nomad/blob/v1.7.4/client/allocrunner/taskrunner/envoy_bootstrap_hook.go#L382
> docs: fix s/envoy-bootstrap-error redirect

- .changelog/19986.txt
- nomad/structs/workload_id.go
Fixes a null pointer exception if `Alloc.SignIdentities` was called for any service and any service lacked an identity.
Fixes #19986
> Prevent NPE when service lacks identity

- website/content/docs/job-specification/consul.mdx
This PR updates the consul Block page for admin partition support, per [CE-555](https://hashicorp.atlassian.net/browse/CE-555).
The following changes were made to the page:
- Admin partitions example added 
- `CONSUL_PARTITION` environment variable sentence and link added
- Description of a Consul partition was modified. It's not that Consul Community has access to zero admin partitions. There is one admin partition, called `default` that Community edition is limited to.
[Link to deployment preview](https://nomad-2ncfwj0sc-hashicorp.vercel.app/nomad/docs/job-specification/consul#consul-admin-partition)
[CE-555]: https://hashicorp.atlassian.net/browse/CE-555?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: Consul Admin partition example and updates

- .changelog/20047.txt
- ui/app/controllers/evaluations/index.js
- ui/app/templates/evaluations/index.hbs
Because we have multiple links on the Evaluations page table (to open the eval in a sidebar, and also to open the job to which the eval is related), we used a keyboard event "keyup" binding to let a user do something like tab + enter or tab + space to open the sidebar.
This predated the general keyboard navigation convention in the Nomad UI of shift+01, shift+02 to open a list row item action. The "which key was pressed" guard on opening the sidebar prevents this sidebar from opening with shift+n, and this PR fixes that by passing in an explicit "keynav" string on command.
> [ui] Fixes an issue where shift+num would not open an eval on the evaluations index table

- .changelog/20049.txt
- command/job_restart.go
stopAlloc() checks if an allocation represents a system job like this:
```
if *alloc.Job.Type == api.JobTypeSystem {
...
}
```
This caused the cli to crash:
```
==> 2024-02-29T08:45:53+01:00: Restarting 2 allocations
2024-02-29T08:45:54+01:00: Rescheduling allocation "6a9da11a" for group "redacted-group"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x20 pc=0x10686affc]
goroutine 36 [running]:
github.com/hashicorp/nomad/command.(*JobRestartCommand).stopAlloc(0x14000b11040, {0x14000996dc0?, 0x0?})
github.com/hashicorp/nomad/command/job_restart.go:968 +0x25c
github.com/hashicorp/nomad/command.(*JobRestartCommand).handleAlloc(0x14000b11040, {0x14000996dc0?, 0x0?}) …
```
> Avoid NPE in nomad/command/job_restart.go

- helper/users/dynamic/pool.go
- helper/users/dynamic/pool_test.go
This PR adds an implementation of a Pool from which dynamic users can
be allocated on behalf of tasks making use of an upcoming feature of
Nomad client (dynamic users).
A task hook and client plumbing, etc. will be in follow up PRs.
> exec2: implement a dynamic users pool

- ui/app/templates/allocations/allocation/task/index.hbs
- ui/tests/acceptance/actions-test.js
- ui/tests/acceptance/job-status-panel-test.js
Makes a few percyCSS changes to snapshots to prevent things like dates/times and small svg artefacts from causing a "This template changed" diff on Percy runs.
> [ui]] Percy Stabilization

- nomad/state/schema.go
When creating a job ACL, you must supply a job ID if you supply a namespace.  If you try to give a namespace without a job ID, the error states "JobACL.JobID without Namespace", which is the opposite of what really happened.
> Fix wording of ACL error message

- client/allocrunner/alloc_runner.go
- client/allocrunner/taskrunner/dynamic_users_hook.go
- client/allocrunner/taskrunner/dynamic_users_hook_test.go
- client/allocrunner/taskrunner/task_runner.go
- client/allocrunner/taskrunner/task_runner_hooks.go
- client/client.go
- client/config/arconfig.go
- helper/users/dynamic/pool.go
- helper/users/dynamic/users.go
- plugins/drivers/driver.go
This PR impelements a TR hook for allocating dynamic workload users from
a pool managed by the Nomad client. This adds a new task driver Capability,
DynamicWorkloadUsers - which a task driver must indicate in order to make
use of this feature.
The client config plumbing is coming in a followup PR - in the RFC we
realized having a client.users block would be nice to have, with some
additional unrelated options being moved from the deprecated client.options
config.
> exec2: implement dynamic workload users taskrunner hook

- website/content/docs/upgrade/index.mdx
Nomad has always placed an extremely high priority on backward compatibility. We have always aimed to support N-2 major releases and usually gone above and beyond that.
The new https://www.hashicorp.com/long-term-support policy also mentions that N-2 is what we have always supported, so it's probably time for our docs to reflect that reality.
> docs: skipping a major release is fine

- .changelog/20066.txt
- .changelog/20100.txt
- go.mod
- go.sum
Although Nomad is not vulnerable to CVE-2024-24786 because it's configured to discard unknown messages during unmarshaling, we should upgrade so that third-party vulnerability scanners don't detect the vulnerable version and complain.
I've also updated the changelog for our Go 1.22.1 update to include references to the CVEs it fixes for us.
> deps: upgrade protobuf lib to 1.33.0

- .changelog/18925.txt
- command/job_status.go
- website/content/docs/commands/job/status.mdx
https://github.com/hashicorp/nomad/issues/16566
This modification dumps the entire `job` struct in JSON format. I don't know if just dumps the entire struct is the better approach, if not, i can expose specific fields.
> -json option on jobs status command

- client/client.go
- client/config/config.go
- client/config/users.go
- client/config/users_test.go
- command/agent/agent.go
- command/agent/config.go
- helper/users/dynamic/pool.go
- nomad/structs/config/artifact_test.go
- nomad/structs/config/users.go
- nomad/structs/config/users_test.go
For now just add min/max dynamic user values; soon we can also absorb
the `user.denylist` and `user.checked_drivers` options from the
deprecated `client.options` map.
e.g. usage
```
client {
enabled = true
users {
dynamic_user_min = 70100
dynamic_user_max = 70200
}
}
```
> exec2: add a client.users configuration block

- .changelog/20126.txt
- api/tasks.go
- api/tasks_test.go
- client/allocrunner/taskrunner/getter/params.go
- client/allocrunner/taskrunner/getter/params_test.go
- client/allocrunner/taskrunner/getter/sandbox.go
- client/allocrunner/taskrunner/getter/sandbox_test.go
- client/allocrunner/taskrunner/getter/util.go
- command/agent/job_endpoint.go
- nomad/structs/diff_test.go
- nomad/structs/structs.go
- nomad/structs/structs_test.go
Hey, I'm so glad this is my first PR to nomad. 🎉
this PR supports an insecure flag for artifact download as described in #19883 
The artifact block now supports an insecure flag like the example below. this flag will prevent the go-getter from validating the TLS certificate. 
```
artifact {
source        = "https://expired.badssl.com/"
destination = "local/some-directory"
insecure     = true
}
```
Closes #19883
> Support insecure flag on artifact

- nomad/acl_endpoint.go
- nomad/operator_endpoint.go
As of #18754 which shipped in Nomad 1.7, we no longer need to nil-check the object returned by `ResolveACL` if there's no error return, because in the case where ACLs are disabled we return a special "ACLs disabled" ACL object. Checking nil is not a bug but should be discouraged because it opens us up to future bugs that would bypass ACLs.
While working on an unrelated feature @lindleywhite discovered that we missed removing the nil check from several endpoints with our semgrep linter. This changeset fixes that.
Co-Author: Lindley <lindley@hashicorp.com>
> acl: remove unused nil ACL object handling

- .changelog/20153.txt
- api/operator_autopilot.go
- api/operator_test.go
- command/agent/operator_endpoint.go
- command/agent/operator_endpoint_ce.go
- command/agent/operator_endpoint_test.go
- nomad/autopilot.go
- nomad/autopilot_ce.go
- nomad/autopilot_test.go
- nomad/structs/autopilot.go
- website/content/api-docs/operator/autopilot.mdx
Add information about autopilot health to the `/operator/autopilot/health` API in Nomad Enterprise.
I've pulled the CE changes required for this feature out of @lindleywhite's PR in the Enterprise repo. A separate PR will include a new `operator autopilot health` command that can present this information at the command line.
Ref: https://github.com/hashicorp/nomad-enterprise/pull/1394
> autopilot: add Enterprise health information to API endpoint

- .changelog/20156.txt
- command/commands.go
- command/operator_autopilot_health.go
- command/operator_autopilot_health_test.go
- website/content/docs/commands/operator/autopilot/health.mdx
- website/data/docs-nav-data.json
Add a command line operation that reports Enterprise autopilot data from the `/operator/autopilot/health` API. I've pulled this feature out of @lindleywhite's PR in the Enterprise repo.
Ref: https://github.com/hashicorp/nomad-enterprise/pull/1394
> autopilot: add `operator autopilot health` command

- nomad/operator_endpoint_test.go
Multi-node Nomad clusters under test must use the RPC calls to bootstrap the ACL subsystem. The original implementation of `testcluster` tried naively supersizing the single node behavior in `TestRaftRemovePeer`, which mutates the single node's state directly. In the case of a multi-node cluster, the RPC calls are necessary to ensure that the data is replicated via Raft to all of the cluster members.
Fixes: https://github.com/hashicorp/nomad/issues/19718
> [chore] Fix LeadershipTransfer tests

- website/content/docs/configuration/telemetry.mdx
Metrics tools that "pull" metrics, such as Prometheus, have a configurable interval for how frequently they scrape metrics. This should be greater or equal to the Nomad `telemetry.collection_interval` to avoid re-scraping metrics that cannot have been updated in that interval.
> docs: make recommendation for collection interval vs scrape interval

- .changelog/20165.txt
- client/config/config.go
- command/agent/agent.go
- command/agent/config.go
- command/agent/config_test.go
When loading the client configuration, the user-specified `client.template` block was not properly merged with the default values. As a result, if the user set any `client.template` field, all the other field defaulted to their zero values instead of the documented defaults.
This changeset:
* Adds the missing `Merge` method for the client template config and ensures it's called.
* Makes a single source of truth for the default template configuration, instead of two different constructors.
* Extends the tests to cover the merge of a partial block better.
Fixes: https://github.com/hashicorp/nomad/issues/20164
> config: fix `client.template` config merging with defaults

- api/consul.go
- command/agent/consul/connect.go
- command/agent/job_endpoint.go
- jobspec/parse_service.go
- jobspec/parse_test.go
- jobspec/test-fixtures/tg-service-connect-proxy.hcl
- nomad/job_endpoint_hook_connect.go
- nomad/job_endpoint_hook_connect_test.go
- nomad/structs/connect.go
- nomad/structs/connect_test.go
- nomad/structs/diff.go
- nomad/structs/diff_test.go
- nomad/structs/services.go
- nomad/structs/services_test.go
Add a transparent proxy block to the existing Connect sidecar service proxy block. This changeset is plumbing required to support transparent proxy configuration on the client, and is first of a series of PRs that will target the `f-tproxy` branch which we intend to ship in Nomad 1.8.
Ref: https://github.com/hashicorp/nomad/issues/10628
Ref: [NMD-191](https://docs.google.com/document/d/1GTC-j6sIgQ3LtYcuoDxnAcluenKZU4WHybth2ngcoOc/edit) (internal link)
> transparent proxy: add jobspec support

- .changelog/20189.txt
- client/allocrunner/networking_cni.go
- client/allocrunner/networking_cni_test.go
- client/allocrunner/taskrunner/task_runner_test.go
In #20007 we fixed a bug where the DNS configuration set by CNI plugins was not threaded through to the task configuration. This resulted in a regression where a DNS override set by `dockerd` was not respected for `bridge` mode networking. Our existing handling of CNI DNS incorrectly assumed that the DNS field would be empty, when in fact it contains a single empty DNS struct.
Handle this case correctly by checking whether the DNS struct we get back from CNI has any nameservers, and ignore it if it doesn't. Expand test coverage of this case.
Fixes: https://github.com/hashicorp/nomad/issues/20174
---
In addition to the unit tests here, I verified this works with the Docker DNS override. Using the default values for `dockerd` and this patch, I get the following in a Nomad job using …
> cni: fix regression in falling back to DNS owned by `dockerd`

- .changelog/16753.txt
- api/consul.go
- api/consul_test.go
- api/utils.go
- command/agent/job_endpoint.go
- command/agent/job_endpoint_test.go
- jobspec/parse_service.go
- jobspec/parse_test.go
- jobspec/test-fixtures/tg-service-connect-gateway-ingress.hcl
- nomad/consul.go
- nomad/structs/diff.go
- nomad/structs/services.go
- website/content/docs/job-specification/gateway.mdx
Add support for further configuring `gateway.ingress.service` blocks to bring this block up-to-date with currently available Consul API fields (except for namespace and admin partition, which will need be handled under a different PR). These fields are sent to Consul as part of the job endpoint submission hook for Connect gatways.
Replaces https://github.com/hashicorp/nomad/pull/16753, which I've rebased on `main` and added another commit that addresses a variety of documentation and style issues.
Docs preview: https://nomad-32oz91834-hashicorp.vercel.app/nomad/docs/job-specification/gateway
> jobspec: update `gateway.ingress.service` Consul API fields

- website/content/docs/job-specification/ephemeral_disk.mdx
- website/content/plugins/drivers/community/rkt.mdx
- website/content/tools/index.mdx
* Clarify that rkt is dead and done in docs. (the awkward "has ended" wording is from the rkt repo)
* Remove OpenAPI spec from tools list since it's been deprecated for a while (and thanks to openai I now cannot type openapi correctly on the first try)
* `ephemeral_disk` had a completely useless example section at the bottom :shrug:
> Small docs updates: bai rkt, cya openapi, lol ephemeral_disk "examples"

- website/content/docs/commands/acl/index.mdx
- website/content/docs/commands/namespace/index.mdx
- website/content/docs/commands/server/join.mdx
- website/content/docs/configuration/acl.mdx
- website/content/docs/configuration/server.mdx
- website/content/docs/other-specifications/acl-policy.mdx
- website/content/docs/other-specifications/namespace.mdx
Our documentation has a hidden assumption that users know that federation replication requires ACLs to be enabled and bootstrapped. Add notes at some of the places users are likely to look for it.
A separate follow-up PR to the federation tutorial should point to the ACL multi-region tutorial as well.
Fixes: https://github.com/hashicorp/nomad/issues/20128
> docs: make it clear that federation features require ACLs

- e2e/vaultsecrets/vaultsecrets_test.go
We've been getting a couple of errors from this test on nightly where the template hasn't rendered by the time we expect it to. I've run some tests locally and this may be a timing issue introduced by recent code changes to templates.
Move the start of the timer to after we're guaranteed that we've got a secret lease TTL started, to eliminate this as a source of flakiness. In my tests this adds another ~5s to a test that already takes over a minute to run anyways.
> E2E: change timing of `vaultsecrets` test to guarantee lease window

- .changelog/20206.txt
- command/operator_debug.go
- command/operator_debug_test.go
- website/content/docs/commands/operator/debug.mdx
The `nomad operator debug` command saves a CPU profile for each interval, and names these files based on the interval.
The same functions takes a goroutine profile, heap profile, etc. but is missing the logic to interpolate the file name with the interval. This results in the operator debug command making potentially many expensive profile requests, and then overwriting the data. Update the command to save every profile it scrapes, and number them similarly to the existing CPU profile.
Additionally, the command flags for `-pprof-interval` and `-pprof-duration` were validated backwards, which meant that we always coerced the `-pprof-interval` to be the same as the `-pprof-duration`, which always resulted in a single profile being taken at the start of the bundle. Correct the check as well …
> operator debug: fix pprof interval handling

- .changelog/20218.txt
- ui/app/controllers/exec.js
- ui/tests/acceptance/actions-test.js
- ui/tests/acceptance/exec-test.js
Adds a `-namespace $NAMESPACEID` string to the example we show when you exec in a task in the Nomad web UI (when not in the default namespace)
Resolves #20213
> [ui] Namespace added to example test in exec window

- helper/subproc/self.go
- helper/subproc/self_test.go
Avoid having a dependency on the `nomad` binary being present if we are invoking as a test binary and not using this functionality.
> subproc: lazy lookup nomad binary in self call

- nomad/structs/volumes.go
- scheduler/util.go
- scheduler/util_test.go
In a [past PR](https://github.com/hashicorp/nomad/pull/19886), a new parameter was introduced as part of the volume mount configuration in the task definition. It controls a security feature in case SELinux is being used. In case the job definition changes, the security feature needs to be reevaluated and the podman plugin in charge of doing the mount re run. This PR forces the scheduler to restart the allocations in case of a change in the job definition.
For more information, refer to the [ticket](https://github.com/hashicorp/nomad-driver-podman/pull/208).
> [f-gh-208] Force recreation and redeployment of task if volume label changes

- .changelog/20234.txt
- go.mod
- go.sum
A Nomad user reported an issue where template runner `View.poll` goroutines were being leaked when using templates with many dependencies. This resource leak was fixed in consul-template 0.37.4.
Fixes: https://github.com/hashicorp/nomad/issues/20163
> deps: update consul-template to 0.37.4 to fix resource leak

- client/allocrunner/network_manager_linux.go
- client/allocrunner/networking_bridge_linux.go
- client/allocrunner/networking_bridge_linux_test.go
- client/allocrunner/networking_cni.go
- client/allocrunner/networking_cni_test.go
- client/client.go
- helper/envoy/envoy.go
When `transparent_proxy` block is present and the network mode is `bridge`, use a different CNI configuration that includes the `consul-cni` plugin. Before invoking the CNI plugins, create a Consul SDK `iptables.Config` struct for the allocation. This includes:
* Use all the `transparent_proxy` block fields
* The reserved ports are added to the inbound exclusion list so the alloc is reachable from outside the mesh
* The `expose` blocks and `check` blocks with `expose=true` are added to the inbound exclusion list so health checks work.
The `iptables.Config` is then passed as a CNI argument to the `consul-cni` plugin.
Ref: https://github.com/hashicorp/nomad/issues/10628
Ref: https://github.com/hashicorp/consul-k8s/pull/3795
---
This PR targets the feature branch. In addition to the new unit …
> tproxy: networking hook changes

- website/content/docs/integrations/consul/index.mdx
Version of Nomad and Consul that were known not to be compatible are no longer supported in general. Update the compatibility matrix for Consul to match.
> docs: update Consul compatibility matrix

- .changelog/15473.txt
- client/allocrunner/networking_bridge_linux.go
- nomad/job_endpoint_hooks.go
- nomad/job_endpoint_hooks_test.go
- nomad/structs/job.go
- nomad/structs/structs.go
- website/content/docs/upgrade/upgrade-specific.mdx
This PR adds a job mutator which injects constraints on the job taskgroups
that make use of bridge networking. Creating a bridge network makes use of the
CNI plugins: bridge, firewall, host-local, loopback, and portmap. Starting
with Nomad 1.5 these plugins are fingerprinted on each node, and as such we
can ensure jobs are correctly scheduled only on nodes where they are available,
when needed.
Targets v1.5.0
Closes #14022
> networking: Inject implicit constraints on CNI plugins when using bridge mode

- nomad/structs/structs.go
- nomad/structs/structs_test.go
The `DNSConfig.IsZero` method incorrectly returns true if any of the fields are empty, rather than if all of them are empty.
The only code path that consumes this method is on the client, where it's used as part of equality checks on the allocation network status to set the priority of allocation updates to the server. Hypothetically, if the network hook modified only the DNS configuration and no task states were emitted, it would be possible to miss an allocation update. In practice this appears to be impossible, but we should fix the bug so that there aren't errors in future consumers.
---
* Backported only to 1.6.x and 1.7.x because this code doesn't exist in 1.5.x.
* I don't have a changelog here because this isn't user-visible as far as I can tell
> structs: fix test for empty DNS configuration

- .changelog/20261.txt
- api/nodes.go
- api/nodes_test.go
The JSON response for the Read Stats client API includes an `AllocDirStats` field. This field is missing in the `api` package, so consumers of the Go API can't use it to read the values we're getting back from the HTTP server.
Fixes: https://github.com/hashicorp/nomad/issues/20246
> api: add missing `AllocDirStats` field in Go API

- website/content/docs/integrations/consul/service-mesh.mdx
- website/content/docs/networking/cni.mdx
Update the service mesh integration docs to explain how Consul needs to be configured for transparent proxy. Update the walkthrough to assume that `transparent_proxy` mode is the best approach, and move the manually-configured `upstreams` to a separate section for users who don't want to use Consul DNS.
Ref: https://github.com/hashicorp/nomad/pull/20175
Ref: https://github.com/hashicorp/nomad/pull/20241
> docs: update service mesh integration docs for transparent proxy

- website/content/docs/job-specification/expose.mdx
- website/content/docs/job-specification/proxy.mdx
- website/content/docs/job-specification/transparent_proxy.mdx
- website/content/docs/job-specification/upstreams.mdx
- website/data/docs-nav-data.json
This PR is targeting the feature branch, and only covers the jobspec reference docs, not the more involved integration docs that'll be under a separate PR.
Preview links:
* https://nomad-git-f-tproxy-docs-hashicorp.vercel.app/nomad/docs/job-specification/transparent_proxy
* https://nomad-git-f-tproxy-docs-hashicorp.vercel.app/nomad/docs/job-specification/proxy
* https://nomad-git-f-tproxy-docs-hashicorp.vercel.app/nomad/docs/job-specification/upstreams
Ref: https://github.com/hashicorp/nomad/pull/20175
> tproxy: `transparent_proxy` reference docs

- website/content/docs/configuration/client.mdx
- website/content/docs/configuration/index.mdx
- website/content/docs/configuration/server.mdx
The data dir parameters for client and server agents confusingly detailed string literal values which were intended to describe interpolated values. This change attempts to remove the confusion and clarify the wording slightly.
closes #20265
> docs: clarify data dir default parameters and default creation.

- nomad/job_endpoint_hook_connect.go
- nomad/job_endpoint_hook_connect_test.go
- nomad/job_endpoint_hooks.go
- nomad/job_endpoint_hooks_test.go
- nomad/structs/job.go
- nomad/structs/job_test.go
Add a constraint on job submission that requires the `consul-cni` plugin fingerprint whenever transparent proxy is used. Add a validation that the `network.dns` cannot be set when transparent proxy is used, unless the `no_dns` flag is set.
This PR targets the feature branch.
Ref: https://github.com/hashicorp/nomad/pull/20175
> tproxy: job submission hooks

- website/content/docs/job-specification/template.mdx
We don't have docs on this, just the warning in the CT logs that suggests 128 is an upper limit (per task, not per template): [runner.go#L304](https://github.com/hashicorp/consul-template/blob/ee19d705e7c12ae05bac4f7302b65ede843c7258/manager/runner.go#L304). Given the debugging we did for https://github.com/hashicorp/nomad/pull/20234 https://github.com/hashicorp/nomad/issues/20163 https://github.com/hashicorp/consul-template/pull/1898 it seems like good advice to have.
> docs: recommendation for maximum number of template dependencies

- e2e/vaultcompat/vaultcompat_test.go
Vault 1.16.1 has a known issue around the JWT auth configuration that will prevent this test from ever passing. Skip testing the JWT code path on 1.16.1. Once 1.16.2 ships it will no longer get skipped.
Ref: https://github.com/hashicorp/nomad/issues/20298
> E2E: skip Vault 1.16.1 for JWT compatibility test

- .changelog/20294.txt
- drivers/docker/cpuset.go
- drivers/docker/cpuset_test.go
Fixes https://github.com/hashicorp/nomad/issues/20293
> docker: use correct effective cpuset filename on legacy cgroups v1 systems

- nomad/state/paginator/paginator.go
- nomad/state/paginator/paginator_test.go
- nomad/state/paginator/tokenizer.go
- nomad/state/paginator/tokenizer_test.go
- nomad/structs/structs.go
For #19339 we will be creating a state index that sorts jobs by `ModifyIndex`, in order to show most-recently-changed jobs at the top of the Nomad web UI, while continuing to sort appropriately with pagination.
The current pagination logic assumes all `NextToken`s are `string`s, which results in odd paging behavior (including infinite loops!) when the token is actually a number, due to lexicographical ordering, e.g. `"10" < "2"`
This doesn't go as far as fully generalizing the `Paginator`/`Tokenizer` relationship (as might be done with `comparable` or `cmp.Ordered` generics), but it adds support for `uint64` tokens for my immediate use case, and opens a door for further future flexibility.
> Enable numeric pagination tokens

- .changelog/20235.txt
- ui/app/components/keyboard-shortcuts-modal.js
- ui/app/services/keyboard.js
- ui/tests/acceptance/keyboard-test.js
In the Nomad UI, you can re-bind your keyboard shortcuts (from `g j` to `job` to go to the jobs route, for example).
But prior to this PR, whether or not you'd re-bound a key command, the hint that would show up when holding `shift` would always be the default. This is because the hints are generated via `{{keyboard-shortcut}}` modifier, and are separate from the list of the keyboard service's `defaultCommands` list.
This PR does a lookup on `get hints()`, which fires every time the user holds `shift`.
> [ui] Show re-bound keyboard nav hints instead of their default values

- command/fmt.go
When `nomad fmt` writes to stdout instead of overwriting a file, the command was using the `UI` output, which appends an extra newline. This results in extra trailing newlines when using `nomad fmt` as part of a pipeline or editor plugin.
Update the command to write directly to stdout when in the stdout mode.
Fixes: https://github.com/hashicorp/nomad/issues/20307
> cli: remove extraneous trailing newline from `nomad fmt`

- .changelog/20317.txt
- nomad/fsm.go
- nomad/node_endpoint.go
- nomad/node_endpoint_test.go
- nomad/structs/structs.go
When a node is set to drain, the state store reads the auth token off the request to record `LastDrain` metadata about the token used to drain the node. This code path in the state store can't correctly handle signed Workload Identity tokens or bearer tokens that may have expired (for example, while restarting a server and applying uncompacted Raft logs).
Rather than re-authenticating the request at the time of FSM apply, record the string derived from the authenticated identity as part of the Raft log entry.
Fixes: https://github.com/hashicorp/nomad/issues/17471
> drain: use authenticated ID as source of drained-by metadata

- .changelog/20346.txt
- scheduler/rank.go
- scheduler/rank_test.go
If preemption is enabled, Nomad doesn't report back the `devices: no devices match request` when it does not find an allocation to evict. 
This allows admins to check why allocations are not being placed when preemption is configured in Nomad.
> fix exhausted node metrics reporting in preemption

- .changelog/20348.txt
- nomad/deploymentwatcher/deployments_watcher.go
- nomad/deploymentwatcher/deployments_watcher_test.go
The deployment watcher on the leader makes blocking queries to detect when the set of active deployments changes. It takes the resulting list of deployments and adds or removes watchers based on whether the deployment is active. But when a job is purged, the deployment will be deleted. This unblocks the query but the query result only shows the remaining deployments.
When the query unblocks, ensure that all active watchers have a corresponding deployment in state. If not, remove the watcher so that the goroutine stops.
Fixes: https://github.com/hashicorp/nomad/issues/19988
> deployment watcher: fix goroutine leak when job is purged

- .changelog/20344.txt
- client/allocrunner/alloc_runner.go
- client/allocrunner/alloc_runner_hooks.go
- client/allocrunner/consul_hook.go
- client/allocrunner/consul_hook_test.go
- client/allocrunner/identity_hook_test.go
- client/allocrunner/taskrunner/identity_hook_test.go
- client/allocrunner/taskrunner/task_runner_test.go
- client/allocrunner/taskrunner/vault_hook_test.go
- client/taskenv/services.go
- client/widmgr/mock.go
- client/widmgr/widmgr.go
- client/widmgr/widmgr_test.go
- nomad/alloc_endpoint.go
- nomad/structs/services.go
- nomad/structs/structs.go
- nomad/structs/structs_test.go
- nomad/structs/workload_id.go
Services can have some of their string fields interpolated. The new Workload Identity flow doesn't interpolate the services before requesting signed identities or using those identities to get Consul tokens.
Add support for interpolation to the WID manager and the Consul tokens hook by providing both with a taskenv builder. Add an "interpolate workload" field to the WI handle to allow passing the original workload name to the server so the server can find the correct service to sign.
This changeset also makes two related test improvements:
* Remove the mock WID manager, which was only used in the Consul hook tests and isn't necessary so long as we provide the real WID manager with the mock signer and never call `Run` on it. It wasn't feasible to exercise the correct behavior without this …
> WI: ensure Consul hook and WID manager interpolate services

- .changelog/20315.txt
- client/allocrunner/taskrunner/getter/params.go
- client/allocrunner/taskrunner/getter/params_test.go
- client/allocrunner/taskrunner/getter/sandbox.go
- client/allocrunner/taskrunner/getter/util_default.go
- client/allocrunner/taskrunner/getter/util_linux.go
- client/allocrunner/taskrunner/getter/util_windows.go
- client/allocrunner/taskrunner/getter/z_getter_cmd.go
- client/config/artifact.go
- client/config/artifact_test.go
- command/agent/agent.go
- nomad/structs/config/artifact.go
- nomad/structs/config/artifact_test.go
- website/content/docs/configuration/client.mdx
> func: Allow custom paths to be added the the getter landlock

- website/content/docs/job-specification/ephemeral_disk.mdx
The docs for ephemeral disk migration use the term "best effort" without outlining the requirements or the cases under which the migration can fail. Update the docs to make it obvious that ephemeral disk migration is subject to data loss.
Fixes: https://github.com/hashicorp/nomad/issues/20355
Preview link: https://nomad-nsel0s9mv-hashicorp.vercel.app/nomad/docs/job-specification/ephemeral_disk#migrate
> docs: clarify "best effort" for ephemeral disk migration

- e2e/terraform/packer/ubuntu-jammy-amd64/setup.sh
In #20296 we added a Go tool chain to the AMI we use for E2E tests, so that we can build `consul-cni` for tproxy testing. This is intended to be temporary until `consul-k8s` 1.4.2 is officially released. But the Go cache from building `consul-k8s` uses up roughly 1.5GiB of space and the test machines have fairly small disks. This causes the Nomad clients to aggressively GC client allocations that stop, which breaks tests that run batch workloads and then read their logs.
> E2E: clean up go mod cache after building `consul-cni`

- client/allocrunner/networking_cni.go
- nomad/job_endpoint_hook_connect.go
Ports are a maximum of uint16, but we have a few places in the recent tproxy code where we were parsing them as 64-bit wide integers and then downcasting them to `int`, which is technically unsafe and triggers code scanning alerts. In practice we've validated the range elsewhere and don't build for 32-bit platforms. This changeset fixes the parsing to make everything a bit more robust and silence the alert.
Fixes: https://github.com/hashicorp/nomad-enterprise/security/code-scanning/444
> CNI: fix bugs in parsing strings to port number integers

- website/content/docs/integrations/consul/index.mdx
Add a standalone section to the Consul integration docs showing how to configure both the Consul agent and the workload to take advantage of Consul DNS. Include a reference to the new transparent proxy feature as well.
Fixes: https://github.com/hashicorp/nomad/issues/18305
Preview link: https://nomad-2z0hxy8kc-hashicorp.vercel.app/nomad/docs/integrations/consul#dns
---
I can backport this to 1.5.x-1.7.x, but I'll need to remove the reference to tproxy, so I'll do that by hand.
> docs: provide guidance on using Consul DNS

- .changelog/20383.txt
- ui/app/models/allocation.js
the hasBeenRestarted allocation property checks against its task events, which can sometimes be null
This can result on a job-index-page error when calculating the `filteredAllocations` to show (we don't show those allocations as "failed" that have been restarted/rescheduled if other more recent ones exist, up to a job's desired count)
(The `?.` is a defensive pattern that fails truthiness checks when the object in question doesn't exist, so `s.events?.content` will return `null` instead of erroring)
> [ui] don't assume that an allocation has a task events array when checking if it hasBeenRestarted

- .changelog/20391.txt
- go.mod
- go.sum
Ref: https://github.com/hashicorp/go-getter/releases/tag/v1.7.4
Note that Nomad isn't impacted on Linux due to our `artifact` sandboxing. The release notes above are in the process of being updated by our security team.
> deps: update `go-getter`

- .release/linux/package/usr/lib/systemd/system/nomad.service
We were asked about this specifically due to client agents not getting OOM killed, so this comment adds some context on why this is set, and when/why you might want to change it.
related: #6672
cc: @davemay99
> systemd: comment on OOMScoreAdjust in service unit

- client/driver_manager_test.go
- drivers/mock/driver.go
- website/content/api-docs/events.mdx
- website/content/api-docs/nodes.mdx
The `mock_driver` is an internal task driver used mostly for testing and simulating workloads. During the allocrunner v2 work (#4792) its name changed from `mock_driver` to just `mock` and then back to `mock_driver`, but the fingreprint key was kept as `driver.mock`.
This results in tasks configured with `driver = "mock"` to be scheduled (because Nomad thinks the client has a task driver called `mock`), but fail to actually run (because the Nomad client can't find a driver called `mock` in its catalog).
Fingerprinting the right name prevents the job from being scheduled in the first place.
Also removes mentions of the mock driver from documentation since its an internal driver and not available in any production release.
No changelog since this is an internal change.
> mock_driver: fix fingreprint key

- .changelog/20408.txt
- ui/app/components/job-status/panel/deploying.js
- ui/tests/integration/components/job-page/service-test.js
The "Are all your canaries healthy?" part of the "should we prompt the user to manually promote their deployment" depended on an `array.every` check without a condition that the array have some members.
This meant that, as shown in #20308, a user can run into a situation where a new canary allocation fails to place, but the system insists that "there are no unhealthy canaries!" so it's manual promotion time.
This checks for at least one new-version allocation with canary status that hasn't been rescheduled before flipping `canariesHealthy` to true. If there are none, the user will continue to be met with a "Your deployment's canaries are still being health checked" pending status.
> [ui] Fix a bug where promotion would be asked with no new canaries

- helper/raftutil/fsm.go
- helper/raftutil/sample_test.go
- nomad/fsm.go
- nomad/job_endpoint.go
- nomad/leader.go
- nomad/namespace_endpoint.go
- nomad/node_pool_endpoint.go
- nomad/operator_endpoint.go
- nomad/periodic.go
- nomad/search_endpoint.go
- nomad/state/sorting.go
- nomad/state/sorting_test.go
- nomad/state/state_store.go
- nomad/state/state_store_test.go
No one asked for this, but I did it while building out the new job statuses endpoint.  I ended up using a different (new) index there, so this may be considered extra unnecessary, and it only actually adds sorting to jobs endpoint, but I think it moves the ball forward slightly, so here it is.
I could be convinced to either:
* go further, add sorting to more endpoints
* go backwards, throw out everything except the new lil helpers I want to use
If we keep this, should I backport it?  Seems like something that could cause backport headaches down the road if I don't.
> state: enable more reverse sorting

- client/allocrunner/consul_hook.go
- client/allocrunner/consul_hook_test.go
- client/allocrunner/taskrunner/consul_hook.go
- client/allocrunner/taskrunner/consul_hook_test.go
- client/allocrunner/taskrunner/task_runner_test.go
- client/allocrunner/taskrunner/template_hook.go
- client/allocrunner/taskrunner/template_hook_test.go
The `consul_hook` in the allocrunner gets a separate Consul token for each task, even if the tasks' identities have the same name, but used the identity name as the key to the alloc hook resources map. This means the last task in the group overwrites the Consul tokens of all other tasks.
Fix this by adding the task name to the key in the allocrunner's `consul_hook`. And update the taskrunner's `consul_hook` and `template_hook` to expect the task name in the key.
Fixes: https://github.com/hashicorp/nomad/issues/20374
Fixes: https://hashicorp.atlassian.net/browse/NOMAD-614
---
In addition to the updated and new tests, I've tested this end-to-end.
<details><summary>jobspec</summary>
```hcl
group "web" {
network {
mode = "bridge"
port "www" {
to = 8001
}
}
service {
port = …
```
> WI: ensure tasks within same alloc get different Consul tokens

- website/content/api-docs/jobs.mdx
The dispatch payload limit is limited to 16KiB, not 64KiB. It's correct in the command docs but incorrect in the API docs. It looks like this was accidentally updated in https://github.com/hashicorp/nomad/commit/c2491e9146ae5db92bb04d2eda2b5ccd58d07851 which was supposed to be for the Variables payload size.
Ref: https://github.com/hashicorp/nomad/blob/v1.7.7/nomad/job_endpoint.go#L36-L38
Fixes: https://github.com/hashicorp/nomad/issues/20432
> docs: fix incorrect dispatch payload limit in API docs

- .semgrep/rpc_endpoint.yml
- nomad/csi_endpoint.go
- nomad/job_endpoint.go
- nomad/namespace_endpoint.go
- nomad/operator_endpoint.go
- nomad/search_endpoint.go
- nomad/stream/event_broker.go
As of #18754 which shipped in Nomad 1.7, we no longer need to nil-check the object returned by ResolveACL if there's no error return, because in the case where ACLs are disabled we return a special "ACLs disabled" ACL object. Checking nil is not a bug but should be discouraged because it opens us up to future bugs that would bypass ACLs.
We fixed a bunch of these cases in https://github.com/hashicorp/nomad/pull/20150 but I didn't update the semgrep rule, which meant we missed a few more. Update the semgrep rule and fix the remaining cases.
> acl: remove remaining unused nil ACL object handling

- ui/app/adapters/job.js
- ui/app/controllers/jobs/index.js
- ui/app/templates/jobs/index.hbs
- ui/config/environment.js
- ui/mirage/config.js
- ui/mirage/scenarios/default.js
- ui/tests/acceptance/jobs-list-test.js
- ui/tests/pages/jobs/list.js
- Adds support for the new modifyIndex-based pagination provided by the /statuses endpoint with a custom First/Prev/Next/Last pagination template on the jobs index
- Adds a new `withPagination` hook for Mirage endpoints (that builds on top of `withBlockingSupport`) that takes a customizable property to paginate upon and provide as `x-nomad-nexttoken`
> modifyIndex-based pagination

- ui/app/components/job-status/allocation-status-row.hbs
- ui/app/components/job-status/allocation-status-row.js
- ui/app/templates/jobs/index.hbs
This hasn't been an issue for the (same components used) viz on Job deploy/status panels, as they are elements with fixed size and css block-level scoping.
Table cells, on the other hand, change their sizes dynamically. Even force-setting the size of the particular cell where this visualization sits wasn't enough to prevent this bug from happening.
What would happen is, it would re-calculate the width of the containing element every time you resize your browser (good!) but a combination of "the nature of table cells is such that they derive their width from their contents" (bad!) and "I wasn't taking the inter-block-gaps into consideration when determining width/ratios" (bad!) meant that this was a funky looking bug.
This fixes that last part, and makes the whole issue go away!
To test …
> [ui] Bugfix: Browser resize no longer makes jobs index summary viz grow forever

- command/acl_token_update.go
- website/content/api-docs/acl/tokens.mdx
- website/content/docs/commands/acl/token/create.mdx
- website/content/docs/commands/acl/token/update.mdx
True up `nomad acl token update` CLI and some docs with most docs and API reality.
Most API docs already rightly say "Note that a token cannot be switched from global to local or visa versa."
Here's what happens if you try:
```
$ nomad acl token update -global=false $accessor
Error updating token: Unexpected response code: 400 (token 0 invalid: 1 error occurred:
* cannot toggle global mode)
```
> acl: token global mode can not be changed

- e2e/vaultcompat/vaultcompat_test.go
This reverts commit 45b36371a12ffae5b5bfaaeadb08f801fb6bc98d. Now that Vault 1.16.2 has shipped, the E2E test will pick up only a working version.
Closes: https://github.com/hashicorp/nomad/issues/20298
> Revert "E2E: skip Vault 1.16.1 for JWT compatibility test (#20301)"

- ui/app/adapters/job.js
- ui/app/components/job-search-box.hbs
- ui/app/components/job-search-box.js
- ui/app/controllers/jobs/index.js
- ui/app/routes/jobs/index.js
- ui/app/routes/optimize.js
- ui/app/serializers/job.js
- ui/app/styles/components/jobs-list.scss
- ui/app/templates/jobs/index.hbs
- ui/config/environment.js
- ui/mirage/config.js
- ui/mirage/scenarios/default.js
- ui/tests/acceptance/jobs-list-test.js
- ui/tests/integration/components/job-search-box-test.js
- ui/tests/pages/components/facet.js
- ui/tests/pages/jobs/list.js
Introduces server-side search and filter to the Jobs index page
Uses [Filter Expressions](https://developer.hashicorp.com/nomad/api-docs#filtering) with our /statuses endpoint to achieve job-property-level filtering. 
Translates dropdown toggles and search queries into filter expression syntax to help teach the syntax for future advanced usage
Re-implements quite a lot of test logic that was performed against an "all jobs are always loaded" version of this page to use the "what we ask for is what we get" version.
> [ui] Searching and filtering options

- website/redirects.js
Manual cherry-pick which got overwritten by the recent release.
Commit has been merged into 1.7.x which means overwrite won't happen again.
> docs: fix s/envoy-bootstrap-error redirect (#20015)

- .changelog/_1432.txt
- nomad/state/state_store.go
When a job is purged, we delete all its allocations and the client detects the absense of the allocations to clean up its resources locally. But the client won't be able to send an allocation status update in this case, which frees the quota being used by that allocation. Instead, we need to free the quota usage inside the state store immediately. To do so, we check if the allocation is already client-terminal before copying it and passing it into the Enterprise code for cleanup.
This commit also refactors the job delete to make it clear there's a single caller of this alloc deletion path. This refactoring eliminates some wasteful logic that queries the "allocs" table, allocates a slice of strings for their IDs, and then queries the "allocs" table one-by-one for each of them for deletion …
> quota: ensure quota usage is freed when jobs are purged

- command/operator_debug_test.go
- nomad/structs/group_test.go
- scheduler/reconnecting_picker/reconnecting_picker_test.go
- scheduler/scheduler_system_test.go
Before:
```
(main)~/src/nomad/nomad/structs$ go test
what? 2 errors occurred:
* stop_after_client_disconnect must be a positive value
* Task group web validation failed: 2 errors occurred:
* Task group cannot be configured with both max_client_disconnect and stop_after_client_disconnect
* max_client_disconnect cannot be negative
what?
PASS
ok      github.com/hashicorp/nomad/nomad/structs        0.057s
```
After:
```
(test-remove-prints)~/src/nomad/nomad/structs$ go test
PASS
ok      github.com/hashicorp/nomad/nomad/structs        0.057s
```
> test: remove spurious print statements

- .changelog/20518.txt
- command/setup_consul.go
- command/setup_vault.go
- website/content/docs/commands/setup/consul.mdx
- website/content/docs/commands/setup/vault.mdx
When setting up auth methods for Consul and Vault in production environments, we can typically assume that the CA certificate for the JWKS endpoint will be in the host certificate store (as part of the usual configuration management cluster admins needs to do). But for quick demos with `-dev` agents, this won't be the case.
Add a `-jwks-ca-file` parameter to the setup commands so that we can use this tool to quickly setup WI with `-dev` agents running TLS.
> cli: add `-jwks-ca-file` to Vault/Consul setup commands

- .changelog/20528.txt
- .release/linux/package/usr/lib/systemd/system/nomad.service
- command/agent/command.go
- command/agent/sdnotify_default.go
- command/agent/sdnotify_linux.go
Nomad agents expect to receive `SIGHUP` to reload their configuration. The signal handler for this is installed fairly late in agent startup, after the client or server components are up and running. This means that configuration management tools can potentially reload the configuration before the agent can handle it, causing the agent to crash.
We don't want to allow configuration reload during client or server component startup, because it would significantly complicate initialization. Instead, we'll implement the systemd notify protocol. This causes systemd to block sending configuration reload signals until the agent is actually ready. Users can still bypass this by sending signals directly.
Note that there are several Go libraries that implement the sdnotify protocol, but most are …
> agent: add support for sdnotify protocol

- ui/app/components/variable-form.js
- ui/app/modifiers/code-mirror.js
- ui/ember-cli-build.js
- ui/package.json
- ui/yarn.lock
This removes the JSON Linting gutter highlight capabilities originally added in https://github.com/hashicorp/nomad/pull/13461
The main reason for this removal is the inclusion of a nested Underscore dependency: https://github.com/hashicorp/nomad/security/dependabot/110
However, our dependency (a grandparent of the insecure underscore version) has not been updated in quite some time and appears to be unmaintained.
As such, I've given consideration to whether this feature is worth forking, pinning, or abandoning. Per https://github.com/zaach/jsonlint/pull/120 a change has been merged to `master` in `jsonlint`, but no release on `npm` has been made. As such, I've opted to remove the feature for the same reasons [other projects](https://github.com/mapbox/mapbox-gl-draw/issues/1049) have done …
> [ui] Remove json linting while editing variables

- ui/app/components/global-header.js
- ui/app/components/profile-navbar-item.hbs
- ui/app/controllers/settings.js
- ui/app/controllers/settings/tokens.js
- ui/app/controllers/settings/user-settings.js
- ui/app/router.js
- ui/app/routes/settings/tokens.js
- ui/app/styles/core/navbar.scss
- ui/app/templates/components/global-header.hbs
- ui/app/templates/settings.hbs
- ui/app/templates/settings/tokens.hbs
- ui/app/templates/settings/user-settings.hbs
- ui/tests/acceptance/token-test.js
This all stemmed from wanting a dedicated place to set "Do/Don't jostle me on the jobs index page". This PR adds a user settings page under "settings", which was previously used just to sign in / view profile.
As such, a global-nav item is always shown (regardless of whether ACLs are disabled) and is either:
- an icon with a link to the sign-in page (if ACLs are enabled and you're not signed in)
- an icon with a link to the user settings page (if ACLs are disabled)
- a dropdown that links to the sign-in page (if ACLs are enabled and you're signed in)
These settings are localStorage-specific (and noted as such on the user settings page)
I imagine we'll be adding more settings from around the app here soon
> [ui] Splits Settings into 2 sections, sign-in/profile and user settings

- .changelog/20539.txt
- ui/app/components/profile-navbar-item.hbs
Displays `token.name` in the dropdown button for ease of identification for screenshots, etc.
Resolves #20538
> [ui] Adds the token name to the Profile link in the top nav

- .changelog/20543.txt
- client/client.go
> client: fix unallocated CPU metric when reserved cpu is set.

- website/content/docs/other-specifications/acl-policy.mdx
The ACL docs have a section explaining that some parts of the UI need slightly wider read permissions than expected. These docs should include that you need `plugin:read` to look at CSI volume pages in the UI.
Fixes: https://github.com/hashicorp/nomad/issues/18527
> docs: note that plugin policy is required in the UI for CSI volumes

- website/content/api-docs/plugins.mdx
CSI plugins are not namespaced, and there's no "list plugin" ACL. Instead, listing and reading plugins require the `plugin:read` ACL.
Noticed this while working on https://github.com/hashicorp/nomad/pull/20551
> docs: correct ACL requirements for CSI plugins

- .changelog/20532.txt
- client/allocrunner/csi_hook.go
- client/allocrunner/csi_hook_test.go
- client/allocrunner/state/state.go
- client/csi_endpoint.go
- client/pluginmanager/csimanager/interface.go
- client/pluginmanager/csimanager/testing.go
- client/pluginmanager/csimanager/usage_tracker.go
- client/pluginmanager/csimanager/usage_tracker_test.go
- client/pluginmanager/csimanager/volume.go
- client/pluginmanager/csimanager/volume_test.go
- client/structs/csi.go
- nomad/csi_endpoint.go
- testutil/mock_calls.go
CSI volumes are namespaced. But the client does not include the namespace in the staging mount path. This causes CSI volumes with the same volume ID but different namespace to collide if they happen to be placed on the same host. The per-allocation paths don't need to be namespaced, because an allocation can only mount volumes from its job's own namespace.
Fixes: https://github.com/hashicorp/nomad/issues/18741
See https://github.com/hashicorp/nomad/issues/18741#issuecomment-2102752320 for my notes on upgrade testing.
> CSI: include volume namespace in staging path

- website/content/docs/commands/alloc/exec.mdx
- website/content/docs/concepts/cpu.mdx
We have some broken markdown code block fences which broke pages once a new syntax highlighter got deployed.
> docs: fix broken markdown

- .changelog/20551.txt
- nomad/csi_endpoint.go
- nomad/csi_endpoint_test.go
The `nomad plugin status :plugin_id` command lists allocations that implement the plugin being queried. This list is filtered by the `-namespace` flag as usual. Cluster admins will likely deploy plugins to a single namespace, but for convenience they may want to have the wildcard namespace set in their command environment.
Add support for handling the wildcard namespace to the CSI plugin RPC handler.
Fixes: https://github.com/hashicorp/nomad/issues/20537
> CSI: add support for wildcard namespaces on `plugin status`

- client/allocdir/task_dir.go
In the Unveil filesystem isolation mode we were mounting the shared
alloc dir with the UID/GID of the user of the task dir being mounted
and 0710 filesystem permissions. This was causing the actual shared 
alloc dir to become inaccessible to other tasks in the allocation
(a race where the last mounter wins). Instead mount the shared alloc 
dir as nobodywith 0777 filesystem permissions.
> client: mount shared alloc dir as nobody

- .changelog/20590.txt
- nomad/core_sched_test.go
- nomad/node_endpoint.go
- nomad/node_endpoint_test.go
- nomad/state/state_store.go
- nomad/state/state_store_service_registration.go
This changeset fixes three potential data integrity issues between allocations and their Nomad native service registrations.
* When a node is marked down because it missed heartbeats, we remove Vault and Consul tokens (for the pre-Workload Identity workflows) after we've written the node update to Raft. This is unavoidably non-transactional because the Consul and Vault servers aren't in the same Raft cluster as Nomad itself. But we've unnecessarily mirrored this same behavior to deregister Nomad services. This makes it possible for the leader to successfully write the node update to Raft without removing services.
To address this, move the delete into the same Raft transaction. One minor caveat with this approach is the upgrade path: if the leader is upgraded first and a node is marked …
> services: fix data integrity errors for Nomad native services

- .changelog/20553.txt
- api/api.go
- client/lib/numalib/detect_linux.go
- command/agent/http.go
- command/agent/http_test.go
- helper/flags/autopilot_flags.go
- helper/testlog/testlog.go
- helper/users/dynamic/users.go
Resolves `Incorrect conversion between integer types` alerts to catch potential overflows.
> bug: resolve type conversion alerts

- ui/app/adapters/job.js
- ui/app/styles/components/empty-message.scss
Does 2 things on the newly reworked jobs index page:
1. Makes the [default helios empty state component](https://helios.hashicorp.design/components/application-state?tab=code) look more Nomad-ish (grey bg, widened)
2. Makes the minimum ?index on the /statuses request 1, instead of 0, so it successfully blocks instead of polls.
> [ui] Jobs Index page min-index and default empty-state styles

- .changelog/20522.txt
- nomad/structs/structs.go
- nomad/structs/structs_test.go
> structs: Fix job canonicalization for array type fields

- .github/actionlint.yml
- .github/workflows/build.yml
- .github/workflows/test-core.yaml
👋 Greetings!
To align with Github’s removal of custom labels on larger runners, this PR is removing extra custom labels defined in your Github Actions. Moving forward, only one label (the github runner name) will be needed to ensure the appropriate larger runner is used for your GHA job.
> migrate GHA workflows to using single runner labels

- .changelog/20596.txt
- client/serviceregistration/nsd/nsd.go
- client/serviceregistration/nsd/nsd_test.go
When the allocation is stopped, we deregister the service in the alloc runner's `PreKill` hook. This ensures we delete the service registration and wait for the shutdown delay before shutting down the tasks, so that workloads can drain their connections. However, the call to remove the workload only logs errors and never retries them.
Add a short retry loop to the `RemoveWorkload` method for Nomad services, so that transient errors give us an extra opportunity to deregister the service before the tasks are stopped, before we need to fall back to the data integrity improvements implemented in #20590.
Ref: https://github.com/hashicorp/nomad/issues/16616
> services: retry failed Nomad service deregistrations from client

- nomad/structs/structs_test.go
my mistake, I didn't notice that the backported tests involved Identities and Actions.
> fix backport of 898dddc5dbfb204d08b6557414e0a11ff671d47c

- .changelog/20550.txt
- client/pluginmanager/csimanager/volume.go
- client/pluginmanager/csimanager/volume_test.go
The CSI hook for each allocation that claims a volume runs concurrently. If a call to `MountVolume` happens at the same time as a call to `UnmountVolume` for the same volume, it's possible for the second alloc to detect the volume has already been staged, then for the original alloc to unpublish and unstage it, only for the second alloc to then attempt to publish a volume that's been unstaged.
The usage tracker on the volume manager was intended to prevent this behavior but the call to claim the volume was made only after staging and publishing was complete. Move the call to claim the volume for the usage tracker to the top of the `MountVolume` workflow to prevent it from being unstaged until all consuming allocations have called `UnmountVolume`.
Fixes: …
> CSI: track node claim before staging to prevent interleaved unstage

- .changelog/20555.txt
- nomad/core_sched_test.go
- nomad/csi_endpoint.go
- nomad/csi_endpoint_test.go
- nomad/state/state_store.go
- nomad/state/state_store_test.go
- nomad/structs/errors.go
- nomad/structs/structs.go
When a job that implements a plugin is updated to have a new plugin ID, the old version of the plugin is never deleted. We want to delay deleting plugins until garbage collection to avoid race conditions between a plugin being registered and its allocations being marked healthy.
Add logic to the state store's `DeleteCSIPlugin` method (used only by GC) to check whether any of the jobs associated with the plugin have no allocations and either have been purged or have been updated to no longer implement that plugin ID.
This changeset also updates the CSI plugin lifecycle tests in the state store to use `shoenig/test` over `testify`, and removes a spurious error log that was happening on every periodic plugin GC attempt.
Fixes: https://github.com/hashicorp/nomad/issues/20225
> CSI: allow plugin GC to detect jobs with updated plugin IDs

- scheduler/generic_sched_test.go
While working on #20462, I discovered that some of the scheduler tests for disconnected clients making long blocking queries. The tests used `testutil.WaitForResult` to wait for an evaluation to be written to the state store. The evaluation was never written, but the tests were not correctly returning an error for an empty query. This resulted in the tests blocking for 5s and then continuing anyways.
In practice, the evaluation is never written to the state store as part of the test harness `Process` method, so this test assertion was meaningless. Remove the broken assertion from the two top-level tests that used it, and upgrade these tests to use `shoenig/test` in the process. This will save us ~50s per test run (for just the `test-groups/quick` group)
> tests: update disconnected client scheduler tests to avoid blocking

- .github/workflows/backport.yml
- .release/versions.hcl
Configuration changes to use backport assistant with LTS support. These include:
- adding a manifest file for active releases
- adding configuration to send backport to ENT repo
New BPA labels created under the new BPA changes/LTS policy: 
- `backport/ent/1.5.x+ent`
- `backport/ent/1.6.x+ent`
- `backport/ent/1.7.x+ent`
- `backport/ent/1.8.x+ent`
> SMRE/BPA Onboarding LTS

- .changelog/20611.txt
- nomad/job_endpoint_hook_connect.go
- nomad/job_endpoint_hook_connect_test.go
Enable use of Consul Connect Gateways (ingresss/terminating/mesh) with podman task driver.
task driver for Connect-enabled tasks for sidecar services which used podman if any other task in the same task group was using podman or fell back to docker otherwise.
That PR did not consider consul connect gateways, which remained hardcoded to using docker task driver always.
This change applies the same heuristic also to gateway tasks, enabling use of podman.
Limitations: The heuristic only works where the task group containing the gateway also contains a podman task. Therefore it does not work for the ingress example in the docs
(https://developer.hashicorp.com/nomad/docs/job-specification/gateway#ingress-gateway) which uses connect native and requires the gateway be in a separate task.
I've …
> Permit Consul Connect Gateways to be used with podman

- .changelog/20619.txt
- drivers/shared/executor/executor_basic.go
- drivers/shared/executor/executor_linux.go
- drivers/shared/executor/executor_universal_linux.go
- drivers/shared/executor/procstats/list_default.go
- drivers/shared/executor/procstats/list_windows.go
- drivers/shared/executor/procstats/list_windows_test.go
- drivers/shared/executor/procstats/procstats.go
This PR overhauls the way processes are scanned on Windows for the exec driver(s).
A regression was introduced in Nomad 1.7 where we would invoke an [expensive syscall](https://github.com/hashicorp/nomad/blob/release/1.7.0/drivers/shared/executor/procstats/list_default.go#L40) for every descendant of a process to build a tree of the processes associated with a task. Instead, we restore the behavior of scanning the process table once and rebuild the process tree manually.
Fixes https://github.com/hashicorp/nomad/issues/20042
> windows: fix inefficient gathering of task processes

- nomad/job_endpoint_hooks.go
- nomad/job_endpoint_hooks_test.go
The new transparent proxy feature already has an implicity constraint on the presence of the CNI plugin. But if the CNI plugin is installed on an older version of Nomad, this isn't sufficient to protect against placing tproxy workloads on clients that can't support it. Add a Nomad version constraint as well.
Fixes: https://github.com/hashicorp/nomad/issues/20614
> tproxy: add implicit constraint on client version

- website/content/docs/integrations/vault/acl.mdx
(Certificate management is the worst.)
Had some confusion from a user thinking they _had_ to use a lb/proxy to configure the Vault integration. I noticed our docs about mTLS/verify_client lacked mentioning that Vault needs to trust Nomad's CA, so I added some words to hopefully make that more clear? The words do not seem like good words so if you have gooder words please suggest them.
> doc: specify ca cert needs to be shared

- scripts/docker-entrypoint.sh
During this update https://github.com/hashicorp/nomad/pull/16247, the new URL points to a page that doesn't exist and shows the 404 page.
Whenever I ran the Docker image `hashicorp/nomad`, it showed logs like this, but the URL was invalid.
```
...
nomad-server-3  | ===============================================================================================
nomad-server-3  | !! Running Nomad clients inside Docker containers is not supported.                          !!
nomad-server-3  | !! Refer to https://developer.hashicorp.com/nomad/s/nomad-in-docker for more information.    !!
...
```
I guess, the URL should be [this](https://developer.hashicorp.com/nomad/docs/install/production/requirements#running-nomad-in-docker).
> build: fix broken link to Nomad in docker documentation

- client/allocrunner/alloc_runner.go
- command/agent/agent.go
This PR adjusts the default location of `-alloc-mounts-dir` path to be a
sibling of the `-data-dir` path rather than a child. This is because on a
production-hardened systems the data dir is supposed to be `chmod 0700`
owned by `root` - preventing the `exec2` task driver (and others using
unveil file system isolation features) from working properly.
For reference the directory structure from `-data-dir` now looks like this
after running an example job. Under the `alloc_mounts` directory, task
specific directories are mode `0710` and owned by the task user (which
may be a dynamic user UID/GID). The `data` directory remains `0700` and
owned by root.
```
➜ sudo tree -p -d -u /tmp/mynomad
[drwxrwxr-x shoenig ]  /tmp/mynomad
├── [drwx--x--x root    ]  alloc_mounts
│   └── [drwx--x--- 80552   ] …
```
> client: alloc_mounts directory must not be child of data directory

- ui/app/controllers/jobs/index.js
- ui/app/routes/jobs/index.js
- ui/app/templates/jobs/index.hbs
- ui/mirage/config.js
- ui/tests/acceptance/jobs-list-test.js
In the jobs index search box, we interpret non-expression-looking strings as filter expressions of `Name contains ________` type.
This is neat and probably how users expect searching for jobs to work (just type in a job name, that job shows up) but we are being over-eager with our solution, notably by prepending "Name contains" in the search box before your cursor. This is particularly troublesome if you were doing something like typing "Type contains sys" but stopped for a moment while thinking about what the operator should be. You'd end up with "Name contains Type" before you know it.
Instead, we make that search / apply the filter expression in the URL and API call, but keep the search box itself untouched.
Secondly, we now give users suggestions for when they attempt a filter …
> [ui] Better UX with filter expressions in the jobs index search box

- .changelog/22229.txt
- nomad/job_endpoint_hooks.go
- nomad/job_endpoint_hooks_test.go
- nomad/job_endpoint_test.go
- nomad/mock/job.go
- nomad/structs/structs.go
Fixes a regression in Nomad 1.7 which caused task-level services no longer having created implicit Consul constraints. 
Resolves #22190
> job endpoint: fix implicit constraint mutation for task-level services

- e2e/terraform/packer/README.md
The process by which we tag AMIs with the commit SHA of the Packer directory isn't documented in this repository, which makes it easy to accidentally build an AMI that will break nightly E2E.
> E2E: document how the AMIs are tagged and how those tags are used

- website/content/docs/install/index.mdx
Latest CNI reference plugin versions are now 1.5.0: https://github.com/containernetworking/plugins/releases/tag/v1.5.0
> docs: Update CNI Plugin versions

- .changelog/22228.txt
- command/agent/consul/config_entries_testing.go
- nomad/consul.go
- nomad/consul_test.go
- nomad/job_endpoint.go
- nomad/structs/connect.go
When we write Connect gateway configuation entries from the server, we're not passing in the intended partition. This means we're using the server's own partition to submit the configuration entries and this may not match. Note this requires the Nomad server's token has permission to that partition.
Also, move the config entry write after we check Sentinel policies. This allows us to return early if we hit a Sentinel error without making Consul RPCs first.
Ref: https://hashicorp.atlassian.net/browse/NET-9529
> consul: set partition for gateway config entries

- .changelog/22226.txt
- client/allocrunner/alloc_runner_hooks.go
- client/allocrunner/consul_hook.go
- client/consul/consul.go
When logging into a JWT auth method, we need to explicitly supply the Consul admin partition if the local Consul agent is in a partition. We can't derive this from agent configuration because the Consul agent's configuration is canonical, so instead we get the partition from the fingerprint (if available). This changeset updates the Consul client constructor so that we close over the partition from the fingerprint.
Ref: https://hashicorp.atlassian.net/browse/NET-9451
> consul: include admin partition in JWT login requests

- .changelog/22419.txt
- drivers/docker/config.go
- drivers/docker/config_test.go
- drivers/docker/driver.go
- website/content/docs/drivers/docker.mdx
This allows users to set a custom value of attempts that will be made to purge an existing (not running) container if one is found during task creation. See https://github.com/hashicorp/nomad/issues/22218 for more context.
> docker: new container_exists_attempts configuration field

- e2e/exec2/doc.go
- e2e/exec2/exec2_test.go
- e2e/exec2/input/countdash.hcl
- e2e/exec2/input/env.hcl
- e2e/exec2/input/http.hcl
- e2e/exec2/input/http_curl.hcl
- e2e/exec2/input/secrets.hcl
- e2e/terraform/Makefile
- e2e/terraform/etc/nomad.d/client-linux.hcl
- e2e/terraform/packer/ubuntu-jammy-amd64/setup.sh
A first pass at getting some e2e tests setup on the Nomad side for the exec2 task driver. It includes running the countash example with a custom envoy task for the sidecar proxy, which is a pretty good test of the driver functionality.
I tweaked the `e2e/Makefile` to include the Consul license file (you need to have `CONSUL_LICENSE_PATH` set), which is basically a required parameter now.
Also discovered https://github.com/hashicorp/nomad-driver-exec2/issues/29 which I will get around to fixing next.
> e2e: add tests for exec2 task driver

- ui/yarn.lock
Recently, we've made a few changes that affected our JS dependencies heavily (such as the [removal of storybook](https://github.com/hashicorp/nomad/pull/22232) and [Helios/PowerSelect upgrades](https://github.com/hashicorp/nomad/pull/22328))
On the back of these changes, it seemed worthwhile to update our UI lockfile and run a fresh `make dev-ui` and commit the generated assets.
> [ui] Lockfile and bindata_assetfs recompiled on latest main

- ui/app/controllers/allocations/allocation/index.js
On a page like this one...
You can both click on, and also use `Shift+01`, to open the task shown.
If you click the link (the underlined word itself that says "task") this is a simple href and your browser handles it.
On the other hand, if you click on the rest of the row, or type `Shift+01`, a function runs that uses Ember's router service to move you to the right spot.
Knowing what that spot is depends on knowing both the task and the allocation (since the eventual URL is `/allocations/:ALLOC_ID/:TASK_ID`)
This differs from most of the other keyboard shortcuts throughout the app in that there are multiple params passed into the router function (normally you just say "go to a job with :JOB_ID" etc.)
Noticed that this stopped working today, and dug into why. Here are the param patterns of …
> [ui] Fix keynav when selecting a task from an allocation route

- ui/tests/acceptance/job-detail-test.js
Visual diff tests with Percy are generated at test-time, which means that our components show time-sensitive things (like "last updated at" times for allocations) will trigger a "something changed" warning. This hides those time-sensitive things for a recently-added test.
> [ui] Omit the current-time-displaying components during our visual diff tests

- .changelog/22312.txt
- nomad/job_endpoint_hook_connect.go
When a consul connect sidecar service is defined with multiple local_bind_socket_path upstreams, validation fails due to duplicate socket address bindings on `:0` being detected:
```
Error submitting job: Unexpected response code: 500 (1 error occurred:
* Consul Connect services "caddy-https" and "caddy-https" in group "caddy" using same address for upstreams (:0))
```
This patch validates `local_bind_socket_path` upstreams separately from `local_bind_address` sockets.
> Consul Connect: Fix validation with multiple local_bind_socket_paths

- plugins/drivers/testutils/testing.go
This PR fixes the value of NOMAD_SECRETS_DIR to be the alloc_mounts
secrets directory instead of the real secrets directory, which is protected
by root 0700 even when running tests.
Needed for https://github.com/hashicorp/nomad-driver-exec2/issues/29
> testing: fix the value of NOMAD_SECRETS_DIR in test harness

- .github/actions/vault-secrets/action.yml
Removes a dependency on a node 16 action, which are EOLed.
> [actions] Update hashicorp/vault-action to v3.0.0

- scheduler/stack_test.go
Some of our scheduler tests use the `AllocName` function from the structs package incorrectly. This function should always receive the `Job.ID` and not the `Job.Name`. Fix this to prevent future bugs from copy-pasting usage around.
> scheduler: stack test should use job.ID and not job.Name

- jobspec2/parse_test.go
1. Add test case for constraint alternatives from #18122
1. Followup to #22439
> jobspec2: add test for parsing `constraint {}` alternatives

- website/content/docs/job-specification/spread.mdx
Update the documentation for the `spread` block:
* Make it clear that the default behavior within a given job when the `spread` block is omitted is to spread out allocs among feasible nodes.
* Describe the difference between the `spread` block and `spread` scheduler algorithm.
* Add warnings about the performance impact of using `spread` and how to mitigate it.
Preview: https://nomad-fic95l7zo-hashicorp.vercel.app/nomad/docs/job-specification/spread
> docs: describe omitted `spread` behavior and perf impact

- .github/workflows/build.yml
- GNUmakefile
- build_linux_arm.go
- website/content/docs/release-notes/nomad/v1_8_x.mdx
We no longer intend to release 32-bit builds for any platform. We'd previously removed the builds for i386 on both Linux and Windows, but never got around to removing the ARM builds. Add a note about this deprecation in the release notes for 1.8.x.
Closes: https://github.com/hashicorp/nomad-enterprise/issues/1053
> build: remove 32-bit ARM builds

- website/content/docs/release-notes/nomad/v1_8_x.mdx
Backport of docs from https://github.com/hashicorp/nomad/pull/23189 so we can have the docs in the 1.8.x branch without the build changes themselves, which we only want to land in 1.9.0.
> docs: 32-bit build deprecation

- drivers/docker/driver_unix_test.go
In https://github.com/hashicorp/nomad/pull/17401 we added test helpers that would allow `docker` driver tests to pull from a mirror of the Docker Hub registry. Extend the use of this helper to tests that recently hit rate-limiting.
Fixes: https://github.com/hashicorp/nomad/issues/23174
> testing: pull Docker images from mirror

- .changelog/23237.txt
- client/allocdir/task_dir.go
This PR fixes a bug where Nomad client would leave behind an empty directory
created on behalf of tasks making use of the unveil filesystem isolation
mode (i.e. using exec2 task driver). Once unmounting is complete, we should
remember to also delete the directory.
Fixes #22433
> client: cleanup empty task directory when using unveil filesystem isolation

- ui/mirage/scenarios/default.js
Does an early check to see if the passed `?mirage-scenario=${VALUE}` value is found within our const list of scenarios. If not, provide a console error and proceed with the default (smallCluster) scenario.
This:
1. shortens the distance between parsing the URL and checking if it's valid (happens in same function now to prevent possibly adding an unsafe method in the middle later)
2. lets mirage proceed (we `console.error` + set to default instead of `throw`ing)
A (small) fear here is that we might do something like typo our queryParam in the URL and neglect to check our console errors, and proceed without noticing that our intended scenario is actually running as `smallCluster`. I think that's a worthwhile tradeoff.
Resolves #23260
> [ui] Do an early check for mirage-scenario URL param when in mirage mode

- website/content/docs/other-specifications/acl-policy.mdx
> docs: update ACL policy example spec to remove plugin write cap.

- client/pluginmanager/drivermanager/testing.go
The `testing.go` test helpers file for the driver manager initializes the NUMA scan as a package-global variable. This causes it to be pulled in even in production builds, so even running commands like `nomad version` will cause the NUMA scan to happen. Move the scan into the test helper setup.
I discovered this while debugging https://github.com/hashicorp/nomad/pull/23284 but this suggests there may be other cases where our `testing.go` test helper files are dragging wasteful startup behaviors into production builds.
---
Before:
```
$ objdump -t $(which nomad) | grep topology
00000000011096e0 l     F .text  00000000000003d0              github.com/hashicorp/nomad/nomad/structs.topologyFromLegacyGeneric
0000000001109e60 l     F .text  00000000000000a5 …
```
> test: move NUMA platform scan out of testing global

- e2e/consulcompat/run_ce_test.go
- e2e/consulcompat/shared_download_test.go
- e2e/vaultcompat/run_ce_test.go
Update the Consul/Vault build downloader functions so that we include the current prerelease build (if any) in our E2E compatibility testing we do on each PR. This will automatically cycle out when the GA build is released, because that build is "higher" in the sorted set.
> e2e: add prerelease builds to Consul/Vault compatibility tests

- client/fingerprint/cpu.go
- client/lib/idset/idset.go
- client/lib/numalib/detect_darwin.go
- client/lib/numalib/detect_generic.go
- client/lib/numalib/detect_linux.go
- client/lib/numalib/detect_linux_test.go
- client/lib/numalib/topology.go
- nomad/job_endpoint_test.go
- nomad/structs/cpucompat_generic.go
- nomad/structs/cpucompat_linux.go
- nomad/structs/cpucompat_linux_test.go
- nomad/structs/extensions.go
- nomad/structs/funcs_test.go
- nomad/structs/structs_test.go
- nomad/structs/testing.go
- plugins/base/base.go
- plugins/base/base_test.go
- scheduler/context_test.go
- scheduler/rank_test.go
The NUMA topology struct field `NodeIDs` is a `idset.Set`, which has no public members. As a result, this field is never serialized via msgpack and persisted in state. When `numa.affinity = "prefer"`, the scheduler dereferences this nil field and panics the scheduler worker.
Ideally we would fix this by adding a msgpack serialization extension, but because the field already exists and is just always empty, this breaks RPC wire compatibility across upgrades. Instead, create a new field that's populated at the same time we populate the more useful `idset.Set`, and repopulate the set on demand.
Fixes: https://hashicorp.atlassian.net/browse/NET-9924
Ref: https://github.com/hashicorp/nomad-enterprise/pull/1527
> numa: fix scheduler panic due to topology serialization bug

- .github/workflows/jira-sync.yml
This is a GHA workflow to allow labeling individual GitHub issues to synchronize into Jira.
> Adding GHA workflow to sync with Jira

- .changelog/23297.txt
- drivers/docker/config.go
- drivers/docker/config_test.go
- drivers/docker/driver.go
- website/content/docs/drivers/docker.mdx
See https://github.com/hashicorp/nomad/pull/23259 and https://github.com/hashicorp/nomad/issues/11087 for context.
> docker: oom_score_adj support

- drivers/docker/driver_unix_test.go
fixes:
```
driver_unix_test.go:731: 
Error Trace:	/home/runner/work/nomad/nomad/drivers/docker/driver_unix_test.go:731
Error:      	Received unexpected error:
rpc error: code = FailedPrecondition desc = Failed to pull `gcr.io/google_containers/pause:0.8.0`: [DEPRECATION NOTICE] Docker Image Format v1 and Docker Image manifest version 2, schema 1 support is disabled by default and will be removed in an upcoming release. Suggest the author of gcr.io/google_containers/pause:0.8.0 to upgrade the image to the OCI Format or Docker Image manifest v2, schema 2. More information at https://docs.docker.com/go/deprecated-image-specs/
```
> docker: update image in TestDockerDriver_Start_Image_HTTPS

- .semgrep/rpc_endpoint.yml
- acl/acl.go
- nomad/alloc_endpoint.go
- nomad/csi_endpoint.go
- nomad/csi_endpoint_test.go
- nomad/node_endpoint.go
- nomad/service_registration_endpoint.go
Nomad client agents run as privileged processes and require access to much of the cluster state, secrets, etc. to operate. But we can improve upon this by tightening up the virtual policy that use for RPC requests authenticated by the node secret ID. This changeset removes the `node:read`, `plugin:read`, and `plugin:list` policy, as well as namespace operations. In return, we add a `AllowClientOp` check to the RPCs the client uses that would otherwise need those policies.
Where possible, the update RPCs have also been changed to match on node ID so that a client can only make the RPC that impacts itself. In future work, we may be able to downscope further by adding node pool filtering to `AllowClientOp`.
Ref: https://github.com/hashicorp/nomad-enterprise/issues/1528
Ref: …
> acls: reduce permissions of client agent virtual policy

- .changelog/23290.txt
- ui/app/components/job-page/parts/stats-box.js
- ui/app/models/node-driver.js
- ui/app/models/structured-attributes.js
- ui/app/styles/core/table.scss
- ui/app/templates/clients/client/index.hbs
- ui/app/templates/components/attributes-section.hbs
- ui/app/templates/components/job-page/parts/meta.hbs
- ui/app/templates/components/job-page/parts/stats-box.hbs
- ui/app/templates/components/job-page/parts/title.hbs
- ui/app/utils/path-tree.js
- ui/package.json
- ui/tests/integration/components/attributes-table-test.js
- ui/yarn.lock
This extends and reuses PathTree logic originally written for Variables in https://github.com/hashicorp/nomad/pull/13202
This PR specifically fixes a bug where a metadata k/v item wouldn't show up in the UI if its full key was the prefix of a nested child key.
For example, this metadata:
```
{
'phil.hair': 'yes',
'phil.hair.colour': 'black',
'phil.hair.length': 'short'
};
```
would produce the following:
and now produces:
> [ui] Rework of node/job attributes/meta using PathTree

- .changelog/22518.txt
- drivers/shared/executor/executor_linux.go
- drivers/shared/executor/executor_linux_test.go
Using a device inside a container requires two things:
1. binding the device
2. allowing the device in cgroup rules
The nomad linux executor sets up cgroups only for default devices and does not correctly set up other devices specified in configuration.
This change sets up cgroup rules for all devices needed by the container. An important non-default device that is relevant here is /dev/fuse.
I don't believe this has worked at any point in history; a backport to 1.7 would be appreciated if that's possible.
> [bug] Fix cgroup setup for non-default devices

- .changelog/23306.txt
- ui/app/components/job-status/panel/steady.hbs
- ui/app/components/job-status/panel/steady.js
- ui/tests/acceptance/job-status-panel-test.js
While most of our job status panel allocation numbers use allocations live as they're updated from the /allocations endpoint for a given job, one holdout remained: the the "X Allocations Running" number came from the `job-summary`, which tabulates at a slightly different time than allocations do (and is sometimes susceptible to inaccuracy)
This changes the number in steady-state jobs to be what we actually see among currently running allocations from the /allocations endpoint. This doesn't discriminate between new-version and old-version allocations, only returning the number currently running. 
Resolves #20627
> [ui] Remove simulacral allocation stat in favor of live-updating one

- .changelog/23329.txt
- nomad/structs/task_sched.go
- nomad/structs/task_sched_test.go
Fix erroneous "end cannot be sooner than start" error condition on the last day of the month.
By building "`next end` from `from`" instead of "`next end` from `next start`" (we actually use the latter for the schedule), on the last day of any given month, the next `start.Day()` would be `1` (the first of the next month), which is less than the current `end.Day()` -- whatever the last day of the month is, `28-31` -- so it would mistakenly think the user provided improper values.  (I'm sorry, this is really hard to put into plain language... hopefully the code makes sense.)
I happened to be starting some e2e testing (not present in this PR) at the end of May and bumped into this, so formalize with a unit test case, and also include Fuzz testing to try and catch other possible unforeseen …
> task schedule: fix end-of-month validation bug

- website/content/docs/install/index.mdx
- website/content/docs/integrations/consul/service-mesh.mdx
- website/content/docs/release-notes/nomad/v1_8_x.mdx
Install the `consul-cni` plugin via apt or yum.
> docs: install `consul-cni` manually or via linux packaging

- .changelog/23328.txt
- nomad/job_endpoint_statuses.go
- nomad/structs/job.go
- ui/app/components/job-status/panel/steady.js
- ui/app/models/job.js
- ui/app/serializers/job.js
- ui/mirage/config.js
- ui/mirage/factories/job.js
- ui/tests/acceptance/jobs-list-test.js
Our recent changes to how we label jobs in the UI considers any job "failed" if none of its expected allocations are running or pending, and it's not in active deployment.
This is coincidentally both true for jobs that failed because a user clicked the "stop" button, and also for jobs that failed because of the universe conspiring against us generally.
Luckily, jobs already had a nice `Stop` boolean to indicate the manual, deliberate stopping of a job (until it gets garbage collected, and provided it didn't have a "purge" flag passed in).
This PR observes that boolean and displays a new "Stopped" status in the UI in two places:
resolves #22101
> [ui] Add "stopped" as a valid status on jobs index/job detail

- .changelog/23365.txt
- ui/app/services/keyboard.js
- ui/tests/acceptance/keyboard-test.js
Resolves #23361 
- Buy a macbook (or pretend)
- Hold down shift, to see hints. Release and they're gone!
- Hold down cmd+shift+4 to take a screenshot
- Note that in holding the command key, the shift key no longer triggers the display of keyboard hints.
> [ui] Dont show keyboard hints when a user is trying to take a screenshot

- .changelog/23366.txt
- ui/app/templates/administration/namespaces/acl-namespace.hbs
- ui/app/templates/administration/namespaces/new.hbs
- ui/app/templates/administration/policies/new.hbs
- ui/app/templates/administration/policies/policy.hbs
- ui/app/templates/administration/roles/new.hbs
- ui/app/templates/administration/roles/role.hbs
- ui/app/templates/administration/sentinel-policies/policy.hbs
- ui/app/templates/administration/tokens/new.hbs
- ui/app/templates/administration/tokens/token.hbs
Page headers in the Admin (formerly ACL) section of the UI get the [Helios](https://helios.hashicorp.design/) treatment. This being one of the newer sections in the UI, the page title convention was copied over as new sub-sections were added. This standardizes them.
> [ui] Helios page headers added to the administration section

- .changelog/23377.txt
- api/allocations.go
Without this, the method just doesn't work. :upside_down_face: 
For context, the "pause" state is the state of a task that has a [schedule{} block](https://developer.hashicorp.com/nomad/docs/job-specification/schedule) on it (enterprise feature).
> api: use the task in Allocations.GetPauseState
