hashicorp/nomad

ui/app/machines/evaluations.js, ui/app/serializers/task-event.js
Getting pretty tired of these party-poopers:
Note: a few of the other deprecation warnings are such that an upgrade to Ember 4+ is warranted if we want them to go away badly enough. This gets rid of the noisiest one (without having to mess with our deprecation-workflow.js file)
=> [ui] Squashing Ember deprecations

website/content/docs/commands/alloc/exec.mdx
=> docs: fix typo in alloc exec CLI docs page.

e2e/task_schedule/input/schedule.nomad.hcl, e2e/task_schedule/task_schedule_test.go
What it says on the tin -- testing the task [`schedule{}`](https://developer.hashicorp.com/nomad/docs/job-specification/schedule) block (enterprise feature).
I did not contrive a way to restart the client agent, to try to ensure that schedules continue uninterrupted in that case, but if we want to do that, I think it'd be wonky enough to justify its own PR.  But I'm open to other suggestions for basic test cases!
Example run:
```
=== RUN   TestTaskSchedule
=== RUN   TestTaskSchedule/in_schedule
task_schedule_test.go:45: 2024-06-18T18:37:33Z job options: start="36 18 * * * *" end="38 18"
task_schedule_test.go:45: 2024-06-18T18:37:34Z ran job "test_task_schedule-823"
task_schedule_test.go:48: 2024-06-18T18:37:34Z waiting up to 5s: task should start
task_schedule_test.go:51: …
```
=> e2e: add test for task schedule{}

.changelog/23386.txt, nomad/structs/funcs.go, nomad/structs/funcs_test.go, nomad/structs/structs.go
Fixes a bug in the [`nodeResources.Comparable` method](https://github.com/hashicorp/nomad/blob/a0a717342775bce914aeb7ef052e59d3cb6dc41c/nomad/structs/structs.go#L3194), where CPU resources were accidentally offset with reserved resources, whereas functions that use this field expect total CPU resources. 
Fixes #23371 and #23314
=> scheduler: fix a bug where we subtract reserved node resources twice

CHANGELOG.md
The changelog is slightly misleading in that recent Enterprise-only backports following our LTS release have titles that don't call out they're for Enterprise only. Updating the title brings us in line with what Consul has done.
Ref: https://github.com/hashicorp/nomad-releases/pull/361
Ref: https://hashicorp.atlassian.net/browse/NET-9577
=> changelog: update titles of recent ENT-only backports

website/content/docs/job-specification/job.mdx
The `task` block should be inside the `group` block. The example in the page places the `task` block directly under `job`.
=> docs/jobspec: Fix "task" block placement

website/content/docs/configuration/client.mdx
The **reserved cores** parameter in [Nomad client agent configuration](https://developer.hashicorp.com/nomad/docs/configuration/client#cores) is `int` type, and default value is `0`.
But according to [the source codes](https://github.com/hashicorp/nomad/blob/main/command/agent/config.go#L1209), it is `string` type, and defalut value is `empty string`.
This part of the document has bothered me for a long time, so I want to fix it.
=> docs: Fix parameter type and default value in client reserved configuration.

website/content/docs/job-specification/periodic.mdx
Fixes https://github.com/hashicorp/nomad/issues/23391
There are quite a few different approaches to mark deprecation across the docs, I picked this as it was the most explicit parameter-level option in my opinion.
Screenshot below:
Other refs:
- The PR that added the original deprecation notice to the tool itself https://github.com/hashicorp/nomad/pull/17858
- Changelog entry mentioning that PR for Nomad 1.6.2 https://github.com/hashicorp/nomad/blob/main/CHANGELOG.md#162-september-13-2023
=> docs: add deprecation notice to `cron` on `docs/job-specification/periodic`

website/content/docs/upgrade/upgrade-specific.mdx
The upgrade to sentinel v0.26 is a breaking change for users of custom Sentinel plugins, requiring rebuilding the plugins with sentinel-sdk v4.
=> [docs] Add Sentinel info to version-specific upgrade page

.github/workflows/jira-sync.yml
This will allow Jira issues to be synced from GH issue only via the Jira:Issue Link field and not issue type. 
The new tickets will come across as type:GitHub, but can be changed to bugs or any other Jira issue type and still sync.
=> Fixing sync to work only on Issue Link field

.changelog/23427.txt, ui/app/controllers/jobs/index.js, ui/app/routes/jobs/index.js, ui/app/serializers/job.js, ui/app/styles/components/jobs-list.scss, ui/app/templates/jobs/index.hbs, ui/tests/acceptance/jobs-list-test.js
Previously, our jobs index page would handle handle all errors when fetching jobs by resetting state and trying again (with 5-second backoff).
This PR makes it so that proxy-timeout specific errors instead throw a notification, but keep the cached jobs shown on the page.
The user is then presented with two options to move forward:
- pause fetch attempts (for this session or until they click "Manually fetch jobs")
- Immediately try again (in case they extended their proxy settings in the background and want to immediately cancel pending requests and try again, or restart previously-paused attempts)
Resolves #23228
=> [ui] Jobs list should handle 502s and 504s gracefully

.changelog/23381.txt, client/allocrunner/alloc_runner_hooks.go, client/allocrunner/consul_hook.go, client/allocrunner/taskrunner/envoy_bootstrap_hook.go, client/allocrunner/taskrunner/envoy_bootstrap_hook_test.go, client/allocrunner/taskrunner/sids_hook.go, client/allocrunner/taskrunner/sids_hook_test.go, client/allocrunner/taskrunner/task_runner_hooks.go, client/allocrunner/taskrunner/task_runner_test.go, client/client.go, client/config/config.go, client/consul/consul.go, client/consul/consul_test.go, client/consul/consul_testing.go, client/consul/identities.go, client/consul/identities_test.go, client/consul/identities_testing.go, website/content/docs/integrations/consul/service-mesh.mdx
Nomad creates Consul ACL tokens and service registrations to support Consul service mesh workloads, before bootstrapping the Envoy proxy. Nomad always talks to the local Consul agent and never directly to the Consul servers. But the local Consul agent talks to the Consul servers in stale consistency mode to reduce load on the servers. This can result in the Nomad client making the Envoy bootstrap request with a tokens or services that have not yet replicated to the follower that the local client is connected to. This request gets a 404 on the ACL token and that negative entry gets cached, preventing any retries from succeeding.
To workaround this, we'll use a method described by our friends over on `consul-k8s` where after creating the objects in Consul we try to read them from the local …
=> Consul: add preflight checks for Envoy bootstrap

website/content/docs/upgrade/upgrade-specific.mdx
Upgrade guide should be uniform across all supported versions, otherwise backporting breaking changes is tedious.
=> docs: upgrade guide updates for backported Docker windows changes

.changelog/23456.txt, nomad/job_endpoint_statuses.go, nomad/job_endpoint_statuses_test.go
The job statuses endpoint does not filter jobs by the namespace query parameter unless the user passes a management token. The RPC handler creates a filter based on all the allowed namespaces but improperly conditions reducing this down to only the requested set on there being a management token. Note this does not give the user access to jobs they shouldn't have, only ignores the parameter.
Remove the RPC handler's extra condition that prevents using the requested namespace. This is safe because we specifically check the ACL for that namespace earlier in the handler.
Fixes: https://github.com/hashicorp/nomad/issues/23370
=> job statuses: fix filtering for namespace parameter

.changelog/23457.txt, api/jobs.go, api/scaling.go, command/agent/job_endpoint.go, command/job_scale.go, nomad/job_endpoint.go, nomad/job_endpoint_test.go, nomad/structs/structs.go, website/content/api-docs/jobs.mdx, website/content/docs/commands/job/scale.mdx
The RPC handler for scaling a job passes flags to enforce the job modify index is unchanged when it makes the write to Raft. But its only checking against the existing job modify index at the time the RPC handler snapshots the state store, so it can only enforce consistency for its own validation.
In clusters with automated scaling, it would be useful to expose the enforce index options to the API, so that cluster admins can enforce that scaling only happens when the job state is consistent with a state they've previously seen in other API calls. Add this option to the CLI and API and have the RPC handler check them if asked.
Fixes: https://github.com/hashicorp/nomad/issues/23444
=> scale: add `-check-index` to `job scale` command

.changelog/23458.txt, ui/app/templates/components/job-editor.hbs, ui/app/templates/components/job-editor/edit.hbs, ui/app/templates/jobs/run/templates/manage.hbs
This adds nuance to the ACL policy checks for a user to be able to see Job Templates (which are specifically-named Nomad Variables behind the scenes).
The way it works today has some specific checks in place:
- to even get into the job templates section, you have to first click the "Run Job" button, which only exists if you have the `submit-job` ACL capability, or a general `"write"` policy.
- Once there, we only show you a "Choose from template" button if you can write variables to `*`.
I think the original intent here was to do up-front checks for full CRUD access, but this PR moves that access check a little downstream. Here, you'll see that the check to see the "Choose from template" button requires specifically `read variable` access (and I could be convinced to make it `list …
=> [ui] Read-based checks for viewing templates and write-based checks for saving them

.changelog/23452.txt, drivers/docker/config.go, drivers/docker/driver.go, website/content/docs/drivers/docker.mdx, website/content/docs/upgrade/upgrade-specific.mdx
We should default to `hyper-v` isolation mode on Windows, as suggested in discussions between @tgross and @angrycub.
=> docker: default to hyper-v isolation on Windows

.github/workflows/actionlint.yml, .github/workflows/backport.yml, .github/workflows/build.yml, .github/workflows/checks.yaml, .github/workflows/copywrite.yml, .github/workflows/ember-test-audit.yml, .github/workflows/lock.yml, .github/workflows/release.yml, .github/workflows/semgrep.yml, .github/workflows/test-core.yaml, .github/workflows/test-e2e.yml, .github/workflows/test-ui.yml, .github/workflows/test-windows.yml
Update HashiCorp actions
* hashicorp/actions-docker-build v1 ==> v2.0.0
* hashicorp/actions-generate-metadata v1.1.1 ==> v1.1.1(pinned)
* hashicorp/actions-packaging-linux v1 ==> v1.8.0
* hashicorp/setup-copywrite v1.1.2 ==> v1.1.3
Updated actions
* actions/checkout v4.1.1 ==> v4.1.7
* actions/download-artifact v3.0.2 ==> v4.1.7
* actions/setup-go v4.0.1 ==> v5.0.1
* actions/setup-node v3.7.0 ==> v4.0.2
* actions/upload-artifact v3.1.2 ==> v4.3.3
* andstor/file-existence-action v2.0.0 ==> v3.0.0
* browser-actions/setup-chrome v1.2.0 ==> v1.7.1
* dessant/lock-threads v4.0.1 ==> v5.0.1
* marocchino/sticky-pull-request-comment v2.6.2 ==> v2.9.0
* mshick/add-pr-comment v2.8.1 ==> v2.8.2
* nanasess/setup-chromedriver v2.1.2 ==> v2.2.2
* slackapi/slack-github-action v1.24.0 ==> v1.26.0
This PR …
=> [actions] Update projects GitHub actions

nomad/structs/diff.go, nomad/structs/diff_test.go
Currently, the MBits field is not filtered and therefore always shown in diffs (regardless of MBits even being defined in an old or new network resource), and after finding that it is a deprecated field, this pr adds MBits to the list of filtered fields so it will not be shown as a diff.
=> mbits: filter mbits out of diff

nomad/structs/structs.go, nomad/structs/structs_test.go
CE component of: https://github.com/hashicorp/nomad-enterprise/pull/1561
Related: https://github.com/hashicorp/nomad/issues/18876
Jira: https://hashicorp.atlassian.net/browse/NET-9978
Once merged and backported, the enterprise component will be merged and backported.
=> quota: add cores to resource addition calculation.

.changelog/23492.txt, ui/app/controllers/jobs/job.js
This prevents an issue where, still on the job page, the cache-removed job would have trouble accessing properties and relationships of its now-removed Ember Data object.
Resolves #23410
=> [ui] When a job is deleted in the background, wait until redirect before cache unload

.changelog/23468.txt, ui/app/controllers/jobs/index.js, ui/app/routes/jobs/index.js, ui/app/templates/jobs/index.hbs, ui/mirage/config.js, ui/tests/acceptance/jobs-list-test.js
Changes the jobs index page's Namespaces dropdown from single select (radio buttons) to checkboxes (multiple OR-based selection)
Also fixes an error noted in #23445  where node pools and namespaces with `-` characters would not filter correctly
Resolves NET-10159
=> [ui] Generalized namespace handling, generalized facet searching, node pools facet search

.changelog/23399.txt, .github/workflows/test-windows.yml, client/lib/numalib/topology.go, plugins/base/base_test.go
After changes introduced in https://github.com/hashicorp/nomad/pull/23284 we no longer need to make a `if !st.SupportsNUMA()` check in the `GetNodes()` topology method. In fact this check will now cause panic in [`nomadTopologyToProto`](https://github.com/hashicorp/nomad/blob/7cf63326322c92074dab53321c32ddee92627bcd/plugins/base/base.go#L166) method on systems that don't support NUMA. 
Fixes #23385 
Internal ref: https://hashicorp.atlassian.net/browse/NET-10134
=> plugins: fix nomadTopologyToProto panic on systems that don't support NUMA

website/data/docs-nav-data.json, website/redirects.js
This PR removes a reference page's listing in the main navigation file, which caused a 404 and created a navigation quirk. 
It also adds a redirect. According to [this PR merged in 2022](https://github.com/hashicorp/nomad/pull/14947), the content of the `source` page is now part of the `policy` page.
=> docs: Autoscaling agent 404 and navigation fix

.changelog/23502.txt, command/helpers.go, command/helpers_test.go, command/plugin_status_csi.go, command/quota_inspect.go, command/quota_status.go, command/scaling_policy_info.go, command/scaling_policy_info_test.go, command/service_info.go, command/volume_deregister.go, command/volume_detach.go, command/volume_status_csi.go
Several commands that inspect objects where the names are user-controlled share a bug where the user cannot inspect the object if it has a name that is an exact prefix of the name of another object (in the same namespace, where applicable). For example, the object "test" can't be inspected if there's an object with the name "testing".
Copy existing logic we have for jobs, node pools, etc. to the impacted commands:
* `plugin status`
* `quota inspect`
* `quota status`
* `scaling policy info`
* `service info`
* `volume deregister`
* `volume detach`
* `volume status`
If we get multiple objects for the prefix query, we check if any of them are an exact match and use that object instead of returning an error. Where possible because the prefix query signatures are the same, use a generic …
=> CLI: fix prefix matching across multiple commands

command/quota_apply.go, command/quota_init.go, command/quota_status.go, nomad/structs/structs.go
CE component of: https://github.com/hashicorp/nomad-enterprise/pull/1560
Once merged and backported, the enterprise side will be updated and merged. Docs and changelog will follow once the merge dance is complete.
=> quota: Allow cores to be configured within an enterprise quota.

nomad/plan_normalization_test.go, nomad/structs/diff.go, nomad/structs/structs.go, nomad/structs/structs_test.go
the ratio of optimized/unoptimized log size in TestPlanNormalize has been increased several times as people have added to various structs and coincidentally bumped into the magic limit.
we encountered another such case when adding to NetworkResource, but here we omitempty on the struct instead of bumping the limit in the test.
this has the added benefit of reducing the serialized struct size! which was the original intent (#5602) behind this test in the first place :P the actual value of the ratio is now 0.628... but here the test value is only dropped down to 0.66 to leave some wiggle room.
=> msgpack: omit empty fields on NetworkResource

ui/app/utils/sentinel_policy_templates/restrict-images.js
This PR improves the restrict-images Sentinel policy template to:
* only apply to Docker/Podman tasks
* to handle version numbers starting with v (instead of just starting with a number).
* better check for e.g. the default registry
The checks are now split in three - registry, image, and version.
=> Improve the restrict-images Sentinel policy template

ui/app/components/sentinel-policy-editor.hbs
Currently the UI page managing a single Sentinel policy, in the "Enforcement Levels" part, links to ACL Token Types instead of Sentinel Enforcement Levels.
=> Fix Sentinel UI link to point to Sentinel Enforcement Levels

.changelog/23548.txt, ui/app/modifiers/code-mirror.js, ui/app/templates/components/job-editor.hbs
At some point recently, the upload jobspec button (on the Job Run page) stopped working and I've yet to find a good reason why.
The job editor component uses what's called a [render modifier](https://blog.emberjs.com/coming-soon-in-ember-octane-part-4/) in Ember. It uses [a library](https://github.com/ember-modifier/ember-modifier/tree/main) to help add syntactical sugar to do this.
(Modifier TLDR: it "modifies" an existing HTML element, like a `<div>` in this case, instead of creating a new one in an Ember context. This is useful for codemirror, our text editor, because it needs to exist outside of an Ember context for lifecycle reasons)
There's a lifecycle hook in modifiers written this way called `modify()`, and there were previously ones called `didUpdateArguments()` and …
=> [ui] Fix: upload jobspec button

.changelog/23553.txt, ui/app/adapters/job.js
This makes it so that jobs with a `name` field that differs from their ID will correctly route an action when run via the web UI.
Resolves #23464
=> [ui] Fix: Actions should pass job id instead of job name

.changelog/23560.txt, api/jobs.go, api/jobs_test.go, command/agent/job_endpoint.go
Fixes a bug where variable values in job submissions that contained newlines weren't encoded correctly, and thus jobs that contained them couldn't be resumed once stopped via the UI. 
Internal ref: https://hashicorp.atlassian.net/browse/NET-9966
=> api: handle newlines in JobSubmission vars correctly

e2e/ui/run.sh
otherwise namespace deletion fails due to non-terminal allocations
=> e2e: purge the job in the UI stop_proxy() script

website/content/plugins/drivers/podman.mdx
We now provide linux packages and our installation instructions should reflect that.
=> docs: update podman driver installation instructions

.changelog/23538.txt, api/resources.go, client/allocrunner/networking_cni.go, client/allocrunner/networking_cni_test.go, client/taskenv/network.go, client/taskenv/network_test.go, command/agent/job_endpoint.go, nomad/structs/cni_config.go, nomad/structs/cni_config_test.go, nomad/structs/diff.go, nomad/structs/diff_test.go, nomad/structs/structs.go, nomad/structs/structs_test.go, website/content/docs/job-specification/network.mdx
This PR allows for users to set up CNI args in a job specification through the network block by adding a cni block and specifying an args field. 
Resolves #16197
=> cni: allow users to set CNI args in job spec

nomad/structs/cpucompat_default_test.go
I think this was missed because of the `!linux` build tag.
This [previous commit](https://github.com/hashicorp/nomad/commit/7d73065066e61c19e96a555749a51be83d14926f#diff-5c2cb0736f6332a8e02ab7b266defcdc423a2caaf16f14fb69e5e0215cc053c1R60) changed NodeIDs to a private attribute.
=> fix cpucompat_default_test

e2e/cni/cni_test.go, e2e/cni/input/cni_args.nomad.hcl, e2e/terraform/packer/ubuntu-jammy-amd64/cni_args.conflist, e2e/terraform/packer/ubuntu-jammy-amd64/cni_args.sh, e2e/terraform/packer/ubuntu-jammy-amd64/setup.sh
This PR adds an e2e test for cni args implemented in #23538. 
The test uses a job specification with a custom cni plugin "cni_args.sh" to write a file containing an interpolated variable passed in as a cni arg to the task local folder. Then the test makes sure that this file exists in the correct location and checks that the value was written and interpolated correctly.
=> e2e: test cni args

.changelog/23599.txt, drivers/docker/driver.go, drivers/docker/driver_test.go, drivers/docker/driver_windows.go, drivers/shared/capabilities/defaults.go, drivers/shared/capabilities/defaults_default.go, drivers/shared/capabilities/defaults_test.go, drivers/shared/capabilities/defaults_windows.go
Adjusts Docker capabilities per OS, and checks for runtime on Windows. 
Fixes #15181 
Internal ref: https://hashicorp.atlassian.net/browse/NET-9506
=> docker: adjust capabilities on Windows

client/allocrunner/networking_cni.go, client/allocrunner/networking_cni_mock_test.go, client/allocrunner/networking_cni_test.go, nomad/structs/structs.go
This PR adds a test for the `Setup` method, as well as an `nsOpts` field to the `cniNetworkConfigurator` struct. This field is specifically used to keep track of namespace usage for test assertions, and is used in the test written for Setup.
=> cni: test Setup method

e2e/terraform/.gitignore, e2e/terraform/Makefile, e2e/terraform/compute.tf
and tweak Makefile to generate a `custom.tfvars` instead of specifying vars separately via CLI.
hoping this makes it a little more obvious if there is no consul/nomad license.
I often packer build only linux if I'm testing something in linux (which is most of the time),
and as a result, there's no windows image with my git sha, so tf plan fails looking for the AMI,
even though I set windows clients to 0.
the change to `compute.tf` allows me to avoid futzing with any .tf files when testing such things.
=> e2e: skip missing windows ami if windows clients=0

e2e/terraform/packer/ubuntu-jammy-amd64/setup.sh
now that the version with tproxy CNI_ARGS is on releases.hashicorp.com, instead of building from source.
=> e2e: hc-install consul-cni

.changelog/23629.txt, client/allocrunner/networking_bridge_linux.go, client/allocrunner/networking_cni.go, client/allocrunner/networking_cni_test.go
Our documentation states that we support `.conf` and `.json` config formats (which are the same, actually), but in reality only `.conflist` works properly.  All of them are fingerprinted correctly, but only conflist works at allocation run time.
Fixes #19816
The first commit is here for a reference, which used a boolean to keep track of whether or not `confIsList`, but in my second pass I made a little struct to make it easier (I think) to hold correctly.
I have some e2e tests set up for this too, but I'll do that in a separate PR since we generally don't backport those.
=> Fix parsing CNI .conf and .json config formats

website/content/plugins/drivers/exec2.mdx
Mirrors README updates from https://github.com/hashicorp/nomad-driver-exec2/pull/40
=> exec2: update documentation with oom_score_adj settings

website/content/docs/drivers/docker.mdx
The documentation for the `SSL` option for the Docker driver is misleading inasmuch as it's both deprecated and non-functional in current versions of Docker. Remove this option from the docs and add a section explaining how to use insecure registries.
Fixes: https://github.com/hashicorp/nomad/issues/23616
Note to reviewers: see my repro here https://github.com/hashicorp/nomad/issues/23616#issuecomment-2239280566
=> docs: explain how to use insecure registries with Docker

scheduler/reconcile_util_test.go
Found a typo in `TestAllocSet_filterByTainted` while working on a related issue.
=> scheduler: fix TestAllocSet_filterByTainted

.changelog/23577.txt, api/keyring.go, command/agent/keyring_endpoint.go, command/agent/keyring_endpoint_test.go, command/operator_root_keyring.go, command/operator_root_keyring_rotate.go, nomad/core_sched.go, nomad/core_sched_test.go, nomad/encrypter.go, nomad/encrypter_test.go, nomad/keyring_endpoint.go, nomad/keyring_endpoint_test.go, nomad/leader.go, nomad/state/state_store.go, nomad/state/state_store_test.go, nomad/structs/keyring.go, website/content/docs/commands/operator/root/keyring-rotate.mdx, website/content/docs/configuration/server.mdx, website/content/docs/integrations/consul/acl.mdx, website/content/docs/integrations/vault/acl.mdx, website/content/docs/upgrade/upgrade-specific.mdx
When a root key is rotated, the servers immediately start signing Workload Identities with the new active key. But workloads may be using those WI tokens to sign into external services, which may not have had time to fetch the new public key and which might try to fetch new keys as needed.
Add support for prepublishing keys. Prepublished keys will be visible in the JWKS endpoint but will not be used for signing or encryption until their `PublishTime`. Update the periodic key rotation to prepublish keys at half the `root_key_rotation_threshold` window, and promote prepublished keys to active after the `PublishTime`.
This changeset also fixes three bugs in periodic root key rotation and garbage collection, none of which can be safely fixed without implementing prepublishing:
* Periodic root …
=> keyring: support prepublishing keys

e2e/keyring/doc.go, e2e/keyring/keyring_test.go, e2e/terraform/etc/nomad.d/server-linux.hcl, e2e/terraform/main.tf, e2e/terraform/nomad.tf, e2e/terraform/provision-nomad/main.tf, e2e/terraform/provision-nomad/variables.tf, e2e/terraform/variables.tf
In #23580 we're implementing support for encrypting Nomad's key material with external KMS providers or Vault Transit. In #23577 we're implementing support for prepublishing keys. This changeset updates the E2E infrastructure to use an external KMS and adds tests for rotation.
Ref: https://hashicorp.atlassian.net/browse/NET-10398
Ref: https://hashicorp.atlassian.net/browse/NET-10280
Ref: https://hashicorp.atlassian.net/browse/NET-10334
Ref: https://github.com/hashicorp/nomad/issues/14852
Ref: https://github.com/hashicorp/nomad/pull/23580
---
Note to reviewers: this PR requires #23580 and #23577 to be merged before we can merge this. Test run against a build that includes both PRs:
```
$ go test -v -count=1 ./keyring
=== RUN   TestKeyringRotation
--- PASS: TestKeyringRotation (0.62s)
PASS …
```
=> keyring: E2E testing for KMS/rotation

website/content/docs/configuration/keyring/awskms.mdx, website/content/docs/configuration/keyring/azurekeyvault.mdx, website/content/docs/configuration/keyring/gcpckms.mdx, website/content/docs/configuration/keyring/index.mdx, website/content/docs/configuration/keyring/transit.mdx, website/content/docs/operations/key-management.mdx, website/data/docs-nav-data.json
In #23580 we're implementing support for encrypting Nomad's key material with external KMS providers or Vault Transit. This changeset breaks out the documentation from that PR to keep the review manageable and present it to a wider set of reviewers.
Ref: https://hashicorp.atlassian.net/browse/NET-10334
Ref: https://github.com/hashicorp/nomad/issues/14852
Ref: https://github.com/hashicorp/nomad/pull/23580
Preview link: https://nomad-git-docs-keyring-external-kms-hashicorp.vercel.app/nomad/docs/configuration/keyring
(and the other pages in this new section)
---
Note to reviewers: 
* This PR describes the work in #23580.
* A lot of this is lifted right out of the Vault [seal](https://developer.hashicorp.com/vault/docs/configuration/seal) documentation.
* ~I don't have all the KMS types …
=> docs: external KMS configuration

website/content/docs/commands/operator/root/keyring-rotate.mdx, website/content/docs/configuration/server.mdx
Backports required documentation bits from #23577 because the PR was only automatically backported to the 1.7.x+ent branch.
=> Backport docs: keyring support prepublishing keys

.changelog/23663.txt, client/allocrunner/taskrunner/task_runner_hooks.go, client/allocrunner/taskrunner/template/template.go, client/allocrunner/taskrunner/template_hook.go, client/allocrunner/taskrunner/template_hook_test.go
For templates with `change_mode = "script"`, we set a driver handle in the poststart method, so the template runner can execute the script inside the task. But when the client is restarted and the template contents change during that window, we trigger a change_mode in the prestart method. In that case, the hook will not have the handle and so returns an errror trying to run the change mode.
We restore the driver handle before we call any prestart hooks, so we can pass that handle in the constructor whenever it's available. In the normal task start case the handle will be empty but also won't be called.
The error messages are also misleading, as there's no capabilities check happening here. Update the error messages to match.
Fixes: https://github.com/hashicorp/nomad/issues/15851
Ref: …
=> template: allow change_mode script to run after client restart

command/agent/config_parse.go, command/agent/config_parse_test.go, command/agent/testdata/basic.hcl, command/agent/testdata/basic.json, nomad/structs/config/reporting.go
The internal library for [automated license utilization reporting](https://developer.hashicorp.com/nomad/docs/enterprise/license/utilization-reporting) supports configuration to send metrics to a local development version of the collector. Add "undocumented" configuration options to the `reporting` block allow developers to debug and verify we're sending the data we expect with real Nomad servers and not just unit tests.
Note this behavior does not impact Nomad Community Edition whatsoever, which does not collect telemetry outside of the incidental data from version upgrade checks ([Checkpoint](https://developer.hashicorp.com/nomad/docs/faq#q-what-is-checkpoint-does-nomad-call-home)).
Ref: https://hashicorp.atlassian.net/browse/NET-10057
Ref: …
=> reporting: allow export interval and address to be configurable

.changelog/23673.txt, nomad/state/state_store.go, nomad/state/state_store_test.go, nomad/structs/structs.go
When updating a `JobScalingEvent`, the state store function did not copy the existing object before mutating it. This corrupts the state store because it modifies the leaf node without committing it in a transaction. It can also cause the Nomad server to crash with a "fatal error: concurrent map read and map write" if its `ScalingEvents` map is read via the `ScaleStatus` RPC at the same time as it's being written.
This changeset also removes some mostly-unused public methods on the struct that dangerously encourage you to mutate it outside of a copy.
Ref: https://hashicorp.atlassian.net/browse/NET-10529
=> scaling: fix state store corruption bug for job scaling events

.release/linux/package/usr/lib/systemd/system/nomad.service
The default root:root is used as this provides permissions to run both server and client agents. The comment details what changes can be made to operators if needed.
When running the service file prior to this change, root:root would be the default.
closes #23685
=> release: explicitly set Linux service file user and group param.

website/content/docs/integrations/consul/acl.mdx, website/content/docs/integrations/vault/acl.mdx, website/content/docs/job-specification/consul.mdx, website/content/docs/job-specification/vault.mdx, website/content/docs/release-notes/nomad/upcoming.mdx, website/content/docs/upgrade/upgrade-specific.mdx, website/data/docs-nav-data.json
Add a section to the docs describing planned upcoming deprecations and removals. Also added some missing upgrade guide sections missed during the last release.
=> docs: notices of upcoming deprecations and backports

.changelog/23625.txt, ui/app/adapters/plugin.js, ui/mirage/config.js
This PR unescapes the `/` in the `csi/PLUGIN_NAME` path that Ember Data was escaping due to how/where it was prepended at the adapter layer.
Re: #23615 : This makes it so the plugins UI is usable again, but doesn't solve the underlying no-longer-handles-unescaped-path-slashes problem.
=> [ui] Unescape csi/ in plugin GET requests

website/content/docs/release-notes/nomad/upcoming.mdx
In Nomad 1.6.0 we started sending the node secret with RPCs that previously did not include it. We planned to deprecate the older auth workflow but didn't set a release. Removing the legacy support means that nodes running <1.6.0 will fail to heartbeat.
Ref: https://hashicorp.atlassian.net/browse/NET-10009
=> docs: add note about removing support for older clients in 1.9

.changelog/23693.txt, nomad/structs/network.go, nomad/structs/network_test.go
When a client add two IP matching the same network host, it should be able to used both for static ports
The primary used case is when an application with not configurable port is deployed on a big bare metal host. It would be wasteful to not allow multiple time the same host to be used.
Fixes: #23693
=> Allow static ports duplication on network host with multiple matches

ui/app/utils/sentinel_policy_templates/restrict-images.js
In my previous PR ( #23530 ) I made a small mistake - the starting multiline comment is missing an opening # on the second line, and thus gets interpreted as Sentinel code instead of a comment.
=> Fix a Sentinel policy template

CHANGELOG.md
After updating the 1.6.13 release, I noticed none of the changes of 1.8.2 applied to it, this PR updates the changelog to reflect it.
=> fix: Remove the changelog from v1.6.13

.release/versions.hcl
As of Nomad 1.8.0 LTS we're no longer backporting changes to Nomad CE versions 1.7.x and 1.6.x. We never got around to removing the flags in the file the backport assistant uses to control automated backports.
=> build: remove inactive CE versions from being backport eligible

.github/workflows/build.yml
Changes to the build workflow around 32-bit arm builds were not backported to the 1.8.x release branch, which resulted in extra builds being generated that weren't intended and will no longer match our artifact manifest.
=> build: backport build workflow to 1.8.x

website/content/docs/configuration/client.mdx
In Nomad 1.8.0 we introduced the `alloc_mounts_dir` to support unveil filesystem isolation, but we didn't document the configuration value.
=> docs: document `client.alloc_mounts_dir` configuration

website/content/docs/configuration/client.mdx, website/content/docs/drivers/exec.mdx, website/content/partials/chroot-limitations.mdx
[Jira issue](https://hashicorp.atlassian.net/browse/CE-659). 
Based on my research, this looks like a chroot limitation and not necessarily a Nomad issue (I could be completely wrong), so I added a new partial with a warning.
Deploy previews:
- [Fork/isolated chroot section](https://nomad-git-docs-ce659-hashicorp.vercel.app/nomad/docs/drivers/exec#chroot)
- [Client config chroot section](https://nomad-git-docs-ce659-hashicorp.vercel.app/nomad/docs/configuration/client#chroot_env-parameters)
=> DOCS: CE-659 chroot limitations for isolated fork/exec driver

e2e/vaultcompat/cluster_setup_test.go, e2e/vaultcompat/input/restricted_jwt.hcl, e2e/vaultcompat/run_ce_test.go, e2e/vaultcompat/vaultcompat_test.go, nomad/alloc_endpoint.go, nomad/config.go, nomad/structs/config/workload_id.go, nomad/structs/workload_id.go, nomad/structs/workload_id_test.go, testutil/server.go, website/content/docs/configuration/vault.mdx
Although we encourage users to use Vault roles, sometimes they're going to want to assign policies based on entity and pre-create entities and aliases based on claims. This allows them to use single default role (or at least small number of them) that has a templated policy, but have an escape hatch from that.
When defining Vault entities the `user_claim` must be unique. When writing Vault binding rules for use with Nomad workload identities the binding rule won't be able to create a 1:1 mapping because the selector language allows accessing only a single field. The `nomad_job_id` claim isn't sufficient to uniquely identify a job because of namespaces. It's possible to create a JWT auth role with `bound_claims` to avoid this becoming a security problem, but this doesn't allow for correct …
=> workload identity: add support for extra claims config for Vault

.changelog/23699.txt, command/job_inspect.go, command/job_inspect_test.go, website/content/docs/commands/job/index.mdx, website/content/docs/commands/job/inspect.mdx
In 1.6.0 we shipped the ability to review the original HCL in the web UI, but didn't follow-up with an equivalent in the command line. Add a `-hcl` flag to the `job inspect` command.
Closes: https://github.com/hashicorp/nomad/issues/6778
=> cli: add option to return original HCL in `job inspect` command

.changelog/23738.txt, client/allocwatcher/alloc_watcher.go, client/allocwatcher/alloc_watcher_unix_test.go
Resolves symlink escape when unarchiving by removing existing paths within the same allocation directory which can occur by writing a header that points to a symlink that lives outside of the sandbox environment. This exploit requires first compromising the Nomad client agent at the source allocation.
Ref: [NET-10607](https://hashicorp.atlassian.net/browse/NET-10607) & https://github.com/hashicorp/nomad-enterprise/pull/1725
[NET-10607]: https://hashicorp.atlassian.net/browse/NET-10607?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> security: fix write symlink escape on the same allocdir path

website/content/docs/concepts/plugins/cni.mdx, website/content/docs/install/index.mdx, website/content/docs/install/production/requirements.mdx, website/content/docs/integrations/consul/service-mesh.mdx, website/content/docs/networking/cni.mdx, website/content/docs/networking/index.mdx, website/content/partials/install/bridge-iptables.mdx, website/content/partials/install/cgroup-controllers.mdx, website/content/partials/install/install-cni-plugins.mdx, website/content/partials/install/install-consul-cni-plugin.mdx, website/content/partials/install/manual-install.mdx, website/data/docs-nav-data.json
- Pulled common content from multiple pages into new partials
- Refactored install/index to be OS-based so I could add linux-distro-based instructions to install-consul-cni-plugins.mdx partial. The tab groups on the install/index page do match and change focus as expected.
- Moved CNI overview-type content to networking/index
- Refactored networking/cni to include install CNI plugins and configuration content (from install/index).
- Moved CNI plugins explanation in bridge mode configuration section into bullet points. They had been #### headings, which aren't rendered in the R page TOC. I tried to simplify and format the bullet point content to be easier to scan.
Ref: https://hashicorp.atlassian.net/browse/CE-661
Fixes: https://github.com/hashicorp/nomad/issues/23229
Fixes: …
=> Backport of: docs: refactor CNI plugin content to 1.7.x (#23707)

website/content/docs/concepts/plugins/cni.mdx, website/content/docs/install/index.mdx, website/content/docs/install/production/requirements.mdx, website/content/docs/integrations/consul-connect.mdx, website/content/docs/networking/cni.mdx, website/content/docs/networking/index.mdx, website/content/partials/install/bridge-iptables.mdx, website/content/partials/install/cgroup-controllers.mdx, website/content/partials/install/install-cni-plugins.mdx, website/content/partials/install/install-consul-cni-plugin.mdx, website/content/partials/install/manual-install.mdx, website/data/docs-nav-data.json
- Pulled common content from multiple pages into new partials
- Refactored install/index to be OS-based so I could add linux-distro-based instructions to install-consul-cni-plugins.mdx partial. The tab groups on the install/index page do match and change focus as expected.
- Moved CNI overview-type content to networking/index
- Refactored networking/cni to include install CNI plugins and configuration content (from install/index).
- Moved CNI plugins explanation in bridge mode configuration section into bullet points. They had been #### headings, which aren't rendered in the R page TOC. I tried to simplify and format the bullet point content to be easier to scan.
Ref: https://hashicorp.atlassian.net/browse/CE-661
Fixes: https://github.com/hashicorp/nomad/issues/23229
Fixes: …
=> Backport of: docs: refactor CNI plugin content to 1.6.x (#23707)

.release/versions.hcl
In #23720 we removed the 1.7.x and 1.6.x release branches from the "active" versions for backports. But we forgot that we needed these backports to remain active for documentation backports because of versioned docs.
=> build: revert change to active versions

.changelog/23757.txt, acl/policy.go, acl/policy_test.go, website/content/docs/other-specifications/acl-policy.mdx
The path for a Variable never begins with a leading `/`, because it's stripped off in the API before it ever gets to the state store. The CLI and UI allow the leading `/` for convenience, but this can be misleading when it comes to writing ACL policies. An ACL policy with a path starting with a leading `/` will never match.
Update the ACL policy parser so that we prevent an incorrect variable path in the policy.
Fixes: https://github.com/hashicorp/nomad/issues/23730
=> acl: disallow leading `/` on variable paths

.changelog/23764.txt, scheduler/util.go
We missed this tiny bit in #23538
A change to the [`network{cni{}}` block](https://developer.hashicorp.com/nomad/docs/job-specification/network#cni-parameters) means that the user wants the network config to change, and that only happens during initial alloc setup, so we need to replace the alloc(s) to get fresh network(s) to reconfigure from scratch.
e.g. a job plan diff like this
```
+/- Task Group: "g" (1 in-place update)
+ Network {
+ CNIConfig {
+ a: "ayy"
}
```
should instead be
```
+/- Task Group: "g" (1 create/destroy update)
+ Network {
+ CNIConfig {
+ a: "ayy"
}
```
=> cni: network.cni job updates should replace allocs

.changelog/23763.txt, nomad/encrypter.go, nomad/structs/structs.go, nomad/structs/workload_id.go
Tasks have a default identity created during canonicalization. If this default identity is somehow missing, we'll hit panics when trying to create and sign the claims in the plan applier. Fallback to the default identity if it's missing from the task.
This changeset will need a different implementation in 1.7.x+ent backports, as the constructor for identities was refactored significantly in #23708. The panic cannot occur in 1.6.x+ent.
Fixes: https://github.com/hashicorp/nomad/issues/23758
=> identity: prevent missing task identity from panicking server

.changelog/23750.txt, client/testutil/driver_compatible.go, drivers/docker/driver.go, drivers/docker/driver_test.go
The Docker driver's `volume` field to specify bind-mounts takes a list of strings that consist of three `:`-delimited fields: source, destination, and options. We append the SELinux label from the plugin configuration as the third field. But when the user has already specified the volume is read-only with `:ro`, we're incorrectly appending the SELinux label with another `:` instead of the required `,`.
Combine the options into a single field value before appending them to the bind mounts configuration. Updated the tests to split out Windows behavior (which has a different volume specification format) and to ensure the test task has the expected environment for bind mounts.
Fixes: https://github.com/hashicorp/nomad/issues/23690
=> docker: fix delimiter for selinux label for read-only volumes

.changelog/16437.txt, command/acl_token_create.go
This pr is related to #14058 .
I wanted to work on that issue, but as I saw still it's not quite obvious on how we are going to fix it, I decided to only show a warning so at-least user can be aware the policy he/she is referring to, doesn't exist at the moment.
Also I can continue fixing this one if the expected result is known now.
Thanks.
Fixes: #14058
=> feat: show warning if policy doesn't exist

.changelog/18532.txt, command/acl_token_update.go, website/content/docs/commands/acl/token/update.mdx
This pull request adds the ability to update roles in the `acl token update` command.
Fixes: #18354
=> Add role update functionality to acl token update

.changelog/23785.txt, api/api.go, api/api_test.go
In #16872 we added support for configuring the API client with a unix domain socket. In order to set the host correctly, we parse the address before mutating the Address field in the configuration. But this prevents the configuration from being reused across multiple clients, as the next time we parse the address it will no longer be pointing to the socket. This breaks consumers like the autoscaler, which reuse the API config between plugins.
Update the `NewClient` constructor to only override the `url` field if it hasn't already been parsed. Include a test demonstrating safe reuse with a unix domain socket.
Ref: https://github.com/hashicorp/nomad-autoscaler/issues/944
Ref: https://github.com/hashicorp/nomad-autoscaler/pull/945
---
Note for reviewers: in some hypothetical "v2" of the API …
=> api: only set url field in config if previously unset

website/content/docs/integrations/consul/acl.mdx
Since Consul 1.15 (https://github.com/hashicorp/consul/pull/16097) Consul client agent only uses the agent token to perform [anti-entropy](https://developer.hashicorp.com/consul/docs/architecture/anti-entropy) after you deregister a service via the Agent API. so the Consul client agent must have its own agent token.
Internal ref: https://hashicorp.atlassian.net/browse/NET-10360
=> docs: minimal Consul policy for Nomad agents needs node:write

.github/workflows/test-core.yaml
Run `apt update` before `apt install` for `qemu-system` install step. Otherwise the cache may be out of date with Azure's own mirrors.
=> build: apt update before apt install

client/allocrunner/cni/bridge.go, client/allocrunner/cni/bridge_test.go, client/allocrunner/cni/plugins.go, client/allocrunner/networking_bridge_linux.go, client/allocrunner/networking_bridge_linux_test.go, client/allocrunner/test_fixtures/bad_input.conflist.json, client/allocrunner/test_fixtures/consul-cni.conflist.json, client/allocrunner/test_fixtures/empty.conflist.json, client/allocrunner/test_fixtures/hairpin.conflist.json
This PR refactors building the Nomad Bridge network configuration JSON, in order to allow for more manipulation of variables within the network configuration.
=> networking: refactor building nomad bridge config

.changelog/23804.txt, drivers/docker/config.go, drivers/docker/driver.go, drivers/docker/fingerprint.go, drivers/docker/handle.go, website/content/docs/drivers/docker.mdx
Nomad clients manage a cpuset cgroup for each task to reserve or share CPU cores. But Docker owns its own cgroups, and attempting to set a parent cgroup that Nomad manages runs into conflicts with how runc manages cgroups via systemd. Therefore Nomad must run as root in order for cpuset management to ever be compatible with Docker.
However, some users running in unsupported configurations felt that the changes we made in Nomad 1.7.0 to ensure Nomad was running correctly represented a regression. This changeset disables cpuset management for non-root Nomad clients. When running Nomad as non-root, the driver will not longer reconcile cpusets with Nomad and `resources.cores` will behave incorrectly (but the driver will still run).
Although this is one small step along the way to supporting a …
=> docker: disable cpuset management for non-root clients

.changelog/23803.txt, client/lib/cgroupslib/init.go, client/lib/cgroupslib/mount.go, client/lib/cgroupslib/mount_test.go
During Nomad client initialization with cgroups v2, we assert that the required cgroup controllers are available in the root `cgroup.subtree_control` file by idempotently writing to the file. But if Nomad is running with delegated cgroups, this will fail file permissions checks even if the subtree control file already has the controllers we need.
Update the initialization to first check if the controllers are missing before attempting to write to them. This allows cgroup delegation so long as the cluster administrator has pre-created a Nomad owned cgroups tree and set the `Delegate` option in a systemd override. If not, initialization fails in the existing way.
Although this is one small step along the way to supporting a rootless Nomad client, running Nomad as non-root is still …
=> cgroupslib: allow initial controller check with delegated cgroups

client/fingerprint/cpu.go
It would be useful to surface CPU fingerprinting issue with an `ERROR` level log message, vide suggestion in https://github.com/hashicorp/nomad/issues/23811
=> client: log an error message if total detected cpu is zero

.changelog/23832.txt, ui/app/controllers/jobs/index.js
Previously, cmd+click (or ctrl+click) on the `<a>` tag within job rows on the jobs index page would double-open the page: once in a new tab (as cmd+click does) and another in the same tab (as it would trigger the `{{on "click"}}` Ember event for the job row.
This checks to make sure the clicked element wasn't the anchor tag itself, and if it is, it returns early.
NB: it's a bad practice, generally, to have non-interactive elements like table rows be clickable! However this follows a long-standing convention in the Nomad UI that users may be used to from years of use, and has more than one highly accessible fallback.
Resolves #23544
=> [ui] Prevent double-open for cmd+click on jobs index links

e2e/artifact/artifact_test.go
Because this will definitely never change again, for sure, trust me.
=> e2e: fix module name of an artifact we download

api/resources.go, api/resources_test.go, client/lib/idset/idset.go, client/lib/numalib/detect_linux.go, client/lib/numalib/detect_linux_test.go, client/lib/numalib/testing.go, client/lib/numalib/topology.go, nomad/mock/node.go, nomad/structs/devices.go, nomad/structs/devices_test.go, nomad/structs/numa.go, nomad/structs/numa_test.go, nomad/structs/structs.go, nomad/structs/structs_test.go, nomad/structs/testing.go, scheduler/device.go, scheduler/device_test.go, scheduler/numa_ce.go, scheduler/preemption.go, scheduler/preemption_test.go, scheduler/rank.go, scheduler/rank_test.go
(CE backport of ENT 59433d56c7215c0b8bf33764f41b57d9bd30160f (without ent files))
original in https://github.com/hashicorp/nomad-enterprise/pull/1760
=> scheduler: support for device - aware numa scheduling (#1760)

.changelog/23850.txt, command/operator_debug.go, website/content/docs/commands/operator/debug.mdx
This PR changes `nomad operator debug`'s default behavior to include more logs. Specifically:
1. Increase the default duration to 5 minutes.
2. Capture the logs at TRACE level by default.
Jira: [NET-10281](https://hashicorp.atlassian.net/browse/NET-10281)
[NET-10281]: https://hashicorp.atlassian.net/browse/NET-10281?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> command/debug: capture more logs by default

client/allocrunner/networking_bridge_linux.go, client/allocrunner/networking_cni.go, client/allocrunner/networking_cni_test.go, client/allocrunner/networking_iptables.go, client/allocrunner/networking_iptables_test.go
When adding support for ipv6 to the Nomad bridge network, I found that iptables admin chain logic was untested, so this refactor is in pursuit of that.  I also creeped a little bit to move the iptables cleanup mock to live next to the chain mock, so this iptables stuff is more centralized in one spot.
The coming-soon bridge+ipv6 PR will do more actual testing -- this is a separate no-op PR to allow easier backporting for potential future bugfixes and such.
=> networking: refactor some iptables for testability

api/jobs.go, command/agent/job_endpoint.go, command/agent/job_endpoint_test.go, nomad/structs/structs.go, nomad/structs/structs_test.go
Establishes a `TaggedVersion` structure that attaches to Jobs (and therefore JobVersions)
Resolves #23836
=> TaggedVersion information in structs, rather than job_endpoint

website/README.md
Validating content section doesn't mention that you need to have the @hashicorp/platform-content-conformance installed if you want to run `npm run content-check` locally.
=> Website README: Add install HashiCorp package to run content-check locally

website/content/docs/commands/operator/snapshot/restore.mdx, website/content/docs/commands/operator/snapshot/save.mdx
- Highlight that snapshot does not include the keyring and that the keyring must be backed up and restored separately. Clarified that snapshot does not contain the keyring.
- Copy edits on existing text.
Fixes: Jira [CE-705](https://hashicorp.atlassian.net/browse/CE-705)
Deploy previews:
- [operator snapshot save](https://nomad-git-ce705-hashicorp.vercel.app/nomad/docs/commands/operator/snapshot/save/)
- [operator snapshot restore](https://nomad-git-ce705-hashicorp.vercel.app/nomad/docs/commands/operator/snapshot/restore/)
[CE-705]: https://hashicorp.atlassian.net/browse/CE-705?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Docs: CE-705 Highlight that user must back up keyring separately

.changelog/23858.txt, nomad/node_endpoint.go, nomad/node_endpoint_test.go
`node-update` triggers should never trigger sysbatch allocations, these should only ever be create by `periodic-job` or `job-register`.
An example scenario is: an allocation spawned by a sysbatch periodic job is running on a node, the allocation gets stopped, GC runs, the node becomes ineligible and eligible again, all within the parent sysbatch job period window. If this happens, `node-update` will trigger the system scheduler and prematurely start an allocation. This is not a desired behavior, and in fact a bug. 
Ref: https://hashicorp.atlassian.net/browse/NET-9323
=> node endpoints: do not create evals for sysbatch jobs

api/util_test.go, command/quota_apply.go
related to: https://github.com/hashicorp/nomad/issues/9917
internal ref: https://hashicorp.atlassian.net/browse/NET-9858
~note to reviewers: This CE PR doesn't require an ENT counterpart, because for parsing quota spec ce and ent share the code. Follow-up PRs with updated `quota init` command and the actual logic of enforcing quotas will follow.~
Sorry for going back and forth on this,  I'm still confused about the ce/ent split in quotas. Of course we need an ent PR to handle ent structs: https://github.com/hashicorp/nomad-enterprise/pull/1787
=> quota: parse device block

.changelog/23675.txt, .changelog/23817.txt, CHANGELOG.md, nomad/auth/auth.go, nomad/structs/structs.go, nomad/structs/workload_id.go, nomad/structs/workload_id_test.go, website/content/docs/configuration/vault.mdx
When we interpolate job fields for the `vault.default_identity.extra_claims` block, we forgot to use the parent job ID when that's available (as we do for all other claims). This changeset fixes the bug and adds a helper method that'll hopefully remind us to do this going forward.
Also added a missing changelog entry for #23675 where we implemented the `extra_claims` block originally, which shipped in Nomad 1.8.3.
Fixes: https://github.com/hashicorp/nomad/issues/23798
Ref: https://hashicorp.atlassian.net/browse/NET-10714
=> WI: interpolate parent job ID in `vault.default_identity.extra_claims`

.changelog/23902.txt, nomad/structs/workload_id.go, nomad/structs/workload_id_test.go
When we use the job ID in creating the subject claim (`sub`) for workload identities, we forgot to use the parent job ID when that's available. Child job IDs have a random component that makes them unsuitable for the subject field.
Ref: https://github.com/hashicorp/nomad/pull/23817#discussion_r1717490323
Ref: https://hashicorp.atlassian.net/browse/NET-10714
=> WI: use parent job ID for subject claim

.changelog/23882.txt, client/allocrunner/cni/bridge.go, client/allocrunner/network_manager_linux.go, client/allocrunner/networking_bridge_linux.go, client/allocrunner/networking_bridge_linux_test.go, client/allocrunner/networking_cni.go, client/allocrunner/networking_cni_test.go, client/allocrunner/test_fixtures/ipv6.conflist.json, client/config/config.go, command/agent/agent.go, command/agent/agent_test.go, command/agent/config.go, command/agent/config_parse_test.go, command/agent/testdata/basic.hcl, command/agent/testdata/basic.json, website/content/docs/configuration/client.mdx
Users may optionally enable IPv6 on the Nomad `bridge` network mode by setting `bridge_network_subnet_ipv6` in the client config.
Aside from that, there is a small functional change regarding our attempt to force-cleanup iptables if CNI fails to do so.  Now if the postrouting rule is not found, it only logs that instead of returning an error.  This way the new best-effort attempt to cleanup `ip6tables` can be less frightening in the logs if ipv6 isn't even enabled on the bridge.
Resolves #14101
=> networking: option to enable ipv6 on bridge network

website/content/api-docs/jobs.mdx
Currently the documentation for the parse job endpoint mentions the parameter `VariableFlags` which is not actually supported by the code, this PR removes it from the website.
=> Remove wrong `VariableFlags` parameter from parse job endpoint

.changelog/23913.txt, api/jobs.go, command/job_plan.go, command/job_run.go, command/job_validate.go, jobspec/parse.go, website/content/docs/commands/job/plan.mdx, website/content/docs/commands/job/run.mdx, website/content/docs/commands/job/validate.mdx
In Nomad 1.9.0 we're removing support for HCLv1. This has been long deprecated, but this changeset adds warnings to the command line and package documentation to make it that much more obvious.
Ref: https://github.com/hashicorp/nomad/pull/23912
Ref: https://github.com/hashicorp/nomad/issues/20195
Note to reviewers: this branch targets 1.8.x and not `main` because the PR with the removal is already targeting `main`.
=> jobspec: add deprecation warnings for removal of HCLv1

.changelog/23910.txt, acl/acl.go, nomad/service_registration_endpoint_test.go
As of Nomad 1.5.0, Nomad clients never make RPC requests to the ServiceRegistrationList/Read RPC without using a specific Workload Identity rather than the node secret. Nomad servers already have an anti-entropy behavior where terminal allocations / lost nodes get their services cleaned up, so there's no future reason for clients to have this access. Tighten the ACL permissions on these RPCs so that node secrets are no longer valid tokens.
Ref: https://hashicorp.atlassian.net/browse/NET-10009
Ref: https://developer.hashicorp.com/nomad/docs/release-notes/nomad/upcoming#nomad-1-9-0
=> services: reject node secret for Read/List RPC

client/client.go, client/lib/cgroupslib/partition_default.go, client/lib/cgroupslib/partition_linux.go, client/lib/cgroupslib/partition_test.go
As reported by support[ here](https://hashicorp.atlassian.net/browse/NET-10880) when a node is downscale to one with less number of cores, Nomad correctly fingerprints it, but the old allocations have the outdated information of the usable cores and might end up assigning more cores to the share and reserve cgroups than the ones present on the node., resulting on an error: 
```"Setup Failure" msg="failed to setup alloc: pre-run hook \"cpuparts_hook\" failed: write /sys/fs/cgroup/nomad.slice/share.slice/cpuset.cpus: numerical result out of range" failed=true```
And blocking the job from starting.
This PR adds a new field to the entity in charge of keeping track of the cgroups cpu distribution, that is populated at client start with the fresh information from the fingerprinting. This new …
=> [NET-10880] Keep a register of the usable cores to avoid using more than that

.changelog/23927.txt, drivers/docker/config.go, drivers/docker/driver_unix_test.go, drivers/docker/network_test.go, website/content/docs/drivers/docker.mdx, website/content/docs/upgrade/upgrade-specific.mdx
The gcr.io container registry is shutting down in March. Update the default `infra_image` for Docker's "pause" containers to point to the new location hosted by the k8s project.
Fixes: https://github.com/hashicorp/nomad/issues/23911
Ref: https://hashicorp.atlassian.net/browse/NET-10942
---
Question/note for reviewers: I said in #23911 that this is a breaking change so it should go in 1.9.0, but in March when the registry move happens our 1.8 LTS will still be in its support window (as will 1.7 until ~May or so, assuming that's when 1.10 goes out). Anyone on these older versions will have new allocations fail unless they update their pause container. Maybe we should pre-announce backporting this to 1.8 and 1.7 and then do so after 1.9 goes GA to give folks some time to deal with it if they …
=> docker: update infra_image to new registry

plugins/csi/client.go
When making ControllerPublishVolume, NodePublishVolume, and NodeStageVolume calls, in case of a `FailedPrecondition` error, Nomad returns the same error message, this PR makes a distinction to help users differentiate between the 3 calls.
=> Differentiate the error message for different rpc calls

.changelog/23894.txt, command/quota_apply.go, command/quota_init.go, nomad/structs/structs.go, nomad/structs/structs_test.go
CE part of https://github.com/hashicorp/nomad-enterprise/pull/1790
Resolves https://github.com/hashicorp/nomad/issues/9917
internal ref: https://hashicorp.atlassian.net/browse/NET-9858
=> quotas: corrections to `Resources.Add` and quota apply parsing logic

e2e/jobsubmissions/jobsubapi_test.go, website/content/api-docs/jobs.mdx
HCLv1 support was removed entirely in #23912, but I missed this one test and documentation reference.
=> E2E: remove invalid HCLv1 field on submissions test

nomad/state/state_store.go, nomad/state/state_store_test.go
Quota usage calculation depends on `allocation.Resources` field (which will be
deprecated in the future), while device resources are being kept in
`allocation.AllocatedResources` and parsed into a structure (vendor/type/name)
in order for the ranking in the scheduler to find nodes that can satisfy device
requirements. To make device quotas work properly, this has to be temporarily
translated into `allocation.Resources.Devices`.
=> quotas: correct addComputedAllocAttrs

command/quota_status.go
This `quota status` CLI extension aggregates over all devices that are part of a quota and lists their usage/limit.
=> cli: quota status extension for devices

website/content/docs/job-specification/vault.mdx
The documentation is referring to a `file` attribute that does not exist on the `vault` block.
This PR changes those references to mention the `disable_file` attribute instead.
=> Stop referring non existent vault.file attribute

api/allocations.go, client/allocrunner/networking_cni.go, client/allocrunner/networking_cni_test.go, nomad/structs/structs.go
#23882 added an IPv6 option for the Nomad `bridge` network mode, but an IPv6 addr created by it was not stored anywhere (aside from ip6tables on the node).
This puts it alongside the IPv4 address in an alloc's NetworkStatus, so it can be found with an API call if needed.
e.g.:
```
$ nomad alloc status -json 3dca | jq '.NetworkStatus'
{
"Address": "172.26.64.14",
"AddressIPv6": "fd00:a110:c8::b",
"DNS": null,
"InterfaceName": "eth0"
}
```
=> networking: set alloc NetworkStatus.AddressIPv6

nomad/encrypter.go, nomad/structs/keyring.go
While working on #23655 I found there were a few places in the encrypter/keyring where we could make modest improvements to performance and reliability of the existing code.
This changeset allows keyring replication to skip trying to replicate from itself, switches some of the read-only keyring accesses to use the read lock instead of a r/w lock, fixes the logging configuration to drop spurious "extra value" warnings in the logs, drops an unused type, and makes a minor refactoring to eliminate shadowing of the `keyset` type. Pulling this out to its own PR lets us backport these changes to the LTS and reduces the size of the PR that implements #23665.
Ref https://github.com/hashicorp/nomad/issues/23665
=> keyring: reduce locking and replication overhead

client/fingerprint/landlock_test.go
The landlock fingerprint test assumes there's no version of the landlock API >3. Update the test assertion to allow for the current v4 and any future
versions.
=> fingerprint: update landlock test to accept v4+ APIs

.github/dependabot.yml, .github/scan.hcl, .github/workflows/security-scan.yml, .gitignore, .release/security-scan.hcl
This PR updates the security scanner configuration for better accuracy and coverage.
=> security: fine tune security-scanner

nomad/vault_test.go, testutil/vault.go
Follows the pattern from `NewTestVault` to check for the vault binary, and skips if it does not exist.
=> add missing checks for vault binary in unit tests

.changelog/23977.txt, go.mod, helper/backoff.go, helper/raftutil/msgtypes.go, nomad/acl_test.go, nomad/alloc_endpoint_test.go, nomad/core_sched.go, nomad/core_sched_test.go, nomad/encrypter.go, nomad/encrypter_test.go, nomad/fsm.go, nomad/keyring_endpoint.go, nomad/keyring_endpoint_test.go, nomad/leader.go, nomad/plan_apply_test.go, nomad/server.go, nomad/state/schema.go, nomad/state/state_store_keyring.go, nomad/state/state_store_keyring_test.go, nomad/state/state_store_restore.go, nomad/structs/keyring.go, nomad/structs/structs.go
In Nomad 1.4, we implemented a root keyring to support encrypting Variables and signing Workload Identities. The keyring was originally stored with the AEAD-wrapped DEKs and the KEK together in a JSON keystore file on disk. We recently added support for using an external KMS for the KEK to improve the security model for the keyring. But we've encountered multiple instances of the keystore files not getting backed up separately from the Raft snapshot, resulting in failure to restore clusters from backup.
Move Nomad's root keyring into Raft (encrypted with a KMS/Vault where available) in order to eliminate operational problems with the separate on-disk keystore.
Fixes: https://github.com/hashicorp/nomad/issues/23665
Ref: https://hashicorp.atlassian.net/browse/NET-10523
Ref: …
=> keyring in raft

.github/workflows/backport.yml, .github/workflows/checks.yaml, .github/workflows/test-core.yaml, .github/workflows/test-ui.yml
I believe recent internal changes imply these jobs are running on some new default (AWS's smallest) spot instance types. Instead lets run them on something more powerful.
Internal RFC: IPS-056
=> ci: (ent) specify instance types when using self hosted runners

nomad/plan_endpoint_test.go
In #23977 we merged a change to how the keyring was stored. Because keyring initialization takes slightly longer now, this uncovered existing timing bugs in some of our tests where tests that require the keyring (ex. plan applier tests) were waiting for the leader but not the keyring initialization. Fix some of the examples we've seen cause test flakes.
=> test: wait for keyring for plan apply tests

.github/workflows/checks.yaml, .github/workflows/security-scan.yml, .github/workflows/test-core.yaml, .github/workflows/test-e2e.yml
This PR drops the `mods` workflow as well as the use of the `hashicorp/setup-go` action. These were added in the past to try and speed up downstream workflows by having go modules already cached. Since then, the `actions/setup-go` action added support for caching which we can now just make use of. But also we've been required to split some workflows into running on self-hosted runners (in ENT). On these runners the caching mechanism implies a slow rsync between the underlying Azure infrastructure and the runner on AWS. Empirically I've found it's much faster to just download the Go modules from the Go module cache hosted by Google. So, disable caching on self hosted runners.
=> ci: try less hard to cache go modules

.changelog/24023.txt, command/commands.go, command/operator_snapshot_redact.go, command/operator_snapshot_save.go, command/operator_snapshot_state.go, helper/raftutil/fsm.go, helper/raftutil/snapshot.go, helper/snapshot/snapshot.go, helper/snapshot/snapshot_test.go, nomad/fsm.go, scheduler/benchmarks/helpers_test.go, website/content/docs/commands/operator/snapshot/redact.mdx, website/content/docs/commands/operator/snapshot/save.mdx, website/data/docs-nav-data.json
In #23977 we moved the keyring into Raft, which can expose key material in Raft snapshots when using the less-secure AEAD keyring instead of KMS. This changeset adds tools for redacting this material from snapshots:
* The `operator snapshot state` command gains the ability to display key metadata (only), which respects the `-filter` option.
* The `operator snapshot save` command gains a `-redact` option that removes key material from the snapshot after it's downloaded.
* A new `operator snapshot redact` command allows removing key material from an existing snapshot.
Full documentation on the new keyring work coming in a separate PR
=> command line tools for redacting keyring from snapshots

website/content/docs/operations/aws-oidc-provider.mdx, website/data/docs-nav-data.json
Reference: [JIRA ticket](https://hashicorp.atlassian.net/browse/CE-672)
Preview: [Build link](https://nomad-omfjob7xa-hashicorp.vercel.app/nomad/docs/operations/aws-oidc-provider)
=> Usage doc for configuring Nomad OIDC with AWS IAM

.changelog/24029.txt, go.mod, go.sum
The major change between Raft v1.6 -> v1.7 was the introduction of the Prevote feature. Before Prevote, when a partitioned node rejoins a cluster it may cause an election even if the cluster was stable. Prevote can avoid this useless election so reintroducing partitioned servers to an otherwise stable cluster becomes seamless.
Full details: https://github.com/hashicorp/raft/pull/530
In #20335 we discussed whether or not to add a configuration option to disable prevote in case bugs were discovered. While bugs have been found (hence the v1.7.1 version as opposed to v1.7.0), I'm choosing to follow Vault's lead of straightfordwardly bumping the raft dependency: hashicorp/vault#27605 and hashicorp/vault#28218
=> deps: upgrade raft from v1.6.1 -> v1.7.1

.changelog/24038.txt
Adds missing changelog entry for previous [PR](https://github.com/hashicorp/nomad/pull/24038) regarding the new filename parameter in the job spec.
=> add changelog entry for workload identity filename feature

nomad/structs/structs_test.go
Validation of the default task was enabled after adding the filename parameter in [#24038](https://github.com/hashicorp/nomad/pull/24038).  This adds a valid identity name to the test tasks so validation tests will pass.
=> test: add valid identity name for test task

.changelog/24052.txt, client/taskenv/env.go, client/taskenv/env_test.go
Added `node.pool` attribute to interpretable node attributes so it could be used as per the [docs](https://developer.hashicorp.com/nomad/docs/runtime/interpolation#node-attributes)
=> fix: add node pool attribute to interpretable values in task env

.changelog/24058.txt, go.mod, go.sum
The main point of this dependency upgrade is to pull in the fixes in hashicorp/yamux#127 which prevents leaking deadlocked goroutines. It has been observed to improve the issue in hashicorp/nomad#23305 but does not seem sufficient to fix it entirely.
Since touching yamux is a rare and scary event (bugs can have pathological consequences at scale), I do **not** intend to backport this. If we discover the improvements are stable and significant enough, or if further fixes land in yamux, backporting can be done at that time.
=> deps: upgrade yamux from v0.1.1 to v0.1.2

.changelog/24057.txt, client/allocrunner/interfaces/task_lifecycle.go, client/allocrunner/taskrunner/driver_handle.go, client/allocrunner/taskrunner/interfaces/lifecycle.go, client/allocrunner/taskrunner/lifecycle.go, client/allocrunner/taskrunner/task_runner_hooks.go, client/allocrunner/taskrunner/template/template.go, client/allocrunner/taskrunner/template/template_test.go, client/allocrunner/taskrunner/template_hook.go, client/allocrunner/taskrunner/template_hook_test.go, client/allocrunner/taskrunner/testing/testing.go
When we introduced `change_mode=script` to templates, we passed the driver handle down into the template manager so we could call its `Exec` method directly. But the lifecycle of the driver handle is managed by the taskrunner and isn't available when the template manager is first created. This has led to a series of patches trying to fixup the behavior (#15915, #15192, #23663, #23917). Part of the challenge in getting this right is using an interface to avoid the circular import of the driver handle.
But the taskrunner already has a way to deal with this problem using a "lazy handle". The other template change modes already use this indirectly through the `Lifecycle` interface. Change the driver handle `Exec` call in the template manager to a new `Lifecycle.Exec` call that reuses the …
=> template: fix panic in change_mode=script on client restart

website/content/docs/operations/key-management.mdx, website/content/docs/upgrade/upgrade-specific.mdx
In #23977 we moved the keyring into Raft. This changeset documents the operational changes and adds notes to the upgrade guide.
=> docs: update key management docs for keyring-in-Raft

nomad/core_sched.go, nomad/core_sched_test.go, nomad/state/schema.go, nomad/state/schema_test.go, nomad/state/state_store.go, nomad/state/state_store_test.go
Hi this is totally Phil and not Daniel (ok it is Daniel)
This protects tagged versions of jobs from being bumped off as new versions are created, and prevents jobs that have any tagged versions from being GC'd.
=> Prevent pruning and reaping of TaggedVersion jobs

nomad/job_endpoint.go, ui/app/adapters/version-tag.js, ui/app/components/job-version.js, ui/app/models/job-version.js, ui/app/models/version-tag.js, ui/app/serializers/job-version.js, ui/app/serializers/version-tag.js, ui/app/styles/components/timeline.scss, ui/app/templates/components/job-version.hbs, ui/app/templates/components/two-step-button.hbs, ui/mirage/config.js, ui/mirage/factories/job-version.js, ui/mirage/scenarios/default.js, ui/tests/acceptance/job-versions-test.js
Version tag CRUD in the UI. Allows a user to create, modify, and remove version tags.
=> [ui] Version Tags on the job versions page

ui/app/adapters/job.js, ui/app/components/job-version.js, ui/app/controllers/jobs/job/versions.js, ui/app/models/job.js, ui/app/routes/jobs/job/versions.js, ui/app/serializers/job.js, ui/app/templates/components/job-versions-stream.hbs, ui/app/templates/jobs/job/versions.hbs, ui/tests/acceptance/job-versions-test.js
=> [ui] Add tag filter to the job versions page

ui/app/styles/components/timeline.scss, ui/app/templates/jobs/job/versions.hbs
Noticed that while the radio button itself was clickable, the labels in the dropdown fell beneath the `.timeline` text and so weren't clickable, and in some browsers even showed up behind the timeline itself.
=> [ui] Versions page diff dropdown: z-index so you can click on labels

website/content/docs/drivers/docker.mdx, website/content/docs/upgrade/upgrade-specific.mdx
Nomad v1.9.0 (finally!) removes support for HCL1 and the `-hcl1` flag. See #23912 for details.
One of the uses of HCL1 over HCL2 was that HCL1 allowed quoted keys in blocks such as env, meta, and Docker's labels:
```hcl
some_block {
"foo.bar" = "baz"
}
```
This works in HCL1 but is invalid HCL2. In HCL2 you must use a map instead of a block:
```hcl
some_map = {
"eggs.spam" = "works!"
}
```
This was such a hassle for users we special cased the `env` and `meta` blocks to be accepted as blocks or maps in #9936.
However Docker `labels`, being a task config option, is much harder to special case and commonly needs dots-in-keys for things like DataDog autodiscovery via Docker container labels:
https://docs.datadoghq.com/containers/docker/integrations/?tab=labels
Luckily `labels` can be …
=> docs: explain how to use dots in docker labels

drivers/docker/handle.go
In ##23966 when we switched to using the official Docker SDK client, we had more contexts to add because most of the library methods take one. But for some APIs like waiting for a container to exit after we've started it, we never want to close this context, because the container can outlive the Nomad agent itself. If we close this context, the waiter fails and then we stop the container (after only running 5min).
* Ref: [NET-11202 (comment)](https://hashicorp.atlassian.net/browse/NET-11202?focusedCommentId=550009)
* This has shipped in Nomad 1.9.0-beta.1 but not production yet.
=> docker: fix bug in waiting for container to exit

website/content/docs/operations/aws-oidc-provider.mdx
A few small updates to the recent "Federate access to AWS with Nomad Workload Identity" documentation, most notably that `restart` isn't needed because AWS SDKs handle OIDC reauth gracefully (unlike *any* other type of auth - for all others it's cached statically on startup, so nothing but a full restart works in case your credentials expire).
=> Update to Nomad as an AWS OIDC Provider doc

drivers/docker/stats.go
In ##23966 when we switched to using the official Docker SDK client, we had to rework the stats collection loop for the new client. But we missed resetting the timer on the collection loop, which meant that we'd only collect stats once and then never again.
* Ref: [NET-11202 (comment)](https://hashicorp.atlassian.net/browse/NET-11202?focusedCommentId=550814)
* This has shipped in Nomad 1.9.0-beta.1 but not production yet.
=> docker: reset timer after collecting stats

drivers/docker/handle.go
In ##23966 when we switched to using the official Docker SDK client, this included new API calls for attaching to the "exec objects" created for running processes inside a running Docker task. When we updated the API for the non-streaming cases (script health checks, and `change_mode = "script"`), we used the container ID and not the exec object ID. These IDs aren't identical because you can have multiple exec objects for a given container. This results in errors like "unable to upgrade to tcp, received 404" because the Docker API can't find the exec object with the container ID.
* Ref: [NET-11202 (comment)](https://hashicorp.atlassian.net/browse/NET-11202?focusedCommentId=551618)
* This has shipped in Nomad 1.9.0-beta.1 but not production yet.
* I found this via hands-on testing but I …
=> docker: fix non-streaming exec attachment

.changelog/24065.txt, command/agent/job_endpoint.go, command/agent/scaling_endpoint.go, nomad/fsm.go, nomad/job_endpoint_test.go, nomad/mock/job.go, nomad/scaling_endpoint_test.go, nomad/structs/structs.go, nomad/structs/structs_test.go
When jobs are submitted with a scaling policy, the scaling policy's target only includes the job's namespace if the `namespace` field is set in the jobspec and not from the request. Normally jobs are canonicalized in the RPC handler before being written to Raft. But the scaling policy targets are instead written during the conversion from `api.Job` to `structs.Job`. We populate the `structs.Job` namespace from the request here as well, but only after the conversion has occurred. Swap the order of these operations so that the conversion is always happening with a correct namespace.
Long-term we should not be making mutations during conversion either. But we can't remove it immediately because API requests may come from any agent across upgrades. Move the scaling target creation into the …
=> scaling policy: use request namespace as target if unset in jobspec

.changelog/24007.txt, client/config/config.go, command/agent/config_parse.go, command/agent/config_parse_test.go, command/agent/testdata/template.hcl, command/agent/testdata/template.json
```bash
cat ./debug/config.json
{
"bind_addr": "0.0.0.0",
"client": {
"cni_config_dir": "/etc/nomad/cni.d",
"cni_path": "/usr/libexec/cni",
"enabled": true,
"max_dynamic_port": 20010,
"min_dynamic_port": 20000,
"servers": [
"nomad-server-001.internal"
],
"template": {
"wait": {
"max": "15s",
"min": "5s"
},
"wait_bounds": {
"max": "15s",
"min": "5s"
}
}
},
"consul": {
"address": "consul.internal:8500"
},
"data_dir": "/opt/nomad/data",
"datacenter": "dc1",
"name": "nomad-client-001",
"telemetry": {
"collection_interval": "1s",
"disable_hostname": true,
"prometheus_metrics": true,
"publish_allocation_metrics": true,
"publish_node_metrics": true
},
"vault": {
"address": "https://vault.services.internal",
"enabled": true
}
}
```
Btw I think the artifacts block will have the same problem
Fixes …
=> Allow client template config block to be parsed when using json config

drivers/docker/handle.go, e2e/consul/input/on_update_check_restart.nomad
In #24095 we made a fix for non-streaming exec into Docker tasks for script checks and `change_mode = "script"`, but didn't complete E2E testing. We need to use `ContainerExecAttach` in the new API in order to get stdout/stderr from tasklets, but the previous `ContainerExecStart` call will prevent this from running successfully with an error that the exec has already run.
* Ref: [NET-11202 (comment)](https://hashicorp.atlassian.net/browse/NET-11202?focusedCommentId=551618)
* This has shipped in Nomad 1.9.0-beta.1 but not production yet.
* This should fix the remaining issues in nightly E2E for Docker.
---
Note for reviewers: at this point the `(*taskHandle).Exec` and `(*driver).ExecTaskStreaming` are similar enough that I suspect we could at least partially merge them, but I'm trying to …
=> docker: fix script check execution

command/agent/testdata/template.hcl
In #24007 we merged new HCL files but they were missing copywrite headers because the scan didn't run on this PR for some reason. I've already backported this to the Enterprise branches.
=> tests: fixup copywrite in test file

command/node_status.go
We initialize this slice with a zeroed array and then append to it, which means we then have to clean out the empty strings later. Initialize to the correct capacity up front so there are no empty values.
Ref: https://github.com/hashicorp/nomad/pull/24104
=> refactor: clean up slice initialization in node status

nomad/state/state_store.go, nomad/state/state_store_test.go
#23983 prevented tagged job versions from being pruned, but sometimes they would still count against `job_tracked_versions`, which was not what we intended.
This puts back the original old-version pruning logic, and instead filters out the tagged versions earlier (in `jobVersionByID()` to avoid additional slice construction to filter the list in `upsertJobVersion()`), so that tagged versions are simply not considered during pruning at all.
The test seems rather convoluted, but I opted to keep it because it exercises the holistic behavior that we want to see, while still also covering the more localized change to `jobVersionByID()`.
=> differently exclude tagged job versions from being pruned

nomad/server.go, website/content/docs/concepts/gossip.mdx, website/content/docs/concepts/security.mdx
The serf.io site is being taken down, so change all our links to point to the repo docs instead.
Ref: https://github.com/hashicorp/serf/pull/743
=> docs: remove references to serf.io site

website/content/plugins/devices/nvidia.mdx
- Incorporate content from driver repo [README](https://github.com/hashicorp/nomad-device-nvidia) into plugin overview paragraph.
- Replace the HTML table with a Markdown table to reduce lines in the file.
- Replace Nvidia with NVIDIA to match the how NVIDIA uses its name.
Fixes: [CE-681]
Deploy preview: https://nomad-git-ce681-hashicorp.vercel.app/nomad/plugins/devices/nvidia
[CE-681]: https://hashicorp.atlassian.net/browse/CE-681?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Docs: Add MIG support to NVIDIA driver overview paragraph

website/content/docs/concepts/cpu.mdx
- Add content from Matt's blog post to the Numa scheduling section of the CPU page.
- Change some of the headings to use sentence case so all headings use same case.
- Update NUMA scheduling code snippet to the one used in the blog
Fixes: [CE-682]
NUMA devices added to job spec in #24067.
Deploy preview: https://nomad-git-ce682-hashicorp.vercel.app/nomad/docs/concepts/cpu#numa-aware-scheduling
[CE-682]: https://hashicorp.atlassian.net/browse/CE-682?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Docs: Add devices to NUMA section of CPU page

scheduler/rank.go
e.g. before:
```
* Dimension "devices: %!s(<nil>)" exhausted on 1 nodes
```
after:
```
* Dimension "devices: no devices match request" exhausted on 1 nodes
```
=> scheduler: non-nil err when no devices match

nomad/worker_test.go
In #23977 we merged a change to how the keyring was stored. Because keyring initialization takes slightly longer now, this uncovered existing timing bugs in some of our tests where tests that require the keyring (ex. plan applier tests) were waiting for the leader but not the keyring initialization. Fix another example we've seen causing test flakes.
Ref: https://github.com/hashicorp/nomad/pull/24021 for an earlier example
=> test: wait for keyring in plan submission tests

.changelog/24125.txt, .github/workflows/test-windows.yml, client/allocdir/alloc_dir.go, client/allocdir/alloc_dir_nonlinux_test.go, client/allocdir/alloc_dir_test.go, client/allocdir/fs_linux_test.go, client/allocdir/task_dir_test.go
When using the Client FS APIs, we check to ensure that reads don't traverse into the allocation's secret dir and private dir. But this check can be bypassed on case-insensitive file systems (ex. Windows, macOS, and Linux with obscure ext4 options enabled). This allows a user with `read-fs` permissions but not `alloc-exec` permissions to read from the secrets dir.
This changeset updates the check so that it's case-insensitive. This risks false positives for escape (see linked Go issue), but only if a task without filesystem isolation deliberately writes into the task working directory to do so, which is a fail-safe failure mode.
Ref: https://github.com/golang/go/issues/18358
Ref: https://hashicorp.atlassian.net/browse/NET-10664
=> alloc fs: use case-insensitive check for reads of secret/private dir

plugins/device/cmd/example/README.md
While testing our new device quotas (enterprise), I had to (re)discover a couple little things to properly install and configure our `example` device plugin.
=> update example device readme

.changelog/24127.txt, nomad/structs/structs.go
While testing with agents built with the race-detection option enabled, I encountered a data race while draining a node.
When we upsert a node we copy the `NodeResources` struct and then perform a fixup for backwards compatibility of the topology struct. This fixup was being executed on the original struct and not the copy, which means we're uselessly fixing up the wrong struct and we're corrupting the state store in the process (albeit harmlessly, I suspect).
Fix the data race by calling the method on the correct pointer.
=> fix data race in node upsert

e2e/ui/package-lock.json, e2e/ui/package.json, e2e/ui/run.sh
fix for e2e failure
```
Error: browserType.launch: Executable doesn't exist at /ms-playwright/chromium-1140/chrome-linux/chrome
╔══════════════════════════════════════════════════════════════════════╗
║ Looks like Playwright Test or Playwright was just updated to 1.48.0. ║
║ Please update docker image as well.                                  ║
║ -  current: mcr.microsoft.com/playwright:v1.47.0-jammy               ║
║ - required: mcr.microsoft.com/playwright:v1.48.0-jammy               ║
║                                                                      ║
║ <3 Playwright Team                                                   ║
╚══════════════════════════════════════════════════════════════════════╝
```
steps to update:
* edit run.sh IMAGE variable manually
* run ./run.sh test
=> e2e: ui: update playwright to 1.48.0

website/content/docs/commands/quota/apply.mdx, website/content/docs/commands/quota/init.mdx, website/content/docs/enterprise/index.mdx, website/content/docs/job-specification/resources.mdx, website/content/docs/other-specifications/index.mdx, website/content/docs/other-specifications/quota.mdx, website/data/docs-nav-data.json
main new page: https://nomad-bmjsdet16-hashicorp.vercel.app/nomad/docs/other-specifications/quota
other affected pages:
* [docs/enterprise](https://nomad-bmjsdet16-hashicorp.vercel.app/nomad/docs/enterprise#resource-quotas)
* [docs/job-specification/resources](https://nomad-bmjsdet16-hashicorp.vercel.app/nomad/docs/job-specification/resources)
* [docs/other-specifications](https://nomad-bmjsdet16-hashicorp.vercel.app/nomad/docs/other-specifications)
---
relates to hashicorp/tutorials#2263
closes #23258
=> docs: add Quota specification page

website/content/docs/configuration/consul.mdx, website/content/docs/integrations/consul/acl.mdx
As of #24166, Nomad agents will use their own token to deregister services and checks from Consul. This returns the deregistration path to the pre-Workload Identity workflow. Expand the documentation to make clear why certain ACL policies are required for clients.
Additionally, we did not explicitly call out that auth methods should not set an expiration on Consul tokens. Nomad does not have a facility to refresh these tokens if they expire. Even if Nomad could, there's no way to re-inject them into Envoy sidecars for Consul Service Mesh without recreating the task anyways, which is what happens today. Warn users that they should not set an expiration.
Closes: https://github.com/hashicorp/nomad/issues/20185 (wontfix)
Ref: https://hashicorp.atlassian.net/browse/NET-10262
=> docs: clarify requirements for Consul token policies and TTLs

.changelog/24157.txt, api/tasks.go, api/tasks_test.go, client/allocrunner/taskrunner/artifact_hook.go, client/allocrunner/taskrunner/getter/params.go, client/allocrunner/taskrunner/getter/params_test.go, client/allocrunner/taskrunner/getter/sandbox.go, client/allocrunner/taskrunner/getter/sandbox_test.go, client/allocrunner/taskrunner/getter/util.go, client/allocrunner/taskrunner/getter/z_getter_cmd.go, client/interfaces/client.go, command/agent/job_endpoint.go, command/agent/job_endpoint_test.go, nomad/structs/diff_test.go, nomad/structs/structs.go, nomad/structs/structs_test.go, website/content/docs/job-specification/artifact.mdx
This PR adds a boolean `chown` field to the artifact block.
It indicates whether the Nomad client should `chown` the downloaded files
and directories to be owned by the `task.user`. This is useful for drivers
like `raw_exec` and `exec2` which are subject to the host filesystem user
permissions structure. Before, these drivers might not be able to use or
modify the downloaded artifacts since they would be owned by the root
user on a typical Nomad client configuration.
```hcl
artifact {
source      = "https://example.org/blah/Hello.java"
destination = "local/java"
chown       = true
}
```
In this example the `local/java` directory will recursively become owned by the task's user instead of `root`.
Fixes https://github.com/hashicorp/nomad-driver-exec2/issues/51
=> jobspec: add a chown option to artifact block

.release/versions.hcl
We can't backport to 1.9.x release branches without this change.
=> build: update versions file for backports

.changelog/24166.txt, command/agent/consul/service_client.go, command/agent/consul/unit_test.go
When the local Consul agent receives a deregister request, it performs a pre-flight check using the locally cached ACL token. The agent then sends the request upstream to the Consul servers as part of anti-entropy, using its own token. This requires that the token we use for deregistration is valid even though that's not the token used to write to the Consul server.
There are several cases where the service identity token might no longer exist at the time of deregistration:
* A race condition between the sync and destroying the allocation.
* Misconfiguration of the Consul auth method with a TTL.
* Out-of-band destruction of the token.
Additionally, Nomad's sync with Consul returns early if there are any errors, which means that a single broken token can prevent any other service on the …
=> Consul: improve reliability of deregistration

website/content/api-docs/jobs.mdx, website/content/docs/commands/job/revert.mdx, website/content/docs/commands/job/tag.mdx, website/content/docs/concepts/job.mdx, website/content/partials/version/tag-reason.mdx, website/data/docs-nav-data.json
Add job version content to Job page. https://nomad-git-ce714-hashicorp.vercel.app/nomad/docs/concepts/job/
Update CLI:
- revert https://nomad-git-ce714-hashicorp.vercel.app/nomad/docs/commands/job/revert
- new page for tag  https://nomad-git-ce714-hashicorp.vercel.app/nomad/docs/commands/job/tag
Update API:
- jobs.mdx https://nomad-git-ce714-hashicorp.vercel.app/nomad/api-docs/jobs#create-job-version-tag
**There are broken links to the Jobs version tutorial since that PR hasn't been merged**
Partial: [CE-714]
Relates to: https://github.com/hashicorp/tutorials/pull/2294  which is the version tags how-to guide. It's in tutorials because all the other Job-related how-to guides are there. Eventually that how-to content will be moved to docs.
[CE-714]: …
=> Docs: Golden Versions updates

.changelog/24165.txt, scheduler/reconcile.go, scheduler/reconcile_test.go
In scenarios where a disconnected client reconnects with failed replacement allocs, the reconcile strategy for picking the correct allocation was not working.  These changes allow evaluation of multiple replacement allocs, and the stopping of allocs that are in a client terminal status.
=> scheduler: fix reconnecting allocations getting rescheduled

website/content/docs/release-notes/nomad/v1_9_x.mdx, website/data/docs-nav-data.json
Add 1.9 release notes based on Matt's [blog draft](https://docs.google.com/document/d/1VBrCfQnmw744Js_VzZF0407981pMaa3i7Z69GwkIiw8/edit?usp=sharing).
**Some links are broken because PRs have not yet been published. DOUBLE CHECK ALL LINKS.**
Fixes: [CE-728]
[CE-728]: https://hashicorp.atlassian.net/browse/CE-728?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Docs: Add 1.9 release notes

website/content/docs/concepts/job.mdx
Add tutorial links to Job versions section.
- Tag a version: add link to Job versions guide
- Compare versions: add link to Compare versions section
- Revert: add link to Revert to a version section
Deploy preview: https://nomad-git-ce714a-hashicorp.vercel.app/nomad/docs/concepts/job#job-versions
Relates to: https://github.com/hashicorp/tutorials/pull/2294
Partial: [CE-714]
[CE-714]: https://hashicorp.atlassian.net/browse/CE-714?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Docs: Update job version section with tutorial links

command/agent/consul/connect.go, command/agent/consul/connect_test.go, nomad/structs/structs.go
Mostly resolves #7905 -- #23882 introduced IPv6 support to Nomad's "bridge" network mode, and this extends that to Consul Connect (which also requires "bridge" mode).  I say "mostly" because Transparent Proxy still does not work (the Consul CNI plugin does not do any `ip6tables` at the moment for its extra functionality).
Along the way, I found that since we were always setting Connect/Envoy's `bind_address` to `"0.0.0.0"`, the user couldn't pick anything else (like I had tried `"::"`).  In particular, even with this PR auto-detecting IPv6, I imagine a user might like to set it to `""` (empty), so that Consul [`proxy-defaults` config](https://developer.hashicorp.com/consul/docs/connect/config-entries/proxy-defaults#examples) can come into play.  I did not add a config option for the …
=> Consul Connect over IPv6 (except tproxy)

GNUmakefile, e2e/consulcompat/shared_download_test.go, e2e/terraform/packer/ubuntu-jammy-amd64/setup.sh, e2e/vaultcompat/vaultcompat_test.go
Installing Vault and Consul from releases.hashicorp.com via `hc-install` has been failing intermittently. Update the `hc-install` binaries to be current and add one retry to downloads for our compat tests so that we can get builds more reliably green while the underlying issue is being debugged.
=> build: update hc-install to current

.changelog/24214.txt, .github/workflows/test-windows.yml, drivers/rawexec/driver_test.go, drivers/rawexec/driver_unix_test.go, drivers/rawexec/driver_windows_test.go, drivers/shared/executor/executor_test.go, drivers/shared/executor/executor_windows.go, drivers/shared/executor/executor_windows_test.go, drivers/shared/executor/utils_test.go
On Windows, if the `raw_exec` driver's executor exits, the child processes are not also killed. Create a Windows "job object" (not to be confused with a Nomad job) and add the executor to it. Child processes of the executor will inherit the job automatically. When the handle to the job object is freed (on executor exit), the job itself is destroyed and this causes all processes in that job to exit.
Fixes: https://github.com/hashicorp/nomad/issues/23668
Ref: https://learn.microsoft.com/en-us/windows/win32/procthread/job-objects
~Note: automated testing for this will need to be end-to-end but we're not running Windows on nightly anymore.~ I've verified the behavior works as expected using Process Explorer. Killing the executor kills all child processes as expected. Killing the root child …
=> windows: set job object for executor and children

command/agent/consul/connect_test.go
I realized this test I wrote in #24203 didn't actually test the IPv6-detection logic, because `"bind_address": "::"` was being passed in as config, effectively bypassing the important bit here:
https://github.com/hashicorp/nomad/blob/eb8d240aeefa4edf4b632cc6a9d39984103a6848/command/agent/consul/connect.go#L250-L252
=> connect: fix ipv6 bind_address test

.changelog/24229.txt, drivers/docker/driver_test.go, drivers/docker/stats.go
In #23966 we switched to the official Docker SDK for the `docker` driver. In the process we refactored code around stats collection to use the "one shot" version of stats. Unfortunately this "one shot" stats collection does not include the `PreCPU` stats, which are the stats from the previous read. This breaks the calculation we use to determine CPU ticks, because now we're subtracting 0 from the current value to get the delta.
Switch back to using the streaming stats collection. Add a test that fully exercises the `TaskStats` API.
Fixes: https://github.com/hashicorp/nomad/issues/24224
Ref: https://hashicorp.atlassian.net/browse/NET-11348
---
In addition to new tests here, I've tested manually with the setup described here https://github.com/hashicorp/nomad/issues/24224#issuecomment-241722 …
=> docker: use streaming stats collection to correct CPU stats

.changelog/24237.txt, drivers/docker/docklog/docker_logger.go, drivers/docker/driver.go
During a refactoring of the docker driver in https://github.com/hashicorp/nomad/pull/23966 we introduced a bug: API version negotiation option was not passed to every new client call. 
Fixes https://github.com/hashicorp/nomad/issues/24212
internal ref: https://hashicorp.atlassian.net/browse/NET-11337
=> docker: always use API version negotiation when initializing clients

.changelog/24202.txt, drivers/docker/driver.go, e2e/allocexec/doc.go, e2e/allocexec/docker_exec_test.go, e2e/allocexec/input/sleepytar.hcl
This PR ensures we close the hijacked writer connection once there is no more data going into the stdin buffer of the exec'd command. Without this, the command (tar in this case) would hang forever awaiting more input.
Fixes #24171
Internal: NET-11378
=> docker: close response connection once stdin is exhausted

.changelog/24244.txt, drivers/docker/driver.go
Close the `stdin` and hijacked write connection handles upon exiting the exec function. Otherwise the goroutine reading from `stdin` will leak and hang forever.
Fixes #24242
=> docker: close hijacked write connection when exec ends

.changelog/24232.txt, command/asset/connect.nomad.hcl, command/asset/example.nomad.hcl
The full example jobspecs emitted by [`nomad job init`](https://developer.hashicorp.com/nomad/docs/commands/job/init) and `nomad job init -connect` have not seen any improvement in over a year. I intended to just peek in, add a new [`ui{}` block](https://developer.hashicorp.com/nomad/docs/job-specification/ui) block, and be done. However, something about skimming over the phrase `the online documentation` a dozen times made me stop and do some spring cleaning.
The diff is an absolute nightmare even though I think my changes are fairly minor. Some highlights:
1. Added a `ui` block because I think it should be a widely used feature!
2. Removed tons of non-connect-related blocks from the connect example. I don't think the value of documenting blocks twice in the normal example and in connect …
=> cli: update nomad job init full examples

.changelog/24241.txt, nomad/auth/auth.go, nomad/heartbeat.go, nomad/node_endpoint_test.go, testutil/wait.go
In #23838 we updated the `Node.Update` RPC handler we use for heartbeats to be more strict about requiring node secrets. But when a node goes down, it's the leader that sends the request to mark the node down via `Node.Update` (to itself), and this request was missing the leader ACL needed to authenticate to itself.
Add the leader ACL to the request and update the RPC handler test for disconnected-clients to use ACLs, which would have detected this bug. Also added a note to the `Authenticate` comment about how that authentication path requires the leader ACL.
Fixes: https://github.com/hashicorp/nomad/issues/24231
Ref: https://hashicorp.atlassian.net/browse/NET-11384
=> heartbeat: use leader's ACL token when failing heartbeat

api/allocations.go, website/content/api-docs/allocations.mdx
GET /v1/client/allocation/:alloc_id/pause?task=:task_name is a tiny but critical API for observability of tasks with a schedule. This PR explains each of the values which might be returned.
Preview: https://nomad-csj1dlx3r-hashicorp.vercel.app/nomad/api-docs/allocations#override-pause-schedule-state
Internal: NET-11261
=> docs: explain schedule state values

.changelog/24240.txt, ui/app/styles/core/navbar.scss
Maxes out the width of the profile dropdown for token name so that it isn't as likely to bump into the searchbox etc.
(Note: a better, and eventual, solution to this is to use css grid or flexbox, but today is not that day)
=> [ui] Adds an ellipsis and max width to profile nav token name

.changelog/24162.txt, ui/app/styles/components/variables.scss
Resolves #24151 
(To test: check out the variables page in firefox/safari. Appears to have been working fine in chrome etc.)
=> [ui] Fix an issue where variables index dropdown would appear underneath table headers

.changelog/24265.txt, go.mod, go.sum, plugins/drivers/testutils/testing.go
During allocation recovery, the go-plugin reattachment workflow checks to see if the PID we stored in client state is still running. If so, we try to connect to that process. If that fails, we kill the process under the presumption it's not working. But during reattachment we don't know that the PID we have is still valid. Which means that the process we're trying to attach to may have exited and a different process has spawned with the same PID. This results in some unrelated process getting silently killed.
Update go-plugin to 1.6.2, which includes a bug fix so we do not kill the process.
Fixes: https://github.com/hashicorp/nomad/issues/23969
Ref: https://hashicorp.atlassian.net/browse/NET-11233
=> deps: update go-plugin to 1.6.2

command/operator_raft_leadership_transfer.go
Before:
```
Remove Peer Options:
-peer-address="IP:port"
Transfer leadership to the Nomad server with given Raft address.
-peer-id="id"
Transfer leadership to the Nomad server with given Raft ID.
```
After
```
Transfer Leadership Options:
-peer-address="IP:port"
Transfer leadership to the Nomad server with given Raft address.
-peer-id="id"
Transfer leadership to the Nomad server with given Raft ID.
```
=> Docs: Update leadership transfer options docs

.changelog/24169.txt, client/fingerprint/env_gce.go, client/fingerprint/env_gce_test.go
As documented in https://cloud.google.com/compute/docs/metadata/predefined-metadata-keys
This PR fingerprints one more piece of information on Google Cloud instances: whether the instances are preemptible or not.
=> fingerprint gce: collect preemptibility

website/content/docs/commands/job/tag.mdx
CLI help order was wrong, so updating the CLI command.
I updated the usage to use `[options]`, moved general options into each subcommand but put that list in  `<details>` so the long general options list doesn't take up space. I didn't add the details tags to the included general_options file because that would affect several pages, but not all since use of that include is not consistent throughout the CLI command pages.
Fixes: [CE-739]
Relates to: [#24272] [#24266]
https://nomad-git-ce739-hashicorp.vercel.app/nomad/docs/commands/job/tag
[CE-739]: https://hashicorp.atlassian.net/browse/CE-739?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Docs: Update CLI job tag unset

website/content/docs/integrations/consul/acl.mdx
The locality of Consul tokens we mint via Workload Identity is governed by the Consul auth method configuration. By default tokens are local to the Consul datacenter, which typically maps 1:1 with a Nomad region. Cluster administrators who need cross-datacenter tokens can get them by setting the locality to global, at the risk of placement problems if the primary DC isn't available.
Ref: https://github.com/hashicorp/consul/issues/21863
Fixes: https://github.com/hashicorp/nomad/issues/23505
=> docs: warn about Consul auth method locality

website/content/docs/integrations/consul/service-mesh.mdx, website/content/docs/job-specification/transparent_proxy.mdx
When using transparent proxy mode with the `connect` block, the UID of the workload cannot be the same as the UID of the Envoy sidecar (currently 101 in the default Envoy container image).
Fixes: https://github.com/hashicorp/nomad/issues/23508
~I'll follow-up with a second PR for the tutorial.~ Actually, that doesn't fit in the tutorial format.
=> docs: warn about UID overlap between workload and Envoy tproxy

.changelog/24186.txt, api/services.go, command/agent/consul/service_client.go, command/agent/consul/service_client_test.go, command/agent/job_endpoint.go, command/agent/job_endpoint_test.go, nomad/structs/diff.go, nomad/structs/diff_test.go, nomad/structs/services.go, website/content/docs/job-specification/service.mdx
```
No `weights`
```
```
$ curl -s http://127.0.0.1:8500/v1/agent/services  | jq '.[] | select(.Service=="global-redis-check") | .Weights'
{
"Passing": 1,
"Warning": 1
}
$ dig @127.0.0.1 -p 8600 global-redis-check.service.consul SRV +short
1 1 27982 7f000001.addr.dc1.consul.
```
---
```
weights {}
```
```
$ ./bin/nomad job plan ./job.hcl
+/- Job: "redis"
+/- Task Group: "cache" (1 in-place update)
+/- Task: "redis" (forces in-place update)
+/- Service {
Address:           ""
...
+ Weights {
+ Passing: "1"
+ Warning: "1"
}
}
```
```
$ curl -s http://127.0.0.1:8500/v1/agent/services  | jq '.[] | select(.Service=="global-redis-check") | .Weights'
{
"Passing": 1,
"Warning": 1
}	
```
---
```
weights {
passing = 5
}
```
```
$ ./bin/nomad job plan ./job.hcl
+/- Job: "redis"
+/- Task Group: …
```
=> consul: add support for service weight

website/content/api-docs/jobs.mdx
The parsing of the idempotency_token requires snake case, as it is a URL query parameter and not part of the JSON request body. 
See also: https://github.com/hashicorp/nomad/blob/2df473c5612cd46000bad755221de49e994256ba/command/agent/http.go#L951
=> fix: documentation of idempotency_token in API

website/content/docs/operations/ipv6-support.mdx, website/data/docs-nav-data.json
Add IPv6 support page to operations section.
Fixes: [CE-718]
Deploy preview https://nomad-git-ce718-hashicorp.vercel.app/nomad/docs/operations/ipv6-support
[CE-718]: https://hashicorp.atlassian.net/browse/CE-718?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Docs: Add IPv6 support page

.changelog/24329.txt, nomad/structs/services.go, nomad/structs/services_test.go
This PR adds a validation check for PortLabels on Connect Native enabled services. This is a [requirement](https://github.com/hashicorp/consul/blob/6351a821aa171fddfab01776cce199d62aa6d5e2/agent/structs/structs.go#L1692-L1695) in Consul and if missing from the job spec will continually error.
```
"service": "nomad",
"message": "failed to update services in Consul",
"attributes": {
"hostname": "<snip>",
"@level": "warn",
"@timestamp": "2024-10-29T15:16:34.148322Z",
"service": "nomad",
"@module": "consul.sync",
"error": "Unexpected response code: 400 (Validation failed: 1 error occurred:\n\t* Port or SocketPath must be set for a Connect native service.)",
"status": "info",
}
```
I can't get all of the tests to pass locally but `TestService_Validate` looked good.
```
=== RUN …
```
=> Validate that Connect Native services define a port

ui/app/components/actions-flyout.hbs, ui/app/components/allocation-service-sidebar.hbs, ui/app/components/job-status/allocation-status-block.hbs, ui/app/components/job-status/failed-or-lost.hbs, ui/app/components/job-status/individual-allocation.hbs, ui/app/components/job-status/latest-deployment.hbs, ui/app/components/job-status/panel/deploying.hbs, ui/app/components/task-sub-row.hbs, ui/app/components/variable-paths.hbs, ui/app/styles/components/actions.scss, ui/app/styles/components/job-status-panel.scss, ui/app/templates/administration/policies/policy.hbs, ui/app/templates/administration/roles/role.hbs, ui/app/templates/allocations/allocation/index.hbs, ui/app/templates/clients/client/index.hbs, ui/app/templates/components/job-service-row.hbs, ui/app/templates/components/scale-events-accordion.hbs, ui/app/templates/components/task-row.hbs, ui/app/templates/components/topo-viz/node.hbs, ui/app/templates/jobs/index.hbs, ui/app/templates/jobs/job/services/service.hbs, ui/app/templates/variables/variable/index.hbs, ui/ember-cli-build.js, ui/package.json, ui/tests/acceptance/variables-test.js, ui/tests/pages/clients/list.js, ui/tests/pages/components/topo-viz/node.js, ui/yarn.lock
Upgrade HDS dependency to 4.13 & migrate `FlightIcon` to `Hds::Icon`
=> Upgrade HDS dependency to 4.13 & migrate `FlightIcon` to `Hds::Icon`

drivers/rawexec/driver_unix_test.go
The `must` package import was missing from the `drivers/rawexec/driver_unix_test.go` file.  This PR adds the import so these tests can build and run.
=> test: fix rawexec driver unix test imports

ui/app/controllers/settings/tokens.js, ui/app/services/system.js, ui/app/templates/components/region-switcher.hbs, ui/mirage/config.js, ui/tests/acceptance/regions-test.js, ui/tests/unit/adapters/job-test.js
Relates to @shoenig's work in https://github.com/hashicorp/nomad/pull/24320 so branching off of that
As it stands, when you sign in with a token in a multi-region cluster, the `system.regions` array exists, but the `system.activeRegion` doesn't re-compute.
This makes that value recompute automatically during token verification, and refreshes the regions list to trigger that.
(Note: I don't think this is an issue for SSO-based authentication, since there is an explicit page refresh, which would handle region-setting by virtue of initial page load)
Resolves #24337
=> [ui] Signing in with a token explicitly sets the region dropdown activeRegion

.changelog/24297.txt, nomad/structs/structs.go, nomad/structs/structs_test.go
Fixes a bug in the AllocatedResources.Comparable method, which resulted in
reporting less required resources than actually expected. This could result in
overscheduling of allocations on a single node  and overlapping cgroup cpusets.
Split to #24304
---
```
job "redis2nd" {
type = "service"
group "cache" {
count = 1
task "redis-prestart" {
lifecycle {
hook    = "prestart"
sidecar = false
}
config {
image = "hello-world:latest"
}
resources {
cpu = 1000
}
}
task "redis" {
config {
image = "redis:3.2"
}
resources {
cpu = 1000
}
}
task "redis-start-side" {
lifecycle {
hook    = "poststart"
sidecar = true
}
config {
image = "redis:3.2"
}
resources {
cpu = 1000
}
}
task "redis-poststop" {
lifecycle {
hook    = "poststop"
sidecar = false
} …
```
=> scheduler: fixed a bug where resource calculation did not account correctly for poststart tasks

client/testing.go, nomad/client_csi_endpoint_test.go
In #10193 we introduced a testing helper that spins up a client RPC server without the rest of the client operations so that we can make server-side client RPC tests lighter. But this wasn't actually ever wired up to the intended target. While working on Dynamic Host Volumes I noticed that this would be useful for RPC tests.
This changeset fixes some bugs in the helper that arose from client code drift, and makes it used by the client RPC tests for CSI. This will also get used for the DHV RPC tests.
Ref: https://github.com/hashicorp/nomad/pull/10193
=> testing: RPC-only test client helper

acl/acl_test.go, acl/policy.go, acl/policy_test.go
This changeset implements the ACLs required for dynamic host volumes RPCs:
* `host-volume-write` is a coarse-grained policy that implies all operations.
* `host-volume-register` is the highest fine-grained privilege because it potentially bypasses quotas.
* `host-volume-create` is implicitly granted by `host-volume-register`
* `host-volume-delete` is implicitly granted only by `host-volume-write`
* `host-volume-read` is implicitly granted by `policy = "read"`,
These are namespaced operations, so the testing here is predominantly around parsing and granting of implicit capabilities rather than the well-tested `AllowNamespaceOperation` method.
This changeset does not include any changes to the `host_volumes` policy which we'll need for claiming volumes on job submit (if any). That'll be …
=> dynamic host volumes: ACL policies

client/testing.go
Closes: https://github.com/hashicorp/nomad-enterprise/issues/1985
Additional details can be seen in the linked issue and evidence of the tested fix working.
=> test: ensure RPC only test client sets enterprise specific config.

.changelog/24340.txt, drivers/shared/executor/executor.go, drivers/shared/executor/executor_basic.go, drivers/shared/executor/executor_universal_linux.go, drivers/shared/executor/executor_universal_linux_test.go
This PR changes the behavior of the raw exec task driver on old cgroups v1
systems such that the executor process is no longer a member of the cgroups
created for the task. Now, the executor process is placed into those
cgroups and starts the task child process (just as before), but now then
exits those cgroups and exists in the nomad parent cgroup. This change
makes the behavior sort of similar to cgroups v2 systems, where we never
have the executor enter the task cgroup to begin with (because we can
directly clone(3) the task process into it).
Fixes #23951
=> drivers: move executor process out of v1 task cgroup after process starts

.changelog/24280.txt, client/allocrunner/consul_grpc_sock_hook.go
This PR fixes a bug where the `consul.grpc_address` could not be set using
a `go-sockaddr/template` string. This was inconsistent with how we do accept
such strings for `consul.address` values.
=> connect: handle grpc_address as gosockaddr/template string

.changelog/24374.txt, ui/app/components/forbidden-message.js, ui/app/controllers/application.js, ui/app/controllers/settings/tokens.js, ui/app/routes/application.js, ui/app/services/token.js, ui/app/templates/application.hbs, ui/app/templates/components/forbidden-message.hbs, ui/tests/acceptance/token-test.js
When your token 403s or 500s (when it's deleted behind the scenes, or expires either while you're using the app, or while it's in your localStorage, say, overnight), this PR adds functionality to remember the page (and queryParams) you were on when it happened.
Upon signing back in (with a renewed token, say), you'll be automatically rerouted back to that page, with a little notification saying so.
Resolves #23793
=> [ui] When your token expires and you sign in again, redirect to your original route.

.changelog/24312.txt, command/agent/job_endpoint.go, command/agent/job_endpoint_test.go, website/content/api-docs/jobs.mdx
This opens up dispatching parameterized jobs by systems that do not allow modifying what http request body they send (like webhooks).
e.g. these two requests are equal:
```shell
POST '{"Payload": "'"$(base64 <<< "hello")"'"}' /v1/job/my-job/dispatch
POST 'hello' /v1/job/my-job/dispatch/payload
```
Closes #24312
=> api: new dispatch endpoint sends body as Payload

.changelog/24396.txt, nomad/csi_endpoint.go, nomad/csi_endpoint_test.go
When creating or registering a CSI volume, the RPC handler uses the volume specification's namespace instead of the request namespace. This works as intended, but the ACL check is only on the request namespace.
This allows a cross-namespace ACL bypass for authenticated users who have `csi-write-volume` capabilities in one namespace but not another namespace. Such a user can set the volume specification to a forbidden namespace while setting the `-namespace` flag in the CLI or API. The ACL check happens against the namespace they do have permission to, but the volume is created in the forbidden namespace.
This changeset fixes the bug by moving the namespace check into the loop over the volumes being written by the RPCs. It also updates the tests to better cover ACL checking in these two …
=> CSI: fix namespace ACL bypass on create/register APIs

nomad/blocked_evals.go, nomad/core_sched.go, nomad/core_sched_test.go, nomad/mock/csi.go, nomad/mock/job.go, nomad/structs/csi.go, scheduler/reconcile.go
Whenever setting objects creation/modify time, we should always use UTC. https://github.com/hashicorp/nomad/pull/24112 introduced some inconsistencies in this area, and this PR fixes it.
=> gc: be consistent with setting create/modify timestamp tz

website/content/docs/job-specification/parameterized.mdx, website/content/docs/job-specification/periodic.mdx
Addresses [this](https://hashicorp.atlassian.net/browse/NET-11577) issue.
Deploy preview: https://nomad-git-d-gh24311-parameterized-jobs-hashicorp.vercel.app/nomad/docs/job-specification/parameterized#interactions-with-periodic
=> [gh-24311] Expand on documentation about jobs that are both parameterised and periodic

.github/workflows/release.yml, GNUmakefile
In the past the `make changelog` command expected `v`-prefixed `LAST_VERSION`, but now it doesn't. The regular expression we had in the release workflow did not account for this and thus the changelog update didn't work correctly.
=> release: fix typo in the LAST_RELEASE sed regex

.changelog/24399.txt, client/allocrunner/taskrunner/template/template.go, client/allocrunner/taskrunner/template/template_test.go
When multiple templates with api functions are included in a task, it's possible for consul-template to re-render templates as it creates watchers, overwriting render event data. This change uses event fields that do not get overwritten, and only executes the change mode for templates that were actually written to disk.
Fixes: [#24140](https://github.com/hashicorp/nomad/issues/24140)
=> fix: handle template re-renders on client restart

nomad/fsm.go
When we removed the time table in #24112 we introduced a bug where if a previous version of Nomad had written a time table entry, we'd return from the restore loop early and never load the rest of the FSM. This will result in a mostly or partially wiped state for that Nomad node, which would then be out of sync with its peers (which would also have the same problem on upgrade).
The bug only occurs when the FSM is being restored from snapshot, which isn't the case if you test with a server that's only written Raft logs and not snapshotted them.
While fixing this bug, we still need to ensure we're reading the time table entries even if we're throwing them away, so that we move the snapshot reader along to the next full entry.
Fixes: https://github.com/hashicorp/nomad/issues/24411
---
To …
=> fsm: fix bug in snapshot restore for removed timetable

drivers/shared/capabilities/defaults.go, drivers/shared/executor/executor.go, go.mod, go.sum
github.com/moby/sys/capability is a fork of the (no longer maintained)
github.com/syndtr/gocapability package.
For changes since the fork took place, see
https://github.com/moby/sys/blob/main/capability/CHANGELOG.md
=> deps: switch to moby/sys/capability

.changelog/24432.txt, command/volume_status_csi.go
The `volume status :id` command outputs the namespace for a CSI volume twice. Drop the second output.
Ref: https://github.com/hashicorp/nomad/pull/24382#discussion_r1837097250
=> csi: remove redundant namespace field from volume status output

nomad/fsm.go
As @tgross noticed in #24412, we never handled `EventSinkSnapshot` correctly. We should error on this snapshot type, since it should never be encountered in prod Nomad clusters.
=> fsm: handle EventSinkSnapshot type correctly

.changelog/24442.txt, nomad/encrypter.go, nomad/encrypter_test.go
Clusters that have gone through several upgrades have be found to include keyring material which has an empty RSA block.
In more recent versions of Nomad, an empty RSA block is omitted from being written to disk. This results in the panic not being present. Older versions, however, did not have this struct tag meaning we wrote an empty JSON block which is not accounted for in the current version.
Spot check for this locally in the code:
```
ag "WrappedRSAKey != nil {"
```
```
ag "WrappedRSAKey != nil && "
nomad/encrypter.go
480:		if wrappedKey.WrappedRSAKey != nil && len(wrappedKey.WrappedRSAKey.Ciphertext) > 0 {
808:	if kekWrapper.WrappedRSAKey != nil && len(kekWrapper.WrappedRSAKey.Ciphertext) > 0 {
```
closes #24441 
related https://github.com/hashicorp/nomad/pull/24383
changelog entry …
=> keyring: Fix a panic when decrypting aead with empty RSA block.

dev/hooks/pre-push
Our git pre-push hook already prevents Nomad Enterprise code from getting pushed anywhere but its own repo. But this hook only works for files on the current worktree (checkout). Were you to fetch an Enterprise tag into your local Community Edition repo but not have it checked out, and then `git push --tags`, you'd push that tag and the associated commit history.
Add tag filtering to the pre-push hook to prevent Enterprise tags (and the older `+pro` SKU) tags from getting pushed to the Community Edition repo.
To test from any CE checkout:
```
$ git tag v1.20.0+ent
$ git push --tags
```
(and then cleanup via `git tag -d v1.20.0+ent`)
=> tools: filter Nomad Enterprise tags in pre-push hook

drivers/shared/capabilities/defaults.go
In #24093 we moved from github.com/syndtr/gocapability to github.com/moby/sys/capability due to the former package no longer being maintainer. The new package's capability function works differently: the known/supported functionality is split now, and the `.ListSupported()` call will always return an empty list on non-linux systems. This means Nomad agents won't start on darwin or windows.
=> drivers: fix capabilities on non-linux systems

.changelog/24363.txt, e2e/scaling/input/namespace_default_system.nomad, e2e/scaling/scaling.go, nomad/job_endpoint.go, nomad/job_endpoint_test.go, nomad/structs/structs.go
This PR introduces the possibility to temporarily stop a system job by scaling it to 0 and then restart it again by scaling it back up to 1, without having to resubmit it.
=> Allow scaling system jobs to 0

.changelog/24409.txt, client/vaultclient/vaultclient.go
The errors we get aren't wrapped by the Vault SDK, so unfortunately we have to read the error messages and can't easily enumerate non-fatal error messages (which might be bubbling up from the stdlib). I've audited the errors currently used and have documented their source.
Ref https://github.com/hashicorp/vault/blob/52ba156d47da170bf40471fe57d72522030bdc7e/vault/expiration.go#L1327
Fixes: https://github.com/hashicorp/nomad/issues/23859
=> vault: catch expired lease as fatal error

client/lib/nsutil/netns_linux.go
User of `nsutil` library should be able to do the following and for it to work:
```
var errno syscall.Errno
if errors.As(err, &errno) {
if errno == unix.EBUSY { ... }
}
```
This commit fixes that issue.
Call the function and try to do errors.As error handling, it won't work.
...
=> nsutil: wrap error that comes from the syscall so caller can do errors.As

.changelog/24410.txt, client/allocrunner/taskrunner/consul_hook.go
When a task restarts, the Nomad client may need to rewrite the Consul token, but it's created with permissions that prevent a non-root agent from writing to it. While Nomad clients should be run as root (currently), it's harmless to allow whatever user the Nomad agent is running as to be able to write to it, and that's one less barrier to rootless Nomad.
(Note that the Vault token already has `u+rw` permissions.)
Ref: https://github.com/hashicorp/nomad/issues/23859#issuecomment-2465757392
=> consul: allow non-root Nomad to rewrite token

.changelog/24466.txt, ui/app/adapters/job.js
Resolves #24444 
I was using a custom `+=`-based url modifier to add the `?diffVersion` to the query to get job versions, ignoring that this was also happening in a nested `addToPath` method if other query params were inherently present — which is the case if the job has a non-default namespace.
This resulted in a url like `job/:jobid/versions?namespace=myNS?diffs=true&diffVersion=3`
This PR fixes the double `?` and lets the well-vested addToPath() handle all relevant URL param appending.
To test, try applying a namespace, running a job within it, making a new version of it, and checking out the versions page. Before, you'd get 404s and "No changes"; now you should get 200s and version changes.
=> [ui] Fixes double-namespace-query-param when getting versions

.changelog/24319.txt, client/allocrunner/networking_cni.go, client/allocrunner/networking_cni_test.go, website/content/docs/networking/cni.mdx
Tihs PR adds nomad workload information to CNI_ARGS when a `cni/*` is used (not for the `bridge` network which also uses CNI). This information can be used by CNI plugins to correlate the assigned IP to nomad workloads/allocations (among other things).
Fixes #23830
=> Add Nomad workload information to CNI args

.changelog/24489.txt, command/agent/http.go, command/agent/http_test.go
This PR addresses an XSS vulnerability where Nomad agents wouldn't explicitly set content type headers for error responses. 
Internal ref: https://hashicorp.atlassian.net/browse/SECVULN-14567
=> agent: set content type header explicitly

command/agent/host_volume_endpoint_test.go, command/volume_create_host_test.go, command/volume_delete_host_test.go, command/volume_status_host_test.go, helper/funcs.go, helper/funcs_test.go, nomad/host_volume_endpoint.go, nomad/host_volume_endpoint_test.go, nomad/mock/host_volumes.go, nomad/state/state_store_host_volumes.go, nomad/structs/host_volumes.go, nomad/structs/host_volumes_test.go
Add several validation steps in the create/register RPCs for dynamic host volumes. We first check that submitted volumes are self-consistent (ex. max capacity is more than min capacity), then that any updates we've made are valid. And we validate against state: preventing claimed volumes from being updated and preventing placement requests for nodes that don't exist.
Ref: https://github.com/hashicorp/nomad/issues/15489
=> dynamic host volumes: create/register RPC validation

client/allocrunner/taskrunner/remotetask_hook.go
Driver capabilities and ECS driver were deprecated in 1.9; marking this in a similar way for future removal. 
=> client: mark the remote_task hook as deprecated.

.changelog/24513.txt, command/agent/consul/service_client.go
When the service client syncs to Consul, we accumulate service sync errors in a multierror before reading all the local checks. If the API call to the local checks fails, we either return that error or append it to the multierror and return the set of errors. But `multierror.Error.Len()` doesn't nil-check, so we need to do this ourselves.
I've also made a quick pass through the rest of the code base looking for multierror `Len` method calls to see if we have this pattern elsewhere.
Fixes: https://github.com/hashicorp/nomad/issues/24512
=> consul: handle nil multierror pointer correctly

.changelog/24494.txt, drivers/shared/executor/procstats/list_test.go, drivers/shared/executor/procstats/list_windows.go, drivers/shared/executor/procstats/procstats.go
In Nomad 1.7 much of the process management code was refactored, including
a rewrite of how the process tree of an executor was determined on Windows
machines. Unfortunately that rewrite has been cursed with performance issues
and bugs. Instead, revert to the logic used in [v1.6.10](https://github.com/hashicorp/nomad/blob/v1.6.10/drivers/shared/executor/pid_collector.go#L84).
Fixes #23984
=> windows: revert process listing logic to that of v1.6.10

.changelog/24456.txt, nomad/core_sched.go, nomad/core_sched_test.go, nomad/system_endpoint_test.go
This PR fixes a bug where `System.GarbageCollect` endpoint didn't work on objects that weren't older than their respective GC thresholds. `System.GarbageCollect` is used to force garbage collection (also used by the `system gc` command) and should ignore any GC threshold settings. 
Fixes #24455
Internal ref: https://hashicorp.atlassian.net/browse/NET-11747
=> scheduler: fix a bug where force GC wasn't respected

command/agent/host_volume_endpoint_test.go, command/volume_create_host_test.go, nomad/host_volume_endpoint.go, nomad/host_volume_endpoint_test.go, nomad/state/state_store_host_volumes.go, nomad/structs/host_volumes.go, scheduler/context.go, scheduler/feasible.go, scheduler/feasible_test.go
When making a request to create a dynamic host volume, users can pass a node pool and constraints instead of a specific node ID.
This changeset implements a node scheduling logic by instantiating a filter by node pool and constraint checker borrowed from the scheduler package. Because host volumes with the same name can't land on the same host, we don't need to support `distinct_hosts`/`distinct_property`; this would be challenging anyways without building out a much larger node iteration mechanism to keep track of usage across multiple hosts.
=> dynamic host volumes: node selection via constraints

.changelog/24415.txt, client/lib/numalib/detect_linux.go, client/lib/numalib/detect_linux_test.go, client/lib/numalib/hw/speeds.go
Relates to: #19468
Within one of our production sites we are running on a mixed server fleet, where some are running baremetal Nomad and others are part of the virtualised fleet. We noticed a big difference in the reported CPU . On the baremetal systems they were using the boost clock at 3.5 GHz whereas on the virtualised load they were using the QEMU default for dmidecode at 2GHz
```
nomad version
Nomad v1.8.2
BuildDate 2024-07-16T08:50:09Z
Revision 7f0822c1e4f25907d9f60e2d595411950dd1bd28
```
```
grep -H . /sys/devices/system/cpu/cpu0/cpufreq/*
/sys/devices/system/cpu/cpu0/cpufreq/affected_cpus:0
/sys/devices/system/cpu/cpu0/cpufreq/bios_limit:2450000
/sys/devices/system/cpu/cpu0/cpufreq/cpb:1
/sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_cur_freq:2450000 …
```
=> client: fixed a bug where AMD CPUs were not correctly fingerprinting base speed

.changelog/24304.txt, client/lib/cgroupslib/partition_linux.go, nomad/structs/funcs_test.go, nomad/structs/structs.go, nomad/structs/structs_test.go
In our production environment where we run Nomad on `v1.8.2` we noticed overlapping cpusets and the Nomad reserve/share slices being out of sync. Specifically, the below setup where we have various task in `prestart` and `poststart` that are part of the `main` lifecycle.
I managed to reproduce it with the below job spec on the latest main (v1.9.1) in my sandbox environment :
```hcl
job "redis-job-{{SOME_SED_MAGIC}}" {
type = "service"
group "cache" {
count = 1
task "redis" {
config {
image = "redis:3.2"
}
resources {
cores = 4
}
}
task "redis-start-side" {
lifecycle {
hook    = "poststart"
sidecar = true
}
config {
image = "redis:3.2"
}
resources {
cores = 4
}
}
}
}
```
Spinning up two jobs with this spec resulted in the following overlap :
``` …
```
=> scheduler: take all assigned cpu cores into account instead of only those part of the largest lifecycle

.changelog/24522.txt, e2e/csi/input/plugin-aws-ebs-controller.nomad, e2e/csi/input/plugin-aws-ebs-nodes.nomad, nomad/structs/node.go, nomad/structs/node_test.go
CSI volume is created with following topology
```
"Topologies": [
null,
{
"Segments": {
"topology.kubernetes.io/zone": "us-east-1a"
}
}
],
```
and Node Accessible Topology is reported as 
```
"6befce82-c4e5-8509-55ad-3b69bde1fa22": {
"AllocID": "b6b6f136-d4c4-691e-47b6-330e1fbf4c4f",
"HealthDescription": "healthy",
"Healthy": true,
"NodeInfo": {
"AccessibleTopology": {
"Segments": {
"topology.kubernetes.io/zone": "us-east-1a",
"kubernetes.io/os": "linux",
"topology.ebs.csi.aws.com/zone": "us-east-1a"
}
},
"ID": "i-05feecab254e44c60",
"MaxVolumes": 26,
"RequiresNodeStageVolume": true,
"SupportsCondition": false,
"SupportsExpand": true,
"SupportsStats": true
},
"PluginID": "aws-ebs",
"RequiresControllerPlugin": true,
"RequiresTopologies": true,
"UpdateTime": "2024-11-20T21:41:43.593062188Z" …
```
=> Fix CSITopology matching logic for csi storage driver

client/host_volume_endpoint_test.go, client/hostvolumemanager/host_volume_plugin.go, client/hostvolumemanager/host_volume_plugin_test.go, client/hostvolumemanager/test_fixtures/test_plugin.sh, client/hostvolumemanager/test_fixtures/test_plugin_sad.sh, nomad/structs/host_volumes.go, nomad/structs/host_volumes_test.go
adding tests for #24497 
also happened to notice we weren't validating that volume ID was uuid-shaped, so add that too.
main issue: #24479
=> dynamic host volumes: test client RPC and plugins

.changelog/24540.txt, command/agent/host/host.go, command/agent/host/host_test.go, website/content/docs/configuration/client.mdx, website/content/docs/upgrade/upgrade-specific.mdx
Our `env.denylist` should by default be more comprehensive. 
Internal reference: https://hashicorp.atlassian.net/browse/SECVULN-14555
=> security: a more comprehensive env.denylist

api/contexts/contexts.go, nomad/search_endpoint.go, nomad/search_endpoint_test.go, nomad/state/state_store_host_volumes.go, nomad/state/state_store_host_volumes_test.go, nomad/structs/search.go
Add support for dynamic host volumes to the search endpoint. Like many other objects with UUID identifiers, we're not supporting fuzzy search here, just prefix search on the fuzzy search endpoint.
Because the search endpoint only returns IDs, we need to seperate CSI volumes and host volumes for it to be useful. The new context is called `"host_volumes"` to disambiguate it from `"volumes"`. In future versions of Nomad we should consider deprecating the `"volumes"` context in lieu of a `"csi_volumes"` context.
---
To test end-to-end, create sufficient volumes to have at least 2 matching prefix characters in the ID (this may take quite a few tries!).
```
$ nomad volume create ./demo/hostvolume/host.volume.hcl
Created host volume test with ID …
```
=> dynamic host volumes: search endpoint

client/allocrunner/networking_iptables_test.go, client/allocrunner/taskrunner/sids_hook_test.go, client/allocrunner/taskrunner/task_runner_test.go, drivers/shared/executor/executor_test.go
I'm a heavy LSP user and I frequently goto:next_error. This confuses my editor on macOS.
=> goflags: go:build linux for tests that won't compile on other platforms

.changelog/24561.txt, command/agent/retry_join.go, command/agent/retry_join_test.go
The retry_join logic was not allowing for retries to happen and was exiting after the first failed discovery attempt. This change fixes that behaviour and adds a test to ensure no further regressions.
Closes: https://github.com/hashicorp/nomad/issues/24560
Jira: https://hashicorp.atlassian.net/browse/NET-11821
in the majority of situations. The main exceptions are long-lived feature branches or …
=> agent: Fix a bug where retry_join was not retrying.

api/host_volumes.go, command/agent/host_volume_endpoint_test.go, command/volume_create_host.go, command/volume_register_host.go, nomad/fsm.go, nomad/host_volume_endpoint.go, nomad/host_volume_endpoint_ce.go, nomad/host_volume_endpoint_test.go, nomad/search_endpoint_test.go, nomad/state/state_store_host_volumes.go, nomad/state/state_store_host_volumes_test.go, nomad/structs/host_volumes.go
Most Nomad upsert RPCs accept a single object with the notable exception of CSI. But in CSI we don't actually expose this to users except through the Go API. It deeply complicates how we present errors to users, especially once Sentinel policy enforcement enters the mix.
Refactor the `HostVolume.Create` and `HostVolume.Register` RPCs to take a single volume instead of a slice of volumes.
Add a stub function for Enterprise policy enforcement. This requires splitting out placement from the `createVolume` function so that we can ensure we've completed placement before trying to enforce policy.
=> dynamic host volumes: Enterprise stubs and refactor API

.changelog/24538.txt, drivers/shared/executor/utils.go
Fixes a bug reported by Windows users where Nomad was killing random processes on reboot.  This was due to the reattach config containing a PID and RPC address that was now occupied by other processes/listeners.  When Nomad would attempt to make an RPC, it would fail, and kill the process. With this change, we fail early on reattach, and do not kill the process.
Reproduction involves simulating this scenario via overriding the reattach PID when starting a task to a known PID (another bash session), rebooting Nomad, killing the executor process, and listening on the reattach address.
Fixes [GH #23969](https://github.com/hashicorp/nomad/issues/23969)
and job configuration, please update the  Nomad website …
=> executor: fail early on reattach if listener is not executor

.github/workflows/release.yml
We are shoring up our user and bot accesses, and this seems to be our only usage of the github-actions bot.
These were the commits that have been flagged as needing adjustment:
```
workflows/release.yml
145:            git commit --message "Generate files for ${{ github.event.inputs.version }} release"
212:            git commit --message 'Prepare for next release'
```
We may later discover other of our repos that need a similar treatment, if they've just not been run during this information-gathering time, but at present this is the only known case.  Our CE->ENT merge workflow in the ENT repo is already set up properly.
=> release: always use service user for git ops

.changelog/24495.txt, drivers/exec/driver.go, drivers/exec/driver_test.go, drivers/java/driver.go
If an error occurs before a task is started, but after this executor process is created, the executor must be explicity stopped.  This change updates the logic in StartTask so launching the task happens immediately after creating the executor.
Run a job with a configuration that would fail after the executor process has started, but before the task is launched.  For example, an exec task with `cap_add = ["net_raw"]`.  After the job fails, the executor process will still be running.
Fixes [GH #11958](https://github.com/hashicorp/nomad/issues/11958)
the [website README](../website/README.md) for docs guidelines. …
=> drivers: update ordering of events in StartTask to fix executor leak

command/volume_create_host.go
In #24528 we added monitoring to the CLI for dynamic host volume creation. But when the volume's namespace is set by the volume specification instead of the `-namespace` flag, the API client doesn't have the right namespace and gets a 404 when setting up the monitoring. The specification always overrides the `-namespace` flag, so use that when available for all subsequent API calls.
=> dynamic host volumes: set namespace from volume spec when monitoring

api/host_volumes.go, command/volume_create.go, command/volume_create_host.go, command/volume_register.go, command/volume_register_host.go
The create/register volume RPCs support a policy override flag for soft-mandatory Sentinel policies, but the CLI and Go API were missing support for it.
Also add support for Sentinel warnings to the Go API and CLI.
---
Testing with the following policy file:
```hcl
has_tag = func() {
print("volume is missing tag")
tag = volume.parameters["tag"] else 0
return tag is not 0
}
main = rule { has_tag() }
```
After applying this branch on top of https://github.com/hashicorp/nomad-enterprise/pull/2087:
```sh
$ nomad sentinel apply -scope=submit-volume -level=soft-mandatory no-untagged-volumes ./policy.hcl
Successfully wrote "no-untagged-volumes" Sentinel policy!
$ nomad volume create ./demo/hostvolume/host.volume.hcl
Error creating volume: …
```
=> dynamic host volumes: policy-override flag on CLI

.github/workflows/test-ui.yml, scripts/combine-ui-test-results.js, ui/app/index.html, ui/test-reporter.js, ui/testem.js, ui/tests/acceptance/variables-test.js
Our `ember-test-audit` action is currently failing, and I'm using that as an excuse to improve our front-end testing story generally.
This will be a two-step approach, and this PR is the first step:
1. Save artifacts, including test timing, from `test-ui` test results on merge to `main`
2. Compare to a rolling window of these test results on subsequent PRs
This PR adds artifact uploads on the back of `test-ui`. Because those are partitioned/run concurrently 4x, part of this is combining those.
The artifact generated looks like this:
```
{
"timestamp": "2024-12-02T18:20:59.531Z",
"sha": "7fd10531ef3e12672a19a7a9aa7a6e4f4f874614",
"summary": {
"total": 1606,
"passed": 1606,
"failed": 0
},
"duration": 841403,
"tests": [
{
"name": "Acceptance | allocation fs: it passes an accessibility …
```
=> [ui, ci] retain artifacts from test runs including test timing

nomad/structs/acl.go, nomad/structs/event.go
There are several places where we want to redact the secret ID of an ACL token, some of which are in the Enterprise code base for Sentinel. Add a new method `Sanitize` that mirrors the one we have on `Node`.
This changeset doesn't change any existing behavior, just makes it easier to reuse.
Ref: https://github.com/hashicorp/nomad-enterprise/pull/2087
=> helper: sanitize method on ACL token object

.changelog/24601.txt, api/sentinel.go, command/sentinel_apply.go
When we add a Sentinel scope for dynamic host volumes, having a default `-scope` value for `sentinel apply` risks accidentally adding policies for volumes to the job scope. This would immediately prevent any job from being submitted. Forcing the administrator to pass a `-scope` will prevent accidental misuse.
Ref: https://github.com/hashicorp/nomad-enterprise/pull/2087
=> sentinel: remove default scope for Sentinel apply command

nomad/host_volume_endpoint.go, nomad/host_volume_endpoint_test.go
Node fingerprints include attributes for the host volume plugins, including the built-in plugins. Add an implicit constraint on this fingerprint during volume placement to ensure we only place volumes on hosts with the right plugins.
=> dynamic host volumes: add implicit constraints on plugin fingerprint

.github/workflows/checks.yaml
Pushing a cache bundle from a self-hosted runner may be causing file permission issues when unpacking the bundle in later tests. This attempts to fix that issue by only pushing a bundle from Github hosted runners.
=> ci: only cache from github hosted runners to avoid file perm issues

api/host_volumes.go, command/agent/host_volume_endpoint.go, command/volume_delete.go, nomad/fsm.go, nomad/host_volume_endpoint.go, nomad/host_volume_endpoint_test.go, nomad/state/state_store_host_volumes.go, nomad/state/state_store_host_volumes_test.go, nomad/structs/host_volumes.go
the `Delete` side of #24545 which did this for `Create` and `Register` -- `id string` instead of `ids []string`
=> dynamic host volumes: delete by single volume ID

command/agent/csi_endpoint.go, command/agent/http.go, command/agent/volumes_endpoint.go
The List Volumes API was originally written for CSI but assumed we'd have future volume types, dispatched on a query parameter. Dynamic host volumes uses this, but the resulting code has host volumes concerns comingled in the CSI volumes endpoint. Refactor this so that we have a top-level `GET /v1/volumes` route that's shared between CSI and DHV, and have it dispatch to the appropriate handler in the type-specific endpoints.
---
I did extra testing of this by running the hostpath CSI plugin demo and creating a bunch of host volumes, and verifying the CLI worked as expected for both.
=> dynamic host volumes: refactor HTTP routes for volumes list dispatch

nomad/state/state_store_host_volumes.go, scheduler/feasible.go, scheduler/feasible_test.go, scheduler/scheduler.go, scheduler/stack.go
Static host volumes have a simple readonly toggle, but dynamic host volumes have a more complex set of capabilities similar to CSI volumes. Update the feasibility checker to account for these capabilities and volume readiness.
Also fixes a minor bug in the state store where a soft-delete (not yet implemented) could cause a volume to be marked ready again. This is needed to support testing the readiness checking in the scheduler.
=> dynamic host volumes: capabilities check during scheduling

nomad/structs/diff_test.go, nomad/structs/volumes.go, nomad/structs/volumes_test.go
This changeset adds `Sticky` property to task group Volumes block, which will later be used by stateful deployments.
=> stateful deployments: add Sticky property to task group volumes

.changelog/24642.txt, nomad/structs/actions.go, nomad/structs/actions_test.go
Lifts the naming restriction on task actions so that you can put user-friendly emoji in there if you were so inclined.
=> Character restrictions in action names were unduly oppressive

command/asset/asset.go, command/asset/volume.csi.hcl, command/asset/volume.csi.json, command/asset/volume.host.hcl, command/asset/volume.host.json, command/volume_init.go
Adds a `-type` flag to the `volume init` command that generates an example volume specification with only those fields relevant to dynamic host volumes. This changeset also moves the string literals into uses of `go:embed`
=> dynamic host volumes: add -type flag to volume init

.changelog/24644.txt, api/api.go, e2e/terraform/provision-nomad/etc/nomad.d/base.hcl
In #16872 we added support for unix domain sockets, but this required mutating the `Config` when parsing the address so as to remove the port number. In #23785 we fixed a bug where if the configuration was used across multiple clients (as in the autoscaler) that mutation would happen multiple times and the address would be incorrectly parsed.
When making `alloc log`, `alloc fs`, or `alloc exec` calls where we have line-of-sight to the client, we attempt to make a HTTP API call directly to the client node. So we create a new API client from the same configuration and then set the address. But in this case we copy the private `url` field and that causes the URL parsing to be skipped for the new client.
This results in the region always being set to the string literal `"global"` (because of …
=> Allocation API: fix "no path to region" errors for non-global regions

.changelog/24683.txt, command/agent/node_endpoint.go, nomad/alloc_endpoint.go, nomad/structs/structs.go
Sanitize the Allocations SignedIdentities to prevent privilege escalation within a namespace through unauthorized impersonation of [workload associated with ACL policies](https://developer.hashicorp.com/nomad/docs/concepts/workload-identity#workload-associated-acl-policies) in any workload within the namespace. 
This resolves CVE-2024-12678.
Current tests are passing.
https://github.com/hashicorp/nomad-enterprise/pull/2098 …
=> sec: fix alloc workload identity namespace permission

.changelog/24620.txt, ui/app/components/job-status/panel/steady.js, ui/app/models/job.js, ui/tests/acceptance/jobs-list-test.js
Found a fun UI bug today: my system job had allocations fail, and then I worked on something else for several hours, and the garbage collector subsequently removed my terminal allocs.
When viewing the job in the UI, the job showed up as "Scaled Down". This is a new status we added [this summer](https://github.com/hashicorp/nomad/pull/23829) to help show when an operator manually set a job's group counts to 0 to let it sit dormant.
While there are problems with showing an alloc-less system job as "Failed" (it may in fact have been deliberately "scaled down" by virtue of taking all eligible nodes offline, for example), this seems like it's by far the most common reason you'd have an un-GC'd system job with no allocs, and so "Scaled Down" shouldn't be the default label for it. This PR makes …
=> [ui] Fixes an issue where system jobs' status were set to Scaled Down when their allocs get garbage collected

ui/package.json, ui/yarn.lock
Pins cross-spawn to a healthy version. Yarn will complain that it's incongruent, but the major version upgrade appears to cause no issues and reading through their upgrade notes, it's only to disable support for a very old version of node (8)
Resolves https://github.com/hashicorp/nomad/security/code-scanning/758
Resolves https://github.com/hashicorp/nomad/security/code-scanning/759
Resolves https://github.com/hashicorp/nomad/security/code-scanning/760
Resolves https://github.com/hashicorp/nomad/security/code-scanning/761
=> [ui] Resolutions for code-scanner/dependabot alerts in UI

e2e/terraform/nomad.tf, e2e/terraform/provision-nomad/etc/nomad.d/base.hcl, e2e/terraform/provision-nomad/main.tf, e2e/terraform/provision-nomad/tls.tf, e2e/terraform/provision-nomad/variables.tf, e2e/terraform/terraform.tfvars, e2e/terraform/variables.tf
In #24644 we set the region to "e2e" but forgot to setup the TLS certificate names appropriately. Swap the region out for a variable instead.
=> E2E: use a variable for region

.changelog/24668.txt, ui/app/controllers/jobs/job/index.js
Resolves #24666
We had a bug where our `watchChildJobs` ember concurrency task (which kicks off whenever you hit a parameterized/periodic parent job route) would have a memoized list of childjobs from whenever it was last run. These components are not route-bound, and so don't shed data automatically when their route changes, and since we don't return a `[]` on /statuses with an ?index=1 parameter, but instead hold the blocking query open for further updates, we don't get any kind of "Clear what the app has in cache" signal.
This explicitly clears what the app has in cache on parent job route load.
=> [ui] Bugfix: prevent parent job from showing another job's dispatches when it has none

.changelog/24649.txt, client/rpc.go, client/rpc_test.go
Nomad sets a default port when resolving server addresses that don't have one. When we get a "bare" IPv6 address without a port, we end up with an unexpected error "too many colons in address" when we try to split the address and host, because the standard library function expects IPv6 addresses to be wrapped in brackets as recommended by RFC5952. User-configured addresses avoid this problem by accepting IP address and port as separate configuration values, but go-discover emits "bare" IPv6 addresses without a port in IPv6 environments.
Fix this by adding brackets to IPv6 addresses when we get the "too many colons" error from the stdlib. This will still give erroneous results if the address includes the port but is missing brackets, but there's no way to unambiguously parse that address. …
=> discovery: correctly handle IPv6 addresses from go-discover

nomad/structs/host_volumes.go, nomad/structs/host_volumes_test.go, nomad/structs/volumes.go, nomad/structs/volumes_test.go
CSI volumes support multi-node access patterns on the same volume ID, but dynamic host volumes by nature do not. The underlying volume may actually be multi-node (ex. NFS), but Nomad is ignorant of this. Remove the CSI-specific multi-node access modes and instead include the single-node access modes that are currently in the alpha edition of the CSI spec but which are better suited for DHV.
This PR has been extracted from #24684 to keep reviews manageable.
Ref: https://github.com/hashicorp/nomad/pull/24684
=> dynamic host volumes: remove multi-node access modes

.github/workflows/lock.yml
The parameters used for the reusable action were incorrect since the 5.0.1 update. The permissions were also incorrect as the workflow needs to write to issues and PRs.
=> github: Fix lock threads syntax and permissions.

.changelog/24622.txt, ui/app/templates/components/job-editor/edit.hbs
This PR will show the text area for entering HCL variable values on job submission, as suggested in #23582.
It was already shown when editing a job using the UI, but not when submitting a new job.
The underlying model already supports the this, only the UI was missing.
- Submit a new job using variables
- Enter the variables in the new text area below the job spec
- Github Issue: #23582
in the …
=> Show HCL variable input on job submission.

client/fingerprint/dynamic_host_volumes.go, client/fingerprint/dynamic_host_volumes_test.go, client/hostvolumemanager/host_volume_plugin.go, client/hostvolumemanager/host_volume_plugin_test.go, client/hostvolumemanager/test_fixtures/test_plugin.sh, demo/hostvolume/_test-plugin.sh, demo/hostvolume/example-plugin-mkfs, nomad/host_volume_endpoint.go, nomad/host_volume_endpoint_test.go
Instead of a plugin `version` subcommand that responds with a string (established in #24497), respond to a `fingerprint` command with a data structure that we may extend in the future (such as plugin capabilities, like size constraints?). In the immediate term, it's still just the version: `{"version": "0.0.1"}`.
In addition to leaving the door open for future expansion, I think it will also avoid false positives detecting executables that just happen to respond to a `version` command.
This also reverses the ordering of the fingerprint string parts
from `plugins.host_volume.version.mkdir` (which aligned with CNI plugins)
to `plugins.host_volume.mkdir.version`.
Since this is a breaking change, any fine folks out there who have copied `example-plugin-mkfs` from the demo dir will need to …
=> dynamic host volumes: tweak plugin fingerprint

scheduler/feasible.go, scheduler/feasible_test.go, scheduler/generic_sched_test.go
When we feasibility check a dynamic host volume against a volume request, we check the attachment mode and access mode. This only ensures that the capabilities match, but doesn't enforce the semantics of the capabilities against other claims that may be made on the allocation.
Add support for checking the requested capability against other allocations that the volume claimed.
=> dynamic host volumes: account for other claims in capability check

nomad/structs/volumes.go, nomad/structs/volumes_test.go
This changeset adds an additional validation that prevents users from setting `per_alloc` and `sticky` flags on volume requests. 
=> stateful deployments: validate there are no sticky per_alloc volume requests

e2e/cni/cni_test.go, e2e/cni/input/cni_args.nomad.hcl, e2e/jobsubmissions/jobsubapi_test.go
=> e2e: Update e2e tests to match new e2e infra Nomad region name.

CHANGELOG.md
=> created changelog for 1.8.8

website/content/docs/concepts/job.mdx
The clone and edit tutorial has been published, so I am adding a link to that tutorial in the Job concept page's clone/edit section. This is a 1.9.4 feature.
I also cleaned up a few typos.
Jira: [CE-801]
Deploy preview: https://nomad-git-ce801-hashicorp.vercel.app/nomad/docs/concepts/job#clone-and-edit
in the majority of situations. The main exceptions are long-lived feature branches or merges …
=> Docs: Add link to published clone and edit tutorial

website/content/docs/job-specification/disconnect.mdx, website/data/docs-nav-data.json
Change `stop_after` to `stop_on_client_after`.
Update examples.
Move `disconnect` entry to correct alphabetical order in nav.
Looks like the code change was part of 1.8, so not backporting to 1.7.
Jira: [CE-800]
GH Issue: https://github.com/hashicorp/nomad/issues/24702
[Deploy preview](https://nomad-git-ce800-hashicorp.vercel.app/nomad/docs/job-specification/disconnect)
in the majority of …
=> Docs: change stop_after to stop_on_client_after

nomad/state/deployment_events_test.go, nomad/state/events.go, nomad/state/events_test.go, nomad/state/state_store_host_volumes.go, nomad/stream/event_broker.go, nomad/structs/event.go, website/content/api-docs/events.mdx
Add a new topic to the event stream for host volumes. We'll emit events when a dynamic host volume is registered or deregistered, and whenever a node fingerprints with a changed volume.
Ref: https://hashicorp.atlassian.net/browse/NET-11549
CSI will be done in a separate PR.
In addition to the unit tests, you can use `nomad operator api "/v1/event/stream?topic=HostVolume"` to poll for host volume events while running the host volume demo [setup script](https://github.com/hashicorp/nomad/blob/main/demo/hostvolume/setup.sh) …
=> event stream: add events for dynamic host volumes

.changelog/24724.txt, nomad/state/events.go, nomad/state/events_test.go, nomad/state/schema.go, nomad/state/state_store.go, nomad/state/state_store_restore.go, nomad/stream/event_broker.go, nomad/structs/event.go, nomad/volumewatcher/volumes_watcher.go, website/content/api-docs/events.mdx
Adds new topics to the event stream for CSI volumes and CSI plugins. We'll emit events when either is created or deleted, and when CSI volumes are claimed.
Ref: https://github.com/hashicorp/nomad/pull/24721
In addition to the unit tests, you can use nomad operator api "/v1/event/stream?topic=CSIVolume" to poll for CSI volume events while running the [host path demo](https://github.com/hashicorp/nomad/tree/main/demo/csi/hostpath). …
=> event stream: add events for CSI volumes and plugins

website/content/docs/job-specification/disconnect.mdx, website/data/docs-nav-data.json
Manual backport 
Replaces https://github.com/hashicorp/nomad/pull/24729
=> Manual Backport of Docs: change stop_after to stop_on_client_after into release/1.8.x

.github/workflows/build.yml
Add `dmidecode` to "recommended" dependencies to improve UX on Linux machines that install Nomad via official packages. 
Resolves [#19382](https://github.com/hashicorp/nomad/issues/19382)
Internal ref: https://hashicorp.atlassian.net/browse/NET-10747
=> build: recommend dmidecode for rpm and deb packages

.changelog/24547.txt, drivers/docker/driver_test.go, drivers/docker/utils.go
when using private registry without any image tag pull get *Invalid reference format* issue
on version 1.9.4 send a job with image with following format:
```
ghcr.service.consul:5000/paperless-ngx/paperless-ng
```
=> docker: Fix a bug where images with port number and no tags weren't parsed correctly

.changelog/24645.txt, client/allocdir/fs_linux.go, website/content/docs/concepts/filesystem.mdx
This adds `noswap` mount option to the `SecretDir` mount.
- Create an allocation that triggers a secret dir creation
(having a hell of a time trying to get tests to run locally so I'm going to rely on GHA to run unit tests (fingers crossed))
todo issue
=> add noswap to secretdir tmpfs

client/hostvolumemanager/host_volume_plugin.go, client/hostvolumemanager/host_volume_plugin_test.go, client/hostvolumemanager/host_volumes.go, client/hostvolumemanager/host_volumes_test.go, client/hostvolumemanager/volume_fingerprint.go, client/hostvolumemanager/volume_fingerprint_test.go, command/agent/config.go, demo/hostvolume/_test-plugin.sh, demo/hostvolume/example-plugin-mkfs
Sprucing things up after the initial push to get it working.
I added test coverage before moving funcs around to ensure no functional changes.
Lots of lines, but hopefully an easy read!
=> dynamic host volumes: client-side tests, comments, tidying

client/client.go, client/hostvolumemanager/host_volumes.go, client/hostvolumemanager/host_volumes_test.go, client/hostvolumemanager/volume_fingerprint.go, client/hostvolumemanager/volume_fingerprint_test.go, client/node_updater.go
Volume name must be unique per node.
For existing static host vols, the scheduler will prevent creation of duplicate names ("no node meets constraints"), and it will similarly prevent duplicate dynamic vols _after_ fingerprint (node re-registration), but we need to prevent concurrent duplicate creation that may happen within a fingerprint interval, too.
Here a lock is set for name+id during `Create` (and restore), then released when `Delete`d to prevent such very-fast or concurrent creates.
If the a volume spec is submitted again with a valid `id` set, it can still update the volume, and the plugin's `Create` will be run with the new spec.  I'm guessing that folks may want to do this if either A) the plugin has been updated and folks want to regenerate their vols in place? or B) to …
=> dynamic host volumes: ensure unique name per node

.changelog/24768.txt, drivers/docker/stats.go, drivers/docker/stats_test.go
The recent change to collection via a "one-shot" Docker API call did not update the stream boolean argument. This results in the `PreCPUStats` values being zero and therefore breaking the CPU calculations which rely on this data. The base fix is to update the passed boolean parameter to match the desired non-streaming behaviour. The non-streaming API call correctly returns the `PreCPUStats` data which can be seen in the added unit test and the soak testing details seen below.
The most recent change also modified the behaviour of the `collectStats` go routine, so that any error encountered results in the routine exiting. In the event this was a transient error, the container will continue to run, however, no stats will be collected until the task is stopped and replaced. This PR reverts …
=> driver/docker: Fix container CPU stats collection

.changelog/24766.txt, api/keyring.go, api/keyring_test.go, command/agent/keyring_endpoint.go, command/agent/keyring_endpoint_test.go, command/operator_root_keyring_remove.go, nomad/keyring_endpoint.go, nomad/keyring_endpoint_test.go, nomad/structs/keyring.go, website/content/api-docs/operator/keyring.mdx, website/content/docs/commands/operator/root/keyring-remove.mdx
This PR adds an additional check in the `Keyring.Delete` RPC to make sure we're not trying to delete a key that's been used to encrypt a variable. It also adds a `-force` flag for the CLI/API to sidestep that check. 
Resolves https://github.com/hashicorp/nomad/issues/24591
Internal ref: https://hashicorp.atlassian.net/browse/NET-11829
=> keyring: warn if removing a key that was used for encrypting variables

command/volume_register_host.go, nomad/host_volume_endpoint.go, nomad/host_volume_endpoint_test.go
When registering a host volume created out-of-band, the volume will have been created on a specific node. Require the node ID field to be set.
Ref: https://github.com/hashicorp/nomad/pull/24789#discussion_r1904690799
=> dynamic host volumes: require node ID on register

.changelog/24723.txt, ui/app/models/agent.js, ui/app/routes/clients.js, ui/app/routes/servers.js, ui/app/services/system.js, ui/app/styles/core/table.scss, ui/app/templates/components/server-agent-row.hbs, ui/mirage/config.js, ui/mirage/factories/agent.js, ui/mirage/scenarios/default.js, ui/tests/acceptance/servers-list-test.js
Resolves #24309 
In a multi-region setup:
In a single-region setup:
=> [ui] Show ALL regions' leaders when viewing servers route

e2e/terraform/packer/ubuntu-jammy-amd64/dnsconfig.sh
When creating the packer images for the e2e tests, the dns is configured on boot to add the default network interfaces available to the instance, but the script didn't account for more than one:
```
IFACE=$(ip route | grep default | awk '{print $5}')
cat <<EOF > /tmp/dnsmasq
port=53
resolv-file=/var/run/dnsmasq/resolv.conf
bind-interfaces
interface=docker0
interface=lo
interface=$IFACE
listen-address=127.0.0.1
server=/consul/127.0.0.1#8600
EOF
```
resulting in configurations like this:
```
port=53
resolv-file=/var/run/dnsmasq/resolv.conf
bind-interfaces
interface=docker0
interface=lo
interface=eth0
interface=ens5
ens6
listen-address=127.0.0.1
server=/consul/127.0.0.1#8600
```
Which caused dnsmasq to fail, draging consul and nomad along with it.
This PR accounts for multiple default …
=> Update the dnsconfig script to handle multiple interfaces

.changelog/24798.txt, client/logmon/plugin.go
This PR is similar to [PR # 24538](https://github.com/hashicorp/nomad/pull/24538) which fixes an edge case on Windows where Nomad would kill random processes on reboot while attempting to reattach to executors.  The problem was reported as half fixed, with Nomad still killing some processes on occasion.  The previous PR did not fix reattaching to the logmon process, which is very similar to reattaching to executors.
Reproduction involves simulating this scenario via overriding the reattach PID when starting a task to a known PID (another bash session), rebooting Nomad, killing the logmon process, and listening on the reattach address.
Fixes [GH #23969](https://github.com/hashicorp/nomad/issues/23969)
and job …
=> plugins: validate logmon process during reattach

nomad/structs/volumes.go, scheduler/feasible.go
Some comment cleanups as we're wrapping up dynamic host volumes work:
* We're not going to implement mount_options for host volumes, as the dynamic host volumes don't have the equivalent of the stage/publish phase that CSI volumes do. Users who want that sort of thing will pass them as `parameter` field during volume create/register.
* The scheduler feasibility check prevents a dynamic host volume being claimed by a job in the wrong namespace, but the comment incorrectly identifies that code path as only being about the race between fingerprint and delete. Update the comment to make the intent clear so that we don't accidentally remove this behavior in the future.
=> dynamic host volumes: cleanup comments

website/content/docs/configuration/acl.mdx, website/content/docs/configuration/audit.mdx, website/content/docs/configuration/autopilot.mdx, website/content/docs/configuration/client.mdx, website/content/docs/configuration/consul.mdx, website/content/docs/configuration/index.mdx, website/content/docs/configuration/keyring/awskms.mdx, website/content/docs/configuration/keyring/azurekeyvault.mdx, website/content/docs/configuration/keyring/gcpckms.mdx, website/content/docs/configuration/keyring/index.mdx, website/content/docs/configuration/keyring/transit.mdx, website/content/docs/configuration/plugin.mdx, website/content/docs/configuration/reporting.mdx, website/content/docs/configuration/search.mdx, website/content/docs/configuration/sentinel.mdx, website/content/docs/configuration/server.mdx, website/content/docs/configuration/server_join.mdx, website/content/docs/configuration/telemetry.mdx, website/content/docs/configuration/tls.mdx, website/content/docs/configuration/ui.mdx, website/content/docs/configuration/vault.mdx, website/data/docs-nav-data.json
- Front matter `description` updates for DevDot search.
- Add intro body paragraph that summarizes page content ("This page..."). This is basically the same verbiage as the front matter `description` but in the body for better Google search indexing.
- Ensure front matter `page_title` and `# <title>` match.
I mostly **did not** edit page content because that's out of scope for this effort. I did some small replacements tho ("see", "below"). Added a few links to pages that didn't have any (orphan pages).
**A member of the Runtime Education team will review all SEO PRs**.
Jira: [CE-775]
Preview: https://nomad-git-ce775-hashicorp.vercel.app/nomad/docs/configuration
and job configuration, please update the  Nomad …
=> Docs SEO: Update Configuration section to improve search

client/hostvolumemanager/host_volumes_test.go
The output of `GetDynamicHostVolumes` is a slice but that slice is constructed from iterating over a map and isn't sorted. Sort the output in the test to eliminate a test flake.
=> testing: fix test flake in dynamic host volume client tests

website/content/docs/job-specification/volume.mdx
The job specification's `volume` block can claim either static or dynamic host volumes. Update the documentation to explain this and cover the additional fields this exposes.
=> docs: jobspec updates for dynamic host volumes

website/content/docs/configuration/client.mdx
Document the client configuration changes needed to support dynamic host volumes. This changeset excludes the plugin specification/concepts, which will be under a separate PR.
=> dynamic host volumes: client configuration docs

.changelog/24785.txt, api/quota.go, api/util_test.go, command/quota_apply.go, command/quota_delete_test.go, command/quota_init.go, command/quota_init_test.go, website/content/docs/upgrade/upgrade-specific.mdx
In anticipation of having quotas for dynamic host volumes, we want the user experience of the storage limits to feel integrated with the other resource limits. This is currently prevented by reusing the `Resources` type instead of having a specific type for `QuotaResources`.
Update the quota limit/usage types to use a `QuotaResources` that includes a new storage resources quota block. The wire format for the two types are compatible such that we can migrate the existing variables limit in the FSM.
Also fixes improper parallelism in the quota init test where we change working directory to avoid file write conflicts but this breaks when multiple tests are executed in the same process.
Ref: https://github.com/hashicorp/nomad-enterprise/pull/2096
Upgrade testing (from the ENT version of this …
=> quotas: refactor storage limit specification

api/host_volumes.go
We changed the list of access modes available for dynamic host volumes in #24705 but neglected to change them in the API package. Update the API package to match.
Ref: https://github.com/hashicorp/nomad/pull/24705
=> API: host volume access modes should match list in structs package

client/fingerprint/dynamic_host_volumes.go, client/hostvolumemanager/host_volume_plugin.go, client/hostvolumemanager/host_volume_plugin_test.go, client/hostvolumemanager/host_volumes.go, client/hostvolumemanager/host_volumes_test.go, client/hostvolumemanager/test_fixtures/test_plugin.sh, demo/hostvolume/_test-plugin.sh, demo/hostvolume/example-plugin-mkfs
Some plugin spec changes based on recent discussion.
* All env prefixed with `DHV_`
* Add: `DHV_VOLUME_ID`, `DHV_PLUGIN_DIR`
* 5 second timeout for `fingerprint` operation
Notice to anyone using the `example-plugin-mkfs` demo plugin: you'll need to copy this changed version of it.
=> dynamic host volumes: plugin spec tweaks

nomad/structs/host_volumes.go, nomad/structs/host_volumes_test.go
When using the register workflow, `capacity_max` is ignored so is likely unset. If the volume is then updated later, the check we had for valid updates assumes that the value was previously. Only perform this check if the value is set.
=> dynamic host volumes: capacity_max may be unset during register

e2e/.gitignore, e2e/terraform/.gitignore, e2e/terraform/provision-infra/.gitignore
In #24694 we did a major refactoring of the E2E Terraform configuration. After deploying a cluster this morning, I noticed a few moved/removed files were not reflected in the .gitignore files. This changeset updates the .gitignore to have no unstaged files after applying.
=> E2E: update .gitignore files to avoid committing runtime files

.changelog/24781.txt, client/serviceregistration/checks/client.go, client/serviceregistration/checks/client_test.go, client/serviceregistration/checks/result.go, client/serviceregistration/checks/result_test.go, nomad/structs/check_test.go, nomad/structs/checks.go, nomad/structs/services.go, website/content/docs/job-specification/check.mdx
Checks within a service using the Nomad provider can now utilise the `tls_skip_verify` parameter.
I tested this locally on macOS running a single Nomad agent (with this change) using additional config to enable the raw_exec driver:
```hcl
plugin "raw_exec" {
config {
enabled = true
}
}
```
I then used the following job specification to test the parameter. Note: you'll need to add your own TLS certificate data to the templates which can be generated using the `nomad tls` command.
<details>
<summary>nomad-server.nomad.hcl</summary>
```hcl
variable "nomad-binary-path" {
type        = string
description = "The path to the Nomad binary to run."
default     = "/Users/jrasell/go/bin/nomad"
}
variable "nomad-region" {
type        = string
description = "The Nomad region identifier to configure …
```
=> services: Support TLS Skip Verify within Nomad service checks.

.changelog/24820.txt, command/agent/command.go, command/agent/syslog.go, command/agent/syslog_test.go
The mapping between Nomad log level identifiers and syslog priorities did not handle the error level string correctly.
The change includes a new function which can be used for lookups in all places the conversion is needed. This function makes the translation easier to test.
Running on a Linux workstation (Ubuntu 24.04) I added the following lines to the `/etc/rsyslog.conf` before restarting rsyslog via `sudo service rsyslog restart`.
```conf
$template verbose, "%syslogseverity-text%, %syslogfacility%, %timegenerated%, %HOSTNAME%, %syslogtag%, %msg%\n"
*.* /var/log/all-messages.log;verbose
```
I then ran Nomad via `sudo -i nomad agent -config=/home/jrasell/config.hcl` using the following configuration to ensure errors are generated in the log:
```hcl
enable_syslog = true
data_dir      = …
```
=> agent: Fixed a bug where syslog error messages marked as notice.

.changelog/24818.txt, ui/app/styles/components/services.scss
Fills the service check marker with a grey when in pending state, whereas it was previously empty. I personally found the empty space a little confusing at first glance, whereas having this addition makes it obvious what is happening with the check and that you can hover and see the status.
I chose the colour based on a quick look, trying to find a grey that wasn't too dark, but I don't really know what I am doing, so please let me know what changes to make.
I think it makes sense to backport. Let me know if you think I should add a changelog entry.
Before:
After:
the [website README](../website/README.md) for docs …
=> ui: Fill service check background object for pending checks.

nomad/state/state_store_host_volumes.go, nomad/state/state_store_host_volumes_test.go, nomad/structs/host_volumes.go, nomad/structs/host_volumes_test.go
Update dynamic host volume validation and update logic to allow for changes to the node pool and plugin ID. If the client's node pool changes we'll sync up the correct node pool for the volumes already placed on that client. We'll also allow the plugin ID to be changed to allow for new versions of plugins supporting the same volume over time.
Ref: https://github.com/hashicorp/nomad/pull/24810#discussion_r1911366838
Ref: https://github.com/hashicorp/nomad/pull/24810#discussion_r1911361745
(Note this PR will conflict with https://github.com/hashicorp/nomad/pull/24857, so whichever one lands last will need rebasing.)
=> dynamic host volumes: allow for node pool and plugin ID changes

nomad/host_volume_endpoint.go, nomad/host_volume_endpoint_ce.go, nomad/host_volume_endpoint_test.go
Enterprise governance checks happen after dynamic host volumes are placed, so if node pool governance is active and you don't set a node pool or node ID for a volume, it's possible to get a placement that fails node pool governance even though there might be other nodes in the cluster that would be valid placements.
Move the node pool governance for host volumes into the placement path, so that we're checking a specific node pool when node pool or node ID are set, but otherwise filtering out candidate nodes by node pool.
This changset is the CE version of ENT/2200.
Ref: https://hashicorp.atlassian.net/browse/NET-11549
Ref: https://github.com/hashicorp/nomad-enterprise/pull/2200
=> dynamic host volumes: move node pool governance to placement filter (CE)

command/asset/volume.host.hcl, nomad/host_volume_endpoint_test.go, nomad/mock/host_volumes.go, nomad/structs/host_volumes.go, nomad/structs/host_volumes_test.go
We can reduce the amount of volume specification configuration many users will need by setting a default capability on a dynamic host volume if none is set. The default capability will allow using the volume in read/write mode on its node, with no further restrictions except those that might be set in the jobspec.
(Note this PR will conflict with https://github.com/hashicorp/nomad/pull/24851, so whichever one lands last will need rebasing.)
=> dynamic host volume: set default capability

website/content/docs/commands/volume/create.mdx, website/content/docs/commands/volume/delete.mdx, website/content/docs/commands/volume/deregister.mdx, website/content/docs/commands/volume/init.mdx, website/content/docs/commands/volume/register.mdx
Dynamic host volumes use some of the same commands as CSI volumes but with different parameters, semantics, and inputs.
=> docs: dynamic host volume command line

.changelog/24865.txt, command/agent/command.go, command/agent/syslog.go, command/agent/syslog_test.go
The agent syslog write handler was unable to handle JSON log lines correctly, meaning all syslog entries when using JSON log format showed as NOTICE level.
This change adds a new handler to the Nomad agent which can parse JSON log lines and correctly understand the expected log level entry.
The change also removes the use of a filter from the default log format handler. This is not needed as the logs are fed into the syslog handler via hclog, which is responsible for level filtering.
Running on a Linux workstation (Ubuntu 24.04) I added the following lines to the `/etc/rsyslog.conf` before restarting rsyslog via `sudo service rsyslog restart`.
```
$template verbose, "%syslogseverity-text%, %syslogfacility%, %timegenerated%, %HOSTNAME%, %syslogtag%, %msg%\n"
*.* …
```
=> agent: Fix a bug where all syslog lines are notice when using JSON

website/content/docs/install/index.mdx
For all HashiCorp tools, the install command has been updated for Fedora. This PR updates the docs to match the install page
=> Update install command for Fedora to match install page

command/agent/command.go, command/agent/command_test.go, command/agent/log_file.go, command/agent/log_file_test.go, command/agent/log_levels.go, command/agent/log_levels_test.go, go.mod, go.sum
The Nomad agent used a log filter to ensure logs were written at the expected level. Since the use of hclog this is not required, as hclog acts as the gate keeper and filter for logging. All log writers accept messages from hclog which has already done the filtering.
Double filtering has been removed from syslog in previous PR's. The full removal in this PR, and from the log file implementation will give this log feature a tiny performance improvement.
The change allows us to remove an external library; albeit a small one.
Can be tested via a dev agent. It touches the agent logging as a whole, so worth trying a few different combinations of level and logging type, especially log-file.
and job configuration, …
=> agent: remove unused log filter and unrequired library.

e2e/volume_mounts/input/volumes.nomad, e2e/volume_mounts/volumes_test.go
The volume_mounts test is flaky due to slow starts from the exec-driver and some incorrect wait code. Refactor the volume_mounts test to use the `e2e/v3` package helpers, and use these to give it enough time to start the exec tasks.
---
Run against a 3-node E2E cluster:
```
$ go test -v -count=1 ./e2e/volume_mounts
=== RUN   TestVolumeMounts
jobs3.go:321: register (service) job: "volumes-247"
jobs3.go:369: checking eval: fb0f3879-8ea9-9763-e3a0-2d0975d727fe, status: pending
jobs3.go:369: checking eval: fb0f3879-8ea9-9763-e3a0-2d0975d727fe, status: complete
jobs3.go:429: checking deployment: 1941ddd5-18c5-6a0e-85da-2b9a8b6c5d10, status: running
jobs3.go:429: checking deployment: 1941ddd5-18c5-6a0e-85da-2b9a8b6c5d10, status: running
jobs3.go:429: checking deployment: …
```
=> E2E: refactor volume_mounts test

website/content/api-docs/acl/policies.mdx, website/content/docs/commands/acl/policy/apply.mdx
Workload-associated ACL policies can only be set on a specific job within a namespace, not the namespace as a whole. Clarify the documentation for the CLI and API.
Fixes: https://github.com/hashicorp/terraform-provider-nomad/issues/500
Ref: https://github.com/hashicorp/terraform-provider-nomad/pull/504
Ref: https://hashicorp.atlassian.net/browse/NET-11994
=> docs: clarify workload-associated policy parameters

api/quota.go, command/quota_apply.go, command/quota_apply_test.go, command/quota_init.go, nomad/state/state_store_host_volumes.go, nomad/state/state_store_host_volumes_ce.go
Allow users to configure a host volumes quota in MB. This will be enforced at the time of provisioning via create/register RPCs. This changeset is the CE version of ENT/2114. I'll have a separate PR for docs.
Ref: https://github.com/hashicorp/nomad-enterprise/pull/2114
Ref: https://hashicorp.atlassian.net/browse/NET-11549
=> dynamic host volumes quotas (CE)

website/content/docs/other-specifications/namespace.mdx
For Nomad Enterprise, the namespace specification's node pool configuration can control access to node pools for dynamic host volumes as well.
=> dynamic host volumes: document option for node pool governance

website/content/docs/other-specifications/quota.mdx
In Nomad 1.10, quotas will use the new `storage` block to specify limits on host volume and variables storage. Previous PRs have updated the upgrade guide noting the deprecation of the existing `variables_limit` field.
=> docs: update quota specification for new storage block

website/content/docs/enterprise/sentinel.mdx
Document the new `submit-host-volume` scope for Sentinel policies, which will support Sentinel enforcement for dynamic host volumes.
=> dynamic host volumes: sentinel documentation

command/agent/command.go
Fixes #24847
We forgot to update the log line when we bumped the deprecation date: https://developer.hashicorp.com/nomad/docs/integrations/vault/acl#authentication-without-workload-identity-legacy
=> update vault token warning from 1.9->1.10

nomad/structs/funcs.go, nomad/structs/funcs_test.go
Some dynamic host volumes are claimed by allocations with the capability we borrowed from CSI called `single-node-single-writer`, which says only one allocation can use the volume, and it can use it in read/write mode. We enforce this in the scheduler, but if evaluations for different jobs were to be processed concurrently by the scheduler, it's possible to get plans that would fail to enforce this requirement. Add a check in the plan applier to ensure that non-terminal allocations have exclusive access when requested.
Ref: https://hashicorp.atlassian.net/browse/NET-11549
=> dynamic host volumes: enforce exclusive access in plan apply

api/allocations.go, nomad/structs/structs.go
=> stateful deployments: remove CSIVolumeIDs

client/client.go, client/hostvolumemanager/volume_fingerprint.go
The default `node` configuration in the client should always set an empty `HostVolumes` map. Otherwise callers can panic, e.g.,:
```
goroutine 179 [running]:
github.com/hashicorp/nomad/client/hostvolumemanager.UpdateVolumeMap({0x36042b0, 0xc000c62a80}, 0x0, {0xc000a802a0, 0xd}, 0xc000691940)
github.com/hashicorp/nomad/client/hostvolumemanager/volume_fingerprint.go:43 +0x1b2
github.com/hashicorp/nomad/client.(*Client).batchFirstFingerprints.func1({0xc000a802a0, 0xd}, 0xc000691940)
github.com/hashicorp/nomad/client/node_updater.go:54 +0xd7
github.com/hashicorp/nomad/client.(*batchNodeUpdates).batchHostVolumeUpdates(0xc000912608?, 0xc0009f2f88)
github.com/hashicorp/nomad/client/node_updater.go:417 +0x152
github.com/hashicorp/nomad/client.(*Client).batchFirstFingerprints(0xc000c2d188) …
```
=> client: always initialize node.HostVolumes map

e2e/terraform/provision-infra/main.tf
In order to unify per cluster  the ssh keys generated during the provisioning process, the path to create them now dependes on the cluster's random identifier. This PR makes the dependency explicit to avoid execution errors.
=> Add a dependency to avoid terraform errors when generating ssh keys

command/asset/volume.csi.hcl, command/asset/volume.csi.json, command/asset/volume.host.hcl, command/asset/volume.host.json
The `volume init` command creates example volume specifications. But one of the values for `capability.access_mode` is not a valid value. Correct the example to match the validation logic.
=> volume spec: fix `access_mode` field in examples

.changelog/24892.txt, api/acl.go, lib/auth/binder.go, lib/auth/binder_test.go, nomad/acl_endpoint.go, nomad/acl_endpoint_test.go, nomad/mock/acl.go, nomad/structs/acl.go, website/content/api-docs/acl/auth-methods.mdx
Adds the ability to enable a verbose logger when configuring an auth-method.  This logger will output token claims and information related to how claims are mapped to Nomad identities, and how those identities map to Nomad binding-rules and role/policies.
Create an auth-method and enable the `VerboseLogging` option.  Then start the process of configuring SSO and see the logs.
Fixes [GH #16360](https://github.com/hashicorp/nomad/issues/16360) …
=> auth: adds option to enable verbose logging during sso

.changelog/24849.txt, nomad/event_endpoint.go, nomad/event_endpoint_test.go, nomad/state/state_store.go, nomad/stream/event_broker.go, nomad/stream/event_broker_test.go, nomad/stream/subscription.go
Enables Workload Identities to subscribe to event streams.  Previously, the event broker used custom authentication logic that could only accept the secretID from an ACL Token.  This change refactors the event broker to use an authentication callback for handling authentication while subscribing and after various ACL events.  This allows us to inject the standardized `Authenticator` logic into the event broker.
Enable ACL's, create the appropriate policy, associate it with a workload, and use the WI as the Bearer token when subscribing to the events stream.
Fixes [GH #18186](https://github.com/hashicorp/nomad/issues/18186)
and job configuration, please update the  Nomad website documentation to reflect this. …
=> Enable workload identity for event stream

.changelog/24922.txt, nomad/structs/csi.go, nomad/structs/csi_test.go
When a volume is updated, we merge the new definition to the old. But the volume's context comes from the plugin and is likely not present in the user's volume specification. Which means that if the user re-submits the volume specification to make an adjustment to the volume, we wipe out the context field which might be required for subsequent operations by the CSI plugin. This was discovered to be a problem with the Terraform provider and fixed there, but it's also a problem for users of the `volume create` and `volume register` commands.
Update the merge so that we only overwrite the value of the context if it's been explictly set by the user. We still need to support user-driven updates to context for the `volume register` workflow.
Ref: …
=> CSI: don't overwrite context with empty value from request

nomad/heartbeat.go, nomad/heartbeat_test.go, nomad/reporting/reporting_ce.go, nomad/server.go
Nomad Enterprise will utilise new reporting metrics and the changes here allow this work to be conducted.
The server specific GetClientNodesCount function has been removed from CE as this is only called within enterprise code. A new heartbeater function allows us to get the number of active timers, which can be used by the heartbeater metrics and any other callers that want this data.
This has been originally reviewed within the enterprise codebase.
In order to juggle the CE and Enterprise specific code portions, I plan on backporting this change to CE only and then performing manual merging into Enterprise along with the specific changes needed there.
Once the merging juggling has been complete, I will raise a followup documentation and changelog PR.
Jira: …
=> reporting: Update server to accommodate new enterprise reporting.

client/csi_endpoint_test.go, client/pluginmanager/csimanager/interface.go, client/structs/csi.go, command/agent/job_endpoint.go, nomad/structs/csi.go, nomad/structs/funcs.go, nomad/structs/funcs_test.go, nomad/structs/host_volumes.go, nomad/structs/volumes.go, plugins/csi/plugin.go, scheduler/feasible.go, scheduler/feasible_test.go
When we implemented CSI, the types of the fields for access mode and attachment mode on volume requests were defined with a prefix "CSI". This gets confusing now that we have dynamic host volumes using the same fields. Fortunately the original was a typedef on string, and the Go API in the `api` package just uses strings directly, so we can change the name of the type without breaking backwards compatibility for the msgpack wire format or HTTP API.
Update the names to `VolumeAccessMode` and `VolumeAttachmentMode`. Keep the CSI and DHV specific value constant names for these fields (they aren't currently 1:1), so that we can easily differentiate in a given bit of code which values are valid.
Ref: https://github.com/hashicorp/nomad/pull/24881#discussion_r1920702890
=> refactor: volume request modes to be generic between DHV/CSI

.changelog/24526.txt, client/fingerprint/consul.go, client/fingerprint/consul_test.go, client/fingerprint/vault.go, client/fingerprint/vault_test.go
This PR changes the Consul and Vault fingerprint implementations to be
reloadable rather than periodic. Reasons described in the issue.
Closes: https://github.com/hashicorp/nomad/issues/24049
=> fingerprint: convert consul and vault fingerprinters to be reloadable

e2e/ui/package-lock.json, e2e/ui/package.json, e2e/ui/run.sh
Spiritual successor to https://github.com/hashicorp/nomad/pull/24158
```
Error: browserType.launch: Executable doesn't exist at /ms-playwright/chromium_headless_shell-1155/chrome-linux/headless_shell
╔══════════════════════════════════════════════════════════════════════╗
║ Looks like Playwright Test or Playwright was just updated to 1.50.0. ║
║ Please update docker image as well.                                  ║
║ -  current: mcr.microsoft.com/playwright:v1.49.0-jammy               ║
║ - required: mcr.microsoft.com/playwright:v1.50.0-jammy               ║
║                                                                      ║
║ <3 Playwright Team                                                   ║
╚══════════════════════════════════════════════════════════════════════╝
```
=> [e2e, ui] Update playwright to 1.50.0 for e2e ui tests

client/allocrunner/taskrunner/dynamic_users_hook.go, client/allocrunner/taskrunner/dynamic_users_hook_test.go
Before this, the nomad client would crash with:
```
panic: assignment to entry in nil map
```
We are seeing in our production clusters the following crash when this codepath is being hit.
The unit test I added doesn't pass without this change.
=> taskrunner: fix panic when a task that has a dynamic user is recovered

api/host_volumes.go, command/volume_create_host.go, nomad/state/state_store_host_volumes.go, nomad/state/state_store_host_volumes_test.go, nomad/structs/host_volumes.go, scheduler/feasible_test.go
When a client restarts but can't restore a volume (ex. the plugin is now missing), it's removed from the node fingerprint so we won't allow future scheduling of the volume. But we were not updating the volume state field to report this reasoning to operators. Make debugging easier and the state field more meaningful by setting the value to "unavailable".
Also, remove the unused "deleted" field value. We did not implement soft deletes and aren't planning on it for Nomad 1.10.0.
Ref: https://hashicorp.atlassian.net/browse/NET-11551
=> dynamic host volumes: set status unavailable on failed restore

.changelog/24966.txt, nomad/state/events.go
Adding the `alloc.Sanitize()` sanitization on `eventFromChange(change memdb.Change) (structs.Event, bool)` to clean identity tokens in events.
=> sec: sanitize identity token from events

e2e/terraform/provision-infra/outputs.tf
The pathing needed updating due to recent changes in the directory structure of the e2e Terraform.
=> e2e: Fix TF output SSH key path.

website/content/docs/operations/stateful-workloads.mdx
We have a document describing the various approaches to storage that surveys the landscape and makes recommendations based on the user's environment. Add dynamic host volumes to this document.
[Preview link](https://nomad-git-dhv-docs-considerations-for-stateful-ca1891-hashicorp.vercel.app/nomad/docs/operations/stateful-workloads)
=> docs: considerations for stateful workloads updates for DHV

.changelog/24973.txt, ui/app/components/task-log.js, ui/app/routes/allocations/allocation/task/logs.js
The node read on the task logs page is not required and therefore should be callable by users which do not have node:read in their ACL token capabilities. The job allocation logs work without this currently, so this not only fixes the bug, but also creates better consistency across pages.
Linked GitHub issue has good reproduction steps.
Jira: https://hashicorp.atlassian.net/browse/NET-11262
Closes: https://github.com/hashicorp/nomad/issues/23786 …
=> ui: Remove unrequired node read from task log streaming page.

website/content/partials/install/install-cni-plugins.mdx
CNI had release problems which meant 1.6.1 got pulled and 1.6.2 is identical.
Closes #24975 
=> docs: Update CNI install detail to use 1.6.2

command/volume_create.go, command/volume_create_host.go, command/volume_create_host_test.go, command/volume_register.go, command/volume_register_host.go, command/volume_register_host_test.go, command/volume_status_host.go
If you create a volume via `volume create/register` and want to update it later, you need to change the volume spec to add the ID that was returned. This isn't a very nice UX, so let's add an `-id` argument that allows you to update existing volumes that have that ID.
Ref: https://hashicorp.atlassian.net/browse/NET-12083
---
Example of use:
```
$ nomad volume create ./internal-plugin.volume.hcl
==> Created host volume internal-plugin with ID 78898137-6457-03be-1960-8f2ad946ff11
✓ Host volume "78898137" ready
2025-01-31T15:39:19-05:00
ID        = 78898137-6457-03be-1960-8f2ad946ff11
Name      = internal-plugin
Namespace = default
Plugin ID = mkdir
Node ID   = d361ff13-df88-b944-2c06-1f01d3e16557
Node Pool = default
Capacity  = 0 B
State     = ready
Host Path = …
```
=> dynamic host volumes: add `-id` arg for updates of existing volumes

.changelog/24997.txt, command/volume_delete.go, command/volume_delete_host_test.go
The `volume delete` command doesn't allow using a prefix for the volume ID for either CSI or dynamic host volumes. Use a prefix search and wildcard namespace as we do for other CLI commands.
Ref: https://hashicorp.atlassian.net/browse/NET-12057
---
Example of use:
```
$ nomad volume create ./internal-plugin.volume.hcl
==> Created host volume internal-plugin with ID aeea91a0-06df-c16e-5403-ff82a2f28fd4
✓ Host volume "aeea91a0" ready
2025-01-31T15:55:14-05:00
ID        = aeea91a0-06df-c16e-5403-ff82a2f28fd4
Name      = internal-plugin
Namespace = default
Plugin ID = mkdir
Node ID   = b4611abd-d4a8-c83a-b05e-7d9f5b44a179
Node Pool = default
Capacity  = 0 B
State     = ready
Host Path = /run/nomad/dev/data/host_volumes/aeea91a0-06df-c16e-5403-ff82a2f28fd4
$ nomad volume delete -type host …
```
=> volume delete: allow prefix for ID

.changelog/24959.txt, command/job_status.go, website/content/docs/commands/job/status.mdx, website/content/docs/commands/status.mdx
Provides a little table showing Nomad Actions available to a job when running `nomad job status $jobid`. Mimics what we show in the Web UI (where there's an Actions dropdown on the main page of jobs that have 'em)
```
nomad job status actions-demo-service
ID            = actions-demo-service
Name          = actions-demo-service
Submit Date   = 2025-01-23T16:13:22-05:00
Type          = service
Summary
Task Group  Queued  Starting  Running  Failed  Complete  Lost  Unknown
actionless  0       0         3        0       16        0     0
group1      0       0         1        0       7         0     0
group2      0       0         6        0       25        0     0
.....
Actions
Action Name     Task Group  Task
weather         group1      task
get-alloc-info  group1      task
echo-time …
```
=> [cli] Adds Actions to job status command output

website/content/docs/job-specification/resources.mdx
Fix: Inaccurate Memory Resource Example
Nomad memory sizes are always in binary units (plenty of places with e.g. `MemoryMB * 1024 * 1024` around the codebase). This snippet of documentation, however, is misleading, and implies that Nomad manages/tracks memory with decimal units.
Without going crazy changing "MB"->"MiB" everywhere, causing mass confusion and horrid edit wars, let's just change this one number! This is a subtle but effective way to signal to developers that we're using binary-based sizes.
(Even if this argument fails, this documentation is plain _wrong_: `MemoryMB = 2000` will use ~2.1GB: 2000 binary megabytes, 1048576 bytes each.)
N/A
[Example of size computation in Docker driver, clearly computing mibibytes](https://github.com/hashicorp/nomad/blob/9367929d87c0a5d654fb4dea …
=> Fix: Inaccurate Memory Resource Example

enos/modules/test_cluster_health/main.tf, enos/modules/test_cluster_health/scripts/allocs.sh, enos/modules/test_cluster_health/scripts/servers.sh, enos/modules/test_cluster_health/scripts/versions.sh, enos/modules/test_cluster_health/variables.tf
While running the tests after upgrading the cluster I found that the endpoint being called for ` last_log_index` didn't actually had the information but the test was passing because the result for all servers was the same: `null`. This PR fixes that mistake by updating the call and explicitly checking for not empty responses.
It Also introduces tests for versions, to make sure all clients and all servers have the expected version.  …
=> Fix the last_log_index check and add a versions check

GNUmakefile, jobspec2/hcl_conversions.go, jobspec2/helper_test.go, jobspec2/parse_job.go, jobspec2/parse_test.go, jobspec2/util.go
Isolate the jobspec2 package (MPL-2.0) from Nomad core by removing imports of packages licensed under BUSL. In order to flag regressions, a new makefile check has been added.
Tests are fine to run in parallel and the suite which runs jobspec2 run at least as quick as previously, if not quicker (30-60s).
in the majority of situations. The main exceptions are long-lived feature branches or merges …
=> jobspec2: isolate package from Nomad core and BUSL.

website/content/api-docs/volumes.mdx, website/content/docs/commands/volume/delete.mdx, website/content/docs/commands/volume/deregister.mdx, website/content/docs/commands/volume/init.mdx, website/content/docs/commands/volume/register.mdx, website/content/docs/concepts/plugins/storage/csi.mdx, website/content/docs/concepts/plugins/storage/host-volumes.mdx, website/content/docs/concepts/plugins/storage/index.mdx, website/content/docs/job-specification/volume.mdx, website/content/docs/operations/stateful-workloads.mdx, website/content/docs/other-specifications/volume/capability.mdx, website/content/docs/other-specifications/volume/mount_options.mdx, website/content/docs/other-specifications/volume/topology_request.mdx
Updates to front matter description to include dynamic host volumes.
@boruszak  - this is merging into the dynamic-host-volume-docs branch (1.10 feature). No title/heading changes to sentence case. 
Jira: [CE-812]
[CE-812]: …
=> DHV Front matter description updates for devdot search

e2e/terraform/provision-infra/provision-nomad/install-linux.tf, e2e/terraform/provision-infra/provision-nomad/install-windows.tf
…remote instances
The[ `resource`](https://github.com/hashicorp/nomad/blob/d9e2cb23b9af3fbf7e172d3547b004a25fa9cff2/e2e/terraform/provision-infra/provision-nomad/install-linux.tf#L10) in charge of installing the nomad binary in the terraform was written with the idea of allowing "hot" upgrades, by triggering a new installation every time the binary it was using as an input was changed. It presents a problem when using it in conjunction with other modules because any change in that path will trigger the resource, preventing the use of dynamic inputs.
This PR removes the trigger.
the [website …
=> Remove triggers from null resources

.changelog/25040.txt, client/vaultclient/vaultclient.go
In #24409 we fixed a bug where some of the error messages we get from Vault weren't being caught correctly. This fix itself contains a bug where we changed the logic that logged the non-fatal errors so that it logs when there is no renewal error.
Ref: https://github.com/hashicorp/nomad/pull/24409
Fixes: https://github.com/hashicorp/nomad/issues/24933
=> vault: fix bug in logging logic around renewals

.changelog/25039.txt, client/rpc.go, client/rpc_test.go
When a blocking query on the client hits a retryable error, we change the max query time so that it falls within the `RPCHoldTimeout` timeout. But when the retry succeeds we don't reset it to the original value.
Because the calls to `Node.GetClientAllocs` reuse the same request struct instead of reallocating it, any retry will cause the agent to poll at a faster frequency until the agent restarts. No other RPC on the client currently has this behavior, but we'll fix this in the `rpc` method rather than in the caller so that any future users of the `rpc` method don't have to remember this detail.
Fixes: https://github.com/hashicorp/nomad/issues/25033
Ref: https://hashicorp.atlassian.net/browse/NET-12116
and job …
=> reset max query time of blocking queries in client after retries

enos/enos-scenario-upgrade.hcl, enos/enos-vars.hcl, enos/modules/fetch_artifactory/main.tf, enos/modules/fetch_artifactory/variables.tf
The variables definitions for Enos upgrade scenarios have a couple of unused variables and some of the documentation strings are ambiguous:
* `nomad_region` and `binary_local_path` variables are unused and can be removed.
* `nomad_local_binary` refers to the directory where the binaries will be download, not the binaries themselves. Rename to make it clear this belongs to the artifactory fetch and not the provisioning step (which uses the artifactory fetch outputs).
=> enos: improve documentation around required variables

.changelog/24981.txt, drivers/docker/coordinator.go, drivers/docker/coordinator_test.go
With the `docker` driver, if an error is encountered while reading image pull progress, the allocation gets stuck `pending`.
This happens because `dockerCoordinator.PullImage()` gets deadlocked at `future.wait()`, because this one error path (introduced [here](https://github.com/hashicorp/nomad/commit/981ca3604965b6934a96559634887ee443106bfb#diff-a812e02f32452925890f1c3f229cc5ea705e7c1db1637b0295796236fbbc6affR218-R219) in v1.9.0) does not do a `future.set()` to close the channel that `future.wait()` blocks on.
Worse, the whole `TaskRunner.Run()` goroutine from the allocrunner remains stuck until the client is forcibly restarted (it can not shut down gracefully). This same bug could be introduced again in the future by mistake, but since the error path fixed in this PR is the only one …
=> docker: properly handle "error reading image pull progress"

.changelog/24991.txt, drivers/docker/coordinator.go, drivers/docker/coordinator_test.go
I believe the `docker` driver stopped respecting [image_pull_timeout](https://developer.hashicorp.com/nomad/docs/drivers/docker#image_pull_timeout) in Nomad `1.9.0` in [this refactor](https://github.com/hashicorp/nomad/commit/981ca3604965b6934a96559634887ee443106bfb#diff-a812e02f32452925890f1c3f229cc5ea705e7c1db1637b0295796236fbbc6affL192).
This makes the timeout apply again.  There is some risk that folks are unwittingly depending on the timeout not working (it is a generous 5 minutes by default), but since it has only been this way since `1.9` (as far as I can tell), the exposure is somewhat limited.
The different `context`s around here are pretty confusing. I hope I got them right, and left informative enough var names and comments to help future folks keep them straight.
This PR …
=> docker: respect image_pull_timeout

drivers/docker/coordinator.go
PR #24981 fixes a bug that I think this would have prevented.
Instead of requiring humans understand/remember that within `pullImageImpl()`, each `return` needs an associated `future.set()`, this `set()`s in the outer scope where the future is created and `wait()`ed on. So now `pullImageImpl()` can be a simple normal function without needing to worry about any `future` business.
No new tests needed for this. At least most of the relevant code paths are covered by existing tests (including some added in PR #24991, which this builds upon), so the overall contract for `PullImage()` is intact.
=> docker: refactor PullImage future handling

.changelog/24974.txt, nomad/core_sched_test.go, nomad/fsm.go, nomad/job_endpoint.go, nomad/state/state_store.go, nomad/state/state_store_test.go, nomad/system_endpoint_test.go
The state store persists the correct job version for job summaries, but not for specific versions.  This fix attempts to simplify the logic around evaluating a job's status, and then make's sure it is persisted.
See GH issue for replication steps
Fixes [GH #24957](https://github.com/hashicorp/nomad/issues/24957)
in the majority of situations. The main exceptions are long-lived feature branches or …
=> state store: fix logic for evaluating job status

e2e/dynamic_host_volumes/dynamic_host_volumes_test.go, e2e/dynamic_host_volumes/input/mount-created.nomad.hcl, e2e/dynamic_host_volumes/input/sticky.nomad.hcl, e2e/dynamic_host_volumes/input/volume-sticky.nomad.hcl, e2e/v3/volumes3/host3.go
Add tests for dynamic host volumes where the claiming jobs have `volume.sticky = true`. Includes a test for forced rescheduling and a test for node drain.
This changeset includes a new `e2e/v3`-style package for creating dynamic host volumes, so we can reuse that across other tests.
---
This is currently failing the node drain portion of the test, which suggests there's a flaw in how we're dealing with blocked evals. An example run against a Nomad cluster with 2 nodes:
```
$ NOMAD_E2E_VERBOSE=1 go test -v -count=1 ./e2e/dynamic_host_volumes -run TestDynamicHostVolumes_StickyVolumes
=== RUN   TestDynamicHostVolumes_StickyVolumes
dynamic_host_volumes_test.go:163: [69.181463ms] volume "167f0c30-0564-6a17-228c-31f138375315" created
dynamic_host_volumes_test.go:163: [5.364112673s] volume …
```
=> E2E: dynamic host volume tests for sticky volumes

e2e/dynamic_host_volumes/dynamic_host_volumes_test.go, e2e/e2e_test.go
I merged #24869 having forgotten we don't run these tests in PR CI, so there's a compile error in the test. Fix that error and add the no-op import we use to catch this kind of thing.
Ref: https://github.com/hashicorp/nomad/pull/24869
---
Unfortunately the test still does not pass, even following https://github.com/hashicorp/nomad/pull/24993
```
$ NOMAD_E2E_VERBOSE=1 go test -v -count=1 ./e2e/dynamic_host_volumes -run TestDynamicHostVolumes_StickyVolumes
=== RUN   TestDynamicHostVolumes_StickyVolumes
dynamic_host_volumes_test.go:163: [54.688678ms] volume "cfad0d80-3b91-4e53-c06c-d4938a0b2919" created
dynamic_host_volumes_test.go:163: [5.203492879s] volume "cfad0d80-3b91-4e53-c06c-d4938a0b2919" is "ready" on node "2426901b-0887-f851-4479-990c9ec4db25"
dynamic_host_volumes_test.go:167: …
```
=> E2E: dynamic host volumes sticky volumes drain test fix

e2e/terraform/provision-infra/compute.tf, e2e/terraform/provision-infra/outputs.tf
Having only one output for both clients simplifies the scenario definition of the upgrade tests because the steps variable inputs don't accept dynamic values, forcing us to do an intermediate step only to determine which clients are being used.
But thinking on a future where we could make mixed cluster, a tag with the OS is added to each instance so we can differentiate them later.
in the majority …
=> Add tag to instances with OS and add merged output

nomad/state/state_store.go, nomad/state/state_store_test.go
This change removes some logic from the `getJobStatus()` method in order to remove the call to `time.Now()`.  With this logic removed, we revert back the edge case where jobs that should be pending can be marked dead for a very brief period of time until an evaluation is created for them.
history …
=> state store: remove reschedulable check when getting job status

nomad/state/state_store_test.go
This test was failing because the child job had no evaluations.  When running a real periodic job, the child job would have an evaluation, so we should add it to the test.
=> test: add eval to state store periodic job test

.changelog/24849.txt, nomad/event_endpoint.go, nomad/event_endpoint_test.go, nomad/state/state_store.go, nomad/stream/event_broker.go, nomad/stream/event_broker_test.go, nomad/stream/subscription.go
Manual backport of authenticating with event stream using Workload Identities
=> Backport of Enable workload identity for event stream into release/1.9.x

.changelog/25085.txt, e2e/task_schedule/input/schedule.nomad.hcl, e2e/task_schedule/task_schedule_test.go
CE side of ENT PR: hashicorp/nomad-enterprise#2307 - task schedule: pauses are not restart "attempts"
Internal ticket: https://hashicorp.atlassian.net/browse/NET-12119
Distinguish between these two cases:
1. Task dies because we "paused" it (on purpose)
- should not count against restart attempts, because nothing is wrong.
2. Task dies because it didn't work right
- should count against restarts, so users can address application issues.
With this, the `restart{}` block is back to its normal behavior, so its documentation applies without caveat.
<details><summary>Output of the tests:</summary>
```
$ go test ./e2e/task_schedule/ -v -count=1
=== RUN   TestTaskSchedule
=== RUN   TestTaskSchedule/in_schedule
task_schedule_test.go:47: 2025-02-10T21:04:00Z job options: start="3 21 * * * *" …
```
=> e2e: task schedule: pauses vs restarts

scheduler/feasible.go, scheduler/feasible_test.go
A return statement was missing in the sticky volume check—when we weren't able to find a suitable volume, we did not return `false`. This was caught by e2e test. 
This PR fixes the issue, and corrects and expands the unit test. 
E2E run on this branch:
```
=== RUN   TestDynamicHostVolumes_CreateWorkflow
dynamic_host_volumes_test.go:34: [8.449645s] submitting mounter job
dynamic_host_volumes_test.go:37: [10.121018s] test complete, cleaning up
--- PASS: TestDynamicHostVolumes_CreateWorkflow (10.71s)
=== RUN   TestDynamicHostVolumes_RegisterWorkflow
dynamic_host_volumes_test.go:54: [988.745416ms] register job "register-volumes-769" created
dynamic_host_volumes_test.go:61: [1.3541875s] ACL policy for job "register-volumes-769" created
dynamic_host_volumes_test.go:69: [3.232239833s] job …
```
=> stateful deployments: fix return in the `hasVolumes` feasibility check

.github/workflows/semgrep.yml, .semgrep/rpc_endpoint.yml
Fixes an error in the RPC endpoint rule which meant semgrep was not correctly running all rules in CI. The change also includes a new semgrep-validate workflow which will trigger to ensure the rules are valid before running the semgrep scan.
=> semgrep: Fix invalid RPC rule and add validation GHA workflow.

.changelog/25093.txt, client/client.go, helper/escapingfs/copydir.go, helper/escapingfs/copydir_test.go
In #24650 we switched to using ephemeral state for CNI plugins, so that when a host reboots and we lose all the allocations we don't end up trying to use IPs we created in network namespaces we just destroyed. Unfortunately upgrade testing missed that in a non-reboot scenario, the existing CNI state was being used by plugins like the ipam plugin to hand out the "next available" IP address. So with no state carried over, we might allocate new addresses that conflict with existing allocations. (This can be avoided by draining the node first.)
As a compatibility shim, copy the old CNI state directory to the new CNI state directory during agent startup, if the new CNI state directory doesn't already exist.
Ref: https://github.com/hashicorp/nomad/pull/24650
Ref: …
=> CNI: migrate from persistent state to ephemeral state during restart

.changelog/25102.txt, .release/linux/package/usr/lib/systemd/system/nomad.service, client/fingerprint/consul.go, client/fingerprint/consul_test.go, client/fingerprint/fingerprint.go, client/fingerprint/vault.go, client/fingerprint/vault_test.go
In #24526 we updated the Consul and Vault fingerprints so that they are no longer periodic. This fixed a problem that cluster admins reported where rolling updates of Vault or Consul would cause a thundering herd of fingerprint updates across the whole cluster.
But if Consul/Vault is not available during the initial fingerprint, it will never get fingerprinted again. This is challenging for cluster updates and black starts because the implicit service startup ordering may require reloads. Instead, have the fingerprinter run periodically but mark that it has made its first successful fingerprint of all Consul/Vault clusters. At that point, we can skip further periodic updates. The `Reload` method will reset the mark and allow the subsequent fingerprint to run normally.
Fixes: …
=> fingerprint: initial fingerprint of Vault/Consul should be periodic

.changelog/25113.txt, client/allocrunner/taskrunner/template/template_test.go, client/config/config.go, command/agent/config_test.go, command/agent/test-resources/client_with_template.hcl
In #20165 we fixed a bug where a partially configured `client.template` retry block would set any unset fields to nil instead of their default values. But this patch introduced a regression in the default values, so we were now defaulting to unlimited retries. Restore the correct behavior and add better test coverage at both the config parsing and template configuration code.
Ref: https://github.com/hashicorp/nomad/pull/20165
Ref: https://github.com/hashicorp/nomad/issues/23305#issuecomment-2643731565
In addition to the new and fixed unit tests, I tested with Vault and a template that would never succeed due to permission denied errors, with different client configurations as show here.
Empty (default)
```hcl
template {}
```
> * permission denied (retry attempt 1 after "250ms")
> * …
=> template: fix client's default retry configuration

website/content/docs/commands/job/status.mdx, website/content/docs/concepts/job.mdx, website/content/partials/job-status-map.mdx
- Add `dead (stopped)` row to status mapping table in Job statuses section. This small change is a result of clarification provided to me in reviewing https://github.com/hashicorp/nomad/pull/24150  ([comment](https://github.com/hashicorp/nomad/pull/24150#discussion_r1951623749))
- In mapping table, change `complete` to `dead` since the job status is actually `dead` when the allocation status is `complete` (suggestion by Michael in DM conversation)
- pull job status mapping into partial and include in the job status command page so users don't have to refer to another page 
- remove API from table since the API endpoint lists different statuses
- Add CLI status definitions based on [code](https://github.com/hashicorp/nomad/blob/main/nomad/structs/structs.go#L4361-L4365)
- Additional …
=> Docs: Clarify Job status mapping on Job page

command/job_restart.go, scheduler/generic_sched.go, website/content/docs/commands/job/restart.mdx, website/content/docs/configuration/server.mdx, website/content/docs/job-specification/disconnect.mdx, website/content/docs/job-specification/group.mdx, website/content/docs/job-specification/migrate.mdx, website/content/docs/job-specification/reschedule.mdx, website/content/docs/job-specification/restart.mdx
Our vocabulary around scheduler behaviors outside of the `reschedule` and `migrate` blocks leaves room for confusion around whether the reschedule tracker should be propagated between allocations. There are effectively five different behaviors we need to cover:
* restart: when the tasks of an allocation fail and we try to restart the tasks in place.
* reschedule: when the `restart` block runs out of attempts (or the allocation fails before tasks even start), and we need to move the allocation to another node to try again.
* migrate: when the user has asked to drain a node and we need to move the allocations. These are not failures, so we don't want to propagate the reschedule tracker.
* replacement: when a node is lost, we don't count that against the `reschedule` tracker for the …
=> docs: clarify reschedule, migrate, and replacement terminology

website/content/plugins/drivers/virt/task-config.mdx
The "network" block does not have a "provider" option, therefore it was removed.
The example job spec in the docs contained an unsupported argument. This PR fixes that.
=> docs: remove non-existing option in task-config.mdx for virt driver

.github/workflows/test-ui.yml, ui/mirage/factories/job.js, ui/tests/acceptance/job-detail-test.js, ui/tests/acceptance/regions-test.js, ui/tests/acceptance/server-detail-test.js, ui/tests/acceptance/task-logs-test.js, ui/tests/helpers/module-for-job.js, ui/tests/integration/components/job-page/periodic-test.js, ui/tests/integration/components/job-page/service-test.js, ui/tests/integration/components/task-log-test.js
In https://github.com/hashicorp/nomad/pull/24555, I changed up our `ember-exam` step in `test-ui` tests to use a custom test runner. In CI, it runs in parallel in 4 partitions.
This code had a bug: my tests were being reported locally in each partition, but because `continue-on-error` was set, they would also report back with a green checkmark / passing. A PR author or reviewer would have to click through passed test logs to see the failures.
**This PR does two main things:**
- Fixes the failing tests that have resulted from (and been suppressed during) new feature work since this has been in place
- Adds an `Express failure` step afterward `ember-exam` that summarizes failures and acts as the red-x for failing tests/checks.
- In order to do this, this PR keeps `continue-on-error` (so …
=> [ui, tests] Various acceptance test fixups (v main)

nomad/state/state_store_host_volumes.go, nomad/state/state_store_host_volumes_test.go
We update the status of a volume when the node fingerprint changes. But if a node goes down, we still show the volume as available. The scheduler behavior is correct because a down node can never have work scheduled on it, but it might be confusing for job authors who are looking at volumes that are showing as available.
Update the volume update logic we have on node updates to include marking the volume as unavailable when a node goes down.
Fixes: https://hashicorp.atlassian.net/browse/NET-12068
=> dynamic host volumes: mark volumes on down nodes as unavailable

enos/modules/test_cluster_health/scripts/servers.sh, enos/modules/upgrade_clients/scripts/verify_metadata.sh, enos/modules/upgrade_servers/scripts/wait_for_stable_cluster.sh
While testing #25172 I found a few spots where #25152 wasn't capturing the errors from transient failures correctly or exiting early instead of retrying.
Ref: https://hashicorp.atlassian.net/browse/NET-11546
=> upgrade testing: make sure we capture last error if not exiting

website/content/docs/concepts/scheduling/preemption.mdx
Fix a broken link from the preemption concepts docs to the relevant API. Also include a link to the relevant command.
Ref: https://github.com/hashicorp/nomad/issues/25038
Preview link: https://nomad-m6t6tq8jc-hashicorp.vercel.app/nomad/docs/concepts/scheduling/preemption#details
=> docs: improve cross-links for scheduler preemption

.github/dependabot.yml
Dependabot can update actions to versions that are not in the TSCCR allowlist. The TSCCR check doesn't happen in CE, which means we don't learn we have a problem until after we've spent the effort to backport them. Remove the automation that updates actions automatically until this issue is resolved on the security team's side.
Ref (internal): https://github.com/hashicorp/nomad-enterprise/pull/2379
Ref (internal): https://hashicorp.slack.com/archives/C02V6HVS98E/p1740495088397829
=> deps: remove actions updates from dependabot

.changelog/25104.txt, ui/app/models/job.js, ui/app/templates/components/job-page/parts/title.hbs, ui/app/templates/components/job-version.hbs, ui/mirage/scenarios/default.js, ui/tests/acceptance/job-detail-test.js, ui/tests/acceptance/job-versions-test.js
Follow-up on #24985: Because that PR looks for a previous `stable=true` version of a job, and system/batch/sysbatch jobs don't have the concept of version stability<sup>1</sup>, this allows for both a "Revert to prev version" and "Edit and Resubmit" (when at least one other version is present), or just an "Edit and Resubmit" button (when there are no previous versions)
<sup>1</sup> ~TODO: I should probably remove that label from the versions component in the UI if it's one of these job types~ done like dinner
=> [ui] System, Batch, and Sysbatch jobs' Start Job buttons let you revert to previous versions

website/content/partials/virt-beta-callout.mdx, website/content/plugins/drivers/virt/index.mdx, website/content/plugins/drivers/virt/install.mdx, website/content/plugins/drivers/virt/task-config.mdx
- Update the Virt beta callout partial to use the Note component
- Move the callout after the intro text because for SEO, the first paragraph is super important. We don't want Google to display a beta feature note in search results.
- Add intro paragraph to Configure... page.
Jira: [CE-819]
Deploy previews:
- https://nomad-git-virtbeta-hashicorp.vercel.app/nomad/plugins/drivers/virt
- https://nomad-git-virtbeta-hashicorp.vercel.app/nomad/plugins/drivers/virt/install
- https://nomad-git-virtbeta-hashicorp.vercel.app/nomad/plugins/drivers/virt/task-config
the [website README](../website/README.md) for docs guidelines. …
=> Docs: update Virt beta callout to use Note component

e2e/dynamic_host_volumes/dynamic_host_volumes_test.go
In #25185 we changed the output of `volume status` to include both DHV and CSI volumes by default. When the E2E test parses the output, it's not expecting the new section header.
Ref: https://github.com/hashicorp/nomad/pull/25185
---
Before:
```
$ go test -v -count=1 ./e2e/dynamic_host_volumes -run TestDynamicHostVolumes_RegisterWorkflow
=== RUN   TestDynamicHostVolumes_RegisterWorkflow
dynamic_host_volumes_test.go:54: [146.351879ms] register job "register-volumes-902" created
dynamic_host_volumes_test.go:61: [204.457851ms] ACL policy for job "register-volumes-902" created
dynamic_host_volumes_test.go:69: [1.270517466s] job dispatched
dynamic_host_volumes_test.go:92: [1.334329081s] dispatched job done
dynamic_host_volumes_test.go:102:
dynamic_host_volumes_test.go:102: expected nil error
↪ …
```
=> E2E: fix column parsing for dynamic host volumes test

enos/enos-scenario-upgrade.hcl, enos/modules/run_workloads/jobs/docker-batch.nomad.hcl, enos/modules/run_workloads/jobs/docker-service.nomad.hcl, enos/modules/run_workloads/jobs/docker-system.nomad.hcl, enos/modules/run_workloads/jobs/raw-exec-batch.nomad.hcl, enos/modules/run_workloads/jobs/raw-exec-system.nomad.hcl, enos/modules/run_workloads/main.tf, enos/modules/run_workloads/outputs.tf, enos/modules/run_workloads/variables.tf, enos/modules/test_cluster_health/scripts/allocs.sh, enos/modules/test_cluster_health/scripts/jobs.sh, enos/modules/test_cluster_health/scripts/versions.sh
This PR adds new system and batch workloads to the upgrade tests.
=> Add new workloads

enos/README.md, enos/debug-environment
Enos buries the Terraform output from provisioning. Add a shell script to load the environment from provisioning for debugging Nomad during development of upgrade tests.
=> upgrade testing: debugging assistance

enos/enos-scenario-upgrade.hcl, enos/enos-vars.hcl, enos/modules/run_workloads/efs.tf, enos/modules/run_workloads/jobs/plugin-aws-efs-nodes.nomad.hcl, enos/modules/run_workloads/jobs/raw-exec-system.nomad.hcl, enos/modules/run_workloads/jobs/wants-volume.nomad.hcl, enos/modules/run_workloads/main.tf, enos/modules/run_workloads/scripts/volume.hcl.tpl, enos/modules/run_workloads/scripts/wait_for_efs_plugin.sh, enos/modules/run_workloads/scripts/wait_for_efs_volume.sh, enos/modules/run_workloads/variables.tf
Add an upgrade test workload for CSI with the AWS EBS plugin. In order to validate this workload, we'll need to deploy the plugin jobs and then register volumes with them. So this extends the `run_workloads` module to allow for a "post script" to be run after a given job has been deployed. We can use that as a model for other test workloads.
Ref: https://hashicorp.atlassian.net/browse/NET-12217
=> upgrade tests: add CSI workload

client/client.go
This PR removes the unused nodeID parameter from several metric collection functions in the client package. The parameter was being passed but not utilized in any of the functions, creating unnecessary overhead.
No functional changes as the parameter was unused. Standard test suite passes.
history …
=> client: remove unused `nodeID` parameter from host stats metric functions

.changelog/24942.txt, client/allocrunner/networking_cni.go, client/allocrunner/networking_cni_test.go, client/fingerprint/consul.go, client/fingerprint/consul_test.go, client/fingerprint/nomad.go, client/fingerprint/nomad_test.go, nomad/structs/node_class.go, nomad/structs/node_class_test.go, scheduler/benchmarks/benchmarks_test.go, scheduler/testing.go
When a node is fingerprinted, we calculate a "computed class" from a hash over a subset of its fields and attributes. In the scheduler, when a given node fails feasibility checking (before fit checking) we know that no other node of that same class will be feasible, and we add the hash to a map so we can reject them early. This hash cannot include any values that are unique to a given node, otherwise no other node will have the same hash and we'll never save ourselves the work of feasibility checking those nodes.
In #4390 we introduce the `nomad.advertise.address` attribute and in #19969 we introduced `consul.dns.addr` attribute. Both of these are unique per node and break the hash.
Additionally, we were not correctly filtering attributes out when checking if a node escaped the class by …
=> remove addresses from node class hash

nomad/acl_endpoint.go, nomad/alloc_endpoint.go, nomad/csi_endpoint.go, nomad/deployment_endpoint.go, nomad/eval_endpoint.go, nomad/host_volume_endpoint.go, nomad/job_endpoint.go, nomad/job_endpoint_statuses.go, nomad/leader_test.go, nomad/node_endpoint.go, nomad/node_pool_endpoint.go, nomad/service_registration_endpoint.go, nomad/state/paginator/filter.go, nomad/state/paginator/filter_test.go, nomad/state/paginator/paginator.go, nomad/state/paginator/paginator_test.go, nomad/state/paginator/tokenizer.go, nomad/state/paginator/tokenizer_test.go, nomad/structs/host_volumes.go, nomad/structs/node_pool.go, nomad/structs/service_registration.go, nomad/structs/structs.go, nomad/task_group_host_volume_claim_endpoint.go, nomad/variables_endpoint.go
The paginator was developed before generics were available, so we've had to work around a lack of compile-time safety by creating configuration objects at runtime that require a lot of branching and type casts. This results in a lot of added boilerplate in the RPC handlers.
Refactor the paginator to take advantage of generics. 
* Move all decision making around tokenization to compile-time by providing pre-built generic functions that close over target tokens. 
* Remove the `appendFunc` parameter in lieu of a `Stub` function parameter that will accept existing `Stub` functions in most cases (with the addition of an extra `error` return value).
* Generally remove boilerplate in the RPC handlers as a result, except where a given handler wants more complex filtering.
This doesn't reduce the …
=> generic paginator

e2e/terraform/provision-infra/consul-servers.tf, e2e/terraform/provision-infra/network.tf
Allows the Consul server access to the Nomad cluster in E2E testing. This allows Consul to make the necessary JWKSUrl test call when creating an authentication method.
=> e2e: allow consul access to nomad cluster

website/content/docs/job-specification/consul.mdx
- `partition` parameter: add that using this parameter requires Consul Enterprise and Nomad workload identity integration with Consul authentication.
- Fixed a few outdated links.
Jira: [CE-820] (created by Dan Hung in Support)
Deploy preview: https://nomad-git-ce820note-hashicorp.vercel.app/nomad/docs/job-specification/consul#partition
in the majority of situations. The main exceptions are …
=> Docs: Add workload identity and Consul Enterprise info to partition parameter

drivers/docker/coordinator.go, drivers/docker/driver.go, drivers/docker/driver_test.go, drivers/docker/network.go, drivers/docker/utils.go, drivers/docker/utils_test.go
This PR addresses this[ issue](https://github.com/hashicorp/nomad/issues/24913).
There was a little bug in the `parseDockerImage` where we were using `/`  the determine the tag and if none was found, it would add latest, completely ignoring the cases where there is a sha present.
This PR refactors the logic to avoid adding the `latest` tag if a sha is provided. 
The extra change corresponds to moving the tests to the `utils_test.go` for clarity. …
=> Fix the docker image parser to account for private repos

enos/enos-scenario-upgrade.hcl, enos/enos-vars.hcl, enos/enos.vars.example.hcl
During initial development of upgrade testing, we had a hard-coded prefix to distinguish between clusters created for this vs those created by GHA runners. Update the prefix to be a variable so that developers can add their own prefix during test workload development.
=> upgrade testing: make cluster name prefix a variable

enos/enos-scenario-upgrade.hcl
The CSI workload is failing and creating complications for teardown, so I'm reworking it. But this work is taking a while to finish, so while that's in progress let's disable the CSI workload so that we're running the upgrade tests all the way through to the end. I expect to be able to revert this in the next couple days.
=> upgrade testing: temporarily disable CSI test

nomad/structs/structs.go
When upgrading from older versions of Nomad, the reschedule policy block may be nil. There is logic to handle this safely in the `NextRescheduleTimeByTime` used for allocs on disconnected clients, but it's missing from the `NextRescheduleTime` method used by more typical allocations. Return an empty time object in this case.
Fixes: https://github.com/hashicorp/nomad/issues/24846
=> scheduler: prevent nil pointer ref when reschedule policy is missing

drivers/shared/executor/executor.go, drivers/shared/executor/executor_universal_linux.go
This PR attempts to fix a panic that happens when running a job with a raw_exec task, the executor panics leading to allocation failure. 
More details [here](https://github.com/hashicorp/nomad/issues/24931)
=> [gh-24931] Return dummy function for moving processes when running rootless 

.changelog/25294.txt, jobspec2/hcl_conversions.go
Nomad panics when parsing a job specification which contains a kill_timeout that is null.
This is normally caught with a validation error, but if the null is provided via a ternary expression false ? "5s" : null Nomad panics instead.
It fixes [25292](https://github.com/hashicorp/nomad/issues/25292)
I couldn't find any other places where not checking the nil value could lead to a panic.
in the …
=> Check for nil values when parsing HCL strings

enos/modules/upgrade_client/main.tf
The check to read back node metadata depends on a resource that waits for the Nomad API, but that resource doesn't wait for the metadata to be written in the first place (and the client subsequently upgraded). Add this dependency so that we're reading back the node metadata as the last step.
Ref: https://github.com/hashicorp/nomad-e2e/actions/runs/13690355150/job/38282457406
=> upgrade testing: add missing dependency during client upgrades

client/allocrunner/taskrunner/template/template.go, client/allocrunner/taskrunner/template/template_test.go
In https://github.com/hashicorp/nomad/pull/25217 we removed legacy Consul token based task authentication. Unfortunately this change removed all the logic to configure consul-template with a token which meant Consul based templates would always get "ACL not found" errors. This change adds the correct configuration setup entry back.
Not released and caught by testing.
No backport.
https://hashicorp.atlassian.net/browse/NET-12253
https://hashicorp.atlassian.net/browse/NET-10260 …
=> template: Set any Consul token generated by workload identity.

.changelog/25307.txt, client/allocrunner/taskrunner/plugin_supervisor_hook.go
When a CSI plugin is launched, we probe it until the csi_plugin.health_timeout expires (by default 30s). But if the plugin never becomes healthy, we're not restarting the task as documented.
Update the plugin supervisor to trigger a restart instead. We still exit the supervisor loop at that point to avoid having the supervisor send probes to a task that isn't running yet. This requires reworking the poststart hook to allow the supervisor loop to be restarted when the task restarts. In doing so, I identified that we weren't respecting the task kill context from the post start hook.
Fixes: https://github.com/hashicorp/nomad/issues/25293
Ref: https://hashicorp.atlassian.net/browse/NET-12264
For the happy path, run the [`demo/csi/hostpath`](https://github.com/hashicorp/nomad/tree/main/demo/csi …
=> CSI: restart task on failing initial probe, instead of killing it

e2e/terraform/outputs.tf, e2e/terraform/provision-infra/main.tf, e2e/terraform/provision-infra/outputs.tf, enos/enos-scenario-upgrade.hcl, enos/modules/run_workloads/jobs/tproxy.nomad.hcl, enos/modules/run_workloads/main.tf, enos/modules/run_workloads/scripts/create-consul-intention.sh, enos/modules/run_workloads/scripts/intention.hcl, enos/modules/run_workloads/variables.tf
Add an upgrade test workload for Consul service mesh with transparent proxy.
Note this breaks from the "countdash" demo. The dashboard application only can verify the backend is up by making a websocket connection, which we can't do as a health check, and the health check it exposes for that purpose only passes once the websocket connection has been made. So replace the dashboard with a minimal nginx reverse proxy to the count-api instead.
Ref: https://hashicorp.atlassian.net/browse/NET-12217
=> upgrade tests: add transparent proxy workload

.changelog/25310.txt, command/asset/consul-wi-default-policy.hcl
When Nomad registers a service within Consul it is regarded as a node service. In order for Nomad workloads to read these services, it must have an ACL policy which includes node_prefix read. If it does not, the service is filtered out from the result.
This change adds the required permission to the Consul setup command.
in the majority of situations. The main exceptions are long-lived feature …
=> cli: Add node_prefix read policy to Consul setup task policy.

contributing/README.md
Expand this document with some rough signposts to the major packages that developers will need to know about when getting started.
=> docs: extend code layout in contributing guides

.changelog/25328.txt, nomad/acl_endpoint.go, nomad/state/events.go, nomad/structs/acl.go, nomad/structs/acl_test.go
OIDC client secrets that users provide in auth method configuration are, well, secret, so we should hide them from API calls and event streams.
=> auth: redact auth method client secret

enos/enos-scenario-upgrade.hcl, enos/modules/run_workloads/jobs/writes-vars.nomad.hcl, enos/modules/run_workloads/scripts/configure-variables-acls.sh
Add an upgrade test workload for that continuously writes to a Nomad Variable. In order to run this workload, we'll need to deploy a Workload-Associated ACL policy. So this extends the `run_workloads` module to allow for a "pre script" to be run before a given job is deployed. We can use that as a model for other test workloads.
Ref: https://hashicorp.atlassian.net/browse/NET-12217
=> upgrade testing: Variables, Workload Identity, and Task API

go.mod, go.sum, lib/auth/oidc/request.go, lib/auth/oidc/request_test.go, nomad/acl_endpoint.go, nomad/acl_endpoint_test.go, nomad/server.go
#25231 introduced a cache of OIDC requests to retain some state (mainly PKCE verifier) in between auth-url and complete-auth requests on the server.
This follows up on some useful comments that folks had about the cache:
* order-of-operations concerns, potential attack vectors, and mentions LRU cache:
https://github.com/hashicorp/nomad/pull/25231#discussion_r1985550068
* limitations of my usage of `sync.Map`:
https://github.com/hashicorp/nomad/pull/25231#discussion_r1985740444
Here we replace just about the whole thing (you may as well read the whole `requests.go` file instead of a diff) and instead wrap an auto-expiring, thread-safe LRU: https://github.com/hashicorp/golang-lru
I do still think the wrapper has some utility, so I kept it instead of using the LRU directly in the `*ACL` RPC. …
=> auth: oidc request lru cache

api/host_volumes.go, client/hostvolumemanager/host_volume_plugin.go, client/hostvolumemanager/host_volume_plugin_test.go, client/hostvolumemanager/test_fixtures/test_plugin_sad.sh, command/agent/host_volume_endpoint.go, command/agent/host_volume_endpoint_test.go, command/volume_delete.go, website/content/docs/concepts/plugins/storage/host-volumes.mdx
Errors from `volume create` or `volume delete` only get logged by the client agent, which may make it harder for volume authors to debug these tasks if they are not also the cluster administrator with access to host logs.
Allow plugins to include an optional error message in their response. Because we can't count on receiving this response (the error could come before the plugin executes), we parse this message optimistically and include it only if available.
Ref: https://hashicorp.atlassian.net/browse/NET-12087
=> dynamic host volumes: allow plugins to return an error message

client/allocrunner/checks_hook_test.go, client/allocrunner/taskrunner/task_runner_test.go, client/client_test.go, client/consul/consul_test.go, command/agent/alloc_endpoint_test.go, command/agent/retry_join_test.go, command/helpers_test.go, go.mod, nomad/leader_test.go
I went to use a go 1.24 feature and found that my IDE didn't know what I was talking about, until I changed `go.mod` to `go 1.24` to align with #25249. That worked, but then running `go test` threw various complaints like
```
Error: nomad/leader_test.go:382:12: non-constant format string in call to (*testing.common).Fatalf
```
I made a little test workflow over here to track them down: https://github.com/hashicorp/nomad/actions/runs/13773711997
Fortunately the only complaints are these formatting nitpicks.
=> test: fix go 1.24 test complaints

api/acl.go, lib/auth/oidc/client_assertion.go, lib/auth/oidc/client_assertion_test.go, nomad/structs/acl.go, nomad/structs/acl_test.go
@dduzgun-security was nice enough to write a bunch of tests for us for #25231 :)
I changed some of em, and moved some logic into structs/
The main functional change here is that `Pem(Key|Cert)File` fields must be absolute paths.
=> oidc: more tests for client assertions

website/content/api-docs/acl/auth-methods.mdx, website/content/api-docs/acl/binding-rules.mdx, website/content/api-docs/acl/policies.mdx, website/content/api-docs/acl/roles.mdx, website/content/api-docs/acl/tokens.mdx
Just add api version prefix `/v1` in each path to be consistent with other api documentation and avoid confusion
=> docs: fix missing api version on acl path

website/content/api-docs/agent.mdx
Just add api version prefix `/v1` in each path to be consistent with other api documentation and avoid confusion
=> docs: fix missing api version on agent path

lib/auth/oidc/request.go
If the auth-url api is getting DOS'd, then we do not expect it to still function; we only protect the rest of the system.
Users will need to use a break-glass ACL token if they need Nomad UI/API access during such a denial of service.
=> auth: decrease size of oidc request cache

command/acl_auth_method.go
I opted to leave off the `PrivateKey` field, because a) it makes the left column huge, b) a `PemCert` value would be even huger, c) it's pretty advanced information, and d) it's easily accessible with `-json`
Example output:
```
$ nomad acl auth-method info my-auth-method
... existing stuff ...
Auth Method Config
JWT Validation Public Keys      = <none>
JWKS URL                        = <none>
OIDC Discovery URL              = http://localhost:8080/realms/Nomad
OIDC Client ID                  = nomad
OIDC Client Secret              = <none>
OIDC Client Assertion KeySource = nomad
OIDC Client Assertion Algorithm = RS256
OIDC Client Assertion Audience  = one,two
OIDC Client Assertion Headers   = {one: uno}; {two: dos}
OIDC Disable PKCE               = false
OIDC Disable UserInfo           = …
```
=> cli: acl auth-method info: add client assertion / pkce

enos/enos-scenario-upgrade.hcl, enos/enos-vars.hcl
Prerelease builds are in a different Artifactory repository than release builds. Make this a variable option so we can test prerelease builds in the nightly/weekly runs.
Ref: https://github.com/hashicorp/nomad-e2e/pull/161
Ref: https://hashicorp.atlassian.net/browse/NET-12274
=> upgrade testing: allow configurable artifactory repo

website/content/docs/integrations/consul/acl.mdx
Update the Consul ACL Docs, legacy (token) auth, to clarify that it doesn't support Consul Admin Partitions. While it was removed in 1.10, 1.8 and 1.9 are still supported so it's useful to have a clear warning about that in their versioned docs. …
=> update legacy Consul ACL doc to add a warning about Admin Partitions

nomad/host_volume_endpoint.go, nomad/host_volume_endpoint_test.go, nomad/state/state_store_host_volumes.go, nomad/state/state_store_host_volumes_test.go
If multiple dynamic host volumes are created in quick succession, it's possible for the server to attempt placement on a host where another volume has been placed but not yet fingerprinted as ready (which returns an error from the client). Once a `VolumeCreate` RPC returns a response, we've already invoked the plugin successfully and written to state, so we're just waiting on the fingerprint for scheduling purposes. Change the placement selection so that we skip a node if it has a volume, regardless of whether that volume is ready yet.
=> dynamic host volumes: don't wait for fingerprint to reserve node

.changelog/25378.txt, ui/app/controllers/jobs/index.js, ui/mirage/config.js, ui/tests/acceptance/jobs-list-test.js
Currently, when you search (filter) the jobs list page by typing in a single word, we use a shortcut to translate that to `Name contains "$query"`.
This is a nice sprinkling of sugar but it comes at the cost of being case sensitive.
This PR changes the "contains" to a "matches" and uses an inline regex modifier (which our go backend is kind enough to play nice with; see mirage/js implementation note below) to make it case insensitive
The above image does have the somewhat unsightly URL of `/ui/jobs?filter=Name%20matches%20%22(%3Fi)Fail%22` but the `(%3Fi)` is hardly the most egregious part of that.
Resolves #25316
=> [ui] Case-insensitive jobs list filtering

website/content/docs/concepts/scheduling/preemption.mdx
Hello 👋
Small fix about wording around delta priority needed to trigger preemption.
[Looking at the code ](https://github.com/hashicorp/nomad/blob/88ff5a7cae67152e4e6745100bff41af2efc05f6/scheduler/preemption.go#L339) delta priority needs to be greater or equal to 10 and not strictly greater.
=> Fix wording about delta priority needed to trigger preemption

e2e/terraform/provision-infra/scripts/consul-agents-policy.hcl
Service deregistrations in E2E were failing but this was going unnoticed because the consul config `default_policy` was defaulting to `allow`.  When this was changed to `deny`, service de-registration began failing due to this typo in the policy. …
=> e2e: fixes node write policy for consul agents

command/agent/command.go, command/agent/retry_join.go, command/agent/retry_join_test.go
The agent retry joiner implementation had different parameters to control its execution for agents running in server and client mode. The agent would set up individual joiners depending on the agent mode, making the object parameter overhead un-required.
This change removes the excess configuration options for the joiner, reducing code complexity slightly and hopefully making future modifications in this area easier to make.
Notes:
- no user facing changes, so PR doesn't require a changelog entry
- should backport to make future work and backports easier
the [website README](../website/README.md) for docs …
=> agent: Improve retry joiner code with small refactor.

website/content/docs/operations/metrics-reference.mdx
fix URL for periodic jobs
The original seems like a copy-pasta bug. Same url was being shown for `parameterized` and `periodic` jobs.
N/A
N/A
=> fix URL for periodic jobs

ui/app/controllers/storage/index.js, ui/app/routes/storage/index.js, ui/app/templates/storage/index.hbs, ui/tests/acceptance/storage-list-test.js, ui/tests/pages/storage/list.js
Adds live reload to Dynamic Host Volumes and CSI Volumes tables
Implements the watchQuery pattern in a bespoke way, kind of like what we do on the jobs index page.
(Note for reviewers: because Mirage doesn't have any kind of concept of "hold open this query until new data shows up on the server", we are manually triggering the JS functions that would run if one were observed)
- Make a dynamic host volume, say with `nomad volume create`
- Head to the storage page. Check out your network requests; there should be a pending one with ?index=$notZero, for both type=host and type=csi
- If you make another dynamic host volume, the type=host query should `200`, and a new volume should show up on your page.
- The blocking query should kick back off a moment or two later
- When you leave the page, …
=> [ui] Custom watchQuery equivalent on the storage index

.github/actions/setup-js/action.yml, .github/workflows/build.yml, .github/workflows/release.yml, ui/app/index.html
A note:
- Node v20 will be under [maintenance LTS mode until May 2026](https://nodejs.org/en/about/previous-releases), at which point it will fall out of support
- Node v22 is out and preferable, but comes with a few necessary internal upgrades. Notably:
- An upgrade to Ember Data, which requires
- A move away from Ember Data Model Fragments, which are used extensively throughout our codebase
- Some node-sass related changes
- Surely some other esm-related things
We have not prioritized these upgrades because the cost has seemed greater than the payoff. This might change under end-of-life node version scenarios next year, but the development cost is non-trivial.
=> [ci/cd] Moves our default github action flows to use Node v20

drivers/docker/driver_test.go
Docker driver's `TestDockerDriver_OOMKilled` should run on cgroups v2 now, since we're running [docker v27 client library](https://github.com/hashicorp/nomad/blob/release/1.10.0-beta.1/go.mod#L29) and our runners run docker v26 that contain containerd fix https://github.com/containerd/containerd/pull/6323. 
With cgroups v2:
```
$ go test -v -timeout 30s -count 10 -run ^TestDockerDriver_OOMKilled$ github.com/hashicorp/nomad/drivers/docker
🎬🎬🎬
driver_test.go:2615: Successfully killed by OOM killer
2025-03-19T16:39:25.419+0100 [DEBUG] go-plugin@v1.6.2/grpc_stdio.go:142: docker.docker_logger.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = error reading from server: EOF"
2025-03-19T16:39:25.421+0100 [INFO]  go-plugin@v1.6.2/client.go:780: …
```
=> docker: `TestDockerDriver_OOMKilled` should run on cgroups v2

.changelog/25157.txt, client/allocrunner/group_service_hook.go, client/allocrunner/group_service_hook_test.go
When all the tasks in an allocation have completed, the allocation will run the PostRun hooks, and deregister the task.  When that happens, it is not necessary to wait on the shutdown_delay during garbage collection.
=> client: skip shutdown delay when tasks already deregistered

.changelog/25441.txt, command/agent/agent.go, command/agent/agent_endpoint_test.go, command/agent/agent_test.go, nomad/leader_test.go, nomad/server.go, nomad/server_test.go
The `server.num_scheduler` configuration value should be a value between 0 and the number of CPUs on the machine. The Nomad agent was not validating the configuration parameter which meant you could use a negative value or a value much larger than the available machine CPUs. This change enforces validation of the configuration value both on server startup and when the agent is reloaded.
The Nomad API was only performing negative value validation when updating the scheduler number via this method. This change adds to the validation to ensure the number is not greater than the CPUs on the machine.
Out documentation currently correctly states the expected value bounds: https://developer.hashicorp.com/nomad/docs/configuration/server#num_schedulers
Using the configuration example below, try …
=> server: Validate config num schedulers is between 0 and num CPUs.

website/content/docs/drivers/docker.mdx
From [NET-12322]
Docker task driver, `sysctl` parameter. HCL expects a key-value map, but JSON expects an array of maps. Add warning that JSON expects an array of maps.
Jira: [CE-837] [NET-12322]
Deploy preview: https://nomad-git-ce837sysctl-hashicorp.vercel.app/nomad/docs/drivers/docker#sysctl
[NET-12322]: https://hashicorp.atlassian.net/browse/NET-12322?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CE-837]: https://hashicorp.atlassian.net/browse/CE-837?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[NET-12322]: …
=> Docs: Add JSON format note to docker driver sysctl parameter

.github/workflows/build.yml
arm GHA runners currently do not support private repositories.
=> build: split minimum-os job into 2 and only run arm checks on CE

client/client_test.go, client/heartbeatstop_test.go, nomad/client_alloc_endpoint_test.go, nomad/client_fs_endpoint_test.go, nomad/csi_endpoint_test.go, nomad/eval_broker_test.go, nomad/heartbeat_test.go, nomad/job_endpoint_test.go, nomad/leader_test.go, nomad/node_endpoint_test.go, nomad/serf_test.go, nomad/stats_fetcher_test.go
Smattering of *test only* data race fixes. Individual commits have details, but the recurring theme is adding locking around peeking at internal shared struct fields.
```
go test -race
```
Related to #12098 but unfortunately doesn't squash any of those. …
=> tests: Fixes a few data races in tests

website/content/api-docs/volumes.mdx, website/content/docs/commands/node/drain.mdx, website/content/docs/commands/volume/create.mdx, website/content/docs/commands/volume/delete.mdx, website/content/docs/commands/volume/register.mdx, website/content/docs/commands/volume/snapshot-create.mdx, website/content/docs/commands/volume/snapshot-delete.mdx, website/content/docs/commands/volume/snapshot-list.mdx, website/content/docs/concepts/filesystem.mdx, website/content/docs/ecosystem.mdx, website/content/docs/operations/stateful-workloads.mdx, website/content/docs/partnerships.mdx
1.10 beta docs
Fix broken links to CSI concepts page, which changed location. The redirect is in `redirects.js`: 
```js
// CSI plugins moved under new storage path alongside new host volume plugins
{
source: '/nomad/docs/concepts/plugins/csi',
destination: '/nomad/docs/concepts/plugins/storage/csi',
permanent: true,
},
```
But that isn't working for the 1.10 beta docs due to `v1.10.x` in the beta URL. So update the pages with the broken link rather than add a version-based redirect for the 1.10 beta URL.
**Merge into `main` only.**
Jira: [CE-839]
[CE-839]: …
=> Docs: fix broken links in 1.10 beta docs

.changelog/25472.txt, client/allocrunner/allocdir_hook.go, client/allocrunner/checks_hook.go, client/allocrunner/checks_hook_test.go, client/allocrunner/consul_grpc_sock_hook.go, client/allocrunner/consul_hook.go, client/allocrunner/consul_hook_test.go, client/allocrunner/consul_http_sock_hook.go, client/allocrunner/cpuparts_hook.go, client/allocrunner/csi_hook.go, client/allocrunner/csi_hook_test.go, client/allocrunner/fail_hook.go, client/allocrunner/group_service_hook.go, client/allocrunner/group_service_hook_test.go, client/allocrunner/health_hook.go, client/allocrunner/health_hook_test.go, client/allocrunner/identity_hook.go, client/allocrunner/identity_hook_test.go, client/allocrunner/migrate_hook.go, client/allocrunner/network_hook.go, client/allocrunner/network_hook_test.go, client/allocrunner/upstream_allocs_hook.go
While working on #25373, I noticed that the CSI hook's `Destroy` method doesn't match the interface, which means it never gets called. Because this method only cancels any in-flight CSI requests, the only impact of this bug is that any CSI RPCs that are in-flight when an alloc is GC'd on the client or a dev agent is shut down won't be interrupted gracefully.
Fix the interface, but also make static assertions for all the allocrunner hooks in the production code, so that you can make changes to interfaces and have compile-time assistance in avoiding mistakes.
Ref: https://github.com/hashicorp/nomad/pull/25373
the …
=> client: statically assert hook interfaces in build

command/agent/agent_endpoint_test.go
This fix already went into the release/1.{7,8}.x+ent branches. Replicating this change into the final release branches.
=> test: Calculate agent endpoint scheduler count, not static.

.changelog/25428.txt, nomad/csi_endpoint.go, nomad/csi_endpoint_test.go, nomad/state/state_store.go, nomad/volumewatcher/volume_watcher.go
If a CSI volume is has terminal allocations, the volumewatcher will submit an `Unpublish` RPC. But the "past claim" we create is missing the "external" node identifier (ex. the AWS EC2 instance ID). The unpublish RPC can tolerate this if the node still exists in the state store, but if the node has been GC'd the controller unpublish step will return an error. But at this point we've already checkpointed the unpublish workflow, which triggers a notification on the volumewatcher. This results in the volumewatcher getting into a tight loop of retries. Unfortunately even if we somehow break the loop (perhaps because we hit a different code path), we'll kick off this loop again after a leader election when we spin up the volumewatchers again.
This changeset includes the following:
* Fix the …
=> CSI: prevent loop in volumewatcher when node is GC'd

website/content/docs/configuration/server.mdx
Fix link rendering in /configuration/server#default_scheduler_config.
**Current**
**Fix**
Jira: [CE-821]
https://nomad-git-ce821link-hashicorp.vercel.app/nomad/docs/configuration/server#default_scheduler_config
[CE-821]: https://hashicorp.atlassian.net/browse/CE-821?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Docs: Fix link rendering in server.default_scheduler_config

website/content/docs/configuration/server.mdx
Manual backport of https://github.com/hashicorp/nomad/pull/25482 since https://github.com/hashicorp/nomad/pull/25485 failed.
=> Docs: Manual back to release/1.8.x of Fix link rendering in server.default_scheduler_config (#25482)

website/content/docs/configuration/server.mdx
Manual backport of https://github.com/hashicorp/nomad/pull/25482 since https://github.com/hashicorp/nomad/pull/25484 failed. 
The backport to 1.7.x+ent failed. Is there a way to automatically backport this PR? I added the backport label but IIRC that doesn't work when merging to a branch...
=> Docs: Manual backport to release/1.7.x of Fix link rendering in server.default_scheduler_config (#25482)

enos/modules/run_workloads/jobs/plugin-nfs-controllers.nomad.hcl
The nfs controller takes a long time to start and that was causing the upgrade scenario to fail locally because it was timing out. This PR increases the health time out. 
=> Give the nfs controller a longer start up time

enos/enos-quality.hcl, enos/enos-scenario-upgrade.hcl, enos/modules/upgrade_client/main.tf, enos/modules/upgrade_client/scripts/verify_allocs.sh
There was a quality in the upgrade scenario that was not being tested yet, we need to make sure the workloads are not stopped when the agent stops on a client and that they reattach when the agent comes back up.
This PR introduces a check that looks up any running alloc on a client before the upgrade and verifies that the same ones are running after the upgrade.
in the majority of situations. The …
=> Add a test for re attaching allocs after client restart

go.mod, go.sum
Backports of:
* https://github.com/hashicorp/nomad/pull/25495
* https://github.com/hashicorp/nomad/pull/25493
* https://github.com/hashicorp/nomad/pull/25494
* https://github.com/hashicorp/nomad/pull/25491
* https://github.com/hashicorp/nomad/pull/25490
=> Consolidated dependabot backports to 1.9.x

.github/dependabot.yml
When we updated the codeowner for the website directory to include the "web presence" group, we didn't also update the dependabot reviewer. This results in errors in dependabot PRs.
Ref: https://github.com/hashicorp/nomad/pull/25492#issuecomment-2746105976
=> dependabot: update reviewer for website directory

command/volume_create_host.go
The volume object does not have the indexes set which is a symptom of the FSM and RPC workings. If the create CLI runs against a follower, the subsequent monitor command might error with a 404 code because the follower does not have the object in state and the wait index is set to zero.
No changelog or backport needed.
in the majority of situations. The main exceptions are long-lived feature …
=> cli: Use meta response index to start monitoring volume create.

.changelog/25253.txt, client/pluginmanager/csimanager/volume.go
Fix the checking of the staging path against the mountRoot on the host rather then checking against the containerMountPoint which (probably) never exists on the host causing it to default back the the legacy behaviour.
Should be easily reproducible on any csi driver supporting ExpandVolume and has nomad namespaces enabled. Tested with nomad enterprise 1.8.5
https://github.com/hashicorp/nomad/issues/24465
backporting …
=> Fix CSI ExpandVolume stagingPath

enos/modules/upgrade_client/scripts/verify_allocs.sh
There is a typo on the verify allocs script on the upgrade client module of the upgrade test.
=> Fix for wrong function name on verify allocs script

website/content/docs/commands/volume/create.mdx, website/content/docs/concepts/plugins/storage/host-volumes.mdx, website/content/docs/other-specifications/volume/host.mdx
Describe the built-in `mkdir` plugin in the plugin concepts docs in a little more detail. Crosslink to there from the `plugin_id` field docs, and clarify that the `mkdir` plugin doesn't support the capacity request fields.
Update the example plugins to avoid using volume author controlled variables in favor of Nomad-controlled ones, to reduce the risk of path traversal, and explain to plugin authors they'll likely want to avoid this in their own plugins.
Preview links:
* https://nomad-git-docs-dhv-tweaks-hashicorp.vercel.app/nomad/docs/commands/volume/create
* https://nomad-git-docs-dhv-tweaks-hashicorp.vercel.app/nomad/docs/concepts/plugins/storage/host-volumes
* https://nomad-git-docs-dhv-tweaks-hashicorp.vercel.app/nomad/docs/other-specifications/volume/host
=> docs: expand info on built-in mkdir dynamic host volume plugin

nomad/acl_endpoint.go
Auth method create/update APIs only work for someone who has the OIDC client's secret(s) in hand, but that could be a CI system, which might log output in the clear.
Attn: @dduzgun-security 
Follow-up to PR #25328 which includes doc changes and a changelog.
=> auth: sanitize auth method in create/update reply

.changelog/25528.txt, nomad/structs/diff.go, nomad/structs/diff_test.go
Is it a bug or a feature, I could see either side of this but marking as a bug initially which allows backporting.
Closes #25522 
=> job: Add migrate block detail when performing task group diff

e2e/terraform/provision-infra/compute.tf
Require Instance Metadata Service v2 to access EC2 instance metadata for all VMs that run our e2e suite. 
Internal ref: https://hashicorp.atlassian.net/browse/SECVULN-18860
=> e2e: require IMDSv2 for ec2 instances

client/fingerprint/dynamic_host_volumes.go, client/host_volume_endpoint.go, client/hostvolumemanager/host_volume_plugin.go, client/hostvolumemanager/host_volume_plugin_test.go, client/hostvolumemanager/host_volumes.go, command/volume_create_host_test.go, nomad/mock/host_volumes.go, website/content/docs/concepts/plugins/storage/host-volumes.mdx, website/content/docs/other-specifications/volume/host.mdx
Our friend @ygersie [requested an option](https://github.com/hashicorp/nomad/pull/24479#issuecomment-2754239594) to change perms/ownership on the directory that our built-in `mkdir` plugin creates, which is a nice idea, so let's do it!
=> dhv: mkdir plugin parameters: uid,guid,mode

e2e/consul/namespaces.go, e2e/e2eutil/consul.go
For the Consul E2E tests to function with workload identity, the nomad policy and associated role need to be present in the consul namespace that the nomad task is registering in.
=> e2e: create consul policies and roles in respective namespaces

e2e/terraform/provision-infra/compute.tf
Consul needs to use a newer version of go-discover that can query IMDSv2 in order for our test infrastructure to be enabled with it.
=> e2e: disable IMDSv2 in tests

website/content/plugins/drivers/podman.mdx
Adds missing Podman task config options to the Podman driver docs.
=> docs: add missing podman task config options

website/content/docs/configuration/consul.mdx
When using Nomad with Consul, each Nomad agent is expected to have a Consul agent running alongside. When using Nomad Enterprise and Consul Enterprise together, the Consul agent may be in a Consul admin partition. In order for Nomad's "anti-entropy" sync to work with Consul, the Consul ACL token and ACL policy for the Nomad client must be in the same admin partition as the Consul agent. Otherwise, we can register services (via WI) but then won't be able to deregister them unless they're the default namespace.
Ref: https://hashicorp.atlassian.net/browse/NET-12361
Preview link: https://nomad-git-docs-consul-partitions-agents-hashicorp.vercel.app/nomad/docs/configuration/consul
=> docs: document requirements for Consul tokens in admin partitions

nomad/host_volume_endpoint.go, nomad/leader.go
All Nomad servers should be running v1.10.0 before the DHV feature can be used. Without this, it is possible for a write to succeed and cause immediate loss and subsequant failure to establish leadership.
I had the following setup:
- 1 Nomad client on 1.10.0-beta.1
- 1 Nomad server on 1.10.0-beta.1
- 2 Nomad servers on 1.9.7
I ran the following steps:
- Transferred leadership to the Nomad server running 1.10.0-beta.1
- Stopped the Nomad service running on the older servers to force the node connection to go to the leader
- Started the stopped services
- Ensured my CLI used the 1.10.0-beta.1 API address
- Ran the nomad volume create command which returned the monitor
The cluster lost leadership and cannot elect a new leader. The older version servers have the following interesting log …
=> volumes: Version gate create/delete host volume RPCs.

e2e/terraform/provision-infra/provision-nomad/etc/nomad.d/base.hcl
Some of our E2E utils parse Nomad commands, and fail if CLI hints are enabled.
=> e2e: disable cli hints for command parsing

e2e/ui/package-lock.json, e2e/ui/package.json, e2e/ui/run.sh
Spiritual successor to #24956 
```
Error: browserType.launch: Executable doesn't exist at /ms-playwright/chromium_headless_shell-1161/chrome-linux/headless_shell
╔══════════════════════════════════════════════════════════════════════╗
║ Looks like Playwright Test or Playwright was just updated to 1.51.1. ║
║ Please update docker image as well.                                  ║
║ -  current: mcr.microsoft.com/playwright:v1.50.0-jammy               ║
║ - required: mcr.microsoft.com/playwright:v1.51.1-jammy               ║
║                                                                      ║
║ <3 Playwright Team                                                   ║
╚══════════════════════════════════════════════════════════════════════╝
```
=> Update playwright to 1.51.0 for e2e ui tests

.changelog/25581.txt, client/allocrunner/network_hook.go
In #24658 we fixed a bug around client restarts where we would not assert network namespaces existed and were properly configured when restoring allocations. We introduced a call to the CNI `Check` method so that the plugins could report correct config. But when we get an error from this call, we don't log it unless the error is fatal. This makes it challenging to debug the case where the initial check fails but we tear down the network and try again (as described in #25510). Add a noisy log line here.
Ref: https://github.com/hashicorp/nomad/pull/24658
Ref: https://github.com/hashicorp/nomad/issues/25510
=> cni: add warning log for CNI check command failures

.changelog/25511.txt, drivers/rawexec/driver.go, drivers/rawexec/driver_test.go, website/content/docs/drivers/raw_exec.mdx
Adds a raw exec plugin config option enabling users to define a list of environment variable names to be dropped from all or a single task's environment, as requested in [issue #17650](https://github.com/hashicorp/nomad/issues/17650). 
Configuration is accepted in the form of a `DeniedEnvars` option added to the rawexec driver and task config structs and rpcs and includes simple globbing support, defined as "prefix & suffix" in the documentation.
[issue #17650](https://github.com/hashicorp/nomad/issues/17650)
change …
=> modify rawexec TaskConfig and Config to accept envvar denylist

enos/enos-scenario-upgrade.hcl
The CSI workload we're using for upgrade testing seems to be flaky to come up. The plugin jobs don't launch in a timely fashion despite several attempts. In order to not block running the rest of the upgrade testing, let's disable this workload temporarily. We'll fix this in NET-12430.
Ref: https://hashicorp.atlassian.net/browse/NET-12430
=> upgrade testing: temporarily disable CSI workload

api/acl.go, command/acl_auth_method.go, internal/testing/apitests/acl_test.go, nomad/acl_endpoint.go, nomad/acl_endpoint_test.go, nomad/mock/acl.go, nomad/structs/acl.go, website/content/docs/upgrade/upgrade-specific.mdx, website/content/partials/api-docs/auth-method-params.mdx
Trying not to violate the principle of least astonishment.
We want to only auto-enable PKCE on *new* auth methods, rather than *new or updated* auth methods, to avoid a scenario where a Nomad admin updates an auth method sometime in the future -- something innocent like a new client secret -- and their OIDC provider doesn't like PKCE.
The main concern is that the provider won't like PKCE in a totally confusing way. Error messages rarely say PKCE directly, so why the user's auth method suddenly broke would be a big mystery.
This means that to enable it on existing auth methods, you would set `OIDCDisablePKCE = false`, and the double-negative doesn't feel right, so instead, swap the language, so enabling it on *existing* methods reads sensibly, and to disable it on *new* methods reads …
=> auth: oidc: enable pkce only on new auth methods

lib/auth/oidc/client_assertion.go, lib/auth/oidc/client_assertion_test.go, lib/auth/oidc/provider.go, nomad/structs/acl.go, nomad/structs/acl_test.go
Couple small things, neither strictly necessary, but "fit and finish":
1. Modify how we skip sending an OIDC client secret the non-client-assertion way if `PrivateKey.KeySource = "client_secret"`, mainly so that it still shows up as `redacted` instead of `<none>` in the output of `nomad acl auth-method info`
2. Allow some flexibility in how users provide custom key/cert. It can be fiddly to get newlines in the exact right places (required after the header, and before the footer), so adding ~~header/footer and~~ newlines in the right spots makes it easier to configure.
=> auth: oidc client assertion tweaks

.release/versions.hcl
With the release of Nomad 1.10.0-rc.1, we'll start backporting to the 1.10.x release series. Add this to the supported versions and remove 1.7.x.
(This step appears to be missing from https://github.com/hashicorp/nomad-releases/issues/432; I'll update that checklist)
=> release: update backport versions for 1.10.0

.github/workflows/build.yml
The investigation is long, so I'll ask reviewers to use the linked Jira to gain addition context. This should resolve an issue identified in our build/release process that has resulted in release revisions including `+CHANGES`.
Jira: https://hashicorp.atlassian.net/browse/NET-12429
history should be …
=> ci: Run the build workflow on pushes to long-lived branches only.

api/acl.go, command/acl_auth_method.go, internal/testing/apitests/acl_test.go, nomad/acl_endpoint.go, nomad/acl_endpoint_test.go, nomad/mock/acl.go, nomad/structs/acl.go, website/content/partials/api-docs/auth-method-params.mdx
~I introduced a bug in #25593: PKCE was properly enabled by default on new auth methods, but then create/update-ing the same auth method, it got set to `nil` and got stuck that way until being explicitly enabled.~
Even with this original bugfix in this PR, it would still leave unintuitive behavior, namely that removing the `OIDCEnablePKCE` field from an existing auth method that had it set to `*false` would not default-enable it as one might expect, but rather leave it at whatever its last value was: still disabled.
So instead, we'll do the safest and most straightforward implementation, and do a simple `bool` that must be explicitly enabled.
=> auth: oidc: disable pkce by default

e2e/terraform/provision-infra/provision-nomad/etc/nomad.d/base.hcl
The `ui.enabled` parameter is a non-pointer bool which means the merge function is unable to differentiate between false and not set. When e2e introduced the `ui.show_cli_hints` configuration parameter, the way we merge meant the UI became disabled.
As a follow up, we should consider expanding our documentation to detail this, or change the `enabled` variable to a pointer, so we can differentiate between false and not set.
Run a Nomad agent locally in development mode with the following config snippet:
```hcl
ui {
show_cli_hints = true
}
```
the [website README](../website/README.md) for docs guidelines. Please also …
=> e2e: Ensure UI is enabled.

client/allocrunner/taskrunner/api_hook.go, client/allocrunner/taskrunner/dynamic_users_hook.go, client/allocrunner/taskrunner/identity_hook.go, client/client.go, client/widmgr/widmgr.go, nomad/job_endpoint.go, nomad/leader.go, nomad/locks.go, scheduler/scheduler_system.go
Arguments passed to hclog log lines should always have an even number to provide the expected k/v output.
Related #25628 
=> agent: Fix misaligned contextual k/v logging arguments.

website/content/docs/commands/operator/root/keyring-remove.mdx
Replaces failed automatic backport https://github.com/hashicorp/nomad/pull/25645
* Add note to root keyring remove command
This PR updates the documentation for the root keyring remove command to note that the full key ID must be provided for the command to function correctly.
* Move keyID explanation to usage section
---------
=> Docs: Manual backport of Add note to root keyring remove command (#25637) to release/1.8.x

CHANGELOG.md
Manual backport of #25654 because #25655 failed
=> Backport (manual) of Add changelogs for 1.9.8+ent and 1.8.12+ent into release/1.10.x

.changelog/25340.txt, scheduler/numa_ce.go, scheduler/numa_ce_test.go
We were using version `1.6.10` with a configuration for the reservable cores as the following:
`reservable_cores = "1-31,33-63"`
If the available cores are not a continuous set, the core selector might panic when trying to select cores. This happened when we tried to upgrade to version `1.7.7`.
For example, consider a scenario where the available cores for the selector are the following:
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47]
This list contains 46 cores, because cores with IDs 0 and 24 are not included in the list
Before this patch, if we requested 46 cores, the selector would panic trying to access the item with index 46 in `cs.topology.Cores`.
This …
=> Use core ID when selecting cores

.github/workflows/copywrite.yml, scheduler/numa_ce_test.go
This updates our copywrite CI check to run in all the same circumstances as our other checks, which will help this from falling through the cracks during reviews.
=> CI: run copywrite on PRs, not just after merges

api/go.mod, api/go.sum, api/internal/testutil/server.go, client/allocdir/testing.go, client/allocrunner/tasklifecycle/testing.go, client/config/testing.go, client/lib/proclib/testing.go, client/testing.go, go.mod, helper/pluginutils/catalog/testing.go, nomad/mock/acl.go, nomad/testing.go, testutil/file.go, testutil/mock_calls.go, testutil/server.go, testutil/vault.go
The stdlib testing package now includes this interface, so we can remove our dependency on the external library.
Final uses are external to this repository:
```console
$ go mod why -m github.com/mitchellh/go-testing-interface
github.com/hashicorp/nomad/client/allocrunner/taskrunner/getter
github.com/hashicorp/go-getter
github.com/mitchellh/go-testing-interface
```
Jira: https://hashicorp.atlassian.net/browse/NET-11447 …
=> test: Remove use of "mitchellh/go-testing-interface" for stdlib.

.github/nomad-builder/Dockerfile, .github/workflows/build.yml
This introduces a docker image based off of `ubuntu:bionic` that can be used to compile Nomad binary against glibc 2.27.
The image cannot build JS assets, which must be created before we compile the Go binary. 
Demonstration:
```
$ docker run -ti -v $(pwd)/build:/tmp/build nomad-builder
root@700996484f70:/# cd /tmp/build
root@700996484f70:/tmp/build# git clone https://github.com/hashicorp/nomad.git
Cloning into 'nomad'...
remote: Enumerating objects: 310410, done.
remote: Counting objects: 100% (274/274), done.
remote: Compressing objects: 100% (157/157), done.
remote: Total 310410 (delta 186), reused 117 (delta 117), pack-reused 310136 (from 4)
Receiving objects: 100% (310410/310410), 560.45 MiB | 38.19 MiB/s, done.
Resolving deltas: 100% (221073/221073), done. …
```
=> build: use nomad-builder docker image to build Nomad

.github/workflows/build.yml
TSCCR checker has been complaining about this on enterprise repository.
=> ci: pin docker/build-push-action to a TSCCR approved version

.github/workflows/actionlint.yml, .github/workflows/backport.yml, .github/workflows/build.yml, .github/workflows/copywrite.yml, .github/workflows/jira-sync.yml, .github/workflows/lock.yml, .github/workflows/release.yml, .github/workflows/semgrep.yml, .github/workflows/test-core.yaml, .github/workflows/test-e2e.yml, .github/workflows/test-failure-notification.yml, .github/workflows/test-ui.yml
Our runners are a mixture of `ubuntu-latest`, `ubuntu-22.04` and `ubuntu-20.04`. Seeing as 20.04 is reaching end of support and becoming a security vulnerability, we should unify our CI infrastructure and pin it to the latest LTS. 
_caution:_ Do not merge this before https://github.com/hashicorp/nomad/pull/25626 lands.
=> ci: migrate runners to ubuntu-22.04

.github/workflows/actionlint.yml, .github/workflows/backport.yml, .github/workflows/build.yml, .github/workflows/copywrite.yml, .github/workflows/jira-sync.yml, .github/workflows/lock.yml, .github/workflows/release.yml, .github/workflows/semgrep.yml, .github/workflows/test-core.yaml, .github/workflows/test-e2e.yml, .github/workflows/test-failure-notification.yml, .github/workflows/test-ui.yml
Manual backport of #25651 because we need to be able to run CI on this branch when we backport PRs for documentation without it blowing up.
* ci: migrate runners to ubuntu-22.04
* find a supported build for custom-linux-xl
=> Backport ci: migrate runners to ubuntu-22.04 to 1.9.x (#25651)

.github/workflows/actionlint.yml, .github/workflows/backport.yml, .github/workflows/build.yml, .github/workflows/copywrite.yml, .github/workflows/lock.yml, .github/workflows/release.yml, .github/workflows/semgrep.yml, .github/workflows/test-core.yaml, .github/workflows/test-e2e.yml, .github/workflows/test-ui.yml
Manual backport of #25651 because we need to be able to run CI on this branch when we backport PRs for documentation without it blowing up.
* ci: migrate runners to ubuntu-22.04
* find a supported build for custom-linux-xl
=> Backport ci: migrate runners to ubuntu-22.04 to 1.8.x. (#25651)

.github/workflows/build.yml
Having `.dockerbuild` as one of the artifacts messes with our release tooling. 
example `build` run with this change: https://github.com/hashicorp/nomad/actions/runs/14472045048
=> ci: disable docker build summary

enos/modules/test_cluster_health/scripts/allocs.sh, enos/modules/upgrade_client/main.tf, enos/modules/upgrade_client/scripts/verify_allocs.sh, enos/modules/upgrade_servers/main.tf
Right now the upgrade test is extremely flaky and not easy to debug because the information is not complete and the cluster is destroyed upon finishing, either it fails or not. This PR adds some more debug information to helps us pin point the cause of the errors in the future. It also adds a delay to let the cluster run a little more and collect some more information.
in the majority of …
=> Add some more debug information in case of failure

.github/workflows/backport.yml
Fixes logging issues with the errors we've been getting for backport failures, which will help us further diagnose the problem.
Ref: https://hashicorp.atlassian.net/browse/NET-11804
=> update BPA to 0.5.6

.github/workflows/backport.yml
Update BPA to avoid problems when requerying for reviewers.
Ref: https://github.com/hashicorp/backport-assistant/pull/152
Ref: https://hashicorp.atlassian.net/browse/NET-11804
=> update backport assistant to 0.5.7

.github/workflows/test-core.yaml
Nomad is released as a Linux arm64 binary, so having a compilation step on this OS/ARCH within our core test workflow will help ensure basic arm64 problems do not get into our release branches.
I tested this change on Enterprise to ensure the conditional works as expected and the repository has access to the runners required. Ref: https://github.com/hashicorp/nomad-enterprise/actions/runs/14473962830/job/40594856618
Internal ref: NET-12466 …
=> ci: Compile on Ubuntu arm64 within core test workflow.

.changelog/25698.txt, nomad/structs/structs.go, scheduler/generic_sched.go, scheduler/generic_sched_test.go, scheduler/reconcile.go, scheduler/reconcile_util.go
In #12319 we fixed a bug where updates to the reschedule tracker would be dropped if the follow-up allocation failed to be placed by the scheduler in the later evaluation. We did this by mutating the previous allocation's reschedule tracker. But we did this without copying the previous allocation first and then making sure the updated copy was in the plan. This is unfortunately unsafe and corrupts the state store on the server where the scheduler ran; it may cause a race condition in RPC handlers and it causes the server to be out of sync with the other servers. This was discovered while trying to make all our tests race-free, but likely impacts production users.
Copy the previous allocation before updating the reschedule tracker, and swap out the updated allocation in the plan. This also …
=> scheduler: fix state corruption from rescheduler tracker updates

.changelog/25714.txt, client/allocrunner/network_manager_linux.go, client/lib/nsutil/netns_linux.go
Nomad was holding open the namespace file handle, which would eventually get cleaned up by garbage collection. In batch jobs that ran very quickly, it was possible the leaked file handle was still open, and causing errors when attempting to unmount the namespace.
In addition to closing the file handle, we can use a `MNT_DETACH` flag when unmounting to ensure that in the event a namespace file handle is left open, the namespace is still unmounted eventually and no resources are leaked.
Fixes [GH#25610](https://github.com/hashicorp/nomad/issues/25610)
See [GH#25610](https://github.com/hashicorp/nomad/issues/25610) for reproduction steps.  In addition, you can see Nomad accessing the namespace file via shimming in an `exec.Command("fuser", -v, nsPath)` right before unmounting. This can be …
=> client: close namespace file handle and defensively lazy unmount

.changelog/25716.txt, command/meta.go, command/operator_debug.go
Fixes #25672 - tl;dr `NOMAD_REGION` and `NOMAD_NAMESPACE` are ignored by `nomad operator debug`
I thought about having `Meta.clientConfig()` _write_ `Meta.region` and `Meta.namespace`, but that felt off, so I opted for a couple of getters that can hopefully be easily discovered if needed for other cases.
Before:
```
$ NOMAD_REGION=global NOMAD_NAMESPACE=default nomad operator debug
Starting debugger...
Nomad CLI Version: Nomad v1.10.0
BuildDate 2025-04-09T16:40:54Z
Revision e26a2bd2acac2dcdcb623f4d293bac096beef478
Region:
Namespace:
Servers: (1/1) ... etc etc ...
```
After:
```
$ NOMAD_REGION=global NOMAD_NAMESPACE=default nomad operator debug
Starting debugger...
Nomad CLI Version: Nomad v1.10.1-dev
BuildDate 2025-04-21T18:49:12Z
Revision c86d63da13145326ae69649fa9c51601dc16914a+CHANGES …
```
=> cli: operator debug: respect NOMAD_REGION env var

api/util_test.go, command/agent/acl_endpoint.go, nomad/acl_endpoint.go, nomad/acl_endpoint_test.go
`ResolveToken` RPC endpoint was only used by the `/acl/token/self` API. We should migrate to the WI-aware `WhoAmI` instead. 
Related to https://github.com/hashicorp/nomad/issues/24663
Internal ref: https://hashicorp.atlassian.net/browse/NET-11867
=> acl: use WhoAmI RPC endpoint in /acl/token/self

.changelog/25705.txt, scheduler/generic_sched_test.go, scheduler/util.go
When an alloc is running with the core resources specified, and the alloc is able to be updated in place, the cores it is running on should be preserved.
This fixes a bug where the allocation's task's core resources (CPU.ReservedCores) would be recomputed each time the reconciler checked that the allocation could continue to run on the given node. Under circumstances where a different core on the node became available before this check was made, the selection process could compute this new core as the core to run on, regardless of core the allocation was already running on. The check takes into account other allocations running on the node with reserved cores, but cannot check itself.
When this would happen for multiple allocations being evaluated in a single plan, the selection process …
=> Preserve core resources during inplace service alloc updates

website/content/plugins/drivers/podman.mdx
incorrect parameter documented for TLS verify parameter for podman task driver. Currently states `tlsVerify`, but needs to be `tls_verify`
when using the tlsVerify parameter and submitting a job with podman task driver this error is thrown: 
`* failed to parse config: * Invalid label: No argument or block type is named "tlsVerify". Did you mean "tls_verify"?`
in the majority of situations. The …
=> podman tls_verify doc fix

.github/workflows/jira-sync.yml
Removing custom fields no longer available, adding GitHub as a tag (in addition to community), and setting native Jira Team.
=> Testing Revised Jira Fields

e2e/docker/docker_test.go
The fresh deployment of the Redis job took around 20s which is also the default context timeout on the e2e util that monitors and waits for a deployment to complete.
The tight timing meant the test often timed out but sometimes would complete successfully. Increasing the timeout for this deployment will remove the flakiness.
Ran against an e2e cluster:
```console
$ go test -count 1 -v -run TestDocker ./...
=== RUN   TestDocker
docker_test.go:54: Setting up insecure private registry at 172.31.93.113:23700
=== RUN   TestDocker/testRedis
=== RUN   TestDocker/testAuthBasic
docker_test.go:91: test disabled until we have a local docker registry setup with tf
=== RUN   TestDocker/testAuthFileStatic
docker_test.go:107: test disabled until we have a local docker registry setup with tf
=== RUN …
```
=> e2e: Fix TestDocker/testRedis with increased timeout on deployment

e2e/ui/package-lock.json, e2e/ui/package.json, e2e/ui/run.sh
Snippet from run against an e2e cluster:
```console
Running 2 tests using 2 workers
✓  1 [webkit] › tests/example.spec.js:8:1 › authenticated users can see their policies (2.8s)
✓  2 [chromium] › tests/example.spec.js:8:1 › authenticated users can see their policies (2.1s)
2 passed (7.9s)
+ rc=0
+ stop_proxy
+ export NOMAD_ADDR=https://35.174.137.147:4646
+ NOMAD_ADDR=https://35.174.137.147:4646
+ nomad job stop -purge -namespace=proxy nomad-proxy
==> 2025-04-24T08:49:45+01:00: Monitoring evaluation "67969937"
2025-04-24T08:49:45+01:00: Evaluation triggered by job "nomad-proxy"
2025-04-24T08:49:45+01:00: Evaluation status changed: "pending" -> "complete"
==> 2025-04-24T08:49:45+01:00: Evaluation "67969937" finished with status "complete"
+ nomad namespace delete proxy
Successfully deleted …
```
=> e2e: Update UI playwright version to 1.52.0

drivers/docker/driver_test.go
This image was missed in https://github.com/hashicorp/nomad/pull/25703 and is resulting in rate limited in tests.
=> testing: use Docker Hub registry mirror for additional tests

.changelog/25741.txt, drivers/docker/stats.go, drivers/docker/stats_test.go, drivers/docker/util/stats_posix.go
https://github.com/hashicorp/nomad/pull/25138 refactoring accidentally removed
some of the memory stats that weren't available as concrete types in
containerapi. 
Fixes https://github.com/hashicorp/nomad/issues/24920
Internal ref: https://hashicorp.atlassian.net/browse/NMD-437
=> docker: correct stat response for rss, cache and swap memory in cgroups v1

.changelog/25726.txt, scheduler/generic_sched_test.go, scheduler/reconcile_test.go, scheduler/reconcile_util.go
When a node is drained that has canaries that are not yet healthy, the canaries may not be properly migrated and the deployment will halt. This happens only if there are more than `migrate.max_parallel` canaries on the node and the canaries are not yet healthy (ex. they have a long `update.min_healthy_time`). In this circumstance, the first batch of canaries are marked for migration by the drainer correctly. But then the reconciler counts these migrated canaries against the total number of expected canaries and no longer progresses the deployment. Because an insufficient number of allocations have reported they're healthy, the deployment cannot be promoted.
When the reconciler looks for canaries to cancel, it leaves in the list any canaries that are already terminal (because there …
=> scheduler: allow canaries to be migrated on node drain

nomad/drainer/drainer.go, nomad/drainer/watch_jobs.go
While working on #25726, I found a method in the drainer code that records creates a map of job IDs to allocations.
At first glance this looks like a bug because it effectively de-duplicates the allocations per job. But the consumer of the map is only concerned with jobs, not allocations, and simply reads the job off the allocation. Refactor this to make it obvious we're looking at the job.
Ref: https://github.com/hashicorp/nomad/pull/25726
=> refactor alloc drain to make intent more clear

drivers/docker/driver_test.go
When the context closes, the stats emitter closes its channel. It's possible for the channel to be closed in the stats emitter goroutine before the `select` in the test sees that the context has closed, which can result in a panic in the test when we try to read the empty value off the channel.
Example test run https://github.com/hashicorp/nomad-enterprise/actions/runs/14643472774/job/41091737592?pr=2654
=> testing: fix a panic in docker stats collection test

.changelog/25751.txt, drivers/docker/driver_test.go, drivers/docker/stats_test.go, drivers/docker/util/stats_posix.go, drivers/shared/executor/executor_linux.go
In cgroups v2, a different map of memory stats is available from the kernel than in v1. The Docker API reflects this change. But there are equivalent values in the map for RSS (anonymously mapped memory) and cache (filesystem cache and tmpfs), which the Docker driver and shared executor are not currently emitting.
Fallback to these alternate values when the cgroups v1 values are not available. Include the anonymous mapping in the "measured" allocation stats as "RSS" so that they both show up in allocation metrics.  We can do this on both the `docker` driver and the Linux executor for `exec` and `java` drivers.
Fixes: https://github.com/hashicorp/nomad/issues/19185
Ref: https://hashicorp.atlassian.net/browse/NMD-437
Ref: https://www.kernel.org/doc/html/latest/admin-guide/cgroup-v2.html#memo …
=> metrics: emit cache and rss stats on cgroup v2

.changelog/25742.txt, ui/app/models/job.js, ui/mirage/factories/allocation.js, ui/mirage/scenarios/default.js, ui/tests/acceptance/allocation-detail-test.js, ui/tests/acceptance/jobs-list-test.js
Jobs were being marked incorrectly as having paused allocations when terminal allocations were marked with the paused boolean. The UI should only mark a job as including paused allocations when these paused allocations are in the correct client state, which is pending.
In order to correctly handle the modified behaviour, mirage required an update, so that pending allocations had task states set.
The linked Jira contains reproduction steps. The feature is Enterprise only, so you'll need to port this change into your ENT code and run `make dev-ui` to test locally.
[NMD-668](https://hashicorp.atlassian.net/browse/NMD-668)
and job configuration, please update the  Nomad website documentation to reflect this. Refer …
=> ui: Only show paused icon when allocs in pending state are paused.

.changelog/25792.txt, nomad/state/paginator/tokenizer.go, nomad/state/paginator/tokenizer_test.go
The `CreateIndexAndIDTokenizer` creates a composite token by
combining the create index value and ID from the object with
a `.`. Tokens are then compared lexicographically. The comparison
is appropriate for the ID segment of the token, but it is not for
the create index segement. Since the create index values are stored
with numeric ordering, using a lexicographical comparison can cause
unexpected results.
For example, when comparing the token `12.object-id` to `102.object-id`
the result will show `12.object-id` being greater. This is the
correct comparison but it is incorrect for the intention of the token.
With the knowledge of the composition of the token, the response
should be that `12.object-id` is less.
The unexpected behavior can be seen when performing lists (like listing …
=> paginator: fix tokenizer comparison of composite index and ID

.changelog/25721.txt, command/agent/command.go, website/content/docs/upgrade/upgrade-specific.mdx
Currently if an agent performs a system reload after a configuration update and encounters an error, it just logs it and continues, which can lead to agents running but unable to communicate. 
This PR changes that behaviour by forcing the agent to exit with an error code if it runs into a fatal error while reloading.
It also does a little refactor of the`handleSignals()` function for clarity and makes the graceful termination function aware of any drain configuration deadlines.
Related issues:
-  [NMD-321](https://hashicorp.atlassian.net/browse/NMD-321)
- [GH-25199](https://github.com/hashicorp/nomad/issues/25199) …
=> Force an agent return if there is an error on reload

nomad/encrypter.go, nomad/encrypter_test.go
When a Nomad server restores its state via a snapshot and logs, it is possible a legacy wrapped key object/log is found. This key will not contain any wrapped keys and therefore should be ingored within the encrypter.
It is theoretically possible without this change that a key which generates zero decrypt tasks supersedes a running task and will place itself in the tracked decrypt task tracker. This decrypt task has no running work to remove its entry.
The added test cover the steps needed.
change requires notes within …
=> encrypter: Ignore wrapped key additions with zero wrapped keys.

go.mod, go.sum
The dependency is already at this version in all Enterprise long-lived branches. Updating it within CE brings more consistency and stops automated merges breaking in the go.mod file due to this.
=> deps: Update mitchellh/colorstring to d06e56a500db

command/setup_vault_test.go
The test for `nomad setup vault` command expects a specific `CreateIndex` for the job it creates. Any change in Raft writes when a server comes up or establishes leadership can cause this test to break. Interpolate the expected index as we've done for other indexes on the job to make this test less brittle.
Ref: https://github.com/hashicorp/nomad-enterprise/pull/2673#issuecomment-2847619747
=> testing: fix vault setup test's reliance on specific Raft index

enos/modules/upgrade_client/main.tf, enos/modules/upgrade_client/scripts/verify_allocs.sh
The upgrade test is very flaky because checking the allocs running before and after un update on every client presents a lot of inconsistencies.  Sometimes there are more allocs after than before, sometimes it is the other way around. This PR introduces 2 things: It prints out the info of any alloc present on the client before upgrading, restarts the client, waits for the correct number of allocs to be running and then checks that they are the same that were running before. …
=> Check for allocs running before checking for IDs after a client upgrade

enos/README.md, enos/modules/drain_nodes/scripts/drain.sh, enos/modules/run_workloads/outputs.tf, enos/modules/test_cluster_health/scripts/allocs.sh, enos/modules/test_cluster_health/scripts/clients.sh, enos/modules/test_cluster_health/scripts/jobs.sh, enos/modules/test_cluster_health/scripts/servers.sh, enos/modules/upgrade_client/scripts/get_expected_allocs.sh, enos/modules/upgrade_client/scripts/verify_allocs.sh, enos/modules/upgrade_servers/scripts/wait_for_stable_cluster.sh
This changeset includes several adjustments to the upgrade testing scripts to reduce flakes and make problems more understandable:
* When a node is drained prior to the 3rd client upgrade, it's entirely possible the 3rd client to be upgraded is the drained node. This results in miscounting the expected number of allocations because many of them will be "complete" (service/batch) or "pending" (system). Leave the system jobs running during drains and only count the running allocations at that point as the expected set. Move the inline script that gets this count into a script file for legibility.
* When the last initial workload is deployed, it's possible for it to be briefly still in "pending" when we move to the next step. Poll for a short window for the expected count of jobs.
* Make …
=> reduce upgrade testing flakes

website/content/docs/job-specification/artifact.mdx
Support requested that we move the Environment section further up the page because users don't see the section when it's at the bottom.
Jira: [CE-712]
[Deploy preview](https://nomad-git-ce712-hashicorp.vercel.app/nomad/docs/job-specification/artifact) …
=> Docs: Job spec artifact - move environment section

.changelog/25844.txt, api/operator.go, command/agent/config_parse.go, command/agent/config_parse_test.go, command/agent/http.go, command/agent/operator_endpoint_ce.go, command/agent/testdata/basic.hcl, command/agent/testdata/basic.json, command/commands.go, command/operator_utilization.go, nomad/event_endpoint.go, nomad/state/events.go, nomad/state/events_ce.go, nomad/structs/config/reporting.go, nomad/structs/event.go, website/content/api-docs/events.mdx, website/content/api-docs/operator/utilization.mdx, website/content/docs/commands/operator/utilization.mdx, website/content/docs/configuration/reporting.mdx, website/data/api-docs-nav-data.json, website/data/docs-nav-data.json
Nomad Enterprise users operating in air-gapped or otherwise secured environments don't want to send license reporting metrics directly from their servers. Implement manual/offline reporting by periodically recording usage metrics snapshots in the state store, and providing an API and CLI by which cluster administrators can download the snapshot for review and out-of-band transmission to HashiCorp.
This is the CE portion of the work required for implemention in the Enterprise product (see https://github.com/hashicorp/nomad-enterprise/pull/2673). Nomad CE does not perform utilization reporting ([ref](https://developer.hashicorp.com/nomad/docs/faq#q-what-is-checkpoint-does-nomad-call-home)).
Ref: https://github.com/hashicorp/nomad-enterprise/pull/2673
Ref: …
=> offline license utilization reporting

.github/workflows/actionlint.yml
We're required to pin Docker images for Actions to a specific SHA now and this is tripping scans in the Enterprise repo. Update the actionlint image.
Ref: https://go.hashi.co/memo/sec-032
=> build: pin actionlint workflow

.changelog/24150.txt, command/commands.go, command/job_start.go, command/job_start_test.go, command/testing_test.go, website/content/docs/commands/job/restart.mdx, website/content/docs/commands/job/start.mdx, website/data/docs-nav-data.json
This PR implements the `job start` command, which allows for users to call "job start [options] <job>" with a valid job that has been previously stopped and starts the most recent running and stable version up. 
Fixes: https://github.com/hashicorp/nomad/issues/23852
After more investigation, we found that batch job versions do not get set as running after a stop, rather they are set to pending, and because of this, it is hard to nail down another marker to use in order for us to establish if the version we’d like to revert to is stable , so for now, this feature has been implemented and tested for service jobs only.
=> start: allow users to call job start command to start stopped jobs

enos/modules/run_workloads/templates/vault-secrets.nomad.hcl.tpl
During the upgrade test we can trigger a re-render of the Vault secret due to client restart before the allocrunner has marked the task as running, which triggers the change mode on the template and restarts the task. This results in a race where the alloc is still "pending" when we go to check it. We never change the value of this secret in upgrade testing, so paper over this race condition by setting a "noop" change mode.
=> upgrade test: remove change mode from Vault workload

.changelog/25850.txt, scheduler/scheduler_sysbatch_test.go, scheduler/scheduler_system.go, scheduler/scheduler_system_test.go
When running a system job with a constraint, any run after an initial startup returns an exit(2) and a warning about unplaced allocations due to constraints. An error that is not encountered on the initial run, though the constraint stays the same. This is because the node that satisfies the condition is already running the allocation, and the placement is ignored. Another placement is attempted, but the only node(s) left are the ones that do not satisfy the constraint. Nomad views this case (no allocations that were attempted to placed could be placed successfully) as an error, and reports it as such. In reality, no allocations should be placed or updated in this case, but it should not be treated as an error.
This change uses the `ignored` & in-place `updated` placements from …
=> Only error on constraints if no allocs are running

.changelog/25859.txt, client/testutil/driver_compatible.go, drivers/shared/executor/executor_basic.go, drivers/shared/executor/executor_linux.go, drivers/shared/executor/executor_linux_test.go, drivers/shared/executor/executor_universal_linux.go, drivers/shared/executor/executor_unix.go
=> exec: Fix incorrect `HOME` and `USER` env variables for tasks that have `user` set

.changelog/25870.txt, client/allocrunner/taskrunner/stats_hook.go, client/allocrunner/taskrunner/stats_hook_test.go, client/allocrunner/taskrunner/task_runner_hooks.go, drivers/shared/executor/executor.go, drivers/shared/executor/executor_linux.go, drivers/shared/executor/procstats/getstats.go, drivers/shared/executor/procstats/getstats_test.go, drivers/shared/executor/procstats/list_test.go, drivers/shared/executor/procstats/list_windows.go, drivers/shared/executor/procstats/procstats.go
Collecting metrics from processes is expensive, especially on platforms like
Windows. The executor code has a 5s cache of stats to ensure that we don't
thrash syscalls on nodes running many allocations. But the timestamp used to
calculate TTL of this cache was never being set, so we were always treating it
as expired. This causes excess CPU utilization on client nodes.
Ensure that when we fill the cache, we set the timestamp. In testing on Windows,
this reduces exector CPU overhead by roughly 75%.
This changeset includes two other related items:
* The `telemetry.publish_allocation_metrics` field correctly prevents a node
from publishing metrics, but the stats hook on the taskrunner still collects
the metrics, which can be expensive. Thread the configuration value into the
stats hook so …
=> telemetry: fix excessive CPU consumption in executor

website/content/docs/job-specification/task.mdx, website/content/docs/runtime/environment.mdx
In #25859 we fixed the task environment variables to account for `user` field
setting. This PR follows up with documentation adjustments.
=> docs: emphasize HOME and USER env vars for tasks that use custom `user` setting

.changelog/25800.txt, scheduler/rank.go, scheduler/rank_test.go
If there are no affinities on a job, we don't want to count an affinity score of zero in the number of scores we divide the normalized score by. This is how we handle other scoring components like node reschedule penalties on nodes that weren't running the previous allocation.
But we also exclude counting the affinity in the case where we have affinity but the value is zero. In pathological cases, this can result in a node with a no affinity being picked over a node with low affinity, because the denominator is 1 larger. Include zero-value affinities in the count of scores if the job has affinities but the value just happens to be zero.
Fixes: https://github.com/hashicorp/nomad/issues/25621
=> scheduler: account for affinity value of zero in score normalization

.changelog/25799.txt, nomad/state/state_store.go, nomad/state/state_store_test.go
When allocations that already exists in the state store were upserted again, the `NextAllocation` field was being overwritten, causing issues with the reconnecting picker.  This change carries the `NextAllocation` field forward.
=> state store: persist NextAllocation correctly when upserting allocations

.semgrep/imports.yml
We have several semgrep rules forbidding imports of packages we don't want. While testing out a new rule I discovered that the rule we have is completely ineffective. Update the rule to detect imports using the Go language plugin, including regex matching on some packages where it's forbidden to import the root but fine to import a subpackage or different version.
The go-set import rule is an example of one where our `go-set/v3` imports fails the re-written check unless we use the regex syntax. If you replace the pattern rule with `import "=~/github.com\/hashicorp\/go-set/v3$/"` it would fail.
---
Because the check won't actually run against all files without touching them:
<details><summary>semgrep run locally</summary>
```
$ semgrep scan --config .semgrep/imports.yml .
┌──── ○○○ ────┐
│ …
```
=> semgrep: adjust forbidden package rule for regex matches

.changelog/25902.txt, api/host_volumes.go, command/volume_delete.go, nomad/host_volume_endpoint.go, nomad/host_volume_endpoint_test.go, nomad/structs/host_volumes.go, website/content/docs/commands/volume/delete.mdx
When a node is garbage collected, we leave behind the dynamic host volume in the state store. We generally don't want to automatically garbage collect the volumes and risk data loss (see also #25903), but we should allow these to be removed via the API.
Fixes: https://github.com/hashicorp/nomad/issues/25762
Fixes: https://hashicorp.atlassian.net/browse/NMD-705
Ref: https://github.com/hashicorp/nomad/pull/25903 …
=> host volumes: -force flag for delete

website/content/api-docs/acl/roles.mdx, website/content/api-docs/allocations.mdx, website/content/api-docs/jobs.mdx, website/content/api-docs/quotas.mdx, website/content/api-docs/recommendations.mdx, website/content/api-docs/scaling-policies.mdx, website/content/api-docs/sentinel-policies.mdx, website/content/api-docs/services.mdx, website/content/api-docs/status.mdx, website/content/api-docs/ui.mdx
This issue was raised for the ACL endpoints and fixed by an end user in https://github.com/hashicorp/nomad/pull/25356. This PR addresses the remaining API pages.
Jira: [CE-831]
[CE-831]: …
=> Docs: Add "/v1" where missing so endpoint docs are consistent

.semgrep/imports.yml, nomad/state/deployment_events_test.go, nomad/state/events_test.go, nomad/state/indexer/indexer_test.go, nomad/state/indexer/time_test.go, nomad/state/schema_test.go, nomad/state/state_store_acl_test.go, nomad/state/state_store_service_registration_test.go, nomad/state/state_store_test.go
We've been gradually migrating from `testify` to `shoenig/test` on a test-by-test basis. While working on a large refactoring in the state store, I found this to create a lot of diffs incidental to the refactoring.
In this changeset, I've used a prototype collection of semgrep fix rules to autofix most of the uses of testify in the `nomad/state` package. Then I went in manually and fixed any resulting problems, as well as a few minor test bugs that `shoenig/test` catches and `testify` does not because of its API. I've also added a semgrep rule for marking a package as "testify clean", so that we don't accidentally add it back to any package we manage to remove it from going forward.
While I'm here, I've removed most of the uses of `reflect.DeepEqual` in the tests as well as cleaned up …
=> testing: migrate nomad/state off testify

command/agent/config.go, command/agent/config_parse.go, command/agent/config_parse_test.go, command/agent/config_test.go, command/agent/testdata/extra-consul.hcl, command/agent/testdata/extra-consul.json, command/agent/testdata/extra-vault.hcl, command/agent/testdata/extra-vault.json, helper/ipaddr/ipaddr.go, helper/ipaddr/ipaddr_test.go
[RFC-5942 section 4](https://www.rfc-editor.org/rfc/rfc5952.html#section-4) recommends (basically) that IPv6 addresses should have their 0's squashed together, and letters lower-cased.  E.g. `A110:0:0::C8` should become `a110::c8`.
An audit for the [USGv6 program](https://www.nist.gov/programs-projects/usgv6-program)* that turns this recommendation into a requirement found us outputting the verbatim-from-config address in the output of `nomad agent`, and I also found vault/consul addrs in logs (namely, from our passing them to consul-template).
I opted to normalize the addresses at config-parsing time, so the change runs through the whole system, rather than try to chase down each spot where we represent it visually.  This is not without risk, so I could be persuaded to take a more …
=> ipv6: normalize addrs per RFC-5942 §4

.changelog/25881.txt, ui/app/services/token.js
The ACL self lookup now returns a spoof token when ACLs are
disabled, rather than an error. The UI needs to be updated to
handle this change, so permissions checks are not performed which
grey out buttons such as client drain incorrectly.
https://hashicorp.atlassian.net/browse/NMD-768
history should …
=> ui: Handle new token self response object when ACLs are disabled.

.changelog/25903.txt, api/nodes.go, client/client.go, client/config/config.go, command/agent/agent.go, command/agent/config.go, command/agent/config_parse_test.go, command/agent/host_volume_endpoint.go, command/agent/testdata/basic.hcl, command/agent/testdata/basic.json, nomad/host_volume_endpoint.go, nomad/state/events_test.go, nomad/state/state_store.go, nomad/state/state_store_host_volumes.go, nomad/state/state_store_host_volumes_test.go, nomad/structs/structs.go, website/content/docs/configuration/client.mdx
When a node is garbage collected, any dynamic host volumes on the node are orphaned in the state store. We generally don't want to automatically collect these volumes and risk data loss, and have provided a CLI flag to `-force` remove them in #25902. But for clusters running on ephemeral cloud instances (ex. AWS EC2 in an autoscaling group), deleting host volumes may add excessive friction. Add a configuration knob to the client configuration to remove host volumes from the state store on node GC.
(This also fixes a bug I discovered in #25902)
Ref: https://github.com/hashicorp/nomad/pull/25902
Ref: https://github.com/hashicorp/nomad/issues/25762
Ref: https://hashicorp.atlassian.net/browse/NMD-705
and job …
=> host volumes: add configuration to GC on node GC

e2e/terraform/README.md
Should be obvious, but it's not.
=> e2e: mention in the terraform readme that we require a local Consul binary

.changelog/25923.txt, nomad/eval_broker.go, nomad/eval_broker_test.go, nomad/fsm.go, nomad/node_endpoint.go, nomad/state/state_store.go, nomad/state/state_store_test.go, nomad/structs/structs.go
When a disconnected alloc reconnects, the follow-up evaluation is left pending and the followup eval ID field isn't cleared. If the allocation later fails, the followup eval ID prevents the server from creating a new eval for that event.
Update the state store so that updates from the client clear the followup eval ID if the allocation is reconnecting, and mark the eval as canceled. Update the FSM to remove those evals from the eval broker's delay heap.
Fixes: https://github.com/hashicorp/nomad/issues/12809
Fixes: https://hashicorp.atlassian.net/browse/NMD-291
Fixes: https://hashicorp.atlassian.net/browse/NMD-302
* See also my comment below with end-to-end validation: …
=> cancel waiting evals when allocs reconnect

e2e/affinities/affinities.go
`TestSingleAffinities` never expected a node with affinity score set to 0 in
the set of returned nodes. However, since #25800, this can happen. What the
test should be checking for instead is that the node with the highest normalized
score has the right affinity.
Internal ref: https://hashicorp.atlassian.net/browse/NMD-797
=> e2e: correct `TestSingleAffinities` behavior

.changelog/25878.txt, nomad/structs/diff.go, nomad/structs/diff_test.go
volume_mounts are not regarded in `sidecarTaskDiff`, meaning two task which only differ in volume mounts will be considered equal. This addresses that.
- #19786
- #20575
=> fix: consider volume_mounts in sidecarTaskDiff

website/content/docs/concepts/cpu.mdx, website/content/docs/job-specification/resources.mdx
Add some prescriptive guidance to the CPU concepts document around when to use `resources.cores` vs `resources.cpu`. Extend some of the text to cover cgroups v2, and add a brief overview of how relative cpu shares/weights work.
Ref: https://hashicorp.atlassian.net/browse/NMD-297
Ref: https://go.hashi.co/rfc/nmd-211
Ref: https://github.com/hashicorp/nomad/pull/25963
=> docs: expand on recommendations for CPU resource reservation

.changelog/25963.txt, drivers/docker/driver.go, drivers/docker/driver_linux_test.go, drivers/shared/executor/executor_linux.go, drivers/shared/executor/executor_linux_test.go
The `resources.cpu` field is scheduled in MHz. On most Linux task drivers, this value is then mapped to a `cpu.share` (cgroups v1) or `cpu.weight` (cgroups v2). But this means on very large hosts where the total compute is greater than the Linux kernel defined maximum CPU shares, you can't set a `resources.cpu` value large enough to consume the entire host.
The `cpu.share`/`cpu.weight` value is relative within the parent cgroup's slice, which is owned by Nomad. So we can fix this by re-normalizing the weight on very large hosts such that the maximum `resources.cpu` matches up with largest possible CPU share. This happens in the task driver so that the rest of Nomad doesn't need to be aware of this implementation detail. Note that these functions will result in bad share config if the …
=> drivers: normalize CPU shares/weights to fit large hosts

nomad/drainer/watch_jobs_test.go
Some test cases were writing the same allocation object (memory pointer) to Nomad state in subsequant upsert calls. This causes a race condition with the drainer job watcher which reads the same object from Nomad state to perform conditional checks.
The data race is fixed by ensuring the allocation is copied between writes.
in the majority of situations. The main exceptions are long-lived feature …
=> drainer: Fix data race within test by correctly copying alloc.

.github/actionlint.yml, .github/workflows/test-core.yaml, .github/workflows/test-windows.yml
~Naively optimistic~ fix for
> This is a scheduled Windows Server 2019 brownout. The Windows Server 2019 image will be removed on 2025-06-30. For more details, see https://github.com/actions/runner-images/issues/12045
=> ci: windows 2022 runners (upcoming 2019 eol)

helper/pool/pool.go, helper/pool/pool_test.go, nomad/rpc.go, nomad/rpc_test.go
The server RPC handler and RPC connection pool both use a shared configuration object for custom yamux configuration. Both sub-systems were modifying the shared object which could cause a data race. The passed object is now cloned before being modified.
This changes also moves where the yamux configuration is cloned and modified to the relevant constructor function. This avoids performing a clone per connection handle or per new connection generated in the RPC pool.
<details>
<summary>data race</summary>
```console
Write at 0x00c0003745d8 by goroutine 235:
github.com/hashicorp/nomad/nomad.(*rpcHandler).handleMultiplexV2()
github.com/hashicorp/nomad/nomad/rpc.go:522 +0xd4
github.com/hashicorp/nomad/nomad.(*rpcHandler).handleConn() …
```
=> rpc: Fix data race in yamux config modification for conn handling.

.changelog/25921.txt
I neglected to add a changelog entry in #25921 (and backport #26015) -- `ipv6: normalize addrs per RFC-5942 §4`
Calling it an "improvement" seems like a stretch, but if your goal is compliance with USGv6, then it is an improvement.
=> release: add changelog for pr 25921 (ipv6 addr normalization)

.changelog/26022.txt, nomad/client_csi_endpoint_test.go, nomad/csi_endpoint.go, nomad/csi_endpoint_test.go
When running `nomad volume snapshot delete -secret X=Y ...`, the secret(s) are discarded along the way, and do not make it to the CSI plugin.  This adds them to the RPC handler.
Fixes #25976
Unit test covers this change, and I also proved it out with a toy CSI plugin running on an agent.
=> csi: send secrets with snapshot delete command

ci/test-core.json, scheduler/README.md, scheduler/generic_sched.go, scheduler/generic_sched_test.go, scheduler/reconcile/allocs.go, scheduler/reconcile/allocs_test.go, scheduler/reconcile/reconcile_cluster.go, scheduler/reconcile/reconcile_cluster_test.go, scheduler/reconcile/reconcile_node.go, scheduler/reconcile/reconcile_node_test.go, scheduler/reconcile/reconnecting_picker.go, scheduler/reconcile/reconnecting_picker_test.go, scheduler/scheduler_system.go, scheduler/scheduler_system_test.go, scheduler/status/status.go, scheduler/structs/const.go, scheduler/util.go, scheduler/util_test.go
This moves all the code of service/batch and system/sysbatch reconciliation into a new `reconcile` package.
Internal ref: https://hashicorp.atlassian.net/browse/NMD-812
=> scheduler: isolate reconciliation code

.changelog/25927.txt, drivers/docker/config.go, drivers/docker/config_test.go, drivers/docker/driver.go, website/content/docs/drivers/docker.mdx
This is a redo of https://github.com/hashicorp/nomad/pull/17702 
The Datadog Agent [docs](https://docs.datadoghq.com/containers/docker/?tab=standard) specifies that you should set `cgroupns=host`, but I can't do that via nomad.
```
docker run -d --cgroupns host \
--pid host \
--name dd-agent \
-v /var/run/docker.sock:/var/run/docker.sock:ro \
-v /proc/:/host/proc/:ro \
-v /sys/fs/cgroup/:/host/sys/fs/cgroup:ro \
-e DD_SITE=<DATADOG_SITE> \
-e DD_API_KEY=<DATADOG_API_KEY> \
gcr.io/datadoghq/agent:7
```
https://github.com/hashicorp/nomad/pull/17702#issuecomment-1749179725
the [website README](../website/README.md) for …
=> docker: add cgroupns task config

nomad/structs/workload_id_test.go
Without the change, running the `TestNewIdentityClaims` test would show:
```console
=== RUN   TestNewIdentityClaims/job/group/services/group-service-
workload_id_test.go:509: missing expected claims
--- SKIP: TestNewIdentityClaims/job/group/services/group-service- (0.00s)
...
=== RUN   TestNewIdentityClaims/job/group/consul-vault-task/services/consul-task-service
workload_id_test.go:509: missing expected claims
--- SKIP: TestNewIdentityClaims/job/group/consul-vault-task/services/consul-task-service (0.00s)
```
change …
=> test: Fix workload ID claims tests, so cases are not skipped.

.changelog/26018.txt, command/agent/command.go
When performing a graceful shutdown a channel is used to wait for
the agent to leave. The channel is closed when the agent leaves
successfully, but it also is closed within a deferral. If the
agent successfully leaves and closes the channel, a panic will
occur when the channel is closed the second time within the
deferral. To prevent this from occurring, the channel closing
is wrapped within a `OnceFunc` so the channel is only closed
once.
Panic encountered during shutdown:
```
panic: close of closed channel
goroutine 1 [running]:
github.com/hashicorp/nomad/command/agent.(*Command).terminateGracefully(0xc000948720, 0xc000538e70, {0x0?, 0x0?})
github.com/hashicorp/nomad/command/agent/command.go:1019 +0x2a5
github.com/hashicorp/nomad/command/agent.(*Command).handleSignals(0xc000948720) …
```
=> command: prevent panic on graceful shutdown

website/content/docs/job-specification/lifecycle.mdx, website/content/docs/job-specification/task.mdx
We have a description of the order of shutdown in the `task.leader` docs, but the `lifecycle` block is an intuitive place to look for this same information, and the behavior is largely governed by that feature anyways.
=> docs: describe shutdown order on `lifecycle` page

nomad/structs/funcs.go, nomad/structs/network.go, nomad/structs/network_test.go
The check simply returns false and has done for a number of years, therefore there is no need to keep it around or the test that exercises it.
=> net: Remove overcommitted network conditional.

GNUmakefile
Tests running in CI are starting to bump up to this timeout forcing
re-runs. Adding an additional five minutes to the timeout to help
prevent this from occurring.
=> test: update test timeout from 20m to 25m

.changelog/26041.txt, client/allocrunner/taskrunner/task_runner_linux_test.go, client/allocrunner/taskrunner/task_runner_test.go, client/allocrunner/taskrunner/vault_hook.go, client/allocrunner/taskrunner/vault_hook_test.go, client/vaultclient/vaultclient.go, client/vaultclient/vaultclient_test.go, client/vaultclient/vaultclient_testing.go
When we renew Vault tokens, we use the lease duration to determine how often to renew. But we also set an `increment` value which is never updated from the initial 30s. For periodic tokens this is not a problem because the `increment` field is ignored on renewal. But for non-periodic tokens this prevents the token TTL from being properly incremented. This behavior has been in place since the initial Vault client implementation in #1606 but before the switch to workload identity most (all?) tokens being created were periodic tokens so this was never detected.
Fix this bug by updating the request's `increment` field to the lease duration on each renewal and ensuring the vault hook starts with the correct renewal value.
Also switch out a `time.After` call in backoff of the derive token …
=> vault: set renew increment to lease duration

nomad/alloc_endpoint_test.go
Fixes a test case where we weren't waiting for the keyring to be ready on the server, causing flakey failures when attempting to sign identities. 
Flaky test failure was reproducible locally, running enough times 
```
go test ./nomad -count=20 -failfast -run TestAlloc_SignIdentities_Blocking
``` …
=> test: waitForKeyring in SignIdentities test

e2e/terraform/packer/ubuntu-jammy-amd64/consul.service, e2e/terraform/provision-infra/provision-nomad/etc/consul.d/consul.service
In our E2E environment we've seen some flakiness with the Consul-related tests. As it turns out, the Consul agents are getting restarted every 90s or so because they're timing out their systemd notification.
> consul.service: start operation timed out. Terminating.
This appears to be a known issue in Consul and we'll try to contribute some help to hunt down the cause if they want help, but in the meantime let's remove it from our systemd unit files for the Consul agents.
Ref: https://github.com/hashicorp/consul/issues/16844#issuecomment-1913282248
Ref: https://github.com/hashicorp/nomad-e2e/actions/runs/15724328518/job/44311243757
=> E2E: disable sdnotify for Consul agents

.github/workflows/build.yml
Pass the `GO_TAGS` env variable to the docker container when building the binary.
Build succeeded with tags at https://github.com/hashicorp/nomad/actions/runs/15784699403
Fixes https://github.com/hashicorp/nomad/issues/25910
=> ci: pass go_tags to linux docker builder

.github/workflows/build.yml
ent builds use multiple tags, not having `GO_TAGS` quoted breaks the build on ent.
=> ci: docker GO_TAGS must be quoted

go.mod, go.sum
For reasons of backwards compatibility, Nomad uses an older branch of HCL1 (`v1.0.1-nomad`) and HCL2 (`v2.20.2-nomad-1`) and backports a limited set of changes to those branches.
But the Vault API also has their own HCL1 branch, currently tagged as `v1.0.1-vault-7`. Normally this isn't a problem because Nomad pins to our own branch and we don't call any of the Vault API package's HCL code anyways. But in Vault's branch some functions were changed that break our build unless we backport them.
We've backported enough of Vault's changes to make our HCL1 branch build, and now have tags on the HCL repo (`v1.0.1-nomad-1` and `v2.20.2-nomad-1`) so that we can pin to specific tags instead of random commits.
Fixes: https://hashicorp.atlassian.net/browse/NMD-850
Fixes: …
=> update Vault API dependency and pin HCL dependencies

.github/workflows/build.yml
In https://github.com/hashicorp/nomad-enterprise/pull/2592 we introduced a
divergence in how Nomad CE and ENT build their binaries. Nomad CE used a more
sophisticated approach, setting uid, gid and home environment variables in the
`docker run` command. Despite mine (and others) best efforts, we were not able
to do the same in the ENT repo, which relies on special git settings that allow
it to pull dependencies from private repositories, and left a different docker
run command there, that just inherited GHA runner user and copied the resulting
tarball instead of moving it. #26090 then attempted to remedy #25910 resulting
from docker run command ignoring `${{ env.GO_TAGS }}` if run with custom
`--env`, but the resulting backport broke ent builds.
This PR restores ENT behavior of building …
=> ci: align CE build command with ENT

e2e/ui/run.sh
yet another fix for
```
Error: browserType.launch: Executable doesn't exist at /ms-playwright/chromium_headless_shell-1179/chrome-linux/headless_shell
╔══════════════════════════════════════════════════════════════════════╗
║ Looks like Playwright Test or Playwright was just updated to 1.53.1. ║
║ Please update docker image as well.                                  ║
║ -  current: mcr.microsoft.com/playwright:v1.52.0-jammy               ║
║ - required: mcr.microsoft.com/playwright:v1.53.1-jammy               ║
║                                                                      ║
║ <3 Playwright Team                                                   ║
╚══════════════════════════════════════════════════════════════════════╝
```
=> e2e: ui: bump playwright version

.changelog/26107.txt, nomad/auth/auth.go, nomad/server.go, nomad/server_test.go
The Nomad server uses an authenticator backend for RPC handling which includes TLS verification. This verification setting is configured based on the servers TLS configuration object and is built when a new server is constructed.
The bug occurs when a servers TLS configuration is reloaded which can change the desired TLS verification handling. In this case, the authenticator is not updated, meaning the RPC mTLS verification is not modified, even if the configuration indicates it should.
This change adds a new function on the authenticator to allow updating its TLS verification rule. This new function is called when a servers TLS configuration is reloaded.
and job configuration, please update the  Nomad website …
=> tls: Reset server TLS authenticator when TLS config reloaded.

nomad/fsm.go, nomad/node_endpoint_test.go, nomad/state/events_test.go, nomad/state/state_store.go, nomad/state/state_store_test.go, nomad/structs/structs.go
When a node heartbeats, the RPC handler will optionally generate an identity to return to the caller. The identity key ID will be stored in the node object, so we have tracking of keys in use.
The state store has been updated to handle node status update requests that include a signing key ID. Rather than add another parameter into the function signature, the FSM function now takes the entire request object.
internal jira: https://hashicorp.atlassian.net/browse/NMD-779
internal design doc: https://docs.google.com/document/d/1MYjlFlOAmGHmWGC3VsrIMUL_VSgKwjLAq6GUymDY38M/edit?tab=t.0
the [website …
=> fsm: Add identity signing key handling for node status updates.

.changelog/26170.txt, api/services.go, command/agent/consul/service_client.go, command/agent/consul/unit_test.go, command/agent/job_endpoint.go, command/agent/job_endpoint_test.go, nomad/structs/diff_test.go, nomad/structs/services.go, nomad/structs/services_test.go, website/content/docs/job-specification/service.mdx
Adds the `Kind` field to the service block in the jobspec, and allows Consul services to be registered with the [Consul Kind type](https://developer.hashicorp.com/consul/api-docs/agent/service#kind) manually. Previously this was only set when using a defined type of Consul Connect [gateway](https://developer.hashicorp.com/nomad/docs/job-specification/gateway), but with the new change, it can be specified on the service itself. If both values (`kind` and a consul connect gateway) are defined, the service will use the Consul Connect Gateway.
Add `kind` to jobspec, observe the gateway specified for the service in Consul.
internal Ref https://hashicorp.atlassian.net/browse/NMD-702
and job configuration, please …
=> Expose Kind field for Consul Service Registrations

scheduler/doc.go, scheduler/feasible/doc.go, scheduler/reconciler/doc.go, scheduler/structs/doc.go
a) it's reasonably good practice to have package documentation that we have all but abandoned. 
b) my gopls has been complaining about this.
=> scheduler: doc.go files for new packages

client/allocrunner/alloc_runner.go, client/allocrunner/alloc_runner_test.go
The `killTasks` function will kill all the alloc runners
task runners. If the task of a task runner has already
completed, the killing of the task runner can cause
confusion due to the task event showing that the task
was signaled even though it is already complete.
To prevent this, a check is done when creating the
task event to determine if the task has completed. If
it has no task event is created and when the task
runner is killed, no extra task event is added.
With a batch job that has two tasks, one long running and one short running, the first task is allowed to finish and then the node is drained. Currently the task events will look like:
```
Recent Events:
Time                       Type        Description
2025-06-17T15:36:25-07:00  Killing     Sent interrupt. Waiting 5s before …
```
=> client: suppress kill task event on completed tasks

.changelog/26171.txt, command/agent/command.go
When performing a graceful shutdown the client drain configuration
is checked for a deadline which is appended to the timeout. When
running as a server the client will not be set. Attempting to get
the drain deadline will result in a panic. This checks for the
client being available prior to fetching the deadline value.
in the majority of situations. The main exceptions are long-lived feature …
=> command: prevent server panic on graceful shutdown

nomad/drainer/watch_jobs.go, nomad/drainer/watch_jobs_test.go
When draining nodes allocs are checked for a healthy state and
marked to be drained, with the value in the max parallel setting
determining how many allocs will be migrated. Depending on the
circumstances, however, the max parallel setting may not be
properly respected.
Given a job with max parallel set to one, a group count greater
than one, and allocs on multiple nodes: Draining a single node
will result in one alloc being marked to drain. If another
node is immediately drained the alloc running on the first
node will be seen as "healthy" and another alloc will be
marked to be drained resulting in two allocs being marked
for migration at the same time. This can lead to issues with
service availablility.
To prevent this allocs can only be marked as healthy when the
alloc has not been …
=> drainer: respect max parallel setting when draining

.changelog/26183.txt, command/acl_token_self.go, command/acl_token_self_test.go
The meta client looks for both an environment variable and a CLI flag when generating a client. The CLI UUID checker needs to do this also, so we account for users using both env vars and CLI flag tokens.
You can run a local Nomad agent in dev mode with this change and ACLs enabled, and then perform the `nomad acl token -self` with the ACL token set via either as an env var or as a flag.
Jira: https://hashicorp.atlassian.net/browse/NMD-874
Closes #26176 …
=> cli: Fix a bug where self token lookups via token CLI flag failed.

website/content/docs/job-specification/service.mdx
Fixes the link in the doc page to correctly link to the Consul docs
n/a
Fixes doc issue introduced in https://github.com/hashicorp/nomad/pull/26170
=> docs: Fix link in service page documentation

website/content/docs/upgrade/upgrade-specific.mdx
In #25870 we fixed a longstanding bug where allocation metrics were being collected and published even if `telemetry.publish_allocation_metrics` was disabled (the default). This change is unexpected enough that we should surface it in the upgrade guide.
Ref: https://github.com/hashicorp/nomad/pull/25870
Fixes: https://github.com/hashicorp/nomad/issues/26166
=> docs: add upgrade guide note for publish_allocation_metrics

website/content/docs/operations/metrics-reference.mdx
Nomad agents emit metrics for Consul service and check operations, but these were not documented. Update the metrics reference table to include these metrics. Note that the metrics are prefixed `nomad.client` but are present on all agents, because the server registers itself in Consul as well.
Preview link: https://nomad-git-docs-consul-metrics-hashicorp.vercel.app/nomad/docs/operations/metrics-reference#agent-metrics
=> docs: add missing metrics for Consul service client

scheduler/reconciler/reconcile_cluster.go, scheduler/reconciler/reconcile_cluster_prop_test.go
To help break down the larger property tests we're doing in #26167 and #26172 into more manageable chunks, pull out a property test for just the `reconcileReconnecting` method. This method helpfully already defines its important properties, so we can implement those as test assertions.
Ref: https://hashicorp.atlassian.net/browse/NMD-814
Ref: https://github.com/hashicorp/nomad/pull/26167
Ref: https://github.com/hashicorp/nomad/pull/26172
=> scheduler: property testing of reconcile reconnecting

.changelog/26213.txt, nomad/state/state_store_host_volumes.go, nomad/state/state_store_host_volumes_test.go
The RPC handler for deleting dynamic host volumes has a check that any allocations associated with a volume are client-terminal before deleting the volume. But the state store delete that happens after we send client RPCs to the plugin checks that the allocs are non-terminal on both server and client.
This can improperly allow deleting a volume from a client but then not being able to delete it from the state store because of a time-of-check / time-of-use bug. If the allocation fails/completes on the client before the server marks its
desired status as terminal, or if the allocation is marked server-terminal during the client RPC, we can get a volume that passes the first check but not the second check that happens in the state store and cannot be deleted.
Update the state store delete …
=> host volumes: require allocs to be client terminal to delete vols

client/client.go, client/lib/numalib/detect.go, nomad/structs/cpucompat_default.go, nomad/structs/cpucompat_linux.go, nomad/structs/numa.go, nomad/structs/structs.go
This PR addresses [GH-23203](https://github.com/hashicorp/nomad/issues/26203). When starting the nomad client on linux with no fingerprinting, it panics because no topology is assigned. This PR initialises the topology as an empty one to avoid nil 
pointers.
To reproduces it, just start a client on linux with:
```client {
options = {
"fingerprint.allowlist" = "network"
}
}
```
And see it panic.
[GH-23203](https://github.com/hashicorp/nomad/issues/26203). …
=> Avoid panic during startup with 1.10.2

scheduler/reconciler/reconcile_cluster_prop_test.go
Internal ref: https://hashicorp.atlassian.net/browse/NMD-814
=> scheduler: basic cluster reconciler safety properties for service jobs

scheduler/reconciler/reconcile_node.go
While working on property testing in #26216, I discovered we had unreachable code in the node reconciler. The `diffSystemAllocsForNode` function receives a set of non-terminal allocations, but then has branches where it assumes the allocations might be terminal. It's trivially provable that these allocs are always live, as the system scheduler splits the set of known allocs into live and terminal sets before passing them into the node reconciler.
Eliminate the unreachable code and improve the variable names to make the known state of the allocs more clear in the reconciler code.
Ref: https://github.com/hashicorp/nomad/pull/26216
=> scheduler: eliminate dead code in node reconciler

scheduler/reconciler/reconcile_cluster.go, scheduler/reconciler/reconcile_cluster_test.go
While working on property testing in #26172 we discovered there are scenarios where the reconciler will produce more than the expected number of placements. Testing of those scenarios at the whole-scheduler level shows that this gets handled correctly downstream of the reconciler, but this makes it harder to reason about reconciler behavior. Cap the number of placements in the reconciler.
Ref: https://github.com/hashicorp/nomad/pull/26172
=> scheduler: reconciler should constrain placements to count

scheduler/reconciler/reconcile_cluster_prop_test.go
Property test assertions for the core safety properties of the cluster reconciler, for batch jobs.
Ref: https://hashicorp.atlassian.net/browse/NMD-814
Ref: https://github.com/hashicorp/nomad/pull/26167
=> scheduler: basic cluster reconciler safety properties for batch jobs

scheduler/reconciler/reconcile_cluster_prop_test.go, scheduler/reconciler/reconcile_node_prop_test.go
Property test assertions for the core safety properties of the node reconciler, for system and sysbatch jobs.
Ref: https://hashicorp.atlassian.net/browse/NMD-814
Ref: https://github.com/hashicorp/nomad/pull/26167
=> scheduler: basic node reconciler safety properties for system jobs

client/client.go
When the client handles an update status response from the server, it modifies its heartbeat stop tracker with a time set once the RPC call returns. It optionally also emits a log message, if the client suspects it has missed a heartbeat.
These times were originally tracked by two different calls to the time function which were executed 2 microseconds apart. There is no reason we cannot use a single time variable for both uses which saves us one whole call to time.Now. …
=> client: Use single time variable when handling heartbeat response.

website/content/commands/eval/status.mdx
The `eval status` documentation is missing the recently-added reconciler annotations.
Ref: https://hashicorp.atlassian.net/browse/NMD-818
* Preview link: https://nomad-git-docs-more-eval-and-alloc-status-details-hashicorp.vercel.app/nomad/commands/eval/status
* No backport, as this feature is only in main!
=> docs: more details for `eval status`

website/content/commands/alloc/status.mdx
The `alloc status` documentation is missing information about placement metrics.
Ref: https://hashicorp.atlassian.net/browse/NMD-818
Preview link: https://nomad-git-docs-more-alloc-status-details-hashicorp.vercel.app/nomad/commands/alloc/status
=> docs: more details for `alloc status`

website/data/docs-nav-data.json
Website links about task driver plugins contains a typo on the host part.
Just browse using the left menu, for example, on the [task driver part](https://developer.hashicorp.com/nomad/docs/deploy/task-driver).
=> fix(doc): fix links for task driver plugins

command/volume_delete.go, website/content/api-docs/volumes.mdx, website/content/commands/volume/delete.mdx
If you delete a CSI volume, the volume cannot be currently claimed by an allocation or in the process of being unpublished. This is documented in the CLI but not the API. Also, the documentation incorrectly says that the `volume delete` command silently returns without error if the volume doesn't exist, but that's incorrect.
Fixes: https://github.com/hashicorp/nomad/issues/24756
Previews:
* https://nomad-git-docs-api-csi-volume-delete-hashicorp.vercel.app/nomad/api-docs/volumes#delete-csi-volume-snapshot
* https://nomad-git-docs-api-csi-volume-delete-hashicorp.vercel.app/nomad/commands/volume/delete
---
```
$ nomad volume delete -type csi foo
Could not find existing CSI volume to delete: no volumes with prefix or ID "foo" found
$ nomad volume delete -type host …
```
=> docs: clarify requirements for deleting volumes

.changelog/26279.txt, api/tasks.go, nomad/structs/structs.go, nomad/structs/structs_test.go, website/content/docs/upgrade/upgrade-specific.mdx
System and sysbatch jobs don't support the reschedule block, because we'd always replace allocations back onto the same node. The job validation for system jobs asserts that the user hasn't set a `reschedule` block so that users aren't submitting jobs expecting it to be supported. But this validation was missing for sysbatch jobs.
Validate that sysbatch jobs don't have a reschedule block.
backporting document.~ No …
=> sysbatch: correctly validate that reschedule policy is not allowed

nomad/deploymentwatcher/deployment_watcher.go, nomad/deploymentwatcher/deployments_watcher.go, nomad/deploymentwatcher/deployments_watcher_test.go, nomad/deploymentwatcher/testutil_test.go
While investigating whether the deploymentwatcher would need updates to implement system deployments, I discovered that some of the tests are racy and make assertions about called functions without waiting.
Update these tests to wait where needed, and generally clean them up while we're in here. In particular I've removed the heavyweight mocking in lieu of checking the call counts and then asserting the expected state store changes.
Ref: https://hashicorp.atlassian.net/browse/NMD-892
=> deployment watcher: refactoring testing

api/jobs.go, command/eval_status.go, command/eval_status_test.go, nomad/structs/structs.go, scheduler/reconciler/reconcile_cluster.go, scheduler/reconciler/reconcile_cluster_prop_test.go, scheduler/reconciler/reconcile_cluster_test.go, scheduler/reconciler/reconcile_node_prop_test.go, scheduler/util.go, website/content/commands/eval/status.mdx
The `DesiredUpdates` struct that we send to the Read Eval API doesn't include information about disconnect/reconnect and rescheduling. Annotate the `DesiredUpdates` with this data, and adjust the `eval status` command to display only those fields that have non-zero values in order to make the output width manageable.
Ref: https://hashicorp.atlassian.net/browse/NMD-815
=> scheduler: add disconnect and reschedule info to reconciler output

api/node_identity.go, api/node_identity_test.go, client/client.go, client/node_identity_endpoint.go, client/node_identity_endpoint_test.go, client/rpc.go, command/agent/http.go, command/agent/node_identity_endpoint.go, command/commands.go, command/node_identity.go, command/node_identity_renew.go, nomad/client_identity_endpoint.go, nomad/client_identity_endpoint_test.go, nomad/node_endpoint.go, nomad/server.go, nomad/structs/node.go
The Nomad client will have its identity renewed according to the TTL which defaults to 24h. In certain situations such as root keyring rotation, operators may want to force clients to renew their identities before the TTL threshold is met. This change introduces a client HTTP and RPC endpoint which will instruct the node to request a new identity at its next heartbeat. This can be used via the API or a new command.
While this is a manual intervention step on top of the any keyring rotation, it dramatically reduces the initial feature complexity as it provides an asynchronous and efficient method of renewal that utilises existing functionality.
The change also includes a fix in the server node RPC handler that ensures we do not erroneously generate new identities for clients that have been …
=> client: Allow operators to force a client to renew its identity.

client/allocrunner/taskrunner/secrets/aws_provider.go, client/allocrunner/taskrunner/secrets/nomad_provider.go, client/allocrunner/taskrunner/secrets/nomad_provider_test.go, client/allocrunner/taskrunner/secrets/vault_provider.go, client/allocrunner/taskrunner/secrets/vault_provider_test.go, client/allocrunner/taskrunner/secrets_hook.go, client/allocrunner/taskrunner/secrets_hook_test.go
Adds `OpenRoot` for accessing rendered template, and user input validation so users cannot inject template functions into secret block parameters.
=> add input validation and path traversal protections

.changelog/26292.txt, scheduler/generic_sched_test.go, scheduler/reconciler/filters.go, scheduler/reconciler/reconcile_cluster.go, scheduler/reconciler/reconcile_cluster_test.go
When a task group is removed from a jobspec, the reconciler stops all allocations and immediately returns from `computeGroup`. We can do the same for when the group has been scaled-to-zero, but doing so runs into an inconsistency in the way that server-terminal allocations are handled.
Prior to this change server-terminal allocations fall through `computeGroup` without being marked as `ignore`, unless they are terminal canaries, in which case they are marked `stop` (but this is a no-op). This inconsistency causes a _tiny_ amount of extra `Plan.Submit`/Raft traffic, but more importantly makes it more difficult to make test assertions for `stop` vs `ignore` vs fallthrough. Remove this inconsistency by filtering out server-terminal allocations early in `computeGroup`.
This brings the cluster …
=> scheduler: exit early on count=0 and filter out server-terminal 

client/fingerprint/fingerprint.go, client/fingerprint/secrets.go, client/fingerprint/secrets_test.go, nomad/mock/job.go, scheduler/feasible/feasible.go, scheduler/feasible/feasible_test.go, scheduler/feasible/stack.go, scheduler/feasible/stack_test.go
Adds basic fingerprinting for builtin Nomad and Vault secrets providers and adds feasibility checks in the Nomad schedulers for the node attributes added during fingerprinting.
=> scheduler: adds implicit constraint for secrets plugin node attributes

website/content/tools/autoscaling/agent.mdx
The current autoscaler docs imply that it has minimal or non-working support for Nomad namespaces. Whereas in fact the namespace support works fine but just doesn't allow configuring multiple namespaces without using a wildcard (for now). Make this more clear and fix the reference to the configuration "below", which is no longer on that same page.
Ref: https://github.com/hashicorp/nomad-autoscaler/issues/65
cc @sofixa
=> docs: clarify namespace support in autoscaler

nomad/job_endpoint_hooks.go, nomad/job_endpoint_hooks_test.go, nomad/structs/structs.go
These changes introduce implied job constraints via the job endpoint hook when secrets are present. Adding these constraints eliminates the possibility of job placement when upgrading to 1.11.
=> adds implied secrets constraint to job hook

website/content/docs/job-specification/connect.mdx, website/content/docs/job-specification/service.mdx, website/content/docs/job-specification/sidecar_service.mdx, website/content/docs/job-specification/sidecar_task.mdx
- Add table to service.port parameter entry to clarify allowed port value types by service kind. See the Jira ticket for more context. **Note** that I added a row for using connect native since [the example on the connect page](https://developer.hashicorp.com/nomad/docs/job-specification/connect#using-consul-service-mesh-native) shows a port label.
- Update a few outdated links to Consul native docs.
Jira: [CE-855]
https://nomad-git-ce855-hashicorp.vercel.app/nomad/docs/job-specification/service#port
change requires …
=> Docs: Clarify service.port  allowed value types

GNUmakefile
It seems the tool requires a little attention and does not run well across our enterprise codebase. Rolling back that makefile change, so it does not stop enterprise work, backport, CI, etc.
=> ci: Revert hclogvet running across entire codebase.

website/content/docs/other-specifications/volume/capability.mdx
The documentation for CSI and DHV has a list of the available access modes, but doesn't explain what they mean in terms of what jobs can request, the scheduler behavior, or the CSI plugin behavior. Expand on the information available in the CSI specification and provide a description of DHV's behavior as well.
Ref: https://github.com/container-storage-interface/spec/blob/master/spec.md#createvolume (scroll down a bit to `message AccessMode `)
=> docs: explain access modes for CSI and DHV volumes

website/content/docs/job-declare/task-driver/raw_exec.mdx
During the big docs rearchitecture, we split up the task driver pages into separate job declaration and driver configuration pages. The link for the `raw_exec` driver to the configuration page is a self-reference.
=> docs: fix self-referencing link for raw_exec driver config

website/content/docs/networking/consul/index.mdx, website/content/docs/secure/vault/index.mdx
Update our support matrix to show currently-supported versions of Consul, Vault, and Nomad.
=> docs: update Vault/Consul compatibility matrix

e2e/e2e_test.go, e2e/secret/doc.go, e2e/secret/input/nomad_secret.hcl, e2e/secret/input/vault_secret.hcl, e2e/secret/secret_test.go
These changes add E2E testing for the Secret block builtin providers.
=> e2e: add initial tests for secrets block

.changelog/26410.txt, client/agent_endpoint_test.go, command/agent/monitor/monitor_test.go, command/agent/monitor/stream_helpers_test.go, command/agent/monitor/test_helpers.go, command/operator_debug.go, command/operator_debug_test.go, nomad/client_agent_endpoint_test.go, website/content/commands/operator/debug.mdx
Support requested the ability to retrieve historical journald logs as part of the debug capture returned by `nomad operator debug`.  PR #26178  introduced a `MonitorExport()` RPC capable of streaming the contents of an agent's log file (if file logging is enabled) or its journald logs.
This PR adds that functionality to `operator debug` with the inclusion of either a `log-file-export=true` flag or a `-log-lookback=<duration>` flag.  An agent's historical log capture runs alongside the capture of running logs and results in both  `monitor.log` and `monitor_export.log` files appearing in each agent's debug capture.
Note to reviewers: I exported a test helper from PR #26178  for this new test case. The helper  generates a golden log file for testing against stream results. And since the …
=> Add historical journald and log export flags to operator debug command

nomad/state/state_store_variables_test.go
The state store test for Variables check-and-set behavior for deletes uses the same state store for a set of parallel tests. But one of the tests overlaps another by using the same path, and this can cause spurious test failures by hitting the CAS conflict error. This overlap doesn't appear to be intentional, so change the test to use a different path.
Also cleaned up some unused test helpers in the same file.
---
Previously this can fail in two places, but the specific errors for line 819 can vary depending on exact interleaving:
```
$ go test -count=100 -race ./nomad/state -run TestStateStore_Variables_DeleteCAS
...
--- FAIL: TestStateStore_Variables_DeleteCAS (0.00s)
--- FAIL: TestStateStore_Variables_DeleteCAS/real_var-cas_0 (0.00s)
state_store_variables_test.go:807: …
```
=> tests: fix conflict from parallelism in state store variables test

command/eval_status.go, command/eval_status_test.go
The plan annotations table isn't sorted by task group, which makes for a less beautiful UX and a flaky test.
---
This feature hasn't shipped in production code, so it doesn't need backports.
=> eval status: sort plan annotations by task group

.changelog/26424.txt, nomad/node_endpoint_test.go, nomad/state/state_store.go, nomad/state/state_store_service_registration.go, nomad/state/state_store_service_registration_test.go
When a node misses a heartbeat and is marked down, Nomad deletes service registration instances for that node. But if the node then successfully heartbeats before its allocations are marked lost, the services are never restored. The node is unaware that it has missed a heartbeat and there's no anti-entropy on the node in any case.
We already delete services when the plan applier marks allocations as stopped, so deleting the services when the node goes down is only an optimization to more quickly divert service traffic. But because the state after a plan apply is the "canonical" view of allocation health, this breaks correctness.
Remove the code path that deletes services from nodes when nodes go down. Retain the state store code that deletes services when allocs are marked terminal by the …
=> wait for service registration cleanup until allocs marked lost

website/content/docs/configuration/vault.mdx
Fixes a small indentation typo in the client vault config page.
=> docs: fix indent on vault create_from_role

nomad/node_endpoint.go, nomad/structs/node.go, nomad/structs/node_test.go
The RPC handler function is quite long, so moving the argument validation into its own function reduces this and makese sense from an organisation view.
=> rpc: Move register args initial validation into separate function.

.changelog/25632.txt, client/serviceregistration/address.go, client/serviceregistration/address_test.go, client/serviceregistration/checks/result.go, nomad/structs/services.go, nomad/structs/structs.go, website/content/docs/job-specification/service.mdx
Fixes #25627 by adding an extra `alloc_advertise_ipv6` option similar to the `AdvertiseIPv6Addr` with the docker driver config. Seems the simplest way to fix this?
I'll finish the contributor checklist if I get a green light about this PR.
See #25627  …
=> Add AllocIPv6 option to allow IPv6 address being used for service registration

client/allocrunner/taskrunner/secrets/nomad_provider.go, client/allocrunner/taskrunner/secrets/nomad_provider_test.go, client/allocrunner/taskrunner/secrets/plugin_provider.go, client/allocrunner/taskrunner/secrets/plugin_provider_test.go, client/allocrunner/taskrunner/secrets/vault_provider.go, client/allocrunner/taskrunner/secrets/vault_provider_test.go, client/allocrunner/taskrunner/secrets_hook.go, client/allocrunner/taskrunner/secrets_hook_test.go, client/allocrunner/taskrunner/template/template.go
These changes refactor the builtin template providers to use a custom Consul-Template render function that holds all templated data in memory. This keeps any secrets from being written to disk.
=> secrets: refactor template providers to hold secrets in memory

client/allocrunner/taskrunner/secrets/nomad_provider.go, client/allocrunner/taskrunner/secrets/vault_provider.go, client/allocrunner/taskrunner/secrets_hook.go, nomad/structs/structs.go, nomad/structs/structs_test.go
Adds task level validation that requires users to have a vault block if they are using the vault secrets provider.
=> test: add task validation when using vault secret provider

scheduler/generic_sched.go, scheduler/generic_sched_test.go
In #8099 we fixed a bug where garbage collecting a job with `disconnect.stop_on_client_after` would spawn recursive delayed evals. But when applied to disconnected allocs with `replace=true`, the fix prevents us from emitting a blocked eval if there's no room for the replacement.
Update the guard on creating blocked evals so that rather than checking for `IsZero` that we check for being later than the `WaitUntil`. This separates this guard from the logic guarding the creation of delayed evals so that we can potentially create both when needed.
Partial fix of: https://github.com/hashicorp/nomad/issues/16644
Ref: https://hashicorp.atlassian.net/browse/NMD-910
Ref: https://github.com/hashicorp/nomad/pull/8099/files#r435198418
ensure regressions …
=> scheduler: don't suppress blocked evals on delay if previous expires

nomad/namespace_endpoint.go, nomad/namespace_endpoint_test.go
When the namespace was not found in state, indicated by a nil object, we were using the name field of the nil object for the return error.
This code path does not currently get triggered as the call flow ensures the namespace will always be found within state. Make this change makes sure we do not hit this panic in the future.
in the majority of situations. The main exceptions are long-lived …
=> namespace: Avoid potential panic when logging namespace name.

e2e/terraform/packer/ubuntu-jammy-amd64/setup.sh
#26558 removed explicit unveils of `NOMAD_SECRETS_DIR`, assuming that we installed a version of `exec2` that did that automatically, but it (the PR, not me!) was wrong!
the e2e errors that surface from this are not very direct, so we may wish to improve exec2's reporting of such problems, but I believe this will fix these two tests:
```
=== FAIL: e2e/exec2 TestExec2/testSecretsDir (2.84s)
exec2_test.go:48: submitting job: "./input/secrets.hcl"
jobs3.go:487: 
jobs3.go:487: expected not to execute this code path
↪ PostScript | annotation ↷
group "group" allocation 53f0e477-28c8-fe94-93db-c6d5f665b257 failed
jobs3.go:652: tg 'group' alloc status 'failed': Failed tasks
jobs3.go:658: tg 'group' task 'password' event: Task received by client
jobs3.go:658: tg 'group' task 'password' event: …
```
=> e2e: install exec2 driver v0.1.0

scheduler/reconciler/reconcile_node.go, scheduler/util.go
In #26169 we started emitting structured logs from the reconciler. But the node reconciler results are `AllocTuple` structs and not counts, so the information we put in the logs ends up being pointer addresses in hex. Fix this so that we're recording the number of allocs in each bucket instead.
Fix another misleading log-line while we're here.
Ref: https://github.com/hashicorp/nomad/pull/26169
=> scheduler: fix debug-level logging for node reconciler

drivers/docker/config_test.go, drivers/docker/testdata/TestConfig_ParseAllHCL.hcl, website/content/docs/job-declare/task-driver/docker.mdx
Back in #24074 I thought it was necessary to wrap labels in a list to support quoted keys in hcl2. This... doesn't appear to be true at all? The simpler `labels={...}` syntax appears to work just fine.
I updated the docs and a test (and modernized it a bit). I also switched some other examples to the `labels = {}` format from the old `labels{}` format.
in the majority of situations. The main …
=> docs: revert to labels={"foo.bar": "baz"} style

e2e/terraform/provision-infra/compute.tf
Re-enables IMDSv2 on the e2e EC2 instances now that go-discover is updated in all the right places.
Ran the terraform manually to ensure the cluster was created successfully, and that IMDSv2 is required. 
Internal ref https://hashicorp.atlassian.net/browse/NMD-132
within …
=> Require IMDSv2 for e2e EC2 instances

e2e/terraform/main.tf
When we refactored the E2E provisioning to allow it to be reused by the upgrade testing, we didn't thread the `instance_type` variable from the main module down into the `provision-infra` module. This prevents you from setting a custom instance size when deploying the E2E cluster manually.
=> E2E: allow setting instance_type variable

client/allocrunner/health_hook.go, client/allocrunner/health_hook_test.go, scheduler/scheduler_system.go
Corrects two minor bugs that prevented proper deployment monitoring for systems
jobs: populating the new `deployment` field of the system scheduler object, and
correcting allocrunner health checks that were guarded not to run on system
jobs. 
Targets the feature branch `f-system-deployments`.
=> scheduler: monitor deployments correctly

command/agent/retry_join.go, command/agent/retry_join_test.go
The `RetryJoin` function checks for an error and logs it before
retrying. The error variables were shadowed which resulted in
the errors never being logged. This predefines the variables
to prevent them from being shadowed.
The testlog package was also updated to support providing a custom
writer which allows logging output to be easily caught and inspected.
in the majority of situations. The main …
=> [agent] Fix error checking within retry join

nomad/structs/structs.go, scheduler/reconciler/reconcile_node.go, scheduler/scheduler_system.go
As per RFC-216, `Stagger` setting is basically `MinHealthyTime` now, and will be obsoleted in the future. 
Targets the feature branch f-system-deployments.
=> scheduler: correct handling of MaxParallel and obsoleting Stagger in the system scheduler

.changelog/26608.txt, client/allocrunner/taskrunner/getter/params.go, client/allocrunner/taskrunner/getter/params_test.go, client/allocrunner/taskrunner/getter/sandbox.go, client/allocrunner/taskrunner/getter/sandbox_test.go, client/allocrunner/taskrunner/getter/testing.go, client/allocrunner/taskrunner/getter/util.go, client/allocrunner/taskrunner/getter/util_default.go, client/allocrunner/taskrunner/getter/util_linux.go, client/allocrunner/taskrunner/getter/util_test.go, client/allocrunner/taskrunner/getter/util_windows.go, client/config/artifact.go, nomad/structs/config/artifact.go, website/content/docs/configuration/client.mdx
This adds artifact inspection after download to detect any issues
with the content fetched. Currently this means checking for any
symlinks within the artifact that resolve outside the task or
allocation directories. On platforms where lockdown is available
(some Linux) this inspection is not performed.
The inspection can be disabled with the DisableArtifactInspection
option. A dedicated option for disabling this behavior allows
the DisableFilesystemIsolation option to be enabled but still
have artifacts inspected after download.
[SECVULN-12425](https://hashicorp.atlassian.net/browse/SECVULN-12425)
the [website …
=> [artifact] add artifact inspection after download

e2e/ui/input/proxy.nomad, e2e/ui/run.sh
The call to IMDSv1 has been failing since we switched to v2 which meant the UI e2e script attempted to use the service IP address for its tests. The service IP address is the Nomad client's private address which is not routable from the e2e test runner which means the test fails.
This change updates the IP discovery to use IMDSv2 which means the address is correctly populated and routable. The change also makes this discovery method by a job action within the proxy job. This exercises that feature and utilizes it in a way for which it was designed.
I executed the UI e2e test locally against a cloud provisioned cluster:
```console
$ ./run.sh ci
+ run_proxy
+ nomad namespace apply proxy
Successfully applied namespace "proxy"!
+ nomad job run ./input/proxy.nomad
==> …
```
=> e2e: Correctly handle IMDSv2 when discovering UI proxy address.

go.mod, go.sum
No functional changes. Bumping just to clear up some license ambiguities.
See https://github.com/hashicorp/cronexpr/compare/v1.1.2...v1.1.3
=> bump cronexpr from v1.1.2 -> v1.1.3

scheduler/reconciler/reconcile_node.go, scheduler/reconciler/reconcile_node_test.go
In the system scheduler, we need to keep track which nodes were previously used
as "canary nodes" and not pick them at random, in case of previously failed
canaries or changes to the amount of canaries in the jobspec. 
Targets the feature branch f-system-deployments.
=> system scheduler: keep track of previously used canary nodes

.github/actions/setup-js/action.yml, .github/workflows/build.yml, .github/workflows/release.yml
Porting @gulducat's hot fix  to the [release/1.8.17+ent ](https://github.com/hashicorp/nomad-enterprise/commit/557e5331acda4d86d717deb73622308944c82f31)and [1.9.13+ent](https://github.com/hashicorp/nomad-enterprise/commit/49732e8447086745c4ed1913ae9a5e76b1a4b345) branches.
This fix resolves an issue with the setup-node action's clean up stage by ensuring that the path returned by `pnpm store path --silent` exists and creating the directory if not.  This prevents the action from failing otherwise successful builds during the clean up stage.
Successful manual invocation of this repo's build stage [here](https://github.com/hashicorp/nomad/actions/runs/17598638896)
There are no open issues for this but this is the original build failure on …
=> build:replicate nomad-ent 49732e8447086745c4ed1913ae9a5e76b1a4b345

.changelog/26649.txt, scheduler/feasible/feasible.go, scheduler/feasible/feasible_test.go
A small optimization in the scheduler required users to specify specific models of devices if the required count was higher than the individual model/vendor on the node. This change removes that optimization to allow for more intuitive device scheduling when different vendor/model device types exist on a node.
Fixes [GH #26584](https://github.com/hashicorp/nomad/issues/26584)
in the majority of …
=> scheduler: allow device count to use different vendors/models

client/commonplugins/secrets_plugin.go, client/fingerprint/secrets.go, helper/funcs.go, helper/funcs_unix.go, helper/funcs_windows.go
I was testing secrets plugins support added  by #26681 and noticed it does not load plugins in Windows because those always have `exe` extension. So this fixes that.
<details>
<summary>Secrets plugin</summary>
```golang
package main
import (
"encoding/json"
"fmt"
"os"
)
type FingerprintResponse struct {
Type    string `json:"type"`
Version string `json:"version"`
}
type FetchResponse struct {
Result map[string]string `json:"result"`
}
func fingerprint() {
resp := FingerprintResponse{
Type:    "secrets",
Version: "0.0.1",
}
output, _ := json.Marshal(resp)
fmt.Println(string(output))
}
func fetch() {
secretMap := make(map[string]string)
secretMap["password"] = "P@ssw0rd!"
resp := FetchResponse{Result: secretMap}
output, _ := json.Marshal(resp)
fmt.Println(string(output))
}
func main() {
if …
```
=> secrets: Support custom plugins in Windows

command/agent/node_identity_endpoint.go, command/agent/node_identity_endpoint_test.go
When calling the client identity renew API, it is possible the target node ID is provided by either the URI or within the request body. This change fixes a bug where all calls using a node_id query parameter would be reject as it failed to decode the empty request body. …
=> http: Fix client identity renew call when node ID is in URI.

scheduler/reconciler/reconcile_node.go, scheduler/reconciler/reconcile_node_test.go
System jobs that get rescheduled should not get new deployments. 
Fixes unit test failure from https://github.com/hashicorp/nomad/pull/26777
=> scheduler: do not create deployments for system job reschedules

client/client_test.go
The test was incorrectly writing to state that registration had been finished before writing the node identity token. This is the opposite of what happens in the client code and caused a timing issue which meant we read registration as completed before we had the identity available and therefore returned the secret ID.
Before change:
```console
$ NOMAD_TEST_LOG_LEVEL=ERROR gotestsum -- -v -count=10 ./client -run TestClient_getRegistrationToken/node_identity_registered_state
✖  client (2.37s)
=== Failed
=== FAIL: client TestClient_getRegistrationToken/node_identity_registered_state (0.17s)
2025-09-18T09:48:02.447+0100 [ERROR] client/client.go:3134: client: error discovering nomad servers: error="no Nomad Servers advertising service \"nomad\" in Consul datacenters: [\"dc1\"]" …
```
=> test: Fix test flake in client get registration token

.changelog/26794.txt, Dockerfile
Nomad's periodic block includes a "time_zone" parameter which lets operators set the time zone at which the next launch interval is checked against. For this to work, Nomad needs to use the "time.LoadLocation" which in-turn can use multiple TZ data sources.
When using the Docker image to trigger Nomad job registrations, it currently does not have access to any TZ data, meaning it is only aware of UTC. Adding the tzdata package contents to the release image provides the required data for this to work.
It would have also been possible to set the "-tags" build tag when releasing Nomad which would embed a copy of the timezone database in the code. We decided against using the build tag approach as it is a subtle way that we could introduce bugs that are very difficult to track down and we …
=> build: Add tzdata to Docker container final image.

e2e/scaling/scaling_test.go
We need to wait for the deployment for a system job to finish before scaling, otherwise:
```
=== RUN   TestScaling/TestScaling_System
scaling_test.go:194:
scaling_test.go:194: expected nil error
↪ error: Unexpected response code: 400 (job scaling blocked due to active deployment)
--- FAIL: TestScaling (56.34s)
```
=> e2e: fix TestScaling/TestScaling_System

CHANGELOG.md
Due to the delayed release of Nomad Enterprise, we didn't have the changelog entries for these two releases.
=> changelog for Nomad Enterprise 1.9.13+ent and 1.8.17+ent

api/node_pools.go, api/node_pools_test.go, command/asset/pool.nomad.hcl, command/asset/pool.nomad.json, command/node_pool_apply.go, command/node_pool_apply_test.go, command/node_pool_info.go, command/node_pool_info_test.go, command/node_pool_list_test.go, helper/hcl/decode.go, helper/hcl/parse.go, helper/hcl/parse_test.go, nomad/mock/mock.go, nomad/structs/node_pool.go
The node identity TTL defaults to 24hr but can be altered by setting the node identity TTL parameter. In order to allow setting and viewing the value, the field is now plumbed through the CLI and HTTP API.
In order to parse the HCL, a new helper package has been created which contains generic parsing and decoding functionality for dealing with HCL that contains time durations. hclsimple can be used when this functionality is not needed. In order to parse the JSON, custom marshal and unmarshal functions have been created as used in many other places.
The node pool init command has been updated to include this new parameter, although commented out, so reference. The info command now includes the TTL in its output too.
Using the `nomad node pool init` command you can generate HCL and JSON …
=> node pool: Allow specifying node identity ttl in HCL or JSON spec.

.changelog/26832.txt, client/pluginmanager/csimanager/volume.go, client/pluginmanager/csimanager/volume_test.go
In #26831 we're preventing unexpected node RPCs by ensuring that the volume watcher only unpublishes when allocations are client-terminal.
To mitigate any remaining similar issues, add serialization of node plugin RPCs, as we did for controller plugin RPCs in #17996 and as recommended by the CSI specification. Here we can do per-volume serialization rather than per-plugin serialization.
This PR is broken into two commits: one that adds the serialization (and tests) and a second one reorders the methods in this file so that each interface method and its directly-associated helper methods read from top-to-bottom, instead of a mix of directions. It may be easier to review the commits one-by-one.
Ref: https://github.com/hashicorp/nomad/pull/17996
Ref: …
=> CSI: serialize node plugin RPCs per-volume

.changelog/26872.txt, nomad/fsm.go
When we attempt to drop unneeded evals from the eval broker, if the eval has been GC'd before the check is made, we hit a nil pointer. Check that the eval actually exists before attempting to remove it from the broker.
Fixes: https://github.com/hashicorp/nomad/issues/26871
history should be …
=> state: nil-check waiting evals before attempting to cancel them

.changelog/26664.txt, nomad/encrypter.go, nomad/encrypter_test.go, nomad/structs/config/vault.go
The transit keyring uses the go-kms-wrapper for parsing the vault config and errors if tlsSkipVerify is an empty string. We should ensure TLSSkipVerify is defaulting to false.
Fixes [GH #26596](https://github.com/hashicorp/nomad/issues/26596) …
=> vault: default tlsSkipVerify to false

e2e/scheduler_system/input/system_canary_v1_100.nomad.hcl, e2e/scheduler_system/systemsched_test.go
Assertions didn't account for infeasible nodes.
=> e2e: correction to assertions in system scheduler tests

GNUmakefile
- Adds automatic architecture detection to the `cni` makefile target
- Enables arm64/aarch64 support alongside existing amd64 support
- Uses existing `THIS_ARCH` variable for consistency with other build targets
The `cni` make target was hardcoded to download amd64 CNI plugins, preventing users on arm64/aarch64 Linux systems from using this convenience target. This change detects the system architecture and downloads the appropriate CNI plugin binary.
- Added architecture mapping logic: `aarch64` → `arm64`, `x86_64` → `amd64`
- Modified CNI plugin download URL to use detected architecture variable
- Added comment explaining the architecture detection
- Verified make dry-run (`make -n cni`) correctly detects architecture
- Confirmed both amd64 and arm64 CNI plugin URLs exist and are …
=> build: add architecture detection to CNI makefile target

.changelog/26664.txt, nomad/encrypter.go, nomad/encrypter_test.go
Manual backport of https://github.com/hashicorp/nomad/pull/26664
=> backport of: vault: default tlsSkipVerify to false (#26664) into release/1.10.x

.changelog/26858.txt, command/agent/agent.go, command/agent/agent_test.go, command/agent/config.go, command/agent/config_parse_test.go, command/agent/config_test.go, command/agent/testdata/basic.hcl, command/agent/testdata/basic.json, nomad/config.go, nomad/job_endpoint.go, nomad/job_endpoint_hooks.go, nomad/job_endpoint_hooks_test.go, nomad/job_endpoint_test.go, nomad/structs/structs.go, website/content/docs/configuration/server.mdx, website/content/docs/upgrade/upgrade-specific.mdx
If a Nomad job is started with a large number of instances (e.g. 4 billion), then the Nomad servers that attempt to schedule it will run out of memory and crash. While it's unlikely that anyone would intentionally schedule a job with 4 billion instances, we have occasionally run into issues with bugs in external automation. For example, an automated deployment system running on a test environment had an off-by-one error, and deployed a job with `count = uint32(-1)`, causing the Nomad servers for that environment to run out of memory and crash.
To prevent this, this PR introduces a `job_max_count` Nomad server configuration parameter. `job_max_count` limits the number of allocs that may be created from a job. The default value is 50000 - this is low enough that a job with the maximum …
=> Add job_max_count option to keep Nomad server from running out of memory

.changelog/26662.txt, scheduler/generic_sched.go, scheduler/generic_sched_test.go
Preferred node is used when a task group has an ephemeral disk, so we ideally stay on the same node. However if the jobs node pool changes, we should not select the current node as the preferred node, and let the scheduler decide which node to pick from the correct node pool.
Fixes [GH #26600](https://github.com/hashicorp/nomad/issues/26600)
in the majority of situations. The main exceptions are …
=> scheduler: skip setting preferred node when nodepool changes
