hashicorp/nomad

CHANGELOG.md

This adds changelog for https://github.com/hashicorp/nomad/pull/8311

changelog for sidecar bug

---

CHANGELOG.md

CHANGELOG agent host

---

scheduler/reconcile.go

Pre-0.12.0 beta, a deployment was considered "complete" if it was
successful. But with MRD we have "blocked" and "unblocking" states as well. We
did not consider the case where a concurrent alloc health status update
triggers a `Compute` call on a deployment that's moved from "blocked" to
"unblocking" (it's a small window), which caused an extra pass thru the
`nextRegion` logic in `deploymentwatcher` and triggered an error when later
transitioning to "successful".
This changeset makes sure we don't overwrite that status.

reconcile should not overwrite unblocking state

---

website/data/docs-navigation.js
website/pages/docs/internals/security.mdx

Adding a security model for Nomad.

Add security model document

---

website/data/docs-navigation.js
website/pages/docs/autoscaling/agent.mdx
website/pages/docs/autoscaling/api.mdx
website/pages/docs/autoscaling/cli.mdx
website/pages/docs/autoscaling/index.mdx
website/pages/docs/autoscaling/internals/checks.mdx
website/pages/docs/autoscaling/internals/index.mdx
website/pages/docs/autoscaling/plugins/apm.mdx
website/pages/docs/autoscaling/plugins/index.mdx
website/pages/docs/autoscaling/plugins/strategy.mdx
website/pages/docs/autoscaling/plugins/target.mdx
website/pages/docs/autoscaling/policy.mdx

related https://github.com/hashicorp/nomad-autoscaler/issues/167
related https://github.com/hashicorp/nomad-autoscaler/issues/188

 docs: migration of Nomad Autoscaler docs with cluster updates.

---

CHANGELOG.md

docs: update changelog with some connect fixes
docs: update changelog with note for go modules switch

docs: some additional CL entries

---

website/pages/docs/enterprise/index.mdx

This updates the Enterprise documentation page to reflect current offerings and new features.

Update Enterprise docs page, add new features

---

e2e/terraform/packer/linux/setup.sh

update packer script to use latest podman version

use latest podman release

---

client/fingerprint/network_test.go
go.mod
vendor/modules.txt

Noticed this while reviewing PRs.

tests: avoid os.Exit in a test

---

website/pages/docs/internals/security.mdx

Address some feedback on https://github.com/hashicorp/nomad/pull/8369 .

Revise security model feedback

---

website/pages/docs/job-specification/reschedule.mdx

Struck paragraph that said it didn't

[docs] Rescheduling does happen during deployments

---

api/namespace_test.go
api/sentinel_test.go
command/agent/agent.go
command/agent/command.go
command/license_get_test.go
command/namespace_apply_test.go
command/namespace_delete_test.go
command/namespace_list_test.go
nomad/client_agent_endpoint_test.go
nomad/config.go
nomad/fsm_test.go
nomad/operator_endpoint.go
nomad/server_setup_oss.go
nomad/state/state_store.go
nomad/state/state_store_oss.go
nomad/state/testing.go
nomad/state/testing_oss.go

Backport some OSS changes from Enterprise repository.

Back-port Some Enterprise changes

---

CHANGELOG.md

Changelog item for https://github.com/hashicorp/nomad/pull/8456

changelog item for MRD canary bugfix

---

CHANGELOG.md

Change log for Enterprise bug fix
fixes #8457

changelog for license apply bug

---

command/assets/connect.nomad

Fixes https://github.com/hashicorp/nomad/issues/8109

format job init hcl

---

command/license.go
command/license_get_test.go

Removes duplicated CLI output for license info

remove duplicate license info

---

CHANGELOG.md
website/pages/docs/commands/operator/snapshot-agent.mdx

and update changelog for NodeNetwork fix

Docs snapshot docs tweaks

---

website/_redirects
website/data/docs-navigation.js
website/pages/docs/drivers/podman.mdx

Moves podman documentation into non-external task drivers

move podman out of external task drivers

---

website/data/alert-banner.js

webinar scheduled for July 23rd, can roll back to the previous banner afterwards

updating banner for webinar

---

website/data/alert-banner.js

This reverts commit 2c4a801b7de8857a1cd58c40f1d7ff8be951102c.

Revert "updating banner for webinar"

---

CHANGELOG.md
website/pages/docs/job-specification/scaling.mdx

related - https://github.com/hashicorp/nomad/issues/8481

docs: update website and changelog to clarify and detail GH-8481

---

command/ui.go
command/ui_test.go

Fix for https://github.com/hashicorp/nomad/issues/7739

change url to client

---

CHANGELOG.md
website/pages/api-docs/jobs.mdx

docs: update website and changelog to detail GH-8527

---

website/pages/api-docs/jobs.mdx

This param changed at some point. Updating the docs to match.

Docs: Update Reason to Message in the job scale docs

---

website/data/docs-navigation.js
website/pages/docs/drivers/external/containerd.mdx
website/pages/docs/drivers/external/index.mdx

Add nomad-driver-containerd to nomad UI docs.

---

nomad/csi_endpoint.go

Using the count of node claims from earlier in the `CSIVolume.Unpublish` RPC
doesn't correctly account for cases where the RPC was interrupted but
checkpointed. Instead, we'll check the current allocation count and status to
determine whether we need to send a controller unpublish.
I've pulled this changeset out of #8584 because it's not really related.

csi: controller unpublish should check current alloc count

---

website/data/docs-navigation.js
website/pages/docs/drivers/external/containerd.mdx
website/pages/docs/drivers/external/index.mdx
website/pages/docs/install/index.mdx
website/pages/docs/install/quickstart/index.mdx

Cherrypicking #8574 and #8534 onto stable-website for release.

[docs] Deploy Install, nomad-driver-containerd docs

---

CHANGELOG.md

docs: add cl entry for connect native bridge mode

---

nomad/client_csi_endpoint.go

Our RPC calls mangle the errors we get, which prevents us from using wrapped
errors and `errors.Is`.
Also fixes log message fields.
This partially reverts https://github.com/hashicorp/nomad/pull/8632, which I shouldn't have merged until I'd tested it end-to-end. I've now done that. 😊

msgpack-rpc errors cannot be wrapped

---

demo/csi/cinder-csi-plugin/README.md
demo/csi/cinder-csi-plugin/cinder-csi-plugin.hcl
demo/csi/cinder-csi-plugin/example_volume.hcl

Adding a demo for the Cinder CSI Plugin following the guidelines specified in the newly added [demo/csi/README.md](demo/csi/cinder-csi-plugin/README.md).

Add Demo for Openstack Cinder CSI Plugin Deployment

---

website/pages/docs/drivers/podman.mdx

Website changes for https://github.com/hashicorp/nomad-driver-podman/pull/64

Podman driver: Add support for signal task.

---

e2e/README.md

Just a smattering of attempted improvements as I read through this
again. Some of my goals:
- Tried to add more high level info to the intro to set the context
- Clarify the difference between *test* dev and *agent* dev workflows
- Add -timeout to provisioning step because cable Internet is lol

docs: clarify e2e tests

---

website/pages/docs/commands/job/run.mdx

docs: fix job run -detach example

---

website/pages/docs/drivers/external/nspawn.mdx

There have been some new config options added in recent releases of the nspawn
driver. This commit updates the docs accordingly.

Update docs for nspawn driver

---

command/agent/csi_endpoint.go

Fixes https://github.com/hashicorp/nomad/issues/8730
I've also opened https://github.com/hashicorp/nomad/issues/8734 as what will probably be a post-1.0 effort to eliminate this particular source of bugs in the future.

csi: fix panic in serializing nil allocs in volume API

---

website/pages/docs/enterprise/index.mdx

remove preemption from summary of governance and policy module since it is now OSS.
add cross-namespace queries to that same sentence.

remove preemption, add cross-namespace queries

---

acl/policy.go
acl/policy_test.go
client/allocdir/alloc_dir.go
nomad/job_endpoint.go
nomad/structs/structs.go

Assorted random fixes, best reviewed commit by commit.

Assorted small fixes

---

nomad/job_endpoint.go
nomad/job_endpoint_oss.go

This changeset is the OSS hooks for what will be implemented in ENT.

MRD: deregister regions that are dropped on update

---

CHANGELOG.md

Covers [MRD and CSI bug fixes](https://github.com/hashicorp/nomad/pulls?q=is%3Apr+is%3Aclosed+author%3Atgross+milestone%3A0.12.4)

changelog: batch of bug fixes for 0.12.4

---

website/data/docs-navigation.js

Everything else in the docs sidebars is alphabetized, so do it here too.

docs: alphabetize community task driver listing

---

ui/mirage/factories/agent.js
ui/mirage/factories/evaluation.js
ui/mirage/factories/job-summary.js
ui/mirage/factories/job.js
ui/mirage/factories/node.js
ui/mirage/factories/task-group.js
ui/mirage/models/allocation.js
ui/mirage/models/job-summary.js
ui/mirage/models/job.js
ui/mirage/models/service.js
ui/mirage/serializers/allocation.js
ui/mirage/serializers/application.js
ui/mirage/serializers/job.js
ui/tests/acceptance/allocation-detail-test.js
ui/tests/acceptance/exec-test.js
ui/tests/acceptance/servers-list-test.js
ui/tests/acceptance/task-detail-test.js
ui/tests/integration/components/scale-events-accordion-test.js

These warts from when I didn't know what I was doing with Mirage have bothered me for too long. Time for them to go.

UI: Clean up erroneous and redundant mirage things

---

website/pages/docs/install/production/deployment-guide.mdx

i think https://learn.hashicorp.com/collections/nomad/access-control is the right link

Docs: update acl guide broken link

---

command/operator_debug.go

add's license info json to debug command

add license info to operator debug command

---

website/pages/docs/autoscaling/plugins/target.mdx

related https://github.com/hashicorp/nomad-autoscaler/issues/254

docs: fix incorrect aws-asg autoscaler target plugin policy params

---

website/data/docs-navigation.js
website/pages/docs/autoscaling/agent.mdx
website/pages/docs/autoscaling/api.mdx
website/pages/docs/autoscaling/cli.mdx
website/pages/docs/autoscaling/telemetry.mdx

Related: https://github.com/hashicorp/nomad-autoscaler/pull/238

docs: add Autoscaler telemetry documentation to website.

---

website/pages/docs/autoscaling/plugins/apm.mdx

Related: https://github.com/hashicorp/nomad-autoscaler/pull/241

docs: add Nomad Autoscaler Datadog APM plugin details.

---

CHANGELOG.md

Forgot to stick this onto the end of the PR.

Changelog entry for 8833

---

website/pages/api-docs/volumes.mdx

Fix sample JSON payload when updating a Volume

---

CHANGELOG.md

changelog entry for #8902

---

website/pages/docs/drivers/docker.mdx

Came across this when reading docs.

Add missing double quote

---

website/pages/docs/job-specification/job.mdx

Fixes https://github.com/hashicorp/nomad/issues/8786

docs: Fix group link in job spec docs

---

CHANGELOG.md

update changelog with 0.12.5 content

---

CHANGELOG.md

[ci skip]
For:
* https://github.com/hashicorp/nomad/pull/8836
* https://github.com/hashicorp/nomad/pull/8921

changelog items for community PRs

---

scripts/vagrant-linux-priv-consul.sh
scripts/vagrant-linux-priv-vault.sh

Update Vagrant setup to use the consul/vault versions used in CI.

Update Vagrant consul/vault deps

---

CHANGELOG.md

Changelog item for https://github.com/hashicorp/nomad/pull/8979

changelog: azure fingerprint

---

drivers/exec/driver_test.go
drivers/shared/executor/executor_linux_test.go
drivers/shared/executor/executor_test.go
drivers/shared/resolvconf/mount_unix_test.go
plugins/drivers/testutils/dns_testing.go

More test fixes so it can succeed when running on Ubuntu 18.04, the vagrant setup.  Best reviewed commit-by-commit.

Tests: fix some tests for Ubuntu 18.04

---

CHANGELOG.md

Changelog entry for https://github.com/hashicorp/nomad/pull/7214

changelog entry for Consul segment fingerprint

---

website/pages/docs/job-specification/network.mdx

[doc] fix deprecated port_map example

---

ui/app/components/line-chart.js
ui/app/utils/properties/style-string.js

UI: Change htmlSafe prototype calls to imports

---

e2e/vaultsecrets/vaultsecrets.go

resolves https://app.circleci.com/pipelines/github/hashicorp/nomad/12347/workflows/0dd4401b-da3c-495a-848c-7259e37ffdb3/jobs/108127

fix go 1.15 pickiness

---

CHANGELOG.md

Forgotten changelog entry for https://github.com/hashicorp/nomad/pull/9101

changelog entry for Docker config image_delay fix

---

e2e/spread/spread.go

To help diagnose https://github.com/hashicorp/nomad/issues/7314
The spread test is infrequently flaky and it's hard to extract what's actually
happening. If the test fails, dump all the allocation metrics so that we can
debug the behavior.

e2e: add reporting to flaky spread test

---

CHANGELOG.md
client/allocrunner/taskrunner/getter/getter.go
client/allocrunner/taskrunner/template/template.go
helper/funcs.go
helper/funcs_test.go

artifact/template: make destination path absolute inside taskdir (0.11.6)

---

CHANGELOG.md
client/allocrunner/taskrunner/getter/getter.go
client/allocrunner/taskrunner/template/template.go
helper/funcs.go
helper/funcs_test.go

Backport of https://github.com/hashicorp/nomad/pull/9149 to 0.12.7

artifact/template: make destination path absolute inside taskdir (0.12.7)

---

website/data/alert-banner.js
website/package-lock.json
website/package.json
website/pages/style.css

[Asana](https://app.asana.com/0/0/1198562802487554/f)
Adds an example of the `expirationDate` prop associated with the `<AlertBanner/>` component, in order to help expose this "feature" to future contributors.

Document new `expirationDate` prop for AlertBanner

---

website/data/docs-navigation.js
website/pages/docs/commands/scaling/index.mdx
website/pages/docs/commands/scaling/policy-info.mdx
website/pages/docs/commands/scaling/policy-list.mdx

docs: add new scaling command website documentation.

---

website/pages/api-docs/events.mdx

event sink api docs

---

website/data/docs-navigation.js
website/pages/docs/commands/job/scale.mdx
website/pages/docs/commands/job/scaling-events.mdx

docs: add new job scale and scaling-events CLI website docs.

---

website/data/api-navigation.js
website/pages/api-docs/recommendations.mdx
website/pages/api-docs/scaling-policies.mdx
website/pages/docs/autoscaling/index.mdx
website/pages/docs/autoscaling/plugins/strategy.mdx
website/pages/docs/autoscaling/plugins/target.mdx
website/pages/docs/autoscaling/policy.mdx
website/pages/docs/enterprise.mdx

Reviewed in private previously.

docs: DAS related documentation updates

---

CHANGELOG.md

changelog entry for https://github.com/hashicorp/nomad/pull/9225

CHANGELOG entry for #9225

---

website/package-lock.json
website/package.json

This should allow the website to render normally again! 🙌🏼

fix website dependency issue

---

ui/app/components/topo-viz.js
ui/app/components/topo-viz/node.js
ui/app/styles/charts/tooltip.scss
ui/app/templates/components/topo-viz.hbs
ui/app/templates/components/topo-viz/datacenter.hbs
ui/app/templates/components/topo-viz/node.hbs
ui/app/utils/properties/style-string.js
ui/tests/integration/components/topo-viz-test.js
ui/tests/integration/components/topo-viz/datacenter-test.js
ui/tests/integration/components/topo-viz/node-test.js
ui/tests/pages/components/topo-viz/node.js

See some allocation information at a glance.
A lot of this diff is a CSS indentation change.

UI: Topo Viz Tooltips

---

command/scaling_policy_list.go
website/pages/docs/commands/scaling/policy-list.mdx

include doc update to detail flag options.

cli: update scaling policy list help to include job flag.

---

ui/app/components/fs/file.js
ui/app/templates/components/fs/file.hbs
ui/tests/integration/components/fs/file-test.js

Fixes #9022 
Use fetch API to download file so we can:
- send Token in headers
- assign filename to download

ui: "View Raw File" download using JS instead simple link

---

ui/app/abilities/abstract.js
ui/app/abilities/job.js
ui/app/controllers/topology.js
ui/app/routes/topology.js
ui/app/services/user-settings.js
ui/app/styles/components/dashboard-metric.scss
ui/app/styles/components/tooltip.scss
ui/app/styles/core/columns.scss
ui/app/templates/topology.hbs

Rounding out the page with some clarificationy things.
The majority of this diff is indentation.

UI: Topo viz error state and no data polling notice

---

command/commands.go
command/recommendation.go
command/recommendation_apply.go
command/recommendation_apply_test.go
command/recommendation_dismiss.go
command/recommendation_dismiss_test.go
command/recommendation_info.go
command/recommendation_info_test.go
command/recommendation_list.go
command/recommendation_list_test.go

Adds new CLI commands for applying, dismissing and detailing Nomad
recommendations under a new top level recommendation command.

cli: add recommendation commands.

---

.circleci/config.yml
.circleci/config/config.yml
CHANGELOG.md
README.md
scripts/release/mac-remote-build
scripts/vagrant-linux-priv-go.sh

1.15.5 is due in a couple days but we may release before then.

go: update from 1.15.1 to 1.15.4

---

CHANGELOG.md

changelog for enterprise bug

---

ui/tests/acceptance/optimize-test.js

One of those situations where the PR branch passed but failed after merging due to being behind master.
Most of the diff is Prettier (which raises another question), it's only line 361 that fixed the test failures.

UI: Add missing feature fixture that was introduced while DAS filtering was being implemented

---

CHANGELOG.md
website/pages/docs/drivers/docker.mdx

small assorted changes - some context in individual commit messages.

Assorted changelog and docs changes

---

scripts/release/Dockerfile
scripts/vagrant-linux-unpriv-ui.sh

Pin the exact node version, as expected by the release scripts.

ui: Pin ui node version

---

ui/app/components/lifecycle-chart.js
ui/app/styles/components/lifecycle-chart.scss
ui/app/templates/components/lifecycle-chart.hbs
ui/mirage/factories/task.js
ui/tests/acceptance/allocation-detail-test.js
ui/tests/acceptance/task-detail-test.js
ui/tests/integration/components/lifecycle-chart-test.js
ui/tests/pages/components/lifecycle-chart.js

This brings back the poststop phase extracted from https://github.com/hashicorp/nomad/pull/8742.
It also fixes the two flaky tests and the one typo'd assertion.

UI: Task lifecycle poststop phase.

---

ui/app/templates/components/task-row.hbs
ui/app/templates/jobs/job/task-group.hbs

Fixes https://github.com/hashicorp/nomad/issues/9249
(I've got a changelog with a handful of CSI items I'm batching up which will include this)

ui/csi: fix links to volume IDs

---

vendor/github.com/hashicorp/nomad/api/tasks.go

Change resulting from `make sync`

vendor: sync api/tasks for poststop hook

---

website/pages/api-docs/allocations.mdx

document `api.Allocation.Job` field

---

website/pages/api-docs/jobs.mdx
website/pages/docs/commands/job/dispatch.mdx

Fixes https://github.com/hashicorp/nomad/issues/7614

docs: make dispatch payload size limit unambiguous

---

website/pages/docs/configuration/vault.mdx

See
https://github.com/hashicorp/nomad/blob/v0.12.7/nomad/vault.go#L36-L39

docs: add task_token_ttl default

---

website/pages/docs/job-specification/task.mdx

Fixes https://github.com/hashicorp/nomad/issues/7747

docs: clarify default signal for raw_exec on Windows

---

website/pages/docs/drivers/exec.mdx

Fixes https://github.com/hashicorp/nomad/issues/9242

docs: enumerate required cgroups for exec driver

---

ui/README.md
ui/mirage/scenarios/default.js

You can see an example with `emptyCluster` [here](https://deploy-preview-9380--nomad-ui.netlify.app/ui/?mirage-scenario=emptyCluster).

UI: Add query parameter to override Mirage scenario

---

website/pages/docs/job-specification/hcl2/functions/ipnet/cidrsubnets.mdx

address https://github.com/hashicorp/nomad/pull/9322#discussion_r529576871

add sidebar title for cidrsubnets

---

nomad/state/state_store.go

Create events for upsertjob msg type
resolves #9432

pass in msgType for UpsertJob

---

website/pages/docs/job-specification/hcl2/index.mdx

per our discussion today, taking a first pass to head off some possible confusion about new HCL parsing features.

added some discussion of HCL parsing context

---

website/pages/api-docs/agent.mdx
website/pages/api-docs/json-jobs.mdx
website/pages/docs/autoscaling/plugins/strategy.mdx
website/pages/docs/commands/node/eligibility.mdx
website/pages/docs/configuration/audit.mdx
website/pages/docs/drivers/docker.mdx
website/pages/docs/drivers/external/containerd.mdx
website/pages/docs/drivers/external/index.mdx
website/pages/docs/drivers/external/nspawn.mdx
website/pages/docs/drivers/qemu.mdx
website/pages/docs/index.mdx
website/pages/docs/internals/architecture.mdx
website/pages/docs/internals/security.mdx
website/pages/docs/job-specification/service.mdx
website/pages/docs/upgrade/index.mdx
website/pages/docs/upgrade/upgrade-specific.mdx
website/pages/intro/index.mdx
website/pages/intro/use-cases.mdx
website/pages/use-cases/non-containerized-application-orchestration.jsx

- ✏️ spelling errors
- 💁 preferred case fixes for brand names
- Qemu -> QEMU
- Containerd -> containerd
- Systemd -> systemd
- 🙅 exclamation points.

Small website updates

---

website/pages/downloads/index.jsx

docs: publish v1.0.0-rc1

---

CHANGELOG.md

removes bugfix from prerelease version from GA changelog

remove prerelease bug fix from GA changelog

---

ui/app/serializers/application.js
ui/app/serializers/scale-event.js
ui/tests/unit/serializers/scale-event-test.js

UI: Guard against null Meta on scale events

---

website/data/alert-banner.js

docs: add an announcement for 1.0

---

CHANGELOG.md

Reported by https://github.com/hashicorp/nomad/pull/8996/files#r538702174

docs: fix cpu comment for 10->1 to 20->1

---

client/allocrunner/taskrunner/stats_hook.go
command/agent/pprof/pprof.go
drivers/docker/docklog/docker_logger.go
drivers/docker/driver.go
drivers/docker/driver_pre09.go
drivers/docker/handle.go
drivers/docker/network.go
drivers/docker/stats.go
drivers/shared/executor/exec_utils.go
e2e/cli/command/environment.go
e2e/execagent/execagent.go
helper/testtask/testtask.go
jobspec2/types.variables.go
nomad/structs/network.go
nomad/structs/structs.go
plugins/drivers/testutils/testing.go
scheduler/rank.go

This doesn't enable staticcheck as a linter yet; just applies some suggestions.

Apply some suggested fixes from staticcheck

---

website/pages/home/index.jsx

Can we have a line break before "Learn why users...." Thanks

Highlight "alternative to Kubernetes"

---

GNUmakefile

compile release on s390x architecture

---

.circleci/config.yml

As suggested in the CircleCI documentation:
https://circleci.com/docs/2.0/yarn/

UI: Change to use frozen lockfile for UI in CI

---

CHANGELOG.md
website/data/alert-banner.js
website/data/version.js

- Update release date in changelog
- Update download version
- Update alert banner to not be so specific

docs: release v1.0.1

---

website/pages/docs/configuration/index.mdx

Fixes https://github.com/hashicorp/nomad/issues/8156

docs: clarify which address configurations can include ports

---

website/pages/docs/commands/operator/keygen.mdx
website/pages/docs/configuration/server.mdx

Fixes https://github.com/hashicorp/nomad/issues/8032

docs: describe gossip encryption encoding requirements

---

website/pages/docs/configuration/audit.mdx
website/pages/docs/configuration/index.mdx
website/pages/docs/configuration/tls.mdx

Fixes https://github.com/hashicorp/nomad/issues/7400 and https://github.com/hashicorp/nomad/issues/6700

docs: document SIGHUP handling behavior

---

website/pages/docs/configuration/index.mdx

Fixes https://github.com/hashicorp/nomad/issues/9382
Although this behavior is unfortunate, we want to document the existing
behavior rather than break backwards compatibility.

docs: clarify behavior of plugin block merging

---

README.md
contributing/README.md

* Add alt text to Nomad logo
* Hoist Resources
* Use description from nomadproject.io
* Getting Started -> Quick Start
* Add production cluster section to Quick Start
* Remove "Who Uses Nomad"
* Move Contributing to contributing/README.md
* Add reference to Nomad Enterprise

README: Align with Consul README

---

website/pages/api-docs/client.mdx
website/pages/api-docs/nodes.mdx

docs: added examples of device responses to api docs

---

website/pages/api-docs/jobs.mdx

- Document job register payload
- Update job versions job output

add job register preservecounts param, update job versions response

---

website/pages/docs/job-specification/lifecycle.mdx

docs: more documentation for lifecycle stanza

---

website/pages/api-docs/jobs.mdx

docs: added lifecycle example to JSON Jobs API docs

---

website/pages/docs/nomad-vs-kubernetes/index.mdx

Fixed typo in index.mdx

---

website/pages/docs/autoscaling/policy.mdx

https://github.com/hashicorp/nomad-autoscaler/pull/313 added the ability to define multiple policies per file. This PR splits the example into job and file policy samples.

docs: update file scaling policy docs

---

website/pages/api-docs/[[...page]].jsx
website/pages/docs/[[...page]].jsx
website/pages/intro/[[...page]].jsx

Missed this in the recent mdx remote upgrade PR, so sorry! Going to quick merge this to fix.

hotfix: fix 'edit this page' links

---

CHANGELOG.md

For https://github.com/hashicorp/nomad/issues/9050 and https://github.com/hashicorp/nomad/pull/9349

changelog: add entry for GH-9050

---

CHANGELOG.md

changelogfmt

---

website/data/version.js

bump website version

---

website/content/docs/drivers/external/containerd.mdx

https://github.com/Roblox/nomad-driver-containerd/pull/60

containerd-driver: Update FSIsolation from none to image.

---

website/content/api-docs/events.mdx

rm invalid duplicate for event type

remove invalid duplicate

---

e2e/e2eutil/allocs.go
e2e/e2eutil/cli.go
e2e/events/events.go
e2e/namespaces/namespaces.go
e2e/volumes/volumes.go

Deflake some e2e tests.  Best reviewed commit-by-commit.
Closes 9866

Deflake some e2e tests

---

website/package-lock.json
website/package.json
website/pages/style.css

Routine dependency update - this one notably will fix an issue with line breaks on lines with links in Chrome due to a chrome bug with hyphenation.

Website: update dependencies

---

ui/app/templates/components/primary-metric.hbs
ui/app/templates/components/topo-viz/datacenter.hbs
ui/app/templates/components/topo-viz/node.hbs
ui/app/templates/topology.hbs
ui/mirage/factories/job.js
ui/tests/integration/components/topo-viz/datacenter-test.js
ui/tests/integration/components/topo-viz/node-test.js

The case of conformant casing.

UI: Use MHz instead of Mhz throughout

---

CHANGELOG.md
website/content/docs/drivers/external/containerd.mdx
website/content/docs/drivers/external/rkt.mdx
website/content/docs/drivers/podman.mdx
website/content/docs/job-specification/service.mdx

Includes the changelog entry for removing mbits from consideration by quotas.

docs: remove mbits examples

---

website/content/partials/envvars.mdx
website/pages/community/index.jsx
website/pages/not-found/index.jsx

Replace &lsquo; and &apos; with '

---

website/content/docs/job-specification/hcl2/functions/collection/setproduct.mdx

A follow-up to hashicorp/terraform#27692

Correct the spelling of heirarchical/hierarchical

---

website/package-lock.json
website/package.json
website/pages/community/index.jsx
website/pages/community/style.css
website/pages/style.css

🔍 [Preview](https://nomad-esi6dgwse.vercel.app/community)
Aligns the `/community` page with other HashiCorp project sites.

website: update community page to be consistent with other projects

---

e2e/periodic/input/simple.nomad
e2e/periodic/periodic.go

e2e: account for race condition in periodic dispatch test.

---

CHANGELOG.md

Trying to slip these in in time 😅

CHANGELOG entries for some 1.0.4 UI bug fixes

---

website/content/docs/commands/ui.mdx

Docs for `nomad ui -login`. Related to https://github.com/hashicorp/nomad/pull/10066 and the implementation of https://github.com/hashicorp/nomad/issues/6054
I'm making this PR to a branch `f-nomad-ui-login` so that I can make a number of incremental PRs as I work through this small project.

docs: 'nomad ui -login' command

---

website/content/docs/autoscaling/plugins/target.mdx

closes https://github.com/hashicorp/nomad-autoscaler/issues/372

docs: add Nomad Autoscaler GPC MIG target plugin detail.

---

website/content/docs/autoscaling/agent.mdx

Documentation related to https://github.com/hashicorp/nomad-autoscaler/pull/390

docs: expand Autoscaler SIGHUP documentation

---

website/content/docs/autoscaling/plugins/target.mdx

Marking this as WIP until the feature is released, but the content is ready for review.

document Autoscaler `node_drain_ignore_system_jobs` configuration

---

website/content/docs/drivers/podman.mdx

remove outdated podman limitations

remove v1-v2 varlink references

---

website/content/docs/internals/security.mdx

docs: remove stray mention that namespaces are ent

---

CHANGELOG.md

Changelog entry for https://github.com/hashicorp/nomad/pull/9885

docs: changelog entry for extra docker labels

---

website/content/docs/install/production/requirements.mdx

Fixes https://github.com/hashicorp/nomad/issues/10050

docs: required capabilities on Linux

---

website/content/api-docs/jobs.mdx

This is maybe a more realistic job that someone would actually submit
via the API.
It's also been updated to use group network and service definitions.

docs: Update sample JSON in Create Job API

---

CHANGELOG.md

As per https://github.com/hashicorp/nomad/pull/10130#issuecomment-794044718

changelog: fix position of entry

---

ui/app/models/service.js
ui/app/templates/allocations/allocation/index.hbs
ui/mirage/factories/service.js
ui/tests/acceptance/allocation-detail-test.js
ui/tests/pages/allocations/detail.js

Adds On Update value to services table

add on update to services table in allocation details

---

client/allocrunner/taskrunner/envoy_bootstrap_hook.go

Sidecar tasks are failing to start when using interpolation in service definition
Fixes #10139

fixed service interpolation for sidecar tasks

---

api/operator.go
command/agent/agent.go
command/agent/command.go
command/agent/config.go
command/agent/config_parse_test.go
command/agent/testdata/basic.hcl
command/agent/testdata/basic.json
command/license.go
command/license_put.go
nomad/config.go
nomad/server.go
nomad/server_setup_oss.go
vendor/github.com/hashicorp/nomad/api/operator.go
website/content/api-docs/operator/license.mdx
website/content/docs/commands/license/put.mdx
website/content/docs/configuration/server.mdx

Server configuration, docs, command updates for enterprise licensing changes to support loading a file license

configuration and oss components for licensing

---

website/content/docs/drivers/external/containerd.mdx

Update containerd task driver docs.

---

website/content/docs/autoscaling/internals/index.mdx
website/content/docs/autoscaling/internals/plugins/apm.mdx
website/content/docs/autoscaling/internals/plugins/base.mdx
website/content/docs/autoscaling/internals/plugins/index.mdx
website/content/docs/autoscaling/internals/plugins/strategy.mdx
website/content/docs/autoscaling/internals/plugins/target.mdx
website/content/docs/autoscaling/plugins/external/index.mdx
website/content/docs/autoscaling/plugins/index.mdx
website/content/docs/autoscaling/plugins/target.mdx
website/data/docs-navigation.js

resolves https://github.com/hashicorp/nomad-autoscaler/issues/409

autoscaler plugin docs

---

website/content/docs/autoscaling/internals/index.mdx
website/content/docs/autoscaling/internals/plugins/apm.mdx
website/content/docs/autoscaling/internals/plugins/base.mdx
website/content/docs/autoscaling/internals/plugins/index.mdx
website/content/docs/autoscaling/internals/plugins/strategy.mdx
website/content/docs/autoscaling/internals/plugins/target.mdx
website/content/docs/autoscaling/plugins/external/index.mdx
website/content/docs/autoscaling/plugins/index.mdx
website/content/docs/autoscaling/plugins/target.mdx
website/data/docs-navigation.js

merge #10125 onto `stable-website` (already merged into `main`)

Docs: update stable website with autoscaler plugins docs

---

command/agent/csi_endpoint.go

This got missed in #10206 because our unit tests can't go end-to-end, so we'd get the error in both cases. I discovered we were hitting the wrong endpoint during E2E testing.
This PR targets `csi-create-volume`

CSI: HTTP delete endpoint should call Delete RPC, not Deregister

---

api/csi.go
vendor/github.com/hashicorp/nomad/api/csi.go

A minor fit-and-finish PR for CSI.

CSI: ensure api package has godoc documentation

---

website/content/docs/autoscaling/internals/node-selector-strategy.mdx
website/content/docs/autoscaling/plugins/target.mdx
website/data/docs-nav-data.json

related: https://github.com/hashicorp/nomad-autoscaler/pull/435

docs: add autoscaling docs to detail node selector strategy feat.

---

vendor/github.com/hashicorp/nomad/api/csi.go

Fixes current lint failure on main.

deps: run make sync to sync vendor dir.

---

api/csi.go
client/csi_endpoint.go
client/csi_endpoint_test.go
client/structs/csi.go
command/agent/csi_endpoint.go
command/agent/csi_endpoint_test.go
command/agent/http.go
command/commands.go
command/volume_snapshot_create.go
command/volume_snapshot_delete.go
command/volume_snapshot_list.go
nomad/client_csi_endpoint.go
nomad/client_csi_endpoint_test.go
nomad/csi_endpoint.go
nomad/csi_endpoint_test.go
nomad/structs/csi.go
plugins/csi/client.go
plugins/csi/client_test.go
plugins/csi/fake/client.go
plugins/csi/plugin.go
plugins/csi/testing/client.go
vendor/github.com/hashicorp/nomad/api/csi.go
website/content/docs/commands/volume/snapshot-create.mdx
website/content/docs/commands/volume/snapshot-delete.mdx
website/content/docs/commands/volume/snapshot-list.mdx
website/data/docs-nav-data.json

CSI volume snapshot workflow for #8212. The resize workflows will be implemented in a separate PR.

CSI: volume snapshot

---

website/content/docs/autoscaling/agent.mdx
website/content/docs/autoscaling/cli.mdx
website/content/docs/autoscaling/internals/node-selector-strategy.mdx
website/content/docs/autoscaling/plugins/strategy.mdx
website/content/docs/autoscaling/plugins/target.mdx
website/content/docs/autoscaling/policy.mdx
website/data/docs-nav-data.json

`git diff main..HEAD website/content/docs/autoscaling/` tells me I `cherry-picked` all changes. 
The only files modified in this PR are for ` website/content/docs/autoscaling/*`

website: updates for Nomad Autoscaler v0.3.1

---

contributing/README.md

If you use too new of a `buf` you will hit #10293
^ please review the linked issue as well and let me know if it needs some more detail.

docs: specify buf v0.30.1

---

website/pages/home/index.jsx

🔍 [Preview](https://nomad-57nc0sel8-hashicorp.vercel.app)
Adds Internet Archive customer testimonial, removes Imgix (for brevity) and removes two out-dated customer logos.

Update homepage testimonial card, customer logos

---

website/content/api-docs/volumes.mdx

Preview: https://nomad-pgwykrxlk-hashicorp.vercel.app/api-docs/volumes

CSI: API docs for create and snapshot workflows

---

demo/csi/hostpath/hostpath.hcl

hclfmt hostpath.hcl

---

CHANGELOG.md

changelog: add entry for #10253

---

scheduler/feasible.go
scheduler/feasible_test.go
scheduler/rank.go
scheduler/rank_test.go

added host network interpolation

---

client/allocrunner/taskrunner/task_runner.go

This partially addresses https://github.com/hashicorp/nomad/issues/9073 - where non-measured metrics don't get reported as zero.
I haven't updated the CPU reporting mechanism.  It's tricker, as the [measured metrics](https://github.com/hashicorp/nomad/blob/v1.0.4/drivers/docker/util/stats_posix.go#L14) doesn't directly translate to [set fields](https://github.com/hashicorp/nomad/blob/v1.0.4/drivers/docker/util/stats_posix.go#L28-L44).

memory metrics: only publish measured metrics

---

website/content/docs/drivers/external/containerd.mdx

- image_pull_timeout
- pids_limit
- sysctl

Update containerd task driver options.

---

e2e/consul/on_update.go

```
→ NOMAD_E2E=1 go test -v -count=1 . -run 'TestE2E/Consul/\*consul\.OnUpdateChecksTest/TestOnUpdate_CheckRestart'
=== RUN   TestE2E/Consul
=== RUN   TestE2E/Consul/*consul.OnUpdateChecksTest
=== RUN   TestE2E/Consul/*consul.OnUpdateChecksTest/TestOnUpdate_CheckRestart
=== RUN   TestE2E/ConsulTemplate
--- PASS: TestE2E (39.94s)
--- PASS: TestE2E/Consul (39.86s)
--- PASS: TestE2E/Consul/*consul.OnUpdateChecksTest (39.45s)
--- PASS: TestE2E/Consul/*consul.OnUpdateChecksTest/TestOnUpdate_CheckRestart (39.13s)
--- PASS: TestE2E/ConsulTemplate (0.08s)
PASS
ok      github.com/hashicorp/nomad/e2e  40.453s
```
Since this was a flake I ran again with `-count=10` with the same result

remove second deploy that did not have anything to do with the test

---

website/content/docs/autoscaling/plugins/target.mdx

docs: update autoscaler target plugins to include datacenter field.

---

website/content/docs/partnerships.mdx
website/data/docs-nav-data.json

🔍 [Preview](https://nomad-gqom94sd2-hashicorp.vercel.app/docs/partnerships)
Stubs in partnerships page for @changli0617 to fill with content.

website: add partnerships page

---

website/content/docs/partnerships.mdx

walkaround for resizing the image

Small typo fixes

---

command/quota_apply.go
command/quota_init.go
command/quota_status.go

These files got updated in private Enterprise repo but live on OSS.

Port OSS changes for Enterprise Quota accounting

---

CHANGELOG.md

😬 I have many PRs to changelog!  Sorry!

batch update changelog

---

api/operator.go
command/agent/operator_endpoint.go
command/agent/operator_endpoint_test.go
vendor/github.com/hashicorp/nomad/api/operator.go

🤦 Missed the api<->structs conversion here. Updated the docs but not the implementation.

api: actually set MemoryOversubscriptionEnabled

---

website/data/alert-banner.js

[🔍 Preview](https://nomad-bf5ybj9fl-hashicorp.vercel.app/)

Updates website banner for Nomad 1.1

---

CHANGELOG.md
website/content/docs/job-specification/sidecar_service.mdx

changelog and docs to go with https://github.com/hashicorp/nomad/pull/10531

documentation for `disable_default_tcp_check`

---

e2e/oversubscription/oversubscription.go

Enable memory oversubscription for the oversubscription tests.

e2e: enable memory oversubscription

---

website/redirects.js

@BRKalow just need you to verify this redirect works on the deploy preview
cc @mikenomitch

website: set up /trial redirection

---

ui/app/services/sockets.js

Fix exec not working for another region

---

website/content/docs/drivers/remote/ecs.mdx
website/content/docs/drivers/remote/index.mdx
website/content/docs/internals/plugins/task-drivers.mdx
website/data/docs-nav-data.json

Fixes #10505
First pass at docs for remote task driver. A proper guide for the demo as well as a guide for developing remote task drivers would definitely be helpful, but I'd like to get *something* up ASAP.

Remote Task Driver docs

---

website/data/alert-banner.js

Adds info for upcoming HashiConf to the website's `<AlertBanner />`

[Website] Add HashiConf alert banner data

---

CHANGELOG.md

docs: run changelogfmt

---

website/pages/downloads/index.jsx

TODO: Update docs on how merchandising slots work. Will follow up in another PR.

Remove 1.1.0 RC merchandising

---

website/content/docs/drivers/remote/ecs.mdx

Fixed broken links for the remote task driver ECS page

docs: fixes broken links

---

website/content/docs/job-specification/hcl2/locals.mdx

discuss related question: https://discuss.hashicorp.com/t/hcl2-is-it-me-or-is-the-example-wrong/24628
related issue: https://github.com/hashicorp/nomad/issues/9522

docs: fix jobspec hcl2 locals example.

---

website/content/docs/enterprise/license/faq.mdx
website/content/docs/enterprise/license/index.mdx
website/data/docs-nav-data.json

- Reorganized the Nomad enterprise section
- Added an FAQ pertaining to the Nomad 1.1.0 license changes

docs: added license faq

---

scheduler/reconcile_test.go

The reconciler has some complicated behavior when there are already running
allocations from a previous version of the job that we want to keep, as
happens during a rollback. Document this behavior with a test.
This commit is a cherry-pick from https://github.com/hashicorp/nomad-enterprise/commit/8f158118b2b20dade5b0f06683c9b4b5deed7678

scheduler: test for reconciler's in-place rollback behavior

---

website/content/docs/commands/volume/snapshot-create.mdx
website/content/docs/commands/volume/snapshot-delete.mdx
website/content/docs/commands/volume/snapshot-list.mdx

Preview links:
https://nomad-iu60tj8ch-hashicorp.vercel.app/docs/commands/volume/snapshot-create
https://nomad-iu60tj8ch-hashicorp.vercel.app/docs/commands/volume/snapshot-delete
https://nomad-iu60tj8ch-hashicorp.vercel.app/docs/commands/volume/snapshot-list

docs: fix broken links in `nomad csi snapshot` commands

---

website/data/alert-banner.js

---
Updates the alert banner data for HashiConf europe going live.

chore: updates alert-banner — hashiconf 

---

.circleci/config.yml
CHANGELOG.md
contributing/README.md
scripts/release/mac-remote-build
scripts/vagrant-linux-priv-go.sh

1.16.5 contains some security fixes for zip that are notable to get.

golang: update to 1.16.5

---

CHANGELOG.md
website/content/docs/commands/deployment/status.mdx
website/content/docs/commands/job/run.mdx

Updates the deployment status and job run docs

docs: add deployment monitor to docs, changelog

---

nomad/volumewatcher/volumes_watcher_test.go

Fixes two types of data races found in the tests.
Fix 1 wraps calling the watchers map in a lock.
<details>
<summary>Data race stack trace 1 example</summary>
```
==================
Write at 0x00c00026a398 by goroutine 45:
github.com/hashicorp/nomad/nomad/state.(*StateStore).upsertAllocsImpl()
/Users/jrasell/go/src/github.com/hashicorp/nomad/nomad/state/state_store.go:3279 +0x2c4
github.com/hashicorp/nomad/nomad/state.(*StateStore).UpsertAllocs()
/Users/jrasell/go/src/github.com/hashicorp/nomad/nomad/state/state_store.go:3237 +0x139
github.com/hashicorp/nomad/nomad/drainer.TestDrainingJobWatcher_DrainJobs()
/Users/jrasell/go/src/github.com/hashicorp/nomad/nomad/drainer/watch_jobs_test.go:192 +0x1246
testing.tRunner() …
```

volumewatcher: fix test data race.

---

plugins/drivers/testutils/testing_test.go

Use an atomic value to avoid potential race condition.
<details>
<summary>Data race stack trace</summary>
```
==================
Write at 0x00c000126128 by goroutine 21:
github.com/hashicorp/nomad/plugins/drivers/testutils.TestBaseDriver_Fingerprint.func1.1()
/Users/jrasell/go/src/github.com/hashicorp/nomad/plugins/drivers/testutils/testing_test.go:65 +0x124
Previous read at 0x00c000126128 by goroutine 32:
github.com/hashicorp/nomad/plugins/drivers/testutils.TestBaseDriver_Fingerprint()
/Users/jrasell/go/src/github.com/hashicorp/nomad/plugins/drivers/testutils/testing_test.go:94 +0x9cb
testing.tRunner()
/Users/jrasell/.gvm/gos/go1.16.4/src/testing/testing.go:1193 +0x202
Goroutine 21 (running) created at:
github.com/hashicorp/nomad/plugins/drivers/testutils.TestBaseDriver …
```

plugins: fix test data race.

---

website/content/docs/job-specification/csi_plugin.mdx

Closes https://github.com/hashicorp/nomad/issues/10793
* add some more context to the recommendations
* add recommendations around per-AZ `plugin_id`

docs: improve CSI deployment recommendations

---

command/system_gc.go
command/system_gc_test.go
command/system_reconcile_summaries.go
command/system_reconcile_summaries_test.go

closes #10820 
Tests have been modified to ensure the flag usage is tested.

cli: fixed system commands so they correctly use passed flags.

---

CHANGELOG.md

Also fixes a syntax issue on main which is why I raised it as a separate PR.

changelog: add entry for #10822

---

client/allocrunner/groupservice_hook.go

client: fix logline in group shutdown hook

---

website/content/docs/upgrade/index.mdx

Adds caveat about federated regions needing the authoritative region to be upgraded for some features.

[docs] Adds federation caveat to upgrade guide

---

website/package-lock.json
website/package.json
website/pages/style.css

Fix up the broken tab styles on the downloads page

website: add back tab styles

---

website/content/docs/configuration/audit.mdx

Adds documentation on "mode" in the sink config.

Adds documentation for file mode to sink docs

---

website/content/docs/drivers/external/index.mdx
website/content/docs/drivers/external/rookout.mdx

I have added documentation for the Rookout driver.
The driver can be found at https://github.com/Rookout/rookout-nomad-driver

Rookout driver docs

---

website/package-lock.json
website/package.json

Updates `react-consent-manager` to latest. See [RFC MKTG-036](https://docs.google.com/document/d/12UIDBgpR6lilkFrxQFr7i1zTxCm04szAZkGKSSlgRkI/edit) for context.

website: update consent manager

---

website/content/docs/drivers/external/rookout.mdx

Hey @jrasell, I have done a few minor changes to the Rookout docs, I'd love to get your review.

Some Rookout docs tweaks

---

.changelog/11083.txt
.circleci/config.yml
contributing/README.md
scripts/release/mac-remote-build
scripts/vagrant-linux-priv-go.sh

Should follow up to upgrade line to 1.17 shortly afterwards.

update golang to 1.16.7

---

GNUmakefile
website/data/version.js

Also update LAST_RELEASE in makefile to 1.1.5

website: update to 1.1.5

---

website/data/alert-banner.js

[:mag: Preview link](https://nomad-git-nqupdate-alert-banner-hcg2021-hashicorp.vercel.app/)
---
This PR updates the alert banner for HashiConf Global 2021.

Update alert banner for HashiConf Global 2021

---

demo/csi/README.md
demo/csi/hostpath/README.md

Also start tagging authors to ease support by third parties.

docs: note demos/csi is unsupported

---

demo/csi/portworx-csi-plugin/README.md
demo/csi/portworx-csi-plugin/portworx-csi-plugin.hcl
demo/csi/portworx-csi-plugin/portworx-volume.hcl

Add Portworx CSI Driver example

---

website/content/docs/configuration/server.mdx
website/content/docs/job-specification/job.mdx
website/content/docs/schedulers.mdx

docs: add Nomad version requirement note for sysbatch

---

nomad/autopilot_test.go

The fix seems to be related to the pointer comparison and swapping we
did around killing a non-leader. I actually can't quite explain it, but
when comparing against Consul's version of this test I noticed they used
the slice index to track the killed server instead of pointer swapping.
As soon as I switched to slice index tracking I could no longer
reproduce the failure.
In addition:
- Tested membership counts on all servers instead of just 1 for added
correctness.
- Stopped testing raft v1 because it is unsupported.

test: fix flaky TestAutopilot_CleanupDeadServer

---

.changelog/11249.txt
go.mod

deps: update hashicorp/go-discover.

---

.changelog/11283.txt
go.mod
go.sum

deps: update hashicorp/go-hclog to v1.0.0

---

.changelog/11411.txt
command/acl_bootstrap.go
website/content/docs/commands/acl/bootstrap.mdx

cli: add json and template flag opts to acl bootstrap command.

---

website/package-lock.json
website/package.json

This is a PR opened from the GH CLI﻿

chore: react-subnav

---

website/content/docs/job-specification/gateway.mdx

i believe mesh should be included in this statement was omitted.

exactly one of ingress, terminating, or mesh must be configured

---

client/client.go
nomad/structs/structs.go

client: emit max_memory metric

---

.changelog/11132.txt
.changelog/11323.txt
.changelog/11325.txt
.changelog/11490.txt

A batch of changelog entries for community-submitted and dependency PRs I've merged today: #11132 #11323 #11325 #11490

changelog batch

---

website/content/docs/autoscaling/plugins/apm/datadog.mdx
website/content/docs/autoscaling/plugins/apm/prometheus.mdx

Document the new features added by https://github.com/hashicorp/nomad-autoscaler/pull/522, https://github.com/hashicorp/nomad-autoscaler/pull/547, and https://github.com/hashicorp/nomad-autoscaler/pull/548

docs: document new Prometheus configuration for the Autoscaler APM plugin

---

website/content/docs/job-specification/parameterized.mdx
website/content/docs/job-specification/periodic.mdx

mention `sysbatch` in addition to `batch`

mention `sysbatch` in addition to `batch`

---

.github/workflows/backport.yml

Fixes https://github.com/hashicorp/nomad/runs/4437401518?check_suite_focus=true#step:4:21

fix: backport release branch target

---

website/content/docs/operations/monitoring-nomad.mdx

Optional updates for your consideration on #11623.

touchups for consistency; reduce colons.

---

ui/app/templates/components/global-header.hbs
ui/mirage/factories/agent.js
ui/mirage/scenarios/default.js
ui/tests/acceptance/global-header-test.js
ui/tests/pages/layout.js

Adding acceptance tests and mirage setup for product links.

UI: Add tests for prodcut links

---

website/next.config.js
website/package-lock.json
website/package.json
website/pages/api-docs/[[...page]].jsx
website/pages/docs/[[...page]].jsx
website/pages/intro/[[...page]].jsx
website/pages/plugins/[[...page]].tsx
website/pages/tools/[[...page]].tsx

https://nomad-git-kevin-versioned-docs-hashicorp.vercel.app/api-docs

feat: versioned docs

---

.changelog/11555.txt
.changelog/11557.txt
.changelog/11687.txt

Adding missing changelog entries for #11555, #11557, and #11687

changelog: add entries for #11555, #11557, and #11687

---

website/content/tools/autoscaling/internals/index.mdx

Hi!
There's a typo in the URL to /internal/checks, leading to a 404.
Thanks,

Fix 'check calculations' link

---

website/content/docs/upgrade/upgrade-specific.mdx

closes https://github.com/hashicorp/nomad/issues/11681

docs: add 1.2.0 HCLv2 strict parsing upgrade note.

---

nomad/structs/structs.go
scheduler/reconcile.go

We implemented this as a companion to #10236 for metrics visibility into rescheduler decisions and limits.
I do not know whether this meets the quality standard to be upstreamed.  If you have ideas on how to make this upstream worthy, I'd be willing to make changes.  I was unable to find a metrics loop that was more appropriate than this with the access to the required alloc info.

Emit metrics on reschedule later decisions as nomad.client.allocs.reschedule

---

.changelog/11783.txt

Forgot to ask for a changelog for https://github.com/hashicorp/nomad/pull/11783

docs: changelog for PR #11783

---

.changelog/11848.txt

changelog: add entry for #11848

---

CHANGELOG.md

For some reason `make changelog` didn't pick this item, so I'm adding it manually to `CHANGELOG.md`

changelog: manually add entry for #11793

---

website/data/version.js

Note: I'm waiting on packaging to be fixed before merging this.

update download to Nomad v1.2.5

---

website/content/api-docs/operator/scheduler.mdx

not sure about the exact version this was introduced

api-docs:  add SysBatchSchedulerEnabled docs

---

.changelog/11980.txt
ui/app/templates/components/task-row.hbs

correct task row memory unit 
Closes https://github.com/hashicorp/nomad/issues/10499

correct task row memory unit 

---

.changelog/12036.txt
.changelog/12037.txt
.changelog/12038.txt
.changelog/12039.txt
CHANGELOG.md
GNUmakefile
acl/policy.go
acl/policy_test.go
client/allocdir/alloc_dir.go
client/allocdir/alloc_dir_test.go
client/allocrunner/taskrunner/getter/getter.go
command/agent/agent_endpoint.go
command/agent/http.go
command/agent/http_test.go
command/agent/job_endpoint.go
command/agent/job_endpoint_test.go
helper/escapingfs/escapes.go
helper/escapingfs/escapes_test.go
jobspec2/parse.go
jobspec2/parse_test.go
nomad/structs/structs.go
scheduler/spread.go
scheduler/spread_test.go

I'm not sure why the commits for the `1.2.5` are showing in the history, but their changes are already in `main`.

Merge release 1.2.6 branch

---

.changelog/12040.txt

changelog: add entry for #12040

---

client/allocrunner/csi_hook.go

In PR #11892 we updated the `csi_hook` to unmount the volume locally
via the CSI node RPCs before releasing the claim from the server. The
timer for this hook was initialized with the retry time, forcing us to
wait 1s before making the first unmount RPC calls.
Use the new helper for timers to ensure we clean up the timer nicely.

CSI: don't wait to fire initial unmount RPC

---

website/content/api-docs/agent.mdx

Corrected urls that were likely copypasta. 🤭

Fixed scheduler config examples

---

website/content/docs/commands/plugin/index.mdx

Fixes https://github.com/hashicorp/nomad/issues/10305

docs: clarify that plugin commands are for CSI only

---

.changelog/12154.txt
command/plugin_status_csi.go

A minor fit-and-finish issue in the CLI.

CSI: sort capabilities in `plugin status`

---

e2e/csi/csi.go

The AWS EBS plugin appears to use the name field of the volume as an
idempotency token that persists across the entire AWS account, not
just the plugin lifespan.
Also fix the regex for the volume ID, which was originally taken from
the job ID regex but isn't actually the same. This hasn't failed tests
for us because we've always passed in the same volume ID.

e2e: use UUID for CSI idempotency token

---

website/content/tools/index.mdx

Adding openapi and caravan to tools page.

Add openapi and caravan to tools page

---

website/content/docs/drivers/docker.mdx
website/content/docs/job-specification/network.mdx

Elaborate on issues when using group-bridge networking on systems with firewalld enabled, as per #12199.

docs: elaborate on networking issues with firewalld

---

website/content/api-docs/acl-tokens.mdx
website/content/api-docs/allocations.mdx
website/content/api-docs/deployments.mdx
website/content/api-docs/evaluations.mdx
website/content/api-docs/index.mdx
website/content/api-docs/jobs.mdx
website/content/api-docs/volumes.mdx

Provide documentation for the new filtering, sorting, and pagination features for the Nomad API. Filtering documentation adapted from [Consul](https://www.consul.io/api-docs/features/filtering).
Documentation for `reverse` provided in https://github.com/hashicorp/nomad/pull/12244

docs: initial docs for the new API features

---

nomad/state/state_store_test.go

These tests were left out during the migration of namespaces from ENT to OSS. I made a few small tweaks during the move:
1. Don't override the `testify` package
2. Use `require` instead of `assert`
3. Use `NoError` instead of `Nil`
4. Add `ci.Parallel(t)`

tests: move state store namespace tests from ENT

---

client/serviceregistration/nsd/doc.go
client/serviceregistration/nsd/nsd.go
client/serviceregistration/nsd/nsd_test.go

related https://github.com/hashicorp/team-nomad/issues/266

client: add Nomad service registration implementation.

---

nomad/node_endpoint.go
nomad/node_endpoint_test.go

When a node fails its heart beating a number of actions are taken
to ensure state is cleaned. Service registrations a loosely tied
to nodes, therefore we should remove these from state when a node
is considered terminally down.
closes https://github.com/hashicorp/team-nomad/issues/329

core: remove node service registrations when node is down.

---

nomad/leader.go
nomad/leader_test.go

Raft v3 introduced a new API for adding and removing peers that takes
the peer ID instead of the address.
Prior to this change, Nomad would use the remote peer Raft version for
deciding which API to use, but this would not work in the scenario where
a Raft v3 server tries to remove a Raft v2 server; the code running uses
v3 so it's unable to call the v2 API.
This change uses the Raft version of the server running the code to
decide which API to use. If the remote peer is a Raft v2, it uses the
server address as the ID.

core: use the new Raft API when removing peers

---

.changelog/12388.txt

For https://github.com/hashicorp/nomad/pull/12388

docs: changelog entry

---

ui/app/components/evaluation-sidebar/detail.hbs
ui/app/machines/evaluations.js

F UI/evaluation detail sidebar rel evals

---

drivers/docker/driver_unix_test.go

Not actually sure this fixes the flaky tests, but seems like it could be related

tests: create fresh harness for each docker dns test

---

nomad/service_registration_endpoint.go
nomad/service_registration_endpoint_test.go

In the same manner as the delete RPC, the list and read service
registration endpoints can be called either by external operators
or Nomad nodes. The latter occurs when a template is being
rendered which includes Nomad API template funcs. In this case,
the auth token is looked up as the node secret ID for auth.
This doesn't change the behaviour on the wildcard list endpoint
which I don't believe will ever be called via templates. If this
changes we can 100% look into modifying this, however, this
work covers the core use case.

service-disco: add mixed auth to list and read RPC endpoints.

---

command/service_delete_test.go

I believe the service delete test was suffering due to the eventual consistency between job registration, eval completion, allocation placement, allocation start, and service registration.
I have therefore changed the test to upsert the service registrations directly into state, avoiding this while still allowing the test to serve its purpose of testing the delete CLI. A nice secondary outcome is that it now also tests cross-namespace deletion as the mock generates two service registrations, within different namespaces.

cli: fixup service test delete by using atomic actions.

---

drivers/exec/driver_test.go

Fixup this test to handle cgroups v2, as well as the :misc: cgroup

exec: fix exec handler test

---

e2e/consultemplate/consultemplate.go

Failure: https://app.circleci.com/pipelines/github/hashicorp/nomad-e2e/472/workflows/0a855d95-b76d-4f88-bd53-a35082b7cce9/jobs/2717
Tested with a full E2E cluster:
```
=== RUN   TestE2E/ConsulTemplate
=== RUN   TestE2E/ConsulTemplate/*consultemplate.ConsulTemplateTest
=== RUN   TestE2E/ConsulTemplate/*consultemplate.ConsulTemplateTest/TestConsulTemplate_NomadServiceLookups
--- PASS: TestE2E (18.95s)
--- PASS: TestE2E/ConsulTemplate (18.95s)
--- PASS: TestE2E/ConsulTemplate/*consultemplate.ConsulTemplateTest (18.94s)
--- PASS: TestE2E/ConsulTemplate/*consultemplate.ConsulTemplateTest/TestConsulTemplate_NomadServiceLookups (18.42s)
PASS
ok  	github.com/hashicorp/nomad/e2e	19.487s
```

e2e: fix eventual consistency failure within consultemplate suite.

---

e2e/oversubscription/oversubscription.go

The oversubscription test expects an output that requires the client
has polled the task for stats at least once. Wait long enough to
ensure that we've polled the stats before failing the test.

E2E: oversubscription assertion needs to wait for stats

---

client/allocwatcher/alloc_watcher.go
client/client.go
client/rpc.go
client/servers/manager.go
command/agent/agent.go
command/agent/command.go
helper/cluster.go
helper/eof.go
helper/math.go
helper/path.go
helper/pool/pool.go
nomad/blocked_evals.go
nomad/heartbeat.go
nomad/rpc.go
nomad/server.go

Was #7533 
The last bit of consul seems to be the autopilot which is now elsewhere as well.
https://github.com/hashicorp/raft-autopilot

feat: remove dependency to consul/lib

---

.github/workflows/backport.yml

These are the updates done to backport-assistant that I believe need to be updated in order to work to backport to the release branches!

updates for backport-assistant [For CRT main] 

---

jobspec/parse_group.go
jobspec/parse_test.go
jobspec/test-fixtures/basic.hcl

jobspec: add max_client_disconnect to hcl1 group parsing.

---

drivers/docker/docklog/docker_logger_test.go

This test checks for behavior when asking for logs of a docker task
configured with a log driver that does not support streaming logs.
Previously this was using the `gelf` log driver, but it seems that no
longer returns an error as expected. Instead we can just use the 'none'
log driver, which has the desired effect
```
2022-04-19T10:23:19.129-0500 [ERROR] docklog/docker_logger.go:133: log streaming ended with terminal error: error="API error (501): configured logging driver does not support reading"
```
https://docs.docker.com/config/containers/logging/configure/#supported-logging-drivers
Originally added in https://github.com/hashicorp/nomad/pull/5420

ci: fix docker logger not supported test

---

e2e/ui/run.sh

We don't need the absolute path for any of the commands in this script
so long as we `cd` into the source directory path. Doing this removes
the need for weird platform-specific tricks we have to do with
realpath vs GNU realpath.
Cleans up hastily-added logic I added in https://github.com/hashicorp/nomad/pull/12739

E2E: remove platform specific realpath code from UI run script

---

.changelog/12544.txt

Adding changelog note

---

ui/app/styles/components/sidebar.scss
ui/app/styles/utils/z-indices.scss

Sets up a new z-modal z-index and assigns it to the sidebar

---

.changelog/12774.txt
scheduler/util.go

Fixes https://github.com/hashicorp/nomad/issues/12771

CSI: plugin config updates should always be destructive

---

client/allocrunner/taskrunner/plugin_supervisor_hook.go

Fixes https://github.com/hashicorp/nomad/issues/12772
We enforce exactly one plugin supervisor loop by checking whether
`running` is set and returning early. This works but is fairly
subtle. It can briefly result in two goroutines where one quickly
exits before doing any work. Clarify the intent by using
`sync.Once`. The goroutine we've spawned only exits when the entire
task runner is being torn down, and not when the task driver restarts
the workload, so it should never be re-run.
---
There's no behavioral change here, so no changelog.

CSI: enforce one plugin supervisor loop via `sync.Once`

---

GNUmakefile

Also drive-by upgrade `golangci-lint` to a version that can handle go1.18
after:
```shell
➜ make help
Valid targets:
changelog                 Generate changelog from entries
check                     Lint the source code
checkproto                Lint protobuf files
checkscripts              Lint shell scripts
clean                     Remove build artifacts
deps                      Install build and development dependencies
dev                       Build for the current development platform
dev-ui                    Build a dev UI binary
e2e-test                  Run the Nomad e2e test suite
ember-dist                Build the static UI assets from source
generate-all              Generate structs, protobufs, examples
generate-structs          Update generated code
hclfmt …
```

build: add missing help descriptions to makefile

---

.release/ci.hcl

Fixes the current error being seen on main: https://app.circleci.com/pipelines/github/hashicorp/nomad/23633/workflows/a9af16ed-f62f-42c1-953e-2be7fd947846/jobs/252435

release: fix hcl linting error within CI file.

---

website/content/docs/job-specification/parameterized.mdx

Closes https://github.com/hashicorp/nomad/issues/10941

docs: note that already-dispatched jobs cannot be updated

---

website/content/docs/upgrade/upgrade-specific.mdx

Add notice alert to the upgrade page with known issues when using Consul 1.12.0.
[Preview](https://nomad-pndmeu8zu-hashicorp.vercel.app/docs/upgrade/upgrade-specific)

docs: add Consul 1.12.0 upgrade notice

---

.changelog/13065.txt
api/jobs.go

Fixes https://github.com/hashicorp/nomad/issues/12822

api: include Consul token in job revert API

---

0a511bff-5b99-7f9c-602e-3829c3812ea7.json
api/keyring.go
api/keyring_test.go
command/agent/http.go
command/agent/keyring_endpoint.go
command/agent/keyring_endpoint_test.go

Implements the secure variables keyring HTTP API.

keyring HTTP API

---

drivers/docker/driver_linux_test.go
drivers/docker/driver_unix_test.go

cherry-pick https://github.com/hashicorp/nomad/pull/13107/commits and fix conflict
@lgfa29 please double check my git branches - this is going onto `release/1.2.x`, that's the correct thing to do, right?
Closes https://github.com/hashicorp/nomad/pull/13114

tests: minor fixes for some docker tests

---

website/content/tools/index.mdx

Add @robinovitch61 `wander` to our community tool list.

docs: add wander to the community tools page

---

.gitignore

build: git ignore go.work.sum files

---

.changelog/13184.txt
api/consul.go
api/consul_test.go
command/agent/job_endpoint.go
command/agent/job_endpoint_test.go
go.mod
go.sum
jobspec/parse_service.go
jobspec/parse_test.go
jobspec/test-fixtures/tg-service-connect-gateway-ingress.hcl
nomad/consul.go
nomad/job_endpoint_hook_connect.go
nomad/job_endpoint_hook_connect_test.go
nomad/structs/diff.go
nomad/structs/diff_test.go
nomad/structs/services.go
website/content/docs/job-specification/gateway.mdx

exposes TLSMinVersion, TLSMaxVersion, and CipherSuites ingress configurations
through gateway stanza. Closes #12349

adding support for customized ingress tls

---

.changelog/12534.txt

For https://github.com/hashicorp/nomad/pull/12534

changelog entry for #12534

---

website/content/docs/nomad-vs-kubernetes/supplement.mdx

Hi, GitHub employee here. It's actually GitHub with capital H 😄

Update supplement.mdx with the right spelling

---

ui/app/components/secure-variable-form.hbs
ui/app/components/secure-variable-form.js
ui/app/controllers/variables/variable/index.js
ui/app/models/variable.js
ui/app/styles/components/secure-variables.scss
ui/app/templates/variables/variable.hbs
ui/app/templates/variables/variable/edit.hbs
ui/app/templates/variables/variable/index.hbs
ui/app/utils/path-tree.js
ui/mirage/config.js
ui/mirage/scenarios/default.js
ui/tests/acceptance/secure-variables-test.js
ui/tests/integration/components/secure-variable-form-test.js

variable index header and deletion hook

---

command/agent/secure_variable_endpoint.go
command/agent/secure_variable_endpoint_test.go
nomad/core_sched_test.go
nomad/encrypter.go
nomad/fsm.go
nomad/fsm_test.go
nomad/mock/mock.go
nomad/secure_variables_endpoint.go
nomad/state/schema.go
nomad/state/state_store_restore.go
nomad/state/state_store_restore_test.go
nomad/state/state_store_secure_variables.go
nomad/state/state_store_secure_variables_test.go
nomad/structs/secure_variables.go
nomad/structs/secure_variables_test.go

- Make Encrypt function return KeyID
- Split SecureVariable
- Refactor agent secure variable endpoint test

Secure Variables: Seperate Encrypted and Decrypted structs

---

api/contexts/contexts.go
command/agent/search_endpoint_test.go
nomad/search_endpoint.go
nomad/search_endpoint_oss.go
nomad/state/schema.go
nomad/state/state_store_secure_variables.go
nomad/state/state_store_secure_variables_test.go
nomad/structs/search.go

- Add Path only index for SecureVariables
- Add GetSecureVariablesByPrefix; refactor tests
- Add search for SecureVariables

Implement HTTP search API for Variables

---

ui/app/components/variable-paths.hbs
ui/app/utils/path-tree.js
ui/mirage/factories/variable.js
ui/tests/acceptance/secure-variables-test.js
ui/tests/integration/components/variable-paths-test.js

Doesn't handle anything related to sorting (yet); just lists times and namespaces.

Secure Variables: show file metadata on list pages

---

command/alloc_exec.go
command/deployment_status.go
go.mod

See https://github.com/moby/moby/pull/40825

feat: docker/docker/pkg/term has been deprecated in favor of moby/term

---

nomad/structs/structs.go

Fix typo: orthogonal.

---

.changelog/13491.txt
go.mod

closes https://github.com/hashicorp/nomad/issues/13014

deps: update `github.com/hashicorp/go-discover` to latest.

---

website/content/docs/job-specification/hcl2/functions/collection/index-fn.mdx

docs: fixup HCL2 index collection function documentation.

---

ui/app/components/secure-variable-form.hbs
ui/app/components/secure-variable-form/input-group.hbs
ui/app/templates/variables/index.hbs
ui/app/templates/variables/variable/index.hbs
ui/tests/acceptance/secure-variables-test.js

This PR is an acceptance test for the create flow in secure variables.

ui:  acceptance test for create flow in secure variables

---

ui/app/abilities/variable.js
ui/app/templates/variables/variable/index.hbs
ui/tests/acceptance/secure-variables-test.js
ui/tests/unit/abilities/variable-test.js

This PR addresses @tgross's feedback on #13451 to compute the difference for each candidate calculated as `len(path) - len(pattern) + (number of globs in pattern)`.

ui: compute length difference

---

website/content/plugins/devices/community/usb.mdx

:wave: Ive published a new version of the USB driver which adds a new fingerprinted attribute. This PR is to update the documentation to reflect this change

docs: Add 'serial' attribute to usb driver

---

demo/csi/kadalu-csi/README.md
demo/csi/kadalu-csi/cluster.vars
demo/csi/kadalu-csi/controller.nomad
demo/csi/kadalu-csi/nodeplugin.nomad

ref: kadalu/kadalu#817
Signed-off-by: Leela Venkaiah G <leelavg@thoughtexpo.com>

demo/docs: update demo of Kadalu CSI Plugin

---

.changelog/13551.txt
nomad/state/state_store.go
nomad/state/state_store_test.go

state: fix eval list by prefix with * namespace

---

go.mod
go.sum
helper/boltdd/boltdd_test.go

- helpers: fix critical typo 
- we'll just pretend this never happened 
- helpers: use unreachable assertion

boltdd: fixup typo and use unreachable assertion 

---

website/content/docs/upgrade/upgrade-specific.mdx

@lgfa29 do I need to make PRs for each of the release branches as well?

docs: upgrade guide for client max_kill_timeout

---

.changelog/13659.txt

Add missing changelog entry for #13659.

changelog: add entry for #13659

---

command/commands.go
command/var.go
command/var_list.go
command/var_list_test.go
nomad/secure_variables_endpoint.go

Includes the switch from the ApplyFunc to the FilterIterator for managing allowed namespaces and prefix.

SV: CLI: var list command

---

nomad/encrypter_test.go

The test for simulating a key rotation across leader elections was
flaky because we weren't waiting for a leader election and was
checking the server configs rather than raft for which server was
currently the leader. Fixing the flake revealed a bug in the test that
we weren't ensuring the new leader was running its own replication, so
it wouldn't pick up the key material from the previous follower.

keyring: fix flake in replication-after-election test

---

website/content/plugins/drivers/podman.mdx

README diff:
https://github.com/hashicorp/nomad-driver-podman/compare/v0.3.0...v0.4.0#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

docs: update Podman docs to v0.4.0

---

ui/app/components/keyboard-shortcuts-modal.hbs
ui/app/helpers/clean-keycommand.js

Replaces "ArrowUp" with `↑` in the modal, and so forth.

Replace ArrowLeft etc. with an ascii arrow

---

website/content/tools/autoscaling/plugins/target/aws-asg.mdx

Document the work done in https://github.com/hashicorp/nomad-autoscaler/pull/586.

docs: update Autoscaler AWS plugin with new ws_credential_provider config

---

ui/app/templates/evaluations/index.hbs

Reorder the select boxes on evals so namespaces are first

---

ui/app/templates/evaluations.hbs

Add a title to the evals route

---

website/content/docs/job-specification/csi_plugin.mdx
website/content/docs/job-specification/scaling.mdx

Fixing another small inconsistency in the nomad docs.

Fixing placement in docs for scaling

---

go.mod
go.sum

Another attempt at resolving the flakey `TestNomad_BootstrapExpect_NonVoter`

deps: update raft library

---

website/content/docs/concepts/secure-variables.mdx
website/content/docs/concepts/security.mdx
website/content/docs/concepts/workload-identity.mdx
website/content/docs/operations/key-management.mdx
website/content/docs/other-specifications/acl-policy.mdx
website/data/docs-nav-data.json

Includes concept docs for secure variables, concept docs for workload identity, and an operations docs for keyring management.
Tagging just about everyone even peripherally involved with the project for input. Note there are no docs yet for the HTTP API or storage CLI; those will be separate PRs.

docs: concepts for secure variables and workload identity

---

client/serviceregistration/checks/client_test.go

This PR hopefully fixes a race condition of this little test tcp server used by the check observer is making connections for test cases.
I believe the tcp listener would sometimes not listen fast enough, and the checker expecting a successful connection would fail to connect. Instead, we now wait for Listen to return before kicking off a goroutine to handle the Accept

checks: better goroutine handling for test tcp server

---

ui/app/components/secure-variable-form.hbs

This PR closes [13863](https://github.com/hashicorp/nomad/issues/13863).

bug:  link generation for related entity

---

ui/app/serializers/job.js

Closes [13864](https://github.com/hashicorp/nomad/issues/13864)

refact:  update serializer log for prefix and namespace

---

website/content/docs/job-specification/template.mdx

docker and podman don't suck 🤣

template doc typo fix

---

ui/app/controllers/variables/variable/index.js
ui/app/templates/variables/variable/index.hbs

Resolves #13854 
Changes the error type from an in-template error to using the new global error notification state. Is dismissable by default.

Error typed changed to dismissable global toast

---

website/content/tools/autoscaling/agent/dynamic_application_sizing.mdx
website/content/tools/autoscaling/plugins/target/app-sizing-nomad.mdx

Add note that DAS is prometheus only?
Question: Can it also use raw Nomad? If so, I must clarify this!

Add notes about DAS being prometheus only

---

.changelog/14115.txt
ui/app/components/breadcrumbs/job.hbs
ui/app/components/breadcrumbs/job.js

Closes [12819](https://github.com/hashicorp/nomad/issues/12819).

refact: add parent check to boolean

---

command/commands.go
command/var_init.go
go.mod
go.sum

Command to create a skeleton secure variable specification
- Nomad dep: add museli/reflow
- SV CLI: var init

SV CLI: var init

---

website/content/tools/index.mdx

Hello maintainers 👋🏼 
This PR adds a link to the Nomad Pack GitHub Action.

adds link for Nomad-Pack GitHub action

---

ui/app/templates/components/job-page/parameterized-child.hbs
ui/app/templates/components/job-page/periodic-child.hbs
ui/app/templates/components/plugin-allocation-row.hbs
ui/app/templates/topology.hbs

Closes [12764](https://github.com/hashicorp/nomad/issues/12764).

remove unnecessary query parameters in `LinkTo` components

---

client/heartbeatstop.go

Part 1/n of my effort to make agent tests race free.

client: fix race in heartbeat tracker

---

.changelog/13539.txt
CHANGELOG.md

changelog: add missing entry for #13539

---

ui/app/adapters/variable.js

Resolves https://github.com/hashicorp/nomad/issues/14166 and https://github.com/hashicorp/nomad/issues/14167

[ui] Secure Vars: ? instead & for check-and-set param

---

helper/pool/pool.go

Part 5/n of my effort to make agent tests race free. (Prev: #14139)

rpc: fix race in conn last used tracking

---

drivers/java/utils_test.go

added this for https://github.com/hashicorp/nomad/issues/14275, may as well keep it around

drivers/java: add parsing test case for corretto 17

---

api/acl_test.go
command/acl_bootstrap.go
command/acl_bootstrap_test.go
command/acl_role_create.go
command/acl_role_create_test.go
command/acl_role_update.go
command/acl_role_update_test.go
command/acl_token_create_test.go
nomad/acl_endpoint.go
nomad/acl_endpoint_test.go
nomad/state/state_store_acl.go
nomad/state/state_store_acl_test.go

Each commit contains an overview of each fix.

acl: three small fixes for CLI and state consistency

---

command/job_periodic_force_test.go

Remove use of `pointer` from #14345

remove use of the pointer package

---

ui/app/services/system.js
ui/app/services/token.js

Reverts hashicorp/nomad#14323
Reverting the backport as well for the reasons explained in #14381

Revert "Backport of refact: conditional checks for token secret before fetch into release/1.3.x"

---

website/content/docs/job-specification/change_script.mdx

"path" parameter doesn't work, should be command

docs: template change script example correction

---

website/content/docs/job-specification/ephemeral_disk.mdx

It is really unclear on how to use this feature. it took me a while to find this, so I thought I would purpose how to use this by explaining where it is mounted and providing a link to more detailed documentation.

Update ephemeral_disk.mdx to explain how to use the ephemeral disk

---

e2e/ui/api-client.js
e2e/ui/global-setup.js
e2e/ui/global-teardown.js
e2e/ui/playwright.config.js
e2e/ui/tests/example.spec.js
e2e/ui/utils/index.js

This PR refactors invocations of the `api-client` to match the request schema in the Nomad docs.
Side Effect: I ran `prettier` on this directory.

test:  refactor `api-client` to match REST API request schema

---

e2e/ui/global-setup.js

This PR updates the `globalSetup` script to save the tokens created during this process to a file to be used later in parameterized tests.

e2e: save tokens to file to use in parameterized tests

---

.changelog/_839.txt

See https://github.com/hashicorp/nomad-enterprise/pull/839 for original (Enterprise only)
Let me know if I didn't structure this commit/PR right. It's been a long time since I've done an enterprise-only change!

docs: add quota panic fix changelog entry

---

e2e/acl/acl_token_test.go

This has been hard to prove and test, but my current theory is that the force GC is taking longer to run than the test waits before checking that the token has been deleted. This is likely in the e2e run as the ACL suite runs towards the end of the full suite and there are likely more than just the expired token to collect.

e2e: fix-up token expiration test to account for longer forced GC.

---

e2e/acl/acl_token_test.go
e2e/servicediscovery/nomad_checks_test.go

The NSD checks tests were racey, whereby the check may not have been triggered by the time it was queried. This change wraps the check so it can account for this.
This removes the current ACL expiration GC section in order to get the tests passing and allow more time to investigate the test. I have full confidence the feature is working as expected and have tested extensively locally.

e2e: fixup service discovery and ACL expiration tests.

---

client/allocrunner/group_service_hook.go
client/allocrunner/taskrunner/service_hook.go
command/agent/consul/check_watcher.go
command/agent/consul/structs.go
command/agent/consul/testing.go

This PR combines two of the same interface definitions around workload restarting

cleanup: consolidate interfaces for workload restarting

---

website/content/api-docs/operator/keyring.mdx
website/data/api-docs-nav-data.json

Preview: https://nomad-8bi9ilj87-hashicorp.vercel.app/api-docs/operator/keyring

docs: keyring HTTP API documentation

---

website/content/api-docs/variables.mdx
website/data/api-docs-nav-data.json

Preview: https://nomad-jr8krs923-hashicorp.vercel.app/api-docs/variables

docs: variables HTTP API documentation

---

.github/dependabot.yml

Make dependabot around the same time for all the things

deps: run all dependabot configs over the weekend

---

go.mod

Seems to have gotten lost from the pack

mods: move require statement with the rest

---

api/variables.go

Consul-template expects that the Response Metadata is non-zero, but on a 403 we do not pass back QueryMeta headers.

[vars:api] Return fake QueryMeta on 403s with Peek()

---

.changelog/14677.txt
ui/app/components/service-status-indicator.hbs
ui/app/helpers/format-ts.js
ui/app/styles/components/services.scss

[ui] Service Healthchecks: styles for pseudo-timestamp axis

---

ui/tests/acceptance/exec-test.js
ui/tests/acceptance/servers-list-test.js

Will take 2 snaps:
Empty state:
Default command:

Empty and filled task exec screenshots for test

---

ui/tests/acceptance/task-logs-test.js

task logs page snapshot

---

e2e/ui/README.md

docs:  add steps on contributing to E2E test suite

---

nomad/job_endpoint_test.go

Need to wait for Stop evals to be processed before you can expect subsequent RPCs to see the alloc's DesiredStatus=stop.

test: fix flaky TestJobEndpoint_Register_NonOverlapping test

---

ui/mirage/common.js
ui/tests/acceptance/application-errors-test.js

Captures "No Cluster Leader", Server Error. and general 403.

Visual diff tests: error states

---

ui/app/routes/allocations/allocation.js

Thanks for @mikenomitch for identifying the bug.
Nomad's current UI will fail because of a [check for [0]](https://github.com/hashicorp/nomad/blob/main/ui/app/routes/allocations/allocation.js#L22) instead of a check for `.any()` on an allocation's task states.
This means any job with 2 tasks, the second of which having services but the first not, would fail to kick off health checks.
This probably warrants a RC2 (cc @lgfa29) — let me know if I should add a backport label as such

[ui] Bugfix: Service health checks would not take into account a second task of an alloc

---

e2e/overlap/overlap_test.go
testutil/wait.go

Windows got me.
Added a little "about to fail" warning to my new Wait test helper to hopefully help catch so-close-it-might-be-flaky timings. Sadly didn't help this time, but I think it's kinda nice to get an early heads up when things are _about_ to fail:
```
=== RUN   TestOverlap
overlap_test.go:61: 375/500 retries reached for github.com/hashicorp/nomad/e2e/overlap.TestOverlap (err=timed out before an allocation was found for overlapc0944355)
<< 1.25s pass >>
overlap_test.go:61: timeout: timed out before an allocation was found for overlapc0944355
--- FAIL: TestOverlap (49.30s)
```

Fixing flaky TestOverlap test

---

client/config/config.go
command/agent/agent.go

client: remove unused LogOutput and LogLevel

---

GNUmakefile

My make knowledge is very very limited, so if there's a better way to do this please let me know! This seems to work and lets me cut one off builds easily.

build: add ability to specify release targets

---

website/content/tools/autoscaling/plugins/strategy/target-value.mdx

Provide more technical details about how the `target-value` strategy calculates new scaling actions.
Preview: https://nomad-mhebwhzoz-hashicorp.vercel.app/nomad/tools/autoscaling/plugins/strategy/target-value

docs: explain autoscaler target-value strategy

---

.changelog/14798.txt
ui/app/routes/allocations/allocation.js
ui/app/templates/components/allocation-row.hbs

In the process of debugging [14654](https://github.com/hashicorp/nomad/issues/14654). This will not resolve the issue, but part of the process of cleaning things up as I see them.

refact: upgrade Promise.then to async/await

---

.changelog/15045.txt
go.mod
go.sum

Updates consul-template to https://github.com/hashicorp/consul-template/commit/90370e07bf621811826b803fb633dadbfb4cf287
Fixes https://github.com/hashicorp/nomad/issues/14768

[deps] Update consul-template dependency

---

nomad/eval_endpoint_test.go

While working on filtering improvements to the `Eval.Delete` endpoint I noticed that this test was going to need to expand significantly and needed some refactoring to make that work nicely. In order to reduce the size of the eventual diff, I've pulled this refactoring out into its own changeset.

test: refactor EvalEndpoint_Delete

---

.golangci.yml
GNUmakefile
client/serviceregistration/checks/client.go

Remove dead linters and add some interesting new ones.
Fixes #15060

build: update linters

---

website/content/api-docs/jobs.mdx

Accidentally trailed off on a docs paragraph

---

website/content/api-docs/variables.mdx

A comma was missed in the payload example

Fix example in docs

---

e2e/terraform/Makefile
e2e/terraform/README.md
e2e/terraform/compute.tf
e2e/terraform/nomad.tf
e2e/terraform/outputs.tf
e2e/terraform/packer/README.md
e2e/terraform/packer/build
e2e/terraform/packer/ubuntu-jammy-amd64.pkr.hcl
e2e/terraform/packer/ubuntu-jammy-amd64/consul.service
e2e/terraform/packer/ubuntu-jammy-amd64/dnsconfig.sh
e2e/terraform/packer/ubuntu-jammy-amd64/dnsmasq
e2e/terraform/packer/ubuntu-jammy-amd64/dnsmasq.service
e2e/terraform/packer/ubuntu-jammy-amd64/io.podman.service
e2e/terraform/packer/ubuntu-jammy-amd64/io.podman.socket
e2e/terraform/packer/ubuntu-jammy-amd64/nomad.service
e2e/terraform/packer/ubuntu-jammy-amd64/setup.sh
e2e/terraform/terraform.tfvars
e2e/terraform/tls_client.tf
e2e/terraform/variables.tf

18.04 is EOL in a few months, time to upgrade!
Fixes https://github.com/hashicorp/nomad/issues/15143
stuck on 
```
│ Error: Your query returned no results. Please change your search criteria and try again.
│ 
│   with data.aws_ami.ubuntu_jammy_amd64,
│   on compute.tf line 67, in data "aws_ami" "ubuntu_jammy_amd64":
│   67: data "aws_ami" "ubuntu_jammy_amd64" {
│ 
╵
```

e2e: swap bionic image for jammy

---

nomad/eval_endpoint.go

Ensure we never block in the `Eval.Ack`

make eval cancelation really async with `Eval.Ack`

---

.changelog/15324.txt
ui/app/components/allocation-service-sidebar.hbs
ui/app/templates/allocations/allocation/index.hbs
ui/app/templates/components/job-service-row.hbs

[ui] Show Consul Connect upstreams / on update info in sidebar

---

ui/app/templates/variables/variable/index.hbs

style: wrap secret value in  tag

---

ui/app/components/allocation-service-sidebar.hbs
ui/app/styles/core/tag.scss
ui/app/templates/allocations/allocation/index.hbs

Resolves [15264](https://github.com/hashicorp/nomad/issues/15264)

respect casing on service tags

---

.changelog/15363.txt
ui/app/styles/components/task-sub-row.scss

[ui] Task sub row alignment changes

---

ui/app/templates/clients/client/index.hbs

ui: html escaping

---

website/content/docs/job-specification/affinity.mdx

Fix the comment to correspond to the code

[docs] Update affinity.mdx

---

ui/app/controllers/jobs/index.js

bug: sorting problem with text filter

---

ui/app/helpers/async-escape-hatch.js
ui/app/helpers/format-id.js
ui/app/templates/jobs/job/services/service.hbs

bug:  hitting refresh on `/jobs/:jobId/services/:serviceId` doesn't display data

---

api/acl.go
command/acl_auth_method_list.go
nomad/structs/acl.go
nomad/structs/acl_test.go

acl: added type to ACL Auth Method stub

---

nomad/fsm_test.go

acl: sso auth method snapshot restore test

---

command/acl_auth_method_create_test.go
command/acl_auth_method_update_test.go
nomad/acl_endpoint.go
nomad/acl_endpoint_test.go
nomad/state/state_store_acl_sso.go

This PR fixes unit test failures introduced in f4e89e2895b1d6a5aa270ce27483d4bc2cc6d97a

bugfix: acl sso auth methods test failures

---

.github/workflows/build.yml

Backport of https://github.com/hashicorp/nomad/pull/15490

Backport of Use custom runners for building nomad into release/1.2.x

---

command/acl_auth_method.go
command/acl_auth_method_create.go
command/acl_auth_method_info.go
command/acl_auth_method_list.go
command/acl_auth_method_update.go

This PR contains a number of small bugfixes discovered during #15538 work.

acl: numerous small bugfixes for acl auth methods CLI

---

nomad/state/events.go
nomad/state/events_test.go
nomad/structs/event.go

events: add ACL binding rules to core events stream topics.

---

command/acl_binding_rule.go
command/acl_binding_rule_create.go
command/acl_binding_rule_create_test.go
command/acl_binding_rule_delete.go
command/acl_binding_rule_delete_test.go
command/acl_binding_rule_info.go
command/acl_binding_rule_info_test.go
command/acl_binding_rule_list.go
command/acl_binding_rule_list_test.go
command/acl_binding_rule_update.go
command/acl_binding_rule_update_test.go
command/commands.go

cli: add ACL binding rule commands for CRUD actions.

---

website/content/api-docs/acl/binding-rules.mdx
website/content/api-docs/acl/index.mdx
website/data/api-docs-nav-data.json

acl: binding rules API documentation

---

website/content/docs/commands/acl/auth-method/create.mdx
website/content/docs/commands/acl/auth-method/list.mdx
website/content/docs/commands/acl/binding-rule/create.mdx
website/content/docs/commands/acl/binding-rule/delete.mdx
website/content/docs/commands/acl/binding-rule/info.mdx
website/content/docs/commands/acl/binding-rule/list.mdx
website/content/docs/commands/acl/binding-rule/update.mdx
website/content/docs/commands/acl/index.mdx
website/data/docs-nav-data.json

acl: binding rules CLI documentation

---

website/content/docs/job-specification/service.mdx

docs: fix service name interpolation key details.

---

website/content/docs/commands/eval/delete.mdx

[doc] nomad `eval delete` example typo fix

---

nomad/structs/variables.go
nomad/structs/variables_test.go
ui/app/components/variable-form.js

Rebased version of https://github.com/hashicorp/nomad/pull/15611 that lacks the CLI changes in history that will otherwise be made in #15571

Disallow specific variable at nomad/job-templates

---

api/allocations_test.go

Pretty sure this is just a race between `makeClient` producing a usable node and us trying to register a job. If we lose the race, the job registration produces a queued eval rather than the eval for running the job, which has a different ID.
Adds a little more debug output to help with debugging if it still breaks.
Closes https://github.com/hashicorp/nomad/issues/15662

test: wait for node in api tests that register job

---

api/go.mod
api/go.sum
api/internal/testutil/server.go
go.mod
go.sum
nomad/acl_test.go
nomad/variables_endpoint_test.go

Adds support for custom cmp.Options; needed to fix one minor thing
causing api breakage.

deps: update shoenig/test to v0.6.0

---

.changelog/15735.txt
ui/app/components/task-context-sidebar.hbs
ui/app/components/task-context-sidebar.js
ui/app/styles/components/sidebar.scss

Resolves #15731 
https://user-images.githubusercontent.com/713991/211417117-65a224ca-24f4-444b-85f4-43287c37286e.mov

[ui] Task Logs sidebar expansion button

---

.changelog/15469.txt
command/commands.go
command/operator_client_state.go
command/operator_client_state_test.go
website/content/docs/commands/operator/client-state.mdx
website/data/docs-nav-data.json

Resolve issue #15447
Please let me know if you want to change to `nomad operator client state` and update the documentation too!

cli: Add a nomad operator client state command

---

website/content/docs/job-specification/volume_mount.mdx

Content extracted from the [original PR](https://github.com/hashicorp/nomad/pull/6331). 
Many thanks to @endocrimes for the great PR description 😄

docs: add missing parameter `propagation_mode` to `volume_mount`

---

ui/app/components/job-editor.js
ui/app/controllers/jobs/run.js
ui/app/controllers/jobs/run/index.js
ui/app/routes/jobs/run/templates/new.js
ui/app/templates/components/job-editor.hbs
ui/app/templates/jobs/run/index.hbs
ui/tests/acceptance/job-run-test.js

ui: save as template

---

ui/app/components/job-editor.js
ui/app/controllers/jobs/run.js
ui/app/controllers/jobs/run/index.js
ui/app/controllers/jobs/run/templates/new.js
ui/app/routes/jobs/run/templates/new.js
ui/app/styles/core/forms.scss
ui/app/templates/components/job-editor.hbs
ui/app/templates/jobs/run/index.hbs
ui/app/templates/jobs/run/templates/new.hbs
ui/tests/acceptance/job-run-test.js

ui: add error handling and form validation to job create template

---

website/README.md
website/package-lock.json
website/package.json

This updates the generated docs for the new [mdx inline alert component](https://github.com/hashicorp/dev-portal/pull/1517). See [docs on dev portal here.](https://developer.hashicorp.com/swingset/components/mdxinlinealert)

[website] chore: updates generated docs

---

website/content/api-docs/acl/auth-methods.mdx
website/content/api-docs/acl/oidc.mdx
website/content/docs/commands/login.mdx
website/data/api-docs-nav-data.json
website/data/docs-nav-data.json

docs: add OIDC login API and CLI docs.

---

ui/mirage/config.js
ui/mirage/scenarios/default.js

test:  update mirage fixtures logic

---

website/content/docs/install/index.mdx

docs: clarify installing from source requirement on PATH.

---

.changelog/15522.txt
command/agent/agent.go
command/agent/agent_test.go
command/agent/config.go
nomad/server.go
nomad/server_test.go
website/content/docs/configuration/server.mdx

This plumbs raft snapshot configuration out to the server config

Add raft snapshot configuration options

---

ui/app/templates/components/topo-viz/node.hbs
ui/tests/integration/components/topo-viz-test.js

ui: add client links to topo viz

---

ui/app/routes/jobs/run/templates/index.js
ui/tests/acceptance/job-run-test.js

Bug associated with `O(n+1)` query causing us to lose reference to Ember Data Store because we're using the `map` method.

bug: reactively update view

---

ui/app/adapters/variable.js
ui/app/controllers/jobs/run/templates/index.js
ui/app/controllers/jobs/run/templates/manage.js
ui/app/helpers/format-template-label.js
ui/app/routes/jobs/run/index.js
ui/app/routes/jobs/run/templates/index.js
ui/app/routes/jobs/run/templates/manage.js
ui/app/serializers/variable.js
ui/app/templates/jobs/run/templates/index.hbs
ui/app/templates/jobs/run/templates/manage.hbs
ui/app/utils/default-job-templates.js
ui/app/utils/default_jobs/hello-world.js
ui/app/utils/default_jobs/parameterized.js
ui/app/utils/default_jobs/service-discovery.js
ui/app/utils/default_jobs/variables.js
ui/mirage/config.js
ui/tests/acceptance/job-run-test.js

Stands up 4 Default job templates for users to select from when running a job via the UI
Establishes a new a utils const directory of job templates to be included. These are currently lightly-commented and I hope to improve commenting before this merges.

Initialized default jobs

---

GNUmakefile

Update golangci-lint again, and also hc-install which now has a real version.

build: update hc-install and golangci-lint tools

---

website/README.md
website/package-lock.json
website/package.json

Add a `content-check` npm command and document it in the website directory's README file. This command validates the documentation content against a set of rules to ensure it will render as expected on the Developer site.

website: add content-check command

---

contributing/checklist-command.md

I think these were the things we found today. Anything else we should add?

docs: update CLI contrib checklist

---

README.md

readme: fix incorrect link to ref. arch.

---

ui/app/utils/default_jobs/hello-world.js
ui/app/utils/default_jobs/parameterized.js
ui/app/utils/default_jobs/service-discovery.js
ui/app/utils/default_jobs/variables.js

Comments show up nicer now, and new datacenter wildcard globbing should be encouraged.

[ui] Default Job Templates: change datacenters to use wildcard, change comment style

---

.gitignore

New IDE from jetbrains gets its own config directory.

git: ignore .fleet directory

---

ui/app/components/job-editor.js
ui/app/templates/components/job-editor.hbs
ui/app/templates/jobs/job/definition.hbs
ui/app/templates/jobs/run/index.hbs
ui/tests/acceptance/job-definition-test.js
ui/tests/integration/components/job-editor-test.js
ui/tests/pages/components/job-editor.js

There are no behavior and visual changes in this PR. Just converting `JobEditor` from a Classic Component to Octane.
Here is a [video walkthrough](https://www.loom.com/share/a6be202bfd034bbb90190d8b263ebab8) of the code changes.

Glimmerize `JobEditor` component

---

.changelog/16243.txt
command/job_plan.go

Fixes https://github.com/hashicorp/nomad/issues/16242

Add namespace argument to the job verification help text

---

demo/digitalocean/app/bench.go
e2e/clientstate/clientstate.go
e2e/csi/csi.go
e2e/e2eutil/job.go
e2e/execagent/execagent.go
e2e/metrics/prometheus.go
e2e/vaultcompat/vault_test.go
e2e/vaultsecrets/vaultsecrets.go
helper/escapingfs/escapes_test.go
helper/pluginutils/loader/loader_test.go
helper/snapshot/archive.go
helper/snapshot/archive_test.go
helper/snapshot/snapshot.go
helper/testtask/testtask.go
jobspec2/parse.go
jobspec2/parse_test.go
nomad/acl_endpoint.go
nomad/acl_endpoint_test.go
nomad/event_endpoint.go
nomad/operator_endpoint_test.go
nomad/rpc_test.go
nomad/server.go
testutil/server.go

No user facing changes so I assume no change log is required

deps: Update ioutil library references to os and io respectively for e2e helper nomad

---

drivers/docker/driver.go
drivers/docker/driver_linux_test.go
drivers/docker/driver_test.go
drivers/exec/driver_test.go
drivers/java/driver_test.go
drivers/mock/driver.go
drivers/rawexec/driver_test.go
drivers/rawexec/driver_unix_test.go
drivers/shared/executor/executor.go
drivers/shared/executor/executor_linux_test.go
drivers/shared/executor/executor_test.go
drivers/shared/hostnames/mount.go
drivers/shared/hostnames/mount_unix_test.go
drivers/shared/resolvconf/mount_unix_test.go

No user facing changes so I assume no change log is required

deps: Update ioutil library references to os and io respectively for drivers package

---

ui/app/controllers/policies/policy.js
ui/app/services/notifications.js

Also, removed an errant console.log

[ui] Fix: New toast notifications no longer last forever

---

website/Makefile
website/scripts/should-build.sh
website/scripts/website-build.sh
website/scripts/website-start.sh

Update website scripts on release/1.3.x so the correct UI is showing.

chore: update website scripts (release/1.4.x)

---

website/package-lock.json
website/package.json

Update the content-conformance package to latest to fix an issue with how we check nav data. Specifically: https://github.com/hashicorp/web-platform-packages/blob/main/packages/content-conformance/CHANGELOG.md#008

docs: update content-conformance package

---

ui/app/styles/components/codemirror.scss
ui/app/templates/components/job-editor/read.hbs

This PR updates the CSS class name because SCSS classnames are applied globally.

chore:  update CSS classname

---

api/acl.go
command/agent/acl_endpoint.go
command/agent/acl_endpoint_test.go
command/agent/http.go
command/login.go
internal/testing/apitests/acl_test.go
nomad/leader.go

This PR introduces HTTP endpoints for JWT auth.

acl: HTTP endpoints for JWT auth

---

.changelog/16504.txt
command/login.go
command/login_test.go
website/content/docs/commands/login.mdx

admin: manual backport of commit b95b1052881ecaf18b41c360a2096bab9b1e03a8

---

website/content/docs/concepts/plugins/task-drivers.mdx

updated propogating to propagating

Spelling update

---

command/acl_auth_method.go
command/acl_auth_method_create.go
command/acl_auth_method_create_test.go
command/acl_auth_method_update.go
command/login.go
command/login_test.go
website/content/docs/commands/acl/auth-method/create.mdx
website/content/docs/commands/acl/auth-method/update.mdx

This PR introduces CLI command adjustments for JWT-based auth.

acl: JWT auth CLI

---

website/content/docs/other-specifications/acl-policy.mdx

Added a UI section noting the needed read rules (node and agent) when using the Nomad UI

Added section of needed rules for Nomad UI

---

ui/app/styles/charts/colors.scss
ui/app/styles/components/job-status-panel.scss
ui/app/styles/core/tag.scss
ui/app/styles/utils/product-colors.scss

Changes the completed colour from dark green to pale green (for the new visualizations only)

Updates complete alloc colour to green for new visualizations only

---

website/content/docs/configuration/client.mdx

The former link results in a 404. Update the link to the correct developer docs.

docs: fix link of Read Stats API

---

website/content/tools/index.mdx

@lgfa29 suggested that I add my Nomad Admission Control Proxy to the community tools
https://discuss.hashicorp.com/t/nomad-admission-control-proxy/51896/2

docs: mention Nomad Admission Control Proxy

---

ui/app/adapters/token.js
ui/app/controllers/settings/tokens.js
ui/app/models/auth-method.js
ui/app/styles/components/authorization.scss
ui/app/templates/settings/tokens.hbs
ui/jsconfig.json
ui/mirage/config.js
ui/mirage/scenarios/default.js
ui/tests/acceptance/token-test.js

[ui] Web sign-in with JWT

---

ui/app/components/job-editor.js
ui/app/routes/jobs/job/definition.js
ui/app/templates/components/job-editor/alert.hbs
ui/app/templates/components/job-editor/edit.hbs

Loom Walk Through:  https://www.loom.com/share/e44928734f314deca5840c247f249eaf

ui:  enable editing of HCL vars in the UI

---

ui/app/components/job-editor.js
ui/app/routes/jobs/job/definition.js
ui/app/templates/components/job-editor/alert.hbs
ui/app/templates/components/job-editor/edit.hbs

ui:  warning message

---

website/content/docs/install/index.mdx

Ref https://github.com/hashicorp/dev-portal/pull/1737/files
Ref https://github.com/hashicorp/nomad/pull/16764#issuecomment-1494399214

docs: fix use of gpg to avoid teeing binary to terminal

---

GNUmakefile

This just helps keep up with the podman driver repo.

deps: bump build and linter tool versions

---

command/node_meta_apply.go
website/content/docs/commands/node/index.mdx
website/content/docs/commands/node/meta/apply.mdx
website/content/docs/commands/node/meta/index.mdx
website/content/docs/commands/node/meta/read.mdx
website/data/docs-nav-data.json

docs: add node meta command docs

---

ui/app/components/job-status/update-params.js

Changes the nanoseconds in Update Params to seconds/mins/etc. using our formatDuration utility.

[ui, deployments] Conversions on long nanosecond update params

---

website/content/docs/job-specification/artifact.mdx

docs: update artifact jobspec sshkey example path.

---

.github/workflows/release.yml

Missed these in the previous pass.

build: upgrade deprecated actions syntax

---

api/allocations.go
ui/app/components/job-status/failed-or-lost.hbs

Corrections from https://github.com/hashicorp/nomad/pull/17227

Fixes to scheduling-filtering-in-ui

---

acl/acl.go
acl/acl_test.go
acl/policy.go
acl/policy_test.go
website/content/docs/other-specifications/acl-policy.mdx

Implement ACL concepts for node pool management.
Website preview documenting the details:
https://nomad-git-f-node-pools-acl-hashicorp.vercel.app/nomad/docs/other-specifications/acl-policy#node-pools-rules

np: implement ACL for node pools

---

.changelog/17313.txt
drivers/docker/config.go
drivers/docker/config_test.go
drivers/docker/driver.go
drivers/docker/driver_test.go
website/content/docs/drivers/docker.mdx

fix https://github.com/hashicorp/nomad/issues/17108

Add group_add docker option

---

nomad/node_pool_endpoint.go
nomad/node_pool_endpoint_test.go

We don't want to delete node pools that have nodes or non-terminal jobs. Add a check in the `DeleteNodePools` RPC to check locally and in federated regions, similar to how we check that it's safe to delete namespaces.

node pools: protect against deleting occupied pools

---

.copywrite.hcl

Once merged, will close #17500

build: add agent bindata file to copywrite ignore list.

---

nomad/structs/node_pool_oss.go
nomad/structs/node_pool_oss_test.go

I have no idea how I managed to copy these in lowercase 😅

chore: fix typo and copyright header

---

ui/mirage/factories/agent.js
ui/mirage/scenarios/default.js
ui/tests/acceptance/allocation-detail-test.js
ui/tests/acceptance/behaviors/fs.js
ui/tests/acceptance/client-detail-test.js
ui/tests/acceptance/clients-list-test.js
ui/tests/acceptance/exec-test.js
ui/tests/acceptance/regions-test.js
ui/tests/acceptance/server-detail-test.js
ui/tests/acceptance/servers-list-test.js
ui/tests/acceptance/task-detail-test.js
ui/tests/acceptance/task-group-detail-test.js
ui/tests/acceptance/task-logs-test.js
ui/tests/acceptance/token-test.js

This information is useful when switching between different scenarios for testing.

ui: display mirage scenario in header label

---

nomad/node_pool_endpoint.go
nomad/node_pool_endpoint_oss.go

Actual license verification will happen in the Enterprise repo.

np: check for license on RPC endpoints

---

.changelog/11041.txt

I don't have a specific PR to point to, so I'm using #11041 since it's more or less where the feature started. I posted an update there describing how node pools work.

changelog: add entry for node pools

---

nomad/server.go

This reverts commit 82763a809ffebc1418a9be7bf0c7cecaf0ef869d.

Revert backport of commit 362911a64352e1e3f47e2266bdc0bb58a2027e25

---

ci/test-core.json
nomad/lock/delay.go
nomad/lock/delay_test.go
nomad/lock/ttl.go
nomad/lock/ttl_test.go

Targets feature branch.
Related https://github.com/hashicorp/nomad/issues/17449

var: add TTL and delay timer functionality to new pkg

---

go.mod
go.sum

Closes https://github.com/hashicorp/nomad/issues/17723

deps: update cronexpr to capture license file in SBOM tools

---

nomad/state/state_store_restore.go
nomad/state/state_store_restore_test.go

I've not had a chance to test this using the linked issue.
closes #17764

job: ensure node pool is canonicalized for state restores.

---

website/content/docs/concepts/security.mdx

Correcting a broken link under "similar to consul" and correcting list formatting under "general mechanisms" in 
https://developer.hashicorp.com/nomad/docs/concepts/security

[Docs] Update security.mdx

---

client/allocrunner/config.go

remove empty file

---

website/content/docs/drivers/raw_exec.mdx

docs: clarify using user on raw_exec driver

---

drivers/docker/config.go
drivers/docker/utils.go

Found a couple of typos while in the Docker driver codebase. Small PR to correct them.

[chore] Fix typos

---

CHANGELOG.md

Let's see if BPA can handle this 😄

changelog: add entry for #17731 into 1.4.11

---

.changelog/17911.txt
command/node_status.go
command/volume_status.go
command/volume_status_csi.go
website/content/docs/commands/node/status.mdx
website/content/docs/commands/volume/status.mdx

Fixes: https://github.com/hashicorp/nomad/issues/17912

volume-status : show namespace the volume belongs to

---

.changelog/17932.txt
ui/app/controllers/variables/index.js
ui/app/controllers/variables/path.js
ui/app/templates/variables/index.hbs
ui/app/templates/variables/path.hbs

Now, from a variable page, you can type in `n v`, which stands for "NeVermind why I chose those letters"

[ui] New keyboard shortcut for Create Variable

---

.changelog/17933.txt
ui/app/components/variable-form.hbs

[ui] Copy change to include the nomad/jobs all-access variable prefix

---

.changelog/17935.txt
ui/app/styles/components/variables.scss
ui/app/templates/variables/variable/index.hbs

[ui] Copy button added to variables title

---

.changelog/17915.txt

Meant to include this in #17915

Changelog entry for remote purge boot-out

---

.changelog/17815.txt
command/alloc_logs.go

check in stderrFrame is nil before logging stderrFrame.Data (#17815)

---

.changelog/18044.txt

adding missed changelog entry from perviously merged PR

changelog: add entry for #18044

---

.changelog/18070.txt

Missing changelog entry for https://github.com/hashicorp/nomad-enterprise/pull/1201

changelog entry for nomad-enterprise#1201

---

website/content/api-docs/allocations.mdx

docs: add allocation checks API documentation.

---

scheduler/reconcile_util_test.go

related to [#10727](https://github.com/hashicorp/nomad/issues/10727)

test: add tests for allocNameIndex core funcs

---

.changelog/17939.txt
command/agent/agent.go
command/agent/config.go
nomad/config.go
nomad/fsm.go
nomad/fsm_test.go
nomad/server.go
nomad/state/state_store.go
nomad/state/state_store_test.go
nomad/state/testing.go
nomad/structs/structs.go
website/content/docs/configuration/server.mdx

https://github.com/hashicorp/nomad/issues/17635

Tuning job versions retention. #17635

---

api/acl.go
api/api_test.go
internal/testing/apitests/api_test.go

Remove Deprecated BootStrap Code

Deprecate the Original Bootstrap Token Code

---

website/content/docs/drivers/docker.mdx

Closes https://github.com/hashicorp/nomad/issues/18276

docs: clarify reference to `network.mode` in docker `network_mode` config

---

website/content/docs/integrations/vault-integration.mdx

The sentence was incomplete and had some other grammatical problems.

docs: fix a sentence in vault-integration.mdx

---

website/content/docs/job-specification/job.mdx

Close https://github.com/hashicorp/nomad/issues/18284

docs: remove datacenter from job examples

---

website/content/docs/configuration/client.mdx

Close https://github.com/hashicorp/nomad/issues/18282

docs: expand on where node_class may be used

---

nomad/state/state_store_restore_test.go

Yes...I am looking forward to the backports :|

test: use must package for state store restore test file.

---

client/allocrunner/alloc_runner_test.go
client/allocrunner/taskrunner/artifact_hook_test.go
client/client_test.go
client/widmgr/widmgr_test.go
command/tls_cert_create_test.go
drivers/docker/driver_test.go
nomad/acl_endpoint_test.go
nomad/alloc_endpoint_test.go
nomad/node_endpoint_test.go
nomad/plan_apply_test.go
nomad/plan_endpoint_test.go
nomad/structs/workload_id_test.go
nomad/util_test.go

related: https://github.com/hashicorp/nomad/issues/18325

test: use correct parallel test setup func

---

client/client.go

When restoring an allocation `WIDMgr` was not being set in the alloc runner config, resulting in a nil panic when the task runner attempted to start.
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x10 pc=0x10336152c]
goroutine 247 [running]:
github.com/hashicorp/nomad/client/widmgr.(*WIDMgr).SignIdentities(0x0, 0x14000aa8570?, {0x14000710020, 0x1, 0x1})
github.com/hashicorp/nomad/client/widmgr/widmgr.go:57 +0x7c
github.com/hashicorp/nomad/client/allocrunner/taskrunner.(*identityHook).getIdentities(0x14000cc44e0, 0x1400086a600, 0x140001d1800)
github.com/hashicorp/nomad/client/allocrunner/taskrunner/identity_hook.go:141 +0x1a0
github.com/hashicorp/nomad/client/allocrunner/taskrunner.(*identityHook).Prestart(0 …
```

client: fix panic on alloc restore

---

.changelog/18380.txt
api/deployments.go
api/deployments_test.go
api/util_test.go

Hi team, 
This PR adds more unit tests to api/deployments client 
Fixes: https://github.com/hashicorp/nomad/issues/18060

Add unit test for api/deployments.go

---

website/content/docs/job-specification/index.mdx

docs: improve diagram on jobspec overview for multi group + tasks.

---

nomad/structs/csi.go

Found while randomly perusing the code.

csi: remove unused internal funcs.

---

website/content/tools/autoscaling/plugins/external/index.mdx

aliyun is the biggest cloud service provider in china, It would be very helpful if implemented.

add new target plugin for aliyun

---

.changelog/18366.txt
api/jobs.go
jobspec/parse_job.go
jobspec/parse_test.go
jobspec/test-fixtures/basic.hcl

Issue where problem was found - https://github.com/hashicorp/levant/issues/499

Adding node_pool to job key validation

---

website/content/tools/autoscaling/plugins/external/index.mdx

add repo in md. link to pr : https://github.com/hashicorp/nomad/pull/18473.

Update external target plugins md file

---

website/content/docs/job-specification/periodic.mdx

provide an example of multiple crons by looking at the PR:
https://github.com/hashicorp/nomad/pull/17858
tested the syntax using `nomad agent -dev` and a sample job

example of multiple crons

---

.changelog/18553.txt
nomad/job_endpoint.go
nomad/job_endpoint_ce.go

This is the CE work required for https://github.com/hashicorp/nomad-enterprise/pull/1136

[sentinel] Add existing job to enforceSubmitJob

---

.changelog/18570.txt
nomad/csi_endpoint.go
nomad/csi_endpoint_test.go
nomad/state/state_store.go

backport csi: check controller health early into release/1.4.x

---

nomad/encrypter_test.go

Encoded JWTs include an `alg` header key that tells the verifier which signature algorithm to use. Bafflingly, the JWT standard allows a value of `"none"` here which bypasses signature verification.
In all shipped versions of Nomad, we explicitly configure verification to a specific algorithm and ignore the header value entirely to avoid this protocol flaw. But in #18123 we updated our JWT library to `go-jose`, which rightfully doesn't support `"none"` but this detail isn't encoded anywhere in our code base. Add a test that ensures we catch any regressions in the library.

WI: add test to verify we don't allow empty signatures for JWT

---

website/content/tools/autoscaling/plugins/external/index.mdx

closes https://github.com/hashicorp/nomad/issues/18613

docs: fix link to alicloud autoscaler plugin (#18495)

---

command/job_status.go
command/status.go

Improves help text for `nomad job status` and `nomad status` CLI commands

chore(command): improve `job` and `status` text

---

client/allocrunner/taskrunner/consul_hook.go

vide https://github.com/hashicorp/nomad/pull/18557#discussion_r1341513988
Ref https://github.com/hashicorp/team-nomad/issues/404

consul: consul taskrunner hook should only write tokens that belong to its task

---

nomad/csi_endpoint_test.go

A CSI plugin can be made up of multiple jobs, which may not be in the same namespace. When querying for a plugin and getting information about the allocations that implement the plugin, we need to filter by the namespaces the user has access to.
This test existed in the ENT code base and was never moved over to CE when we made namespaces part of the CE product. I've given the test a slightly different name than the one in ENT to avoid any potential build conflicts from the merge, but I'll open a separate PR to remove it from ENT.

csi: add test for that plugin allocs are filtered by namespace

---

client/allocrunner/consul_hook.go
nomad/job_endpoint_hook_consul_ce.go

vide https://github.com/hashicorp/nomad/pull/18742#discussion_r1357173520

client: correct consul block validation in the consul_hook

---

demo/csi/hostpath/README.md

Related: https://github.com/hashicorp/nomad/issues/18678

demo: clarify CSI host-path single client limitation.

---

testutil/server.go

Some of our `api` package tests have ACLs enabled, but none of those tests also run clients and the "wait for the clients to be live" code reads from the Node API. The caller can't bootstrap ACLs until `NewTestServer` returns, and this makes for a circular dependency.
Allow developers to provide a bootstrap token to the test server config, and if it's available, have the server bootstrap the ACL system with it before checking for live clients.
Pulled out of https://github.com/hashicorp/nomad/pull/18799

testutil: add ACL bootstrapping to test server configuration

---

.changelog/18832.txt
command/helpers.go
command/helpers_test.go

cli: ensure HCL env vars are added to the job submission object.

---

.changelog/18463.txt

The Features header is reserved for "tent-pole" features of a Nomad version.

cl: minor features are listed as improvements

---

client/lib/cgroupslib/init.go

This PR fixes a forgotten TODO from the cgroups refactoring specific to cgroups v1. At the time I was thinking ahead about maybe leveraging `cpuset.mems` to restrict memory node access, but per the RFC that did not (yet) come to fruition. I left a stub that just sets `cpuset.mems = 0` instead of re-creating the previous behavior of enabling all nodes (or the limited set if nodes of the cgroup parent is pre-existing).
Closes https://github.com/hashicorp/nomad/issues/18865

client: fix detection of cpuset.mems on cgroups v1 systems

---

api/api.go

When attempting a WebSocket connection upgrade the client may receive a redirect request from the server, in which case the request should be reattempted using the new address present in the `Location` header.

api: handle redirect during websocket upgrade

---

client/allocrunner/taskrunner/template_hook_test.go

The template hook emits an error when the task has a Consul block that requires WI but there's no WI. The exact error message we get depends on whether we're running in CE or ENT. Update the test assertion so that we can tolerate this difference without building ENT-specific test files.

template: fix test assertion to be compatible between CE/ENT

---

website/content/docs/upgrade/upgrade-specific.mdx

docs: recommend rotating keys on upgrade

---

nomad/core_sched_test.go

One of our core scheduler tests for GC tests that volumes with invalid allocations immediately have those claims marked as past claims and puts them into the unpublishing state. This happens synchronously with the GC evaluation processing, so there's no need for us to wait for the results.
Fixes: #18959

test: make CSI bad state GC test synchronous

---

command/asset/consul-wi-default-auth-method-config.json
command/asset/consul-wi-default-policy.hcl
command/commands.go
command/setup.go
command/setup_consul.go

An interactive setup helper for configuring Consul to accept Nomad WI-enabled workloads.

cli: consul setup command

---

client/lib/numalib/detect_linux.go

This PR tweaks the linux cpu fingerprinter to handle the case where no
NUMA node data is found under /sys/devices/system/, in which case we
need to assume just one node, one socket.
Fixes #18963

client: fix cpu fingerprint on raspberry pi

---

command/alloc_exec.go
command/asset/vault-wi-default-auth-method-config.json
command/asset/vault-wi-default-policy.hcl
command/asset/vault-wi-default-role.json
command/commands.go
command/helpers.go
command/setup_consul.go
command/setup_vault.go

An interactive setup helper for configuring Vault to accept Nomad WI-enabled workloads.

cli: setup vault command

---

command/setup_consul.go
command/setup_vault.go

Ref: https://github.com/hashicorp/nomad/pull/18910#discussion_r1382301949

cli: simplify conditionals in setup commands

---

client/allocrunner/taskrunner/task_runner_test.go

PRs #19034 and #19040 accidentally conflicted with each other without a merge conflict when #19034 changes the method signature of `SetConsulTokens`. Because CI doesn't rebase, both PRs tested fine and only were broken once they landed on `main`. Fix that.

fix taskrunner test after broken signature

---

client/allocrunner/taskrunner/template_hook.go
client/allocrunner/taskrunner/template_hook_test.go

The template hook must use the Consul token for the cluster defined in the task-level `consul` block or, if `nil, in the group-level `consul` block.
The Consul tokens are generated by the allocrunner consul hook, but during the transition period we must fallback to the Nomad agent token if workload identities are not being used.
So an empty token returned from `GetConsulTokens()` is not enough to determine if we should use the legacy flow (either this is an old task or the cluster is not configured for Consul WI), or if there is a misconfiguration (task or group is `consul` block is using a cluster that doesn't have an `identity` set).
In order to distinguish between the two scenarios we must iterate over the task identities looking for one suitable for the Consul cluster being used.

client: fix Consul token retrievel for templates

---

.github/workflows/test-ui.yml

Seems like I was overly restrictive and forgot my `**` in #19038 , h/t @tgross

Re-add wildcard for test-ui path restrictions

---

e2e/acl/acl_role_test.go

The ACL role test asserts that the role has various permissions by listing jobs in namespaces. It never creates jobs, because we can make all the assertions we need by checking the error. But the test included an assertion that the namespace was empty. Usually this will be the case, but if the previous test case has not completed its GC (which is sync), then it's possible a stopped job will be in the namespace. Because this assertion is irrelevant for this test, remove it.
Fixes: https://github.com/hashicorp/nomad/issues/19109

E2E: remove assertion from ACL role test

---

client/allocrunner/consul_hook.go

Fixes https://github.com/hashicorp/nomad/issues/19127

client: make sure consul_hook does not perform double requests for tasks

---

.changelog/18967.txt
nomad/fsm.go
nomad/job_endpoint.go
nomad/structs/structs.go

Set correct submit time to stopped jobs

---

website/content/docs/operations/metrics-reference.mdx

docs: add alloc metrics note about possible cgroup variations.

---

website/content/docs/concepts/cpu.mdx

Preview link: https://nomad-bm777y1zx-hashicorp.vercel.app/nomad/docs/concepts/cpu#nomad_cpu_cores

docs: fix typos and markdown issues on CPU concepts page

---

client/allocrunner/consul_hook.go
client/allocrunner/consul_hook_test.go
client/consul/consul.go
client/consul/consul_testing.go

Refactor the JWT token derivation logic to only take a single request since it was only ever called with a map of length one.
The original implementation received multiple requets to match the legacy flow, but but legacy flow requests were batched from the Nomad client to the server, which doesn't happen for JWT. Each JWT request goes directly from the Nomad client to the Consul agent, so there is no batching involved.

consul: refactor allocrunner consul hook

---

client/allocrunner/taskrunner/script_check_hook.go

The `script_check_hook` runs at the task level but can create script checks for both task-level services and group-level services. Now that we allow the Consul namespace to be set at the task-level `consul.namespace`, we need to have both possible namespaces handy when creating and updating checks.

script_check_hook: handle task-level Consul namespace

---

e2e/consultemplate/consultemplate_test.go

When porting the `ConsulTemplate` test, I made a last-minute refactor to the assertions for waiting on files, and accidentally inverted the test assertion in the process.
Also, when running `jobs3.Submit` you need to include the `Namespace` option so that the cleanup function that gets return deletes the job from the correct namespace. This was causing the namespace cleanup to fail because the job deletion had failed.
Fixes: https://github.com/hashicorp/nomad/issues/19075
---
Resulting tests vs one of our 4-node E2E clusters on AWS:
```
$ go test -v -count=1 ./e2e/consultemplate
=== RUN   TestTemplateUpdateTriggers
consultemplate_test.go:70: alloc "73e96237-c4d4-082b-d196-98bcf3ec1638" (exec_downstream) on node "e35a4b9e-d33f-3ce3-7465-c46d8b4377c4"
consultemplate_test.go:70: alloc …
```

E2E: fix assertion in CT native service lookup test

---

website/content/docs/configuration/consul.mdx

I was a bit late to review #19258 so here a few minor fixes and updates.

docs: small updates to agent `consul`

---

e2e/isolation/pids_test.go

couple more timeout extensions for #16607

e2e: more occasionally slow exec tasks in isolation test

---

.changelog/19415.txt

changelog: add entry for #19415

---

.changelog/19423.txt
command/var_put.go
command/var_put_test.go

cli: Fix bug in `var put` command using mix of flags and spec.

---

.changelog/19441.txt
nomad/structs/structs.go
nomad/structs/structs_test.go
website/content/docs/job-specification/csi_plugin.mdx

[CSI] Prevent stage_publish_base_dir from being subdir of mount_dir

---

website/content/docs/upgrade/upgrade-specific.mdx

docs: fix migration to workload identity links

---

website/content/tools/autoscaling/plugins/target/aws-asg.mdx
website/content/tools/autoscaling/plugins/target/azure-vmss.mdx
website/content/tools/autoscaling/plugins/target/gce-mig.mdx

Document the `node_pool` node selector configuration.
Ref: https://github.com/hashicorp/nomad-autoscaler/pull/810

docs: add `node_pool` autoscaler node selector

---

.copywrite.hcl
LICENSE
api/.copywrite.hcl
demo/.copywrite.hcl
drivers/shared/.copywrite.hcl
jobspec/.copywrite.hcl
jobspec2/.copywrite.hcl
plugins/.copywrite.hcl

DO NOT MERGE UNTIL EOY 2023.
Updates year in LICENSE and related files for release/1.7.x branch of Nomad.

[DO NOT MERGE UNTIL EOY] update year in LICENSE and copywrite files v1.7.x

---

.copywrite.hcl
LICENSE
api/.copywrite.hcl
demo/.copywrite.hcl
drivers/shared/.copywrite.hcl
jobspec/.copywrite.hcl
jobspec2/.copywrite.hcl
plugins/.copywrite.hcl

DO NOT MERGE UNTIL EOY 2023.
Updates year in LICENSE and related files for main branch of Nomad.
Do not backport, older branches will be addressed separately.

[DO NOT MERGE UNTIL EOY] update year in LICENSE and copywrite files

---

website/content/tools/autoscaling/telemetry.mdx

Ref.: https://github.com/hashicorp/nomad-autoscaler/pull/814

docs: add `policy_id` and `target_name` metric labels

---

.changelog/19544.txt

[ui] Changelog for multi-line variables

---

.changelog/19652.txt
nomad/structs/structs.go
nomad/structs/structs_test.go

server: Fix panic when validating non-service reschedule block.

---

website/content/docs/drivers/docker.mdx

Removed info regarding development of Nomad

[DOCS] Update docker.mdx

---

website/content/docs/operations/stateful-workloads.mdx

In response to the latest feedback in #19077

Improve wording and clarity on Considerations for Stateful Workloads

---

.changelog/_1370.txt

Ref: https://github.com/hashicorp/nomad-enterprise/pull/1370

docs: changelog entry for ENT PR

---

website/content/tools/autoscaling/agent/nomad.mdx
website/content/tools/autoscaling/cli.mdx

Ref: https://github.com/hashicorp/nomad-autoscaler/pull/755

docs: autoscaler config for blocking query timeout

---

website/content/api-docs/index.mdx

Found myself scrolling past these docs today and thought it'd be a good place to promote wildcard support.

docs: mention wildcards in namespace api docs

---

e2e/v3/jobs3/jobs3.go

The main goal is to enrich mysterious errors like these
```
assert.go:14:
jobs3.go:421: expected not to execute this code path
↪ PostScript | annotation ↷
deployment is failed
assert.go:14: 
jobs3.go:357: expected not to execute this code path
↪ PostScript | annotation ↷
timeout reached waiting for deployment
```
by default with info about evals, allocs, and task events, like these:
```
assert.go:14:
jobs3.go:406: expected not to execute this code path
↪ PostScript | annotation ↷
timeout reached waiting for deployment
jobs3.go:600: eval for tg 'conf' failed; constraints: map[missing network:1]
assert.go:14:
jobs3.go:421: expected not to execute this code path
↪ PostScript | annotation ↷
deployment is failed
jobs3.go:606: tg 'conf' alloc status 'failed': Unable to add allocation due to …
```

e2e: add PreCleanup and some jobs3 helpers

---

website/content/docs/job-specification/upstreams.mdx

docs: remove duplicate entry for `upstreams.config`

---

ui/app/components/conditional-link-to.hbs
ui/app/components/das/recommendation-card.hbs
ui/app/components/das/task-row.hbs
ui/app/components/job-status/individual-allocation.hbs
ui/app/components/keyboard-shortcuts-modal.hbs
ui/app/styles/core/table.scss
ui/app/templates/allocations/allocation/index.hbs
ui/app/templates/clients/client/index.hbs
ui/app/templates/clients/index.hbs
ui/app/templates/components/job-deployment/deployment-allocations.hbs
ui/app/templates/components/job-editor/review.hbs
ui/app/templates/components/job-page/parts/recent-allocations.hbs
ui/app/templates/components/multi-select-dropdown.hbs
ui/app/templates/components/scale-events-accordion.hbs
ui/app/templates/components/task-row.hbs
ui/app/templates/components/topo-viz/node.hbs
ui/app/templates/csi/plugins/plugin/allocations.hbs
ui/app/templates/csi/plugins/plugin/index.hbs
ui/app/templates/csi/volumes/volume.hbs
ui/app/templates/jobs/job/allocations.hbs
ui/app/templates/jobs/job/task-group.hbs
ui/package.json
ui/tests/acceptance/behaviors/fs.js
ui/tests/integration/components/scale-events-accordion-test.js
ui/tests/integration/components/service-status-bar-test.js
ui/tests/integration/components/topo-viz/node-test.js
ui/tests/pages/components/topo-viz/node.js
ui/yarn.lock

Upgrades to the latest [Helios](https://helios.hashicorp.design/whats-new/release-notes#360) (and corresponding icons/branding changes)
(Pending visual regression check w/ Percy)

[ui] HashiCorp Design System upgraded to 3.6.0

---

website/content/tools/autoscaling/plugins/strategy/target-value.mdx

See https://github.com/hashicorp/nomad-autoscaler/pull/848

docs: autoscaler doc for max_scale_up and max_scale_down of target-value strategy

---

website/content/tools/autoscaling/policy.mdx

Document feature implemented in from https://github.com/hashicorp/nomad-autoscaler/pull/850

docs: add Autoscaler `query_window_offset` config

---

website/content/plugins/drivers/community/index.mdx
website/content/plugins/drivers/community/nomad-iis.mdx
website/data/docs-nav-data.json
website/data/plugins-nav-data.json

Backport Docs: Alternative IIS Task Driver (#19411)

---

website/content/tools/autoscaling/agent.mdx

Not sure how I messed up copying it from my lab that badly.

docs: fix autoscaler variable ACL policy example.

---

.github/workflows/actionlint.yml
.github/workflows/backport.yml
.github/workflows/build.yml
.github/workflows/checks.yaml
.github/workflows/copywrite.yml
.github/workflows/ember-test-audit.yml
.github/workflows/release.yml
.github/workflows/semgrep.yml
.github/workflows/test-core.yaml
.github/workflows/test-e2e.yml
.github/workflows/test-ui.yml
.github/workflows/test-windows.yml

Eliminates warnings about node16 being deprecated

build: update the actions/checkout version

---

website/redirects.js

docs: fix s/port-plan-failure

---

client/config/config_test.go
client/logmon/logging/rotator_test.go
client/logmon/logmon_test.go

I got bored and cleaned up a few files
- tests: swap testify for test in client/config
- tests: swap testify for test in logmon/

more test refactoring

---

command/acl_policy_info.go

Fixes: https://github.com/hashicorp/nomad/issues/20117

cli: add options to help string for `acl policy info`

---

website/content/docs/configuration/consul.mdx

Fixes: https://github.com/hashicorp/nomad/issues/20132

docs: improve wording around autoconfiguration via Consul

---

contributing/architecture-eval-triggers.md
website/content/docs/configuration/server.mdx
website/content/docs/job-specification/disconnect.mdx
website/content/docs/job-specification/group.mdx
website/content/docs/upgrade/upgrade-specific.mdx
website/data/docs-nav-data.json

This PR introduces the documentation for the now disconnect block on the job configuration.

Add docs for disconnected block

---

website/content/tools/autoscaling/plugins/strategy/pass-through.mdx

See the PR: https://github.com/hashicorp/nomad-autoscaler/pull/881#event-12349788958

doc nomad-autoscaler: add options for pass-through strategy

---

.changelog/20276.txt
drivers/docker/driver.go
drivers/docker/handle.go
drivers/docker/handle_test.go

cpuset fixer: use correct cgroup path for updates

---

website/content/docs/job-specification/artifact.mdx

docs: add Digital Ocean Spaces artifact jobspec example.

---

website/content/docs/other-specifications/acl-policy.mdx

docs: ensure namespace ACL policy capabilities are all listed.

---

.github/workflows/build.yml
Dockerfile
GNUmakefile

and add some more docker labels (including license)

license: add LICENSE file to release zip and docker image

---

terraform/shared/config/consul.hcl
terraform/shared/config/consul_client.hcl

Missed somehow in https://github.com/hashicorp/nomad/pull/19512

docs: add missing copyright headers in Terraform examples

---

website/data/intro-nav-data.json

Consolidated quickstart dropdown in intro links and updated it to new quickstart guide!

update docs link in quick start

---

e2e/workload_id/input/nobody.nomad

sometimes the container would quit too fast

e2e: unflake TestWorkloadIdentity/testNobody

---

.github/actions/install-vault/action.yml

failure per: https://github.com/hashicorp/nomad/actions/runs/9015558278/job/24770644273?pr=20546

github: fix lint action check with install-vault descriptions.

---

scheduler/generic_sched_test.go

While working on #20462 #12319 I found that some of our scheduler tests around down nodes or disconnected clients were enforcing invariants that were unclear. This changeset pulls out some minor refactorings so that the bug fix PR is easier to review. This includes:
* Migrating a few tests from `testify` to `shoenig/test` that I'm going to touch in #12319 anyways.
* Adding test names to the node down test
* Update the disconnected client test so that we always re-process the pending/blocked eval it creates; this eliminates 2 redundant sub-tests.
* Update the disconnected client test assertions so that they're explicit in the test setup rather than implied by whether we re-process the pending/blocked eval.
Ref: https://github.com/hashicorp/nomad/issues/20462
Ref: …

refactor scheduler tests for node down/disconnected

---

website/content/plugins/drivers/exec2.mdx

Add installation section for manual, apt, and yum installs.

docs: add installation section to exec2 driver

---

website/content/plugins/drivers/exec2.mdx

Small change, removal of extraneous close paren

docs: small typo

---

website/content/plugins/drivers/exec2.mdx

Manual backport of https://github.com/hashicorp/nomad/pull/22234

docs: Update exec2.mdx, fix typo

---

.changelog/20626.txt
ui/app/controllers/jobs/index.js
ui/app/templates/jobs/index.hbs
ui/tests/acceptance/jobs-list-test.js

[ui] Dropdowns on the jobs index page get a max-height and filtering

---

website/content/docs/commands/operator/snapshot/inspect.mdx

docs: update snapshot inspect CLI detail to mirror recent changes.

---

website/content/docs/integrations/consul/index.mdx
website/content/docs/release-notes/nomad/v1_8_x.mdx

- Adds Enterprise next to a few enterprise only features
- Adds a link to https://developer.hashicorp.com/nomad/docs/commands/alloc/pause 
- Update Consul compat matrix

docs - release notes updates

---

e2e/v3/cluster3/cluster3.go

I'm writing E2E tests for an enterprise feature, and while they're conventionally run against ENT nightly, I figure it might be nice to auto-skip tests that opt in to this new option explicitly, if run against a CE build.
Example usage:
```go
cluster3.Establish(t,
cluster3.Enterprise(),
cluster3.Leader(),
cluster3.LinuxClients(1),
)
```

e2e: add Enterprise Option for cluster3.Establish

---

e2e/v3/jobs3/jobs3.go

By using a `Set.Insert("{k}={v}")`, repeat `Var()` calls (as with `Submission.Rerun()`) with different variable values would send both the previous vars and the new ones, which produced confusing results.  Keeping a map instead allows easily overwriting vars by key.  If concurrency is a concern, I could add a lock or use sync.Map, but I don't think this stuff tends to be called concurrently.
I also included the jobspec source and stringified variables in the job registration, so a test author can look in the UI to easily see what was registered, which is particularly useful for jobspecs with variables or otherwise templated contents.

e2e: jobs3 hcl vars differently

---

.github/actions/setup-js/action.yml

Uses a deprecated node 16 action

[action] Update actions in test-ui workflow

---

.changelog/23499.txt
nomad/namespace_endpoint.go
nomad/namespace_endpoint_test.go
nomad/structs/structs.go

Fixes #17088 
Relates to #19979
Relates to #19483 
Relates to #19414 
Internal ref: https://hashicorp.atlassian.net/browse/NET-9341

namespaces: warn if deleting namespaces that have allocs, volumes, vars or quotas associated with them

---

.changelog/23506.txt
ui/app/adapters/application.js
ui/app/adapters/token.js
ui/app/components/region-switcher.js
ui/app/components/token-editor.hbs
ui/app/components/token-editor.js
ui/app/controllers/clients/index.js
ui/app/controllers/jobs/index.js
ui/app/routes/clients.js
ui/mirage/config.js
ui/tests/acceptance/regions-test.js
ui/tests/acceptance/token-test.js

This PR allows for creation of global tokens, tokens of differing regions, and generally improves the handling of regions in the UI a bit better.
Resolves #23429

[ui] Global token CRUD in the web UI

---

nomad/encrypter_test.go
nomad/testing.go

Nomad's default serf configuration has a full sync interval of 60s (the WAN default configuration in the library). If tests need to join nodes and the leader is not in the join set, the test can hang up to twice that interval waiting for the new node to be seen by the leader and added to Raft.
This changeset includes the following tweaks to improve test timings:
* Ensure that nodes introduced later in the keyring replication test are joined to all peers. (Also updates the test to `shoenig/test`.)
* Update the `TestJoin` helper so that all servers passed are joined to the full set, instead of a set that's offset by 1, and use a single `Join` call for each server to reduce the number of messages sent.
* Reduce the `PushPullInterval` from 60s to 500ms in our unit test configuration, to force …

testing: fix serf join on keyring test and tighten serf config

---

website/content/docs/other-specifications/acl-policy.mdx

Clarify how Nomad evaluates policy rules.
Fixes: #20118
Jira: https://hashicorp.atlassian.net/browse/CE-695
Related tutorial PR: https://github.com/hashicorp/tutorials/pull/2205

docs: Clarify namespace rules matching criteria.

---

website/content/docs/commands/login.mdx

Currently, the page doesn't explain how to do things as the logged in user.

login.mdx: Illustrate how to use the obtained token

---

client/testutil/driver_compatible.go

Ref: https://github.com/hashicorp/nomad/commit/9543e740af72d1b94dc1a907d6de3c673c7aec52#r145182897 :blush:

testing: fix skip comment on `RequireWindows` helper

---

website/content/docs/configuration/client.mdx
website/content/docs/job-specification/constraint.mdx

docs: remove remaining references to network_speed config

---

.changelog/23813.txt
api/namespace.go
command/namespace_status.go
nomad/job_endpoint_validators.go
nomad/job_endpoint_validators_test.go
nomad/structs/structs.go
website/content/docs/commands/namespace/apply.mdx
website/content/docs/commands/namespace/status.mdx
website/content/docs/other-specifications/namespace.mdx

Tie allowed network modes to namespace capabilities.

---

.changelog/23829.txt
ui/app/components/job-status/panel/steady.js
ui/app/models/job.js
ui/mirage/factories/job.js
ui/tests/acceptance/jobs-list-test.js

[ui] Show "Scaled Down" as a valid job status when task groups' counts are set to zero

---

command/quota_init.go

related to: https://github.com/hashicorp/nomad/issues/9917
internal ref: https://hashicorp.atlassian.net/browse/NET-9858

quota: add device block to the quota init command

---

e2e/ui/package-lock.json
e2e/ui/package.json
e2e/ui/run.sh

(so as to fix [recent test failures related to unlaunchable chromium](https://github.com/hashicorp/nomad-e2e/actions/runs/10732748275/job/29787236798))

[tests] Update the pinned playwright version for E2E UI tests

---

ui/package.json
ui/yarn.lock

Resolves https://github.com/hashicorp/nomad/security/dependabot/242
Resolves https://github.com/hashicorp/nomad/security/dependabot/241

[ui] Pin path-to-regexp with yarn1 syntax

---

ui/package.json
ui/yarn.lock

Resolves https://github.com/hashicorp/nomad/security/dependabot/243

[ui] Pin body-parser to resolve an outdated dep

---

ui/package.json
ui/yarn.lock

This reverts commit 51caca1a854b9f5e60584d09810a92c64af876eb.

Revert "Pin body-parser to resolve an outdated dep problem (#23954)"

---

e2e/consulcompat/shared_run_test.go

When we start the Consul agent in the `consulcompat` test package, we check that the version matches the version we expect. But Consul agents may omit non-core parts of the version string (ex. `1.20.0-rc1` displays `1.20.0`). Compare only the core portions of the version string.

E2E: allow Consul version to omit tags

---

website/content/docs/job-specification/numa.mdx

Add docs for the numa devices block.

docs: add documentation for numa devices block

---

.changelog/24055.txt
CHANGELOG.md

Missed this in https://github.com/hashicorp/nomad/pull/24055

Changelog for Golden Versions added

---

GNUmakefile

Backported from https://github.com/hashicorp/nomad/pull/24070

Backport of: correct LAST_RELEASE in Makefile

---

website/content/docs/operations/aws-oidc-provider.mdx

Clarify Terraform prereq since you don't need to install the Terraform CLI locally.
Fixes: [CE-726](https://hashicorp.atlassian.net/browse/CE-726)
[CE-726]: https://hashicorp.atlassian.net/browse/CE-726?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Docs: Terraform prereq clarification

---

website/content/docs/commands/node-pool/list.mdx

docs: CLI node pool list does not accept arguments.

---

website/content/partials/virt-beta-callout.mdx
website/content/plugins/drivers/virt/client.mdx
website/content/plugins/drivers/virt/index.mdx
website/content/plugins/drivers/virt/installation.mdx
website/content/plugins/drivers/virt/task-config.mdx
website/data/docs-nav-data.json
website/data/plugins-nav-data.json

Jira: https://hashicorp.atlassian.net/browse/NET-11215
Deploy preview https://nomad-git-f-net-11215-hashicorp.vercel.app/nomad/plugins/drivers/virt
Fixes: [CE-680]
[CE-680]: https://hashicorp.atlassian.net/browse/CE-680?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs: Add initial nomad-driver-virt driver plugin documentation.

---

.changelog/24316.txt
ui/app/components/variable-paths.js
ui/app/controllers/variables/index.js

I pretty much duplicated the fix performed in https://github.com/hashicorp/nomad/pull/23832 but modified it for Vars instead of Jobs.
Not a JS guy so I could be way off-base here.
[Hopefully] Resolves https://github.com/hashicorp/nomad/issues/24315

[ui] Prevent double-open for cmd+click on vars index links

---

e2e/allocexec/docker_exec_test.go

Sometimes there are leftover/unexpected allocs and the `must.SliceLen` check fails.

e2e: unflake testDockerExecStdin

---

.changelog/24412.txt

This is a changelog entry for #24412

changelog entry for 24412

---

website/content/docs/configuration/vault.mdx

remove duplicated word “Using using”
remove duplicated word “Using using”.

minor: remove duplicated word.

---

e2e/terraform/README.md
e2e/terraform/terraform.tfvars

Update some details of the terraform readme file for e2e provisioning

---

website/content/docs/operations/federation/index.mdx

- Add '#' heading
- Add opening paragraph
- Update front matter description to be more description (for SEO)
Jira: [CE-759]
[Deploy preview](https://nomad-jg5efxna1-hashicorp.vercel.app/nomad/docs/operations/federation)
[CE-759]: …

Docs: Add top-level heading to operations/federation so the page renders correctly

---

website/content/docs/enterprise/sentinel.mdx

docs: fix broken link within enterprise Sentinel docs.

---

e2e/ui/run.sh

In response to the failure in the nightly runner @ https://github.com/hashicorp/nomad-e2e/actions/runs/11906607661/job/33179054461#step:29:42

Updates Playwright in response to an E2E nightly failure

---

website/content/docs/commands/job/index.mdx

Update the job subcommands on the `job` command page

---

CODEOWNERS

Setting a default for codeowners file for PLAT-3161

add default for codeowners file

---

website/content/docs/concepts/security.mdx

The doc title in https://developer.hashicorp.com/nomad/docs/concepts/security is wrong

Fix doc title in security.mdx

---

website/content/docs/enterprise/sentinel.mdx

The title in https://developer.hashicorp.com/nomad/docs/enterprise/sentinel is wrong.

Fix title in sentinel page

---

nomad/periodic_test.go

Test setup for the `TestPeriodicDispatch_Add_TriggersUpdate` test can panic if the goroutine for the runner is running concurrently with adding the job the second time.
Update the test as follows:
* Make a copy when mutating the job before adding it.
* Add a lock around checking if the dispatcher has a waiting eval.
* Update to use `shoenig/test` in lieu of `testify`.
---
Original panic (https://github.com/hashicorp/nomad/actions/runs/12148703441/job/33877901796?pr=24479):
```
=== RUN   TestPeriodicDispatch_Add_TriggersUpdate
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x21abc83]
goroutine 105547 [running]:
github.com/hashicorp/nomad/nomad/structs.(*PeriodicConfig).GetLocation(...) …
```

test: fix panic from concurrent writes in periodic dispatch test

---

website/content/docs/concepts/job.mdx

- Slated for 1.9.4 (17 Dec) release. Merge to `main` only.
- Add clone and edit feature to concepts/jobs page.
- I will add user guide content to the existing jobs page in the tutorials repo. This docs PR can be merged before the tutorials PR. After the tutorials PR has been merged, I will create another PR to update this page to include a tutorials link.
Partial Jira: [CE-741]
Deploy preview: https://nomad-git-ce741-hashicorp.vercel.app/nomad/docs/concepts/job#clone-and-edit …

Docs Feature: Add clone and edit feature

---

nomad/structs/config/workload_id.go

The word `configuration` has been spelled `configuraion`, and in the eyes of one of my illustrious co-workers (Umar Dar) this is a firm tarnishing of the fine work that goes on here and shall not go unresolved in life.

Spelling error

---

CODEOWNERS

Let nomad education and web presence merge PRs to website files

Let nomad education and web presence merge PRs to website files

---

api/tasks.go
command/agent/job_endpoint.go
nomad/structs/diff_test.go
nomad/structs/volumes.go

This changeset includes changes accidentally left out from [24641](https://github.com/hashicorp/nomad/pull/24641).

stateful deployments: add corrections to API structs and methods

---

.release/security-scan.hcl

Ref: [Thread](https://hashicorp.slack.com/archives/CUYKT2A73/p1734461997398449) 🧵 
CRT should pass.

sec: suppress osv alert in CRT

---

website/content/tools/autoscaling/plugins/strategy/threshold.mdx

reported via Slack
Type reported via Slack.
Jira: [CE-802]
[CE-802]: https://hashicorp.atlassian.net/browse/CE-802?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Docs: fix typo in lower_bound

---

website/content/docs/other-specifications/acl-policy.mdx

Add ACL policy documentation for the dynamic host volumes feature.
Ref: https://github.com/hashicorp/nomad/issues/15489
---
Note this PR targets the `dynamic-host-volumes-docs` branch so that we can review all the docs together once we've landed each of the bite-sized chunks.

docs: dynamic host volumes ACL policies

---

e2e/metrics/input/prometheus.hcl

e2e: Account for non-default region in Prometheus scrape config.

---

website/package-lock.json
website/package.json

This fixes an issue with prettier incorrectly causing pre-commit hooks to fail
Fixes an issue raised on the back of #24783 where an older version of prettier was causing the pre-commit hooks to (incorrectly) fail when changes were made to `redirects.js`. 
1. Check out `main` and attempt to commit a change to `redirects.js`
2. Observe that the pre-commit hooks fail (error from Husky and eslint)
3. Check out this branch and verify that the pre-commit hooks pass …

Add override to force prettier 5.0

---

CHANGELOG.md
GNUmakefile
version/version.go

Post release 195 release merge

---

CHANGELOG.md

added 1.7.16+ent and 1.7.17+ent to changelog

---

CHANGELOG.md

add 1.8.9 to changelog

---

nomad/server.go

server: Fix error message format when detailing cluster metadata.

---

website/content/docs/operations/stateful-workloads.mdx

Portworx website no longer has Nomad related documentation.

docs: Remove Portworx state workloads link.

---

.changelog/24739.txt

Adds a changelog entry for PR #24739

changelog: add entry for PR #24739

---

e2e/terraform/provision-infra/outputs.tf

Add the path to the ssh key to connect to the cluster's instances as an output

---

command/quota_apply.go
nomad/state/state_store_host_volumes.go
nomad/state/state_store_host_volumes_ce.go

CE stub method for respective ENT PR hashicorp/nomad-enterprise#2256

dynamic host volumes: stub quota subtraction

---

.release/security-scan.hcl

The change also removes an old suppression which has now been resolved.
Internal thread: https://hashicorp.slack.com/archives/C02V6HVS98E/p1738226446099239

sec: Suppress yamux OSV alert in CRT.

---

.changelog/24985.txt
ui/app/components/job-page/parts/title.js
ui/app/models/job.js
ui/app/routes/jobs/job/index.js
ui/app/templates/components/job-page/parts/title.hbs
ui/mirage/scenarios/default.js
ui/tests/acceptance/job-detail-test.js
ui/tests/pages/jobs/detail.js

Stopped: 
Failed, but once upon a time it was running:
Failed, has always been a failure:
Resolves #24980

[ui] Multi-condition start/revert/edit buttons when a job isn't running

---

website/content/docs/job-specification/sidecar_service.mdx

Removed quotes from keys in meta block example according to [meta block documentation](https://developer.hashicorp.com/nomad/docs/job-specification/meta). 

docs: Corrected meta keys example from sidecar_service documentation

---

.release/security-scan.hcl

sec: Remove yamux suppression as vuln has been revoked.

---

enos/enos-modules.hcl
enos/enos-quality.hcl
enos/enos-scenario-upgrade.hcl
enos/modules/fetch_artifactory/outputs.tf
enos/modules/test_cluster_health/scripts/allocs.sh
enos/modules/upgrade_clients/main.tf
enos/modules/upgrade_clients/scripts/set_metadata.sh
enos/modules/upgrade_clients/scripts/verify_metadata.sh
enos/modules/upgrade_clients/scripts/wait_for_nomad_api.sh
enos/modules/upgrade_clients/variables.tf
enos/modules/upgrade_instance/main.tf
enos/modules/upgrade_instance/variables.tf
enos/modules/upgrade_servers/main.tf

Add module to upgrade clients

---

.github/workflows/semgrep.yml

ci: Update semgrep container version to 1.107.0

---

.changelog/25108.txt
client/config/config.go
client/driver_manager_test.go
client/fingerprint/cpu.go
client/lib/numalib/detect_darwin.go
client/lib/numalib/detect_default.go
client/lib/numalib/detect_linux.go
client/lib/numalib/detect_noimpl_test.go
client/lib/numalib/detect_test.go
client/pluginmanager/drivermanager/testing.go
command/agent/agent.go
command/agent/config.go
drivers/docker/driver_test.go
drivers/docker/fingerprint_test.go
drivers/exec/driver_test.go
drivers/java/driver_test.go
drivers/qemu/driver_test.go
drivers/rawexec/driver_test.go
drivers/shared/executor/executor_test.go
drivers/shared/executor/executor_windows_test.go
website/content/docs/configuration/client.mdx

Add config option to disable dmidecode

---

command/setup_consul.go
command/setup_vault.go
website/content/docs/commands/setup/consul.mdx
website/content/docs/commands/setup/vault.mdx

Jira: https://hashicorp.atlassian.net/browse/NET-10260

cli: Remove warning notes from Vault and Consul setup commands.

---

.github/workflows/backport.yml
.github/workflows/build.yml
.github/workflows/checks.yaml
.github/workflows/release.yml
.github/workflows/security-scan.yml
.github/workflows/test-core.yaml
.github/workflows/test-e2e.yml
.github/workflows/test-failure-notification.yml
.github/workflows/test-ui.yml
.github/workflows/test-windows.yml

Consolidates numerous dependabot PR's into a single PR:
- https://github.com/hashicorp/nomad/pull/24898
- https://github.com/hashicorp/nomad/pull/24899
- https://github.com/hashicorp/nomad/pull/24951
- https://github.com/hashicorp/nomad/pull/24952
- https://github.com/hashicorp/nomad/pull/25001 …

github: update numerous workflow dependencies 

---

ui/package.json
ui/yarn.lock
website/package-lock.json
website/package.json

fix code scanning alert   ws affected by a dos when handling a request with many http headers

---

.changelog/25140.txt

changelog: add entry for #25140

---

client/fingerprint/consul.go

In #24526 we updated Consul and Vault fingerprinting so that we no longer periodically fingerprint. In #25102 we made it so that we fingerprint periodically on start until the first fingerprint, in order to tolerate Consul or Vault not being available on start. For clusters not running Consul, this leads to a warn-level log every 15s. This same log exists for Vault, but Vault support is opt-in via `vault.enable = true` whereas you have to manually disable the fingerprinter for Consul.
Make it so that we only log a failed Consul fingerprint once per Consul cluster. Reset the gate on this once we have a successful fingerprint, so that we get the logs after a reload if Consul is unavailable.
Ref: https://github.com/hashicorp/nomad/pull/24526
Ref: https://github.com/hashicorp/nomad/pull/25102 …

fingerprint: only log failed Consul fingerprint once

---

website/package.json

internal ref https://hashicorp.atlassian.net/browse/SECVULN-13035

[website, prodsec] Pins trim-newlines for the website package

---

command/agent/task_group_host_volume_claim_endpoint.go
command/commands.go
command/meta.go
command/setup_consul.go
command/setup_vault.go
command/volume_claim.go
command/volume_claim_delete.go
command/volume_claim_delete_test.go
command/volume_claim_list.go
command/volume_claim_list_test.go
nomad/fsm.go

CLI for interacting with task group host volume claims.

stateful deployments: task group host volume claims CLI

---

website/content/docs/commands/alloc/stop.mdx

Add note to `stop allocs` for system allocs

---

tools/go.mod
tools/go.sum

deps: Update tool dependencies.

---

website/content/docs/concepts/stateful-deployments.mdx
website/content/docs/job-specification/volume.mdx
website/data/docs-nav-data.json

See https://github.com/hashicorp/nomad/pull/25290 for additional task group host volume claims documentation.

stateful deployments: concept and jobspec documentation

---

.changelog/24683.txt

Adding CVE description in the changelog.

update: changelog 24683.txt

---

CHANGELOG.md

update: changelog 1.9.6

---

CHANGELOG.md
GNUmakefile
version/version.go

release: post 1.9.7 release merge

---

enos/README.md

Add instructions to add new workloads to the tests.

---

e2e/terraform/provision-infra/provision-nomad/etc/consul.d/servers.hcl

Set the default policy to deny for consul ACLs on e2e cluster

---

ui/package.json
ui/yarn.lock

[ui, prodsec] Upgrade the ember-auto-import pin to fix the postcss->nanoid chain

---

.github/workflows/build.yml

Internal ref: https://hashicorp.atlassian.net/browse/NET-10276
Build workflow run: https://github.com/hashicorp/nomad/actions/runs/13923797456

build: smoke test on RHEL8 instead of RHEL7

---

enos/enos-vars.hcl

Declare license input variables as sensitive

---

e2e/terraform/provision-infra/scripts/bootstrap-consul.sh
e2e/terraform/provision-infra/scripts/setup-consul-wi.sh

The previous logic used in the bootstrap scripts was not evaluating correctly, leading to incorrect auth method configuration.

e2e: fix consul e2e enterprise logic in bootstrapping

---

client/servers/manager_internal_test.go
client/servers/manager_test.go

test: Move client server manager tests to use must library.

---

nomad/host_volume_endpoint.go
nomad/host_volume_endpoint_test.go

Testing found that if you create or register a dynamic host volume in a non-existing namespace, the volume gets created on the client but then we can't write it to state. Add a check for this in the initial validation.
changelog entry using the `make cl` command.~ unshipped feature
Also:
```
$ nomad volume create -namespace foo ./internal-plugin.volume.hcl
Error creating volume: Unexpected response code: 500 (volume validation failed: no such namespace "foo")
``` …

dynamic host volumes: enforce that namespace exists

---

CHANGELOG.md

Add changelogs for 1.9.8+ent and 1.8.12+ent

Add changelogs for 1.9.8+ent and 1.8.12+ent

---

website/content/docs/release-notes/nomad/v1_8_x.mdx
website/content/docs/release-notes/nomad/v1_9_x.mdx
website/content/docs/upgrade/upgrade-specific.mdx
website/content/partials/release-notes/v1-10/breaking-vault-consul-token.mdx

Update links in 1.9, 1.8 release notes and specific upgrade details to point to correct, prior version docs.
Note that deploy previews do not generate the previous version docs, so visual confirmation of code will have to suffice.
Jira: [CE-845] …

Docs: Update links in prior version release notes and specific upgrade details to point to prior version docs

---

main.go

Remove a useless comment to run a test of the build and backport workflows.
Ref: https://hashicorp.atlassian.net/browse/NET-11804
Ref: https://hashicorp.atlassian.net/browse/NET-10556

workflow test for builds and backports

---

nomad/state/state_store_test.go

While working on #25726, I explored a hypothesis that the problem could be in the state store, but this proved to be a dead end. While I was in this area of the code I migrated the tests to `shoenig/test`.
Ref: https://github.com/hashicorp/nomad/pull/25726

testing: state store test improvements around deployments

---

client/acl_test.go

Avoids cache invalidation race. 
Internal ref: https://hashicorp.atlassian.net/browse/NMD-557

client: unflake TestClient_ACL_ResolveToken_InvalidClaims

---

website/content/docs/operations/garbage-collection.mdx
website/data/docs-nav-data.json

Add page explaining garbage collection.
This is based on:
- [Nomad’s internal garbage collection and optimization discovery during the
Nomad Bench project blog post](https://www.hashicorp.com/en/blog/nomad-garbage-collection-optimization-discovery-during-nomad-bench)
- Internal doc from Austin Workman. See the Jira ticket for the doc link. 
Jira: [CE-746] [NET-9333]
GitHub: https://github.com/hashicorp/nomad/issues/13037
Deploy preview: https://nomad-git-ce746garbage-hashicorp.vercel.app/nomad/docs/operations/garbage-collection
the [website README](../website/README.md) for docs guidelines. Please also consider …

Docs: Add garbage collection page

---

website/content/intro/index.mdx

This updates the existing iframe for youtube to a `VideoEmbed` component. This is so we can standardize how we are serving and tracking video plays across DevDot.
Related PR: https://github.com/hashicorp/dev-portal/pull/2699

Update iframe to VideoEmbed

---

enos/modules/upgrade_client/scripts/verify_allocs.sh

Fix typo on check allocs script

---

enos/modules/upgrade_client/scripts/verify_allocs.sh

Nojira upgrade3

---

enos/modules/upgrade_client/scripts/verify_allocs.sh

jq requires the raw option to output json as string, the missing flag was causing some comparisons to fail.

Fix the verify alloc script

---

ui/tests/pages/jobs/job/actions.js

This PR would update a test selector in the job actions test for the HDS `DisclosurePrimitive` to accommodate an upcoming change to the `DisclosurePrimitive`'s DOM structure. 
The HDS `DisclosurePrimitive` needs to update its DOM structure to address existing accessibility issues. More details can be found in the [HDS PR](https://github.com/hashicorp/design-system/pull/2643). This update would cause test failures in the existing Nomad test suite due to certain tests relying on the `hds-disclosure-primitive__content` class.
Previously the `hds-disclosure-primitive__content` element was added and removed from the DOM as the visibility of the primitive changes. The intended change would have this element always be present in the DOM and **only** the content inside this element would be added …

[UI] Update selector of test in job actions

---

enos/enos-scenario-upgrade.hcl

enos: Modify Windows TF variable to match new 2022 value.

---

website/content/docs/concepts/job.mdx

Fix broken link on concepts/job.mdx

Docs bug: Fix broken link on concepts/job.mdx

---

website/content/docs/configuration/server_join.mdx

Documenting that Azure managed identity is supported for cloud auto-join. The`<Note>...</Note>` is copied from the Consul documentation where the same functionality exists.
I successfully tested this with a Nomad cluster running on Azure virtual machine scale-sets. I realized this was likely supported after discovering the same thing on Consul.
See the corresponding docs on Consul https://github.com/hashicorp/consul/blob/0b20fdc682d4d4fa1a77a5519f35b638a110cd0f/website/content/docs/deploy/server/cloud-auto-join.mdx?plain=1#L209
the [website README](../website/README.md) for docs guidelines. Please also consider …

docs: adding note on azure msi for server join

---

CHANGELOG.md

created changelog for 1.9.11

---

CHANGELOG.md

created changelog for 1.8.15

---

CHANGELOG.md
GNUmakefile
version/version.go

Update long lived 1.10.x branch

---

scheduler/reconciler/reconcile_cluster_prop_test.go

In the spirit of #26180
Internal ref: https://hashicorp.atlassian.net/browse/NMD-814

scheduler: property testing of cancelUnneededCanaries

---

website/redirects.js

Add regex redirect to handle 1.9, 1.8 path change from `/nomad/docs/commands` to `/nomad/commands`.
The redirect entry should handle requests like this:
- https://developer.hashicorp.com/nomad/docs/v1.9.x/commands/agent  should redirect to https://developer.hashicorp.com/nomad/commands/1.9.x/agent
- https://developer.hashicorp.com/nomad/docs/v1.8.x/commands/agent  should redirect to https://developer.hashicorp.com/nomad/commands/1.8.x/agent
Merge this PR after these:
- https://github.com/hashicorp/nomad/pull/26251
- https://github.com/hashicorp/nomad/pull/26253
Testing redirects across versions
Local and preview builds only render the most recent version of content for [developer.hashicorp.com](http://developer.hashicorp.com/). To test versioned redirects, you need to verify URLs manually …

Docs: Add redirect to handle new 1.9, 1.8 /commands path

---

GNUmakefile
client/allocrunner/networking_cni.go

ci: Update hclogvet and correctly run across codebase.

---

client/fingerprint/secrets.go
command/agent/config.go
nomad/structs/structs.go
nomad/structs/structs_test.go

Introduces some missing validation for secret names and updates client config for common plugins to match the current naming conventions used in other plugin dirs.

secrets: validate name and update client config

---

website/content/docs/use-cases.mdx

The paragraph contains an incomplete phrase at the end.

fix(docs): remove incomplete phrase fragment

---

.release/security-scan.hcl

security: bypass scan for GO-2025-3829 (#26505)

---

CHANGELOG.md
GNUmakefile
version/version.go

Post 1.10.4 release 1.10.x

---

.gitignore

Zed reference: https://zed.dev/docs/configuring-zed#settings-files

admin: Add Zed project settings dir to gitignore file.

---

command/var_get.go

The cli var get command was getting the wrong value for the feedback when the  request key doesn't exist in the variable.
It addresses [26559](https://github.com/hashicorp/nomad/issues/26559)
Are there any changes to security controls …

Add the correct value for costumer feedback on var error

---

e2e/terraform/provision-infra/compute.tf

Disable IMDSv2 on just the windows test instances for now 

Disable IMDSv2 on windows test instances

---

e2e/client_identity/client_identity_test.go
e2e/client_identity/doc.go

Jira: https://hashicorp.atlassian.net/browse/NMD-787

e2e: Add Client Identity get and renew tests.

---

.golangci.yml
testutil/server.go

Also fixes a configuration error within the golangci-lint config file.

ci: Enable SA5008 linting and fix discovered error.

---

.changelog/26642.txt
api/csi.go
command/agent/csi_endpoint.go
command/volume_register_csi.go
nomad/csi_endpoint.go
nomad/structs/csi.go

Volume registrations were appearing to fail due to returning a nil response object.
Fixes: [GH #26581](https://github.com/hashicorp/nomad/issues/26581)
Are there any changes to security controls (access controls, encryption, logging) in this …

csi: fix volume registration error

---

scheduler/reconciler/reconcile_node.go

Otherwise we will frequently end up with deployments that never complete. 
Targets the feature branch f-system-deployments.

scheduler: check if system job deployment is complete before other guards

---

nomad/volumewatcher/volume_watcher_test.go
nomad/volumewatcher/volumes_watcher_test.go

The TestVolumeWatch_LeadershipTransition test was a little racy and the fix required adding an eventually wrapper to the end of the test. While doing this work, it seemed fit to move the package to the must library also.
Uncovered as a result of https://github.com/hashicorp/nomad/pull/26669. It seems that the library update has sped up the test which meant we raced to the end of the test function and checked the unpublish RPC count before it had been incremented. This failure was seen both on CI and locally.
change …

test: Migrate volumewatcher to must and fix racy test.

---

.changelog/26708.txt
client/allocrunner/health_hook.go
client/allocrunner/health_hook_test.go
nomad/state/state_store.go
nomad/structs/structs.go
scheduler/reconciler/deployments.go
scheduler/reconciler/reconcile_cluster.go
scheduler/reconciler/reconcile_node.go
scheduler/reconciler/reconcile_node_prop_test.go
scheduler/reconciler/reconcile_node_test.go
scheduler/scheduler_sysbatch_test.go
scheduler/scheduler_system.go
scheduler/scheduler_system_test.go

This PR merges the feature branch that contains all the work done on enabling
system deployments. Every commit has been reviewed separately and they each
contain explanations of implementation details. 
RFC: https://go.hashi.co/rfc/nmd-216
Resolves https://github.com/hashicorp/nomad/issues/3644
Supersedes https://github.com/hashicorp/nomad/pull/8841

scheduler: system deployments

---

website/content/docs/job-specification/multiregion.mdx

This link contained an extra `/`. Fix link by removing that.

docs: fix link in multiregion job spec page

---

contributing/README.md

Contributing: Add a section asking contributors to open a Feature Request GH issue before coding.
[Internal Slack thread](https://hashicorp.slack.com/archives/C02V6HVS98E/p1758209701509969)
Are there any changes to security controls (access …

Contributing README: Add section for creating an issue

---

website/content/commands/node-pool/apply.mdx
website/content/commands/node-pool/info.mdx
website/content/commands/node/identity/get.mdx
website/content/docs/architecture/cluster/node-identity.mdx
website/content/docs/concepts/node-identity.mdx
website/content/docs/other-specifications/node-pool.mdx
website/data/commands-nav-data.json
website/data/docs-nav-data.json

Jira: https://hashicorp.atlassian.net/browse/NMD-783

docs: Add node identity concepts page and other missing items.

---

website/content/docs/architecture/storage/host-volumes.mdx

Does what it says, fixes a broken link for the host volume plugin guide.

docs: fix broken link for plugin guide

---

e2e/consulcompat/shared_download_test.go

If the latest Consul version has known bugs that cause failures of the test suite, it is useful to be able to skip this. Otherwise, CI will fail on all PRs and release branches until a new version is released.
Related #26860 

e2e: Add ability to skip known bad Consul versions in compat test.
