client/allocrunner/taskrunner/plugin_supervisor_hook.go

This moves `defer client.Close()` after the check for a non-nil `err` to prevent `Close()` from being called on a nil `CSIPlugin`.

client/allocrunner/taskrunner: client.Close after err check

---

e2e/framework/provisioning/deploy.go
e2e/terraform/packer/linux/provision.sh
e2e/terraform/packer/linux/setup.sh
e2e/terraform/packer/packer-windows.json
e2e/terraform/packer/windows/install-consul.ps1
e2e/terraform/packer/windows/install-vault.ps1
e2e/terraform/packer/windows/provision.ps1

Pulled out of https://github.com/hashicorp/nomad/pull/8748, where the single provisioning script will be responsible for everything including configuration of Consul and Vault, so leaving it as `install-nomad` was goofy but changing it balloons #8748 a bit because git isn't picking up the rename across multiple commits.

e2e: minor rename and cleanup

---

e2e/terraform/compute.tf

Our provisioning process for E2E doesn't require the `depends_on` fields to be
set for client instances, so dropping that field allows all instances to be
started in parallel.
We don't use the extra EBS volumes (they aren't even mounted), so remove them
to reduce costs.

e2e: remove unused EBS volumes and depends_on

---

ui/mirage/common.js
ui/mirage/factories/allocation.js
ui/mirage/factories/job.js
ui/mirage/factories/task-group.js
ui/mirage/serializers/allocation.js

First and foremost, this makes no changes to any tests, mirage scenarios, or application code.
While working off to the side of the topo viz, I needed more control over resource requirements for jobs. Moreover, I needed those resource requirements to propagate down to tasks and be reflected in allocations without tediously updating every model by hand. 
These changes introduce a new `resourceSpec` property on the job factory that:
1. Sets the job group count based on the length of the `resourceSpec` array.
2. Overrides the generic CPU, Memory, Disk, and IOPS requirements for a task.
3. Automatically splits the task group-level resource requirements into task level requirements in a way that isn't a mechanical even split but also guarantees that the aggregate values is still equivalent to …

UI: Allow for setting job resource requirements in via the Mirage job factory

---

website/pages/docs/autoscaling/plugins/target.mdx

related: https://github.com/hashicorp/nomad-autoscaler/pull/258

docs: update Autoscaler AWS target with new purge config option.

---

ui/app/serializers/allocation.js
ui/app/serializers/application.js
ui/app/serializers/job-summary.js
ui/app/serializers/plugin.js
ui/tests/unit/serializers/allocation-test.js
ui/tests/unit/serializers/application-test.js

Fixes #8545 
**Issue**
When streaming logs for a task, the logs will suddenly flip to the logs of a different task for the allocation. When this happens, the entire log output is flipped.
**Reproduction**
1. Run a job with multiple tasks (job file at the bottom)
2. Open the logs for one task in a tab
3. In another tab, open the task detail page of the other tab.
4. Restart the task.
5. Sometimes this will cause the logs of the task being streamed to change to the other tasks
**Root cause**
A few things are important to know to understand the root cause.
1. Tasks are modeled as Fragments.
2. The task logs page watches the allocation, which means whenever it changes server-side it is reloaded client-side.
3. `TaskStates` in the API response are a `map[string]interface{}` that get converted …

UI: Fix bug where task logs would suddenly switch to another task's logs

---

nomad/deployment_endpoint.go

check ACLs against deployment namespace on Deployment.GetDeployment, filtering the deployment if the ACL isn't appropriate

GetDeployment should not return 500 error

---

e2e/metrics/prometheus.go

When running the Fabio and Prometheus jobs for the metrics suite
it seems the outer directory is required in the call when
registering the job.
error: "e2e/input/fabio.nomad: no such file or directory"

e2e: fix failure in running metrics test suite jobs.

---

nomad/job_endpoint_oss.go
nomad/job_endpoint_test.go

if `err` is nil, then doing `err.Error()` triggers a panic.

fix: panic introduced by #8453

---

.circleci/config.yml
.circleci/config/config.yml
README.md
command/agent/http_test.go
drivers/shared/executor/pty_unix.go
scripts/release/mac-remote-build
scripts/update_golang_version.sh
scripts/vagrant-linux-priv-go.sh

This upgrades Nomad to use Golang 1.15.
Golang 1.15 introduced two changes that got addressed in the PR.  One is very tiny affecting the error type.
The more significant one is handling of `Ctty` in child processes.  Starting with golang 1.5, setting Ctty value result in `Setctty set but Ctty not valid in child` error, as part of golang/go#29458 .  This commit here lifts the fix in creack/pty#97 .

Upgrade to golang 1.15

---

api/api.go
api/api_test.go
vendor/github.com/hashicorp/nomad/api/api.go

Fixes #8009 
Copy Consul API's format: QueryOptions.WithContext(context) will now return a new QueryOption whose HTTP requests will be canceled with the context provided, and the same for WriteOptions

Add API support for cancelation contexts passed via QueryOptions and WriteOptions

---

nomad/job_endpoint.go
nomad/job_endpoint_oss.go

#8834 introduced a variable into nomad/job_endpoint_oss.go (OSS-only), which is used by nomad/job_endpoint_test.go (OSS and Ent), causing Ent builds to break
this moves that variable out of oss-only build into shared file

moved shared variable into shared-build file

---

e2e/rescheduling/helpers.go
e2e/rescheduling/input/norescheduling.nomad
e2e/rescheduling/input/rescheduling_canary.nomad
e2e/rescheduling/input/rescheduling_canary_autorevert.nomad
e2e/rescheduling/input/rescheduling_default.nomad
e2e/rescheduling/input/rescheduling_fail.nomad
e2e/rescheduling/input/rescheduling_maxp.nomad
e2e/rescheduling/input/rescheduling_maxp_autorevert.nomad
e2e/rescheduling/input/rescheduling_progressdeadline.nomad
e2e/rescheduling/input/rescheduling_success.nomad
e2e/rescheduling/input/rescheduling_system.nomad
e2e/rescheduling/input/rescheduling_update.nomad
e2e/rescheduling/rescheduling.go

The rescheduling test workloads were created before we had Windows targets in
the E2E nightly run. When these were recently ported to the e2e framework (#8860) they
were missing the constraint to Linux machines.
Also added a little extra time to polling to avoid some flakiness on the first
run, and a minor readability adjustment to the job names.
<details><summary>Test results vs a full nightly cluster</summary>
```
$ NOMAD_E2E=1 go test -v . -suite Rescheduling
=== RUN   TestE2E/Affinity
framework.go:181: skipping suite 'Affinity': only running suite "Rescheduling"
=== RUN   TestE2E/clientstate
framework.go:181: skipping suite 'clientstate': only running suite "Rescheduling"
=== RUN   TestE2E/Connect
framework.go:181: skipping suite 'Connect': only running suite …
```

e2e: constrain rescheduling test workloads to Linux

---

nomad/job_endpoint_hook_expose_check.go
nomad/job_endpoint_hook_expose_check_test.go

In #7800, Nomad would automatically generate a port label for service
checks making use of the expose feature, if the port was not already
set. This change assumed the group network would be correctly defined
(as is checked in a validation hook later). If the group network was
not definied, a panic would occur on job submisssion. This change
re-uses the group network validation helper to make sure the network
is correctly definied before adding ports to it.
Fixes #8875

consul/connect: validate group network on expose port injection

---

command/agent_monitor.go

The `nomad monitor` help has a formatting issue because of tabs in the string which should be spaces.
Before:
```
Usage: nomad monitor [options]
Stream log messages of a nomad agent. The monitor command lets you
listen for log levels that may be filtered out of the Nomad agent. For
example your agent may only be logging at INFO level, but with the monitor
command you can set -log-level DEBUG
General Options:
-address=<addr>
The address of the Nomad server.
Overrides the NOMAD_ADDR environment variable if set.
Default = http://127.0.0.1:4646
```
After:
```
Usage: nomad monitor [options]
Stream log messages of a nomad agent. The monitor command lets you
listen for log levels that may be filtered out of the Nomad agent. For
example your agent may only be logging at INFO level, but with the …
```

Change tabs to spaces in `nomad monitor` help text

---

scheduler/generic_sched_test.go
scheduler/reconcile_util.go

This is a band-aid fix for a case where an alloc has been rescheduled but somehow is left in a running state.  In such case, currently, the alloc is left running uninterrupted as it is removed from consideration by the scheduler.  The alloc will remain running uninterrupted even after a new job version is pushed, resulting into a mixed fleet.  Currently, operators need to manually force stop these "leaked" allocations.
This PR fixes the issue by reconsidering an alloc that has been rescheduled but is still running for scheduling purposes.  The check in reconciler_util.go meant that once an allocation is rescheduled, forever it will never be examined again as it's removed from the untainted allocations.
It is very unclear how an alloc can get into this state.  In all of my testing so far, …

Stop already rescheduled but somehow running allocs

---

scheduler/generic_sched_test.go
scheduler/reconcile.go

Revert the `requireCanary` check introduced in https://github.com/hashicorp/nomad/pull/8691/files#diff-1801138ac4d10f2064ba6f2e434ac9b4L430-R431 .
The change was intended to fix a case where a canary alloc may fail to
be rescheduled if all the other allocs fail as well (e.g. if all allocs
happen to be placed on a node that died).
However, it introduced some unintended side-effects: if all allocs of a successful deployment fail, the scheduler will place canary allocs unexpectedly if the service has a single alloc that is to be migrated. Services with multiple allocations can be affected if all allocations are to be migrated or lost at once (e.g. all happen to run on a single client that is drained).
I added a test case for the failure, and it's failing in …

scheduler: Revert requireCanary logic

---

ui/app/utils/generate-exec-url.js
ui/tests/unit/utils/generate-exec-url-test.js

This closes #8769. This new-window-opening code is not possible
to properly exercise within Ember’s testing facilities 😞

UI: Add handling for allocation-less exec URL

---

website/pages/docs/autoscaling/agent.mdx

The Datadog telemetry example does not use the right attribute names.
I'm not sure what name you want to use, if it is the name of the example that is incorrect or the attributes defined in the [Nomad autoscaler project](https://github.com/hashicorp/nomad-autoscaler/blob/master/agent/config/config.go#L141). Nomad agent use `datadog_address` and `datadog_tags`, Nomad autoscaler use `dogstatsd_address` and `dogstatsd_tags`.

docs: Fix Nomad autoscaler Datadog telemetry example

---

api/allocations.go
vendor/github.com/hashicorp/nomad/api/allocations.go

Allocation requests should target servers, which then can forward the
request to the appropriate clients.
Contacting clients directly is fragile and prune to failures: e.g.
clients maybe firewalled and not accessible from the API client, or have
some internal certificates not trusted by the API client.
FWIW, in contexts where we anticipate lots of traffic (e.g. logs, or
exec), the api package attempts contacting the client directly but then
fallsback to using the server.  This approach seems excessive in these
simple GET/PUT requests.
Fixes https://github.com/hashicorp/nomad/issues/8894

api: target servers for allocation requests

---

command/node_status.go

Fixes https://github.com/hashicorp/nomad/issues/8901
Volume requests can be either CSI or host volumes, so when displaying the CSI
volume info for `nomad node status -verbose` we need to filter out the host
volumes.

filter volumes by type in 'nomad node status' output

---

client/fingerprint/env_aws.go
client/fingerprint/env_aws_test.go

If available, get the first IPv6 address assigned to the `eth0` interface via the AWS metadata API.  This gives access to `attr.unique.platform.aws.public-ipv6` for variable interpolation.

Add AWS `mac` address and `public-ipv6`

---

e2e/terraform/README.md
e2e/terraform/config/dev-cluster/consul/server/server.json
e2e/terraform/packer/linux/provision.sh
e2e/terraform/userdata/ubuntu-bionic.sh
e2e/terraform/userdata/windows-2016.ps1

A few minor items pulled out of https://github.com/hashicorp/nomad/pull/8748 to reduce the line count slightly:
* remove outdated references to envchain in documentation
* add new host volume locations in userdata
* don't exit the entire script during provisioning, just return

e2e: documentation and minor tweaks to configs

---

website/pages/docs/job-specification/proxy.mdx

Since the default value for `local_service_port` depends on the parent service, I used the same syntax `<varies>` syntax as [`reschedule.attempts`](https://www.nomadproject.io/docs/job-specification/reschedule#attempts).
Before:
After

docs: fix type for `local_service_port`

---

ui/tests/acceptance/job-deployments-test.js

I believe this test became flaky after #8833, you can see
an example failure here:
https://app.circleci.com/pipelines/github/hashicorp/nomad/11809/workflows/0dc3c8f4-187c-44af-8bdb-6f010d653081/jobs/100848
My understanding is the aim here is not to assert that the
first task group in the server database matches the first
row displayed, but that before #8833 it could be assumed
that they did match. This changes to find the row corresponding
to the first server task group instead of assuming it’ll
be first.

UI: Change compared page object to match by name

---

client/rpc.go
nomad/structs/structs.go

The current implementation measures RPC request timeout only against
config.RPCHoldTimeout, which is fine for non-blocking requests but will
almost surely be exceeded by long-poll requests that block for minutes
at a time.
This adds an HasTimedOut method on the RPCInfo interface that takes into
account whether the request is blocking, its maximum wait time, and the
RPCHoldTimeout.

RPC Timeout/Retries account for blocking requests

---

.circleci/config.yml
.circleci/config/workflows/build-test.yml

Branches for the e2e code base can't have impact on the unit tests, so running
those tests just extends the time it takes to ship e2e updates. This changeset
updates the CircleCI config so that e2e branches run linting, build the
binary, and run the e2e unit tests (currently just vault compatibility).

CI: exclude unit test runs from e2e branches

---

e2e/terraform/config/dev-cluster/nomad/client-windows/client-windows.hcl

The `dev-cluster` profile doesn't include a Windows client configuration, which means you can't easily test a Windows client by swapping out `windows_client = 1` like you could before. This changeset fixes that by copying over the one from `full-cluster`

e2e: make sure dev-cluster has the option to run windows config

---

e2e/rescheduling/rescheduling.go

Fixes https://github.com/hashicorp/nomad/issues/8895
The conditional around some of the rescheduling tests was backwards, where we
were waiting for allocations to be rescheduled but testing for a count of
0. The test was passing but flaky because if the check happened quickly enough
before the scheduler rescheduled the allocations, it would pass.
---
```
$ NOMAD_E2E=1 go test -v . -suite=Rescheduling
...
=== RUN   TestE2E/Rescheduling
=== RUN   TestE2E/Rescheduling/*rescheduling.RescheduleE2ETest
=== RUN   TestE2E/Rescheduling/*rescheduling.RescheduleE2ETest/TestDefaultReschedule
=== RUN   TestE2E/Rescheduling/*rescheduling.RescheduleE2ETest/TestNoReschedule
=== RUN   TestE2E/Rescheduling/*rescheduling.RescheduleE2ETest/TestNoRescheduleSystem
=== RUN …
```

e2e: reschedule tests should check for non-zero rescheduled allocs

---

e2e/e2e_test.go
e2e/nodedrain/input/drain_deadline.nomad
e2e/nodedrain/input/drain_ignore_system.nomad
e2e/nodedrain/input/drain_migrate.nomad
e2e/nodedrain/input/drain_simple.nomad
e2e/nodedrain/nodedrain.go

Fixes https://github.com/hashicorp/nomad/issues/8639 and https://github.com/hashicorp/nomad/issues/8843
Exercise the `nomad node drain` features, driving them via the new CLI helpers.

E2e node drain tests

---

ui/app/components/job-page/parts/children.js
ui/app/components/job-row.js
ui/app/models/job.js
ui/app/routes/jobs/job/index.js
ui/app/serializers/job.js
ui/app/templates/components/job-page/parts/children.hbs
ui/app/templates/components/job-row.hbs
ui/mirage/factories/job.js
ui/tests/acceptance/job-detail-test.js
ui/tests/helpers/module-for-job.js
ui/tests/integration/components/job-page/parts/children-test.js
ui/tests/integration/components/job-page/periodic-test.js
ui/tests/pages/jobs/detail.js

This adds three things to improve the job detail pages for periodic and parameterized jobs.
1. Adds the submitted time as a column in the table of job launches.
2. Default sorts by most recent submission.
3. Adds the same page size selector and global page size setting used elsewhere in the UI.

UI: Launched jobs quality of life improvements

---

CHANGELOG.md
nomad/fsm.go
nomad/fsm_test.go

Noticed this error in some production logs, and they were far from
helpful. Changes:
1. Include job ID in logs
2. Wrap errors and log once instead of double log lines
3. Test fsm error handling behavior

core: improve job deregister error logging

---

scheduler/system_sched.go

This was originally mentioned in https://github.com/hashicorp/nomad/pull/8208#discussion_r443067187, and purportedly fixed in #8230, but we noticed our system job appeared to bind on all interfaces instead of the specified `host_network`.
We noticed we were always evaluating to the first half of this conditional which didn't seem right:  https://github.com/hashicorp/nomad/blob/4ba3afa44b389aa1e29743e81a83b33598be95a9/client/allocrunner/networking_cni.go#L170
This is a proposed fix, it seems correct given previous discussion but we are new to Nomad internals.

Fix multi-interface networking in the system scheduler

---

client/client.go

- We previously added these to the client host metrics, but it's useful to have them on all client metrics.
- e.g. so you can exclude draining nodes from charts showing how much memory / CPU capacity your fleet has.

Add node "status", "scheduling eligibility" to all client metrics

---

website/pages/docs/commands/job/run.mdx

Broken escaping:
* https://www.nomadproject.io/docs/commands/job/run#consul-token
* https://www.nomadproject.io/docs/commands/job/run#vault-token
Fixed with this PR:
* https://deploy-preview-8944--nomad-website.netlify.app/docs/commands/job/run#consul-token
* https://deploy-preview-8944--nomad-website.netlify.app/docs/commands/job/run#vault-token

docs: fix escaping in job run env vars

---

.circleci/config/workflows/build-test.yml

We currently have two jobs commented out in ENT because we don't have the test
target configured there. So having the filter attached to one of those jobs
means changes to filters always create a merge conflict.

ci: reduce merge conflict potential in CircleCI config

---

e2e/terraform/README.md
e2e/terraform/nomad.tf
e2e/terraform/packer/linux/provision.sh
e2e/terraform/packer/windows/provision.ps1
e2e/terraform/provision-nomad/main.tf
e2e/terraform/provision-nomad/variables.tf
e2e/terraform/tests/nomad.tf
e2e/terraform/variables.tf

Add a `nomad_enterprise` variable to the Terraform config so that we can pull builds of Nomad Enterprise from S3 after the nightly merge.

e2e: add flags for provisioning Nomad Enterprise

---

e2e/terraform/terraform.tfvars
e2e/terraform/terraform.tfvars.dev
e2e/terraform/userdata/ubuntu-bionic.sh

Newer EC2 instances are cheaper and have generally better performance.
The dnsmasq configuration had a hard-coded interface name, so in order to
accomodate instances with more recent networking that result in so-called
predictable interface names, the dnsmasq configuration needs to be replaced at
runtime with userdata to select the default interface.
--- 
Tested end-to-end:
```
$ nomad server members
Name                     Address        Port  Status  Leader  Protocol  Build       Datacenter  Region
ip-172-31-0-181.global   172.31.0.181   4648  alive   false   2         0.13.0-dev  dc1         global
ip-172-31-1-84.global    172.31.1.84    4648  alive   false   2         0.13.0-dev  dc1         global
ip-172-31-10-115.global  172.31.10.115  4648  alive   true    2         0.13.0-dev …
```

e2e: use more recent instance type

---

CHANGELOG.md
drivers/docker/config.go
website/pages/docs/drivers/docker.mdx

The `docker.config.infra_image` would default to an amd64 container.
It is possible to reference the correct image for a platform using
the `runtime.GOARCH` variable, eliminating the need to explicitly set
the `infra_image` on non-amd64 platforms.
Also upgrade to Google's pause container version 3.1 from 3.0, which
includes some enhancements around process management.
Fixes #8926

drivers/docker: detect arch for default docker plugin infra_image

---

.circleci/config.yml
.circleci/config/workflows/build-test.yml

In https://github.com/hashicorp/nomad/pull/8909 we excluded `e2e` branches from running unit tests, because there's no way for those changes to have unit test impact. But we missed the `test-ui` job.

ci: don't run UI tests for e2e branches

---

command/quota_apply.go
command/quota_apply_test.go
command/quota_init.go

With the deprecation of `mbits` resource, it should be removed from quotas as well.

command: remove mbits from quota hcl

---

e2e/terraform/README.md
e2e/terraform/acls/anonymous.policy.hcl
e2e/terraform/acls/bootstrap-nomad.sh
e2e/terraform/config/shared/README.md
e2e/terraform/config/shared/nomad-acl.hcl
e2e/terraform/nomad-acls.tf
e2e/terraform/nomad.tf
e2e/terraform/outputs.tf
e2e/terraform/packer/linux/provision.sh
e2e/terraform/packer/windows/provision.ps1
e2e/terraform/provision-nomad/main.tf
e2e/terraform/provision-nomad/variables.tf
e2e/terraform/terraform.tfvars
e2e/terraform/variables.tf

Adds a `nomad_acls` flag to our Terraform stack that bootstraps Nomad ACLs via
a `local-exec` provider. There's no way to set the `NOMAD_TOKEN` in the Nomad
TF provider if we're bootstrapping in the same Terraform stack, so instead of
using `resource.nomad_acl_token`, we also bootstrap a wide-open anonymous
policy. The resulting management token is exported as an environment var with
`$(terraform output environment)` and tests that want stricter ACLs will be
able to write them using that token.
This should also provide a basis to do similar work with Consul ACLs in the
future.

e2e: add flag to bootstrap Nomad ACLs

---

e2e/e2eutil/allocs.go
e2e/e2eutil/deployments.go
e2e/nodedrain/nodedrain.go
e2e/rescheduling/rescheduling.go
e2e/volumes/volumes.go

Required to support tests for namespaces and other ENT features.

e2e: namespace support for CLI helpers

---

CHANGELOG.md
client/allocrunner/taskrunner/script_check_hook.go
client/allocrunner/taskrunner/script_check_hook_test.go
nomad/job_endpoint_test.go
nomad/structs/structs.go
nomad/structs/structs_test.go
website/pages/docs/job-specification/service.mdx

When defining a script-check in a group-level service, Nomad needs to
know which task is associated with the check so that it can use the
correct task driver to execute the check.
This PR fixes two bugs:
1) validate service.task or service.check.task is configured
2) make service.check.task inherit service.task if it is itself unset
Fixes #8952

consul: fix validation of task in group-level script-checks

---

nomad/fsm.go
nomad/state/node_events.go
nomad/state/node_events_test.go
nomad/state/state_changes.go
nomad/state/state_store.go
nomad/structs/structs.go

events for node drain and node events

Node Drain and Node Events events

---

drivers/docker/driver.go

Partial #8932 (needs docs)
NOTE: I'm guessing ideally, the standard messaging in various places (`nomad/structs/structs.go`, `command/alloc_status.go`) with text like 'Sent interrupt' might have to change as well, but maybe that can be part of a bigger discussion. For now, I think updating the default from SIGINT to SIGTERM makes sense.
References: https://www.nomadproject.io/docs/job-specification/task#kill_signal, https://docs.docker.com/engine/reference/commandline/stop/

drivers/docker/driver.go: change default signal for docker driver to SIGTERM?

---

client/config/config.go

Host with systemd-resolved have `/etc/resolv.conf` is a symlink to `/run/systemd/resolve/stub-resolv.conf`. By bind-mounting /etc/resolv.conf only, the exec container DNS resolution fail very badly.
This change fixes DNS resolution by binding /run/systemd/resolve as well.
Note that this assumes that the systemd resolver (default to 127.0.0.53) is accessible within the container. This is the case here because exec containers share the same network namespace by default.
Jobs with custom network dns configurations are not affected, and Nomad will continue to use the job dns settings rather than host one.
Anecdote about systemd and docker: In a docker container, the host systemd resolver isn't accessible, as each container is in separate namespace.  So docker copies …

drivers/exec: fix DNS resolution in systemd hosts

---

api/scaling.go
api/scaling_test.go
nomad/fsm.go
nomad/job_endpoint_test.go
nomad/mock/mock.go
nomad/state/schema.go
nomad/state/schema_test.go
nomad/state/state_store.go
nomad/state/state_store_test.go
nomad/structs/funcs.go
nomad/structs/structs.go
nomad/structs/structs_oss.go
nomad/structs/structs_test.go
vendor/github.com/hashicorp/nomad/api/scaling.go

This PR introduces a new field to allow specifying the type of scaling a policy provides. Currently the only policy type available is `horizontal` and existing policies are automatically assigned this value on snapshot restore. With this new field, scaling policy uniqueness is now determined by its target and type.

Add scaling policy type

---

client/fs_endpoint_test.go

This fixes two spots in `client` where the file permissions were being set to `777` instead of `0777`, so it was evaluating to `01411`.

client: fix test umask

---

e2e/nodedrain/nodedrain.go
e2e/rescheduling/rescheduling.go
e2e/volumes/volumes.go

The E2E framework wraps testify's `require` so that by default we can stop
tests on errors, but the cleanup functions should use `assert` so that we
continue to try to cleanup the test environment even if there's a failure.

e2e: cleanup errors should use assert, not require

---

e2e/lifecycle/inputs/batch.nomad
e2e/lifecycle/inputs/service.nomad
e2e/podman/input/redis.nomad
e2e/volumes/input/volumes.nomad

Until we have LCOW (#2633) support in the E2E environment (which requires a Windows
2019 test target #7767), we need to constrain E2E tests to the appropriate kernel.

e2e: ensure tests are constrained to Linux

---

drivers/java/driver_test.go
drivers/shared/executor/executor_test.go

Symlinking busybox may fail when the test code and the test temporary
directory live on different volumes/partitions; so we should copy
instead.  This situation arises in the Vagrant setup, where the code
repository live on special file sharing volume.
Somewhat unrelated, remove `f.Sync()` invocation from a test copyFile
helper function.  Sync is useful only for crash recovery, and isn't
necessary in our test setup.  The sync invocation is a significant
overhead as it requires the OS to flush any cached writes to disk.
Related to #8970

tests: failover to copying when symlinking fails

---

CHANGELOG.md
api/resources.go
command/agent/job_endpoint_test.go
nomad/structs/structs.go
nomad/structs/structs_test.go
vendor/github.com/hashicorp/nomad/api/resources.go

Since CPU resources are usually a soft limit it is desirable to allow
setting it as low as possible to allow tasks to run only in "idle" time.
Setting it to 0 is still not allowed to avoid potential unintentional
side effects with allowing a zero value. While there may not be any side
effects this commit attempts to minimize risk by avoiding the issue.
This does *not* change the defaults.

jobspec: lower min cpu resources from 10->1

---

website/pages/api-docs/volumes.mdx

`nomad volume detach volume-id 00000000-0000-0000-0000-000000000000` produces an API call containing the UUID as part of the query string. This is the only way the API accepts the request correctly - if you pass it in the payload you get `detach requires node ID`

Fix docs on API for volume detaching

---

e2e/terraform/terraform.tfvars.dev

The `-var-file` flag for loading variables into Terraform overlays the default
variables file if present. This means that variables that are set in the
default variables file will take precedence if the overlay file does not have
them set.
Set `nomad_acls` and `nomad_enterprise` to `false` in the dev cluster.
ref [Variable Definition Precedence docs](https://www.terraform.io/docs/configuration/variables.html#variable-definition-precedence) and a very confused hour of my afternoon

e2e: tfvars.dev file must override default tfvars file

---

CHANGELOG.md
drivers/docker/driver.go
drivers/docker/driver_test.go
website/pages/docs/upgrade/upgrade-specific.mdx

This PR adds a version specific upgrade note about the docker stop
signal behavior. Also adds test for the signal logic in docker driver.
Closes #8932 which was fixed in #8933
tagging @jf

docs: document docker signal fix, add tests

---

CHANGELOG.md
client/allocrunner/taskrunner/envoybootstrap_hook.go
client/allocrunner/taskrunner/template/template.go
nomad/structs/config/consul.go
website/pages/docs/configuration/consul.mdx

Currently Nomad has the option of setting a global [Vault namespace configuration](https://www.nomadproject.io/docs/configuration/vault#namespace)
This PR brings feature parity, by allowing a global option to be set for [Consul namespaces](https://www.consul.io/docs/enterprise/namespaces) in the [consul configuration](https://www.nomadproject.io/docs/configuration/consul)

[Feature] Configure nomad cluster to use a Consul Namespace [Consul Enterprise]

---

CHANGELOG.md
website/pages/docs/configuration/consul.mdx

In support of https://github.com/hashicorp/nomad/pull/8849

docs: add Consul policy for Consul Namespace support

---

client/fingerprint/env_azure.go
client/fingerprint/env_azure_test.go

The name metadata doesn't always match the hostname. In the case of scale sets the value will be "{scale-set-name}_{instance-id}" and the hostname would  "{computer-name-prefix}{base-36-instance-id}".  Azure metadata service doesn't have metadata for hostname.

Change Azure attribute for hostname to name

---

command/agent/agent.go
command/agent/keyring.go
command/agent/keyring_test.go
command/agent/testagent.go
command/operator_keygen.go
command/operator_keygen_test.go
website/pages/docs/commands/operator/keygen.mdx
website/pages/docs/configuration/server.mdx

Nomad's gossip protocol utilizes AES GCM under-the-hood for encryption which relies on [`crypto/aes`](https://golang.org/pkg/crypto/aes/#NewCipher). The 16-byte key currently used enables AES-128, while a 32-byte key enables AES-256. The larger key size is ultimately preferable from a security standpoint, and this PR updates the CLI key generation command + documentation to reference/use 32-byte keys.
Consul already defaults to generating a 32-byte gossip key: https://github.com/hashicorp/consul/commit/1a14b94441dbd715fcb83d78c99fe87de9ad01ea

Use 32-byte key for gossip encryption to enable AES-256 

---

CHANGELOG.md
api/jobs_test.go
command/agent/command.go
command/agent/command_test.go
nomad/structs/structs.go
nomad/structs/structs_test.go
website/pages/docs/upgrade/upgrade-specific.mdx

resolves #8796 
null characters in region, datacenter, job ID/name, task group name, and task name can break a lot of things, including:
* memdb compound indexing
* default task environment variables
changelog summary:
* d4ef12e42ebfde8575caa86e8b649cf0d6fcb2e5 is a documenting test
* 39c73f1b3256b1f780d329de381a3bf2d1a21d9b introduces the additional validation, but fails, because other tests actually rely on the ability to use null characters 😦 . also, updates CHANGELOG and upgrade guide.
* 5062e74b3e644887ffc39b41e07f341c1ba9af47 relaxes the tests which protect this backwards compatibility
* b0c2e5176a8e0dff88c152460f3d59f9310df62a adds additional tests for agent Region and Datacenter, as well as Job.Name

job, task group, and task IDs should not allow null characters

---

nomad/structs/services.go
nomad/structs/services_test.go
nomad/structs/structs.go
nomad/structs/structs_test.go
scheduler/util.go
scheduler/util_test.go

This PR fixes a long standing bug where submitting jobs with changes
to connect services would not trigger updates as expected. Previously,
service blocks were not considered as sources of destructive updates
since they could be synced with consul non-destructively. With Connect,
task group services that have changes to their connect block or to
the service port should be destructive, since the network plumbing of
the alloc is going to need updating.
Fixes #8596 #7991
Non-destructive half in #7192

consul/connect: trigger update as necessary on connect changes

---

command/commands.go
command/scaling.go
command/scaling_policy.go
command/scaling_policy_info.go
command/scaling_policy_info_test.go
command/scaling_policy_list.go
command/scaling_policy_list_test.go
command/scaling_policy_test.go

This adds the ability to detail scaling policies via the CLI.
Relates #8649
Docs to be added in future PR.

cli: add policy list and info to new scaling cmd.

---

command/agent/consul/catalog_testing.go
command/agent/consul/client.go

When deregistering a service, consul also deregisters the associated
checks. The current state keeps track of all services and all checks
separately and deregisters them in sequence, which leads, whether during
syncs or shutdowns, to check deregistrations happening twice and failing
the second time (generating errors in logs)
This fix includes:
- a fix to the sync logic that just pulls the checks *after* the
services have been synced
- a fix to the shutdown mechanism that gets an updated list of checks
after deregistering the services, so that we get a cleaner check
deregistration process.

Do not double-remove checks removed by Consul

---

api/operator.go
command/commands.go
command/metrics.go
command/metrics_test.go
command/operator_debug.go
command/operator_debug_test.go
vendor/github.com/hashicorp/nomad/api/operator.go

This PR adds a `metrics.json` file to each interval captured by the `nomad operator debug` command.  A new CLI sub-command `nomad operator metrics` and associated plumbing was added to support this feature, and also allow easier access for operators to gather metrics requested by support.  Data is retrieved using the existing `/v1/metrics` API endpoint.
Future improvements will optionally collect metrics from each server/client node specified.

Add metrics command / output to debug bundle

---

command/commands.go
command/job_scale.go
command/job_scale_test.go
command/job_scaling_events.go
command/job_scaling_events_test.go

This adds the ability to scale Nomad jobs and view scaling events
via the CLI.
Relates #8648 
Docs to be added in future PR.

cli: add scale and scaling-events commands to job cmd.

---

CHANGELOG.md
nomad/csi_endpoint_test.go
nomad/structs/csi.go
nomad/structs/csi_test.go
scheduler/feasible_test.go

Fixes https://github.com/hashicorp/nomad/issues/8968
Fixes a bug where CSI volumes with the `MULTI_NODE_MULTI_WRITER` access mode
were using the same logic as `MULTI_NODE_SINGLE_WRITER` to determine whether
the volume had writer claims available for scheduling.

csi: allow more than 1 writer claim for multi-writer mode

---

CHANGELOG.md
command/volume_detach.go

Fixes https://github.com/hashicorp/nomad/issues/8963
Fixes a bug where the `nomad volume detach` command would not accept a node ID
prefix instead of a full node ID. The volume ID is already prefix matched
server-side.

csi: allow volume detach to take a node ID prefix

---

website/pages/docs/commands/volume/register.mdx
website/pages/docs/job-specification/volume.mdx

Partial fix for https://github.com/hashicorp/nomad/issues/9021
The CSI specifcation allows only the `file-system` attachment mode to have
mount options. The `block-device` mode is left "intentionally empty, for now"
in the protocol. We should be validating against this problem, but our
documentation also had it backwards.
Also adds missing docs for `mount_options` on the group's `volume` spec.
Fixing the validation is in https://github.com/hashicorp/nomad/pull/9044

docs: CSI mount_options are available only for filesystem vols

---

CHANGELOG.md
nomad/csi_endpoint_test.go
nomad/structs/csi.go

Partial fix for https://github.com/hashicorp/nomad/issues/9021
Volumes using attachment mode `file-system` use the CSI filesystem API when
they're mounted, and can be passed mount options. But `block-device` mode
volumes don't have this option. When RPCs are made to plugins, we are silently
dropping the mount options we don't expect to see, but this results in a poor
operator experience when the mount options aren't honored. This changeset
makes passing mount options to a `block-device` volume a validation error
as opposed to a run-time error.
This doesn't entirely close-out #9021 because there's a question about how we're
supposed to be reconciling the controller plugin response at runtime, but this solves
a real submission-time problem.

csi: validate mount options during volume registration

---

CHANGELOG.md
plugins/csi/client.go
plugins/csi/client_test.go
website/pages/docs/commands/volume/register.mdx
website/pages/docs/job-specification/volume.mdx

Fixes https://github.com/hashicorp/nomad/issues/9021
The CSI specification for `ValidateVolumeCapability` says that we shall
"reconcile successful capability-validation responses by comparing the
validated capabilities with those that it had originally requested" but leaves
the details of that reconcilation unspecified. This API is not implemented in
Kubernetes, so controller plugins don't have a real-world implementation to
verify their behavior against.
We have found that CSI plugins in the wild may return "successful" but
incomplete `VolumeCapability` responses, so we can't require that all
capabilities we expect have been validated, only that the ones that have been
validated match. This appears to violate the CSI specification but until
that's been resolved in upstream we have to …

csi: loosen ValidateVolumeCapability requirements

---

website/README.md
website/redirects.js

This is a follow-up to https://github.com/hashicorp/nomad/pull/9036
@jescalan and I agreed to update the `redirects.js` file to use a more general-purpose catch-all for our routes ending in `.html` (eg. routes that may have been used with middleman). We lose some granularity in terms of _intent_ for some of our redirects, but according to our Google Analytics, there are still a significant number of routes ending in `.html` that do not properly redirect. This change fixes all of those routes at once, and as an added benefit, makes the redirects file a bit cleaner.

docs: Update redirects to use a broader catch-all for routes ending in .html

---

website/pages/docs/job-specification/csi_plugin.mdx

CSI plugins with the same plugin ID and type (controller, node, monolith) will collide on a host, both in the communication socket and in the dynamic plugin registry. Until this can be fixed, leave notice to operators in the documentation.
Related to https://github.com/hashicorp/nomad/issues/8628. That issue probably isn't going to be fixed before 0.13's beta, so updating the documentation in the meantime.

docs: show distinct_hosts constraint for CSI plugins

---

command/volume_detach.go
website/pages/docs/commands/volume/detach.mdx

Follow-up to https://github.com/hashicorp/nomad/pull/9041
When we try to prefix match the `nomad volume detach` node ID argument, the
node may have been already GC'd. The volume unpublish workflow gracefully
handles this case so that we can free the claim. So make a best effort to find
a node ID among the volume's claimed allocations, or otherwise just use the
node ID we've been given by the user as-is.
ref https://github.com/hashicorp/nomad/blob/v0.12.5/nomad/csi_endpoint.go#L664-L671 for the graceful handling of missing nodes.

csi: allow for volume detach to work with gc'd nodes

---

client/allocrunner/csi_hook.go
nomad/csi_endpoint.go
nomad/volumewatcher/volume_watcher.go

A collection of tiny changes:
* Fix an incorrect comment about `csi_hook` context lifetime and change it from `context.TODO()` to `context.Background()`
* Remove stray TODO comment for work completed in #8626
* Make only one pass to collect past claims in volumewatcher: if a volume GC and a `nomad volume detach` command land concurrently, we can end up with multiple claims without an allocation, which results in extra no-op work when finding claims to collect as past claims.

CSI: comment clarifications and dropping no-op work

---

CHANGELOG.md
nomad/job_endpoint.go
nomad/job_endpoint_oss.go
nomad/state/state_store.go

Stop coercing version of new job to 0 in the state_store, so that we can add
regions to a multi-region deployment. Send new version, rather than existing
version, to MRD to accomodate version-choosing logic changes in ENT.

Allow job Version to start at non-zero value

---

e2e/csi/csi.go
e2e/terraform/network.tf
e2e/terraform/terraform.tfvars
e2e/terraform/terraform.tfvars.dev
e2e/terraform/variables.tf
e2e/terraform/volumes.tf

For everyday developer use, we don't need volumes for testing CSI. Providing a
flag to opt-in speeds up deploying dev clusters and slightly reduces infra costs.

e2e: add flag to opt-in to creating EBS/EFS volumes

---

e2e/terraform/packer/packer.json

Follow-up to https://github.com/hashicorp/nomad/pull/9076
Instead of hard-coding the base AMI for our Packer image for Ubuntu, use the
latest from Canonical so that we always have their current kernel patches.

e2e: use AMI filter for Ubuntu packer image

---

e2e/rescheduling/rescheduling.go

Fixes https://github.com/hashicorp/nomad/issues/8895 (specifically https://github.com/hashicorp/nomad/issues/8895#issuecomment-707083004)
The autorevert test checks for reverted allocations to be placed and running
before checking the deployment status, but the deployment can be completed and
marked "successful" before we check it for "running" status. Instead, just
wait for it to be marked "successful" and assert we have the expected count of
deployment statuses.

e2e: eliminate race condition causing rescheduling test flake

---

.circleci/config.yml
.circleci/config/jobs/test-e2e.yml
.circleci/config/workflows/build-test.yml
GNUmakefile

Currently we compile (but don't run) the e2e tests as part of `test-other`,
which is skipped for branches named `e2e-*`. Move this check into the
`test-e2e` job. Split out the vault compatibility integration check as its own
makefile target for clarity.
Prevents issues like https://github.com/hashicorp/nomad/pull/9089 from slipping by e2e branches and into master.

CI: make split between e2e and integration tests explicit

---

CHANGELOG.md
api/allocations.go
api/allocations_test.go
api/nodes.go
api/nodes_test.go
api/util_test.go
command/agent/alloc_endpoint.go
command/agent/csi_endpoint.go
command/agent/http.go
command/agent/http_test.go
command/agent/node_endpoint.go
nomad/alloc_endpoint.go
nomad/alloc_endpoint_test.go
nomad/deployment_endpoint.go
nomad/deploymentwatcher/deployment_watcher.go
nomad/eval_endpoint.go
nomad/job_endpoint.go
nomad/node_endpoint.go
nomad/node_endpoint_test.go
nomad/state/state_store.go
nomad/structs/structs.go
scheduler/generic_sched.go
scheduler/system_sched.go
vendor/github.com/hashicorp/nomad/api/allocations.go
vendor/github.com/hashicorp/nomad/api/nodes.go
website/pages/api-docs/allocations.mdx
website/pages/api-docs/nodes.mdx

Fixes #9017
The ?resources=true query parameter includes resources in the object stub listings. Specifically:
- For `/v1/nodes?resources=true` both the `NodeResources` and `ReservedResources` field are included.
- For `/v1/allocations?resources=true` the `AllocatedResources` field is included.
The ?task_states=false query parameter removes TaskStates from
/v1/allocations responses. (By default TaskStates are included.)

api: add field filters to /v1/{allocations,nodes}

---

ui/public/robots.txt

Fixing the default robots.txt, similar to hashicorp/consul#8958 & hashicorp/vault#10150.
The path pattern specified in allow / deny lines should start with a forward slash to designate the root.
[1] https://tools.ietf.org/html/draft-koster-rep-00#section-2.2
[2] https://developers.google.com/search/reference/robots_txt

Fix robots.txt to disallow indexing of all paths

---

nomad/rpc.go
nomad/structs/structs.go

The MaxQueryTime value used in QueryOptions.HasTimedOut() can be set to
an invalid value that would throw off how RPC requests are retried.
This fix uses the same logic that enforces the MaxQueryTime bounds in the
blockingRPC() call.

Enforce bounds on MaxQueryTime

---

drivers/docker/config.go
drivers/docker/config_test.go

Fixes https://github.com/hashicorp/nomad/issues/9045
In the Docker driver plugin config for garbage collection, the `image_delay`
field was missing from the default we set if the entire `gc` stanza is
missing. This results in a default of 0s and immediate GC of Docker images.

docker: image_delay default missing without gc stanza

---

command/agent/agent.go

return a validation error if event stream cfg values are negative

event buffer size and durable count must be non negative

---

ui/app/components/loading-spinner.js
ui/app/styles/components/loading-spinner.scss
ui/app/templates/components/loading-spinner.hbs
ui/public/images/icons/nomad-logo-n.svg

I thought it might be nice to have a logo-based loading spinner as a small 1.0 bonus. It has a tiny easter egg: clicking the spinner causes the animation to pause.
A low-resolution GIF of an artificially-inflated loading time including click-to-pause:

UI: Update loading spinner to be logo-based

---

website/pages/intro/use-cases.mdx

Removed ref to [Spark](https://github.com/hashicorp/nomad-spark) based on 
https://github.com/hashicorp/nomad-spark/commit/2c6092a2a6df6236282d2777e7de4a11c76f7cd6

Remove Nomad-spark reference from use-cases.mdx

---

e2e/networking/inputs/basic.nomad

The `e2ejob` utility asserts that a job is running for 5s, but with a sleep
time of 5s, the networking job can race with that check. Sleeping for a longer
period should guarantee that we're running long enough to pass the assert.
Also constrains the job to Linux because our Windows test targets don't yet
support Docker (LCOW), and expand the set of DCs we can safely land on.

e2e: networking test job needs to outlast assert

---

e2e/taskevents/taskevents.go

Fixes https://github.com/hashicorp/nomad/issues/7737
Assert that we get at least N task events, rather than exactly N. When a
task within an allocation dies, a sibling task can get an Allocation Unhealthy
event after it's also killed, even though it's not the origin of the event.

e2e: fix flaky TaskEventsTest

---

website/pages/docs/commands/alloc/fs.mdx
website/pages/docs/configuration/client.mdx
website/pages/docs/drivers/docker.mdx
website/pages/docs/drivers/external/firecracker-task-driver.mdx
website/pages/docs/drivers/external/jail-task-driver.mdx
website/pages/docs/drivers/external/lxc.mdx
website/pages/docs/job-specification/artifact.mdx
website/pages/docs/job-specification/template.mdx
website/pages/docs/runtime/environment.mdx

Fixes https://github.com/hashicorp/nomad/issues/8919
The terms task directory and allocation directory are used throughout the
documentation but these directories are not the same as the `NOMAD_TASK_DIR`
and `NOMAD_ALLOC_DIR` locations. This is confusing when trying to use the
`template` and `artifact` stanzas, especially when trying to use a destination
outside the Nomad-mounted directories for Docker and similar drivers.
This changeset introduces "allocation working directory" to mean the location
on disk where the various directories and artifacts are staged, and "task
working directory" for the task. Clarify how specific task drivers interact
with the task working directory.

docs: clarify task working directories

---

GNUmakefile

-I ../../.. is meant to navigate from `GOPATH/src/github.com/hashicorp/nomad` to `GOPATH/src`
This is fine but it assumes a few things about how the dev has setup nomad, which is also fine if that is the expected dev environment, however the `../../..` is not as explicit as "GOPATH/src" and it would also enable a few more scenarios so it seems strictly better to me.
Random example: nomad is a subrepo of ours, but with this change we can symlink from GOPATH/src/github.com/hashicorp/nomad and `make proto` will work.

Use GOPATH/src explicitly in proto build target

---

tools/go.mod
tools/go.sum

Upstream pushed a commit onto the untagged 0.0.0, which breaks our check for no diffs in the go.mod/go.sum files.

update tree tool to pass lint-go

---

go.mod

Keep go.mod go version up to date with the version of Go used
to build Nomad.

build: update gomod go version

---

e2e/e2e_test.go
e2e/events/events.go
e2e/events/input/deploy.nomad
e2e/events/input/initial.nomad
e2e/events/input/large-job.nomad
nomad/state/events.go
nomad/state/events_test.go

Adds two event stream tests checking for specific Deployment and Eval events
```
--- PASS: TestE2E (34.25s)
--- SKIP: TestE2E/Affinity (0.00s)
--- SKIP: TestE2E/clientstate (0.00s)
--- SKIP: TestE2E/Connect (0.00s)
--- SKIP: TestE2E/ConnectACLs (0.00s)
--- SKIP: TestE2E/Consul (0.00s)
--- SKIP: TestE2E/ConsulTemplate (0.00s)
--- SKIP: TestE2E/CSI (0.00s)
--- SKIP: TestE2E/Deployment (0.00s)
--- PASS: TestE2E/Events (34.25s)
--- PASS: TestE2E/Events/*events.EventsTest (34.25s)
--- PASS: TestE2E/Events/*events.EventsTest/TestBlockedEvalEvents (1.32s)
--- PASS: TestE2E/Events/*events.EventsTest/TestDeploymentEvents (32.89s)
--- SKIP: TestE2E/simple (0.00s)
--- SKIP: TestE2E/Lifecycle (0.00s)
--- SKIP: TestE2E/Metrics (0.00s)
--- SKIP: TestE2E/Networking (0.00s)
--- SKIP: TestE2E/NodeDrain …
```

adds two base event stream e2e tests

---

ui/app/styles/components/loading-spinner.scss

Spinning is one of the triggers mentioned on [this page](https://webkit.org/blog/7551/responsive-design-for-motion/
). Thanks to @fivetanley for mentioning that this exists.
Here’s a GIF showing it working, though the looping is confusing 😐

UI: Remove logo spin for prefers-reduced-motion

---

website/pages/docs/integrations/consul-connect.mdx

Issue #6459 has been fixed for a while, but the docs still point to it as a limitation.
I tested switching ports in a sonarqube installation (postgres mounted in 5432 -> 5431) and it worked cleanly

Remove limitation that has been fixed

---

CHANGELOG.md
client/taskenv/services.go
client/taskenv/services_test.go

Adds onto https://github.com/hashicorp/nomad/pull/9096 for tests, CL, rebase w/ master

consul: add tests for meta/canarymeta interpolation

---

client/allocrunner/alloc_runner.go
client/state/db_test.go
client/state/errdb.go
client/state/interface.go
client/state/memdb.go
client/state/noopdb.go
client/state/state_database.go
helper/boltdd/boltdd.go
nomad/mock/mock.go

Fixes #9047, see problem details there.
As a solution, we use BoltDB's 'Batch' mode that opportunistically combines multiple parallel writes into a small number of transactions. See https://github.com/boltdb/bolt#batch-read-write-transactions for more information.

Implement 'batch mode' for persisting allocations on the client.

---

e2e/terraform/provision-nomad/main.tf

Fixes provisioning bugs I discovered while testing https://github.com/hashicorp/nomad/issues/9129 this morning.
When uploading a local binary for provisioning, the location that we pass into
the provisioning script needs to be where we uploaded it to, not the source on
our laptop. Also, the null_resource for uploading needs to read in the private
key, not its path.

e2e: path fixes for local_binary uploads

---

CHANGELOG.md
client/allocrunner/taskrunner/getter/getter.go
client/allocrunner/taskrunner/getter/getter_test.go
client/allocrunner/taskrunner/template/template.go
client/allocrunner/taskrunner/template/template_test.go
helper/funcs.go
helper/funcs_test.go
website/data/version.js
website/pages/docs/upgrade/upgrade-specific.mdx

For https://github.com/hashicorp/nomad/issues/9129

OSS merge for CVE-2020-27195

---

nomad/core_sched.go

Fixes an issue noticed in https://github.com/hashicorp/nomad/issues/8949#issuecomment-712118627
During CSI plugin GC, we don't return an error if the volume is in use,
because this is not an error condition. If we were to return an error during a
`nomad system gc`, we would not continue on to GC volumes.
But the check for the specific error message fails if the GC is performed on a
worker rather than on the leader, due to RPC forwarding wrapping the error
message. Use a less specific test so that we don't return an error.

csi: prevent in-use plugin GC from blocking volume GC

---

website/pages/api-docs/jobs.mdx

The current documentation implies that job JSON is submitted as a string (`...`) but this is not the case (if you do this you will receive a 400)
Changed the text to match the convention in 'update job' wherein the job is correctly illustrated as an object literal

docs: update plan API documentation

---

e2e/vaultsecrets/input/secrets.nomad

Fixes https://github.com/hashicorp/nomad/issues/9144
The `$NOMAD_SECRETS_DIR` environment variable is rendered as `/secrets`, which
if used as a `template.destination` prior to the recent security patch would unintentionally 
escape the file sandbox and get dropped in a directory named `/secrets` where the Nomad 
client binary was running. The `VaultSecrets` test was accidentally relying on this
behavior and that causes the test to fail.
---
This is an easy mistake to make, and makes me worry whether we have a lot of this
behavior "in the wild" and what we could do to improve the UX.
Addendum: in 0.12.5 it doesn't _actually_ escape the file sandbox, but it fails the check in
0.12.6 as though it does. So there may be a bug in the patch 😦 (Going to spin that out to a new issue)

e2e: fix destination of templates in VaultSecrets test

---

ui/mirage/faker.js

This will hopefully make it easier to reproduce test failures
that happen intermittently, especially in CI.
It shows up in a somewhat strange place in the [CircleCI logs](https://app.circleci.com/pipelines/github/hashicorp/nomad/12536/workflows/1309c73f-c4c5-4222-a32e-803c2ca50c4f/jobs/110577) but maybe it’s fine?
```
ok 1 Chrome 86.0 - [1322 ms] - Acceptance | allocation detail: it passes an accessibility audit
---
browser log: |
LOG: No seed specified with faker-seed query parameter, seeding Faker with 13497
```

UI: Add logged Faker seed when none is set in tests

---

client/allocrunner/taskrunner/getter/getter.go
client/allocrunner/taskrunner/template/template.go
e2e/consultemplate/input/templating.nomad
helper/funcs.go
helper/funcs_test.go

Fixes https://github.com/hashicorp/nomad/issues/9148
Prior to Nomad 0.12.5, you could use `${NOMAD_SECRETS_DIR}/mysecret.txt` as
the `artifact.destination` and `template.destination` because we would always
append the destination to the task working directory. In the recent security
patch we treated the `destination` absolute path as valid if it didn't escape
the working directory, but this breaks backwards compatibility and
interpolation of `destination` fields.
This changeset partially reverts the behavior so that we always append the
destination, but we also perform the escape check on that new destination
after interpolation so the security hole is closed.

artifact/template: make destination path absolute inside taskdir

---

CHANGELOG.md
client/allocrunner/taskrunner/getter/getter.go
client/allocrunner/taskrunner/template/template.go
helper/funcs.go
helper/funcs_test.go

artifact/template: make destination path absolute inside taskdir (0.10.7)

---

e2e/vaultsecrets/input/secrets.nomad

This reverts commit 8aed53c177aea024d4f24d1fbb4d6e0881f04eab.
The regression was fixed in https://github.com/hashicorp/nomad/pull/9149

Revert "e2e: fix destination of templates in VaultSecrets test (#9146)"

---

CHANGELOG.md
website/pages/docs/upgrade/upgrade-specific.mdx

_Pending backport release of 0.12.7, 0.11.6, and 0.10.7 tomorrow_

docs: add regression warning for GH-9148 to upgrade guide

---

client/taskenv/env.go
client/taskenv/env_test.go
website/pages/docs/runtime/environment.mdx
website/pages/partials/envvars.mdx

[Updated] Beforehand tasks and field replacements did not have access to the
unique ID of their job or information about its parent. This adds this information
as new environment variables.

Add NOMAD_JOB_ID and NOMAD_JOB_PARENT_ID env variables

---

command/agent/event_endpoint.go
command/agent/event_endpoint_test.go
command/agent/http.go
helper/raftutil/msgtypes.go
nomad/event_endpoint.go
nomad/event_endpoint_test.go
nomad/fsm.go
nomad/mock/mock.go
nomad/server.go
nomad/state/schema.go
nomad/state/state_store.go
nomad/state/state_store_test.go
nomad/structs/event.go
nomad/structs/structs.go
tools/go.sum

CRUD operations and plumbing :hammer_and_wrench:  for managing event stream sinks

event sink crud operation api

---

website/pages/docs/integrations/vault-integration.mdx

Fix a command typo at `Submitting a job with a Vault Namespace` unit.
It should be 
`vault token create -policy access-kv -namespace=engineering -period 72h -orphan`

Fix a command typo of vault token create

---

ui/app/services/system.js
ui/app/styles/components/gutter.scss
ui/app/templates/components/gutter-menu.hbs
ui/mirage/config.js
ui/tests/acceptance/regions-test.js

Closes: #8389 
Slipping this one in. It would be nice to avoid making an additional request for this considering we have to fetch members to get the default region anyway, but I think this is the only guaranteed way to get the actual version in the event that servers are running different versions.

UI: Show the nomad agent version of the agent the UI is served from

---

ui/app/routes/allocations/allocation/fs.js
ui/app/routes/allocations/allocation/task/fs.js
ui/app/templates/components/fs/browser.hbs
ui/tests/acceptance/allocation-fs-test.js
ui/tests/acceptance/task-fs-test.js

Before, we'd show a helpful error message when a task isn't running instead of erroring in a generic way. Turns out when an alloc is terminal but reachable, the filesystem is left behind and we were hiding it.
Now it is always shown and in the event that something errors, it'll either be generic, or--more commonly--a 404 of the allocation.
Fixes #9065

UI: Always show the file browser for allocations and tasks.

---

ui/app/components/flex-masonry.js
ui/app/components/topo-viz.js
ui/app/models/allocation.js
ui/app/styles/charts/topo-viz-node.scss
ui/app/styles/components/dashboard-metric.scss
ui/app/templates/components/flex-masonry.hbs
ui/app/templates/components/topo-viz.hbs
ui/app/templates/topology.hbs
ui/tests/integration/components/flex-masonry-test.js
ui/tests/integration/components/topo-viz-test.js

Just a collection of little things.
1. Make the info panel a fixed width so it can no longer be impractically narrow.
2. Force a single column display of datacenters and nodes when the viewport is narrow.
3. Remove failed allocs since they don't actually occupy space.
4. Don't draw allocation associations when the allocations selected are numerous relative to the client count.
5. Fix the styling of starting allocs, which weren't actually blue.
6. Fixed a couple bugs in `FlexMasonry`.

UI: topo viz refinements

---

ui/app/templates/clients/client/index.hbs

Display node class in client detail at /ui/clients/{client-id}
also fixes https://github.com/hashicorp/nomad/issues/8547

Display class in client details

---

jobspec/parse_test.go
jobspec/test-fixtures/tg-scaling-policy.hcl
jobspec2/hclutil/blockattrs.go
jobspec2/parse_map.go
jobspec2/parse_test.go
jobspec2/test-fixtures/config-compatibility.hcl

Fix HCLv2 special handling of `map[string]interface{}` that appears in Task driver config and scaling policies.  Here, the HCLv2 parser needs to parse the tree the exact way as HCLv1 to maintain compatibility.
This PR fixes three classes of discrepancies:
First, floats are interpretted as float64 and never as big.Float
Second, in HCLv1, attributes assigned to map are interpreted as single map slices, so
```
map_attr = { "K" = "V" }
{"map_attr": [{"K": "V"}]}
```
Lastly, when blocks are repeated with labels, so
```
check "foo" {
query = "query1"
}
check "bar" {
query = "query2"
}
{
"check": [
{"foo": [{"query": "query1"}]},
{"bar": [{"query": "query2"}]}
]
}
```
I've added tests first, so reviewer can see the failures initially in …

Fix HCLv2 parser discrepancies

---

command/agent/event_endpoint.go
helper/raftutil/msgtypes.go
nomad/event_endpoint.go
nomad/event_endpoint_test.go
nomad/event_sink_manager.go
nomad/event_sink_manager_test.go
nomad/fsm.go
nomad/leader.go
nomad/mock/mock.go
nomad/server.go
nomad/state/state_store.go
nomad/state/state_store_test.go
nomad/stream/sink.go
nomad/stream/webhook_sink.go
nomad/stream/webhook_sink_test.go
nomad/structs/event.go
nomad/structs/structs.go

Adds a new SinkManager to control sending events to configured event sinks.
This PR adds a new SinkManager to Nomad Servers. When a server establishes leadership it will run the manager.
A SinkManager is responsible for:
- Establishing and running ManagedSinks
- Starting new ManagedSinks when one is added to the state store
- Periodically Checking in ManagedSink progress to raft
A ManagedSink is responsible for:
- Subscribing to the event broker 
- Sending events from the subscription to a SinkWriter
- Reloading itself when its EventSink is updated in the state store

Send events to EventSinks

---

website/vercel.json

this allows the ability for outside contributors to view website build logs

website: make build logs public

---

website/pages/downloads/index.jsx

Calling it "Beta" despite being "beta2" since "beta1" was never published.

docs: v1.0.0-beta2 released!

---

e2e/terraform/packer/packer-ubuntu-bionic-amd64.json

The base Ubuntu AMI modifies apt sources during cloud-init. But the Packer
build can potentially start the setup script before that work is done,
resulting in errors trying to install base system dependencies like
`dnsmasq`. Delay the setup long enough to lose the race with cloud-init.
This is a mildly hacky fix but these builds are automated (running weekly), so
adding 30s to the build costs us a lot less than the time it would take to try
to fix how cloud-init is working for us.

e2e: reduce risk of flaky Ubuntu AMI build

---

e2e/terraform/Makefile
e2e/terraform/terraform.tfvars

Improve the DX for deploying a dev cluster by making it obvious that there's a default to change.

e2e: set default version for dev cluster

---

e2e/terraform/Makefile
e2e/terraform/README.md
e2e/terraform/provision-nomad/main.tf
e2e/terraform/terraform.full.tfvars
e2e/terraform/terraform.tfvars

The `nomad_sha`, `nomad_version`, and `nomad_local_binary` variables for the
Nomad provisioning module assumed that only one would be set. By having the
override each other with an explicit precedence, it makes it easier to avoid
problems with Terraform's implicit variables behavior.
Set the expected default values in the `terraform.full.tfvars` to avoid
shadowing by any future changes to the `terraform.tfvars` file.
Update the Makefile to put the `-var` and `-var-file` in the correct order.

e2e: provide precedence for version variables

---

ui/app/routes/topology.js
ui/tests/acceptance/topology-test.js

Adding `namespace=*` will bring in allocations from all namespaces instead of only the default one.
Adding `task_states=false` will remove the task states properties from the allocations response which significantly reduces the size of the response.

UI: Add namespace and task states query params to the topology route

---

website/pages/docs/job-specification/template.mdx

The `template.allow_host_source` configuration was not operable, leading to
the recent security patch in 0.12.6. We forgot to update this piece of the
documentation referring to the correct configuration value.

docs: remove outdated reference to template.allow_host_source

---

ui/tests/acceptance/topology-test.js
ui/tests/pages/components/topo-viz/node.js

This test occasionally fails because the random generation
sometimes produces a node with no allocations, such as [here](https://app.circleci.com/pipelines/github/hashicorp/nomad/12735/workflows/9a407f87-0383-48ee-8e41-7e6e351dce28/jobs/113130/steps).
This is one way to solve it without trying to force the generated
data to always have an allocation.

UI: Add handling for empty state flaky test edge case

---

drivers/java/driver.go
drivers/java/utils.go

Fixes #7865
Found that `/usr/libexec/java_home` will provide information about whether or not a JVM is installed and not stimulate the "Install a JVM" popup window that running the shim commands do.

Fix for Java fingerprinter on macOS

---

.circleci/config.yml
.circleci/config/config.yml
.circleci/config/jobs/algolia_index.yml
.circleci/config/jobs/test-ui.yml
.circleci/config/jobs/test-windows.yml
.circleci/config/jobs/website-docker-image.yml
drivers/docker/docklog/docker_logger_test.go
drivers/docker/driver_test.go
drivers/docker/driver_windows_test.go
website/Dockerfile

Dockerhub is going to rate limit unauthenticated pulls.
Use our HashiCorp internal mirror for builds run through CircleCI.

Use Dockerhub Mirror.

---

website/data/docs-navigation.js
website/pages/docs/commands/job/plan.mdx
website/pages/docs/commands/job/run.mdx
website/pages/docs/job-specification/hcl2.mdx
website/pages/docs/upgrade/upgrade-specific.mdx

This is a first draft of HCLv2 docs - I added the details under `hcl2` doc with some minimal info highlighting the hcl2 introductions.
As a longer term strategy, we'll want to mimic the [Packer HCL docs structure](https://www.packer.io/docs/from-1.5) that details all the blocks and allowed expressions/functions in greater details.  However, given that the exact functions and templating syntax is still somewhat influx, I opt to push that to another time.

First draft of HCLv2 docs

---

CHANGELOG.md
nomad/periodic_endpoint.go
nomad/periodic_endpoint_test.go
website/pages/api-docs/jobs.mdx

This PR repurpose `dispatch-job` for periodic job force invocation in addition to parameterized jobs.
Currently, force evaluating a periodic job requires `submit-job` capability, a too powerful capability as it allows submitting arbitrary jobs to the cluster.  In contrast, submitting a new parameterized job require `submit-job` capability, but manually invoking it only requires `dispatch-job`. Having a lower-scoped capability allow delegating debugging or recovery handling to operators or tools with less privileges.
I've considered introducing a new capability just for periodic jobs, but I thought such fine-grain capability seems unwarranted. In both the periodic and parameterized job, we'd want operators to invoke jobs that are already registered and allowed in the cluster.
Closes #7703

Repurpose dispatch-job capability to dispatch periodic jobs

---

website/Dockerfile
website/Makefile
website/README.md
website/package.json

Start using Node.js v12.19.0, the most recent active LTS that is
supported by Vercel:
https://vercel.com/docs/runtimes#official-runtimes/node-js/node-js-version
.
The docs now require String.prototype.matchAll, that's part of ES2020
support, and is not available on Node.js 10.x as seen in https://node.green/#ES2020 .
Also, explicitly set Vercel javascript version instead of relying on default, so we can ensure local environment matches Vercel, and avoid having deployment environment change significantly from under our feet.

website: require Node v12

---

command/alloc_stop.go
command/deployment_fail.go
command/deployment_promote.go
command/deployment_resume.go
command/deployment_unblock.go
command/eval_status.go
command/job_dispatch.go
command/job_eval.go
command/job_periodic_force.go
command/job_promote.go
command/job_revert.go
command/job_run.go
command/job_scale.go
command/job_status_test.go
command/job_stop.go
command/monitor.go
command/monitor_test.go

The only user of monitor(evalID, true) was command/eval_status, and
eval_status had a duplicate of the prefix-handling code inside it, so in
all cases the complete evalID was being passed to monitor.
Given that, we can remove the prefix code from command/monitor, and
remove the boolean arg.
This supersedes https://github.com/hashicorp/nomad/pull/9250.

Update monitor func not to take a prefix

---

ui/app/styles/components/recommendation-card.scss

I noticed this while poking around.
**Before**
**After**

UI: Fix the raw 'blue' in recommendation cards to use '$blue'

---

command/event.go

@krishicks, I spotted this while playing with command.

Add missing comma in help-text example.

---

website/data/docs-navigation.js
website/pages/docs/internals/filesystem.mdx
website/pages/docs/job-specification/artifact.mdx
website/pages/docs/job-specification/template.mdx
website/pages/docs/runtime/environment.mdx

Follows from https://github.com/hashicorp/nomad/issues/8919 https://github.com/hashicorp/nomad/pull/9098, closes https://github.com/hashicorp/nomad/issues/2948
We recently added documentation disambiguating the terminology of the
allocation/task working directories. This changeset adds an internals document
that describes in more detail exactly what does into the allocation working
directory, how this interacts with the filesystem isolation provided by task
drivers, and how this interacts with features like `artifact` and `template`.
See preview at https://nomad-jpdfu3avq.vercel.app/docs/internals/filesystem

docs: internals documentation for alloc filesystem

---

ui/app/components/global-search/control.js
ui/tests/acceptance/search-test.js

This test has been periodically failing, like [here](https://app.circleci.com/pipelines/github/hashicorp/nomad/12879/workflows/40c0445c-b244-4a04-a5a3-d9685b656c94/jobs/114751/tests).
This test has sometimes been failing because the first node contains
the beginning of the `otherNode` id somewhere within its id. It seems
less useful to match within the node, so this changes id search to
only match at the beginning of the id.

UI: Change node id search to prefix-only

---

demo/csi/cinder-csi-plugin/cinder-csi-plugin.hcl
demo/csi/cinder-csi-plugin/example_volume.hcl

- Add verbose logging to CSI Driver example
- Update the `attachment_mode` in the example volume registration to be `file-system`

Update Cinder CSI example docs

---

website/pages/intro/use-cases.mdx

I believe there’s a typo where “workloads” was changed to “jobs” but the original word wasn’t removed. Or maybe it’s the other way around. But currently there is an orphaned one-word sentence.

Fix typo in batch processing use case

---

nomad/state/events.go
nomad/state/events_test.go

Without this change all events are discarded if any change was a deletion.

Fix handling of deleted change

---

client/allocrunner/groupservice_hook.go
command/agent/consul/service_client.go

Fixes a bug introduced in #9095 where the wrong port was used in service registration. This is because group services initially passed the port to the service watcher through use of a DriverNetwork. #9095 switch to using newer apis/interfaces that weren't previously available at the time, but didn't remove this initial functionality causing the wrong port number to be used on registration. 
fixes #9221

ar/groupservice: remove drivernetwork

---

CHANGELOG.md
nomad/alloc_endpoint.go
nomad/alloc_endpoint_test.go
nomad/state/state_store.go

resolves #9268 
first commit adds a test that multi-namespace queries actually works... as well as a documenting test that ACLs with multi-namespace query didn't work.
second commit fixes the discovered issues, using the multi-namespace pattern employed by `/v1/jobs` and `/v1/scaling/policies`

fix ACL bugs in listing allocs across all namespaces

---

ui/stories/components/gutter-menu.stories.js
ui/stories/components/table.stories.js

I missed these when I removed the warning icon. Note to self: grep the stories directory as well as app and tests.

UI: Update lingering instances of the old warning icon in stories

---

ui/app/abilities/abstract.js
ui/app/abilities/recommendation.js
ui/app/routes/application.js
ui/app/routes/jobs/job.js
ui/app/services/system.js
ui/app/templates/components/job-page/service.hbs
ui/app/templates/components/job-page/system.hbs
ui/mirage/config.js
ui/mirage/models/feature.js
ui/tests/acceptance/job-detail-test.js
ui/tests/acceptance/optimize-test.js
ui/tests/acceptance/regions-test.js
ui/tests/unit/abilities/recommendation-test.js

Without this, visiting any job detail page on Nomad OSS would
crash with an error like this:
```
Error: Ember Data Request GET /v1/recommendations?job=ping%F0%9F%A5%B3&namespace=default returned a 404
Payload (text/xml)
```
The problem was twofold.
1. The recommendation ability didn’t include anything about checking whether the feature was present. This adds a request to `/v1/operator/license` on application load to determine which features are present and store them in the system service. The ability now looks for `Dynamic Application Sizing` in that feature list.
1. Second, I didn’t check permissions at all in the job-fetching or job detail templates.
Thanks to @DingoEatingFuzz for catching this! 😯

UI: Fix job detail crash when recommendations off

---

api/internal/testutil/server.go

The [AWS](https://github.com/hashicorp/nomad/blob/master/client/fingerprint/env_aws.go#L25) and [GCE](https://github.com/hashicorp/nomad/blob/master/client/fingerprint/env_gce.go#L29) fingerprinters have 2-second timeouts by default.
This makes startup time for the `nomad` binary in dev-mode in non-AWS/GCE environments longer, as the the server will not have started until these fingerprint timeouts are hit.
In the case of running tests locally, these 2-second timeouts make any test that starts a dev-mode server very likely to time out. (CI is configured with a much longer default test timeout.)
There already is functionality in place for using a much shorter timeout via the client configuration option `test.tighten_network_timeouts`. This defaults to `true` when creating a test client: …

api/testutil: Use fast fingerprint timeout in dev mode tests

---

website/pages/docs/commands/operator/snapshot-agent.mdx

I noticed that `nomad.address` has a familiar looking port -- consul's! Most likely an accidental stowaway while porting over the snapshot functionality from Consul to Nomad.
PR updates the documentation to use the correct default Nomad API port, 4646.

Document correct default Nomad port

---

command/agent/job_endpoint.go
nomad/structs/structs.go

Having the `Namespace` as a top-level field causes the RPC decoding process to use it as the request namespace. Since we are not using this field, the namepsace would be set to an empty string when going from a client to a server, causing the request to fail with a `404` when looking for the job:
```
job "webapp" not found
```

Remove Namespace field from JobScaleRequest

---

command/agent/job_endpoint.go
command/helpers.go
command/helpers_test.go
command/job_plan.go
command/job_run.go
command/job_validate.go
jobspec2/addrs/README.md
jobspec2/addrs/doc.go
jobspec2/addrs/input_variable.go
jobspec2/addrs/parse_ref.go
jobspec2/addrs/referenceable.go
jobspec2/hcl_conversions.go
jobspec2/parse.go
jobspec2/parse_job.go
jobspec2/parse_test.go
jobspec2/types.config.go
jobspec2/types.variables.go

This adds support for declaring Variables and Locals that are present in Terraform and Packer, by porting Packer's implementation to Nomad.
This PR makes the following functional changes:
* Job Variables now must be declared, using the same syntax and specification as Packer: https://www.packer.io/docs/from-1.5/variables
* Locals can be defined as well, similar to Packer's locals: https://www.packer.io/docs/from-1.5/locals
* Add support for reading input variable files by passing `-var-file=` similar to Terraform and Packer
This PR makes a change so that variables are referenced with `var.<NAME>` rather than `vars.<NAME>` to bring Nomad inline with other products. Locals can be referred to by `local.<NAME>`.
In summary, a variable file may be:
```hcl
variables {
image = "nginx:1.19"
} …
```

HCL2: Variables and Locals

---

CHANGELOG.md
client/fingerprint/bridge.go
client/fingerprint/bridge_linux.go
client/fingerprint/bridge_linux_test.go

In Nomad v0.12.0, the client added additional fingerprinting around the
presense of the bridge kernel module. The fingerprinter only checked in
`/proc/modules` which is a list of loaded modules. In some cases, the
bridge kernel module is builtin rather than dynamically loaded. The fix
for that case is in #8721. However we were still missing the case where
the bridge module is dynamically loaded, but not yet loaded during the
startup of the Nomad agent. In this case the fingerprinter would believe
the bridge module was unavailable when really it gets loaded on demand.
This PR now has the fingerprinter scan the kernel module dependency file,
which will contain an entry for the bridge module even if it is not yet
loaded.
In summary, the client now looks for the bridge kernel module in
- …

client/fingerprint: detect unloaded dynamic bridge kernel module

---

CHANGELOG.md
drivers/shared/executor/legacy_executor_wrapper.go

This fixes a bug where pre-0.9 executors fail to recover after an
upgrade.
The bug is that legacyExecutorWrappers didn't get updated with
ExecStreaming function, and thus failed to implement the Executor
function. Sadly, this meant that all recovery attempts fail, as the
runtime check in
https://github.com/hashicorp/nomad/blob/b312aacbc961dfd976b6a402d22d80b45176a962/drivers/shared/executor/utils.go#L103-L110
.
The bug affects all versions since 0.9.2: if a client upgrades from pre-0.9 to 0.9.2 or later; then all exec based tasks (i.e. exec, raw_exec, java, qemu) will fail to recover, will be leaked, and then nomad will start another task.  The leaked pre-0.9 task will run un-interrupted and unmanaged until the client dies or it's killed manually.

Legacy executors are executors after all

---

command/helpers.go
command/helpers_test.go

Use a custom message when the job file is a valid HCL1 but no longer
valid under HCL 2 syntax.
A sample error:
```
$ nomad job run /tmp/example.nomad
Error getting job struct: Failed to parse using HCL 2. Use the HCL 1 parser with `nomad run -hcl1`, or address the following issues:
example.nomad:20,5-6: Invalid argument name; Argument names must not be quoted.
```

Custom message when job file is HCL2 incompatible

---

e2e/terraform/config/full-cluster/nomad/base.hcl

Enables audit logging for full-cluster clients and servers, the full-cluster profile [specifies `nomad_enterprise = true`](https://github.com/hashicorp/nomad/blob/master/e2e/terraform/terraform.full.tfvars) so enabling audit logging will ensure that all http requests go through the auditing process

e2e enables audit log on full-cluster

---

CHANGELOG.md
drivers/docker/config.go
drivers/docker/driver.go
drivers/docker/driver_test.go
drivers/docker/driver_unix_test.go
website/pages/docs/upgrade/upgrade-specific.mdx

Fixes https://github.com/hashicorp/nomad/issues/9303
The default behavior for `docker.volumes.enabled` is intended to be `false`,
but the HCL schema defaults to `true` if the value is unset. Set the default
literal value to `true`.
Additionally, Docker driver mounts of type "volume" (but not "bind") are not
being properly sandboxed with that setting. Disable Docker mounts with type
"volume" entirely whenever the `docker.volumes.enabled` flag is set to
false. Note this is unrelated to the `volume_mount` feature, which is
constrained to preconfigured host volumes or whatever is mounted by a CSI
plugin.
This changeset includes updates to unit tests that should have been failing
under the documented behavior but were not.

docker: disallow volume mounts from host by default

---

CHANGELOG.md
nomad/scaling_endpoint.go
nomad/scaling_endpoint_test.go
nomad/state/state_store.go
nomad/state/state_store_test.go

the `/v1/scaling/policies` list endpoint allows filtering by `?job` and `?type`. unfortunately, the code path for `job` ignored the `type` query. this PR remedies this. 
unsurprisingly, there weren't any tests protecting this behavior, so those are added as well.
resolves #9227

use both job and type query on scaling policy list endpoint

---

CHANGELOG.md
api/contexts/contexts.go
command/recommendation_apply.go
command/recommendation_apply_test.go
command/recommendation_dismiss.go
command/recommendation_dismiss_test.go
command/recommendation_info.go
command/recommendation_info_test.go
command/recommendation_list_test.go
nomad/structs/structs.go
vendor/github.com/hashicorp/nomad/api/contexts/contexts.go

relies on and provides structure for `/v1/search` support in Enterprise, which will be merged next
the autocomplete support is redundant across all of the supported commands: `apply`, `dismiss`, and `info`, and I just copied it between them. this seems a little gross, but it's the same pattern used in the `nomad job` commands and `nomad deployment` commands (where it is repeated 6 times)
**update**: refactored to reduce redundancy in autocomplete code. 🤷

recommendations CLI: autocomplete support

---

client/allocrunner/csi_hook.go
command/agent/csi_endpoint.go
nomad/core_sched.go
nomad/csi_endpoint.go
nomad/state/state_store.go
nomad/state/state_store_test.go
nomad/structs/csi.go
nomad/volumewatcher/volume_watcher_test.go
nomad/volumewatcher/volumes_watcher_test.go

Fixes https://github.com/hashicorp/nomad/issues/9259
The unpublish workflow requires that we know the mode (RW vs RO) if we want to
unpublish the node. Update the hook and the Unpublish RPC so that we mark the
claim for release in a new state but leave the mode alone. This fixes a bug
where RO claims were failing node unpublish.
The core job GC doesn't know the mode, but we don't need it for that workflow,
so add a mode specifically for GC; the volumewatcher uses this as a sentinel
to check whether claims (with their specific RW vs RO modes) need to be claimed.

csi: Postrun hook should not change mode

---

client/devicemanager/instance.go

Even if a plugin sends back an empty []*device.DeviceGroup, it's transformed to nil during the RPC between nomad and the plugin. This conditional block prevented the manager to trigger the logic for "first fingerprint received". This adds a lot of latency when starting nomad.
Our custom device plugin is returning an empty FingerprintResponse.Devices slice very often. Our temporary fix is to send a ][]*DeviceGroup with a "dummy" DeviceGroup if the slice is empty.
Not triggering the "first fingerprint received" adds 50s to nomad's startup time (because of the batch fingerprint timeout of 50s). In turn, this made our node exceed its hearbeat grace period with our leader when restarting it, revoking all vault tokens for its allocations, causing a restart of all our allocations because their …

Don't ignore nil devices in plugin fingerprint

---

CHANGELOG.md
drivers/rawexec/driver_unix_test.go
drivers/shared/executor/executor.go
drivers/shared/executor/executor_linux_test.go

When raw_exec is configured with [`no_cgroups`](https://www.nomadproject.io/docs/drivers/raw_exec#no_cgroups), raw_exec shouldn't attempt to create a cgroup.
Prior to this change, we accidentially always required freezer cgroup to do stats PID tracking. We already have the proper fallback in place for metrics, so only need to ensure that we don't create a cgroup for the task.
I've added the tests in a commit first. You can see the failure in https://app.circleci.com/pipelines/github/hashicorp/nomad/13091/workflows/b2d02203-1a9b-4c46-92b1-7b35e58ed63a/jobs/117359 where `freezer` cgroup differed from expected.
Fixes https://github.com/hashicorp/nomad/issues/8565

raw_exec: don't use cgroups when no_cgroup is set 

---

command/agent/alloc_endpoint.go
nomad/structs/structs.go
nomad/structs/structs_test.go

This PR populates the `Ports` fields of the `AllocatedSharedResources` struct with port information from the deprecated task network resources. This should allow allocations to display network information in the UI correctly until the user migrates to the new group network definition syntax.
Fixes #9031

structs: canonicalize allocatedtaskresources to populate shared ports

---

command/commands.go
command/recommendation_apply.go
command/recommendation_apply_test.go
command/recommendation_dismiss.go
command/recommendation_dismiss_test.go
command/recommendation_info.go
command/recommendation_info_test.go

i got the composition wrong 😞 so that `meta` was duplicated, and downstream code was using the wrong one
new approach is not as pretty, but still better than repeating this across all three (so far) commands

recs cli: fixed bad composition

---

ui/app/controllers/optimize.js
ui/app/models/recommendation-summary.js
ui/app/routes/optimize/index.js
ui/app/templates/optimize.hbs
ui/tests/acceptance/optimize-test.js
ui/tests/pages/optimize.js

This adds text and facet filtering to the DAS summary table. It’s mostly a combination
of facet code taken from `controller:jobs/index`, search adapted from the global
search control, and tests.
The only search is fuzzy matching against the recommendation summary slug; the other
strings of task names and namespaces didn’t seem applicable to me, but it wouldn’t
be difficult to add anything else desirable.
Some design decisions:
* if changing the filter causes the currently-active summary to be excluded, the active card (and subroute) updates to the first summary in the filtered collection
* if the filter causes the collection to become empty, it navigates to `/optimize?…`

UI: Add DAS summary table filtering

---

drivers/docker/config.go
drivers/docker/driver.go
drivers/docker/driver_test.go
website/pages/docs/drivers/docker.mdx

Fixes #2303 
We have an internal HPC customer who could also benefit from the ability to pin CPUs to a docker container.
It would be ideal to have:
1) `--cpuset-cpus` which will allow pinning CPUs to a docker container.
2) If the user tries to pin the same CPU (e.g. CPU 0) to another docker container, it should error out (if on the same node) OR
schedule on CPU 0 on a different node.
Currently (2) is not supported by docker. This PR only addresses (1).
As a follow-up, we can try nomad docker driver to do some bookkeeping, and achieve (2).

Add cpuset_cpus to docker driver.

---

CHANGELOG.md
command/agent/consul/service_client.go
command/agent/consul/service_client_test.go

Previously, connect sidecars would be re-registered with consul every cycle
of Nomad's reconciliation loop around Consul service registrations. This is
because part of the comparison used `reflect.DeepEqual` on `[]string` objects,
which returns false when one object is `[]string{}` and the other is `[]string{}(nil)`.
Unfortunately, this was always the case, and every Connect sidecar service
would be re-registered on every iteration, which happens every 30 seconds.
At the very least exacerbates https://github.com/hashicorp/nomad/issues/9307

consul: prevent re-registration churn by correctly comparing connect sidecar tags

---

website/pages/docs/configuration/client.mdx

Update the default value for `client.bridge_network_subnet` in docs
to match the new value from 99742f2665. Was `172.26.66.0/23`, is
now `172.26.64.0/20`.
Fixes #9316

docs: update brige network subnet docs

---

api/tasks.go
client/allocrunner/alloc_runner.go
client/allocrunner/alloc_runner_test.go
client/allocrunner/task_hook_coordinator.go
client/allocrunner/taskrunner/restarts/restarts.go
client/allocrunner/taskrunner/task_runner.go
client/allocrunner/taskrunner/task_runner_getters.go
client/allocrunner/taskrunner/task_runner_hooks.go
e2e/lifecycle/inputs/batch.nomad
e2e/lifecycle/inputs/service.nomad
e2e/lifecycle/lifecycle.go
nomad/structs/structs.go

For https://github.com/hashicorp/nomad/issues/8193
A `poststop` hook has been added to the `lifecycle` stanza to allow users to run tasks after all other tasks in an allocation have completed.
This `poststop` task will run after main tasks are finished running. It will run no matter the final status of the main tasks, whether it is completed, failed or killed.
* batch job: `poststop` waits until main tasks have finished before starting
* service & system jobs: since services & system jobs are long-lived, `poststop` will only run poststop tasks after the allocation receives a kill signal or a main task fails
I plan to make these improvements in separate pull requests
* increased e2e testing
* refactor to move behavior out of the allocrunner Run() & back into the TaskHookCoordinator
* …

lifecycle: add poststop hook

---

command/operator_debug.go
command/operator_debug_test.go
testutil/wait.go

Adds `max-nodes`, `node-id=all`, and `node-class` cmdline arguments to `nomad operator debug`
From the helpText:
```
-max-nodes=<count>
Cap the maximum number of client nodes included in the capture.  Defaults to 10, set to 0 for unlimited.
-node-id=<node>,<node>
Comma separated list of Nomad client node ids, to monitor for logs and include pprof
profiles. Accepts id prefixes, and "all" to select all nodes (up to count = max-nodes).
-node-class=<node-class>
Filter client nodes based on node class.
```

nomad operator debug - add client node filtering arguments

---

jobspec2/helper_test.go
jobspec2/parse.go
jobspec2/parse_job.go
jobspec2/parse_map.go
jobspec2/parse_test.go
jobspec2/types.config.go

The HCL2 parser needs to apply special parsing tweaks so it can parse
the task config the same way as HCL1. Particularly, it needs to
reinterprets `map[string]interface{}` fields and blocks that appear when
attributes are expected.
This commit restricts the special casing to the Job fields, and ignore
`variables` and `locals` block.

Restrict HCL special casing of map[string]interface{} fields

---

.circleci/config.yml
.circleci/config/config.yml
CHANGELOG.md
README.md
scripts/release/mac-remote-build
scripts/vagrant-linux-priv-go.sh

Despite being a security release for Go, we do not believe Nomad is
impacted.

build: upgrade from Go 1.15.4 to 1.15.5

---

nomad/structs/diff.go

This fixes two places in `nomad/structs` where `break` was happening in a switch, therefore not affecting the intended`for` loop.

nomad/structs: fix noop breaks

---

e2e/csi/csi.go
e2e/csi/input/use-ebs-volume.nomad
e2e/csi/input/use-efs-volume-write.nomad
e2e/e2eutil/allocs.go
e2e/e2eutil/job.go

Assert that deregistering a volume works without errors following a volume
reap. This has been an area where we've been hit by bugs and the existing
tests don't cover it. (And it seems very difficult to make happen in unit testing.)
Includes:
* Use CLI helpers where feasible to exercise CSI command line.
* Dump plugin allocation logs on deregistration failures for debugging purposes.

e2e: CSI test should detect un-deregisterable volumes

---

scripts/release/Dockerfile
scripts/vagrant-linux-unpriv-ui.sh

Avoids setting the node version in the release Dockerfile, by using
an alias.  This allows us to update the node version in one file only.

release: infer node version

---

demo/csi/digitalocean/.gitignore
demo/csi/digitalocean/README.md
demo/csi/digitalocean/main.tf
demo/csi/digitalocean/plugin.nomad
demo/csi/digitalocean/terraform.tf
demo/csi/digitalocean/variables.tf
demo/csi/digitalocean/versions.tf
demo/csi/digitalocean/volume-job.nomad

This is a slight rework of an internal testing deployment.

demo: CSI example for DigitalOcean block storage

---

demo/csi/digitalocean/volume-job.nomad

The demo that got merged didn't get `hclfmt` checked because it was on a `docs-*` branch.

hclfmt digitalocean demo to pass linting

---

CHANGELOG.md
api/tasks.go
api/tasks_test.go
client/allocrunner/taskrunner/getter/getter.go
client/allocrunner/taskrunner/getter/getter_test.go
command/agent/job_endpoint.go
command/agent/job_endpoint_test.go
nomad/structs/diff_test.go
nomad/structs/structs.go
vendor/github.com/hashicorp/nomad/api/tasks.go
website/pages/docs/job-specification/artifact.mdx

This PR adds the ability to set HTTP headers when downloading
an artifact from an `http` or `https` resource.
The implementation in `go-getter` is such that a new `HTTPGetter`
must be created for each artifact that sets headers (as opposed
to conveniently setting headers per-request). This PR maintains
the memoization of the default Getter objects, creating new ones
only for artifacts where headers are set.
Closes #9306

jobspec: add support for headers in artifact stanza

---

website/pages/downloads/index.jsx

`stable-website` branch needs to be updated as well with this change, and it is currently lagging `master`

website: update downloads page to beta3

---

command/alloc_status.go
command/alloc_status_test.go

Fixes https://github.com/hashicorp/nomad/issues/9297
The `nomad alloc status -verbose` command returns a 404 from CSI volumes
because the volume mount block in the task points back to the
`job.group.volume` block. So using the `Name` field to query is the "name" as
seen in the jobspec, and not the name of the volume that we need for querying.
Show both the job-specific name and the volume ID in the resulting output,
which clarifies the difference between the two fields and is more consistent
with the web UI.

csi: alloc status -verbose should query volume request 'source'

---

scheduler/feasible.go
scheduler/feasible_test.go

This PR enables users of Nomad < 0.12 and bridge networks to 
upgrade to Nomad 0.12 and beyond. Nomad 0.12 introduced a 
network fingerprinter for bridge networks, which is a constraint checked 
for if bridge network is being used. If users upgrade servers first (as 
recommended), suddenly no clients running older versions of Nomad
will satisfy the bridge network resource constraint. This change insetad 
only enforces the constraint if the Nomad client version is also >= 0.12.
Closes #8423

scheduler: enable upgrade path for bridge network finger print

---

CHANGELOG.md
command/agent/alloc_endpoint.go
command/agent/alloc_endpoint_test.go

#9367 suggests that the canonicalization of `structs.Allocation.AllocatedResources` is mutating the memdb object, causing the number of ports to grow on every call
there are a few solutions here: 
* rewrite canonicalize to avoid this; this allows the field to exist and attempts consistency, which is presumably what we wanted to avoid
* mutate a copy
documenting test in the first commit:
https://app.circleci.com/pipelines/github/hashicorp/nomad/13195/workflows/63c91dd0-ea6e-440e-b080-50b68b680dbc/jobs/118749
copy-based fix in the second commit:
https://app.circleci.com/pipelines/github/hashicorp/nomad/13196/workflows/c857a136-5584-4d3f-ad10-6684bc7f9c68/jobs/118744

fix duplication of ports in `AllocatedResources`

---

client/allocrunner/networking_cni.go

CNI plugins can return multiple interfaces, eg the bridge plugin. (See https://github.com/containernetworking/plugins/blob/8aad9739d8383de465293d5da346a61ff3131449/plugins/main/bridge/bridge.go#L415)
At the moment a random interface is returned, this PR returns the one with the sandbox.

cni: use correct interface for netStatus

---

README.md

This is mostly switching paragraphs to bullets to make following
instructions easier. In doing so, this also adds instructions to install
things that were previously assumed to be installed, like Vagrant,
Virtualbox, and Consul.
It also removes the expectation that Nomad is cloned to $GOPATH, as that
is not necessary.

doc: Simplify README

---

nomad/csi_endpoint_test.go
nomad/state/state_store.go
nomad/structs/csi.go
nomad/structs/csi_test.go

Fixes https://github.com/hashicorp/nomad/issues/8949 https://github.com/hashicorp/nomad/issues/9230
The `CSIVolume` struct "denormalizes" allocations when it's first queried from the state store. The `CSIVolumeByID` method on the state store copies the volume before denormalizing so that we don't end up with unexpected changes. The copying has some subtle bugs that meant that `Allocations` (as well as `Topologies` and `MountOptions`) were not getting copied when expected.
Also, ensure we never write allocations attached to volumes to the state store during claims.

CSI: fix struct copying errors

---

client/allocrunner/taskrunner/template/template.go
client/allocrunner/taskrunner/template/template_test.go
e2e/consultemplate/consultemplate.go
e2e/consultemplate/input/bad_template_paths.nomad
e2e/consultemplate/input/template_paths.nomad

Followup to #9149 
While Nomad v0.12.8 fixed `NOMAD_{ALLOC,TASK,SECRETS}_DIR` use in
`template.destination`, interpolating these variables in
`template.source` caused a path escape error.
[repro](https://gist.githubusercontent.com/schmichael/d9f89ac845a80c5c05788e1ccc7119e7/raw/512bac51e0e25decdcccfe06dc8cdb6eab1c39c1/repro.hcl)
**Why not apply the destination fix to source?**
The destination fix forces destination to always be relative to the task
directory. This makes sense for the destination as a destination outside
the task directory would be unreachable by the task. There's no reason
to ever render a template outside the task directory. (Using `..` does
allow destinations to escape the task directory if
`template.disable_file_sandbox = true`. That's just awkward and unsafe
enough I …

client: fix interpolation in template source

---

CHANGELOG.md
client/allocrunner/taskrunner/template/template.go
client/allocrunner/taskrunner/template/template_test.go

Backport of `client: fix interpolation in template source` #9383 to 0.12.

Backport of client: fix interpolation in template source #9383

---

website/pages/docs/job-specification/artifact.mdx

Fixes https://github.com/hashicorp/nomad/issues/2043
Adds an example of using HTTP Basic Auth, git options, and using HCL2 syntax
to encode an SSH key from file.
Preview link: https://nomad-77pkljq5p.vercel.app/docs/job-specification/artifact

docs: expand artifact getter options

---

website/pages/docs/commands/job/revert.mdx
website/pages/docs/commands/job/run.mdx
website/pages/docs/drivers/external/singularity.mdx
website/pages/partials/general_options.mdx

Preview links:
* https://nomad-2qc05gu75.vercel.app/docs/commands/job/revert
* https://nomad-2qc05gu75.vercel.app/docs/commands/job/run
* https://nomad-2qc05gu75.vercel.app/docs/drivers/external/singularity

docs: fix some markdown escaping errors

---

command/alloc_logs.go
website/pages/docs/commands/alloc/logs.mdx

Fixes https://github.com/hashicorp/nomad/issues/9182
The `nomad alloc logs` command does not remove terminal escape sequences for
color from the log outputs of a task. Clarify that the standard `-no-color`
flag, which does apply to Nomad's error responses from `nomad alloc logs`,
does not apply to the log output.

docs/help: -no-color does not apply to alloc logs content

---

website/pages/docs/job-specification/template.mdx

Fixes https://github.com/hashicorp/nomad/issues/8703 and https://github.com/hashicorp/nomad/issues/6099
* vault secrets named with `-` characters cannot be read by `consul-template` due to limitations in golang's template rendering engine.
* environment variables are not modified in running tasks if `change_mode.noop` is set.
Preview link https://nomad-qb01ses7r.vercel.app/docs/job-specification/template

docs: template behavior warnings

---

client/allocrunner/taskrunner/template/template.go
client/allocrunner/taskrunner/template/template_test.go

Backport of client: fix interpolation in template source #9383 to 0.11.

Backport to 0.11 of client: fix interpolation in template source #9383

---

CHANGELOG.md
client/allocrunner/taskrunner/template/template.go
client/allocrunner/taskrunner/template/template_test.go

Backport of client: fix interpolation in template source #9383 to 0.10

Backport to 0.10 of client: fix interpolation in template source #9383

---

command/metrics.go
website/data/docs-navigation.js
website/pages/docs/commands/operator/keyring.mdx
website/pages/docs/commands/operator/metrics.mdx

Fixes https://github.com/hashicorp/nomad/issues/9404 and https://github.com/hashicorp/nomad/issues/9403
* `nomad operator keyring` was missing the general options section
* `nomad operator metrics` was missing a page in the docs entirely

docs: add missing command documentation

---

CHANGELOG.md
api/event_stream.go
e2e/events/events.go
vendor/github.com/hashicorp/nomad/api/event_stream.go

Stream() method on the Event API client was neglecting to pass the `index` argument.
i added this as an e2e test, my first one. feedback appreciated.

events: API event stream client should the index flag

---

website/pages/docs/job-specification/template.mdx

Fixes https://github.com/hashicorp/nomad/issues/9417 and rewords https://github.com/hashicorp/nomad/commit/1392246e4e843ad58fa1c1755b8bbfee85d097b3
Only `change_mode = "restart"` will result in the template environment
variables being updated in the task. Clarify the behavior of the unsupported
options.

docs: template signal change_mode not compatible with env

---

e2e/terraform/config/dev-cluster/nomad/client-linux/client.hcl
e2e/terraform/config/full-cluster/nomad/client-linux/indexed/client-0.hcl
e2e/terraform/packer/ubuntu-bionic-amd64/nomad.service
e2e/terraform/packer/ubuntu-bionic-amd64/setup.sh
e2e/terraform/userdata/ubuntu-bionic.sh

Fixes https://github.com/hashicorp/nomad/issues/9324
The cloud-init configuration runs on boot, which can result in a race condition between that and service startup. This has
caused provisioning failures because Nomad expects the userdata to have configured a host volume directory. Diagnosing this was also compounded by a warning being fired by systemd for the Nomad unit file.
* Update the location of the `StartLimitIntervalSec` field to it's post-systemd-230 location.
* Ensure that the weekly AMI build is up-to-date to reduce the risk of unexpected system software changes.
* Move the host volume to a directory we can set up at AMI build time rather than in userdata.

e2e: prevent Ubuntu startup race conditions

---

e2e/csi/csi.go
e2e/csi/input/plugin-aws-ebs-controller.nomad
e2e/csi/input/plugin-aws-ebs-nodes.nomad

* Wait longer for plugins to become healthy. Plugins are Docker containers, and as such sometimes we get delays in startup due to pulling from the registry and this is a source of test flakiness. Give the plugins a little longer to start up.
* Version bump for AWS EBS plugins

E2E: CSI driver provisioning

---

CHANGELOG.md
drivers/rawexec/driver_unix_test.go
drivers/shared/executor/executor.go
drivers/shared/executor/executor_basic.go
drivers/shared/executor/executor_universal_linux.go
plugins/drivers/testutils/exec_testing.go

Fix #9210 .
This update the executor so it honors the User when using `nomad alloc exec`.  The bug was that the exec task didn't honor the init command when execing.
I've added a failing test first, with the failure visible in https://app.circleci.com/pipelines/github/hashicorp/nomad/13370/workflows/4ba32530-41fd-4fa0-b73b-fbc5ad76b7f8/jobs/120664 - but succeeds at the end.

honor task user when execing into raw_exec task

---

nomad/csi_endpoint.go
nomad/state/state_store.go
nomad/state/state_store_test.go

Fixes https://github.com/hashicorp/nomad/issues/9371 and possibly https://github.com/hashicorp/nomad/issues/9248 and https://github.com/hashicorp/nomad/issues/8034
When making updates to CSI plugins and volumes, the state store methods that have open write transactions were querying the state store using the same methods used by the CSI RPC endpoint, but these methods create their own top-level read transactions. During concurrent plugin updates (as happens when a plugin job is stopped), this can cause write skew in the plugin counts. This bug hasn't yet been identified as the root cause of any volume query bug, but it seems likely.
Best reviewed commit-by-commit.

CSI: fix transaction handling in state store

---

GNUmakefile
tools/buf/buf.yaml

Parameterize it so we can arbitrary target other versions, if we
are doing some manual checking, specially in the beginning when we may
want to validate compatibilities for skip release upgrades.
Also, introduce `checkbuf` target so we can run buf linter without the
rest.

Parameterize buf compatibility check

---

ui/app/templates/csi/plugins/index.hbs
ui/app/templates/csi/volumes/index.hbs
ui/tests/acceptance/volumes-list-test.js

Fixes https://github.com/hashicorp/nomad/issues/9252
Plugin health for controllers should show "Node Only" in the UI only when both
conditions are true: controllers are not required, and no controllers have
registered themselves (0 expected controllers). This accounts for "monolith"
plugins which might register as both controllers and nodes but not necessarily have 
`ControllerRequired = true` because they don't implement the Controller RPC 
endpoints we need (this requirement was added in https://github.com/hashicorp/nomad/pull/7844)
This changeset includes the following fixes:
* Update the Plugins tab of the UI so that monolith plugins don't show "Node
Only" once they've registered.
* Add the missing "Node Only" logic to the Volumes tab of the UI.

csi/ui: show Node Only for volumes when controllers aren't required

---

drivers/shared/executor/proto/executor.pb.go
drivers/shared/executor/proto/executor.proto
plugins/base/proto/base.pb.go
plugins/base/proto/base.proto
plugins/device/proto/device.pb.go
plugins/device/proto/device.proto
plugins/drivers/proto/driver.pb.go
plugins/drivers/proto/driver.proto
plugins/shared/hclspec/hcl_spec.proto
tools/buf/buf.yaml

Use targetted ignore comments for the cases where we are bound by
backward compatibility.
I've left some file based linters, especially when the file is riddled
with linter voilations (e.g. enum names), or if it's a property of the
file (e.g. package and file names).
I encountered an odd behavior related to RPC_REQUEST_RESPONSE_UNIQUE and
RPC_REQUEST_STANDARD_NAME.  Apparently, if they target a `stream` type,
we must separate them into separate lines so that the ignore comment
targets the type specifically.
This is the follow up of https://github.com/hashicorp/nomad/pull/9414#discussion_r527870340 .

buf: use comment ignores

---

e2e/consulacls/manage.go

The clean up in #8908 inadvertently caused the output from the scripts
involved in the Consul ACL bootstrap process to be printed as a big blob
of bytes, which is slightly less useful than the text version.

e2e: print consulacls scripts output as string

---

api/csi.go
command/agent/csi_endpoint.go
ui/app/serializers/volume.js
ui/mirage/models/csi-volume.js
ui/mirage/serializers/csi-volume.js
ui/tests/acceptance/volume-detail-test.js
ui/tests/acceptance/volumes-list-test.js
ui/tests/unit/serializers/volume-test.js
vendor/github.com/hashicorp/nomad/api/csi.go
website/pages/api-docs/volumes.mdx

Fixes https://github.com/hashicorp/nomad/issues/9215
The API is missing values for `ReadAllocs` and `WriteAllocs` fields, resulting
in allocation claims not being populated in the web UI. These fields mirror
the fields in `nomad/structs.CSIVolume`. Returning a separate list of stubs
for read and write would be ideal, but this can't be done without either
bloating the API response with repeated full `Allocation` data, or causing a
panic in previous versions of the CLI.
The `nomad/structs` fields are persisted with nil values and are populated
during RPC, so we'll do the same in the HTTP API and populate the `ReadAllocs`
and `WriteAllocs` fields with a map of allocation IDs, but with null
values. The web UI will then create its `ReadAllocations` and
`WriteAllocations` fields by mapping from …

csi/api: populate ReadAllocs/WriteAllocs fields

---

CHANGELOG.md

Batched up changelog for CSI bug fixes and improvements in 1.0. Waiting on merges of:

changelog entries for CSI

---

client/fingerprint/env_azure.go

Nomad 1.0.0 features Azure fingerprinting, however it is missing 1 important metadata field `compute/zone`.
When a VM is part of a scaling set it is populated (non-empty) in the response from Azure metadata service.
With AWS we can do the following in the job def to spread allocs across AZs equally:
```
spread {
attribute = "${attr.platform.aws.placement.availability-zone}"
weight = 100
}
```
By adding 1 line to the code we can do the same on Azure:
```
spread {
attribute = "${attr.platform.azure.zone}"
weight = 100
}
```
Not adding `compute/zone` to the tests because it is empty when a VM is not a part of VMSS.

Add "compute/zone" to Azure fingerprinting

---

e2e/connect/acls.go
e2e/connect/client.go
e2e/connect/connect.go
e2e/connect/input/ingress-gateway.nomad
e2e/consulacls/nomad-server-policy.hcl

Add the ingress gateway example from the noamd connect examples
to the e2e Connect suite. Includes the ACLs enabled version,
which means the nomad server consul acl policy will require
operator=write permission.

e2e: add e2e test for consul connect ingress gateway demo

---

command/node.go

Fix a error in the documentation that prints as a result of the "nomad node help" command.

command: Fix node help error

---

CHANGELOG.md
api/services.go
api/services_test.go
command/agent/consul/connect.go
command/agent/consul/connect_test.go
command/agent/job_endpoint.go
command/agent/job_endpoint_test.go
contributing/checklist-jobspec.md
nomad/structs/diff_test.go
nomad/structs/services.go
vendor/github.com/hashicorp/nomad/api/services.go
website/pages/docs/job-specification/upstreams.mdx

Before, upstreams could only be defined using the default datacenter.
Now, the `datacenter` field can be set in a connect upstream definition,
informing consul of the desire for an instance of the upstream service
in the specified datacenter. The field is optional and continues to
default to the local datacenter.
Closes #8964

consul/connect: enable setting datacenter in upstream

---

client/rpc.go
nomad/rpc.go
nomad/structs/structs.go

Overhaul the RPC retry logic with recent learnings about how it can fail. For tons of detail about all the learnings and care we put into this please see https://github.com/hashicorp/nomad/issues/9265
I realize this probably looks scary, so i am also available for a voice chat, and I hope the details in #9265 help.
[The fix](https://github.com/hashicorp/nomad/pull/8921) which we merged into Nomad for the above issue is a good one - without it retries cannot possibly work, but it does have a flaw.
Consider:
1. A long poll is made with a timeout of 5 minutes
2. A retriable error occurs at the 4 minute mark
3. We make a new request to the server
What you would expect is that the second request, #3, has a timeout of 1 minute. Unfortunately, that is not what happens. The request is made again …

Fix RPC retry logic in nomad client's rpc.go for blocking queries

---

website/pages/docs/drivers/docker.mdx

Fixes https://github.com/hashicorp/nomad/issues/3030
If Docker auth helpers are used but auth fails or the image isn't found, we
hard fail the task. Users may set `auth_soft_fail` to fallback to the public
Docker Hub on a per-job basis. But users that mix public and private images
have to set `auth_soft_fail=true` for every job using a public image if Docker
auth helpers are used.
Preview link https://nomad-8j2sxuxz9.vercel.app/docs/drivers/docker

docs: warn about Docker auth_soft_fail behavior

---

nomad/state/state_store.go

return potential error from txn.Commit, missed during initial pass through and subsequent namespace OSS commit.

return potential errors from txn.Commit

---

client/acl_test.go
command/acl_policy_delete_test.go
command/acl_policy_info_test.go
command/acl_policy_list_test.go
command/acl_token_delete_test.go
command/acl_token_info_test.go
command/acl_token_list_test.go
command/acl_token_self_test.go
command/acl_token_update_test.go
command/agent/testagent.go
nomad/acl_endpoint_test.go
nomad/acl_test.go
nomad/csi_endpoint_test.go
nomad/event_endpoint.go
nomad/event_endpoint_test.go
nomad/fsm.go
nomad/fsm_test.go
nomad/job_endpoint_test.go
nomad/leader_test.go
nomad/mock/acl.go
nomad/state/events.go
nomad/state/state_store.go
nomad/state/state_store_test.go
nomad/stream/event_broker.go
nomad/stream/event_broker_test.go
nomad/stream/subscription.go
nomad/structs/event.go
nomad/testing.go

Re-Evaluate or terminate streams on ACL changes.
This PR adds ACL events to the event broker. When the broker receives an ACL event it re-evaluates current subscriptions requests and if necessary, closes the stream.
ACL handling and checking has been moved from the RPC endpoint into the event broker itself using a delegate interface to query the state store. Previously, all ACL object creation happened on the Nomad Server itself, with the server having its own acl 2 queue cache. The event broker now duplicates some of this logic, and also maintains a smaller cache for itself and to be able to use `structs.CompileACLObjects`.
Best viewed commit by commit
[`master...1e39a71`](https://github.com/hashicorp/nomad/compare/master...1e39a7179203538785b9885d8b27ff8aa6a08223) are mostly changes to …

Event Stream: Track ACL changes, unsubscribe on invalidating changes

---

CHANGELOG.md
client/client.go
nomad/node_endpoint.go

Always wait 200ms before calling the Node.UpdateAlloc RPC to send
allocation updates to servers.
Prior to this change we only reset the update ticker when an error was
encountered. This meant the 200ms ticker was running while the RPC was
being performed. If the RPC was slow due to network latency or server
load and took >=200ms, the ticker would tick during the RPC.
Then on the next loop only the select would randomly choose between the
two viable cases: receive an update or fire the RPC again.
If the RPC case won it would immediately loop again due to there being
no updates to send.
When the update chan receive is selected a single update is added to the
slice. The odds are then 50/50 that the subsequent loop will send the
single update instead of receiving any more updates.
This could …

client: always wait 200ms before sending updates

---

website/data/docs-navigation.js
website/pages/docs/operations/index.mdx
website/pages/docs/operations/nomad-agent.mdx
website/redirects.js

As suggested in https://github.com/hashicorp/nomad/pull/9395#issuecomment-730547191
Website preview: https://nomad-edohxyewc.vercel.app/docs/operations/nomad-agent

docs: move agent lifecycle doc under Operations heading

---

command/operator_debug.go
command/operator_debug_test.go
helper/funcs.go
helper/funcs_test.go

- Adds `pprof-duration` to allow pprof capture over timeframe longer than 1 second
- Extends CSI support to iterate over plugins and volumes for more detail (fixes #9262)
From the helpText:
```
-pprof-duration=<duration>
Duration for pprof collection. Defaults to 1s.
```

nomad operator debug - add pprof duration / csi details

---

website/pages/docs/job-specification/check_restart.mdx

Add a warning about check_restart being limited to task networks and
link to the relevant issue: #9176.

docs: check_restart is broken for group networks

---

nomad/state/events.go
nomad/state/events_test.go

Switch on change table instead of type to prevent multiple events being created for values like Job which are tracked in multiple tables.
resolves https://github.com/hashicorp/nomad/issues/9484

Events switch on memdb change table instead of type to prevent duplicates

---

CHANGELOG.md
client/client.go
nomad/job_endpoint_hook_connect.go
website/pages/docs/job-specification/sidecar_task.mdx
website/pages/docs/upgrade/upgrade-specific.mdx

Previously, every Envoy Connect sidecar would spawn as many worker
threads as logical CPU cores. That is Envoy's [default behavior](https://www.envoyproxy.io/docs/envoy/latest/operations/cli#cmdoption-concurrency) when
`--concurrency` is not explicitly set. Nomad now sets the concurrency
flag to 1, which is sensible for the default cpu = 250 Mhz resources
allocated for sidecar proxies. The concurrency value can be configured
in Client configuration by setting `meta.connect.proxy_concurrency`.
Closes #9341
For more finely tuned configuration (i.e. job/group/task level), we'll need https://github.com/hashicorp/nomad/issues/7221

consul/connect: default envoy concurrency to 1

---

e2e/lifecycle/inputs/service.nomad

To test the lifecycle `poststop` hook for service jobs, we need to confirm that poststop will run after the main task is stopped with `nomad job stop` or `nomad alloc signal`. This signal is determined by the task driver, which in the Docker case was recently switched from SIGINT to SIGTERM re: #8932 & #8933.

lifecycle: update e2e test for service job with new docker signal #8932

---

website/pages/docs/job-specification/volume.mdx
website/pages/docs/job-specification/volume_mount.mdx

Fixes https://github.com/hashicorp/nomad/issues/8058 https://github.com/hashicorp/nomad/issues/8262
Expand `volume` and `volume_mount` sections to describe how to use HCL2
dynamic blocks and interpolation to have finer-grained control over how
allocations get volumes.
Preview link: https://nomad-1kc5xw5ek.vercel.app/docs/job-specification/volume#volume-interpolation
(cc @galeep as a heads up)

docs: using interpolation for volumes

---

CHANGELOG.md
drivers/docker/driver.go
drivers/docker/handle.go

Possible fix for https://github.com/hashicorp/nomad/issues/9375 and https://github.com/hashicorp/nomad/issues/9376, based on the discovery of open Docker bugs 
that might trigger this behavior (as described in https://github.com/hashicorp/nomad/issues/9375#issuecomment-737487598). I've smoke-tested 
this for safety but haven't had a chance yet to see if it really improves the situation from
those issues.
When the Docker driver kills as task, we send a request via the Docker API for
dockerd to fire the signal. We send that signal and then block for the
`kill_timeout` waiting for the container to exit. But if the Docker API
blocks, we will block indefinitely because we haven't configured the API call
with the same timeout.
This changeset is a minimal intervention to add the timeout to the …

docker: kill signal API should include timeout context

---

website/pages/docs/integrations/consul-connect.mdx
website/pages/docs/upgrade/upgrade-specific.mdx

During testing we discovered old versions of Nomad and Consul seemed to
prevent Envoy from accepting new connections while the Nomad agent was
being upgraded.

docs: clarify connect upgrade procedure

---

ui/app/models/volume.js
ui/app/templates/csi/volumes/index.hbs
ui/mirage/serializers/csi-volume.js

As detailed in #9495, the collection query `GET /v1/volumes?type=csi` doesn’t return `ReadAllocs` and `WriteAllocs`, so the `# Allocs` cell was always showing `0` upon first load because it was derived from the lengths of those arrays. This uses the heretofore-ignored `CurrentReaders` and `CurrentWriters` values to calculate the total instead.
The single-resource query `GET /v1/volume/csi%2F:id` doesn’t return `CurrentReaders` and `CurrentWriters` but you can see here that the missing values don’t cause the already-fetched ones to be deleted.
Thanks to @apollo13 for reporting this in #9495 and to @tgross for the API logs and suggestion.

UI: Fix allocation count in CSI volumes table

---

website/pages/docs/configuration/client.mdx

Add note about `.conflist` extension for CNI config files.
Closes #9534

docs: note conflist extension for cni plugin configuration files

---

website/pages/docs/autoscaling/plugins/apm.mdx
website/pages/docs/autoscaling/policy.mdx

Add documentation around the new `check` parameter called `query_window`.
This parameter can be used to specify a query window size when calling the APM.

docs: update autoscaling docs for the new query interface

---

website/pages/docs/job-specification/hcl2/expressions.mdx
website/pages/docs/job-specification/hcl2/index.mdx

Mainly note that block labels need to be string literals, and that decimals without a leading significant digits aren't acceptable anymore (e.g. `.9` are required to be `0.9`).
Dynamic blocks can be used here, but feels too much of a hack, or a hammer to highlight it here, specially given the error reporting and debugging isn't so straightforward. I'd advocate internally for relaxing the restriction and allowing expressions in block labels instead.
Related to https://github.com/hashicorp/nomad/issues/9522 .

document some hcl2 quarks

---

command/agent/agent_endpoint.go
command/operator_debug_test.go

When running `nomad operator debug` from a client node, attempts to retrieve Agent.Host from a server member would panic when trying to make the RPC request.  This PR tests both s.agent.Server() and s.agent.Client() to ensure they are valid before making the RPC call.
A test case was added to verify the panic, then verify the fix worked.  Also cleaned up TestDebug_NodeClass test as it was used as the test template.

fix AgentHostRequest panic found in GH-9546

---

website/pages/docs/install/quickstart.mdx

Fixes #9535 - Katacoda guides are all embedded into Learn guides now, so no direct links.
Small drive-by style fixes.

Upgrade links to guides

---

contributing/golang.md
scripts/update_golang_version.sh

Updated Nomad / Go version table to include 1.0.  0.12 was missing altogether, so I also added the interim versions to provide a more complete picture of what we shipped.
Also a small tweak to `update_golang_version.sh` help text.

Update golang version table

---

CHANGELOG.md

I didn't think this patch had hit the 1.0.0 merge window but it looks like it did.

changelog entry for #9495

---

command/agent/event_endpoint.go

Not sure if you want to have an additional test for this. I checked and I don't think any other endpoint has.

return 405 on non-GET requests to /v1/event/stream (fixes #9526)

---

e2e/events/events.go

`Eval` changed to `Evaluation` in 1.0.0, but there is also an easier way to get a concrete type out of an event now.

use concrete type helper instead of interface surfing

---

.circleci/config.yml

These tags default to the same value in GNUMakefile. This will also help
fix a discrepancy between the build-binaries job in OSS and Ent, which will make merging OSS into Ent clean.

circleci: Remove GO_TAGS from build-binaries job

---

client/fingerprint/cpu.go

Previously, Nomad would fail to startup if the CPU fingerprinter could
not detect the cpu total compute (i.e. cores * mhz). This is common on
some EC2 instance types (graviton class), where the env_aws fingerprinter
will override the detected CPU performance with a more accurate value
anyway.
Instead of crashing on startup, have Nomad use a low default for available
cpu performance of 1000 ticks (e.g. 1 core * 1 GHz). This enables Nomad
to get past the ignored cpu fingerprinting on those EC2 instances. The
crashing error message is now a log statement suggesting the setting of
cpu_total_compute in client config.
Fixes #7989

client/fingerprint/cpu: use fallback total compute value if cpu not detected

---

.circleci/Makefile

OSS no longer needs the multi-file config Makefile content, so it was removed. However, enterprise does benefit from having that around. We can allow enterprise to expand on OSS' CircleCI Makefile by adding an include directive in OSS. This will allow the Makefile to be the same on both OSS and Enterprise, so merge conflicts cannot occur.

circleci: Allow expanding Makefile in enterpise

---

command/helpers.go
command/helpers_test.go

Apparently, we missed passing VarFile argument, so var files were
ignored.
Fixes https://github.com/hashicorp/nomad/issues/9588

actually honor var files

---

CHANGELOG.md
client/taskenv/services.go
client/taskenv/services_test.go
nomad/job_endpoint_hook_connect.go
nomad/job_endpoint_hook_connect_test.go
nomad/job_endpoint_test.go

This PR enables job submitters to use interpolation in the connect
block of jobs making use of consul connect. Before, only the name of
the connect service would be interpolated, and only for a few select
identifiers related to the job itself (#6853). Now, all connect fields
can be interpolated using the full spectrum of runtime parameters.
Note that the service name is interpolated at job-submission time,
and cannot make use of values known only at runtime.
Fixes #7221

consul/connect: interpolate connect block

---

.circleci/config.yml

Makes two changes to CI steps:
1. Halt the website-docker-image job early if no changes are detected. We
halt early before spinning up the remote docker engine, as the remote
docker engine step can add some delay (seconds to minutes) and is more
likely to suffer circleci instability.
This relies on https://circleci.com/docs/2.0/configuration-reference/#ending-a-job-from-within-a-step .
2. Add a CircleCI conditional to avoid running website worklows on forks. This eliminates starting the job in the first place!
The second relies on Config 2.1 option that wasn't available to us before: https://circleci.com/docs/2.0/pipeline-variables/#conditional-workflows .

Tweak early return website workflow

---

client/pluginmanager/group.go
client/pluginmanager/group_test.go
client/pluginmanager/testing.go

As pointed out by [@tgross](https://github.com/hashicorp/nomad/pull/9590#discussion_r539534906), prior to this change we would have been blocking until all managers waited for first fingerprint rather than timing out as intended.

pluginmanager: WaitForFirstFingerprint times out

---

ui/tests/acceptance/job-detail-test.js

This is meant to fix the flaky test failure seen [here](https://app.circleci.com/pipelines/github/hashicorp/nomad/13672/workflows/5a38de22-ca06-4deb-adeb-6eab375a749f/jobs/124184). There are two changes:
* constructing a job specifically for the recommendations test that has more task groups and therefore a vanishingly small (0.0001%) likelihood that no recommendations will be created
* calculating the number of task groups with recommendations instead of assuming that the group count would always equal the recommendation summary count, which was false in 1% of cases

UI: Fix job recommendation test flakiness

---

command/agent/http.go
command/agent/http_test.go
go.mod
go.sum
vendor/github.com/hashicorp/go-connlimit/LICENSE
vendor/github.com/hashicorp/go-connlimit/NOTICE.md
vendor/github.com/hashicorp/go-connlimit/README.md
vendor/github.com/hashicorp/go-connlimit/connlimit.go
vendor/modules.txt

Expands on https://github.com/hashicorp/nomad/pull/9359 from @benbuzbee 
In addition this PR fixes the original tests, which produced the correct result for the wrong reason. In TLS mode, the clients were creating HTTP connections which would be shunted by the server in the same way being ratelimited would (i.e. `io.EOF`). Instead, use a tls `net.Conn` for tls tests.
Also rebased the original commit to remove extraneous file. 
Closes #9359

Use go-connlimit to ratelimit with 429 responses

---

website/pages/docs/configuration/client.mdx
website/pages/docs/job-specification/env.mdx
website/pages/docs/job-specification/group.mdx
website/pages/docs/job-specification/hcl2/index.mdx
website/pages/docs/job-specification/hcl2/variables.mdx
website/pages/docs/job-specification/job.mdx
website/pages/docs/job-specification/meta.mdx
website/pages/docs/runtime/interpolation.mdx

Tweak the docs for some HCL2 changes: update remaining examples that still quoted `env`/`meta` keys, remove `var-file` reference (until https://github.com/hashicorp/nomad/pull/9592 ships), and note that env/meta keys need to be valid identifiers.

docs: Moe unquoting of HCL block attributes

---

ui/tests/acceptance/client-detail-test.js
ui/tests/acceptance/client-monitor-test.js
ui/tests/acceptance/optimize-test.js
ui/tests/acceptance/plugin-detail-test.js
ui/tests/acceptance/regions-test.js
ui/tests/acceptance/search-test.js
ui/tests/acceptance/server-monitor-test.js
ui/tests/acceptance/task-detail-test.js
ui/tests/acceptance/task-group-detail-test.js
ui/tests/acceptance/volume-detail-test.js
ui/tests/pages/allocations/task/detail.js
ui/tests/pages/clients/detail.js
ui/tests/pages/clients/monitor.js
ui/tests/pages/jobs/job/task-group.js
ui/tests/pages/layout.js
ui/tests/pages/optimize.js
ui/tests/pages/servers/monitor.js
ui/tests/pages/storage/plugins/detail.js
ui/tests/pages/storage/volumes/detail.js

Various page objects had `breadcrumbs` and `breadcrumbFor` within them, this
moves those to the existing `Layout` page object that contains shared page objects.
`Layout` is sometimes imported as `PageLayout`; I chose the former for tests that
didn’t have it imported already. I could easily change them all to the same thing if
that seems desirable 🤓

UI: Move breadcrumbs objects into shared layout object

---

nomad/job_endpoint_hook_connect.go
website/pages/docs/upgrade/upgrade-specific.mdx

Applying the default `--concurrency` for gateways was missed before.
Set the default Envoy concurrency to 1 for connect gateways. The
same override value `meta.connect.proxy_concurrency` applies.

consul/connect: set default Envoy worker threads for gateways

---

command/helpers.go
command/helpers_test.go
website/pages/docs/job-specification/hcl2/variables.mdx

Another 🤦 case of missing to wire parameters in :( , just the environment variables this time.
Fixes #9622 .

set EnvVar variables in hcl2 parsing

---

.golangci.yml

As suggested, enable `depgaurd` and enable it on a package recently removed that should never be invited back (`github.com/hashicorp/consul/command/flags`).

Add and enable depgaurd linter

---

client/allocrunner/networking_cni.go

CNI network configuration is currently only supported on Linux.
For now, add the linux build tag so that the deadcode linter does
not trip over unused CNI stuff on macOS.

build: set linux build tag on CNI networking

---

website/pages/docs/drivers/docker.mdx
website/pages/docs/job-specification/hcl2/index.mdx

Make backward compatibility notes about Task Driver config options.  Namely, call out the use of blocks with non-identifier attributes (like in docker systctl and storage_options) or nesting block syntax within an attribute assignment.  Neither of these are valid HCL2.  The solution is relatively simple: We can add `=` and quote the non-identifier attribute names.
Related to https://github.com/hashicorp/nomad/issues/9604 .

docs: more notes about hcl2 compatibility

---

command/operator_debug_test.go

Refactored tests to eliminate duplicated code, and added two writeBytes tests to validate writing a nil file and path escaping sandbox.  Tests that do not use the runTestCases function have been moved to the bottom of the file.

Debug test refactor

---

GNUmakefile

Add a build target for Apple Silicon (m1) macs.
Note that Go must have been built with c4f497da6f for
Nomad to work on darwin/arm64 (i.e. wait for go1.16).
Closes #9408

build: add build target for darwin/arm64

---

scripts/release/Dockerfile
scripts/vagrant-linux-priv-go.sh

This makes few changes to golang installation scripts: ensure that the script fails if any step fails, retry downloading if the download fails.
Also, update our release docker container image to use 18.04, so it matches our Vagrant box.  We ought to upgrade both to 20.04 but punting on for now that until I can test the Vagrant box.

scripts: fail if golang installation fails

---

CHANGELOG.md
client/allocrunner/networking_cni.go

Fixes https://github.com/hashicorp/nomad/issues/9647
When we iterate over the interfaces returned from CNI setup, we filter for one
with the `Sandbox` field set. Ensure that if none of the interfaces has that
field set that we still return an available interface.

cni: prevent NPE if no interface has sandbox field set

---

jobspec2/parse.go

Previously, if decoding the job, tasks, or vault portion of the config
failed, we would not return an error; it was silently ignored.
This also includes a little refactor to reduce some duplication I saw.

jobspec2: decode returns error in more cases

---

GNUmakefile

This removes small differences between the targets, like the statement about what's being built, and makes it clear when targets special-case environment variables.
It makes the help less verbose, which could be considered a downside:
```
...snip...
integration-test          Run Nomad integration tests
lint-deps                 Install linter dependencies
pkg/%/nomad               Build Nomad for GOOS_GOARCH, e.g. pkg/linux_amd64/nomad
prerelease                Generate all the static assets for a Nomad release
release                   Build all release packages which can be built on this platform.
...snip...
```
However, on the upside, we don't have to manually write the rules for all `GOOS`/`GOARCH` combos anymore.

makefile: DRY out pkg targets

---

.circleci/config.yml

Builds on the main branch have been failing, perhaps due to
a corrupt cache.

UI: Change cache prefix

---

CHANGELOG.md

https://github.com/hashicorp/nomad/pull/9624
https://github.com/hashicorp/nomad/pull/9611

docs: add two connect entries to changelog

---

CHANGELOG.md
client/allocrunner/taskrunner/interfaces/lifecycle.go
client/allocrunner/taskrunner/lifecycle.go
client/allocrunner/taskrunner/template/template.go
client/allocrunner/taskrunner/template/template_test.go
website/pages/docs/upgrade/upgrade-specific.mdx

Fixes https://github.com/hashicorp/nomad/issues/9491
When a task is restored after a client restart, the template runner will
create a new lease for any dynamic secret (ex. Consul or PKI secrets
engines). But because this lease is being created in the prestart hook, we
don't trigger the `change_mode`.
This changeset uses the the existence of the task handle to detect a
previously running task that's been restored, so that we can trigger the
template `change_mode` if the template is changed, as it will be only with
dynamic secrets.
---
Note to reviewers: because this requires a bit of a refactor of the `onTemplateRendered`  so that it can be used for both first-pass and re-render, this PR is probably best reviewed commit-by-commit. …

template: trigger change_mode for dynamic secrets on restore

---

website/pages/docs/drivers/docker.mdx
website/pages/docs/job-specification/hcl2/index.mdx
website/pages/docs/job-specification/hcl2/variables.mdx

Revert the removal of `-var-file` and variable environment variable setting.  Also, document the new docker `mount` field.

Update HCL2 docs for 1.0.1

---

e2e/terraform/compute.tf
e2e/terraform/packer/ubuntu-bionic-amd64/dnsconfig.sh
e2e/terraform/packer/ubuntu-bionic-amd64/dnsmasq.service
e2e/terraform/packer/ubuntu-bionic-amd64/setup.sh

Our dnsmasq configuration needs host-specific data that we can't configure in
the AMI build. But configuring this in userdata leads to a race between
userdata execution, docker.service startup, and dnsmasq.service startup. So
rather than letting dnsmasq come up with incorrect configuration and then
modifying it after the fact, do the configuration in the service's prestart,
and have it kick off a Docker restart when we're done.
I've built a test AMI with this and it seems to solve the recent provisioning issue.
Will kick off a re-build on CI and then the nightly E2E when that's done.

e2e: move dnsmasq config into dnsmasq service unit

---

e2e/terraform/README.md
e2e/terraform/terraform.tfvars

* Bump the default developer cluster to a 1.0.x version.
* Add some design notes to the README to make it a little more obvious what the constraints on future improvements of the provisioning process.

E2E: default version bump and design docs

---

nomad/job_endpoint_hook_connect.go
nomad/job_endpoint_hook_connect_test.go
website/pages/docs/job-specification/connect.mdx
website/pages/docs/job-specification/gateway.mdx
website/pages/docs/job-specification/sidecar_task.mdx

Add the ability to configure the Task used for connect gateways,
similar to how sidecar Task can be configured.
The implementation here simply re-uses the `sidecar_task` stanza,
which now gets applied whether `connect.sidecar_service` or
`connect.gateway` is the thing being defined. In retrospect,
`connect.sidecar_task` might have been more generically named
as something like `connect.task`.
Closes #9474

consul/connect: enable configuring custom gateway task

---

ui/app/components/topo-viz.js
ui/tests/unit/components/topo-viz-test.js

Fixes #9658 
Conveniently, we were already detecting this case—just handling it in a less than ideal way.
Nomad will reference and surface allocations with no nodes until a GC event clears them. Draining and removing a node should consistently get a cluster into this state.
Since the topo viz only shows running and starting allocations on nodes, omitting these orphaned allocations has no impact on the feature.

UI: Quietly ignore orphaned allocs in the topo viz

---

GNUmakefile

Warn about unsupported OS rather than error
Also:
* Only print the warning when trying to build Nomad
* Print correct list of supported OSes
---
Re-scope VERBOSE=true
Previously this was only set when the OS was Linux; this was added in
805ade7d3.
I'm not sure who would actually see the verbose output, given it doesn't run in CI and is only used in the test-nomad, test-nomad-module, e2e-test, and integration-test targets. :shrug: 
---
Set 'only' ALL_TARGETS rather than append
This is functionally no different than before, but it's more correct.

makefile: Re-scope VERBOSE=true, update build warnings

---

command/quota_init.go
website/pages/docs/commands/namespace/apply.mdx

This updates `quota init` to provide an unlimited quota by default, which is then referenced in the docs for how to remove a quota. The [Learn docs](https://learn.hashicorp.com/tutorials/nomad/quotas) would be out of date with this change, but maybe should also be updated to include similar quota removal steps.

docs: Add quota removal step to namespace apply

---

website/pages/docs/install/production/requirements.mdx
website/pages/docs/operations/nomad-agent.mdx

Document recommendations for configuring the Nomad data directory permissions. (Reviewed previously in ENT)

docs: data directory permissions

---

website/pages/docs/job-specification/service.mdx

I followed #7709 when trying to reproduce this. I wasn't able to confirm that name needs to be set on both `service` and `check`; it appeared only to be required on `check` (as the service gets a name by default).

docs: Document required name for expose=true check

---

website/pages/docs/configuration/client.mdx

This field is deprecated and should not be used.
Closes #9385

docs: Remove network_speed client config field

---

client/devicemanager/instance.go

We started noticing log lines like:
```
2020-12-29T20:02:55.284Z [ERROR] client.device_mgr: fingerprinting returned an error: plugin=fly-volume error=<nil>
```
when our device plugin stopped. That's not very helpful. Looking at the code, it appeared that the error being logged was unrelated to the problem.
This should log the correct error (the fingerprint response error)

Wrong device plugin fingerprint error being logged

---

CHANGELOG.md
nomad/serf.go
nomad/serf_test.go

When [`bootstrap_expect`](https://www.nomadproject.io/docs/configuration/server#bootstrap_expect) is 0, the Nomad server shouldn't attempt to bootstrap and elect itself as the leader.  This is the behavior of Consul, the previous Nomad behavior, as well as intended behaviod.
The behavior was accidentally changed in https://github.com/hashicorp/nomad/pull/7252/files#diff-adc7208ec155586c7694004df7060da8916517d28041e0660d171d73bfdfee47L86-R86 . Prior to that, Nomad only attempted to bootstrap if BootstrapExpect is non-zero, while the change made it such that bootstrapping is always attempted regardless of bootstrap expect value.
Added a failing test in https://app.circleci.com/pipelines/github/hashicorp/nomad/13931/workflows/4f71cf9d-5617-4ce1-b92c-749cfddf05f2/jobs/127419 .

Don't bootstrap when `bootstrap_expect` is zero

---

client/alloc_endpoint.go
client/alloc_endpoint_test.go
website/pages/api-docs/client.mdx

The client allocation GC API returns a misleading error message when the
allocation exists but is not yet eligible for GC. Make this clear in the error
response.
Note in the docs that the allocation will still show on the server responses.
Got rabbit-holed a bit by this while working on https://github.com/hashicorp/nomad/issues/9376

client: improve alloc GC API error messages

---

website/pages/docs/operations/metrics.mdx

Fixes https://github.com/hashicorp/nomad/issues/7728 https://github.com/hashicorp/nomad/issues/8297. 
* Remove metrics deprecated by https://github.com/hashicorp/nomad/pull/9080
* Fixes all the tables
* Adds a bunch of descriptions
There's probably some metrics I've missed here still, but we can add those more easily now that the tables are fixed.
Preview link: https://nomad-7ced9jfx9.vercel.app/docs/operations/metrics

docs: update metrics tables

---

demo/vagrant/Vagrantfile

Vagrant was using Ubuntu 18.04 as base; update to use 20.04
Also updated Nomad and Consul versions to the latest

Version update for demo Vagrant: Ubuntu 20.04, Nomad 1.0.1, Consul 1.9.0

---

e2e/terraform/packer/ubuntu-bionic-amd64/dnsconfig.sh
e2e/terraform/packer/ubuntu-bionic-amd64/dnsmasq.service
e2e/terraform/provision-nomad/main.tf

* systemd units require absolute paths
* ensure directory exists for dnsmasq
This should have been caught when I tested https://github.com/hashicorp/nomad/pull/9660, but I can't figure out why it didn't show up there. The resulting failure is intermittent so it's possible that there's a race condition we're winning sometimes in the directory configuration, but sometimes not.
AMI ami-00efbb65a6510a043 has this patch, which I've tested for a full cluster (and inadvertently so has @shoenig b/c I built the AMI without tagging it for testing accidentally).

e2e: dnsmasq configuration fixes

---

contributing/checklist-rpc-endpoint.md

Adds notes to our contributor checklist to make sure we keep the new table in https://github.com/hashicorp/nomad/pull/9694 up to date.

docs: add metrics and API docs to RPC contributors checklist

---

CHANGELOG.md
client/allocrunner/taskrunner/artifact_hook.go
client/allocrunner/taskrunner/artifact_hook_test.go
client/allocrunner/taskrunner/envoy_version_hook_test.go
client/allocrunner/taskrunner/getter/getter.go
client/allocrunner/taskrunner/getter/getter_test.go
client/allocrunner/taskrunner/task_dir_hook.go
client/allocrunner/taskrunner/template/template.go
client/allocrunner/taskrunner/template/template_test.go
client/taskenv/env.go
client/taskenv/env_test.go
client/taskenv/services_test.go
e2e/consultemplate/consultemplate.go
e2e/consultemplate/input/template_paths.nomad
e2e/consultemplate/input/template_shared_alloc.nomad
plugins/drivers/testutils/testing.go

refactored #9668 for (imho) better abstraction
Resolves #9610 
Resolves #9389 
Resolves #6929
The main change is to use client-specific absolute paths in the environment maps for interpolating `source` for `template` and `destination` for `template` and `artifact`.
Because of this, it required adjusting the sandbox-escape checks to allow shared alloc dir, in addition to task working dir.
The result is that we should now support source and destination paths of the following forms:
* well-known interpolated paths: `${NOMAD_ALLOC_DIR}`, `${NOMAD_SECRETS_DIR}`, `${NOMAD_TASK_DIR}`
* task-dir relative paths: `local`, `secrets`, `../alloc`
The new [e2e test](https://github.com/hashicorp/nomad/pull/9668/files#diff-f806af7529cc10075671623ecd284693609d4014a3245fa05c34691feeac265a) shows the …

address interpolation of artifact and template src/dest

---

nomad/scaling_endpoint_test.go

stale read support is built-in to RPC forwarding, as long as the request object has `IsRead() == true`. this PR adds a simple test of that for policy get and list. 
_`IsRead() == true` is, like most read requests, provided by the embedded `QueryOptions`_
resolves #7410

simple stale read test

---

website/pages/api-docs/quotas.mdx
website/pages/api-docs/recommendations.mdx
website/pages/api-docs/sentinel-policies.mdx
website/pages/docs/autoscaling/index.mdx
website/pages/docs/autoscaling/plugins/strategy.mdx
website/pages/docs/autoscaling/plugins/target.mdx
website/pages/docs/autoscaling/policy.mdx
website/pages/docs/integrations/vault-integration.mdx
website/pages/docs/job-specification/multiregion.mdx

Fixes #9529 . Added Enterprise Badges in these [files](https://github.com/hashicorp/nomad/search?l=Markdown&q=%2A%2AEnterprise+Only%21%2A%2A+This+functionality+only+exists+in) using the reference from [here](https://github.com/hashicorp/nomad/tree/master/website#enterprise-alert) .

Added Enterprise Badges in Docs

---

CHANGELOG.md
client/allocrunner/taskrunner/task_runner_hooks.go
e2e/consul/consul.go
e2e/consul/input/consul_example.nomad
e2e/consul/input/services_empty.nomad
e2e/consul/input/services_present.nomad
e2e/consul/script_checks.go
e2e/e2eutil/consul.go
helper/uuid/uuid.go

Previously, Nomad would optimize out the services task runner
hook for tasks which were initially submitted with no services
defined. This causes a problem when the job is later updated to
include service(s) on that task, which will result in nothing
happening because the hook is not present to handle the service
registration in the .Update.
Instead, always enable the services hook. The group services
alloc runner hook is already always enabled.
Fixes #9707

consul: always include task services hook

---

e2e/terraform/.terraform.lock.hcl

Terraform v0.14 is producing a lockfile after running `terraform init`.
The docs suggest we should include this file in the git repository:
> You should include this file in your version control repository so
> that you can discuss potential changes to your external dependencies
> via code review, just as you would discuss potential changes to your
> configuration itself.
Sounds similar to go.sum
https://www.terraform.io/docs/configuration/dependency-lock.html#lock-file-location

e2e: add terraform lockfile

---

CHANGELOG.md
command/agent/consul/connect.go
command/agent/consul/connect_test.go
nomad/structs/services.go

Submitting a job with an ingress gateway in host networking mode
with an absent gateway.proxy block would cause the Nomad client
to panic on NPE.
The consul registration bits would assume the proxy stanza was
not nil, but it could be if the user does not supply any manually
configured envoy proxy settings.
Check the proxy field is not nil before using it.
Fixes #9669

consul/connect: avoid NPE from unset connect gateway proxy

---

command/alloc_exec.go
command/alloc_exec_test.go
command/alloc_fs.go
command/alloc_logs.go

While looking into `alloc exec`, I found there were some improvements that could be made to the code for readability, as well as correctness, so as a low-priority thing I did a rewrite.
This re-arranges the alloc exec Run implementation to have validation hoisted as high as possible, ~which allows for returning a better error message when `-job` is given with a too-short job ID, as well as a more correct error message in that case.~ <- this was removed as the full job name is required.

Refactor alloc exec command

---

website/pages/docs/upgrade/upgrade-specific.mdx

We accidently deployed 1.0.2 upgrade notes before 1.0.2 is released. Obviously we don't want to confuse people about what the latest version of Nomad is, but I feel like pre-publishing upgrade notes might be useful for users to be aware of chanes ahead of time (similar to the `Unreleased` section of the changelog). So instead of removing the unreleased 1.0.2 notes, I marked them the same as the changelog.
Not a big deal, so if there are any concerns I'm more than happy to just remove the unreleased version's notes from the website until release day.

docs: note that 1.0.2 is unreleased

---

website/pages/api-docs/jobs.mdx

Closes #9398 
This is modeled after the existing [Field Reference](https://www.nomadproject.io/api-docs/allocations#field-reference) seen on the allocations doc page.
This isn't a complete field reference, but statuses and types are the hardest to infer from a response.

docs: Enumerate job statuses and types in docs

---

website/pages/api-docs/jobs.mdx
website/pages/docs/configuration/client.mdx
website/pages/docs/operations/nomad-agent.mdx

Each commit has a small docs change:
- remove duplicate PreserveCounts entry
- remove old client.options migration note
- There's no reason to give the `client.options` to `plugins` migration top billing on the client configuration page. Remove and and clarify the more appropriately placed note down below.
- mention client can be non-root; I want to strike a balance here:
- On the one hand there are use cases (raw_exec or Docker only) where running Nomad clients as an unprivileged user is *preferable.*
- On the other hand running Nomad clients as root is our main and best tested environment. So I want to leave that a strong recommendation.

Docs cleanup

---

command/agent/consul/service_client.go

While reading this code during debugging I felt there was room for improvement.
This removes modification of `ops` in methods that `UpdateWorkload` calls, keeping them local to `UpdateWorkload`. It also includes some rewrites of `checkRegs` for clarity.
I find things like this in particular make reasoning about the code easier:
```diff
- checkIDs, err := c.checkRegs(ops, id, service, workload)
+ checkRegs, err := c.checkRegs(id, service, workload)
```
`c.checkRegs` just returns `checkRegs` rather than `checkIDs`.

consul: Refactor parts of UpdateWorkload

---

client/allocrunner/taskrunner/stats_hook.go
client/allocrunner/taskrunner/stats_hook_test.go

This PR deflakes TestTaskRunner_StatsHook_Periodic tests and adds backoff when the driver closes the channel.
TestTaskRunner_StatsHook_Periodic is currently the most flaky test - failing ~4% of the time (20 out of 486 workflows). A sample failure: https://app.circleci.com/pipelines/github/hashicorp/nomad/14028/workflows/957b674f-cbcc-4228-96d9-1094fdee5b9c/jobs/128563 .
This change has two components:
First, it updates the StatsHook so that it backs off when stats channel is closed. In the context of the test where the mock driver emits a single stats update and closes the channel, the test may make tens of thousands update during the period.  In real context, if a driver doesn't implement the stats handler properly or when a task finishes, we may generate way too many Stats queries in a …

tests: deflake TestTaskRunner_StatsHook_Periodic

---

api/internal/testutil/freeport/freeport.go

Deflake test-api job, currently failing at around 7.6% (44 out of 578
workflows), by ensuring that test nomad agent use a small dedicated port
range that doesn't conflict with the kernel ephemeral range.
The failures are disproportionately related to port allocation, where a
nomad agent fails to start when the http port is already bound to
another process. The failures are intermittent and aren't specific to any
test in particular. The following is a representative failure:
https://app.circleci.com/pipelines/github/hashicorp/nomad/13995/workflows/6cf6eb38-f93c-46f8-8aa0-f61e62fe7694/jobs/128169
.
Upon investigation, the issue seems to be that the api freeport library
picks a port block within 10,000-14,500, but that overlaps with the
kernel ephemeral range 32,769-60,999! So, freeport may …

tests: deflake test-api job

---

website/content/docs/job-specification/group.mdx

Add a link back to configuration/consul in the `service` parameter section of the `group` stanza.

Fix missing link for Consul integration on group stanza docs

---

CHANGELOG.md
command/agent/consul/service_client.go
command/agent/consul/service_client_test.go
command/agent/consul/unit_test.go
website/content/docs/job-specification/service.mdx

This PR changes the behavior of a how the service address is built for services configured with the new `alloc` addr_mode. Previously the alloc's IP and the host port value were used. With this change, the mapped `to` value of the port is used, falling back to the host's value if `to` is not set. 
fixes #9730

Use port's to value when building service address under 'alloc' addr_mode

---

e2e/namespaces/input/namespace_a.nomad
e2e/namespaces/input/namespace_b.nomad
e2e/namespaces/input/namespace_default.nomad
e2e/namespaces/namespaces.go
e2e/namespaces/namespaces_oss.go

As noted within #9135 these should be moved into OSS.
The move includes lint fixes that were all `ineffassign` to `err` when running commands.
Local testing:
```
--- PASS: TestE2E/Namespaces (10.24s)
--- PASS: TestE2E/Namespaces/*namespaces.NamespacesE2ETest (10.16s)
--- PASS: TestE2E/Namespaces/*namespaces.NamespacesE2ETest/TestNamespacesFiltering (10.03s)
```

e2e: move namespace tests into OSS.

---

ui/app/components/topo-viz.js
ui/app/controllers/topology.js
ui/app/templates/topology.hbs
ui/tests/acceptance/topology-test.js
ui/tests/integration/components/topo-viz-test.js
ui/tests/pages/topology.js

Fixes #9702 
If a cluster has nodes running a version of Nomad <0.9.0, they won't have the requisite `NodeResources` property. Instead of blowing up, now the UI will filter those nodes out of the viz and report the situation to the user.

UI: Guard against nodes running an old version of the Nomad agent

---

website/pages/use-cases/simple-container-orchestration.jsx

🎟️ [Asana Task](https://app.asana.com/0/1188331750716498/1199373521776172/f)
🔍 [Preview Link](https://nomad-git-docs-zsbuild-time-code-highlight-revised.hashicorp.vercel.app/)
This PR pulls adds back code highlighting to the `/use-cases/simple-container-orchestration` page.
- [`/use-cases/simple-container-orchestration`](https://nomad-git-docs-zsbuild-time-code-highlight-revised.hashicorp.vercel.app/use-cases/simple-container-orchestration)
- Recent updates to `text-split-with-code` mean that client-side code highlighting is no longer supported. Code snippets are now highlighted in `getStaticProps`, using utilities from `@hashicorp/nextjs-scripts`.

Add build-time highlighting to code blocks

---

website/content/api-docs/ui.mdx

These were very out of date, lol.

WTDD: Update UI api docs

---

CHANGELOG.md
client/client.go

When in-place upgrading from Nomad v0.12.x to v1.0.x, Nomad client will panic on
startup if the node is running Connect enabled jobs. This is caused by
a missing piece of plumbing of the Consul Proxies API interface during the
client restore process.
Fixes #9738

consul/connect: fix panic during in-place upgrade with connect jobs

---

client/fingerprint/cpu.go
client/fingerprint/cpu_test.go
client/fingerprint/env_aws.go
client/fingerprint/env_aws_test.go

The [documentation](https://www.nomadproject.io/docs/runtime/interpolation#interpreted_node_vars) states that `${attr.cpu.totalcompute}` may be overridden by `client.cpu_total_compute`.  The actual behaviour was that `attr.cpu.totalcompute` was unset when `cpu_total_compute` was used.
I think either the feature should operate how the documentation says, or the documentation should be updated.  I opted for changing the feature, as I think it would be useful.

Allow client.cpu_total_compute to override attr.cpu.totalcompute

---

website/content/docs/drivers/docker.mdx

Following a conversation with @louievandyke I realized the documentation for `userns_mode` is somewhat unclear. The Docker [documentation](https://docs.docker.com/engine/security/userns-remap/#disable-namespace-remapping-for-a-container) refers to "disabling user namespaces". Although this isn't strictly accurate as the host namespace still exists, adding it to the our docs can help make the translation between our driver and Docker's behavior more clear.

docs: clarify default behavior of docker userns_mode

---

CHANGELOG.md
scheduler/util.go
scheduler/util_test.go

Ensure that allocation AllocatedResources Shared Ports are not dropped during inplace updates.
When performing in place updates, the scheduler creates a shallow copy of the allocation and updates a few fields. It's not immediately clear to me why we do a shallow copy instead of something like `allocation.Copy()`. The AllocatedSharedResources Ports were not copied over causing issues after the plan was applied.
As a side effect, removing or updating a task group service stanza, resulting in an inplace update would error and prevent a service from being registered or deregistered during an inplace update.  This issue was reported in  https://github.com/hashicorp/nomad/issues/9360 
This error was displayed in the logs like so:
```
2021-01-06T12:49:47.127-0500 [ERROR] client.alloc_runner: …
```

Persisted shared ports during inplace update

---

CHANGELOG.md
api/util_test.go
nomad/job_endpoint.go
nomad/job_endpoint_test.go

the `Job.Scale` endpoint did not enforce min/max from the group scaling policy. this PR addresses that with a simple check. unit tested the RPC; I had to make a small tweak to one of the `api` scaling tests because it was previously (incorrectly) scaling outside of bounds.
resolves #9758

in Job.Scale, ensure that new count is within [min,max] configured in  scaling policy

---

e2e/terraform/.terraform.lock.hcl
e2e/terraform/nomad.tf
e2e/terraform/provision-nomad/main.tf
e2e/terraform/terraform.tfvars

Also bumps patch versions of some TF modules
Ran into this while testing TF0.15, where these warnings will become errors.

e2e: remove deprecated terraform syntax

---

e2e/terraform/packer/ubuntu-bionic-amd64/setup.sh
website/content/docs/drivers/external/containerd.mdx
website/content/docs/integrations/consul-connect.mdx

https://github.com/containernetworking/plugins/releases/tag/v0.9.0
Also make the copy-paste install instructions work with arm64 for a better OOTB experience (AWS Graviton, Pi 4's). (Is there a better way to do this? I like the architecture tabs Docker uses at the bottom of https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository but that seems hard).

cni: bump CNI plugins version to v0.9.0

---

CHANGELOG.md
client/allocrunner/network_manager_linux.go

Fixes https://github.com/hashicorp/nomad/issues/9750. A similar problem was fixed for the Docker driver in 0.10.0 with  https://github.com/hashicorp/nomad/pull/6315 but it looks like we missed the `exec` driver and other non-Docker drivers that support network isolation.
---
When a client restarts, the network_hook's prerun will call
`CreateNetwork`. Drivers that don't implement their own network manager will
fall back to the default network manager, which doesn't handle the case where
the network namespace is being recreated safely. This results in an error and
the task being restarted for `exec` tasks with `network` blocks (this also
impacts the community `containerd` and probably other community task drivers).
If we get an error when attempting to create the namespace and that error is …

safely handle existing net namespace in default network manager

---

client/allochealth/tracker.go
client/allochealth/tracker_test.go
client/allocrunner/task_hook_coordinator_test.go
nomad/mock/mock.go

Ignores poststop jobs pending state when calculating the lastest start time for an allocation
resolves #9361

investigating where to ignore poststop task in alloc health tracker

---

CHANGELOG.md
client/fingerprint/bridge_linux.go
client/fingerprint/bridge_linux_test.go

The modules.dep file on RHEL includes .xz for compressed kernel modules.

Properly detect unloaded dynamic modules on RHEL derivates. Fixes #9776

---

GNUmakefile

This is required because Go does not pull CC from the make variable. This uses whatever Go's default CC unless CC is overridden, as it is for the ARM targets.
This also makes it easier to build Nomad on a native ARM device, via:
```
make CC= pkg/linux_arm/nomad
```

makefile: Set CC explicitly in go build

---

website/content/docs/commands/agent.mdx
website/content/docs/configuration/client.mdx
website/content/docs/configuration/index.mdx

Follow-up to https://github.com/hashicorp/nomad/pull/9685, as noted by @nh2 in https://github.com/hashicorp/nomad/issues/9385#issuecomment-759154171

docs: remove remaining references to network_speed config

---

website/content/docs/drivers/podman.mdx

As of podman 0.2.0 (and https://github.com/hashicorp/nomad-driver-podman/commit/b580f2d1874273bd61640525d54a02e3747c2df4), podman correctly advertises its filesystem isolation as `FSIsolationImage`.
(Noticed this was stale in https://github.com/hashicorp/nomad/issues/9790#issuecomment-759458730)

docs: podman FSIsolation is image

---

CHANGELOG.md
command/agent_info.go
command/agent_info_test.go
website/content/docs/commands/agent-info.mdx

Added -json and -t formatting options to `nomad agent-info` CLI command, which provides access to the complete set of data available from the /v1/agent/self API.

nomad agent-info: Add json/gotemplate formatting

---

.circleci/config.yml
scripts/vagrant-linux-unpriv-ui.sh

Have the build-binary bundle the UI by default.  This eases getting "alpha pre-releases" out for support without compiling locally, and engineer's experience with e2e test clusters.

build binaries with UI enabled

---

website/content/docs/job-specification/hcl2/index.mdx

docs: fix HCL2 doc page code block

---

client/allochealth/tracker.go

In 492d62d we prevented poststop tasks from contributing to allocation health
status, which fixed a bug where poststop tasks would prevent a deployment from
ever being marked successful. The patch introduced a regression where prestart
tasks that complete are causing the allocation to be marked unhealthy. This
changeset restores the previous behavior for prestart tasks.
Note to reviewers: you can [compare to the original line](https://github.com/hashicorp/nomad/pull/9548/files#diff-22c7aef46df110dd1b35c5ef1f7a090779ac2c9c1b8a0cd8d8137ff6deb6fe3bL281).

lifecycle: successful prestart tasks should not fail deployments

---

e2e/e2eutil/utils.go

We directly parse job files in e2eutil, but currently using jobspec
package. Instead, use the Parse method from the jobspec2 package so
we can parse job files with new features.

e2e: use jobspec2 Parse for parsing jobfile in e2e utils

---

.circleci/config.yml

Only lookup GO_TAGS variable, and avoid the false positives where GO_TAGS is a variable suffix.
Needed to fix the Enterprise (private fork) build binary jobs.

ci: only read/modify `GO_TAGS` field

---

nomad/fsm.go

As it says on the tin. This looks like it was missed when the namespace persistence was added.

Add missing sink.Cancel() in fsm

---

nomad/job_endpoint.go
nomad/structs/structs.go

I was perusing the git log history and found a recently-modified func could be cleaned up a bit.
The main things here are creating a JobScaleRequest.Validate() to handle some simple validation stuff, and special-casing the nil JobScaleRequest.Count scenario to remove a bunch of `if args.Count != nil` below, which also removes some nested conditionals.

Refactor Job.Scale()

---

helper/gated-writer/writer.go
helper/gated-writer/writer_test.go

If one thread calls `Flush()` on a gatedwriter while another thread attempts to `Write()` new data to it, strange things will happen.
The test I wrote shows that at the very least you can write _while_ flushing, and the call to `Write()` will happen during the internal writes of the buffered data, which is maybe not what is expected. (i.e. the `Write()`'d data will be inserted somewhere in the middle of the data being `Flush()'d`)
It's also the case that, because `Write()` only has a read lock, if you had multiple threads trying to write ("read") at the same time you might have data loss because the `w.buf` that was read would not necessarily be up-to-date by the time `p2` was appended to it and it was re-assigned to `w.buf`. You can see this if you run the gatedwriter tests with `-race`: …

gatedwriter: Fix race condition

---

nomad/structs/csi.go
nomad/structs/csi_test.go

The error that this would have returned would only have been returned if
the lookup in a map did not fail and the value that the map returned was
nil, ~which I think is not possible~ the map keys are pointers, so they can be!
In this change we'll properly return the error in the
CSIPluginTypeMonolith case (which is the type given in DeleteNode()),
and also actually return the error when the given ID is not found.
This was found via errcheck.
Note: ~Since I don't think it was possible for this to have ever actually returned an error before,~ I wonder if the behavior when trying to delete a node where one of the controller or node is not found should actually return an error, and if so, if it should only do so for one and not the other. In other words, if you want to delete a node and …

csi: Return error when deleting node

---

client/allocrunner/taskrunner/template/template.go
client/client.go
client/devicemanager/manager.go
command/job_validate.go
command/server_members.go
helper/pluginutils/loader/init.go
nomad/eval_endpoint.go
nomad/job_endpoint_hooks.go
nomad/mock/mock.go
nomad/namespace_endpoint.go
nomad/server.go
nomad/structs/funcs.go
nomad/structs/funcs_test.go
nomad/structs/streaming_rpc.go
nomad/structs/structs.go
nomad/structs/structs_test.go
nomad/structs/testing.go
nomad/vault.go
plugins/device/device.go

I encourage reviewers to review this on a per-commit basis for clarity.
This is mostly scoped to the structs package, except for the changes to `multierror.Append`, which were done repo-wide.
The behavior here is all unchanged except for the changes in `nomad/struts/testing.go`, which I think we would want, but maybe not.
This does not include fixing errcheck errors in `nomad/structs/csi.go`, which do result in changed behavior in production code, and which are covered in https://github.com/hashicorp/nomad/pull/9803.

Fix some errcheck errors

---

CHANGELOG.md

Seems like this was missing from the docs. Was trying to make this work on 1.0.1 (it was on the docs), however, it's only working on 1.0.2.

Missed improvement regarding IGW task customization

---

CHANGELOG.md
scheduler/generic_sched_test.go
scheduler/util.go
scheduler/util_test.go

Ports were not copied over when performing inplace updates in the
generic scheduler
Fixes #9808

Persist shared allocated ports for inplace update

---

drivers/shared/executor/executor_linux.go
drivers/shared/executor/executor_linux_test.go

This was found via an updated golangci-lint, which noted that the HasPrefix invocation was backwards.
This is split into two commits on purpose:
The first commit removes the untested code that tries to find a given command.Cmd in a path defined in the command.Env as `PATH=`. I think the thinking here is that you could make a relative reference to a binary that lives in a directory that's in a user-defined `PATH` env var. However, the code that looks for a `PATH=` entry in command.Env is backwards; the prefix needs to be the second arg, not the first. That means this code never would have worked the way it was intended.
The second commit fixes this functionality, adding tests to back it up.
I'm fine with either commit being approved.

executor_linux: Remove unreachable PATH= code

---

CHANGELOG.md
api/services.go
nomad/job_endpoint_hook_connect.go
nomad/job_endpoint_hook_connect_test.go
vendor/github.com/hashicorp/nomad/api/services.go

If the connect.proxy stanza is left unset, the connection timeout
value is not set but is assumed to be, and may cause a non-fatal NPE
on job submission.

consul/connect: always set gateway proxy default timeout

---

command/agent/command.go

This fixes the extra spaces at the beginning of json logging (#9489).
However I'm not a 100% happy with the current solution. Ideally we would switch the UI to `logging.HcLogUI` after reading the config. But to initialize one we need a logger, which needs a UI. Classic Catch-22.

don't prefix json logging (fixes #9489)

---

CHANGELOG.md
client/allocrunner/taskrunner/envoy_bootstrap_hook.go
client/allocrunner/taskrunner/envoy_bootstrap_hook_test.go
e2e/connect/acls.go
e2e/connect/connect.go
e2e/connect/input/multi-ingress.nomad

Connect ingress gateway services were being registered into Consul without
an explicit deterministic service ID. Consul would generate one automatically,
but then Nomad would have no way to register a second gateway on the same agent
as it would not supply 'proxy-id' during envoy bootstrap.
Set the ServiceID for gateways, and supply 'proxy-id' when doing envoy bootstrap.
Fixes #9834

consul/connect: Enable running multiple ingress gateways per Nomad agent

---

command/agent/job_endpoint.go
nomad/structs/structs.go
nomad/structs/structs_test.go

This adds the missing validation mentioned in #9450 for a connect block to be allowed only in a group service.

validate connect block allowed only within group.service (fixes #9450)

---

drivers/docker/driver_linux_test.go
drivers/docker/utils.go

Fixes: #8316
Some credential helpers, like the ECR helper, will strip the protocol if
given. Others, like the linux "pass" helper, do not.

Don't prepend https to docker cred helper stdin

---

nomad/structs/structs_test.go

Fixes: #6844
This adds two helpers to structs_test:
* `requireMultierrorContaining`
* `requireMultierrorNotContaining`
These helpers remove the tight coupling of the expected error count and ordering in the tests.

Clean up Task Validation tests

---

command/agent/job_endpoint.go
e2e/e2e_test.go
e2e/e2eutil/job.go
e2e/periodic/input/simple.nomad
e2e/periodic/periodic.go
e2e/terraform/Makefile
nomad/fsm_test.go
nomad/job_endpoint_hook_connect.go
nomad/job_endpoint_hook_connect_test.go
nomad/mock/mock.go
nomad/state/state_store.go
nomad/state/state_store_test.go
nomad/structs/services.go
nomad/structs/services_test.go

#8435 introduced atomic eval insertion when registering/de-registering jobs.
This change removes a now obsolete guard which checked if the index was 
equal to the job.CreateIndex, which would empty the status. 
Now that the job regisration eval insertion is atomic with the registration 
this check is no longer necessary to set the job statuses correctly
fixes https://github.com/hashicorp/nomad/issues/8692

prevent double job status update

---

CHANGELOG.md
client/allocrunner/alloc_runner.go
client/allocrunner/alloc_runner_hooks.go
client/allocrunner/groupservice_hook.go
client/allocrunner/groupservice_hook_test.go
client/allocrunner/interfaces/runner_lifecycle.go
e2e/consul/check_restart.go
e2e/consul/consul.go
e2e/consul/input/checks_group_restart.nomad
e2e/consul/input/checks_task_restart.nomad
website/content/docs/job-specification/check_restart.mdx

Fixes https://github.com/hashicorp/nomad/issues/9176
Most allocation hooks don't need to know when a single task within the
allocation is restarted. The check watcher for group services triggers the
alloc runner to restart all tasks, but the alloc runner's `Restart` method
doesn't trigger any of the alloc hooks, including the group service hook. The
result is that after the first time a check triggers a restart, we'll never
restart the tasks of an allocation again.
This commit adds a `RunnerTaskRestartHook` interface so that alloc runner
hooks can act if a task within the alloc is restarted. The only implementation
is in the group service hook, which will force a re-registration of the
alloc's services and fix check restarts.

implement alloc runner task restart hook

---

CHANGELOG.md
drivers/docker/config.go
drivers/docker/driver.go

fix a minor inconsistency in how nomad handles image url for task and infra.
basically a duplication of https://github.com/hashicorp/nomad/blob/2176fbd90a228a6aafba4ff7a9042fc0fc7dcdf0/drivers/docker/driver.go#L253-L256

fix the inconsistency handling between infra image and normal task image

---

ui/app/styles/components/dropdown.scss
ui/app/templates/components/gutter-menu.hbs
ui/tests/acceptance/job-detail-test.js
ui/tests/acceptance/namespaces-test.js

Fixes #9814 
This makes the UI more consistent and also correctly displays the `default` namespace as "default" instead of "Default".

UI: Use the same prefix pattern for both the region switcher and the namespace switcher

---

website/content/docs/devices/external/index.mdx
website/content/docs/devices/external/usb.mdx
website/data/docs-navigation.js

Adds a community device plugin page for the [usb device plugin](https://gitlab.com/CarbonCollins/nomad-usb-device-plugin).
I believe I have updated the javascript file that was referenced in #9806 and have updated the device plugin community page to become a sub list of device plugins so others can be added in the future.

Adds community USB plugin to documentation site

---

nomad/state/state_store.go
nomad/state/state_store_test.go

Ignoring setting job summary when job status has not changed.
`firstPass` was an invalid approach to prevent double job summary updates since `applyUpsertJob` calls `setJobStatus` twice, once during `UpsertJob` and once during `UpertEval` (atomic eval insertion).
When setting the job status, if oldstatus == newstatus, truly no-op instead of calculating the Jobsummary. 
Before #9768, `setJobStatus` set `oldStatus = ""` which allowed the job summary to increment and decrement properly
https://github.com/hashicorp/nomad/blob/release-1.0.1/nomad/state/state_store.go#L4482-L4484
The current situation seems to be mostly related to test setup, before we could rely on the implementation to empty out the job status when it was created, but in reality the job comes in through the FSM without a job …

ignore setting job summary when oldstatus == newstatus

---

CHANGELOG.md
api/services.go
api/services_test.go
client/allocrunner/taskrunner/envoy_bootstrap_hook.go
command/agent/consul/connect.go
command/agent/consul/connect_test.go
command/agent/consul/service_client.go
command/agent/job_endpoint.go
command/agent/job_endpoint_test.go
contributing/checklist-jobspec.md
e2e/connect/acls.go
e2e/connect/connect.go
e2e/connect/input/terminating-gateway.nomad
nomad/consul.go
nomad/consul_test.go
nomad/job_endpoint.go
nomad/job_endpoint_hook_connect.go
nomad/job_endpoint_hook_connect_test.go
nomad/node_endpoint_test.go
nomad/structs/connect.go
nomad/structs/diff.go
nomad/structs/diff_test.go
nomad/structs/services.go
nomad/structs/services_test.go
nomad/structs/structs.go
nomad/structs/structs_test.go
vendor/github.com/hashicorp/nomad/api/services.go
website/content/docs/job-specification/gateway.mdx

This PR implements Nomad built-in support for running Consul Connect
terminating gateways. Such a gateway can be used by services running
inside the service mesh to access "legacy" services outside the mesh
while still making use of Consul's service identity based networking and
ACL policies.
https://www.consul.io/docs/connect/gateways/terminating-gateway
These gateways are declared as part of a task group level service
definition within the connect stanza.
```hcl
service {
connect {
gateway {
proxy {
// envoy proxy configuration
}
terminating {
// terminating-gateway configuration entry
}
}
}
}
```
Currently Envoy is the only supported gateway implementation in
Consul. The gateway task can be customized by configuring the
`connect.sidecar_task` block or `meta.connect.gateway_image` …

consul/connect: Add support for Connect terminating gateways

---

e2e/terraform/.terraform.lock.hcl
e2e/terraform/README.md
e2e/terraform/compute.tf
e2e/terraform/packer/README.md
e2e/terraform/packer/build
e2e/terraform/packer/ubuntu-bionic-amd64.pkr.hcl
e2e/terraform/packer/ubuntu-bionic-amd64/setup.sh
e2e/terraform/packer/windows-2016-amd64.pkr.hcl
e2e/terraform/provision-nomad/main.tf

This PR makes two ergonomics changes, meant to get e2e builds more reproducible and ease changes.
First, we pin the server AMIs to the commits associated with the build.  No more using the latest AMI a developer build in a test branch, or accidentally using a stale AMI because we forgot to build one!  Packer is to tag the AMI images with the commit sha used to generate the image, and then Terraform would look up only the AMIs associated with that sha. To minimize churn, we use the SHA associated with the latest Packer configurations, rather than SHA of all.
This has few benefits: reproducibility and avoiding accidental AMI changes and contamination of changes across branches. Also, the change is a stepping stone to an e2e pipeline that builds new AMIs automatically if Packer files …

e2e infrastructure tweaks

---

website/content/docs/job-specification/hcl2/variables.mdx

Attempting to make it clearer variables go into the jobspec file while attempting to use similar terminology.
closes #9842

docs: clarify where variables can be placed with HCLv2.

---

.github/workflows/ember-test-audit.yml

This fixes the version reference error seen in [this](https://github.com/hashicorp/nomad/actions/runs/504695096) workflow failure.
I’ve also included an update to the sticky comment action version to address this warning in the above link:
```
marocchino/sticky-pull-request-comment@33a6cfb looks like the shortened version of a commit SHA. Referencing actions by the short SHA will be disabled soon. Please see https://docs.github.com/en/actions/learn-github-actions/security-hardening-for-github-actions#using-third-party-actions.
```
We were previously using `33a6cfb` after the maintainer merged [my PR](https://github.com/marocchino/sticky-pull-request-comment/pull/118) to allow the comment to be read from a file, there was no released version with that, but it’s now included in `v2.0.0`.

UI: Fix audit workflow action versions

---

e2e/connect/multi_service.go
e2e/consul/check_restart.go
e2e/consul/consul.go
e2e/consulacls/manage.go
e2e/consultemplate/consultemplate.go
e2e/e2e_test.go
e2e/e2eutil/allocs.go
e2e/e2eutil/consul.go
e2e/e2eutil/e2ejob.go
e2e/e2eutil/utils.go
e2e/framework/framework.go
e2e/lifecycle/lifecycle.go
e2e/metrics/metrics.go
e2e/nodedrain/input/drain_deadline.nomad
e2e/nodedrain/nodedrain.go
e2e/nomadexec/exec.go
e2e/taskevents/taskevents.go
e2e/terraform/packer/build
e2e/vaultcompat/vault_test.go
e2e/vaultsecrets/vaultsecrets.go
e2e/volumes/volumes.go

I've dug into e2e test flakiness a bit.  This PR includes assorted modifications to get better error reporting as well as attempts for fixing/patching some.  The PR is best reviewed commit by commit.
Most of the changes are relatively trivial.  The potentially controversial ones are the disabling of connect tests and node-drain.  I'll add some comments inline.

2021-01-26 Attempt at deflaking e2e tests

---

api/api.go
api/api_test.go
vendor/github.com/hashicorp/nomad/api/api.go

👋 I've got Nomad behind a proxy that requires setting headers to authentication.
This allows you to configure the client with headers that will be passed on every request.

Allow setting of headers in api client

---

ui/app/styles/charts/topo-viz-node.scss

Use dominant-baseline instead of alignment-baseline to get firefox support

---

e2e/consul/consul.go
e2e/nodedrain/nodedrain.go

Disabling node drain deadlines tests.  They assert that the allocations to be migrated get killed immediate (with `--force`) or after the specified drain deadline.  However, that doesn't seem the case in practice.  Issue #9902 is the placeholder issue to investigate behavior.

e2e: Disable node drain deadline tests

---

website/content/docs/operations/metrics.mdx

These metrics around raft leadership transitions got missed during the big metrics docs rework before the holidays.

docs: add metrics from raft leadership transitions

---

ui/app/components/topo-viz.js
ui/app/templates/components/topo-viz.hbs
ui/tests/integration/components/topo-viz-test.js

Closes #9769 
This fixes the bug reported in the above issue and hopefully also clears up some of the confusing behavior.
**Bug**
When allocation associations aren't supposed to be drawn, resizing the window will cause them to be drawn anyway.
**Confusion**
Sometimes allocation associations aren't supposed to be drawn but it's not clear when or why.
The motive behind this behavior is the lines can become more overwhelming than they are helpful for densely placed allocs on large clusters. The lines are supposed to help get a sense of spread, but when it's just spaghetti, it's not solving that anymore.
I think this motive is still valid, but the logic behind it is admittedly naive. Before this pr, the logic was `allocCount < nodeCount * 0.75` And as you can see in the issue, this means …

UI: Show allocation associations in the topo viz more often (and fix a bug)

---

ui/app/components/topo-viz/node.js
ui/app/controllers/topology.js
ui/app/templates/topology.hbs
ui/tests/acceptance/topology-test.js
ui/tests/integration/components/topo-viz/node-test.js
ui/tests/pages/topology.js

Fixes #9800 
The cluster info panel was over-reporting reserved amounts due to counting the reserved capacity for terminal allocations. This fixes that bug.
Additionally, the topo viz node component did the same over-reporting by counting all allocs instead of only the pending and running ones.
This also adds acceptance tests to all the info panel states, and by writing those tests I discovered another bug: the unique allocation placements figure was always equal to the number of sibling allocations instead of the count of unique clients. I fixed that.

UI: Topology info panel incorrect accounting bugs

---

ui/app/components/job-page/parts/latest-deployment.js
ui/app/components/job-page/parts/title.js
ui/app/components/job-page/periodic.js
ui/app/controllers/allocations/allocation/index.js
ui/app/controllers/allocations/allocation/task/index.js
ui/app/utils/message-from-adapter-error.js
ui/tests/acceptance/task-detail-test.js
ui/tests/unit/utils/message-from-adapter-error-test.js

Fixes #7875 
In most places in the UI, the error message shown after failed actions is a mostly generic "Your ACL token said no" message. Sometimes this occludes genuine and helpful 500 error messages being returned from the API.
This makes it so anywhere we show an error message we make sure to only show an ACL error message if it is a 403 error, otherwise just print what the API gave us.

UI: Use server-sent error messages when applicable

---

go.mod
go.sum
jobspec2/parse_test.go
vendor/github.com/hashicorp/hcl/v2/ext/dynblock/expand_body.go
vendor/modules.txt

Fixes https://github.com/hashicorp/nomad/issues/9871
This changeset includes both a test and a dependency update for a patch that fixes map interpolation inside `dynamic` blocks. This dependency update is from the off-release HCL2 version as described https://github.com/hashicorp/nomad/issues/9918

interpolate maps in dynamic blocks

---

GNUmakefile
scripts/vagrant-linux-priv-buf.sh

Also, update the compatibility check to 1.0.3, the latest release so far.
Closes https://github.com/hashicorp/nomad/issues/9925

lint: Upgrade buf to 0.36.0, latest so far

---

ui/app/models/node.js
ui/tests/acceptance/client-detail-test.js
ui/tests/acceptance/clients-list-test.js

As pointed out by @nickethier, if a node was ineligible before
it went down, downness should be displayed, not ineligibility.

UI: Change down to highest-priority composite status

---

command/helpers_test.go
jobspec2/hcl_conversions.go
jobspec2/parse_test.go
jobspec2/types.config.go

Allow expressing `meta` and `env` blocks as map attributes as well.
`env` and `meta` should support arbitrary key and values, yet hcl2
restricts the keys to valid identifiers. For example, block attribute
identifiers may not contain dots, `.`, which frequently used in meta
fields, and sometimes in environment variable fields.
By adding attribute syntax support, we maintain backward compatibility and relax the block attribute key restrictions. This change attempts to parse `env`/`meta` both as an attribute and as a
block.
Additionally, the change allows better expressivity for env/meta blocks, using
functions and for expressions. For example, one can reuse a set of environment variables for
multiple tasks, using a local `common_envs` value:
```hcl
env = merge(local.common_envs, …
```

hcl2: special case meta and env blocks

---

CHANGELOG.md

I merged https://github.com/hashicorp/nomad/pull/9940 without having figured out what to do about the issue link, but had forgotten that we had https://github.com/hashicorp/nomad/issues/9920 open, so I've linked that here.

changelog: link for quota docs change

---

scheduler/util.go
scheduler/util_test.go

This PR changes the scheduler to detect if a `to` or `host_network` field is updated.
fixes #9728

scheduler: add tests and fix for detected host_network and to port field changes

---

e2e/terraform/packer/ubuntu-bionic-amd64/setup.sh

also, change JDK install to headless.
resolves https://github.com/hashicorp/nomad-e2e/issues/36 
resolves https://github.com/hashicorp/nomad/issues/9939

e2e packer build: upgrade jdk to java 14

---

ui/app/components/agent-monitor.js
ui/app/services/token.js
ui/tests/integration/components/agent-monitor-test.js
ui/tests/unit/services/token-test.js

Fixes #8885
This was just some oversight. Switching regions and monitoring a server worked, but since the serves page lists all servers across all regions, we need to special case this one.

UI: Cross region server monitor

---

ui/config/targets.js
ui/ember-cli-build.js

This changes the Babel compilation targets to exclude IE, which results in significant payload size savings.
Thanks to @pichfl for [this](https://github.com/ember-cli/ember-cli/issues/9290#issuecomment-672734338) solution to an Uglify problem.

UI: Remove support for IE11

---

CHANGELOG.md
drivers/docker/driver_default.go
drivers/docker/driver_windows.go
drivers/docker/ports.go
drivers/docker/ports_test.go

The docker driver native port mapping logic would overwrite ports with the same container port. This wouldn't allow multiple ports to be mapped to the came container port.
This PR fixes this issue by correctly appending to the published port map instead of overwriting.
fixes #8284

drivers/docker: support mapping multiple host ports to the same container port

---

website/content/docs/autoscaling/plugins/target.mdx

- aws secret key is named incorrectly in the target docs.
It needs to match what is in the nomad-autoscaler repo
(see link below), otherwise the autoscaler will default to AWS sdk
behavior, which could end up using an IAM instance profile
or other environment variables instead of what is passed into the
autoscaler config file.
Ref: https://github.com/hashicorp/nomad-autoscaler/blob/e60fb5268d2107ab18e2be11e5d438fedc3eb2a8/plugins/builtin/target/aws-asg/plugin/plugin.go#L27

Fix aws secret key name in autoscaler aws target docs

---

CHANGELOG.md
api/contexts/contexts.go
command/alloc_status.go
command/eval_status.go
command/job_inspect.go
command/scaling_policy_info.go
command/scaling_policy_info_test.go
command/scaling_policy_list.go
nomad/search_endpoint.go
nomad/search_endpoint_oss.go
nomad/search_endpoint_test.go
nomad/structs/structs.go
vendor/github.com/hashicorp/nomad/api/contexts/contexts.go

also, i think there was some bad boolean logic in a few other info-like commands
resolves #9787

add prefix-search and auto-completion for `scaling policy info` command

---

ui/app/utils/generate-exec-url.js
ui/tests/unit/utils/generate-exec-url-test.js

This closes #9966. It was looking at the query parameters
for the namespace and region, but allocation (and task!)
routes don’t have a namespace query parameter. Since the URL
generator requires the job for all calls, it makes sense to
extract the namespace and region from the job instead.

Change exec URLs to use job’s namespace/region

---

CHANGELOG.md
nomad/structs/diff.go
nomad/structs/diff_test.go

Fixes https://github.com/hashicorp/nomad/issues/9962
The details of host volume and CSI volume requests do not show up in `nomad
plan` outputs, although the updates are detected by the scheduler and result
in an update as expected.

volumes: implement plan diff for volume requests

---

api/operator.go
command/agent/http.go
command/agent/http_oss.go
command/agent/operator_endpoint.go
command/agent/operator_endpoint_oss.go
vendor/github.com/hashicorp/nomad/api/operator.go

This changes the OSS response for `GET /v1/operator/license` from 501 to 204 to close #9827. It preserves the `1` status code when running `nomad operator license`. Here’s me interacting with it locally:
This means people won’t see what appears to be an error in their logs for a known situation, as the UI checks this endpoint to decide whether to show enterprise features.

Add handling for license requests in OSS

---

website/content/docs/enterprise.mdx

Coming out of https://github.com/hashicorp/nomad/issues/9774 and the discussion that inspired https://github.com/hashicorp/nomad/issues/9958. I considered adding the phrase "while online" but I'm not sure that we should be encouraging folks to even attempt to go down this path?
8c69af5 has the actual docs change here, the rest is bringing this page in-line with the formatting standard.

document that Nomad ENT cannot be downgraded to Nomad OSS

---

client/allocrunner/network_manager_linux.go
client/allocrunner/networking.go

This PR adds a global mutex for network hook operations which invoke iptables. This is to isolate these and avoid race conditions related toconcurrent iptables read then write operations.
fixes #8838

ar: isolate network actions performed by client

---

ui/app/utils/escape-task-name.js
ui/tests/unit/utils/escape-task-name-test.js

This closes #7459.
While emoji don’t actually need escaping, expanding the
expression that enumerates all task name characters that
don’t need escaping to include emoji is prohibitive, since
it’s a discontinuous range. The emoji-regex project has
such an expression and it’s 12kB.
This fixes the regular expression to property escape emoji
as a single character instead of as its component bytes.
Thanks to @DingoEatingFuzz for the suggestion.

UI: Add workaround to exclude emoji from task escaping

---

CHANGELOG.md
drivers/exec/driver.go
drivers/exec/driver_test.go
drivers/java/driver.go
drivers/shared/executor/client.go
drivers/shared/executor/executor.go
drivers/shared/executor/executor_linux.go
drivers/shared/executor/executor_linux_test.go
drivers/shared/executor/server.go
drivers/shared/executor/utils.go
drivers/shared/executor/utils_test.go
e2e/isolation/input/exec_host.nomad
e2e/isolation/input/java_host.nomad
e2e/isolation/isolation.go
website/content/docs/drivers/exec.mdx
website/content/docs/drivers/java.mdx

This PR adds pid_mode and ipc_mode options to the exec and java task
driver config options. By default these will defer to the default_pid_mode
and default_ipc_mode agent plugin options created in #9969. Setting
these values to "host" mode disables isolation for the task. Doing so
is not recommended, but may be necessary to support legacy job configurations.
Closes #9970

drivers/exec+java: Add task configuration to restore previous PID/IPC isolation behavior

---

website/content/docs/job-specification/template.mdx

Since [mounts](https://www.nomadproject.io/docs/drivers/docker#mounts) is deprecated,
switch to newer `mount` in `task.config` for `docker` driver.

fix: docs/job-specification change mounts to mount

---

ui/app/components/job-page/parts/latest-deployment.js

This is a supplement to #9831 to incorporate the extracted
missing-permissions error handling from #9909.
It fixes [this failure](https://app.circleci.com/pipelines/github/hashicorp/nomad/14728/workflows/4c147dca-fd1e-4de7-86aa-90ded7aabad2/jobs/137137) on the main branch! 😳

UI: Fix deployment failure error handling

---

website/content/docs/commands/operator/keygen.mdx

The encryption key uses 32 bytes now, not 16 bytes

The encryption key uses 32 bytes now

---

CHANGELOG.md
nomad/structs/structs.go
nomad/structs/structs_test.go

Previously static port validation did not take host_networks into account. This meant Nomad thought two static ports with the same value but separate host_networks conflicted. The scheduler already tracks port allocations by the assigned HostIP so the issue is solely wrongful validation.
fixes #9477 
fixes #8891

structs: namespace port validation by host_network

---

website/content/docs/job-specification/gateway.mdx

Using the environment variable stopped working here a while back,
should be using the port label. Also upgrade to uuid-api:v5 which
supports linux/arm64.

docs: update ingress gateway runnable demo

---

website/content/docs/install/index.mdx

Updated the Homebrew installation instructions to refer to the HashiCorp maintained tap.

Updated Homebrew install instructions

---

ui/tests/acceptance/optimize-test.js

This fixes a flaky test, as seen in [this failure](https://app.circleci.com/pipelines/github/hashicorp/nomad/14726/workflows/f4ae0bf2-0699-4d18-b55e-5221aafe393c/jobs/137128) mentioned [here](https://github.com/hashicorp/nomad/pull/9831#issuecomment-776746688).
One part of the test involves toggling off all memory recommendations
and then accepting, but it’s not possible to accept when there are
no CPU recommendations to begin with, which can happen because
there’s a [10% chance](https://github.com/hashicorp/nomad/blob/edd296ff519e829b6534b8a52578274ca42e740b/ui/mirage/factories/task.js#L55-L57) of not creating a corresponding recommendation
in the task factory. Since two tasks are created for this module, it’s
only a 1% chance of no CPU task, but that means 1% flakiness!
I confirmed this …

UI: Fix recommendation test to ensure CPU exists

---

client/allocrunner/networking_bridge_linux.go
client/allocrunner/taskrunner/envoy_bootstrap_hook.go
command/agent/consul/connect.go
command/agent/consul/connect_test.go
command/agent/consul/service_client.go
nomad/job_endpoint_hook_connect.go
nomad/job_endpoint_hook_expose_check.go
nomad/structs/structs.go

- fixed sidecar address and TCP healthcheck when host_network is defined
Fixes #9683

Updated Default Consul Sidecar Healthcheck

---

website/content/docs/job-specification/artifact.mdx

Fixes https://github.com/hashicorp/nomad/issues/9905 (recently raised in https://github.com/hashicorp/nomad/issues/8969#issuecomment-778825690 so I wanted to fix that up).
I took a pass through the [Filesystem Internals](https://www.nomadproject.io/docs/internals/filesystem) docs and I don't think there's any change needed there -- we don't really discuss interpolation so much as the placement of the artifact relative to the task's working directory and how that interacts with task drivers.

docs: remove artifact destination interpolation warning

---

website/content/docs/job-specification/hcl2/variables.mdx

Fixes https://github.com/hashicorp/nomad/issues/10031
Block labels are not expressions so they can't be interpolated without hacks
like `dynamic` blocks. Clarify this so that we don't confuse users who
shouldn't need to dig into the subtle nuances between expressions and blocks.

docs: clarify that block labels can't be interpolated in HCL2

---

website/content/docs/job-specification/hcl2/functions/conversion/convert.mdx
website/content/docs/job-specification/hcl2/locals.mdx

Fixes https://github.com/hashicorp/nomad/issues/10024
HCL2 locals don't have type constraints, and the map syntax is interpreted as
an object. So users may need to explictly convert to map for some functions.
The `convert` function documentation was missing the required type constructor
parameter for collections.

docs: clarify type constraints for collections in locals

---

jobspec2/parse_test.go
jobspec2/types.config.go

Fixes https://github.com/hashicorp/nomad/issues/10043
Variables that are unset return the correct diagnostic but throw a panic when
we later parse the job body. Return early if there are any variable parsing
errors instead of continuing in a potentially invalid state.

hcl2: avoid panic on unset variable

---

CHANGELOG.md

Add a handful of missing changelog entries for the upcoming Nomad 1.0.4.

changelog: missing changelog items for 1.0.4

---

website/content/docs/configuration/index.mdx

clarify some confusion for customers who observe +1 log file compared to the set `log_rotate_max_files` value

log_rotate_max_files docs request 29569

---

CHANGELOG.md
command/agent/consul/service_client.go
command/agent/consul/service_client_test.go

This PR fixes a bug where sidecar services would be re-registered into Consul every ~30
seconds, caused by the parent service having its tags field set and the sidecar_service
tags unset. Nomad would directly compare the tags between its copy of the sidecar service
definition and the tags of the sidecar service reported by Consul. This does not work,
because Consul will under-the-hood set the sidecar service tags to inherit the parent
service tags if the sidecar service tags are unset. The comparison then done by Nomad
would not match, if the parent sidecar tags are set.
Fixes #10025

consul/connect: Fix bug where connect sidecar services would be unnecessarily re-registered

---

CHANGELOG.md
nomad/deploymentwatcher/deployment_watcher.go
nomad/deploymentwatcher/deployments_watcher_test.go
nomad/state/state_store.go
nomad/structs/structs.go
website/content/docs/job-specification/update.mdx

Fixes https://github.com/hashicorp/nomad/issues/7058
In a deployment with two groups (ex. A and B), if group A's canary becomes healthy before group B's, the deadline for the overall deployment will be set to that of group A. When the deployment is promoted, if group A is done it will not contribute to the next deadline cutoff. Group B's old deadline will be used instead, which will be in the past and immediately trigger a deployment progress failure. Reset the progress deadline when the job is promotion to avoid this bug, and to better conform with implicit user expectations around how the progress deadline should interact with promotions.

deploymentwatcher: reset progress deadline on promotion

---

dist/README.md
dist/systemd/nomad.service
e2e/terraform/packer/ubuntu-bionic-amd64/nomad.service
terraform/shared/config/nomad.service

This PR places `StartLimitIntervalSec` and `StartLimitBurst` in the
`Unit` section of systemd unit files, rather than the `Service` section.
https://www.freedesktop.org/software/systemd/man/systemd.unit.html
Fixes #10065

dist: place systemd unit options correctly

---

api/allocations.go
go.sum
vendor/github.com/hashicorp/nomad/api/allocations.go

This PR adds the missing `Devices` field on `AllocatedTaskResources `.
We've been running this in production at fly.io, works as expected 😄 
Fixes #10063

Add devices to AllocatedTaskResources

---

command/namespace.go

The old URL redirects to https://learn.hashicorp.com/nomad

cli: Update namespace helptext guide URL

---

CHANGELOG.md

Fix a link to the wrong PR. I'll need to cherry-pick this into the release branch along with 6bf43bcf9b895dd05a59c1b707830bb815e449c0.

changelog: fix link for GH-9937

---

CHANGELOG.md
scheduler/util.go
scheduler/util_test.go

This PR fixes a bug where tasks where Connect services could be
triggered to destructively update (i.e. placed in a new alloc)
when no update should be necessary.
Fixes #10077

consul/connect: correctly detect when connect tasks not updated

---

api/jobs_test.go
api/services.go
api/services_test.go
client/allochealth/tracker.go
client/allochealth/tracker_test.go
client/allocrunner/groupservice_hook.go
command/agent/consul/service_client.go
command/agent/consul/service_client_test.go
command/agent/job_endpoint.go
command/agent/job_endpoint_test.go
e2e/consul/consul.go
e2e/consul/input/on_update.nomad
e2e/consul/input/on_update_2.nomad
e2e/consul/input/on_update_check_restart.nomad
e2e/consul/on_update.go
e2e/e2eutil/allocs.go
jobspec/parse_service.go
jobspec/parse_test.go
jobspec/test-fixtures/basic.hcl
nomad/structs/diff_test.go
nomad/structs/services.go
nomad/structs/services_test.go
vendor/github.com/hashicorp/nomad/api/services.go
website/content/docs/job-specification/service.mdx

This PR introduces a new configuration option `on_update` to determine how service checks should evaluate a reported health status. The default value `require_healthy` requires the check  to report healthy for nomad to consider the check healthy. `ignore_warnings` and `ignore` can be used to allow for warnings and errors to be considered healthy as well.
This allows operators to define liveness and readiness checks, by ignoring warnings Nomad can progress a deployment and allow consul to introduce the service into a resource pool once the service no longer reports a warning status.
TODO
Questions
- ~~How should `check_restart` compose with `on_update = ignore`?~~ invalid, hard validation error
fixes #4531

Service and Check on_update configuration option (readiness checks)

---

jobspec/parse_service.go

Fixes https://github.com/hashicorp/nomad/issues/10072

fix: parse_service: return err instead of panic

---

ui/app/components/chart-primitives/area.hbs
ui/app/components/chart-primitives/area.js
ui/app/components/chart-primitives/v-annotations.hbs
ui/app/components/chart-primitives/v-annotations.js
ui/app/components/line-chart.js
ui/app/components/scale-events-chart.js
ui/app/components/stats-time-series.js
ui/app/styles/charts/line-chart.scss
ui/app/templates/components/line-chart.hbs
ui/app/templates/components/stats-time-series.hbs
ui/app/utils/properties/glimmer-style-string.js
ui/app/utils/properties/uniquely.js
ui/stories/charts/line-chart.stories.js
ui/stories/utils/delayed-array.js
ui/tests/helpers/glimmer-factory.js
ui/tests/integration/components/line-chart-test.js
ui/tests/integration/components/primary-metric-test.js
ui/tests/unit/components/line-chart-test.js
ui/tests/unit/components/scale-events-chart-test.js
ui/tests/unit/components/stats-time-series-test.js

This PR does three things:
1. Pulls common chart primitives out of `LineChart` and into their own components
2. Refactors `StatsTimeSeries` to use composition instead of inheritance to get `LineCharts` base features
3. Converts `LineChart`, `StatsTimeSeries`, and `ScaleEventsChart` into Glimmer components.
Converting everything ended up being a doozy, but the before and after stats on `line-chart.js` tell the story, imo. Down from 435 lines to 324 lines with more reductions planned.
------------------------
This PR is the first step in the following project that concludes with improved stats charts:
1. **Pull common chart primitives out of `LineChart`**
2. Use contextual components to reduce the responsibilities and API surface area of `LineChart`
3. Add multi-area support and horizontal …

UI: Line chart decomposed

---

CHANGELOG.md
command/operator_debug.go
command/operator_debug_test.go

This fixes a bug in nomad operator debug that occurred when an HTTPS address was specified for Consul, either through the `-consul-http-addr` CLI argument or `CONSUL_HTTP_ADDR` environment variable
Fixes #10081

Handle Consul API URL protocol mismatch

---

nomad/state/schema.go
nomad/state/state_store.go
nomad/state/state_store_test.go
nomad/structs/structs.go

The `OneTimeToken` struct is to support the `nomad ui -login` command. This
changeset adds the struct to the Nomad state store. (Raft updates will be done when I do the RPC PR next.)
Related to #10066 and the implementation of #6054. I'm making this PR to a branch `f-nomad-ui-login` so that I can make a number of incremental PRs as I work through this small project.

state store updates for one-time tokens

---

ui/.storybook/babel.config.js
ui/app/components/chart-primitives/area.js
ui/app/components/chart-primitives/v-annotations.hbs
ui/app/components/line-chart.js
ui/app/templates/components/line-chart.hbs
ui/app/templates/components/scale-events-chart.hbs
ui/app/templates/components/stats-time-series.hbs
ui/package.json
ui/stories/charts/line-chart.stories.js
ui/tests/integration/components/line-chart-test.js
ui/yarn.lock

**WIP:** Still need to update the line chart stories and reassess test coverage.
In addition to using contextual components, this PR brings in the [named blocks polyfill](https://github.com/ember-polyfills/ember-named-blocks-polyfill) that will be released in Ember core in 3.25. This is due to some yielded components needing to be in the SVG while others need to be outside (e.g., annotations are HTML and cannot be in the SVG).
---------------
This PR is the second step in the following project that concludes with improved stats charts:
1. Pull common chart primitives out of LineChart
2. **Use contextual components to reduce the responsibilities and API surface area of LineChart**
3. Add multi-area support and horizontal annotations to LineChart via the new contextual component interface

UI: Line Chart contextual components

---

helper/raftutil/msgtypes.go
nomad/acl_endpoint.go
nomad/acl_endpoint_test.go
nomad/config.go
nomad/core_sched.go
nomad/fsm.go
nomad/leader.go
nomad/state/state_store.go
nomad/state/state_store_test.go
nomad/structs/structs.go

RPC endpoints for the user-driven APIs (`UpsertOneTimeToken` and `ExchangeOneTimeToken`) and token expiration (`ExpireOneTimeTokens`). Includes adding expiration to the periodic core GC job.
Related to #10066 #10091 and the implementation of #6054. I'm making this PR to a branch `f-nomad-ui-login` so that I can make a number of incremental PRs as I work through this small project. This PR does not include the HTTP APIs that call these RPCs, which will be in the next PR.

RPC endpoints to support 'nomad ui -login'

---

nomad/acl_endpoint.go
nomad/acl_endpoint_test.go

Fix a bug in the `nomad ui -login` RPCs introduced in #10092. The exchange RPC was not verifying that the one-time token was not expired.
Related to #10066 #10091 #10092 and the implementation of #6054. I'm making this PR to a branch f-nomad-ui-login so that I can make a number of incremental PRs as I work through this small project.

one-time token: never return expired tokens

---

e2e/terraform/compute.tf
e2e/terraform/nomad.tf
e2e/terraform/packer/ubuntu-bionic-amd64/provision.sh
e2e/terraform/packer/windows-2016-amd64/provision.ps1
e2e/terraform/provision-nomad/main.tf
e2e/terraform/provision-nomad/variables.tf

Ensure that the e2e clusters are isolated and never attempt to autojoin
with another e2e cluster.
This ensures that each cluster servers have a unique `ConsulAutoJoin`,
to be used for discovery.
Fixes https://github.com/hashicorp/nomad/issues/8344

e2e: segment e2e clusters

---

CHANGELOG.md
ui/app/components/das/recommendation-card.hbs
ui/app/components/das/recommendation-card.js

With the Ember update, when the will-destroy action is called
to check the element height, its height is already zero. That
seems strange but I didn’t look into it any further, as
using did-insert to store the element lets us use its height
before any other actions when a processing button is pressed.
Thanks to @lgfa29 for catching this.

UI: Fix rendering of DAS interstitial components

---

website/content/docs/autoscaling/plugins/target.mdx

docs: hightlight different default node drain deadline when using the Autoscaler

---

client/allocrunner/taskrunner/task_runner.go
drivers/docker/config.go
drivers/docker/driver.go
drivers/docker/driver_test.go
plugins/drivers/driver.go
website/content/docs/drivers/docker.mdx

As discussed in #4781 , having those extra labels is needed for log shipping, cAdvisor, etc.

Add extra Docker labels ( job name, task and task group name)

---

api/acl.go
api/acl_test.go
command/agent/acl_endpoint.go
command/agent/acl_endpoint_test.go
command/agent/http.go
command/ui.go
vendor/github.com/hashicorp/nomad/api/acl.go
website/content/api-docs/acl-tokens.mdx
website/content/docs/commands/ui.mdx

The last bit of `nomad ui -authenticate`. Only the 3a7dba9 and dfd8407  commits are part of this PR; it won't compile without #10095, but I'll rebase it once that's been merged.
Related to #10066 #10091 #10092 #10095 and the implementation of #6054. I'm making this PR to a branch `f-nomad-ui-login`.

CLI 'nomad ui -authenticate' flag for one-time token exchange

---

website/content/docs/internals/filesystem.mdx

Fixes https://github.com/hashicorp/nomad/issues/10122
---
Full example of the path here:
```hcl
datacenters = ["dc1"]
group "web" {
network {
port "www" {
to = 8001
}
}
task "httpd" {
config {
image   = "busybox:1"
command = "httpd"
args    = ["-v", "-f", "-p", "8001", "-h", "/srv"]
ports   = ["www"]
mounts = [{
type   = "bind"
source = "../alloc"
target = "/srv"
}]
}
template {
data        = "<html>hello, world</html>"
destination = "${NOMAD_ALLOC_DIR}/index.html"
}
resources {
cpu    = 128
memory = 128
}
}
}
}
```

docs: clarify mount source path in filesystem docs

---

website/content/api-docs/acl-tokens.mdx

Endpoints for requesting and exchanging one-time tokens via the HTTP API. Includes documentation updates.
Related to #10066 #10091 #10092 and the implementation of #6054. I'm making this PR to a branch `f-nomad-ui-login` so that I can make a number of incremental PRs as I work through this small project. @backspace I've tagged you as a reviewer on this PR mostly so you can verify the JSON response bodies look like something you won't hate working with. 😀 
---
In addition to the unit tests, I've tested this against a dev build via `curl`:
```sh
$ export NOMAD_TOKEN=18c44fd5-5501-3931-ef69-9a32c12e722c
$ curl -XPOST -H "X-Nomad-Token: $NOMAD_TOKEN" \
"http://localhost:4646/v1/acl/token/onetime" | jq .
{
"Index": 15,
"OneTimeToken": {
"AccessorID": "0ff9d33b-a937-c8cd-0bbe-616dd127caab", …
```

HTTP API support for 'nomad ui -login'

---

website/content/docs/job-specification/artifact.mdx

Fixes https://github.com/hashicorp/nomad/issues/10036
The example without `git::` is incorrect when used with hosting providers such as BitBucket that aren't automatically detected by go-getter. Plus added a note about known_hosts.

docs/artifact: clarify git:: prefix usage for private repos

---

CHANGELOG.md
client/allocrunner/alloc_runner.go

Old log line looked this:
```
[INFO]  client.alloc_runner: killing task: : alloc_id=7b9282db-...-6d35ce172fdd EXTRA_VALUE_AT_END=connect-proxy-nomadrepodb
```

client: fix task name logging

---

contributing/README.md
contributing/checklist-jobspec.md
contributing/golang.md
dev/hooks/pre-push
e2e/README.md
e2e/terraform/Makefile
terraform/gcp/README.md
ui/README.md

Nomad's `master` branch is being renamed to `main`. Once that's done, we'll want to update the links in this PR.

docs: swap master for main in Nomad repo

---

demo/csi/digitalocean/plugin.nomad

This is causing everyone's `lint-go` tests to fail.

demo: hclfmt a jobspec

---

website/content/api-docs/libraries-and-sdks.mdx
website/content/api-docs/quotas.mdx
website/content/docs/internals/plugins/devices.mdx
website/pages/docs/[[...page]].jsx

Updates all our internal links. Punted on hunting down third-parties to verify they're up-to-date.

docs: update website links from master to main

---

api/acl.go
api/acl_test.go
command/agent/acl_endpoint.go
command/agent/acl_endpoint_test.go
command/agent/http.go
command/ui.go
helper/raftutil/msgtypes.go
nomad/acl_endpoint.go
nomad/acl_endpoint_test.go
nomad/config.go
nomad/core_sched.go
nomad/fsm.go
nomad/leader.go
nomad/state/schema.go
nomad/state/state_store.go
nomad/state/state_store_test.go
nomad/structs/structs.go
vendor/github.com/hashicorp/nomad/api/acl.go
website/content/api-docs/acl-tokens.mdx
website/content/docs/commands/ui.mdx

Merge PR for the feature branch inclusive of all work except for the web UI work being done by @backspace in #10066. This PR contains the work previously reviewed in #10066 #10091 #10092 #10095 and #10097.

cli: authenticate to the Nomad web UI via the CLI

---

CHANGELOG.md
api/internal/testutil/server.go
api/operator_metrics_test.go
command/agent/metrics_endpoint.go
command/agent/metrics_endpoint_test.go
website/content/docs/upgrade/upgrade-specific.mdx

If the user has disabled Prometheus metrics and a request is
sent to the metrics endpoint requesting Prometheus formatted
metrics, then the request should fail.
The returned response code copies that of Consul, to provide a
consistent user experience.
It also fixes a knock-on test failure which assumed Prometheus
formatted metrics were available from the test server.
closes #10070

agent: return req error if prometheus metrics are disabled.

---

CHANGELOG.md
scheduler/feasible.go
scheduler/feasible_test.go

When multiple CSI volumes are requested, the feasibility check could return
early for read/write volumes with free claims, even if a later volume in the
request was not feasible for any other reason (including not existing at
all). This can result in random failure to fail feasibility checking,
depending on how the map of volumes was being ordered at runtime.
Remove the early return from the feasibility check. Add a test to verify that
missing volumes in the map will cause a failure; this test will not catch a
regression every test run because of the random map ordering, but any failure
will be caught over the course of several CI runs.
Discovered the hard way while working on #10136 for #7877.

scheduler/csi: fix early return when multiple volumes are requested

---

website/components/basic-hero/style.css
website/components/case-study-carousel/style.css
website/components/comparison-callouts/style.module.css
website/components/enterprise-info/style.css
website/components/featured-slider/style.css
website/components/features-list/style.css
website/components/homepage-hero/style.css
website/components/learn-nomad/style.css
website/components/mini-cta/style.css
website/package-lock.json
website/package.json

Removes references to deprecated gray CSS properties and maps all gray colors to new brand values.
[_Created by Sourcegraph campaign `kstraut/product-sites-migrate-v3-gray-colors`._](https://sourcegraph.hashi-mktg.com/users/kstraut/campaigns/product-sites-migrate-v3-gray-colors)
Due to old imports of `react-global-styles` within `react-components`, the proper gray values will not show until we update `react-components` later on because the old style sheets are taking precedent.
```
// v2 gray css properties to new v3 values
"--gray-3" --> "--gray-2" 
"--gray-4" --> "--gray-3" 
"--gray-5" --> "--gray-4" 
"--gray-6" --> "--gray-5" 
"--gray-7" --> "--gray-6" 
// Replace Deprecated Gray Value references
"DEPRECATED-gray-:[~1|2]" --> "gray-1" 
"DEPRECATED-gray-:[~3|4]" --> "gray-2" …
```

website(style): Update gray brand colors

---

command/volume_status.go

Volume IDs are not UUIDs, so truncating them to the short ID isn't really
necessary and makes for especially awkward UX when per-alloc volumes are in
use.

CSI: don't truncate CSI volume IDs

---

website/content/docs/nomad-vs-kubernetes/index.mdx

The terminology here is a bit tricky. Technically Kuberbetes deprecated
their Docker *runtime* support but can still run Docker images. Sadly in
a lot of people's minds "Docker" and "containers" are nearly synonymous.
I think "Linux containers" is a more accurate characterization of
Kubernetes focus than "Docker" at this point.
Fixes #10120

docs: describe k8s in terms of "Linux containers"

---

website/content/api-docs/index.mdx

We've only ever had 1 API version, and we've broken backward
compatibility extremely rarely. Nothing changed about this with the
release of 1.0, let's just remove these sentences and save everybody
some reading.

docs: remove mention of api versioning

---

website/content/docs/job-specification/index.mdx

As pointed out from an user in our [Discuss forum](https://discuss.hashicorp.com/t/group-network-vs-group-task-resources-network/21963/5), the jobspec example in our overview page is missing `ports` assignment to the task.

docs: add ports to jobspec overview example

---

CHANGELOG.md
drivers/docker/config.go
drivers/docker/driver.go
drivers/docker/driver_test.go
website/content/docs/drivers/docker.mdx

Added support to specify default docker log driver in plugin options. 

---

CHANGELOG.md

CHANGELOG entry was present in the 0.12.10 tag, but was missing from main.
https://github.com/hashicorp/nomad/blob/v0.12.10/CHANGELOG.md

CHANGELOG: Add missing 0.12.10 version

---

website/content/docs/job-specification/index.mdx

Clarify a frequent point of confusion. We'd probably like to improve upon this situation (see https://github.com/hashicorp/nomad/issues/6758) but right now, especially with HCL2 being able to access local environment data, this is not likely to land anytime soon.

docs: clarify HCL is parsed in CLI

---

plugins/csi/client.go
plugins/csi/client_test.go
plugins/csi/fake/client.go
plugins/csi/plugin.go
plugins/csi/testing/client.go

The CSI volume creation workflow has a lot of plumbing code to write. So this PR is onto the `csi-create-volume` branch (ref https://github.com/hashicorp/nomad/pull/10165) so as to keep review sizes reasonable.
This changeset is only the protobuffer mappings between the CSI library and our own internal structs.

CSI: protobuffer mappings for Create/Delete/List volume RPCs

---

api/internal/testutil/server.go
command/agent/consul/unit_test.go
drivers/shared/executor/executor_linux_test.go
e2e/connect/acls.go
helper/escapingio/reader_test.go
helper/pluginutils/hclutils/util_test.go
nomad/consul.go
nomad/fsm_test.go
nomad/state/state_store.go
nomad/state/state_store_test.go
nomad/structs/funcs_test.go
nomad/structs/structs.go
testutil/server.go

`Sanity check` is not the preferred vernacular.  Ref: [Writing inclusive documentation. Google.](https://developers.google.com/style/inclusive-documentation#ableist-language)

Fixup uses of `sanity`

---

website/content/docs/commands/operator/debug.mdx

Add missing dashes to `pprof-duration` and `stale` in the `nomad operator debug` Usage docs.
Note -- this was a quick edit directly in GitHub website.  Shouldn't be a problem, but wanted to point it out just in case.

docs: add missing dashes to operator debug Usage

---

.gitignore
command/commands.go
command/volume_init.go
website/content/docs/commands/volume/index.mdx
website/content/docs/commands/volume/init.mdx
website/data/docs-navigation.js

Create a convenience command for generating example CSI volume specifications,
similar to the existing `nomad job init` or `nomad quota init` commands.

CSI: volume init command

---

CHANGELOG.md
api/csi.go
command/agent/csi_endpoint.go
command/volume_deregister.go
command/volume_detach.go
command/volume_status_csi.go
nomad/csi_endpoint.go
nomad/state/state_store.go
nomad/state/state_store_test.go
scheduler/feasible.go
scheduler/scheduler.go
vendor/github.com/hashicorp/nomad/api/csi.go

Callers of `CSIVolumeByID` are generally assuming they should receive a single volume. Among other possible bugs, this potentially results in feasibility checking being performed against the wrong volume if a volume's ID is a prefix substring of other volume. Discovered this while working on https://github.com/hashicorp/nomad/pull/10136 because of `"test"` vs `"test[0]"`
But removing the incorrect prefix matching from `CSIVolumeByID` breaks prefix matching in the command line client. Add the required elements for prefix matching back to the commands and API.

CSI: remove prefix matching from CSIVolumeByID and fix CLI prefix matching

---

CHANGELOG.md
api/tasks.go
client/allocrunner/csi_hook.go
command/agent/job_endpoint.go
e2e/csi/input/use-ebs-volume.nomad
e2e/terraform/compute.tf
e2e/terraform/terraform.tfvars
e2e/terraform/volumes.tf
nomad/state/state_store.go
nomad/structs/diff_test.go
nomad/structs/funcs.go
nomad/structs/structs.go
nomad/structs/structs_test.go
nomad/structs/volumes.go
scheduler/feasible.go
scheduler/feasible_test.go
scheduler/generic_sched.go
scheduler/generic_sched_test.go
scheduler/stack.go
scheduler/stack_test.go
scheduler/system_sched.go
scheduler/util.go
vendor/github.com/hashicorp/nomad/api/tasks.go
website/content/docs/job-specification/update.mdx
website/content/docs/job-specification/volume.mdx

Fixes https://github.com/hashicorp/nomad/issues/7877
Adds a `PerAlloc` field to volume requests that directs the scheduler to test feasibility for volumes with a source ID that includes the allocation index suffix (ex. `[0]`), rather than the exact source ID. This suffix is also being added at the client when the volume claim RPCs are sent.
Reviewer notes:
* Includes a very basic end-to-end smoke test, but I've tested this with multiple volumes as well. Once https://github.com/hashicorp/nomad/issues/8212 is complete, I'll update the E2E test to create multiple volumes for EBS (which has controllers) so that the entire lifecycle is being exercised.
* ~This PR currently depends on and includes 97bb912 from https://github.com/hashicorp/nomad/pull/10158. Once that's merged, d44d62e should be …

CSI: unique volume per allocation

---

client/client.go
client/client_test.go
client/rpc.go
client/testing.go
command/agent/agent.go
nomad/client_csi_endpoint_test.go

This commit includes a new test client that only implements the RPC protocol
and not any other state. Only the RPCs that are passed in are registered,
which lets you implement a mock RPC in the server tests. This commit includes
an example of this for the ClientCSI RPC server.
This commit has been extracted out of https://github.com/hashicorp/nomad/pull/10185 to make review sizes manageable.

test infrastructure for mock client RPCs

---

client/csi_endpoint.go
client/csi_endpoint_test.go
client/pluginmanager/csimanager/volume_test.go
client/structs/csi.go
nomad/client_csi_endpoint.go
nomad/client_csi_endpoint_test.go
nomad/csi_endpoint.go
nomad/csi_endpoint_test.go
nomad/structs/csi.go
plugins/csi/plugin.go

Implementation of the `CreateVolume`, `DeleteVolume`, and `ListVolume` (external volumes) for CSI.
Notes for reviewers:
* This is a bit of a beast of a PR but it's mostly plumbing code and I've got it so that you should be able to review commit-by-commit.
* Note there are no HTTP or CLI commits; those will be handled in the next PR.
* Also note there are no new raft messages for this work.
* This PR is targeting the `csi-create-volume` branch: https://github.com/hashicorp/nomad/pull/10165
* This changeset currently includes the contents of https://github.com/hashicorp/nomad/pull/10193 and will be rebased once that's been merged.

CSI: create/delete/list volume RPCs

---

nomad/structs/testing.go

Update the tests to default to running as 1.0.0 - to ensure that we exercise the latest/modern paths.  When testing compatibility mode with older servers, tests should explicitly downgrade versions; our tests already do like done in https://github.com/hashicorp/nomad/blob/v1.0.4/nomad/client_stats_endpoint_test.go#L144-L169 .
Closes https://github.com/hashicorp/nomad/issues/10201

testing: default nomad test nodes to 1.0.0

---

e2e/csi/csi.go

Fixes https://github.com/hashicorp/nomad/issues/10205, which turned out to be a missed TODO.
---
```
$ go test -v . -run 'TestE2E/CSI/\*csi\.CSIVolumesTest/TestEBSVolumeClaim'
=== RUN   TestE2E/CSI
=== RUN   TestE2E/CSI/*csi.CSIVolumesTest
=== RUN   TestE2E/CSI/*csi.CSIVolumesTest/TestEBSVolumeClaim
--- PASS: TestE2E (75.58s)
--- PASS: TestE2E/CSI (75.58s)
--- PASS: TestE2E/CSI/*csi.CSIVolumesTest (75.50s)
--- PASS: TestE2E/CSI/*csi.CSIVolumesTest/TestEBSVolumeClaim (75.32s)
PASS
ok      github.com/hashicorp/nomad/e2e  75.699s
```

E2E: CSI test should use expected unique-volume name

---

api/api.go
api/csi.go
client/structs/csi.go
command/agent/csi_endpoint.go
command/agent/csi_endpoint_test.go
command/agent/http.go
command/agent/http_test.go
nomad/csi_endpoint.go
nomad/csi_endpoint_test.go
nomad/structs/csi.go
nomad/structs/structs.go
vendor/github.com/hashicorp/nomad/api/api.go
vendor/github.com/hashicorp/nomad/api/csi.go

Implementation of the `CreateVolume`, `DeleteVolume`, and `ListExternalVolume` HTTP endpoints for CSI.
Notes for reviewers:
* Note there are no CLI commits; those will be handled in the next PR but I've got https://github.com/hashicorp/nomad/pull/10211 that uses this API so I feel comfortable with the "shape".
* HTTP API docs will be in a separate PR
* This PR is targeting the `csi-create-volume` branch: https://github.com/hashicorp/nomad/pull/10165, which has the RPCs already merged in.

CSI: HTTP handlers for create/delete/list

---

website/content/api-docs/jobs.mdx

The documentation for /v1/job endpoint is missing the `?namespace=` query parameter

Update /v1/job API docs

---

e2e/csi/input/plugin-aws-ebs-controller.nomad
e2e/csi/input/plugin-aws-ebs-nodes.nomad
e2e/csi/input/plugin-aws-efs-nodes.nomad

Related to the work being done in https://github.com/hashicorp/nomad/pull/10165 but can be merged independently.

E2E: bump AWS CSI driver versions

---

website/content/docs/configuration/audit.mdx

Update the Nomad `Audit` Configuration documentation to show the correct key name.

Change enable to enabled

---

e2e/terraform/nomad.tf
e2e/terraform/packer/ubuntu-bionic-amd64/nomad.service
e2e/terraform/packer/ubuntu-bionic-amd64/provision.sh
e2e/terraform/provision-nomad/main.tf
e2e/terraform/provision-nomad/variables.tf
e2e/terraform/variables.tf

Allow passing in an enterprise license to linux servers.
I believe we only use windows as clients right now so I didn't update the windows provisioning script

e2e allow setting an enterprise license environment variable

---

e2e/e2e_test.go
e2e/e2eutil/job.go
e2e/parameterized/input/simple.nomad
e2e/parameterized/parameterized.go
nomad/job_endpoint.go
nomad/job_endpoint_test.go
nomad/periodic.go
nomad/periodic_test.go

Fixes a bug where Nomad reports negative or incorrect running children
counts for periodic jobs.
The periodic dispatcher derives a child job without reseting the status.
If the periodic job has a `running` status, the derived job will start
as `running` status and transition to `pending`.  Since this is
unexpected transition, the counting in [`StateStore.setJobSummary`](https://github.com/hashicorp/nomad/blob/1b4f186c42316f8d6dd37d50d41d05636a68458b/nomad/state/state_store.go#L4494-L4506) gets out of sync and
result in negative/incorrect values.
Note that this only affects periodic jobs after a leader transition.
During the first job registration, the job is added with `pending` or
`""` status. However, after a leader transition, the new leader
[repopulates the dispatcher …

periodic: always reset periodic children status

---

e2e/e2e_test.go
e2e/license/license.go

adds a small e2e test to ensure the cluster license is what we expect.

e2e license smoke test

---

website/content/docs/integrations/consul-connect.mdx

Fixes https://github.com/hashicorp/nomad/pull/9987
Replaces the closed https://github.com/hashicorp/nomad/pull/9987, which I apparently can't reopen by pushing to.

docs: note that Connect requires a hard-coded port

---

command/agent/http.go
command/agent/http_test.go

Fixes https://github.com/hashicorp/nomad/issues/10241
The OTT feature relies on having a query parameter for a one-time token which
gets handled by the UI. We need to make sure that query param is preserved
when redirecting from the root URL to the `/ui/` URI.

redirect from HTTP root to UI should include query params

---

CHANGELOG.md
command/operator_debug.go

Remove extra linefeed character written to `monitor.log` after each StreamFrame.  Fixes #9889.
Linefeeds are already included in the buffer from StreamFrame.  When a full frame was received (1024 bytes) the extra LF split the last log line in the frame.  Frames with less than 1024 bytes resulted in an extra blank line written to file.

Debug: Remove extra linefeed in monitor.log

---

api/jobs_test.go
api/nodes.go
api/resources.go
api/resources_test.go
client/client_test.go
command/agent/job_endpoint.go
lib/cpuset/cpuset.go
lib/cpuset/cpuset_test.go
nomad/structs/diff_test.go
nomad/structs/funcs.go
nomad/structs/funcs_test.go
nomad/structs/structs.go
nomad/structs/structs_test.go
scheduler/rank.go
scheduler/rank_test.go
scheduler/util.go
scheduler/util_test.go
vendor/github.com/hashicorp/nomad/api/nodes.go
vendor/github.com/hashicorp/nomad/api/resources.go

This is the first of a few PRs to merge in functionality to support the notion of reservable cores as a resource. This adds a new field to the task resources stanza `cores` which is an integer value to set the number of cores to reserve for the task. The scheduler will keep track of the reservable cores on each node and allocate individual cores to the requesting allocations. When the client receives an allocation placement with reserved cores, its `AllocatedResources.Cpu` object will include a new `ReservedCores` field which is a set of cpu cores to isolate to the task.
This PR focuses on the data structure foundation and scheduling logic to implement the feature. Subsequent PRs will include:
* Updating client cpu fingerprinting to detect node reservable cores [#10228]
* Implementing …

Reserved Cores [1/4]: Structs and scheduler implementation

---

CHANGELOG.md
client/allocrunner/taskrunner/connect_native_hook.go
client/allocrunner/taskrunner/connect_native_hook_test.go
website/content/docs/upgrade/upgrade-specific.mdx
website/content/partials/envvars.mdx

Fixes #10239. This only works if the `network` stanza is defined at the group level; otherwise
https://github.com/hashicorp/nomad/blob/3d9464023dbde64417468f4e623643d31fc3e7a5/nomad/job_endpoint_hook_connect.go#L100-L107
will skip the `groupConnectHook` which is responsible for setting the task kind to `connect-native`…
/cc @shoenig for a review :)

Automatically populate `CONSUL_HTTP_ADDR` for connect native tasks in host networking mode.

---

.circleci/config.yml

I believe this should be `main` so that the website image will get built on the base branch.

fix(circle): change website branch filter to main

---

plugins/csi/plugin.go
plugins/csi/testing/client.go

The CSI spec handles empty fields and nil fields in the protobuf differently,
which may result in validation failures for creating volumes with no prior
source (and does in testing with the AWS EBS plugin). Refactor the
`CreateVolumeRequest` mapping to the protobuf in the plugin client to avoid
this bug.
Reviewers: note this is targeting `csi-create-volume`

CSI: unset proto fields for volume create should be nil

---

api/csi.go
client/pluginmanager/csimanager/fingerprint.go
command/agent/csi_endpoint_test.go
nomad/csi_endpoint.go
nomad/csi_endpoint_test.go
nomad/state/testing.go
nomad/structs/csi.go
nomad/structs/node.go
plugins/csi/client_test.go
plugins/csi/plugin.go
vendor/github.com/hashicorp/nomad/api/csi.go

Fix a collection of validation-related issues for CSI volume creation that I discovered while getting things tested end-to-end.
* CSI: add missing `structs.CSIVolume` fields to `api.CSIVolume`
* CSI: volume creation/registration should not validate attachment. The CSI specification requires that we validate a list of `Capability` (access mode + accessibility) when we create volume, but the existing volume
registration workflow  incorrectly validates a single capability. The specific capability required by a volume claim is checked at the time we make the claim, so remove the check for `AttachmentMode`/`AccessMode`.
* CSI: fingerprint detailed controller capabilities. In order to support new controller RPCs, we need to fingerprint volume capabilities in more detail and perform controller …

CSI: create volume capability validation

---

CHANGELOG.md

Also:
* Added missing changlog entry for #10145
* Fixed misclassified entry for #10158

changelog: add section for backports from 1.1.0 to 1.0.5

---

api/csi.go
command/commands.go
command/volume.go
command/volume_create.go
command/volume_create_csi.go
command/volume_delete.go
command/volume_init.go
command/volume_register_csi.go
command/volume_register_test.go
command/volume_status_csi.go
vendor/github.com/hashicorp/nomad/api/csi.go
website/content/docs/commands/volume/create.mdx
website/content/docs/commands/volume/register.mdx
website/data/docs-navigation.js

Implementation of the `nomad volume create/delete` and extended `nomad volume status` commands for CSI. Includes HCL decoding update for volume spec so that we can humanize capacity bytes input values. 
Notes for reviewers:
* This PR is targeting the `csi-create-volume` branch: https://github.com/hashicorp/nomad/pull/10165

CSI: CLI for create/delete/list 

---

drivers/docker/coordinator_test.go

Fixes https://github.com/hashicorp/nomad/issues/10197
The test assertion that we don't have a delete future remaining races with the
code it's testing, because the removal of the image and the removal of the
future are not atomic. Move this assertion into a `WaitForResult` to avoid
test flakes which we're seeing on CI on Windows in particular.

drivers/docker: fix flaky image coordinator test

---

ui/app/adapters/token.js
ui/app/controllers/application.js
ui/app/routes/application.js
ui/app/services/token.js
ui/app/styles/components/empty-message.scss
ui/app/templates/application.hbs
ui/app/templates/components/forbidden-message.hbs
ui/app/utils/ott-exchange-error.js
ui/mirage/config.js
ui/mirage/factories/token.js
ui/tests/acceptance/token-test.js
ui/tests/pages/layout.js

This adds UI support for receiving the one-time token passed via query parameter, as in #10134
and related PRs, and exchanging it for its corresponding secret ID. When this works, it’s mostly
invisible, as seen here when used with `nomad ui -authenticate`, where the OTT is briefly onscreen:
You can also see the amended message when authentication fails suggesting to `-authenticate`.
When it fails, it shows a whole-page error:
Unfortunately, I was unable to produce the desired UX of having the OTT be erased from the URL
after processing, so I’m submitting this for review with that sad caveat. This will only be seen when
jumping directly with an identifier (`nomad ui -authenticate jobname`), as `nomad ui -authenticate`
forwards to `/ui/?ott=…` which then forwards to `/ui/jobs` after the …

UI: Add exchange of one-time token on application load

---

client/pluginmanager/csimanager/fingerprint.go
nomad/structs/csi.go
nomad/structs/node.go
plugins/csi/client_test.go
plugins/csi/plugin.go

In order to support new node RPCs, we need to fingerprint plugin capabilities in more detail. This changeset mirrors recent work to fingerprint controller capabilities (ref #10224), but is not yet in use by any Nomad RPC.
Note for reviewers: this PR will enable work being done in the [`csi-volume-status-stats`](https://github.com/hashicorp/nomad/tree/csi-volume-status-stats) branch and the CSI volume resize PR #10281

CSI: fingerprint detailed node capabilities

---

website/content/docs/autoscaling/cli.mdx

Document new flags added in https://github.com/hashicorp/nomad-autoscaler/pull/421
Preview:

docs: add Autoscaler CLI flags for policy eval configuration

---

website/content/docs/autoscaling/plugins/target.mdx

https://github.com/hashicorp/nomad-autoscaler/pull/425 added a requirement for the `autoscaling:TerminateInstanceInAutoScalingGroup` permission.

docs: Update AWS permission requirements for the Autoscaler

---

website/content/docs/autoscaling/plugins/strategy.mdx

related https://github.com/hashicorp/nomad-autoscaler/pull/436 and https://github.com/hashicorp/nomad-autoscaler/pull/433

docs: add fixed-value and pass-through autoscaler plugin docs.

---

GNUmakefile

This change disables using msgpack generated serializers in dev by
default.
In released binaries, we use code-generated msgpack serializers to
improve performance.  However, in development, code generated
serializers are a pain. If a developer forgets to re-generate code, the
code generated gets out of sync with the go structs, and result into
subtle bugs where some values appear not to persist as expected.
The CI and release scripts will continue to use the msgpack
code-generation. Devs who want to test locally can set
`GO_TAGS=codegen_generated` as well.

dev: ignore msgpack codegen code in dev by default

---

client/agent_endpoint.go
client/alloc_endpoint.go
client/fs_endpoint.go
command/agent/http.go
command/agent/http_test.go
helper/pluginutils/hclutils/testing.go
helper/pluginutils/hclutils/util.go
nomad/client_agent_endpoint.go
nomad/stream/ndjson.go
nomad/structs/encoding.go
nomad/structs/extensions.go
nomad/structs/handlers.go

json handles were moved to a new package in #10202
this was unecessary after refactoring, so this moves them back to their original location in package `structs`

move json handle back to `structs`

---

plugins/drivers/testutils/exec_testing.go

The exec command for this test was flakey and tested docker behavior we don't control, removing

remove flakey exec test that tests non-deterministic docker behavior

---

command/volume_register_csi.go
command/volume_register_test.go

When a volume is registered via `nomad volume register` and not via the
creation workflow, it may not have any of the capacity fields set (as they're
not used for registration). Handle this case without error, and let the
downstream RPCs handle the error case for `nomad volume create`.
---
Fixes these failing E2E tests:
```
=== RUN   TestE2E/CSI/*csi.CSIVolumesTest/TestEBSVolumeClaim
csi.go:112: 
Error Trace:	csi.go:112
Error:      	Received unexpected error:
could not register vol: exit status 1
Error decoding the volume definition: invalid capacity_min: could not parse value as bytes
Test:       	TestE2E/CSI/*csi.CSIVolumesTest/TestEBSVolumeClaim
--- FAIL: TestE2E/CSI/*csi.CSIVolumesTest/TestEBSVolumeClaim (33.82s)
=== RUN   TestE2E/CSI/*csi.CSIVolumesTest/TestEFSVolumeClaim
csi.go:196: …
```

CSI: correctly handly empty capacity fields during registration

---

command/alloc_status.go
command/helpers.go
drivers/docker/util/stats_posix.go
drivers/shared/executor/executor_linux.go

When running with cgroup-v2, the measured memory stats are Usage, Cache, and Swap only: https://github.com/opencontainers/runc/blob/v1.0.0-rc93/libcontainer/cgroups/fs2/memory.go#L75-L106 .
Also, in RSS isn't measured in a task, then `nomad alloc status` will use the reported Usage for the top level item.  This PR only changes the CLI, and we need to update the UI as well.
Fixes #10190
Related to #10251

Memory stats for cgroup-v2

---

.golangci.yml
GNUmakefile
api/api.go
api/csi.go
api/jobs.go
api/nodes.go
api/scaling.go
api/tasks.go
client/fingerprint/env_aws.go
client/fingerprint/env_azure.go
client/fingerprint/env_gce.go
command/agent/testagent.go
command/deployment_status.go
command/job_validate.go
command/operator_debug.go
drivers/docker/driver.go
drivers/java/utils.go
drivers/shared/executor/executor_linux.go
e2e/cli/command/test_decoder.go
vendor/github.com/hashicorp/nomad/api/api.go
vendor/github.com/hashicorp/nomad/api/csi.go
vendor/github.com/hashicorp/nomad/api/jobs.go
vendor/github.com/hashicorp/nomad/api/nodes.go
vendor/github.com/hashicorp/nomad/api/scaling.go
vendor/github.com/hashicorp/nomad/api/tasks.go

What changed
- golangci-lint [v1.39](https://github.com/golangci/golangci-lint/releases/tag/v1.39.0)
- `Replace(..., -1)` becomes `ReplaceAll(...)`
- some extra `fmt.Sprintf`, empty vars, or `for`loops
- `Time.Now().Sub(...)` becomes `Time.Since(...)`
What didn't change and the checks are disabled.
- `Deprecated in Nomad 0.10` which should be `Deprecated: ...`. See: `deprecatedComment`
- `//TODO` instead of `// TODO`. See: `commentFormatting`

chore: bump golangci-lint from v1.24 to v1.39

---

api/operator.go
command/license_get.go
vendor/github.com/hashicorp/nomad/api/operator.go
website/content/docs/commands/license/get.mdx

enable `-stale` flag to retrieve a servers license without forwarding request to leader

allow setting stale flag from cli to retrieve individual server license

---

website/content/docs/configuration/server.mdx

At some point the Operator API docs got broken into multiple pages so this anchor stopped working.

Fix the broken link in the bootstrapping custom scheduler warning

---

GNUmakefile
tools/buf/README.md

Previously installing `buf` was left out of `make bootstrap` because it
had conflicts with the `tools/go.mod` file and dependencies used by
other tools. With Go 1.16 we eliminated that `go.mod` file, and can
now just install `buf` with `go install` like everything else.
Note that v0.36.0 is the version installed in our `scripts/`, so that's the version set here. I noticed the latest version uses a different type for proto timestamps, which seems concerning.

build: install buf during bootstrap

---

website/content/docs/autoscaling/internals/node-selector-strategy.mdx

Preview:
`system` points to https://www.nomadproject.io/docs/schedulers#system but would it be better if it linked to https://www.nomadproject.io/docs/job-specification/job#type?

docs: add `empty_ignore_system` node selector strategy for autoscaling

---

.circleci/config.yml
CHANGELOG.md
api/api.go
api/api_test.go
vendor/github.com/hashicorp/nomad/api/api.go

Resolves #10301 
* Updates the `/api` tests to run with `-race`.
* Documenting test for #10301 
* Resolves race condition
Commit 4e25e8e2350579581b88bf96e67c18627008e65e shows a documenting test, which fails under `-race`:
https://app.circleci.com/pipelines/github/hashicorp/nomad/15527/workflows/d2032205-895a-4d7b-8ec6-41301a1614cb/jobs/147802
New test passes after 60648672518b642ea3b4dcab431ca521b3e6597b

fix potential race condition in API client

---

api/tasks.go
client/allocrunner/csi_hook.go
client/csi_endpoint.go
client/pluginmanager/csimanager/interface.go
client/pluginmanager/csimanager/volume.go
client/pluginmanager/csimanager/volume_test.go
command/agent/job_endpoint.go
command/volume_init.go
nomad/csi_endpoint.go
nomad/state/state_store.go
nomad/structs/csi.go
nomad/structs/csi_test.go
nomad/structs/structs.go
nomad/structs/structs_test.go
nomad/structs/volumes.go
vendor/github.com/hashicorp/nomad/api/tasks.go
website/content/docs/commands/volume/create.mdx
website/content/docs/commands/volume/register.mdx
website/content/docs/job-specification/volume.mdx

Registration of Nomad volumes previously allowed for a single volume capability (access mode + attachment mode pair). The recent `volume create` command requires that we pass a list of requested capabilities, but the existing workflow for claiming volumes and attaching them on the client assumed that the volume's single capability was correct and unchanging. This resulted in volume we create not being schedulable!
Add `AccessMode` and `AttachmentMode` to `CSIVolumeClaim`, use these fields to set the initial claim value, and add backwards compatibility logic to handle the existing volumes that already have claims without these fields.
Includes documentation updates.
Note for reviewers:
* Best reviewed commit-by-commit.
* My apologies for the large diff but ~450 lines of that is new tests …

CSI: set attach/access modes on volume claims

---

command/agent/csi_endpoint.go
command/agent/http.go
command/volume_status_csi.go
nomad/csi_endpoint.go
nomad/csi_endpoint_test.go

This changeset fixes two bugs discovered during E2E testing that unfortunately don't get picked up by our typical approach to HTTP endpoint unit testing (mostly because we don't have live CSI plugins to talk to in the test):
* Fix HTTP routing for external volume list. The HTTP router did not correctly route `/v1/volumes/external` without being explicitly added to the top-level router. Break this out into its own request handler.
* Fix early return on error from list external volumes command. If a plugin returns an error, we should continue at the outer scope to query the next plugin, otherwise we just retry the plugin we got an error on (potentially infinitely if it's an invalid request like an unsupported plugin).
It also includes an error message improvement:
* Capability check …

CSI: external volume list bug fixes

---

website/content/docs/commands/job/run.mdx

Add missing CLI flags for the `nomad job run` command and also move `-hcl1` to the same position as output by `nomad job run --help`.
Preview:

docs: add missing `nomad job run` CLI flags

---

website/package-lock.json
website/package.json

Remove the badges from the HCP products on the HashiStackMenu, as they are no longer needed.
[🔍 Preview](https://nomad-hvt79qrsu-hashicorp.vercel.app/)

Updates stackmenu to latest

---

e2e/csi/csi.go
e2e/csi/ebs.go
e2e/csi/efs.go
e2e/csi/input/ebs-volume0.hcl
e2e/csi/input/ebs-volume1.hcl
e2e/csi/input/use-ebs-volume.nomad
e2e/csi/input/use-efs-volume-read.nomad
e2e/csi/input/use-efs-volume-write.nomad
e2e/terraform/volumes.tf

Split the EBS and EFS tests out into their own test cases:
* EBS exercises the Controller RPCs, including the create/snapshot workflow. Drop the Terraform-created volume in lieu of the one created by the test.
* EFS exercises only the Node RPCs, and assumes we have an existing volume that gets registered, rather than created.
Note: assumes https://github.com/hashicorp/nomad/pull/10330 and https://github.com/hashicorp/nomad/pull/10331 get merged.

E2E: extend CSI test to cover create and snapshot workflows

---

CHANGELOG.md
command/agent/csi_endpoint_test.go
nomad/core_sched_test.go
nomad/csi_endpoint_test.go
nomad/structs/csi.go
website/content/docs/commands/volume/register.mdx
website/content/docs/job-specification/volume.mdx
website/content/docs/upgrade/upgrade-specific.mdx

Add validation for `capability` blocks on volume registration (as well as creation, where it was previously documented). Update documentation and CHANGELOG for new feature and this backwards incompatibility in the volume spec.
(ref https://github.com/hashicorp/nomad/pull/10322 for the E2E test updates for this.)

CSI: capability block is required for volume registration

---

command/volume_snapshot_list.go
command/volume_status_csi.go
plugins/csi/plugin.go

The AWS EBS CSI plugin was observed (see #10322) to return a EOF when we get to the end of the paging for `ListSnapshots`, counter to specification. Handle this case gracefully, including for `ListVolumes` (which EBS doesn't support but has similar semantics).
Also fixes a timestamp formatting bug on `ListSnapshots`

CSI: listing from plugins can return EOF

---

e2e/terraform/README.md
e2e/terraform/provision-nomad/main.tf

The E2E provisioning used local-exec to call ssh in a for loop in a hacky workaround for https://github.com/hashicorp/terraform/issues/25634, which was preventing remote-exec from working on Windows. Move to a newer version of Terraform that fixes the remote-exec bug to make provisioning more reliable and observable.
Note that Windows remote-exec needs to include the `powershell` call itself, unlike Unix-alike remote-exec.
---
_Original PR description:_
This changeset verifies that [TFv0.15.0-alpha20210107](https://github.com/hashicorp/terraform/releases/tag/v0.15.0-alpha20210107) fixed https://github.com/hashicorp/terraform/issues/25634, which allows us to remove our very hacky `local-exec` that we're using for provisioning.
When combined with calling `powershell C:/opt/provisioning.ps1` …

E2E: use remote-exec via TF0.14.7+

---

nomad/structs/diff.go

This fixes a function in `nomad/structs` that was testing the exact same conditions twice between an `if` and an `if else`. This fixes the second check to look for a `nil` `newMO` instead of looking for a `nil` `oldMO` and then clobbering the `newMO`.

nomad/structs: fix diff

---

website/content/partials/general_options.mdx

There was a small typo of "namespacecs" instead of "namespaces"

Fix typo in general options documentation

---

demo/csi/hostpath/README.md
demo/csi/hostpath/hostpath.hcl
demo/csi/hostpath/plugin.nomad
demo/csi/hostpath/redis.nomad
demo/csi/hostpath/run.sh

A demo for the CSI hostpath plugin, used primarily for development
purposes. This reproduction has been used for testing during our CSI
implementation work, and this changeset makes that public.

CSI: demo for hostpath plugin

---

website/content/docs/job-specification/volume.mdx

Remove a reference to a now-closed issue and clarify the wording for using `per_alloc` in lieu of `NOMAD_ALLOC_INDEX`.

docs: clean up explanation of volume per_alloc

---

client/allocrunner/networking_cni.go
client/allocrunner/networking_cni_test.go

This PR adds a branch of logic to how the alloc's IP address is discovered for CNI networks. Some CNI plugins don't reference an interface index in the result response. This leads to go-cni, the library we use for CNI, to associate the address with the default interface.
This logic will attempt to cycle through the interfaces and find the first address if there is no address found for the sandboxed interface.
Some additional debug log statements are also included to aid future CNI debugging.

CNI: add fallback logic if no ip address references sandboxed interface

---

nomad/csi_endpoint.go

Plugins could potentially ignore the `max_entries` field and return a list of
entries that is greater, so we slice the return value in the server RPC to
enforce these value. But page sizes less than the number of entries for the
external CSI ListVolumes and ListSnapshots RPCs could cause a panic, so fix
the boundary checking.

CSI: ensure page slices are within bounds

---

client/allocdir/alloc_dir.go
client/allocdir/alloc_dir_test.go
client/allocdir/input/test.hcl

When detecting the content type for a file, Nomad uses the [`http.DetectContentType`](https://golang.org/pkg/net/http/#DetectContentType) function, which follows the [MIME Sniffing spec](https://mimesniff.spec.whatwg.org). This spec defines a set of [steps](https://mimesniff.spec.whatwg.org/#identifying-a-resource-with-an-unknown-mime-type) to be applied to the first 512 bytes of the file. 
Step 9 is for [binary file detection](https://mimesniff.spec.whatwg.org/#binary-data-byte). It looks for a set of predefined byte patterns, one of which is `0x00`.
Without limiting the amount of bytes passed to `http.DetectContentType`, a file smaller than 512 bytes would cause `fileBytes` to end with several `0x00` bytes, and so the content-type would be set `application/octet-stream`, preventing the …

Limit bytes passed to `http.DetectContentType`

---

website/content/api-docs/allocations.mdx

The API docs don't make it immediately clear that the alloc signal API signals *all* tasks in an allocation if the `Task` parameter is omitted. You have to dig all the way down into the alloc runner to discover that behavior: https://github.com/hashicorp/nomad/blob/v1.0.4/client/allocrunner/alloc_runner.go#L1189-L1213

docs: clarify alloc signal behavior

---

nomad/job_endpoint.go

The error messages are reversed from tests performed above them.  The test uses the `validateJobUpdate()` function, but ignores the text of the error message itself.

Fix parameterized <-> non-parameterized job error

---

demo/csi/hostpath/README.md

As noted in https://github.com/hashicorp/nomad/commit/842d9d2aa9576a42c2c22b501e6739215197aab8#r49357169

docs: CSI hostpath demo doesn't need docker.volumes.enabled

---

.circleci/config.yml

Fixes https://github.com/hashicorp/nomad/issues/10363
"Bottles" have been migrated to GitHub packages, so we need to update homebrew
to point to that new source before installing the `protobuf` formula.
ref https://github.com/Homebrew/homebrew-core/issues/75028#issuecomment-817904447

CI: update homebrew before installing protobuf

---

.circleci/config.yml

Also, remove protobuf installation: it's not used anymore within the job.
CI job: https://app.circleci.com/pipelines/github/hashicorp/nomad/15668/workflows/e240078b-ab82-41c7-935b-0a2e79d3889a/jobs/149495

Update macOS image

---

api/operator.go
vendor/github.com/hashicorp/nomad/api/operator.go

Set the query meta for LicenseGet request. It's expected by api consumers to determine the raft index.
This fixes a regression in 1.0.4. I'll add a test for this on the Enterprise repository.

api: set operator query meta

---

command/ui.go

Noticed that we missed adding this to the CLI help text, even though it managed to make it into the documentation.

cli: add help for 'ui -authenticate' flag

---

e2e/csi/ebs.go

The command line output got changed out from under this test.

E2E/CSI: fix name of column used for snapshot create output parsing

---

CHANGELOG.md

Some changelog entries from community-submitted PRs #10104 and #10196

changelog entries for networking improvements

---

command/agent/acl_endpoint_test.go

This fixes two dropped test errors in `command/agent`.

command/agent: fix dropped test errors

---

ui/app/controllers/application.js
ui/app/routes/application.js
ui/tests/acceptance/token-test.js

This is a follow-on to #10066 to clear out the OTT from the URL after loading. While this approach
is unsightly, it’s how I was able to get it to happen, and it seems less unsightly than having the OTT
persist in the URL.
Here’s a GIF showing it being cleared when passing a job to `nomad ui -authenticate`:

UI: Add removal of OTT query parameter with delay

---

ui/app/components/fs/file.js
ui/tests/integration/components/fs/file-test.js

Between the charts refactor and the units refactor, I've been running a lot of tests. I won't be sad to see this one go:
Unfortunately it required introducing another `Ember.testing` in app code, but that still beats polluting my downloads folder.

UI: No downloads in test

---

jobspec2/types.variables.go

The current error links out to a Packer docs page.  This should probably be made something permalink-ish, but this at least feels less jarring.

Fix link in error for missing variable

---

client/allocrunner/networking_bridge_linux.go

Fixes #10180
I wasn't sure if there was a reason for the forcing first, but if not, this PR appends the rule, rather than forcing first

networking: Ensure CNI iptables rules are appended to chain and not forced to be first

---

e2e/terraform/packer/ubuntu-bionic-amd64/setup.sh
e2e/terraform/packer/windows-2016-amd64/install-consul.ps1

Using Consul Enterprise is going to be necessary for testing Nomad's
Consul Namespace integration in Nomad v1.1 in e2e.

e2e: get consul ent in e2e packer builds

---

e2e/csi/ebs.go

During refactoring of the CSI tests, the EBS test dropped the step where we stop the jobs before checking that the claims were released.
---
```
$ go test . -v -suite CSI
...
--- PASS: TestE2E (290.865s)
...
--- PASS: TestE2E/CSI (233.32s)
--- PASS: TestE2E/CSI/*csi.CSIControllerPluginEBSTest (233.14s)
--- PASS: TestE2E/CSI/*csi.CSIControllerPluginEBSTest/TestSnapshot (137.06s)
--- PASS: TestE2E/CSI/*csi.CSIControllerPluginEBSTest/TestVolumeClaim (34.22s)
--- PASS: TestE2E/CSI/*csi.CSINodeOnlyPluginEFSTest (56.93s)
--- PASS: TestE2E/CSI/*csi.CSINodeOnlyPluginEFSTest/TestEFSVolumeClaim (56.74s)
...
PASS
ok      github.com/hashicorp/nomad/e2e  290.865s
```

E2E/CSI: ensure jobs are stopped before checking claims are released

---

client/client.go
client/client_test.go
client/config/config.go
client/fingerprint/cpu.go
client/fingerprint/cpu_default.go
client/fingerprint/cpu_linux.go
client/lib/cgutil/cgutil_default.go
client/lib/cgutil/cgutil_linux.go
command/agent/agent.go
command/agent/agent_test.go
command/agent/config.go

This PR implements the Nomad client discovery of reservable CPU cores. On Linux systems with cgroups enabled, this uses the configured `cgroup_parent` to inspect the cpuset cgroup for the list of configured cores. On non-Linux systems or Linux systems where the cgroup subsystem is not mounted or the agent is not running as root, the set of reservable cpus defaults to all system cores.
A `cores` field has been added to the client configuration's `reserved` block which accepts a list of cpus or cpu range to remove from the set of discovered cpus, "reserving" them for the Nomad system.

Reserved Cores [2/4]: Client fingerprinting implementation

---

client/allocrunner/alloc_runner.go
client/allocrunner/alloc_runner_hooks.go
client/allocrunner/cgroup_hook.go
client/allocrunner/config.go
client/allocrunner/taskrunner/task_runner.go
client/allocrunner/testing.go
client/client.go
client/client_test.go
client/config/config.go
client/fingerprint/cgroup.go
client/fingerprint/cgroup_default.go
client/fingerprint/cgroup_linux.go
client/fingerprint/cpu.go
client/fingerprint/cpu_linux.go
client/lib/cgutil/cgutil_default.go
client/lib/cgutil/cgutil_linux.go
client/lib/cgutil/cpuset_manager.go
client/lib/cgutil/cpuset_manager_default.go
client/lib/cgutil/cpuset_manager_linux.go
client/lib/cgutil/cpuset_manager_linux_test.go
client/testutil/driver_compatible.go
drivers/exec/driver.go
drivers/java/driver.go
lib/cpuset/cpuset.go
lib/cpuset/cpuset_test.go
plugins/drivers/driver.go

This PR introduces a new AR hook which manages the lifecycle of cpuset cgroup directories. This includes keeping the "shared" cpuset cgroup's `cpuset.cpus` synced.

Reserved Cores [3/4]: Client cpuset cgroup managment

---

e2e/connect/client.go
e2e/consul/consul.go
e2e/consul/input/namespaces/connect_ingress.nomad
e2e/consul/input/namespaces/connect_sidecars.nomad
e2e/consul/input/namespaces/connect_terminating.nomad
e2e/consul/input/namespaces/script_checks_group.nomad
e2e/consul/input/namespaces/script_checks_task.nomad
e2e/consul/input/namespaces/services_group.nomad
e2e/consul/input/namespaces/services_task.nomad
e2e/consul/input/namespaces/template_kv.nomad
e2e/consul/namespaces.go
e2e/consul/namespaces_oss.go
e2e/consul/script_checks.go
e2e/consultemplate/consultemplate.go
e2e/e2eutil/allocs.go
e2e/e2eutil/consul.go
e2e/e2eutil/e2ejob.go
e2e/e2eutil/utils.go

This PR adds a set of tests to the Consul test suite for testing
Nomad OSS's behavior around setting Consul Namespace on groups,
which is to ignore the setting (as Consul Namespaces are currently
an Enterprise feature).
Tests are generally a reduced facsimile of existing tests, modified
to check behavior of when `group.consul.namespace` is set and not set.
Verification is oriented around what happens in Consul; the in-depth
functional correctness of these features is left to the original tests.
Nomad ENT will get its own version of these tests in `namespaces_ent.go`.
This is like part 1 of 4, where we also need Consul ACL version of this,
the Nomad ENT version, and the Nomad ENT + Consul ACLs.
Also need tests that test setting `--consul-namespace` on job run making
sure the setting …

e2e: add tests for consul namespaces from nomad oss

---

command/quota_init.go
command/quota_init_test.go
command/volume_init.go

Allow optional filename as an argument for `volume init` and `quote init` commands, to match `job init` behavior.
Updated tests to use testify as well.
Fixes #10198

cli: filename arg for `volume init` and `quote init`

---

client/allocrunner/taskrunner/task_runner_hooks.go

Similar to a bugfix made for the services hook, we need to always
set the script checks hook, in case a task is initially launched
without script checks, but then updated to include script checks.
The scipt checks hook is the thing that handles that new registration.

client: always set script checks hook

---

client/allocrunner/taskrunner/script_check_hook.go
command/agent/consul/service_client.go
e2e/consul/input/namespaces/connect_terminating.nomad
e2e/consul/input/namespaces/template_kv.nomad
e2e/consul/namespaces.go
nomad/consul.go
nomad/consul_test.go
nomad/job_endpoint.go
nomad/structs/connect.go
nomad/structs/consul_oss_test.go

(cherry-picked from ent, minus _ent stuff)
This is part 2/4 of e2e tests for Consul Namespaces. Took a
first pass at what the parameterized tests can look like, but
only on the ENT side for this PR. Will continue to refactor
in the next PRs.
Also fixes 2 bugs:
- Config Entries registered by Nomad Server on job registration
were not getting Namespace set
- Group level script checks were not getting Namespace set
Those changes will need to be copied back to Nomad OSS.
Nomad OSS + no ACLs (previously, needs refactor)
Nomad ENT + no ACLs (this)
Nomad OSS + ACLs (todo)
Nomad ENT + ALCs (todo)

cherry-pick fixes from cns ent tests

---

api/search_test.go
nomad/search_endpoint.go

Pulling in small change from https://github.com/hashicorp/nomad-enterprise/commit/7846fc9e8506bf78f4aca063031d04eb2618d0c1
that apply to the shared part of `search_endpoint.go`
Where we have the `ent` types referenced in a switch statement,
that are just not relevant in oss. Copying them here to prevent merge
diffs between oss/ent.

api: include ent fuzzy struct types in oss

---

command/agent/config.go
command/agent/config_test.go
website/content/docs/configuration/client.mdx

This adds go-sockaddr templating for the client.network_interface attribute. @lgfa29 helped me write the tests.
Closes #3675
Fixes #5498

Enable go-sockaddr templating for `network-interface`

---

nomad/drainer/drainer.go
nomad/drainer_int_test.go
nomad/structs/structs.go

This fixes a bug affecting drain nodes, where allocs may fail to be
migrated if they belong to different namespaces but share the same job
name.
The reason is that the helper function that creates the migration evals
indexed the allocs by job ID without accounting for the namespaces.
When job ids clash, only an eval is created for one and the rest of the
allocs remain intact.
I've added the test first, so the failure can be seen in https://app.circleci.com/pipelines/github/hashicorp/nomad/15799/workflows/383e0ec3-0803-4751-ba8f-862461d12741/jobs/151142 .
Fixes #10172

Migrate all allocs when draining a node

---

jobspec2/parse_test.go
jobspec2/types.config.go

This fixes a regression in https://github.com/hashicorp/nomad/pull/10326, to handle unquoted unknown variables.
The HCL job may contain unquoted undefined variable references without `${...}` wrapping, e.g. `value = meta.node_class`. In 1.0.4, this got parsed as `value = "${meta.node_class}"`.
This code performs a scan to find the relevant `${` and `}`, and only tries to find the closest ones with whitespace as the only separator.

hcl2: handle unquoted undefined variables

---

website/content/api-docs/search.mdx
website/content/docs/configuration/search.mdx

I noticed the scope headers weren’t all the same and chose to make them `####` as they’re nested beneath a `###`.
I also added a missing `a` 🤓

docs: Fix minor fuzzy search things

---

command/agent/job_endpoint.go
command/agent/job_endpoint_test.go

ParentID is an internal field that Nomad sets for dispatched or parameterized jobs. Job submitters should not be able to set it
directly, as that messes up children tracking.
Fixes #10422 . It specifically stops the scheduler from honoring the ParentID.  The reason failure and why the scheduler didn't schedule that job once it was created is very interesting and requires follow up with a more technical issue.

api: Ignore User provided ParentID

---

nomad/job_endpoint.go
nomad/job_endpoint_test.go
nomad/structs/structs.go

Add Namespace as a top-level field in `/v1/jobs` stub.
The `/v1/jobs` endpoint already includes the namespace under `JobSummary`, though the API is odd, as typically the job ID and Namespace are in the same level, and the oddity complicates the UI frontend development.
The downside of adding it is redundant field, that makes the response body a bit bigger, specially for clusters with large jobs. Though, it should compress nicely and I expect the overhead to be small to overall response size. The benefit of a cleaner and more consistent API seem worth it.
<details>
<summary>Sample /v1/api response before</summary>
```json
[
{
"CreateIndex": 10,
"Datacenters": [
"dc1"
],
"ID": "example",
"JobModifyIndex": 10,
"JobSummary": {
"Children": {
"Dead": 0,
"Pending": 0,
"Running": 0
}, …
```

api: /v1/jobs always include namespaces

---

CHANGELOG.md
client/allocrunner/taskrunner/envoy_bootstrap_hook.go
client/allocrunner/taskrunner/envoy_bootstrap_hook_test.go
helper/exptime/LICENSE.md
helper/exptime/backoff.go

This PR wraps the use of the consul envoy bootstrap command in
an expoenential backoff closure, configured to timeout after 60
seconds. This is an increase over the current behavior of making
3 attempts over 6 seconds.
Should help with #10451

connect: use exp backoff when waiting on consul envoy bootstrap

---

CHANGELOG.md
nomad/job_endpoint_hook_connect.go
nomad/job_endpoint_hook_connect_test.go

This PR adds job-submission validation that checks for the use of uppercase characters
in group and service names for services that make use of Consul Connect. This prevents
attempting to launch services that Consul will not validate correctly, which in turn
causes tasks to fail to launch in Nomad.
Underlying Consul issue: https://github.com/hashicorp/consul/issues/6765
Closes #7581 #10450

consul/connect: check connect group and service names for uppercase characters

---

CHANGELOG.md
nomad/structs/services.go
nomad/structs/services_test.go

This PR fixes a bug where Nomad was more restrictive on Ingress Gateway Configuration
Entry definitions than Consul. Before, Nomad would not allow for declaring IGCEs with
http listeners with service name "*", which is a [special feature](https://www.consul.io/docs/connect/config-entries/ingress-gateway#hosts) enabled by Consul.
Note: to make http protocol work, a `service-default` must be defined setting the
`protocol` to `http` for each service. (Setting `protocol` on the service definition in Consul is not possible)
Fixes: https://github.com/hashicorp/nomad/issues/9729

consul/connect: fix bug where ingress gateways could not use wildcard services

---

website/content/docs/internals/filesystem.mdx

The file had "read the the" but it should have been "read by the"

Fix "read the the" typo in filesystem.mdx file

---

command/agent/consul/acl_testing.go
e2e/connect/acls.go
e2e/connect/connect.go
e2e/consul/namespaces.go
e2e/consulacls/nomad-client-policy.hcl
e2e/consulacls/nomad-server-policy.hcl
e2e/e2eutil/consul.go
nomad/consul.go
nomad/consul_policy.go
nomad/consul_policy_test.go
nomad/consul_test.go

~(hold until ent half goes in - making sure oss CI still works)~
This PR cherry-picks changes made for ENT testing of Consul Namespaces with ACLs enabled.

e2e: add e2e tests for consul namespaces on ent with acls

---

command/license.go
command/license_get.go

This changeset includes two small tweaks:
* In https://github.com/hashicorp/nomad/pull/10458 I missed porting over the updates to `license_get.go`
* Remove the deprecated `Terminates At` field from the command output so that it's not confusing to operators.

License get command updates

---

api/allocations.go
nomad/blocked_evals.go
nomad/blocked_evals_stats.go
nomad/blocked_evals_stats_test.go
nomad/blocked_evals_test.go
nomad/mock/mock.go
nomad/structs/structs.go
scheduler/generic_sched.go
scheduler/system_sched.go
vendor/github.com/hashicorp/nomad/api/allocations.go
website/content/docs/operations/metrics.mdx

When an eval is blocked, it's often because of insufficient resources available. Nomad currently tracks now many evals are blocked, but it has not indication of how much resource is required to unblock them, or how where they are assigned to run.
This PR adds a new set of metrics that emit how much resource have been requested by blocked evals. The metrics are split into jobs, datacenters and node classes.
If a job spans multiple datacenters or node classes, they will all be updated, since adding more resources to any of them would be enough to unblock the eval.
This metric is emitted by the leader, since it is the only node in the cluster that has the proper scheduling information.
Missing work:

Add metrics for blocked eval resources

---

nomad/job_endpoint.go
nomad/job_endpoint_hooks.go
nomad/job_endpoint_test.go
nomad/structs/operator.go
scheduler/generic_sched_test.go
scheduler/preemption_test.go
scheduler/rank.go
scheduler/rank_test.go
scheduler/stack.go

Cluster operators want to have better constrol over memory
oversubscription and may want to enable/disable it based on their
experience.
This PR adds a scheduler configuration field to control memory
oversubscription. It's additional field that can be set in the [API via Scheduler Config](https://www.nomadproject.io/api-docs/operator/scheduler), or [the agent server config](https://www.nomadproject.io/docs/configuration/server#configuring-scheduler-config).
I opted to have the memory oversubscription be an opt-in, but happy to change it.  To enable it, operators should call the API with:
```json
{
"MemoryOversubscriptionEnabled": true
}
```
If memory oversubscription is disabled, submitting jobs specifying `memory_max` will get a "Memory oversubscription is not
enabled" warnings, but the …

Allow configuring memory oversubscription

---

ui/mirage/config.js

Similarly to [735f056](https://github.com/hashicorp/nomad/pull/10444/commits/735f0560f152f9580da2c035198f78483d4d35ed), this won’t happen with real data,
but can happen in the current Mirage factory setup.

ui: Add guard against missing namespace in Mirage

---

website/content/api-docs/operator/license.mdx

This got missed in https://github.com/hashicorp/nomad/pull/10463

docs: remove API doc for license PUT

---

website/content/docs/job-specification/artifact.mdx

when troubleshooting it is better if this command will actually work (pointing to a real repository)

suggestion for git example - provide a real repo

---

website/content/docs/commands/index.mdx

Fixes https://github.com/hashicorp/nomad/issues/9967
Adding a single home with a list of environment variables that the `nomad` command uses.
🔍 [Preview Link](https://nomad-f3d4r5h6x-hashicorp.vercel.app/docs/commands#environment-variables)

Docs - Add environment variables to Command>Overview page.

---

CHANGELOG.md
nomad/job_endpoint_hook_expose_check.go
nomad/job_endpoint_hook_expose_check_test.go

This PR uses the hash of the check for which a dynamic exposed
port is being generated (instead of a UUID prefix) so that the
generated port label is deterministic.
This fixes 2 bugs:
- `job plan` output is now regular for jobs making use of exposed checks
- tasks will no longer be destructively updated when jobs making use of
exposed checks are re-run without changing any user specified part of
the job
Closes: https://github.com/hashicorp/nomad/issues/10099

connect: use deterministic injected dynamic exposed port label

---

drivers/docker/utils.go

Fixes https://github.com/hashicorp/nomad/issues/10480
The error returned from the stdlib's `exec` package is always a message with
the exit code of the exec'd process, not any error message that process might
have given us. This results in opaque failures for the Nomad user. Cast to an
`ExitError` so that we can access the output from stderr.
cc'ing @isabeldepapel @jsosulska b/c they shadowed on the issue triage for this one.

docker: improve error message for auth helper

---

ui/app/components/primary-metric/allocation.hbs
ui/app/components/primary-metric/allocation.js
ui/tests/acceptance/topology-test.js
ui/tests/pages/topology.js

This closes #10489. It adds `dependentKeyCompat` to the allocation getter so it works
as expected as a dependent key for the `tracker` computed property, as described [here](https://guides.emberjs.com/release/upgrading/current-edition/tracked-properties/#toc_backwards-compatibility):
> Note, however, that if you want to use a getter as a dependent key, you will need to use the `dependentKeyCompat` decorator. This allows you to refactor existing computed properties into getters without breaking existing code that observes them.
From the [documentation](https://api.emberjs.com/ember/release/functions/@ember%2Fobject%2Fcompat/dependentKeyCompat):
> In general, only properties which you _expect_ to be watched by older, untracked clases should be marked as dependency compatible. The decorator …

ui: Fix bug where switching topo viz allocation highlights doesn’t update charts

---

client/allocrunner/taskrunner/lifecycle.go
client/allocrunner/taskrunner/task_runner.go
client/allocrunner/taskrunner/task_runner_test.go

This PR ensures Nomad captures the task code more reliably even when the task is killed. This issue affect to `raw_exec` driver, as noted in https://github.com/hashicorp/nomad/issues/10430 .
We fix this issue by ensuring that the TaskRunner only calls `driver.WaitTask` once. The TaskRunner monitors the completion of the task by calling `driver.WaitTask` which should return the task exit code on completion. However, it also could return a "context canceled" error if the agent/executor is shutdown.
Previously, when a task is to be stopped, the killTask path makes two WaitTask calls, and the second returns "context canceled" occasionally because of a "race" in task shutting down and depending on driver, and how fast it shuts down after task completes.
By having a single WaitTask call and …

drivers: Capture exit code when task is killed

---

command/alloc_status.go
website/content/docs/configuration/client.mdx
website/content/docs/job-specification/resources.mdx

This PR adds some minor docs for the new `cores` resource field as well as updating the output of `nomad alloc status` to include the number of reserved cores if specified.

minor docs and cli update for reserved cores

---

client/taskenv/env.go
client/taskenv/env_test.go
website/content/docs/runtime/environment.mdx
website/content/partials/envvars.mdx

Follow up to memory oversubscription - expose an env-var to indicate when memory oversubscription is enabled and what the limit is.
This will be helpful for setting hints to app for memory management.

expose NOMAD_MEMORY_MAX_LIMIT env var

---

website/content/docs/configuration/consul.mdx

We already supported this configuration, but forgot to document it.
Closes #10512

docs: add agent consul grpc_address docs

---

CHANGELOG.md
api/event_stream_test.go
api/nodes.go
api/nodes_test.go
command/agent/node_endpoint.go
command/agent/node_endpoint_test.go
command/node_drain.go
nomad/drainer/watch_nodes_test.go
nomad/fsm.go
nomad/node_endpoint.go
nomad/node_endpoint_test.go
nomad/state/events_test.go
nomad/state/state_store.go
nomad/state/state_store_test.go
nomad/structs/structs.go
vendor/github.com/hashicorp/nomad/api/nodes.go
website/content/api-docs/nodes.mdx
website/content/docs/commands/node/drain.mdx

resolves #9928 
This persists information about the last "drain operation" in a new `Node.LastDrain` field. A "drain operation" begins when the node begins draining, and ends when the drain is complete or canceled. A new drain operation will overwrite any existing `Node.LastDrain` field.
In addition to native metadata about the drain operation (start time, status, end time), operators can provide additional key/value pairs about the drain operation:
* API: via the `.Meta` field in the drain payload
* CLI: via the `-meta` flag or the `-m` git-style shortcut (which is a shortcut for `Meta.message` or `Meta.cancel_message`, appropriately)
The work in this PR performs the following:
* a new field `LastDrain` in `structs.Node` and `api.Node`
* updates to the FSM and the state store to …

Node Drain Metadata

---

website/content/docs/autoscaling/plugins/strategy/threshold.mdx
website/data/docs-nav-data.json

Documentation for the new autoscaling `threshold` strategy. 
This PR targets `docs-restructure-autoscaling-plugin` to facilitate the review process. 
It should be merged before #10534.

docs: add autoscaling threshold strategy

---

website/content/docs/job-specification/group.mdx
website/content/docs/job-specification/job.mdx
website/content/docs/job-specification/update.mdx

Fixes #10542
I have tried to clarify that a default update strategy is used if no update strategy is specified, see issue above. I'm not very familiar with Nomad, so could be very well that I missed something.
I believe this change in behaviour was introduced in https://github.com/hashicorp/nomad/pull/6191

docs: clarify that a default update strategy is used when update strategy is omitted

---

website/content/docs/upgrade/upgrade-specific.mdx

Adding some details to the 1.1 upgrade guide regarding the licensing changes.
If this goes into too much detail here let me know, but it feels like the most prominent location to share this info.

docs: add detail to 1.1 upgrade guide for licensing

---

e2e/README.md
e2e/terraform/README.md
e2e/terraform/terraform.full.tfvars
e2e/terraform/terraform.tfvars
e2e/terraform/variables.tf

The `nomad_sha` variable for E2E runs can only be used by the nightly E2E run and not by developers who are running E2E from Terraform directly. Remove these references from the documentation so that they're not misled.

E2E: remove references to nomad_sha

---

CHANGELOG.md
drivers/docker/config.go
drivers/docker/driver.go
drivers/docker/driver_default.go
drivers/docker/driver_test.go
drivers/shared/executor/executor.go
drivers/shared/executor/executor_linux.go
drivers/shared/executor/executor_linux_test.go
website/content/docs/upgrade/upgrade-specific.mdx

The default Linux Capabilities set enabled by the docker, exec, and
java task drivers includes CAP_NET_RAW (for making ping just work),
which has the side affect of opening an ARP DoS/MiTM attack between
tasks using bridge networking on the same host network.
https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities
This PR disables CAP_NET_RAW for the docker, exec, and java task
drivers. The previous behavior can be restored for docker using the
allow_caps docker plugin configuration option.
A future version of nomad will enable similar configurability for the
exec and java task drivers.

drivers/docker+exec+java: disable net_raw capability by default

---

website/content/docs/commands/volume/create.mdx

The `capacity` block was removed during implementation in lieu of the
`capacity_max` and `capacity_min` fields, but it wasn't removed from the
example in the documentation.

docs: fix fields in 'volume create' example

---

ui/app/models/agent.js
ui/app/utils/format-host.js
ui/mirage/config.js
ui/mirage/factories/agent.js
ui/tests/acceptance/allocation-detail-test.js
ui/tests/acceptance/server-detail-test.js
ui/tests/acceptance/servers-list-test.js

This closes #10513, thanks to @bastelfreak for the report.
`GET /status/leader` returns an IPv6 host with square brackets
around the IP address as expected, but the `rpcAddr` property
on the agent model does not.
This fixes `rpcAddr`, updates the Mirage `/status/leader` mock
to properly format an IPv6 host, and changes the agent
factory to sometimes produce IPv6 addresses.
I added a `formatHost` utility function to centralise the
conditional square bracket-wrapping that would have
otherwise been further scattered around.

ui: Fix server list leader determination for IPv6

---

website/content/docs/job-specification/resources.mdx

Add a section about memory oversubscription and caveats/recommendations operators should take into account.

add a section about memory oversubscription

---

client/alloc_endpoint.go
client/alloc_endpoint_test.go
client/client_test.go

This fixes three instances of multiple imports of the same package in `client`.

client: fix multiple imports

---

website/content/docs/job-specification/service.mdx

according to docs, `network` has to be under job > group

Docs: Update network to be under job group

---

e2e/terraform/.terraform.lock.hcl

Our lockfile for E2E is out of date, resulting in an error asking you to run `terraform init`. This changeset updates the lockfile (run with Terraform 0.15.3... not sure if that matters).

e2e: update TF lockfile

---

website/content/docs/enterprise/license.mdx

Added a link to the enterprise license tutorial and updated the trial link to use the recommended marketing url.

docs: update enterprise license page

---

website/content/docs/internals/architecture.mdx

Move the words being defined in the /docs/internal/architecture page to be
small headers so that they can be linked to with anchors from Learn guides and
other documentation location.
@jescalan per our discussion in chat I tried this with `###` first. But because those 
get a light underline, it opened up the space way too much and looked terrible. This
looks nicer to me?

docs: ensure definitions have anchors

---

CHANGELOG.md
command/quota_status.go

Handle when MemoryMaxMB is nil, as expected when a new 1.1.0 is hitting a pre-1.1.0 Server.
With this change, we sill still display `Memory Max Usage` column, though it's not meaningful:
```
$ nomad namespace status default
Name        = default
Description = Default shared namespace
Quota       = default-quota
Quota Limits
Region  CPU Usage   Memory Usage  Memory Max Usage  Network Usage
global  500 / 2500  256 / 1000    0 / -             - / inf
```
Fixes https://github.com/hashicorp/nomad/issues/10619

cli: Handle nil MemoryMaxMB

---

website/content/docs/commands/volume/index.mdx

Adds some commands from Nomad 1.1 that are missing from the overview page.

Add new volume commands to overview page

---

CHANGELOG.md
nomad/stream/ndjson.go
nomad/stream/ndjson_test.go

Fixes #10636 
Fixed it in the API instead of the client because it probably affects all HTTP clients waiting for any response (at least HTTP headers) before returning the HTTP body to the caller. Sending an initial heartbeat shouldn't do any harm because it should already be handled by all event stream clients.

events: fix slow client connection to empty event stream

---

website/content/docs/commands/volume/create.mdx

Volume creation doesn't support the context (this would only be used for register)

Removed unsupported options from volume create

---

nomad/event_endpoint_test.go

#10637 added initial heartbeat functionality to events and it
seems when this PR was raised, the Nomad CI provider was having
availability issues meaning the test suite was not correctly run,
thus allowing broken tests into main. The PR itself exercised test
code which had not been hit before.
The particular problem is when identifying whether the event
received is a heartbeat; this was performed using standard Golang
conditionals. Unfortunately the operator == is not defined on byte
arrays, resulting in the check always returning false. To overcome
this issue the code now uses the bytes.Equal function to correctly
compare the data.

events: fix event endpoint tests to ignore heartbeats.

---

client/pluginmanager/csimanager/volume.go
client/structs/csi.go
nomad/csi_endpoint.go
plugins/csi/plugin.go

Include the VolumeCapability.MountVolume data in
ControllerPublishVolume, CreateVolume, and ValidateVolumeCapabilities
RPCs sent to the CSI controller. The previous behavior was to only
include the MountVolume capability in the NodeStageVolume request, which
on some CSI implementations would be rejected since the Volume was not
originally provisioned with the specific mount capabilities requested.

CSI: Include MountOptions in capabilities sent to CSI for all RPCs

---

CHANGELOG.md
website/content/docs/commands/volume/create.mdx
website/content/docs/commands/volume/register.mdx

Adds clarification to `nomad volume create` commands around how the `volume`
block in the jobspec overrides this behavior. Adds missing section to `nomad
volume register` and to example volume spec for both commands.
Also add a changelog entry for https://github.com/hashicorp/nomad/pull/10643
Preview links:
https://nomad-jyqbf335s-hashicorp.vercel.app/docs/commands/volume/create#mount_options
https://nomad-jyqbf335s-hashicorp.vercel.app/docs/commands/volume/register#mount_options

docs: improve documentation for CSI create/register mount_options

---

CHANGELOG.md
command/job_deployments.go
command/job_history.go
command/job_inspect.go
command/job_promote.go
command/job_revert.go
command/job_status.go
command/job_stop.go

Fixes https://github.com/hashicorp/nomad/issues/10625
When a wildcard namespace is used for `nomad job` commands that support prefix
matching, avoid asking the user for input if a prefix is an unambiguous exact
match so that the behavior is similar to the commands using a specific or
unset namespace.

cli: improve wildcard namespace prefix matches

---

CHANGELOG.md
command/volume_delete.go
command/volume_deregister.go

Display confirmation message on 'nomad volume delete' and 'nomad volume deregister'

---

e2e/terraform/README.md
e2e/terraform/nomad.tf
e2e/terraform/packer/build
e2e/terraform/packer/ubuntu-bionic-amd64/provision.sh
e2e/terraform/packer/windows-2016-amd64/provision.ps1
e2e/terraform/provision-nomad/main.tf
e2e/terraform/provision-nomad/variables.tf
e2e/terraform/terraform.tfvars
e2e/terraform/variables.tf

Ease spinning up a cluster, where binaries are fetched from arbitrary urls.  These could be CircleCI `build-binaries` job artifacts, or presigned S3 urls.

e2e: Spin clusters with custom url binaries

---

api/allocations.go
api/allocations_exec.go
command/agent/alloc_endpoint.go
e2e/nomadexec/exec.go
vendor/github.com/hashicorp/nomad/api/allocations.go
vendor/github.com/hashicorp/nomad/api/allocations_exec.go

Ensure that websocket channels are closed gracefully and that exit codes are properly captured, to avoid the spurious "unexpected EOF" failures even when command completes successfully.
Examining the paths, there are two bugs contributing to the cause.
First, the http handler that bridge the internal streaming RPC to websocket connection had a goroutine that could returned early before emitting the `websocket.CloseNormalClosure` message.
Second, on the api consumer side, if we got an "unexpected EOF" error, the api may prioritize handling it before emitting the last output or exit code. In theory, we can safely ignore any error occurring after receiving the exit code message, as the exit code message is the last message.
In this PR, we fix the goroutine early termination, and ensure that …

Handle `nomad exec` termination events in order

---

command/volume_snapshot_list.go

CSI snapshot list: do not shorten snapshot ID

---

e2e/terraform/outputs.tf

Without `--raw` this command fails: 
```shellsession
$ $(terraform output environment)
zsh: command not found: <<EOT
```

e2e: fix terraform output environment command instruction

---

nomad/leader.go

Arguments to our logger's various write methods are evaluated eagerly, so method calls in log parameters will always be called, regardless of log level. Move some logger messages to the logger's `Fmt` method so that `GoString` is evaluated lazily instead.
Noticed this while working on an unrelated bug, where it'll matter more as it's in a hot code path. Realistically if we're on this code path we're going to evaluate these anyways because our worst log level is `warn`, but given that we have a habit of copy-and-pasting code around it's better to "always do it right". 
https://play.golang.org/p/azP_04QmQGY gives a demonstration of how the lazy evaluation works out.

leader: call argument eval for log formatting lazily

---

nomad/plan_apply.go
nomad/structs/structs.go

The plans generated by the scheduler produce high-level output of counts on each
evaluation, but when debugging scheduler issues it'd be nice to have a more
detailed view of the resulting plan. Emitting this log at trace minimizes the
overhead, and producing it in the plan applier makes it easier to find as it
will always be on the leader.
---
Example output:
> 2021-05-27T17:40:19.333Z [TRACE]  nomad: evaluating plan: plan="(eval d3f3e9c7, job example, deploy bbb91268, NodeUpdates: (node[dde41025] (1dd4b77f stop/evict)), NodeAllocations: (node[dde41025] (48240cba example.cache[0] run) (ef9f052e example.cache[2] run)))"

plan applier: add trace-level log of plan

---

website/content/docs/job-specification/service.mdx

An internal support request showed that the wording here was misleading. Make the default behavior explicit in the docs.

docs: clarify default `check.initial_status` behavior

---

drivers/shared/executor/executor_linux.go
drivers/shared/executor/executor_linux_test.go

Explicitly set the `oom_score_adj` value for `exec` and `java` tasks.
We recommend that the Nomad service to have oom_score_adj of a low value
(e.g. -1000) to avoid having nomad agent OOM Killed if the node is
oversubscriped.
However, Nomad's workloads should not inherit Nomad's process, which is
the default behavior.
Added a failed test first that you can see in https://app.circleci.com/pipelines/github/hashicorp/nomad/16419/workflows/2c6fee1f-13c5-4d8b-99c2-75bce52bb949/jobs/158264 .
Fixes #10663

drivers/exec: Don't inherit Nomad oom_score_adj value

---

CHANGELOG.md
nomad/job_endpoint_test.go
nomad/structs/structs_test.go
nomad/structs/volumes.go

Fixes https://github.com/hashicorp/nomad/issues/10645
The `attachment_mode` and `access_mode` fields are required for CSI
volumes. The `mount_options` block is only allowed for CSI volumes.

csi: validate `volume` block has `attachment_mode` and `access_mode`

---

CHANGELOG.md
client/csi_endpoint_test.go
client/structs/csi.go
nomad/csi_endpoint.go
plugins/csi/client_test.go
plugins/csi/plugin.go

Fixes https://github.com/hashicorp/nomad/issues/10626
When `nomad volume create` was introduced in Nomad 1.1.0, we changed the volume spec to take a list of capabilities rather than a single capability, to meet the requirements of the CSI spec. When a volume is registered via `nomad volume register`, we should be using the same fields to validate the volume with the controller plugin.

CSI: accept list of caps during validation in volume register

---

CHANGELOG.md
nomad/job_endpoint_hook_connect.go
nomad/job_endpoint_hook_connect_test.go
nomad/structs/structs.go

This PR adds two additional constraints on Connect sidecar and gateway tasks,
making sure Nomad schedules them only onto nodes where Connect is actually
enabled on the Consul agent.
Consul requires `connect.enabled = true` and `ports.grpc = <number>` to be
explicitly set on agent configuration before Connect APIs will work. Until
now, Nomad would only validate a minimum version of Consul, which would cause
confusion for users who try to run Connect tasks on nodes where Consul is not
yet sufficiently configured. These contstraints prevent job scheduling on nodes
where Connect is not actually use-able.
Closes #10700

consul/connect: use additional constraints in scheduling connect tasks

---

api/services.go
api/services_test.go
client/allocrunner/taskrunner/envoy_bootstrap_hook.go
client/allocrunner/taskrunner/envoy_bootstrap_hook_test.go
command/agent/consul/connect.go
command/agent/consul/connect_test.go
command/agent/consul/service_client.go
command/agent/job_endpoint.go
command/agent/job_endpoint_test.go
helper/envoy/envoy.go
helper/envoy/envoy_test.go
nomad/job_endpoint_hook_connect.go
nomad/job_endpoint_hook_connect_test.go
nomad/mock/mock.go
nomad/structs/connect_test.go
nomad/structs/diff.go
nomad/structs/diff_test.go
nomad/structs/services.go
nomad/structs/services_test.go
nomad/structs/structs.go
vendor/github.com/hashicorp/nomad/api/services.go
website/content/docs/job-specification/gateway.mdx
website/content/docs/job-specification/upstreams.mdx

This PR implements first-class support for Nomad running Consul
Connect Mesh Gateways. Mesh gateways enable services in the Connect
mesh to make cross-DC connections via gateways, where each datacenter
may not have full node inter-connectivity.
Note: in this context "datacenter" means _Consul_ datacenter.
Consul docs with more information:
https://www.consul.io/docs/connect/gateways/mesh-gateway
The following group level service block can be used to establish
a Connect mesh gateway.
```hcl
service {
connect {
gateway {
mesh {
// no configuration
}
}
}
}
```
Services can make use of a mesh gateway by configuring so in their
upstream blocks, e.g.
```hcl
service {
connect {
sidecar_service {
proxy {
upstreams {
destination_name = "<service>"
local_bind_port  = <port>
datacenter       = …
```

consul/connect: add support for connect mesh gateways

---

e2e/terraform/.terraform.lock.hcl
e2e/terraform/network.tf
e2e/terraform/nomad.tf
e2e/terraform/packer/ubuntu-bionic-amd64/provision.sh
e2e/terraform/variables.tf

Tweaks to the terraform scripts, mainly so that we restrict ingress traffic by default to the host invoking the terraform apply. Useful as a basic security control for our e2e infrastructure as well as dev clusters. Dev clusters are typically accessed from a single host, the developers account, and they can change the security groups after creation.
Also, some fixes for handling `nomad_url`.

e2e terraform tweaks: 2021-06 edition

---

CHANGELOG.md
command/agent/agent.go
command/agent/command.go
command/agent/config.go
nomad/config.go
nomad/server.go

Make it configurable for users to say how many statestore queries deployments can happen simultaneously. For the use case of huge deployment loads.

deployment query rate limit

---

CHANGELOG.md
command/agent/agent.go
command/agent/config.go
nomad/config.go
nomad/server.go

Backport of #10706 against 1.0.2

deployment query rate limit (#10706)

---

client/rpc.go
helper/pool/pool.go
helper/pool/pool_test.go

Track usage of incoming streams on a connection. Connections without
reference counts get marked as unused and reaped in a periodic job.
This fixes a bug where `alloc exec` and `alloc fs` sessions get terminated
unexpectedly. Previously, when a client heartbeats switches between
servers, the pool connection reaper eventually identifies the connection
as unused and closes it even if it has an active exec/fs sessions.
I've tested this code in a live cluster, and had an `alloc exec` command session almost 3 hours before I killed it. Without the change, an `alloc exec` session used to last around 7-20 minutes or so.
Fixes #10579

pool: track usage of incoming streams

---

CHANGELOG.md
ui/app/components/global-search/control.js
ui/tests/acceptance/search-test.js

Fixed global-search keyboard shortcut for non-english keyboard layouts.

---

CHANGELOG.md

https://github.com/hashicorp/nomad/pull/10714 impacts pre-1.1.0, so it's getting backported.

changelog for backporting #10714

---

CHANGELOG.md
client/allocrunner/groupservice_hook_test.go
client/allocrunner/taskrunner/connect_native_hook_test.go
client/allocrunner/taskrunner/envoy_bootstrap_hook_test.go
client/allocrunner/taskrunner/task_runner_test.go
client/fingerprint/consul.go
client/fingerprint/consul_test.go
command/agent/agent.go
command/agent/consul/catalog_testing.go
command/agent/consul/check_watcher_test.go
command/agent/consul/connect_proxies_test.go
command/agent/consul/group_test.go
command/agent/consul/int_test.go
command/agent/consul/namespaces_client.go
command/agent/consul/namespaces_client_test.go
command/agent/consul/self.go
command/agent/consul/self_test.go
command/agent/consul/service_client_test.go
command/agent/consul/unit_test.go

This PR changes Nomad's wrapper around the Consul NamespaceAPI so that
it will detect if the Consul Namespaces feature is enabled before making
a request to the Namespaces API. Namespaces are not enabled in Consul OSS,
and require a suitable license to be used with Consul ENT.
Previously Nomad would check for a 404 status code when makeing a request
to the Namespaces API to "detect" if Consul OSS was being used. This does
not work for Consul ENT with Namespaces disabled, which returns a 500.
Now we avoid requesting the namespace API altogether if Consul is detected
to be the OSS sku, or if the Namespaces feature is not licensed. Since
Consul can be upgraded from OSS to ENT, or a new license applied, we cache
the value for 1 minute, refreshing on demand if expired.
Fixes …

consul: probe consul namespace feature before using namespace api

---

website/content/docs/drivers/docker.mdx

This warning comes out of https://github.com/hashicorp/nomad/issues/8900 and other issues where the correct configuration for `network_mode` of Connect-enabled `docker` driver tasks is a little unclear.

docs: warn not to set `network_mode` for Connect-enabled Docker task

---

e2e/terraform/network.tf

ipv4.icanhazip.com returns ipv6 addresses
```
$ curl ipv4.icanhazip.com
2601:1c2:1a80:xxxx:xxxx:xxxx:xxxx:xxxx
$ curl https://api.ipify.org
73.xxx.xxx.xxx
```

e2e: use api.ipify.org

---

website/content/docs/operations/metrics.mdx

Old description of `{plan,worker}.wait_for_index` described the metric
in terms of waiting for a snapshot which has two problems:
1. "Snapshot" is an overloaded term in Nomad and operators can't be
expected to know which use we're referring to here.
2. The most important thing about the metric is what we're waiting *on*
before taking a snapshot: the raft index of the object to be
processed (plan or eval).
The new description tries to cram all of that context into the tiny
space provided.
See #5791 for details about the `wait_for_index` mechanism in general.

docs: improve wait_for_index metrics description

---

drivers/docker/driver_linux.go

This PR fixes an edge case in the reserved cores feature where switching the cpuset of a docker container occurs after the container has exited.

driver/docker: ignore error if container exists before cgroup can be written

---

command/agent/consul/acl_testing.go
nomad/consul_policy_oss_test.go

(cherry-pick ent back to oss)
This PR moves a lot of Consul ACL token validation tests into ent files,
so that we can verify correct behavior difference between OSS and ENT
Nomad versions.

consul: move consul acl tests into ent files

---

CHANGELOG.md
drivers/docker/driver_linux.go

Follow up for GH-10416 .
Should have pushed this to the original PR, but realized that the PR doesn't need backporting to 1.0.X only after merging the PR.

B cores docker followup

---

.circleci/config.yml
CHANGELOG.md
contributing/README.md
nomad/event_endpoint_test.go
scripts/release/mac-remote-build
scripts/vagrant-linux-priv-go.sh

The golang 1.15 line contains many fixes since 1.15.6: https://golang.org/doc/devel/release#go1.15 .

1.0.7: update golang to latest 1.15 point release

---

nomad/types/types.go

```
~/go/src/github.com/hashicorp/nomad main  ag PeriodicCallback                                                                                ✔  4s  15:53:10
nomad/types/types.go
3:type PeriodicCallback func() error
```
I also checked the enterprise code and got the same result.

core: remove unused types pkg and PeriodicCallback type.

---

client/client.go
nomad/autopilot_test.go
nomad/client_agent_endpoint_test.go
nomad/leader_test.go
nomad/serf_test.go
nomad/testing.go

Best reviewed commit-by-commit. The commit messages have more info.
Deflake tests that I examined part of https://github.com/hashicorp/nomad/issues/10437. After examining the tests, I believe now that the test failures were due to improper handling.
One common source of flakiness is tests not waiting for clients to be properly registered with servers. The leadership transition isn't the cause of failure there, but simply highlight the issue further. Some tests were blocking only until the nomad client fingerprinted, and others waited until network connection to server got established but not necessary that the node info got committed. I addressed the issue in the tests that flaked the most in my sample. I anticipate having another round of deflakiness due to this type of bug.

Deflaking Test 2021 June edition

---

nomad/deploymentwatcher/deployments_watcher_test.go

<details>
<summary>Data race stack trace</summary>
```
==================
Read at 0x00c0003fd740 by goroutine 17:
github.com/hashicorp/nomad/nomad/deploymentwatcher.TestWatcher_AutoPromoteDeployment.func2()
/Users/jrasell/go/src/github.com/hashicorp/nomad/nomad/deploymentwatcher/deployments_watcher_test.go:617 +0x6c
2021-06-11T11:26:00.889+0200 [TRACE] deploymentwatcher/deployment_watcher.go:481: deployments_watcher: resetting deadline: deployment_id=f7406e82-ac4b-aed9-f16e-9c673e5b4300 job="<ns: "default", id: "mock-service-2e0bcb57-df41-52e4-d528-370d30ad3bdb">"
github.com/hashicorp/nomad/testutil.WaitForResultRetries()
/Users/jrasell/go/src/github.com/hashicorp/nomad/testutil/wait.go:27 +0x5a
github.com/hashicorp/nomad/testutil.WaitForResult() …
```

deploymentwatcher: fix test data race.

---

command/agent_info.go

Small formatting fix in the `nomad agent-info` help message.

Fix agent-info help message formatting

---

website/pages/home/index.jsx

Patch up a 404 on an image that appears on the homepage CaseStudyCarousel.
[🔍 Preview](https://nomad-8isly8xf5-hashicorp.vercel.app/)
Fixes #10749

Fix headshot image 404

---

CHANGELOG.md
scheduler/stack.go

The `QuotaIterator` is used as the source of nodes passed into feasibility
checking for constraints. Every node that passes the quota check counts the
allocation resources agains the quota, and as a result we count nodes which
will be later filtered out by constraints. Therefore for jobs with
constraints, nodes that are feasibility checked but fail have been counted
against quotas. This failure mode is order dependent; if all the unfiltered
nodes happen to be quota checked first, everything works as expected.
This changeset moves the `QuotaIterator` to happen last among all feasibility
checkers (but before ranking). The `QuotaIterator` will never receive filtered
nodes so it will calculate quotas correctly.
This PR is in OSS because it doesn't touch the `QuotaIterator` code in ENT. …

quotas: evaluate quota feasibility last in scheduler

---

nomad/job_endpoint_hook_connect.go
nomad/job_endpoint_hook_connect_test.go

PR https://github.com/hashicorp/nomad/pull/10702 added 2 new constraints
for connect jobs - one for Consul gRPC listener, and one for Connect being
enabled on Clients. Connect does not need to be enabled on clients, only
on Consul servers. Remove the extra constraint.
Discuss:
https://discuss.hashicorp.com/t/nomad-1-1-1-and-consul-connect-enabled-on-consul-clients/25295

consul/connect: remove unnecessary connect constraint on clients

---

nomad/deploymentwatcher/deployment_watcher.go

Fix deployment watchers to avoid creating unnecessary deployment watcher goroutines and blocking queries. `deploymentWatcher.getAllocsCh` creates a new goroutine that makes a blocking query to fetch updates of deployment allocs.
When operators submit a new or updated service job, Nomad create a new deployment by default. The deployment object controls how fast to place the allocations through [`max_parallel`](https://www.nomadproject.io/docs/job-specification/update#max_parallel) and health checks configurations.
The `scheduler` and `deploymentwatcher` package collaborate to achieve deployment logic: The scheduler only places the canaries and `max_parallel` allocations for a new deployment; the `deploymentwatcher` monitors for alloc progress and then enqueues a new evaluation whenever the …

deployment watcher: Reuse allocsCh if allocIndex remains the same

---

command/deployment_status.go
command/monitor.go
website/content/docs/commands/job/run.mdx

System and batch jobs don't create deployments, which means nomad tries
to monitor a non-existent deployment when it runs a job and ouputs an
error message. This adds a check to make sure a deployment exists before
monitoring.

cli: check deployment exists before monitoring

---

CHANGELOG.md
command/agent/job_endpoint.go
command/agent/job_endpoint_test.go

This PR fixes some job submission plumbing to make sure the Consul check parameters
- failure_before_critical
- success_before_passing
work with group-level services. They already work with task-level services. Took this opportunity to apply a `todo` refactoring to re-use common API->structs services copying helper. 
Fixes #10678

consul: make failures_before_critical and success_before_passing work with group services

---

drivers/java/driver.go
drivers/java/utils.go
drivers/java/utils_test.go

This PR improves the regular expression used for matching the java
version string, which varies a lot depending on the java vendor and
version.
These are the example strings we now test for
```
java version "1.7.0_80"
openjdk version "11.0.1" 2018-10-16
openjdk version "11.0.1" 2018-10-16
java version "1.6.0_36"
openjdk version "1.8.0_192"
openjdk 11.0.11 2021-04-20 LTS
```
The last one is a new test added on behalf of #6081, which is
still broken on today's CentOS 7 default JDK package.
```
openjdk 11.0.11 2021-04-20 LTS
OpenJDK Runtime Environment 18.9 (build 11.0.11+9-LTS)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.11+9-LTS, mixed mode, sharing)
```
```
==> Evaluation "21c6caf7" finished with status "complete" but failed to place all allocations:
Task Group "example" (failed to place 1 …
```

client/fingerprint/java: improve java version string regex matching

---

website/content/docs/job-specification/network.mdx

Fixes https://github.com/hashicorp/nomad/issues/10010
---
Per the discussion in https://github.com/hashicorp/nomad/issues/10010#issuecomment-780669549 this has worked fine for a quite a while but we forgot to remove the note. The other items in that comment were addressed in docs fixes in https://github.com/hashicorp/nomad/pull/10766 and https://github.com/hashicorp/nomad/pull/10724.
To demonstrate, run the following job on a machine with a second network named `"public"` configured:
<details><summary>jobspec</summary>
```hcl
datacenters = ["dc1"]
group "web" {
network {
mode = "bridge"
port "www" {
to           = 8001
host_network = "public"
}
}
task "httpd" {
config {
image   = "busybox:1"
command = "httpd"
args    = ["-v", "-f", "-p", "8001", "-h", …
```

docs: host_network does support Docker task port mapping

---

command/agent/consul/service_client.go
command/agent/consul/service_client_test.go

This PR fixes a bug where modifying the upstreams of a Connect sidecar proxy
would not result Consul applying the changes, unless an additional change to
the job would trigger a task replacement (thus replacing the service definition).
The fix is to check if upstreams have been modified between Nomad's view of the
sidecar service definition and the service definition for the sidecar that is
actually registered in Consul during service reconciliation. 
Fixes #8754

consul/connect: in-place update service definition when connect upstreams are modified

---

CHANGELOG.md
go.mod
go.sum
vendor/github.com/hashicorp/go-cleanhttp/cleanhttp.go
vendor/github.com/hashicorp/go-cleanhttp/go.mod
vendor/github.com/hashicorp/go-getter/client.go
vendor/github.com/hashicorp/go-getter/client_option_insecure.go
vendor/github.com/hashicorp/go-getter/detect_s3.go
vendor/github.com/hashicorp/go-getter/get_gcs.go
vendor/github.com/hashicorp/go-getter/get_http.go
vendor/github.com/hashicorp/go-getter/get_s3.go
vendor/github.com/hashicorp/go-getter/go.mod
vendor/github.com/hashicorp/go-getter/go.sum
vendor/modules.txt

Fixes https://github.com/hashicorp/nomad/issues/10438

deps: bump go-getter to 1.5.4

---

client/allocrunner/networking_cni_test.go

Running the `client/allocrunner` tests fail to compile on macOS because the
CNI test file depends on the CNI network configurator, which is in a
Linux-only file.
Without this patch, on macOS:
```
$ go test ./client/allocrunner
client/allocrunner/networking_cni_test.go:32:8: undefined: cniNetworkConfigurator
client/allocrunner/networking_cni_test.go:57:8: undefined: cniNetworkConfigurator
FAIL    github.com/hashicorp/nomad/client/allocrunner [build failed]
FAIL
```

tests: allocrunner CNI tests are Linux-only

---

command/agent/job_endpoint.go
e2e/e2eutil/job.go

15d39f0de - use `-detatch` mode when registering jobs with the CLI
57fdb8143 - only set task name for group service checks (broke in [refactoring](https://github.com/hashicorp/nomad/pull/10764/files))
No CL or BP needed, these happened after 1.1.1
Fixes https://github.com/hashicorp/nomad/issues/10781

e2e: fix a couple recent e2e bugs

---

command/alloc_fs.go

Resolves: #10786
Rub a bit of:
```go
if err != nil {
```
On `getRandomJobAlloc`. If the client returns an error, forward that error along, rather than the less helpful error about no job allocations existing.

Adds error handling for client error in getRandomJobAlloc.

---

CHANGELOG.md
nomad/job_endpoint_hook_connect.go
nomad/job_endpoint_hook_connect_test.go

This PR adds validation during job submission that Connect proxy upstreams
within a task group are using different listener address:port. Otherwise, a
duplicate envoy listener will be created and not be able to bind.
Perhaps one day Consul will have a way to consolidate envoys, but this is not that day.
Closes #7833

consul/connect: Validate uniqueness of Connect upstreams within task group

---

CHANGELOG.md
command/operator_debug.go
command/operator_debug_test.go
testutil/wait.go
testutil/wait_test.go

This PR adds to the remaining pprof profiles to `nomad operator debug`.  It also adds 2 helper functions `WaitForResultUntil` and `WaitForFilesUntil` which reduce the flakiness of the associated test.
* heap
* allocs
* threadcreate
* block
* mutex
In the future the `block` and `mutex` profiles can be enabled using the `runtime.SetBlockProfileRate` and `runtime.SetMutexProfileFraction` functions, respectively.

Add remaining pprof profiles to nomad operator debug

---

CHANGELOG.md
command/volume_status_csi.go

Fixes https://github.com/hashicorp/nomad/issues/10816
When the `-verbose` flag is passed to the `nomad volume status` command, we
hit a code path where the rows of text to be formatted were not initialized
correctly, resulting in a panic in the CLI.
This bug was introduced in 1.1.0 so no backport is required.

csi: fix CLI panic when formatting volume status with -verbose flag

---

CHANGELOG.md
website/content/docs/upgrade/upgrade-specific.mdx

Fixes https://github.com/hashicorp/nomad/issues/9710
The `docker` driver's `port_map` field was deprecated in 0.12 and this is
documented in the task driver's docs, but we never explicitly flagged it for
backwards compatibility.

docs: add missing backwards compat warning about port_map

---

CHANGELOG.md
website/content/docs/job-specification/network.mdx

Fixes https://github.com/hashicorp/nomad/issues/6958 and https://github.com/hashicorp/nomad/issues/9456

docs: unset port `to` field maps to dynamic port

---

CHANGELOG.md
client/allocrunner/taskrunner/connect_native_hook.go
client/allocrunner/taskrunner/connect_native_hook_test.go
website/content/partials/envvars.mdx

This PR makes it so that Nomad will automatically set the CONSUL_TLS_SERVER_NAME
environment variable for Connect native tasks running in bridge networking mode
where Consul has TLS enabled. Because of the use of a unix domain socket for
communicating with Consul when in bridge networking mode, the server name is
a file name instead of something compatible with the mTLS certificate Consul
will authenticate against. "localhost" is by default a compatible name, so Nomad
will set the environment variable to that.
Fixes #10804

consul/connect: automatically set consul tls sni name for connect native tasks

---

website/content/docs/drivers/docker.mdx

Fix missing quote in `cap_add` documentation code snippet.

[docs] Fix missing opening quote

---

.changelog/10823.txt
CHANGELOG.md
drivers/docker/driver.go
drivers/shared/hostnames/mount.go
website/content/docs/upgrade/upgrade-specific.mdx

Fixes #10809 
In Nomad 1.1.1 we generate a hosts file based on the Nomad-owned network
namespace, rather than using the default hosts file from the pause
container. This hosts file should be shared between tasks in the same
allocation so that tasks can update the file and have the results propagated
between tasks.

docker: move host path for hosts file mount to alloc dir

---

.changelog/10840.txt
nomad/csi_endpoint.go

CSI: Snapshot volume create should use vol.Secrets

---

website/content/docs/drivers/docker.mdx

Between this page and https://www.nomadproject.io/docs/runtime/interpolation
I realized that the syntax on the Docker page was missing the word `attr`.
Nomad version: 1.1.2

constraint on the Docker driver missing 'attr'

---

.changelog/10855.txt
command/agent/job_endpoint.go

Fixes https://github.com/hashicorp/nomad/issues/10834
Fix a nil pointer in the API struct to `nomad/structs` conversion when a
`volume` or `volume_mount` block is empty.

csi: account for nil volume/mount in API-to-structs conversion

---

api/services.go
jobspec/parse_service.go
jobspec/parse_test.go
jobspec/test-fixtures/tg-service-connect-gateway-terminating.hcl
vendor/github.com/hashicorp/nomad/api/services.go

Parse terminating gateway stanzas. While Nomad supports terminating GWs, its own parse function doesn't actually support them and populate the structs. This attempts to address that.

Parse term gws

---

.changelog/10861.txt
api/jobs.go
api/jobs_test.go
vendor/github.com/hashicorp/nomad/api/jobs.go

api: Added `NewSystemJob` job creation helper function.

---

.changelog/10842.txt
client/allocrunner/alloc_runner_unix_test.go
client/allocrunner/groupservice_hook.go
client/allocrunner/groupservice_hook_test.go
client/allocrunner/taskrunner/service_hook.go
client/allocrunner/taskrunner/service_hook_test.go
client/allocrunner/taskrunner/task_runner_test.go

There are bits of logic in callers of RemoveWorkload on group/task
cleanup hooks which call RemoveWorkload with the "Canary" version
of the workload, in case the alloc is marked as a Canary. This logic
triggers an extra sync with Consul, and also doesn't do the intended
behavior - for which no special casing is necessary anyway. When the
workload is marked for removal, all associated services and checks
will be removed regardless of the Canary status, because the service
and check IDs do not incorporate the canary-ness in the first place.
The only place where canary-ness matters is when updating a workload,
where we need to compute the hash of the services and checks to determine
whether they have been modified, the Canary flag of which is a part of
the hash function.
Fixes #10842

consul: avoid triggering unnecessary sync when removing workload

---

.changelog/10859.txt
command/alloc_logs.go
command/alloc_restart.go
command/alloc_signal.go
website/content/docs/commands/alloc/logs.mdx
website/content/docs/commands/alloc/restart.mdx
website/content/docs/commands/alloc/signal.mdx

Alloc exec only works when task is passed as a flag and not an arg.
Alloc logs currently accepts either, but alloc signal and restart only
accept task as an arg. This adds -task as a flag to the other alloc
commands to make the cli UX consistent. If task is passed as a flag and
an arg, it ignores the arg.

cli: add -task flag to alloc signal, restart

---

.changelog/10865.txt
command/agent/consul/service_client.go
command/agent/consul/service_client_test.go

This PR makes it so the Consul sync logic will ignore operations that
do not specify an action to take (i.e. [de-]register [services|checks]).
Ideally such noops would be discarded at the callsites (i.e. users
of [Create|Update|Remove]Workload], but we can also be defensive
at the commit point.
Also adds 2 trace logging statements which are helpful for diagnosing
sync operations with Consul - when they happen and why.
Fixes #10797

consul: avoid extra sync operations when no action required
